### ISSUE TITLE
Graph batch requests failing

### ISSUE THREAD

**Issue by siljemda** [pnp/pnpjs#1001]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.3.8 ]

Please specify what version(s) of SharePoint you are targeting: [ Online ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Fetch several groups with PnP Graph, using batching. Resolve the batch.execute() promise when all independent requests are finished.

### Observed Behavior
Unstable behaviour: The error happens when one or more of the batched requests fail. This causes the batch.execute() promise to be rejected. None of the calls have explicit dependencies.

In some tenants the batch call will succeed after one or two retries. In another SPO tenant where the relevant webpart is installed, it will always fail.

### Steps to Reproduce
```
        const graphGroups = [];
                let graphGroupsBatch = graph.createBatch();
                for (let id of groupIds) {
                        graph.groups.getById(id).inBatch(graphGroupsBatch).get().then(res => {
                            graphGroups.push(res);
                        }, rej => {
                            console.log(rej);
                        });
                }
        await graphGroupsBatch.execute().then(res => console.log(res), rej => console.log(rej));
```

Please note that the following subsequent call will always succeed if the above succeeded:

```
for (let group of graphGroups) {
        group.owners = await graph.groups.getById(group.id).inBatch(graphGroupsOwnerBatch).owners.get();
}
```

**Comment by semopz** [comment]
I think what you are describing is functioning as intended. The batch task will fail when the batch query or one of the individual batched operations fail. You can do whatever you want with that information.

```typescript
const graphGroups = [];
const graphGroupErrors = [];
const graphGroupsBatch = graph.createBatch();
const graphGroupPromises = groupIds.map(
  groupId => graph.groups.getById(groupId).inBatch(graphGroupsBatch).get()
);

try {
  // Response here is always void. No need to log it to the console. It just tells you when all operations are done
   await graphGroupsBatch.execute();
} catch {
  // Option 1. leave blank/do nothing and inspect the individual responses
  // Option 2. bail out early if you don't care about the succeeded responses
}

// Assuming you did nothing with the batch error if there was one

for (const graphGroupPromise of graphGroupPromises) {
  try {
    graphGroups.push(await graphGroupPromise);
  } catch (graphGroupError) {
    graphGroupErrors.push(graphGroupError);
  }
}

// You can now get the group owners of graphGroups and retry graphGroupErrors
const groupIdsToRetry = graphGroups.map(group => {
  if (groupIds.indexOf(group.id === -1)) {
    return group.id;
  }
});
```

Also, pick async/await or the thenable pattern. Mixing the two only leads to confusion.

**Comment by siljemda** [comment]
@semopz Thanks for your response.

I think part of my problem was that I would only await the batch execution call before posting results from the individual calls. I have previously attempted to await the individual requests, however at the timeI positioned them before the "batch execute" call, which caused the process to hang.

Following your example I was able to retrieve information as expected. Thank you :)
