### ISSUE TITLE
Would be great to be able to set resourceBehaviorOptions for group created using graph.teams.create

### ISSUE THREAD

**Issue by ElinKolloen** [pnp/pnpjs#1003]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [    1.3.8     ]
Please specify what version(s) of SharePoint you are targeting: [   node function app      ]

### Expected / Desired Behavior / Question
I'm using the graph.teams.create method to provision groups with teams. When adding members to the group by code, they get an welcome email with a link to the group in outlook. My members is only interested in the Team, so this is confusing to them. If I could have access to the "resourceBehaviorOptions" of the group when creating the group+team I could disable this email to new users by adding the "WelcomeEmailDisabled".

**Comment by patrick-rodgers** [comment]
Does updating the group not support this requirement? The v1 `teams.create` method is a left over workaround from before you could create a team via the post request. In v2 you use `group.createTeam` as the group already exists in that case. In v2 groups.add supports passing additional props so I think the workflow now would be:

1. create group with settings you want
2. call group.createTeam to create the team for that group

Not sure we need to provide additional access to any properties in this case?

**Comment by patrick-rodgers** [comment]
Going to close this due to lack of feedback - if you are still having issues related to this please open a new issue and ref this one with any additional details you can provide. Thanks!
