### ISSUE TITLE
Break Item level permission - User having only Edit permission at Site level

### ISSUE THREAD

**Issue by Nagarajan1605** [pnp/pnpjs#1005]
Hi koltyakov,

I have a doubt if person has only Edit with contribute permission on the site level. Using this "Edit" permission how user can break the item permission. As of now user who is having "Full Conrol" only can break the item permission. In this scenario user is having only Edit permission but needs to break the item permission.

Could you please assist me.

am Currently using Pnp.js for breaking and setting the item permission. 
Thanks

**Comment by koltyakov** [comment]
A user should have a proper permission level for specific actions within an application. Otherwise, that action should be executed with high privileges as a server-side operation.

**Comment by Nagarajan1605** [comment]
It means using pnp.js User should have only FullControl or Site Admin permission to break the item permission. Without this user cant break the permission is it correct. 

Do we have any other options in PNP.js because that certain group will have only Edit permission only. Serverside operation execution is really gone be tough for my scenario is concern.

**Comment by koltyakov** [comment]
I can't understand what's the relation to PnPjs specifically? It's relevant to any client-side code. The user has no permissions - action/resource is locked. If an action by a user for a resource can't be done in the OOTB UI due to the permission restrictions it can't be done with the APIs.

**Comment by Nagarajan1605** [comment]
Got it. Whatever API we been using it doesnt matter. User should have Full Control or Site Admin permission or relevant permission to break that item permission. 

My question is Do we have anything like runwithelevatedprevileages in PnP.js. 

Though user has low level permission(Edit Permission) in SharePoint. By using some feature in Pnp.js can we break the item permission. This is my question.

I appreciate your extended support and quick reply. 

Thanks

**Comment by koltyakov** [comment]
> Do we have anything like runwithelevatedprevileages in PnP.js.

Sure thing NO. :D One can't expect this in a client-side library, how would it work? When privileges go to a logical level and have to be elevated the logic is pushed to a service layer. In SPO, an Azure Function secured with AAD and service account actions is handy. In On-Prem, just a custom web service. Also, the elevated action can be executed with a workflow, etc.

**Comment by Nagarajan1605** [comment]
Thank you so much for your clear and detailed explanation. I appreciate your wonderful support activity. Thanks again.
