### ISSUE TITLE
Get the modern pages where the "Save for later" option has been selected

### ISSUE THREAD

**Issue by sureshmemmi** [pnp/pnpjs#1008]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [@pnp/sp 2.0.0]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Question
Is there a way to get the **modern** pages where the "Save for later" option has been selected using the pnp js library? Also similarly can we get the view count for each page using pnp js library?

**Comment by semopz** [comment]
It seems you need to get a token and a resource endpoint from `/_api/sphomeservice/context?$expand=Token,Payload`. You then POST a request to the endpoint obtained from the previous from the previous response in the following location `/api/v1/documents/metadata` using the token provided in the auth header.

Would be nice if pnpjs exposed an API to do all that

**Comment by patrick-rodgers** [comment]
We can - though I am not clear on exactly what is desired here? If you can provide more detail on what we need to implement we can see how best to do it.

**Comment by semopz** [comment]
I think this is regarding the Save for Later and View Count widgets at the bottom of Modern UI Pages
https://office365itpros.com/2018/12/30/save-for-later-sharepoint-online
Did I get that right @sureshmemmi?

**Comment by sureshmemmi** [comment]
@semopz thats very useful i can give that a try

@patrick-rodgers i'm trying to create an spfx web part that shows the modern pages that have been marked with "Save for later" option at the bottom of the modern page for the current logged on user. Also in the web part I want to show the pages that have the most views by accessing the Page view count. I've looked through the pnp js library but cant see anything like this available...

**Comment by jhholm** [comment]
You can get approximate information about views for a page via search with managed properties ViewsLifeTime and ViewsLifeTimeUniqueUsers. Not sure if it is the exact value that modern sharepoint is using. Both properties are also sortable, so you are able to create search e.g. for all modern client side pages and get results sorted by the view count.

**Comment by ValerasNarbutas** [comment]
@sureshmemmi save for later pages displayed when calling:
{SPurl}/_layouts/15/sharepoint.aspx?v=saved

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
