### ISSUE TITLE
Property 'EffectiveBasePermissions' does not exist on type 'IListInfo'.

### ISSUE THREAD

**Issue by enti333** [pnp/pnpjs#1011]
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

Hello I am using new PNPJS version 2.0. 
I am converting my old project from old version pnpjs to new...Almost everything is working but I have found one problem in my code...

```
sp.web.lists.getById(this.properties.listGuid).inBatch(batch).select('EffectiveBasePermissions').get()
        .then(({ EffectiveBasePermissions: eBasePerm }) => {
          const { hasPermissions } = sp.web;
          const { ViewListItems, AddListItems, EditListItems } = PermissionKind;
          return {
            viewListItems: hasPermissions(eBasePerm, ViewListItems),
            addListItems: hasPermissions(eBasePerm, AddListItems),
            editListItems: hasPermissions(eBasePerm, EditListItems)
          };
```

The problem is that I get this error 

> Property 'EffectiveBasePermissions' does not exist on type 'IListInfo'.

I am importing pnp 
```
 import { sp, PermissionKind } from "@pnp/sp/presets/all"; 
```

The code was working with old version of pnp but right now not....
What I am doing wrong. 
Thank you very much for help.

**Comment by patrick-rodgers** [comment]
Looks like some properties didn't make it on to the interface, that being one of them. We can get it updated. Thanks for letting us know.
