### ISSUE TITLE
FileNotFoundException when updating file after add

### ISSUE THREAD

**Issue by jpalo** [pnp/pnpjs#1014]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.8]

Please specify what version(s) of SharePoint you are targeting: [Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.* >> Cannot update ATM.

### Expected / Desired Behavior / Question
I try to add file to folder, and update it according to documentation, so after files.add, I get the list item using `FileAddResult.file.getItem()`.

```
let far: FileAddResult = await sp.web.getFolderByServerRelativePath(targetFolderUrl)
    .files.add(targetFolderUrl + targetFileName, blob);                
const item = await far.file.getItem();
await item.update({
    Title: "A Title"
});  
```
targetFolderUrl is `/sites/projectfolders_test/slow21/01%20Handover%20documents/`
targetFileName is `Document.docx`

However, the outcome is error 
```
System.IO.FileNotFoundException`, while HTTP GET is being made in `far.file.getItem()` to `https://XYZ.sharepoint.com/sites/projectfolders_test/_api/web/getFolderByServerRelativePath(decodedUrl='/sites/projectfolders_test/slow41/01%20Handover%20documents/')/files('/sites/projectfolders_test/slow41/01%20Handover%20documents/Document.docx')/listItemAllFields
```

What am I doing wrong? 😊

**Comment by koltyakov** [comment]
The endpoint URL generated is what should it end up after the provided parameters.
`.files.add(targetFolderUrl + targetFileName, blob)` <- this part should be changed to `.files.add(targetFileName, blob)`, where `targetFileName` is file name without the path part `filename.docx` for example.

**Comment by jpalo** [comment]
I know, but please see this: https://github.com/pnp/pnpjs/issues/1013.

**Comment by patrick-rodgers** [comment]
I think this is a dupe of #1013, please see [comment](https://github.com/pnp/pnpjs/issues/1013#issuecomment-575305997) there.

**Comment by patrick-rodgers** [comment]
Any additional details here, otherwise I think this is a dupe of #1013 and will close it and we can follow the thread in the other issue. Thanks!

**Comment by jpalo** [comment]
I don't see how they're duplicates as this one asks why FileAddResult doesn't work as documented, and 1013 asks why server relative path of a document must be passed in as a parameter and not document name as documented.

**Comment by patrick-rodgers** [comment]
Ok, it felt like a duplicate because in both you expressed issues with special chars in paths - which is resolved using the *Path methods as discussed in #1013. If you use the addUsingPath method does the file add result work as you expect?

**Comment by jpalo** [comment]
This was due to having slash at the end of `targetFolderUrl`. Apparently although it fails the `getFolderByServerRelativePath` query, it succeeds the chained `.files.add` query IF you have server relative path to the file instead of just file name.
