### ISSUE TITLE
Looking for good SP examples with React hooks

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#1019]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   latest      ]

Please specify what version(s) of SharePoint you are targeting: [   SPO      ]

Can't figure out how to use pnp js to get list items in a SPFx web part that is not a class because I use Hooks.
the TS linter gives me all kinds of errors.

**Comment by koltyakov** [comment]
With hooks, PnPjs usage is identical to any other promise-based getting data, PnPjs is no different at all. useState for updating the state, useEffect for component did mount and so on. It's not about PnPjs but how to use Hooks in React in general.

**Comment by patrick-rodgers** [comment]
Can you provide your code or the errors you are seeing? This isn't enough for us to really help out here.

**Comment by ncmadhan1989** [comment]
https://www.c-sharpcorner.com/blogs/reacthooks-with-spfx

**Comment by Ofer-Gal** [comment]
@ncmadhan1989 Thank you
I created your web part with new Yo and your code verbatim
It does not render because of this error:
------------------------------------------------------------------------------------
Error - [tsc] src/webparts/spfxReactHooksCrud/components/mySpListCollection.tsx(7,12): error TS2339: Property 'web' does not exist on type 'SPRest'.
---------------------------------------------------------------------
project.json shows "@pnp/sp": "^2.0.0", and all the SPFx pieces are "1.10.0"
Maybe there was a change?
Thank you for the help.

**Comment by ncmadhan1989** [comment]
@Ofer-Gal  Yeah i have used pnp/sp 1.38 version, its my old blog
yeah use 
const web = new Web(siteUrl);

**Comment by Ofer-Gal** [comment]
Thank you

**Comment by Ofer-Gal** [comment]
const web = new Web(siteUrl);  (before the call to web.lists.getByTitle( .... )
Now I get "Only a void function can be called with the 'new' keyword.ts(2350) "
Is this just TypeScript ?
