### ISSUE TITLE
Query functions and properties are ignored by SharePoint with local setup of the SPFetchClient 

### ISSUE THREAD

**Issue by pavsavov** [pnp/pnpjs#1020]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.0.0    ]

Please specify what version(s) of SharePoint you are targeting: [    SharePoint 2019 On-Premises     ]

### Expected / Desired Behavior / Question
**I am using SPFetchClient to connect with SharePoint:**

```       sp.setup({
            sp: {
                fetchClientFactory: function () {
                    return new SPFetchClient(
                        "Url",
                        "ClientId",
                        "Client-secret",
                        SPOAuthEnv.SPO,
                        "realm"
                    );
                },
            },
        });
```

**An example query:**

```
sp.web.lists.getByTitle("City").items.select("Title").get().then(function(items){
       console.log(items);
})
```

### Observed Behavior

The provided example is a simple query operation which should print on console all items associated with the selected List. However everything after  **sp.web**  seems to be ignored in terms of responded result.
If the provided Url to the **SPFetchClient** ends with "**_api/web/lists?**"  I will get all items currently part of the site content(no matter if they are a list or a library). If I try to get a single list as in the example above- "City", I will again get all resources currently in the site content. If I try to get it by ID, same result.
It seems,that every function and/or property after **sp.web** is ignored and will not modify the response.

Using the SP Editor extension for chrome, I was able to retrieve the expected data.

### Steps to Reproduce
Using the configuration as above, use any kind of queries.Everything chained after sp.web will be ignored.

Feel free for follow ups, if necessary!

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
Are you working in nodejs? If so please see our just updated [article on working in node](https://pnp.github.io/pnpjs/nodejs-support/).

If you are working on the clientside you shouldn't use a client id and secret as they are exposed then to all users.

Can you describe a bit more about what you are doing and we'll do our best to help out.

**Comment by pavsavov** [comment]
Greetings Patrick,

Yes, I am working in a NodeJS runtime environment. I was able to check out the updated article. I am experiencing some issues regarding importing the packages. The error I am struggling is `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: --Path to file where i want to importpnp--`
This might not be a "pnp" issue. In the comming day or two,I will return to this task and will post the result.

**Comment by patrick-rodgers** [comment]
Did you read the [updated article on working in node](https://pnp.github.io/pnpjs/nodejs-support/)? It instructs you to [use the commonjs version](https://pnp.github.io/pnpjs/nodejs-support/#install-libraries) of the libraries. Can you give those a try and see if they work for you? For all versions of node in LTS currently es modules don't really work amazingly.

**Comment by pavsavov** [comment]
After using the common-js everything seems to be working exactly as it should be.

You can close this one.

Thanks!

**Comment by patrick-rodgers** [comment]
Thanks!
