### ISSUE TITLE
SharePoint 2016 On Premise - Pnpjs v2 - Field Choices

### ISSUE THREAD

**Issue by sgovaerts** [pnp/pnpjs#1023]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.0 ]

Please specify what version(s) of SharePoint you are targeting: [ 2016 On Premise ]

### Expected / Desired Behavior / Question
When requesting a field (IFieldInfo), I need to access the Choices properties.

### Observed Behavior
When requesting a field the IFieldInfo doesn't have the Choices property present. I had the code working on SPO before the v2 update as a test and when I tried to run it on 2016 On Premise with the 2.0.0 library I noticed it stopped working.

### Steps to Reproduce
`sp.web.lists.getByTitle('List').fields.getByInternalNameOrTitle('ChoiceField').select('Choices').get().then(e => { console.log(e); console.log(e.Choices); });`

While checking the interface I noticed there's no Choices property. https://github.com/pnp/pnpjs/blob/version-2/packages/sp/fields/types.ts 

While checking the response from the call I can see Choices property.
`{
	"odata.metadata": "https://sharepoint.example.com/sites/test/_api/$metadata#SP.ApiData.Fields/@Element&$select=Choices",
	"odata.type": "SP.FieldChoice",
	"odata.id": "https://sharepoint.example.com/sites/test/_api/Web/Lists(guid'97e17dd2-a156-4e14-8deb-4b0a5b43ce1f')/Fields(guid'23550288-91b5-4e7f-81f9-1a92661c4838')",
	"odata.editLink": "Web/Lists(guid'97e17dd2-a156-4e14-8deb-4b0a5b43ce1f')/Fields(guid'23550288-91b5-4e7f-81f9-1a92661c4838')",
	"Choices": ["Herpety", "Derpety"]
}
`

**Comment by koltyakov** [comment]
Hi @sgovaerts,
 
Fields info response type is generic, but you can recast in a case when you know that a specific property is there.

**Comment by sgovaerts** [comment]
@koltyakov Ah was thinking I was doing something wrong or it was missing. But wouldn't it make sense  to have an IChoiceFieldInfo or similar? Right now I just tried extending it and it works but seems weird you'll have to do it for this situation.

Pretty much just this:

```
import { IFieldInfo } from "@pnp/sp/fields";

export interface IChoiceFieldInfo extends IFieldInfo {
    Choices: string[];
}
```
