### ISSUE TITLE
Search bug: TypeError: Cannot read property 'RelevantResults' of undefined

### ISSUE THREAD

**Issue by oppie85** [pnp/pnpjs#1027]
### Category
- [*] Bug

### Version
Please specify what version of the library you are using: [ 2.0.0 ]
Please specify what version(s) of SharePoint you are targeting: [ SPO ]

### Expected / Desired Behavior / Question
I want to execute a search in an otherwise blank webpart

### Observed Behavior
I created a blank new SPFx webpart using the latest Yeoman generator and added 2.0.0. PNP packages. When performing a search using `await sp.search("test")`, I observe the search executing correctly from the Network tab in the browser dev panel, but the SearchResults object contains only undefined properties. When attempting to use the search results the browser console window reports the error: TypeError: Cannot read property 'RelevantResults' of undefined

### Steps to Reproduce
Create a new blank SPFx webpart using the latest Yeoman generator
Add the relevant imports, setup and add a search using `await sp.search("test")`.
Run the webpart in a workbench

**Comment by oppie85** [comment]
Update: Using the beta 2.0.2-5 package solves the problem; it's a bit strange that such a core feature doesn't work in the latest published version though

**Comment by patrick-rodgers** [comment]
There was a [bug reported](https://github.com/pnp/pnpjs/issues/975) that was fixed in 2.0.1 which we unpublished due to the module issues. That fix will be included in 2.0.2 when it goes out later today (Jan, 23). Going to close this as it is already fixed.
