### ISSUE TITLE
Version on docs displaying wrong

### ISSUE THREAD

**Issue by JakeStanger** [pnp/pnpjs#1030]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Not a major issue by any means, but I have noticed on <https://pnp.github.io/pnpjs/packages> the templating does not seem to work as expected and it reads `The latest published version is ****.`.

**Comment by patrick-rodgers** [comment]
Ok, thanks for letting us know.
