### ISSUE TITLE
Renderlistdataastream - Lookup additional field

### ISSUE THREAD

**Issue by sgovaerts** [pnp/pnpjs#1032]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0      ]

Please specify what version(s) of SharePoint you are targeting: [  2016 On Premise       ]

### Expected / Desired Behavior / Question
I have a site collection with a list with data "test" (Id, Title, Extra). Then I have a subsite that uses the list from the site collection and that's why I'm using Renderlistdataasstream. 
When using Renderlistdataasstream to request the lookup, I only get lookupId, lookupValue and isSecretFieldValue. Is there a possibility to get additional columns, in this case "Extra"?

```
sp.web.lists.getByTitle('SubsiteList').renderListDataAsStream({
      ViewXml: '
        <View>
          <ViewFields>
              <FieldRef Name='Id' />
              <FieldRef Name='Title' />
              <FieldRef Name='Test' />
          </ViewFields>
        </View>
     '
    }).then(e => {
      console.log(e)
   });

```

What I get back for the site collection object.

```
lookupId: 1
lookupValue: "test"
isSecretFieldValue: false`
```

**Comment by sgovaerts** [comment]
Hmm I was looking again at the documentation and first thought I needed the Field parameter but no luck. I still just get the lookupId, lookupValue & isSecretFieldValue.  [renderlistdataasstream uri parameters](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#renderlistdataasstream-uri-parameters)

```
sp.web.lists.getByTitle('SubsiteList').renderListDataAsStream({
      ViewXml: "<View><RowLimit>5</RowLimit></View>"
    }, null, new Map([["Field", "Test/Extra"]])).then(e => {
      console.log(e);
    });
```

**Comment by sgovaerts** [comment]
I got a little further, when I go into my subsite list and in the lookup field I choose to also show the additional column 'Extra' then I can see it in the response.

Example:

I now add the Test_x003a_Extra field in the ViewFields.

sp.web.lists.getByTitle('SubsiteList').renderListDataAsStream({
      ViewXml: '
        <View>
          <ViewFields>
              <FieldRef Name='Id' />
              <FieldRef Name='Title' />
              <FieldRef Name='Test' />
              <FieldRef Name='Test_x003a_Extra' />
          </ViewFields>
        </View>
     '
    }).then(e => {
      console.log(e)
   });

When I check the response I can see the new field returned.
```
"Test": [{"lookupId":1,"lookupValue":"test1","isSecretFieldValue":false},{"lookupId":2,"lookupValue":"test2","isSecretFieldValue":false},{"lookupId":4,"lookupValue":"test3","isSecretFieldValue":false},{"lookupId":3,"lookupValue":"test4","isSecretFieldValue":false}],
"Test_x003a_Extra": [{"lookupId":1,"lookupValue":"extra1","isSecretFieldValue":false},{"lookupId":2,"lookupValue":"extra2","isSecretFieldValue":false},{"lookupId":4,"lookupValue":"extra3","isSecretFieldValue":false},{"lookupId":3,"lookupValue":"extra0","isSecretFieldValue":false}],

```

**Comment by patrick-rodgers** [comment]
Nice! - does this mean you've got this sorted or do you still have a question? Looks like you have it figured out.

**Comment by koltyakov** [comment]
@sgovaerts, with renderListData/renderListDataAsStream you can use those CAML features, as you mentioned, or others e.g. projected fields and joins for that purpose. PnPjs doesn't limit this part or wraps CAML overengeneerly as it has many nuances and it would be too opinionated for us, so ViewXml is bypassed with all its complexities and capabilities.

**Comment by sgovaerts** [comment]
I've ended up moving some lists to the subsite instead of getting it from the main site collection. The renderlistdataasstream and working like that was too annoying just to get it working as opposed to the lists of the same site.
