### ISSUE TITLE
Unable to use config-store in IE 11

### ISSUE THREAD

**Issue by wizneeraj** [pnp/pnpjs#1036]
#121 # Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  @pnp/config-store": "^2.0.0"       ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online      ]

### Expected / Desired Behavior / Question
config-store should work in IE 11

### Observed Behavior
Getting the below error when utilizing Config-Store
Unhandled promise rejection ReferenceError: 'Proxy' is undefined

### Steps to Reproduce
using the below code to initialize and load the config-store which is failing in IE-11
```
const web = Web(siteUrl);        
const provider = new SPListConfigurationProvider(web, "confgurations");
const wrappedProvider = provider.asCaching();   
this._settings = new Settings();
const wrappedProvider = provider.asCaching();
await settings.load(wrappedProvider);
```

**Comment by patrick-rodgers** [comment]
Have you [read the article on working in IE11](https://pnp.github.io/pnpjs/concepts/ie11-mode/)?

**Comment by patrick-rodgers** [comment]
Going to close this due to lack of response. Using ie11 mode should address this as we bypass Proxy. If this remains an issue please open a new issue with additional details and ref this one so we can revisit.
