### ISSUE TITLE
GraphApi Set Permission on Item

### ISSUE THREAD

**Issue by enti333** [pnp/pnpjs#1038]
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

Hello. I just start to test GraphApi with pnpjs and everything is working fine I can simply add Item, Update Item, Delete Item. But I didn't find how to set permission via GraphApi on SharePoint Online List Item. I have also looked at the documentation but find only information about setting the permission on Files in SharePoint, not on Items. GraphApi doesn't support such an important function? Thank you.

**Comment by patrick-rodgers** [comment]
I do not believe the [graph currently supports](https://docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-1.0) setting the permissions for items. You can express the need in the [user voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests).

**Comment by patrick-rodgers** [comment]
Going to close this question as it is answered. Please open a new issue and ref this one if you have further questions related to this topic. Thanks!
