### ISSUE TITLE
Sharepoint Online - Status bar

### ISSUE THREAD

**Issue by Cazeu64** [pnp/pnpjs#104]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ Any ]

### Question
I would like to be able to notify users via the native status bar like the following picture does :
![image](https://user-images.githubusercontent.com/26091376/40006253-325a14b0-579a-11e8-8693-d0af138628c5.png)
(Blue bar, where it is written "Publié").

If there is no way using pnpjs, do you know any native option in order to do that kind of stuff ?

Thanks in advance :).

**Comment by Cazeu64** [comment]
@KEMiCZA I'll probably use Extensions, but I wanted to be sure there is no other way to do it. A Pnp utility tool for example.

Thanks for your fast answer ! :)

**Comment by koltyakov** [comment]
@Cazeu64,

PnPjs is everything about REST API. It doesn't include any UI components or utilities by design, just solve different tasks.

SPFx's Application Customizer can be used for this, with custom styles of Office UI Fabric components.
