### ISSUE TITLE
sp.web.getFolderById and sp.web.getFileById gone in v2

### ISSUE THREAD

**Issue by jpalo** [pnp/pnpjs#1040]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.2]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
Is there a reason `sp.web.getFolderById` and `sp.web.getFileById` were removed from v2 as they were only just added 10 months ago (https://github.com/pnp/pnpjs/pull/562)? Blocking migration from 1.3.X in my project.

**Comment by patrick-rodgers** [comment]
No reason, they got added after we forked for v2 and we missed bringing them over to the v2 branch. We can get them added.
