### ISSUE TITLE
Import graph/contacts, Type expected

### ISSUE THREAD

**Issue by robiharid** [pnp/pnpjs#1041]
I am following the sample code:
```

import { graph } from "@pnp/graph";
import "@pnp/graph/users";
import "@pnp/graph/contacts";

const contacts = await graph.me.contacts();
```
This is my error:
`Error - [tsc] node_modules/@pnp/graph/contacts/types.d.ts(12,50): error TS1110: Type expected.`

This is the repo I forked: https://social.technet.microsoft.com/wiki/contents/articles/52249.sharepoint-online-live-persona-card-in-custom-webpart.aspx

I want to call graph API to retrieve top 3 people (https://docs.microsoft.com/en-us/graph/api/user-list-people?view=graph-rest-1.0&tabs=http)
would this be `await graph.me.people()` in pnp-js?

**Comment by patrick-rodgers** [comment]
For the tsc error I think you can merge the following into the tsconfig.json.

```JSON
{
    "compilerOptions": {
        "skipLibCheck": true
    }
}
```

When you say "top 3 people" - based on what? How are they ordered and where do you expect to get them? From the current users contacts? or? If you can provide a little more detail on what you mean to do we will do our best to assist. Thanks!

**Comment by robiharid** [comment]
> For the tsc error I think you can merge the following into the tsconfig.json.
> 
> ```json
> {
>     "compilerOptions": {
>         "skipLibCheck": true
>     }
> }
> ```
> 
> When you say "top 3 people" - based on what? How are they ordered and where do you expect to get them? From the current users contacts? or? If you can provide a little more detail on what you mean to do we will do our best to assist. Thanks!

Hey thanks for chiming in Patrick!

I seem to have already got the skipLibCheck set to true in my tsconfig.json

Top 3 people: under 'List people' it says it will retrieve list of people most relevant to the user (we want to do Office intelligence stuff) but basically I ask because pnp has graph/contacts but not graph/people (https://pnp.github.io/pnpjs/graph/contacts/). Does this mean I have to manually do an sp web query?

But it will be easier if I can fix the type error.

**Comment by patrick-rodgers** [comment]
It sounds like you are asking for us to add the people property to the user object? That's easy enough.

I can't recreate the type error so not sure on that. Can you share a repo that demos the error?

**Comment by robiharid** [comment]
> It sounds like you are asking for us to add the people property to the user object? That's easy enough.
> 
> I can't recreate the type error so not sure on that. Can you share a repo that demos the error?

Thanks for the PRs, would like to contribute as well 

https://github.com/robiharid/SPFxPersonaCard

This should show you the error when you run `gulp serve`
