### ISSUE TITLE
Setting banner image fails when setting it on the ClientSidePage

### ISSUE THREAD

**Issue by MagtheRag** [pnp/pnpjs#1049]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.0.2     ]

Please specify what version(s) of SharePoint you are targeting: [    SharePoint Online     ]

### Expected / Desired Behavior / Question
When using addBannerImage the code fails. If I remove the addBannerImage() then the page gets created and everything works as it should. The error message is what follows: 
![image](https://user-images.githubusercontent.com/7849138/73734285-b09edd80-473d-11ea-9a61-95331c45b59f.png)

```
Uncaught (in promise) Error: Error making HttpClient request in queryable [400] Bad Request ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"Invalid request."}}}
    at new HttpRequestError (parsers.js?c5b5:130)
    at Function.eval (parsers.js?c5b5:145)
    at step (tslib.es6.js?b770:99)
    at Object.eval [as next] (tslib.es6.js?b770:80)
    at fulfilled (tslib.es6.js?b770:70)
```

### Observed Behavior
I am not 100% sure but it seems like, when stepping through the code, that it fails somewhere when it tries to add the image to the layoutparts on the page. 

### Steps to Reproduce
First I uploaded a file by code in a document library in a sub folder within the same site and passed in the url to the function. 

```TypeScript
if (bannerImageFile) {
        var bannerUrl = bannerImageFile.data.ServerRelativeUrl;
        page.setBannerImage(bannerUrl);
 }
```
Then I hard coded with an image from the internet. 

```TypeScript
page.setBannerImage( 'https://cdn140.picsart.com/306147367001201.jpg?type=webp&to=min&r=1024');
```
It failed as well.

**Comment by patrick-rodgers** [comment]
Ok, thanks we will have a look and see if we can figure out what might be happening. The API we use isn't "public" as such and subject to breaking changes - perhaps something happened with how this works.

**Comment by patrick-rodgers** [comment]
It looks like the API now requires a server relative URL of the image - though I am not sure why your first snippet didn't work. I tested using the below successfully:

```TypeScript
const page = await sp.web.addClientsidePage("BannerTest6", "My Title");

const file = await sp.web.getFileByServerRelativeUrl("/sites/dev/Shared Documents/file.png").select("ServerRelativeUrl")();

page.setBannerImage(file.ServerRelativeUrl);

await page.save();
```

This code then failed, showing that the image needs to be in the same site collection:

```TypeScript
// this web is /sites/dev
const page = await sp.web.addClientsidePage("BannerTest6", "My Title");

page.setBannerImage("/Documents/file.png");

await page.save();
```

We need to update the docs to indicate the image file needs to exist in the same site collection as the page. Does this match what you are seeing?

**Comment by MagtheRag** [comment]
Thank you for your response. 
I tried to hard code a relative url to an image that I know is at the root of the document library. 
like this:
page.setBannerImage('/Shared Documents/analysis.jpg');

Sadly I still have the same problem though. 
The site I am working with has /teams/sitename but that should not be a problem should it?
//M

**Comment by MagtheRag** [comment]
And I have an update:
I did use promise instead of using the await key word as all other functions are wrapped inside of a promise chain. Something like this:

``` javascript
const w = Web('https://server.sharepoint.com/teams/sitename');

return w().then(() => {
    // first add the page
    return CreateClientsidePage(w, ensurePageName(pageData.Title.value), pageData.Title.value);
});

```
Then the setBannerImage failed all the time no matter what URL I passed. 
But when transforming it into the await pattern

```javascript
  const page = await sp.web.addClientsidePage(
    ensurePageName(pageData.Title.value),
    pageData.Title.value,
  );

  page.setBannerImage('/teams/sitename/Shared Documents/analysis.jpg');

  await page.save();
```

Though I needed to have the whole relative url '/teams/sitename/Shared Documents/analysis.jpg' to make it work. Otherwise the setBannerImage would fail and complain about server relative url must be in use

**Comment by patrick-rodgers** [comment]
Yes, you need to use the ServerRelativeUrl to set the banner image. I have updated the docs to reflect this. Sounds like we are good to close this now?

**Comment by MagtheRag** [comment]
Yes closed it is !! Thanx

**Comment by patrick-rodgers** [comment]
Thanks!
