### ISSUE TITLE
install packages from npm. UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by aslanovsergey** [pnp/pnpjs#105]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.0.5]

### Expected / Desired Behavior / Question
To get 1.0.5 version of packages running command 
`npm install @pnp/logging @pnp/common @pnp/odata @pnp/sp @pnp/graph --save`

### Observed Behavior
Only @pnp/graph comes 1.0.5 version others are 1.0.4

```
npm WARN saveError Problems were encountered
npm WARN saveError Please correct and try again.
npm WARN saveError peer invalid: @pnp/common@1.0.5, required by @pnp/graph@1.0.5
npm WARN saveError peer invalid: @pnp/logging@1.0.5, required by @pnp/graph@1.0.5
npm WARN saveError peer invalid: @pnp/odata@1.0.5, required by @pnp/graph@1.0.5

+-- UNMET PEER DEPENDENCY @pnp/common@1.0.4
+-- @pnp/graph@1.0.5
| +-- @microsoft/microsoft-graph-types@1.3.0
| `-- tslib@1.9.0
+-- UNMET PEER DEPENDENCY @pnp/logging@1.0.4
+-- UNMET PEER DEPENDENCY @pnp/odata@1.0.4
`-- @pnp/sp@1.0.4
```

**Comment by patrick-rodgers** [comment]
All of the libraries have a peer dependency on the same version as they are. So if you are trying to use graph 1.0.5 you would need the same version of the other libraries. I just gave it a try in a clean directory and things look good. Is it possible you have some older versions of the libraries installed?

```
C:\test
λ npm install @pnp/logging @pnp/common @pnp/odata @pnp/sp @pnp/graph --save
npm WARN saveError ENOENT: no such file or directory, open 'C:\test\package.json'
C:\test
+-- @pnp/common@1.0.5
| +-- @types/adal-angular@1.0.0
| +-- adal-angular@1.0.17
| `-- tslib@1.9.0
+-- @pnp/graph@1.0.5
| `-- @microsoft/microsoft-graph-types@1.3.0
+-- @pnp/logging@1.0.5
+-- @pnp/odata@1.0.5
`-- @pnp/sp@1.0.5
```

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please do _reopen_ if you need additional assistance. Thanks!
