### ISSUE TITLE
Changelog link broken in transition guide

### ISSUE THREAD

**Issue by mplwork** [pnp/pnpjs#1050]
The link [https://pnp.github.io/pnpjs/transition-guide/#changelog](https://pnp.github.io/pnpjs/transition-guide/#changelog) is broken. Points to
[https://github.com/pnp/pnpjs/blob/dev-v2/CHANGELOG.md](https://github.com/pnp/pnpjs/blob/dev-v2/CHANGELOG.md)

### Category
- [ ] Enhancement
-  Bug
- [ ] Question
- [ ] Documentation gap/issue

### Expected / Desired Behavior / Question
Display the transition guide

### Observed Behavior
Error page 404 displayed.

### Steps to Reproduce
Go to [https://pnp.github.io/pnpjs/transition-guide/#changelog](https://pnp.github.io/pnpjs/transition-guide/#changelog) and click on CHANGELOG

**Comment by patrick-rodgers** [comment]
Thanks, we'll get that fixed.
