### ISSUE TITLE
The returned key of the web's properties is different from relative property name in SharePoint Designer

### ISSUE THREAD

**Issue by YanYi2017** [pnp/pnpjs#1054]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.0.0    ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online   ]

### Expected / Desired Behavior / Question
I'm getting the root web's all properties collection by `sp.site.rootWeb.allProperties()`. The response 
contains the following:
![image](https://user-images.githubusercontent.com/34807478/73825419-e4116300-4836-11ea-9c96-64f0f1ba8ba4.png)

The highlighted key is different from the relative property name in SharePoint Designer, which like:
![image](https://user-images.githubusercontent.com/34807478/73826137-3901a900-4838-11ea-888b-9fe68fc4b6d6.png)

Are there some ways to make the key of response same as the relative property name in SharePoint Designer?

**Comment by koltyakov** [comment]
That's how REST API returns OData Entity names with some special characters like underscores. We consciously do not transform properties names, that would be too opinionated and confusing sometimes. Especially if you'd expect the same property being written back (regarding property bags they obviously read-only in REST but anyways).

**Comment by YanYi2017** [comment]
@koltyakov Thanks. I thought it's internal name, so I was confused with it. Now, I know how to deal with it. Thanks again.
