### ISSUE TITLE
Wanting to add withCredentials: true to sp.setup

### ISSUE THREAD

**Issue by robb1ssell** [pnp/pnpjs#1057]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [X ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [@pnp/sp 1.3.8  ]

Please specify what version(s) of SharePoint you are targeting: [ 2013 ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
This issue was mentioned in #502 when trying to add options to the API call when using sp.setup. I am able to successfully connect to sharepoint using the following:
```
Axios({
    method: 'GET',
    withCredentials: true,
    headers: {
      'Accept': "application/json;odata=verbose",
    },
    url: process.env.REACT_APP_SP_BASEURL + "_api/web/SiteUserInfoList/items?$filter=Title eq '"+name+"'"
  })
```

I have tried the credentials: 'include' and cors mode options with no success. I saw no mention of the `withCredentials: true` line, but I believe this to be the missing piece since this example is working with Axios. In #502, they suggested just using regular fetch calls, but I have a substantial amount of code invested in sp.web calls so I'd like to see if we can figure out support for this option.

### Observed Behavior
Accept header is set in the request, but no other options add the proper headers.

### Steps to Reproduce
```
import { sp } from "@pnp/sp";

sp.setup({
  sp: {
    headers: {
      Accept: "application/json;odata=verbose",
    },
    mode: 'cors',
    credentials: 'include',
    baseUrl: process.env.REACT_APP_SP_BASEURL
  },
});
```
Does not set the correct headers. I have tried adding `withCredentials: true` to the set up as well to no avail. I'm assuming there is not support for it? This is the ticket to it working, at least in my use case.

**Comment by patrick-rodgers** [comment]
I am confused - you think we have a bug in that we don't work the same way as another library?

You can set the things you want to set, we implemented the configure method within the chain because these options often need to be set on a per-request basis so it fit there better for our model. IF you want all requests to be configured you can use the pattern below, which fits well into the [project preset model](https://github.com/pnp/pnpjs/tree/version-2/samples/project-preset).

```TypeScript
import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

// if you want all calls to share the same thing you can configure the root sp object to a new
// const and use that as the root of your fluent chains
const spConfigured = sp.configure({
  credentials: "include",
  mode: "cors",
});

// this request and all requests from spConfigured will include those settings
const w = await spConfigured.web.lists.getByTitle("OrderByList").items();
```

[This is in the docs here](https://pnp.github.io/pnpjs/odata/queryable/#configure).

**Comment by robb1ssell** [comment]
Thanks for a quick reply.

Apologies.. I was unsure whether the behavior was intended to be available based on the information given in the other issue I linked - and that remained unresolved on that thread. I did not think to look in that section of the documentation, as the problem did not appear to me as relevant to the odata package.

I will see if I can get the approach you suggested to work.

**Comment by patrick-rodgers** [comment]
Closing this as it appears resolved. Should you need additional help please open a new issue and ref this one. Thanks!
