### ISSUE TITLE
@pnp/sp/utilities

### ISSUE THREAD

**Issue by dhheeraj** [pnp/pnpjs#1059]
using sp.utility.sendEmail from @pnp/sp/utilities. Forming the proper format for Emailprops and getting issue in below format -

odata.es5.js:93 Uncaught (in promise) Error: Error making HttpClient request in queryable [400] Bad Request ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"A collection was found without the 'results' property. In OData, each collection must be represented as a JSON object with a property 'results'."}}}
    at new HttpRequestError (odata.es5.js:93)
    at odata.es5.js:102

**Comment by patrick-rodgers** [comment]
You didn't provide any of the information in the issue template - can you please include that so we can have a chance to understand this issue?

**Comment by patrick-rodgers** [comment]
Closing this - if you are still having this issue please open a new issue and include all of the information requested in the template. Thanks!
