### ISSUE TITLE
Error: Error making HttpClient request in queryable [403] Forbidden ::> {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}

### ISSUE THREAD

**Issue by pmeripe** [pnp/pnpjs#1062]
Hello, 
I am using below code to get subsite lists/libraries. As an admin I can get all site contents, but user with full control or contribute access getting 403 forbidden error.
**const web = Web("https://abc.sharepoint.com/sites/abc/xyz/");
            web.lists.get().then((webLists) =>
            {
               console.log(weblists);
           }**

**Comment by patrick-rodgers** [comment]
You didn't complete the template with the required information or provide any details. Security errors are not bugs in the library, your permissions aren't what you think if you are getting a 403 error.

**Comment by pmeripe** [comment]
Hello Patrick,
Appreciated your response.

How can I use PnPJs library to get subsite site contents for contribute level user?
Please suggest.

Thanks

**Comment by pmeripe** [comment]
I resolved my problem. Agreed that this is non-library issue.
Thank you.

**Comment by wasiullah-mh** [comment]
Hi @pmeripe 
Can you tell me how you solved this problem

**Comment by pmeripe** [comment]
@wasiullah-mh,

I ended up using jQuery to get the site contents for selected web.
