### ISSUE TITLE
SP.Web.Webs.Add() generates incorrect url conatains some string with app

### ISSUE THREAD

**Issue by aadilwani** [pnp/pnpjs#1064]
### Category

- [ ] Bug

### Version

Please specify what version of the library you are using: [  PNPJS v2       ]

Please specify what version(s) of SharePoint you are targeting: [   Sharepoint   Online   ]

I am using the below lines of code 

Creating Site Collection : **Working fine**
sp.site.createModernTeamSite(newSiteName, newSiteName, true, selectedLanguage, newSiteDescription)

However when I  invoke the below method i see something strange in the Url in the PostRequest

 sp.web.webs.add(newWorkspaceName, newWorkspaceName, newWorkspaceDescription, "STS#3", selectedWorkspaceLanguage, false)

**POST REQUEST**
https://helloabc-**app5f61aed9a87141cdab35c4134d4d3717**.sharepoint.com/sites/SiteCollSPTest/_api/web/webs/add

This string gets appended in the POST request url .

It should be something like 

https://helloabc.sharepoint.com/sites/SiteCollSPTest/_api/web/webs/add

**Comment by patrick-rodgers** [comment]
Can you share a repro we can use to see what is happening? The only way what you describe could be happening is if you are somehow running in an add-in and don't realize it / aren't accounting for that.

**Comment by aadilwani** [comment]
[src.zip](https://github.com/pnp/pnpjs/files/4196512/src.zip)

Actually i am testing it on a web part. I have a simple web part with 2 Textboxes and a Button. On Button click i am creating a Subsite with the below code .

sp.web.webs.add(newWorkspaceName, newWorkspaceName, newWorkspaceDescription, "STS#3", selectedWorkspaceLanguage, false).then((w: IWebAddResult) => {
         w.web.select("Title", "Url").get().then((w1: any) => {....}

However, I noticed the post request is wong some additional string [mostly like the package id] is getting appended to it. 


![image](https://user-images.githubusercontent.com/17984143/74402158-72926f80-4e49-11ea-9db8-2c5680c9ae26.png)

**Comment by koltyakov** [comment]
Is it [isolated webpart](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/isolated-web-parts)?

Are you establishing [SPFx context](https://pnp.github.io/pnpjs/getting-started/#establish-context)? 
Did you try providing site URL explicitly (`const web = Web('https://aadilwani.sharepoint.com/sites/SiteCollSPTest')`)?

**Comment by aadilwani** [comment]
Yes, an Isolated Webpart. Yes setting up the context 

 sp.setup(this.context);

I am not providing the Url explicitly, in my previous reply i have attached the code as well SRC.ZIP
