### ISSUE TITLE
getitemsbycamlQuery return Publishing image field

### ISSUE THREAD

**Issue by vinaunder** [pnp/pnpjs#1070]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
I have a field in the list called "Icon" which is a field of type **Publishing Image,** when I query the list
this field is the only one that does not return me, is there any way to return this information?
I'm using the method
`sp.web.lists.getbytitle (listname) .getitemsbycamlQuery ()`

**Comment by koltyakov** [comment]
Hi @vinaunder,

Not sure that this field type is supported in OData methods.
But you can try using renderListData/renderListDataAsStream methods for this.

**Comment by vinaunder** [comment]
> Hi @vinaunder,
> 
> Not sure that this field type is supported in OData methods.
> But you can try using renderListData/renderListDataAsStream methods for this.

Hi @koltyakov  don´t work for me this solution =(

**Comment by patrick-rodgers** [comment]
Unsure if [this section in the docs](https://pnp.github.io/pnpjs/sp/items/#retrieving-publishingpageimage) will help you - publishing fields work differently and aren't supported for all the operations.

**Comment by vinaunder** [comment]
> Unsure if [this section in the docs](https://pnp.github.io/pnpjs/sp/items/#retrieving-publishingpageimage) will help you - publishing fields work differently and aren't supported for all the operations.

Hi @patrick-rodgers, i shared part of my code, this FieldValuesAsText/MetaInfo Work for all metainfos?
![image](https://user-images.githubusercontent.com/8633332/74945866-574ad580-53f0-11ea-902a-551542c6e5d1.png)
Result..
![image](https://user-images.githubusercontent.com/8633332/74946031-98db8080-53f0-11ea-95e4-61ae53e2c917.png)

List
![image](https://user-images.githubusercontent.com/8633332/74946234-e526c080-53f0-11ea-9de5-1fd05f644a6d.png)

**Comment by vinaunder** [comment]
For Pages its Works, but for Lists not return metaInfos and dont work

**Comment by koltyakov** [comment]
That's how API works, we can't amend such things in the client, obviously. The one thing I can't understand is why renderListDataAsStream doesn't work for you.

**Comment by vinaunder** [comment]
> renderListDataAsStream

@koltyakov Look my code.
`const w = Web(siteurl);
 const list = w.getList(listName);
const rowLimit = `<RowLimit>${quantidade}</RowLimit>`;
const camlQuery = `<Query><Where><And><Eq><FieldRef Name='SANDestaqueHome' /><Value Type='Boolean'>1</Value></Eq><Eq><FieldRef Name='SANAtivo' /><Value Type='Boolean'>1</Value></Eq></And></Where><OrderBy><FieldRef Name='SANOrdem1' Ascending='True' /></OrderBy></Query>`;
const renderListDataParams: IRenderListDataParameters = {
        ViewXml: `<View>${camlQuery}${rowLimit}</View>`
      };
      const r = await list.renderListDataAsStream(renderListDataParams);

      console.log("row", r.Row);
`

Return this error:
![image](https://user-images.githubusercontent.com/8633332/75039759-3eeebf80-54b1-11ea-9029-095b5b9ec901.png)

My Imports
![image](https://user-images.githubusercontent.com/8633332/75039824-5ded5180-54b1-11ea-9738-77b6c93c94b6.png)

**Comment by koltyakov** [comment]
\* Got to edit the sample formatting as nothing could be read.

What imports chaos! That doesn't look correct at all for me. I'd suggest `import { sp } from "@pnp/sp/presets/all";` for simplicity and optimize partials after the main app logic is done and clear it works and it comes to bundle optimization.

Side comment. `web.getList()` receives list relative URL but not the name.

`r.getList` in TypeError but not `w.getList` - doesn't it mean the output is from a different code as in sample?

As it also a topic switch and the original one is resolved with an answer, I'm closing this one. Feel free to open a separate one if something is really wrong with the imports sequencing and mixing partials and specific after each other.
