### ISSUE TITLE
Support of Tenant (Admin) REST API methods

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/pnpjs#1071]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 2.0.3

Please specify what version(s) of SharePoint you are targeting: Online

### Expected / Desired Behavior / Question

The idea is to propose tenant scoped functions that are available in the REST API like:
- delete a site
- restore a deleted site
- getting site properties without creating a Web instance
- check tenant licences
- ...

It could be requested like this : ```sp.tenant.getSitePropertiesByUrl('https://contoso.sharepoint.com/sites/hr', true)```

The library will be able to setup an instance to the Admin Site in the background if not exists, so that each method called will refer to the Admin Site instance.

Possible ? Relevant ?

**Comment by patrick-rodgers** [comment]
Def possible - been a bit since I checked what is actually exposed via REST from that API. I think re-checking that would be a first step to see what we could effectively surface.

**Comment by michaelmaillot** [comment]
Great, I'll have a look and let you know if you want.

**Comment by patrick-rodgers** [comment]
Thanks @michaelmaillot - I will be on leave so please don't be discouraged if I don't respond immediately. Excited to see what we can support here.

**Comment by mplwork** [comment]
Wow, that is exactly what I need right now (I think).  I want to set the external sharing property of a site.

In Powershell we do it like 

`Set-PnPTenantSite -Url $sharepointurl -sharing "ExistingExternalUserSharingOnly"`

 Is there any other pnpjs or other way to achieve this?

**Comment by michaelmaillot** [comment]
Hi @mplwork !

I know there's an endpoint for this : _https://contoso-admin.sharepoint.com/_api/Microsoft.Online.SharePoint.TenantAdministration.SiteProperties("https://contoso.sharepoint.com/sites/blog")/Update_

Reference [here](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/dn174862(v=office.15)).

You can also achieve this through CSOM (example [here](https://github.com/SharePoint/PnP/tree/master/Samples/Core.ExternalSharing#controlling-tenant-and-site-collection-setting-with-csom)).

But I didn't try it.

**Comment by mplwork** [comment]
> 
> 
> Hi @mplwork !
> 
> I know there's an endpoint for this : _[https://contoso-admin.sharepoint.com/_api/Microsoft.Online.SharePoint.TenantAdministration.SiteProperties("https://contoso.sharepoint.com/sites/blog")/Update](https://contoso-admin.sharepoint.com/_api/Microsoft.Online.SharePoint.TenantAdministration.SiteProperties(%22https://contoso.sharepoint.com/sites/blog%22)/Update)_
> 
> Reference [here](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/dn174862(v=office.15)).

Thanks very much for the link but I can't get it to work. What is the actual URL?  

I tried 

[https://mytenant-admin.sharepoint.com/_api/Microsoft.Online.SharePoint.TenantAdministration.SiteProperties("https://mytenant.sharepoint.com/sites/og_0002")/Update](https://mytenant-admin.sharepoint.com/_api/Microsoft.Online.SharePoint.TenantAdministration.SiteProperties("https://mytenant.sharepoint.com/sites/og_0002")/Update
)

 but whatever I try (with `/Update` or without) I get a 

`Microsoft.SharePoint.Client.InvalidClientQueryException`. 

`"The expression "Microsoft.Online.SharePoint.TenantAdministration.SiteProperties("https:/mytenant.sharepoint.com/sites/og_0002")/Update" is not valid."`

My token is apparently working as I first tried without a scope for `mytenant-admin.sharepoint.com` and got a corresponding error.

**Comment by michaelmaillot** [comment]
As working on the CLI for M365, I tried to use some Tenant REST API methods (such as restoring / removing deleted sites), but as it returns SpoOperation objects that doesn't give any identifier to check the status of the execution, I eventually had to use CSOM (eg `client.svc`) instead.

So to answer @mplwork, the only thing I noticed is that you have to replace double quotes by simple quotes in the URL of the query. Instead of the error you described (which says your query is invalid), you'll have an `Microsoft.Online.SharePoint.Common.SpoException` 500 error message : _The site Uri provided is null._ Don't know what to do with that anyway and what's missing since it's not documented.

My suggestion would be to use CSOM approach and to give you another implementation, I suggest you to have a look at what has been coded for the [`spo site classic set`](https://pnp.github.io/cli-microsoft365/cmd/spo/site/site-classic-set/) command. The source code for that is [here](https://github.com/pnp/cli-microsoft365/blob/master/src/m365/spo/commands/site/site-classic-set.ts).

So, to init the implementation in PnP JS, a first approach would be to reuse the commands used in the CLI, based on CSOM, that we are sure are working. Here's a list:

* Get / Set properties on a specific site from the Tenant instance (Site Properties like LockState, AllowEditing, Sharing Capability,..)
* Get / Set properties on the Tenant instance (like OneDriveStorageQuota, UserVoiceForFeedbackEnabled,...)
* Get list of deleted sites
* Restore a deleted site
* Remove a deleted site
* Get Tenant Id
* Get Tenant App Catalog

What do you think about that?

**Comment by patrick-rodgers** [comment]
I would prefer strongly we not add CSOM calls to PnPjs.

**Comment by michaelmaillot** [comment]
Ok, so if we keep in mind the approach by REST API, there a many operations that are available. Below a list of endpoints with which we could start:

* `_api/Microsoft.Online.SharePoint.TenantManagement.Office365Tenant`
    * Properties like "AllowGuestUserShareToUsersNotInSiteCollection", "ExternalServicesEnabled", "GuestSharingGroupAllowList"
    * Methods like "GetExternalUsers", "GetAllTenantThemes"
* `_api/Microsoft.Online.SharePoint.TenantAdministration.SiteProperties`
    * Get method on root endpoint
* `_api/Microsoft.Online.SharePoint.TenantAdministration.Tenant`
    * Similar properties as `_api/Microsoft.Online.SharePoint.TenantManagement.Office365Tenant`
    * Methods like "RemoveDeletedSites", "RestoreDeletedSites"

The complexity is about making some queries to work, as they're not documented and when executing them, I got error responses without details like the one mentioned in my previous comment.

Does anyone have detailed info about those APIs or how to query them correctly ?

**Comment by patrick-rodgers** [comment]
@michaelmaillot - I don't have details off the top of my head but when I have some time I can investigate, though unsure how soon that will be. Welcome other's input as well

**Comment by patrick-rodgers** [comment]
An update on this after several years, but finally had the time to work on this. We waited for v3 because it didn't make sense to add a new package for only a few releases in v2 and we needed all the time we could get for v3 work. Now that v3 is stable it seems like a good time to introduce support for the tenant admin apis.

You can see the draft PR here #2328 (unfinished as I write this).

The new library will support calls to the following apis:
- _api/Microsoft.Online.SharePoint.TenantManagement.Office365Tenant
- _api/Microsoft.Online.SharePoint.TenantAdministration.SiteProperties
- _api/Microsoft.Online.SharePoint.TenantAdministration.Tenant

I haven't included every method available as I don't think folks would use them, but we can always add more after launch, good to get the library done and out for people to test. I also don't plan to document every method in the docs, rather folks can look at the code comments or help update the docs.

> Update doesn't work because of how these apis are built, the update operation is only supported in CSOM.

**Comment by michaelmaillot** [comment]
Awesome to see that admin node alive! I will take time to have a look at it, thank you for updating this!
