### ISSUE TITLE
SharePoint Add List - {OnQuickLaunch: true} is not working

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1073]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ @pnp/sp:  2.0.0 ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]

### Expected / Desired Behavior / Question
Docs give an example of how to add a list and include 'OnQuickLaunch': true 
https://pnp.github.io/pnpjs/sp/lists/#add-list
![image](https://user-images.githubusercontent.com/49648086/75102616-68484200-55bc-11ea-8946-cf471f689d2a.png)

### Observed Behavior
Get error that "OnQuickLaunch" does not exist in type 'Partial<IListInfo>'.

![image](https://user-images.githubusercontent.com/49648086/75102622-99287700-55bc-11ea-86c9-09c149f9c06d.png)

**Comment by patrick-rodgers** [comment]
I need to double check but I think that is a bug in the docs and that property isn't available in list creation properties.

**Comment by PathToSharePoint** [comment]
I checked the version history and found out that OnQuickLaunch was added on January 15. You might want to upgrade to a more recent version.

**Comment by patrick-rodgers** [comment]
I will have a look when I am back from leave if this isn't resolved. Thanks!

**Comment by patrick-rodgers** [comment]
Closing this after confirming the property is now in the interface. Thanks!
