### ISSUE TITLE
Using pagination with Redux without helpers

### ISSUE THREAD

**Issue by fanatyko47** [pnp/pnpjs#1074]
### Category
- [ ] Enhancement
- [ ] Bug
- [X ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.3  ]

Please specify what version(s) of SharePoint you are targeting: [  2013+   ]

### Expected / Desired Behavior / Question

Hi,

I'm trying implementing pagination in my app where I use Redux. Unfortunetaly there is no way to get next link as string, method nextLink is private in response object from getPaged(). 

Normally I would store nextLink reference somewhere in React context etc. but Redux doesn't allow storing of unserializable data. Is there any reason to not allow getting nextLink as string ?

Let's say I'll get next link from standard get() call on list item, how can I call it with pnp to get all benefits from entities, formated data etc. ?

Is there any plans to make Redux (or something alike) and pagination work a bit better ? 

Cheers, and as always thanks for your awesome work.

**Comment by koltyakov** [comment]
I consider we can expose it as public. Not sure there was a hard reason but an esthetic aspect.
I personally used unsafe `(pagedRes as any).nextUrl` right in case with a Redux app and pagination back and forward last time I need it.

**Comment by fanatyko47** [comment]
Well, that workaround is enough for me, but now, when I have nextUrl link, how can I use it with pnp methods to call it ? Or I have to use fetch/axios etc. but then I need to handle headers and stuff... :)
Something like sp.web.lists.get(nextUrl), for sending generic calls? 

Maybe I'm missing something, but can't see anything like that in docs. 

Thanks, for your time.

**Comment by koltyakov** [comment]
It's possible using `PagedItemCollection`:

```typescript
import { sp, PagedItemCollection } from '@pnp/sp/presets/all';

(async () => {

  const items = sp.web.lists.getByTitle('my-list').items;
  const nextUrl = 'some_url_with_page_token';
  const paged = new PagedItemCollection(items, nextUrl, {})
  const nextPageItems = await paged.getNext();
  // ...

})().catch(console.log)
```

**Comment by fanatyko47** [comment]
Sweet, that's everything I've needed. Thank you very much !
