### ISSUE TITLE
Stop excessive console.log warnings if in ie11 compat mode

### ISSUE THREAD

**Issue by jpalo** [pnp/pnpjs#1075]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.3]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Suggestion
We don't like to support IE11 any more than you, or anyone I suppose, but could we consider not logging warning to console.log on (apparently) each PnPJS method call? Or is there way to neatly omit logging that? I have a functionality doing lots of operations using PnPJS and console log gets filled with these warnings.

```
backend.js:6 PnPjs is running in ie11 compat mode. Not all features may work as expected.
```

![image](https://user-images.githubusercontent.com/6917905/75155266-51b6fd80-5718-11ea-9534-7ddf2f94069c.png)

**Comment by koltyakov** [comment]
As discussion suggestions I'd highlight the following options:
- Keep "as is" to encourage not using IE (kidding)
- Introduce internal state to log the warning once per opened page
- Introduce config parameter to suppress that warning
- Provide a readme how to suppress the warning using bundler

As an existing workaround to suppress that warning without a single change to the library I'd suggest Webpack [string replace loader](https://www.npmjs.com/package/string-replace-loader) and sort of the following configuration:

```json
module.exports = {
  // ...
  module: {
    rules: [
      {
        test: /linconfig\.js$/,
        loader: 'string-replace-loader',
        options: {
          search: 'console.warn("PnPjs is running in ie11 compat mode. Not all features may work as expected.");',
          replace: '',
        }
      }
    ]
  }
}
```

**Comment by jpalo** [comment]
Of your options 2 and 3 feel overkill unless there would be broader way to configure logging. I'll probably go with 4 as it is quick and "scales" also to other similar tasks.

I'd also reconsider what is the true purpose to log this warning at all.

**Comment by patrick-rodgers** [comment]
Ok, I just removed the warning. Change will go out in 2.0.4.

But you gotta talk to your customers/company and start really pushing them off ie11. It is time. Lots of great options out there, all free.
