### ISSUE TITLE
Getting [object Object] when trying to display a Person or Group field using PnP

### ISSUE THREAD

**Issue by astatke** [pnp/pnpjs#1078]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of SharePoint you are targeting: [   SP 2016      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

### Submission Guidelines
I am using PnP to display a list time in my SP 2016 on-premise for a list that has a column called ServiceContact with People or Group type. I can easily display all fields but not ServiceContact. I have limited JS skill and is wondering if you could help. Attached find a screenshot of my REST API call displayed in ATOMS. I also attached my JS code file.
<img width="672" alt="2-MyServices html-code" src="https://user-images.githubusercontent.com/5934455/75404175-04c55980-58c7-11ea-9bc0-499b146664dc.png">
<img width="791" alt="1-rest-api-atoms" src="https://user-images.githubusercontent.com/5934455/75404178-05f68680-58c7-11ea-95b2-f6a8bd0e4235.png">

**Comment by PathToSharePoint** [comment]
You are not using expand correctly, see the documentation. Your query should look like this:
```
$pnp.sp.web.lists.getByTitle("ListName")
.items
.select(...)
.expand(...)
.get()
```

**Comment by koltyakov** [comment]
Not related to the library actually. Generic JS dev question. We encourage asking such in community forums or [Gitter channel](https://gitter.im/OfficeDev/PnP-JS-Core).
To reach a property as in any JS code you should provide a path to the prop, e.g. `result[i].ServiceContact.EMail` with all corresponding validations and checks. Regarding library-specific, I'd say two things: one - expand is better be places into `.expand()` method and another one, it's likely, you have incorrect expand and `/Id` part should not be there.
