### ISSUE TITLE
How to add values to the publishing field in the sharepoint list pnp js

### ISSUE THREAD

**Issue by Muthuprasanth** [pnp/pnpjs#108]
I have an list with publishing fields. How to add items to the list using pnp js.I have tried the following code.But it throws an error.Please help me to resolve it.
 list.items.add({
            Title: "Add from node js PnP with image tag",
            t8ct: "10",
            choose_menu:"option2",
            Profilepic_sitecolumn:"`<img alt='no image' height='150' src='/SiteAssets/image/image1/India.png' style='BORDER: 0px solid '>`",
        }).then((res) => {
        console.log("items added successfully");
            console.log(res);
        });

**Comment by patrick-rodgers** [comment]
Can you share the error you are getting? What type of column is it?

**Comment by Muthuprasanth** [comment]
Hi Patrick It is a  Publishing Image column. I need to add items to the list

**Comment by Muthuprasanth** [comment]
Hi Patrick, It is a Publishing Image field. I need to add items to the list having publishing fields.
<img width="1063" alt="publishind field error" src="https://user-images.githubusercontent.com/17947663/40373585-d9c6cb10-5e04-11e8-9ff9-64a0eee6d619.png">

**Comment by Muthuprasanth** [comment]
Sorry Patrick By Mistake I close this issue

**Comment by patrick-rodgers** [comment]
I noticed in the error that you are using the old library, sp-pnp-js. Would encourage you to transition to these libraries going forward. There is [a transition guide](https://pnp.github.io/pnpjs/transition-guide.html) to help.

I am not aware of a way to set publishing page images from REST.

When updating a URL or Picture field you need to include the __metadata descriptor as shown below.

```TypeScript
const data = {
    "My_Field_Name": {
        "__metadata": { "type": "SP.FieldUrlValue" },
        "Description": "A Pretty picture",
        "Url": "https://tenant.sharepoint.com/sites/dev/Style%20Library/DSC_0024.JPG",
    },
};

await sp.web.lists.getByTitle("MyListTitle").items.getById(1).update(data);
```

**Comment by Muthuprasanth** [comment]
@patrick-rodgers Thanks.

**Comment by patrick-rodgers** [comment]
YW - going to close this issue as answered. Please _reopen_ should you need to continue the conversation.
