### ISSUE TITLE
Unable to copy/create a page with a specified PromotedState

### ISSUE THREAD

**Issue by jhholm** [pnp/pnpjs#1080]
### Category
- [X] Enhancement

### Version

Please specify what version of the library you are using: [1.3.10 / 2.0.3]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
When creating a page with ClientSidePage.create or copying a page with ClientSidePage.copyPage I should be able to set the page to be a news page (PromotedState = 1).

### Observed Behavior
When creating a page with ClientSidePage.create or copying a page with ClientSidePage.copyPage the new page is always a regular ClientSidePage (PromotedState = 0) after creation. I am unable to set the page afterwards as a unpublished news page (PromotedState = 1). I can only set the page to be a published news page via ClientSidePage.promoteToNews (PromotedState = 2).

### Steps to Reproduce
The code behind ClientSidePage.create doing the API call does not set parameter PromotedState. Thus a new page is always created implicitly with PromotedState = 0.

### Change proposal
Adding PromotedState parameter to the API call within ClientSidePage.create. I checked how SharePoint itself calls the API when creating a news page / regular page via OTB UI. If you are creating a standard page the parameter is not given in the API call, thus being implicitly 0. If you are creating a news page, the parameter PromotedState is given as 1.

I made a fork and created a branch from version-1 with my proposal to implement this functionality. I added the parameter PromotedState to create and copyPage methods. By default the parameter is set to 0.  I'm handling the logic of setting the correct PromotedState outside the pnpjs library in application code. The only difference between OTB SharePoint UI API calls is that in this case the PromotedState is always given: e.g. if you are creating a page, the call will have PromotedState = 0 explicitly.

You can see the change here:
https://github.com/jhholm/pnpjs/commit/7cfc7583d33410f3dfe5dae54a8a3eef653dc88c

### Reasoning for change

You could use promoteToNews method to set a page as news page, but that sets PromotedState to 2 and makes the news published. It is not possible for now to create a news page that is not published and thus has PromotedState = 1.

**Comment by jhholm** [comment]
I just noticed that my change proposal was a breaking change. I did not add PromotedState as the last optional parameter on copyPage. Changed the parameter to be the last parameter so no breaking changes would be needed.

https://github.com/jhholm/pnpjs/commit/ffbe7cd74bb993e295a567d3118320ca28b33469

**Comment by patrick-rodgers** [comment]
Thanks, will review the PR once I am back from leave. Appreciate you submitting it.

**Comment by patrick-rodgers** [comment]
Now that I am back I am seeing that you didn't create a PR for this, can you please do so and we will review? Thanks!

**Comment by patrick-rodgers** [comment]
@pkmelee337 - if this change was implemented does it help with your scenario of setting the state to 1 at creation time? I haven't tested this yet but @jhholm seems to have it working. Wondering if it is possible to achieve what you wanted and I didn't realize it.

**Comment by patrick-rodgers** [comment]
Anyway, had some time tonight waiting for a late meeting so I have implemented this change.

**Comment by jhholm** [comment]
Sorry. I was also on holiday and did not notice your message. Thanks.

**Comment by pkmelee337** [comment]
@patrick-rodgers Many many thanks! This would help with my scenario for sure as we are copying a page template and promoting it right after copying. Thanks a lot! (and @jhholm of course)
