### ISSUE TITLE
403 Forbidden error on graph.users.get() 

### ISSUE THREAD

**Issue by limcysam** [pnp/pnpjs#1081]
#1025 # Category
- [X] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ @pnp/graph ]

### Question

I am trying to create a new group and add a Team in MS Teams through a SPFx webpart (react). When I try to get the users (using the code graph.users.get()) I get a 403 Forbidden error. I am not sure what I am doing wrong. 

I have installed the following packages
` npm install @pnp/logging@1.3.10 @pnp/common@1.3.10 @pnp/odata@1.3.10 @pnp/sp@1.2.1 @pnp/graph@1.3.10 --save`

Can you please help me with this?

### Observed Behavior

I get the following error in console
_Uncaught (in promise) Error: Error making HttpClient request in queryable [403] Forbidden ::> {
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {
      "request-id": "c5c7f5e1-8513-4054-b818-67551017d20b",
      "date": "2020-02-28T02:41:16"
    }
  }
}
    at new HttpRequestError (parsers.ts:13)
    at parsers.ts:19_

### Steps to Reproduce

I am using the following code within my webpart.ts file

`
protected onInit(): Promise<void> {
    return super.onInit().then(_ => {
      graph.setup({
        spfxContext: this.context
      });
    });
}

  public async render(): Promise<void> {    
    const users = await graph.users.get();
    const element: React.ReactElement<IProvisionTeamsProps > = React.createElement(
      ProvisionTeams,
      {
        description: this.properties.description
      }
    );
    ReactDom.render(element, this.domElement);
  }
`

**Comment by koltyakov** [comment]
External APIs require permissions configuration. Check out [configure API request permissions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#configure-the-api-permissions-requests) it should shed the light what is missed in your SPFx solution.

**Comment by limcysam** [comment]
I am setting the following permissions in the package-solution.json

"webApiPermissionRequests":  [
      {
        "resource": "Microsoft Graph",
        "scope": "User.ReadBasic.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Group.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Directory.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "GroupMember.ReadWrite.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Group.ReadWrite.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Directory.ReadWrite.All"
      }
    ]

**Comment by limcysam** [comment]
When I deployed the package to the app catalog's site it worked. I was trying to get it to work using the gulp serve command 'https://site-url/_layouts/workbench.aspx'
