### ISSUE TITLE
AuthorByLine when Creating Clientside page

### ISSUE THREAD

**Issue by MagtheRag** [pnp/pnpjs#1082]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.x  ]

Please specify what version(s) of SharePoint you are targeting: [ Online ]

I was wondering if there is any way, when creating clientside pages to add the authorByLine. It does not seem like you have any function for it though I see it in this.json where you then have to append the whole json structure which feels a bit off?

//M

**Comment by patrick-rodgers** [comment]
Looking at this (like everything in client side pages) there are some complications which is why we took it out of the original implementation. Am looking at adding two methods `setAuthorsById` and `setAuthorsByLoginName`.

**Comment by patrick-rodgers** [comment]
Added this support, will go out in 2.0.4
