### ISSUE TITLE
Get item hidden fields values with pnp.js

### ISSUE THREAD

**Issue by fonbrauzen** [pnp/pnpjs#1083]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.3 ]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
I try to get list item field values via pnp.js:
`const item: any = await sp.web.lists.getById(itemIds.listId.toString()).items.getById(itemIds.id).get();`
is it possible to retieve also values for hidden fields?

### Observed Behavior
1. I can write values in hidden fields with pnp.js
2. I can retrieve such field object via `sp.web.lists.getById(itemIds.listId.toString()).fields.getByInternalNameOrTitle('MY_FIELD_NAME')`
So in this case a bit strange, that we don't have their values from list item...

### Steps to Reproduce
set some field as hidden with PowerShell and try to get its value with pnp.js from list item

**Comment by koltyakov** [comment]
Hi @fonbrauzen, 

Fields entity names can be explicitly provided with `.select('*,MY_FIELD')`, so hidden fields also can be retrieved.

**Comment by fonbrauzen** [comment]
> Hi @fonbrauzen,
> 
> Fields entity names can be explicitly provided with `.select('*,MY_FIELD')`, so hidden fields also can be retrieved.

thx, please mark as resolved. 
`await sp.web.lists.getById(itemIds.listId.toString()).items.getById(itemIds.id).select('*,MY_FIELD').get();`
