### ISSUE TITLE
Graph: Batch request error uncaught

### ISSUE THREAD

**Issue by RoelVB** [pnp/pnpjs#1084]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.x & 2.x]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
If a batch request fails I would like to get the error received from the Graph API. But instead we get `Cannot read property 'length' of undefined`.
> This only happens if the batch request itself fails, not the requests inside the batch

### Observed Behavior
If a batch request returns an error the parser method tries looping through `responses`, which is undefined.
This is the line that raises the error:
https://github.com/pnp/pnpjs/blob/8fa66e559d6fff5d3425fb34a5f8ac6f1a607187/packages/graph/batch.ts#L124

### Steps to Reproduce
I was adding members to a group using a batch request.
```typescript
graph.groups.getById('SomeID').members.inBatch(batch).add(`https://graph.microsoft.com/v1.0/users/SomeId`);
```
Reported this in issue #1085 

### Possible solution
I'm not sure about the best solution here. If I was I probably would have made a PR.
A quick solution I was thinking of is this:
```typescript
if(graphResponse.error) throw graphResponse.error
```
But I don't think this is in line with other errorhandling in this library? 😅

**Comment by patrick-rodgers** [comment]
Ok, thanks, will have to take a look.
