### ISSUE TITLE
lists.ensure always assumes manage permission

### ISSUE THREAD

**Issue by henningeiben** [pnp/pnpjs#1086]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  1.3.7 / 2.0.3   ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online      ]

### Expected / Desired Behavior / Question
If a list "foo" exists in the current site `sp.web.lists.ensure("foo")` should return the list even if the caller only has view-permissions on the list.

If the list does not exists, I would expect an error for a user with view-only permission, as he cannot create the list.

### Observed Behavior

Because the `ensure` method is calling

```javascript
const data = await list.update(addOrUpdateSettings).then(r => r.data);
```

when the lists exists, this fails for users with view-only permissions. Thus I cannot use this method to retrieve a list if it exist and have it created (as long as the calling user has sufficent permissions). Instead I will have to check myself if the list exists, which defeats the point of `ensure`.

**Comment by patrick-rodgers** [comment]
This is by design and [discussed here](https://github.com/SharePoint/PnP-JS-Core/issues/540). We have no plans to change this behavior.

**Comment by henningeiben** [comment]
Thx @patrick-rodgers for pointing that out. So I will refactor my code accordingly.
