### ISSUE TITLE
Patrick is on Family Leave

### ISSUE THREAD

**Issue by patrick-rodgers** [pnp/pnpjs#1087]
Hello,

I am as of now on family leave caring for my family and its new addition. If you are unsure where this work ranks against that, please read on 😀.

This project of course remains important to me and will continue on as normal - but with less attention from me for about a month or so. I encourage folks to help each other as possible, submit PRs to fix issues or add enhancements, and continue to report issues. But I won't be personally active here for a bit, so don't be discouraged that the project is somehow in trouble. I _may_ pop in from time to time depending, but for now my focus is on my family.

## What about the March release?

For now we will likely not do a March release and all milestones will move out a month. I _may_ have time to do the release depending on how things are going, but for now my focus is on my family.

## What about my issue?

@koltyakov, @juliemturner, @sympmarc, @PopWarner, @tavikukko (and many others) are active here, very smart, and will be around to help out. If for some reason they can't answer I will be catching up on issues when I am back.

## But I need answers now!

I understand and I have every confidence that one or more of the many very capable folks will do their best to help out. Your work is important but no amount of emailing, tagging me, etc. will change my current priorities.

## But there is an emergency!!!

In the case of an emergency you can write out your issue on [300 lb. paper](https://www.amazon.com/Fabriano-Artistico-Watercolor-Paper-10-Pack/dp/B00627VYDC/ref=sr_1_26?keywords=300+lb+paper&qid=1582937254&sr=8-26), wrap it around a standard Swiss Bank 1000g gold ingot, mail it to me in a box you make demonstrating two types of dovetail techniques, and I will address your issue as soon as I am back from family leave.

**But seriously - thank you to everyone for your support, understanding, and participation in PnPjs. It is deeply gratifying and I want you all to know you are appreciated. Thanks!**

**Comment by PopWarner** [comment]
Give our best to the family @patrick-rodgers and thanks for all your awesome work!

**Comment by LauraKokkarinen** [comment]
Dear Patrick, you do realise that it takes a bit longer for the baby to grow up than "a month or so" right? ;)

Don't feel guilty about prioritising your family over a leisure time open-source project now or in the future! It's the right thing to do. PnPJS might not be here in 15 years or so but your child hopefully will. Make sure you put in the time and effort to build a proper foundation. It's a PITA to try to re-architect that later on.

L

**Comment by ValerasNarbutas** [comment]
Congrats @patrick-rodgers !!
Take care your family, and first month is easiest :) eat sleep eat sleep... Now next ones you have to prepare :)

**Comment by VesaJuvonen** [comment]
Congratulations @patrick-rodgers. Enjoy the time off and prioritze family. We will be waiting for you when you get back. You have had just a tramendious impact on our open-source community within the past years, so if someone deserves some time off, it's you. 

Projects come and go, but family and friends stay for the lifetime. Let us know if we can help with anything before or when you are back. ❤

**Comment by simonagren** [comment]
Congratulations @patrick-rodgers. Have the best of time with the family <3

**Comment by KEMiCZA** [comment]
Congratulations @patrick-rodgers! Enjoy your time with your family and I wish you all good health and love.

**Comment by joelfmrodrigues** [comment]
Congratulations, but first month is the easiest one 😄 consider that your last month to rest. Two and half year old kid here and it just gets harder every month 😄

**Comment by VesaJuvonen** [comment]
I can't add reaction to actions, so a comment will do: Great to have you back @patrick-rodgers. ❤

**Comment by patrick-rodgers** [comment]
Great to be back, now to get to work 😁🐇

**Comment by sympmarc** [comment]
Welcome back, @patrick-rodgers! Where are the photos? :)

**Comment by koltyakov** [comment]
Welcome back! You missed the part when everyone started working from home.

**Comment by PopWarner** [comment]
Welcome back @patrick-rodgers! 🤗
