### ISSUE TITLE
Documentation: sp\items.html

### ISSUE THREAD

**Issue by GokuSSL5** [pnp/pnpjs#109]
Please describe how we can improve the doc page:
Improvement is to this page:
https://pnp.github.io/pnpjs/sp/items.html, under Basic Get

It should be noted that orderBy can be used on multiple columns. The format would be:
.orderBy("ColumnName desc/asc, ColumnName", true/false)

The documentation didn't cover that. I knew odata supported multiple columns. You just need to include the sort order after the first column then comma second column, all in quotations as your first parameter. 

I hope this helps.
Thanks,
Andy

**Comment by koltyakov** [comment]
Hey @GokuSSL5,

This is supported in PnPjs too for sure. 
Multiple orderBy can be chained for this purposes like this:

```
.orderBy("ColumnName1", true).orderBy("ColumnName2", false)
```
