### ISSUE TITLE
Question (low priority): what is an invokable factory?

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/pnpjs#1090]
**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2]

Please specify what version(s) of SharePoint you are targeting: [any]

### Expected / Desired Behavior / Question
The documentation is using the term "invokable factory". What does it mean, and how is it different from a factory function? I did a search but couldn't find the term used anywhere else in the JavaScript world.

Thanks you!

**Comment by juliemturner** [comment]
Although I didn't write that documentation I'm fairly sure he's just using the meaning of invokable as in IIFE [Immediately Invokable Function](https://developer.mozilla.org/en-US/docs/Glossary/IIFE). The term factory could easily be replaced with object. The only point is that you do not have to reference a function inside the factory to get it to execute.
