### ISSUE TITLE
Current versions of @pnp/sp do not work with angular >=6 out of the box

### ISSUE THREAD

**Issue by ntziolis** [pnp/pnpjs#1092]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: **@pnp/sp@latest**

Please specify what version(s) of SharePoint you are targeting: **SP Online**

### Expected / Desired Behavior / Question
Library should be able to make web requests after installing the respective packages + calling `sp.setup`.

The `@pnp/*` libraries should not rely on existence of `global` when executed in a web environment.

### Observed Behavior
Due to reliance of `global` (which is not recommended in web scenarios). Since angular 6 the global variable is not polyfilled by default anymore. Hence the pnp/sp libs do not work after installing them inside an angular app.

To make it work, the following has to be added manually to the `polyfills.ts`:
```
(window as any).global = window;
```

See for reference:
https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

### Steps to Reproduce
- generate new angular app
- install @pnp/sp
- setup sp + try to make a call

**Comment by patrick-rodgers** [comment]
I don't think this is a bug on our part that Angular decided to change how they handle things. They freely admit they are breaking a ton of stuff.

I do think we can improve our code so this isn't an issue.
