### ISSUE TITLE
Add Microsoft.Sharepoint.Utilities.WebTemplateExtensions.SiteScriptUtility.ExecuteSiteScriptAction()

### ISSUE THREAD

**Issue by jonathanhotono** [pnp/pnpjs#1096]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.0.3     ]

Please specify what version(s) of SharePoint you are targeting: [    online     ]

Can we add `Microsoft.Sharepoint.Utilities.WebTemplateExtensions.SiteScriptUtility.ExecuteSiteScriptAction()` into `@pnp/sp/site-scripts` ?

Sample code:
```
public executeSiteScriptAction = (site, actionDefinition) =>{
     let payload = {
                actionDefinition: JSON.stringify(actionDefinition)
            };
     const client = new SPHttpClient();
            client.post(site + "/_api/Microsoft.Sharepoint.Utilities.WebTemplateExtensions.SiteScriptUtility.ExecuteSiteScriptAction()", {
                body: JSON.stringify(payload)
            }).then(d => {
                return d.json();
            }).then(data => {
                res(data);
            });
}
```
Could also probably extend to have array of definitions consecutively if needed.
e.g:
```
private applySiteDesigns = async (site, definitions) => {
        for (let x = 0; x < definitions.length; x++) {
            let def = definitions[x];
            await this.applySiteDesign(site, def)
        }
}
```

sample definition (just normal site scripts):
```
const definitions = [
    {
        "verb": "installSolution",
        "title": "Announcements webpart",
        "id": "0eeb6e77-1068-4706-b9e5-02e9cf595921"
    },
    {
        "verb": "installSolution",
        "title": "Content Editor Enhancements webpart",
        "id": "a2567ab7-a3b5-4ea9-a1d5-49627515d8b2"
    }
];
```

Not sure if we can officially use it since I debugged this from the "Create new list" functionality on sharepoint online.

**Comment by patrick-rodgers** [comment]
Yes, we can look at adding this.

**Comment by patrick-rodgers** [comment]
Added this, will go out as part of 2.0.4
