### ISSUE TITLE
How to download file from document library using PnP JS

### ISSUE THREAD

**Issue by spvjebaraj** [pnp/pnpjs#1098]
Hi,

I am working in SPFx project. In that am having the requirement to download the file from document library to local system folder. How to do it via PnP JS?

Please help me.

**Comment by koltyakov** [comment]
Where to send an invoice?

**Comment by koltyakov** [comment]
You can use `getBuffer` or `getBlob` file methods:

```typescript
sp.web.getFileByServerRelativePath('/path/to/file').getBuffer()
  .then((b) => { /* do whatever needed with the buffer */ })
```

Other, is generic JS dev.

**Comment by koltyakov** [comment]
Please check the documentation before posting the issue first. E.g. there is plenty of samples for getting files content: https://pnp.github.io/pnpjs/sp/files/#reading-files

Also, please follow the issue template which is for the reason.

Please don't abuse issues list which is mainly used for issues and enhancement tracking, but not the support and "please do my job" questions!

Please target non-issue related and generic JS development questions in tech community, public chats or StackOverflow, first.

Thanks!

**Comment by spvjebaraj** [comment]
Thanks Andrew.
