### ISSUE TITLE
How to get the photo and presence from graph

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#1099]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  @pnp/graph": "^2.0.3"       ]

Please specify what version(s) of SharePoint you are targeting: [     Online    ]

### Expected / Desired Behavior / Question

How do I get user's photo and presence from graph?

### Observed Behavior
I see in the issue that the photo was added to version 2 but I can figure out how to use it.
Using the graph explorer, I can get the 2 like so:
`https://graph.microsoft.com/v1.0/users/user@tenant.onmicrosoft.com/photo/$value
https://graph.microsoft.com/beta/users/user@tenant.onmicrosoft.com/presence
`
Any suggestions?
Thank you!

**Comment by simonagren** [comment]
Hi @Ofer-Gal
I looked through the Graph package, and it seems that we have some gaps.

Some of the "stuff" is already there an will be mapped to the user, some other stuff needs to be created.

I could make these two a priority, and I'll get back to you as soon as it's finished. 
Please be a bit patient, since it's a manual job :)

/Simon

**Comment by Ofer-Gal** [comment]
Thank you!

**Comment by lgadola** [comment]
sorry, couldn't find the photo() function on graph.users. Has this been implemented?
using @pnp/graph 2.0.6

**Comment by juliemturner** [comment]
IT doesn't appear that it was fully implemented no.  For the time being, you can probably use the invokable override. 
For example, try this:
`let domains = await graphGet(GraphQueryable(graph.user.getById('userId')), "photo");`

**Comment by Ofer-Gal** [comment]
The Graph toolkit has an HTML for that now

**Comment by juliemturner** [comment]
Ok, but we need to either complete or remove the functionality from this library so I'll reopen this.

**Comment by juliemturner** [comment]
Photo endpoint is included and sample was added to the docs.
Presence endpoint is in the beta version, and as a rule we are not implementing endpoints in that branch.

**Comment by Ofer-Gal** [comment]
I am using the toolkit for Presence now. works nice.
