### ISSUE TITLE
Enums in TypeScript Declaration files

### ISSUE THREAD

**Issue by tavikukko** [pnp/pnpjs#110]
### Category
- [ ] Enhancement
- [x] Bug
- [ x] Question
- [ ] Documentation gap/issue

### Expected / Desired Behavior / Question
Using PnPjs in SP Editor, when compiling and executing the code against precompiled *js files, the enums can be used by the name, not by the index.

### Observed Behavior
When executing the code, for example using LogLevel.Error, you get error message saying "Uncaught (in promise) TypeError: Cannot read property 'Error' of undefined". if you use the index, in this case 3, it works. So, the compiled *.js file looses the enum values and is only accessible using the index of enums. Here is a article about using [Enums in Declarations files](https://lukasbehal.com/2017-05-22-enums-in-declaration-files)

### Steps to Reproduce
I have only tested this in my SP Editor with new PnPjs modules and I do not have any instructions to reproduce, I hope you cats the possible bug here. One possibility is also that if there is a options to transpile the TypeScript code to js, that it includes the enums from the d.ts file?

**Comment by tavikukko** [comment]
![screen shot 2018-05-24 at 13 16 09](https://user-images.githubusercontent.com/2223355/40479629-c734139e-5f54-11e8-96eb-f8092928788d.png)
![screen shot 2018-05-24 at 13 20 46](https://user-images.githubusercontent.com/2223355/40479828-59d8ae30-5f55-11e8-9a2e-3c9a3f6548e4.png)

**Comment by tavikukko** [comment]
ok, one possible solution is to remove the **const** from the declarations, like in pnp-js-core [LogLevel declarations](https://github.com/SharePoint/PnP-JS-Core/blob/master/src/utils/logging.ts#L5) and [compiled version](https://github.com/SharePoint/PnP-JS-Core/blob/master/dist/pnp.js#L1200).
Here is a blog post describing the effect of using const with [live demo](https://netbasal.com/a-smaller-bundle-with-const-enums-in-typescript-b7f786227e5e)

**Comment by patrick-rodgers** [comment]
Closing as this change is merged and live.
