### ISSUE TITLE
Validation error messages in PnPjs files

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/pnpjs#1101]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.3 ]

Please specify what version(s) of SharePoint you are targeting: [any ]

### Question
I am getting validation errors on the PnPjs files and wondering what I am doing wrong.

Here is an example of interface where I am getting errors:
`export interface IFieldCreationProperties extends ITypedHash<string | number | boolean>`

The error messages (on every property):
TS2411 Property ... of type 'string | undefined' is not assignable to string index type 'string | number | boolean'

The error messages disappear if I edit the PnPjs file and replace the line with:
`export interface IFieldCreationProperties extends ITypedHash<string | number | boolean | undefined>`

Thank you!

**Comment by patrick-rodgers** [comment]
You probably have strict or strict null checks enabled in your project. Please see [this thread](https://github.com/pnp/pnpjs/issues/1047).

**Comment by PathToSharePoint** [comment]
Thanks @patrick-rodgers , setting strictNullChecks to false removed the messages. I had initialized the project with tsc --init, which sets strict to true by default.
