### ISSUE TITLE
Missing properties CurrentUser and ParentWeb on type IWebInfo

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/pnpjs#1102]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.3]

Please specify what version(s) of SharePoint you are targeting: [any]

### Question
I am using the following code to retrieve CurrentUser and ParentWeb:
`sp.web.expand("CurrentUser, ParentWeb")()`

This gives me a validation error when I try to retrieve the CurrentUser and ParentWeb properties, as they are not listed in type IWebInfo.

My current workaround is to force a type of any on the REST response, is there a better way?

Thank you!

**Comment by koltyakov** [comment]
Yes, the approach is to cast the payload to extended interface with extra requested data structures. E.g. when list items are requested their structure is only known in the context of application logic and custom interfaces are commonly used for type safety.  
You also can use [entity merging](https://pnp.github.io/pnpjs/sp/entity-merging/) or [parsers](https://pnp.github.io/pnpjs/odata/parsers/#lambdaparser).

**Comment by PathToSharePoint** [comment]
Thank you for the reply and the pointers!
