### ISSUE TITLE
System.UriFormatException when using File.copyByPath()

### ISSUE THREAD

**Issue by mzbrandl** [pnp/pnpjs#1104]
### Category
- [x] Bug
- [x] Question

### Version

Please specify what version of the library you are using: [2.0.3]

Please specify what version(s) of SharePoint you are targeting: [online]

### Expected / Desired Behavior / Question
File.copyByPath() working as described in the [documentation](https://pnp.github.io/pnpjs/sp/files/#copy-by-path) and copying a file from one site collection to another.

### Observed Behavior
Following errors are thrown:
`POST https://xxx.sharepoint.com/sites/a/_api/SP.MoveCopyUtil.CopyFileByPath(overwrite=@a1)?@a1=false 500 (Internal Server Error)
Uncaught (in promise) Error: Error making HttpClient request in queryable [500] Internal Server Error ::> {"error":{"code":"-1, System.UriFormatException","message":{"lang":"en-US","value":"Invalid URI: The format of the URI could not be determined."}}}
at new HttpRequestError (parsers.js:130) 
at Function.<anonymous> (parsers.js:145) 
at step (tslib.es6.js:99)
at Object.next (tslib.es6.js:80)
at fulfilled (tslib.es6.js:70)`

### Steps to Reproduce
Create a SPFx web part, add pnp and deploy on a site. Get a file with getFileByServerRelativePath() works. Try to copy a file with .copyByPath() using either absolute url (https://xxx.sharepoint.com/sites/b/SitePages/test.aspx) or relative url (sites/b/SitePages/test.aspx) as parameter and providing either true or false as second parameter.

I hope this can be resolved, Thanks!

**Comment by koltyakov** [comment]
`sites/b/SitePages/test.aspx` is incorrect relative URL. A relative URL must start with `/`. Could you try does it work for you with a correctly formatted relative URL (`/sites/b/SitePages/test.aspx`)?

**Comment by mzbrandl** [comment]
I tried it with `/sites/b/SitePages/test.aspx`, same result. Then thats also an error for the destinationUrl in the code example in the [docs](https://pnp.github.io/pnpjs/sp/files/#copy-by-path) which is also missing `/`.

**Comment by koltyakov** [comment]
Confirming the method doesn't work for me too, or I miss something (never used that method in my apps). @joelfmrodrigues looks that the method was added initially with your help, maybe you know what we miss? For me, it looks that it worked before and stopped due to possible server-side changes (e.g. expect only absolute paths for both `destPath` and `srcPath`),

**Comment by joelfmrodrigues** [comment]
Hi @koltyakov @mzbrandl  
yes the documentation is definitely missing the starting '/' on the relative url.
I have just tested a component that is currently deployed on a client tenant and it's still working and I am passing relative urls, but I can see the actual requests using absolute urls on the Network tab of the browser dev tools.

Any chance one of you could check the network requests and confirm if you get the same?

**Comment by koltyakov** [comment]
Thanks @joelfmrodrigues,
 
They are relative:

![image](https://user-images.githubusercontent.com/7816483/76319644-9209a480-62f0-11ea-9816-a7770b92ba88.png)

Test it using the following code, \w 2.0.3:

```typescript
await sp.web.getFileByServerRelativePath('/sites/site1/Shared Documents/Doc.docx')
  .copyByPath('/sites/site2/Shared Documents/Doc.docx', true)
  .catch(console.log);
```

**Comment by joelfmrodrigues** [comment]
I'm inclined to think that this could be down to a change on PnPjs after I used it (I used 2.0.2)
The url should be converted to absolute

`
public async copyByPath(destUrl: string, KeepBoth = false): Promise<void> {

        const { ServerRelativeUrl: srcUrl, ["odata.id"]: absoluteUrl } = await this.select("ServerRelativeUrl")();
        const webBaseUrl = extractWebUrl(absoluteUrl);
        const hostUrl = webBaseUrl.replace("://", "___").split("/")[0].replace("___", "://");
        await spPost(Folder(webBaseUrl, `/_api/SP.MoveCopyUtil.CopyFolderByPath()`),
            body({
                destPath: {
                    DecodedUrl: isUrlAbsolute(destUrl) ? destUrl : `${hostUrl}${destUrl}`,
                    __metadata: {
                        type: "SP.ResourcePath",
                    },
                },
                options: {
                    KeepBoth: KeepBoth,
                    ResetAuthorAndCreatedOnCopy: true,
                    ShouldBypassSharedLocks: true,
                    __metadata: {
                        type: "SP.MoveCopyOptions",
                    },
                },
                srcPath: {
                    DecodedUrl: `${hostUrl}${srcUrl}`,
                    __metadata: {
                        type: "SP.ResourcePath",
                    },
                },
            }));
    }
`

**Comment by joelfmrodrigues** [comment]
Just updated PnPjs to the latest version on my project and it still works, so not an issue with the library.
Also debugged to double check that I was definitely passing relative paths when calling the function and I can confirm this was the case.
"It works on my machine" 😁

@koltyakov just noticed that you had already provided details with the post request body...sorry my bad. It seems to be an issue with constructing the absolute Url...I will try to investigate further later today

**Comment by joelfmrodrigues** [comment]
I can get the same error when testing with SP Editor extension. Did you test here, or in a SPFx project?

**Comment by koltyakov** [comment]
It was SPEditor which I used for testing this issue.

**Comment by joelfmrodrigues** [comment]
@koltyakov  not sure how this could get more confusing...
Was having the same error when trying via SP Editor some hours ago. Was going to give it another go and now it just works...same code snippet...

**Comment by mzbrandl** [comment]
When using the SP Editor I get `System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."`. I am site owner on both sites. What permissions are needed?

**Comment by joelfmrodrigues** [comment]
@mzbrandl @koltyakov  I have been unable to recreate this since the first day. I can't understand why I was getting the error on SP Editor and now it just works. Any chance you could try again and try to provide some additional info

**Comment by koltyakov** [comment]
@joelfmrodrigues can the method potentially require some extra settings on the tenant which is just applied for you and not for me? I.e. official document within record management, or something.

Are you on target of standard release? I'm mostly on the standard releases.

@mzbrandl, regarding permissions, SPEditor doesn't require any permissions settings, the request is sent from the current page using the current user permissions, so native APIs do not need any auth bindings configuration so it's something else.

**Comment by joelfmrodrigues** [comment]
@koltyakov No...this seems to work on my dev tenant (using target release) and on a client tenant using standard release.

@mzbrandl can you try to copy or move a document using the OOB Copy to or Move to and see if that works? Please test within the same site collection as the Copy to and Move to functionality use a different API when going cross-site collections

**Comment by mzbrandl** [comment]
@joelfmrodrigues OOB Copy To works. Using File.copyByPath() within the same site collection now works as well. I am now only getting `System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."` when trying to copy between site collections. I wonder what user permissions could that be, since I am site owner on both sites?

**Comment by mzbrandl** [comment]
I figured it out!
It seems the problem was that I tried to copy an aspx file to Site Pages, which is apparently blocked. [This thread](https://techcommunity.microsoft.com/t5/sharepoint/access-denied-in-sharepoint-sitepages-library/m-p/77891) helped me figure this out. I will be using Files.AddTemplateFile() in a C# solution instead.
Thanks for your attention.

**Comment by joelfmrodrigues** [comment]
@mzbrandl thanks for the info.
I still have no idea why it was failing on my first test with SP Editor after you reported it and why it started working the next day...perhaps some server side changes...

**Comment by samu11** [comment]
Hi @joelfmrodrigues I hope you are doing fine.
I am having an error when using the .copyByPath "{"odata.error":{"code":"-2147024809, System.ArgumentException","message":{"lang":"sv-SE","value":"Value does not fall within the expected range."}}}". I dont get it which value is it is the destination url or the source url. I am using serverreletive urls and @pnp version is 2.0.9. When i use copyTo function it works fine but now i need to copy docs across a different site collection.
sp.web.getFileByServerRelativePath(surl).copyByPath(durl,true,false);
Can u please help me?
