### ISSUE TITLE
Custom User-Agent causes requests to fail in Firefox

### ISSUE THREAD

**Issue by JakeStanger** [pnp/pnpjs#1106]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.10]

Please specify what version(s) of SharePoint you are targeting: [SPO, SPFx 1.9.1 / 1.10.0]

### Expected / Desired Behavior / Question
Requests succeed regardless of browser

### Observed Behavior
Requests sent through PnP fail on Firefox with service unavailable. The same requests do not fail using the `fetch` API, or using PnP in Chrome.

This only seems to be happening for some endpoints in some tenants currently. 

It seems to be related to the fact Firefox sends a custom User-Agent string for PnP, while Chrome sends its default.

This has seemingly only just started happening too.

### Steps to Reproduce
- Try and get the site groups using PnP JS (to form `_api/web/sitegroups?$select=Id,Title`)
- Notice the request fails on Firefox but succeeds on Chrome
- Notice the difference in request user agent strings.

**Comment by patrick-rodgers** [comment]
Ok, we can just remove that user agent stuff I think - was added as part of a throttling scheme that never ended up being used.

**Comment by JakeStanger** [comment]
It looked like the problem was only a temporary one, but I think removing the custom UA is a good idea regardless. I suspect this won't be the only problem of its kind.

Cheers for the quick work.

**Comment by patrick-rodgers** [comment]
Moved the user agent code to the nodejs module only. Closing this as it should be resolved with 2.0.4

**Comment by JakeStanger** [comment]
Was this dropped from the V1 release?

No worries if so, just means I've finally got to put in the effort to upgrade to V2.
