### ISSUE TITLE
RenderListDataAsStream not working for item in subfolder.

### ISSUE THREAD

**Issue by RamaKaryam** [pnp/pnpjs#1115]
### Category
Bug

### Version

Please specify what version of the library you are using: [   1.3.4      ]

Please specify what version(s) of SharePoint you are targeting: [   SPO      ]

### Issue
I have the below code
let params = {
            RenderOptions:RenderListDataOptions.ListData,
            ViewXml: `<View>
            <Query>
                <Where>
                    <Eq>
                    <FieldRef Name="ID"/>
                    <Value Type="Number">${itemId}</Value>
                    </Eq>
                </Where>
                </Query>
                <RowLimit Paged="TRUE">1</RowLimit>
            </View>`
        };
        return sp.web.getList(libraryUrl).renderListDataAsStream(params).then((data) => {
//some more code;
});

I get item metadata just fine when item is in root folder of library. But I get zero rows back when item is in a subfolder. Tried the below as well:

        return sp.web.getList(libraryUrl).renderListDataAsStream(params,{RootFolder:'folderA/folderB'}).then((data) => {});

And documentation about usage of renderListDataAsStream is very scanty. So I apologize if I am just missing something.

**Comment by koltyakov** [comment]
When dealing with CAML and subfolders, don't forget defining scope to be recursive: `<View Scope=" RecursiveAll">...</View>`. What you describe us the expected behavior.

**Comment by RamaKaryam** [comment]
@koltyakov Sorry about that. I did try a 'Recursive'. Apparently not 'RecursiveAll'. Thank you.
Shouldn't it also be working with RootFolder override param?
