### ISSUE TITLE
How to create a non-group connected modern TeamSite

### ISSUE THREAD

**Issue by sohotra-dev** [pnp/pnpjs#1117]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0.3      ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online      ]

### Expected / Desired Behavior / Question
How can I create a non-group connected modern TeamSite?

### Observed Behavior
Only non-group connected option is a communication site, however, for TeamSite there is no function for non-group connected.

[PnP JS - Create a Communication site](https://pnp.github.io/pnpjs/sp/sites/#create-a-modern-communication-site)

**Comment by patrick-rodgers** [comment]
@VesaJuvonen - please help me understand if this is possible. I thought all modern team sites were backed by a group?

**Comment by sohotra-dev** [comment]
I used the SharePoint API to [create the non-group connected modern TeamSite](https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest).

**Comment by patrick-rodgers** [comment]
Ah, ok - a new API (at least to me). Will need to have a look and see how best to add it but should be able to.

**Comment by patrick-rodgers** [comment]
Looking at this the method `site.createCommunicationSite` is the right method, we just need to include a param for the webtemplate as currently it is hard coded. So that is all that is needed, we already implemented this api I just forgot. So we can make that change.

**Comment by sohotra-dev** [comment]
> Looking at this the method `site.createCommunicationSite` is the right method, we just need to include a param for the webtemplate as currently it is hard coded. So that is all that is needed, we already implemented this api I just forgot. So we can make that change.

Cool, thank you.

**Comment by patrick-rodgers** [comment]
Added two new methods, change will go our in 2.0.4 giving you access to all the parameters used in the request.

**Comment by sohotra-dev** [comment]
awesome thank you!
