### ISSUE TITLE
ClientSidePage promoteToNews function publishes the page - SharePoint search will crawl the page from this moment

### ISSUE THREAD

**Issue by pkmelee337** [pnp/pnpjs#1121]
### Category
- [ ] Enhancement
- [ x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.9]

Please specify what version(s) of SharePoint you are targeting: [SharePoint online]

### Expected / Desired Behavior / Question
When promoting a ClientSidePage to a news article with the promoteToNews function, I don't expect the page to get published. For example. we have created a panel to create different kind of pages from an overview. Users will have to fill the page afterwards, and publish it themselves when the page is ready.

### Observed Behavior
Due to an bugfix for issue #858 the page get's saved with publish to true (pull request #916 - commit 7d04fb4faf790b96e5862ab4db5d712e81f158c5) when LastVersionCreatedBy is empty. The promotedstate also is 2, but it should be 1 I think. This results off course in the page getting published, but more important: the page is also crawled by search while there isn't any content on the page yet.

### Steps to Reproduce
Create a page and promote it as news using the ClientSidePage.promoteToNews function.

**Comment by patrick-rodgers** [comment]
See [this issue](https://github.com/pnp/pnpjs/issues/858) and the [related code change](https://github.com/pnp/pnpjs/pull/916/files#diff-eaa43f351a84c7dba0df886080736c6eR718)s to understand why we publish on promoteToNews. I think we might be stuck on this one but will look deeper once I am back from leave.

**Comment by pkmelee337** [comment]
Hi Patrick,

Thanks for your fast reply! Yeah, that's exactly the issue and code changes I mentioned in Observed behavior and I do understand the code change. However, before those code changes the page also wasn't published, so isn't it possible to use the suggestion Ajit mentioned? PromotedState 1 means a News page which isn't published yet and that's exactly the case. That would give us more control over when to publish the page.

I just tested it without publishing the page, (ClientSidePage.save(false)) and the FirstPublishingDate also stays null after publishing from the UI.

About your edit. We have created a panel where users are able to select different types of pages from a custom news overview. (with extra filters etc.) These pages are all based on different page templates. Some are news and some are not. When a page is created from this panel, the user is redirected to the edit view of the page, where he is able to fill the page and publish it from the UI. When we use the promoteToNews from this panel, the page is already published when it is not filled by the user yet. This means that this empty news page is already crawled by search.

**Comment by pkmelee337** [comment]
Just also tested the suggestion Ajit mentioned and this sadly does not update the PromotedState. (stays 0) Also updating the PromotedState on the listitem doesn't work. The only thing that seems to work is setting the PromotedState on the page with the file editor from SP Editor (<mso:PromotedState msdt:dt="string">1.00000000000000</mso:PromotedState>), but I do not see any options to do this from js.

I also found jhholm working [on a possible solution](https://github.com/jhholm/pnpjs/commit/7cfc7583d33410f3dfe5dae54a8a3eef653dc88c) by setting the PromotedState from the create or copy page the first time.

**Comment by patrick-rodgers** [comment]
The big problem is that this API isn't a public one - so we have to mostly guess and figure out how it works and more importantly is designed only to support the UI actions on the page. It isn't designed to be able to call any method at anytime and have everything work. Certain things aren't available on pages until other actions happens, and the API gets confused if you try and do too many things out of order.

I would again question the process of promoting an empty page - think of it from the UI. A user would create a page, fill out the page, then promote the page. That workflow works, trying to be too clever just breaks things.

I don't view this behavior as a bug in the library but rather us doing our best to make an undocumented unofficial API available to folks. Not all scenarios can or will be supportable because the underlying API may not support them.

**Comment by pkmelee337** [comment]
Ah I didn't know that, thought it was public. now it makes sense why I couldn't fine any information on this api. Do you know if there are any plans for a public API?

Yeah I understand what you're saying, but hard to explain to customers. Our news template is quite different than the other page templates, so it's confusing if they select a news template and still have to promote it to news afterwards.

No problem. As I said, I didn't know it was an unofficial API. You guys are doing a great job for sure. I made it work with overwriting the promoteToNews functions with a custom method and saving without a publish. We are also doing some custom work on page publish and are setting the FirstPublishedDate right there. This fixes the problem for us. Would be great to have an option to publish the page on a promote or just use a save though, but I also understand if we're the only ones with a scenario like this.

Thanks for your help anyway! 👍

**Comment by patrick-rodgers** [comment]
Going to close this since I think its answered. I did verify that in the UI the promote to news button isn't visible (at least I couldn't find a case) until the page is published. I don't think the API is designed to handle promoting a page until it is published.

If you can provide a PR that addresses this (you say you have code that works) we are happy to review. Thanks!

**Comment by pkmelee337** [comment]
Yes, thank's very much for your efforts. 👍 

The code that works for us wouldn't be something that fit's into the PnPjs code. We have an event on the publish button in a SharePoint page. In this event we are handling some save events for custom fields we have on the page and in this event we are also setting the FirstPublishedDate now. Little bit dirty, but SharePoint doesn't provide a way yet to save our custom fields on a SharePoint modern page.

**Comment by patrick-rodgers** [comment]
Awesome, thanks!
