### ISSUE TITLE
CamlQuery gets no result 

### ISSUE THREAD

**Issue by raimund25** [pnp/pnpjs#1122]
hello, whatever i do, i get no results with CAMLQuery

the code is simple
`import { sp,ICamlQuery } from "@pnp/sp/presets/all";`

and then followed the getting-started
`    // get the list by Id
    const list = await sp.web.lists.getById(listID.Id);

    
    // build the caml query object 
    const caml: ICamlQuery = {
      ViewXml: "<View><ViewFields><FieldRef Name='Title' /></ViewFields><RowLimit>5</RowLimit></View>"      
    };

    // get list items
    let items_query = await list.getItemsByCAMLQuery(caml);

    // log resulting array to console
    console.log(items_query);
`
as shown in this screenshot.. calling a simple query
![image002](https://user-images.githubusercontent.com/62604534/77441824-28a68d00-6dea-11ea-9732-cde15e714150.jpg)

but result is always nothing or a array with 0
![image004](https://user-images.githubusercontent.com/62604534/77441943-54c20e00-6dea-11ea-95c7-5f29dec16f97.jpg)

the query goes to sharepoint online, pnp-version is the latest 2.0.3

**Comment by koltyakov** [comment]
Hey @raimund25,
 
Can it be, all your items in subfolders? Then I'd suggest trying `Scope="RecursiveAll"` for the CAML view.

The off-topic question is why CAML? And can you get the items with `.items.get()`?

**Comment by raimund25** [comment]
hello @koltyakov, thanks for your response.
the list is a simple list in a teamwebsite
i tested if i get the list by using the .ensure()  method and this works to get the list.

`    // ensure that a list exists. 
    const listTestExists = await sp.web.lists.ensure("Liste01");
    const listID = await listTestExists.list.select("Id")();
    console.log("ListID=" + listID.Id); `

but when i try to call the items by list.getItemsByCAMLQuery(caml) then i always get nothing back.

`// // get list items
    let items_query = await list.getItemsByCAMLQuery(caml);

    // log resulting array to console
    console.log(items_query);

     var nItems =items_query.Count;
     console.log("Items Count=" + nItems);`

![image011](https://user-images.githubusercontent.com/62604534/77467731-cca13000-6e0c-11ea-88a0-33a15d87855c.jpg)

List
![image013](https://user-images.githubusercontent.com/62604534/77468115-71237200-6e0d-11ea-90df-b00f24c4c287.jpg)

 
after getting a base Camlquery working, i will build some sums over a bigger list counts.

**Comment by koltyakov** [comment]
I can't see any error in the code samples you posted. Items should be returned.

Can you check if this returns items:

```typescript
const list = sp.web.lists.getByTitle('Liste01');

console.log('get:', await list.items.get());
console.log('renderListData:', await list.renderListData('<View></View>'));
console.log('renderListDataAsStream:', await list.renderListDataAsStream({
  ViewXml: '<View></View>'
}));
```

P.S. Btw, there is no need for getting a list twice. You get is with ensure (which is an admin method) then by id. I'd recommend getting by URI as the most reliable or just by title.

**Comment by koltyakov** [comment]
Have an idea, as you `ensure` the list, it can be, that you actually targeting different web. With the `ensure` method a new list is created (blank new) and the request goes to that different empty list but not the one you think of. Please check in a browser DevTools tools network tab, where the request ends up being sent.

**Comment by raimund25** [comment]
great idea... i will test it now.

**Comment by raimund25** [comment]
hello @koltyakov , i solved my problem by your ideas and by the help of a further collegue.
the point is, that when following the pnp-getting-started, then oninit() initializes the sp context to the place where the webpart is. 
so as you said, the sp.list.ensure() allway created something and gave me an empty table back..
the solution:
first get the Web of the subsite
and then get the list there.... so finally it works fine.
`    let subWeb= Web("https://mysite.sharepoint.com/sites/subsite");
    let list=subWeb.lists.getByTitle("Liste01");`


thank you for your help
regards
raimund
