### ISSUE TITLE
Eror in getClientSideWebparts() in pnp version 1.3.7 & 2.0.3

### ISSUE THREAD

**Issue by Hari1667** [pnp/pnpjs#1128]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [       1.3.7 & 2.0.3  ]

Please specify what version(s) of SharePoint you are targeting: [   SharePointOnline      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
am planning to get clientside webparts from SharePoint Online using 
await web.getClientSideWebparts();
expected to return all clientside webparts from site collection 

### Observed Behavior
It throws error like below

> Uncaught (in promise) Error: Error making HttpClient request in queryable [500]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.UnknownError","message":{"lang":"en-US","value":"Unknown Error"}}}
    at new HttpRequestError

### Steps to Reproduce
add this line and debugged in chrome developer tool it throws error

kindly help to resolve this, Thanks in Advance!!

**Comment by patrick-rodgers** [comment]
Very unsure what you are reporting. If you are [doing things correctly](https://pnp.github.io/pnpjs/sp/clientside-pages/#add-controls) this should work. If you can please provide a repo we can clone and see the issue we might be able to help.

I would:

- Check your imports
- Ensure you are using objects and properties that exist, "sp.we" doesn't exist, did you mean "sp.web"?
- Ensure you have [setup the context](https://pnp.github.io/pnpjs/getting-started/#using-pnpsp-setup)
- There is no webpart.sent() method - so no ideas there

**Comment by Hari1667** [comment]
@patrick-rodgers I have used below line to import PnP
`import { sp } from "@pnp/sp";` then created a function get client side web parts.

`  private async copyPage(){
var webPartCollection=await sp.web.getClientSideWebParts();
}`
but it throws the below error
`Uncaught (in promise) Error: Error making HttpClient request in queryable [500] ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.UnknownError","message":{"lang":"en-US","value":"Unknown Error"}}}
at new HttpRequestError`

**Comment by patrick-rodgers** [comment]
Sorry - that code doesn't make a ton of sense to me. I think you might be missing the [selective imports](https://pnp.github.io/pnpjs/concepts/selective-imports/). You can use a [preset](https://pnp.github.io/pnpjs/concepts/selective-imports/#presets) OR you need to include all the modules you need. [Please see the example](https://pnp.github.io/pnpjs/sp/clientside-pages/#add-controls). I would also suggest checking again that you are performing the setup work as mentioned in my earlier reply.

**Comment by patrick-rodgers** [comment]
Going to close this due to lack of activity. If you are still facing problems here please open a new issue, ref this one and we will do our best to help. Please include as much information as possible to help us figure things out. Thanks!
