### ISSUE TITLE
IDEA: auth @pnp/graph with the @microsoft/sp-client-preview approach

### ISSUE THREAD

**Issue by mpowney** [pnp/pnpjs#113]
### Category
- [x] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ @pnp/graph 1.1.0  ]

### Expected / Desired Behavior / Question
Is it possible to use the fluency of pnp/graph with the same authorization / authentication process as has been implemented in preview in the [MSGraphClient in @microsoft/sp-client-preview](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial)?

### Observed Behavior
As I understand it, to auth to Graph today using pnp/graph, I need to configure an AAD Application in my Azure tenant, and expose the secret in code, which for SPFx solutions isn't ideal.

The MSGraphClient tutorial describes how API auth management is being added to the preview SharePoint admin center.  It would be ideal to use the same admin process for pnp/graph solutions. Is there a way to leverage the same auth process that's been defined in the microsoft/sp-client-preview library when using this library?

While MSGraphClient is fluent, it doesn't come with the typed autocomplete for Graph API calls like @pnp/graph does. @pnp/graph is, in that sense, more developer friendly.

**Comment by patrick-rodgers** [comment]
Yes, this already works today! You only need to register the application when you are using it nodejs in an "app only" mode. If you are working in SPFx you need only do a small piece of setup, [as outlined here](https://pnp.github.io/pnpjs/graph/index.html#getting-started-with-sharepoint-framework):

```TypeScript
public onInit(): Promise<void> {

  return super.onInit().then(_ => {

    // other init code may be present

    graph.setup({
      spfxContext: this.context
    });
  });
}
```

We will under the hood create a new client for you based on the "hidden" SharePoint application behind the scenes. Exactly the same one used by the GraphHttpClient. You will need to still request the permissions in your SPFx app same as for GraphHttpClient.

HTH

**Comment by patrick-rodgers** [comment]
Going to close this as answered. If you have further questions please do _reopen_ the issue so we can follow up. Thanks!
