### ISSUE TITLE
Any way for GetItemsByCAMLQuery to return time zone with the dates? 

### ISSUE THREAD

**Issue by Katydude** [pnp/pnpjs#1145]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [ X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.3.9 ]

Please specify what version(s) of SharePoint you are targeting: [ 2013  ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
 web.lists.getByTitle(listTitle).getItemsByCAMLQuery(camlQuery) should return same values as JSOM for datetime fields.

### Observed Behavior
If I use the JSOM to execute a query via web.get_lists().getByTitle(listTitle).getItems(camlQuery), I get back an integer for datetime fields (opened, modified, etc). This is apparently a UTC value because I can properly pass it to Moment.js and translate the value into local time. However, using @pnp/sp I get a string without any time zone information, e.g. 4/8/2020T12:38. How do you recommend people handle this? I have my own opinions about all of this but I don't want to cloud the issue until I understand if I am missing something, or why the tz information is dropped, or why the dates are not returned in UTC as the baseline. Can UTC be specified as an option for queries?

### Steps to Reproduce
See Observed Behavior

**Comment by koltyakov** [comment]
Hi there,

With 2013, I'm afraid this is not possible (not completely sure though).
In SPO, there was an option to return dates in UTC with CAML-based methods.

**Comment by Katydude** [comment]
JSOM does return a serialized number, though. Let me confirm if this number is in UTC or local to the server. My issue is that I have formulas that give different results depending on whether the values are returned from JSOM or pnp/sp. The pnp/sp ISO 8601 dates must be losing information.

**Comment by koltyakov** [comment]
What's important in the first place, it's not PnPjs which returns something in a specific format but the REST API for a specific version of SharePoint. If REST doesn't do something we can't adjust it. I'd better use/co-use another method with legacy SP 2013. E.g. if CAML can't be replaced with OData (which returns dates in UTC), some additional request(s) might help to retrieve dates in a proper way. Kind of a painful workaround, but wait a minute, it's SP 2013 after all, way too old thing.

**Comment by Katydude** [comment]
Are you saying the newer versions of SharePoint do not have this issue with REST and CAML Queries? Because we are looking to upgrade later this year. Also, JSOM is REST. I will monitor the response in the F12 developer console and see what the server is returning raw. 

You should know by now that SharePoint changes very little from version to version, though.

**Comment by Katydude** [comment]
Ah, I see. JSOM sends its requests to _vti_bin/processquery.svc, not the REST API interface. That endpoint returns fully typed data. Hmm. Might have to look at just packaging up all of the SharePoint .js files into a bundle and using the proper JSOM inside of Angular instead.

Do you think the date values returned by REST are always in the time zone of the server? I notice you have the incorporated the get timezone method into pnp. If the dates always come back in accordance with that then I can do the conversion.

**Comment by juliemturner** [comment]
Here's some guidance on how date values are returned from the REST endpoints: [SharePoint time, is not your time, is not their time.](https://julieturner.net/2017/04/sharepoint-time-is-not-your-time-is-not-their-time/)

**Comment by Katydude** [comment]
Thanks a ton for that, Julie! Now I see why it's so inconsistent. I think I may just overthrow pnp and package up the .js files. I did a trial run of that last week and it worked well in Angular. I was able to pull managed metadata and everything.

**Comment by juliemturner** [comment]
It wouldn't be what I would do, because I'd want my code to be future proof, but if it works for you then best of luck.

**Comment by Katydude** [comment]
Everything's a tradeoff. The pnp framework is missing a lot of stuff so making a bunch of hacks to support one framework over another comes with its own issues. But I do see what you're saying. When I move my app to 2019 later this year, will it still work? Not sure. I'd bet JSOM interface isn't going to change that much so I can possibly just re-package up the SP2019 js files and keep going. We'll see. There's no perfect solution when all software frameworks continue to evolve. It's what keeps us all employed :)

**Comment by patrick-rodgers** [comment]
@Katydude 

> The pnp framework is missing a lot of stuff

We are always looking for feedback on areas folks would like to use and the development targets are prioritized by user feedback. It doesn't help to say many things are missing and leave. Encourage you to submit an issue or issues of things you see as missing so we can look at addressing them.

**Comment by Katydude** [comment]
Who says I left? Man, people on this forum are so snippy. That kind of comment doesn't inspire people to be helpful. All you had to say was, "What items are missing from the framework that you'd like us to consider adding? We'd love the feedback." Sounds like are just looking to make a mountain out of a molehill.
