### ISSUE TITLE
How to update Image on ClientSidePage?

### ISSUE THREAD

**Issue by mstivoi** [pnp/pnpjs#1150]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.0.3 ]

Please specify what version(s) of SharePoint you are targeting: [   Online      ]

### Expected / Desired Behavior / Question
I am trying to update Image Web Part on Client Side Page. I mean image url.
My code was working fine in earlier versions , but not with latest version

```TypeScript
   let control= response.findControlById(field.id);
   let part = ClientsideWebpart.fromComponentDef(imagePartDef);
   part.data.webPartData.serverProcessedContent={imageSources:{imageSource:Url},htmlStrings: 
      {},links:{},searchablePlainTexts:{}};
   part.data.webPartData.properties["imageSource"]=Url;
   part.data.webPartData.properties["fileName"]=FileName;
   control.data.webPartData={...part.data.webPartData};
```

 Currently when page loads i don't see the image , but when press "Edit" button , the picture appeared. 
Publish is not required , image do not disappear after that.
Please let me know what i am doing wrong.

**Comment by patrick-rodgers** [comment]
Has the way that webpart stores its properties changed? Are you getting any errors in the console or anywhere? I am not aware of any changes we made that would affect this code.

**Comment by mstivoi** [comment]
This is OOTB Image Web Part.  

> Has the way that webpart stores its properties changed?

I dont know , i need ask you this question .
No, no errors. 
My code looking tricky , may be there is a legal way for manage Image Web Part ?

**Comment by mstivoi** [comment]
As i may guess , this is environment issue? Any workaround steps possible ?

**Comment by patrick-rodgers** [comment]
If I get the props of the image webpart they look like this:

```JSON
{
  alignment: "Center",
  altText: "",
  captionText: "",
  fileName: "",
  fixAspectRatio: false,
  imageSourceType: 2,
  imgHeight: 1080,
  imgWidth: 1080,
  linkUrl: "",
  listId: "{GUID}",
  overlayText: "",
  siteId: "{GUID}",
  uniqueId: "{GUID}",
  webId: "{GUID}",
};
```

There is no "imageSource" or "fileName" property listed, so perhaps that was in an older version of the web part? Looks like you need to set the siteId, webId, listId, and uniqueId of the image you want to show. And just a heads up you can use the "getProperties" and "setProperties" of the web part as shown [in the example](https://pnp.github.io/pnpjs/sp/clientside-pages/#add-controls) to make things a little easier.

**Comment by patrick-rodgers** [comment]
Going to close this as I believe the question is answered, please open a new issue and ref this one if you are still having problems. Thanks!
