### ISSUE TITLE
Batch updates raise InvalidClientQueryException

### ISSUE THREAD

**Issue by LastGunslinger** [pnp/pnpjs#1151]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     2.0.3    ]

Please specify what version(s) of SharePoint you are targeting: [    SharePoint Online     ]

### Expected / Desired Behavior / Question
Multiple list items should be able to be updated using the batching functionality.

### Observed Behavior
Updating single items individually in a list works as expected, but batch updating on the same list does not. Instead, all attempted batch updates throw an error:

"Error making HttpClient request in queryable [400] Bad Request ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The parameter __metadata does not exist in method GetById."}}}"

### Steps to Reproduce
```javascript
import { sp } from '@pnp/sp'
import '@pnp/sp/webs'
import '@pnp/sp/lists'
import '@pnp/sp/items'

const myList = sp.web.lists.getByTitle('mylist')
const entityTypeFullName = await myList.getListItemEntityTypeFullName()
const updateValues = { Title: 'updated title' }
const itemId = 1

// This line works as expected with no errors
await myList.items.getById(itemId).update(updateValues, '*', entityTypeFullName)

const batch = sp.web.createBatch()
myList.items.getById(itemId).inBatch(batch).update(updateValues, '*', entityTypeFullName)
// This line throws the InvalidClientQueryException error
await batch.execute()
```
Code is being run client-side in an SPFx app. The setup for the app looks like this:

```javascript
import { sp } from '@pnp/sp'

public async onInit() {
    await super.onInit()
    sp.setup({
        spfxContext: this.context,
	ie11: true,
    })
}
```

I'm not sure about the root cause of the issue, but looking at other sources it appears that REST calls can return this error if the 'X-HTTP-Method' header property is not set to MERGE. I have tried to set this manually:
```javascript
const headers = {
    'X-HTTP-Method': 'MERGE',
}

myList.configure({headers})items.getById(itemId).inBatch(batch).update(updateValues, '*', entityTypeFullName)
```
but this also did not seem to work, and I do not see the 'X-HTTP-Method' property in the request headers when I inspect the network call.

**Comment by patrick-rodgers** [comment]
I just confirmed that [the code from the sample](https://pnp.github.io/pnpjs/sp/items/#add-multiple-items) works (updated to perform an update instead of an add) as expected in ie11, edge chromium, and nodejs. I also tried inside and outside SPFx with all things continuing to work. I did these tests with the public code v2.0.3 so wouldn't include any potential work for 2.0.4,

```TypeScript
// only needed for ie11 mode
import "@pnp/polyfill-ie11";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

const list = sp.web.lists.getByTitle("a new list");

const entityTypeFullName = await list.getListItemEntityTypeFullName();

const batch = sp.web.createBatch();

list.items.getById(16).inBatch(batch).update({ Title: "Batch 6 - edited" }, "*", entityTypeFullName).then(b => {
    console.log(b);
});

list.items.getById(17).inBatch(batch).update({ Title: "Batch 7 - edited" }, "*", entityTypeFullName).then(b => {
    console.log(b);
});

await batch.execute();
console.log("Done");
```

And my setup:

```TypeScript
public async onInit(): Promise<void> {

  await super.onInit();

  sp.setup({
    ie11: true,
    spfxContext: this.context,
  });
}
```

Is there any additional information you can provide that would help us reproduce the issue?

**Comment by LastGunslinger** [comment]
I think I figured out what the issue was. I was creating and executing the batches in a loop, and there was a logic error that was causing the batch to be executed more often than it needed to be be. Now that I have fixed the loop, it is working correctly.
