### ISSUE TITLE
Error with SPFetchClient from "@pnp/nodejs" or "@pnp/nodejs-commonjs"

### ISSUE THREAD

**Issue by Harshagracy** [pnp/pnpjs#1157]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [x] Documentation gap/issue

### Version
```
 "dependencies": {
    "@microsoft/sp-core-library": "1.10.0",
    "@microsoft/sp-lodash-subset": "1.10.0",
    "@microsoft/sp-office-ui-fabric-core": "1.10.0",
    "@microsoft/sp-property-pane": "1.10.0",
    "@microsoft/sp-webpart-base": "1.10.0",
    "@pnp/common": "^2.0.3",
    "@pnp/graph": "^2.0.3",
    "@pnp/logging": "^2.0.3",
    "@pnp/nodejs-commonjs": "^2.0.4",
    "@pnp/odata": "^2.0.3",
    "@pnp/polyfill-ie11": "^2.0.1",
    "@pnp/sp": "^2.0.3",
    "@pnp/sp-commonjs": "^2.0.4",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@types/webpack-env": "1.13.1",
    "office-ui-fabric-react": "6.189.2",
    "react": "16.8.5",
    "react-dom": "16.8.5"
  },
  "resolutions": {
    "@types/react": "16.8.8"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "@microsoft/sp-build-web": "1.10.0",
    "@microsoft/sp-module-interfaces": "1.10.0",
    "@microsoft/sp-tslint-rules": "1.10.0",
    "@microsoft/sp-webpart-workbench": "1.10.0",
    "@types/chai": "3.4.34",
    "@types/core-js": "^2.5.3",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "typescript": "^3.8.3"
  }
```

### Expected / Desired Behavior / Question
I am trying to access sharepoint using sharepoint app context using client id, client secret using the below code from this [doc](https://pnp.github.io/pnpjs/nodejs-support/)

```
 public onInit(): Promise<void> {
    return super.onInit().then(_ => {
      sp.setup({
        spfxContext: this.context,
        sp: {
          fetchClientFactory: () => {
            return new SPFetchClient(this.context.pageContext.web.absoluteUrl, 
              "guid",
             "secret",
             SPOAuthEnv.SPO );
          },
        },
      });
    });
  }

```

this is added in the webpart.ts file. I tried even the other example from this [link.](https://pnp.github.io/pnpjs/nodejs/sp-fetch-client/) by importing "@pnp/nodejs";.  But I am getting error with both the examples. 

### Observed Behavior
error on gulp serve
INNERERROR:
Failed to load entry point from component "3768e2ed-eec4-4f76-9a1a-b399bf73671f" (exampleWebPart). Original error: Cannot find module 'net'
CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client/sp-webpart-workbench-assembly_nl-nl_eb4672a382739125c66328f1c1a2a2b4.js:4:53271)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client/sp-webpart-workbench-assembly_nl-nl_eb4672a382739125c66328f1c1a2a2b4.js:20:10687)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-webpart-workbench-assembly_nl-nl_eb4672a382739125c66328f1c1a2a2b4.js:20:53298)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-webpart-workbench-assembly_nl-nl_eb4672a382739125c66328f1c1a2a2b4.js:20:49329)
    at https://spoprod-a.akamaihd.net/files/sp-client/sp-webpart-workbench-assembly_nl-nl_eb4672a382739125c66328f1c1a2a2b4.js:20:42884

### Steps to Reproduce
Create the SPFx project version 1.10
Try both the examples for SPFetchClient
-https://pnp.github.io/pnpjs/nodejs-support/
-https://pnp.github.io/pnpjs/nodejs/sp-fetch-client/

Please help me to connect with SharePoint using add-in app access instead of user access. Also Please let me know which example is correct.

**Comment by koltyakov** [comment]
`@pnp/nodejs` is not obviously compatible with in-browser solutions, it's for server-side usage in Node.js process but not an SPFx bundle.

**Comment by Harshagracy** [comment]
hi @koltyakov 

Thanks for that explanation. But the library I am using is "@pnp/nodejs-commonjs". It should work with that. I have mentioned the error I am getting with that in the question.

**Comment by koltyakov** [comment]
**No, it should not.** It's only for Node.js. You can't use it in the browser as well as to authenticate that way in the browser. That's just not possible by design. For in-browser auth [there are other approaches](https://pnp.github.io/pnpjs/adaljsclient/adalclient/).

**Comment by Harshagracy** [comment]
Hi @koltyakov ,

Thanks for your reply. These approaches seem to work only for azure active directory. I am trying to read/write data from a list using add-in only context instead of the current logged-in user context. Is that possible using PnP JS ?

**Comment by koltyakov** [comment]
> I am trying to read/write data from a list using add-in only context instead of the current logged-in user context. Is that possible using PnP JS ?

It's not about PnPjs. This is **just not possible at all** via client-side only solution. If you need to use a service account/add-in context it should be a web service hosted somewhere, e.g. as an Azure Function, and that web service can authenticate it's backend calls with Add-in Only auth, etc.

**Comment by Harshagracy** [comment]
@koltyakov Thank you so much for explaining it to me patiently :) Let me close this thread.
