### ISSUE TITLE
Property 'me' does not exist on type 'GraphRest'.ts(2339) when using graph

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#1159]
### Category
- [ ] Enhancement
- [ ] Bug
- [ X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.0.4       ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]
I use 
import { graph } from "@pnp/graph";

Then I want to get the same results as the graph explorer
https://graph.microsoft.com/v1.0/me/
`{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
    "businessPhones": [
        "+1 412 555 0109"
    ],
    "displayName": "Megan Bowen",
    "givenName": "Megan",
    "jobTitle": "Auditor",
    "mail": "MeganB@M365x214355.onmicrosoft.com",
    "mobilePhone": null,
    "officeLocation": "12/1110",
    "preferredLanguage": "en-US",
    "surname": "Bowen",
    "userPrincipalName": "MeganB@M365x214355.onmicrosoft.com",
    "id": "48d31887-5fad-4d73-a9f5-3c356e68a038"
}`

so I tried:
`  const me = await graph.me;`
But the liter says: "Property 'me' does not exist on type 'GraphRest'.ts(2339)" 

What will be the equivalent of https://graph.microsoft.com/v1.0/me/ in PNP/JS?

Thank you

**Comment by juliemturner** [comment]
There is a documentation gap there for Users/Me. You need to add an import.

`import "@pnp/graph/users";`

Also, if that is your actual call you're going to want to make sure you invoke it:

`const me = await graph.me();`

**Comment by Ofer-Gal** [comment]
Thank you much. I got it
