### ISSUE TITLE
How to add configuration for UserAgent "NONISV|Contoso|GovernanceCheck/1.0" to avoid throttling limit?

### ISSUE THREAD

**Issue by ahsanranjha** [pnp/pnpjs#1162]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [Lastest]
Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
How to add following configuration to avoid throttling limit. 

```
HttpWebRequest endpointRequest = (HttpWebRequest) HttpWebRequest.Create(sharepointUrl.ToString() + "/_api/web/lists");
endpointRequest.Method = "GET";
endpointRequest.UserAgent = "NONISV|Contoso|GovernanceCheck/1.0";
endpointRequest.Accept = "application/json;odata=nometadata";
endpointRequest.Headers.Add("Authorization", "Bearer " + accessToken);
HttpWebResponse endpointResponse = (HttpWebResponse)endpointRequest.GetResponse();
```

### Observed Behavior
https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

**Comment by patrick-rodgers** [comment]
You haven't provided a ton of detail but adding a custom user agent won't work in the browser. Are you working in nodejs? If so, the library already adds a custom user agent. If you want to override it for all requests you can do the following in your setup:

```TypeScript
import { SPFetchClient } from "@pnp/nodejs";
import { sp } from "@pnp/sp";

// configure your node options
sp.setup({
  sp: {
    fetchClientFactory: () => {
      return new SPFetchClient(settings.testing.sp.url, settings.testing.sp.id, settings.testing.sp.secret);
    },
    headers: {
      "User-Agent": "NONISV|Contoso|GovernanceCheck/1.0",
    },
  },
});
```

**Comment by patrick-rodgers** [comment]
Going to close this as the question appears answered. If you are still stuck please open a new issue and ref this one providing any additional details available. Thanks!
