### ISSUE TITLE
fields missing delete method (V2)

### ISSUE THREAD

**Issue by tavikukko** [pnp/pnpjs#1164]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.4]

Please specify what version(s) of SharePoint you are targeting: [online/onprem]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
executing this deleted field
```typescript
const result = await sp.web.fields.getByTitle("My Field").delete();
```

### Observed Behavior
throws error
```javascript
TypeError: list.fields.getByTitle(...).delete is not a function
```

Seems like the delete method are not implemented in V2
referencing old issue related to this: #803

**Comment by tavikukko** [comment]
tested with SP Editor and with just a simple delete call removed the field, so the rest api is available.

```typescript
import { SPHttpClient } from "@pnp/sp";

(async () => {

  const client = new SPHttpClient()
  await client.delete(`https://tenant.sharepoint.com/sites/sitecollection/_api/web/lists/getbytitle('testlist')/fields/getbytitle('testcolumn')`)

})().catch(console.log)
```

**Comment by juliemturner** [comment]
Ok, we'll investigate.
