### ISSUE TITLE
Copy bannerImageUrl from another file

### ISSUE THREAD

**Issue by thenail** [pnp/pnpjs#1167]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Expected / Desired Behavior / Question
It would be nice to copy bannerImageUrl from another file (i.e. a template), currently when setting bannerImageUrl it uses getFileByServerRelativePath to get the image but it doesn't seems to work that well with _layouts/15/getpreview.ashx from the bannerImage url of the other file.

**Comment by patrick-rodgers** [comment]
Ok, we can have a look at this, unsure exactly what is needed. Can you provide some details on the use case to ensure we know what you are trying to do and they what we might offer meets those needs?

**Comment by thenail** [comment]
I'm trying to reproduce the standard behavior of creating a page from template, I'm using copyPage but that only includes the canvas. PageLayout, bannerImageUrl and bannerImageSourceType needs to be copied from the template afterwards. PageLayout and bannerImageSourceType works fine by just assigning but when doing the same for bannerImageUrl the saves causing error.

**Comment by patrick-rodgers** [comment]
Added support into copy to ensure the banner image is set from the source to the copy. As well the PageLayout seems to already be working in my tests. Will go out in the 2.0.5 release.
