### ISSUE TITLE
Property 'details' does not exist on type 'ITask' with NodeJS

### ISSUE THREAD

**Issue by dfector** [pnp/pnpjs#1170]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.4]

Please specify what version(s) of SharePoint you are targeting: [???]

### Expected / Desired Behavior / Question
From the documentation, this is the way to grab planner task details... 
```
const taskDetails = await graph.planner.tasks.getById('taskId').details.get();
```

### Observed Behavior
Compilation error...
```
test.ts:32:62 - error TS2339: Property 'details' does not exist on type 'ITask'.
```

**Comment by patrick-rodgers** [comment]
We'll have a look, thanks for letting us know.

**Comment by Steven-Chorkawy** [comment]
I'm also experiencing this problem.
