### ISSUE TITLE
ReferenceError: sessionStorage is not defined     at PnPClientStorage.get [as session]

### ISSUE THREAD

**Issue by mplwork** [pnp/pnpjs#1171]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.0.4   ]

Please specify what version(s) of SharePoint you are targeting: [ online  ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I am converting a nodejs app from V1 to V2 for which I did these changes to my code:
```
diff --git a/sp/simple-sp-client.js b/sp/simple-sp-client.js
index 79b0867..befc1ae 100644
--- a/sp/simple-sp-client.js
+++ b/sp/simple-sp-client.js
@@ -1,6 +1,6 @@
 const { SpClient } = require("./sp-client");

-const { Web } = require("@pnp/sp");
+const { Web } = require("@pnp/sp-commonjs/presets/all");
 const { xml2json } = require("xml-js");

 class SimpleSpClient extends SpClient {
diff --git a/sp/sp-client.js b/sp/sp-client.js
index cfca4e5..c5b530d 100644
--- a/sp/sp-client.js
+++ b/sp/sp-client.js
@@ -1,5 +1,5 @@
-const { BearerTokenFetchClient} = require("@pnp/nodejs");
-const { sp, PrincipalType, PrincipalSource } = require("@pnp/sp");
+const { BearerTokenFetchClient} = require("@pnp/nodejs-commonjs");
+const { sp, PrincipalType, PrincipalSource } = require("@pnp/sp-commonjs/presets/all");

 class SpClient {
     constructor(token, sharepoint) {

```

The app starts fine but fails in this call:
```
       const fields = await this.spClient.web.lists.getByTitle(this.spList)
            .fields
            .filter(filter)
            .usingCaching().get();
```

What did I do wrong?

### Observed Behavior
```
Exception has occurred: ReferenceError
ReferenceError: sessionStorage is not defined
    at PnPClientStorage.get [as session] (c:\MyBot\node_modules\@pnp\common-commonjs\storage.js:245:62)
    at CachingOptions.get [as store] (c:\MyBot\node_modules\@pnp\odata-commonjs\caching.js:18:47)
    at c:\MyBot\node_modules\@pnp\odata-commonjs\pipeline.js:117:34
    at new Promise (<anonymous>)
    at Function.PipelineMethods.caching (c:\MyBot\node_modules\@pnp\odata-commonjs\pipeline.js:108:16)
    at descriptor.value (c:\MyBot\node_modules\@pnp\odata-commonjs\pipeline.js:80:27)
    at next (c:\MyBot\node_modules\@pnp\odata-commonjs\pipeline.js:37:48)
    at c:\MyBot\node_modules\@pnp\odata-commonjs\pipeline.js:80:76
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
### Steps to Reproduce
Do the above changes to the nodejs app and run it.

**Comment by patrick-rodgers** [comment]
There is no session storage in node but looks like we are missing a check that must have been there previously. We'll have a look, thanks for letting us know.

**Comment by patrick-rodgers** [comment]
Yep, definitely a bug. Got it fixed and will go out in the next release.
