### ISSUE TITLE
add file whose name have long chinese characters 

### ISSUE THREAD

**Issue by justin0522** [pnp/pnpjs#1174]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version 

Please specify what version of the library you are using: [ 2.0.3 ]

Please specify what version(s) of SharePoint you are targeting: [ sharepoint online  ]

### Expected / Desired Behavior / Question
add file successfully

### Observed Behavior
failed to upload file, error message:
The length of the URL for this request exceeds the configured maxUrlLength value.

### Steps to Reproduce
const fileName = "你好你好......"; // 200 characters 
await sp.web.getFolderById(folderId).files.add(fileName, "hello world", true);

### Submission Guidelines
https://sharepoint.stackexchange.com/questions/125737/the-length-of-the-url-for-this-request-exceeds-the-configured-maxurllength-value/156784#156784

**Comment by patrick-rodgers** [comment]
You can use the [existing capability to alias arguments](https://pnp.github.io/pnpjs/sp/alias-parameters/). Does that help you here?

**Comment by justin0522** [comment]
thank you very much, it work well.
