### ISSUE TITLE
Cannot read property 'RelevantResults' of null at SearchResults.get

### ISSUE THREAD

**Issue by sandeepvootoori** [pnp/pnpjs#1176]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.4]

Please specify what version(s) of SharePoint you are targeting: [SPO]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

Hello,
I am using pnp js to get data from search result source but the totalrows shows the below error "TypeError: Cannot read property 'RelevantResults' of null at SearchResults.get" when there are no rows returned instead of showing 0

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

const _searchQuerySettings: ISearchQuery = {
                TrimDuplicates: false,
                RowLimit: pageSize,
                RefinementFilters:["ContentType:Document"],
                SourceId:resultsourceid,
                SelectProperties:["ContentType","ServerRedirectedURL","RefinableString02", "RefinableString00", "RefinableString01","DefaultEncodingURL","FileExtension","Filename","LastModifiedTime"],
                SortList:
                [
                  {
                    Property: 'LastModifiedTime',
                    Direction: SortDirection.Descending
                  }
                ]                
            };

            let q3 = SearchQueryBuilder("", _searchQuerySettings).enableQueryRules;
### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!

**Comment by juliemturner** [comment]
I've never done a search without a query, did you leave the SEARCH STRING empty on purpose?

`let q3 = SearchQueryBuilder("**{SEARCH STRING}**", _searchQuerySettings).enableQueryRules;`

And then I don't see the rest of the call so I'm not sure how to answer, do you have a call to execute the search? 

`const results = await sp.search(q3);`

**Comment by SV932** [comment]
Search String was left empty on purpose.

I do have the call to execute search and below is the full code with search call

 `const _searchQuerySettings: ISearchQuery = {
                TrimDuplicates: false,
                RowLimit: pageSize,
                RefinementFilters:["ContentType:Document"],
                SourceId:resultsourceid,
                SelectProperties:["ContentType","ServerRedirectedURL","RefinableString02", "RefinableString00","RefinableString01","DefaultEncodingURL","FileExtension","Filename","LastModifiedTime"],
                SortList:
                [
                  {
                    Property: 'LastModifiedTime',
                    Direction: SortDirection.Descending
                  }
                ]                
            };

            let q3 = SearchQueryBuilder("", _searchQuerySettings).enableQueryRules;
            const results2: SearchResults = await sp.search(q3);`

**Comment by juliemturner** [comment]
Ok, so you're telling me the value of restuls2 is undefined or null? If that's the case could you validate that if you simplify your call it still doesn't work... i.e. 

`let q3 = SearchQueryBuilder("")`

And then work up from there so we can isolate where your issue is, we believe this endpoint is working properly so if you could please isolate your specific problem.

**Comment by sandeepvootoori** [comment]
@juliemturner - results2 is not null but when there are no results i expect that TotalRows property will show 0 instead of the error. Please see the attached screenshot
![image](https://user-images.githubusercontent.com/40895430/80389032-983fea00-8878-11ea-9d44-a65f32321ec4.png)

**Comment by patrick-rodgers** [comment]
I had a look and fixed this. We were not checking to ensure results existed before accessing them. What is amazing is this is the first time someone reported it. Anyway, it is fixed now and will be part of the next release. Thanks!

**Comment by sandeepvootoori** [comment]
@patrick-rodgers  - Thank you :)
