### ISSUE TITLE
can i use this library into a close source commercial project?

### ISSUE THREAD

**Issue by quantrpeter** [pnp/pnpjs#1177]
Hi
  can i use this library into a close source commercial project?
Thanks
From Peter

**Comment by koltyakov** [comment]
Please check [License](https://github.com/pnp/pnpjs/blob/version-2/LICENSE) conditions. Long story short, yes, MIT allows this.

**Comment by patrick-rodgers** [comment]
As @koltyakov says the license permits this, but for such questions you should always consult with your legal staff to ensure everything is in order.

**Comment by koltyakov** [comment]
The fact which might help is most of the popular open-sourced libraries and frameworks have the same license, MIT. React, Angular, to name a few. So if the product assumes using these (or literally any open-source library), adding PnPjs with the same exact license is the identical case. MIT as well as some other licenses, e.g. BSD, Apache 2, are really friendly and don't limit the usage as some others, e.g. GPL.

**Comment by patrick-rodgers** [comment]
Going to go ahead and close this as answered. If you have further questions please open a new issue and ref this one. Thanks!
