### ISSUE TITLE
SharePoint - Can't filter with substringof on "Person or Group" column type 

### ISSUE THREAD

**Issue by aakash15patel** [pnp/pnpjs#1178]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of SharePoint you are targeting: [         ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thank you for your feedback!

**Comment by aakash15patel** [comment]
![Filter](https://user-images.githubusercontent.com/64275759/80402341-65e7ba00-8883-11ea-8891-044b47ddfa36.PNG)

**Comment by koltyakov** [comment]
Assumably, if you're getting threshold error the lookup list (UIL in case of People Picker) contains more than 5000 items.

In my knowledge, `substringof()` only can be used together with `string` data type, not the lookup. At least without expanding a string value.

Can confirm that with expanded string value `substringof()` works in REST:

![image](https://user-images.githubusercontent.com/7816483/80407918-0ca57800-88cf-11ea-8610-12284f993060.png)

With large lists, indexing columns should be used and getting data via Search API or ahead of time preparation.

**Comment by aakash15patel** [comment]
@koltyakov - Thank you for your response. Yes, as I've more then 5K records in the list, thus I can't filter People Picker column. 

- But I have found alternative approach for it - i.e. First I'm querying **"UserInformationList"**, and I'll get ID's for the user using **'substringof' filter** on Title. Then I'll be filtering the People picker column based on ID using **'eq' filter.** 

- I havn't tried using SearchAPI. Let me try that too.
