### ISSUE TITLE
PnP Search doesn't work in SPFx webpart hosted on modern page

### ISSUE THREAD

**Issue by sandeepvootoori** [pnp/pnpjs#1179]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.4]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Observed Behavior

I am using  PNP Search Command as below in a SPFx Webpart and for some reason this doesn't work on the modern pages.
```
const _searchQuerySettings: ISearchQuery = {
               TrimDuplicates: false,
               RowLimit: pageSize,
               RefinementFilters:["ContentType:Document"],
               SourceId:resultsourceid,
               SelectProperties:["ContentType","ServerRedirectedURL","RefinableString02", "RefinableString00","RefinableString01","DefaultEncodingURL","FileExtension","Filename","LastModifiedTime"],
               SortList:
               [
                 {
                   Property: 'LastModifiedTime',
                   Direction: SortDirection.Descending
                 }
               ]                
           };
           let q3 = SearchQueryBuilder("", _searchQuerySettings).enableQueryRules;
           const results2: SearchResults = await sp.search(q3);
```

I have done some investigation and it looks like in modern pages call is being made to 
{Site}/Sitepages/_api/search/postquery which in turn is causing 404 but in classic pages its being made to {Site}/_api/search/postquery.
![image](https://user-images.githubusercontent.com/40895430/80417635-0f3ea800-88a4-11ea-85c0-5a558b20cf3e.png)
![image](https://user-images.githubusercontent.com/40895430/80417863-778d8980-88a4-11ea-89c5-df5a5ebbc1fd.png)
Please let me know if I am doing something wrong

### Steps to Reproduce

- Create a React SPFx webpart
- Use PnP Search 
- Add webpart to a classic SharePoint page and it should work as expected
- Add webpart to a modern SharePoint page and it doesn't work as expected

**Comment by juliemturner** [comment]
This seems like a duplicate of the issue you reported earlier: #1176?

**Comment by koltyakov** [comment]
Obviously, SPFx context is not established. Please see more: https://pnp.github.io/pnpjs/getting-started/#establish-context

**Comment by sandeepvootoori** [comment]
@juliemturner This is different.

@koltyakov  - I will try by setting up SPFx context, Thank you !

**Comment by sandeepvootoori** [comment]
Setting up PnPContext resolved this, Thanks @koltyakov
