### ISSUE TITLE
@pnp/sp-taxonomy : Select not working

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/pnpjs#118]
const store: ITermStore = await taxonomy.termStores.getByName("Taxonomy_nDD4UWOngbVo1QUTBEs7gg==");
    const terms3: ITerms = store.getTermSetById("9cf36824-ca35-420c-ba10-62f74e7b0641").terms;
// when i m trying to get information of specific columns , it doesnt work ?
```
    terms3.select("Id,IsRoot").get().then((data1)=>{
console.log(data1);
    })

//this works 
    terms3.get().then((data)=>{
      console.log(data);
    })
   
```

**Comment by koltyakov** [comment]
Please use `.select("Id", "IsRoot")` for now instead of `.select("Id,IsRoot")`.

**Comment by harshdamaniahd** [comment]
Thanks
