### ISSUE TITLE
Error - typescript - node_modules/@pnp/sp/appcatalog/types.d.ts(29,33): error TS1110: Type expected.

### ISSUE THREAD

**Issue by Gennady-G** [pnp/pnpjs#1180]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  pnp v.2 (I suppose..)]
![versions-2020-04-28_173127](https://user-images.githubusercontent.com/5569346/80493387-62812b00-8976-11ea-8fac-53db25b43303.png)

Please specify what version(s) of SharePoint you are targeting: [ 2019 on-premise and Online, webpart ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Successfull bundle expected

### Observed Behavior
> [17:14:14] Error - typescript - node_modules\@pnp\sp\appcatalog\types.d.ts(29,33): error TS1110: Type expected.
> [17:14:14] Error - typescript - node_modules\@pnp\sp\appcatalog\types.d.ts(29,98): error TS1005: '(' expected.
> [17:14:14] Error - typescript - node_modules\@pnp\sp\appcatalog\types.d.ts(65,26): error TS1110: Type expected.

![err-2020-04-28_171931](https://user-images.githubusercontent.com/5569346/80491953-6f048400-8974-11ea-90e6-6624d8e7f21d.png)

### Steps to Reproduce
1) make webpart targeted to 2019+Online, 
2) install pnp:
> npm install @pnp/logging @pnp/common @pnp/odata @pnp/sp --save
3) write in Your code 
`import { sp } from "@pnp/sp/presets/all";`
4) gulp bundle

package.json:
https://gist.github.com/Gennady-G/4940ad39a0c74249b0fec194629d7e29

maybe related with:
https://github.com/pnp/pnpjs/issues/978

**Comment by koltyakov** [comment]
This is tricky, it looks that the version of the build tools shipped with SPFx which targeted for SP2019 doesn't respect `skipLibCheck` option. This should theoretically lead to the similar issues when using any dependency with which the old version of SPFx's build tools and related dependencies, TypeScript in particular, are not happy with.

Not sure if we can be anything on our end to fix this. As this is not the bug to have an up to date toolchains.

I tried a couple of options with `tsconfig.json` in SPFx v1.4 project, such as `exclude` option and legacy `skipDefaultLibCheck` but nothing worked for me as well. Only bumping TypeScript to the recent version in a hacky way in `package-lock.json` worked, which I can't suggest as a solution as there are potential side effects and fragility. 

Currently puzzled if this can be resolved at all.

**Comment by juliemturner** [comment]
I haven't anything to add to what @koltyakov mentioned here other than just a general usage point that changed from v1 to v2, you don't need to import common, odata, etc anymore, just the sp library.

`npm install @pnp/sp --save`

**Comment by Gennady-G** [comment]
Thank You much for answers!

As I said in related thread, I can resolve with this workaround:

> npm install @pnp/sp@1.3.8 @pnp/odata@1.3.8 @pnp/logging@1.3.8 @pnp/common@1.3.8 

Thanks to @patrick-rodgers https://github.com/pnp/pnpjs/issues/983#issuecomment-569959137

So if I understand You correctly - for 2019 I can use old versions, but in O365, in "modern toolchain" it works well..

I develop in on-prem and then upload solutions to O365, it is Ok for me.

Best regards, Gennady

**Comment by josemvalente** [comment]
Hi @Gennady-G ,

setting the pnp/sp version to 1.3.8 solver the typescript error, 
but introduces the following:
Error - typescript - src\extensions\helloWorld\HelloWorldCommandSet.ts(17,19): error TS2307: Cannot find module '@pnp/sp/presets/all'.

Did you experience the same error? if so how did you managed?



Best regards,
Jose Valente

**Comment by koltyakov** [comment]
In v1 there was no concept of partial imports and presets. So, with v1 (1.3.11 is the latest from v1 branch, btw) it should be an import from '@pnp/sp' but not '@pnp/sp/presets/all'.

**Comment by Gennady-G** [comment]
Hi @koltyakov !
yes, exactly, used 

> import { sp } from "@pnp/sp";
instead

**Comment by josemvalente** [comment]
Hi,

thanks for the quick reply guys, solved :)

**Comment by koltyakov** [comment]
I hate to say that this is a solution. But likely with SPFx for On-Prem until the version of the build tools is bumped in there, we can only recommend sticking with v1 due to the nuances spotlighted in the thread.

**Comment by josemvalente** [comment]
Hi again,

did you manage to read "xlsx" files?

**Comment by patrick-rodgers** [comment]
Going to close this one as it is answered as best we can. If there are updates on this front that change things we will be sure to let folks know. Thanks!

**Comment by narendotnet** [comment]
Hi everyone, after done with this import { sp } from "@pnp/sp"; I'm still getting the issues like below 

let web = Web(this.context.pageContext.web.absoluteUrl);

Please suggestions and I'm new to spfx and sharepoint web part

thanks
