### ISSUE TITLE
How to update the RelationshipDeleteBehavior property of a lookup field

### ISSUE THREAD

**Issue by waldekmastykarz** [pnp/pnpjs#1187]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 2.0.4

Please specify what version(s) of SharePoint you are targeting: SPO

### Expected / Desired Behavior / Question

How can you update the value of the RelationshipDeleteBehavior property on a lookup field using PnPjs?

Using the following code:

```ts
const change = {RelationshipDeleteBehavior: 1};
sp.web
  .lists.getById(listGuid)
  .fields.getById(fieldGuid)
  .update(change);
```

fails with the following error:

```text
The property 'RelationshipDeleteBehavior' does not exist on type 'SP.Field'. Make sure to only use property names that are defined by the type.
```

So far I wasn't able to find any reference to the RelationshipDeleteBehavior property in the repo or docs but perhaps there is another way to apply a change to a lookup field that I'm missing.

For the reference, the following REST request works as expected:

```text
POST .../_api/web/lists('listGuid')/fields('fieldGuid')
accept: application/json
content-type: application/json
IF-MATCH: *
X-HTTP-Method: MERGE

{"@odata.type":"#SP.FieldLookup","Indexed":true,"RelationshipDeleteBehavior":1}
```

**Comment by patrick-rodgers** [comment]
For fields you need to specify the field type on update which is the second parameter. I just saw that the docs don't mention this so need to update that. Your example would be:

```TypeScript
const change = {RelationshipDeleteBehavior: 1};
sp.web
  .lists.getById(listGuid)
  .fields.getById(fieldGuid)
  .update(change, "SP.FieldLookup");
```

That is how to do it today. We could make a request for the type and just set it for folks which might be easier. Originally we didn't because of the extra call for all updates. Best might be to leave the param so it isn't a breaking change but make it optional. If undefined we do a lookup for the type and use that.

**Comment by waldekmastykarz** [comment]
Thank you for the explanation. The reasoning makes sense. Using the field type is good enough for now and it unblocks me. Thanks for your help! 👍

**Comment by patrick-rodgers** [comment]
Made this change will go out in the next version.

**Comment by gitbrent** [comment]
@patrick-rodgers - this issue persists in v2.0.5

![2020-06-03 11_15_19-package json - spfx-toolkit - Visual Studio Code](https://user-images.githubusercontent.com/7218970/83661484-d329f180-a58b-11ea-8ff2-afb97ecf3319.png)

![2020-06-03 11_16_00-● DapDelete tsx - spfx-toolkit - Visual Studio Code](https://user-images.githubusercontent.com/7218970/83661490-d624e200-a58b-11ea-8140-42eae7317c3c.png)
