### ISSUE TITLE
Creating role definitions fails with error: 'Cannot convert a primitive value to the expected type 'Edm.Int64''

### ISSUE THREAD

**Issue by waldekmastykarz** [pnp/pnpjs#1188]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 2.0.4

Please specify what version(s) of SharePoint you are targeting: SPO

### Expected / Desired Behavior / Question

Creating role works

### Observed Behavior

Creating role fails with the following error:

```text
Cannot convert a primitive value to the expected type 'Edm.Int64'. See the inner exception for more details.
```

### Steps to Reproduce

```ts
const high = "432";
const low = "1011031039";
sp.web
  .roleDefinitions.add(roleTitle, '', 255, {
    High: Number(high),
    Low: Number(low)
  });
```

The following request works as expected:

```text
POST .../_api/web/roledefinitions
content-type: application/json;IEEE754Compatible=true

{"@odata.type":"#SP.RoleDefinition","Name":"Change Request Team","BasePermissions":{"High":"432","Low":"1011031039"}}
```

**Comment by koltyakov** [comment]
Interesting, thanks @waldekmastykarz, looks that it's better to pass base permissions' low/high as strings. E.g. if to force them as strings no error from the API:

```typescript
const high = "432";
const low = "1011031039";
sp.web
  .roleDefinitions.add('Test 001', '', 255, {
    High: high,
    Low: low
  } as any);
```
