### ISSUE TITLE
Error: Property 'delete' does not exist on type 'IField'

### ISSUE THREAD

**Issue by waldekmastykarz** [pnp/pnpjs#1189]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 2.0.4

Please specify what version(s) of SharePoint you are targeting: SPO

### Expected / Desired Behavior / Question

According to the [docs](https://pnp.github.io/pnpjs/sp/fields/#delete-a-field) you should be able to call `delete()` on a field, like:

```ts
await sp.web.lists.getByTitle("My List").fields.getByTitle("My Field").delete();
```

### Observed Behavior

When trying to call `delete()` on a field, you get the following TypeScript error:

```text
Property 'delete' does not exist on type 'IField'
```

### Steps to Reproduce

```ts
import { sp } from "@pnp/sp/presets/all";
await sp.web.lists.getByTitle("My List").fields.getByTitle("My Field").delete();
```

Including

```ts
import "@pnp/sp/webs";
import "@pnp/sp/fields";
```

doesn't help either

**Comment by koltyakov** [comment]
Thank you! This is a duplicate https://github.com/pnp/pnpjs/issues/1164, the fix was already merged and will be published next release.

**Comment by waldekmastykarz** [comment]
Ah sorry, missed that. Great to hear that it's been already fixed! ❤️
