### ISSUE TITLE
Unable to access parent of term  : @pnp/taxonomy

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/pnpjs#119]
## I am trying to access parent of a term , but it doesnot work ?
parsers.ts:46 Uncaught (in promise) Error: {"ErrorMessage":"Field or property \"Parent\" does not exist.","ErrorValue":null,"TraceCorrelationId":"97da6c9e-800b-5000-cea4-1abc552e9906","ErrorCode":-1,"ErrorTypeName":"Microsoft.SharePoint.Client.InvalidClientQueryException"}
    at parsers.ts:46
```
// load the data into the terms instances
const termsWithData = set.terms.get();
console.log(termsWithData);
termsWithData.then((data)=>{
  const a = data[0].Id.split("(")[1].split(")")[0];
  var t = data[0].parent.get().then((f)=>{
    console.log(f.Name + f.Id)
    
  });
  
})


  }
```

**Comment by tocnr** [comment]
I was just trying to do something pretty similar and was receiving the same error. 

I’m trying to figure out the easiest way to build up the term set hierarchy.

**Comment by harshdamaniahd** [comment]
Yes actually, so if the hierarchy is A-B-C-D
Where D is child of C and C is child of B and B is child of A and A is parent
In this way from last child D I need to traverse up getting the parent of each term.
Let me know if anything works?

**Comment by harshdamaniahd** [comment]
In the console , i get this 
![image](https://user-images.githubusercontent.com/11780473/40870197-f28e5a32-6647-11e8-99a0-2a4b3ca00bac.png)

**Comment by harshdamaniahd** [comment]
I can get path, but I don't get the guid.
You can download the API and try..it doesn't work

**Comment by fthorild** [comment]
Oh i see now, well my suggestion would be to skip the parent property and instead "calculate" the tree based on the other property, PathOfTerm. With a big tree performance could be an issue with the extra calls.

I found another solution also using PathOfTerm, should be possible to re-implement based on either of those two:

https://www.agates.io/loading-terms-as-a-tree-from-sharepoint-online.html

**Comment by fthorild** [comment]
...but I would also expect to get the ID from how you did it no question about that...

**Comment by koltyakov** [comment]
Hey guys,

One can get a Parent term in a single call like this:

```typescript
const terms = await set.terms.select('Id', 'Name', 'Parent').get();
```

All other required props can be provided in `.select`.

Currently, IFAIK, selectable props can't contain sub props, like 'Parent.Id'. Or I might be wrong and @patrick-rodgers may correct me.

Having a term Id, it's parent can be requested with:

```typescript
const parentTerm = await store.getTermById('3dbb2701-3c8b-42e9-9cdd-6a7cc5d877f1').parent.get();
```

Hope this helps.

**Comment by harshdamaniahd** [comment]
Thanks @koltyakov let me try and get back to you soon.
And appreciate the reply

**Comment by fthorild** [comment]
@koltyakov thanks for pointing out it was possible in a single call - in that case it makes more sense to go with parent id rather than path - cool, thanks!

**Comment by patrick-rodgers** [comment]
Thanks all, going to close this as answered. If you have additional questions on this topic please _reopen_ the thread. Thanks!
