### ISSUE TITLE
@pnp/sp/attachments - Issue with examples from the docs

### ISSUE THREAD

**Issue by marwankhalili** [pnp/pnpjs#1194]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.5 ]

Please specify what version(s) of SharePoint you are targeting: [ SPO ]

### Question

It seems like the documentation examples are incorrect/outdated for the @pnp/sp/attachments module. 

E.g. the following code from the documentation does not work for me:

```TypeScript
import { sp } from "@pnp/sp";
import { IItem } from "@pnp/sp/items/types";
import "@pnp/sp/webs";
import "@pnp/sp/lists/web";
import "@pnp/sp/items";
import "@pnp/sp/attachments";

const item: IItem = await sp.web.lists.getByTitle("MyList").items.getById(1)();
const text = await item.attachmentFiles.getByName("file.txt").getText();
``` 

However, replacing the last two lines with this works:

```TypeScript
const text = await sp.web.lists
    .getByTitle("MyList")
    .items.getById(1)
    .attachmentFiles.getByName("file.txt")
    .getText();
```

I haven't double checked but I think all of the examples in the documentation that are using the `attachmentFiles` property have the same issue.

**Comment by jscedunn1** [comment]
Do you have a full example of a webpart that selected attachments and submits it?

**Comment by juliemturner** [comment]
No, sorry I don't

**Comment by jscedunn1** [comment]
Do you have the full example that I could reference?

😊

**Comment by juliemturner** [comment]
I'm sorry, as I said I do not have an example to share with you. I will investigate it further when I have time and update the documentation appropriately.
