### ISSUE TITLE
pnpjs and jest / enzyme tests

### ISSUE THREAD

**Issue by Link631** [pnp/pnpjs#1199]
### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Hello,

when I am reference pnpjs in my react typescript project, I am not able to run my tests anymore.

The Typescript does not get compiled. A thread about that can be found here: 
https://github.com/pnp/pnpjs/issues/1058

My Question:
Is it a valid solution to use @pnp/common instead of pnpjs?
When I reference @pnp/common then my tests are running fine and the code also works.

What is the exact difference between pnpcommon and pnpjs? Is it just a subset of pnpjs functionalities or is it a copy of functionalities? 

Thanks :-)

**Comment by juliemturner** [comment]
@patrick-rodgers mentioned in the thread you pointed to that he doesn't know jest. I also know nothing about jest so I'm probably still not going to be able to help you.  I can tell you that some of your terminology is confusing... pnpjs is a package all on it's own that is a bundle of everything that we maintain for posterity but isn't something that should be used.  What I did notice in the thread you pointed to is that you're package.json is importing the way we did for version 1.  For version 2 you only need to import "@pnp/sp" which has references to all the packages it needs. Have zero idea if that means anything to your project but thought you should know. To try and answer one of your questions, no @pnp/common is not the same as @pnp/sp or pnpjs.  The common package has a set of commonly used functions that many of the other packages reuse, sort of like it's name implies.

As to this question
> Is it a valid solution to use @pnp/common instead of pnpjs
I can't really say as I don't really know what that means.

Really sorry we can't be more helpful but without really knowing jest and having worked with it we really don't have a lot to go on.

**Comment by Link631** [comment]
Sorry for the confusing terminology.

With using pnp common I meant exaclty:

Is it valid to write imports like so
import { sp,..... } from "@pnp/sp-commonjs";

instead of 

import { sp, .... } from "@pnp/sp";

While using the way as it was in version 1, the jest tests are running fine. 

As far as I understood @pnp/sp references all packages but we are still able to import sp from @pnp/sp-commonjs

**Comment by juliemturner** [comment]
Well... that's a huge difference! @pnp/sp-commonjs != @pnp/common.  

Yes, the commonjs libraries were built to use with nodejs (because nodejs doesn't play well with es modules) - https://pnp.github.io/pnpjs/nodejs-support/.  

If you've managed to coordinate everything I don't personally know of any reason that you can't use the commonjs modules vs the es modules.

**Comment by Link631** [comment]
Thanks, that reply is very useful. I will close this question.
