### ISSUE TITLE
How to filter column value using 'ne' operator 

### ISSUE THREAD

**Issue by harishtiwari27** [pnp/pnpjs#1202]
Hello,
In below code filter work fine with 'eq' operator but does not work with 'ne'.
 sp.web.lists.getByTitle("List Title").items
.select("Id,RequesterNameId,Requester_x0020_Location,Status,ExtensionNumber,Mobile_x0020_Number,Request_x0020_Title,Details,TargetDate,RequesterName/Title,Service_x0020_Request/Title,Service_x0020_Request/EmailID,Service_x0020_Request/CCEmailID")
      .expand("RequesterName,Service_x0020_Request/Title")
     **.filter(`Status ne 'Closed'`)**
      .get().then((items: any) => {
        this.setState({
          items: items
        });
      });

Thanks, 
Harishchandra

**Comment by koltyakov** [comment]
You're omitting catch and error handling if not it would say some details what's possibly wrong in a final request and response from the API. The Not equal filter operator is `ne`, as you mentioned, `.filter('SomeField ne "Value"')`.

**Comment by harishtiwari27** [comment]
Hello @koltyakov ,
Thanks for your quick response. 

When I was changeing code .filter(`Status eq 'Closed'`) to  .filter(`Status ne 'Closed'`). 
There were some null and empty value due to this I was facing issues. Found relevant error after closing browser and restart _gulp serve_ command. Now It's working fine

Thanks,
Harishchandra
