### ISSUE TITLE
Retrieving items from a list folder  and update them using PNPjs

### ISSUE THREAD

**Issue by NethraKonkamurthy** [pnp/pnpjs#1206]
We have a list with user specific folders and items inside each folder. 
I am facing issue while trying to fetch the list item from folder and to update it using pnp js code. 

```
const userList = sp.web.lists.getByTitle('listname');
const userFolders = await userList.items.filter("FSObjType eq 1 and Title eq " + this.state.userName)
                                  .get().then((folders)=>{folder[0].Id}) /*Unable to update the item here*/
```

How can I update item inside a list folder using PnpJS.

Thanks,
Nethra

**Comment by koltyakov** [comment]
Operations with items located in folders are no different from the same with items in a root folder.

Update an item nomatter a folder it's located in: `.getById(1).update({ ... })`, etc. See more in [docs](https://pnp.github.io/pnpjs/sp/items/).

These threads have some samples for fetting items in a folder:
- https://github.com/pnp/pnpjs/issues/890
- https://github.com/pnp/pnpjs/issues/473

**Comment by NethraKonkamurthy** [comment]
Thank you, that worked!
