### ISSUE TITLE
Special characters (& = +) URL encoding in .filter() function

### ISSUE THREAD

**Issue by toblum** [pnp/pnpjs#1208]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [ 2.0.5 ]

Please specify what version(s) of SharePoint you are targeting: [ Online ]

### Expected / Desired Behavior / Question
A file or page may have the name "Test & = + Test.aspx" in SharePoint. This may not be a good idea, but is allowed. If querying the list with PnP.js I should be able to use a filter like this:
```
import { sp } from "@pnp/sp/presets/all";
(async () => { 
  const listItems = await sp.web.lists.getByTitle("Site Pages")
			.items
			.filter(`FileRef eq '/sites/example/SitePages/Test & = + Test.aspx'`)
			.get();
  console.log("Listitems found: ", listItems.length);
})().catch(console.log)
``` 

### Observed Behavior
This results in a query that looks like:
https://contoso.sharepoint.com/sites/example/_api/web/lists/getByTitle('Site%20Pages')/items?$filter=FileRef%20eq%20%27/sites/example/SitePages/Test%20&%20=%20+%20Test.aspx%27

This results in a HTTP 400 InvalidQueryException `"message":{"lang":"de-DE","value":"Der Ausdruck \"FileRef eq '/sites/example/SitePages/Test \" ist ung\u00fcltig."}}}` because the & indicates the end of the query parameter.
The problematic characters & + and = are not urlencoded and may lead to query errors. Other special characters like spaces and umlauts are urlencoded correctly. 

I tried to perform url encoding on my own like this:
```
...
.filter(`FileRef eq '${encodeURIComponent('/sites/example/SitePages/Test & = + Test.aspx')}'`)
...
```
But then characters like spaces are encoded twice: %2520 instead of %20. That also leads to errors.

It looks to me that in pnpjs the encodeURI() function is used instead of encodeURIComponent(). Unfortunately I didn't find the code piece where this happens to dig deeper.

### Steps to Reproduce
Try out the above example code.

Thank you for your support!
Tobias

**Comment by patrick-rodgers** [comment]
This is exactly why I was so reluctant to place encoding logic inside the library. We can have a look but this will likely be lower priority as it appears to be an issue with a test case. Thanks for letting us know.

**Comment by toblum** [comment]
Hi Patrick,

thank you for the feedback. I was also surprised that there is encoding done in the library. I didn't expect that. But in the end I think it helps more users than it hurts.

BTW: This was a real-world use case, where we stumbled over this.

Best regards
Tobias
