### ISSUE TITLE
Cannot read property 'toUrl' of undefined when working with Web

### ISSUE THREAD

**Issue by AJIXuMuK** [pnp/pnpjs#1215]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.5]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
no errors when working with manually created `Web` Object.

### Observed Behavior
`Cannot read property 'toUrl' of undefined`

### Steps to Reproduce
```typescript
const web = Web(webUrl);
await web.select('Title', 'Url').get();
const subwebs = await web.getSubwebsFilteredForCurrentUser().get(); // this one fails
```

OR

```typescript
const web = Web(webUrl);
const subwebs = await web.getSubwebsFilteredForCurrentUser().get();
await web.select('Title', 'Url').get(); // this one fails
```

**Comment by AJIXuMuK** [comment]
Trying to create `Web` object twice doesn't help.
```typescript
const webToSave = Web(webUrl);
await webToSave.select('Title', 'Url').get();

const web = Web(webUrl);
const subwebs = await web.getSubwebsFilteredForCurrentUser().get();
```

**Comment by patrick-rodgers** [comment]
Just tried it and I cannot duplicate with the information provided. toUrl is one of the core methods used in the queryable stack - unlikely there is a bug there as **all requests** would be affected. Can you provide more details or is this no longer an issue?

**Comment by AJIXuMuK** [comment]
I can't repro it with some simple example.
In real project I made a workaround.

If I experience the error again, I'll create a new issue and will try to provide a good example.
