### ISSUE TITLE
How to merge two Application customizers 

### ISSUE THREAD

**Issue by nmaitreyi** [pnp/pnpjs#1217]
We have two different application customizers one is a notification application customizer and an other one is  different application extension to show list of roles to users. How do we merge these two extensions into a div while displaying in sharepoint site page in the top placeholder.

**Comment by koltyakov** [comment]
SPFx is mostly not a topic of issues here, especially when it comes to generics not connected with PnPjs internals. Would encourage you to seek assistance for general questions in the [tech community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) or SPFx specific places.
