### ISSUE TITLE
Misspelled word in Issue template

### ISSUE THREAD

**Issue by gitbrent** [pnp/pnpjs#1219]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  (current)  ]

Please specify what version(s) of SharePoint you are targeting: [  (current)  ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
- Fix misspelling

### Observed Behavior
- The "Submission Guidelines" section has "seperate" [sic] misspelled.

**Comment by patrick-rodgers** [comment]
Thanks, fixed it.
