### ISSUE TITLE
Updating profile picture fails (same as closed issue 524, but possible with root cause identified)

### ISSUE THREAD

**Issue by jlith** [pnp/pnpjs#1220]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.11] (but I can see the code is the same in 2.0.6)

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected Behavior
Calling the method `sp.profiles.setMyProfilePic` with the blob from input[type=file] should upload the selected image as a new profile picture for me.

### Observed Behavior
Instead I get the following error:
```
Error: Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-2147024809, System.ArgumentException","message":{"lang":"en-US","value":"Parameter is not valid."}}}
```

Looking at the developer console and the network calls in my browser, I can see that the image is not send as parameter to the server (request body is empty).

### Steps to Reproduce
1. Create e.g. React form with input[type=file]
```
<input type="file" onChange={this.handlePictureUpload} accept="image/png, image/jpeg" /> 
```
2. Upload the selected image
```
private handlePictureUpload(e: React.ChangeEvent<HTMLInputElement>) {
    sp.profiles.setMyProfilePic(e.target.files[0]).then(value => console.log(value)).catch(ex => console.warn(ex));
}
```

### Suggestion to Fix
I think that issue is that FileReader is asynchronous, and the current code does not wait it to complete, but immediately sends the result to server (thus it is empty). I copied the code, waited for the FileReader and then called the REST API directly - and that worked.

I think that in the old code base the request is also send after FileReader completes the read operation:
https://github.com/SharePoint/PnP-JS-Core/blob/1500ab7cf66d5ca7c89e1f71c70fc6fcf9e715e6/src/sharepoint/userprofiles.ts#L170

See the current code here:
https://github.com/pnp/pnpjs/blob/687861d5e000dd8edb8cbf078756d0cb7acda738/packages/sp/src/userprofiles.ts#L169

E.g. the following might work (I just moved the POST request into the onLoad event of FileReader)
```
       return new Promise<void>((resolve, reject) => {
            let buffer: any = null;
            const reader = new FileReader();
            reader.onload = (e: any) => {
                buffer = e.target.result;
                const request = new UserProfileQuery(this, "setmyprofilepicture");
                request.postCore({
                     body: String.fromCharCode.apply(null, <any>new Uint16Array(buffer)),
                }).then(_ => resolve()).catch(e => reject(e));
            }                
            reader.readAsArrayBuffer(profilePicSource);
        });
```

**Comment by patrick-rodgers** [comment]
Thanks for reporting this and the careful analysis. This was indeed a bug and I pretty much used your solution. If you are interested in submitting PRs we absolutely welcome that - and have an [ongoing series](https://aka.ms/sharing-is-caring) hosted by @PopWarner that can help answer any questions you might have. Great work and appreciate you reporting the issue. Thanks!
