### ISSUE TITLE
Unable to parse Guid in SharePoint format with SP core library

### ISSUE THREAD

**Issue by EagleWizard28** [pnp/pnpjs#1222]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: **1.3.11**

_Since I'm using "@pnp/sp-taxonomy" I'm unable to use v2._

Please specify what version(s) of SharePoint you are targeting: **SharePoint Online**

### Expected / Desired Behavior / Question
When trying to parse a Guid in the following format "/Guid(d5369f3b-bd7a-412a-9c0f-7f0650bb5489)/" it should work.

### Observed Behavior
Instead of the Guid I get _undefined_ back.
Also when I run "isValid" it returns false.

### Steps to Reproduce
Install the needed pnp packages, for the moment I have these installed
```
 "@pnp/common": "^1.3.11",
    "@pnp/graph": "^1.3.11",
    "@pnp/logging": "^1.3.11",
    "@pnp/odata": "^1.3.11",
    "@pnp/sp": "^1.3.11",
    "@pnp/sp-clientsvc": "^1.3.11",
    "@pnp/sp-taxonomy": "^1.3.11",
```
Import the "Guid" in your code from the core library
`import { Guid } from '@microsoft/sp-core-library';`

Try to parse the SharePoint formatted guid that is given in the documentation.
`const termGuid = Guid.tryParse("/Guid(d5369f3b-bd7a-412a-9c0f-7f0650bb5489)/");`

Normally the Guid should be returned, but I get undefined.

**Comment by koltyakov** [comment]
Hi @EagleWizard28,

`@microsoft/sp-core-library` is not part of PnPjs. It might expect a GUID without `/Guid(...)/` wrapper which is used here and there in old taxonomy API. So you probably should clean up it before validating or use a custom regular expression for validation.

Anyways `@microsoft/sp-core-library` is not connected to PnPjs at all.

P.S. New taxonomy support is on the [way](https://github.com/pnp/pnpjs/pull/1216), btw. Read operations are already a part of v2.0.6 and could be used. We would love to hear some feedback on these 2.1 API methods.
