### ISSUE TITLE
How to tag existing terms to sharepoint client-side page using pnpjs?

### ISSUE THREAD

**Issue by PrathyushP95** [pnp/pnpjs#1223]
### Category
- [x] Question

### Version

Please specify what version of the library you are using: [2.0.5]

Please specify what version(s) of SharePoint you are targeting: [2016]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question

Hi,
I'm able to create a modern page in sharepoint programmatically using pnpjs.
Now i wanted to add terms to my modern pages. I've created terms in termstore manager.
Can someone help me to tag those terms to my sharepoint page programmatically using pnpjs?

![Capture](https://user-images.githubusercontent.com/20680181/84264323-9ab38600-ab3e-11ea-8736-55664d6fb864.PNG)

I want to add tags like the above screenshot example using pnpjs.

**Comment by PrathyushP95** [comment]
@juliemturner , I tried the solution which you have given.

`const item2 = await sp.web.getFolderByServerRelativeUrl("/sites/dev/SitePages/without-tag.aspx").getItem("CandC_Tax_2", "Title");`

This gives me output similar to,

```
_data: {
    cloneParentWasCaching: false,
    options: {},
    parentUrl: "https://domain.sharepoint.com/sites/dev/_api/Web/Lists(guid'5bd023a4-9e31-4c2b-9e5b-eee6e88434a')/Items(371)",
    parser: ODataParser {},
    query: Map {},
    url: "https://domain.sharepoint.com/sites/dev/_api/Web/Lists(guid'5bd023a4-9e31-4c2b-9e5b-eee6e88434a')/Items(371)",
    useCaching: false
  },
  _forceCaching: false,
  delete: [Function],
  'odata.metadata': 'https://domain.sharepoint.com/sites/dev/_api/$metadata#SP.ListData.SitePagesItems/@Element&$select=CandC_Tax_2,Title',
  'odata.type': 'SP.Data.SitePagesItem',
  'odata.id': 'f0ffadb5-7ccf-4efd-81a8-0034020f5c57',
  'odata.etag': '"67"',
  'odata.editLink': "Web/Lists(guid'5bd023a4-9e31-4c2b-9e5b-eee6e884302h')/Items(371)",
  Title: 'with tag',
  CandC_Tax_2: [
    {
      Label: 'UK',
      TermGuid: 'ff2ceb25-1428-406c-9996-1fc43194d742',
      WssId: 2
    }
  ]
}
```
But when i try to update CandC_Tax_2 with the below code it is giving error.

`await item2.update({
    CandC_Tax_2:  [{
Label: 'UK',
TermGuid: 'ff2ceb25-1428-406c-9996-1fc43194d585',
WssId: 2
}]
  })`

`"Error making HttpClient request in queryable [400] Bad Request ::> {\"odata.error\":{\"code\":\"-1, Microsoft.SharePoint.Client.InvalidClientQueryException\",\"message\":{\"lang\":\"en-US\",\"value\":\"A node of type 'StartArray' was read from the JSON reader when trying to read a value of a property; however, a 'PrimitiveValue' or 'StartObject' node was expected.\"}}}"`

I'm able to update Title but not CandC_Tax_2

**Comment by juliemturner** [comment]
See this answer: #355

**Comment by PrathyushP95** [comment]
@juliemturner , i went through #355 and tried below code.

```
const list = await sp.web.lists.getByTitle("Site Pages");
const field = await list.fields.getByTitle('Country').get();
const data = {};
data[field.InternalName] = "2;#Termname|ff2ceb25-1428-406c-9996-1fc43194d725;#";
const updated = await list.items.getById(pageItemId).update(data);
console.log(updated);
```

This now gives me error as,

`An unexpected 'PrimitiveValue' node was found when reading from the JSON reader. A 'StartObject' node was expected.`

Can you please suggest me a fix for this.

**Comment by koltyakov** [comment]
@PrathyushP95,

You probably still use incorrect payload if it's a single item metadata field. Please try corresponding payload:

```js
{
  __metadata: { type: 'SP.Taxonomy.TaxonomyFieldValue' },
  Label: termName,
  TermGuid: termId,
  WssId: '-1'
};
```

P.S.

Also, OData doesn't use internal names but [entity property names](https://pnp.github.io/pnpjs/sp/items/#resolving-field-names) which not necessarily the same as internal names.

**Comment by PrathyushP95** [comment]
@koltyakov I can see value of TypeAsString as 'TaxonomyFieldTypeMulti'. So i hope this is not a single metadata field.
Also, my internal name and entity property name are both same.

**Comment by koltyakov** [comment]
I can also suggest trying, `validateUpdateListItem` which is used in the SP UI, it has though a bit different [payloads](https://github.com/koltyakov/sp-sig-20180705-demo/blob/master/src/03-pnp/FieldTypes.md) which anyways simpler when it comes to MMD fields. See also the good [article](http://blog.aterentiev.com/2018/04/how-to-easily-update-managed-metadata.html) by Alex.

**Comment by PrathyushP95** [comment]
Thanks a lot @koltyakov , that helped. Its working now.
