### ISSUE TITLE
store.getTermsById - Guid should contain 32 digits with 4 dashes

### ISSUE THREAD

**Issue by Sifringer** [pnp/pnpjs#1224]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [^1.3.11]

Please specify what version(s) of SharePoint you are targeting: [Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Hi there.

This is the first time I report an issue, so sorry if I make any mistake.

I'm using below libraries to get data from the Term Store on SP Online.
"@pnp/sp-clientsvc": "^1.3.11",
 "@pnp/sp-taxonomy": "^1.3.11"

Everything was good but suddenly I tried to use the "getTermsById" method

`const terms: ITerms = store.getTermsById("0ba6845c-1468-4ec5-a5a8-718f1fb05431", "0ba6845c-1468-4ec5-a5a8-718f1fb05432");`

`terms.get().then(c=> console.log(c));`

It shows this error message: "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)."

I've tried several ways to use it. For instance: 

`const termsCollection = ["0ba6845c-1468-4ec5-a5a8-718f1fb05431", "0ba6845c-1468-4ec5-a5a8-718f1fb05432"];`
`const terms: ITerms = store.getTermsById(...termsCollection);`

Also tried this format without luck: 
`"/Guid(11f1a272-8398-49e9-bbba-a6d1b53a4c67)/"`

It's the only method that fails when I use a GUID. Everything else works fine.

I wonder if the reason is that the tenant I'm using is configured for Targeted Release or there are other users that are experiencing the same behavior with this method.

I've seen similar issues reported about this, but none of them talk about this specific method.

Thank you.

**Comment by inconscienceAdmin** [comment]
Got the same issue here. Did you manage to find a solution for this?

**Comment by Sifringer** [comment]
Not really. In the end, I changed my approach.

I used the "getTermSetById" method: 

`taxonomy.termStores.getById(termStoreId).getTermSetById(termSetId).terms.usingCaching().get()`

There were more than 70 terms to get, but it worked fast enough to be accepted. 

Hopefully, this will be fixed in PNP js taxonomy v2.1

**Comment by patrick-rodgers** [comment]
The 1.x library is no longer supported but I don't see anything immediately wrong with the code in that method and it uses the same guid normalization as everything else. Can you share the body of the request that is sent? Curious to see what form the guids are in when they are sent. Thanks!

**Comment by Sifringer** [comment]
Hi Patrick.

This is the code (I used SP Editor Chrome extension)

`import { taxonomy, ITermStore, ITerms, ITermData, ITerm } from "@pnp/sp-taxonomy";`
`const store: ITermStore = taxonomy.termStores.getByName("Taxonomy_xe8FnRPMxZZlFAuciSMAWw==");`
`const terms: ITerms = store.getTermsById("4d5ce7bd-f741-465a-9434-4c8f9deed9ce", "36253afd-07c9-49ff-8f9b-e64fffbb8521");`
`terms.get().then(x => { console.log(x); })`

This is the request payload:

`<Request xmlns="http://schemas.microsoft.com/sharepoint/clientquery/2009" SchemaVersion="15.0.0.0" LibraryVersion="16.0.0.0" ApplicationName="PnPjs">
	<Actions>
		<ObjectPath Id="1" ObjectPathId="0" />
		<ObjectPath Id="3" ObjectPathId="2" />
		<ObjectPath Id="5" ObjectPathId="4" />
		<ObjectPath Id="7" ObjectPathId="6" />
		<Query Id="8" ObjectPathId="6">
			<Query SelectAllProperties="true" >
				<Properties />
			</Query >
			<ChildItemQuery SelectAllProperties="true" >
				<Properties />
			</ChildItemQuery >
		</Query >
	</Actions>
	<ObjectPaths>
		<StaticMethod Id="0" Name="GetTaxonomySession" TypeId="{981cbc68-9edc-4f8d-872f-71146fcbb84f}" />
		<Property Id="2" ParentId="0" Name="TermStores" />
		<Method Id="4" ParentId="2" Name="GetByName">
			<Parameters>
				<Parameter Type="String">Taxonomy_xe8FnRPMxZZlFAuciSMAWw==</Parameter>
			</Parameters>
		</Method>
		<Method Id="6" ParentId="4" Name="GetTermsById">
			<Parameters>
				<Parameter Type="Array">&lt;Object Type=&quot;String&quot;&gt;4d5ce7bd-f741-465a-9434-4c8f9deed9ce&lt;/Object&gt;&lt;Object Type=&quot;String&quot;&gt;36253afd-07c9-49ff-8f9b-e64fffbb8521&lt;/Object&gt;
				</Parameter>
			</Parameters>
		</Method>
	</ObjectPaths>
</Request>`

As you see the object is being sent like this:

`<Parameter Type="Array">&lt;Object Type=&quot;String&quot;&gt;4d5ce7bd-f741-465a-9434-4c8f9deed9ce&lt;/Object&gt;&lt;Object Type=&quot;String&quot;&gt;36253afd-07c9-49ff-8f9b-e64fffbb8521&lt;/Object&gt;
				</Parameter>`



Thank you!

**Comment by patrick-rodgers** [comment]
Thanks for sharing the request - it all looks OK to me. It looks like you've found a work around. Going to close this issue as v1 is no longer supported, but if you have time and want to submit a PR targeting version-1 branch with a fix we'll definitely review and merge. Thanks!

**Comment by dmoorjmalani** [comment]
@patrick-rodgers this issue still exists, i know this 1.x library is no longer supported, but i tried to find support of this method in 2.x, but couldn't. Loading all the terms of the termset would be very resource consuming as in my biggest term set i have more than 500 terms.  thanks!
