### ISSUE TITLE
Using with nodejs in a an azure function

### ISSUE THREAD

**Issue by jschaufele** [pnp/pnpjs#1226]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   ^2.0.6     ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question

- I don't know if this is an issue or I am just not familiar enough with the package -
- I am using an azure function (nodejs)  with apollo server to access SPO, 
- Use cert authentication and can access SPO using standard REST calls
- Can't for the life of me to use the pnpjs package to replace it - am using the commonjs version
- Need to add the adal token which I do by using the header option - 
- SPFetchClient won't work for obvoius reasons
- Used the BearerTokenFetchClient but it does not seem to read in the updated headers
- The closest I got was using NodeFetchClient but it just seemed to die on the the response - 
- If you have any examples to access SPO via cert authentication it would be greatly appreciated 

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
Just noting to not forget: this is probably something good to add to the new authentication section in the docs once someone has a chance to figure it out.

**Comment by patrick-rodgers** [comment]
We have added support for MSAL auth in node and include an example for setting up a cert in 2.0.11. You can [read the details in the new docs section](https://pnp.github.io/pnpjs/authentication/server-nodejs/#call-sharepoint).
