### ISSUE TITLE
When i am trying to get data from rich text box from list and bind it to pnp Rich text box nothing is visible in control, though the data is there in that state i have assigned, i have checked in developer tool.....but it is not showing 

### ISSUE THREAD

**Issue by sunnysinha05** [pnp/pnpjs#1228]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of SharePoint you are targeting: [         ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thank you for your feedback!

**Comment by sunnysinha05** [comment]
import * as React from 'react';
import styles from './RichTextTest.module.scss';
import { IRichTextTestProps } from './IRichTextTestProps';
import { escape } from '@microsoft/sp-lodash-subset';

import { sp } from "@pnp/sp";
import { RichText } from "@pnp/spfx-controls-react/lib/RichText";
import { autobind } from 'office-ui-fabric-react/lib/Utilities';
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

export interface ISpfxPnpRichtextState {
  description: string;
  SuccessMessage: string;
}

export default class RichTextTest extends React.Component<IRichTextTestProps, ISpfxPnpRichtextState,{}> {
  constructor(props: IRichTextTestProps, state: ISpfxPnpRichtextState) {
    super(props);
    sp.setup({
      spfxContext: this.props.context
    });

    this.state = { SuccessMessage: '', description: '' };
    this._getDescription();
  }
  public render(): React.ReactElement<IRichTextTestProps> {
    return (
      <div className={styles.richTextTest}>
      <RichText isEditMode={true} value={this.state.description}  />
      <br></br>
      <button className={styles.button} onClick={this._updateDescription}>Save</button>
      <br></br>
      <br></br>
      <label className={styles.label}>{this.state.SuccessMessage}</label>
    </div>
    );
  }

@autobind
 private async _getDescription() {
   const item: any = await sp.web.lists.getByTitle("Employee Registration").items.getById(61).get();

   console.log(this.state.description);
   console.log(item.Description);

   let dummyElement = document.createElement("DIV");
   dummyElement.innerHTML = item.Description;
   let outputText = dummyElement.innerText;

   this.setState({ description: outputText });
 }

 @autobind
 private async _updateDescription() {
   console.log(this.state.description);
   const updatedItem = await sp.web.lists.getByTitle("Employee Registration").items.getById(61).update(
     {
       Description: this.state.description
     });
   this.setState({ SuccessMessage: 'Successfully saved' });
 }
}

**Comment by sunnysinha05** [comment]
import * as React from 'react';
import styles from './RichTextTest.module.scss';
import { IRichTextTestProps } from './IRichTextTestProps';
import { escape } from '@microsoft/sp-lodash-subset';

import { sp } from "@pnp/sp";
import { RichText } from "@pnp/spfx-controls-react/lib/RichText";
import { autobind } from 'office-ui-fabric-react/lib/Utilities';
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

export interface ISpfxPnpRichtextState {
  description: string;
  SuccessMessage: string;
}

export default class RichTextTest extends React.Component<IRichTextTestProps, ISpfxPnpRichtextState,{}> {
  constructor(props: IRichTextTestProps, state: ISpfxPnpRichtextState) {
    super(props);
    sp.setup({
      spfxContext: this.props.context
    });

    this.state = { SuccessMessage: '', description: '' };
    this._getDescription();
  }
  public render(): React.ReactElement<IRichTextTestProps> {
    return (
   <   RichText isEditMode={true} value={this.state.description}   />
    );
  }

@autobind
 private async _getDescription() {
   const item: any = await sp.web.lists.getByTitle("Employee Registration").items.getById(61).get();

   console.log(this.state.description);
   console.log(item.Description);

   let dummyElement = document.createElement("DIV");
   dummyElement.innerHTML = item.Description;
   let outputText = dummyElement.innerText;

   this.setState({ description: outputText });
 }

 @autobind
 private async _updateDescription() {
   console.log(this.state.description);
   const updatedItem = await sp.web.lists.getByTitle("Employee Registration").items.getById(61).update(
     {
       Description: this.state.description
     });
   this.setState({ SuccessMessage: 'Successfully saved' });
 }
}

**Comment by sunnysinha05** [comment]
@koltyakov  : could you please help me in this if this is not a bug, then what is it....as the  code looks pretty simple.....
also  why do we get undefined in className for PnP react controls when we check in dev tool of chrome.....

![image](https://user-images.githubusercontent.com/61428258/84623602-453ff600-aefd-11ea-8205-b848a580b531.png)

**Comment by sunnysinha05** [comment]
i am getting the data but not binding/showing...please suggest...

![image](https://user-images.githubusercontent.com/61428258/84626648-175db000-af03-11ea-8835-ed62143e2484.png)

**Comment by koltyakov** [comment]
Going to close this as not related to PnPjs. Would encourage asking generic questions (e.g. React questions) in tech community forums or in corresponding repositories ([sp-dev-fx-controls-react](https://github.com/pnp/sp-dev-fx-controls-react), if it's about one of its controls usage).

**Comment by sunnysinha05** [comment]
@koltyakov : this is related to pnp react control....where should i post this ?

**Comment by koltyakov** [comment]
> in corresponding repositories ([sp-dev-fx-controls-react](https://github.com/pnp/sp-dev-fx-controls-react), if it's about one of its controls usage)
