### ISSUE TITLE
Is it possible to update the propertybag of a library's root folder using pnpjs/rest.

### ISSUE THREAD

**Issue by russgove** [pnp/pnpjs#1230]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [ x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    latest     ]

Please specify what version(s) of SharePoint you are targeting: [    online     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

Is it possible to update the propertybag of a library's root folder using pnpjs/rest. I see that the propertybag of the web is read-only via rest, but I'm not sure about folders.

**Comment by koltyakov** [comment]
Property bags exposed as read only in REST (in my knowledge it is still relevant), so they can’t be updated with REST, but JSOM/CSOM API. However, this can be done without loading heavy JSOM libraries with use of the same XML package what would been sent by JSOM but using SPHttpClient.

**Comment by russgove** [comment]
thanks andrew!
(i'll just use a list!)

**Comment by russgove** [comment]
In case anyone needss it here is a method to update a propertybag usng the same XML package what would been sent by JSOM but using SPHttpClient.

  private async SetListPropertypagValue(listName: string, propertyName: string, propertyValue: string) {
    const client = new SPHttpClient();
    await Promise.all([
      sp.web.select("Url").get(),
      sp.site.select("Id").get(),
      sp.web.lists.getByTitle(listName).rootFolder.get(),
      sp.web.select("Id").get(),
    ])
      .then(async (results) => {
        debugger;
        const siteObj = results[0];
        const siteId = results[1];
        const folder = results[2];
        const web = results[3];
        const endpoint = siteObj.Url + `/_vti_bin/client.svc/ProcessQuery`;
        const body = `<Request AddExpandoFieldTypeSuffix="true" SchemaVersion="15.0.0.0" LibraryVersion="15.0.0.0" ApplicationName=".NET Library" xmlns="http://schemas.microsoft.com/sharepoint/clientquery/2009">
        <Actions>
        <Method Name="SetFieldValue" Id="4" ObjectPathId="3">
        <Parameters>
        <Parameter Type="String">${propertyName}</Parameter>
        <Parameter Type="String">${propertyValue}</Parameter>
        </Parameters>
        </Method>
        <Method Name="Update" Id="1" ObjectPathId="2" />
        </Actions>
        <ObjectPaths>
        <Property Id="3" ParentId="2" Name="Properties" />
        <Identity Id="2" Name="85525e9f-f0af-b000-5242-902ff09fcdba|740c6a0b-85e2-48a0-a494-e0f1759d4aa7:site:${siteId.Id}:web:${web.Id}:folder:${folder.UniqueId}" />
        </ObjectPaths></Request>`;
        await client.post(endpoint, {
          headers: {
            "content-type": "text/xml"
          },
          body: body
        }).then(async (response) => {
          debugger;
          const result = await response.json();
          console.log(result);
        });
      });
  }
