### ISSUE TITLE
/node_modules/@pnp/sp/index"' has no exported member 'Web'.

### ISSUE THREAD

**Issue by Alper2** [pnp/pnpjs#1232]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [ X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.0.6     ]

Please specify what version(s) of SharePoint you are targeting: [     1.8    ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*
Using the Web property without issues. 

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

I have a working old solution (uses v **1.2.9**) that I am putting/copying in to a new created project (version **2.0.6**). I am importing the Web property:

`import { Web } from "@pnp/sp";`

But I get the following error:
"/node_modules/@pnp/sp/index"' has no exported member 'Web'."

I change the pnp/sp version to the same one in the old working solution (**1.2.9**) and get the following error:
"error TS2345: Argument of type 'Web' is not assignable to parameter of type 'IWeb'."

I also have tried:
`import { sp, Web, IWeb } from "@pnp/sp/presets/all";`

But above complains about the following code (void):

` private globalWeb = new Web(Constants.GlobalUrl);`

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

See above. 
### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thank you for your feedback!

**Comment by juliemturner** [comment]
Can you review this [transition guide](https://pnp.github.io/pnpjs/transition-guide/) and see if it answers your questions.

**Comment by patrick-rodgers** [comment]
Closing this as answered.
