### ISSUE TITLE
Changing visibility of List Field from hidden to shown using field.setShowInDisplayForm not working

### ISSUE THREAD

**Issue by prashanta** [pnp/pnpjs#1234]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.6 ]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

### Expected / Desired Behavior / Question
Expected to create a new field for Document List and change visibility from hidden to shown.

### Observed Behavior
Field is created but remains hidden in Document view.

### Steps to Reproduce
Run the following in the context of a modern team site in nodejs:

```javascript
const fieldAndResult = await sp.web.lists.getByTitle("Documents").fields.add(
  'Project Id',
  'SP.FieldText',
  { 
        FieldTypeKind: 2, 
        Hidden: false, 
        Group: "Custom Columns", 
        DefaultValue: '1234'
  }
);
await fieldAndResult.field.setShowInDisplayForm(true);
await fieldAndResult.field.setShowInEditForm(true);
```

**Comment by koltyakov** [comment]
Can confirm, there is nothing wrong with these methods in the library. They work as expected.

This can be checked by verifying SchemaXML:

```typescript
const field = sp.web.lists.getByTitle('Documents').fields
  .getByInternalNameOrTitle('Project Id');
await field.setShowInDisplayForm(true);
await field.setShowInEditForm(false);
const f = await field.get();
console.log(f.SchemaXml);
```

```xml
<Field
  DisplayName="Project Id"
  Type="Text"
  Required="FALSE"
  ID="{6ebd425a-69ef-4bb0-a739-654be2ffcd1d}"
  SourceID="{77b6cf2f-b4f8-49a9-a203-f1363a8fa117}"
  StaticName="Project_x0020_Id"
  Name="Project_x0020_Id"
  ColName="nvarchar16"
  RowOrdinal="0"
  Hidden="FALSE"
  CanToggleHidden="TRUE"
  Group="Custom Columns"
  Version="11"
  **ShowInDisplayForm="TRUE"**
  **ShowInEditForm="FALSE"**
><Default>1234</Default></Field>
```

Though, having multiple content types you might not even add a field to a content type which form you check later on.

**Comment by patrick-rodgers** [comment]
Closing this as answered. The show in form and hidden are different properties and control different things. I think you might mean to update the field's hidden property value?

**Comment by prashanta** [comment]
What I was trying to achieve is to show the custom columns in "All Documents" view, which is default view.
I was able to achieve this by using:

```
const list = sp.web.lists.getByTitle('Documents');
await list.defaultView.fields.add("Project Name");
await list.defaultView.fields.add("Project Number");
```

**Comment by koltyakov** [comment]
Views and forms are different things obviously.
