### ISSUE TITLE
does the library suypport making one sp group the owner of another sp group

### ISSUE THREAD

**Issue by russgove** [pnp/pnpjs#1235]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  latest       ]

Please specify what version(s) of SharePoint you are targeting: [  onlibe       ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

### Submission Guidelines
does pnpjs support setting a sitegroup as the owner of another sitegroup.
i see issue at https://github.com/pnp/pnpjs/issues/957

was that workaround added to pnpjs?

**Comment by koltyakov** [comment]
It looks very much like a sort of a "bug" in REST API. Or some weird by a design decision. Though it's called `setUserAsOwner` in REST API but not a generic Owner and not a Group to be precise, so technically this would not be a bug in API if pointing out.
`setUserAsOwner` is actually can only set a user principal as owner. But it just silently ignoring if a provided argument Id belongs to a group principal. At least I ended up with such conclusions.
There is no `setGroupAsOwner` and patching a group also doesn't work.
A couple of weeks ago I needed the same, but for On-Prem and [this approach](https://github.com/pnp/pnpjs/issues/957#issuecomment-565484501) worked well. One of the places with REST API, where I'm saying once again the fallback to CSOM is an option.

**Comment by russgove** [comment]
Thanks for the clarification andrew. I ended up  using that appoach as well.
Are we considering putting that approach right in PNP JS?

**Comment by patrick-rodgers** [comment]
We won't add SOAP requests into PnPjs - that's been our position from the start. It is unfortunate the REST API has this limitation but there is a work around for folks that need it - and could be added as a library extension easily if desired to add to how you use the library. Going to close this as the original question is answered. Thanks!

**Comment by koltyakov** [comment]
It was JSOM, not SOAP. :) But anyway, my suggestion for the folks reading this after ending up with a question how to set a group as an owner is adding such methods as [extension](https://pnp.github.io/pnpjs/odata/extensions/) into the custom project codebase.
