### ISSUE TITLE
Create client side page with specified content type

### ISSUE THREAD

**Issue by msgx** [pnp/pnpjs#1237]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version
- Version of the library: **v1.3.11**, **v2.0.6**
- Version of the SharePoint environment: **SharePoint Online**

### Question
As I can see (at least in UI), SharePoint Online supports adding custom content types inherited from Site Page content type and creating "modern" pages of these types. By using the library, however, I have to create a page, get its list item, and set content type by calling `update({ ContentTypeId: "0x0101009D1CB255DA76424F860D91F20E6C411800..." })`. Is it possible to specify content type as an initial parameter? Or is it a limitation of SharePoint API?

**Comment by koltyakov** [comment]
Hey Alisher!

I didn't find obvious evidence after a brief look that a CT can be provided to the modern page in a time of creation via API within one call.

My assumption is that it might be a similar case as with items metadata when you need to create first when switching the CT with validateUpdateListItem method for example (the same way you do it now).

Let's keep it open as discussions to wait for somebody who uses modern pages intensively to say if there is actually a way or not.

**Comment by juliemturner** [comment]
It is also my understanding that it's not possible, through the UI, to select the content type when creating a modern page, so I concur with @koltyakov that the method of updating the metadata in a second call is the correct one at this time.

**Comment by msgx** [comment]
> It is also my understanding that it's not possible, through the UI, to select the content type when creating a modern page...

Actually, it's possible. How to reproduce at least on **Communication** site:

1. Create a custom content type inherited from OOB **Site Page** content type.
2. Add a couple of additional site columns into it just to identify that custom content type visually later.
3. Configure **Site Pages** library with the custom content type: add it to available content types in the library.
4. Go to **All Pages** view (or any other view you prefer).
5. Click **New** button and pick the custom content type from the dropdown appeared.
6. Edit and publish the page.
7. Open **Page details** panel, expand **Properties** section, and check if custom fields are available there.
8. Go to the library view, select the page, open **Details pane**, scroll to **Properties** section, and check the **Content Type** value as well as custom fields availability.
