### ISSUE TITLE
Create client side page in folder

### ISSUE THREAD

**Issue by msgx** [pnp/pnpjs#1238]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version
- Version of the library: v1.3.11, v2.0.6
- Version of the SharePoint environment: SharePoint Online

### Question
I have a requirement to create client side pages in custom folders pre-created in the Site Pages library. Currently, I have to create a page, retrieve its file object, and use `moveTo()` method to achieve the goal. However, PnP Provisioning Schema and PnP PowerShell allows to specify PageName as a path like this:

- PnP provisioning template: `<pnp:ClientSidePage PageName="myfolder/MyArticle" ...`
- PnP PowerShell: `Add-PnPClientSidePage -Name "subfolder/MyArticle"`

Is it possible to have something similar to that in the library?

**Comment by patrick-rodgers** [comment]
I think I see how they are doing this, will work on adding support for 2.0.12.

**Comment by patrick-rodgers** [comment]
Poking at this some more it seems we are currently unable to support adding pages into folders. Not going to close the issue, but haven't yet found a way to support this.

**Comment by juliemturner** [comment]
I'm going to close this now as this is not supported by the currently available API's. If an official pages API is ever released hopefully this will become supported. Thanks for reaching out with your question!
