### ISSUE TITLE
PnPJS IE 11 Polyfill Error

### ISSUE THREAD

**Issue by AJIXuMuK** [pnp/pnpjs#1239]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.5], `polyfill-ie11`: 2.0.2

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
IE 11 polyfill works on relatively old IE 11 versions.

### Observed Behavior
In SPFx solution loading of the component failing:
```
Failed to load entry point from component XXXXXXXX Original Error: Can't convert object to primitive value
```

This happens in InPrivate browser mode only and on **relatively old versions** of IE.
I was able to reproduce it on v11.3686.14393.0

### Steps to Reproduce
But I was able to find the steps to reproduce it:
1. IE 11 v11.3686.14393.0
2. Simple SPFx web part with polyfill and single sp request
3. open browser InPrivate mode

The error is failing the first time only. If you refresh the page - everything is OK.

**Comment by AJIXuMuK** [comment]
Related issue from sp-dev-docs: [https://github.com/SharePoint/sp-dev-docs/issues/5676](https://github.com/SharePoint/sp-dev-docs/issues/5676)

**Comment by juliemturner** [comment]
Please check out our [updated guidance on IE11](https://pnp.github.io/pnpjs/concepts/polyfill/).  Also, I believe there might be an issue with the selective imports but have not fully tested enough to add an issue to the list to be reviewed.

**Comment by AJIXuMuK** [comment]
@juliemturner I didn't use selective imports.
MGT team [has](https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/276) similar issue assigned as well.

**Comment by juliemturner** [comment]
Ok, then I think you need to read the document I referenced above, specifically, the section entitled: "General Statement on Polyfills".  I have many implementations working well in IE11 using the methodology outlined in that section. I am not using the new selective imports feature, although they may work fine I haven't tested them since they were released. I can tell you that the probable problem child is "core-js/stable/symbol".

**Comment by AJIXuMuK** [comment]
Thank you, I read the document.
And the implementation works for me in more or less new version of IE.
The problem is with the older versions.

I'm definitely not pushing to fix something, especially for old IE 11.
It's more an FYI that the polyfill module is not always functional.

**Comment by koltyakov** [comment]
I think more and more of a UI blocking component saying “IE is not an option use a real browser” even for a solutions which actually “can work” in IE. And delivering it by default as a feature where it’s appropriate. Many customers and users are not agains using Chrome or Edge these days but opening in IE incidents happen sometimes. I wish a day MS will retire IE everywhere and completely including Office Adding and hidden places just saying we have a browser and it’s Edge. :D

**Comment by juliemturner** [comment]
As our statement says I think at this point where we stand is that we share what polyfills are required to support IE11 but after that, we cannot guarantee how to make it work. Further that you must target an old version if IE11 is even more out of our scope.  So yes, maybe it doesn't work but there isn't really anything we can do to solve for all the permutations that might arise.

I'm going to close this issue based on that understanding. Thanks for sharing with the community possible impacts.
