### ISSUE TITLE
Is there a way to create a multi-user column outside of by xml?

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1240]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [X] Documentation gap/issue

### Version
    "@pnp/sp": "^2.0.0",

### Expected / Desired Behavior / Question
Is there a way to create a Mutli-User column using the addUser or just add function?
There isn't anything in the pnpjs docs on creating MultiUser columns.
```
listFields.addUser(FieldName,selectionMode,fieldProps);
```

### Observed Behavior
I seem to only get it to work this way:
```
theList.lists.fields.createFieldAsXml(schemaGoesHere);
```

### Steps to Reproduce
I know that the type should be "UserMulti" instead of "User" but the "kind" number might be the same per the docs... based on it saying _**one or more users**_:

[ see User on msdocs](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/ee540543(v=office.15)?redirectedfrom=MSDN#members) | Specifies that the field contains one or more users and groups as values. The value = 20.
-- | --

I've tried numerous things including trying to do an Update after it was created but it doesn't work:
```
theList.lists.fields.getByInternalNameOrTitle(FieldName).update(Mult: true);
```

If I go the schema way and build my own function to create the xml, what is the minimum schema requirements for it to work?  When I look at a field that was created as MutliUser, this is what the schema looks like.  Just don't want to force create properties that might cause an issue down the road:

``` xml
<Field
    DisplayName="Team"
    Type="UserMulti"
    Required="FALSE"
    List="UserInfo"
    ID="{7a97ec36-e121-4a47-ae11-25f9f8112bd8}"
    SourceID="{42d17c8f-338e-405c-bdd7-c72a2a6b66e4}"
    StaticName="Team"
    Name="Team"
    ColName="int2"
    RowOrdinal="0"
    UserSelectionMode="PeopleOnly"
    Group=""
    Description="Other Team Members for this project. Helps you find projects you are working on."
    Version="2"
    EnforceUniqueValues="FALSE"
    ShowField="ImnName"
    UserSelectionScope="0"
    Mult="TRUE"
    Sortable="FALSE" />
```

**Comment by mikezimm** [comment]
I was able to make a relatively easy builder "function" where I can pass in the usual properties and have it build the xml here:

[Short code to convert field properties into schema](https://github.com/mikezimm/TrackMyTime7/blob/5e069d37cc37b53d9b8074fb720a52335726cf7e/src/services/listServices/columnServices.ts#L168)

It seems to work ok but I'm not sure if there is anything else I should have in the schema or can remove... just know it does seem to create the field ok:

```typescript
let fieldName = thisField.name;
let fieldTitle = thisField.title ? thisField.title : thisField.Title ? thisField.Title : thisField.onCreateProps.Title ? thisField.onCreateProps.Title : fieldName;
let fieldGroup = thisField.onCreateProps.Group ? thisField.onCreateProps.Group : '';
let fieldDesc = thisField.onCreateProps.Description ? thisField.onCreateProps.Description : '';
let fieldSelectMode = thisField.selectionMode;
let thisSchema = '<Field DisplayName="' + fieldTitle + '" Type="UserMulti"';
thisSchema += ' Required="FALSE" StaticName="' + fieldName + '" Name="' + fieldName + '"';
thisSchema += ' UserSelectionMode="' + fieldSelectMode + '"';
thisSchema += ' Group="' + fieldGroup + '"';
thisSchema += ' Description="' + fieldDesc + '"';
thisSchema += ' EnforceUniqueValues="FALSE" ShowField="ImnName" UserSelectionScope="0" Mult="TRUE" Sortable="FALSE"/>';
// ^^^^ I think ShowField=ImnName shows field as skype jellybean; ShowField=Name shows account name ; ShowField="EMail" shows email address
// ^^^^ EnforceUniqueValues & Sortable need to be false for Multi-select fields.

actualField = await listFields.createFieldAsXml(thisSchema);
```

Is it worth packaging this option into PnP to make it easier out of the box?

**Comment by juliemturner** [comment]
Certainly, the library could be extended to provide a specific method to create a multiuser field. We have an interface already for the properties that can be modified through one of our calls, in general, I suspect that the reason this wasn't implemented is that it's a more special case and the solution that you've already identified is the way we intended these special field types should be created.

**Comment by mikezimm** [comment]
Thanks @juliemturner for the reply.  I know the community can only do so much.  For now my function is working so I'll close this one.  Have another question related to what I'm working and will do new issue for it.
