### ISSUE TITLE
sp.search() returns answer from call to /_api/contextinfo instead of search result

### ISSUE THREAD

**Issue by lgadola** [pnp/pnpjs#1241]
### Category
- [ ] Enhancement
- [x] Bug ?
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0.6      ]

Please specify what version(s) of SharePoint you are targeting: [    Online     ]

### Expected / Desired Behavior / Question
sp.search() returning search items in JSON format

### Observed Behavior
issues a POST to _api/contextinfo and returns XML-formatted answer to the calling program, causing 
"Uncaught (in promise): SyntaxError: Unexpected token < in JSON at position 0
SyntaxError: Unexpected token < in JSON at position 0

### Steps to Reproduce
call sp.search('searchstring')

if requested, I could upload an Angular app, reproducing the issue

**Comment by juliemturner** [comment]
So I did a quick test but cannot replicate this issue.  I'm wondering if you have a configuration issue as the context info feels like it's happening because you're not authenticated. So this is in a SharePoint Framework solution?

Did you do this step somewhere in your code before calling search?

```
    sp.setup({
      spfxContext: this.context
    });

   let searchResult = await sp.search("Test");
```

**Comment by lgadola** [comment]
I do not use spfxContext but authenticate with MSAL.
overwrite fetchClientFactory like this:
`constructor(private authService: MsalService) {
     sp.setup({
      sp: {
        baseUrl: urlBase,
        fetchClientFactory: () => {
          return {
            fetch: async (url, options) => {
              try {
                const response = await this.authService.acquireTokenSilent({
                  scopes: [
                    urlBase + '/.default'
                  ]
                });
                options.headers = [['Authorization', 'Bearer ' + response.accessToken ]];
                return fetch(url, options);
              } catch (error) {
                console.error('failed to fetch token: ' + error);
              }
            }
          };
        }
      }
    })
};`

when I intercept the token and issue a request to _api/search/query with Postman I get a proper result, so authentication is fine. Before upgrading to 2.0.6, I used BearerTokenFetchClient like this and had no issues:

`public constructor(private i18NService: I18nService, private authService: MsalService) {
    sp.setup({
      sp: {
        fetchClientFactory: () => {
          return {
            fetch: async (url, options) => {
              let client: any;
              try {
                const token = await this.authService.acquireTokenSilent([
                  env.endpoints[env.o365Endpoint] + '/.default'
                ]);
                client = new BearerTokenFetchClient(token);
                url = env.endpoints[env.o365Endpoint] + '/' + url;
                return client.fetch(url, options);
              } catch (error) {
                log.error('failed to fetch token: ' + error);
              }
            }
          };
        }
      }
    });
  }`

**Comment by lgadola** [comment]
Thanks, Julie
I solved it using BearerTokenFetchClient:
`    sp.setup({
      sp: {
        baseUrl: urlBase,
        fetchClientFactory: () => {
          return {
            fetch: async (url, options) => {
              try {
                const response = await this.authService.acquireTokenSilent({
                  scopes: [
                    env.endpoints[env.o365Endpoint] + '/.default'
                  ]
                });
                const client = new BearerTokenFetchClient(response.accessToken);
                return client.fetch(url, options);
              } catch (error) {
                log.error('failed to fetch token: ' + error);
              }
            }
          };
        }
      }
    });`
