### ISSUE TITLE
sp.views.add - is there a list of what properties I can add to the .add function?

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1243]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version
Latest docs

### Question
Is there a list of valid properties I can set in the views.add function shown below?
I was specifically trying to add ViewFields but got an error 400.

https://github.com/pnp/pnpjs/blob/version-2/docs/sp/views.md#add-a-view
```javascript
// create a new view with specific properties
const result2 = await list.views.add("My New View 2", false, {
    RowLimit: 10,
    ViewQuery: "<OrderBy><FieldRef Name='Modified' Ascending='False' /></OrderBy>",
   
    What: else,
    Can: be,
    Added: here, //?

});
```

### for example, this is the schema of a view from a random list I have... what all can be added?

```xml
<View Name="{B02AD2F6-34B3-4AF9-BA56-4B29BF28C49E}" DefaultView="TRUE" MobileView="TRUE" MobileDefaultView="TRUE" Type="HTML" DisplayName="All Items" Url="/sites/Templates/Tmt/Lists/Projects/AllItems.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=47">
	<Query>
		<OrderBy>
			<FieldRef Name="ID" Ascending="FALSE" />
		</OrderBy>
	</Query>
	<ViewFields>
		<FieldRef Name="ID" />
		<FieldRef Name="Active" />
		<FieldRef Name="StatusTMT" />
		<FieldRef Name="SortOrder" />
		<FieldRef Name="LinkTitle" />
		<FieldRef Name="Everyone" />
		<FieldRef Name="Category1" />
		<FieldRef Name="Category2" />
		<FieldRef Name="ProjectID1" />
		<FieldRef Name="ProjectID2" />
		<FieldRef Name="TimeTarget" />
		<FieldRef Name="Story" />
		<FieldRef Name="Chapter" />
		<FieldRef Name="Leader" />
	</ViewFields>
	<CustomFormatter />
	<ColumnWidth>
		<FieldRef Name="Title" width="463" />
		<FieldRef Name="Options" width="321" />
	</ColumnWidth>
	<ViewData />
	<Toolbar Type="Standard" />
	<Aggregations Value="Off" />
	<XslLink Default="TRUE">main.xsl</XslLink>
	<JSLink>clienttemplates.js</JSLink>
	<RowLimit Paged="TRUE">30</RowLimit>
	<ParameterBindings>
		<ParameterBinding Name="NoAnnouncements" Location="Resource(wss,noXinviewofY_LIST)" />
		<ParameterBinding Name="NoAnnouncementsHowTo" Location="Resource(wss,noXinviewofY_DEFAULT)" />
	</ParameterBindings>
</View>
```

Thanks!

**Comment by koltyakov** [comment]
Hi @mikezimm,

In theory, all [__metadata.type - SP.View props](https://github.com/koltyakov/sp-metadata/blob/baf1162394caba1222947f223ed78c76b4a72255/docs/SP/EntityTypes/View.md) can be passed. But on practice, most of them could be ignored by SP API silently (without any errors and without any effects). The most advances would be constructing and passing ListViewXml. However, REST API in the scope of views management edge cases has fewer capabilities than CSOM for instance, e.g. if you'd need to provide ViewType (hope little do that legacy these days) this is not feasible in REST at all.

**Comment by mikezimm** [comment]
Hi @koltyakov , Do you or anyone else know what the **Toolbar** and **ToolbarTemplateName** are for?

I noticed whenever I create a view by hand, the **Toolbar Type** (final prop in my view xml below) is set to 'Standard'.

However, when I create a view using this library and set either **Toolbar** or **ToolbarTemplateName** to "Standard", it still always shows <Toolbar Type="None"/> in the schema.

I can't find any real documentation around that property other than it's a "string".  Does it really impact the end user?

```xml
<View Name="{5E0B6274-F1C7-440D-8778-56FACBE14524}" Type="HTML" DisplayName="Activity Flat" Url="/sites/Templates/Tmt/Lists/Projects/Activity Flat.aspx" Level="1" BaseViewID="1" ContentTypeID="0x" ImageUrl="/_layouts/15/images/generic.png?rev=47" >
	<Query>
		<OrderBy>
			<FieldRef Name="ActivityType" Ascending="FALSE" />
		</OrderBy>
	</Query>
	<ViewFields>
		<FieldRef Name="ID" />
		<FieldRef Name="LinkTitle" />
		<FieldRef Name="ActivityType" />
		<FieldRef Name="ActivityTMT" />
		<FieldRef Name="OptionsTMTCalc" />
		<FieldRef Name="ActivtyURLCalc" />
	</ViewFields>
	<RowLimit Paged="TRUE">30</RowLimit>
	<Aggregations Value="Off" />
	<JSLink>clienttemplates.js</JSLink>
	<XslLink Default="TRUE">main.xsl</XslLink>
	<Toolbar Type="Standard"/>
</View>
```

**Comment by patrick-rodgers** [comment]
Going to close this as the initial question was answered. I am not aware of what those properties control and have never used them.
