### ISSUE TITLE
Contribution guide can be improved

### ISSUE THREAD

**Issue by lafe** [pnp/pnpjs#1247]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [Version-2](https://github.com/pnp/pnpjs/tree/183dc11edb65aa67f6e053e03fb28c5dbdb8a9a5)

Please specify what version(s) of SharePoint you are targeting: SharePoint Online

### Expected / Desired Behavior / Question

The contribution guide contains a complete description on how to setup the machine to start contributing.

### Observed Behavior

There are several issues with the current state of the documentation:

- [Contributing](https://pnp.github.io/pnpjs/getting-started-dev/) page:
  - it does not mention which versions of the tooling should be installed. Especially Node JS and especially Gulp have differences between versions and the exact version number is important for compability
  - The target audience for the page is not clear as there are several verbose passages: in my opinion, it is a safe bet that somebody who wants to start contributing to this project knows the purpose of Node JS. The same is true for installing Cmder - at the beginning PowerShell or even the normal command line would be sufficient. On the other hand, the purpose of the settings.js and its values are not described ("Edit [it] to reflect your personal environment").
  - The settings are explained on the [Debugging](https://pnp.github.io/pnpjs/debugging/#creating-settingsjs) page, but there is no link - this took me a while to see.
- [Debugging](https://pnp.github.io/pnpjs/debugging/) page:
  - The page mentions an `spsave` section in the settings.js file that is not present in the current version of the file. This is very confusing, as it is not clear, if the [linked file](https://pnp.github.io/pnpjs/concepts/settings/) is correct or if there is another version.
  - Register an Add-In - Step 4:

    > Provide a fake value for app domain and redirect uri, you can use the values shown in the examples

    Unfortunately, there are no examples mentioned on the page (and the [code examples](https://github.com/pnp/pnpjs/tree/183dc11edb65aa67f6e053e03fb28c5dbdb8a9a5/samples) do not have setting files, as far as I can tell)
  - [Configure the project settings file](https://pnp.github.io/pnpjs/debugging/#configure-the-project-settings-file-settingsjs): Further mentions of the `spsave` section
  - The chapter that describes, how the [App Registration for Graph Testing](https://pnp.github.io/pnpjs/debugging/#create-app-registration-for-graph-testing) should be set up, is completely missing. Without knowing which permissions are needed, this might be impossible (without analyzing each test in detail)
- The [Settings page](https://pnp.github.io/pnpjs/concepts/settings/) also does not offer any further information. It also does not link to the Debugging page that has the most complete information.

At the end, I was not able to get the tests to run, as I get an error (`Cannot read property 'aadTokenProviderFactory' of null`) and I am not sure if there is something missing. I hope that this description helps to improve the documentation so that it is getting easier and less frustrating to start.

**Comment by patrick-rodgers** [comment]
Thanks for pointing this out, the contributor guides were long overdue for an update. We took the time with 2.0.7 to add an entire contributor section to the docs. Please have a look and I hope its a little easier to understand. Thanks!
