### ISSUE TITLE
Pnp js break role inheritance

### ISSUE THREAD

**Issue by Bijoykrishna6398** [pnp/pnpjs#1250]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.6]

**Question**
I want to break the role inheritance of a SharePoint list item, and I have followed your step from this article(https://github.com/pnp/pnpjs/issues/364) but I am facing an issue with it.

It says
**Uncaught (in promise) TypeError: item.breakRoleInheritance is not a function**

![image](https://user-images.githubusercontent.com/44425176/86208496-4bd19d00-bb8e-11ea-816c-75712bde649a.png)

Here is the code

```
const list = sp.web.getList(`/sites/CMSAlpha/Lists/newRequest`);
const item = list.items.getById(484);
await item.breakRoleInheritance(false);
```

**Comment by Bijoykrishna6398** [comment]
I have found out the cause of the problem. If I import the **pnp** directly to my code then it's working as expected but if I import it from my library component then it's throwing that error.

**Comment by Bijoykrishna6398** [comment]
Never mind, I solved the issue by importing 
![image](https://user-images.githubusercontent.com/44425176/86211760-80e0ee00-bb94-11ea-8632-89dc18c838a0.png)
in my library component.

**Comment by juliemturner** [comment]
Glad you got it solved!! Sometimes those imports can be tricky.
