### ISSUE TITLE
sp.fields Question: How can I do const myFields = await myList.fields.getAllFields()  ?

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1251]
### Category
- [X] Question
- [ ] Documentation gap/issue

### Version
"@pnp/sp": "^2.0.0",    for SharePoint online

### Short version of my Question
I know this is probably butchered syntax but this explains what I am trying to do....
```typescript
//1. Use await syntax and get all fields into an array (filtering if possible), include properties of field like rest response if possible
const allFields = await sp.web.fields.getAll(); 

 //2. Define a new field I want to "check" and build if needed
let field1 = "Field1Title";

//3. If my new field is not in the array of existing fields, create it
if ( allFields.indexOf(field1) < 0 ) {
   const field: IFieldAddResult = await sp.web.fields.addText("My Field", 255, { Group: "My Group" });
}
```

### Longer explanation:
I'm not sure how to categorize the question and it may be more of pure JavaScript but since it's related to using this library here goes....

In some cases I have used pnp JS to get fields from a list using this syntax:

```typescript
const projectWeb = Web(MyWebURL);
let projectWeb.lists.getByTitle(MyListTitle);
projectWeb.fields.filter('Title or Modified or OtherField').get().then((response) => {
  // do something with fields
}).catch((e) => {
  // do something with error
});
```

In other parts of my code, I[ have used the await command](https://pnp.github.io/pnpjs/sp/fields/#add-a-new-field) to create a series of fields **in a particular order**... very important for calculated or other related fields.

```typescript
const field: IFieldAddResult = await sp.web.fields.addText("My Field", 255, { Group: "My Group" });
```

The challenge I'm having is when I'm trying to either provision or update fields on a list with a lot of fields.
1. Check/Create list
2. Create 20 columns on list
3. Create 5 views on list

Instead of using a 'try' command to see if each column or view exists individually, I thought it would be better to just do a single call to get all fields into an array and then just check the array and build each field only if needed.

### So the burning question:
Is there a way to get a list of all fields (and views as well) on a list using the await syntax so I can keep my code cleaner and easier to read?  NOTE:  I come from VBA background and educated myself using google and YouTube so I have trouble with async logic of JavaScript :).

I've tried something like the example below but seem to have a lot of issues trying to get anything to work... like using await when I'm not inside of an async function etc... (I could be butchering that explanation but hopefully someone knows what I'm talking about):

```typescript
const projectWeb = Web(MyWebURL);
let myListt = projectWeb.lists.getByTitle(MyListTitle);
myListt.fields.filter('MyTextField1 or MyTextField2 or MyTextField3').get().then((response) => {
  
   //Check response for field before creating using this syntax
   const field: IFieldAddResult1 = await myListt .fields.addText("MyTextField1", 255, { Group: "My Group" });
   const field: IFieldAddResult2 = await myListt .fields.addText("MyTextField2", 255, { Group: "My Group" });
   const field: IFieldAddResult3 = await myListt .fields.addText("MyTextField3", 255, { Group: "My Group" });

}).catch((e) => {
  // do something with error
});
```

**Comment by mikezimm** [comment]
Well, as luck would have it...

Within a few minutes after posting my question, I stumbled upon part of the docs that made a light go off and found solved my own question:

```typescript
    const thisWeb = Web(webURL);
    const ensuredList = await thisWeb.lists.ensure(myList.title);
    const listFields = ensuredList.list.fields;
    let fieldPropsToReturn = 'StaticName,Title,Hidden,Formula,Required,TypeAsString';
    let fieldsToReturn = `StaticName eq 'Title' or StaticName eq 'Editor';
    const  myFields = await listFields.select(fieldPropsToReturn ).filter(fieldsToReturn).get();
```

## which gives me what I was looking for:
![image](https://user-images.githubusercontent.com/49648086/86297047-5446c980-bbc8-11ea-8822-e63b0fe46084.png)

## Which yet again proves the "[Infinite monkey theorem](https://en.wikipedia.org/wiki/Infinite_monkey_theorem#:~:text=The%20infinite%20monkey%20theorem%20states,complete%20works%20of%20William%20Shakespeare)"

Give a programmer wanna be enough time, google, stackexchange, youtube... they can hack together anything :)

![image](https://user-images.githubusercontent.com/49648086/86297104-78a2a600-bbc8-11ea-9c67-e0dde58f5adb.png)

**Comment by koltyakov** [comment]
Hi @mikezimm!

It's really mostly generic JS questions you're rising. However, I'm not sure what you actually asked, even now looking at the second comment saying you've figured out. =) Anyways, glad you've found an answer.

To not to drop what I already started answering:

`async/await` is a syntax sugar that makes code elegant and logically sequential. But it doesn't change how promises work and you can easily combine the best from both, e.g having `await` and data mapping in the corresponding `then` callback.

> do a single call to get all fields into an array and then just check the array and build each field only if needed

With corresponding `select` and `expand` with is easily achievable. Then results are mapped or reduced as needed in the application logic flow.

> `allFields.indexOf(field1)`

This contains a mistake as `allFields` is an array of objects. `.find((o) => o.InternalName === 'YourField')` should be used instead. Or a `for/of` loop if an `await` is intended being used inside, etc.

> `.getAll()`

`.getAll()` is designed for different purposes for dealing with large lists. In most of the cases `.top(5000).get()` is better be used.

> get a list of all fields (and views as well) on a list using the await syntax so I can keep my code cleaner and easier to read

```typescript
const [ fields, views ] = await list
  .select('Fields/InternalName,Views/Title,Views/ViewFields/InternalName')
  .expand('Fields,Views,Views/ViewFields').get()
  .then((l) => {
    // or do some more robust transformations
    return [ l.Fields, l.Views ];
  });

console.log({ fields, views });
```

> using await when I'm not inside of an async function etc

`await` must be used in `async` functions. Currently, that's so. However, JS community tending to add global await support someday. E.g. that's how async can be added to the place you used awaits in promise resolve callback:

```typescript
.then(async (response) => {
  const r1 = await promise1();
  const r2 = await promise2();
});
```

**Comment by mikezimm** [comment]
@koltyakov , Thanks for the explanation!  Very much appreciated!
