### ISSUE TITLE
In @pnp/graph 2.0.6 version setEndpoint option is missing and couldn't retrieve users photo

### ISSUE THREAD

**Issue by Abilashvb** [pnp/pnpjs#1254]
Hi,

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0.6      ]

Please specify what version(s) of SharePoint you are targeting: [   1.10.0      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I have updated  @pnp/graph to latest version in my SPFx webpart. Previously I could switch graph version with the setEndPoint() method => graph.users.setEndpoint("v1.0"). Now its not possible.
And i could also get users photo by "users.getById(userId).photo.getBlob()" but now it is not working.

### Observed Behavior
 setEndPoint() and users.getById(userId).photo.getBlob() is missing.

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
Thanks for reporting:

- The setEndpoint method was moved to protected. Not sure why, likely a mistake as we moved to v2, updated that.
- The photo property wasn't being added by the photos sub-module, fixed that.

**Comment by Abilashvb** [comment]
@patrick-rodgers Thank you.
