### ISSUE TITLE
PNP Modern Search questions

### ISSUE THREAD

**Issue by krishnaVenkata** [pnp/pnpjs#1255]
###  Question

1.I am currently using **PNP Modern Search** webparts. As per requirement from my company component should not use any NLP services. Require help on identify NLP components. 

2. Currently **PNP Modern Search** is using **dangerouslySetInnerHTML** , which I want to sanitize. Please let me know possible alternatives.

**Comment by koltyakov** [comment]
Wrong repository. PnP Modern Search is located at https://github.com/microsoft-search/pnp-modern-search/

**Comment by sympmarc** [comment]
@krishnaVenkata, could you explain what NLP means in your case and what your actual requirements are? (I was Bingling NLP, and nothing I found seemed like a match.)

**Comment by krishnaVenkata** [comment]
@sympmarc  Natural language processing
