### ISSUE TITLE
Handling errors in catch

### ISSUE THREAD

**Issue by jimmywim** [pnp/pnpjs#1256]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

I don't know if I'm doing something wrong, but I'm wanting to inspect an error result in order to display a friendly message on the UI. If I catch a simple request, the 'caught' parameter appears to just be a formatted string that has embedded a JSON object in it.

Example (runnable within Chrome SP Editor plugin):
```
import { sp } from "@pnp/sp/presets/all";

(async () => {

  try {
    const list = await sp.web.lists.getByTitle("FooBar").get();
    console.log("List details: ", list);
  } catch (err) {
    console.log("Error: ", err);
  }
})().catch(console.log)
```

And you'll observe that `err` is this:
```
Error:  Error: Error making HttpClient request in queryable [404]  ::> {"odata.error":{"code":"-1, System.ArgumentException","message":{"lang":"en-US","value":"List 'FooBar' does not exist at site with URL 'https://XXXXXX.sharepoint.com/'."}}}
    at new HttpRequestError (sp.es5.umd.bundle.js:1808)
    at Function.eval (sp.es5.umd.bundle.js:1823)
    at step (sp.es5.umd.bundle.js:726)
    at Object.eval [as next] (sp.es5.umd.bundle.js:707)
    at fulfilled (sp.es5.umd.bundle.js:697)
```

I'd really like `err` in the catch so simply be that referenced object, so I would just return out `err.message.value` or some such.

**Comment by koltyakov** [comment]
Hi @jimmywim,

You can actually get more from the error than just a message:

```typescript
sp.web.lists.getByTitle('No such a list').get()
  .then(console.log)
  .catch((err) => console.log(err.response))
```

![image](https://user-images.githubusercontent.com/7816483/86604778-7bc5d980-bfae-11ea-9f33-b6d192a67ebb.png)

So, if it's just about status code, it's there.

**Comment by jimmywim** [comment]
Can we get the error text returned from SharePoint though? Specfically, from my example, the text: `"List 'FooBar' does not exist at site with URL 'https://XXXXXX.sharepoint.com/'`. Especially helpful as this is localized.

**Comment by patrick-rodgers** [comment]
Reopening this to remind us to create an error handling article in the docs to cover this as well.
