### ISSUE TITLE
Copy a page using "fromHtml" method

### ISSUE THREAD

**Issue by raymondlittle100** [pnp/pnpjs#126]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.0.5   ]

I originally encountered this with 1.0.4 so I upgraded to 1.1.0 but when I tried to use this I found an issue getting the page which I reported separately 

### Expected / Desired Behavior / Question
Trying to use the ClientSidePage toHtml() and fromHtml to create a copy of the page with all web parts. 

### Observed Behavior
This works fine until you add a text web part to the page and then it only ever copies the first column so if you have two or three columns no other web parts are added. 

### Steps to Reproduce
Created a test web part which initializes PnP context and passes to a react component. This component uses PnP to get page and the details using .toHtml(). Next create a new page with date time stamp and use .fromHtml()

public async loadPageDetails()
  {
    try
    {
      const page = await ClientSidePage.fromFile(
        this.props.spRest.web.getFileByServerRelativeUrl(this.props.pageUrl));        
      
      let newPageName = new Date().toISOString();
      newPageName =newPageName.replace(".","_");
      newPageName =newPageName.replace(":","_");
      newPageName =newPageName.replace(":","_");
      newPageName = `${newPageName}.aspx`;
      let newLocationPage = await this.props.spRest.web.addClientSidePage(newPageName);
      
      //copy the settings from the current page to the new/existing page
      newLocationPage = newLocationPage.fromHtml(page.toHtml()); 

      console.log(newLocationPage)
      //save the updated page
      const saveResults:ItemUpdateResult = await newLocationPage.save()
    }
    catch(error)
    {
      console.log(`Error ${error}`);
      console.log(error);
      if(error.data != null)
      {
        let message = error.data.responseBody["odata.error"].message.value;
        console.log(message);
      }
    }

In the first round of testing create a page with two or more columns. Add any web parts except the text one to the left and right columns. Run the web part and you should get the results below

Source page
![sourcepagenotextwebpart](https://user-images.githubusercontent.com/23637375/41241134-2180feb4-6d94-11e8-90bb-d6470679c642.PNG)

New page
![copiedpagenotextwebpart](https://user-images.githubusercontent.com/23637375/41241142-279c4a56-6d94-11e8-8086-d31c7a06b6be.PNG)

Now update the source page adding the text web part and try again

Source page
![sourcepagewithtextwebpart](https://user-images.githubusercontent.com/23637375/41241168-33d6c012-6d94-11e8-9f77-6a53e3bb370c.PNG)

New page
![copiedpagewithtextwebpart](https://user-images.githubusercontent.com/23637375/41241175-37a045c4-6d94-11e8-9283-8d1465e76e31.PNG)

Only the web parts on the LHS column are present

**Comment by patrick-rodgers** [comment]
I am not sure this is advisable as you are copying all the webpart instance ids using this technique. I get what you are trying to do but this wasn't really the intent of these methods. Will try and have a look but this isn't a high priority use case. Better would be a clone method that treats each of the parts as objects and re-ids them.

**Comment by raymondlittle100** [comment]
ah my bad. I was looking for a way to move a page from one team site to another and i was able to transfer the metadata but needed a way to re-configure the sections and web parts. 

There doesn't seem to be anyway to do this using the REST API so was trying to do it using these methods. Unless you know another way might have to do it manually

**Comment by patrick-rodgers** [comment]
I found a bug with how we are parsing the text web part's content which I am working to resolve. Nothing I am aware of has changed, so it was likely always broken like this. But will get that fixed.

However, trying to copy pages using from and to html is likely still not going to work due to webpart instance ids.

**Comment by raymondlittle100** [comment]
Thanks for the update. Was thinking if you got this fixed i would create the page from html then look over components and generate new guids, do you think that would be a better solution?
