### ISSUE TITLE
Getting error after adding import "@pnp/sp/sputilities";

### ISSUE THREAD

**Issue by manojkumarrai007** [pnp/pnpjs#1262]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0.6      ]

Please specify what version(s) of SharePoint you are targeting: [   SP2019      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
After adding import "@pnp/sp/sputilities"; there should not be build error.

### Observed Behavior
After creating spfx webpart using yo @microsoft/sharepoint by selecting nojavascript framework or react framework, I installed @pnp/sp package. and imported it in webpart by adding two lines,
import {sp} from '@pnp/sp';
import "@pnp/sp/sputilities";
After adding first line there is no build error. but when I am adding second line import "@pnp/sp/sputilities"; it is giving more than 235 errors which are like 
Error - typescript - node_modules\@pnp\sp\fields\types.d.ts(164,29): error TS1110: Type expected.

### Steps to Reproduce
simply, create new webpart using yomen generator and install @pnp/sp and  add this line import "@pnp/sp/sputilities";
![error](https://user-images.githubusercontent.com/38662773/87122217-0efa5a00-c2a2-11ea-8bd1-07d18d995fbb.jpg)

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
This is unfortunately a known issue due to versions of TypeScript. We have [a work around described in the docs](https://pnp.github.io/pnpjs/SPFx-on-premises/). Please give that a try.

**Comment by manojkumarrai007** [comment]
Hi Patrick,
thank you for the reply and providing me the guidance. I gone through the documents and i am happy to say that the errors has gone. but I am stuck in other issue. After doing all the steps, there is no build error and component is loading fine in Firefox and Edge browsers. but it is giving error in IE 11. IE 11 is the most used version in our company. After troubleshooting i found that in IE 11 due to line
 import "@pnp/sp/sputilities"; it is not rendering. attached is the screenshot of the error in IE 11. Would like to know if this is known issue or it does not support IE11. 
![error2](https://user-images.githubusercontent.com/38662773/87933624-3b388680-caab-11ea-87ee-aa46dabf6914.jpg)

**Comment by juliemturner** [comment]
@manojkumarrai007 please see the information about [IE11 Mode](https://pnp.github.io/pnpjs/concepts/ie11-mode/) as well as our complete statement on [Polyfils](https://pnp.github.io/pnpjs/concepts/polyfill/)

**Comment by patrick-rodgers** [comment]
Going to close this as answered, thanks!
