### ISSUE TITLE
How to set thumbnail image and page description for sharepoint modern pages programmatically?

### ISSUE THREAD

**Issue by PrathyushP95** [pnp/pnpjs#1263]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.5 pnp-commonjs]

Please specify what version(s) of SharePoint you are targeting: [2016]

Hi, I'm trying to set thumbnail image and page description programmatically using pnpjs. By default it is picking banner image as thumbnail image and first paragraph in page as page description. How can i update those fields?
![Capture](https://user-images.githubusercontent.com/20680181/87145594-2e57ae00-c2c7-11ea-994b-facd12757417.PNG)

**Comment by patrick-rodgers** [comment]
Have updated library to set the description, will be in 2.0.7 release. Had no luck determining how to set the thumbnail so that functionality is not included at this time.

**Comment by patrick-rodgers** [comment]
Reopening this. Talked to some folks and have a potential path forward on the thumbnail. Will see if it can work, won't block the next release.
