### ISSUE TITLE
Documentation: sp\client-side-pages.html

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/pnpjs#127]
const page = await ClientSidePage.fromFile(sp.web.getFileByServerRelativeUrl("/sites/dev/SitePages/ExistingFile.aspx"));

This line give an error unexpected json token when the ExistingFile.aspx page contains webparts and I am trying to read the page
Uncaught (in promise) SyntaxError: Unexpected token . in JSON at position 281
    at JSON.parse (<anonymous>)
    at Function.ClientSidePage.escapedStringToJson (clientsidepages.ts:265)
    at ClientSideWebpart.fromHtml (clientsidepages.ts:812)
    at clientsidepages.ts:333
    at getBoundedDivMarkup (clientsidepages.ts:136)
    at ClientSidePage.fromHtml (clientsidepages.ts:315)
    at clientsidepages.ts:357

**Comment by harshdamaniahd** [comment]
yes it is a modern page and  the page contains simple text and image webpart
  const page2 = await ClientSidePage.fromFile(this.props.spRest.web.
      getFileByServerRelativeUrl(`/Sites/test/SitePages/Home.aspx`));

this statement fails 
Uncaught (in promise) SyntaxError: Unexpected token . in JSON at position 281
at JSON.parse ()
at Function.ClientSidePage.escapedStringToJson (clientsidepages.ts:265)
at ClientSideWebpart.fromHtml (clientsidepages.ts:812)
at clientsidepages.ts:333
at getBoundedDivMarkup (clientsidepages.ts:136)
at ClientSidePage.fromHtml (clientsidepages.ts:315)
at clientsidepages.ts:357

**Comment by patrick-rodgers** [comment]
Can you capture the actual response? I am curious to see what the JSON parser is trying to parse and failing on. I.e. what is at position 281 etc.

**Comment by harshdamaniahd** [comment]
![image](https://user-images.githubusercontent.com/11780473/41299683-a16dbd7c-6e81-11e8-8980-3a5f07138eec.png)

**Comment by harshdamaniahd** [comment]
It works when there is only text on page

**Comment by harshdamaniahd** [comment]
@patrick-rodgers  is this sufficient or do u need some more details ?

**Comment by patrick-rodgers** [comment]
Wpuld be super helpful to have the full string of the page content. That variable doesn't mean anything goes to me as is.

Thanks,

Patrick

(Sent from phone, pardon spelling errors)
________________________________

**Comment by harshdamaniahd** [comment]
json variable is empty actually.I guess there is something wrong here as well
![image](https://user-images.githubusercontent.com/11780473/41331518-093359d8-6ef7-11e8-89eb-d920f102ea44.png)

When we have  only text webpart on page everything works fine . if we add any other webpart it breaks at this section as well

**Comment by harshdamaniahd** [comment]
i downgraded @pnp/sp to   "@pnp/sp": "^1.0.4"
and now it works 
![image](https://user-images.githubusercontent.com/11780473/41343943-840c57e2-6f1d-11e8-8d97-b9c374257138.png)

**Comment by patrick-rodgers** [comment]
Are you only upgrading one of the packages? You need to upgrade the entire set of @pnp packages each time. They all need to be at the same version, i.e. 1.1.1 for latest.
