### ISSUE TITLE
Question:  Error trapping when batch creating list items

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1275]
### Category
- [X] Question

### Version
    "@pnp/sp": "^2.0.6",
    Target:  SPO

### Expected / Desired Behavior / Question
I made a function to make it easier to batch create list items using the @pnp.sp library.

My "Big Idea" goal is for the function to return an array of all the steps (items it attempted to create), and show what was executed... and more importantly, a **_'human readable'_** itemized list of what things failed and why.

In order to test my function, I created some known failure modes so I could see the result and trap the errors.
In my case, I have an array of objects representing the items to add which include "good" item structures, and a couple with common errors such as:

1. Incorrect spelling of the column name
2. Trying to set an array value (like multi-select choice column) using a string
3. Trying to set a Url field with a string

### Observed Behavior

I'm not sure if it's my logic or a bug or a limitation, but my result array:
- Shows all the valid items
- Unfortunately it only shows the first error.
- It does cycle through all elements in my array and creates all valid items no matter the order of valid and invalid items.

#### Here's my array object with sample items.
The one with "TitleX" as a property is the invalid field name.
If you look at property Category1 in first item, it shows the valid structure for a Multi-select Choice column.
The second item shows my intentional TypeO attempting to save that column like a text field.

```typescript
export const TMTDefaultProjectItems  = [
    { Title: "Training", Everyone: true, Story: 'Training', Chapter: 'Yet more training :)', Category1: { results: ['Training']}},
    { Title: "Category Column Error - not in results", Everyone: true, Story: 'Webpart', Chapter: 'Example', ProjectID1: 'mask=B\\atch99999', ProjectID2: 'My prefix:...', Category1: 'TestWebpart'},
    { TitleX: "Title Column Error", Everyone: true, Story: 'Webpart', Chapter: 'Example', ProjectID1: 'mask=B\\atch99999', ProjectID2: 'My prefix:...', Category1: { results: ['TestWebpart']}},
    { Title: "Email triage", Everyone: true, Story: 'Daily', Chapter: 'Email triage', Category1: { results: ['Daily']}},
    { Title: "Break", Everyone: true, Story: 'Daily', Chapter: 'Break', Category1: { results: ['Daily']}},
    { Title: "Team Meeting", Everyone: true, Story: 'Meetings', Chapter: 'Team Meeting', Category1: { results: ['Meetings']}},
    { Title: "Example for Mask and Prefix in ProjectID columns", Everyone: true, Story: 'Webpart', Chapter: 'Example', ProjectID1: 'mask=B\\atch99999', ProjectID2: 'My prefix:...', Category1: { results: ['TestWebpart']}},

];
```

### Here is a summary of the logic in my function below:

1. I create the batch.
2. Then use the for loop to add each item to list.items.inBatch
- My first 'Try' loop may not be necessary but I am pretty new at this :)
3. If inBatch works, a note is added to my statusLog.
4. If inBatch fails (based on my intentional errors), it does not catch the error or add it to the log.
5. After all items are in the batch, I try and await batch.execute();
6. At this point, the second try/catch does catch one error message... the first one.
7. It puts the error message in statusLog array as expected... but only the first error.

### My Question
Is there a fault in my logic or just a limitation or feature of the sp library?

### My function
```typescript
export async function addTheseItemsToList( myList: IMyListInfo, thisWeb, ItemsToAdd: any[], alertMe: boolean, consoleLog: boolean, alwaysCreateNew = true ): Promise<IListLog[]>{

    let statusLog : IListLog[] = [];
    console.log('Starting addTheseItemsToList', ItemsToAdd);

    let list = thisWeb.lists.getByTitle(myList.title);
    const entityTypeFullName = await list.getListItemEntityTypeFullName();

    let batch = thisWeb.createBatch();
  
    for (let item of ItemsToAdd) {
    //, Category1: { results: ['Training']}
        let thisItem = item[Object.keys(item)[0]];
        try {
            list.items.inBatch(batch).add( item , entityTypeFullName).then(b => {
                statusLog = notify(statusLog, null, null,  'Created Item', thisItem, null);
            });
        } catch (e) {

            // DO NOT SEEM TO CATCH ANY ERRORS HERE SO THIS MAY BE USELESS
            let errMessage = getHelpfullError(e, alertMe, consoleLog);
            statusLog = notify(statusLog, null, null,  'Problem Creating Item: ' + errMessage, thisItem, null);

        }

    }

    try {
        await batch.execute();
        alert(`Just letting you know we added your items`);
    } catch (e) {
        //ONLY SEEMS TO CATCH FIRST ERROR IN BATCH.
        //OTHER BATCH ITEMS GET PROCESSED BUT ONLY FLAGS FIRST ONE.
        //CONFIRMED LATER ITEMS IN ARRAY AFTER ERROR STILL GET PROCESSED, JUST NOT ERRORED OUT
        let errMessage = getHelpfullError(e, alertMe, consoleLog);
         statusLog = notify(statusLog, null, null,  'Problem processing Batch', errMessage, null);
         alert('Had problem with adding items' );
    }

    //let returnArray: [] = [];
    console.log('addTheseItemsToList', statusLog);

    return statusLog;
}
```

Thanks for any help or guidance!

**Comment by koltyakov** [comment]
Hi @mikezimm, 

The first, as well as the second try-catch, are not needed, their code is unreachable. To be more precise, `batch.execute` won't ever fail or rejected and try around it won't catch anything; requests sent in a batch also won't throw an exception (unhandled catches) as try-catch is around a promise without awaiting, but awaiting is not applicable with `.inBatch` flow (`await` in such requests should not be used as it will deadlock the code flow as batch promises start resolving after the batch is executed).

[This sample](https://github.com/pnp/pnpjs/issues/548#issuecomment-472329724) shows how to handle errors with batches, just a basic idea with a promise wrapper hapler.

In two words. The errors should be checked in individual request which is sent in a batch, but in `.catch()` the same way as the response values are treated in `.then()`s and put in a variable. Then after `batch.execute()` is resolved variables with results and errors are checked or used.

**Comment by mikezimm** [comment]
@koltyakov , I will try to look into it a little more closely... I can follow some of the example but other parts I'm not yet getting.  It's my lack of good knowledge of async functions.

I did have one question about your comment:
_The first, as well as the second try-catch, are not needed, their code is unreachable. **To be more precise, batch.execute won't ever fail or rejected**_

In the screenshots below, I have the console output of 2 different examples showing the errors I was trying to trap.  Each screenshot shows
1. the items expanded
2. followed by the error that gets thrown
3. finally the "statusLog"

If you look at the expanded statusLog, the last item shows "Problem processing Batch" (yellow arrow in screenshots).
This is generated by the 2nd try/catch "catch"... so it is catching something or else that line would not have been added.

So that being said, am I miss-understanding your comment that the _**batch.execute won't ever fail or rejected**__?

Thanks again for your time!


## Case 1:  7 items (top expanded console object), 2 errors, (bottom expanded console object)
- first error (in item index 1) looks cropped in my sample code but is trying to save text to multi-select choice.
- second error (in item index 2) is just TitleX not being a valid field name
![image](https://user-images.githubusercontent.com/49648086/87728647-8a23aa80-c791-11ea-8d0f-d2b6794e4db8.png)

## Case 2:  6 items (top expanded console object), 1 errors, (bottom expanded console object)
- first error (in item index 1) is just TitleX not being a valid field name
![image](https://user-images.githubusercontent.com/49648086/87728658-8e4fc800-c791-11ea-83ee-3f33a416cb00.png)

**Comment by koltyakov** [comment]
It could have been that error handling for `batch.execute` was augmented (e.g. "also throw an exception if any of the requests had an error in the response") and I missed that. Yep, looks like it's the case which I miserably missed so my phrase "`batch.execute` won't ever fail or rejected" is not correct.

CC @patrick-rodgers, @juliemturner (might also be interesting to read further investigation)

Currently, I observe a weird behavior that looks like an issue to me. However, not sure that this is on the library end but not the API. After an exception in a sequence of requests, all subsequent requests are resolved as failed with `[500] Internal Server Error ::> {"error":{"code":"-1, System.IndexOutOfRangeException","message":{"lang":"en-US","value":"Index was outside the bounds of the array."}}}`.

```typescript
import { sp } from '@pnp/sp/presets/all';

(async () => {

  const w = (p: Promise<any>) => {
    p.then((r) => console.log('OK:', r))
      .catch((ex) => console.log('Err:', ex))
  };

  const b = sp.web.createBatch();
  w(sp.web.lists.getByTitle('Site Pages').select('Title').inBatch(b).get()); // <- should be OK | and is OK
  w(sp.web.lists.getByTitle('Site Pages').select('Id').inBatch(b).get()); // <- should be OK | and is OK
  w(sp.web.lists.getByTitle('Error No Such List').select('Title').inBatch(b).get()); // <- should be 404 | and is 404
  w(sp.web.lists.getByTitle('Error No Such List 1').select('Title').inBatch(b).get());  // <- should be 404 | but 500 index issue
  w(sp.web.lists.getByTitle('Site Pages').select('Id').inBatch(b).get()); // <- should be OK | but 500 index issue

  await b.execute().catch((ex) => { console.log('Batch error:', ex) }); // <- If there is an error catched only the first one

})().catch((ex) => console.log('Global error:', ex));
```

This ends up with:

![image](https://user-images.githubusercontent.com/7816483/87757454-5721fb00-c813-11ea-88a3-86f20ca6be7f.png)

However, this doesn't look a library fault as the actual response which is parsed by PnPjs batch methods is:

![image](https://user-images.githubusercontent.com/7816483/87757614-9bad9680-c813-11ea-8a55-2d4f7ec669d1.png)

Checked the same on a random On-Prem 2016:

![image](https://user-images.githubusercontent.com/7816483/87757934-3312e980-c814-11ea-9852-6d9e9662ab71.png)

Batch error returns the fists one, which might be OK as anyways is better be ignored with an empty catch (`.catch(() => { /**/ })`) as errors are easily to process as individual connected with a specific request item.

For me, it looks as batches are completely broken in SPO right now (checked on multiple environments) and only applicable if you know that all the requests will end up successfully. That definitely is not something that can be fixed in a library as a server-side issue, but we can reference this to the product team. It could have been a design decision (arguably weird one, IMO) to fail everything after a first error, but more likely it's a bug in the API which was recently introduced, as I believe it previously worked in SPO and works in On-Prem.

**Comment by patrick-rodgers** [comment]
Great conversation, but agree unfortunately this isn't something we can really resolve from a library perspective. Going to close this for now, but will keep an eye out for similar issues. Thanks!
