### ISSUE TITLE
Typescript error: Top-level 'await' expressions are only allowed when the 'module' option is set to 'esnext'...

### ISSUE THREAD

**Issue by Rolando-Barbella** [pnp/pnpjs#1278]
Hello, thanks for creating this, I´m trying to test the library on a project build with yeoman, react, and typescript, but I get the following TS error that blocks me

`Top-level 'await' expressions are only allowed when the 'module' option is set to 'esnext' or 'system', and the 'target' option is set to 'es2017' or higher.`

```
import { graph } from "@pnp/graph";
import { GroupType } from '@pnp/graph/groups';

const groupAddResult = await graph.groups.add("GroupName", "Mail_NickName", GroupType.Office365);
const group = await groupAddResult.group();
```

Is there a workaround for this? 

Thanks

**Comment by koltyakov** [comment]
Top-level `await`s require a specific build configuration and not available by default in most of the pipelines.
For the time being, `await`s are better be used in `async` functions.

```typescript
const foo = async () => {
  const bar = await baz();
  // do smt with bar
};
```

**Comment by Rolando-Barbella** [comment]
Cool, thanks
