### ISSUE TITLE
Question: Best way to set up unit testing with code that uses pnpjs?

### ISSUE THREAD

**Issue by BrianDeJesus** [pnp/pnpjs#1281]
I'm having trouble importing pnp modules and using them in typescript unit test suites with mocha and chai and I see that you are using mocha and chai in this repo as well. I'm trying to eventually incorporate the async functions from pnp js so i can test without deploying the source code to SharePoint. My unit tests work(non async functions that don't use pnp js) until I try to import and incorporate and use any pnp js modules or functions that use those modules in the test suite. I get a vague error that says Error: not supported... from mocha in node modules. I don't expect someone to debug that so my main question is: What is the best way to setup a local node environment to run test suites that use pnpjs? Thanks!

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     ^2.0.6    ]

Please specify what version(s) of SharePoint you are targeting: [    2016 on prem  ]

### Expected / Desired Behavior / Question

What is the best way to setup a local node environment to run test suites that use pnpjs with mocha and chai?

### Observed Behavior
My test suite works until i try to use pnpjs modules and import them in a test file. Maybe there's something i'm missing.
My current dependencies include: 
```json
  "devDependencies": {
    "@pnp/sp": "^2.0.6",
    "@types/chai": "^4.2.11",
    "@types/mocha": "^8.0.0",
    "chai": "^4.2.0",
    "mocha": "^8.0.1",
    "ts-node": "^8.10.2",
    "typescript": "^3.9.6"
  }
```

I'm running the test with
```json
    "test": "mocha -r ts-node/register 'tests/*.spec.ts'",
```

**Comment by koltyakov** [comment]
With mocha, `-commonjs` versions might be required or some extra configurations.
Please check [this configuration of tests with PnPjs in Mocha](https://github.com/koltyakov/sp-rest-proxy/blob/master/test/proxy.spec.ts). As your target environment is On-Prem, authentication will be a thing too.

**Comment by BrianDeJesus** [comment]
@koltyakov  Thank you! I will look into that and node-sp-auth
