### ISSUE TITLE
ClientSideText causing additional <p></p> tags to be added.

### ISSUE THREAD

**Issue by PrathyushP95** [pnp/pnpjs#1282]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.5 pnpjs-common]

Please specify what version(s) of SharePoint you are targeting: [2016]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

Hi,

ClientSideText is adding additional `<p></p>` tags.

`section.addControl(new ClientsideText("<h2>Sub Heading</h2>"));`

This creates an additional `<p></p>` tags in sharepoint console which results in blank spaces.

### Observed Behavior
innerHtml is formed as 
`<p></p><h2>Sub Heading</h2><p></p>`
which causes extra blank spaces at the top and bottom of the heading.

Could you please help to find a solution for this.

**Comment by patrick-rodgers** [comment]
Removed the logic that was in place to add surrounding <p> tags to the value supplied to client side text part. When we first reverse engineered the API those p tags seemed to be required (client text parts didn't appear on the page without them). In re-testing now that no longer appears to be the case and we can remove the logic.

The reason you were seeing double p tags is that the server saw "unclosed p tag"<h2>Sub Heading</h2>"orphan p tag closing" and it closed the two surrounding tags. That hints to me there is server logic to parse/validate the text that wasn't present before.

Update will be part of 2.0.12.
