### ISSUE TITLE
How to access files from different sites?

### ISSUE THREAD

**Issue by PrathyushP95** [pnp/pnpjs#1283]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.5 pnpjs-common]

Please specify what version(s) of SharePoint you are targeting: [2016]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

Hi,

I wanted to access an image in dev site from my test site.

I'm creating my page in test site and would like to set the banner image of that page as,

`await page.setBannerImage("sites/dev/samplelib/image.jpg");`

I tried to pass the relative url as 'sites/dev/samplelib/image.jpg' which gave me below error.

`{"errorType":"Error","errorMessage":"Error making HttpClient request in queryable [400] Bad Request ::> {\"odata.error\":{\"code\":\"-2147024809, System.ArgumentException\",\"message\":{\"lang\":\"en-US\",\"value\":\"Server relative urls must start with SPWeb.ServerRelativeUrl\"}}}`

Is there any way to get this fixed.

**Comment by koltyakov** [comment]
To operate in the context of different SPWeb web objects has to be constructed.

```typescript
const w1 = Web('https://contoso.sharepoint.com/sites/site/web1');
const w2 = Web('https://contoso.sharepoint.com/sites/site/web2');

// w1.getFileByServerRalativeUrl('/sites/site/web1/path_to_file')...
// w2.getFileByServerRalativeUrl('/sites/site/web2/path_to_file')...
```

**Comment by PrathyushP95** [comment]
Thanks for your response @koltyakov ,

I've constructed SPWeb web object for my dev site as
`const w1 = await Web('https://domain.sharepoint.com/sites/dev/');`
`var file = w1.getFileByServerRelativeUrl('/sites/dev/foldername/image.jpg');`
`console.log(file);`

This gives me the below output.

```
_data: {
    cloneParentWasCaching: false,
    options: { headers: {} },
    parentUrl: 'https://domain.sharepoint.com/sites/dev/_api/web',
    parser: ODataParser {},
    query: Map {},
    url: "https://domain.sharepoint.com/sites/dev/_api/web/getFileByServerRelativeUrl('%2Fsites%2Fdev%2Ffoldername%2Fimage.jpg')",
    useCaching: false
  },
  _forceCaching: false,
  delete: [Function]
}
```

How can i use this image as a banner image for modern page in my test site?

I want to use this image as,
`page.bannerImageUrl = '/sites/dev/foldername/image.jpg'`
or
`page.setBannerImage( '/sites/dev/foldername/image.jpg');`
in my test site

**Comment by juliemturner** [comment]
@PrathyushP95 -- have you tried the docs under [Page Operations](https://pnp.github.io/pnpjs/sp/clientside-pages/#page-operations)?

**Comment by PrathyushP95** [comment]
Hi @juliemturner , I can see in the doc that "Banner images need to exist within the same site collection as the page where you want to use them".
In my case i have multiple site collections and i wanted to use my banner image as a global asset so that there is no need to upload the image in all the site collections. Is there any way to achieve this?

**Comment by juliemturner** [comment]
I do not know of any way to achieve this no...

**Comment by patrick-rodgers** [comment]
It appears the original question is answered so going to close this thread. Appreciate the good conversation from all! Thanks!
