### ISSUE TITLE
Setting TextField value if a URL parameter is present?

### ISSUE THREAD

**Issue by mpalmer-sps** [pnp/pnpjs#1286]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    16.8.5     ]

Please specify what version(s) of SharePoint you are targeting: [    Online     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I'm trying to create a form with a textfield control that either updates information from a list or creates a new row in the list. I'm using the PNP library to make async calls to the list after componentDidMount. 
 
The core of what I'm attempting is this:
I'm trying to see if a URL querystring parameter does exist (i.e. ID=1 ) then I'm assuming (because it's there) that the user wants to update or read and existing value. 
If the ID parameter is missing then I make no query to the list and leave the value of the textbox blank (meaning a new row in the list will be created when the user fills out the form and hits submit).

### Observed Behavior
The code below has a single controlled textbox and it works **until** I try to set the state to allow for a (later) update, creation or adding a new row in the list.  If I set the value to the listData state on the "blank" version of the textbox then the page complains that listData is null and stops loading.

My question is: Is there a better way to pre-populate the values in controls without errors but **not** pre-populate if a partcular flag is set like a missing querystring (and leave the Form in place but blank)?

Or am I just making this too complicated and should I create three forms, 1 for updating existing records, 1 for reading existing and 1 for creating new records. The two are so similar in functionality that I thought it would be better to combine with a simple based on the querystring.

![image](https://user-images.githubusercontent.com/12634625/87911748-fa942b00-ca20-11ea-931a-beb00bf71a06.png)

**Comment by juliemturner** [comment]
@mpalmer-sps Unfortunately this question isn't really about using the PnPJS library you're question is really about how to properly write ReactJS code.  I think your best bet would be to submit this question (nicely detailed I might add) to a place like StackOverflow where people help with general programming questions. You'll want to tag it specifically with the ReactJS library as I think that's the area you're having difficulty with.

**Comment by ncmadhan1989** [comment]
> Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
> needs please complete the below template to ensure we have the details to help. Thanks!
> 
> **Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**
> 
> ### Category
> * [ ]  Enhancement
> * [ ]  Bug
> * [X ] Question
> * [ ]  Documentation gap/issue
> 
> ### Version
> Please specify what version of the library you are using: [ 16.8.5 ]
> 
> Please specify what version(s) of SharePoint you are targeting: [ Online ]
> 
> _If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._
> 
> ### Expected / Desired Behavior / Question
> I'm trying to create a form with a textfield control that either updates information from a list or creates a new row in the list. I'm using the PNP library to make async calls to the list after componentDidMount.
> 
> The core of what I'm attempting is this:
> I'm trying to see if a URL querystring parameter does exist (i.e. ID=1 ) then I'm assuming (because it's there) that the user wants to update or read and existing value.
> If the ID parameter is missing then I make no query to the list and leave the value of the textbox blank (meaning a new row in the list will be created when the user fills out the form and hits submit).
> 
> ### Observed Behavior
> The code below has a single controlled textbox and it works **until** I try to set the state to allow for a (later) update, creation or adding a new row in the list. If I set the value to the listData state on the "blank" version of the textbox then the page complains that listData is null and stops loading.
> 
> My question is: Is there a better way to pre-populate the values in controls without errors but **not** pre-populate if a partcular flag is set like a missing querystring (and leave the Form in place but blank)?
> 
> Or am I just making this too complicated and should I create three forms, 1 for updating existing records, 1 for reading existing and 1 for creating new records. The two are so similar in functionality that I thought it would be better to combine with a simple based on the querystring.
> 
> ![image](https://user-images.githubusercontent.com/12634625/87911748-fa942b00-ca20-11ea-931a-beb00bf71a06.png)

your state doesn't have an object Fname,mostly it causes the error
