### ISSUE TITLE
Get Site Page Content using pnpjs unable to update to Angular app

### ISSUE THREAD

**Issue by gurramsubrahmanyam** [pnp/pnpjs#1287]
we are trying to bind the sp.web.getFileByServerRelativeUrl('/SitePages/page.aspx').getText().then(console.log))  which is coming content as sharepoint page but when we try to append to page we are not able fetch any content in the app.
 
"<%@ Page language="C#" Inherits="Microsoft.SharePoint.WebControls.ClientSidePage, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %><%@ Register Tagprefix="SharePoint" Namespace="Microsoft.SharePoint.WebControls" Assembly="Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<html xmlns:mso="urn:schemas-microsoft-com:office:office" xmlns:msdt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"><head>

<title>Arxway</title></head>

"

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of SharePoint you are targeting: [         ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!

**Comment by gurramsubrahmanyam** [comment]
Updating type

**Comment by juliemturner** [comment]
I'm not really sure, as you don't explain, what you're trying to accomplish but based on the URL did you take a look at the docs for [Client-Side pages](https://pnp.github.io/pnpjs/sp/clientside-pages/)?

**Comment by patrick-rodgers** [comment]
Any updates @gurramsubrahmanyam? From your description we aren't certain what you are attempting to do.

**Comment by juliemturner** [comment]
Assuming that you have gotten the assistance you need and am closing this issue.  If you have a new question, please feel free to submit it and reference this closed issue.

**Comment by gurramsubrahmanyam** [comment]
No its not resolved my issue but we found a workaround for that issue. instead of site pages we have created list and added content rendered in angular app.
