### ISSUE TITLE
SPFetchClient Issue with node js and SharePoint On Prem. TypeError: Cannot read property 'headers' of undefined  at SPFetchClient

### ISSUE THREAD

**Issue by BrianDeJesus** [pnp/pnpjs#1289]
### Category
- [ ] Enhancement
- [ x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 
```json
  "@pnp/nodejs": "^2.0.6",
    "@pnp/nodejs-commonjs": "^2.0.6",
    "@pnp/sp": "^2.0.6",
    "@pnp/sp-commonjs": "^2.0.6",
    "@types/chai": "^4.2.11",
    "@types/mocha": "^8.0.0",
    "chai": "^4.2.0",
    "dotenv": "^8.2.0",
    "mocha": "^8.0.1",
    "node-sp-auth": "^3.0.1",
    "sp-rest-proxy": "^3.0.1",
    "ts-node": "^8.10.2",
    "typescript": "^3.9.6"

```
Please specify what version(s) of SharePoint you are targeting: [     on premise 2016    ]

### Expected / Desired Behavior / Question
I'm trying to authenticate to SharePoint from node js with the SPfetchclient. Generally, I'm trying to run unit tests with mocha and use sharepoint rest queries(using this library) in them. Is there a way I can do this without the FetchClient?

### Observed Behavior
I keep getting: TypeError: Cannot read property 'headers' of undefined
    at SPFetchClient.<anonymous>...
node_modules\@pnp\nodejs-commonjs\net\spfetchclient.js:83:34)

I've tried using node-sp-auth and sp-rest-proxy to pass the correct headers to the fetch client factory, but the fetch client seems to never configure the settings properly and i get that error everytime. Maybe I'm doing something wrong.

### Steps to Reproduce
Use the FetchClient with on premise SharePoint 2016. Code:
```javascript
require('dotenv').config({ path: '../.env' });
import * as spauth from 'node-sp-auth';

import { sp } from "@pnp/sp-commonjs/presets/all";
import "@pnp/sp-commonjs/webs";
import { SPFetchClient } from "@pnp/nodejs-commonjs";

const theUrl = "https://mysite.mydomain.com/website";

    sp.setup({
        
   
        sp: {
            fetchClientFactory: () => {
                return new SPFetchClient(theUrl, process.env.CLIENT_ID, process.env.CLIENT_KEY);
            },
            baseUrl: theUrl,
            headers: {
                Accept: 'application/json;odata=verbose'
              },
        },
    });
    console.log(sp);
    sp.web.get()
 

.then((result) => {
    console.log(result);
    
})

.catch((error) => {
    console.log("there was an error");
    console.log(error);
})

```

Thank you

**Comment by koltyakov** [comment]
On-Prem is not supported with `@pnp/nodejs`. For On-Prem please consider [pnp-auth](https://github.com/SharePoint-NodeJS/pnp-auth).

**Comment by BrianDeJesus** [comment]
Thanks @koltyakov  Are we going to see support in pnp-auth for pnp/sp version 2 in the near future?

**Comment by koltyakov** [comment]
@BrianDeJesus it's currently supported with taking [these steps](https://github.com/SharePoint-NodeJS/pnp-auth#pnpjs-v2).

Also, it's likely that we soon will merge and adapt [that PR](https://github.com/SharePoint-NodeJS/pnp-auth/pull/9) after @s-KaiNet is back from family leave.

**Comment by BrianDeJesus** [comment]
@koltyakov  Awesome thanks. Looks like he merged it 18 hours ago. Thanks guys! Great work
