### ISSUE TITLE
Setting up context for pnp/sp inside custom service (Service Scopes)

### ISSUE THREAD

**Issue by theitfactor** [pnp/pnpjs#1290]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.3.7     ]

Please specify what version(s) of SharePoint you are targeting: [   SPO    ]

### Expected / Desired Behavior / Question

I have created a user service that fetches certain settings and profile data for my web parts. This has been created as UserService using the service locator pattern. In my service I have imported the module into my service

`import { sp } from "@pnp/sp";`

When I attempt to use `sp.profiles.getPropertiesFor(login)` I receive an error:

```
sp.es5.js:210 Uncaught (in promise) TypeError: Cannot read property 'web' of undefined
    at SPRuntimeConfigImpl.get [as baseUrl] (sp.es5.js:210)
```

When debug futher into sp.es5.js I can see that is is bombing on this line:

```js
return RuntimeConfig.spfxContext.pageContext.web.absoluteUrl;
```

That seems to indicate that the pageContext is missing. I am using the constructor to setup the library with the PageContext. 
```ts
constructor(serviceScope: ServiceScope) {
        serviceScope.whenFinished(() => {
             this.pageContext = serviceScope.consume(PageContext.serviceKey);
             sp.setup({
                spfxContext: this.pageContext
            });

        });
}
```

Is there another way to setup the pnp/sp library so that I can use it inside my service(s)?

**Comment by koltyakov** [comment]
@theitfactor,
 
Please [check this section](https://pnp.github.io/pnpjs/getting-started/#establish-context-within-an-spfx-service) of the docs.

**Comment by patrick-rodgers** [comment]
Closing this as answered. If you are still having issues please open a new issue, reference this one, and provide any additional details possible. Thanks!
