### ISSUE TITLE
RichText control not displaying value

### ISSUE THREAD

**Issue by mpalmer-sps** [pnp/pnpjs#1291]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.0.3     ]

Please specify what version(s) of SharePoint you are targeting: [  SharePoint Online       ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
The value from a SPList for a Multiline, Rich textfield should be displayed when state is set.

### Observed Behavior
State is set in the CTOR:
![image](https://user-images.githubusercontent.com/12634625/87997035-d2e8a580-caa8-11ea-845c-d38e48a0bcfb.png)

Then componentDidMount is called and all values are correctly populated including the "notes" field which is the RichTextBox control value coming from a SPO list:
![image](https://user-images.githubusercontent.com/12634625/87997154-22c76c80-caa9-11ea-94b0-b3f4f37fa57d.png)

I console log the results just to ensure I get a good value and its all good with Notes:
![image](https://user-images.githubusercontent.com/12634625/87997231-5bffdc80-caa9-11ea-9d49-2406f5328b0b.png)

Then I get to render and check the console again before rendering the controls:
![image](https://user-images.githubusercontent.com/12634625/87997343-b731cf00-caa9-11ea-9837-abe6870ac6d4.png)

the console shows all good:
![image](https://user-images.githubusercontent.com/12634625/87997393-d4669d80-caa9-11ea-8008-6a55c0fa0432.png)

But the control is empty:
![image](https://user-images.githubusercontent.com/12634625/87997425-e9dbc780-caa9-11ea-886a-30a18f82c8ed.png)

And even the state in the REACT components plug-in shows empty:
![image](https://user-images.githubusercontent.com/12634625/87997469-0677ff80-caaa-11ea-951d-eb667ef456a7.png)

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

**Comment by juliemturner** [comment]
@mpalmer-sps Unfortunately this question isn't really about using the PnPJS library you're question is really about how to properly write ReactJS code, similar to the earlier issue you posted #1286. I basically have the same guidance for you for this issue as we do not support general programming questions, only questions specifically related to the library which this is not.

**Comment by mpalmer-sps** [comment]
@juliemturner  Unfortunately I have to disagree. I don't see any error in the code I provided and I was able to verify that the "value" for the richtext control is available in the state of the component just before rendering.
Per the documentation provided on the Richtext box control page here: https://pnp.github.io/sp-dev-fx-controls-react/controls/RichText/ 
The value property can be populated using the method I used with the exception that props are used in the example versus state in my example:
![image](https://user-images.githubusercontent.com/12634625/87999980-4db5be80-cab1-11ea-984c-63182f2edaea.png)

**Comment by mpalmer-sps** [comment]
As an additional test, I've changed the Richtext control to a plain TextBox control. 
Using the exact same method if assigning the value from state and now I am getting text values populated into that control as expected (incorrectly formatted but at least it is a value...).
![image](https://user-images.githubusercontent.com/12634625/88001292-a470c780-cab4-11ea-9d39-039f38b7ee3d.png)

![image](https://user-images.githubusercontent.com/12634625/88001300-ac306c00-cab4-11ea-9e7e-040b7c112186.png)

The issue is not with my code (unless there is something documented somewhere that I'm unaware of) but rather with the control.

**Comment by mpalmer-sps** [comment]
And to further my case, I came across this Blog post wherein the author states:

> "This article provides steps to implement the React Rich Text Editor in the SharePoint Framework (SPFx) web part, generally react rich text editor provides rich text editing and display capability and it is alternate for the PnP rich text editor. **_because in the PnP control having an issue while set value using react state_**. so initial values always have to set from props.

If the only way this control works properly is via PROPS rather than STATE I'd call that a bug and yes, the only reason I'm seeing this is because this is a bug.

Blog: https://ravichandran.blog/2020/06/18/react-rich-text-editor-in-the-sharepoint-framework-spfx-webpart/

**Comment by mpalmer-sps** [comment]
Also, how do I remove the "answered" label from this because I do not feel that this has been answered.

**Comment by mpalmer-sps** [comment]
ok - I've switch away from this broken PnPjs control and was able to fix my issue with the ReactQuill control. Everything is working as I had hoped it would.
Thanks for your help.

**Comment by koltyakov** [comment]
@mpalmer-sps,

[React controls](https://github.com/pnp/sp-dev-fx-controls-react) is a different project which has no direct connection with PnPjs, they are under PnP umbrella but completely independent. PnPjs is API client, `@pnp/spfx-controls-react` which is your question about are reusable controls for SPFx. 

After the initial read, I and @juliemturner even both decided that it's a generic React question as it's so out of the context of PnPjs project.
