### ISSUE TITLE
A type named 'SP.FieldNote' could not be resolved by the model when trying to update a field

### ISSUE THREAD

**Issue by AJIXuMuK** [pnp/pnpjs#1294]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.6]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
Multiline Text field is updated with no errors

### Observed Behavior
A type named 'SP.FieldNote' could not be resolved by the model error.
### Steps to Reproduce
```typescript
await sp.web.fields.getByInternalNameOrTitle('fieldtitle').update({
            // update params
          });
```
Metadata for this request:
```json
"__metadata":{"type":"SP.FieldNote"}
```

If I explicitly set the type to be `SP.Field` (as it was in v1 of the library) - everything works:
```typescript
await sp.web.fields.getByInternalNameOrTitle('fieldtitle').update({
            // update params
          }, 'SP.Field');
```

**Comment by patrick-rodgers** [comment]
This is coming out of the change made in #1187 to make the field type optional. You can always override it like you did.

We've updated the code in update to pull the odata.type which seems to reflect the true type which FieldTypeKind does not.
