### ISSUE TITLE
Update Authentication Documentation for SharePoint Framework

### ISSUE THREAD

**Issue by juliemturner** [pnp/pnpjs#1298]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version
2.0.7

### Expected / Desired Behavior / Question
Need to review and update documentation for authentication with regard to SharePoint Framework.

**Comment by patrick-rodgers** [comment]
So I don't really forget this about the adal auth client and not needing the adal package within spfx.
