### ISSUE TITLE
Giving Group Access to Item in Document Library 

### ISSUE THREAD

**Issue by Steven-Chorkawy** [pnp/pnpjs#1301]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.6]

Please specify what version(s) of SharePoint you are targeting: [Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

###  Question
Hello, 

Is it possible to give a group access to a list item or a file in a document library? 
I've tried the following but I'm not sure it is the correct approach.
`let myGroup = await sp.web.siteGroups.getByName('Site Group Name').get();`
`const { Id: roleDefId } = await sp.web.roleDefinitions.getByName('Edit').get();`
`let item = await sp.web.lists.getByTitle('Document Library Title').items.getById(1);`
`item.roleAssignments.add(myGroup.Id, roleDefId)`

This does not provide me any errors but it also does no provide edit access to my desired group. 

Any feedback would be much appreciated! 

Thank you.

**Comment by koltyakov** [comment]
In SPO, [sharing](https://pnp.github.io/pnpjs/sp/sharing/) can be considered.
In a classic model, before being able to change role assignments [role inheritance](https://pnp.github.io/pnpjs/sp/security/#securable-methods) must be broken (with `breakRoleInheritance`). As by default, permissions are inherited from a parent container and can't be changed.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. If you have additional questions please open a new issue, ref this one, and provide any additional details you can. Thanks!
