### ISSUE TITLE
IE 11 Pnp polyfill question

### ISSUE THREAD

**Issue by manojkumarrai007** [pnp/pnpjs#1309]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of SharePoint you are targeting: [ sharepoint 2019        ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question

Hi Team,
I am creating a spfx application customizer in which i am integrating some js files and css of a chatbot application built in react to show that in sharepoint 2019 modern site. its working fine in all browsers except IE11. after using pnp polyfil IE11, it started working in debug mode. after packaging and deploying solution even on same site where it was working in debug mode, it is not displaying.  i could see all required js files and css files are loading but the entry point function of chatbot application is not getting called. Not getting any idea how it is working in debug mode then. please if anyone can help if I am missing something here which needs to be added it to work after deployment in IE11.
node version is 10.X and typescript which is getting used is 2.4.1 in spfx application customizer.

Thank you for your feedback!

**Comment by juliemturner** [comment]
You don't mention setting ie11 mode? I would suggest you start by reading all the detailed documentation we provide on IE11 and the continued reading on Polyfills and see if that doesn't solve the issue for you. [IE11 Mode](https://pnp.github.io/pnpjs/concepts/ie11-mode/)

**Comment by manojkumarrai007** [comment]
Hi Julie,
Thanks for quick reply. I have tried to add sp.setup and made ie11:true. this is not giving any difference. I am surprised that why it is working in debug mode and not after deployment.

**Comment by juliemturner** [comment]
I'm actually not surprised as I have seen that behavior before. You could try and include the libraries that we detailed separately instead of using our polyfill bundle... but I suspect, based on my own struggles with getting stuff to work in IE11, that you just are missing or are including a polyfil that is/isn't needed.  Sadly, it's a very challenging to support IE11 and in my work we end up charging our clients a premium to support IE11 because doing so is so difficult and unique to each implementation.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. If you still have questions please open a new issue, ref this one and provide any additional details possible. Thanks!
