### ISSUE TITLE
Calling `getParentWeb` on the root Web results in a call to `_api/site/openWebById('undefined')`

### ISSUE THREAD

**Issue by thw0rted** [pnp/pnpjs#1311]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.6]

Please specify what version(s) of SharePoint you are targeting: [2016]

### Expected / Desired Behavior / Question
I created a Web that points to the root web of an instance, and thought if I tried to call `getParentWeb` that it would fail gracefully in some way.  (Maybe there's a better way to tell that my Web instance is the site root?)

### Observed Behavior
It actually makes a request to `_api/site/openWebById('undefined')` (with the string literal "undefined" there) and bubbles out the network error that results.

### Steps to Reproduce
````ts
const web = Web(url);
const parent = await web.getParentWeb();   // throws
````

----

As an aside, if anybody has a better suggestion for how to check that a given Web represents the site root, I'd be happy to hear it.

**Comment by patrick-rodgers** [comment]
I wasn't able to duplicate this. We do check in that method to see if the ParentWeb exists before referencing it. Out of curiosity can you debug and let us know inside the getParentWeb method what the value of ParentWeb is for you? It must be something defined I just can figure out what so might be a SP version difference.

**Comment by thw0rted** [comment]
Sorry for the delay, I had some issues with my lab farm and had to do a re-install.  It's running again (SP 2016 / on-prem, using an MSDN license) and I'm still seeing the issue.  The code that shows this behavior is

````ts
this.web = Web("http://sharepoint.lab.local/").configure({
    credentials: "include",
    mode: "cors",
    headers: {
        Accept: "application/json;odata=verbose",
    },
});

const parent = (await this.web.getParentWeb()).web;
````

I tried putting a breakpoint in `@pnp/sp/webs/types.js`, around line 95 of the generated code, but I quickly lost track of things because the transpiler uses a tangled web of helper methods to handle async/await, at least with the emit target you used. I can tell you that it results in a call to `http://sharepoint.lab.local/_api/web?$select=ParentWeb/Id&$expand=ParentWeb` which returns

````json
{
    "d": {
        "__metadata": {
            "id": "http://sharepoint.lab.local/_api/Web",
            "uri": "http://sharepoint.lab.local/_api/Web",
            "type": "SP.Web"
        },
        "ParentWeb": {
            "__deferred": {
                "uri": "http://sharepoint.lab.local/_api/Web/ParentWeb"
            }
        }
    }
}
````

Looking at the sources, the behavior that I'm seeing makes sense.  On [this line](https://github.com/pnp/pnpjs/blob/version-2/packages/sp/webs/types.ts#L88): `return ParentWeb ? Site(this.parentUrl).openWebById(ParentWeb.Id) : null;` results in passing `undefined` to `openWebById`.  This could be prevented by e.g. `return ParentWeb?.Id ? Site(this.parentUrl).openWebById(ParentWeb.Id) : null;` instead.

(I'm a bit puzzled by the API response.  I would have expected the JSON to look like `{ParentWeb: {Id: null} }`, but the effect is the same regardless.)
