### ISSUE TITLE
Thumbnail image is only working when i update an existing page, it does not work for newly created pages.

### ISSUE THREAD

**Issue by PrathyushP95** [pnp/pnpjs#1313]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.7]

Please specify what version(s) of SharePoint you are targeting: [2016]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Hi,

I observed a strange behavior for thumbnail images. I'm uploading an image using below code,

```
let file_upload = await sp.web.getFolderByServerRelativeUrl(image_folder_path).files.add(image_name, image_body, true);
let relative_path =  file_upload.data.ServerRelativeUrl;
```

Then i'm setting this path as thumbnail image,

`page.thumbnailUrl = relative_path;`

When i create the page it does not show thumbnail image. When i update the same page it shows thumbnail image.

**Comment by juliemturner** [comment]
Are you saving the page?
Did you check if there are errors?

**Comment by PrathyushP95** [comment]
I'm saving my page and i can't see any error in my logs.

**Comment by patrick-rodgers** [comment]
You need to please share enough code we can see what you are doing. If the code works it seems like you have somehow two different code paths or are doing something on the second try that you aren't on the first. You have not provided us enough information to begin to help you.

**Comment by PrathyushP95** [comment]
I'm writing this code in AWS Lambda function.

```
const sp = require('@pnp/sp-commonjs').sp;
const SPFetchClient = require('@pnp/nodejs-commonjs').SPFetchClient;
const ClientsidePageFromFile = require("@pnp/sp-commonjs/clientside-pages").ClientsidePageFromFile;
const ClientsideText = require('@pnp/sp-commonjs/clientside-pages').ClientsideText;
const ClientsideWebpart = require('@pnp/sp-commonjs/clientside-pages').ClientsideWebpart;

exports.handler = async function(event, context) {
sp.setup({
    sp: {
      fetchClientFactory: () => {
        return new SPFetchClient(page_path, client_id, client_secret);
      },
    },
  });
const WebParts_def = await sp.web.getClientsideWebParts();
page = await sp.web.addClientsidePage(page_name, title, 'Article');
page.description = description.substring(0, 255);
page.headerTextAlignment = 'Left';
page.layoutType = "FullWidthImage";
page.showTopicHeader = true;
page.thumbnailUrl = await add_thumbnail_image(image_path, page, sp);
await add_banner_image(full_data, event.post_type, image_dam_path, section, page, sp);
// code to add clientside text, image webpart and video webpart.
page.topicHeader = 'Topic header';
await page.promoteToNews();
await page.save();
}

async function add_thumbnail_image(image_path, page, sp) {
  let thumbnail_image_path = '';
  let thumbnail_image_url = 'somesampleurl.jpg';
  let thumbnail_image_name = 'sample.jpg';
  thumbnail_image_path = await uploadImage(image_path, thumbnail_image_name, thumbnail_image_url, sp, 'thumbnail');
  return thumbnail_image_path;
}

async function add_banner_image(image_path, page, sp) {
  let banner_image_path = '';
  let banner_image_url = 'somesampleurl.jpg';
  let banner_image_name = 'sample.jpg';
  banner_image_path = await uploadImage(image_dam_path, banner_image_name, banner_image_url, sp, 'banner');
  await page.setBannerImage(banner_image_path);
}

async function uploadImage(image_path, image_name, image_url, sp) {
  try {
    let image_body = await axios({ method: 'get', url: image_url, responseType: 'arraybuffer' }).then(response => Buffer.from(response.data, 'binary'));
    let file_upload = await sp.web.getFolderByServerRelativeUrl(image_path).files.add(image_name, image_body, true);
    return file_upload.data.ServerRelativeUrl;
  }
  catch (e) {
    console.log(e);
  }
}
```

**Comment by PrathyushP95** [comment]
I've done a workaround for this. After saving the page i'm again loading the same page and updating thumbnail image.

```
await page.save();
const thumb_page = await ClientsidePageFromFile(sp.web.getFileByServerRelativePath(page_name));
thumb_page.thumbnailUrl = await add_thumbnail_image(image_path, page, sp);
await thumb_page.save();
```
This works fine.

**Comment by patrick-rodgers** [comment]
Awesome - glad you found a work around. Going to close this issue, thanks!
