### ISSUE TITLE
How to access term sets with multi level terms

### ISSUE THREAD

**Issue by yahookevin** [pnp/pnpjs#1315]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0.6     pnp/sp/presets/all ]

Please specify what version(s) of SharePoint you are targeting: [     SP Online    ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
How do i access the termsets and terms within a Termset
Term group
               >Termset
                              >Term set (Level 3)
                                               >Term set(Level 4)
                                                                >Term(Level 5)
At the moment i get all the terms in Level 4 and Level 5 in same level at Level 3. I'm trying to build a tree structure from term store. For that i need to create a JSON object and then pass this to a D3 graph.

### Observed Behavior
Each term should have the setID (ParentID) denoting the previous level. Currently its showing Level 2.

### Steps to Reproduce

```
  private async getTermDetailsforAllv2(){  
    var _term:Array<ITerm>=new Array<ITerm>();
    //console.log("getTermDetails Method");

    for(var i=0;i<this.state.TermSet.length;i++)
    {
            
      const info: ITermInfo[]  = await sp.termStore.termGroups.getById("a8a76ad4-7140-430a-9908-c0bc97231093") // This is Term Group ID  
      .termSets.getById(this.state.TermSet[i].termsetId).terms(); //this is  Term Set ID
    
      info.map((obj)=>{
      console.log(JSON.stringify(obj));
          obj.labels.map((objTerm)=>{
            //console.log("Name "+objTerm.name+" Count "+ obj.childrenCount);

           _term.push(
              {
                  termId:obj.id,
                  termName:objTerm.name,
                  termSetId:this.state.TermSet[i].termsetId,
                  TDescription:obj.descriptions.map(item=>item.description)
              }         
           )
          })
        
      })

    }
    this.setState({Term:_term});  
  } 
```

**Comment by yarick123** [comment]
I would also appreciate to have a possibility to get all the terms of a termset at once. It is possible in PnPjs v1, but not in v2
In ITermInfo there is no even information about the parent term.

**Comment by patrick-rodgers** [comment]
In 2.0.13 we are adding both "terms" to the termset class and a method "getAllChildrenAsOrderedTree" that will get all the set's children ordered based on either default or custom sort.

**Comment by yahookevin** [comment]
> In 2.0.13 we are adding both "terms" to the termset class and a method "getAllChildrenAsOrderedTree" that will get all the set's children ordered based on either default or custom sort.

That'll be awesome. Thanks @patrick-rodgers
