### ISSUE TITLE
Question: How to best import a function, e.g. "stripInvalidFileFolderChars"?

### ISSUE THREAD

**Issue by TheShihan** [pnp/pnpjs#1316]
### Category
- [ ] Enhancement
- [ ] Bug
- [X ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.7]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
What is the recommended way to import/use utility functions, for example `stripInvalidFileFolderChars(...)` (file-names.ts)?

### Observed Behavior
 I have  a SPFX WebPart project (with React), with PnPJS 2.0.7. On top of my TS-file (a service class), I import the PnPJS module:
`import { sp } from "@pnp/sp/presets/all"`
Cannot directly use utility function, when using the import like written above. I have to use the following:
`import * as spFileNames from "@pnp/sp/utils/file-names";`
This makes it work, I can now do this (unsure if this is a good approach):
`spFileNames.stripInvalidFileFolderChars(productTitle, "_");`
Documentation (for Version 1!) says:
```
import { sp } from "@pnp/sp";
const validName = sp.utility.stripInvalidFileFolderChars("Filename?.txt");
```
Which does not work. Function cannot be found under `sp.utility` this way.
Shouldn't `import { sp } from "@pnp/sp/presets/all"` make everything available/import everything? What is the recommended way and why is there no updated V2 documentation?

### Steps to Reproduce
SPFX WebPart project (with React), with PnPJS 2.0.7. TS-file (e.g. a service class), import the PnPJS module:
`import * as spFileNames from "@pnp/sp/utils/file-names";`
This works now (e.g. in a function): `spFileNames.stripInvalidFileFolderChars(productTitle, "_");`
Doing it like mentioned in the V1 documentation, does not work (cannot resolve function):
```
import { sp } from "@pnp/sp";
const validName = sp.utility.stripInvalidFileFolderChars("Filename?.txt");
```

**Comment by juliemturner** [comment]
Have you had a look at this documentation? https://pnp.github.io/pnpjs/concepts/selective-imports/

In general we do not suggest you use the preset unless you don't care at all about the bundle size, it's something we're leaving there for demo projects and backward compatibility but it's definitely not the recommended approach.

Regarding that particular utility function, you're correct it's not documented, but probably should be.

**Comment by TheShihan** [comment]
ah ok, no I haven't seen this documentation page and I now understand that the impact of using the presets all.

So, but what would be the way to only import the utility function I need in my example, do I do it in the correct way?

**Comment by juliemturner** [comment]
I believe it's...
```
import "@pnp/sp/file-names";
const newFileName = stripInvalidFileFolderChars("Filename?.txt");
```

**Comment by tavikukko** [comment]
Here's how to import it

```typescript
import { stripInvalidFileFolderChars } from "@pnp/sp/utils/file-names"

stripInvalidFileFolderChars("","")
```

![Screenshot 2020-08-05 at 22 19 50](https://user-images.githubusercontent.com/2223355/89454835-f595e200-d769-11ea-9a16-4bacc30bd96c.png)

**Comment by TheShihan** [comment]
Thanks, makes sense!

**Comment by patrick-rodgers** [comment]
Going to close this as answered. If you still have questions please open a new issue, ref this one and provide any additional details possible. Thanks!
