### ISSUE TITLE
First call adds SitePages to pnp.sp.site.rootWeb.lists.getByTitle?

### ISSUE THREAD

**Issue by svermaak** [pnp/pnpjs#1317]
# Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ Latest ]

Please specify what version(s) of SharePoint you are targeting: [  Online       ]

### Expected / Desired Behavior / Question
Calling pnp.sp.site.rootWeb.lists.getByTitle("Business Group") results in  the following web request https://XXXX.sharepoint.com/sites/XXXX/SitePages/_api/site/rootweb/lists/getByTitle('Business%20Group')/items?$top=2000

### Observed Behavior
The derived web request URL should be
https://XXXX.sharepoint.com/sites/XXXX/_api/site/rootweb/lists/getByTitle('Business%20Group')/items?$top=2000

Note, context is configured https://pnp.github.io/pnpjs/documentation/getting-started/#using-pnpcommon-setup

### Steps to Reproduce
I have attach STP of list. I assume that it can be reproduced
[businessgroupempty.zip](https://github.com/pnp/pnpjs/files/5032539/businessgroupempty.zip)

I have implemented a workaround that literally does a dummy call before my other calls

**Comment by patrick-rodgers** [comment]
You have likely not established the context property. Please have a [look at the getting started docs](https://pnp.github.io/pnpjs/getting-started/#establish-context).

**Comment by patrick-rodgers** [comment]
Going to close this as answered. If you are still having issues please open a new issue, ref this one, and provide any additional details you can. Thanks!
