### ISSUE TITLE
usingChaching() 

### ISSUE THREAD

**Issue by Galshalom5** [pnp/pnpjs#1318]
### Category
- [ ] Enhancement
- [ ] Bug
- [*] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  latest  ]

Please specify what version(s) of SharePoint you are targeting: [         ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
does usingCaching() implemented based on localStoarge/sessionStoarge?

Thank you for your feedback!

**Comment by sympmarc** [comment]
@Galshalom5 - check the doc about [@pnp/common/storage](https://pnp.github.io/pnpjs/common/storage/):

> This module provides a thin wrapper over the browser storage options, local and session. If neither option is available it shims storage with a non-persistent in memory polyfill.

**Comment by Galshalom5** [comment]
thanks for your comment, i heard that it isnt safe to use browser stoarge, does the wraper incrypt the data?

**Comment by patrick-rodgers** [comment]
We do not encrypt the data. The uses of browser storage is a topic outside the scope of this issues list. The answer always is that it depends on the situation. Going to close this as answered. If you still have questions please open a new issue, ref this one and provide any additional details possible. Thanks!
