### ISSUE TITLE
DeleteWithParameters

### ISSUE THREAD

**Issue by EnableAnders** [pnp/pnpjs#1319]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.0.6     ]

Please specify what version(s) of SharePoint you are targeting: [   SPO      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

Is it possible to use BypassSharedLock when deleting files using pnpjs? It's not a big issue since I can do it with REST, but would be nice todo all with the library. 

_api/web/xxx/DeleteWithParameters()
```
parameters: {
     BypassSharedLock: true
 }
```

**Comment by patrick-rodgers** [comment]
We don't currently have a method for that but we can look at adding it. Thanks for the idea.

**Comment by patrick-rodgers** [comment]
Have implemented these and will shortly do a PR, just cleaning up the docs. There is currently a hard coded check in item.deleteWithParams that ONLY allows systems accounts to call this method. That check is not there for folders or files currently. This behavior may change but is an important note on these methods. Wanted you to be aware of that before using them.
