### ISSUE TITLE
Api called from wrong root URL resulting in 404

### ISSUE THREAD

**Issue by oppie85** [pnp/pnpjs#132]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [ 1.1.1  ]

### Expected / Desired Behavior / Question
I'm using api functions inside an SPFx extension that's being called from a site page. (example:
sp.web.select("welcomepage").get()

### Observed Behavior
When using functions that call an API inside an SPFx extension that's on a sitepage, the api url is constructed as "contoso.sharepoint.com/sites/mysite/SitePages/_api/..." instead of "contoso.sharepoint.com/sites/mysite/_api/..." which results in a 404 error.

### Steps to Reproduce
Create a new SPFx extension (application customizer). In the onInit() of the component, call sp.web.select("welcomepage").get()

**Comment by patrick-rodgers** [comment]
Hi @oppie85 , please see the [getting started guide](https://pnp.github.io/pnpjs/getting-started.html#getting-started-with-sharepoint-framework). You need to supply the context to the library as shown in the docs.

**Comment by oppie85** [comment]
Ah, thanks @patrick-rodgers; I feel rather stupid now for not noticing that in the first place. Apologies for wasting your time.

**Comment by patrick-rodgers** [comment]
No worries, glad it was an easy one :)
