### ISSUE TITLE
Question: How to check if file exists (file.Exists property is not available)?

### ISSUE THREAD

**Issue by TheShihan** [pnp/pnpjs#1320]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.7]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
I want to check if a file exists, normally done with `file.Exists`. It is not currently clear if this can be really achieved with PnPJS or if I have to use CSOM directly (or maybe use a CAML query with PnPJS).

### Observed Behavior
I fetch a file from a library like this, but I am not sure yet if the path points really to a file:
`const file: IFile = sp.web.getFileByServerRelativeUrl(newPageServerRelativeUrl);`
In CSOM, SSOM, we normally check it with: `file.Exist`
This is necessary, because the methods would always return a file object anyway, regardless if it exists or not.
When I try to use `file.Exists` here, the compiler tells me, that there is not Exists property on `IFile`.
When I check the inheritance, I see that in the "end" there is a `IFileInfo `object, that would have the `Exists `property:
```
getFileByServerRelativeUrl(fileRelativeUrl: string): IFile;
export interface IFile extends _File, IDeleteableWithETag { ... }
export declare class _File extends _SharePointQueryableInstance<IFileInfo> { ... }
export interface IFileInfo {
    readonly "odata.id": string;
    Exists: boolean;
    ...
}
```
But I cannot cast an `IFile `to `IFileInfo`. How can I access this property? There is no documentation regarding those properties/IFileInfo.

### Steps to Reproduce
```
import { sp } from '@pnp/sp/presets/all';
import "@pnp/sp/webs";
import "@pnp/sp/files";
import "@pnp/sp/items";
const file: IFile = sp.web.getFileByServerRelativeUrl(newPageServerRelativeUrl);
if (file.Exists) { alert('file exists'); }
```

**Comment by koltyakov** [comment]
If a file doesn't exist the query ends up with HTTP error (400, 404). The existence of a file can be checked this way:

```typescript
const exists = await sp.web
  .getFileByServerRelativeUrl('/no/such/file.txt')
  .select('Exists').get()
  .then((d) => d.Exists)
  .catch(() => false);

console.log(exists);
```

Can't recall what's happening when a user has no read access.

P.S. No need mixing partial and preset imports, should be either partial or a preset.

**Comment by patrick-rodgers** [comment]
We could add a method to check this, tagging as enhancement.
