### ISSUE TITLE
Question:  Add an App to Site/Web

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1325]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version 
Latest

### Expected / Desired Behavior / Question
Is there a way through Pnp or other client side javascript to activate an app on a site/web?
I'm referring to like adding an already tenant activated webpart to a site.

The reason I'm asking is because I was able to create a page with my webpart installed on it but it would not show up until I manually went to contents and added it to the site.

Thanks :)

**Comment by koltyakov** [comment]
I suppose it can be done by activating a solution feature:

```typescript
await sp.web.features.add('{solution-feature-guid}', true);
```

**Comment by patrick-rodgers** [comment]
Going to close this as answered. If you are still having issues please open a new issue, ref this one, and provide any additional details you can. Thanks!
