### ISSUE TITLE
Need api to set default metadata for folders

### ISSUE THREAD

**Issue by nsksaisaravana** [pnp/pnpjs#1328]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Expected / Desired Behavior / Question
Currently no API is available to update the default metadata for folders

![image](https://user-images.githubusercontent.com/17681573/89843293-8a11a180-dbbb-11ea-8e57-a9fa56f16253.png)

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
[Please read the docs](https://pnp.github.io/pnpjs/sp/column-defaults/) describing exactly what you are requesting.

**Comment by nsksaisaravana** [comment]
I have SharePoint document library and i have added two folders 1. New York and 2.Washington. Each folder level I would like to set default metadata for the column city New York and Washington.

Setting default metadata for a column can be done but not possible by folder level.

**Comment by patrick-rodgers** [comment]
Please provide your code that is currently not working so we can attempt to help. Please also let us know any error messages you are seeing. Would also encourage you to [please see the section on in the docs on setting folder defaults](https://pnp.github.io/pnpjs/sp/column-defaults/#set-folder-defaults).

**Comment by patrick-rodgers** [comment]
Going to close this as answered due to no response. If you continue to have issues please open a new issue, ref this one, and provide any additional details you can. Thanks!
