### ISSUE TITLE
How to add the custom agent on a PNP Powershell?

### ISSUE THREAD

**Issue by msnaveen** [pnp/pnpjs#1329]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [- ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ PNP  3.24.2008.0   ]

Please specify what version(s) of SharePoint you are targeting: [   SPO      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

https://github.com/pnp/pnpjs/issues/1162

### Steps to Reproduce

Fiddler Header

POST /_vti_bin/client.svc/ProcessQuery HTTP/1.1
Accept-Encoding: gzip, deflate
User-Agent: NONISV|SharePointPnP|PnPPS/3.24.2008.0
RESPONSE
JSON=429

I call the GRAPH API to get the URL list and then i run the Get-PnPTenantSite -url $urls -ErrorAction SilentlyContinue
Get-PnPTenantSite -url $urls -ErrorAction SilentlyContinue

### Submission Guidelines
#	

User-Agent: NONISV|SharePointPnP|PnPPS/3.24.2008.0 >> How can i Change this if i am just using the fiddler

I am currently only working with 4 K sites but my aim is to go for 300 K site and if it is getting throttled then i will not  be able to get the project finished.

Thank you for your feedback!

**Comment by koltyakov** [comment]
Wrong repo.

**Comment by koltyakov** [comment]
Please post to https://github.com/pnp/PnP-PowerShell
