### ISSUE TITLE
Client-Side page: Vertical sections gets not added with page.addVerticalSection();

### ISSUE THREAD

**Issue by TheShihan** [pnp/pnpjs#1330]
### Category
- [ ] Enhancement
- [x] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.8]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
I want to add a vertical section to a modern SharePoint Page (client-side page).
I am doing it like it is written in the docs, but the vertical section is not added.
Do I something wrong or is this a bug?

### Observed Behavior
Vertical section is not added. I can still add the vertical section manually using a browser (it is greyed-out when there is already a vertical section).

### Steps to Reproduce
I create a page with this command:
`const page = await CreateClientsidePage(sp.web, pageFileName, productTitle, "Article");`
Page gets created successfully
I do some other stuff and then later get the page:
`const page = await sp.web.loadClientsidePage(serverRelativePageUrl);`
And then I add some sections to it  (one third right). And I want to add also the vertical section:
```
        // Setup sections and columns (sums must add up to 12)
        const section1 = page.addSection();
        section1.addColumn(8);
        section1.addColumn(4);
        // publish changes
        await page.save();
        // Vertical section
        const vertSection = page.addVerticalSection();
        // publish changes (again)
        await page.save();
```
I split it up, because I was not sure if I maybe have to add some other sections to it for it to work, but it still doen't work. Also doesn't work when I only add the vertical section or only use one `page.save()` add the end.

**Comment by TheShihan** [comment]
Oh, and I think the documentation regarding this topis has some errors in it:
```
// our page instance
const page: IClientsidePage;

// add or get a vertical section (handles case where section already exists)
const vertSection = page.addVerticalSection();

// if you know or want to test if a vertical section is present:
if (page.hasVerticalSection) {

    // access the vertical section (this method will NOT create the section if it does not exist)
    page.verticalSection.addControl(new ClientsideText("hello"));
} else {

    const vertSection = page.addVerticalSection();
    section.addControl(new ClientsideText("hello"));
}

```
`vertSection` is defined in the beginning, but not used, and then again declared when the page does not have such a section - but it is a const.

**Comment by TheShihan** [comment]
I tested a bit more, with following code:
 ```
       const page = await sp.web.loadClientsidePage(pageUrl);       
        const hasVertical: boolean = page.hasVerticalSection;

        if (!hasVertical)
        {
          page.addVerticalSection().addControl(new ClientsideText("hello world"));;
          page.save(true);
        }
```
The WebPart with "Hello World" gets added to the page, but it is added like a normal full width section, below the rest of existing other sections. It is not added as vertical section, I could manually add the vertical section. And also when I check later the page by code the `page.hasVertical` is set to false (again, it was shortly/temporarily `true`, after calling "`addVerticalSection()`".

Did maybe something change inside SharePoint Online so that this method is now broken?

**Comment by patrick-rodgers** [comment]
Something may have changed in the api - unsure. There is no official API for this so what we have is all reverse engineered.

**Comment by diplobelsdb** [comment]
Something has recently changed in the API. Page sections aren't available anymore.
For ex: 
// Was working until recently
const projectHomePage:IClientsidePage = await Web(<SiteUrl>).loadClientsidePage(<PageRelativeUrl>);
// get WP definition
const partDefs = await sp.web.getClientsideWebParts(); 
// Guid of Contact WP
const peoplePartDef = partDefs.filter(c => c.Id === "7f718435-ee4d-431c-bdbf-9c4ff326f46e");
const WPtoAdd = ClientsideWebpart.fromComponentDef(peoplePartDef[0]);
// add WebPart at second position in second column
projectHomePage.sections[0].columns[1].controls.splice(1,0,WPtoAdd);
//Save page
await projectHomePage.save();

Now projectHomePage.sections is empty.

**Comment by patrick-rodgers** [comment]
Had a chance to look into this today and confirmed I see the bug. Not sure what isn't working yet but digging into it. Am curious if you can test - everything seems to work fine for me if the page is create through the UI and edited using PnPjs. Vertical sections, etc.

**Comment by patrick-rodgers** [comment]
Ok, I think I got it. Very strange now seeing the bug unsure how it was working previously. My _guess_ is they fixed a bug on the server around layoutIndex causing our broken but working impl to start failing. Anyway a few more tests and I think I can PR the fix. Thanks again for reporting.
