### ISSUE TITLE
CORS errors with pnp/sp/search

### ISSUE THREAD

**Issue by CarlosEspejoMartinez** [pnp/pnpjs#1335]
We have a webpart that has benn working fine for the las 8 months, just this week we notice that it was giving us the next error:
![CapturaError](https://user-images.githubusercontent.com/69849594/90506520-b5186a00-e154-11ea-93d7-a7705b2e2d73.PNG)
We checked and notice CORS errors in console:
![CapturaCors](https://user-images.githubusercontent.com/69849594/90506676-f4df5180-e154-11ea-8be6-1a837971b3d2.PNG)
The webpart is a very simple grid view of the pages that are stored in the same SPO subsite, we are using sp.search to get this elements and have checked that by removing this section of code CORS errors cease to appear.
![CapturaCode](https://user-images.githubusercontent.com/69849594/90507517-489e6a80-e156-11ea-891b-3ea51a97b799.PNG)

This is the function we are using to recover the elements in the list (I'm sorry about the screen cap, the insert code wasn't quite working for me).

Thanks in advance.

**Comment by koltyakov** [comment]
From the screens, I can see the hostname duplicated twice. Maybe it's a reason. Are you [establishing SPFx Context](https://pnp.github.io/pnpjs/getting-started/#establish-context)?

**Comment by CarlosEspejoMartinez** [comment]
We establish context on render:
![CapturaRender](https://user-images.githubusercontent.com/69849594/90521289-accb2980-e16a-11ea-8926-eccc11383a56.PNG)
I had notice that too, but it's very strange considering this webpart has been working without issue for months.

**Comment by koltyakov** [comment]
Please, check if you follow the docs recommendations exactly. Basically, render is not a correct place for the context. If it bypassed and then is really established before the first call to the API, it’s not shown on a screenshot above as it might not be even passed to PnPjs (just a guess).

Unfortunately, it happens that changes in SaaS platforms could break things. If it’s really the case (let’s say the context object was updated with breaking changes), we’d expect more issue requests. I also haven’t faced context issues on my environments recently. Need to research or wait for more info to be able to reproduce.

**Comment by CarlosEspejoMartinez** [comment]
We have got it working again after updating react and other components, the cors error persist, but I think you are right, an update must have break something. 

We'll definetly take a look at the context declaration in order to prevent further issues.

Thanks for the help!
