### ISSUE TITLE
Parsing error with batch and RenderListDataAsStream responses

### ISSUE THREAD

**Issue by semopz** [pnp/pnpjs#1336]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.6]

Please specify what version(s) of SharePoint you are targeting: [SPO/2019]

### Expected / Desired Behavior / Question
Be able to retrieve list data (items/rows) or fields using the renderListDataAsStream endpoint in batch request.

### Observed Behavior
Having one or multiple renderListDataAsStream responses in a batch causes a parsing error. It is expected that the response body will be on the same line otherwise you get an error. https://github.com/pnp/pnpjs/blob/c76e90f7e5481c002c6589468cd088be679c3cbb/packages/sp/batch.ts#L40

Unfortunately, SharePoint Online and 2019 will place a new line after `Row` or `Field` when ListData or ListSchema is included in the request. The parser expects the whole body to be on one line.

When your render options include either 2 or 4 you will get the following (i.e., the JSON is not minified)
```
... { "Row" : ***new line***
...
```
or
```
... { "Field": [  ***new line***
....
```
### Steps to Reproduce

```typescript
  // Set to true to avoid error (no list data)
  const forceSuccessBySkippingListData = false;

  const RenderOptions = forceSuccessBySkippingListData ? 1 : 2; // 3, 4 or 5 will also cause a failure
  const listTitle = 'batchParseErrorTest';
  const { list } = await sp.web.lists.ensure(listTitle);

  // this always succeeds (no batch)
  await list.renderListDataAsStream({ RenderOptions });

  const batch = sp.web.createBatch();
  const responseFromBatch = list.inBatch(batch).renderListDataAsStream({ RenderOptions });
  // This will fail if ListData option is included
  // https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#sprenderlistdataoptions-options
  await batch.execute()
  const result = await responseFromBatch;
  console.log(result)
```

### My views
Not sure what the best approach is here. Ideally the SharePoint API will be better behaved but we know that SP 2019 will never be fixed even if a fix is implemented in SPO. Maybe the only practical way is to look for any lines that **end** in `{ "Field": [` or `{ "Row" :` and assume that the next line is part of the same body. The problem then is that other edge cases may pop up. The above assumptions work whether or not you include the ContextInfo/1 but there are quite a lot of possible RenderOptions permutations. Will those weird new lines always appear at the same place with other options...

**Comment by patrick-rodgers** [comment]
Some methods just don't play well in batches for example many of the file operations. I am inclined to just add this method to the list of unsupported for batching rather than investing the 10's of hours in working on this case.
