### ISSUE TITLE
Cannot fetch teams using pnp/graph

### ISSUE THREAD

**Issue by TheShihan** [pnp/pnpjs#1337]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.8]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
I try to simply fetch a list of all MS Teams for a webpart using PnPJS (@pnp/graph). I read the documentation and believe to have set it up correctly (but I am not sure if documentation **https://pnp.github.io/pnpjs/graph/teams/** really reflects version 2.x.

### Observed Behavior
Fetching the teams results in the following error message:
```
Uncaught Error: Error making HttpClient request in queryable [404] Not Found ::> {
  "error": {
    "code": "NotFound",
    "message": "'GET /teams' is not supported.",
    "innerError": {
      "date": "2020-08-19T14:28:06",
      "request-id": "7dd4e55e-6ad5-4e70-b57c-77980354ed37"
    }
  }
}
```

### Steps to Reproduce
I have a service where I setup the context like this:
```
  public setup(context: WebPartContext): void {
    this.context = context;
    sp.setup({
      spfxContext: this.context,
    });
    graph.setup({
      spfxContext: this.context,
    });
  }
```
And in a function I try to access teams like this (note that the first line works, I can get a list of all groups):
```
        const groups = await graph.groups.get();
        const teams = await graph.teams.get();
```
Running it yields the error mentioned above (`"message": "'GET /teams' is not supported."`,);
I know that "/teams" is not in the v1.0 endpoint, but it is in the beta one, so I tried the following:
`const teams2 = await graph.teams.setEndpoint("beta").get();`
But it fails with the same message.
I don't understand why this happens, am I not supposed to use `graph.teams.get()`? Would I need to set explicitly the beta endpoint when I use graph.teams - but it doesn't seem to work and maybe I don't have to, at least I cannot find anything in the docs.
Btw: saw an example in your samples which confues me even more: **https://github.com/pnp/sp-dev-fx-webparts/blob/master/samples/react-teams-message/src/shared/services/ServiceProvider.ts**
Is this the way I should work with the graph API, using a graphClient instance, but why would there be graph.teams then?

**Comment by juliemturner** [comment]
Ok, several things here.  
1. There is a bug in the setEndpoint method thats making that method not work.  That part I can fix.
1. The "teams" endpoint isn't invokable by itself, although because of the way we build the library it's set that way now.** This is an implementation decision by the graph team and one I cannot comment on at all, but this isn't the first time we've seen that type of situation. That said you can call teams/{groupId}.  So... from the perspective of this library it's probable, like the issue we're having with the taxonomy termset api's we need to think of a better way to implement. Will do so and update.
1. Relevant to the point above is that the /teams/{groupId} works just fine on the v1.0 endpoint so no need to switch to the beta endpoint.**
>**Tested using the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)

**Comment by TheShihan** [comment]
OK, thanks for the feedback. In the meantime I've switched to not use PnPJS in this project and use the graphClient that comes with the SPFx framework (I believe it's a wrapper of [https://github.com/microsoftgraph/msgraph-sdk-javascript](https://github.com/microsoftgraph/msgraph-sdk-javascript)):
```
  public getTeamChannelIdByName(teamId: string, channelName: string) {
    return new Promise<string>(async (resolve, reject) => {
      this.context.msGraphClientFactory
        .getClient()
        .then((client: MSGraphClient) =>{
          client
            .api(`/teams/${teamId}/channels`)
            .filter(`displayName eq '${channelName}'`)
            .version("beta")
            .get((error, response: any) => {
              if (response !== null) {
                if ( response.value.length == 1) {
                  const channels: MicrosoftGraph.Channel[] = response.value;
                  resolve(channels[0].id);
                } else if (response.value.length < 1) {
                  reject(new Error(strings.ErrorNoChannelFoundWithConfiguredName));
                } else {
                  reject(new Error(strings.ErrorTooManyChannelsFoundWithConfiguredName));
                }
              } else {
                reject(new Error(strings.ErrorNoChannelFoundWithConfiguredName));
              }
            });
          })
        .catch(error => {
          reject(error);
        });
    });
  }
```

**Comment by juliemturner** [comment]
Yeah there is no reason you need to use PnPjs to make graph calls you can certainly use their SDK or even roll your own... totally your choice.
