### ISSUE TITLE
Batch update of list items in a site collection from a SPFx webpart deployed in another site collection is not working

### ISSUE THREAD

**Issue by The-ARMR** [pnp/pnpjs#1338]
### Category
- [ ] Bug
-[ ] Question

### Version

Please specify what version of the library you are using: [    2.0.5     ]

Please specify what version(s) of SharePoint you are targeting: [     Sharepoint Online SPFx version 1.8.2    ]

### Expected / Desired Behavior / Question
How do we do the batch update of list items in a site collection from a SPFx webpart deployed in another site collection ?

### Kindly bring your attention ,
I am able to perform the following actions using the Web property in sp pnp library

- Add an item,
- Edit an item,
- Delete an item

**but while trying to do batch update am facing an issue.**
batch updation is working well when the list to be updated is within the site collection where the spfx is deployed

### Observed Behavior
I found that batch update is working when updating accessing the web as **sp.web**,
but its not working when we try to do using **Web("<% absolute url of site collection %>")**

### Steps to Reproduce
my initial [Webpart].ts file

i configured the spfx context

`  public async onInit(): Promise<void> {
    await super.onInit();
    sp.setup({
      spfxContext: this.context,
    });
  }`

in the rendered React component tsx file

import is as shown below and **modifiedItems** is an array of object having id

`import { Web, sp } from "@pnp/sp/presets/all";`

`
private async updateAllTaskAsBatch(modifiedItems) {

    let sourceWeb = Web("absolute url of any site collection");
    let taskList = sourceWeb.getList(this.relUrlForList);
    let batch = sourceWeb.createBatch();
    console.log("batch = ", JSON.stringify(batch));
    console.log("batch baseURL = ", batch["baseUrl"]);
    for (let i = 0; i < modifiedItems.length; i++) {
      taskList.items
        .getById(modifiedItems[i].id)
        .inBatch(batch)
        .update(
          {
            Title: "ABC",
          }
        )
        .then(() => {
          console.log("Item updated with id", modifiedItems[i].id);
        })
        .catch((ex) => {
          console.log(ex);
        });
    }
    await batch.execute();
    console.log("Done");
  }
`

The same code works if we use sp.web to get list and batch but this will prevent me from updating list items which are in another site collection.

This is the error which happens when i try to do that
`
**parsers.js:130 Uncaught (in promise) Error: Error making HttpClient request in queryable [400] Bad Request ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"Invalid request."}}}**
`

**Comment by The-ARMR** [comment]
Hi @tavikukko ,

  I found the reason why i was getting that error
I tried the code in SP Editor, have to say its a cool tool easy to check query and doubts
  
**CODE WHICH WORKS :**
```
import { Web } from "@pnp/sp/presets/all";

(async () => {

  let sourceWeb = Web("https://mytenant.sharepoint.com/sites/Projects");

  const list = sourceWeb.getList("/sites/Projects/Lists/ProjectPlan");

  const batch = sourceWeb.createBatch();
  const items = list.items.inBatch(batch);

  items.getById(1).inBatch(batch)
    .update({ Title: "ABC", }).catch(console.warn);

  items.getById(3).inBatch(batch)
    .update({ Title: "DEF", }).catch(console.warn);

  await batch.execute();
  console.log('Done');

})()
  .catch(console.warn);  
```
**OUTPUT : SUCCESS**
![image](https://user-images.githubusercontent.com/65334016/91014398-f2727100-e606-11ea-9636-247844b276a8.png)

*************************************************************************************************

**Now check out the code not working**

```
import { Web } from "@pnp/sp/presets/all";

(async () => {

  let sourceWeb = Web("https://mytenant.sharepoint.com/sites/projects");

  const list = sourceWeb.getList("/sites/Projects/Lists/ProjectPlan");

  const batch = sourceWeb.createBatch();
  const items = list.items.inBatch(batch);

  items.getById(1).inBatch(batch)
    .update({ Title: "ABCD", }).catch(console.warn);

  items.getById(3).inBatch(batch)
    .update({ Title: "DEFG", }).catch(console.warn);

  await batch.execute();
  console.log('Done');

})()
  .catch(console.warn);
```
**OUTPUT : FAILED**
![image](https://user-images.githubusercontent.com/65334016/91014500-1f268880-e607-11ea-8b7e-062f43d5aec0.png)

*************************************************************************************************

**The difference is in the casing of the site naming "Projects" and "projects"** 
the true url of Projects Site is
https://mytenant.sharepoint.com/sites/Projects

and i was trying with url
https://mytenant.sharepoint.com/sites/projects

I don't know what is the reason, why casing mattered for batch update as there is no issue for adding, deleting and updating individual item.
I would be really glad to know the reason behind my situation, or do let me know where i went wrong.

**Comment by patrick-rodgers** [comment]
For whatever reason batches are case sensitive, nothing we can really fix with that. Glad you got things working, thanks @tavikukko for the support. Going to closet his as answered. Thanks all!
