### ISSUE TITLE
Documentation: pnpjs\index.html#grab-bundle-file

### ISSUE THREAD

**Issue by ronaldborman** [pnp/pnpjs#134]
In [Issue 91, comment 386263701](https://github.com/pnp/pnpjs/issues/91#issuecomment-386263701) @koltyakov mentioned that the root object of the UMD bundle is pnp, not $pnp.

In the paragraph ['Grab Bundle File'](https://pnp.github.io/pnpjs/pnpjs/index.html#grab-bundle-file) however, $pnp is still used.

**Comment by koltyakov** [comment]
Thank for reporting this, we'll take a look.

**Comment by patrick-rodgers** [comment]
@pnp/js is a special case. Because it was made to be a drop in replacement for sp-pnp-js it does in fact expose a global $pnp. This is because that is what sp-pnp-js exposes. All of the other libraries expose and attach their code to a global named pnp. This also avoids the problem of overlap since pnpjs exposes much of the same stuff as the individual libraries and if they ended up on the same page somehow it would be last one in wins - which would be confusing to debug.

I know this is a little confusing - but the recommendation when migrating is to use the new libraries and not rely on the pnpjs bundle. Probably a good idea for us to call that out explicitly in the docs.

**Comment by ronaldborman** [comment]
Thanks Patrick. Due to 'business political' reasons, I'm forced to include pnp via a script tag on an HTML page. Because the CDN option is not yet available, I'm using https://unpkg.com/@pnp/pnpjs@1.1.1/dist/pnpjs.es5.umd.js as the src attribute value. No other pnp package is used. I'm using it on a self defined HTML page without other script tags.

When I try to reference $pnp in my code, I get a ReferenceError ('$pnp is not defined') and window.$pnp is undefined. When I reference pnp (or window.pnp) the correct root object is returned.

Should there, in the described situtation, be a defined pnp global variable (and a missing $pnp variable)?

**Comment by patrick-rodgers** [comment]
Hmmm...ok, will definitely take a look. Thanks!

**Comment by ronaldborman** [comment]
Sorry for the confusion, but the src attribute value I mentioned above should be 'https://unpkg.com/@pnp/pnpjs@1.1.1/dist/pnpjs.es5.umd.bundle.js' (including the word 'bundle' at the end).

If I'm using 'https://unpkg.com/@pnp/pnpjs@1.1.1/dist/pnpjs.es5.umd.js' (without the word 'bundle') the $pnp variable is an empty object and the pnp variable is undefined.

**Comment by patrick-rodgers** [comment]
You are right, it definately looks like it is using "pnp" - sorry for the confusion on our end. Need to think about it - if everyone is currently using pnp I don't want to break them by changing it...thoughts? Easy to update the docs to match what is out there.

**Comment by ronaldborman** [comment]
Although I can only speak for myself, I´m perfectly comfortable with using pnp and abolishing $pnp, which I found confusing. Maybe you could, besides updating the docs, mention it in the Transition Guide so that transitioning CDN users also know about it.

**Comment by patrick-rodgers** [comment]
Good idea. I think this is the path we'll take then.

**Comment by patrick-rodgers** [comment]
@ronaldborman good news for you the files just got published to cdnjs, hope that helps. We will still look at updating docs as discussed but wanted to let you know.

**Comment by ronaldborman** [comment]
@patrick-rodgers thanks, I appreciate the feedback. This will help a lot.

**Comment by patrick-rodgers** [comment]
@ronaldborman - made the changes, they will be part of the next release and this Friday's beta. One note after re-reading the thread - you should always aim to use the "bundle" of pnp/pnpjs if you want all the code included in a single file. The other expects that you have individually loaded the other libraries globally.
