### ISSUE TITLE
Docs/github.io dead link

### ISSUE THREAD

**Issue by semopz** [pnp/pnpjs#1341]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Details
The register an add in section is missing from this page: https://pnp.github.io/pnpjs/debugging/#register-an-add-in

The above link appears halfway down the page of the nodejs article https://pnp.github.io/pnpjs/nodejs-support/#indexts

**Comment by juliemturner** [comment]
We recently reworked that entire contributing section to make it more easily readable and digestable and the registering an add-in reference is now here: https://pnp.github.io/pnpjs/contributing/local-debug-configuration/#sp-values 
which references the article under authentication here: https://pnp.github.io/pnpjs/authentication/sp-app-registration/

**Comment by semopz** [comment]
Thanks. Would suggest you update https://pnp.github.io/pnpjs/nodejs-support/#indexts that points to the dead link. Would do a pull request myself but not sure the nodejs doc page is maintained

**Comment by juliemturner** [comment]
I'm not sure what this means

>Would do a pull request myself but not sure the nodejs doc page is maintained

If a page is being shown in our docs then we consider it to be live, so do feel free to make a PR.. but that said if you're uncomfortable with the process I'm certainly happy to adjust it in my next PR.

**Comment by semopz** [comment]
Ah ok. The md page was in the root of docs. I was looking for it under docs/nodejs
