### ISSUE TITLE
pnp js move/copy by path doesn't work properly for document sets

### ISSUE THREAD

**Issue by parwejp** [pnp/pnpjs#1344]
Hi pnp team,

I was trying to move/copy the document sets from one document library to another. Both libraries uses same site content type and are having same fields. 

https://pnp.github.io/pnpjs/sp/folders/#copy-by-path. 

My code looks like this.
await sp.web
        .getFolderByServerRelativeUrl(
          sourceDocumentSetUrl
        )
        .copyByPath(
          destinationDocumentSetUrl, //Absolute 
          true
        );
await sp.web
        .getFolderByServerRelativeUrl(
          sourceDocumentSetUrl
        )
        .moveByPath(
          destinationDocumentSetUrl, //Absolute 
          true
        );

### Category
- [X] Enhancement
- [X ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.7]

Please specify what version(s) of SharePoint you are targeting: [   SPO      ]

### Expected / Desired Behavior / Question
I was expecting that document set will get copied along with metadata and document within. 

### Observed Behavior
I found inconsistent behavior..sometimes document sets are copied correctly with no issues. However there were cases where document sets get converted into folder content type and it's metadata is lost. Found this behavior more often on document sets which are 'unmodifed' (not modified even once). 

I found same behavior on SPO rest api as well. (_api/SP.MoveCopyUtil.MoveFolderByPath(), _api/SP.MoveCopyUtil.CopyFolderByPath()). Just wanted to know if there is any workaround to get this issue/enhancement addressed.

### Steps to Reproduce
1. Create SPFx extension or webpart. 
2. Try using above code to copy or move document sets to different document library.

**Comment by patrick-rodgers** [comment]
If the OOTB rest method being called directly (which is basically all we do) doesn't support this we don't have any special way to achieve this.
