### ISSUE TITLE
Enhancement: Power Apps REST endpoint

### ISSUE THREAD

**Issue by hugoabernier** [pnp/pnpjs#1347]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.8 ]

Please specify what version(s) of SharePoint you are targeting: [ SPO ]

### Expected / Desired Behavior / Question

It would be great to add functionality to make the integration with Power Apps easier. For example, a way to enumerate all Power Apps available for the current user.

I'd be happy to contribute to this, but I may need some help to find a way to actually retrieve the list of Power Apps.

### Observed Behavior
I could not find anything

### Steps to Reproduce

1. Open PnPjs documentation
1. Search for Power Apps
1. Find no results

**Comment by juliemturner** [comment]
Upon further discussion I'm to understand that the request is to find out if anyone is aware of any REST endpoints to access the PowerApps that a user has access to. As far as I'm aware the Microsoft Graph has no endpoint that can provide that information but if I'm wrong we could absolutely investigate adding those endpoints to our graph implementation.

**Comment by juliemturner** [comment]
Going to close this as I think at this time supporting PowerApp API is outside the purview of PnPJS libraries.
