### ISSUE TITLE
By setting sp headers to accept application/json the result is still xml

### ISSUE THREAD

**Issue by bclevering** [pnp/pnpjs#1348]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.0.8     ]

Please specify what version(s) of SharePoint you are targeting: [    2019     ]

### Expected / Desired Behavior / Question
Adding an item to a list completes successfull

### Observed Behavior

parsers.js:22 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parsers.js:22
![image](https://user-images.githubusercontent.com/8439274/91546837-5f497c00-e923-11ea-8f93-6c6c0f2f03d9.png)
![image](https://user-images.githubusercontent.com/8439274/91546888-75efd300-e923-11ea-9be5-101341a8332c.png)

### Steps to Reproduce
```
sp.setup({
  ie11: false,
  sp: {
    baseUrl: "<URL>",
    headers: {
      Accept: "application/json; odata=minimalmetadata",
      "Content-Type": "application/json",
    }
  },
  spfxContext: this.context,
});
```

**Comment by bclevering** [comment]
This problem is on the Microsoft Edge (Version 84.0.522.63) browser. If i use Google Chrome this isn't an issue...

**Comment by patrick-rodgers** [comment]
If you don't set anything except the context in the config does it work as expected? The fact it works in one browser but not another makes me think it isn't something with the library. What if you remove the "Content-Type" header? We are using this: "application/json;odata=verbose;charset=utf-8" by default.

**Comment by bclevering** [comment]
@patrick-rodgers 
if i use:

_sp.setup({
  ie11: false,
  sp: {
    headers: {
      "Accept": "application/json;odata=verbose;charset=utf-8",
      "Content-Type": "application/json",
    }
  },
  spfxContext: this.context,
});_

it doesn't work for Edge but it is still working for Chrome. 
If i remove the Content-Type and/or the Accept header:

_sp.setup({
  ie11: false,
  spfxContext: this.context,
});_

The request doesn't work on Chrome and Edge.

The strange thing is if i remove everything except the context the call that is crashing is the /_api/web/currentuser request (this one is translated to xml) if i add the options of above then the /_api/web/currentuser request is correct but then the "/_api/web/lists/getByTitle" request is translated to xml...

**Comment by bclevering** [comment]
i've written the whole procedure completly in code and then it works on Edge and Chrome.

**Comment by patrick-rodgers** [comment]
Unsure on "i've written the whole procedure completely in code" but the issues you are reporting are ones we aren't able to reproduce. The library processes billions of requests a month across many browsers - unsure what might be wrong here. Do you have anything locally in your network or other configuration that may change these behaviors? If you test the same calls against SPO do they work as expected?

If you look at the response in the browser tools - what does it look like? Is it the data just in xml format - or is it something else like an error page or other type of response?

**Comment by bclevering** [comment]
i've completly written out the functionality to create a list item (obtaining ListItemEntityTypeFullName, getting the formdigest and then adding an item to a list) if i use this funcionality it's working correctly...

if i then use the functionality of the PnPJS library:

_const iar: IItemAddResult = await sp.web.lists.getByTitle("My List").items.add({
  Title: "Title",
  Description: "Description"
});_

then it crashes on the obtaining the ListItemEntityTypeFullName with the error i described above. The xml is the XML output of the request with the ListItemEntityFullName.

for now it's "fixed" because the code is now working....

**Comment by harshdamaniahd** [comment]
I am having the same issue

**Comment by DennisKuhn** [comment]
I am having the issue if I use 
```
            const isolatedSP = await sp.createIsolated();

            isolatedSP.setup({
            sp: {
                baseUrl: siteUrl,
                headers: {
                    "Accept": "application/json;odata=verbose;charset=utf-8"
                }
            },
            });

            this.list = isolatedSP.web.lists.getById(listId);
```
and then call
```
        try {
            const addResponse = await this.list.items.add(spRequest);
            newID = addResponse.data.ID;
            console.log(`controller/this.submit() response=${newID}`, { request, spRequest, addResponse });
        } catch (addError) {
            console.error('controller/this.submit() response', {addError, request, spRequest });
            return addError.message ?? addError;
        }
```
In the chrome debugger I see my accept header coming through:
![image](https://user-images.githubusercontent.com/992724/114129280-61ac9380-9952-11eb-9d12-381f5506462c.png)

But the response is XML:
![image](https://user-images.githubusercontent.com/992724/114129384-928cc880-9952-11eb-9974-2945372c197b.png)

If I do it manually in PostMan it's as expected. I receive JSON if I specify accept, and receive XML if I don't.

**Comment by DennisKuhn** [comment]
It seems the problem was because in my first request in that browser, I did NOT specify accept=json, it responded with XML. The further calls replied a status 304 which caused the previous response to be used. The change in the accept header is ignored (by SharePoint). Clearing cache helps ;-)
