### ISSUE TITLE
Filter calculated field from lookup list

### ISSUE THREAD

**Issue by yogendermanral** [pnp/pnpjs#1355]
List 1 column 
 Title
 IsActive choice field
 IsActiveCal calculated field based on IsActive field
Created a calculated field to get yes/no field value 
 
List 2
  Col1 lookup column pointing to list1

web.lists.getByTitle("List2").items
            .filter("Col1/IsActiveCalc eq '1'")
            .select("ID", "Title", "Col1/Title", "Col1/IsActiveCalc" )
            .expand("Col1")
            .get();

Query not working
Filter    **_.filter("Col1/IsActiveCalc eq '1'")_** not working to get calculated field

Please help asap
Thanks

**Comment by koltyakov** [comment]
@yogendermanral,

When something is not supported in REST API it is also not supported in PnPjs, as the library constructs nothing but HTTP requests to REST APIs.

**Comment by yogendermanral** [comment]
> @yogendermanral,
> 
> When something is not supported in REST API it is also not supported in PnPjs, as the library constructs nothing but HTTP requests to REST APIs.

Thanks for the quick response
It means we cant filter on the lookup field calculated column in rest

**Comment by koltyakov** [comment]
Checked this. Generally, the calc fields can be used in the dependent lookups therefore in REST's "expand from lookup values". But the limitation is the same as with the expanded fields data types. If a calc field resulted data type is supported for being used it should work, if it's unsupported resulted type as Boolean (Yes/No) it won't.

```typescript
// Will work - LookupField/CalcString has `Text` resulted data type
await list.items
  .filter(`LookupField/CalcString eq '1'`)
  .select('*,LookupField/CalcString')
  .expand('LookupField')
  .get()
  .then(console.log); 

// Won't work - LookupField/CalcYesNo has `Boolean` resulted data type
await list.items
  .filter(`LookupField/CalcString eq '1'`)
  .select('*,LookupField/CalcString')
  .expand('LookupField')
  .get()
  .then(console.log); 
```

Anyways it's the REST nuance/limitation to consider. It also could be seen in an error message from the API, e.g. ```{"odata.error":{"code":"-1, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The query to field 'LookupField/CalcYesNo' is not valid."}}}```.

**Comment by yogendermanral** [comment]
> Checked this. Generally, the calc fields can be used in the dependent lookups therefore in REST's "expand from lookup values". But the limitation is the same as with the expanded fields data types. If a calc field resulted data type is supported for being used it should work, if it's unsupported resulted type as Boolean (Yes/No) it won't.
> 
> ```ts
> // Will work - LookupField/CalcString has `Text` resulted data type
> await list.items
>   .filter(`LookupField/CalcString eq '1'`)
>   .select('*,LookupField/CalcString')
>   .expand('LookupField')
>   .get()
>   .then(console.log); 
> 
> // Won't work - LookupField/CalcYesNo has `Boolean` resulted data type
> await list.items
>   .filter(`LookupField/CalcYesNo eq 1`)
>   .select('*,LookupField/CalcYesNo')
>   .expand('LookupField')
>   .get()
>   .then(console.log); 
> ```
> 
> Anyways it's the REST nuance/limitation to consider. It also could be seen in an error message from the API, e.g. `{"odata.error":{"code":"-1, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The query to field 'LookupField/CalcYesNo' is not valid."}}}`.
> 
> UPD: To work around the limitation, you can try using a string or number as resulted data type in a calculated field.

Thanks it work
I found the calulated filed type was of text type but was returning boolean. so i converted it to string ant it worked
Thanks for reply
