### ISSUE TITLE
Wrong exception message on the updating/adding opeartions

### ISSUE THREAD

**Issue by dvd73** [pnp/pnpjs#1356]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0.6      ]

Please specify what version(s) of SharePoint you are targeting: [    O365     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
The batch size exceeds 1048576 bytes. I expect exception with the message: _The maximum number of bytes allowed to be read from the stream has been exceeded. After the last read operation, a total of 1063984 bytes has been read from the stream; however a maximum of 1048576 bytes is allowed._ 

### Observed Behavior
However, I'm getting "Invalid response, line 0".
```
Error: Invalid response, line 0
    at Function.8xxP.SPBatch.ParseResponse (batch.js:41)
    at SPBatch.<anonymous> (batch.js:178)
    at step (tslib.es6.js:99)
    at Object.next (tslib.es6.js:80)
    at fulfilled (tslib.es6.js:70)
```

### Steps to Reproduce
Try to update Note field with large content.

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
Thanks for reporting, we'll have a look.

**Comment by patrick-rodgers** [comment]
I tested using a note field as you suggested and the error message doesn't come back as what you want - it comes back as an html error page. Meaning we can't parse out any information as there isn't an associated error message. We can improve our error reporting here so we give back a meaningful error instead of the invalid response one (which is just an unhelpful failed json parse) but it will still be more general than the string you want.

**Comment by patrick-rodgers** [comment]
So I was right in my comment I deleted - the error that comes back is a generic html error page (hence the parsing error). So we can report a better error than "Invalid response, line 0" but we can't report anything like what you want. Best is the status and status text, which in my test using a large note field as you indicated is just 503 - Service Unavailable.

**Comment by dvd73** [comment]
I use a batch containing 1 command to update Note field. The server response  is not a html page:
![image](https://user-images.githubusercontent.com/8290112/92522404-5ca22d00-f227-11ea-90d0-9f2c22592153.png)
![image](https://user-images.githubusercontent.com/8290112/92522418-6166e100-f227-11ea-9d7c-7a9f26f95d08.png)

**Comment by patrick-rodgers** [comment]
Ok, that is not the behavior I was able to duplicate, and I tested in the same way. Can you share your test code? How are you generating the note content?

**Comment by dvd73** [comment]
`	interface IDatePeriod{
		From: Date;
		To: Date;
		ExtendedProps?:{};
	}
	
	interface IEventInfo extends IDatePeriod {
		Id: string;		
	}
	
	interface IEventRange extends IDatePeriod {
		Id: number;
		UserId: number;
		Count: number;
		Events: IEventInfo[];
	}
	
	class SharePointRepository {
		private async saveEventRanges(ranges: IEventRange[], progressCallback?: DatePeriodProgressCallback): Promise<void> {
			const tz = await this.getTimeZone();
			const list = sp.web.getList(this.getListUrl(listUrl));
			const entityTypeFullName = await list.getListItemEntityTypeFullName();

			if (typeof progressCallback === 'function' && ranges.length > 0) {
				progressCallback({ Period: ranges[0], Index: 0, Total: ranges.length });
			}

			const batch = sp.web.createBatch();

			ranges.forEach((range, idx) => {
				//#region success handler
				let success = (function () {                
					if (typeof progressCallback === 'function') {
						progressCallback({ Period: this, Index: idx + 1, Total: ranges.length });
					}
				}).bind(range);
				//#endregion

				if (range.Id === 0) {
					// add a new range
					list.items.inBatch(batch).add({
						Title: range.From.getFullYear() + ' - ' + range.ExtendedProps['UserName'],
						USRangeStart: this.toServerDate(range.From, tz),
						USRangeEnd: this.toServerDate(range.To, tz),
						USRUserId: range.ProfileId,
						USCount: range.Events.length,
						USValue: JSON.stringify(range.Events)
					}, entityTypeFullName).then(success);
				} else {
					// update existing range
					list.items.getById(range.Id).inBatch(batch).update({
						USCount: range.Events.length,
						USValue: JSON.stringify(range.Events)
					}, '*', entityTypeFullName).then(success);
				}
			});

			await batch.execute();
		}
	}`
