### ISSUE TITLE
how to get a term custom properties in pnpjs v2?

### ISSUE THREAD

**Issue by yarick123** [pnp/pnpjs#1359]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.0.9, 2.0.10  ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint online  ]

### Observed Behavior

cannot find any possibility to get a term custom properties. Neither of ITermInfo.properties, ITermInfo.localProperties contains this information.

**Comment by patrick-rodgers** [comment]
You haven't shared any code showing what you've tried. We are limited by [the available API methods](https://docs.microsoft.com/en-us/graph/api/resources/termstore-store?view=graph-rest-beta) so if the data isn't coming back we wouldn't have any special way to make it come back.

**Comment by yarick123** [comment]
I used the following code:
```ts
import { ITermInfo, ITermSet, SPBatch, sp } from '@pnp/sp-commonjs';
// ...
	const termset: ITermSet = sp.termStore.sets.getById(termsetId);
	const terms: ITermInfo[] = await termset.children.select('id', 'labels', 'childrenCount', 'localProperties')();

	console.log('Raw terms:', terms)
```
the result was:
```json
Raw Term: [
  {
    "id": "3a184017-bca8-49fa-9b23-161b7ec89a11",
    "labels": [
      {
        "name": "Englisch",
        "isDefault": true,
        "languageTag": "de-DE"
      },
      {
        "name": "English",
        "isDefault": true,
        "languageTag": "en-US"
      }
    ]
  },
...
```
the term looks as:
![image](https://user-images.githubusercontent.com/2544771/93062699-98992000-f675-11ea-9b8c-d053ae99f4c0.png)

So, there was no localProperties field in the results in spite of existence of the local properties in the terms.

I tried also not to use select() at all. There were more fields, but unfortunately no localProperties.

Additionally it was interesting. that there was no **childrenCount** field even for the terms with children.

**Comment by yarick123** [comment]
P.S. the same behaviour I experience with the PnPjs v2.0.10
