### ISSUE TITLE
Incorrect Reference in @pnp/nodejs-commonjs

### ISSUE THREAD

**Issue by RequieM88** [pnp/pnpjs#1361]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0.9   ]

Please specify what version(s) of SharePoint you are targeting: [    Online     ]

### Expected / Desired Behavior / Question
Using nodejs (e.g. gulp) via commonjs packages es import/export should not be occuring causing breaking issue.

### Observed Behavior
Using @pnp/nodejs-commonjs package references @pnp/sp instead of @pnp/sp-commonjs in stream.js. Causes import "../folder" error when executing through node.

### Steps to Reproduce
Open @pnp/nodejs-common/sp-extensions/stream.js
See: var files_1 = require("@pnp/sp/files"); 
Should be: var files_1 = require("@pnp/sp-commonjs/files");

**Comment by koltyakov** [comment]
Dup https://github.com/pnp/pnpjs/issues/1358

**Comment by patrick-rodgers** [comment]
Yep, duplicate. Will have a look at pushing a patch release to resolve this.

**Comment by RequieM88** [comment]
Thanks all, hadn't spotted the other post. Will locally correct for the time being then!

**Comment by patrick-rodgers** [comment]
This is fixed in 2.0.10 which is being published currently. Issue was actually with a regex we used in the build pipeline to update the import paths to ensure they used the -commonjs suffix. That is resolved and you should no longer have issues. Thanks again for reporting it.
