### ISSUE TITLE
'Error: Cannot find module '@pnp/sp/files'' + NodeJS environment

### ISSUE THREAD

**Issue by derhallim** [pnp/pnpjs#1362]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

I am trying to use PnPJS with a NodeJS project. Installed the following modules: 

 "@pnp/graph-commonjs": "^2.0.9",
    "@pnp/nodejs-commonjs": "^2.0.9",
    "@pnp/sp-commonjs": "^2.0.9"

NodeJS version: 10.17.0
NPM version: 6.11.3

When running npm start, am getting the following error: 

'Error: Cannot find module '@pnp/sp/files''
Stack: Error: Cannot find module '@pnp/sp/files'

**Comment by koltyakov** [comment]
Duplicate https://github.com/pnp/pnpjs/issues/1358

**Comment by derhallim** [comment]
Thanks @koltyakov
