### ISSUE TITLE
PNP web get list - wrong web URL

### ISSUE THREAD

**Issue by Mykie89** [pnp/pnpjs#1364]
Hi,

I am new in SPFX webpart and I have and error If I deploy my package and add the new webart tot the page
In my webpart I want to get list items and I get the followig error:
`{"odata.error":{"code":"-1, System.ArgumentException","message":{"lang":"en-US","value":"List 'TestList' does not exist at site with URL 'https://***-app6e62cac43b2f4e65a24bce8301b75878.sharepoint.com/sites/testsite'."}}}`

I think the problem is the URL, I don't no why the appURL is in the context, I need my root URL : https://****..sharepoint.com/sites/testsite

In my code I set the onIni method:
```
public onInit(): Promise<void> {

    return super.onInit().then(_ => {
  
      pnp.setup({
        spfxContext: this.context
      });
    });
  }
```
and use: 
`pnp.sp.web.lists.getByTitle("TestList");`

Please help!
Thanks,
Mykie

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

**Comment by koltyakov** [comment]
Hi @Mykie89,
 
Please make sure that sp.setup is called before the API requests and that the SPFx web part [is not isolated](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/isolated-web-parts) (which looks like the case and the URL in the error contains app hash).

**Comment by Mykie89** [comment]
Hi @koltyakov ,

thanks for your reply, the problem was that I use isDomainIsolated": true, instead of false.
