### ISSUE TITLE
pnp/sp on IE11 polyfill not working

### ISSUE THREAD

**Issue by SchroeerM** [pnp/pnpjs#1365]
I already readed that the Internet Explorer 11 is no longer supported but I hope that someone can help me with this problem.

Short explanation:
We use pnp/sp to get the email address of the current logged in Sharepoint User within our react-apps. This simple request to the sharepoint-api fails with the current version.

The error-message is "The Object doesn't support the property or method "configure".
I've followed a lot of polyfill-explanations and tutorials but nothing seems to work. 

### Category
- [ ] Enhancement
- [X] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.9  ]

Please specify what version(s) of SharePoint you are targeting: [ 2019 ]

### Desired Behavior
The request for the current user works as well in internet explorer 11

**Comment by koltyakov** [comment]
Hi @SchroeerM,
Did you try [IE mode](https://pnp.github.io/pnpjs/concepts/ie11-mode/)?

**Comment by SchroeerM** [comment]
Sure. Thats the first change ive made.

**Comment by patrick-rodgers** [comment]
Can you share your code that generates the error?

**Comment by SchroeerM** [comment]
`import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/site-users/web";

class SharePointProvider {
  constructor(context) {
    this.sharePointSetup(context);
    this.currentUserName = "";
    this.currentUser = undefined;
  }

  async getCurrentUser() {
    try {
      this.currentUser = await sp.web.currentUser.get();
      this.currentUserName = this.currentUser.LoginName.split("\\")[1];
      return this.currentUser;
    } catch (error) {
      console.log("Error fetching username (SharePoint)");
      console.log(error);
      throw error;
    }
  }`

This is only a part of my SharePointProvider but simply the Line `this.currentUser = await sp.web.currentUser.get();` causes the error. The corrispondable polyfills are imported in my index.js

**Comment by koltyakov** [comment]
Sounds identical to https://github.com/pnp/pnpjs/issues/941

@SchroeerM aren't you importing `@pnp/polyfill-ie11`?

**Comment by SchroeerM** [comment]
Of cause i import the polyfills but as I mentioned in my post I import these in my index.js. When I move the imports to my SharepointProvider the error is still the same.

**Comment by koltyakov** [comment]
It's always better confirming explicitly, sorry sounding like asking something you thought you already told. As "I'm loading all required polyfills" doesn't say which exactly polyfills are actually loaded and that they were loaded before the library packages. Even a `context` in a custom class constructor doesn't necessarily mean it is the SPFx `context` object.

Another guess, to check/try. Can you try replacing partial imports with `all` preset?

```typescript
import '@pnp/polyfill-ie11'; // verify it's latest 2.0.2
import { sp } from '@pnp/sp/presets/all';

// ...
```

For me, the error with `.configure` method sounds really weird.

**Comment by PathToSharePoint** [comment]
Also, how do you test the code? I am assuming online workbench but just wanted to confirm. This looks more like the kind of error you would get on a classic page.

**Comment by SchroeerM** [comment]
I fully understand that and i'm sorry if my english sounds not so comfortable and kind. 

I checked your sugestions. I Import the polyfills but I used the older beta-polyfills as suggested in another older ticket. I updated back to the version 2.0.2 but the error is still the same. Also I changed the partial imports with the `all` imports. but it changed nothing.

Unfortunately I dont know how a correct SPFx Context should look like. When I view the this.context from my Component which I give into my data-provider It shows to me more like an react context on which every property is undefined.
`[object Object]
   {
      [functions]: ,
      Symbol()_7.q2155gzjggx: undefined,
      Symbol()_n.q2155gzjggx: undefined,
      Symbol()_o.q2155gzjggx: undefined,
      Symbol()_p.q2155gzjggx: undefined,
      Symbol(__extensions)_14.q2155gzjgg: undefined,
      Symbol(react.block)_13.q2155gzjgg: undefined,
      Symbol(react.concurrent_mode)_11.q2155gzjgg: undefined,
      Symbol(react.context)_w.q2155gzjggx: undefined,
      Symbol(react.element)_q.q2155gzjggx: undefined,
      Symbol(react.forward_ref)_x.q2155gzjggx: undefined,
      Symbol(react.fragment)_s.q2155gzjggx: undefined,
      Symbol(react.lazy)_10.q2155gzjgg: undefined,
      Symbol(react.memo)_z.q2155gzjggx: undefined,
      Symbol(react.portal)_r.q2155gzjggx: undefined,
      Symbol(react.profiler)_u.q2155gzjggx: undefined,
      Symbol(react.provider)_v.q2155gzjggx: undefined,
      Symbol(react.strict_mode)_t.q2155gzjggx: undefined,
      Symbol(react.suspense)_y.q2155gzjggx: undefined,
      Symbol(react.suspense_list)_12.q2155gzjgg: undefined
   }
`

**Comment by juliemturner** [comment]
And just to be sure, you've verified this works in a modern browser, just to eliminate some other problem?

**Comment by SchroeerM** [comment]
All other Browsers work without any problems. I've testet it in Opera (Chrome-based), Chrome, Firefox and Edge.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
