### ISSUE TITLE
How to load a term by its id?

### ISSUE THREAD

**Issue by MarkusLanger** [pnp/pnpjs#1366]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.9]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I want to load a single term directly by its id. In version 1.x it was possible => https://pnp.github.io/pnpjs/v1/sp-taxonomy/docs/terms/#load-single-term 
I found no information in the current documentation => https://pnp.github.io/pnpjs/sp/taxonomy/#pnpsptaxonomy

I only have the Id of the term. I don’t want to manually go through the entire store until I find the term.
Isn’t there a possibility or am I missing something?

**Comment by patrick-rodgers** [comment]
Does [this not work](https://pnp.github.io/pnpjs/sp/taxonomy/#get-by-id_2)?

**Comment by MarkusLanger** [comment]
For me it looks like I need the TermSet id for this request.
`const info2: ITermInfo = await sp.termStore.sets.getById("338666a8-1111-2222-3333-f72471314e72").getTermById("338666a8-1111-2222-3333-f72471314e72")();`

But I only have the Term Id. And in version 1.x it was possible this way:
`const term: ITerm = store.getTermById("0ba6845c-1468-4ec5-a5a8-718f1fb05431");`

**Comment by patrick-rodgers** [comment]
Ok, but we are now calling the [new taxonomy API](https://docs.microsoft.com/en-us/graph/api/resources/termstore-store?view=graph-rest-beta) so are bound by the available methods there.

**Comment by MarkusLanger** [comment]
Too bad, I’ll have to use the old version.
