### ISSUE TITLE
Spfx extension to move document 

### ISSUE THREAD

**Issue by AshokSPFX-cloud** [pnp/pnpjs#1367]
I have question regarding spfx extension , i have library1 where document marked as record (Label applied) i want to build spfx extension to MOVE document from library1  another library2 with all metadata , 

The OOB move is feature allow me to move but i want to target specific library(Library2) so user does not have to navigate ,
below is what i can find in PNPjs , but how to write post with all metadata moving

Version:SharePoint Online
Type Issue:Question

import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/files";

// destination is a server-relative url of a new file
const destinationUrl = `/sites/dev/SiteAssets/new-file.docx`;

await sp.web.getFileByServerRelativePath("/sites/dev/Shared Documents/test.docx").moveTo(destinationUrl);

**Comment by koltyakov** [comment]
Documents declared as records can't be even moved within one library. That's by the design of the record management.

`moveTo` and `moveByPath` methods keep moved documents metadata, but the destination library has to have the same fields as the origin. Otherwise, missed fields will be ignored.

**Comment by AshokSPFX-cloud** [comment]
yes destination library have same metadata column, Out of box Moveto allow me to move record document , i am figuring out the way in command extension ,is there a way to write to post ?

**Comment by koltyakov** [comment]
OOTB also blocks moving documents declared as records, as it's a FileRef property change at least it always was. Maybe you're referencing something else.

> is there a way to write to post

Can't understand what do you mean, sorry. What metadata you need to update, while `move to` method(s) copies documents and metadata. Well, let's assume the structure is different when before copying make a request to document's item, keep it in memory, copy/move, map/reduce original metadata and update the moved document item's metadata. Are you asking how to perform this?

```typescript
const file = web.getFileByServerRelativePath('/source/path/doc.docx');
const metadata = await file.listItemAllFields();
await file.moveByPath('/source/path/doc.docx', true);
const movedDocItem = await web.getFileByServerRelativePath('/source/path/doc.docx').getItem();
await movedDocItem.update(reduceMetadata(metadata)); // reduceMetadata - custom function which transforms metadata
```

**Comment by AshokSPFX-cloud** [comment]
extremely sorry i may not able to explain let me frame in this way ,i want to perform below operation
1)User can select multiple document from Library 1
2) on Click of extension selected document should move to Library2 

Before i am doing this with WF copy and deleting now want to build a extension using single operation move

**Comment by koltyakov** [comment]
So it sounds like a question, how to implement an extension using SharePoint Framework.
Unfortunately, this is not an area covered by PnPjs. The repository issues list is for reporting library-related issues, questions about internals that could have been not covered in docs, etc.

For SPFx, I'd suggest researching:
- SPFx docs, https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview
- community samples:
  - https://github.com/pnp/sp-dev-fx-extensions
  - https://github.com/pnp/sp-dev-fx-webparts
  - https://github.com/pnp/sp-dev-solutions
