### ISSUE TITLE
Cannot get related items with  PnPjs search on workflow task content type  

### ISSUE THREAD

**Issue by milindsaraswala** [pnp/pnpjs#1370]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.6 ]

Please specify what version(s) of SharePoint you are targeting: [ 2019 ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

I am working on spfx project and using pnp search. My requirement is to search for pending workflow task for that I have created **result source** at site collection level. Builder query as below

`{searchTerms}  ContentTypeId:0x0108* Path:{SiteCollection.URL}  WorkflowOutcomeOWSTEXT:Pending `

Now I am using SPFx to retrieve data. I cannot get related item of the task or related item id for the original item. Other than that I get all data. Let me know I am doing wrong or there is some issue pnpjs

 My code as below

```
const getContentTypeData = async (rowLimit: number, sourceId: string, querytext: string, selectedProperties: string[]) => {
	const appSearchSettings: ISearchQuery = {
		RowLimit: rowLimit,
		EnableInterleaving: true,
		SourceId: sourceId,
		TrimDuplicates: false,
		Querytext: querytext,
		SelectProperties: selectedProperties
	}
	const searchResults: SearchResults = await sp.search(appSearchSettings)
	return searchResults
}
const selectedProperties = ['ListItemID', 'Path', 'Title', 'HitHighlightedSummary', 'LastModifiedTime', 'ParentLink', 'RelatedItems']
const rowLimit = 10
let queryText = `AssignedTo:"${displayName}"` // Passing current user displayName
getContentTypeData(rowLimit, searchSourceId.PendingTask, queryText, selectedProperties)
					.then((r: SearchResults) => {
						setPendingTask({ totalRows: r.TotalRows, primarySearchResults: r.PrimarySearchResults })
					})
					.catch(console.warn)
```

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!

**Comment by zenaidura** [comment]
I am getting the similar error. Assigned to in querytext does not work correctly for all users. Seems like the permissions are not being calculated correctly?

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
