### ISSUE TITLE
Property 'execute' does not exist on type 'IObjectPathBatch' SPFx 1.11

### ISSUE THREAD

**Issue by sharepointkonsult** [pnp/pnpjs#1375]
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Expected or Desired Behavior
Would like to make batch requests using taxonomy.

Observed Behavior

```TypeScript
import {taxonomy, ITerm, ITermSet, ITermStore} from '@pnp/sp-taxonomy';

const taxonomyBatch = taxonomy.createBatch();

taxonomyBatch**.execute**().then(_r => {resolve
```

I'm using spfx 1.11.0 and is pnp/sp-taxonomy.
Error: Property 'execute' does not exist on type 'IObjectPathBatch'. What is the recommended or how I can fix it.
I'm trying to get the term set hierarchy but I'm not succeeding. All tips are really appreciated.

**Comment by juliemturner** [comment]
To clarify, you're using v1.x? of the library correct.

**Comment by patrick-rodgers** [comment]
Are you using all v1 libraries or trying to mix v1 and v2 - which won't work. [We do have taxonomy support in v2 now](https://pnp.github.io/pnpjs/sp/taxonomy/), while different from v1 it does use the new apis.

We can't provide much support for v1 due simply to available time.

**Comment by sharepointkonsult** [comment]
Hi!
Thank you for your feedback. The following are all dependencies:
"dependencies": {
    "@microsoft/sp-core-library": "1.11.0",
    "@microsoft/sp-lodash-subset": "1.11.0",
    "@microsoft/sp-office-ui-fabric-core": "1.11.0",
    "@microsoft/sp-property-pane": "1.11.0",
    "@microsoft/sp-webpart-base": "1.11.0",
    "@pnp/common": "^2.0.10",
    "@pnp/logging": "^2.0.10",
    "@pnp/odata": "^2.0.10",
    "@pnp/sp": "^2.0.10",
    "@pnp/sp-clientsvc": "^1.3.11",
    "@pnp/sp-taxonomy": "^1.3.11",
    "office-ui-fabric-react": "6.214.0",
    "react": "16.8.5",
    "react-dom": "16.8.5"
  }
I try to follow step by step the following link:
http://www.ktskumar.com/2019/07/get-child-terms-term-group-sharepoint-taxonomy-using-pnp-js/

**Comment by patrick-rodgers** [comment]
You can't mix v1 and v2 of PnPjs. [We do have taxonomy support in v2](https://pnp.github.io/pnpjs/sp/taxonomy/) via the new API. IF you want to use the v1 taxonomy library you would have to use v1 of the other libraries as well. Can't recommend this as we no longer maintain v1.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Thanks!
