### ISSUE TITLE
Property 'execute' does not exist on type 'IObjectPathBatch' SPFx 1.11

### ISSUE THREAD

**Issue by sharepointkonsult** [pnp/pnpjs#1376]
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Expected or Desired Behavior
Would like to make batch requests using taxonomy.

Observed Behavior
import {taxonomy, ITerm, ITermSet, ITermStore} from '@pnp/sp-taxonomy';
. . .
const taxonomyBatch = taxonomy.createBatch();
. . .
taxonomyBatch**.execute**().then(_r => {resolve

I'm using spfx 1.11.0 and is pnp/sp-taxonomy.
Error: Property 'execute' does not exist on type 'IObjectPathBatch'. What is the recommended or how I can fix it.
I'm trying to get the term set hierarchy but I'm not succeeding. All tips are really appreciated.

**Comment by juliemturner** [comment]
duplicate entry
