### ISSUE TITLE
Assign a site column to content type or list content type?

### ISSUE THREAD

**Issue by mgordic** [pnp/pnpjs#1379]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ latest ]

Please specify what version(s) of SharePoint you are targeting: [ O365  ]

###  Question
I want to create a site column, site content type, and then to assign a Site Column to the Content-type. Seems so this is not supported by Library?

As an alternative, an acceptable solution will be to create a List Column and then to assign it to the existing content type in List (Site Pages).

I was checking following [Article](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-visio/jj245869(v=office.15)?redirectedfrom=MSDN#postsyntax), but that's not working as well (either not supported in O365 or I made wrong request)

**Comment by juliemturner** [comment]
The article you're referencing is for sp.js... this repo is for PnPjs and our docs are here: https://pnp.github.io/pnpjs/

Is it possible you're posting this to the wrong repo... you said "latest" but what actual version are you using?

Also our docs for doing what you're asking for are here: https://pnp.github.io/pnpjs/sp/fields/ and here: https://pnp.github.io/pnpjs/sp/content-types/

**Comment by mgordic** [comment]
Hi Julie,

Thank you for your reply.

I'm using version 2.0

I know about the documentation, I already double checked it.

Since there is nothing in documentation, i wanted to ask here if someone have had similar use case, or if there is a workaround.

That's the reason why I posted link to sp.js api.

**Comment by juliemturner** [comment]
I guess I'm missing something. I posted the links to the documentation which does what you asked for (add a site column, add a content type, and a site column to a content type) so why do you need a workaround?

>Also our docs for doing what you're asking for are here: https://pnp.github.io/pnpjs/sp/fields/ and here: https://pnp.github.io/pnpjs/sp/content-types/

**Comment by mgordic** [comment]
There is only method to Get the field links in content type. But there is no method to set / update field links. And that is what I need.

**Comment by juliemturner** [comment]
So, for sure, I was missing something, and I was missing it because I have done this but didn't remember the details.

There is a way to do this using CSOM endpoints but not a way to do so with REST. PnPJS is strictly avoiding officially implementing any deprecated CSOM code within V2. That said, you could absolutely implement this using an extension method, see [Extensions](https://pnp.github.io/pnpjs/odata/extensions/)

I want to preface this code by saying this is a snippet out of the [Multilingual Pages SPFx Extension](https://github.com/pnp/sp-dev-solutions/tree/master/solutions/MultilingualPages/SPFxExt) that I had written as an interim solution for Multilingual Pages in SharePoint. It's specifically meant to add a new site column to the Site Pages content type and so this code is specific to that, so please make sure you review it and refactor for your specific scenario.

```TypeScript
private async tryUnsealCT(context: ApplicationCustomizerContext): Promise<boolean> {
    try {
      let rUnseal: SPHttpClientResponse = null;
      let sitePageCT: { Id: { StringValue: string }, Name: string, Sealed: boolean } = await sp.web.contentTypes.getById('0x0101009D1CB255DA76424F860D91F20E6C4118').get();
      if (sitePageCT.Sealed) {
        let fixUrl = sp.web.contentTypes.getById('0x0101009D1CB255DA76424F860D91F20E6C4118').toUrl();
        let fixOptions = {
          headers: {
            Method: "PATCH"
          },
          body: JSON.stringify({ Sealed: false })
        };
        rUnseal = await context.spHttpClient.post(`${context.pageContext.site.absoluteUrl}/${fixUrl}`, SPHttpClient.configurations.v1, fixOptions);
        if (!rUnseal.ok) {
          Logger.write(`Could not unseal Site Pages content type - ${this.LOG_SOURCE}`, LogLevel.Error);
          return false;
        }
      }
      return true;
    } catch (err) {
      Logger.write(`${err} - ${this.LOG_SOURCE} (tryUnsealCT)`, LogLevel.Error);
      return false;
    }
  }

 private async createFieldLink(context: ApplicationCustomizerContext, fieldId: string): Promise<boolean> {
    let retVal = false;
    try {
      let unsealCT = await this.tryUnsealCT(context);
      if (unsealCT) {
        let fieldLinkUrl = `${context.pageContext.site.absoluteUrl}/_vti_bin/client.svc/ProcessQuery`;
        let body = `<Request AddExpandoFieldTypeSuffix="true" SchemaVersion="15.0.0.0" LibraryVersion="16.0.0.0" ApplicationName="Multilingual" `
          + `xmlns="http://schemas.microsoft.com/sharepoint/clientquery/2009"><Actions><ObjectPath Id="5" ObjectPathId="4" />`
          + `<Query Id="56" ObjectPathId="4"><Query SelectAllProperties="false"><Properties>`
          + `<Property Name="Required" ScalarProperty="true" /><Property Name="Hidden" ScalarProperty="true" />`
          + `</Properties></Query></Query>`
          + `<SetProperty Id="58" ObjectPathId="2" Name="Required"><Parameter Type="Boolean">false</Parameter></SetProperty>`
          + `<SetProperty Id="59" ObjectPathId="2" Name="Hidden"><Parameter Type="Boolean">true</Parameter></SetProperty>`
          + `<Method Name="Update" Id="7" ObjectPathId="1"><Parameters><Parameter Type="Boolean">true</Parameter></Parameters></Method></Actions>`
          + `<ObjectPaths><Identity Id="2" Name="d6667b9e-50fb-0000-2693-032ae7a0df25|740c6a0b-85e2-48a0-a494-e0f1759d4aa7:site:${context.pageContext.site.id}:web:${context.pageContext.web.id}:field:${fieldId}" />`
          + `<Method Id="4" ParentId="3" Name="Add"><Parameters><Parameter TypeId="{63fb2c92-8f65-4bbb-a658-b6cd294403f4}"><Property Name="Field" ObjectPathId="2" /></Parameter></Parameters></Method>`
          + `<Identity Id="1" Name="d6667b9e-80f4-0000-2693-05528ff416bf|740c6a0b-85e2-48a0-a494-e0f1759d4aa7:site:${context.pageContext.site.id}:web:${context.pageContext.web.id}:contenttype:0x0101009D1CB255DA76424F860D91F20E6C4118" />`
          + `<Property Id="3" ParentId="1" Name="FieldLinks" /></ObjectPaths></Request>`;

        let fieldOptions = {
          headers: {},
          body: body
        };
        let rFieldLink = await context.spHttpClient.post(fieldLinkUrl, SPHttpClient.configurations.v1, fieldOptions);
        if (rFieldLink.ok) {
          let responseJson = await rFieldLink.json();
          if (!responseJson[0].ErrorInfo) {
            retVal = true;
          }
        }
      }
    } catch (err) {
      Logger.write(`${err} - ${this.LOG_SOURCE} (createFieldLink)`, LogLevel.Error);
    }
    return retVal;
  }
```

**Comment by mgordic** [comment]
Hi @juliemturner ,

Thank you! I will give it a try.
