### ISSUE TITLE
Inserting parent-child pair in one batch

### ISSUE THREAD

**Issue by nbelyh** [pnp/pnpjs#1381]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.x  ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online   ]

### Question

I have two lists in SharePoint, say, Parent and Child. The child list items have "ParentID" (lookup)
I would like to insert one parent record and multiple child records in one batch.

so the batch looks like:
```
{
- add "parent" item (to the "parent"  list)
- add "child" item (to the child list, this "child" should refer to to the to-be-created "parent")
}
```
Important words here: **in one batch**. That is, in a single round-trip to the server. Is it possible (supported)? The difficulty is, since I don't know the ID of the parent at the time when I issue the request, what value do I put in the lookup fields for the child items?

**Comment by PathToSharePoint** [comment]
Assuming parent and child lists are in the same site, you can use the expand operator to retrieve the parent's details related to each child. More details here:
https://pnp.github.io/pnpjs/sp/items/

**Comment by PathToSharePoint** [comment]
I don't think this is supported. Even SharePoint doesn't know the id until the item (parent in your case) is actually created.

What is the issue with doing it in two steps?

**Comment by nbelyh** [comment]
I think there must be misunderstanding, or am I missing something? There is
no parent item (yet), because it's being inserted by this exactly query? :)

**Comment by nbelyh** [comment]
@PathToSharePoint Thank you for swift response. The batches work like sort of a transaction and more efficient. In principle there is no issue, I just wanted to clarify if it's a supported scenario for batches or not.

**Comment by PathToSharePoint** [comment]
I believe that's what I was saying too. There is no parent item, even less a pointer to it.

And I think that's exactly why some purists despise SharePoint lists (or now Microsoft Lists) used as a database. You don't get that transaction experience out of the box.

**Comment by patrick-rodgers** [comment]
I think the only way to really do this would be to create the parent and then set the right values in the children and add them all as a batch. Batches are executed in sequence so it is possible to say create a list and then add a field to that new list where you know the url (he says without trying it) - but I can't think of a way to add list items because the connect is by id.

**Comment by nbelyh** [comment]
Thank you guys for the clarification. I just thought maybe there could be some sort of "references" or something, like "markers" you can find in some frameworks to do this sort of things. Closing the issue, as it's clear now that this is not possible 😃
