### ISSUE TITLE
Access multi-geo tenants using Pnp JS

### ISSUE THREAD

**Issue by erwinkehrt** [pnp/pnpjs#1382]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0.10      ]

Please specify what version(s) of SharePoint you are targeting: [    Online     ]

### Question

We have enabled multi-geo in our tenant which means we have the main tenant along with its multi-geo equivalents. In practice this ends up looking as https://tenant_A.sharepoint.com and https://tenant_A_eur.sharepoint.com. We have an SPFx web part that grabs data from a list on a site on tenant_A using PnP JS. This web part is deployed to the app catalog on tenant_A. It is used on multiple different sites on tenant_A. This is how we use PnP JS to grab data from the specific site we want.

```
const web = Web(https://tenant_A.sharepoint.com/sites/siteName);

        return await web.lists.getByTitle("ListName").items.select("Col1", "Col2").filter("Title eq 'something'").get()
            .then(data => {
                return data;
            })
            .catch(err => {
                return null;
            });
```

We create a new Web since the call might not be made from the specified site itself. This works well and as expected on tenant_A.

Where it breaks is when we are on tenant_A_eur (which again is a multi-geo offshoot of tenant_A). Tenant_A_eur has its own app catalog and its own sites. When the web part runs on a site on tenant_A_eur and it tries to make the call to the specified site on tenant_A, the call fails. The error is 403 Forbidden. PnP JS does not seem to pass the cookie with the auth token that Sharepoint expects. 

I have tried adding the following code to the "web" object but then we get all sorts of CORS issues.

```
return await web.configure({
                mode: 'cors',
                credentials: 'include',
                headers: {
                    //"Access-Control-Request-Headers": "User-Agent,Content-Type,Authorization,X-RequestDigest,X-ClientService-ClientTag",
                    //"Access-Control-Allow-Credentials": "true",
                    "Access-Control-Allow-Origin": "https://tenant_A_eur.sharepoint.com",
                }
            }).lists.getByTitle("ListName")......
```

Does anyone have an example of something like this working? Is it supposed to work OOTB? Is PnP JS not the correct tool to use in this scenario? I have seen [this](https://pnp.github.io/pnpjs/sp-addinhelpers/) which I'm also not sure if it's supposed to be the way to do this. The example in the documentation isn't necessarily for a multi-geo scenario.

I also read [this issue](https://github.com/pnp/pnpjs/issues/502) from 2019 which seems to end on a note that something like this isn't possible, but I am thinking this was trying to actually access a different domain altogether. Any help would be greatly appreciated. Thank you!

**Comment by erwinkehrt** [comment]
@koltyakov tagging in case you have any ideas, I saw you had good input on issue #502

**Comment by juliemturner** [comment]
I believe this is because PnPJS creates a global base for the tenant using the context of the page it initializes from. We currently do not support cross "tenant" calls like this* but are investigating it. The original request (#589) was referenced for Nodejs but I think this is effectively the same request. Will verify with the rest of the team.

*I understand that it's the same tenant but effectively it behaves as if it isn't.

**Comment by erwinkehrt** [comment]
Thanks @juliemturner! I will leave this open for now in case there are any more updates.

**Comment by patrick-rodgers** [comment]
Have found the time to add the ability to create isolated library instances as discussed in this issue. These changes are not yet merged, but a beta is available `npm install @pnp/sp@beta` for testing. Ask that you please give it a try and let us know what you think of our first pass at enabling this functionality, as well of course of any issues you encounter.

The initial [docs are available in the PR](https://github.com/pnp/pnpjs/pull/1403/files#diff-0139b2cfeda6043e5795e252c8f916b2) and outline how to use the new capabilities.

Very interested in any feedback you have. This is a large change so we will be doing additional testing and may update any of the public methods in the beta as we work with it.
