### ISSUE TITLE
Updated web properties are not saved.

### ISSUE THREAD

**Issue by mzbrandl** [pnp/pnpjs#1385]
I am working on a SPFx extension in which I want to edit the name and description of the site on which it is deployed. The extension runs on a modern team site on a development tenant. I am using pnpjs to update the web, but the changes are not persistent.

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [2.0.10]
Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
Updated web properties stay the same over multiple page reloads.

### Observed Behavior
After updating Title and Description of the web, the new values are returned when getting the web information via pnpjs. On the SharePoint site are still the old values in site name and site information panel.
After reloading the page I still get the new values via pnpjs and the site name is changed to the new value. However when hovering over the site name it shows the old values and the site information panel also contains the old values.
![image](https://user-images.githubusercontent.com/32365313/93899079-3cc53b80-fcf4-11ea-964a-0b4ef7924b7d.png)
After reloading the page a second time there are only the old values to be found via pnpjs, user interface and site information panel.

### Steps to Reproduce
I used the following code the update and get the web properties:
```ts
const props = {
    Title: 'New Name',
    Description: 'New Description'
};

await sp.web.update(props);
 
const res = await sp.web
  .select('Title', 'Description')
  .get();

console.log(res);
```
I got the same results when running this in a SPFx extension as well as in the PnPjs console of the Chrome SharePoint editor.

I hope someone can help me to fix this problem, Thanks!

**Comment by patrick-rodgers** [comment]
Can you share more of your code? I suspect you are updating a different web. For example[ have you ensured to setup the context correctly](https://pnp.github.io/pnpjs/getting-started/#establish-context)?

**Comment by mzbrandl** [comment]
I set the context in the applicationCustomizer.ts file in the onInit like this:
```ts
  @override
  public onInit(): Promise<void> {
    Log.info(LOG_SOURCE, `Initialized ${strings.Title}`);

    initializeIcons();

    return super.onInit().then(_ => {
      sp.setup({
        ie11: true,
        spfxContext: this.context
      });

      // Added to handle possible changes on the existence of placeholders.  
      this.context.placeholderProvider.changedEvent.add(this, this._renderPlaceHolders);

      // Call render method for generating the HTML elements.  
      this._renderPlaceHolders();
    });
  }
```

**Comment by mzbrandl** [comment]
I also tried to run the sp setup directly in the service class, which edits the web, with the same result. And when using the  PnPjs console of the Chrome SharePoint editor the context should be set properly as well right?

**Comment by gautamdsheth** [comment]
That looks like a M365 group site. 
To update that you need to use the Graph endpoints as below:

```Typescript
import { graph } from "@pnp/graph";
import "@pnp/graph/groups";

await graph.groups.getById("7d2b9355-0891-47d3-84c8-bf2cd9c62177").update({ displayName: newName, propertyName: updatedValue});
```

Link - [PnPJS Groups](https://pnp.github.io/pnpjs/graph/groups/)

You also need to add necessary permissions for it and setup PnPJS accordingly as well:

Link - [PnPJS Graph](https://pnp.github.io/pnpjs/graph/)

**Comment by mzbrandl** [comment]
Thanks!
