### ISSUE TITLE
ITermSet::children.skip(NUMBER).get() always fails

### ISSUE THREAD

**Issue by yarick123** [pnp/pnpjs#1387]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.10 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint online ]

### Expected
```ts
import { sp } from '@pnp/sp-commonjs';
const TERMSET_GUID = 'xxxxxxxx-yyyy-zzzz-qqqq-uuuuuuuuuuuu';
...
const terms = await sp.termStore.sets.getById(TERMSET_GUID).children.skip(10).select('id', 'labels').get();
console.log('loaded %d terms', terms.length);
```
should return something like "loaded 200 terms" for my flat termset

### Observed Behavior
the code above produces the error:
```
Error making HttpClient request in queryable [400] Bad Request ::> {"error":{"code":"","message":"The query specified in the URI is not valid. Query option 'Skip' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings."}}
```

### Question

where in PnPjs is it possible to set 'AllowedQueryOptions' property in PnPjs?

### Steps to Reproduce
- create a flat termset with more than 10 terms
- execute the code above

**Comment by patrick-rodgers** [comment]
This is an API issue on the server side and appears that you cannot use skip with "children" collection. Nothing we can do within the library. We are adding the "terms" property to set in 2.0.13 which should get you a flat list of all the terms. Skip does not work here either.

**Comment by patrick-rodgers** [comment]
I have also picked the skip method off the interface using Omit to remove this confusion.
