### ISSUE TITLE
Property 'create' does not exist on type 'ITeams'

### ISSUE THREAD

**Issue by bva999** [pnp/pnpjs#1389]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version 

Please specify what version of the library you are using: [   2.0.10      ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
From documentation we have next example of adding a team: 

```
import { graph } from "@pnp/graph";

const createdGroupTeam = await graph.teams.create('Groupname', 'description', 'OwnerId',{
"memberSettings": {
    "allowCreateUpdateChannels": true
},
"messagingSettings": {
        "allowUserEditMessages": true,
"allowUserDeleteMessages": true
},
"funSettings": {
    "allowGiphy": true,
    "giphyContentRating": "strict"
}});
```

But I get an error : _**"Property 'create' does not exist on type 'ITeams'."**_

**Comment by juliemturner** [comment]
Yes, I can confirm I've seen this too. Based on the graph documentation I'm not sure how this ever worked but have just started looking into it.

**Comment by oyvindam** [comment]
Looks like the code for create is missing in teams in v.2.

In v.1 the code is located in packages/graph/src/teams.ts.
The method wraps group and team creation using createTeam (which **is** available in v.2).

So this should give the same result:

```
import { graph, GroupType } from "@pnp/graph";

 const createdGroup = await graph.groups.add(
      "GroupName",
      "MailNickname",
      GroupType.Office365,
      {
        description: "",
        "owners@odata.bind": [
          `https://graph.microsoft.com/v1.0/users/${ownerId}`,
        ],
      }
    );

const createdTeam = await createdGroup.group.createTeam({
      memberSettings: {
        allowCreateUpdateChannels: true,
      },
      messagingSettings: {
        allowUserEditMessages: true,
        allowUserDeleteMessages: true,
      },
      funSettings: {
        allowGiphy: true,
        giphyContentRating: "strict",
      },
    });
```

**Comment by juliemturner** [comment]
Yes, we're aware the graph endpoints are different and this needs to be reworked but the graph typings are inaccurate and have yet to find the time to make a complete fix.
