### ISSUE TITLE
Best approach to filter managed metadata column

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/pnpjs#139]
Is it possible to filter managed metadata column using pnp filter ?

**Comment by patrick-rodgers** [comment]
Hi @harshdamaniahd 

You are spamming old threads as well as starting this one. The best way to get a question answered is to ask it once as clearly as possible and be patient. So, what exactly would you like to accomplish? I see in some of the other threads you mention id? Can you provide details on your scenario?

**Comment by harshdamaniahd** [comment]
I have a taxonomyfield called  "Organization".

This field i have used in one library , now i am trying to filter data in library based on Organization ..but i dont think it is possible using pnp js

 web.lists.getByTitle(libraryName).items.
        top(topQuery).
        orderBy("Modified", false).
        filter("Title ne 'Home'").
        select("Title", "FileRef", "GUID", "Description",
          "Organization", "Contact/Title", "Modified")
        .expand("Contact").usingCaching({
          key: key.workSpaceNews,
          expiration: Util.dateAdd(new Date(), typeofexpiration, expiration.minutes),
          storeName: "session"
        }).get();

Hence i tried using caml , but it returns result as empty

var query = {
      "ViewXml": '<View> <ViewFields>'+
      '<FieldRef Name="Name" />'+
    '</ViewFields><RowLimit>3</RowLimit><Query><Where><In>' +
        '<FieldRef LookupId="TRUE" Name="Organization" />' +
        '<Values>'+
        '<Value Type="Integer">' + termid+
        '</Value>'+
        '<Value Type="Integer">' + termid  +
        '</Value>'+
        '</Values></In></Where></Query></View>'
    };
    await web.lists.getByTitle(newsWorkspace.libraryName).getItemsByCAMLQuery(query).then((result)=>{
      debugger;
      console.log(result);
    }).catch((ex)=>{
      debugger;
    })

**Comment by harshdamaniahd** [comment]
@patrick-rodgers , I tried this.

Requirement : Filter a library based on three taxonomy columns
Here in the below code i am using TaxCatchAll to filter and I am able to filter by business_x0020_unit column (Taxonomy Field).But is this right approach ...Is there any other way...
What if i want to filter by Business_x0020_Unit and Geo_x0020_location ..how will it work ?
```


return await web.lists.getByTitle(newsWorkspace.libraryName).items.
        top(topQuery).
        orderBy("Modified", false).
        filter("Title ne 'Home' and (TaxCatchAll/IdForTerm eq \'"
          + result.termId + "\'  or TaxCatchAll/IdForTerm eq \'" + guid + "\')").
        select("Title", "TaxCatchAll/IdForTerm", "TaxCatchAll/Term", "FileRef", "GUID", "Description",
          "Business_x0020_Unit", "Geo_x0020_Location", "Competence_x0020_Area", "Contact/Title", "Modified")
        .expand("TaxCatchAll/IdForTerm,TaxCatchAll/Term,Contact")
        .usingCaching({
          key: key.workSpaceNews,
          expiration: Util.dateAdd(new Date(), typeofexpiration, expiration.minutes),
          storeName: "session"
        }).get();
```
Also for business_x0020_unit , the label value is different ?
![image](https://user-images.githubusercontent.com/11780473/41641881-596c2636-7484-11e8-935b-797af5c3fadf.png)

**Comment by patrick-rodgers** [comment]
There isn't another way to filter - you can continue to append filter parameters. Though a better approach depending on the number of items might be to query all the items in the list and create an index on the client side. Alternatively you could use an OOTB list view web part with the filters applied (if they are static) - or provide an interface with tabs or similar allows folks to view certain categories.

It is good you are using caching, that should help your performance.

The label value is the default label value, so that is coming from the data.

**Comment by harshdamaniahd** [comment]
@patrick-rodgers  thank you for the suggesstion , I need to filter on load as my webparts are rendered based on these taxonomy field conditions. Yes  i am using caching as well.
I just  wanted to know that the value of the label in termstore is "HR" , but this is what I get here
![image](https://user-images.githubusercontent.com/11780473/41699915-bc3ff0fc-7543-11e8-84c2-71a31b33ceed.png)
I think sometime ago , i was getting the actual value and now suddenly it gives me number

**Comment by koltyakov** [comment]
I guess it's a well-known REST API/OData issue: when requesting lists items with MMD field with a single term selection option the Label doesn't contain display text.

Alas, nothing can be done within the library to fix it. Luckily, SP REST API is not only the OData but much more and there are other options, like `getItemsByCAMLQuery`, `renderListData`, `renderListDataAsStream`:

![image](https://user-images.githubusercontent.com/7816483/41702457-e1945e98-7538-11e8-8cd4-ef4caa8f9044.png)

![image](https://user-images.githubusercontent.com/7816483/41702482-f4b86f46-7538-11e8-8ab1-6f2dd34524f9.png)

![image](https://user-images.githubusercontent.com/7816483/41702508-0a8eb53c-7539-11e8-8f20-3436c5075cbe.png)
![image](https://user-images.githubusercontent.com/7816483/41702523-14227d40-7539-11e8-9066-2c43a5046689.png)

**Comment by harshdamaniahd** [comment]
I tried this and does not work
![image](https://user-images.githubusercontent.com/11780473/41716708-f88040ae-7574-11e8-9816-b3f130be746d.png)
It returns nothing , but data is present
![image](https://user-images.githubusercontent.com/11780473/41716738-0bbc2fe8-7575-11e8-8ea7-18dbbc64ae49.png)

**Comment by koltyakov** [comment]
@harshdamaniahd,

How about:

```typescript
import { sp } from "@pnp/sp";

(async () => {
    const list = sp.web.lists.getByTitle('MMD_SingleValue_List');
    const taxList = sp.web.lists.getByTitle('TaxonomyHiddenList');

    const termId = '6d29c55e-2c44-4264-a85f-5bf3e397360c';

    const [{ Id: termLookupId }] = await taxList.items.select('Id').filter(`IdForTerm eq '${termId}'`).get();
    const view = 
        '<View><Query>' +
            '<Where><Eq>' +
                '<FieldRef Name="MMD_Single" LookupId="TRUE" />' +
                `<Value Type="Lookup">${termLookupId}</Value>` +
            '</Eq></Where>' +
        '</Query></View>';

    const results = await list.getItemsByCAMLQuery({ ViewXml: view });
    console.log(results);
})()
    .catch(console.log);
```

**Comment by harshdamaniahd** [comment]
@koltyakov ..thanks
This helps

**Comment by koltyakov** [comment]
Cool! Going to close as answered.
