### ISSUE TITLE
Additional steps to allow SP testing on new tenants

### ISSUE THREAD

**Issue by danwatford** [pnp/pnpjs#1391]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    v2     ]

Please specify what version(s) of SharePoint you are targeting: [     SPO    ]

### Expected / Desired Behavior / Question
I ran into some issues setting up testing against a new SPO dev tenant. 
Testing makes use legacy app registration which is disabled by default in new tenants (See https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs).

It might be worth linking to the above MS documentation on page https://pnp.github.io/pnpjs/authentication/sp-app-registration/.

To get testing working on the new tenant I needed to force update the SharePoint PowerShell module with:
Install-Module -Name Microsoft.Online.SharePoint.PowerShell -Force

Then I needed to enable custom app authentication on the tenant:
Connect-SPOService
set-spotenant -DisableCustomAppAuthentication $false

The above steps should allow SP tests to run on new tenants.

**Comment by patrick-rodgers** [comment]
Yep, good note - we haven't updated since this change. We will add the note and also update the docs to MSAL once we add the msal node client. Thanks for the suggestion!

P.S. Great demo today in the SIG call!

**Comment by patrick-rodgers** [comment]
Have made the suggested updates as well as implemented an MSAL node client to help folks with App only auth. You can read more on the [MSAL node client here](https://pnp.github.io/pnpjs/authentication/server-nodejs/#msal).
