### ISSUE TITLE
Method Folder.moveByPath: "Invalid URI: The format of the URI could not be determined." -> odata.id missing

### ISSUE THREAD

**Issue by hohenp** [pnp/pnpjs#1395]
Hello

I am using the method moveByPath to move a folder within a doc library.
I am using version 2.0.8

When I call the method I get the error message ""Invalid URI: The format of the URI could not be determined."
I compared my request, with a request that is done within SPO when I move a folder using the UI. These requests are using absolute URLs. My request the URLs are **relative**. 

I have checked the code of the moveByPath function and the API Request to _api/SP.MoveCopyUtil.MoveFolderByPath() should always use **absolute** paths.

Within debugging I recogniced that the code is expacting an "odata.id" object from the Folder.Select(...) request. This "odata.id" is not within the response, so in line 185 of the file "https://github.com/pnp/pnpjs/blob/version-2/packages/sp/folders/types.ts" you are expecting the "odata.id" to containing the absolute url.

As this object is not present the hosturl is build empty and the request is relative.

I assume that these relative URLs are causing the "Invalid URI" exception...

Thanks for checking and your help
Pascal

moveByPath-Request:
![image](https://user-images.githubusercontent.com/29328026/94927834-1b6a0980-04c3-11eb-92fd-8c4869e777e6.png)

Folder.Select(...) Request within moveByPath Method
![image](https://user-images.githubusercontent.com/29328026/94927911-30df3380-04c3-11eb-881d-807293b5b8fc.png)

**Comment by koltyakov** [comment]
@hohenp,

Not all methods are supported for the mentioned reasons with `odata=nometadata`.
Please try at least `minimalmetadata` mode:

```typescript
sp.setup({
  sp: {
    headers: {
      accept: 'application/json;odata=minimalmetadata'
    }
  }
});

await sp.web.getFolderByServerRelativeUrl('/sites/site/Shared Documents/test')
  .moveByPath('/sites/site/Shared Documents/test1');
```

**Comment by koltyakov** [comment]
Maybe we should change this line:

```typescript
const { ServerRelativeUrl: srcUrl, ["odata.id"]: absoluteUrl } = await this.select("ServerRelativeUrl")();
```

to do not rely on 'odata.id' prop, but:

```typescript
const { ServerRelativeUrl: srcUrl, Url: absoluteUrl } = await this.select("ServerRelativeUrl,Url")();
```

**Comment by hohenp** [comment]
Hi Andrew

thanks a lot for your help. Actually I were not aware that these methods require specific odata settings.
I changed the sp.setup as you suggested and with "odata:minimalmetadata" it works correct as the odata.id property is then set.

But with this setting all the dozens of other requests I am creating in my application behave slightly different or rather the responses looks partly different...

Actually I would be happy if I could continue using odata:verbose. 
Do you see a chance to get the absolute url without the dependency of "odata.id"? Maybe from the context (this.context.pageContext.web.absoluteUrl)?

Thanks
Pascal

**Comment by patrick-rodgers** [comment]
@hohenp - yes we can look at that. One of the big challenges around the three modes is time so we focus on the default (minimal) and look to address issues with the others as they come up. Given infinite resources we could test and code for all three cases but we just don't have the cycles. Always happy to get more help ;)

**Comment by hohenp** [comment]
Hi Patrick, all Right I try to help, but don't complain if my help makes more work that without :)
I have setup my dev machine as described in the contributing documentation and tried to implement another way to get the absolute url. Without the odata information I dont see a chance to get the absolute url without another request to the web.
And I didn't find another beautiful way to get the host url as getting the Url and ServerRelativeUrl of the web and replacing them....

![image](https://user-images.githubusercontent.com/29328026/95092484-fde9a980-0727-11eb-90e6-0d5d93fddb09.png)
