### ISSUE TITLE
Error when setting a proxy

### ISSUE THREAD

**Issue by smalcts** [pnp/pnpjs#1397]
### Category
- [x] Enhancement
- [x] Bug

### Version

Please specify what version of the library you are using: 2.0.10

### Expected / Desired Behavior 
Setting up a proxy url works.

### Steps to Reproduce
I am getting the following exception when using setProxyUrl:
` TypeError: https_proxy_agent_1.HttpsProxyAgent is not a constructor`

Maybe, that's because I have other libraries in my project (e.g. AWS SDK) that are using HttpsProxy.

### Expected
Would that be an option to add something like this to proxy.ts?

> /**
>  * Sets the given as an agent on all requests
>  * 
>  * @param agent The Http/Https agent
>  */
> export function setProxyAgent(agent: any) {
>     proxyAgent = agent;
> }

And then at configureProxyOptions check if proxyAgent is set the same way proxyUrl is checked. In this case, I can put any agent implementation I want as long as node-fetch can use it.

I can also submit a merge request if you think it's a good idea.

**Comment by patrick-rodgers** [comment]
Thanks for the idea. Went ahead and added it for the next version coming out tomorrow (Oct 9 if everything goes to plan). Did a few things:

- updated https-proxy-agent we ref to 5
- added back the docs article on proxy
- added the method you suggest setProxyAgent

I also tested setting a proxy by both the url and agent successfully. I am not sure what might have caused the conflict you hit, but perhaps differing versions. Anyway, hope this helps you out.
