### ISSUE TITLE
CDN Availability

### ISSUE THREAD

**Issue by jacobhummel** [pnp/pnpjs#140]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ v1.1.1 ]

### Expected / Desired Behavior / Question

[sp-pnp-js had a deployment section](https://github.com/SharePoint/PnP-JS-Core/wiki/Deployment#cdn-and-spfx) and provided a CDN for loading the library. I'm using pnpjs in multiple spfx components. Is there a plan to make pnpjs available via a public CDN so it can be shared between SPFx components?

Thanks for the great library! It's made our SPFx code so much better.

**Comment by patrick-rodgers** [comment]
Yes! In fact we just got that setup this week after working on it for months with the cdnjs folks. So all of the pnp js libraries are on cdnjs. Haven't yet had a chance to write a new docs page but it is functionally the same as sp-pnp-js. Here is [pnp-common](https://cdnjs.com/libraries/pnp-common) as an example, the rest follow the same pattern. I'll leave this issue open as a reminder to update the docs.

And thanks for the kind words :)
