### ISSUE TITLE
Spelling mistake in ISearchResult for ViewsLifeTime

### ISSUE THREAD

**Issue by omarelanis** [pnp/pnpjs#1401]
### Category
- [ ] Enhancement
- [ X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    @pnp/sp@2.0.10    ]

Please specify what version(s) of SharePoint you are targeting: [   SP Online      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
When running a search query against PNP Search using following code:

    const searcher = Search(this.props.pageContext.site.absoluteUrl);
    const hostPath = this.props.pageContext.site.absoluteUrl.substring(0,this.props.pageContext.site.absoluteUrl.indexOf(".com/")+4);
    const q = "Path="+hostPath+"/"+this.state.PageUrl;
    **const results = await searcher(q);** -> this is the search query bit but including code above for context

 the returned results include the property "ViewsLifeTime", I should then be able to use "results.PrimarySearchResults[0].ViewsLifeTime" to get the view count of the page from the returned results

### Observed Behavior
 however in the PNP Search library the file "types.d.ts" has the string for the ISearchResult interface defined as "ViewsLifetime" instead of "ViewsLifeTime" so I get the error "Property 'ViewsLifeTime' does not exist on type 'ISearchResult'. Did you mean 'ViewsLifetime'?ts(2551)
" which can be easily fixed by adding a new string to "types.d.ts" i.e -> **ViewsLifeTime?: number;**

![image](https://user-images.githubusercontent.com/35841910/95267557-71c1aa00-082d-11eb-8485-d3446658d355.png)
![image](https://user-images.githubusercontent.com/35841910/95267619-93bb2c80-082d-11eb-97a5-c2230616d874.png)

### Steps to Reproduce
Setup a PNP Search using the standard code here:
https://pnp.github.io/pnpjs/sp/search/

Then access the returned property "ViewsLifetime" in the results object 

### Comments
Just needs the string renaming I think?

I may be doing this wrong so please correct me if there is a better way of handling the returned results!! :)

**Comment by patrick-rodgers** [comment]
Looks like we probably have it wrong in the interface, will have a look. Thanks!
