### ISSUE TITLE
sp.search does not return results - while sp online does?

### ISSUE THREAD

**Issue by rogerlangedal** [pnp/pnpjs#141]
### Category
- [x ] Question

### Version
[1.1.1]

### Expected / Desired Behavior / Question
Executing a query in sharepoint looking for people with birthday in January using the querystring:

Birthday=2000/01/01..2000/01/30

Gets me 3 profile matches

### Observed Behavior
Executing the following gives me 0 matches

sp.search("Birthday=2000/01/01..2000/01/30").then((r: SearchResults) => {

        console.log(r.ElapsedTime);
        console.log(r.RowCount);
        console.log(r.PrimarySearchResults);
    });

**Comment by patrick-rodgers** [comment]
Hi @rogerlangedal - I don't have a great answer for you on this. Default configurations in the search center could differ from what is being sent in the REST request by the library, maybe. Doesn't seem like it would be permissions as I am assuming you ran both as yourself. And I assume you ran them both right around the same time so likely timing isn't an issue. Can you check on the search center settings (and those of the web parts executing the search) and see if you notice anything that is not default?

Want to help but will need your help a bit to do some digging on your end to see if we can repro this elsewhere. Then I can dig in and make any fixes we need. Thanks!

**Comment by patrick-rodgers** [comment]
Going to close this due to no response. If you can provide further details to help us investigate please _reopen_ the issue. Thanks!
