### ISSUE TITLE
renderListDataAsStream not passing in URL parameters

### ISSUE THREAD

**Issue by lworkman** [pnp/pnpjs#1414]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 2.0.10

Please specify what version(s) of SharePoint you are targeting: SharePoint Online

### Expected / Desired Behavior / Question

The `queryParams` argument in `List.renderListDataAsStream` doesn't appear to do anything. I'm passing in a properly created `Map` and none of the query parameters within the map are being applied.

Furthermore, [looking at source code](https://github.com/pnp/pnpjs/blob/1162dbfd5367391f3c35eeec09b8a6cbede87c45/packages/sp/lists/types.ts#L264) I can't actually see the argument being used anywhere. Apologies if I missed it.

### Steps to Reproduce
Basic reproduction:

```
  getListData(): Promise<unknown> {
    const testParams = new Map<string, string>([["test", "PARAM-HERE"]]);

    return sp.web.lists
      .getByTitle("DailySurveyResponses")
      .renderListDataAsStream({}, null, testParams);
  }
```

1. Run above code (with sp already setup through the SharePoint framework).
2. Look at the network request in dev tools. See that there's no query parameters on the request.

**Comment by patrick-rodgers** [comment]
Thanks, we'll have a look. Certainly appears to not be correct. Need to go back and look at the history and see if it was ever correct and got incorrectly updated - or we just never included those params.

**Comment by patrick-rodgers** [comment]
Yep, looks like it was added and then at some point removed. We [added it here](https://github.com/pnp/pnpjs/pull/916/files#diff-a21cf4b922268a7dc8368ef932be8b625b4e3e3b102ab819d4fc91b154f8fc33R383).

**Comment by patrick-rodgers** [comment]
This is fixed and will be in the next release. I don't have a good explanation for how the code was removed obviously a mistake. I also added a test that will catch this in the future and ensure the query params are applied.

**Comment by lworkman** [comment]
Thanks for the quick turn around time!

**Comment by patrick-rodgers** [comment]
We aim to please when we can :)
