### ISSUE TITLE
Getting Error [ERR_REQUIRE_ESM]: Must use import to load ES Module, when importing "@pnp/sp/webs"

### ISSUE THREAD

**Issue by gonadn** [pnp/pnpjs#1415]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Latest PnP version installed
Node: v12.19.0

### Expected / Desired Behavior / Question
Expected behaviour will be that it works as asspected and as shown in pnp node samples.

### Observed Behavior
Getting Error when i try to import "@pnp/sp/webs" and import "@pnp/sp/lists" into my .ts file.
This is a simple node server REST Api solution, you can check the code for this solution on [GitHub]
(https://github.com/gonadn/nodepnptest)

![image](https://user-images.githubusercontent.com/3224441/96996680-92c61280-1530-11eb-951a-27a4ac6b8ee2.png)

**Error Message:**
![image](https://user-images.githubusercontent.com/3224441/96996556-5d212980-1530-11eb-8169-be0713795449.png)

### Steps to Reproduce
Clone the GitHub repo solution and "npm run dev"
![image](https://user-images.githubusercontent.com/3224441/96997055-4c24e800-1531-11eb-9c0b-63a6fec00658.png)

**Comment by patrick-rodgers** [comment]
Have you reviewed [this article on working in nodejs versions that don't handle es modules](https://pnp.github.io/pnpjs/nodejs-support/)?

**Comment by gonadn** [comment]
the error went away after using @pnp/sp-commonjs and @pnp/nodejs-commonjs, but i got another error when i try to get item from a list. 
![image](https://user-images.githubusercontent.com/3224441/97040165-dee37800-156d-11eb-89b8-2191b4b01484.png)

I hae the clientId and secret, and every thing should be correct.

**Comment by gonadn** [comment]
i fixed the error: UnhandledPromiseRejectionWarning: Error: Error making HttpClient request in queryable [401] Unauthorized
i had to add cath like showing in code below:

`sp.web.lists.getByTitle("TestList").items.get()
            .then((items: any) => {
                if (items !== null && items !== undefined) {
                    resolve(JSON.stringify(items));
                } else {
                    reject("Error");
                }  
            })
            .catch((error) => {
                reject(error);
            });`

But know nothing happens, no error thrown. i tried with getting only web infor Title and description, and tems from a list. nothing works.

**Comment by koltyakov** [comment]
@gonadn, 

New tenants by default block AddIn-Only auth for some time now.

If the custom app auth is disabled, it can be enabled with the following command:

```powershell
set-spotenant -DisableCustomAppAuthentication $false
```

**Comment by gonadn** [comment]
@koltyakov  thanks for the response, but when running Powershell command `set-spotenant -DisableCustomAppAuthentication $false` i get an error. 
![image](https://user-images.githubusercontent.com/3224441/97052449-5242b500-1581-11eb-85d9-753bc6532089.png)

And on microsoft documents https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps

I can not find the property:  'DisableCustomAppAuthentication'.

**Comment by koltyakov** [comment]
Installed SPO PowerShell version might require an update.

**Comment by gonadn** [comment]
@koltyakov  thanks alot, finally it worked. something wrong with PS on my machine, but i manged to fix it. Just one more question, will it be any issue when i deploy my app to Microsoft Store, and the app is using PnP libraries, will those who by or download the app have to the same ?

**Comment by koltyakov** [comment]
@gonadn, the auth methods, and corresponding infrastructure depend on a solution. The library doesn't have opinions on which auth to use when in how. For provider-hosted apps, I'd suggest https://pnp.github.io/pnpjs/nodejs/provider-hosted-app/ wiring up. Unfortunately, I have no provider-hosted app to check will it work with disabled custom app authentication.

**Comment by koltyakov** [comment]
Going to close this.
