### ISSUE TITLE
PNPJS page has an image blocking the text

### ISSUE THREAD

**Issue by westleyMS** [pnp/pnpjs#1422]
When navigating to this URL- https://pnp.github.io/pnpjs/
The page is blank. In F12 I find this element blocking everything-
`<img src="https://telemetry.sharepointpnp.com/@pnp/pnpjs/ghpages/pnpjs/" alt="spacer">`
if I delete that, I can see the page fine.

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     NA    ]

Please specify what version(s) of SharePoint you are targeting: [    NA     ]

**Comment by juliemturner** [comment]
Works fine in Chrome, and the new Edge...

**Comment by westleyMS** [comment]
I am using MS Edge-  Version 88.0.673.0 (Official build) dev (64-bit)
Still repros

**Comment by koltyakov** [comment]
Any browser desktop and mobile I tried, no issues with MkDocs I saw.

**Comment by patrick-rodgers** [comment]
Yes, unable to repro this as well. I am on an earlier build of Edge but can't think of how this image tag (which shows a single clear pixel) would be breaking things. It has been present in the docs since they were created and I am not aware of any changes to the css or site that would be in play.

**Comment by westleyMS** [comment]
I just tried again today, and found that the page did render, but I had to scroll down a lot to see it. If I delete that img tag, it pulls the content up. Here is a screen shot, I scrolled a bit so you can see where the page starts-
![image](https://user-images.githubusercontent.com/16966062/97610239-d78af700-19d1-11eb-826c-f0a2379a6087.png)

**Comment by patrick-rodgers** [comment]
Going to close this as we are unable to repro on any browser. Will keep an eye out on the docs to ensure we don't see it in the future. Thanks!

**Comment by westleyMS** [comment]
I am on this build now and it is still happening, just reproed-
Version 88.0.692.0 (Official build) dev (64-bit)

Link again- https://pnp.github.io/pnpjs/

**Comment by koltyakov** [comment]
![Image 2020-11-17 10-25-57](https://user-images.githubusercontent.com/7816483/99358960-5d0e1280-28bf-11eb-988f-7abac3618416.png)

It's really happening in Edge Dev channel but not in the latest Edge Stable channel.
In Edge Dev channel, the telemetry pixel is taking the same fixed height as the window width. In the stable channel Edge, the pixel also can be seen, with scroll straight top it takes hardly seen 2 pixels. Yet, this is the same behavior as in Chrome or even any browser.

![image](https://user-images.githubusercontent.com/7816483/99358390-82e6e780-28be-11eb-9e08-970454255d8a.png)

Maybe we should explicitly force the telemetry image size? Pushed a PR.
