### ISSUE TITLE
PNP Search in list

### ISSUE THREAD

**Issue by Namrata99sah** [pnp/pnpjs#1423]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     v2    ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I'm using pnp search in a custom webpart to find items based on text/search query. Can you help with the below questions?
1. is pnp search security trimmed?
2. is it possible to scope the search with a single library? I tried using the below but it gives error.

import { Search } from "@pnp/sp";

const search = new Search("Your URL");

const results = await search.execute({your query object or string})

**Comment by koltyakov** [comment]
Hi @Namrata99sah, 

1. Yes, the search API is security trimmed.
2. Yes, search API allows it, e.g. by providing `Path` property in KQL:

```typescript
import { sp } from '@pnp/sp/presets/all';

(async () => {

  const rootAbsPath = 'https://contoso.sharepoint.com/sites/site/Shared%20Documents';
  const res = await sp.search(`* Path:"${rootAbsPath}"`);

  console.log(res.PrimarySearchResults);
 
})().catch(console.log);
```

**Comment by patrick-rodgers** [comment]
To add to what @koltyakov says here, there is no special pnp search. We call the REST search service in SharePoint, meaning all the features and security remain in effect.

**Comment by Namrata99sah** [comment]
Hi,

I'm getting below error when trying to map the results into Details List.

Uncaught TypeError: Cannot read property 'length' of undefined
    at Selection.IDeG.Selection.setItems (Selection.js:70)
    at DetailsListBase.DfTE.DetailsListBase.componentWillReceiveProps

Any ideas?

**Comment by koltyakov** [comment]
You're evoking `length` property for the object which is `undefined`, in a custom JS file with name `Selection.js` on a line number 70.

**Comment by koltyakov** [comment]
Going to close this.
