### ISSUE TITLE
method files.addChunked() doesn't work with large libraries

### ISSUE THREAD

**Issue by Supermarcin** [pnp/pnpjs#1424]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.11]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

### Expected / Desired Behavior / Question

Calling method web.getFolderByServerRelativeUrl("<folderRelativeURL>").files.**addChunked**( ... ) results in multiple REST queries. I.e.: 
- POST: <web_url>/_api/web/getFolderByServerRelativeUrl('<folder_relative_path>')/files('<file_name>')
/startupload(uploadId=guid'<GUID>')
- POST: <web_url>/_api/web/getFolderByServerRelativeUrl('<folder_relative_path>')/files('<file_name>')
/continueupload(uploadId=guid'GUID',fileOffset='offset')
- POST: <web_url>/_api/web/getFolderByServerRelativeUrl('<folder_relative_path>')/files('<file_name>')
/finishupload(uploadId=guid'GUID',fileOffset='offset')

When working with large libraries (over 5k items) all calls to these endpoinds fail with "Exceeded List View Treshold error" due to getting file from folder instead of web. 

Replacing usages of `/_api/web/getFolderByServerRelativeUrl('<folder_relative_path>')/files('<file_name>')` with `/_api/web/getFileByServerRelativeUrl('<folder_relative_path>/<file_name>')` might solve the issue.

**Comment by patrick-rodgers** [comment]
Did you try your suggestion? I am not sure it will matter, but curious if it does. Thanks for reporting this, we'll have a look.

**Comment by Supermarcin** [comment]
Yes, that's how I finally implemented my custom AddChunked method.

**Comment by patrick-rodgers** [comment]
Awesome, thanks!

**Comment by patrick-rodgers** [comment]
Updated the method to work with large libraries
