### ISSUE TITLE
Set Default Column Value for a folder in Document library for Metadata column field with a dynamically created term.

### ISSUE THREAD

**Issue by prokach** [pnp/pnpjs#1426]
### Category
- [ ] Bug
- [x] Question
- [x] Documentation gap/issue

### Version
pnpjs version: 2.0.11
SharePoint Online 

### Expected / Desired Behavior / Question
I'm using pnpjs for spfx web-part, which taking a name of a product can create and setup different entities in my modern site collection.
All works as expected except setting folder default value for taxonomy field.
More details: Each time when user types a name of a product and clicks the button 'Create' on web-part, a new term is created based on the name of the product and a new folder is created. I want to set Column Default Value for Metadata column field with the created term for the created folder.
I tried to follow [documentation ](https://pnp.github.io/pnpjs/sp/column-defaults/), so I put such code:

```javascript
sp.web.getFolderByServerRelativePath(_path to a folder_).setDefaultColumnValues([{
                name: "Product"
                value: {
                  termId: _id of a term as guid (without extra '/Guid')_,
                  termName: _name of a term as a string_,
                  wssId: '-1' // I don't know wssId, so I put -1
                }
              }]
);
```
It doesn't throw any exception, but as a result, unfortunately, I get the following error 'Current value invalid'
![Change Default Column Values 2020-](https://user-images.githubusercontent.com/606553/97891390-659b1080-1d37-11eb-9b60-42947b5e4b5f.png)

I've researched different related issues within pnpjs ([Set Default managed metadata column](https://github.com/pnp/pnpjs/issues/506)) and I guess, that a reason is that I need to put a correct wssId value. But I'm not sure and I have no idea where I can take it from via pnpjs. 

Could you please help me to figure out?

**Comment by juliemturner** [comment]
I can probably give you some direction, but I don't have a full solution. 
- Found this article using some GoogleFu: https://pholpar.wordpress.com/2010/02/03/some-words-about-taxonomyfieldvalue-and-its-wssid-property/.  
- By running the following query directly in the browser I see that the hidden list that is discussed above is identified in the field itself as a property:
```
https://contoso.sharepoint.com/sites/PnPJS/_api/web/Lists/GetByTitle('PnPList')/fields/GetByTitle('MyTaxonomyField')
```

![image](https://user-images.githubusercontent.com/7570936/98118692-95eac800-1e79-11eb-900c-ba0d221f7eb4.png)

- By running the following query directly in the browser, I see that once a term is used it shows up in this list and thereby, I can get the ID of it which is what is implied is the WssId from the original article.  

```
https://julieturner.sharepoint.com/sites/PnPJS/_api/web/lists(guid'{VALUEFROMFIELDQUERY}')/items
```

You'll have to play around with it more, and then automate the solution, but that would be the road I would go down.

**Comment by prokach** [comment]
Thank you @juliemturner for your help and the direction for a solution to my problem.

I use a list Name ('TaxonomyHiddenList') in order to take Id value of an appropriate item of the list 
```javascript
await sp.web.lists.getByTitle('TaxonomyHiddenList').items.select("ID").filter(`Title eq '${__name of a term as a string__}'`).getAll();
````
and use it as 'wssId' for creating default value for a folder (main goal):
```javascript
await sp.web.getFolderByServerRelativePath(_path to a folder_).setDefaultColumnValues([{
                name: "Product"
                value: {
                  termId: _id of a term as guid (without extra '/Guid')_,
                  termName: _name of a term as a string_,
                  wssId: wssID.toString()
                }
              }]
);
```

However, it doesn't work. I still experience the same issue, even with a correct 'wssId'.
It seems to me, that it is an issue. 
I'd be glad if someone could approve or reject it.

**Comment by tavikukko** [comment]
Did some tests and got the same result, so confirmed a bug. PR submitted with a fix. Thanks for reporting.
