### ISSUE TITLE
nav.getById is not a function

### ISSUE THREAD

**Issue by dgtheninja** [pnp/pnpjs#1427]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0.11      ]

Please specify what version(s) of SharePoint you are targeting: [    SharePoint Online     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected Behavior
I'm writing a Application Extension and reading the navigation, either quick launch or top bar, for the current site and I need to get the children for a given node, which I think I should be able to get from each node by first calling nav.getById and then calling node.children() on result of getById. 

### Observed Behavior
I can get the first level of nodes but when I try and call nav.getById(node.Id) at runtime I get an error that nav.getById is not a function

### Steps to Reproduce
This is my typescript
```
import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/navigation";
import { INavigationNodes, INavNodeInfo } from '@pnp/sp/navigation';

// In my onInit function for the Application Customiser
if (this.properties.menuLocation === "quicklaunch"){
    nav = await sp.web.navigation.quicklaunch();
} else {
    nav = await sp.web.navigation.topNavigationBar();
}

for (let x = 0; x < nav .length; x++){
    const nodeInfo: INavNodeInfo = nav[x];

    const navNode = nav.getById(nodeInfo.Id);
    const children = await navNode.children();
    // Then my code to process nodes, excluded for brevity
}
```

**Comment by patrick-rodgers** [comment]
This is correct, the `nav` variable in your code contains the result of the execute query. If you want to set it to either the quicklaunch of topNavigationBar I think you want something like:

```TypeScript
if (this.properties.menuLocation === "quicklaunch"){
    nav = await sp.web.navigation.quicklaunch;
} else {
    nav = await sp.web.navigation.topNavigationBar;
}
```

**Comment by dgtheninja** [comment]
thanks for the quick respsonse @patrick-rodgers , that was it!
