### ISSUE TITLE
How to obtain Web.regionalSettings in v2

### ISSUE THREAD

**Issue by politicsruinseverything** [pnp/pnpjs#1428]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.11]

Please specify what version(s) of SharePoint you are targeting: [2019 on-prem and SharePoint Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
In @pnp/sp v1.3.x I was able to obtain the server's timezone settings by calling web.regionalSettings.timeZone.get(). Is this information available somewhere in @pnp/sp v2.x or do I need to make my own REST call to obtain it?

### Observed Behavior
Receiving error message: "regionalSettings does not exist on type IWeb"

### Steps to Reproduce
Try to obtain regionalSettings from an IWeb object in @pnp/sp v2.0.11.

**Comment by juliemturner** [comment]
Have you tried the method outlined in the docs here: https://pnp.github.io/pnpjs/sp/regional-settings/
