### ISSUE TITLE
Cannot access term store data

### ISSUE THREAD

**Issue by sharepointkonsult** [pnp/pnpjs#1443]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint online]

```TS
import { sp } from "@pnp/sp";
import "@pnp/sp/taxonomy";
import { ITermStoreInfo } from "@pnp/sp/taxonomy";

   private async getTermsetWithChildren() {
   const info: ITermInfo = await sp.termStore.groups.getById("a22f3f7d-6065-4d9b-aaae-f72471314e72").sets.getById("be2e4905-6f9f-4304-bee0-f72471314e72").children();

```
----------------------- 

```JSON
"dependencies": {
  "@microsoft/sp-core-library": "~1.4.0",
  "@microsoft/sp-lodash-subset": "~1.4.0",
  "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
  "@microsoft/sp-webpart-base": "~1.4.0",
  "@pnp/common": "^2.0.11",
  "@pnp/logging": "^2.0.11",
  "@pnp/odata": "^2.0.11",
  "@pnp/sp": "^2.0.11"  
},
```
### Observed Behavior

Error: Error: Error making HttpClient request in queryable [404] Not Found ::> <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /temp/_api/v2.1/termstore</pre>
</body>
</html>

---------------------------------  
I fixed the issue by adding the following snippet of code:
protected onInit(): Promise<void> {
  sp.setup({
    spfxContext: this.context
  });
  return super.onInit();
}

BUT  I only get terms, not sub terms. **Is it also possible to get sub terms?**

**Comment by patrick-rodgers** [comment]
That appears to be a component load error and nothing to do with this library?

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
