### ISSUE TITLE
Support for SharePoint 2010

### ISSUE THREAD

**Issue by aslanovsergey** [pnp/pnpjs#1445]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

Can pnp-js library be used against SharePoint 2010?  I have an app in another system were I need to upload files in sharepoint library

**Comment by koltyakov** [comment]
Hi @aslanovsergey,

SharePoint 2010 doesn't have those APIs that PnPjs fluently exposes.
So it can't be used in SP 2010. 

SPHttpClient can be used, similar to Fetch, but you got to manually craft all the requests. Anyways, SP 2010 REST API term wise is completely different.

**Comment by koltyakov** [comment]
There are some oldish but not bad API wrappers for JS to use with SharePoint 2010. SPServices, SharepointPlus, to name a few, which use legacy APIs (SOAP) under the hood and therefore have chances still work with old-old 2010.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Comment by aslanovsergey** [comment]
@koltyakov thank you for info
