### ISSUE TITLE
syncHubSiteTheme:  Is this relavent since I seem to be forced to inherit hub site themes?

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1448]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [x] Documentation gap/issue

## General question on this:  
https://pnp.github.io/pnpjs/sp/hubsites/#synchubsitetheme

I was playing around with hubs the last few days and it seems like Theming is automatically persisted down to all associated sites.  When you go into an associated site setting, it even blocks you from changing the theme which is very annoying for how we are looking at using hubs.

Am I missing something?

# Details from that page

##syncHubSiteTheme
###Allows you to apply theme updates from the parent hub site collection.

import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/hubsites/web";

await sp.web.syncHubSiteTheme();

**Comment by juliemturner** [comment]
You are not, that is a feature of hubs, when you join a hub the theme of the site matches the hub. 

Because I'm curious why do you want to have sites that are joined to the hub have different themes?

**Comment by mikezimm** [comment]
Great question @juliemturner !

We are an automotive supplier.  So our Hubs might include:

- GM
- Ford
- FCA
- Nissan
- SharePoint
- HR-NA
- HR-EU

We use teams like everyone else as well so we are starting to tie both teams and sharepoints to a hub.

But the issue has become this:
We created the Nissan one and they basically use the home page as the communication page for the group.
The manager likes the "Dark" theme and in the case of his page, it looks just fine in part due to the webparts he is using and the content on the page.

Now, we want to create lots of other associated sites and here is the real-world dilema:
1. Dark theme works great for communication sites and VS Code :)
- But I found dark is not good in many cases either due to the webparts not doing themes well
- Lists and Libraries can be harder to use (command buttons, menus, etc)
- One change on a hub can affect the look and feel on hundreds or thousands of pages
- The person setting the hub theme usually does not realize all the downstream implications
- The hub theme can easily be a "personal" choice of the hub owner that everyone else finds harder to use

2. We don't have branding on a department level ( as in MSFT, Xbox = green)
- A Hub could be GM and it would could have 100 associated sites and teams
- Sales, Manufacturing, Quality, Project X, Y, Z
- In this case, these users spend most of their time in the GM Hub and associated sites
- Allowing different themes on Sites just helps them know where they are at (like the site logo but bolder)
- I found this helpful to prevent everything from bleeding together.

3. A similar example, we have a hub for SharePoint.
- It has a mix of public and private sites for various purpopes
- I would like to have my webpart testing site a different theme so it's very easy to know when I'm in my dev environment.
- I know some will say "just look at the url or icon" but having separate themes is important

4. Another use case... say you want to put a site in Read Only mode for any particular reason.
- I would like to change the theme to something like red just so it's painfully obvious :)

5. Maybe you are in the process of migrating things from one site to another and have 2 editable active copies of things.
- Different colors can make it easy for the end user to identify what site they are on if they both look similar

I could go on and on but we should at least have the option.

Hubs are great!  But like I mentioned in number one...
It's almost a deal breaker for that one cases where the communication home page is great in dark but it hurts the 99% because they have to work on something that is harder if not impossible.

Thanks again!

**Comment by juliemturner** [comment]
So, in all of those cases I'm wondering why you're even joining those sites to a hub.  It seems like the only benefit you're even getting is navigation. If that's the case, there are several other ways you could solve it... the most obvious and simplest being for every hub site you now have index sites into a SharePoint list and maybe add some list formatting to make it look pretty, or centralize the list and write a custom web part, or... Anyway, although I see your point unfortunately as a library that just exposes the OOB API's for SharePoint we don't actually have any influence on this functionality.  I might suggest you create a user voice for the issue.

I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue.

Thanks.
