### ISSUE TITLE
Errors trying to use @pnp/sp/hubsites:  IHubSiteData and getSites()

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1449]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0.12      ]
Please specify what version(s) of SharePoint you are targeting: [     SPO    ]

I'm working from the examples on this page:
https://pnp.github.io/pnpjs/sp/hubsites/

### Expected / Desired Behavior / Question
I am looking for a list of sites associated to a  hub and have tried some things based on the examples.

### Observed Behavior
Getting lots of red squiggly lines (see screenshot)...

1. **IHubSiteData** does not seem to be in **@pnp/sp/hubsites**
I tried to substitute with **IHubSiteWebData** but it does not seem to do anything.

2. **getSite()** does not exist on **HubSite**

3. I noticed when I used **getSite()** vs **get()** that I got endless pages of warnings in screenshot

### Steps to Reproduce
Just called my async function during constructor of my react component and it crashed on the await line.

![image](https://user-images.githubusercontent.com/49648086/99600580-b6fbfe80-29cb-11eb-8dbe-e82d2232ce4f.png)

## Example of function I called from my webpart.... crashed on the site: ISite = await line.
```typescript

import { sp } from "@pnp/sp";
import "@pnp/sp/hubsites";

import { ISite, } from  "@pnp/sp/sites";

import { IHubSiteData } from  "@pnp/sp/hubsites";

export async function getMyHub() {
    // invoke the hub sites object
    const site: ISite = await sp.hubSites.getById("3b4f3aaa-6b8f-4129-849b-86dc7d34464c").getSite();
    const siteData = await site();
    console.log(siteData);
    console.log(siteData.Title);

}
```

**Comment by mikezimm** [comment]
I was playing around just trying to get rid of the ts errors... tried to build this version without getSite() and got a different error...
No idea if it helps but thought I'd include.

 [tsc] Property 'features' is missing in type 'IHubSiteInfo'.

![image](https://user-images.githubusercontent.com/49648086/99602520-9d5cb600-29cf-11eb-8545-4a264a569800.png)

**Comment by juliemturner** [comment]
The bug is with the documentation... it's IHubSiteInfo not IHubSiteData.

A way you could know this yourself, as an example, is if you hover over the sp.hubSites() function like this: 

![image](https://user-images.githubusercontent.com/7570936/99696410-a9428980-2a5c-11eb-889d-5d692c0f14b1.png)

As you can see it shows you what the return type is and then it'll even resolve the import for you a lot of times.

**Comment by mikezimm** [comment]
Thanks @juliemturner ,
I ended up rebuilding my solution from scratch, made sure I did as you suggested and I no longer get errors.

I can get all Hubsites, or the current site's hub info.

##N ow my real task is ....

that I need to get a list of associated sites from the hub (including their SiteLogoUrl).

I [found a post on stackexchange]( https://www.techmikael.com/2018/04/working-with-hub-sites-and-search-api.html) from a year ago which talked about it and was able to call it without it erroring out.

However, I don't get any results back in the search.... I do not get errors... just return array of zero length.

By chance do you know how search works?

Thanks again!  If I should post a new issue, please let me know.

```typescript


/**
 * 
 * https://www.techmikael.com/2018/04/working-with-hub-sites-and-search-api.html
 * 
 * There are other options to work with subsites. The CSOM Site object contains a property named IsHubSite
 * you can check on, as does the tenant properties of a site.
 * The site object also has a HubSiteId property which corresponds to the search managed property DepartmentId.
 * 
 */
export async function getAssociatedSites(departmentId: string) {

    var departmentId = departmentId;
    // do a null check of department id
    sp.search(<ISearchQuery>{
        //          Querytext: `contentclass:STS_Site AND NOT siteid:${departmentId} AND departmentid:${departmentId}`,
        Querytext: `contentclass:STS_Site AND NOT siteid:${departmentId} AND departmentid:${departmentId}`,
          SelectProperties: ["Title", "SPSiteUrl", "WebTemplate"],
          RefinementFilters:[`departmentid:string("{*",linguistics=off)`],
          RowLimit: 500,
          TrimDuplicates: false})
          .then((r: SearchResults) => {
    
            //I'm not seeing any results here... array length === 0
            console.log(r.RowCount);
            console.log(r.PrimarySearchResults);
    
            r.PrimarySearchResults.forEach((value) => {
               // do your stuff
          });
    });

}
```

**Comment by mikezimm** [comment]
I'll close this one but if someone has any ideas, please reply back.

In my case I render the webpart without the SiteLogoUrl, then send another call out to get and update the tiles with correct logos.  It could probably be done more efficiently and with quicker response but it works and I'll surive :)
