### ISSUE TITLE
What does it mean to force cache

### ISSUE THREAD

**Issue by AdiuTankT72** [pnp/pnpjs#1455]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.0.0   ]

Please specify what version(s) of SharePoint you are targeting: [ Online ]

I have added configure({cache: "force-cache"}) to my sp.profiles.configure({cache: "force-cache"}).getPropertiesFor(user) but now I wonder what does it really mean. It will cache the response for this specific URL? For how long? How does it work? How does the browser know that this request should be cached? I cannot find an answer :(

**Comment by koltyakov** [comment]
Hey @AdiuTankT72,

The `cache` option you mention is passed to the standard Fetch.

“force-cache” means that the browser will always use a cached response if a matching entry is found in the cache, ignoring the validity of the response.  Thus even if a really old version of the response is found in the cache, it will always be used without validation.  If a matching entry is not found in the cache, the browser will make a normal request, and will update the HTTP cache with the downloaded response. [Details](https://hacks.mozilla.org/2016/03/referrer-and-cache-control-apis-for-fetch/)

**Comment by AdiuTankT72** [comment]
After reading a bit more I can see that this is not a question about PnP ;) Sorry for that. But maybe you will help me to understand - if the response is blocking caching then how it is possible that there will be a cached response? And do we know how long this response will be cached if it shouldn't be cached at all?

**Comment by koltyakov** [comment]
It's a rare case that a request from the API comes cached, at least it caused me issues just a few times when I ended adding adhoc timestamp as a parameter to prevent a cached response.

For the opposite case, when you need caching and control for TTL, etc., [@pnp/odata/caching](https://pnp.github.io/pnpjs/odata/caching/) can be handy.

**Comment by AdiuTankT72** [comment]
Ohh I was trying to use usingCaching in a bad place and I though it is only for lists and items. Thank you! I will check this.

**Comment by koltyakov** [comment]
Going to close it as answered.
