### ISSUE TITLE
How to get a term by name

### ISSUE THREAD

**Issue by ferrarirosso** [pnp/pnpjs#1457]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.9 ]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Question
Is there a way to get a term by name or what is the best approach to fullfill this ?

**Comment by juliemturner** [comment]
In version 2, the ability to access the Taxonomy is still in beta and the only features available are what we have documented here: https://pnp.github.io/pnpjs/sp/taxonomy/

I think you're only option is to get the terms and then loop through them until you find the one with the name you want.
