### ISSUE TITLE
Retrieve terms with a custom sort order or access custom order property

### ISSUE THREAD

**Issue by ferrarirosso** [pnp/pnpjs#1458]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.9]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Question
Is it possible to retrieve all terms from a termset in the specific custom sort order or to access a custom sort order property in order to present the terms in the correct sort order ?

  const currentTermDir: IChildren[] = await sp.termStore.sets.getById("termsetguid").getTermById("termguid").children();
  currentTermDir.forEach(dirTerm => {
    console.log(dirTerm);
    // No property found with custom order
  });

**Comment by patrick-rodgers** [comment]
You can select "customSortOrder" on terms to get the values. That is a painful process of getting all the terms and then at each level getting the custom sort order if it exists and then ordering the terms, repeat recursively. In 2.0.13 we are adding a method to get all the terms of a set as a ordered tree to do all those requests for you.

**Comment by ferrarirosso** [comment]
Nice thanks, I can wait for 2.0.13 😉
