### ISSUE TITLE
Get parent of term, API not found

### ISSUE THREAD

**Issue by ferrarirosso** [pnp/pnpjs#1460]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.9]

Please specify what version(s) of SharePoint you are targeting: [online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Question
I have found some hints about how to get the parent of a term here but it references probably v1 :  https://github.com/pnp/pnpjs/issues/119#issuecomment-394354147

I'm executing the following code and 
const currentTerm: ITerm = await sp.termStore.sets.getById("8d241df8-b470-4718-b143-ff116f23b651").getTermById(currentTermLocId).parent.get();
and I get the following exception 
![Screenshot 2020-12-02 at 17 45 40](https://user-images.githubusercontent.com/5904018/100903893-b59bfd00-34c6-11eb-8b68-8ce9284660b8.png)

What's the correct way to get the parent in V2 ?

**Comment by ferrarirosso** [comment]
Tried with v2.0.12, same result

**Comment by patrick-rodgers** [comment]
I am seeing the same error now (used to work, I know, I tested it) and parent appears in the metadata _api/v2.1/$metadata as a navigation property so unsure what's happened here.

**Comment by patrick-rodgers** [comment]
A small update here, I am trying to track down an answer. The property shows in the API metadata, is listed in the docs, but doesn't work. Unsure where the disconnect is.

**Comment by patrick-rodgers** [comment]
Finally got an update on this and apparently parent is no longer a path property, but you have to use expand. We need to update the library accordingly but today you should be able to:

```TypeScript
const currentTerm: ITerm = await sp.termStore.sets.getById("8d241df8-b470-4718-b143-ff116f23b651").getTermById(currentTermLocId).expand("parent")();
```
