### ISSUE TITLE
.files.addChunked(.. error Error making HttpClient request in queryable [404]  

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#1462]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [ ^2.0.10 then ^2.0.12 ]
Please specify what version(s) of SharePoint you are targeting: [ Online ]

### Expected / Desired Behavior / Question
The code:
` uFile = await projectWebSite.getFolderByServerRelativeUrl("/teams/" + dItem.dpcProjectNumber + "/DPCDocuments/").files.addChunked(
        oneFileData.Name, upFile.getRawFile(), data => {
                 console.log("progress " + data.blockNumber + " Stage " + data.stage);
               }, true);
`
Should upload 39.2 MB file to SPO library with no error.

### Observed Behavior
When using @pnp/sp": "^2.0.10" The file uploaded fine but an error was thrown "Error making HttpClient request in queryable [404]  ::> 
{"odata.error":{"code":"-2130575338, Microsoft.SharePoint.SPException",
"message":{"lang":"en-US",
"value":"The file /teams/2393.019/DPCDocuments/Adventist Health Rural Areas Family Medicine Updated_v4.xlsx does not exist."

After Update to @pnp/sp": "^2.0.12", The file uploaded corrupted but the error was the same. 

I was looking for documentation how to change the "chunkSize" when calling .addChunked but found no explanation except what it does.

Most surprising was the test I made to add the same file without .addChunked but with normal .files.add
The file was uploaded fine with no error messages and not corrupted. I tried with some other big files and again there was no error with files.add .
I am not sure if it is safe for production.

### Steps to Reproduce
Use the above code to upload a big file to SPO

Thank you for your help!

**Comment by tavikukko** [comment]
Tested with this code in SP Editor and it worked fine. Uploaded [50MB.zip](http://xcal1.vodafone.co.uk/) first to library. The script downloads that file, renames it to 50MB2.zip and uploads it back. 

```typescript
/*
  Hit 'ctrl + d' or 'cmd + d' to run the code, view console for results
*/
import { sp } from "@pnp/sp/presets/all";

(async () => {

console.log('downloading')
const blob: Blob = await sp.web.getFileByServerRelativeUrl("/sites/testsite/Shared%20Documents/50MB.zip").getBlob();
console.log('downloaded')

const file = new File([blob], '50MB2.zip');
console.log( file.size );

const uploadedfile = await sp.web.getFolderByServerRelativeUrl("/sites/testsite/Shared%20Documents").files.addChunked( '50MB2.zip', file, data => { console.log("progress " + data.blockNumber + " Stage " + data.stage + " chincksize: " + data.chunkSize); }, true);

console.log(uploadedfile)

})().catch(console.log)
```

**Comment by Ofer-Gal** [comment]
What is "SP Editor"? 
how to change the "chunkSize" when calling .addChunked ?
Maybe the issue is the spaces in the name?
I will test with your version.

**Comment by tavikukko** [comment]
[SP Editor](https://chrome.google.com/webstore/detail/sp-editor/ecblfcmjnbbgaojblcpmjoamegpbodhd) is chrome extension, a SharePoint Developer Power Tool, there you can test your PNPJS snippets. Install it and press F12 and you will find SharePoint tab in the developer tools of Chrome.

**Comment by tavikukko** [comment]
I edited the sample above to add chunkSize 5000000

**Comment by Ofer-Gal** [comment]
Cool I will give it a try
Thank You
I see chunkSize goes at the end Thank you

**Comment by Ofer-Gal** [comment]
I see the difference in the usage and It could be I am doing it wrong. 
My web part is installed on the Root Site Collection and it should upload to any Site Collection the code tells it.
So I change your code and ran it in the  PnPjs Console 
`
import { sp } from "@pnp/sp/presets/all";
import { Web } from "@pnp/sp/webs";
(async () => {

const web = await sp.web.select("Title")()
console.log("Web Title: ", web.Title);
const projectWeb = Web(window.location.origin + "/teams/T000.123");
const webT = await projectWeb.select("Title")()
console.log("projectWeb Web Title: ", projectWeb.name );
console.log(webT.Title);
console.log('downloading');
const blob: Blob = await projectWeb.getFileByServerRelativeUrl("/teams/T000.123/DPCDocuments/50MB Make Belive File.pptx").getBlob();
console.log('downloaded')
const file = new File([blob], '50MB Make Belive File Next.pptx');
console.log( file.size );
const uploadedfile = await projectWeb.getFolderByServerRelativeUrl("/teams/T000.123/DPCDocuments").files.addChunked( '50MB Make Belive File Next.pptx', file, data => { 
console.log("progress " + data.blockNumber + " Stage " + data.stage + " chunkSize: " + data.chunkSize); }, true, 5000000);
console.log(uploadedfile)

})().catch(console.log)

`
The downlod works fine but the upload errors the same as in my code right after the first chunk:

progress 1 Stage starting chunkSize: 5000000
Error: Error making HttpClient request in queryable [404]  ::> {"odata.error":{"code":"-2130575338, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The file /teams/T000.123/DPCDocuments/50MB Make Belive File Next.pptx does not exist."}}}
    at new HttpRequestError (sp.es5.umd.bundle.js:2353)
    at Function.eval (sp.es5.umd.bundle.js:2368)
    at step (sp.es5.umd.bundle.js:1891)
    at Object.eval [as next] (sp.es5.umd.bundle.js:1872)
    at fulfilled (sp.es5.umd.bundle.js:1862)

Thank you for the help and for a great PnPjs 👍

**Comment by tavikukko** [comment]
Actually there is a bug in the code, PR with a fix submitted.

**Comment by Ofer-Gal** [comment]
Thank you for taking care.
Will the fix be available in 2.0.13 ?

**Comment by tavikukko** [comment]
2.0.13 will be released next friday (12/11/2020), and Im quite positive the PR will be merged to it.

**Comment by Ofer-Gal** [comment]
Thank you much. 
Take the weekend off😉  
The fact that I am working doesn't mean you should too.🤣

**Comment by koltyakov** [comment]
It's not a "work" work, so sometimes a weekend is the best time. ;)

**Comment by Ofer-Gal** [comment]
I got 2.0.13 by doing 
` npm i --save @pnp/sp@latest`
And ran with 40mg file
on the second chunk It came back with the error:
`Error making HttpClient request in queryable [404] ` 
SP Editor is still on 2.0.12 so I did not test there.

**Comment by ahyland** [comment]
Hi @Ofer-Gal  did you ever get to the bottom of this I am having the same issue as you when using:

```
export interface IDocumentItem {
    documentFilename: string;
    documentTitle: string;
    actionId: string;
    
    file: File;
}

export interface IAddDocumentResponse { 
	itemid: number;
	filename: string;
	folderserverrelativeurl: string;
	listserverrelativeurl: string;
	serverrelativeurl: string;
	serverredirectedembedurl: string;
    properties: IListItemFormUpdateValue[];
}

public static async uploadEvidence(folderUrl: string, document: IDocumentItem, progress: (data: IFileUploadProgressData, stage?: string) => void):Promise<IAddDocumentResponse> {
const targetActionFolderUrl = `${this._context.pageContext.site.serverRelativeUrl}/DocLib/${folderUrl}`;
const fileContent: Blob = document.file;
const targetFileName = `${document.documentFilename}`;
const addedFile = await sp.web.getFolderByServerRelativeUrl(targetActionFolderUrl).files.addChunked(targetFileName, fileContent, progress, true);

}
```

I call the function from a separate file but I get an error: 

> Error: Error making HttpClient request in queryable [404]  ::> 404 NOT FOUND

Using Chrome Dev Tools I can see that the HTTP Request the code is failing on is as follows:

> Request URL: https://tenant.sharepoint.com/sites/dev/startUpload(uploadId=guid'18f3350d-5876-4049-b63b-90eb564657d9')

When I look in the library where the file is being uploaded, the file itself has been created but it contains no content. 

I am currently using pnp js version 2.1.1, however, I also had this problem with version 2.2.0 I only downgraded as I was able to get it working in the PnP JS Dev Tools which was using 2.1.1 so I thought I would downgrade to test but I still get the same issue.

**Comment by Ofer-Gal** [comment]
My issue was resolved. and later I had permission error that I fixed.
I would suggest you first try with generic upload (:any) until it works then slowly add your specific variables
