### ISSUE TITLE
Labels not retrieved for taxonomy field when retrieving list items

### ISSUE THREAD

**Issue by ferrarirosso** [pnp/pnpjs#1464]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.12]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior
When I read items from a sharepoint list which contains two taxonomy fields : 
- First taxonomy field defined for single value (...Channels in screenshot)
=> I get the value "3" in the field label, but not the label value
- Second taxonomy field defined for multivalue (.... Locations in screenshot )
I get all the terms with the label values

const items: any[] = await sp.web.lists.getByTitle("listname").items.get();
I have tried to use expand on these fields, but it doesn't change anything.

![Screenshot 2020-12-07 at 10 17 17](https://user-images.githubusercontent.com/5904018/101340948-adeea680-3880-11eb-908c-c45419c9cf1a.png)

**Comment by koltyakov** [comment]
It's not the bug of PnPjs, but a well-known REST API issue. The known workaround is using renderListItem[AsStream] methods for the cases with single MMD calues.

**Comment by ferrarirosso** [comment]
Thanks @koltyakov I wasn't aware of this method and the REST API issue
