### ISSUE TITLE
Upgrade error on getByTitle

### ISSUE THREAD

**Issue by khnumtemu** [pnp/pnpjs#1466]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  v1       ]

Please specify what version(s) of SharePoint you are targeting: [    v2     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

Hello All,

I am in the process of upgrading from @pnp version one (1) to the latest version and have run into an issue converting the below code. I have included the error and both the Version 1 Code and the Version 2 code.

**ERROR:**
Cannot read property 'getByTitle' of undefined

**CALL STACK:**
TypeError: Cannot read property 'getByTitle' of undefined
    at t.getSPData (https://publiccdn.sharepointonline.com/skyappscsg.sharepoint.com/sites/apps/ClientSideAssets/1aa4a979-de73-474b-8db9-362eb26215aa/e-comm-custom-hero-web-part_6e88ad3995be14935a9f0ef0a617acf5.js:1:64168)
    at t.render (https://publiccdn.sharepointonline.com/skyappscsg.sharepoint.com/sites/apps/ClientSideAssets/1aa4a979-de73-474b-8db9-362eb26215aa/e-comm-custom-hero-web-part_6e88ad3995be14935a9f0ef0a617acf5.js:1:66499)
    at t._renderWithAccessibleTitle (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:1679753)
    at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js:1:1679307
	
	
Version 1:

import {sp, Item, Web} from "@pnp/sp";

let web = new Web(this.context.pageContext.web.absoluteUrl);  
  
    web.lists.getByTitle("CustomHeroImageList").items  
    .select("Title,CaptionText,HrefURL,DisplayOrder,Attachments,AttachmentFiles")  
    .expand("AttachmentFiles")  
    .filter(`Attachments eq 1 and Published eq 1`)
    .orderBy("DisplayOrder")  
    .get().then((response: Item[]) => { 

});

Version 2:

import {sp} from "@pnp/sp";
import {Web,IWeb} from "@pnp/sp";
	
let web: IWeb = Web(this.context.pageContext.web.absoluteUrl);  
  
    web.lists.getByTitle("CustomHeroImageList").items  
    .select("Title,CaptionText,HrefURL,DisplayOrder,Attachments,AttachmentFiles")  
    .expand("AttachmentFiles")  
    .filter(`Attachments eq 1 and Published eq 1`)
    .orderBy("DisplayOrder")  
    .get().then((result) => { 

});

Any assistance is greatly appreciated.

**Comment by juliemturner** [comment]
Did you call the [sp.setup function](https://pnp.github.io/pnpjs/getting-started/)?
`sp.setup(this.context);`

If you did then you could skip the web call... it would then just be 
`sp.web.lists.getByTitle("CustomHeroImageList").items
.select("Title,CaptionText,HrefURL,DisplayOrder,Attachments,AttachmentFiles")  
.expand("AttachmentFiles")  
.filter('Attachments eq 1 and Published eq 1')
.orderBy("DisplayOrder")  
.get();`

**Comment by khnumtemu** [comment]
Hey @juliemturner, Thank you for getting back to me so quickly. Full disclosure. This is my first SharePoint Framework WebPart. I think I updated correctly but I am still getting the same error. I have attached the Two .ts files associated to this WebPart. Also, below I have included the full code to the .ts file I updated based on your recommendation.

Thanks so much for your assistance.

------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
[carousel ts files.zip](https://github.com/pnp/pnpjs/files/5660373/carousel.ts.files.zip)



import { escape } from '@microsoft/sp-lodash-subset';

import styles from './ECommCustomHeroWebPart.module.scss';
import * as strings from 'ECommCustomHeroWebPartStrings';

import { SPHttpClient, SPHttpClientResponse, SPHttpClientConfiguration } from '@microsoft/sp-http';
import { sp } from "@pnp/sp";
import {Web,IWeb} from "@pnp/sp/webs";
import "@pnp/sp/items";
//import { AttachmentFile, AttachmentFiles, AttachmentFileInfo } from '@pnp/sp/src/attachmentfiles'; 
import { Version } from '@microsoft/sp-core-library';
import { BaseClientSideWebPart } from '@microsoft/sp-webpart-base';
import {
  IPropertyPaneConfiguration,
  PropertyPaneTextField
} from '@microsoft/sp-property-pane';
require('core-js/es6/array');
require('es6-map/implement');
require('core-js/modules/es6.array.find');
import 'jquery';
import TemplateCarousel from './TemplateCarousel';
import { SPComponentLoader } from '@microsoft/sp-loader';
require('bootstrap');

export interface IECommCustomHeroWebPartProps {
  description: string;
}

export default class ECommCustomHeroWebPart extends BaseClientSideWebPart<IECommCustomHeroWebPartProps> {

  //Retrieve all the attachments from all items in a SharePoint List  
  private getSPData(): void {  
    let attachmentfiles: string = "";
    let partOne: string = "";
    let partTwo: string = "";
    let partThree: string = "";
    //let web: IWeb = Web(this.context.pageContext.web.absoluteUrl);
    sp.setup(this.context); 
  
    sp.web.lists.getByTitle("CustomHeroImageList").items
    .select("Title,CaptionText,HrefURL,DisplayOrder,Attachments,AttachmentFiles")  
    .expand("AttachmentFiles")  
    .filter(`Attachments eq 1 and Published eq 1`)
    .orderBy("DisplayOrder")  
    .get().then((result) => { 

      result.forEach((listItem: any) => { 
        listItem.AttachmentFiles.forEach((afile: any) => {
          attachmentfiles += `
          <div class="item ${listItem.DisplayOrder === 1 ? "active" : ""}">
          <a href="${listItem.HrefURL}" target="_blank">
          <img src="https://skyappscsg.sharepoint.com${afile.ServerRelativeUrl}" alt="Breakthru Beverage Group" style="width:100%;"></a>
          <div class="carousel-caption">
             <h3>${listItem.Title == null ? "" : listItem.Title}</h3>
             <p>${listItem.CaptionText == null ? "" : listItem.CaptionText}</p>
          </div>
        </div>`;        
        });  
      });
      
      if(result.length > 0){

        var listItemCount = "";
        for (let i = 0; i < result.length; i++) { 
          
          listItemCount += `<li data-target="#myCarousel" data-slide-to="${i}" class="${i == 0 ? "active" : ""}"></li>`;

          partOne = `
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                `;
                partTwo = `<ol class='carousel-indicators'>
                    ${listItemCount}
                    </ol>`;
                partThree = `

                <div class="carousel-inner">

                               
                      ${attachmentfiles}

                </div>
                
                
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
                </a>
            </div>`; 
        }

      }
      
      this.renderData(partOne + partTwo + partThree);        
    });  
  }
  private renderData(strResponse: string): void {
    const htmlElement = this.domElement.querySelector("#CustomHeroImageLIst");
    htmlElement.innerHTML = strResponse;
  }

  public render(): void {
    let cssBootstrap = "https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css";
    let cssMain = "https://skyappscsg.sharepoint.com/CustomHeroAssets/CustomHero.css";
    SPComponentLoader.loadCss(cssBootstrap);
    SPComponentLoader.loadCss(cssMain);

    this.domElement.innerHTML = TemplateCarousel.templateHtml;
    this.getSPData();
  }

  //protected get dataVersion(): Version {
    //return Version.parse('1.0');
  //}

  protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: [
            {
              groupName: strings.BasicGroupName,
              groupFields: [
                PropertyPaneTextField('description', {
                  label: strings.DescriptionFieldLabel
                })
              ]
            }
          ]
        }
      ]
    };
  }
}

**Comment by juliemturner** [comment]
Ok, I see the error, you don't have complete imports... so I'm going to point you to the [documentation](https://pnp.github.io/pnpjs/sp/items/). 

```typescript
import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
```
Since this is your first webpart I suggest that you spend some time browsing the docs.

That said you may also want to review some getting started videos for SPFx as well if you haven't seen them before.
https://www.youtube.com/playlist?list=PLR9nK3mnD-OV-RPXQ3Lco845qoEy7VJoc

**Comment by khnumtemu** [comment]
I can't thank you enough @juliemturner. That resolved the issues. I will be reviewing that documentation and videos today. Thanks again. I am marking this as close.
