### ISSUE TITLE
User with Read permissions can not get web.webs()

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1467]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version 
"@pnp/sp": "^2.0.12",
SPO

### Expected / Desired Behavior / Question
If the person on the page has Read permissions, they should be able to run this call and get a list of webs for the current site

```typescript
let web = Web('https://currentSiteUrl');
let websResponse = await web.webs();
```

I also tried using the reactPnpjsTester webpart with this command and it threw an error:
sp.web.getSubwebsFilteredForCurrentUser()

### Observed Behavior
I get the error message:
'Access denied.   You do not have permission to perform this action or access this resource.

![image](https://user-images.githubusercontent.com/49648086/101708895-442af400-3a5c-11eb-9b4a-914878e922b3.png)

### Steps to Reproduce
Tested that code with several users on several sites.
I confirmed that the subsites use same permissions as the site that is making the call.

**Comment by PathToSharePoint** [comment]
Apparently this endpoint needs more than just read permissions. I found [more information here](https://sharepoint.stackexchange.com/a/250675/2904).

You could test the endpoint directly in the browser to confirm:
`https://currentSiteUrl/_api/web/webs`

**Comment by patrick-rodgers** [comment]
What is the error you got with "getSubwebsFilteredForCurrentUser"?

**Comment by mikezimm** [comment]
Hi @patrick-rodgers 

> What is the error you got with "getSubwebsFilteredForCurrentUser"?

This is what I tried and the result error message.
In the end, I'm hoping to get a list of subsites along with Title, Description and SiteLogoUrl.
I don't mind getting them filtered as the function seems to indicate... but really need the SiteLogo if possible.

Thanks for any help!

![image](https://user-images.githubusercontent.com/49648086/101836112-cbcf3c00-3b0a-11eb-97d2-52ff84eef4c8.png)

**Comment by mikezimm** [comment]
@patrick-rodgers ,
I found that if I add these parameters, it does work:
sp.web.getSubwebsFilteredForCurrentUser(-1, -1)

However, I'm not able to get the site logos.... any thoughts?

**Comment by patrick-rodgers** [comment]
@mikezimm - the getSubwebsFilteredForCurrentUser method doesn't return the entire web, it returns an SPWebInformation which has these fields available:

```
SPWebInformation(
  web.Created,
  web.Description,
  web.ID,
  web.Language,
  web.LastItemModifiedDate,
  web.Title,
  web.WebTemplateId,
  web.ServerRelativeUrl,
  web.WebTemplate,
  web.Configuration,
  web.LastItemUserModifiedDate
);
```

We will update the code to reflect this properly. You would only be able to select from those fields against this method. You can use the ID to get the actual web and select the site logo. Site has an "[openWebById](https://pnp.github.io/pnpjs/sp/sites/#open-web-by-id)" method you can use.
