### ISSUE TITLE
Batch add users to sitegroup works intermittently

### ISSUE THREAD

**Issue by khanomekhan91** [pnp/pnpjs#1468]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   3.0.10      ]

Please specify what version(s) of SharePoint you are targeting: [  Online    ]

### Expected / Desired Behavior / Question
I want to add multiples users to a Site Group through batch command.

### Observed Behavior
The operation works intermittently, sometimes all the users get added, sometime few of them and sometime none of the users get added to the site group.

```TypeScript
let batch = sp.web.createBatch();
          let userPromise = [];
          userRes.forEach(async user => {
            await sp.web.siteGroups.getByName(groupName).users.inBatch(batch).add(user['LoginName']).then(addUserRes => {
              userPromise.push(addUserRes);
            });
          });
          await batch.execute().then(allResponses => {
            Promise.all(userPromise).then(async () => {
              resolve(true);
            }).catch((error) => {
              console.log(error);
            });
          });           
```

### Steps to Reproduce
NA

**Comment by koltyakov** [comment]
Hi @khanomekhan91, 

Offtopic: `await` should not be used with `inBatch` requests, as in batch requests are resolved after `batch.execute()` is resolved. This can lead to unpredictible code flow locks.

Offtopic: Also, forEach and async/await are not compatible. for/of/in loops should be used for awaits inside a cycle.

Are there any errors? In your sample errors are not handled at all. Please check [this thread](https://github.com/pnp/pnpjs/issues/548#issuecomment-472329724) for details on how to handle errors along with batch requests. `addUserRes` is not a promise, but the response, when `sp.web.siteGroups.getByName(groupName).users.inBatch(batch).add(user['LoginName'])` fails the error goes to its `.catch`.

And the last more thing. There is no such version of PnPjs 3.0.10. The latest version is `2.0.12`.

**Comment by khanomekhan91** [comment]
Hi @koltyakov ,
Sorry I failed to mention the library, I am using sp-pnp-js and its version is 3.0.10.
I tries to restructure my code based on the suggestion and tried error handling based on the thread. 
There are no errors and the behavior is random all users get added sometimes and sometimes few and sometimes none.

The updated code is as given below:
interface Results {
            [key: string]: {
              data: any;
              error?: string;
            }
          }
          const wrapBatchPromise = <T>(promise: Promise<T>, res: Results, key: string): void => {
            res[key] = res[key] || { data: null };
            promise
              .then(data => {
                res[key].data = data;
              })
              .catch(error => {
                res[key].error = error.message;
              });
          };

          (async () => {
            const b = sp.web.createBatch();
            const res: Results = {};
            for (let i = 0; i < userRes.length; i++) {
              wrapBatchPromise(sp.web.siteGroups.getByName(groupName).users.inBatch(b).add(userRes[i]['LoginName']), res, userRes[i]['LoginName']);
            }
            await b.execute().catch(_ => { /**/ });
            const errors = Object.keys(res)
              .filter(k => typeof res[k].error !== 'undefined')
              .map(k => res[k].error);
            if (errors.length > 0) {
              throw Error(`\n- ${errors.join('\n- ')}`);
            }
            return res;
          })()
            .then(() => {
              resolve(true);
            })
            .catch(() => {
              console.warn;
            });

**Comment by koltyakov** [comment]
Thanks @khanomekhan91, 

`sp-pnp-js` was deprecated 2 years ago. Please consider an update in the future.

> There are no errors

How do you know that when not logging the errors? ;)

This would log nothing:
 
![image](https://user-images.githubusercontent.com/7816483/101885006-9548fe00-3baa-11eb-9d35-a8406150d6f6.png)

Should be:

```.catch(console.warn);``` which is an alias for ```.catch((err) => console.warn(err));```

Rather than that have no ideas yet if it could be an API issue. So far more details needed.

**Comment by khanomekhan91** [comment]
@koltyakov I tried putting breakpoint while debugging, it never even hit those lines.

**Comment by juliemturner** [comment]
I'm going to close this as it references a version of the library that was deprecated. I think it'd be in your best interest to move to version 2. These are our [getting started docs](https://pnp.github.io/pnpjs/getting-started/). If you are then having issue please feel free to submit a new issue and reference this one.
