### ISSUE TITLE
sp.utility.sendEmail is not sending to shared inboxes or distribution lists

### ISSUE THREAD

**Issue by chriscasella** [pnp/pnpjs#1471]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 2.0.12   

Please specify what version(s) of SharePoint you are targeting: SharePointOnline

### Expected / Desired Behavior / Question

I am using the sp.utility.sendEmail to send emails within a React.js SPFx webpart. The emails are sent to individual O365 emails as well as distributions lists and shared inboxes. All of the recipients are registered and licensed O365 inboxes, yet none of the distribution lists or shared inboxes are getting the emails. Individual O365 addresses will receive the emails, to confirm I know that the utility is definitely sending emails. I am passing the method an array of strings for the "To" field. Are there any ideas of what could be causing the emails to not be sent to the DL's or shared inboxes?

**Comment by koltyakov** [comment]
It’s a limitation of the API method, it can send email to users’ emails only as far as I know.

**Comment by chriscasella** [comment]
@koltyakov  Thank you for your response! I will find a workaround.
