### ISSUE TITLE
@pnp/sp-taxonomy Object prototype may only be an Object or null: undefined error

### ISSUE THREAD

**Issue by lvasiliou** [pnp/pnpjs#1478]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [
"@pnp/common": "^2.0.12",
    "@pnp/logging": "^2.0.12",
    "@pnp/odata": "^2.0.12",
    "@pnp/sp": "^2.0.12",
    "@pnp/graph": "^2.0.12",
    "@pnp/sp-clientsvc": "^1.3.11",
    "@pnp/sp-taxonomy": "^1.3.11",
]
Please specify what version(s) of SharePoint you are targeting: [  Online        ]

### Expected / Desired Behavior / Question
Web part works with no error messages
### Observed Behavior
web part provides the following error: Object prototype may only be an Object or null: undefined error

please elaborate what the dependencies and their versions are for @pnp/sp-taxonomy
```
public getUserCompanyTerm(company: string): Promise<IPickerTerm> {
        return new Promise<IPickerTerm>(async (resolve, reject) => {
            try {
                
                let store = await this.session.termStores.getByName(Constants.TAX_STORE_NAME).get();
                let termSet = store.getTermSetById(Constants.OPCO_TERMSET_ID);
                let termSetData = await termSet.get();
                let opCoTerm = await termSet.terms.getByName(company).get();

                 if (opCoTerm) {

                     resolve({ name: company, key: opCoTerm.Id, path: opCoTerm.PathOfTerm, termSet: termSetData.Id });
                 }
                resolve(null);
            } catch (error) {
                reject(error);
            }
        });
    }
```

**Comment by juliemturner** [comment]
The first thing I notice just in reviewing your submission is that you're trying to mix versions of the library and that doesn't work.  You either need to be all in v1 or all in v2.  We have some Taxonomy support in v2 now although it's beta and seemingly ever changing it may work for your needs. More documentation on v2 Taxonomy can be found [here](https://pnp.github.io/pnpjs/sp/taxonomy/).

![image](https://user-images.githubusercontent.com/7570936/102095267-53f65f80-3df1-11eb-9085-1ede0c9b2d0f.png)

**Comment by lvasiliou** [comment]
Downgrading @pnp/sp to 1.3.11 broke the rest of the solution. sp-taxonomy v2 might be the answer but its in beta. Ηοw can i obtain beta? I cant see a v2.0 on npm

**Comment by juliemturner** [comment]
So v2 install is different than v1, you may want to review the docs on transitioning [here](https://pnp.github.io/pnpjs/transition-guide/). Long story short the taxonomy endpoints are just available in v2 but are hitting SharePoint APIs that are in beta... We've had to make fixes and updates in every release since they came out, so I'm implying to you that we have no control over those changes and therefore until they say their GA you may find that your requests will break.

**Comment by lvasiliou** [comment]
All i am trying to do is find the termset under a term that matches the given company. Then i want to pass it on as a IPickerTerm to TaxonomyPicker as initial value. However, I dont think its possible to fetch the termset path with the current API.

**Comment by juliemturner** [comment]
Nope.. you're right.
