### ISSUE TITLE
IsSiteAdmin user property shows false when I have read access

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1480]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
"@pnp/sp": "^2.0.12",
SPO

### Expected / Desired Behavior / Question
As a user with read permissions, I should be able to get the list of SiteAdmins on the site.
We are using the script shown in the first clode block of **Steps to Reproduce** in SP2016 which works.
I tried to modify that for my SPFx webpart (second code block of **Steps to Reproduce**) but it does not work.

### Observed Behavior
When I am NOT a site admin and get user information, I see the user exists with all their properties but IsSiteAdmin shows as false.
When I have SCA permissions, the same rest call shows the user IsSiteAdmin = true.

## What seems buggy:
**I would expect that if I can fetch a user object, IsSiteAdmin should show the correct value regardless of my permissions but it does not seem to work that way.**

This is what this user looks like when I am a site admin on the site:
![image](https://user-images.githubusercontent.com/49648086/102102618-06322500-3dfa-11eb-82c1-af99369f11f6.png)

This is what the **SAME USER** looks like when I am a visitor on the site:
![image](https://user-images.githubusercontent.com/49648086/102103023-780a6e80-3dfa-11eb-9524-f18c3eff15ac.png)

## In SharePoint 2016, we run this function and any user can get the list of SiteAdmins.
```typescript
       function GetAdmins() {
           var clientContext = new SP.ClientContext.get_current();

           var web = clientContext.get_web();

           var userInfoList = web.get_siteUserInfoList();
           var camlQuery = new SP.CamlQuery();

           var viewXml = "<View><Query>Where><Eq><FieldRef Name='IsSiteAdmin' /><Value Type='Boolean'>1</Value></Eq></Where></Query></View>";
           camlQuery.set_viewXml(viewXml);

           collListItemAdmins = userInfoList.getItems(camlQuery);  
           clientContext.load(collListItemAdmins, 'Include(Title, IsSiteAdmin)');

           //    context.load(items, 'Include(Deleted,Department,EMail,FirstName,ID,IsActive,IsSiteAdmin,JobTitle,LastName,MobilePhone,Name,Notes,Office,Picture,SipAddress,UserName,WebSite,WorkPhone)');

           clientContext.executeQueryAsync(Function.createDelegate(this, this.onQuerySucceededGetAdmins), Function.createDelegate(this, this.onQueryFailedGetAdmins));
       }
```

## I tried both of these functions in the latest pnpjs without success:
```typescript
    export async function getUsersFromGroup( webURL: string, titleOrId: 'Name' | 'Id' , thisGroup : string ) {

        let thisWebInstance = null;
        let users = [];
        let errMessage = '';
        try {
            thisWebInstance = Web(webURL);
            if ( titleOrId === 'Name' ) {
                try {
                    users = await thisWebInstance.siteGroups.getByName( thisGroup ).users();
                } catch (e) {
                    console.log('You may not have access to view members from this list: ', thisGroup );
                }
 
            } else {
                try {
                    users = await thisWebInstance.siteGroups.getById( thisGroup ).users();
                } catch (e) {
                    console.log('You may not have access to view members from this list: ', thisGroup );
                }
            }
        } catch (e) {
            errMessage = getHelpfullError(e, true, true);
        }
        return { users: users, errMessage: errMessage } ;

    }


  export async function getSiteAdmins( webUrl: string , supressError: boolean ) {
    
    let thisWeb = Web(webUrl);

    let errMessage = null;
    let adminFilter = "IsSiteAdmin eq true";
    //This works in React PnpJS Tester:  sp.web.siteUsers.filter("IsSiteAdmin eq true")
    try {
        const users = thisWeb.siteUsers;
        let returnUsers = await users.filter(adminFilter).get();
        console.log('getSiteAdmins: users', returnUsers );

        return { users: returnUsers, errMessage: errMessage }  ;

    } catch (e) {
        errMessage = getHelpfullError(e, true, true);

        if ( supressError === true && errMessage.indexOf('Save Conflict') === 0 ) {
          //Do nothting
        } else {
          alert( errMessage );
        }

        console.log( 'getSiteAdmins', errMessage );

        return { users: [], errMessage: errMessage }  ;
    }

}
```

**Comment by koltyakov** [comment]
PnPjs "proxies" results from REST API, in other words, this property is bypassed from the API, therefore it's API behavior.

**Comment by mikezimm** [comment]
Thanks for the info @koltyakov ,
Do you think this code from 2016 should work then?
If so, do you have a suggestion on how I should modify to to work in my SPFx project?  

[I found this post which talks about JSOM operations in SPFx](https://www.c-sharpcorner.com/article/sharepoint-jsom-operations-using-spfx-solution/) but it is from 2017 and I started learning SPFx in late 2019.

However, I'm guessing this may not be valid for projects created with later generators so that is why I'm asking.
To date, I have only used pnpjs, never JSOM so it's all new to me :)

Here's the 2016 code we were using:
```typescript
       function GetAdmins() {
           var clientContext = new SP.ClientContext.get_current();

           var web = clientContext.get_web();

           var userInfoList = web.get_siteUserInfoList();
           var camlQuery = new SP.CamlQuery();

           var viewXml = "<View><Query>Where><Eq><FieldRef Name='IsSiteAdmin' /><Value Type='Boolean'>1</Value></Eq></Where></Query></View>";
           camlQuery.set_viewXml(viewXml);

           collListItemAdmins = userInfoList.getItems(camlQuery);  
           clientContext.load(collListItemAdmins, 'Include(Title, IsSiteAdmin)');

           //    context.load(items, 'Include(Deleted,Department,EMail,FirstName,ID,IsActive,IsSiteAdmin,JobTitle,LastName,MobilePhone,Name,Notes,Office,Picture,SipAddress,UserName,WebSite,WorkPhone)');

           clientContext.executeQueryAsync(Function.createDelegate(this, this.onQuerySucceededGetAdmins), Function.createDelegate(this, this.onQueryFailedGetAdmins));
       }
```

**Comment by koltyakov** [comment]
If you're sure that the JSOM/CSOM behaves differently than REST in the UIL scopes, and in a way you need, it's possible to create a custom method in the SPFx solution that [sends CSOM XML package](https://github.com/koltyakov/sp-sig-20180705-demo/blob/master/src/02-clientSvc/helper.ts) and not loading heavy sp.js libraries on a page. I got to take a look in more detail if it's the case that non-admins can't see who are admins API-wise.

**Comment by mikezimm** [comment]
@koltyakov ,
I didn't write the SP2016 code above and can't really find any documentation on our side where it was copied from.  I just know that it works and it seems to be running a function off the context.web equivalent in pnpjs but it's above my level of knowledge.

Any help that can be provided is greatly appreciated.

Thanks again,

**Comment by koltyakov** [comment]
@mikezimm, 

Checked in SPO and SP2016, the hardest part was finding a user with limited permissions. This works in all environment for admin and non-admin and read-only users:

```typescript
sp.web
    .siteUserInfoList
    .items.filter(`IsSiteAdmin eq 1`)
    .get()
    .then(console.log);
```

There is no issue in REST API or PnPjs regarding the question, all works as expected.

**Comment by mikezimm** [comment]
@koltyakov , 
Thank you so much for taking the time and replying... This does work perfectly and although I already figured out the Associated Groups, I did see how easy it is to check the user PermissionKind which I had never done so I may be able to use that as well.

Just for community purpose, I'll try to do a little animated gif tomorrow and post here to show how I'm using this code and a modified React Directory webpart as a component in my own webpart.

Thanks again and I can close after I post the giff.

**Comment by mikezimm** [comment]
@koltyakov , Here's the screenshot and tiny video of how I:
1. modified the [React Directory](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-directory) component layout
2. have it fetching the Associated Groups and also SiteAdmins and "Guests"
3. SiteAdmins are visible to everyone including guests
4. duplicate some properties like **Name** to **loginName** and **EMail**  to **Email** so it marries up with pnpjs user objects as well.

[Short Youtube showing setup/results](https://youtu.be/iAD8LTL4Two )

![image](https://user-images.githubusercontent.com/49648086/102365077-2cd09700-3f85-11eb-9b03-459bee526efd.png)

[My modified code to fetch and marry site admins using read access](https://github.com/mikezimm/pivottiles7/blob/2a185bfb19a08196f6d857de5015185d33457770/src/services/userServices.ts#L243)
```typescript
  export async function getSiteAdmins( webUrl: string , supressError: boolean ) {
    let thisWeb = Web(webUrl);

    let errMessage = null;
    let adminFilter = "IsSiteAdmin eq true";

    try {
 
      const siteAdmins = await thisWeb.siteUserInfoList.items.filter(`IsSiteAdmin eq 1`).get();

      /**
       * This was added because loginName is not retured but is in other functions so it just copies it to make it easier to resuse.
       */
      siteAdmins.map( user => {
        if ( !user.loginName && user.Name ) { user.loginName = user.Name ; }
        if ( !user.Email && user.EMail ) { user.Email = user.EMail ; }
      });

      return { users: siteAdmins, errMessage: errMessage }  ;

    } catch (e) {

      errMessage = getHelpfullError(e, true, true);
      if ( supressError === true && errMessage.indexOf('Save Conflict') === 0 ) {
        //Do nothting
      } else {
        alert( errMessage );
      }
      console.log( 'getSiteAdmins', errMessage );

      return { users: [], errMessage: errMessage }  ;
  }
}
```
