### ISSUE TITLE
Provision List from schemaXML

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/pnpjs#1481]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [latest ]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Question
Is there a pnpjs method to provision a list from an XML template? Basically I am looking for the pnpjs equivalent of pnp powershell Apply-PnPProvisioningTemplate.

I found createFieldAsXml in the documentation, but no method to pass a list schemaXML.

Thank you!

**Comment by koltyakov** [comment]
No, there is no full-blown provisioning with PnPjs, one of the reasons is that many provisioning aspects are not represented in REST API or do not work how they should, therefore many operations require CSOM.

There were tries to create [sp-js-provisioning](https://github.com/pnp/sp-js-provisioning), but this project never went far and was (maybe is) only used by initial maintainers within their scoped use cases.

There were other tries, like [this](https://github.com/kyleschaeffer/engineer).

Site designs, which are covered in REST and PnPjs, can be a closer alternative but with a completely different schema and its limitations: https://pnp.github.io/pnpjs/sp/site-designs/

**Comment by PathToSharePoint** [comment]
Thanks for the info! It seems that for my case creating the list shell then adding columns and settings will be good enough.

For the record I was also looking at a WP sample and [opened this question](https://github.com/pnp/sp-dev-fx-webparts/issues/1653).

Would you have any specifics on what does not work as expected? For my scenario, I'll need to break permission inheritance, add a list validation formula, and give item level permissions to "Create items and edit items that were created by the user".

**Comment by koltyakov** [comment]
Well, the limitations are around content types and field links. Some props are exposed to REST API as read-only and also ignored when passing within XML schemas. Here and there you'd need to fallback to CSOM after hours of experiments. Many list provisioning scenarios would work and covered, but with using only REST many provisioning aspects won't. If a case is simple it definitely can be done without CSOM. 

- [Add list](https://pnp.github.io/pnpjs/sp/lists/#add-list)/[Ensure list](https://pnp.github.io/pnpjs/sp/lists/#ensure-that-a-list-exists-by-title)
- [Add content type](https://pnp.github.io/pnpjs/sp/content-types/#add-a-new-content-type)
- [Create field](https://pnp.github.io/pnpjs/sp/fields/#create-a-field-using-an-xml-schema)
- Field links can't be added via REST, if I'm not wrong
- [Add view](https://pnp.github.io/pnpjs/sp/views/#add-a-view)
- [Permissions](https://pnp.github.io/pnpjs/sp/security/#securable-methods)

However, by diving deeper and adding more features you'd face it simpler to host a provisioning backend (Azure Functions + PnP Provisioning engine) and sending a signal to apply a template.

**Comment by PathToSharePoint** [comment]
Thanks Andrew, I really appreciate the detailed answer and the pointers.

**Comment by PathToSharePoint** [comment]
The replies were extremely helpful, thanks Andrew! I am reopening the thread to confirm a couple points.

1. Is there a setting to prevent re-creating a field? If for example `list.fields.addText("Notes")` runs a second time, it will create a second field with internal name Notes0. I'd like it to not run again. Or to put it another way, is there for fields an equivalent of `lists.ensure`?

2. In the following code, the Buildings list gets created, but myBuildingsList errors out (404). Is it to be expected?
```
    let ensureBuildingsList = await sp.web.lists.ensure("Buildings", " App.", 100);
    let myBuildingsList = await ensureBuildingsList.list.get();
```

**Comment by PathToSharePoint** [comment]
I am going to go ahead and close this question. As field creation is handled by multiple methods (addText, addLookup, etc.), I suspect that there is no single "ensure" method for fields.

For the record I handled this with multiple try/catch. For example:
```
    try {
      await BuildingsFields.getByInternalNameOrTitle("Notes").select("Title").get();
    }
    catch (e) {
      await BuildingsFields.addText("Notes");
    }
```
