### ISSUE TITLE
SharePoint MSAL authority URL requires '/' at the end when using ClientId and Certificate

### ISSUE THREAD

**Issue by pmatthews05** [pnp/pnpjs#1482]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.13]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online]

### Expected / Desired Behavior / Question
Connect to SharePoint Online using Client ID and Certificate using MSAL in a node client.
Following documentation: https://pnp.github.io/pnpjs/authentication/server-nodejs/#call-sharepoint

### Observed Behavior
When following the documents running the below code gives the error:

> "ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: Discovery incomplete."

### Steps to Reproduce
```
import { sp } from "@pnp/sp-commonjs";
import { MsalFetchClient } from "@pnp/nodejs-commonjs";

// read in our private key
const buffer = readFileSync("c:/temp/key.pem");

  sp.setup({
    sp: {
      baseUrl: `https://${tenantName}.sharepoint.com${relativeSiteUrl}`,
      fetchClientFactory: () => {
        return new MsalFetchClient(
          {
            auth: {
              authority: `https://login.microsoftonline.com/${tenantId}`,
              clientCertificate: {
                thumbprint: thumbprint,
                privateKey: buffer.buffer,
              },
              clientId: clientId,
            },
          },
          [`https://${tenantName}.sharepoint.com/.default`]
        ); // you must set the scope for SharePoint access
      },
    },
  });
}

const w = await sp.web();

```

### Fix
The fix appears to be changing the authority URL to include a forward slash at the end '/' 

```
import { sp } from "@pnp/sp-commonjs";
import { MsalFetchClient } from "@pnp/nodejs-commonjs";

// read in our private key
const buffer = readFileSync("c:/temp/key.pem");

  sp.setup({
    sp: {
      baseUrl: `https://${tenantName}.sharepoint.com${relativeSiteUrl}`,
      fetchClientFactory: () => {
        return new MsalFetchClient(
          {
            auth: {
              authority: `https://login.microsoftonline.com/${tenantId}/`, // <-- Don't forget the forward slash!
              clientCertificate: {
                thumbprint: thumbprint,
                privateKey: buffer.buffer,
              },
              clientId: clientId,
            },
          },
          [`https://${tenantName}.sharepoint.com/.default`]
        ); // you must set the scope for SharePoint access
      },
    },
  });
}

const w = await sp.web();

```

Please can you update documentation to reflect this.

This is also the same if you are connecting to Graph with Client ID and Certificate.
The forward slash (with or without) doesn't matter if connecting to the graph with Client Id and Secret.

**Comment by patrick-rodgers** [comment]
This caught me too, seems that they changed their library when we updated from beta 1 to 2.
