### ISSUE TITLE
Could releases be git tagged to trigger Github notifications?

### ISSUE THREAD

**Issue by pdecat** [pnp/pnpjs#1484]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.13 ]

Please specify what version(s) of SharePoint you are targeting: [ tenant.sharepoint.com ]

### Expected / Desired Behavior / Question

It would be awesome if releases of this package were git tagged so that people can watch Github releases to be notified of new versions:

![image](https://user-images.githubusercontent.com/318490/102332611-9b652300-3f8c-11eb-9abc-a68fe40d1ee5.png)

### Observed Behavior

When new releases are made, there's currently no way I'm aware of to get notifications about it, apart manually watching the [CHANGELOG](https://github.com/pnp/pnpjs/blob/version-2/CHANGELOG.md) file.

### Steps to Reproduce

N/A

**Comment by patrick-rodgers** [comment]
We don't currently use github releases, would tagging have any effect? You can also follow @m365pnpjs on twitter where we announce the monthly releases.

**Comment by pdecat** [comment]
Yeah, tags are also triggering notifications nowadays.

**Comment by pdecat** [comment]
e.g 
![image](https://user-images.githubusercontent.com/318490/102366385-e1d07700-3fb8-11eb-8344-677d2f6754e0.png)

**Comment by patrick-rodgers** [comment]
Right on, we'll see about adding tagging to the publish script. Haven't looked at the command in a bit so might add in 2.1.0 which is becoming a big maintenance release for a lot of behind the scenes stuff. If not that one, will try for the next.

**Comment by pdecat** [comment]
Looking at https://github.com/pnp/pnpjs/blob/version-2/tools/publish/publish-win.bat#L32, the `npm version patch` command that is used already git tags the version, so the only thing that seems missing is a `git push --tags`.

See https://git-scm.com/book/en/v2/Git-Basics-Tagging#_sharing_tags

**Comment by pdecat** [comment]
Submitted #1485

**Comment by patrick-rodgers** [comment]
Awesome - thanks! We'll have a look and should have it for the next release. Appreciate the help, cheers.
