### ISSUE TITLE
PnP modern search result webpart issue

### ISSUE THREAD

**Issue by Sarvesh700** [pnp/pnpjs#1487]
We are facing issue in PnP modern search component for search result web part which is not working in internet explorer (working in edge & chrome).
We are getting following error:
Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
Technical Details

[SPLoaderError.loadComponentError]:
Failed to load component "42ad2740-3c60-49cf-971a-c44e33511b93" (SearchResultsWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com

We have tried all the available option such as imported polyfill package but still issue is not resolved.
Can anyone help here?

**Comment by koltyakov** [comment]
Wrong repo

**Comment by Sarvesh700** [comment]
This solution is not working in internet Explorer, Do you have any suggestions to include in the code?
