### ISSUE TITLE
Trouble adding a new view with chosen fields

### ISSUE THREAD

**Issue by Jesper-Damgaard** [pnp/pnpjs#149]
Hello

I am having trouble adding a new list with chosen fields. I have access to the list and update its row limit and it’s caml query.
However I cannot remove all the fields with the removeAll() method. Neither can I remove a single field with the remove(“Title”) method. Additionally, I cannot add new fields with the add(“Title”) method.

pnp.sp.web.lists.getByTitle("Documents").views.add("test", false, {
    RowLimit: 10,
    ViewQuery: "<OrderBy><FieldRef Name='Modified' Ascending='False' /></OrderBy>",
}).then((v: ViewAddResult) => {

    // manipulate the view's fields
    v.view.fields.removeAll().then(_ => {

        Promise.all([
            v.view.fields.add("Title"),
            v.view.fields.add("Modified"),
        ]).then(_ =>{

            console.log("View created");
        });
    });
});

I followed the documentation found on the following page but it doesn’t seem to be working:
https://github.com/pnp/pnpjs/blob/dev/packages/sp/docs/views.md

I am using the latest version of the framework

I hope you have some suggestions

**Comment by patrick-rodgers** [comment]
This appears to be something with the fields in modern views, though I haven't been able to determine exactly what. If you edit a view you can see the fields were added as expected, but the view isn't rendering.

If you change "Title" to "LinkFilename" for instance it works as expected. So for now the solution would be to adjust the fields you are adding to ensure it works.

**Comment by patrick-rodgers** [comment]
Looking at this a little more things seem to work if you add the fields one at a time. So might be worth trying chaining the addition of the fields instead of the Promise.All pattern. Perhaps a conflict is happening in the updates behind the scenes.

**Comment by patrick-rodgers** [comment]
Going to close this as it does not appear to be an issue with the library. If we need to re-investigate please _reopen_ the issue with further details so we can have a look. Thanks!
