### ISSUE TITLE
Likes are not supported in this item

### ISSUE THREAD

**Issue by Bhushan12986** [pnp/pnpjs#1498]
### Category
- [ ] Enhancement
- [x] **Bug**
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [**2.0.13**]

Please specify what version(s) of SharePoint you are targeting: [**SharePoint Online**]

### Expected / Desired Behavior / Question
Current user should able to like or unlike item in document library.

### Observed Behavior
We have created a web part which renders an specific image or a specific video from a document library.
In library's ratting setting is enabled and experience is set to Likes.

![image](https://user-images.githubusercontent.com/16471935/103077817-8a548b80-45f6-11eb-88f2-ac858a0c8069.png)

We are trying to set like and unlike for the current user as per documented in [this](https://pnp.github.io/pnpjs/sp/comments-likes/#like) link, but we are receiving below error.

Error: Error making HttpClient request in queryable [500] Internal Server Error ::> {"odata.error":{"code":"-1, System.NotSupportedException","message":{"lang":"en-US","value":"Likes are not supported in this item."}}}
    at new HttpRequestError (parsers.js:130)
    at Function.<anonymous> (parsers.js:145)
    at step (tslib.es6.js:100)
    at Object.next (tslib.es6.js:81)
    at fulfilled (tslib.es6.js:71)

### Steps to Reproduce
Call any of the code given in [this](https://pnp.github.io/pnpjs/sp/comments-likes/#like) link on click of an icon in SPFx web part.

**Comment by juliemturner** [comment]
Based on what I can tell the "like" API endpoint only works on pages in the Site Pages library.  I'm not sure why, but given the error is internal (500) and I get the message "Likes are not supported in this item." I suspect it's by design.

**Comment by juliemturner** [comment]
Digging a little deeper it appears that there's a Reputation endpoint that can be used to like things other than pages... I'll see if we can implement that on item.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.server.reputationmodel.reputation.setlike?view=sharepoint-server

**Comment by koltyakov** [comment]
As far as I know, legacy reputations API is not exposed to REST. So it can only be bits of CSOM packages.

**Comment by juliemturner** [comment]
Well... sort of it is based on some reverse engineering of the "Number of Likes" column in a test document library I created.  If you click on the heart, it will call this endpoint:

`/_api/Microsoft.Office.Server.ReputationModel.Reputation.SetLike(listID=@a1,itemID=@a2,like=@a3)`

🤷‍♀️

**Comment by koltyakov** [comment]
Yep, did the same and checked what's happening. Just recalling the last time I needed likes in a list I ended up with JSOM. But that endpoint was actually like always there...

![image](https://user-images.githubusercontent.com/7816483/103586280-d1475880-4ef5-11eb-9e61-b86c97ac135d.png)

**Comment by Bhushan12986** [comment]
Thank you team for looking into it.

However, I am able to mange the functionality with help of code given in [this](https://gist.github.com/vgrem/cdaaf82007b7bbb266da377b5d2a2f29) link using PnPJS item update method.

Looking forward to hear from you guys.

**_Thank you!_**

**Comment by juliemturner** [comment]
I wonder if using that code actually does what needs to be done in the background... but if you're happy with it that's great.  I have implemented the fix and it will roll out in the next release 2.1.0.
