### ISSUE TITLE
.files.addChunked in version 2.0.13

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#1499]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.13 ]

Please specify what version(s) of SharePoint you are targeting: [ OnLine ]

### Expected / Desired Behavior / Question
`await projectWeb.getFolderByServerRelativeUrl("/teams/T000.123/DPCDocuments").files.addChunked( '50MB Make Belive File Next.pptx', file, data => { 
console.log("progress " + data.blockNumber + " Stage " + data.stage + " chunkSize: " + data.chunkSize); }, true, 5000000);
`
Should finish without error.

### Observed Behavior
After the last chunk I get 500 error:

`Error: Error making HttpClient request in queryable [500]  ::> {"odata.error":{"code":"-1, Microsoft.FileStore.ErrorExceptionTag","message":{"lang":"en-US","value":"Error=Value=FileUnauthorizedAccess, Tag=0x0121d3da"}}}
    at new HttpRequestError (sp.es5.umd.bundle.js:2354)
    at Function.eval (sp.es5.umd.bundle.js:2369)
    at step (sp.es5.umd.bundle.js:1892)
    at Object.eval [as next] (sp.es5.umd.bundle.js:1873)
    at fulfilled (sp.es5.umd.bundle.js:1863)`

### Steps to Reproduce
Using PnPjs Console V2.0.13 extension
`import { sp } from "@pnp/sp/presets/all";
import { Web } from "@pnp/sp/webs";
(async () => {

const web = await sp.web.select("Title")()
console.log("Web Title: ", web.Title);
const projectWeb = Web(window.location.origin + "/teams/T000.123");
const webT = await projectWeb.select("Title")()
console.log("projectWeb Web Title: ", projectWeb.name );
console.log(webT.Title);
console.log('downloading');
const blob: Blob = await projectWeb.getFileByServerRelativeUrl("/teams/T000.123/DPCDocuments/50MB Make Belive File.pptx").getBlob();
console.log('downloaded')
const file = new File([blob], '50MB Make Belive File Next.pptx');
console.log( file.size );
const uploadedfile = await projectWeb.getFolderByServerRelativeUrl("/teams/T000.123/DPCDocuments").files.addChunked( '50MB Make Belive File Next.pptx', file, data => { 
console.log("progress " + data.blockNumber + " Stage " + data.stage + " chunkSize: " + data.chunkSize); }, true, 5000000);

console.log(uploadedfile)

})().catch(console.log)` 
The results are:
`progress 9 Stage continue chunkSize: 5000000
VM17969:110 progress 10 Stage finishing chunkSize: 5000000
sp.es5.umd.bundle.js:271 POST https://ecgmcdev.sharepoint.com/teams/T000.123/_api/Web/GetFileByServerRelativePath(decodedurl='/teams/T000.123/DPCDocuments/50MB%20Make%20Belive%20File%20Next.pptx')/finishUpload(uploadId=guid'1d0cf52f-5353-41d0-8c46-96ecac2ef04e',fileOffset=45000000) 500
FetchClient.fetch @ sp.es5.umd.bundle.js:271
retry @ sp.es5.umd.bundle.js:3289
eval @ sp.es5.umd.bundle.js:3308
SPHttpClient.fetchRaw @ sp.es5.umd.bundle.js:3307
eval @ sp.es5.umd.bundle.js:3252
step @ sp.es5.umd.bundle.js:1495
eval @ sp.es5.umd.bundle.js:1476
fulfilled @ sp.es5.umd.bundle.js:1466
Promise.then (async)
step @ sp.es5.umd.bundle.js:1468
eval @ sp.es5.umd.bundle.js:1469
__awaiter @ sp.es5.umd.bundle.js:1465
SPHttpClient.fetch @ sp.es5.umd.bundle.js:3219
eval @ sp.es5.umd.bundle.js:3015
PipelineMethods.send @ sp.es5.umd.bundle.js:2998
descriptor.value @ sp.es5.umd.bundle.js:2930
next @ sp.es5.umd.bundle.js:2888
eval @ sp.es5.umd.bundle.js:2930
Promise.then (async)
descriptor.value @ sp.es5.umd.bundle.js:2930
next @ sp.es5.umd.bundle.js:2888
eval @ sp.es5.umd.bundle.js:2930
Promise.then (async)
descriptor.value @ sp.es5.umd.bundle.js:2930
next @ sp.es5.umd.bundle.js:2888
pipe @ sp.es5.umd.bundle.js:2900
eval @ sp.es5.umd.bundle.js:3083
eval @ sp.es5.umd.bundle.js:3453
step @ sp.es5.umd.bundle.js:1495
eval @ sp.es5.umd.bundle.js:1476
fulfilled @ sp.es5.umd.bundle.js:1466
Promise.then (async)
step @ sp.es5.umd.bundle.js:1468
eval @ sp.es5.umd.bundle.js:1469
__awaiter @ sp.es5.umd.bundle.js:1465
eval @ sp.es5.umd.bundle.js:3442
spPost @ sp.es5.umd.bundle.js:3477
eval @ sp.es5.umd.bundle.js:6410
step @ sp.es5.umd.bundle.js:1495
eval @ sp.es5.umd.bundle.js:1476
eval @ sp.es5.umd.bundle.js:1469
__awaiter @ sp.es5.umd.bundle.js:1465
_File.finishUpload @ sp.es5.umd.bundle.js:6406
eval @ sp.es5.umd.bundle.js:3177
step @ sp.es5.umd.bundle.js:1495
eval @ sp.es5.umd.bundle.js:1476
eval @ sp.es5.umd.bundle.js:1469
__awaiter @ sp.es5.umd.bundle.js:1465
descriptor.value @ sp.es5.umd.bundle.js:3174
eval @ sp.es5.umd.bundle.js:6329
step @ sp.es5.umd.bundle.js:1495
eval @ sp.es5.umd.bundle.js:1476
fulfilled @ sp.es5.umd.bundle.js:1466
Promise.then (async)
step @ sp.es5.umd.bundle.js:1468
fulfilled @ sp.es5.umd.bundle.js:1466
Promise.then (async)
step @ sp.es5.umd.bundle.js:1468
fulfilled @ sp.es5.umd.bundle.js:1466
Promise.then (async)
step @ sp.es5.umd.bundle.js:1468
fulfilled @ sp.es5.umd.bundle.js:1466
Promise.then (async)
step @ sp.es5.umd.bundle.js:1468
fulfilled @ sp.es5.umd.bundle.js:1466
Promise.then (async)
step @ sp.es5.umd.bundle.js:1468
fulfilled @ sp.es5.umd.bundle.js:1466
Promise.then (async)
step @ sp.es5.umd.bundle.js:1468
fulfilled @ sp.es5.umd.bundle.js:1466
Promise.then (async)
step @ sp.es5.umd.bundle.js:1468
fulfilled @ sp.es5.umd.bundle.js:1466
Promise.then (async)
step @ sp.es5.umd.bundle.js:1468
fulfilled @ sp.es5.umd.bundle.js:1466
Promise.then (async)
step @ sp.es5.umd.bundle.js:1468
eval @ sp.es5.umd.bundle.js:1469
__awaiter @ sp.es5.umd.bundle.js:1465
_File.setContentChunked @ sp.es5.umd.bundle.js:6299
eval @ sp.es5.umd.bundle.js:5911
step @ sp.es5.umd.bundle.js:1495
eval @ sp.es5.umd.bundle.js:1476
fulfilled @ sp.es5.umd.bundle.js:1466
Promise.then (async)
step @ sp.es5.umd.bundle.js:1468
eval @ sp.es5.umd.bundle.js:1469
__awaiter @ sp.es5.umd.bundle.js:1465
_Files.addChunked @ sp.es5.umd.bundle.js:5903
eval @ sp.es5.umd.bundle.js:3177
step @ sp.es5.umd.bundle.js:1495
eval @ sp.es5.umd.bundle.js:1476
eval @ sp.es5.umd.bundle.js:1469
__awaiter @ sp.es5.umd.bundle.js:1465
descriptor.value @ sp.es5.umd.bundle.js:3174
(anonymous) @ VM17969:109
step @ VM17969:80
(anonymous) @ VM17969:61
fulfilled @ VM17969:52
Promise.then (async)
step @ VM17969:54
fulfilled @ VM17969:52
Promise.then (async)
step @ VM17969:54
fulfilled @ VM17969:52
Promise.then (async)
step @ VM17969:54
(anonymous) @ VM17969:55
__awaiter @ VM17969:51
(anonymous) @ VM17969:88
(anonymous) @ VM17969:118
Promise.then (async)
execme @ VM17969:44
s.onload @ VM17969:34
load (async)
(anonymous) @ VM17969:33
Promise.then (async)
exescript @ VM17969:28
(anonymous) @ VM17969:124
Error: Error making HttpClient request in queryable [500]  ::> {"odata.error":{"code":"-1, Microsoft.FileStore.ErrorExceptionTag","message":{"lang":"en-US","value":"Error=Value=FileUnauthorizedAccess, Tag=0x0121d3da"}}}
    at new HttpRequestError (sp.es5.umd.bundle.js:2354)
    at Function.eval (sp.es5.umd.bundle.js:2369)
    at step (sp.es5.umd.bundle.js:1892)
    at Object.eval [as next] (sp.es5.umd.bundle.js:1873)
    at fulfilled (sp.es5.umd.bundle.js:1863)`

the error "FileUnauthorizedAccess" is always on the last chunk.

Thank you for your future help

**Comment by tavikukko** [comment]
Hi,
you are downloading and uploading to the same location. Could you try to upload to a different library?
The error you are getting is related to permissions, so check also the permissions of the user you are logged in.

**Comment by Ofer-Gal** [comment]
I changed the code to download from different Library and upload Not Chunked first then Chunked.
I am logged on as Global admin so no permission.
The 'Not Chunked' finishes no problem
The 'Chunked' shows 10 stages the last is `progress 10 Stage finishing chunkSize:5000000`
then there is the error:FileUnauthorizedAccess 
but the file is uploaded fine. it should not error.
I tried the other way, Chunked first then  Not Chunked and both were successful. 
In my SPFx code the file comes from a Kendo upload component. So I can't mimic it in the Console.

**Comment by tavikukko** [comment]
The error is **FileUnauthorizedAccess**, either you do not have permission to upload that file or the file exist and you cant override it. Thats all I can think of. If this is not the case, then you need to provide more information of you reprosteps/code/setup, thanks.

**Comment by Ofer-Gal** [comment]
I will give as much details as possible.
The Workbench is at  https://ecgmcdev.sharepoint.com/_layouts/15/workbench.aspx so the webpart context is the root of my tenant.
The library is at  https://ecgmcdev.sharepoint.com/teams/1320.015/DPCDocuments So the code starts with:
`const projectWeb = Web(window.location.origin + "/teams/" + dataItem.dpcProjectNumber);`
To get the context of 'https://ecgmcdev.sharepoint.com/teams/1320.015/DPCDocuments'
Then 
`
try {
    uFile = await projectWebSite.getFolderByServerRelativeUrl("/teams/" + dItem.dpcProjectNumber + "/DPCDocuments/").files.addChunked(
            oneFileData.Name, fileBlob, data => {
              console.log("progress " + data.blockNumber + " Stage " + data.stage);
            }, true, 5000000);
        } catch (error) {
          console.log("Large file add errored " + error);
          throw "Error in PostFile Large file add errored " + error;
}
`
The console shows:
progress 1 Stage starting
net.js:35 POST https://ecgmcdev.sharepoint.com/startUpload(uploadId=guid'88bd471e-b1de-4faf-88ff-964fde01d37b') 404 
Notice, "startUpload" is right after the root of my tenant not the projectWebSite !!
then the error returned from the awaited statment is: "Error making HttpClient request in queryable [404]  ::> 404 NOT FOUND" because it is looking in the root site.
The start does leave a file with no size on the library 
![BadChunkedfile](https://user-images.githubusercontent.com/5054931/103373113-af834700-4a99-11eb-8806-f4a08b854bd7.png)

I assume if I ran the webpart in projectWebSite context, it would work. 

BTW, Using no Chunked works fine with same exact file.
`uFile = await projectWebSite.getFolderByServerRelativeUrl("/teams/" + dItem.dpcProjectNumber + "/DPCDocuments/").files.add(oneFileData.Name,fileBlob , true); `
![goodNoChunkFile](https://user-images.githubusercontent.com/5054931/103373274-19035580-4a9a-11eb-80c7-411d08e658f7.png)
So the issue is not Security. There is a bug when used in another context

**Comment by tavikukko** [comment]
We just fixed this, please verify that you are using the the latest package.

**Comment by Ofer-Gal** [comment]
I have
`
protected onInit(): Promise<void> {
    return new Promise<void>(
      (resolve: () => void, reject: (error?: any) => void): void => {
        sp.setup({
          sp: {
            headers: {
              Accept: "application/json; odata=nometadata"
            }
          },
          spfxContext: this.context
        });        
        graph.setup({ spfxContext: this.context});
        resolve();
      }
    );
  }
`
is this wrong?
