### ISSUE TITLE
Review performance of getListItemEntityTypeFullName

### ISSUE THREAD

**Issue by patrick-rodgers** [pnp/pnpjs#1507]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   latest      ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]

### Expected / Desired Behavior / Question

Reviewing usage data getListItemEntityTypeFullName is one of our most called methods as it is required when updating list items. Let's look at ways to cache the results or reduce calls within the code. We [have guidance on it](https://pnp.github.io/pnpjs/sp/items/#update-multiple-items) but likely most folks won't see it.

**Comment by tavikukko** [comment]
I think you can update listitems without the entityname?

When you set **odata=nometadata**, you don't need to provide "__metadata" property in the body.

Request:
```text
POST https://{site_url}/_api/web/lists/GetByTitle('dalist')/items({item_id})
Content-Type: "application/json; odata=nometadata;"
If-Match: "*"
X-HTTP-Method: "MERGE"
```

Body:
```json
{
    "Title":"My new item title"
}

**Comment by patrick-rodgers** [comment]
Not every environment supports nometadata so we can't force it without breaking someone or having to add a bunch of logic/config to opt in. Unless that first sentence is no longer true?

**Comment by tavikukko** [comment]
yeah, if nometadata is not supported everywhere (onprem I suppose), then this is not going to work.

**Comment by tavikukko** [comment]
Made more tests, works with  **odata=nometadata** and also **odata=minimalmetadata**, but again, don't know how those are supported.

**Comment by patrick-rodgers** [comment]
For v3 we should consider moving to minimal as a default in the library (we need some info to make things work), but its not a change we can put into v2. I think the best we can do is try and optimize it a little to reduce the total number of calls.

**Comment by koltyakov** [comment]
Absolutely agree. v3 is a great candidate to drop support for some legacies as SP2013 and IE, for instance, to move forward faster. In v2 a switch to `minimalmetada` will definitely be a breaking change. As of now, I can see it immediately would break some SP2013-based solutions. Which is a shame but a case, I know many customers stuck with 2013 and never installing OData extensions to the farms to bring minimal metadata support to the API.

**Comment by patrick-rodgers** [comment]
Fix for this turns out to be super simple, I just used our existing caching on the call to store it in local storage. Will be part of next release.

**Comment by koltyakov** [comment]
All genius solutions end up as a simple thing. 👍
