### ISSUE TITLE
Chaining of batch add items

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/pnpjs#1511]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ latest ]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Question
I am looking at the documentation to [batch add items](https://pnp.github.io/pnpjs/v1/sp/docs/items/#add-multiple-items
) to a SharePoint list.

How does the chaining happen? Based on the code sample, `list.items.inBatch(batch).add` is a thenable (promise?), which means that `batch.execute()` will run **without waiting** for the add actions to be completed. What am I missing?

Code excerpt from the documentation:
```
list.getListItemEntityTypeFullName().then(entityTypeFullName => {

    let batch = sp.web.createBatch();

    list.items.inBatch(batch).add({ Title: "Batch 6" }, entityTypeFullName).then(b => {
        console.log(b);
    });

    list.items.inBatch(batch).add({ Title: "Batch 7" }, entityTypeFullName).then(b => {
        console.log(b);
    });

    batch.execute().then(d => console.log("Done"));
});
```

Thank you!

**Comment by koltyakov** [comment]
Hey Christophe!

`inBatch` promise resolves after `batch.execute()` is resolved, and the result is parsed out of a batch response. In other words, if do not provide `batch.execute()` an `inBatch.then` is never resolved.

**Comment by PathToSharePoint** [comment]
@koltyakov thanks for the explanation! I had no idea it was working that way around. Is it explained in the docs? I checked out the [odata batch page](https://pnp.github.io/pnpjs/v1/odata/docs/odata-batch/) before posting but didn't find much there.

**Comment by patrick-rodgers** [comment]
Where the docs are lacking we can always use help in getting them updated if you want to submit a PR to help clarify the spots you see gaps that would be a big help.

**Comment by PathToSharePoint** [comment]
Will do!... as soon as I fully understand the behavior :-) I just wanted to make sure I didn't miss anything. I also plan to update the documentation following #1496.

I was doing a few validation tests yesterday with Promise.all. Unfortunately it seems that Promise.allSettled is not fully supported yet (I am working in SPFx).
