### ISSUE TITLE
IFolder.folders.add() raises Microsoft.SharePoint.SPQueryThrottledException in case of >5K subfolders

### ISSUE THREAD

**Issue by ntodorov** [pnp/pnpjs#1528]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     2.0.13    ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]

### Expected / Desired Behavior / Question
folders.add() should work independed of how many subfolders already exists. 
5K is the SPO API limit on how many items/folders you can load for let say sorting etc, but I do not see why this limit will be imposed in case I want to create a new folder. Is this limitation of the API or it is a potential bug in a `folders.add()` function?
Or is there a better way to create a new folder, without using `IFolder.folders`?

Seems the inner working of `folders.add()` is trying to get a list of the folders collection ...

### Observed Behavior
This is my current code:
```javascript
const createFolder = async (folderName: string) => {
    let result = sp.web.getFolderByServerRelativePath(config.sharePoint.serverRelativeUrl);
    const cleanFolderName = folderName.split('\\').join('/');
    const folders = cleanFolderName.split('/');

    for (let i = 0; i < folders.length; i++) {
      const element = folders[i];
      //here is the problem --> the folders collection will have 68K items and I need to add to it.
      const far = await result.folders.add(element);
      result = far.folder;
    }
    return result;
};
```

The line in the for cycle raises the exception: `const far = await result.folders.add(element);`

The error:
```javascript
Error making HttpClient request in queryable [500] Internal Server Error ::> {"odata.error":{"code":"-2147024860, Microsoft.SharePoint.SPQueryThrottledException","message":{"lang":"en-US","value":"The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator."}}} stack:Error: Error making HttpClient request in queryable [500] Internal Server Error ::> {"odata.error":{"code":"-2147024860, Microsoft.SharePoint.SPQueryThrottledException","message":{"lang":"en-US","value":"The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator."}}}
    at new HttpRequestError (c:\GITROOT\onestop-attachments\node_modules\@pnp\odata-commonjs\parsers.js:133:28)
    at Function.<anonymous> (c:\GITROOT\onestop-attachments\node_modules\@pnp\odata-commonjs\parsers.js:148:47)
    at step (c:\GITROOT\onestop-attachments\node_modules\@pnp\odata-commonjs\node_modules\tslib\tslib.js:140:27)
    at Object.next (c:\GITROOT\onestop-attachments\node_modules\@pnp\odata-commonjs\node_modules\tslib\tslib.js:121:57)
    at fulfilled (c:\GITROOT\onestop-attachments\node_modules\@pnp\odata-commonjs\node_modules\tslib\tslib.js:111:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Steps to Reproduce

You have to have an SPO site that has a folder with >5000 subfolders. In my case, the default "Shared Document" has ~68000.
Use the code above as an example of how to access the folder and try to create a new folder by `.folders.add('some name');`

I saw some explanations for the list limits from @koltyakov in https://github.com/pnp/pnpjs/issues/806

Thanks in advance,
Nik

**Comment by koltyakov** [comment]
`sp.web.getFolderByServerRelativePath('/parent/folder').folders.add('folder name')` ends up with a single call to `/_api/web/getFolderByServerRelativePath(decodedUrl='/parent/folder')/folders/add('folder name')` endpoint.

I was able adding folders in a folder with more than throttling limit folders inside.

I'd suggest rethinking architecture if it's a case that more than 5K folders in a folder is created, this could lead to issues with getting data, if the folder CT contains additional metadata to sort on.

Nothing can be done on a library side if the service returns throttling limitation.

**Comment by koltyakov** [comment]
For the experiment, added 20000+ folders in a folder (no that's not how we're making 10 billion request per month, LOL) on a test tenant. Anyways, didn't face an issue.

**Comment by ntodorov** [comment]
Yesterday, I started using the `sp.web.getFolderByServerRelativePath('/parent/folder')` but with the method `.addSubFolderUsingPath()`, and I still got the same error. The strange behaviour was that the folder was actually created. 
Suppressing the error and trying to get access to the new folder and attempt to create a subfolder inside it let to other strange behaviour - folder found but on adding inside of it, reports that does not exists.

That led to my current solution - it came from observing the modern SPO UI in the browser when creating a folder with it.
They were calling `sp.web.folders.addUsingPath("/the large parent folder/the new child folder");` That worked for me.
The code is not that "elegant" as before (`folders.add()` will not raise an error if the folder exists, it will return the folder object, which awesome!), now I need to first check for the existence of the folder and call create if it does not.

```javascript

const createFolder = async (folderName: string) => {

  let currentPath = config.sharePoint.serverRelativeUrl;
  // let result = sp.web.getFolderByServerRelativePath(currentPath);
  let currentFolder = sp.web.getFolderByServerRelativePath(currentPath);

  if (!folderName) return currentFolder;

  const cleanFolderName = folderName.split('\\').join('/');
  const folderList = cleanFolderName.split('/');

  for (let i = 0; i < folderList.length; i++) {
    const subFolder = folderList[i];

    currentPath = currentPath + '/' + subFolder;
    const exists = await folderExists(currentPath);

    if (exists)
      currentFolder = await sp.web.getFolderByServerRelativePath(currentPath);
    else {
      const newFolder = await sp.web.folders.addUsingPath(currentPath);
      currentFolder = newFolder.folder;
    }

    console.log(currentFolder);
  }

  return currentFolder;
};
```

and the `folderExist()` code if someone needs it. Is there an easier way to check for folder existence?

```javascript
const folderExists = async (folderName: string) => await sp.web
  .getFolderByServerRelativePath(folderName)
  .select('Exists').get()
  .then((d) => {
    console.log(d);
    return d.Exists;
  })
  .catch((err) => {
    console.error(err);
    return false;
  });
```

Thanks for the support @koltyakov !

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
