### ISSUE TITLE
Why not export Views, View and ViewFields in @pnp/sp

### ISSUE THREAD

**Issue by iiunknown** [pnp/pnpjs#153]
Hi guys,

In @pnp/sp package, why not export Views, View and ViewFields ? 

### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

1.1.1

### Expected / Desired Behavior / Question

I am creating a package to wrap `T extends SharePointQueryable`, the purpose is to create a business object easily base on your package. My code fragment likes the behind:

```ts
export abstract class QueryableWrapper<T extends SharePointQueryable> { 
//...
}

export interface ISchema {
  Id: string;
  "odata.editLink": string;
  "odata.etag": string;
  "odata.id": string;
  "odata.metadata": string;
  "odata.type": string;
}

export abstract class SchemaObjectQueryableWrapper<
  T extends SharePointQueryable,
  S extends ISchema | Array<ISchema>
> extends QueryableWrapper<T> { 
//... 
}

export interface SPViewSchema extends ISchema {
//...
}
export interface SPListSchema extends ISchema, IChangeTokenSchema {
//..
}

// SPView wrapper
export class SPView extends SchemaObjectQueryableWrapper<View, SPViewSchema> {
//...
}

// SPList wrapper
export class SPList extends SchemaObjectQueryableWrapper<List, SPListSchema> {
//..
}

// Business object example, LeaveApplications is a SPList, just wrap business logic.
export class LeaveApplications extends SPList { 
// Do business logic.
}

```

So, I read your code, I think exporting them is fine. What are your reasons for not exporting them?  If you export them is great for me. :-) Thanks.

**Comment by patrick-rodgers** [comment]
No reason not to, can easily make this change.

**Comment by patrick-rodgers** [comment]
Done, will be part of today's beta version.

**Comment by simkessy** [comment]
Does this allow me to get View fields? 

I'm return a view and trying to do `viewReview.View.ViewFields` on a `get()`  but it's not working.

**Comment by patrick-rodgers** [comment]
@simkessy - I think you want to do something like is [shown in the docs](https://pnp.github.io/pnpjs/sp/docs/views/#get-a-views-properties) as well as [.fields](https://github.com/pnp/pnpjs/blob/dev/packages/sp/src/views.ts#L62). Something like:

```TypeScript
pnp.sp.web.lists.getByTitle("Documents").views.getByTitle("View Title").fields
```

On a side note, please feel free to open new issues for questions. We often miss comments on old issues.
