### ISSUE TITLE
Get Items not working in workbench

### ISSUE THREAD

**Issue by Brank** [pnp/pnpjs#1532]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.13]

Please specify what version(s) of SharePoint you are targeting: [Sharepoint Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
When using 

```
sp.web.lists.getByTitle("TEST").items.get()
        .then((items)=>{
            console.log(items);
        });

```
It should get all the items in the list "TEST" passed as parameter in method GetByTitle eventhough the code is executing in Sharepoint Workbench.

### Observed Behavior
Using above code, the call is returning a 404 Not found, because the request has the following address:
https://MYSHAREPOINTSITE/sites/MYSUBSITE/_layouts/15/_api/web/lists/getByTitle('TEST')/items

The correct request should be without "/_layouts/15", but for some reason this is added.
### Steps to Reproduce
1.- Create a new SPPFX webpart
2.- Make "npm install @pnp/sp @pnp/graph --save"
3.- Make a call to sharepoint with the following code to retrieve items:
`sp.web.lists.getByTitle("TEST").items.get()
        .then((items)=>{
            console.log(items);
        });`
4.- Make "gulp serve"
5.- In your Sharepoint Online go to https://MYSHAREPOINTSITE/sites/MYSUBSITE/_layouts/15/workbench.aspx
6.- Add the webpart and see result

Thanks in advance.

Best regards,

**Comment by PathToSharePoint** [comment]
I suspect that you didn't establish context (source: happens to me all the time...).

[See the instructions](https://pnp.github.io/pnpjs/getting-started/), this is what I usually include:
```
  return super.onInit().then(_ => {

    // other init code may be present

    sp.setup({
      spfxContext: this.context
    });
  });
```

**Comment by Brank** [comment]
You've just hit the nail, don't know how did I forget such thing...

Thanks!
