### ISSUE TITLE
"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."

### ISSUE THREAD

**Issue by wasiullah-mh** [pnp/pnpjs#1536]
I am trying to create a Site Collection using PNP JS

sp.site.createCommunicationSite(
        "Test",
        1033,
        true,
        "https://XYZ.sharepoint.com/sites/Test",
        "Description",
        ).then((result) => {
     
          alert("Site Created");
      })
      .catch(e => {
        alert("Error"+e);
        console.log(e);
      });

**Comment by patrick-rodgers** [comment]
Whatever use/account you are using doesn't have permissions to create sites is the most likely issue here. How are you handling authentication?

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
