### ISSUE TITLE
Like unlike site pages item throw to 404

### ISSUE THREAD

**Issue by stact** [pnp/pnpjs#1542]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.1.0    ]

Please specify what version(s) of SharePoint you are targeting: [    Online     ]

### Expected / Desired Behavior / Question
Try to like/unlike page with pnpjs api
### Observed Behavior
POST 404 error is raising
![image](https://user-images.githubusercontent.com/9899166/105079239-6ff3bd80-5a8f-11eb-9949-65167853a48a.png)

### Steps to Reproduce
- Import 
```javascript
import { setup as pnpSetup } from "@pnp/common";
import { sp } from "@pnp/sp";
import "@pnp/sp/clientside-pages";
import { IClientsidePage } from "@pnp/sp/clientside-pages";
import "@pnp/sp/comments/clientside-page";
```
- Get page `IClientsidePage`
```javascript
pnpSetup({
  spfxContext: this.context,
});
const page: IClientsidePage = await sp.web.loadClientsidePage(news.relativeUrl);
```
- Then try to like
```javascript
await page.like();
```

**Comment by juliemturner** [comment]
Based on the error I suspect that `news.relativeUrl` is not actually the path to a page?

The value for that has to be something like: `/sites/dev/sitepages/mypage3.aspx`

**Comment by stact** [comment]
The url is well formed because it's working with `getLikedByInformation` 
```javascript
const page: IClientsidePage = await sp.web.loadClientsidePage(news.relativeUrl);
const info = await page.getLikedByInformation();
console.log(info);
```
Results:
![image](https://user-images.githubusercontent.com/9899166/105088387-1ba30a80-5a9c-11eb-8c26-75d7297ff30d.png)

We tried also https://pnp.github.io/pnpjs/sp/comments-likes/#like but here we got 500 internal error
```javascript
const item = await sp.web.getFileByServerRelativeUrl(news.relativeUrl).getItem();
console.log(await item.getLikedByInformation());
await item.like();
```
![image](https://user-images.githubusercontent.com/9899166/105089356-4e013780-5a9d-11eb-9264-b23940663698.png)

`Request URL: https://m365x291874.sharepoint.com/_api/Microsoft.Office.Server.ReputationModel.Reputation.SetLike(listID=@a1,itemID=@a2,like=@a3)?@a1=%27{287ad70f-5bba-4e0a-b312-7d2cca903775}%27&@a2=%2711%27&@a3=true`

Same here getLiked info is working but not like/unlike

Let me know if you need further information. Thank you @juliemturner

**Comment by juliemturner** [comment]
For your second test `item.like()` where the item is a client-side page will not work that was the basis of the fix that went out.

I'll take a look and see if I can figure out what's wrong.
