### ISSUE TITLE
setProxyUrl and ETIMEOUT

### ISSUE THREAD

**Issue by ntodorov** [pnp/pnpjs#1543]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0.13   ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]

### Expected / Desired Behavior / Question
The servers for upper environments (TST, UAT, PRD) are under corporate proxy so when I deploy there I need to set up the proxy configuration.
I used `setProxyUrl()` and it seems it works partially.
From the proxy logs we can see that it hits the SPO authentication URL, but after that the application seems to try to hit another Microsoft owned IP address and that call does not use the proxy settings - we cannot see it in the proxy logs.
The result is:
```
request to https://accounts.accesscontrol.windows.net/xxx-yyy/tokens/OAuth/2 failed, reason: connect ETIMEDOUT 40.126.7.66:443 stack:FetchError: request to https://accounts.accesscontrol.windows.net/xxx-yyy/tokens/OAuth/2 failed, reason: connect ETIMEDOUT 40.126.7.66:443
    at ClientRequest.<anonymous> (E:\inetpub\wwwroot\onestop-attachments\node_modules\node-fetch\lib\index.js:1345:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
NOTE: `xxx-yyy` is just for hiding my config here.

Proxy is configured to allow requests to https://accounts.accesscontrol.windows.net
Any suggestions on how I can better debug this situation?

The IP addresses (ETIMEDOUT 40.126.7.66:443) change almost on every request, I run. 

Also any other approach to work with PnPjs behind a corporate proxy?

### Observed Behavior
using proxy should allow PnPjs to communicate with https://accounts.accesscontrol.windows.net and all it redirects.

### Steps to Reproduce
- you should not have access to internet except through proxy.
- the proxy should be configured to allow access to https://accounts.accesscontrol.windows.net and your SPO site URL
- you may need to config npm to use the proxy and to set the proxy to allow connections to the official npm url.

**Comment by ntodorov** [comment]
Adding more info:
By adding the `global-agent` npm package, the connection worked. This leads me to think, that it is something in the PnPjs - `setProxyUrl()` not bootstrapping all HTTP requests.

With global-agent I used env var `GLOBAL_AGENT_HTTP_PROXY=http://yoour-proxy-url:yourport`
and their second approach:
```javascript
import {
  bootstrap
} from 'global-agent';

bootstrap();
```

If you guys manage to fix it will be great! I would prefer not to use an external package.

**Comment by patrick-rodgers** [comment]
Can you share a bit more of your code? Want to make sure we can easily reproduce what you're seeing so we can debug and fix. Are you calling setProxyUrl("http://yoour-proxy-url:yourport")?

**Comment by ntodorov** [comment]
sure @patrick-rodgers,

yes -> `setProxyUrl("http://yoour-proxy-url:yourport")` 

here is the code

```javascript
import { setProxyUrl, SPFetchClient } from '@pnp/nodejs-commonjs';
import { sp } from '@pnp/sp-commonjs';
import { config } from '../config/config';
import logger from './logger';

sp.setup({
    sp: {
        fetchClientFactory: () => {
            const proxy = config.proxyUrl?.trim();
            if (proxy) {
               logger.info(`using proxy: ${proxy}`);
               setProxyUrl(proxy);
            }


            const Url = config.sharePoint.getSiteURL();
            logger.info(`connectiong to: ${Url}`);
            return new SPFetchClient(Url,
                config.sharePoint.clientId,
                config.sharePoint.clientSecret);

        },
    },
});
```

**Comment by patrick-rodgers** [comment]
That all looks fine at first glance, thanks for sharing it. Let's see if we can figure out what is going on. I had a look and all requests _should_ be getting the proxy settings, but obviously that isn't happening.

**Comment by patrick-rodgers** [comment]
I think I found it - one of the methods was using nodeFetch directly. Going to test out a fix and then push a beta so you can confirm the fix, works?

**Comment by ntodorov** [comment]
Yes - i'm in a testing phase so it will be easy for me to try it out. Let me know which version to use and will fire it up.

**Comment by patrick-rodgers** [comment]
`npm install @pnp/sp@beta --save` should get you 2.1.1-beta0. Please give that a try, I believe the issue you describe to be fixed.

**Comment by ntodorov** [comment]
I was using `@pnp/nodejs-commonjs` and `@pnp/sp-commonjs` so my existing dependencies looked like this:

```
    "dependencies": {
        "@pnp/nodejs-commonjs": "^2.0.13",
        "@pnp/sp-commonjs": "^2.0.13",
```

after installing the betta, it looks like:
```
    "dependencies": {
        "@pnp/nodejs-commonjs": "^2.0.13",
        "@pnp/sp": "^2.1.1-beta0",
        "@pnp/sp-commonjs": "^2.0.13",
```

Will this actually make the app to use the beta0?

I tried to install `@pnp/nodejs-commonjs@beta` but npm cannot find it.

**Comment by patrick-rodgers** [comment]
Should be there: https://www.npmjs.com/package/@pnp/nodejs-commonjs/v/2.1.1-beta0

You will need to update all the modules, sorry missed you were using -commonjs variant. So remove sp and update sp-commonjs and nodejs-commonjs to current beta versions. Then you should be all set.

On a side note, starting with 2.1.0 we should now be working correctly for esm modules in nodejs so you can try that as well, but easier to reduce the number of moving pieces to test this.

**Comment by ntodorov** [comment]
It works now!

Some notes - needed to install this time @pnp/sp package too so my current dependencies are:
```
    "dependencies": {
        "@pnp/nodejs-commonjs": "^2.1.1-beta0",
        "@pnp/sp": "^2.1.1-beta0",
        "@pnp/sp-commonjs": "^2.1.1-beta0",
```
without sp it gave me:
```
> tsc

node_modules/@pnp/sp-commonjs/search/query.d.ts:36:114 - error TS2307: Cannot find module '../../common/libconfig.js' or its corresponding type declarations.

36 export declare const Search: (baseUrl: string | ISharePointQueryable, options?: IConfigOptions, runtime?: import("../../common/libconfig.js").Runtime) => ISearch;
                                                                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@pnp/sp-commonjs/search/suggest.d.ts:10:115 - error TS2307: Cannot find module '../../common/libconfig.js' or its corresponding type declarations.

10 export declare const Suggest: (baseUrl: string | ISharePointQueryable, options?: IConfigOptions, runtime?: import("../../common/libconfig.js").Runtime) => ISuggest;
                                                                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@pnp/sp-commonjs/utils/toabsoluteurl.d.ts:7:78 - error TS2307: Cannot find module '../../common/libconfig.js' or its corresponding type declarations.

7 export declare function toAbsoluteUrl(candidateUrl: string, runtime?: import("../../common/libconfig.js").Runtime): Promise<string>;
```

**Comment by patrick-rodgers** [comment]
Thanks @ntodorov for validating. Will have a quick look at those notes you shared and see if we have any issues. Thanks again!
