### ISSUE TITLE
Getting 403 error when adding and removing role assignments

### ISSUE THREAD

**Issue by cardinalpipkin** [pnp/pnpjs#1551]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [1 ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.0.12  ]

Please specify what version(s) of SharePoint you are targeting: [  SharePoint Online  ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I am getting 403 errors when adding role assignments to a SharePoint list item and document library. How do I stop getting these errors? Is the solution possibly to do with simulating MY permissions instead of another user with lower permissions somehow?

### Observed Behavior
 I have been testing this functionality for a webpart that submits to an SPO list. On the workbench it works fine, but it shows 403 errors when deployed to an SPO site and when "user B" who doesn't have the same permissions as me (I have Full control and user B has Contribute). I think I understand why this is happening due to user B not having the permissions to be able to set permissions, although I elevated user B's permissions to Full Control, and it still returns intermittent errors, working sometimes, and others not. 
 
Below is the code I'm using when submitting to the list, the first 4 lines is me experimenting with PermissionKind, thinking that this might be solution, although I don't know whether it is or not.

```
const perms2 = await list.getCurrentUserEffectivePermissions();
          console.log(perms2);
          await getList2.currentUserHasPermissions(PermissionKind.ManageLists);
          // console.log(v2);

           const owner = this.state.PolicyOwnerBackup; //These are the people pickers where the users are selected by user B to be assigned the permissions.
           const rperson = this.state.ResponsiblePersonBackup;
           console.log(owner, 'owner');
           console.log(rperson, 'rperson');
           
           const EditroleDefinition = await sp.web.roleDefinitions.getByName("Edit").get();
           console.log(EditroleDefinition, 'EditroleDefinition');
           const FulControlroleDefinition2 = await sp.web.roleDefinitions.getByName("Full Control").get();
           console.log(FulControlroleDefinition2, 'FulControlroleDefinition');

           await sp.web.lists.getByTitle('MyList').items.getById(theItem).breakRoleInheritance(false, false); //I break role inheritance here...is this necessary?

           const assignments = await sp.web.lists.getByTitle('MyList').items.getById(theItem).roleAssignments();
           
           console.log(assignments, 'assignemnts');
         
           assignments.forEach(async (entry) => {
            
            const remove = await sp.web.lists.getByTitle('MyList').items.getById(theItem).roleAssignments.remove(entry.PrincipalId,FulControlroleDefinition2.Id );
            console.log(remove);  //Here is where I have to remove the existing permissions, if the people pickers are changed in the form.
        
           });
//From here is where I actually assign the permissions, the group adds fine without problem but the individual people pickers are not added successfully and shows errors if user B is has not got full control.
           const groupName2 = "My List Owners";
           var grp2 = await sp.web.siteGroups.getByName(groupName2)();

           await sp.web.lists.getByTitle('MyList').items.getById(theItem).roleAssignments.add(grp2.Id, FulControlroleDefinition2.Id);
          
           if(owner){
             await sp.web.lists.getByTitle('MyList').items.getById(theItem).roleAssignments.add(owner, FulControlroleDefinition2.Id);
             }
           if(rperson){
             await sp.web.lists.getByTitle('MyList').items.getById(theItem).roleAssignments.add(rperson, FulControlroleDefinition2.Id);
             }
```

Is there a way to simulate my permissions when other users submit to a SPO list? Or am I going about it the wrong way in the first place? Really need help with this one.

**Comment by koltyakov** [comment]
Hi @cardinalpipkin, 

[403 Forbidden](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403)

When a user has no access to perform specific action or reach specific resource 403 is expected.

To stop receiving 403, obviously permissions should be granted to a user. The usual practice is handle the permissions and show "You have no access" in the UI on corresponding error or in application's preflight check.

Please check [permissions related API docs](https://pnp.github.io/pnpjs/sp/permissions/#has-permissions).

In a case a user should process an action which having no permissions, such delegate action can be moved to a backend processing (Flow, Azure Functions, etc.).

**Comment by juliemturner** [comment]
I'm just going to address your general architecture and security question and not the code itself...

Confirming what you suspect, client-side code, no matter what you're trying to do, is limited by the user who's executing the codes permission level. If you really want to have a solution where a certain set of code executes when any user runs it regardless of whether they actually have the permissions to do that then you need to rethink your architecture. 

Given that you're using SharePoint online there a several ways to solve the problem... but probably the easiest is to write an Azure Function that does the work.  That code can use app permissions to execute the thing you want done... it can also, if you want to, use AAD auth to authenticate the user trying to execute the code is authorized to do so.

**Comment by juliemturner** [comment]
HAH @koltyakov  -- we were both answering it at the same time :)

**Comment by cardinalpipkin** [comment]
Hi, thanks for your quick response. I don't have access to Azure. Would using Power Automate to change permissions work? Also, what is the minimum permission level that is required to assign permission levels to SPO list items?

**Comment by koltyakov** [comment]
You don't need a flow to check the permissions. Via a link above to the docs there is desc on how to check a certain permissions level.  If I can recall right `.Manage` permissions level is needed for granting access to other users.

**Comment by cardinalpipkin** [comment]
Ah okay, so a flow would work. I guessing a flow would be created by me, triggered on new list item created, then use my credentials to assign new permissions?
