### ISSUE TITLE
How do I get Associated Site Logos and Descriptions?

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1552]
@patrick-rodgers @tavikukko 

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version
Latest

### Expected / Desired Behavior / Question
I have a webpart that builds tiles for the Hub's associated sites.   I am trying to get both the SiteLogoUrl and Site description in the search results (single call if possible).

Unfortunately I can't seem to do it without first getting the list of associated sites, then iterating through the list of URLs and getting Description/SiteLogoUrl.

I'm wondering if it's a limitation of this library or Search in general?

I did notice with the OOTB Sites webpart, it seems to get at least the SiteLogoUrl because the Sites webpart does show icons so I'm just wondering if there is a better way to approach this so I don't need multiple calls.

![image](https://user-images.githubusercontent.com/49648086/105735862-2decd080-5f02-11eb-88e7-a73d17b156e2.png)

## Here's a snippet of my current search query.  I added "*","SiteLogoUrl","Description" to the SelectProperties but I don't see them in the return.

Thanks!

```typescript

    sp.search(<ISearchQuery>{
        Querytext: `contentclass:STS_Site AND departmentId:{${departmentId}}`,
          SelectProperties: ["*","Title", "SPSiteUrl", "WebTemplate","departmentId","SiteLogoUrl","Description"],
          RefinementFilters:[`departmentid:string("{*",linguistics=off)`],
          RowLimit: 500,
//          SortList: [ {Property: 'Title',Direction: sortDirection }],
          TrimDuplicates: false})
          .then((r: SearchResults) => {
    
            console.log(r.RowCount);
            console.log(r.PrimarySearchResults);
            entireResponse.hubs = r.PrimarySearchResults;

            entireResponse.hubs.map( h => {
                h.sourceType = hubsCategory;
            });

            
            callback( entireResponse, custCategories, newData );
    
    });

```

**Comment by juliemturner** [comment]
Without looking into it further I can't specifically answer your question, but the short answer is that only thing that are configured to be queryable can be retrieved in search results... So where you really want to focus your research is if the SiteLogoUrl and/or Site Description are crawled/managed properties in SharePoint search and if they are queryable ... 

In SharePoint Admin look at the Search Admin settings: https://<yourtenant>-admin.sharepoint.com/_layouts/15/searchadmin

**Comment by tavikukko** [comment]
Just do normal search, no RefinementFilters needed, and use SiteLogo and Description as SelectedProperties
```typescript
sp.search({
  "Querytext": `contentclass:STS_Site AND departmentId:{${departmentId}}`,
  "RowLimit": 10,
  "StartRow": 0,
  "ClientType": "ContentSearchRegular",
  "SelectProperties": [
    "Title",
    "SPSiteUrl",
    "WebTemplate",
    "departmentId",
    "SiteLogo",
    "Description",
  ]
}).then(res => {
  console.log(res)
})
````
![image](https://user-images.githubusercontent.com/2223355/105907390-98e6f600-602d-11eb-9747-4805898515a6.png)

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.

**Comment by mikezimm** [comment]
@tavikukko @juliemturner ,

I did see in my dev tenant the same thing in your screenshot for both **SiteLogo** and **Description**.

I did notice with your code that I retrieved all the desired information with the exception that I did not get the information for the actual Hubsite itself... just associated hubs.

However, I added one line back **TrimDuplicates: false,** and it then got the hub as well:

Here's the final code I ended up using.

Now that you have shown me where to look, I want to also get things like lastModified etc....

Thanks again!

```typescript
    sp.search(<ISearchQuery>{
        Querytext: `contentclass:STS_Site AND departmentId:{${departmentId}}`,
          SelectProperties: ["*","Title", "SPSiteUrl", "WebTemplate","departmentId","SiteLogo","SiteDescription"],
          "RowLimit": 10,
          "StartRow": 0,
          "ClientType": "ContentSearchRegular",
          TrimDuplicates: false, //This is needed in order to also get the hub itself.
        })
          .then( ( res: SearchResults) => {
    
            console.log('associated sites with URL/Desc', res);
            console.log(res.RowCount);
            console.log(res.PrimarySearchResults);
            entireResponse.hubs = res.PrimarySearchResults;

            entireResponse.hubs.map( h => {
                h.sourceType = hubsCategory;
            });
            callback( entireResponse, custCategories, newData );

    });
```

**Comment by mikezimm** [comment]
I checked into what is currently available and modified my query to include:
I was able to get some level of created and modified info so thanks again for the reply!

```typescript
    sp.search(<ISearchQuery>{
        Querytext: `contentclass:STS_Site AND departmentId:{${departmentId}}`,
          SelectProperties: ["*","Title", "SPSiteUrl", "WebTemplate","departmentId","SiteLogo","SiteDescription",
          "ContentModifiedTime","LastModifiedTime", "LastModifiedTimeForRetention","ModifiedBy","Created","Modified","CreatedBy","CreatedById","ModifiedById"],
          "RowLimit": 500,
//          "StartRow": 0,
          "ClientType": "ContentSearchRegular",
          TrimDuplicates: false, //This is needed in order to also get the hub itself.
        }
```
