### ISSUE TITLE
Auth from SPA in on-premise

### ISSUE THREAD

**Issue by aslanovsergey** [pnp/pnpjs#1558]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

What are possible ways to authenticate against SharePoint on-premise (2016) from an SPA which runs outside of SharePoint?

**Comment by patrick-rodgers** [comment]
We have a[ whole section in the docs on authentication](https://pnp.github.io/pnpjs/authentication/) methods, please review and let us know if you don't find an answer there. One of those specifically calls out [SPA apps](https://pnp.github.io/pnpjs/authentication/msaljsclient/#use-in-single-page-applications).

**Comment by koltyakov** [comment]
In On-Premise, especially for non-OAuth auth, the simplest way would be to host an SPA on a SharePoint page and hide/remove whatever is not needed for such an app.

Alternatively, you'd need proxying some API calls through the backend which hosts an SPA and use server-side auth.

**Comment by koltyakov** [comment]
Going to close it as answered and pending for a feedback for a long time. Feel free to reopen.
