### ISSUE TITLE
Graph.me.drive.getItemById(<Id>).update({"name": "new name"}) => Error : 400 Invalid Request

### ISSUE THREAD

**Issue by arunakshi** [pnp/pnpjs#1559]
Hi All,

### Category
- [x] Bug

### Version

Please specify what version of the library you are using: [     2.1.0    ]

Please specify what version(s) of SharePoint you are targeting: [    SPO   ]

### Expected / Desired Behavior / Question
graph.me.drive.getItemById(itemId).update({"name": "sample test"}) updates the content of the file

### Observed Behavior
I have a Bad / Invalid request error when I use PnP OneDrive API. Response is as follows:

 Error making HttpClient request in queryable [400] Bad Request ::> {
  "error": {
    "code": "invalidRequest",
    "message": "Invalid request"....
  }
}

The API uses PATCH for the update and do not have /content at the end of the URL. The request URL looks like this, see below: 
https://graph.microsoft.com/v1.0/me/drive/items/{item-id}

### Steps to Reproduce
Create a new SPFX Webpart
Install pnp graph
used the following code:

I have initialized graph correctly like this in the webpart: 
  public onInit(): Promise<void> {
    return super.onInit().then(_ => {
      graph.setup(this.context);
    });
  }

I am also able to get driveItem content with this code: 
  const content = await graphClient.me.drive.getItemById(itemId).getContent();
 console.log(content);

I set up permissions with Files.ReadWrite and also used User.Read.All.

**For more Information.**

I managed to use same request with below link in the Graph Explorer, it works for me without error.
https://graph.microsoft.com/v1.0/me/drive/items/{item-id}/content      
[PUT]-operation

The reason I am using this in my code is we would want to avoid building PUT requests on update with Etags.

**Comment by patrick-rodgers** [comment]
There are two updates in play. You can update the drive item's meta data (.update method in our library) or you can set the content of the file (.setContent) method in our library. Can you check if the setContent method works for you to update the drive items content?

My tests, which all worked look like:

```TypeScript
import { graph } from "@pnp/graph";
import "@pnp/graph/onedrive";
import "@pnp/graph/users";

const drive = graph.me.drive;
const item = drive.getItemById("{id}");

const u = await item();

console.log(u);

await item.update({ "name": "new-file-name333.txt" });

const r = await item.setContent("Hello am I the content you are looking for?");
```

### Bug Identified

Now while doing the testing on your issue I identified a bug in drives.getById that I fixed, but I don't think that affects your example.

My tests which did not work:

```TypeScript
import { graph } from "@pnp/graph";
import "@pnp/graph/onedrive";
import "@pnp/graph/users";

// this line failed
const drive = graph.users.getById("{id}").drives.getById("{id}");

const item = drive.getItemById("{id}");

const u = await item();

await item.update({ "name": "new-file-name.txt" });

await item.setContent("Hello I am the content");
```
