### ISSUE TITLE
Error trying to upload a file containing single quote

### ISSUE THREAD

**Issue by EagleWizard28** [pnp/pnpjs#156]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
1.1.1

### Expected / Desired Behavior / Question
I am trying to upload a file containing a single quote in the file name by using the "folder.files.add" API. 
`articleFolder.files.add(encodedArticleFileName, articleFile, true)`

### Observed Behavior
For the files without a quote this works without a problem, conform the given example code. But for files where the name contains a single quote ' the method gives issues:

> The expression "web/getFolderByServerRelativeUrl('/sites/testsite/Shared Documents/TestFolder')/files/add(overwrite=true,url='List with ID's.xlsx')" is not valid.

Even when I additionally encode the file name, so the single quote is replaced with %27 it doesn't work.

### Steps to Reproduce
Try to upload a file containing a single quote in the name with the above method.

**Comment by patrick-rodgers** [comment]
Can you try the [suggestion here](https://jaredmeredith.wordpress.com/2017/04/26/solved-issue-with-sharepoint-rest-api-document-upload-solving-the-case-of-the-single-apostrophequote-in-the-url-post/) and escape the quote using another ' char?

We generally don't do any character replacing within the library because there are just too many possibilities across languages.

**Comment by EagleWizard28** [comment]
Thanks for the suggestion Patrick.  It set me on the right track.
But instead of using this in the article: 
`serverRelativeUrlToFolder.replace(/\%27/g,"''")`

My orginal file name was not encoded, so this worked out for me:
`serverRelativeUrlToFolder.replace("'","''")`

**Comment by jpalo** [comment]
Please note that `.replace("'", "''")` only replaces the first occurence, to replace all, use `.replace(/'/, "''")`.
