### ISSUE TITLE
sp.web.getFolderByServerRelativeUrl may format the request url wrong. Feature seems not to work.

### ISSUE THREAD

**Issue by JMTeamway** [pnp/pnpjs#1560]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [  @pnp/sp": "^2.0.5"  ]
Please specify what version(s) of SharePoint you are targeting: [   Online      ]

### Expected / Desired Behavior / Question
I have a webpart running on a page of site "Site1".
Calling from this webpart
`sp.web.getFolderByServerRelativeUrl("/sites/site2/<folderPath>").files`
returns the folders content.

### Observed Behavior
Error: Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-2147024809, System.ArgumentException","message":{"lang":"fr-FR","value":"Server relative urls must start with SPWeb.ServerRelativeUrl"}}}

If it is not possible to look for a folder on another site, then it seems to me the parameter of the function should skip the '/sites/Site2' part and should only take a path to the folder.

If it is possible, then I think there is a bug as the url called in this scenario is :
`https://<tenant>.sharepoint.com/sites/site1/_api/web/getFolderByServerRelativeUrl('%2Fsites%2Fsite2%2F<pathToFolder>')/[...]`
and this url does not work. The url that should be called is
`https://<tenant>.sharepoint.com/sites/site2/_api/web/getFolderByServerRelativeUrl('%2Fsites%2Fsite2%2F<pathToFolder>')/[...]`

### Steps to Reproduce
Create a site site1.
Create a webpart with this call and deploy it on a page from site1.
Create a site s2 with a folder in its library.

**Comment by koltyakov** [comment]
Hi @JMTeamway, 

It's not a bug and expected behaviour. Requests are sent in a context of a web. When a request should be in a different web context this must be explicitly provided with `Web('[web_abs_url]')`.

Referencing `sp.web.` means that it's a current web.

**Comment by JMTeamway** [comment]
Ok, seems legit !
Then this ticket may be closed.

Still, if the call is linked to the context, the fact that we must provide in parameter the portion of url of the current site brings nothing, and is just allowing to mis-use the api.
Maybe it coul be replace with a relative path argument.

**Comment by koltyakov** [comment]
It could, but then it wouldn't be `*ByServerRelative*` which is in SharePoint terminology is the full relative path. We try projecting method names and parameters as close as possible to the original REST API elements. Which we hope in the end of the day is less confusing for the larger audience with SharePoint background than bringing lots of helpers that do not have any direct projection to the API.

PnPjs has extensions API https://pnp.github.io/pnpjs/odata/extensions/ which can be used by local teams, e.g. who will prefer having `.getFolderByRelativeUrl` helper in their code base with extra logic inside.

**Comment by JMTeamway** [comment]
Thanks a lot for the precious information, I can close the ticket in peace now ;-)
