### ISSUE TITLE
Update to use MSAL auth as default for running tests

### ISSUE THREAD

**Issue by juliemturner** [pnp/pnpjs#1564]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.1.1]

### Expected / Desired Behavior / Question

Update scripts so that MSAL will be used as the default auth when running tests.

**Comment by patrick-rodgers** [comment]
Updating to ONLY use MSAL authentication for tests. It just makes things much simpler and has minimal impact to folks outside the library devs.
