### ISSUE TITLE
getAllChildrenAsOrderedTree not working when no customSortOrder is set

### ISSUE THREAD

**Issue by mmol1** [pnp/pnpjs#1567]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [2.1.1]

### Expected / Desired Behavior / Question
When using getAllChildrenAsOrderedTree() the children will always be returned in the correct order, even when no customSortOrder has been set.

### Observed Behavior
When no customSortOrder has been set the function crashes, returning with the following message:

`Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at ensureOrder (types.js:97)
    at Proxy.<anonymous> (types.js:136)
    at Generator.next (<anonymous>)
    at fulfilled (tslib.es6.js:73)`

After enabling customSortOrder (without changing the order of any Term) and saving it works correctly.

### Steps to Reproduce
```
const set = sp.termStore.groups.getById(groupId).sets.getById(setId);
const terms = await set.getAllChildrenAsOrderedTree();
```
without setting any customSortOrders

### Suggestions
1. 'setSorts' is undefined, yet it is not checked. (Also note that it is an optional parameter.) Line: [https://github.com/patrick-rodgers/pnpjs/blob/f7a41feb270a9d7d57546e25d1e2ff979113eb20/packages/sp/taxonomy/types.ts#L110]
2. because the above it not checked correctly, 'sorts' can be null, yet it is not checked. Line: [https://github.com/patrick-rodgers/pnpjs/blob/f7a41feb270a9d7d57546e25d1e2ff979113eb20/packages/sp/taxonomy/types.ts#L113]

**Comment by patrick-rodgers** [comment]
Thanks, will have a look.

**Comment by patrick-rodgers** [comment]
Got this fixed, thanks for reporting it. Will go our in 2.2.0 release likely today.
