### ISSUE TITLE
broken links everywhere

### ISSUE THREAD

**Issue by alirobe** [pnp/pnpjs#157]
If I google "office 365 graph pnp js", I get this article first. 
https://dev.office.com/blogs/introducing-pnpjs-client-side-libraries-for-office365

All links broken 🙃

Would be nice if all the links for anything related to PnP were fixed. I am endlessly finding roads to nowhere and outdated documentation. Use redirect meta tags, don't 404 me...

I'd suggest running something like screamingfrog on the blog site to check for these sorts of things.

**Comment by VesaJuvonen** [comment]
thx Ali for reporting this. When we changed repository names in GitHub due other reasons, it also impacted the URLs of the documentation, which we missed as repository URL is taken care of by GitHub automatically.

Thanks for reporting this one, we have now fixed the links in the above blog post.
