### ISSUE TITLE
currentUserHasPermissions error when cross site.

### ISSUE THREAD

**Issue by Tony518** [pnp/pnpjs#1572]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.1.1  ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online    ]

### Expected / Desired Behavior / Question
When I use pnp.js to check if currentUser has **permissions** to edit the **folder**, and my folder is not in current site, eg: MyCurrentSite: https://serviceme.sharepoint.com/sites/two, and the folder in "https://serviceme.sharepoint.com/sites/one".

### Observed Behavior
When i use item.currentUserHasPermissions(PermissionKind.EditListItems) it still call the site/two api, not the one.
But I use the same method to check the permission of file , it works well.

### Steps to Reproduce
```
//get folder as item
const folder = await Web("https://serviceme.sharepoint.com/sites/tclone").getFolderByServerRelativePath("/sites/tclone/TCL/").getItem();
    console.log("folder",folder);
//check folder permission
    var folderPermission = await folder.currentUserHasPermissions(PermissionKind.EditListItems);
    console.log("folder permission",folderPermission); 
```
the folder can be retrieved successfully, but when i check permission, the error as below.

![image](https://user-images.githubusercontent.com/15099434/106984263-3070e500-67a2-11eb-9fcf-4e89d72372bf.png)

**Comment by tavikukko** [comment]
Its not working even if same site.
The problem here is, that you are requesting the **rootfolder** of the list, and trying to get the item assigned to it using **getItem** method. There is no item assigned to **rootfolder**, it is actually the list itself. So in this case, if the folder is root, getItem should return the list.

**Comment by patrick-rodgers** [comment]
Good analysis, but getItem can't return list information. In 5+ years this is the first time this has come up so maybe something we can cover in the docs?

Now, one could say "well can't you just make the effectivebasepermissions method understand it needs to run on the list's base permissions for the root folder". And maybe, but extend that logic to all the methods on folder/item and quickly it gets super complicated for not much real value.

**Comment by tavikukko** [comment]
Did some more analysis:
when you call getItem on a rootFolder or a folder that does not exist:
```typescript
 await sp.web.getFolderByServerRelativeUrl("/sites/sitecoll/dalist").getItem()
```
 SP responses with 200, and the response is:
```json
{
	"odata.metadata": "https://contoso.sharepoint.com/sites/sitecoll/_api/$metadata#Edm.Null",
	"odata.null": true
}
```
So, instead of making any fancy work-arounds, could we just throw this?

**Comment by patrick-rodgers** [comment]
Yes. I am guessing now we pass back from getItem what? A useless item object? I haven't had a chance to step through it, but a 200 would just get parsed and passed on. But then wouldn't work for anything else.

**Comment by tavikukko** [comment]
seems like getitem() does not get resolved, that might be the smoking gun.

**Comment by patrick-rodgers** [comment]
Added code to check for and throw an error if no item is found for a folder.
