### ISSUE TITLE
createDefaultAssociatedGroups throws exception for modern sites

### ISSUE THREAD

**Issue by nbelyh** [pnp/pnpjs#1575]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.11]
Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

The method `createDefaultAssociatedGroups` throws exception "Access Denied" for modern sites (if setting "No Script Site" is set to true, which is the default). https://pnp.github.io/pnpjs/sp/site-groups/

### Expected / Desired Behavior / Question

I expect the method to create default groups regardless of the scripting setting.

### Observed Behavior

403: Access denied for farm admin

### Steps to Reproduce

Create a new modern Teams site, then run against it the following code (creates a sub-site):
```ts
const created = await sp.web.webs.add("My Web", "web1", "", "STS#3", 1033, false);
const admin = await sp.web.ensureUser("me@mytennant.sharepoint.com");
await created.web.createDefaultAssociatedGroups("My Web", admin.data.LoginName, false, true);  // << 403 here
```

Note: If you [allow custom scripts](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script), the code above works. 
I kind of fail to see any logic or relation between creating site groups and allowing scripts...?

Would appreciate explanation/workaround/fix...

**Comment by koltyakov** [comment]
The workaround is to enable site scripts. Surprise!

Actually, we can't do anything on a library's side while API blocks something due to the server configuration, which is a design of a specific API limitation behaviour.

**Comment by nbelyh** [comment]
@koltyakov Thank you for the prompt response. Do you have a suggestion where I could go with this issue? I mean, are there any chances of being changed, so enabling scripts is not required to be able to add default groups?

**Comment by koltyakov** [comment]
It could be a topic for discussion in this repo https://github.com/SharePoint/sp-dev-docs which receives visibility for product group(s) sometimes.

I'd suggest, as a conceptual workaround, moving such things to a managed provisioning as of backend processing, where scripts could be allowed first, things provisioned, then finally scripts disabled (back to a defaults).

**Comment by nbelyh** [comment]
Thank you, I'm closing the issue then.

**Comment by nbelyh** [comment]
Unfortunately, the issue in sp-dev-docs was closed as library specific, so I guess it can't be helped then

**Comment by koltyakov** [comment]
That's the way you asked and they read, unfortunately. You mentioned repro steps with PnPjs, which is not bad, but who read this only read this part and immediately thought that it's PnPjs related. However, that's not true as PnPjs only constructs and sends the request to a specific API in this case.

**Comment by nbelyh** [comment]
I understand that; but I haven't been give a chance to clarify as the issue has been closed on the spot and does not allow comments. Looks like hey just spotted the keyword "pnpjs" and closed it.

**Comment by andrewconnell** [comment]
@nbelyh What @koltyakov is correct... my "role" in the **sp-dev-docs** repo's issue list is to triage and make sure stuff belongs there. Time permitting, I do try to answer questions.

If it's an issue with permissions / a REST endpoint, then if you can remove the intermediary usage, when MSFT looks into the issue, they can see the endpoint. Otherwise, they'll do what I did: point to you the library you're using.

Please feel free to create an issue and point to the actual REST endpoint in question...

**Comment by PathToSharePoint** [comment]
@nbelyh unfortunately this is how things work on these community-driven forums. People do this in addition to their day job and have limited bandwidth to dig into each thread.

**Comment by nbelyh** [comment]
@andrewconnell created a new [issue](https://github.com/SharePoint/sp-dev-docs/issues/6760), with REST example this time. I hope it makes sense?
