### ISSUE TITLE
How to enable to show dynamically create column in SharePoint default list view

### ISSUE THREAD

**Issue by brijeshpankhaniya** [pnp/pnpjs#1578]
Hello Everyone,

I have created a SharePoint list column using following PNP JS command as below,

return pnp.sp.web.lists.getByTitle(this.assessmentHistoryListName).fields.addMultilineText("Favorite", 6, true, false, false, true, { Group: "Custom Columns", Hidden: false });

**I have added custom property {Group: "Custom Column", Hidden: false}**

Still I can't see column in my SharePoint default list view.

Please refer below screenshot.
![SS](https://user-images.githubusercontent.com/50993814/107327894-e22a5180-6ad3-11eb-965a-752574ee7a08.png)

Thanks in advance.

Regards,
Brijesh

**Comment by koltyakov** [comment]
To add a field to a view you need to add a field to a view or set view's view XML.

```typescript
const field = await list.fields.addMultilineText(
  'Favorite', 6, true, false, false, true,
  { Group: 'Custom Columns', Hidden: false });

await list.defaultView.fields.add(field.data.InternalName);

// or

await list.defaultView.setViewXml(`
  <View>
    <ViewFields>
      <FieldRef Name="Favorite" />
      <FieldRef Name="LinkTitle" />
    </ViewFields>
  </View>
`); // View XML should be aligned with other view requirements, e.g. contain Query stanza, etc.
```

**Comment by brijeshpankhaniya** [comment]
> To add a field to a view you need to add a field to a view or set view's view XML.
> 
> ```ts
> const field = await list.fields.addMultilineText(
>   'Favorite', 6, true, false, false, true,
>   { Group: 'Custom Columns', Hidden: false });
> 
> await list.defaultView.fields.add(field.data.InternalName);
> 
> // or
> 
> await list.defaultView.setViewXml(`
>   <View>
>     <ViewFields>
>       <FieldRef Name="Favorite" />
>       <FieldRef Name="LinkTitle" />
>     </ViewFields>
>   </View>
> `); // View XML should be aligned with other view requirements, e.g. contain Query stanza, etc.
> ```

It's Working Thanks for the help i appreciate your reply.
