### ISSUE TITLE
How to get anonymous links using PnP JS or REST api?

### ISSUE THREAD

**Issue by ymihir** [pnp/pnpjs#1579]
- [x] Question

PnP Version: 2.0.13  
Target SharePoint version: SP Online 

Is there any from PnP to know the anonymous links available at site collection level and list level? I am not able to find any api for now? If not presented in PnP, is there any REST endpoint available for this?

**Comment by patrick-rodgers** [comment]
Did you review the [docs on sharing](https://pnp.github.io/pnpjs/sp/sharing/)? Does that help get going?

**Comment by ymihir** [comment]
Yes this is good. This link talks about at item level links. But I don't see any way of getting anonymous links from list level or site level. This is not possible yet?

**Comment by patrick-rodgers** [comment]
If you look at [this section of the page](https://pnp.github.io/pnpjs/sp/sharing/#imports) I linked it talks about how the methods are available at four levels.

> There are four objects within the SharePoint hierarchy that support sharing: Item, File, Folder, and Web. You can import the sharing methods for all of them, or for individual objects.

So you can import like below to get them all:

```TypeScript
import "@pnp/sp/sharing";
```

Or pick just the ones you need:
```TypeScript
import "@pnp/sp/sharing/file";
import "@pnp/sp/sharing/file";
```

**Comment by ymihir** [comment]
Thanks will try with above

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
