### ISSUE TITLE
graph.me.joinedTeams returns a 400 error when specifying a $top value

### ISSUE THREAD

**Issue by attCurtisHennessy** [pnp/pnpjs#1581]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [
+-- @pnp/graph@2..13
- @pnp/sp@2.0.13

also the same when updating to 2.1.1
]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
I am expecting it to limit the number of results to the number specified.

### Observed Behavior
It returns a 400, this also happens in the graph explorer for me too.

### Steps to Reproduce

`import { graph } from "@pnp/graph/presets/all";`
     `pnpSetup({
        spfxContext: this.context
      });`
      `graph.setup({
        spfxContext: this.context
      });`
`graph.me.joinedTeams.top(7).get().then(data => {
    console.log(data)
})`

or 

`https://graph.microsoft.com/v1.0/me/joinedTeams?$top=5` in the graph explorer

**Comment by patrick-rodgers** [comment]
If the graph explorer is also throwing an error it might be that joinedTeams doesn't support "top"? And if you go checkout the docs for that method in graph [there is a note saying odata stuff isn't supported](https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=http#optional-query-parameters).

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
