### ISSUE TITLE
SharePoint online: sp.search with AccountName as a RefinementFilters

### ISSUE THREAD

**Issue by AkumaTen** [pnp/pnpjs#1583]
Hi there!
I'm migrating from SP 2013 on prem to SP Online and I cannot guess how to set the following call to work properly. I always get an empty array with no error (please note that I use a valid email in my code):

```javascript
sp.search({
   "Querytext":"*",
   "RowLimit":10,
   "EnableInterleaving":true,
   "TrimDuplicates":false,
   "RefinementFilters": ["AccountName:equals('i:0#.f|membership|<email>')"], 
   "SelectProperties":["PreferredName","AccountName"],
   "SourceId":"b09a7990-05ea-4af9-81ef-edfab16C4e31"
}).then((result) => console.log(result.PrimarySearchResults))`
```
I tried to encode the value of the actual account name with no success
```javascript
"RefinementFilters":[`AccountName:${encodeURIComponent("i:0#.f|membership|<email>")}`]
```
I even tried to configure a RefinableString in the admin panel:

![image](https://user-images.githubusercontent.com/38658826/107778756-bf52a400-6d44-11eb-99f6-546920d13401.png)

In SP 2013 on prem a setting like the following works with no problem
```javascript
"RefinementFilters":["AccountName:equals('domain\\id')"]
```

Can this be related to the full re-index not already happened?
Thanks!

### Category
- [X] Question

### Version

@pnp/sp 2.0.10

Please specify what version(s) of SharePoint you are targeting: online

**Comment by patrick-rodgers** [comment]
@wobba - any ideas on search setting here? Library seems to be executing the query correctly, but no results.

**Comment by wobba** [comment]
This seems to work fine as the FQL filter:

`AccountName:"i:0#.f|membership|name@tenant.onmicrosoft.com"`

**Comment by AkumaTen** [comment]
@wobba it works thanks! did you use the RefinableString mapping?

Let's say the equals() version works as expected, do you know the difference from the SharePoint perspective?
Put in another way: what's the use of equals() if it produces the same result?

**Comment by wobba** [comment]
@AkumaTen unsure why `equals` didn't work for this case, but I believe it has to do with tokenization. When matching in search special characters are omitted unless you set that specifically on the managed property. Did not quite get your question on RefinableString mapping, and how it relates to your original question. proposed filter should work equally well this way on both FQL (as refinement filter) and KQL (in the query text).

**Comment by patrick-rodgers** [comment]
Thanks @wobba for the assist! @AkumaTen all set now?

**Comment by AkumaTen** [comment]
@patrick-rodgers Yes It's ok for me we can close

@wobba I checked the solution you suggested with the settings you see in my screenshot: RefinableString01 set as Refine and mapped to AccountName, I just wanted to know if that settings is mandatory or not but from your answer I guess it is not.

Great support and great library! thanks

**Comment by patrick-rodgers** [comment]
Awesome, thanks all!

**Comment by wobba** [comment]
@AkumaTen missed that, and no need to map People:AccountName. You can use the refinement parameter for any queryable managed property. I would unmap it.

**Comment by AkumaTen** [comment]
@wobba great! I will unmap it. Thanks a lot
