### ISSUE TITLE
sp > Client Side Pages:  Copy entire content from one page to another

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1586]
@juliemturner , 

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version
"@pnp/sp": "^2.0.7",

### Expected / Desired Behavior / Question
I am experimenting with the [copy client side page](https://pnp.github.io/pnpjs/sp/clientside-pages/#copy) and was wondering if there is a way to copy content from one page over the top of another page without deleting the destination page first.

The use cases for this would be to prevent history loss and also the trickiness of replacing the out of the box home page.

I'm thinking my new code would have to be something like:
    1. Load source page
    2. Load destination page
    3. Replace destination page structure with source page structure
    4. Resave destination page

Just don't know what to search and replace in step 3.

I've also looked at the response to loadClientsidePage and it has a huge object structure so I have no idea how what parts I could just copy over.

I also noticed in this in the library and was wondering if it may be a possibility... no idea what it does though or how to use it :)
```typescript
    /**
     * Loads this instance from the appropriate JSON data
     *
     * @param pageData JSON data to load (replaces any existing data)
     */
    fromJSON(pageData: Partial<IPageData>): this;
```

### Observed Behavior
When I just use this structure and the page already exists, it creates a new page with a number added to it like a copy.

Source Filename:  SourcePage.aspx

Destination Filename (already exists):  SourcePage.aspx (in another site)
The copied page gets new name SourcePage(1).aspx

### Steps to Reproduce

```typescript
    const page2 = await Web("https://tenant.sharepoint.com/sites/Patterns/").loadClientsidePage("/sites/Patterns/SitePages/" + sourcePageName + ".aspx");

    console.log( 'Source page ' + sourcePageName , page2 );

        try {
            const pageCopy2a = await page2.copy(destWeb, sourcePageName, sourcePageName);
            console.log( 'Succeded pasting page ' + sourcePageName , pageCopy2a );

        } catch (e){
            console.log( 'Failed pasting page ' + sourcePageName  );
        }
    } catch (e) {
            console.log( 'Failed getting page ' + sourcePageName  );
    }
```

**Comment by patrick-rodgers** [comment]
For this you would need to duplicate all the logic in copy but provide it a page. Easiest way to solve it is for us to add something like `copyTo` that would take an existing page instead of creating a new one.
