### ISSUE TITLE
getItem() after Folder.files.addChunked() gives 404

### ISSUE THREAD

**Issue by EagleWizard28** [pnp/pnpjs#159]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

1.1.1

### Expected / Desired Behavior / Question
When uploading a file to a folder in SharePoint by using the  `Folder.files.addChunked` method the file gets uploaded and I'm able to use the `uploadResult.file.getItem()` method to update the related item.

### Observed Behavior
When uploading a file to a folder in SharePoint by using the  `Folder.files.addChunked` method, the file gets uploaded correctly. However when I'm trying to get the item from the upload result as following `uploadResult.file.getItem()` I get a 404. An attempt is done to fetch data from the following URL, but the format doesn't seem to be correct:
`uploadResult.file.getItem().then(item => {`

> https://tenant.sharepoint.com/sites/kb-KB20/sites/kb-KB20/Shared%20Documents/A1/IT.png/listItemAllFields

When using the `Folder.files.add` method, it works without an issue.

As a workaround for the moment I use the following code:
`sp.web.getFileByServerRelativeUrl(`//${uploadResult.file.toUrl()}`).getItem().then(item => {`

### Steps to Reproduce
Upload a file using the` Folder.files.addChucked` method and try to afterwards fetch the item with the above mentioned code.

**Comment by patrick-rodgers** [comment]
Ya, this is definitely a bug. Merging a fix shortly.
