### ISSUE TITLE
Graph user's managers and direct reports

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/pnpjs#1590]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [latest]

### Question

How can I retrieve a user's manager and direct reports? Based on #790 these endpoints are implemented but I am not able to surface them. I tried both imports below without success:

```
import { graph } from '@pnp/graph';
import '@pnp/graph/users';
```

and 

`import { graph } from "@pnp/graph/presets/all";
`

I also searched the code for "directReports" but that didn't return anything.

In addition, how would I get the whole management chain? That would be the equivalent of `/me?$expand=manager`

Thank you!

**Comment by patrick-rodgers** [comment]
Looks like these might have gotten dropped in the move from v1 to v2, will add them back in.

**Comment by PathToSharePoint** [comment]
That was my guess, thanks Patrick!
