### ISSUE TITLE
Cannot query a column with internalname DisplayName

### ISSUE THREAD

**Issue by qlxh** [pnp/pnpjs#1593]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.11]

Please specify what version(s) of SharePoint you are targeting: [2016 on-premises]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*
Unfortunately this is the latest that works

### Expected / Desired Behavior / Question
A query on a list with a column "DisplayName" returns its data

### Observed Behavior
Column is not in result

### Steps to Reproduce
1. Create a list
2. Add a field with name DisplayName
3. Insert a few items in the list
4. Create a webpart with script to get all items from that list (see below)
5. Observe that DisplayName is not returned

```
const listName: string = 'name of your list';
const xml: string = '<View><ViewFields><FieldRef Name='DisplayName'/></ViewFields><Query><OrderBy><FieldRef Name="DisplayName" /></OrderBy></Query></View></Query></View>';

this.context.pageContext.web.lists.getByTitle(listName).getItemsByCAMLQuery({ 'ViewXml': xml }).then((items: any) => { 
    Logger.writeJSON(items);
}
```

**Comment by qlxh** [comment]
The code got lost. Here it is
```
const listName: string = 'name of your list';
const xml: string = '<View><ViewFields><FieldRef Name='DisplayName'/></ViewFields><Query><OrderBy><FieldRef Name="DisplayName" /></OrderBy></Query></View></Query></View>';

this.context.pageContext.weblists.getByTitle(listName).getItemsByCAMLQuery({ 'ViewXml': xml }).then((items: any) => { 
    Logger.writeJSON(items);
}
```

**Comment by patrick-rodgers** [comment]
Are you certain "DisplayName" is the internal name of the field? Did a quick test and it worked for me. I don't have the ability currently to test on 2016 easily so might need your help on some debugging here.

Do want to add that I see you are using version 1.3.11 and any fix we would do will be for version 2. Are you able to upgrade or blocked due to something in 2016?

**Comment by qlxh** [comment]
Yes, definitely certain the internal name was "DisplayName". The customer is a slow organization, they are just now moving to SP2016 and all I could find in any "documentation" is that pnpjs v2 is not compatible. I tried an upgrade to pnpjs v2, as gulp build (webpack) gives tons of errors like this:
```
./~/@pnp/sp/presets/core.js
Cannot find source file '../../../../../packages/sp/presets/core.ts': Error: Can't resolve '../../../../../packages/sp/presets/core.ts' in 'C:\Prj\[...]\node_modules\@pnp\sp\presets'
@ ./lib/webparts/[...]WebPart.js 46:13-44
./~/@pnp/logging/index.js
Cannot find source file '../../../../packages/logging/index.ts': Error: Can't resolve '../../../../packages/logging/index.ts' in 'C:\Prj\[...]node_modules\@pnp\logging'
@ ./lib/webparts/[...].js 47:16-39
```

Note: It is rare I've had such a poorly documented environment to work on (in my 30+ years of experience with professional software development). I understand it is mostly volunteers and the community that builds it, and it's all wonderful (when it works). And if it doesn't work?? 
I felt lost in the dark. I really had no clue where to look, even after spending several days searching for documentation of the build system (gulp, webpack), how to configure that, etc. So I hope all the great people out there spend just a little more time documenting their inventions and systems...

**Comment by juliemturner** [comment]
@qlxh -- I'm sorry you're having difficulty using the library and that you feel the documentation is so poor. If that's the case you do realize that you don't have to use the library at all, simply make the rest calls natively and you can circumvent it entirely. Here's a link to Microsoft's documentation on them: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service?tabs=http

**Comment by qlxh** [comment]
@juliemturner I feel equally lost in Microsoft's documentation ;-) It was definitely not meant as a complaint, but maybe just a little nudge for the great people buiding this all to spend a little bit more time on documentation.
PNPjs is much easier to use, so I like it a lot over plain native sp.

**Comment by qlxh** [comment]
@patrick-rodgers I forgot to mention that the DisplayName field is a calculated field (concatenates choice field, a space, and Title field). I'll just document this for the customer
