### ISSUE TITLE
Get AssociatedOwnerGroup in one call not working

### ISSUE THREAD

**Issue by EagleWizard28** [pnp/pnpjs#1594]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   **2.2.0**      ]

Please specify what version(s) of SharePoint you are targeting: [    **SharePoint Online**     ]

### Expected / Desired Behavior / Question
I'm trying to fetch the associated owners of a web as described in the documentation, in 1 call:
https://pnp.github.io/pnpjs/sp/webs/#associatedownergroup

```
const ownersGroup = await sp.web.associatedOwnerGroup();
const usersOneCall = await sp.web.associatedOwnerGroup.users();
const users = await sp.web.siteGroups.getById(ownersGroup.Id).users();
```

Retrieving the "users" works without a problem, by first fetching the ownersGroup. 
However using it in one call for "usersOneCall" gives me an error:

_Uncaught (in promise) TypeError: _pnp_sp_presets_all__WEBPACK_IMPORTED_MODULE_0__.sp.web.associatedOwnerGroup.users is not a function_

### Observed Behavior
Error is thrown in the line to fetch usersOneCall

### Steps to Reproduce
I started from a fresh SPFx project and included both the sp and graph 

```
"@pnp/graph": "^2.2.0",
"@pnp/sp": "^2.2.0",
```

Additionally I loaded all the presets to make sure that isn't the problem. 

`import {sp, SiteUsers } from "@pnp/sp/presets/all";`

I know the way of fetching is a bit changed from before, but considering the documentation I think this should work? 
Or am I missing something here?

**Comment by patrick-rodgers** [comment]
Seems to be a bug here, not sure what yet - thanks for reporting it will dig in.

**Comment by patrick-rodgers** [comment]
Wow, big miss here on our part. We were incorrectly assigning the `SiteGroups` factory instead of `SiteGroup`. Amazed no one hit this until now. Thanks again for reporting. Fixed and will be in the next release.

**Comment by EagleWizard28** [comment]
Thanks for the follow up and the fix @patrick-rodgers 👍🏻
