### ISSUE TITLE
sp.web.getFileByServerRelativeUrl().getItem() is trying to fetch item with wrong ID

### ISSUE THREAD

**Issue by EagleWizard28** [pnp/pnpjs#160]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

1.1.1

### Expected / Desired Behavior / Question
After removing a folder in a document library, containing a specific file. I want to be able to create the folder again and upload a file with the same name in this folder again, and be able to fetch the item by using the `sp.web.getFileByServerRelativeUrl().getItem()` method.

### Observed Behavior
When uploading a file to the folder it initially works. But when you remove the folder, recreate it again and upload the same file again, an error is thrown:

> https://tentant.sharepoint.com/sites/kb-KB20/_api/Web/Lists(guid'd59d2f62-5122-4cec-bc94-e6c473d11508')/Items(267) 404 ()

The item ID that is being used is not the correct one.

### Steps to Reproduce

1. In the standard "Documents" library, create a folder "A1"
`sp.web.getFolderByServerRelativeUrl().folders.add()`

2. Add a file "IT.png" to the folder ussing the addChunked method
`folder.files.addChunked()`

3. Retrieve the related item with the help of getFileByServerRelativeUrl method. Consider that I'm not using the `file.getItem()` method because of an issue that I registered here [getItem() after Folder.files.addChunked() gives 404 ](https://github.com/pnp/pnpjs/issues/159)
_To this point everything works as expected and the item is retrievable_
`sp.web.getFileByServerRelativeUrl().getItem()`

4. Manually select the created folder and delete the whole folder

5. Repeat steps 1 to 3

6. When tyring to fetch the item from the uploaded file. A 404 error is thrown while trying to fetch the item with a wrong ID.
> https://tentant.sharepoint.com/sites/kb-KB20/_api/Web/Lists(guid'd59d2f62-5122-4cec-bc94-e6c473d11508')/Items(267) 404 ()

### To take into consideration for finding a solution

When I remove the deleted folder also from the recycle bin and I repeat steps 1 to 3 again, it works again. So it seems while trying to fetch the item from URL, it still sees the item that is in the deleted folder in the recycle bin.

If I remember correctly, when removing a file or folder from a document library, these are still kept in the same location but can only be seen in the recycle bin. However the API should be able to handle this.
I'm not sure if this is actually a bug in pnp or in SharePoint itself.

**Comment by koltyakov** [comment]
Interesting one. Thanks for the detailed information, Mathieu. Will investigate this.

Connecting the issue with [this one](https://github.com/pnp/pnpjs/issues/159).

For me, it looks like an issue when constructing the uploaded file URL:

![image](https://user-images.githubusercontent.com/7816483/42310829-091b9366-8045-11e8-996e-4d4d16947307.png)

Yet, any amount of upload/recycle do not cause the same behavior for web.getFileByServerRelativeUrl, always a correct Id. Maybe that's because for quick tests I use SP Editor which still uses 1.1.0 will do the same research with latest versions.

**Comment by patrick-rodgers** [comment]
We have seen this before in exactly this scenario. There is a small amount of caching that is done on the server side and when you are deleting and immediately recreating the folder/file with the same name and path we get back the wrong ID. I am not sure there is a lot we can do on this one.

@EagleWizard28 - I understand you want to do this, but can you expand on why a bit? Perhaps we can come up with an alternative way to approach the problem.

**Comment by patrick-rodgers** [comment]
Going to close this one, but have merged a fix for #159 which should help. When I do testing I just create random file names to ensure I avoid any caching issues. The other option if you really need the file/folder names to be the same is to wait a bit before recreating them. You can test it out but as little as 30 seconds might be enough. Thanks!

**Comment by EagleWizard28** [comment]
Great! Thanks for the feedback @patrick-rodgers

**Comment by djef8012** [comment]
I have the exact same issue in an spfx webpart. Using web.getFileByServerRelativeUrl().getItem() , and from time to time, it gets me a wrong ID... a previous ID actually. I just uploaded a file with an the same name as one I deleted before, then I got the ID of the previous one in the web.getFileByServerRelativeUrl().getItem() (ID= 88) instead of the new generated ID (ID= 100). I don't really get the fix/solution you implemented?... Do you have a least a workaround? My pnpjs version in my SPFX solution is ^1.3.7. Thank you!

**Comment by koltyakov** [comment]
@djef8012, 

This is the caching issue, the API returns the same changed data for a path while the file location is the same.

If you absolutely know that it's a new file, e.g. a scenario a file is always uploaded with the same name, then being deleted and uploaded once again. You can add a unique parameter to a file path, like this:

```typescript
import { sp } from '@pnp/sp/presets/all';

(async () => {

  const item = await sp.web
    .getFileByServerRelativeUrl(`/sites/ci/Shared Documents/test.png#t=${new Date().toISOString()}`)
    .getItem();

  const { Id } = await item.get();

  console.log(Id);

})().catch(console.log)
```

**Comment by djef8012** [comment]
Thank you for the quick answer.
I tested the change you suggested but It says: The expression is not valid.
When I test directly the query using the rest api it says the same:
/sites/XXX/_api/web/getFileByServerRelativeUrl('/sites/XXX/Documents/test1.txt#t=2021-03-09T12:21:23.602Z')/ListItemAllFields
Am I missing something?

**Comment by koltyakov** [comment]
What's SharePoint version? It works in SPO. Let me check in On-Prem.

**Comment by djef8012** [comment]
On-prem - SharePoint 2019. Sorry that I forgot to mention that.

**Comment by koltyakov** [comment]
Maybe kind of hacky, this works for me in 2016:

```typescript
const file = sp.web.getFileByServerRelativeUrl(`/sites/ci/Shared Documents/test.png`);
file.query.set('t', new Date().getTime().toString()); // <-- forces unique Get path

const item = await file
  .select('ListItemAllFields/Id')
  .expand('ListItemAllFields')
  .get<{ ListItemAllFields: { Id: number }}>();

console.log(item.ListItemAllFields.Id);
```

Yet, I can't recall was query exposed as a public method in v1.

In old versions this approach might work:

```typescript
const item = await sp.web.getFileByServerRelativeUrl(`/sites/ci/Shared Documents/test.png`)
  .getItem(`Id,&t=${new Date().getTime()}`);
```
