### ISSUE TITLE
Cannot set default folder values with setDefaultColumnValues() - default values don't get set

### ISSUE THREAD

**Issue by TheShihan** [pnp/pnpjs#1601]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.2.0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
I want to set default folder values in a document library, so that files receive a specific term value automatically.

### Observed Behavior
No exception occurs, but the value is not set when I check with browser if the value is there.

### Steps to Reproduce
Basically I am using the approach that is also mentioned here: https://github.com/pnp/pnpjs/issues/1426
and documented here: https://pnp.github.io/pnpjs/sp/column-defaults/ (althought the last part of the document includes a "path", which I don't use (and cannot use) on folders:
```
            if (productTermWssId && productTermWssId > 0) {
              const folderPath: string = selectedListUrl + "/" + selectedFolderPath;
              const fieldInternalName = productTermFieldInternalName;
              const wssId = `${productTermWssId}`;
              const termName: string = productTerm.Name;
              const termId: string = productTerm.Id.replace('/Guid(', '').replace(')/', ''); // id must be passed as ID only, without '/Guid(' etc.
              const folderDefaultValues: IFieldDefaultProps[] =
              [{
                name: fieldInternalName,
                value:  {
                  wssId: wssId,
                  termName: termName,
                  termId: termId
                }
              }];
              await sp.web.getFolderByServerRelativePath(folderPath).setDefaultColumnValues(folderDefaultValues);
```
Example values are:
`folderPath:`
`'/sites/Products/NotesEbooks/PSC-Folder-Test-11'`
folderDefaultValues:
```
(1) [{…}]
name:'Product'
value:{wssId: '28', termName: 'PSC Folder Test 11', termId: 'e7bb135f-4992-4479-bbc3-095b4765da8a'}
```
As said `setDefaultColumnValues(...)` does not throw an exception. I also made sure the passed values are there, e.g. it threw an exception when I used a bad folderPath or the wrong internal name of the term field ('Product' is correct) for testing purposes.
The `termName`, `termId` and `wssId` are also correct. I also tried it with using "-1" as wssId, as mentioned in the documentation, but I get the same results (= value not set).

Does this still work for others, using version 2.2.0? What could be the issue here.

**Comment by patrick-rodgers** [comment]
Spent some time testing this morning and I am not able to repro what you report. Sharing my full test code below:

```TypeScript
import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/column-defaults";
import "@pnp/sp/taxonomy";

const term = await sp.termStore.sets.getById("{id}").getTermById("{id}")();
const defLabel = term.labels.find(v => v.isDefault);

await sp.web.lists.getByTitle("MetaDataDocLib").rootFolder.setDefaultColumnValues([{
    name: "MetaData",
    value: {
        wssId: "-1",
        termId: term.id,
        termName: defLabel.name,
    }
}])

const defaults = await sp.web.lists.getByTitle("MetaDataDocLib").getDefaultColumnValues();
```

Perhaps the name you are using isn't the default? I will add this exact example to the docs as well.

**Comment by TheShihan** [comment]
@patrick-rodgers what do you mean with default name? If I am using an alias label of the term? No, the term is created some seconds before this action and added to a page item (field). I create the term only with this (default) name.

But I will try it it your way again, with the defLabel approach anyway, maybe it's worth to give it a try. What I still don't get. The WssID in your example is (again) "-1". Does this mean we don't need to find the real WssID and can just always use "-1" for this method?

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
