### ISSUE TITLE
Getting a folder in a document library. 

### ISSUE THREAD

**Issue by ahyland** [pnp/pnpjs#1605]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.0.6  ]

Please specify what version(s) of SharePoint you are targeting: [ SPO ]

### Expected / Desired Behavior / Question
Currently development a react SPFx web part and I am trying to check if a folder exists in a library. I have tried the following code so far:

```
const folders = await sp.web.getFileByServerRelativeUrl("/sites/sitecol/doclib").select('Exists').get();`
const folders = await sp.web.getList("sites/sitecol/doclib").rootFolder.folders();
const folders = await sp.web.getList("sites/sitecol/doclib").rootFolder.folders.select("Name", "Exists").get();
```

None of the above are currently working, I am using Edge Chromium to test and I have for the following imports:

```
import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import { Folders, IFolder } from "@pnp/sp/folders";
```

Not sure if I am doing something wrong or this is a bug. 

### Observed Behavior
Currently when trying to run any of the above code I get the following in the console:

> TypeError: _pnp_sp__WEBPACK_IMPORTED_MODULE_5__.sp.web.getFileByServerRelativeUrl is not a function

**Comment by ahyland** [comment]
Apologies I got this working, I was using the incorrect import. Using the following got it working:

`import "@pnp/sp/folders/web";`

**Comment by juliemturner** [comment]
Awesome, glad you're all set.
