### ISSUE TITLE
Call of IContentType.fields() yields 404

### ISSUE THREAD

**Issue by xyz0815** [pnp/pnpjs#1606]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.1.1       ]

Please specify what version(s) of SharePoint you are targeting: [ online  ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Calling fields() on a valid IContentType should yield its fields.

### Observed Behavior
Error thrown: 404 (see screenshot for details)

### Steps to Reproduce
with ...tuProps.contentTypes being a IContentTypeInfo[]:

```
        console.log("CT-Id", this.properties.tuProps.contentTypes[0].Id.StringValue); 
        let ct: IContentType = sp.web.contentTypes.getById(this.properties.tuProps.contentTypes[0].Id.StringValue); // ok
        console.log("IContentType", ct);
        let ctFields =  await ct.fields(); // error 404
        console.log("Fields of CT " + this.properties.tuProps.contentTypes[0].Name, ctFields);

```
![ctfieldserr](https://user-images.githubusercontent.com/327665/108598664-33b5c480-738f-11eb-80d6-c1f1bb711061.png)

**Comment by koltyakov** [comment]
Doesn't look as a bug to me. It's expected getting 404 when providing a path to non-existent resources. So the API responses that a content type is not found.

I guess, the ID of a content type received from a CT from a list. To get the CT and its fields' the specific list's CT should be requested.

**Comment by xyz0815** [comment]
Hi Andrew,

your answer solved my problem, I actually could get the CT directly from the list.
I wasn't aware that there are list-dependent "instances" of CTs, since they are declared on site collection level.

Thank you very much!

Best Regards,
Markus
