### ISSUE TITLE
Verify if user is a Teams owner

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/pnpjs#1614]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Question

What would be the most reliable way to check if a user is owner of the current Teams team, using PnPjs? Or maybe there is a more relevant tool for the job?

This is what I have been using so far, I am just not sure if it covers all cases:
`const verifyOwner: boolean = await sp.web.currentUserHasPermissions(PermissionKind.ManagePermissions);
`

**Comment by juliemturner** [comment]
No that won't work for a "team" as the team site uses M365 Group as it's security construct, this endpoint only is going to work with communication sites that use SharePoint Groups for security.  See the Microsoft Graph for information about team owners -- https://docs.microsoft.com/en-us/graph/api/group-list-owners?view=graph-rest-1.0&tabs=http seems like the easiest way. Based on a quick scan of the code I don't think the PnPjs endpoint implemented owners yet.

**Comment by PathToSharePoint** [comment]
Thanks for the reply Julie.

Don't the group permissions still translate into SharePoint permissions? If I am not mistaken, the Teams owners automatically become owners of the associated SharePoint team site.

Thanks for the useful Graph link. I was just hoping I could sort this out without requiring custom Graph permissions.

**Comment by juliemturner** [comment]
Yes, they do but its the owners group that becomes a member, not the members of the owner groups... so you can't resolve an individual user that way, unless all you want to know is that X Team Owners is in the Owners group of the SharePoint site... doesn't seem useful, but maybe I don't understand your use case.

**Comment by PathToSharePoint** [comment]
Fair point about providing some context. I have a menu in my Client Side Web Part, with member actions and owner actions. If the current logged in user is not an owner, I want to hide or disable the menu items that are not relevant.

The Web Part can also be installed as a Teams tab.

**Comment by juliemturner** [comment]
Yeah, so based on that you need to resolve if a user is in the M365 group... can't do that with the SharePoint APIs

**Comment by PathToSharePoint** [comment]
okay, it seems that the Graph is the path forward... Thanks for the help Julie!
