### ISSUE TITLE
@microsoft/microsoft-graph-types/microsoft-graph.js has no exported member named 'SearchRequest'

### ISSUE THREAD

**Issue by karabaesh** [pnp/pnpjs#1615]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.2.0 ]

### Expected / Desired Behavior / Question

Usual compile when using the import statement:
import { graph } from '@pnp/graph/presets/all';

### Observed Behavior

Getting error when compiling:
Error: node_modules/@pnp/graph/search/index.d.ts:1:10 - error TS2724: '"../node_modules/@microsoft/microsoft-graph-types/microsoft-graph.js"' has no exported member named 'SearchRequest'. Did you mean 'SearchResult'?

Indeed @pnp/graph uses version 1.13.0 of @microsoft/microsoft-graph-types, which is an old version where is not an exported member. The current version @microsoft/microsoft-graph-types has the exported member. An update should solve this problem.

### Steps to Reproduce

Use of import statement:
import { graph } from '@pnp/graph/presets/all';

Thank you for your feedback!

**Comment by juliemturner** [comment]
We can look at this... but so you know version 2.2.0 of PnPjs imports version 1.30 of the typings... 

> "@microsoft/microsoft-graph-types": "^1.30.0",

see https://github.com/pnp/pnpjs/blob/main/package.json

**Comment by juliemturner** [comment]
Oh wait, I see... it's because you're using the `all` preset... yep, we can get that corrected.

If there's not a specific reason why you're using the present you might want to reconsider as it does bloat your code.
