### ISSUE TITLE
Packages are transpiled to ES2015 instead of ES5

### ISSUE THREAD

**Issue by marwankhalili** [pnp/pnpjs#1619]
### Category
- [x] Bug

### Version

Please specify what version of the library you are using: [^2.2.0]

### Expected / Desired Behavior / Question
The code should be transpiled to ES5. 

### Observed Behavior
The commit: a338584c10f00974b65121e3396236af16753c67 changed the target in `tsconfig.json` from ES5 to ES2015. This change was released in v2.1.0 and causes syntax errors in older browsers unless the installed package in node_modules is transpiled.

I could not find any documentation or other issues of this arguably breaking change so I assume the change was by mistake, hence the "Bug"-category.

In case someone else has the same issues, a temporary solution would be to transpile the `node_modules/@pnp` folder yourself, using e.g. babel-loader with webpack.

### Steps to Reproduce
- Run `npm i @pnp/odata@2.2.0`
- Check e.g. `invokable-extensions.js` and look for syntax that does not work in ES5
   - `less node_modules/@pnp/odata/invokable-extensions.js`

**Comment by patrick-rodgers** [comment]
Yep, that seems to have been an accident. Thanks for letting us know! Fixed in 2.3.0 scheduled to go out on March 12, 2021. Thanks!
