### ISSUE TITLE
Requests using wrong base URL despite being configured

### ISSUE THREAD

**Issue by JakeStanger** [pnp/pnpjs#1621]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.2.0]

Please specify what version(s) of SharePoint you are targeting: [SPO, SPFx 1.11.0]

### Expected / Desired Behavior / Question

I'm raising this as a question rather than a bug, as I think the problem lies outside of the library, but it's absolutely stumped me and I'm hoping somebody has a better idea of what's happening than I do.

All SharePoint API requests are failing with 404 as they're resolving the wrong URL (using `<SITE>/_layouts/15/` as the base instead of just `<SITE>`).

In my web part `onInit`, I'm calling
```ts
sp.setup({ spfxContext: this.context });
```

And then later on in another class:
```ts
import { sp } from '@pnp/sp';
import '@pnp/sp/webs';
import '@pnp/sp/site-users';
import '@pnp/sp/site-groups';

class UserService {
  ...
  public async getCurrentUser() {
    // outputs the correct URL, so we know the library is configured
    console.log((sp as any)._runtime._v.get('spfxContext').pageContext.web.absoluteUrl);

    // Fails with 404 because it is using the wrong URL  
    return await sp.web.currentUser
      .select('Id,Title,Email,UserPrincipalName')
      .get<IUser>();
  }
}
```

I've no idea where to begin with this one. As I said, I'm relatively confident it's not a bug with the library. Any ideas what sort of thing could cause this to happen?

**EDIT**
To add to this, I've done some further testing and it looks like straying from the `sp` singleton at all is causing the context to be set to `null`.

```ts
// logs spfx context object
console.log('sp', (sp as any)._runtime._v.get('spfxContext'));

// both log `null`
console.log('sp.site', (sp.site as any)._runtime._v.get('spfxContext'));
console.log('sp.web', (sp.web as any)._runtime._v.get('spfxContext'));
```

**Comment by JakeStanger** [comment]
I had `@pnp/odata@2.2.0` explicitly listed in my dependencies and removing it fixed the problem.

I presume this is an oddity with yarn, but I'd be interesting to know if you have any insight as to why it'd happen?

Feel free to close at any time.

**Comment by patrick-rodgers** [comment]
I don't have any idea what the issue might be, but glad things are working for you now. If you have some more trouble please let us know. Thanks!
