### ISSUE TITLE
_File.prototype.moveTo should not auto-overwrite

### ISSUE THREAD

**Issue by Mulando** [pnp/pnpjs#1623]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
[2.2.0]
[Sharepoint online]

### Expected / Desired Behavior / Question
If a file is moved via _File.prototype.moveTo, by default it should not be overwritten (destructible operation) instead it should lead to an error if a file with the same name does already exist (error with code -2130575257). Problem is also that the MoveOperations-Enum does not have such an option. Just "OverWrite" and "AllowBrokenThickets". Also an Option "None"=0 should be added.

Btw, the method does also not work with absolute URLs like mentioned in the description. It is only working with server-relative URLs (the MoveByPath on the other does only work with absolute URLs and not with relative URLs).

### Observed Behavior
When calling "MoveTo("url")" from a _File Object it overwrites any existing file in it's path.

### Steps to Reproduce
web.getFileByUrl(fileServerrelativeUrl).moveTo(newServerRelativeUrl)

**Comment by patrick-rodgers** [comment]
Thanks for reporting this @Mulando. We can't change the default behavior as it would be a breaking change, but your point is taken and we'll update it for v3 to use none as the default. We did add the missing flags so you can select the none option now. Update will go out in 2.3.0 scheduled for today March, 12, 2021. Thanks!
