### ISSUE TITLE
Trying to get page comment and like count

### ISSUE THREAD

**Issue by raymondlittle100** [pnp/pnpjs#163]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.1.1        ]

### Expected / Desired Behavior / Question
I'm trying to use getItemsByCAMLQuery to get a collection of pages and roll them up to display a list to the user. As part of this I'm trying to get the some OOTB fields to show information around comment count and likes. 

### Observed Behavior
Regardless of what values I put in the select properties or view field information I can't seem to get the field information. 

### Steps to Reproduce
First tried to set various versions of the hidden fields names using the code below but none of these worked.

**Code to execute query**
let itemLimit:string ="5"
      let viewXML:string = `<View><RowLimit>${itemLimit}</RowLimit></View>`;
      let results = await this.props.spRest.web.lists.getByTitle("Site Pages").select("Title, KIRA_CP_PageType, OData__LikeCount, OData__CommentCount").getItemsByCAMLQuery({
        ViewXml: viewXML
      });      

I tried various versions of the like count and comment count but nothing worked. I then used the code below to get the OData versions of the names. Even using these names doesn't work, any ideas?

**Code to get field names**
const fieldDetails = await this.props.spRest.web.lists
    .getByTitle('Site Pages')
    .fields
    .select('Title, EntityPropertyName')    
    .get();   
        
    console.log(fieldDetails.map(field => {
      return {
        Title: field.Title,
        EntityPropertyName: field.EntityPropertyName
      };
    }));

      console.log(results);

**Code to get field names result**
![image](https://user-images.githubusercontent.com/23637375/42576930-67f25336-851b-11e8-8b7a-d21b66777d0b.png)

**Data using CamlDesigner**
![image](https://user-images.githubusercontent.com/23637375/42576908-5a9bff2a-851b-11e8-8eda-40dc9bf2fa11.png)

**Comment by PavelAl** [comment]
Hello. I also worked with comments for pages in shrepoint online and here is my solution on sp pnp: 
```
sp.web.getList(`${siteurl}/SitePages/`.replace(/\/\//g, '/'))
      .items
      .getById(newsId)
      .comments
      .expand('replies')
      .get();
```
And for likes.
```
sp.web.getList(`${siteurl}/SitePages/`.replace(/\/\//g, '/'))
      .items
      .getById(newsId)
      .getLikedBy();
```
This would give you comments and as an array. To count comments it is nessesary to count replies thats why I expanded them. I was unable to find the way to get this counts with 1 query because there is no such property in SitePagesItem metadata and this forced me to take this data individualy for each page. Hope it would help.

**Comment by raymondlittle100** [comment]
@PavelAl there is a comments and likes count on a page list item so you should be able to access these directly, see screenshot in my issue. This uses CAML designer to execute a query and fetches the data which shows results coming back for these fields

**Comment by koltyakov** [comment]
OData `select` as well as other modifiers won’t work with `getItemsByCAMLQuery`. `getItemsByCAMLQuery` method has expand capabilities, yet not sure this would work with _CommentCount and _LikeCount. But you can try `renderListData` or `renderListDataAsStream`, these guys expose likes and comment coult if I’m not wrong.

**Comment by raymondlittle100** [comment]
@koltyakov thanks for the feedback I'll give it a try and see

**Comment by raymondlittle100** [comment]
@koltyakov just tried and works great. Thanks for this I'll look to switch to either of these methods. What are the advantages of each approach, is there one which is better than the other?

**Comment by raymondlittle100** [comment]
@koltyakov  another case of 10 different ways to do anyone thing in SharePoint
