### ISSUE TITLE
setDefaultColumnValues not applying to correct folders

### ISSUE THREAD

**Issue by AmonHouston** [pnp/pnpjs#1637]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.2.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
setDefaultColumnValues sets the default value of a folder provided in the getFolderByServerRelativePath function. 

### Observed Behavior
setDefaultColumnValues only sets metadata to the first folder that is created and not subsequent. 

### Steps to Reproduce
```
const result = await sp.web.getFolderByServerRelativePath("/sites/Design/Shared Documents/General/2016-2017")

.setDefaultColumnValues([{

            name: "DefaultColumn", // string column on the document library
            
            value: metadata, //variable with the folder name as the metadata value (2016-2016 for example)
          }

 ]);
```

I've hard-coded the relative path URL to point at the folder 2016 - 2017, but it continues to reapply the default metadata setting to the 2016-2016 folder. I've closed my browser, hard freshed etc and it continues to only apply to the first folder. 

When I navigate to the library default settings, only the 2016-2016 folder has the new icon:
![image](https://user-images.githubusercontent.com/34081746/110388381-ded0b880-80c7-11eb-938a-daefac3a759f.png)

If I remove the default value like so:
![image](https://user-images.githubusercontent.com/34081746/110388452-ff990e00-80c7-11eb-8a8a-760c2ad16f80.png)

It will then update to the next default metadata value that was set
![image](https://user-images.githubusercontent.com/34081746/110388502-16d7fb80-80c8-11eb-8ecf-aba54e9b4f2e.png)

**Comment by juliemturner** [comment]
Can you please try this with the library settings that use path in the payload and see if that does work:
https://pnp.github.io/pnpjs/sp/column-defaults/#pattern-for-setting-defaults-on-various-column-types

**Comment by AmonHouston** [comment]
> Can you please try this with the library settings that use path in the payload and see if that does work:
> https://pnp.github.io/pnpjs/sp/column-defaults/#pattern-for-setting-defaults-on-various-column-types

I did the following:

```
        const result = await sp.web.lists.getByTitle("Documents")
        .setDefaultColumnValues(
            [
                {
                    name: "DefaultColumn",
                    path: "/sites/Design/Shared Documents/General/2016-2017",
                    value: metadata,
                }
            ]
        );
```

And it still applied the metadata to the other folder 2016-2016 and not 2016-2017

**Comment by patrick-rodgers** [comment]
We'll have a look. I just tested this for another issue and things appeared to be working but will see.

**Comment by AmonHouston** [comment]
> We'll have a look. I just tested this for another issue and things appeared to be working but will see.

Would you be able to post the key bits of code that got it working for you? Maybe I missed a fundamental piece somewhere. 

Also, I've tried this code on two different site collections with the same issue. I've only run the code via gulp serve however. I'm going to try pushing the code properly as well as trying a new tenant to see if the issue still occurs.

**Comment by patrick-rodgers** [comment]
From a current [open issue](https://github.com/pnp/pnpjs/issues/1601#issuecomment-785135814)

**Comment by AmonHouston** [comment]
> From a current [open issue](https://github.com/pnp/pnpjs/issues/1601#issuecomment-785135814)

Ah, that code is for setting it at the root folder level. I'm wanting each folder to have metadata. 

Also, as of this morning I had two weird things happen. 

The following code will add the correct metadata to the correct folder in the document library, but it would remove the default values from other folders in the same document library. Seemingly only allowing 1 folder to have default metadata. 

```
    private async addDefaultMetadata(folder : string, metadata : string) : Promise<any>{
        const result = await sp.web.lists.getByTitle("Documents")
        .setDefaultColumnValues(
            [
                {
                    name: "DefaultColumn",
                    path: `${this.state.generalFolderRelativeURL}/${folder}`,
                    value: metadata,
                }
            ]
        );
        return result;
    }

```


The following code reverted it back to only applying metadata to a specific folder and not the one i'm passing through on the getFolderByServerRelativePath function. 
```
  private async addDefaultMetadata(folder : string, metadata : string) : Promise<any>{
        const result = await sp.web.getFolderByServerRelativePath(`${this.state.generalFolderRelativeURL}/${folder}`)
        .setDefaultColumnValues(
            [
                {
                    name: "DefaultColumn",
                    value: metadata,
                }
            ]
        );
        return result;
    }
```

**Comment by AmonHouston** [comment]
As another test, I've tried the following

- Manually set the default field of a folder via the UI 
- Send request setting the defaults for numerous folders at once like so:


```
    private async addDefaultMetadata(folder : string, metadata : string) : Promise<any>{
        const result = await sp.web.lists.getByTitle("Documents")
        .setDefaultColumnValues(
            [
                {
                    name: "DefaultColumn",
                    path: `${this.state.generalFolderRelativeURL}/${folder}`,
                    value: metadata,
                },
                {
                    name: "DefaultColumn",
                    path: `${this.state.generalFolderRelativeURL}/2021-2021`,
                    value: `2021-2021`,
                },
                {
                    name: "DefaultColumn",
                    path: `${this.state.generalFolderRelativeURL}/2020-2020`,
                    value: `2020-2020`,
                }
            ]
        );
        return result;
    }
```

This ended up with the manually set value on the 2020-2020 folder disappearing and only the 2019-2019 (the latest created folder) having metadata. 

Another note is that I have default metadata on another column that is library specific and that information holds. 
![image](https://user-images.githubusercontent.com/34081746/110538023-5c5bfd80-8188-11eb-8aed-cf97fcb31cf4.png)

**Comment by AmonHouston** [comment]
For anyone else who stumbles across this error (until its fixed 😊 )here is the process I've done to get around this for now:

- There is a hidden file in the forms folder in the document library called client_LocationBasedDefaults.html
- This is the file that holds the metadata defaults for all the files. 
- If this file exists, I just append the content thats in the folder with my new default content. Note: The capitalization of the Elements and the %20 in the URL in the file content is key to making it work. 
- If the file does not exist, I use the pnpjs folder defaults to create the file, then any subsequent updates I append directly to the folder itself. 
- The reason for this step is that if I try to create the file directly myself, it doesn't trigger the applying of default metadata when uploading a file. I think an event listener is missing when I do it, but not when pnpjs does.
