### ISSUE TITLE
"Failed to fetch"  on  .files.addChunked(...) 

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#1640]
is there a way to prevent "Failed to fetch" errors?

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.0.13  ]

Please specify what version(s) of SharePoint you are targeting: [ SPO ]

### Expected / Desired Behavior / Question
 .files.addChunked(...) should always work

### Observed Behavior

Some users sometime get the error "Failed to fetch" 

Thank you for your help!

**Comment by patrick-rodgers** [comment]
Can you please provide full repro steps? There is no way we can diagnose this given the information provided. Thanks!

**Comment by patrick-rodgers** [comment]
Going to close this due to lack of details. Please open a new issue with sufficient detail for us to review if you are still having trouble. Thanks!
