### ISSUE TITLE
Getting error when updating multi-value metadata field

### ISSUE THREAD

**Issue by gauravgoyal5** [pnp/pnpjs#1645]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version 

Please specify what version of the library you are using: [  2.3.0       ]

Please specify what version(s) of SharePoint you are targeting: [  SharePoint Online  ]

### Expected / Desired Behavior / Question
I am using PnPJS 2.3.0 updated code to update multi-value metadata field :

```TypeScript
await list.items.getById(itemId).update({
"My_x0020_Metadata_x0020_2": "-1#;Accountant|70edea16-6811-4e4f-ac27-8f1c567ad01e;#-1#;Designer|302dcafd-c992-4688-9f56-5e30c7e74b86;#-1#;Developer|7a139032-0898-4268-8917-64db96397d43;#-1#;Director|f1764c7b-f8b9-4fc0-a061-5f9403382311;#"
});
```

Another code also :
```TypeScript
await list.items.getById(itemId).update({
"My_x0020_Metadata_x0020_2": "Accountant|70edea16-6811-4e4f-ac27-8f1c567ad01e;Designer|302dcafd-c992-4688-9f56-5e30c7e74b86;Developer|7a139032-0898-4268-8917-64db96397d43;Director|f1764c7b-f8b9-4fc0-a061-5f9403382311;"
});
```

### Observed Behavior
it is throwing error :
```
error Error: Error making HttpClient request in queryable [400] ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"An unexpected 'PrimitiveValue' node was found when reading from the JSON reader. A 'StartObject' node was expected."}}}
```

### Steps to Reproduce
Create a SPFx Webpart Solution.
Add PnP JS V2.3.0
Run this code

**Comment by Tanddant** [comment]
You're submitting a string, not multiple values - PnPjs dosen't change your submitted values, it just wraps the rest API

You should use:
```
await list.items.getById(itemId).update({
"My_x0020_Metadata_x0020_2": {results: ["-1#;Accountant", "70edea16-6811-4e4f-ac27-8f1c567ad01e;#-1#;Designer", "302dcafd-c992-4688-9f56-5e30c7e74b86;#-1#;Developer", "7a139032-0898-4268-8917-64db96397d43;#-1#;Director", "f1764c7b-f8b9-4fc0-a061-5f9403382311;#"]}
});
```

The exception you get helps a bit:

"An unexpected 'PrimitiveValue' node was found when reading from the JSON reader. A 'StartObject' node was expected."
"Hey, I got a PrimitiveValue (string, number, bool and so on) what I was expecting was a JSON object, please provide that"


For more context on how SharePoint rest handles multivalue fields:
https://sharepoint.stackexchange.com/questions/83396/sp-2013-updating-a-multi-value-lookup-field-via-the-rest-api

**Comment by gauravgoyal5** [comment]
Hi,

I have made changes as per your suggestion, but still I am getting same error.

await list.items.getById(itemId).update({
"My_x0020_Metadata_x0020_2": {results: ["**-1#;Accountant**", "**70edea16-6811-4e4f-ac27-8f1c567ad01e;#-1#;Designer**", "**302dcafd-c992-4688-9f56-5e30c7e74b86;#-1#;Developer**", "**7a139032-0898-4268-8917-64db96397d43;#-1#;Director**", "**f1764c7b-f8b9-4fc0-a061-5f9403382311;#**"]}
});

I have made bold the values. I think these values are not in proper format. Can you let me know what should be the format of values?

I followed these solutions as well, but no luck :-
[Solution1](https://simonagren.github.io/pnpjs-update-managed-metadata/)
[Solution2](https://github.com/pnp/pnpjs/issues/355)
[Solution3](https://blog.aterentiev.com/how-to-easily-update-managed-metadata)
[Solution4](https://medium.com/@eitvydastamoinas/working-with-managed-metadata-using-sharepoint-rest-with-pnp-js-ea10c3302c5a)


Thanks,
Gaurav Goyal

**Comment by Tanddant** [comment]
What is the field type of the field you're trying to set?

**Comment by gauravgoyal5** [comment]
Field type is Managed Metadata 
![image](https://user-images.githubusercontent.com/6926513/111905347-2fa1c300-8a71-11eb-8578-077d8f49aea5.png)

**Comment by patrick-rodgers** [comment]
Hi @gauravgoyal5,

I went ahead and did the research on how to do this for you, here is what I found. Based on [this excellent article](https://www.aerieconsulting.com/blog/update-using-rest-to-update-a-multi-value-taxonomy-field-in-sharepoint) from Beau Cameron (@bcameron1231).

As he says you must update a hidden field to get this to work via REST. My meta data field accepting multiple values is called "MultiMetaData".

```TypeScript
import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/fields";

// first we need to get the hidden field's internal name.
// The Title of that hidden field is, in my case and in the linked article just the visible field name with "_0" appended.
const fields = await sp.web.lists.getByTitle("TestList").fields.filter("Title eq 'MultiMetaData_0'").select("Title", "InternalName")();

// now we have to create an update object
// to do that for each field value you need to serialize each as -1;#{field label}|{field id} joined by ";#"

// get an item to update, here we just create one for testing
const newItem = await sp.web.lists.getByTitle("TestList").items.add({
  Title: "Testing",
});

// update with the values you want, this also works in the add call, but you asked about updating
const updateVal = {};
Reflect.defineProperty(updateVal, fields[0].InternalName, {
  value: "-1;#New Term|bb046161-49cc-41bd-a459-5667175920d4;#-1;#New 2|0069972e-67f1-4c5e-99b6-24ac5c90b7c9"
});

// execute the update call
await newItem.item.update(updateVal);
```

P.S. If you have a question, please mark is as a question and not a bug. Choosing bug doesn't get a higher priority and if it turns out to be a bug we can always update the tags. Thanks!

**Comment by bcameron1231** [comment]
Thank you for the tag @patrick-rodgers.  There is also another method using the ValidateUpdateListItem endpoint, which is a cleaner approach.

See below. Where my column is called MMD. 

```
  const item = await sp.web.lists.getByTitle('Demo').items.getById(2).validateUpdateListItem([{
    FieldName: "MMD",
    FieldValue: "HR|02cf219e-8ce9-4e85-ac04-a913a44a5d2b;IT|247543b6-45f2-4232-b9e8-66c5bf53c31e",
  }]);
```

@gauravgoyal5  Just be aware of some of the nuances for ValidateUpdateListItem, such as not creating item versions for the update.

**Comment by patrick-rodgers** [comment]
Awesome, that's even better -- Thanks for sharing!
