### ISSUE TITLE
Setup VS Code + Intellisense + use the correct package

### ISSUE THREAD

**Issue by masterl1983** [pnp/pnpjs#165]
### Category
- [ ] Enhancement
- [ ] Bug
- [ x] Question
- [ x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.1.2]

### Expected / Desired Behavior / Question
As pnp-js-core is now deprecated it is now time for me to move to the new library. I am not a "real" developer so my question might be silly - please excuse. I am not working with Sharepoint-Frameword neither do I use TypeScript yet. I am working with plain JavaScript and Content-Editor Webparts for my solution.

Could you guide me through the setup process so that I can use the new library? I am using Visual Studio Code - I have created a new project (folder) --> Whats next?

I know where I could download the JavaScript File (https://unpkg.com/@pnp/pnpjs@latest/dist/).
Questions: 

1. How do I get IntellisSense to work? 
2. Should I use the package pnpjs or sp?

**Comment by koltyakov** [comment]
@masterl1983, 

I would:

- encourage you to invest into TypeScript on a long run, it worth it, I promise!
- recommend installing the dependency as `node_module` via `npm`, this is required for typings support.
- recommend using `@pnp\pnpjs` at first as it mimics `sp-pnp-js` and simpler to start with without thinking of peer dependencies, anyways, please check the [install notes](https://pnp.github.io/pnpjs/getting-started.html#install).
- when using node modules and having the packages installed you can add `//@ts-check` at the beginning of your JS files, this adds IntelliSense and typing support in ordinary JavaScript's.
- if it's an ordinary CEWP development and SPFx can't be used in your project for some reasons I can also recommend taking a look at [sppp](https://github.com/koltyakov/generator-sppp) - the generator for `pre-SPFx-solutions`, yet it's also for modern JS which is compiled to ES5 and bundled and involve build tools, but a good news is that all the tasks are built in.

And, btw, we have PnPjs published to CDN - https://cdnjs.com/libraries/pnp-pnpjs.
