### ISSUE TITLE
stream.readable and addChunked

### ISSUE THREAD

**Issue by ckersic** [pnp/pnpjs#1656]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.2.0     ]

Please specify what version(s) of SharePoint you are targeting: [    2016     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

Question
Is it possible to use the addChunked method with a stream.Readable object? if so, do you have some sample code.

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
