### ISSUE TITLE
SPFx Retrieve list items from another site collection - 403 Error making HttpClient request in queryable

### ISSUE THREAD

**Issue by MarkuZI95** [pnp/pnpjs#1658]
Hi Team,

- [ ] Enhancement
- [ ] Bug
- [ x] Question (probably Bug?)
- [ ] Documentation gap/issue

Environment:
@pnp/sp v 2.3.0
SharePoint Online

ErrorMessage:
Error making HttpClient request in queryable [403]  ::> {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"de-DE","value":"Zugriff verweigert. Sie haben keine Berechtigung, diesen Vorgang auszuf\u00fchren oder auf diese Ressource zuzugreifen."}}

Desired behavior:
In SPFx webpart, i want to retrieve list items from a list in **another site collection**. 
Current User is a SharePoint Admin and has FullControl access to both SiteCollections. 

Additional Information:
Browser Network Tab:
![image](https://user-images.githubusercontent.com/71842494/111795244-4ad0cf00-88c7-11eb-9268-925ad9670535.png)
![image](https://user-images.githubusercontent.com/71842494/111795481-879cc600-88c7-11eb-89f3-614b6a7a5dbd.png)

Also tried with switching property **isDomainIsolated** = true & false.
**Running webpart with gulp serve --> Everything works as desired. Error only appears after deploying webpart to appcatalog + add to page .**

My code i try to run (i know i could directly get item without await getting list before, but i need list afterwards.).

```
protected async onInit(): Promise<void>
{
    await super.onInit();

    sp.setup(this.context);

    var web = Web("URLSiteCollection2");

    var list : IList = web.lists.getByTitle("ListTitle");

    var item : IItem = list.items.getById(ItemIDInt);

    var webProps: IWebInfo = await web.get();
}
```

Also tried with:

```
sp.setup({
      spfxContext: this.context
    }); 
```

Any ideas/suggestions what i am doing wrong or what i can try?
Is this even supposed to work?
If you need more details feel free to ask.

Any help is appreciated.

Thanks
Markus

**Comment by MarkuZI95** [comment]
Ok, for any reason its working now. I realized a change in referer/origin Request Header. Its without -app{ID} now but im 100% sure i deployed the webpart like 30 times with isDomainIsolated=false. 

Does anyone know why it suddenly works? 
Is the isDomailIsolated chached or does this even effect the sent Request Headers? Why are my headers changed?

**Comment by patrick-rodgers** [comment]
I have no idea what might have changed, and I am not sure it would be related to this library? Hard to say without a solid repro. We don't cache things automatically, possible the browser cached something. Are you OK if we close this and can revisit if it comes up again?

**Comment by MarkuZI95** [comment]
I agree - this might not be a problem with this library and this can be closed. 

Anyway if anyone else have to face the described error: 
make sure your webpart property isDomainIsolated is set to false if you want to make cross site calls and additionally ensure in your browsers network tab that your request headers "Origin" & "Referer" are your original SharePoint Site/Web Url WITHOUT any -app{ID]. Atleast thats what i observed. 

If anyone got an explanation for the described behavior, please post it.

**Comment by patrick-rodgers** [comment]
Thanks, going to close - if you run into more trouble please do open a new issue so we can work on helping out. Thanks!
