### ISSUE TITLE
Getting optional Person field does not work as expected

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#1664]
### Category
- [ ] Enhancement
- [?] Bug (Maybe I am doing it wrong)
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.3   ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question

`const otherUser: any = await w.lists.getByTitle("DPC-Job-Master").items.getById(920).expand("CurrentAssignedTo").select("CurrentAssignedTo/EMail");`
Should return the same as the 
`https://mycompany.sharepoint.com/sites/dpc/_api/lists/getbytitle('DPC-Job-Master')/items(920)?$expand=CurrentAssignedTo&$select=CurrentAssignedTo/Title,CurrentAssignedTo/EMail
`
either {} if ther is no CurrentAssignedTo or
```
{
  "CurrentAssignedTo": {
    "Title": "Eric Kang",
    "EMail": "EKang@mycompany.onmicrosoft.com"
  }
}
```

### Observed Behavior

otherUser.data has everything but the Title or the EMail
I also tried 
`const otherUser: any = await w.lists.getByTitle("DPC-Job-Master").expand("CurrentAssignedTo").select("CurrentAssignedTo/EMail").items.getById(job.ItemId);`

same results.
Maybe I am looking for the results wrong?

### Steps to Reproduce

Thank you for your help!

**Comment by koltyakov** [comment]
Hey @Ofer-Gal,

In your PnPjs core I can't see any `CurrentAssignedTo/Title` selection? Why you're expecting it being in results?

After constructing a request PnPjs sends it to the same REST API, so there should be no difference in behaviour. If you comparing a response from a Postman or something please check that OData modes are the same.

**Comment by Ofer-Gal** [comment]
Sorry it actually 
`const otherUser: any = await w.lists.getByTitle("DPC-Job-Master").expand("CurrentAssignedTo").select("CurrentAssignedTo/EMail,CurrentAssignedTo/Title").items.getById(job.ItemId);`

I am only interested in the CurrentAssignedTo/EMail though

**Comment by patrick-rodgers** [comment]
Hi @Ofer-Gal - The following works for me, please review your code and note the misposition of the ".items.getById" pieces.

```
const w = await sp.web.lists.getByTitle("UserFieldList").items.getById(1).expand("User1").select("User1/EMail")();
```

**Comment by Ofer-Gal** [comment]
Thanks!
The extra () at the end helped too. :-)
