### ISSUE TITLE
Site Groups - Get Owner

### ISSUE THREAD

**Issue by arunkumaryoyo** [pnp/pnpjs#1668]
### Category

- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.2.0     ]

Please specify what version(s) of SharePoint you are targeting: [    SharePoint Online     ]

### Expected / Desired Behavior / Question
A method under SiteGroups to get the owner of the Group, if its an individual or a SiteGroup itself

### Observed Behavior
The service to get the Site Group Owner is not included in the solution. Also the REST API to get the Site owner is broken. It works only if the Group Owner is a SiteGroup.
/_api/web/SiteGroups/GetByName('[[GROUP NAME]]')/owner

### Steps to Reproduce
Replace [[SITE URL]] and [[GROUP NAME]] with actual values and navigate to the below URL
[[SITE URL]]/_api/web/SiteGroups/GetByName('[[GROUP NAME]]')/owner

If the Group owner is an individual, you will see "Unknown Error" error.
If the Group owner is another SiteGroup, you will get proper response.

Thanks in advance,
-- Arun

**Comment by koltyakov** [comment]
Why not to select an Owner?

```typescript
await sp.web.siteGroups.getByName(groupName)
  .select('Owner').expand('Owner').get()
```

**Comment by arunkumaryoyo** [comment]
I tried the same code and ended up with the same error.

Please follow this scenario,

- Create a Group in SharePoint Online,
- Make the owner of the Group as an Individual
- Access the api/pnp code that you suggested above to get the owner

-- Arun

**Comment by arunkumaryoyo** [comment]
> This is likely due to the different principal types that can be assigned as owner. You can get the group details:
> 
> ```
> const groupInfo = await sp.web.siteGroups.getByName("TestGroup")();
> ```
> 
> Or you can get the Owner user details:
> 
> ```
> const userOwnerDetails = await sp.web.siteGroups.getByName("TestGroup").expand("Owner").select("Owner/Email", "Owner/Title")();
> ```
> 
> Edit:
> 
> This query may allow you to make the determination on what type of principal is assigned as the PrincipalType field is common. [Listing of principal types and values](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.utilities.spprincipaltype?view=sharepoint-server).
> 
> ```
> const userOwnerDetails = await sp.web.siteGroups.getByName("TestGroup").select("Owner/PrincipalType").expand("Owner")();
> ```

Thanks. This works.. 😊😃
