### ISSUE TITLE
if Person/EMail is empty, rest call fails

### ISSUE THREAD

**Issue by joshburns49** [pnp/pnpjs#1669]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     2.0.0    ]

### Expected / Desired Behavior / Question
Use rest api to get Person/EMail and Person/Title

### Observed Behavior
rest api call fails if user doesn't have an email address

I have seen a few people have raised bugs/questions about this but not since 2019 so i am wondering if there has been any updates around this? 

Cheers

Josh

**Comment by koltyakov** [comment]
Unfortunately, it is REST API issue in SharePoint and can't be fixed in the library. The workaround is using renderListDataAsStream I guess.

**Comment by patrick-rodgers** [comment]
Can you share the code you are using to execute the request?

**Comment by joshburns49** [comment]
Hi Patrick,

This is code that we are using to get the list items

`const shoutOuts = await sp.web.lists
        .getById(this.properties.listId)
        .items
        .select(
          'Kind', 'Message', 'Person/EMail', 'Person/Title',
          'Submitter/Title', 'Created'
        )
        .expand('Person', 'Submitter')
        .orderBy('Created', false)
        .top(this.pageSize)
        .getPaged();

      this.allShoutOuts = shoutOuts.results;`

Cheers 

Josh

**Comment by patrick-rodgers** [comment]
Thanks Josh, and what is the error you are getting?

**Comment by joshburns49** [comment]
Hey, 

its something similar to the message below.

Uncaught (in promise) Error: Error making HttpClient request in queryable [500] ::> {"odata.error":{"code":"-2146232832, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"Cannot get value for projected field person_x005f_EMail."}}}

Cheers

Josh

**Comment by joshburns49** [comment]
ok, thanks @patrick-rodgers  :)
