### ISSUE TITLE
sp.profiles.clientPeoplePickerResolveUser throws an error: Index was out of range. Must be non-negative and less than the size of the collection Parameter name: index

### ISSUE THREAD

**Issue by truespinmice** [pnp/pnpjs#1675]
### Category
- [ ] Enhancement
- [x ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.3 ]

Please specify what version(s) of SharePoint you are targeting: [  SPO ]

### Expected / Desired Behavior / Question
clientPeoplePickerResolveUser  should return something

### Observed Behavior
clientPeoplePickerResolveUser  returns 400:
_api/sp.ui.applicationpages.clientpeoplepickerwebserviceinterface.clientpeoplepickerresolveuser

TESTED ON 2 DIFFERENT TENANTS!!!

{"odata.error":{"code":"-2146233086, System.ArgumentOutOfRangeException","message":{"lang":"en-US","value":"Index was out of range. Must be non-negative and less than the size of the collection.\r\nParameter name: index"}}}

### Steps to Reproduce
try to call:
let queryString = "example_email_address_of_the_user"; //you can use any query string here, the error will be the same
await sp.profiles.clientPeoplePickerResolveUser({
        AllowEmailAddresses: true,
        AllowMultipleEntities: false,
        MaximumEntitySuggestions: 1,
        QueryString: queryString
      });

**Comment by emilALX** [comment]
I have the same issue!!!

**Comment by lukaszorso** [comment]
Unfortunately, the same on my end!

**Comment by truespinmice** [comment]
adding:
        PrincipalSource: PrincipalSource.All,
        PrincipalType: PrincipalType.All,

      let ret = await sp.profiles.clientPeoplePickerResolveUser({
        AllowEmailAddresses: true,
        AllowMultipleEntities: false,
        MaximumEntitySuggestions: 1,
        QueryString: queryString,
        PrincipalSource: PrincipalSource.All,
        PrincipalType: PrincipalType.All,
      });

solve the problem.

Damn, why this was working till Yesterday???? And why these params are not mentioned in the doc:
https://pnp.github.io/pnpjs/sp/profiles/

:(

**Comment by koltyakov** [comment]
Looks as a server side API-dependent update. In SP Metadata (edmx) which I collect automatically I can see a change committed 6 hrs ago.
Though nothing seems to be changed in `SP.UI.ApplicationPages.`... endpoint schema wise.

Can also confirm that without `PrincipalSource` and `PrincipalType` it fails now on my SPO tenant. But works when provided. Can't say have it been working previously without principals as I mostly have always provide these in the code.

**Comment by truespinmice** [comment]
Hi @koltyakov  thanks for confirmation. So it's not only on my end :)
