### ISSUE TITLE
PnP Js for SPFx Onpremises

### ISSUE THREAD

**Issue by joaosilva2313** [pnp/pnpjs#168]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     latest    ]

### Expected / Desired Behavior / Question
What is the version to use with sharepoint onpremises. I have errors while runing gulp bundle for onpremises webpart

**Comment by patrick-rodgers** [comment]
What are the errors you are getting?

**Comment by patrick-rodgers** [comment]
This issue #170 may also help you, though you didn't provide much information so I am just guessing.

**Comment by patrick-rodgers** [comment]
Going to close this due to lack of details. If you can provide further details and the linked details above don't help, please _reopen_ the issue so we can assist. Thanks!
