### ISSUE TITLE
.files.add( errors with "The attempted operation is prohibited because it exceeds the list view threshold."

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#1680]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.3.0   ]

Please specify what version(s) of SharePoint you are targeting: [  SPO   ]

### Expected / Desired Behavior / Question
`web.getFolderByServerRelativeUrl(someurl).files.add(fileName, fileBlob, true) `
Should add to a library regardless of the current number of files

### Observed Behavior
"message":{"lang":"en-US","value":"The attempted operation is prohibited because it exceeds the list view threshold.

I have seen here and figured out how to get files by limiting the `.top(4999)` but what should I do when adding files?

Thank you much

**Comment by Ofer-Gal** [comment]
Managed To solve part of the problem.
`web.getFolderByServerRelativeUrl(someurl).files.top(10).add(fileName, fileBlob, true)`
Does not error
But then I need to publish and
`web.getFileByServerRelativeUrl(someurl + fileName).publish("Replace Existing File").top(1);`
Errors: getFileByServerRelativeUrl(...).top is not a function
and
`web.getFileByServerRelativeUrl(someurl + fileName).top(1).publish("Replace Existing File");`
Errors:.getFileByServerRelativeUrl(...).top is not a function

Also, I need the ID of the new file but
`const item: any = await uFile.file.getItem();`
Errors "The attempted operation is prohibited because it exceeds the list view threshold."
puting `.top(1)` anywhere was an error by typescript 

Any idea how to solve this?

**Comment by juliemturner** [comment]
I don't get why you would call top on getFileByServerRelativeUrl... by definition that should only return 1 item.

**Comment by Ofer-Gal** [comment]
@juliemturner because `web.getFolderByServerRelativeUrl(someurl).files.add(fileName, fileBlob, true)` errored with 

> "The attempted operation is prohibited because it exceeds the list view threshold"

 and adding `.top(10)` worked even though it makes no sense either.

Apparently the same (makes no sense) fix, did not help  `.publish("Replace Existing File")` and .`file.getItem()`
They error with 

> "The attempted operation is prohibited because it exceeds the list view threshold"

 
Are the answers: 
> "You can't publish when you have more than 5000 files"  
> "you can't get the Item Id with .file.getItem()"

There must be a way to do these actions when you have more than 5000 files in a library. No?

**Comment by juliemturner** [comment]
My comment was only on this command...
`web.getFileByServerRelativeUrl(someurl + fileName).publish("Replace Existing File")`..
top(1) there is redundant so take it off and try it.

**Comment by Ofer-Gal** [comment]
web.getFileByServerRelativeUrl(someurl + fileName).publish("Some Text") errors with

> "The attempted operation is prohibited because it exceeds the list view threshold"

with the results of
`uFile: IFileAddResult  = await projectWebSite.getFolderByServerRelativeUrl(someurl ).files.top(10).add(....`

That works because of .files.top(10)
I do 
`const item: any = await uFile.file.getItem();`
which fails with:
> "The attempted operation is prohibited because it exceeds the list view threshold"

so the question remains:
How does one deal with publish and getItem when there are more than 5000 in SPO library?
If I use SharePoint's UI, it does let me add files and publish them no?

**Comment by juliemturner** [comment]
I would suspect it's done with the list item id... but I can't say that I know the answer to this. It would take some research.

Have you tried getting a list item and then the file from that?

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
