### ISSUE TITLE
How to add pages / web-part zones / web-parts programmatically in SharePoint online using PnP JS?

### ISSUE THREAD

**Issue by BhattMeet98** [pnp/pnpjs#1683]
I have created pages then added web-part zones / web-parts programmatically using the below function,

```
function addWebPart(webUrl, pageUrl,webPartXml,zoneId,zoneIndex, Success,Error){
var context = new SP.ClientContext(webUrl);
var web = context.get_web();

var file = web.getFileByServerRelativeUrl(webUrl + pageUrl);
var webPartMngr = file.getLimitedWebPartManager(SP.WebParts.PersonalizationScope.shared);
var webPartDef = webPartMngr.importWebPart(webPartXml);
var webPart = webPartDef.get_webPart();
webPartMngr.addWebPart(webPart, zoneId, zoneIndex);

context.load(webPart);
context.executeQueryAsync(
  function() {
    Success(webPart);
  },
  Error
);
```

Now, I need to create a page then add web-part zones / web-parts programmatically in SharePoint online using PnP JS.

Can anyone help me with the same?

Thanks in Advance.

**Comment by patrick-rodgers** [comment]
Hi @BhattMeet98 - that code isn't related to PnPjs rather you are using the [official JS SDK](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-javascript-library-code-in-sharepoint). As such we can't really provide support.

IF you are asking how to accomplish the same thing in PnPjs - the answer is that you can't for classic pages. There is poor REST API support for classic pages so we aren't able to offer the same level of functionality. There is [very limited support](https://github.com/pnp/pnpjs/blob/version-2/packages/sp/webparts/types.ts) to perform some basic actions - but largely we haven't found it useful.

For modern pages we have [an implementation](https://pnp.github.io/pnpjs/sp/clientside-pages/) on top of the non-public and unofficial api you can have a look at using.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
