### ISSUE TITLE
Folder.MoveTo results in 403

### ISSUE THREAD

**Issue by Bo4711** [pnp/pnpjs#1686]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 
@pnp/nodejs-commonjs
@pnp/sp-commonjs
^2.2.0

Please specify what version(s) of SharePoint you are targeting:
SO Online

### Expected / Desired Behavior / Question
Trying to move a folder within one library from
/sites/site1/library/folder1 to
/sites/site1/library/subfolder/folder1

Using App-Only Permissions defined in site.
Script is executed in NodeJS code

### Observed Behavior
Gettings a 403 Error
{ Error: Error making HttpClient request in queryable [403] Forbidden ::> {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}

Same approach for files works without issues.
**Also I was able to execute the same code in SPFX Webpart in Browser without issues.**

Interesting part:
In the error response the root site instead of site1 is mentioned (for which the app-only id indeed has no access):
url: https://xxx.sharepoint.com/_api/contextinfo
status: 403,

### Steps to Reproduce
```
import { SPFetchClient } from "@pnp/nodejs-commonjs";
import { sp, Web } from "@pnp/sp-commonjs";

sp.setup({
  sp: {
    baseUrl: "https://xxx.sharepoint.com/sites/site1",
    fetchClientFactory: () => {
      return new SPFetchClient(
        "https://xxx.sharepoint.com/sites/site1",
        "clientID",
        "clientSecret"
      );
    },
  },
});

const f = async () => {
  const source = "/sites/site1/Docs/folder1";
  const target = "/sites/site1/Docs/read-only/folder1";
  try {
    const r = await sp.web.getFolderByServerRelativeUrl(source).moveTo(target);
    console.log("ok");
    return true;
  } catch (ex) {
    console.log("error");
    console.log(ex);

    return ex;
  }
};

f().then((r) => {
  console.log("done");
});
```

**Comment by Bo4711** [comment]
Short Update:
Executing the code with a client ID which has FullControl on Tenant (and not only on SiteCollection) works without issues as well.

**Comment by patrick-rodgers** [comment]
This results from your user(s) not having access to the root site collection which was an assumption we made in our design. I updated the code to invoke the static method from the current site collection which should address this. Update will go our in 2.4.0 today. Thanks!
