### ISSUE TITLE
Adding @pnp/nodejs@2.2.0 to my spfx webpart project causes errors

### ISSUE THREAD

**Issue by karthikramasubramanian** [pnp/pnpjs#1687]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ @pnp/nodejs@2.2.0 ]

Please specify what version(s) of SharePoint you are targeting: [  Sharepoint Online       ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*
I tried using the latest version and it still throws the same error.

### Expected / Desired Behavior / Question
As per the documentation found here https://pnp.github.io/pnpjs/graph/, I am trying to setup graph using the AdalFetchClient 
import { graph } from "@pnp/graph";
import { AdalFetchClient } from "@pnp/nodejs";
import "@pnp/graph/groups";

// do this once per page load
graph.setup({
    graph: {
        fetchClientFactory: () => {
            return new AdalFetchClient("{tenant}.onmicrosoft.com", "AAD Application Id", "AAD Application Secret");
        },
    },
});
I am currently using the 2.2.0 version of pnp/common, pnp/sp, pnp/graph , so, I tried installing the 2.2.0 version of @pnp/nodejs.

I expected the project to build without any issues. 

### Observed Behavior
After doing npm install pnp/nodejs and building the project, I am seeing the errors listed below:

Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(17,1): error TS1128: Declaration or statement expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(17,13): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(17,47): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(18,1): error TS1128: Declaration or statement expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(18,13): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(18,46): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(19,1): error TS1128: Declaration or statement expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(19,13): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(19,46): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(20,1): error TS1128: Declaration or statement expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(20,13): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(20,40): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(21,1): error TS1128: Declaration or statement expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(21,13): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(21,40): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(22,1): error TS1128: Declaration or statement expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(22,13): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(22,46): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(23,1): error TS1128: Declaration or statement expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(23,13): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(23,42): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(24,1): error TS1128: Declaration or statement expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(24,13): error TS1005: ';' expected.
Error - [tsc] node_modules/@azure/msal-node/dist/index.d.ts(24,40): error TS1005: ';' expected.
Error - 'tsc' sub task errored after 17 s 
 exited with code 2

### Steps to Reproduce
`-- typescript@4.0.5
`-- @microsoft/generator-sharepoint@1.11.0
webpart project

connect to graph using app id and app secret.

Thank you for your feedback!

**Comment by koltyakov** [comment]
Why you added Node.js (server-side) package to client-side SPFx solution? It's expected it won't gonna work.
The setup for SPFx doesn't involve `@pnp/nodejs`, please check: https://pnp.github.io/pnpjs/graph/#getting-started-with-sharepoint-framework

**Comment by karthikramasubramanian** [comment]
Hi @koltyakov 
Thanks for your response.  I want to connect to graph api using the the app_id, app_secret and bearer_token.  i.e,, I want to connect to graph in the application context (Application API access) and not the current users context (Delegated API access).  Can you please advise how I can setup and use the pnp graph package for this purpose?

**Comment by juliemturner** [comment]
The browser doesn't support doing app level permissions, you're going to have to build and host your solution elsewhere (ie. not the SharePoint Framework) to make that work... depends on what you're doing as to where but there are a couple Azure services that would probably do the trick that support nodejs... like Azure Functions and the like.

**Comment by karthikramasubramanian** [comment]
> The browser doesn't support doing app level permissions, you're going to have to build and host your solution elsewhere (ie. not the SharePoint Framework) to make that work... depends on what you're doing as to where but there are a couple Azure services that would probably do the trick that support nodejs... like Azure Functions and the like.

Hi @juliemturner ,
Thanks for your response.  I managed to create a test Azure function, that returns an access token that allows access to call azure api.  But, what i want is to be able to use the pnp graph api functions with that token.  Can you give some pointers on how I can set this up?  or do i have to expose methods from the azure function that does specific graph api calls?  Any help is apperciated

**Comment by juliemturner** [comment]
Yes, the latter, you need to do all the work in the Azure Function and then you call the azure function from the SPFx solution passing in any parameters that the function needs to do the work you want and then responds with whatever response gives your SPFx solution the details it needs to continue.

**Comment by karthikramasubramanian** [comment]
Thanks @juliemturner 
Do you have any pointers on how to secure an Azure function so that it can only be called from my spfx webpart?

**Comment by juliemturner** [comment]
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/isolated-web-parts

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
