### ISSUE TITLE
Property getById does not exist on type INavNodeInfo[].

### ISSUE THREAD

**Issue by Marc93-14** [pnp/pnpjs#1694]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.3.0 ]

Please specify what version(s) of SharePoint you are targeting: [Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Observed Behavior
According to the documentation, I should be able to run this: 
```
const nav = await sp.web.navigation.topNavigationBar();
await nav.getById(200).delete();
```
However, I am getting Property getById does not exist on type INavNodeInfo[].

### Expected / Desired Behavior / Question
My understanding is sp.web.navigation.topNavigationBar(); returns an object that has the getByID.

**Comment by patrick-rodgers** [comment]
I think you want:

```
const nabBarObject = sp.web.navigation.topNavigationBar.getById(1);

const navBarData = sp.web.navigation.topNavigationBar.getById(1)();
```

The parens invoke the request in your sample code. So "nav" is the data, not the object at that point. Looking at the docs we can make that more clear.
