### ISSUE TITLE
Version 2.4.0 did not resolve the apostrophes Issue in addChunked

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#1698]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.4.0   ]

Please specify what version(s) of SharePoint you are targeting: [ SPO     ]

### Expected / Desired Behavior / Question
```
let fileName = "Meeting Facilitation's info.pptx"
 uFile = await projectWebSite.getFolderByServerRelativeUrl(somepath).files.addChunked(fileName, fileBlob, data => {  console.log("progress " + data.blockNumber + " Stage " + data.stage);                     }, true, 5000000);

```
Should work 

### Observed Behavior
getting error "The expression \"Web/GetFileByServerRelativePath(decodedurl='/teams/T000.011/DPCDocuments/Meeting Facilitation'sSutuf.pptx')/listItemAllFields\" is not valid."

On the last chunk.

### Steps to Reproduce
use the code with a file name with apostrophes

Is there decoding that can help?

Thank you for your help!

**Comment by patrick-rodgers** [comment]
Certainly sorry you're still having issues. It looked fixed on our end.

I can't find where we are doing a call to "listItemAllFields" within the addChunked code path. Perhaps I am missing it, or is there possibly some other code you havent' shared where you make that call? For example are you trying to use the addChunked resulting file object and it is erroring?

If you can provide a full repro or a bit more detail we can def take a look at resolving this, but the code you shared above works for me as written. I must be missing a step to get the error. Thanks!

**Comment by Ofer-Gal** [comment]
The only thing that is not exactly the same as your examples is that I do not use sp.web.....
I first get the web with 
`const projectWeb = Web(window.location.origin + "/teams/" + dataItem.dpcProjectNumber);`
and only then 
```
let  fileName = fileName.split("'").join("%27"); // I added this no help
 uFile = await projectWebSite.getFolderByServerRelativeUrl(somepath).files.addChunked(fileName, fileBlob, data => {  console.log("progress " + data.blockNumber + " Stage " + data.stage);    }, true, 5000000);
```
I found out that the file is actually saving OK so for now I disregard errors with " is not valid"

**Comment by patrick-rodgers** [comment]
We will try and have a look but I just don't see where in the addChunked code path we make a call to "listItemAllFields" that would generate the error you reported. Do please share any more details you think might be relevant and sorry again the fix didn't work for your case.
