### ISSUE TITLE
Error on import { Web, PermissionKind } from "@pnp/sp"; with "SharePoint 2016 onwards" webpart

### ISSUE THREAD

**Issue by mn0073xx** [pnp/pnpjs#170]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

When doing the import { Web, PermissionKind } from "@pnp/sp"; on a SharePoint 2016 onwards webpart, we don't receive gulp errors.

#### Observed Behavior

No errors reported by gulp

#### Steps to Reproduce

I recorded a transcript and I am attaching the out to the request.  The only step not recorded is inserting the line: 

**import { Web, PermissionKind } from "@pnp/sp";**

into the file MyTestWpWebPart.ts.  The output of errors is also in the transcript.  This error does not happen when doing SharePoint online only.

[PowerShell_transcript.txt](https://github.com/SharePoint/sp-dev-docs/files/2194205/PowerShell_transcript.txt)

**Comment by patrick-rodgers** [comment]
Hi @mn0073xx - we have an [article covering this in the docs](https://pnp.github.io/pnpjs/SPFx-On-Premesis-2016.html). The version of TypeScript in the on-premises version of SPFx is older than what we used as a baseline in our project. At the time everything was fine, but that was before we had split versions. We won't be going back in versions of TS so the workaround is what is described in the article. Can you please give those steps a try and let us know if you are all set. Thanks!

**Comment by patrick-rodgers** [comment]
Going to close this due to lack of response. If the above article did not help resolve your issue, please _reopen_ the issue so we can provide further assistance. Thanks!
