### ISSUE TITLE
How to create reposts pages

### ISSUE THREAD

**Issue by ydescortes** [pnp/pnpjs#1703]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.12]

Please specify what version(s) of SharePoint you are targeting: [Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Hi,

I want to use pnp js for creating reposts page (news pages with external link) but it seems to be not implemented yet.
How can i extend api in my project for call it with post request : [how to create news link programmatically](https://sharepoint.handsontek.net/2020/11/01/post-sharepoint-news-link-programmatically/)

I use the api pnp js in node js project (not spfx)

**Comment by koltyakov** [comment]
Please check this https://pnp.github.io/pnpjs/contributing/extending-the-library/

**Comment by patrick-rodgers** [comment]
You can extend the library for your use as linked by @koltyakov for sure. Would also encourage you to submit the work as a PR to the lib to benefit everyone.

I have gone ahead an added a `addRepostPage` method to web and updated docs to describe it. Will go out as part of 2.5.0 release.
