### ISSUE TITLE
SharePoint /_api/web/ request fails when the url is too long

### ISSUE THREAD

**Issue by JohanFiske** [pnp/pnpjs#1726]
### Category
- [X] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.4.0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
We're using the method **getFileByServerRelativePath** along with **moveTo** to move a file inside a SharePoint library and run into problems when the path is too long, giving us a 400 Bad Request in return.
`sp.web.getFileByServerRelativePath(sourcePath).moveTo(targetPath)`

If trigger the request manually and change the format from:
`/_api/web/getFileByServerRelativePath(decodedUrl=[a_very_long_path])/moveTo(newurl = [another_very_long_path], flags = 1)`
to
`/_api/web/getFileByServerRelativePath(decodedUrl=@f)/moveTo(newurl = @n, flags = 1)?@f=[a_very_long_path]&@n=[another_very_long_path]`
things seem to work. But maybe there are other ways to get around this also?

### Observed Behavior
File is not moved and the network tab in F12 shows that the underlying request to /_api/web/getFileByServerRelativePath(...)/moveTo(...) has failed.

### Steps to Reproduce
I don't know the exakt amount of characters that causes the request to fail. But it can be reproduced by having long folder/docset names in combination with long file names.

Thanks in advance!

**Comment by patrick-rodgers** [comment]
Hi @JohanFiske,

We support alias parameters for just this scenario. Please [have a look at the docs](https://pnp.github.io/pnpjs/sp/alias-parameters/) and let us know if this solves the issue for you.

**Comment by JohanFiske** [comment]
Oh, my bad! Works perfect now. Thanks for a quick and kind respons!
