### ISSUE TITLE
The Correct Way To Retrieve User Id?

### ISSUE THREAD

**Issue by jerryjili** [pnp/pnpjs#1732]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [✔] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  pnpjs 1.3.5    ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online   ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Question

Hi all, I have one question regarding the user entity in ```sp.web```. Basically, I was trying to retrieve the Id of the current logged in user. I was able to use ```sp.web.currentUser.get()``` to get the user object. With that, if I do one step further to get the Id ```sp.web.currentUser.get().Id```, the web part results in the following error status. And I cannot even track the http request corresponding to it.
![image](https://user-images.githubusercontent.com/66039996/116630445-fd08a700-a907-11eb-898a-ec75042d7e37.png)
If I do ```sp.web.currentUser.get().UserId```, the error no longer exists, but the result is always null. However, if I query the user's email by ```sp.web.currentUser.get().Email```, it returns the correct result. 

I'm wondering, is this a normal behavior? Or did I miss anything to get the Id? Meanwhile, if our user is authenticated via AAD, is it possible to retrieve the AAD Object Id of the user from Pnp sdk?

Thank you very much!

**Comment by koltyakov** [comment]
Async programming, Promises! =)

```typescript
import { sp } from '@pnp/sp';
import '@pnp/sp/webs';
import '@pnp/sp/site-users';

(async () => {

  const { Id: userId } = await sp.web.currentUser.select('Id').get();
  console.log({ userId });

})().catch(console.log)
```

**Comment by PathToSharePoint** [comment]
@koltyakov that was my first thought too, but then how do you explain that `sp.web.currentUser.get().Email` returns the correct result?

**Comment by koltyakov** [comment]
> how do you explain that sp.web.currentUser.get().Email

Explanation is simple. It doesn't. ;)

`sp.web.currentUser.get()` is a Promise, not an object with a data.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
