### ISSUE TITLE
Cannot find module util, only util.js (this project relies on CJS paths despite being an MJS project)

### ISSUE THREAD

**Issue by ValeTheVioletMote** [pnp/pnpjs#1737]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.4.0]

Please specify what version(s) of SharePoint you are targeting: N/A

Node version 15.4.0

### Expected / Desired Behavior / Question
Expect the libraries to run just fine.

### Observed Behavior
Running the libraries results in this error:
```
node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\git\REDACTED\node_modules\@pnp\common\util' imported from C:\git\REDACTED\node_modules\@pnp\nodejs\sp-extensions\stream.js
Did you mean to import @pnp/common/util.js?
    at new NodeError (node:internal/errors:278:15)
    at finalizeResolution (node:internal/modules/esm/resolve:307:11)
    at moduleResolve (node:internal/modules/esm/resolve:742:10)
    at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:853:11)
    at Loader.resolve (node:internal/modules/esm/loader:86:40)
    at Loader.getModuleJob (node:internal/modules/esm/loader:230:28)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:56:40)
    at link (node:internal/modules/esm/module_job:55:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Steps to Reproduce
Install the packages @pnp/nodejs @pnp/sp at 2.4.0.

Code (the example from https://pnp.github.io/pnpjs/sp/ but simplified even more):
```js
import {sp} from "@pnp/sp";
import {SPFetchClient} from "@pnp/nodejs";

var HTTP_PROXY = process.env.HTTP_PROXY;

sp.setup({
    sp: {
        fetchClientFactory: () => {
            return new SPFetchClient("SITE_URL", "CLIENT_ID", "CLIENT_KEY");
        }
    }
});
```

Workaround: running with the flag `--experimental-specifier-resolution=node`

**Comment by ValeTheVioletMote** [comment]
Wow, yeah, v2 of this project seems completely unfriendly to the vanilla JS approach. Will have to go back to v1.

```
C:\git\onpoint>node --experimental-specifier-resolution=node cron
file:///C:/git/REDACTED/node_modules/@pnp/nodejs/net/proxy.js:2
import { HttpsProxyAgent } from "https-proxy-agent";
         ^^^^^^^^^^^^^^^
SyntaxError: Named export 'HttpsProxyAgent' not found. The requested module 'https-proxy-agent' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'https-proxy-agent';
const { HttpsProxyAgent } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:104:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:149:5)
    at async Loader.import (node:internal/modules/esm/loader:166:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```

**Comment by ValeTheVioletMote** [comment]
Switching to the `-commonjs` series of your packages (@pnp/sp-commonjs, @pnp/nodejs-commonjs) solved all my problems.

**Comment by patrick-rodgers** [comment]
It looks like an import got auto-shortened from when we did the patching to make things work in node 15 when they changed how modules are resolved. We can get that fixed up. Should resolve things for you.

> Wow, yeah, v2 of this project seems completely unfriendly to the vanilla JS approach. Will have to go back to v1.

That is just an untrue and unfair statement. We updated the entire library to work with node 15 and it looks like we missed something. That happens, we are only human. If you have constructive comments we certainly welcome them, but please leave stuff like this out.

**Comment by ValeTheVioletMote** [comment]
If that's truly a Node 15 issue then it's on me, I'm sorry. Yesterday was very frustrating. Only when I got it working with commonjs did I finally catch the warning about supported versions being Node 10/12/14, but I wasn't sure if that was your package or a dependency. Still not sure.

Thank you for looking into this. I'll be happy to test again as an MJS.

**Comment by patrick-rodgers** [comment]
Starting with Node 15 they (and webpack 5) updated how they do module resolution. Some folks would point out they are just being strict about the rules that have always existed, but the decision created a breaking change the package ecosystem. We went through and did a lot of work to support the new resolution rules, and this is one we missed. With v3 we are looking to expand our test matrix across node versions that will help with this type of thing.

If you have a chance you can install the latest beta versions:

`npm install @pnp/sp@beta @pnp/nodejs@beta --save`

With these beta versions the below code worked for me in an index.js file using `node index.js` which shows it will work in plain js. I used and recommend the [MSAL client](https://pnp.github.io/pnpjs/authentication/server-nodejs/#call-sharepoint) which is preferred over the older SPFetchClient but SPFetchClient still works fine.

### index.js

```TypeScript
import { sp } from "@pnp/sp";
import { MsalFetchClient } from "@pnp/nodejs";
import settings from "../settings.js";
import "@pnp/sp/webs/index.js";

// var HTTP_PROXY = process.env.HTTP_PROXY;

sp.setup({
    sp: {
        baseUrl: settings.testing.sp.url,
        fetchClientFactory: () => {
            return new MsalFetchClient(settings.testing.sp.msal.init, settings.testing.sp.msal.scopes);
        }
    }
});

const y = await sp.web();

console.log(JSON.stringify(y));
```

### package.json

Also I updated the package.json to include the "type": "module" entry.

```JSON
{
  "name": "nodejs-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@pnp/nodejs": "^2.5.0-beta2",
    "@pnp/sp": "^2.5.0-beta2"
  }
}
```

If things look good in your testing we will include this in 2.5.0.

**Comment by ValeTheVioletMote** [comment]
Confirmed working. Thanks again, and apologies again.

**Comment by patrick-rodgers** [comment]
All good, glad we were able to get it sorted. As mentioned fix will go out with next release. Thanks for using the library and reporting the bug so we could get it fixed!
