### ISSUE TITLE
Unable to call ClientsidePageFromFile when using web instead of currentContext from SPFx webpart

### ISSUE THREAD

**Issue by kininarasimha** [pnp/pnpjs#1742]
const url = "https://{tenantName}.sharepoint.com/SitePages/Home.aspx";
    // file is an IFile and supports all the file operations
    const web = Web("https://{tenantName}.sharepoint.com");
    const file = web.getFileByUrl(url);
    let page: IClientsidePage =  await ClientsidePageFromFile(file);

getting this error VM3665:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parsers.js:22

**Comment by patrick-rodgers** [comment]
HI @kininarasimha - you've deleted our entire issue template. Can you please resubmit this issue including all of the requested information? Thanks!
