### ISSUE TITLE
Unable to use ClientSidePageFromFile when using Web("url") instead of using sp.web

### ISSUE THREAD

**Issue by kininarasimha** [pnp/pnpjs#1743]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.4.0       ]

Please specify what version(s) of SharePoint you are targeting: [     SPO    ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Want to load a page using a SPFx webpart from a sitecollection
    const url = "https://{tenantName}.sharepoint.com/SitePages/Home.aspx";
    // file is an IFile and supports all the file operations
    const web = Web("https://{tenantName}.sharepoint.com")
    const file = web.getFileByUrl(url);
    let page: IClientsidePage =  await ClientsidePageFromFile(file);

### Observed Behavior
Unable to use ClientSidePageFromFile when using Web("url") instead of using sp.web
getting the below error  when this line gets called let page: IClientsidePage =  await ClientsidePageFromFile(file);
VM4192:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parsers.js:22

### Steps to Reproduce
create an SPFX webpart and try to load the clientside page and it doesnt work
    const url = "https://{tenantName}.sharepoint.com/SitePages/Home.aspx";
    // file is an IFile and supports all the file operations
    const web = Web("https://{tenantName}.sharepoint.com")
    const file = web.getFileByUrl(url);
    let page: IClientsidePage =  await ClientsidePageFromFile(file);

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
Hi @kininarasimha,

Had a chance to test this and cannot duplicate the error you got. My code matches yours so far as I can tell. Are you setting any other configuration? The error makes me think you are getting back either XML or an error HTML page, but the error page should be caught as an error.

```TypeScript
const web = Web("https://318studios.sharepoint.com/sites/dev/");

const file = web.getFileByUrl("https://318studios.sharepoint.com/sites/dev/SitePages/List-Web-Part.aspx");

const page = await ClientsidePageFromFile(file);
```

**Comment by kininarasimha** [comment]
Hi Patrick,

Thank you for responding Patrick.

I think there was some issue with the page I was trying to load, once I re published the page, I was not getting this error and the code was working.

Regards
Narasimha

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by patrick-rodgers** [comment]
Awesome, thanks for letting us know - will close this.
