### ISSUE TITLE
PnP js to get all site users from the site collection who is having access

### ISSUE THREAD

**Issue by Divyakrishna123** [pnp/pnpjs#1745]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [1 ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [pnp-sp version "@pnp/sp": "2.0.5",         ]

Please specify what version(s) of SharePoint you are targeting: [  SharePoint Online       ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question

PnP js to get all site users from the site collection who is having access 

I am using below api to get all the user details within the site collection

const users = await sp.web.siteUsers();

I am able to get all the user details from this, this api will returns the user details who is having access and whose access is removed.

But I need to display only the user who is having access to the site currently.

### Observed Behavior
It displays all the user details, even whose access is removed

In my case
 1. I need to displays only the user who are having the access
2.  should not display the users who does not have access to the site

### Steps to Reproduce
please provide the access to any test user to site collection and then remove the permission for the same user and run the above code

Even the user whose permission is removed will get displayed

Please let me know is there a way differentiate whether user is having access to site or not, which helps me further

Thank you for your feedback!

**Comment by Divyakrishna123** [comment]
Any update on this: 

Is there a way to differentiate whether user is having access to site or not(if user is added and then removed) using the below code

const users = await sp.web.siteUsers();

**Comment by Divyakrishna123** [comment]
Any update on this:

Is there a way to differentiate whether user is having access to site or not using the below code

const users = await sp.web.siteUsers();

**Comment by juliemturner** [comment]
You would have to probably use [Permissions](https://pnp.github.io/pnpjs/sp/permissions/)
