### ISSUE TITLE
sp.social.my.followed() should return Promise<SocialActor[]> and not Promise<Any[]> in MySocialQueryMethods

### ISSUE THREAD

**Issue by baywet** [pnp/pnpjs#175]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [1.1.2]

### Expected / Desired Behavior / Question
Today the interface MySocialQueryMethods defines the followed method with a return type of Promise<Any[]> when it's implementation MySocialQuery implements it with a return type of Promise<SocialActor[]>
This jams the compiler in doing type check validation, the editor in doing auto-complete and so on.
All the other methods return a strongly typed interface and not any. To be consistent I think the return type of the followed method in the interface should be changed.

**Comment by patrick-rodgers** [comment]
Updated the interface, will be in next release.

Side note, items like this are a great way to contribute back in a PR :)

**Comment by baywet** [comment]
Thanks!
I'd love to! Usually when I open an issue I wait for the authors to let me know if they want to tackle it themselves or if they are open for PR. 
Maybe leveraging a help wanted tag and tackling it yourself after a week of it hasn't moved would be a good way to achieve the display of work?
