### ISSUE TITLE
Add support for creating SingleWebPartAppPage and set a Component id

### ISSUE THREAD

**Issue by cneSPFX0815** [pnp/pnpjs#1751]
### Category
- [x] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.4.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
Currently it is not possible to create Pages with a FullPage App on it. Will this be possible the next versions

### Observed Behavior
If i create a new page using pnp/js (sp.web.addClientsidePage) it should be possible to add type SingleWebPartAppPage and provide a Component id (for the full page app) .

**Comment by patrick-rodgers** [comment]
Turns out you can do this today as follows:

```TypeScript
const web = Web("https://{tenant}.sharepoint.com/sites/dev/");

// get all the available components
const parts = await web.getClientsideWebParts();

// find the one you want to add, this GUID is the manifests id value
const partDef = parts.find(p => /{?~Component GUID~}?/i.test(p.Id));

// create a page
const page = await web.addClientsidePage("test", "title", "SingleWebPartAppPage");

const part = ClientsideWebpart.fromComponentDef(partDef);

page.addSection().addColumn(12).addControl(part);

await page.save();
```

Given that is a bit of a pain, I am looking to add a method to take the component Id and perform those steps for you.

**Comment by cneSPFX0815** [comment]
> Turns out you can do this today as follows:
> 
> ```ts
> const web = Web("https://{tenant}.sharepoint.com/sites/dev/");
> 
> // get all the available components
> const parts = await web.getClientsideWebParts();
> 
> // find the one you want to add, this GUID is the manifests id value
> const partDef = parts.find(p => /{?~Component GUID~}?/i.test(p.Id));
> 
> // create a page
> const page = await web.addClientsidePage("test", "title", "SingleWebPartAppPage");
> 
> const part = ClientsideWebpart.fromComponentDef(partDef);
> 
> page.addSection().addColumn(12).addControl(part);
> 
> await page.save();
> ```
> 
> Given that is a bit of a pain, I am looking to add a method to take the component Id and perform those steps for you.

@patrick-rodgers 
Thx for your answer. I tested your code in my application. Unfortunatly the code doesn't work for my FullPage App. When calling `await web.getClientsideWebParts();`, the collection contains all available web parts in my tenant, but my web part, which is a FullPage WebPart, is not included. 

Just to be sure i explained my issue correctly. I am using the following Type (from *.manifest.json in folder "src/webparts"):
![image](https://user-images.githubusercontent.com/83806610/119148019-633aa280-ba4c-11eb-8834-17a4c1b600b4.png)

The webpart could not be added in modern pages. It could only be used when creating a new page:
![image](https://user-images.githubusercontent.com/83806610/119148205-911fe700-ba4c-11eb-8373-a89e326864fe.png)
