### ISSUE TITLE
Throttled requests do not return HttpRequestError

### ISSUE THREAD

**Issue by RafalUrbanski** [pnp/pnpjs#1754]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of SharePoint you are targeting: SharePoint Online

### Expected / Desired Behavior / Question
When rest call to SharePoint Online endpoint returns 429 status (throttled), error returned from pnpjs library should be of type HttpRequestError (same as for 403, or 500 exception), not of Error type. 

### Observed Behavior
Standard Error is being returned and thus it is not possible to check the status of the error and 'isHttpRequestError' property does not exist. Because of that it is difficult to create common approach for errors returned by pnpjs library rest calls.
Code responsible for this behaviour:
https://github.com/pnp/pnpjs/blob/013ca6b693d862166a03d418a4bcd4312e9ba187/packages/sp/sphttpclient.ts#L113

**Comment by patrick-rodgers** [comment]
I don't have any reason when it is an Error vs HttpRequestError so we can get that updated.

**Comment by RafalUrbanski** [comment]
Great! :)
