### ISSUE TITLE
Isolated runtimes are not inherited to item, if item is from folder.getItem()

### ISSUE THREAD

**Issue by morgars** [pnp/pnpjs#1755]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.4.0     ]

Please specify what version(s) of SharePoint you are targeting: [   Sharepoint Online      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question

If the isolated runtime is used and a item was get with "folder.getItem()", then further calls do not work, because the item is using the default-runtime

### Observed Behavior
The item has the runtime with which it was fetched with.

### Steps to Reproduce
create an isolated runtime with bearerTokenFetchClient
```
// get a web with isolatedSP.site.openWebById:
const web = await (await isolatedSP.site.openWebById(webId))?.web;
// get a folder 
const folder = await web.getList("serverRelativeLisUrl").rootFolder.folders.getByName("folderName").get();
// get an item
const item = await folder.getItem();
// try to breakRoleInheritance
await item.breakRoleInheritance(false);
```

### Workaround
// set the runtime on the item-object
`item.setRuntime(isolatedSP.site.getRuntime())`

**Comment by patrick-rodgers** [comment]
Thanks for reporting this, fixed it this morning before the release. Let us know if you catch any more places we missed in transferring the configuration.

**Comment by morgars** [comment]
Thank you for fixing it! I hope it was the last place. I will write an new issue when I catch any more places.
