### ISSUE TITLE
Property 'properties' missing in getAllChildrenAsOrderedTree. 

### ISSUE THREAD

**Issue by breivald** [pnp/pnpjs#1765]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.5        ]

Please specify what version(s) of SharePoint you are targeting: [     SharePoint Online    ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
When using getAllChildrenAsOrderedTree the property 'properties' should be returned and added to the IOrderedTermInfo object

### Observed Behavior
The property 'properties' does not get returned from graph if not included in the selected parameter. I saw that you have added customSortOrder but you'll also need to add properties.

### Steps to Reproduce
Use graph explorer and use termStore/groups/{groupId}/sets/{setId}/terms. Properties is not returned. 
If using termStore/groups/{groupId}/sets/{setId}/terms?$select('*','properties'), properties are returned

**Comment by patrick-rodgers** [comment]
Why should properties be returned? The choice was to bring back a little less since this method could be aggregating hundreds of terms. What is the use case supporting that?

**Comment by breivald** [comment]
In our case we would like to use the properties (local properties) for
various of things and our termsets is not that big but we cache the
results. It would be nice to have the option to choose if properties should
be returned or not.




tis 18 maj 2021 kl. 18:39 skrev Patrick Rodgers ***@***.***>:

**Comment by patrick-rodgers** [comment]
Making it optional is a good way to handle it. Will look at adding that capability for the next release.

**Comment by patrick-rodgers** [comment]
Added and will be part of 2.6.0
