### ISSUE TITLE
How to avoid SNAT Port Exhaustion using pnpjs from node Azure Function App?

### ISSUE THREAD

**Issue by ElinKolloen** [pnp/pnpjs#1767]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.3.5     ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online      ]

I've created a Function App (v2) running on node,js that has both https endpoints and timer jobs as separate functions in the same package. The Function App is running in an App Service Plan S3 (single instance) and AlwaysOn is enabled.

Now my problem is that the Azure Environment is reporting that my Function App has SNAT port issues. 

In my code I'm opening connections to a custom https endpoint running ouside Azure, in addition to a lot of requests to SharePoint. 

I'm now rewriting my code calling the external endpoint using node-fetch to use a custom https agent where I can specify keepalive = true as described from MS in https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-intermittent-outbound-connection-errors.

Do anoyne know if connections to SharePoint Online through pnpjs also is using separate SNAT ports for each request? It is sure opening a lot of TCPIP connections, but SNAT is a different resource. If this is the case, I hope it is possible to reuse the connection between different calls with this library aswell. The documentation describes "Custom IRequestClient" that I'm thinking could be a possible solution. Has anyone else had the same SNAT port issue? What would be the correct way to control the connections made to SharePoint by the library?

Best regards
Elin Kolloen

**Comment by patrick-rodgers** [comment]
Will need to do some digging. For sure you can use your own client. This is not an issue others have reported, so I need to do some reading. If others can share ideas as well that would be great. Will work on something for the next release and see what we can do to help here.

**Comment by patrick-rodgers** [comment]
Coming back to research this I have a proposed solution for you. In the document you linked it points to the [agentkeepalive](https://www.npmjs.com/package/agentkeepalive) which you can use to help with the SNAT port issue. You can actually today set an agent for the request, but since we first enabled this for proxy scenarios the method you need is "[setProxyAgent](https://pnp.github.io/pnpjs/nodejs/proxy/#setproxyagent)".

 - [MSAL client docs](https://pnp.github.io/pnpjs/authentication/server-nodejs/#msal)

Here is a sample that should help illustrate, please let us know your findings.

```TypeScript
import { SPFetchClient, SPOAuthEnv, setProxyAgent } from "@pnp/nodejs";
const Agent = require('agentkeepalive');

const keepaliveAgent = new Agent({
  maxSockets: 100,
  maxFreeSockets: 10,
  timeout: 60000, // active socket keepalive for 60 seconds
  freeSocketTimeout: 30000, // free socket keepalive for 30 seconds
});

sp.setup({
    sp: {
        fetchClientFactory: () => {

            const myAgent = new MyAgentOfSomeType({});

            // call the set proxy agent function and the keep alive agent will be applied to the requests
            setProxyAgent(keepaliveAgent );
            
           // use any of the node clients, we now recommend MSAL whenever possible
            return new SPFetchClient(settings.testing.sp.url, settings.testing.sp.id, settings.testing.sp.secret);
        },
    },
});
```

**Comment by ElinKolloen** [comment]
Thank you for the reply, this looks very promising and I will implement this in my code. :-)

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
