### ISSUE TITLE
What happened to the documentation?

### ISSUE THREAD

**Issue by simkessy** [pnp/pnpjs#177]
Haven't used PNP in a couple months, seems pretty different now. What happened to the documentation on how to do various tasks, everything on github is archived now :/

**Comment by patrick-rodgers** [comment]
Hi @simkessy,

We've been discussing the transition for over 6 months with July 2018 being the archive date and final release of the sp-pnp-js libraries. During that time we had an explanation posted on the readme for sp-pnp-js discussing the move as well as providing a link to the [transition guide](https://pnp.github.io/pnpjs/transition-guide.html). [The documentation](https://github.com/pnp/pnpjs#documentation) is linked from the readme in this library as well as the readme for sp-pnp-js. [The documentation](https://pnp.github.io/pnpjs) is also linked in the header for this repository. You can also have a look as the [getting started guide](https://pnp.github.io/pnpjs/getting-started.html) in [the documentation](https://pnp.github.io/pnpjs) for how to easily add and begin using the new libraries in your applications.

In addition to that we have covered the change in our [bi-weekly calls](https://docs.microsoft.com/en-us/sharepoint/dev/community/community#community-calls) - the recordings for which can be found on our [youtube channel](https://www.youtube.com/channel/UC_mKdhw-V6CeCM7gTo_Iy7w/featured). You can find the JS SIG videos in [this playlist](https://www.youtube.com/playlist?list=PLR9nK3mnD-OXdcwfcHGsGr78nHWLRsv1x).

**Comment by simkessy** [comment]
I see...I'm not sure how you can compare what you guys had in the wiki to https://pnp.github.io/pnpjs/ which essentially shows the bare minimum on getting up and running with no real examples like the wiki provided before. 

[This page ](https://github.com/SharePoint/PnP-JS-Core/wiki/Developer-Guide) was pretty extensive in explaining what you could do with the library. The link you provided above, well, :/

**Comment by koltyakov** [comment]
Hi @simkessy,

Did you try drilling down to any of the packages from the index docs page, e.g. `sp` package?
`sp-pnp-js` wiki contains 46 pages while new docs at the moment have 68 info pages. I don't believe that new docs miss some info which was in the old lib.

What we really miss now, IMO, is search over the docs, yet it searchable from outside `web site:https://pnp.github.io/pnpjs`.

Anyway, it's a sign for us that docs site UX has some gaps to enhance and do more straightforward for the folks to find required article even without knowing of its existence.

**Comment by simkessy** [comment]
@koltyakov 

I see, I was looking at pnpjs instead of sp. Hmm yea maybe a search would be helpful. I don't really see the batch information anymore, it's kind of become a bit more challenging to find how to use pnp compared to before. Probably my fault for now having kept up over the past couple months, at least the old wiki is still available.

**Comment by patrick-rodgers** [comment]
@simkessy - Can you share some concrete suggestions for improving the docs? We can look at adding a search box (just a scoped bing search). What else would help?

**Comment by simkessy** [comment]
It could just be me really. For some reason I was having a really hard time getting to what I needed. I think it would help if there was a larger link in the old github repo that pointed directly to the list of topics like (dealing with items, update, add, batch, etc etc.). I was trying to figure out where that was moved too and couldn't find it until I asked.

**Comment by koltyakov** [comment]
The wrong one to reference in a legacy style projects, please try this `https://cdnjs.cloudflare.com/ajax/libs/pnp-pnpjs/1.1.2/pnpjs.es5.umd.bundle.min.js`.

**Comment by simkessy** [comment]
Thank you that helped.

**Comment by patrick-rodgers** [comment]
Going to close this. Added a search box to the header. If you have other constructive suggestions for the docs we can implement please create a new issue. We are going to look at a "left nav" but unsure on timeline for that. Thanks!
