### ISSUE TITLE
getListItemEntityTypeFullName fails when Validation Rule is defined in SP list

### ISSUE THREAD

**Issue by kkazala** [pnp/pnpjs#1770]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: 2.5.0
Please specify what version(s) of SharePoint you are targeting:  SP Online

### Expected / Desired Behavior / Question

I'm copying items between lists using the following code:
```
            const sourceList = sp.web.lists.getByTitle(this.props.sourceListName);
            const  targetList = sp.web.lists.getByTitle(this.props.targetListName);
            let entityTypeFullName = await targetList.getListItemEntityTypeFullName();

            let copyBatch = sp.web.createBatch();
           [...]
```
The entityTypeFullName  should retrieve correct entity name from the list

### Observed Behavior
If the list has Validation Rules defined (List Settings / Validation Settings : =[EndDate ]>[StartDate]), the 
`let entityTypeFullName = await targetList.getListItemEntityTypeFullName();`
results in error: 
`Error making HttpClient request in queryable [500] Internal Server Error ::> {"odata.error":{"code":"-2130575162, Microsoft.SharePoint.SPListDataValidationException","message":{"lang":"en-US","value":"List data validation failed."}}}
`
If I remove the validation rule, it works again

### Steps to Reproduce

1. Create a SP list
2. Execute a code snippet: 
```
(async () => {
            
            let targetList = sp.web.lists.getByTitle(LISTNAME);
            let entityTypeFullName = await targetList.getListItemEntityTypeFullName();
})();
```
3. Ensure the code executes correctly
4. Set Validation Rules defined (List Settings / Validation Settings )
5. Test the code again

**Comment by patrick-rodgers** [comment]
That's very strange. The only thing that method does is a get request to the list. Are there any other details you can share about your configuration? If the presence of validation breaks doing a select on the list I am not sure what we can do on our end, but we can have a look. Would appreciate any other details you can share.

**Comment by kkazala** [comment]
hi  @patrick-rodgers , thank you for picking the issue up so fast. 

I will tell you as much as I can about my solution and if you need anything else, pls let me know

I am creating the list using PnP PS:

```
$listName= 'Termine'
New-PnPList -Title $listName -Template GenericList -Url Lists/Termine -EnableVersioning -OnQuickLaunch
Add-PnPFieldFromXml -List $listName -FieldXml '<Field Type="DateTime" Name="EventDate" ID="{8ecdce10-b381-4179-9122-0470446fb326}" DisplayName="Raum von " Format="DateTime" FriendlyDisplayFormat="Disabled"/>'
Add-PnPFieldFromXml -List $listName -FieldXml '<Field Type="DateTime" Name="EndDate" ID="{2684f9f2-54be-429f-ba06-76754fc056bf}" DisplayName="Raum bis" Format="DateTime" FriendlyDisplayFormat="Disabled" DefaultValue = ""/>'
```

I had the validation rule set with the following code, but it's basically the same if I create the rule manually. No surprise here :)

```
    # $clientContext = Get-PnPContext
    # $list = Get-PnPList $listName
    # $list.ValidationFormula = "=[Raum von]<[Raum bis]"
    # $list.ValidationMessage = "Please correct the Raum von/Raum bis entries."
    # $list.update()
    # $clientContext.ExecuteQuery()
```

Next, I have an SPFx  extension which allows users to copy selected items from one list to another list (the Termine list I created above). Both, the source and the target are in the same site. 
I'm not sure if it makes sense to share the whole solution with you? There's a similar example here https://github.com/pnp/sp-dev-fx-extensions/blob/main/samples/js-command-clone/src/extensions/spfxClone/SpfxCloneCommandSet.ts and the only difference is that in my case, the target list is another list. 

The important part is that the issue really only appears when the validation rule is defined. If I remove it, the app works again. If I add it again, it stops working, 

Running GET https://_tenantUrl_/sites/_siteName_/_api/web/lists/getByTitle('Termine')/ works fine and returns     `"ListItemEntityTypeFullName": "SP.Data.TermineListItem",` as it should

Not sure if it helped...?

**Comment by juliemturner** [comment]
@kkazala 
So, I tried to replicate this and could not, but... you have some fundamental problems with what you shared. PowerShell that you said you used to set the validation settings I believe would be wrong. When I set them in the UI manually it worked but only when I used the UI to create the validation and I think that's because you put a trailing space in your display name in the PowerShell script

`DisplayName="Raum von "`

This is what my validation looked like when I did it through the UI and when I did, I got no error, so I think that you have fundamentally something incorrect with your setup and once you fix that the code will work.

![image](https://user-images.githubusercontent.com/7570936/120043688-67ca0280-bfda-11eb-8473-0385092ef787.png)

**Comment by kkazala** [comment]
@juliemturner  You are absolutely right about the space after "von". It was a regression error, but it didn't make it to deployment- I have some calculated fields based on this column, so I caught this additional space really fast. 

I just made a new deployment with the "Ram von" without the white space, and the validation logic I pasted above. 
Now I have the "Raum von" field:
![image](https://user-images.githubusercontent.com/22429087/120481337-4c7f3e80-c3b0-11eb-88e0-68483b01af91.png)
the validation: 
![image](https://user-images.githubusercontent.com/22429087/120481418-615bd200-c3b0-11eb-8abe-fd8f8b003a9c.png)
which works, because I provision content and the formula caught wrong dates.

The SPFx app works for copying between the lists without the validation rule, but fails at the exact same place 
`let entityTypeFullName = await targetList.getListItemEntityTypeFullName();`
this time with another error:
```
parsers.js:130 Uncaught (in promise) Error: Error making HttpClient request in queryable [500] Internal Server Error ::> {"odata.error":{"code":"-2130575162, Microsoft.SharePoint.SPListDataValidationException","message":{"lang":"en-US","value":"List data validation failed."}}}
    at new HttpRequestError (parsers.js:130)
    at Function.<anonymous> (parsers.js:145)
    at step (tslib.es6.js:102)
    at Object.next (tslib.es6.js:83)
    at fulfilled (tslib.es6.js:73)
```
Would it help if I gave you access to my dev tenant so you can see it in action?

**Comment by patrick-rodgers** [comment]
Are you 100% certain it is failing on the line where it is getting the list item entity type? Because that is just a get request to the list and I wouldn't think any validation would run at that point. Are you trying to copy items to the list that do not meet the validation criteria? Can you capture a fiddler/browser trace of the actual network calls to see where it fails and validate the information being sent conforms to the validation criteria in the list?

**Comment by kkazala** [comment]
@patrick-rodgers  well... what can I say. You are both right... the call works and I was confused regarding the method that was throwing exception. I fixed my error handling :)
Thank you for your time!
