### ISSUE TITLE
Folder version end point implementation is missing

### ISSUE THREAD

**Issue by sankarkumar23** [pnp/pnpjs#1773]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Expected / Desired Behavior / Question
I do not see a good method to call the below REST API call.
The item is a Folder in a document library. Its working on browser and returning XML as output.
https://some.sharepoint.com/sites/sitename/_api/web/lists/getByTitle('libname')/Items(1)/Versions?$top=10&$select=Status,Created,Author&$orderby=VersionId%20desc&$filter=Status%20ne%20null

### Observed Behavior
I tried with .select("Versions").expand("Versions") but getting FileNotFound exception.. looks like this works only for documents.

Please let us know if I am missing something.

**Comment by koltyakov** [comment]
Hi @sankarkumar23,

How are you getting Folder's item with PnPjs? Here a working sample:

```typescript
const folder = sp.web
  .getFolderByServerRelativeUrl('/sites/ci/Shared Documents/345');
const item = await folder.getItem();
console.log(await item.versions.get());
```

![image](https://user-images.githubusercontent.com/7816483/119454645-6fbb4580-bd41-11eb-90c3-5e1d848d10aa.png)

**Comment by patrick-rodgers** [comment]
I do not believe folder has version information other than as @koltyakov points out through the underlying item.

**Comment by sankarkumar23** [comment]
Oh.. ok.. we can get through with folder.getItem(). I missed this.. It's all good then. Thank you for the sample.
