### ISSUE TITLE
sp.site.exists() doesn't work on pages which url contain dashes

### ISSUE THREAD

**Issue by sadomovalex** [pnp/pnpjs#1787]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

@pnp/sp 2.5.0

### Expected / Desired Behavior / Question
sp.site.exists() works on pages which url contains dashes

### Observed Behavior
sp.site.exists() ends with 403 System.UnauthorizedAccessException exception

### Steps to Reproduce
Run code which calls sp.site.exists(url) method on some page which contains dash: https://{tenant}.sharepoint.com/sites/mysitecol#/favorites

It will try to make HTTP POST calls to the following url in this case: https://{tenant}.sharepoint.com/sites/_api/contextinfo which is definitely not correct because https://{tenant}.sharepoint.com/sites is not correct url but managed path.

As workaround I've used API call instead of pnp js:
```js
let promise = context.spHttpClient.post(context.pageContext.site.absoluteUrl + "/_api/SP.Site.Exists",
  SPHttpClient.configurations.v1, {
  headers: {
    "accept": "application/json;"
  },
  body: JSON.stringify({
    url: s.url
  })
}).then((response: SPHttpClientResponse) => {
  response.json().then((exists: any) => {
    if (exists.value) {
      // site exists
    } else {
      // site doesn't exist
    }
  });
});
```

**Comment by koltyakov** [comment]
Hey Alex!

Do you mean hashes?
Are you providing SPFx context?

**Comment by patrick-rodgers** [comment]
Can you share an example of a url that doesn't work? You can make it up, but we need to see the full format that is giving you issues and so we can test.

As well, double check the [getting started section](https://pnp.github.io/pnpjs/getting-started/#establish-context), as @koltyakov mentions from your explanation it appears you haven't set context or a base url.

**Comment by sadomovalex** [comment]
hello, yes sorry - I meant hashes of course. In my post I've added example of url where issue was found:

https://{tenant}.sharepoint.com/sites/mysitecol#/favorites
or also with query string parameter
https://{tenant}.sharepoint.com/sites/mysitecol?foo=bar#/favorites

> Are you providing SPFx context?
I checked provided link now. I didn't set context before to use it - need to try that, thank you for hint.

**Comment by patrick-rodgers** [comment]
Hi @sadomovalex - yes please let us know if proper setup helps this issue. As for the "#" char, I am not sure that is a valid URL character within path. It is appended as an anchor so help me understand what you are reporting:

For https://{tenant}.sharepoint.com/sites/mysitecol#/favorites do you mean that to read Web URL "https://{tenant}.sharepoint.com/sites/mysitecol" and anchor "#/favorites"? If so, how are you setting the absolute base url for the library? That would come from the configuration.

**Comment by sadomovalex** [comment]
@patrick-rodgers sorry for delayed reply. Yes, suggestion to initialize context helped and it works correctly now! So we switched to sp.site.exists() now.

> For https://{tenant}.sharepoint.com/sites/mysitecol#/favorites do you mean that to read Web URL "https://{tenant}.sharepoint.com/sites/mysitecol" and anchor "#/favorites"? If so, how are you setting the absolute base url for the library? That would come from the configuration.

I didn't fully get your question but yes in url which looks like
https://{tenant}.sharepoint.com/sites/mysitecol#/favorites
part "https://{tenant}.sharepoint.com/sites/mysitecol" means site collection url (which is returned from SPFx context.pageContext.site.absoluteUrl) and "#/favorites" is anchor which is added by react Switch/Route component when user navigates through its tabs.
