### ISSUE TITLE
How to create a taxonomy term with version 2.x

### ISSUE THREAD

**Issue by DennisKuhn** [pnp/pnpjs#1790]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.5.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
Ability to add a taxonomy term to a termset.

### Observed Behavior
I can't find how to add a new term to a termset in version 2.5. Version 1 documentation still includes the possibility,

**Comment by juliemturner** [comment]
@DennisKuhn - Unfortunately, the new Taxonomy APIs are in beta and ever changing. We have not yet implemented some of these newer features that have been introduced. As you can see the Microsoft Graph beta endpoint now has support for create so you could certainly use that. 

https://docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-beta&tabs=http

**Comment by DennisKuhn** [comment]
@juliemturner thanks a lot for the pointer and keep up the awesomest work please :-)
