### ISSUE TITLE
Question using the addChunked method with sp-rest-proxy and local environment

### ISSUE THREAD

**Issue by michaelcmelton** [pnp/pnpjs#1797]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

Please specify what version of the library you are using: [2.5.0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

Question around using the addChunked Method for file upload, I'm utilizing the sp-rest-proxy along with pnpJS for a local React Environment setup. After running a test build, and deploying to our SPO instance, the addChunked method works wonders. In local development, there seems to be an issue where the addChunked method called contextInfo after the first add call, and never starts the startUpload call. It errors with a 403 on a call to contextInfo. I know for a fact this has something to do with our local setup, but the docs do not show how to properly setup PNPJS with a standalone React app outside of the SPFx ecosystem. Any help would be appreciated.

Thanks for all of your time in advance.

**Comment by patrick-rodgers** [comment]
As this questions relates to something outside of this library would suggest posting the question in [sp-rest-proxy](https://github.com/koltyakov/sp-rest-proxy/issues) issues list.

**Comment by koltyakov** [comment]
For the continue and finish methods PnPjs uses OData response parsing. So following requests end up being targeted not to the initial context but the actual SP/SPO endpoint and it's expected getting 403. @michaelcmelton please post an issue to the proxy's repo as @patrick-rodgers mentioned. I try not mutating responses in the proxy to represent identical behaviour as on a real environment but sometimes it is needed and feasible to add an exception to the responses transformation.
