### ISSUE TITLE
SP online returning only part of JSON?

### ISSUE THREAD

**Issue by wmertens** [pnp/pnpjs#1804]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.3.8 ]

Please specify what version(s) of SharePoint you are targeting: [ online ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

Can't do this right now but I'm pretty sure it's not related to version.

### Observed Behavior

Lately, we're often seeing JSON responses being cut off prematurely, mostly when POSTing to `getChanges`.

This code was working fine before, and suddenly these errors started appearing. Was there a change to SP online?

 ```
POST https://mysite.sharepoint.com/sites/foo/bar/_api/web/lists('3f93ebc3-f333-4333-8333-f333338bfe8a')/getchanges
  =>
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/sync/app/node_modules/.pnpm/@pnp/odata@1.3.8_a15ea9e35f8185850c85b3a619175833/packages/odata/src/parsers.ts:44:72
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  [stack]: 'SyntaxError: Unexpected end of JSON input\n' +
    '    at JSON.parse (<anonymous>)\n' +
    '    at /home/sync/app/node_modules/.pnpm/@pnp/odata@1.3.8_a15ea9e35f8185850c85b3a619175833/packages/odata/src/parsers.ts:44:72\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
  [message]: 'Unexpected end of JSON input'
```

**Comment by patrick-rodgers** [comment]
1.3.8 is a pretty old version at this point, would suggest updating when you get a chance.

If there are changes in SPO they would be outside out control. You can [report them here](https://github.com/SharePoint/sp-dev-docs/issues). We'll try and do a little investigation but if the server response changed we wouldn't have a path to resolution.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
