### ISSUE TITLE
Is there a way to get Shared Properties of a term using PnP JS?

### ISSUE THREAD

**Issue by sandeepvootoori** [pnp/pnpjs#1806]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.6.0      ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]

### Expected / Desired Behavior / Question
One of these below calls should return customProperties/sharedProperties
`const terms: ITermInfo[] = await sp.termStore.groups.getById(pGroup[0].id).sets.getById(requiredSet[0].id).children();
`
`const terms: ITermInfo[] = await sp.termStore.sets.getById(requiredSet[0].id).children.select('id','labels','customProperties','sharedProperties','localProperties','ShortName')();
`
       

### Observed Behavior

Not getting the data for custom properties
#

**Comment by patrick-rodgers** [comment]
I believe the properties you need to select are "properties" and "localProperties" which works.

So taking your code:

```
const terms: ITermInfo[] = await sp.termStore.sets.getById(requiredSet[0].id).children.select('id','labels','properties','localProperties','ShortName')();
```

**Comment by sandeepvootoori** [comment]
That worked, Thank you!!

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
