### ISSUE TITLE
[Graph] Support for $search parameter

### ISSUE THREAD

**Issue by JakeStanger** [pnp/pnpjs#1807]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.6.0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question

Documentation link: https://docs.microsoft.com/en-us/graph/query-parameters#search-parameter

I've just discovered Graph has support for a `$search` parameter which works on messages, people and directory objects (users/groups). I can immediately see use-cases for this so it'd be great to get it in here!

I'd be happy to take this on as a PR (or at least as much as I can) if needed/wanted. One sticking point:

Should the `.search` method exist regardless of endpoint being used and return errors where used incorrectly, or should it only appear where support exists? (I'm not sure on how possible this is in the library currently)

**Comment by patrick-rodgers** [comment]
We can have a look at adding it, would only want it to show up where it works vs. on all objects leading people to errors. If you want to have a swing at it, please do - always appreciate your help!

**Comment by JakeStanger** [comment]
I'm pretty swamped in work this week so I likely won't be able to have a look until next week, but if nobody's picked it up by then I'll have a play :+1:
