### ISSUE TITLE
How to get an invokable handle to web other than the current context

### ISSUE THREAD

**Issue by teresahoes** [pnp/pnpjs#1809]
## Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.6.0   ]

Please specify what version(s) of SharePoint you are targeting: [  1.12.1   ]

### Expected / Desired Behavior / Question
I am trying to access a different web than the current spfx context. i have tried both the Web('https://mysitehere.com') factory method and the sp.createIsolated().  when i call the await web() method - Both them will only return me an IWebInfo object with all the properties of the site rather than an invokable object so i cannot access the lists below the site.  So using this example below - i get an error **"isolatedSP.web.lists is not a function"** - and upon inspection, i do only see properties associated with the web.  

import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";

// create an isolated sp root instance
const isolatedSP = await sp.createIsolated();

// this configuraiton applies to all objects created from "isolatedSP"
isolatedSP.setup({
  sp: {
    baseUrl: "https://mytenant.sharepoint.com/sites/dev",
  },
});

// details for the lists at https://mytenant.sharepoint.com/sites/dev
const lists2 = await isolatedSP.web.lists(); <== fails

So my question is - am i missing some type library perhaps or have  you heard of this issue?  Here is my package.json dependencies

"dependencies": {
    "@microsoft/decorators": "1.12.1",
    "@microsoft/sp-core-library": "1.12.1",
    "@microsoft/sp-dialog": "1.12.1",
    "@microsoft/sp-listview-extensibility": "1.12.1",
    "@microsoft/sp-lodash-subset": "1.12.1",
    "@pnp/sp": "^2.6.0",
    "@pnp/telemetry-js": "^2.0.0",
    "crypto-js": "^4.0.0",
    "office-ui-fabric-react": "6.214.0",
    "react": "16.8.5",
    "react-dom": "16.8.5",
    "utf8": "^3.0.0"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "@microsoft/sp-build-web": "1.12.1",
    "@microsoft/sp-module-interfaces": "1.12.1",
    "@microsoft/sp-tslint-rules": "1.12.1",
    "@microsoft/sp-webpart-workbench": "1.12.1",
    "@types/chai": "3.4.34",
    "@types/es6-promise": "0.0.33",
    "@types/mocha": "2.2.38",
    "@types/node": "^14.14.6",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@types/webpack-env": "1.13.1",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1"
  }

**and tsconfig.json**
{
  "extends": "./node_modules/@microsoft/rush-stack-compiler-3.3/includes/tsconfig-web.json",
  "compilerOptions": {
    "target": "es5",
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "outDir": "lib",
    "inlineSources": false,
    "strictNullChecks": false,
    "noUnusedLocals": false,
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules/@microsoft"
    ],
    "types": [
      "es6-promise",
      "webpack-env",
      "node"
    ],
    "lib": [
      "es5",
      "dom",
      "es2015.collection"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx"
  ],
  "exclude": [
    "node_modules",
    "lib"
  ]
}

thank you in advance for any insight.

**Comment by patrick-rodgers** [comment]
Hi @teresahoes,

The following should work fine, just tested it as well to be sure:

```TypeScript
import { sp } from "@pnp/sp";
import { Web } from "@pnp/sp/webs";
import "@pnp/sp/lists";

// create a web queryable with a given url
const w = Web("https://absolute.url.com");

// read the lists information from that web
const lists = await w.lists();
```

I also to double check that we didn't have a bug in the isolated code (at least not affecting this):

```TypeScript
import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";

// create an isolated sp root instance
const isolatedSP = await sp.createIsolated();

// this configuraiton applies to all objects created from "isolatedSP"
isolatedSP.setup(        
    {
    sp: {
        baseUrl: "https://absolute.url.com",
    },
});

// details for the lists at https://mytenant.sharepoint.com/sites/dev
const lists2 = await isolatedSP.web.lists();
```

Can you please give either of those approaches a try and let us know how it goes? IF you just want to access another web, using the Web("url") pattern is probably easier.

**Comment by teresahoes** [comment]
thanks @patrick-rodgers  -- i did try both of those, neither worked which is why i was asking about maybe type version or something was wrong. I have finally got it working, it was some wrong package versions as it turned out. I am running on the latest of everything and all working now.  thanks
