### ISSUE TITLE
bookings

### ISSUE THREAD

**Issue by quantrpeter** [pnp/pnpjs#1814]
Hi
   It seems doens't have "bookings" yet, how can i call to a specific url like "https://graph.microsoft.com/beta/bookingBusinesses/QuantrBooking@quantr.hk/appointments" ?
thanks
Peter

**Comment by juliemturner** [comment]
You can use the graphGet method to execute any graph endpoint you'd like to...

This is not a documented method so use at your own risk, but it is how the internals of the library execute methods.

```
const appointments = await graphGet(GraphQueryable("https://graph.microsoft.com/beta/bookingBusinesses/QuantrBooking@quantr.hk/appointments"));
```
