### ISSUE TITLE
Too many request (429) error in .update() method of PnP js

### ISSUE THREAD

**Issue by manjeetjagtap** [pnp/pnpjs#1816]
We have a custom Import Excel SPFx app to read excel files and push this data to the SharePoint Online list.
We have tested this app and works very well for 6-7 months without any issues. 

Recently on the weekend (6/27/2021), user reported they were trying to import an excel file that has only 300 rows of data that needs to be imported into the SharePoint Online list. However, it was failing and throwing 429 errors which performing importing. So we also tried for less number of rows upto 100, but still it was failing with error code 429.

We are using Pnp/SP 2.0.3, (also tried 2.4.0 and 2.6.0)

### Observed Behavior
Getting error 429 and all subsequent requests were failing.

![image](https://user-images.githubusercontent.com/25087835/123843401-deab3180-d8df-11eb-895f-462310b0c468.png)

### Steps to Reproduce
I am still able to reproduce an issue if trying to import an excel file that pushes data to the SharePoint list.

**Comment by manjeetjagtap** [comment]
It has been mentioned pnp library included retry logic to handle 429, 503, and 504 errors. But still, we are getting 429 errors.
https://pnp.github.io/pnpjs/concepts/error-handling/

**Comment by juliemturner** [comment]
Getting a 429 error would imply that you're issuing too many requests. Although we do try and handle throttling it's usually best to try and avoid throttling. Since we're effectively just a proxy for the SharePoint API's it is entirely possible that the APIs can change without us being aware of it but I would suspect you would be better off trying to implement some batching to try and avoid the issue, have you looked at that yet ([batching example](https://pnp.github.io/pnpjs/concepts/configuration/#batching))?  Also, you might want to try and debug how many calls it will accept before it fails.

**Comment by manjeetjagtap** [comment]
> Getting a 429 error would imply that you're issuing too many requests. Although we do try and handle throttling it's usually best to try and avoid throttling. Since we're effectively just a proxy for the SharePoint API's it is entirely possible that the APIs can change without us being aware of it but I would suspect you would be better off trying to implement some batching to try and avoid the issue, have you looked at that yet ([batching example](https://pnp.github.io/pnpjs/concepts/configuration/#batching))? Also, you might want to try and debug how many calls it will accept before it fails.

After implementation batching, each batch has 10 requests to process. I used batching in two places. One for to fetch all from SharePoint to see if the item has already existed. And another one is to update that item.
Select batching works fine (I tested for 1316 number of rows data in excel). However, it still throttling for update batching.
![image](https://user-images.githubusercontent.com/25087835/124109224-e92b0f80-da34-11eb-8187-a471e0f67722.png)

![image](https://user-images.githubusercontent.com/25087835/124109248-f0521d80-da34-11eb-8ad0-ceeb4217b0fc.png)

**Comment by koltyakov** [comment]
AFAIK, batched requests counts the same as if they were called individually ending up making no difference to throttling limitations. 

@manjeetjagtap, are you sure that something else not started producing tons of requests in addition to your app?

Any retry logic on a client-side won't help lot if the nature of the app is to sent too many create/update calls.

**Comment by manjeetjagtap** [comment]
> AFAIK, batched requests counts the same as if they were called individually ending up making no difference to throttling limitations.
> 
> @manjeetjagtap, are you sure that something else not started producing tons of requests in addition to your app?
> 
> Any retry logic on a client-side won't help lot if the nature of the app is to sent too many create/update calls.

@koltyakov - I am batching 10 requests(create/update) in one go. And then another 10's of a batch to process. We don't have anything running which creates huge requests to SPO. We only get the throttled error when we run the app and start importing data. What would you suggest if we have to import such 10k-100k of rows of data?

**Comment by koltyakov** [comment]
The only way I know to load tons of data is to spread the loading in time and hitting throttling limitation less intense by moving the upload to the background job, which will stop any activity on 429 and continue after a suggested Retry-After. Background job would be more manageable as a user can't accidentally stop a process by closing a browser's page. Moving some non time critical uploads to a non working hours also might increase an API spot to vital operations.

**Comment by koltyakov** [comment]
PnPjs handles Retry-After header in retries logic. It comes in the response headers when 429 error happening. 
For the background job (server-side) processing you might want a custom retry logic. As with really many items sometimes you need to wait minutes and then continue.

**Comment by manjeetjagtap** [comment]
@koltyakov - I will try Retry-After. Could you please share some samples here? I believe the Retry-After number indicates seconds (not milliseconds )

**Comment by patrick-rodgers** [comment]
@manjeetjagtap - you don't need to do anything for Retry-After the library handles that for you. Getting lots of 429s means the service is throttling, nothing the library can do outside of retry and wait. As mentioned by others you might look for other things making lots of requests or a general spike in traffic. Have any new solutions been deployed lately that might be making lots of requests? Often something like a news webpart that checks for new articles continuously can lead to more load than one thinks.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
