### ISSUE TITLE
Set version number of schemaxml

### ISSUE THREAD

**Issue by jd215** [pnp/pnpjs#1821]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.6.0       ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online        ]

### Expected / Desired Behavior / Question

I'm trying to clone a site column using the element.SchemaXml from a source field so that I can create the new column using 

await sp.web.fields.createFieldAsXml(field.SchemaXml);

however, this gives the error _the object has been updated by another user since it was last fetched_ which apparantly has to do with a  Version='1' tag in the source xml. 

So.... how do I change the version number of the fetched schema xml?

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
You would need to use a library that parses XML or do string manipulation to properly describe the new field using XML. This library doesn't include XML editing capabilities.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
