### ISSUE TITLE
Is store.getTermsById supported in version 2?

### ISSUE THREAD

**Issue by jacksonv1lle** [pnp/pnpjs#1823]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version 2.0.6

Please specify what version of the library you are using: [ 2.0.6 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint online ]

### Question
The `sp-taxonomy` module in version 1 had a `store.getTermsById(termId1, termId2, termId3)` function. This was useful as you could load many terms using a single request regardless of what term set they belong to. Is this possible in version 2 of pnpjs?

I have seen another user [mention this missing feature here](https://github.com/pnp/pnpjs/issues/1224#issuecomment-796704544)

**Comment by patrick-rodgers** [comment]
No, as the underlying API doesn't support that method. What we can support matches what is available through the Graph Taxonomy API.
