### ISSUE TITLE
fields.addLookup displayname overwrites internalname

### ISSUE THREAD

**Issue by MudulOzan** [pnp/pnpjs#1825]
### Category
* [x]  Question

### Version
Please specify what version of the library you are using: [ ^2.5.0 ]

Please specify what version(s) of SharePoint you are targeting: [ sharepoint online ]

### Expected / Desired Behavior / Question
Hello, I want to create a lookup field using 
```sp.web.lists.GetByTitle("ListTitle").fields.addLookup(....``` 

When lookup created displayname overwrites internalname.  Are there any way to change displayname while adding lookup? 
 I couldn't find how to use ``createFieldAsXml``  with lookup

**Comment by koltyakov** [comment]
As a common trick it's possible to create with an internal name when rename a display name. Not elegant but simple. Otherwise a valid XML definition should be provided.

**Comment by MudulOzan** [comment]
Ah, sorry it is duplicate of #265, I am closing it
