### ISSUE TITLE
Get all folders,Subfolders,filesNames in folder for tree view

### ISSUE THREAD

**Issue by try4ajay** [pnp/pnpjs#1828]
### Category
- [ ] Question

### Question
* I needs to get folders subfolders and file names in a folder so that i can display as a tree view in the UI .

### Steps I tried
      const list = await sp.web.lists.getByTitle("Documents")
      console.log(list, "list---------------")

      const items = await list.getItemsByCAMLQuery({
        ViewXml: "<View><Query><Where><Eq><FieldRef Name='xyz'/><Value Type='Text'>006f000000Pe35wAAB</Value></Eq></Where></Query></View>"
      })
      console.log(items, "items-------------------------")

      var Item = items[0];
      console.log(Item, "Item-------------------------")

      var ItemID = Item.ID;
      console.log(ItemID, "ItemID-------------------------")
     // i want all the folders,subfolder and filenames of this item

      const itemfolder = await sp.web.lists.getByTitle("Documents").items.getById(ItemID).folder()
      console.log(itemfolder.Name, "itemfolderName---------------------")

      const itemfile = await sp.web.lists.getByTitle("Documents").items.getById(ItemID).folder.folders.getByName("Rent Rolls").select('File').expand('File').get()
      console.log(itemfile, "itemfile---------------------")

**Comment by koltyakov** [comment]
Hi there,

Please check docs for working with:
- [folders](https://pnp.github.io/pnpjs/sp/folders/)
- [files](https://pnp.github.io/pnpjs/sp/files/)

```typescript
import { sp } from '@pnp/sp/presets/all';

(async () => {

  const rootFolderPath = '/sites/site/Shared Documents';

  const folder = sp.web.getFolderByServerRelativeUrl(rootFolderPath);

  const files = await folder.files.select('Name,ServerRelativeUrl').get();
  const folders = await folder.folders.select('Name,ServerRelativeUrl,ItemCount').get();

  console.log({ files, folders });

})().catch(console.log)
```

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
