### ISSUE TITLE
Unhandled promise rejection when creating buffer from large file.

### ISSUE THREAD

**Issue by alex-simmons** [pnp/pnpjs#1833]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 2.7.0

Please specify what version(s) of SharePoint you are targeting: SharePoint Online 

### Expected / Desired Behavior / Question
Expect fetch errors to be passed up to my code or handled by library

### Observed Behavior
When file size is too large to create a buffer then I get a unhandled promise rejection even when wrapped in try-catch block

### Steps to Reproduce

Assuming file is a large file > 4294967295
```
async function testFunction(file) {
  try {
    const buffer = await sp.web.getFileById(file.UniqueId).getBuffer();
    // Do something with buffer...
  } catch (err) {
    console.log("caught error")
  }
}
```

**Comment by patrick-rodgers** [comment]
I don't have a good resolution for this, likely the answer is not to open 4 GB through the buffer. If you need to operate with files this size you could try the [stream support](https://pnp.github.io/pnpjs/nodejs/sp-extensions/#ifilegetstream) available in node.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
