### ISSUE TITLE
Getting all Lookup Options via GetLookupFieldChoices ?

### ISSUE THREAD

**Issue by Link631** [pnp/pnpjs#1836]
Hi,

I want to get all Lookup Field Choices. I checked the requests being made by the SharePoint default form. SharePoint simply sends a Request to 

_api/web/GetListUsingPath(DecodedUrl=@v1)/GetLookupFieldChoices(targetFieldName...) and with that call it gets all lookups.

How can I use this with pnpjs?

I can not find the GetLookupFieldChoices method.

If this is not included in pnp, how would you suggest to get all lookup values? Should I use RenderListDataAsStream?

Thanks

**Comment by juliemturner** [comment]
Unless there is something undocumented, I am not aware of an implemented helper function that does what you're asking for.  I do this a lot, but I just make a request to the related lists items and then store those in memory to use as the lookup values in my UI. https://pnp.github.io/pnpjs/sp/items/

**Comment by Link631** [comment]
Thanks for the reply. I guess I will use the renderListDataAsStream with paging capabilities to avoid list view thresholds.
