### ISSUE TITLE
some SPBatch requests hang forever when body is PassThrough

### ISSUE THREAD

**Issue by Gostron** [pnp/pnpjs#1837]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [@pnp/sp-commonjs@2.7.0]
Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

### Expected / Desired Behavior / Question
I'm using batches a lot to improve performance and get around throttling, but it hangs silently a lot while still doing the deed.
In NodeJS (10, 14 and 16 all have the issue), I use the "-commonjs" packets for SharePoint.
In this example, I query user properties (sp.profiles.getPropertiesFor), but it also works when creating fields or lists for example.

```
for (const user of users.slice(0, 10)) {
      sp.profiles.inBatch(batch).getPropertiesFor(`i:0#.f|membership|${user}`)
}
await batch.execute()
```
This just hangs forever. After 4 hours of debugging and investigation here are my conclusions:
- It hangs only when the result of the batch is a 'PassThrough' instance (in opposition to the zlib body type)
- It hangs in the `sp-commonjs/batch.js` file at the `fetchResponse.clone().text()` between 4 and 5 in the await case
- It does not hang if I remove the `.clone()` part
- Adding beforehand a `fetchResponse.clone().text().then(console.log)` actually displays the result correctly, but the code still hangs at the same location
- Making the `fetch` query (same url + options) myself in a reproduction project does not reproduce the issue
- Changing the fetching behavior in the sources of `sp-commonjs/batch.js` to be the manual `fetch()` from the reproduction project does not resolve the issue
- Changing node versions does not resolve the issue (I've tested with 10.24.1, 14.16.1 and 16.6.1)
- Changing Typescript versions does not resolve the issue (I've tested 4.3.5 and the latest 3)
- In my reproduction project I tried adding `tslib` to compile in a similar fashion, and still can't reproduce the issue
- The hanging actually occurs in the `node-fetch/index.js` `Body.prototype.text()` method, never resolving the promise within

### Observed Behavior
The application hangs

### Steps to Reproduce
Make a batch request of sp.profiles.getPropertiesFor() (works for several types of batch requests, but not for all, as it depends on the instantiation of the Response.Body to be 'PassThrough') and await it

It considered writing an issue to the `node-fetch` library, but I can't reproduce the issue without the @pnp/sp-commonjs library.

I am open to any suggestion. My only workaround is to modify the source to remove the `.clone()` method of the request, but that is not a viable solution.

I am having a hard time believing I am the only one with this kind of issue, please reassure me :)

Don't hesitate to ask for any more context or information.

**Comment by patrick-rodgers** [comment]
This is a bug specific to node-fetch, not a ton we can do about it.

I removed the clone from our code, hopefully that doesn't break anything else. Change will go out in 2.8
