### ISSUE TITLE
Batch fails with Invalid Request but individual links work fine

### ISSUE THREAD

**Issue by simkessy** [pnp/pnpjs#184]
### Category
- [ ] Enhancement
- [ ] Bug
- [ X] Question
- [ ] Documentation gap/issue

### Version 

Please specify what version of the library you are using: [   3.X   ]

I'm writting what I think should be a simple batch request into a list on a different site (same domain) to return various items filtered by a column identifier. 

The request returns 200 but each request itself fails. However, when I take a look at the payload requests, the GET url works perfectly fine. I can take it and paste it in the browser and get my response, however the batch fails and I'm not sure why. 

Here's what I'm doing: 

```
                    // Setup batch
                    var  webUrl = location.origin + config.SiteUrl;
                    var web = new $pnp.Web(webUrl);
                    var webBatch = web.createBatch();
                    r.projects = [];

                    // Create batch
                    var findProjects = function(projectID) {
                        web.lists.getByTitle(config.ListName)
                            .items.select("Title")
                            .filter("Project_x0020_ID_x0020__x0023_%20eq%2011159")
                            .inBatch(webBatch).get()
                            .then(function(item) {
                                console.log(item);
                                // r.projects.push(item);
                            })
                            .catch(function(e) {
                                    console.log(e.data.responseBody['odata.error'].message.value);
                            });
                };

                projectIds.map(findProjects);

                // Execute batch
                webBatch.execute().then(function() {
                    console.log("Batch completed");
                });
```

> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"Invalid request."}}}
> --batchresponse_8e3865af-c7cc-4e73-a033-9caac769aed6
> Content-Type: application/http
> Content-Transfer-Encoding: binary

> GET https://my.sharepoint.com/sites/QAI/_api/web/lists/getByTitle('Projects')/items?$select=Title&$filter=Project_x0020_ID_x0020__x0023_%20eq%2011159 HTTP/1.1
> accept: application/json
> content-type: application/json;odata=verbose;charset=utf-8
> x-clientservice-clienttag: PnPCoreJS:3.0.4

**Comment by koltyakov** [comment]
Hey @simkessy,

`sp-pnp-js` is not supported anymore and archived, there was a half-a-year notice and transition period. Please update to the `@pnp/pnpjs` to see if the issue remains first.

> The request returns 200 but each request itself fails

This is by design. As a batch contains a number of requests, some of them may end up with success, some may fail. When the batch is completed the library resolves individual promises, so the validate logic should be inside individual requests constructors.

Will the request work for you without batch?

```typescript
web.lists.getByTitle(config.ListName)
  .items.select("Title")
  .filter("Project_x0020_ID_x0020__x0023_ eq 11159")
  .get().then(console.log)
```

**Comment by simkessy** [comment]
Hi @koltyakov 

I'll work on updating today but I'm hoping I can get it working now. 

I did as suggested and ran the query without batching and that worked. Then I added that 1 query in a batch and that failed with the same issue as highlighted above.

**Comment by simkessy** [comment]
I updated to the bundle but I'm receiving the same error. 

Is it normal that when I go to, Request URL: https://mysite.sharepoint.com/sites/QA/_api/$batch

I get:

```
<m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<m:code>
-1, Microsoft.SharePoint.Client.ResourceNotFoundException
</m:code>
<m:message xml:lang="en-US">Cannot find resource for the request $batch.</m:message>
</m:error>
```

**Comment by simkessy** [comment]
👎 https://github.com/pnp/pnpjs/issues/82
