### ISSUE TITLE
Question about proper way to get HasUniqueRoleAssignments on a specific list

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1841]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     "@pnp/sp": "^2.6.0",    ]

Please specify what version(s) of SharePoint you are targeting: [    Online    ]

I know I'm 1 version behind but based on the behavior, I'm wondering if this is more a SharePoint thing vs this library.

### Expected / Desired Behavior / Question
I am just trying to find out if a list (by Title) HasUniqueRoleAssignments.
The easiest way I thought of is in the second screenshot...
Basically get the list by title and select "HasUniqueRoleAssignments".
Unfortunately that gives the wrong result (or maybe at least it's delayed somehow on the server side).

When I try the long way by
Getting all lists with my Title from the web object, and adding select "HasUniqueRoleAssignments"
I get expected "up to the second when I make the call" result.

NOTE:  Both screenshots were taken in the same debug 'pause'... so values I'm hovering on were fetched within a fraction of a second of each other.

![image](https://user-images.githubusercontent.com/49648086/128439792-8a3b0163-abe9-47cb-9759-be00fbd73399.png)

### Observed Behavior
If I already fetched the list object in the lines prior, then select "HasUniqueRoleAssignments", I get an incorrect (outdated) value.
Is there something inherently wrong with how I'm using this method?

![image](https://user-images.githubusercontent.com/49648086/128439801-4226827d-2293-4626-bc0a-55344653cb29.png)

### Steps to Reproduce
```typescript
            thisWebInstance = Web(webURL);
            if ( webOrList === 'list' ) {
                let thisListObject = thisWebInstance.lists.getByTitle( listTitle );

                //This call does not seem to provide the latest status of permissions..
                hasUniqueRoleAssignments = await thisListObject.select('Title,HasUniqueRoleAssignments').get();

                //This call seems to always return the most recent expected value.
                let tempThisList = await thisWebInstance.lists.select('Title,HasUniqueRoleAssignments').filter( `Title eq '${listTitle}'` ).get();

                hasUniqueRoleAssignments = tempThisList.length > 0 ? tempThisList[0].HasUniqueRoleAssignments : null;
                myPermissions.HasUniqueRoleAssignments = hasUniqueRoleAssignments.HasUniqueRoleAssignments;

                allRoleAssignments = await thisListObject.roleAssignments();
            } else {

                hasUniqueRoleAssignments = await thisWebInstance.select('HasUniqueRoleAssignments').get();
                myPermissions.HasUniqueRoleAssignments = hasUniqueRoleAssignments.HasUniqueRoleAssignments;

                allRoleAssignments = await thisWebInstance.roleAssignments();
            }
```

**Comment by koltyakov** [comment]
It might be caching issue. Could you please try adding `.query.set('t', new Date().getTime().toString())` ([more details](https://github.com/pnp/pnpjs/issues/160#issuecomment-793849161)) and check if `thisListObject.select` returns a right value?

**Comment by juliemturner** [comment]
I assume if you run this code multiple times it continues to give you the same result?

Have you tried making the call this way:

``` TypeScript
const listDetail = await thisWebInstance.lists.getByTitle(listTitle).select('Title,HasUniqueRoleAssignments').get<{Title: string, HasUniqueRoleAssignments: boolean}>();
console.log(listDetail.HasUniqueRoleAssignments);
```

**Comment by mikezimm** [comment]
@koltyakov , I finally got back to this after having a similar caching issue in another webpart.

Adding the query.set trick did fix the issue for me now.

However, I was wondering if this makes sense to you and given your knowledge of the library:

I ran the virtually the same call 2 different ways:
When using .select(), it consistently gave cached correct result.
When I removed the .select(), it consistently gave latest result (before adding your suggestion).
So nothing else was changed, and it was like a light-switch.

I would think if there were caching, **_it should at least be consistent_**?

## When USING .select() it consistently returned **cached result:**
See red arrow for LastUserModifiedDate (a week ago) and item count

![image](https://user-images.githubusercontent.com/49648086/133680000-9d22bf27-4a39-4eb8-8b74-bc1e6b708c02.png)

## When REMOVING .select() it consistently returned **latest result:**
See red arrow for LastUserModifiedDate (current date) and item count

![image](https://user-images.githubusercontent.com/49648086/133680060-117573a4-bd3d-497a-aee8-58fa4255f64e.png)
