### ISSUE TITLE
Cannot create folder using PnP OneDrive module

### ISSUE THREAD

**Issue by omarelanis** [pnp/pnpjs#1844]
### Category
- [ ] Enhancement
- [X] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.7.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Running the following command as per https://pnp.github.io/pnpjs/graph/onedrive/ should create a new folder

      const addFolder = await graph.me.drives.getById(myDrive.id).root.children.add('New Folder', <IDriveItem>{folder: {}});

### Observed Behavior
An error is displayed in the code:

Property 'add' does not exist on type 'IDriveItems'.ts(2339)

Checking IDriveItems.ts does in fact show there is no method for add

### Steps to Reproduce
Follow steps under the heading "Add folder or item" on page https://pnp.github.io/pnpjs/graph/onedrive/

**Comment by patrick-rodgers** [comment]
Not sure the exact history here, but something was missed as there is no add method. Unsure why the docs were updated but the methods weren't added. I am working on adding "add" and "addFolder" to driveitems, should be part of the next release. Thanks for reporting this!

**Comment by patrick-rodgers** [comment]
Fix will go our in 2.8 - there are a lot of ways to address drive items, so please let us know if you see any issues and we can investigate - but at least now there is an add method :)
