### ISSUE TITLE
SearchQueryBuilder, searching terms with GP0|# doesn't give any results

### ISSUE THREAD

**Issue by ferrarirosso** [pnp/pnpjs#1848]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.4.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
I have developed a webpart which searches for specific termstore terms using the following query syntax :
GP0|#guid
And it did work
I had now to update the webpart but was not able to get any results.
Using the sharepoint query tools, I was able to find that the terms are also exposed with the L0|#guid prefix (I didn't find any doc for this prefix)
Using the L0 prefix, I am getting the correct search results.

On other tenants, the GP0 prefix still works.

What is the correct way prefix to query terms through sharepoint search ?

### Steps to Reproduce
![Screenshot 2021-08-12 at 16 47 02](https://user-images.githubusercontent.com/5904018/129217803-262b5ae0-f0a6-4815-86d4-9712fa3cac49.png)

**Comment by ferrarirosso** [comment]
Any update on this ?

I just found another dev tenant which we use for user tests. It did work last week and now it only work when using L0.

Is this :
1. a persistent change which is rolling out ? If yes, how fast will this be deployed on all tenants ?
2. a temporary change, then when will the GP0... syntax be available ?

Can I rely on the L0|GUID Syntax because I did not find any hint somewhere on the internet ?

**Comment by juliemturner** [comment]
@ferrarirosso - I just want to set expectations on your questions as they not directly related to the pnpjs library, which is a community project not a Microsoft one and also is an abstraction layer.  We have no control how the underlying api's that we abstract. If you can replicate or share your issue using the API directly you might try to ask your question in sp-dev-docs, although I'm not sure what type of response you might get, but it is the more formal channel for your question. If you cannot then there may be an issue with our abstraction and then we could help you, but based on what you've shared thus far it doesn't seem like that's the case.

**Comment by ferrarirosso** [comment]
I have created a managed property and it works now as expected on every tenant.

I don't know why I did have these behaviour changes.

And thank you for your quick answer !
