### ISSUE TITLE
fetch linked Office 65 Group Id from Site

### ISSUE THREAD

**Issue by mdissel** [pnp/pnpjs#1849]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version
Sharepoint Online

### Expected / Desired Behavior / Question

How can i fetch the Office 365 Group ID that is linked to a Sitecollection?

**Comment by mdissel** [comment]
The rest API /_api/site is returning the GroupId.

**Comment by patrick-rodgers** [comment]
Great! Sorry for the delay in responding, making some time in the new year to catch up after a busy end of the 2021.

Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
