### ISSUE TITLE
Can this library be used for on-prem sharepoint? 

### ISSUE THREAD

**Issue by nddipiazza** [pnp/pnpjs#185]
### Category
question

Question: Can this library be used for on-prem sharepoint?

**Comment by koltyakov** [comment]
Hi @nddipiazza,

Yes, it can and welcomed to be used with SP 2013, 2016 and 2019. 

With old versions (i.e. 2013) some methods which were missed in the API (addChunked, renderListDataAsStream, batch api, etc.) will just not work and should not be used. 

Actually, almost every On-Prem project which we deliver for our clients uses PnPjs as a dependency, it’s a standard tool for our and many other teams I would say.

**Comment by nddipiazza** [comment]
Hey there @koltyakov thanks ! 

Let's say I'm using this project in a standalone nodejs application. How do I do the NTLM authentication? Is there an example?

**Comment by nddipiazza** [comment]
thanks!
