### ISSUE TITLE
Missing interface on teams ->  primaryChannel

### ISSUE THREAD

**Issue by raclettierer** [pnp/pnpjs#1855]
### Category
- [x] Enhancement

### Version

Please specify what version of the library you are using: [    2.0.11     ]
Please specify what version(s) of SharePoint you are targeting: [     SPO    ]

### Expected / Desired Behavior / Question
try to get the default channel of a team, but the interface is not implemented

https://graph.microsoft.com/v1.0/teams/6c1f36cc-f051-409c-bc23-31624067342c/primaryChannel

Doc: https://docs.microsoft.com/en-us/graph/api/team-get-primarychannel?view=graph-rest-1.0&tabs=http

Like to use it: 
const generalChannel = await graph.teams.getById(groupId).primaryChannel....
generalChannel.id.....

**Comment by patrick-rodgers** [comment]
Added for 2.11.0.
