### ISSUE TITLE
[taxonomy] method to get term set by name has been removed in pnpjsv2 ?

### ISSUE THREAD

**Issue by David74000** [pnp/pnpjs#1856]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version 

Please specify what version of the library you are using: [    2.8.0     ]

Please specify what version(s) of SharePoint you are targeting: [   SPO      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Hi,
I was using the PNP/JS v1 on a project where I used the following code to fetch a tanonomy termset by its name:
await currentStore.getTermSetsByName("MYTERMSETNAME", 1033).getByName("MYTERMSETNAME").get();

it works since it return all data I need. 

I was trying to update my PNP JS version to v2 but I can find any method allowing me to get a termset by its name.
I only found the sp.termStore.sets.getById("MYTERMSETID"). Does the method getByName has been remove on PNP JS v2 ?

### Steps to Reproduce

Thank you for your feedback!

**Comment by juliemturner** [comment]
Version 1 of the library uses old, deprecated APIs for the Termstore. Version 2 implemented the new "beta" endpoints for taxonomy.  They are not as robust feature wise as the old version. At this time we can only support what has been implemented by the platform and that is limited to what we have in the [documentation](https://pnp.github.io/pnpjs/sp/taxonomy/) which is loosely based on the [graph implementations of same](https://docs.microsoft.com/en-us/graph/api/resources/termstore-store?view=graph-rest-beta), although we're using the internal SharePoint endpoints to avoid authentication.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
