### ISSUE TITLE
ITermSet.getTermById(..) cannot be batched

### ISSUE THREAD

**Issue by yarick123** [pnp/pnpjs#1857]
### Category
- [ ] Enhancement
- [?] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.8.0   ]

Please specify what version(s) of SharePoint you are targeting: [ o365 ]

### Expected / Desired Behavior / Question
The sample is artificial, but it illustrates the problem.

```typescript
import { ITermInfo, ITermSet, sp, SPBatch } from '@pnp/sp-commonjs';
...
// in an async method:

const batch: SPBatch = sp.createBatch();
const termset = sp.termStore.sets.getById("43ff9e12-c335-47a0-a6fe-742add6f06ba");
const termInfoPromise = termset
	.getTermById("32607d10-9265-41db-90bb-a9bcbe2b90b9")
	.expand('parent')
	.select('id', 'labels')
	.inBatch(batch)
	.get();

await batch.execute(); // throws Bad Request error (400)

const termInfo = await termInfoPromise;
...
```

"await batch.execute();" should not throw an exception. termInfo should get the term data.

If ".inBatch(batch)" is commented, everything works. But, unfortunately, every term loading happens in a separated http request, as we do not use the batching functionality in this case.

### Observed Behavior

"await batch.execute();" throws an error like:

```
Error: Error making HttpClient request in queryable [400] Bad Request ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The expression \"v2.1/termstore/sets/43ff9e12-c335-47a0-a6fe-742add6f06ba/terms/32607d10-9265-41db-90bb-a9bcbe2b90b9\" is not valid."}}}
    at new HttpRequestError (c:\Users\asdf\Documents\Projects\g\g-nmapi\node_modules\@pnp\odata-commonjs\parsers.js:133:28)
    at Function.<anonymous> (c:\Users\asdf\Documents\Projects\g\g-nmapi\node_modules\@pnp\odata-commonjs\parsers.js:148:47)
    at step (c:\Users\asdf\Documents\Projects\g\g-nmapi\node_modules\tslib\tslib.js:143:27)
    at Object.next (c:\Users\asdf\Documents\Projects\g\g-nmapi\node_modules\tslib\tslib.js:124:57)
    at fulfilled (c:\Users\asdf\Documents\Projects\g\g-nmapi\node_modules\tslib\tslib.js:114:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  response: [Response],
  status: 400,
  statusText: 'Bad Request',
  isHttpRequestError: true
}
```

### Steps to Reproduce

initialize SP subsistem of pnp/js, set existing termset and term guids in the code above, execute.

**Comment by patrick-rodgers** [comment]
I think the issue here is that this request crosses api versions so can't be batched. termset requests are routed to v2.1 endpoints. I tried a few things but doesn't look like termset related requests can be batched currently.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
