### ISSUE TITLE
How to auth to SharePoint when using this library against On-prem sharepoint?

### ISSUE THREAD

**Issue by nddipiazza** [pnp/pnpjs#186]
Type: Question

The only examples that I can find online with this library use clientID/clientSecret authentication to sharepoint.

I am using OnPrem SharePoint and I want to write a standalone NodeJS program using pnpjs. 

How do you authenticate to SharePoint using Windows integrated auth (NTLM)?

I'm looking for something like this:

```
sp.setup({
    sp: {
        fetchClientFactory: () => {
            return new SPFetchClientNTLM("{netbios domain}\\{login name}", "{password}");
        },
    },
});
```

Does it exist? How else can I authenticate to a remote sharepoint instance using NTLM using pnpjs?

**Comment by koltyakov** [comment]
Hi @nddipiazza,

`@pnp/nodejs` (Node.js fetch factory) supports auths strategies for SPO, for NTML the 3rd party auth lib can be used. Please take a look at [this example](https://github.com/koltyakov/sp-pnp-node#factory-example).

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please _reopen_ if you require additional assistance. Thanks!
