### ISSUE TITLE
Cannot read property 'headers' of undefined when spfetchclient.js fetch request fails

### ISSUE THREAD

**Issue by jamie-pate** [pnp/pnpjs#1863]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
@pnp/nodejs-commonjs@2.8.0 

 Sharepoint in Microsoft 365  

### Expected / Desired Behavior / Question

When making requests using `IFolder.files()` when the network is not working properly the library throws `TypeError: Cannot read property 'headers' of undefined`

This is not a useful error, and the code should probably catch promise rejections from the `fetch()` call or propagate the error from fetch instead.

### Observed Behavior

The error occurs here: https://github.com/pnp/pnpjs/blob/84009ce6b8bb521bae3d8de679be42a7be84eb91/packages/nodejs/net/spfetchclient.ts#L60

The commonjs export is difficult to read and converts the await/async into some tslib generator mess :) but it looks like the `NodeFetchClient` class has a codepath that returns undefined if the error isn't one of the ones that it expects:
https://github.com/pnp/pnpjs/blob/84009ce6b8bb521bae3d8de679be42a7be84eb91/packages/nodejs/net/nodefetchclient.ts#L62

The real error is `FetchError: request to https://xyz.sharepoint.com/sites/SiteName/_vti_bin/client.svc failed, reason: getaddrinfo EAI_AGAIN xyz.sharepoint.com`

from man getaddrinfo:

```
EAI_AGAIN
              The name server returned a temporary failure indication.
              Try again later.
```

### Steps to Reproduce
Create an environment where DNS doesn't work?

I created program that uses @pnp/nodejs-commonjs and runs inside a docker container. Everything works if I use `docker run --network=host ...` but fails otherwise.

Dockerfile
```
FROM node:14-alpine

WORKDIR /opt/resource

ADD dist .
add node_modules ./node_modules
```

**Comment by jamie-pate** [comment]
It seems like this issue occurs in docker when you have suspended and resumed?

Restarting the docker service has solved my name resolution issue, but the pnp code remains broken for this situation.

https://stackoverflow.com/questions/51786057/name-resolution-failing-during-docker-build

**Comment by patrick-rodgers** [comment]
So if I read this correctly you see an issue when mid-request you suspend a docker container and then restart it? If you want to propose a fix as a PR we will review but this isn't something we are likely to spend time investigating.
