### ISSUE TITLE
PublicClientApplication.acquireTokenSilent - no_account_error 

### ISSUE THREAD

**Issue by nguyendn** [pnp/pnpjs#1864]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.8.0     ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]

```
"dependencies": {
    "@azure/msal-browser": "^2.16.1",
    "@microsoft/sp-adaptive-card-extension-base": "1.13.0-beta.17",
    "@microsoft/sp-core-library": "1.13.0-beta.17",
    "@microsoft/sp-property-pane": "1.13.0-beta.17",
    "@pnp/common": "^2.8.0",
    "@pnp/logging": "^2.8.0",
    "@pnp/odata": "^2.8.0",
    "@pnp/sp": "^2.8.0",
    "axios": "^0.21.1"
  },
```

#### Context

- I have an application that supports Microsoft Login. 

<img width="449" alt="Screen Shot 2021-08-25 at 9 54 09 PM" src="https://user-images.githubusercontent.com/1620357/130902977-c55d34a4-1ada-41fa-a7a9-7fb20f306dca.png">

- I'm building a SharePoint AdaptiveCard Extension. The extension will be a part of the Viva Connections Dashboard, which locates in MS Teams.

#### Task

I want to fetch an OAuth token for the Authorization Code Flow with PKCE like these documentations.

https://pnp.github.io/pnpjs/authentication/lambdaclient/
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-acquire-token?tabs=javascript2

My code is below:

```
const config: Configuration = {
        auth: {
            clientId: "<client_id>",
            authority: "https://login.microsoftonline.com/common/"
        }
      };
const msal = new PublicClientApplication(config);
const request = { scopes: ["openid", "email", "offline_access", "profile"] };
return msal.acquireTokenSilent(request).then((res) => console.log(res)).catch((err) => console.log(err));
````

When I run the code I had this error:

```
BrowserAuthError: no_account_error: No account object provided to acquireTokenSilent and no active account has been set. Please call setActiveAccount or provide an account on the request.
```

#### Question

1. Does the `@azure/msal-browser` support fetching OAuth Token like that? Did I misunderstand the library?
2. If I understand the library correctly, do you know what might be the root cause?

**Comment by patrick-rodgers** [comment]
Have you [reviewed the docs on MSAL auth](https://pnp.github.io/pnpjs/authentication/msaljsclient/)? We have a client specifically to support it.
