### ISSUE TITLE
SiteGroups - Is there a way to get user count when fetching the list of all groups in a site?

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1866]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    latest     ]

Please specify what version(s) of SharePoint you are targeting: [   SPO      ]

### Expected / Desired Behavior / Question
When fetching the list of site groups, I'd like to also get the user count  ( kind of like a library which as the item count right on the object ).  I am wondering if there is a way to get that using select?

All the documentation I have found suggests getting the group first, then fetching the users list.  Unfortunately this is pretty intensive when there are over 100 groups and I really don't need all the user data.  Just the count.

### Observed Behavior
Takes a long time to map through over 100 groups and get the users just to get a count.

### Steps to Reproduce
I'd like to get the user count when I run this command:
allGroups = await thisWebInstance.siteGroups.get();

The only way I have found so far is to run this on every group:
users = await thisWebInstance.siteGroups.getById( thisGroup ).users();

Thanks!

**Comment by juliemturner** [comment]
What you really need to check is the [Graph documentation](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0)... at a quick glance both members and owners supports expand, so that maybe indicates you could do what you're looking for but since I've never tried it, I'm not 100% sure... you're kind of looking for a way to combine expand with [count](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#count-parameter)... Maybe someone else has done it and can comment.

**Comment by mikezimm** [comment]
@juliemturner , that is correct... was looking for something like that.  I know there are sometimes properties that can be retrieved that are not included in the generic get(). 

I think an example of this was this issue https://github.com/pnp/pnpjs/issues/1552 where you replied but tavikukko's reply was the secret to success.

In this particular case, I also would like to stick with sp functions and not the graph.
```javascript
thisWebInstance = Web(webURL);
//Instead of this
allGroups = await thisWebInstance.siteGroups.get();
//Something like this
allGroups = await thisWebInstance.siteGroups.select("*,count").get();
```

or if there is a way to use sharepoint search and do something like this but modified for site groups?

```javascript
    sp.search(<ISearchQuery>{
        Querytext: `contentclass:STS_Site AND departmentId:{${departmentId}}`,
          SelectProperties: ["*","Title", "SPSiteUrl", "WebTemplate","departmentId","SiteLogo","SiteDescription",
          "ContentModifiedTime","LastModifiedTime", "LastModifiedTimeForRetention","ModifiedBy","Created","Modified","CreatedBy","CreatedById","ModifiedById"],
          "RowLimit": 500,
//          "StartRow": 0,
          "ClientType": "ContentSearchRegular",
          TrimDuplicates: false, //This is needed in order to also get the hub itself.
        })
          .then( ( res: SearchResults) => {
```

Thanks again

**Comment by juliemturner** [comment]
Ahh, ok, I wasn't following that you were asking about SharePoint Groups and not M365 Groups.  Ok, glad you solved it.

**Comment by mikezimm** [comment]
@juliemturner , actually I didn't solve the current question.  I was just showing how another challenge was solved by adding an unknown select property to the call.

I was just wondering if there was another property I'm not aware of that would give me the results through search.
