### ISSUE TITLE
SPFx Context is using /SitePages in the query parameters sometimes.

### ISSUE THREAD

**Issue by BrunoAlmeidaKotesky** [pnp/pnpjs#1867]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [**2.8.0**]

Please specify what version(s) of SharePoint you are targeting: [Sharepoint Online / SPFx 1.12.2]

### Expected / Desired Behavior / Question
The expected behavior is to always querying the absoluteUrl, not the Site Pages: Such as
`https://tenant.sharepoint.com/_api/web/lists/getByTitle(...)` and not `https://tanant.sharepoint.com/SitePages/_api/web/lists/getByTitle('')`
### Observed Behavior
This may be a duplicate of https://github.com/pnp/pnpjs/issues/1184, but i tried to reproduce, but it didn't work.
This is very strange, sometimes the api calls the correct URI (without the site pages), but sometimes it doesn't.
The code is on onInit() mehtod

```ts
await super.onInit();
console.log(this.context.pageContext.web.absoluteUrl) //Logs the correct absolute URL
sp.setup({
      sp: {
        baseUrl: this.context.pageContext.web.absoluteUrl,
      },
     //Also tried with spfxContext: this.context.pageContext.legacyPageContext
    //Also tried with spfxContext: this.context
    });
```
![errorPnp](https://user-images.githubusercontent.com/41238306/131388353-8322e35b-a76e-4373-8492-4082734e02bb.png)

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making a suggestion or asking a question delete this section.*

Make an api call like sp.web.lists.getByTitle('') when the webpart is inside a site page.

**Comment by juliemturner** [comment]
So wait, are you in the SharePoint framework? It appears so but maybe I'm missing something. Anyway, if that is the case then you should only be calling:

`sp.setup({ spfxContext: this.context });`

**Comment by BrunoAlmeidaKotesky** [comment]
I've already tried to use only this.context, but it didn't work as well, and yes i am using SPFx for taht.

I don't know if that could help somehow,
What i tried is to log the spfxContext, and in the init method it looks something like this, note the absoluteUrl is null:
![image](https://user-images.githubusercontent.com/41238306/131397054-60c9d556-c96b-4b51-95fd-32d4fa57bebf.png)

So ok, i have a generic class that make's some calls to the api, it happens way after the initialization, and i am using the imported sp object, `import {sp} from '@pnp/sp'`. The context seens to be null in that case.
<img width="180px" src="https://user-images.githubusercontent.com/41238306/131397211-97959b4e-d355-4281-bd38-0a3a40b6f831.png"/>
<img width="200px" src="https://user-images.githubusercontent.com/41238306/131397217-2fa9d4dc-137f-42d3-938e-64b8cc71d68b.png"/>

**Comment by juliemturner** [comment]
Well... I'm at a loss as this is not something I've ever seen or heard of. How are you debugging this?

**Comment by BrunoAlmeidaKotesky** [comment]
I am debugging with Brave Browser.
It really doesn't seen to be a bug related to pnp/sp itself, but probably something with yarn/node, as the user @JakeStanger mentions on his closed issue https://github.com/pnp/pnpjs/issues/1621

**Comment by juliemturner** [comment]
Ok... so, I'm not sure what to say but (assuming you're not using the graph portion of the library) then you only need @pnp/sp in your package.json as a dependency... I will also say I gave up a very long time ago on yarn and pnpm because of odd issues popping up, but have no more insight than that.

**Comment by BrunoAlmeidaKotesky** [comment]
Yeah, somethings simply does'nt make sense.
I guess i really had the same issue that i mentioned, after a hard cache reset on every module, it started to work 🙄 again.
I'll be closing this issue, thx for the attention.
