### ISSUE TITLE
From SP api response to Custom Model

### ISSUE THREAD

**Issue by nicholasp** [pnp/pnpjs#187]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.1.3 ]
"@pnp/sp"

### Question
Its not exactly question for the pnp itself but I face this problem. I am not very familiar with the syntax but i would like to do a service method that returns a specific model.

My model is:
export class Task {
  id: number;
  title: string;
  date: Date;
  user: string;
  userId: number;
}

I use the pnp sp for the sp api call (getTasks) and i made a maping so i can make my custom array from the sharepoint response

return response.map(field => {
            return {
              id: field.Id,
              title: field.Title,
              date: new Date(field.TaskDate),
              user: field.CreatedById,
              userId: field.CreatedById
            };
          });

I tried to force the return as <Task[]> but it seems its type of void | Task[] so i getting the following error:

Type 'void | Task[]' is not assignable to type 'Task[]'

![image](https://user-images.githubusercontent.com/876585/43516156-60de5342-958d-11e8-9f1b-3dbefb6e8c99.png)

any thoughts ?

**Comment by koltyakov** [comment]
Hi @nicholasp,

 `get` method uses generics and expected types can be bound like `list.items.get<Type[]>().then(...)`.

I.e.:

```typescript
import { sp } from '@pnp/sp';

interface ITaskOdata {
  Id: number;
  Title: string;
}

interface ITask {
  id: number;
  title: string;
}

(async () => {

  const list = sp.web.lists.getByTitle('ID3Vnext');
  const map = (data: ITaskOdata[]): ITask[] => {
    return data.map(({ Id: id, Title: title }) => {
      return { id, title };
    });
  };
  const items = await list.items.select('Id,Title').get<ITaskOdata[]>().then(map);

  console.log(items);

})();
```

**Comment by nicholasp** [comment]
thanks!

**Comment by patrick-rodgers** [comment]
Going to close this as answered. If that is not the case please _reopen_ the issue so we can continue assisting. Thanks!
