### ISSUE TITLE
Get member of a Team

### ISSUE THREAD

**Issue by raclettierer** [pnp/pnpjs#1872]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: ["@pnp/graph": "2.8.0",]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online]

### Expected / Desired Behavior / Question
I try to get the members of a teams (owner and members). In the graph explorer I can use the following url.
https://graph.microsoft.com/v1.0/teams/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/members

I want the same in pnpjs and I found the following API

 const member =  (await graph.teams.getById(groupId)()).members;

But the members are always empty

Following code not working :
- await graph.groups.getById(groupId).expand('members')();
- await graph.teams.getById(groupId).select('members')();

How do I can load the members of a team like the graph url it does ??

### Observed Behavior

I like to get the member with following code:
const teamMembers =  graph.teams.getById(groupId).members();

**Comment by juliemturner** [comment]
Unfortunately for some reason group membership didn't end up in the docs. I've updated it: https://pnp.github.io/pnpjs/graph/groups/#group-membership

You just need to adjust your call slightly and make sure you have the right imports.

**Comment by raclettierer** [comment]
@juliemturner Thanks for your response.
But I need the members from the graph.teams api and not from graph.group api. 
->  graph.**teams**.getById(groupId).members();

**Comment by juliemturner** [comment]
At the team level, group membership and team membership would be the same.  We can look into adding chat and channel membership in the future but do not have it now. We also take contributions so we'd be happy to accept a pull request if you'd like to add it yourself. In the mean time, if you want to make that call specifically you can do so by using the following technique:

`const teamMember = graphGet(GraphQueryable(graph, "/teams/{group-id}/members"));`

**Comment by raclettierer** [comment]
The response via teams api is easier with the roles. Via Graph you have double the user as owner and members ... 

Thanks for help.
