### ISSUE TITLE
Navigatedevent does not fire on search

### ISSUE THREAD

**Issue by jaluguri** [pnp/pnpjs#1873]
### Category
- [ ] Enhancement
- [ x ] Bug
- [ x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.11 ]

Please specify what version(s) of SharePoint you are targeting: [  SPO       ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Observed Behavior
I expect the navigated event to fire when a user is navigating from a SP page including when a user is searching from the top site search section. The user goes to _layouts/15/search.aspx/?q=test, The application customizer exists on this page. The same navigated event works when navigating to other pages. 

### Steps to Reproduce
Attached is the screenshot, 
- Add navigated event in onint method. 
- validate if this fires when navigating in the same site to a different page. 
- now search using the top search control and the same navigatedevent does not fire.

**Comment by juliemturner** [comment]
@jaluguri  I think you really need to post this question to the [sp-dev-docs repo](https://github.com/SharePoint/sp-dev-docs/issues) as this is a question about the SharePoint Framework not about PnPjs.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
