### ISSUE TITLE
Enhancement: Upgrade to msal.js 2.0

### ISSUE THREAD

**Issue by EldinHb** [pnp/pnpjs#1879]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.8.0]

Please specify what version(s) of SharePoint you are targeting: [not relevant]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

Are you guys planning to update MSAL to version 2.x for the MsalClient? PnPJS uses [the deprecated msal](https://www.npmjs.com/package/msal) package. [This](https://www.npmjs.com/package/@azure/msal-browser) is the new one.

A significant amount of our users seem to use Safari and they encounter [this bug](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Known-issue-on-Safari) with ADAL or MSAL >2. MSAL 2.x is supposed to fix this issue. 

And Microsoft and Google are planning to provide a similar feature in their respective browsers like Safari.

More information: https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas

Thank you for your feedback!

**Comment by juliemturner** [comment]
We only provide an authentication layer for MSAL for Node are using almost the most current released version (version 1.3.1 dropped only 7 days ago).  So, I think you are mistaken about it being deprecated. https://www.npmjs.com/package/@azure/msal-node.  

That said you may be experiencing an issue with the SharePoint platform itself... Can you share more information about the code you're specifically having problems with?

**Comment by juliemturner** [comment]
Oh, ok, you're saying you're specifically creating a separate authentication using that package then and working outside of SharePoint/SPFx?  I.e. you're following this setup? https://pnp.github.io/pnpjs/authentication/msaljsclient/

**Comment by EldinHb** [comment]
Hi Julie, Ive made a very barebones webpart where the issue is replicated. It does a simple call to Graph groups and displays the group displaynames. https://github.com/EldinHb/PnPIssueRepro

When you visit a sharepoint page with this webpart on safari the page will refresh once and show this error in the console log: 
<img width="1206" alt="Screenshot 2021-09-16 at 10 39 27" src="https://user-images.githubusercontent.com/8807015/133620033-ffe32052-a9d1-4953-90fb-20773cc6e323.png">

After the refresh the behavior is as normal. The issue is not in PnP but in an old version of msal or adal implicit login flow. I think the issue will be resolved if pnp would use msal 2.0, though you guys are obviously better judges for that.

**Comment by EldinHb** [comment]
Ah, thanks for the information. Ill definitely follow your suggestion.
