### ISSUE TITLE
Role Definition getByType documentation

### ISSUE THREAD

**Issue by MudulOzan** [pnp/pnpjs#1889]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.8.0 ]

Please specify what version(s) of SharePoint you are targeting: [ Sharepoint Online ]

### Expected / Desired Behavior / Question
In the get by type section it should be 
const def = await sp.web.roleDefinitions.getByType(5)();

### Observed Behavior
Instead it is shown as below
const def = await sp.web.roleDefinitions.getByName(5)();

I found getByType in the type files yet in the documentation it is written as getByName

Link: https://pnp.github.io/pnpjs/sp/security/#role-definitions

**Comment by Abderahman88** [comment]
@juliemturner I confirm this bug. Can you assign to me?

![image](https://user-images.githubusercontent.com/36161889/135914552-e9e39333-e0f9-495c-a89a-bd6d82fdef68.png)

**Comment by juliemturner** [comment]
you can just submit a PR to fix it, we don't really do assignments.  Just remember to mention #1889 in your PR.

**Comment by Abderahman88** [comment]
Good to know. Thanks 👍
