### ISSUE TITLE
Is it possible to post a message to a channel?

### ISSUE THREAD

**Issue by rajivsr23** [pnp/pnpjs#1895]
### Category

- [ x] Question

### Expected / Desired Behavior / Question

I want to post a message to a channel Reference: [https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&tabs=javascript](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&tabs=javascript) Is it possible?

**Comment by patrick-rodgers** [comment]
Yes it is possible, but we don't currently have the methods/types built out to support it. We can look to add it in v3 or if you have time and want to submit a PR adding this capability for v2 we're happy to review. Thanks!

**Comment by patrick-rodgers** [comment]
We will look to expand graph support in v3 and include the teams messaging methods.

**Comment by juliemturner** [comment]
I'm going to close this issue as completed. If you have further issues, please feel free to create a new issue and reference this one.
