### ISSUE TITLE
Problem with urls when updating list item

### ISSUE THREAD

**Issue by yenoh2** [pnp/pnpjs#190]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.1.3-1]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
When executing update on an "Item", it will use the url supplied, to the "Web" instance that was originally used to retrieve the list item, as the base url.  I also expect that the url will automatically include "_api", if it is not in _parentUrl or _url.  

### Observed Behavior
When I get a list item, the _parentUrl and _url properties of the Item object, are relative to the current site (of the page url), and when I try to perform an update on the item, it returns me the error message "_site/Web/Lists(guid'491ec82d-102c-4583-990b-93ddb71b4d49')?$select=ListItemEntityTypeFullName 404 (NOT FOUND)_", because "_api" is omitted and it is using the current site url, instead of using the specified site in the variable "environment.baseUrl".  As you can see below, my SharePoint 2013 on Premise environment returns the relative url without "_api".  When I modified the Item "_url" and "_parentUrl" variable in the console to include the proper subsite path and "_api/", then executed the Item update it worked.  
![image](https://user-images.githubusercontent.com/23555613/43644024-87f4d630-972d-11e8-9c55-9d7a81d5054a.png)

This issue appears to be similar to [issue](https://github.com/SharePoint/PnP-JS-Core/issues/517) and its fix.  

### Steps to Reproduce

Using SharePoint 2013 on Premise environment.  
This is a code example I am using:
```
web = new Web(environment.baseUrl)
    web.lists
      .getByTitle('Outage_Users')
      .items.select('Title')
      .get(spODataEntityArray(Item))
      .then((items: Item[]) => {
        items[0].update({Title: "New Title"})
        return items
      })
  }
```

**Comment by patrick-rodgers** [comment]
This is fixed now in dev branch, debating an out of band release since this affects a lot of stuff inside the library.
