### ISSUE TITLE
Jest test case compilation throws error with imports from latest pnp/sp modules (2.9.0)

### ISSUE THREAD

**Issue by in8rakda** [pnp/pnpjs#1900]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.9.0 ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Jest test case should compile without any errors.
Please find below test file:
/// <reference types="jest" />
import * as sinon from 'sinon';
import { IService } from '../Service/IService';
import { CalendarProvider } from '../BAL/CalendarProvider';
import { MockService } from '../Service/MockService';
import { ICategoryListItem, IHolidayListItem } from '../controls/Calendar/ICalendarInternalProps';
import { IStreamCategoryTimeLineListItem } from '../webparts/calendar/components/ITimeLineViewProps';
import { calendar } from 'CalendarWebPartStrings';
import { Items } from '@pnp/sp/items';

describe('CalendarProvider', () => {

    let pnpItemsGetAllStub: sinon.SinonStub;
    let mockService: IService;
    let calendarProvider: CalendarProvider;
    beforeEach(() => {
        mockService = new MockService(null, true, 5000);
        calendarProvider = new CalendarProvider(mockService, null);
        pnpItemsGetAllStub = sinon.stub(Items.prototype, 'getAll');
    });

    afterEach(() => {
        pnpItemsGetAllStub.restore();
    });

    /** this test to validate getCategoryLists method */
    it('getCategoryLists', async () => {
        const listName: string = 'categoryList';
        const mockCategoryListItem = await mockService.getCategoryLists(listName);
        pnpItemsGetAllStub.resolves(mockCategoryListItem);
        const categoryListItem: ICategoryListItem[] = await calendarProvider.getCategoryLists(listName);
        pnpItemsGetAllStub.resolves(categoryListItem);

        expect(categoryListItem.length).toBe(mockCategoryListItem.length);
        expect(categoryListItem[0].eventCode).toBe(mockCategoryListItem[0].eventCode);
        expect(categoryListItem[1].eventColorCode).toBe(mockCategoryListItem[1].eventColorCode);
    });

Package.json:

"dependencies": {
    "@microsoft/sp-core-library": "1.12.1",
    "@microsoft/sp-lodash-subset": "1.12.1",
    "@microsoft/sp-office-ui-fabric-core": "1.12.1",
    "@microsoft/sp-property-pane": "1.12.1",
    "@microsoft/sp-webpart-base": "1.12.1",
    "@pnp/common": "^2.9.0",
    "@pnp/logging": "^2.9.0",
    "@pnp/odata": "^2.9.0",
    "@pnp/polyfill-ie11": "^2.0.2",
    "@pnp/sp": "^2.9.0",
    "@pnp/spfx-controls-react": "^3.3.0",
    "@pnp/spfx-property-controls": "^3.2.0",
    "luxon": "^2.0.2",
    "moment-timezone": "^0.5.33",
    "office-ui-fabric-react": "^7.176.2",
    "react": "16.9.0",
    "react-dom": "16.9.0"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-3.7": "0.2.3",
    "@microsoft/sp-build-web": "1.12.1",
    "@microsoft/sp-module-interfaces": "1.12.1",
    "@microsoft/sp-tslint-rules": "1.12.1",
    "@microsoft/sp-webpart-workbench": "1.12.1",
    "@types/react": "16.9.36",
    "@types/react-dom": "16.9.8",
    "@types/webpack-env": "^1.13.1",
    "ajv": "~5.2.2",
    "gulp": "~4.0.2",
    "jest": "^27.2.2",
    "jest-junit": "^12.3.0",
    "sinon": "^11.1.2",
    "ts-jest": "^27.0.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "transformIgnorePatterns": [
      "/node_modules/(?!${esModules})"
    ],
    "transform": {
      "^.+\\.(js|ts|tsx|jsx)$": "ts-jest"
    },
    "testMatch": [
      "**/src/**/*.test.+(ts|tsx|js)"
    ],
    "collectCoverage": true,
    "coverageReporters": [
      "json",
      "lcov",
      "text",
      "cobertura"
    ],
    "coverageDirectory": "<rootDir>/jest",
    "moduleNameMapper": {
      "\\.(css|less|scss|sass)$": "identity-obj-proxy",
      "office-ui-fabric-react/lib/(.*)$": "office-ui-fabric-react/lib-commonjs/$1"
    },
    "reporters": [
      "default",
      "jest-junit"
    ],
    "coverageThreshold": {
      "global": {
        "branches": 90,
        "functions": 90,
        "lines": 90,
        "statements": 90
      }
    }
  },
  "jest-junit": {
    "output": "./jest/summary-jest-junit.xml"
  }

### Observed Behavior
While I try to run npm test, I receive below syntax error:
\node_modules\@pnp\sp\items\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import "./list.js";
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

       7 | import { IStreamCategoryTimeLineListItem } from '../webparts/calendar/components/ITimeLineViewProps';
       8 | import { calendar } from 'CalendarWebPartStrings';
    >  9 | import { Items } from '@pnp/sp/items';

The code was running fine with @pnp/sp version: 1.3.8 but with upgrade to latest version and performing selective imports throws the above error.

### Steps to Reproduce
 For pnp/sp version 2.9.0
Use import { Items } from '@pnp/sp/items' in test case file and refer the Items using pnpItemsGetAllStub = sinon.stub(Items.prototype, 'getAll');

Please refer the test case and package.json mentioned above.

Please let me know where I'm going wrong with the above test case.
Thank you for your feedback!

**Comment by MudulOzan** [comment]
@patrick-rodgers I have the same problem maybe this topic is relevant to this issues?
#1058 #1199 #1425

**Comment by patrick-rodgers** [comment]
I would suggest [checking with the Jest team](https://github.com/facebook/jest/issues) for guidance as debugging Jest isn't something we will take on.
