### ISSUE TITLE
Is it possible to use current pnpjs to get Hub of Hubs info?

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#1902]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    latest     ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]

### Expected / Desired Behavior / Question
Can we today ( or are there plans to be able to ) access the new Hub of Hubs data?
[Hub of Hubs Docs](https://docs.microsoft.com/en-gb/SharePoint/hub-to-hub-association#add-links-to-hub-associations-to-hub-site-navigation)

Given the docs show a way easily add all child hub links to  navigation, They must have a fast way to get the info.

### Observed Behavior
I'm guessing maybe we just add a new Select field but I have no clue.  Just asking.

This is what I'm using today to get my associated hubsite info: 

```typescript
import { sp } from "@pnp/sp";

//https://sharepoint.stackexchange.com/questions/261222/spfx-and-pnp-sp-how-to-get-all-sites
//Just had to change SearchQuery to ISearchQuery.

import { ISearchQuery, SearchResults, ISearchResult } from "@pnp/sp/search";

import { IHubSiteWebData, IHubSiteInfo } from  "@pnp/sp/hubsites";
import "@pnp/sp/webs";
import "@pnp/sp/hubsites/web";

export function getAssociatedSites(departmentId: string, callback: any, entireResponse: any , custCategories, hubsCategory, ascSort: boolean, newData ) {

    //var departmentId = departmentId;
    // do a null check of department id
    //366df2ee-6476-4b15-a4fd-018dfae71e48 <= SPHub

    //Sort ascending by default
    let sortDirection = ascSort === false ? 1 : 0;

    console.log('current department ID:', departmentId );

    /**
     *  Updated search query per pnpjs issue response:
     *  https://github.com/pnp/pnpjs/issues/1552#issuecomment-767837463
     * 
     * GET Managed properties here:  https://tenanat-admin.sharepoint.com/_layouts/15/searchadmin/ta_listmanagedproperties.aspx?level=tenant
     */
    sp.search(<ISearchQuery>{
        Querytext: `contentclass:STS_Site AND departmentId:{${departmentId}}`,
          SelectProperties: ["*","Title", "SPSiteUrl", "WebTemplate","departmentId","SiteLogo","SiteDescription",
          "ContentModifiedTime","LastModifiedTime", "LastModifiedTimeForRetention","ModifiedBy","Created","Modified","CreatedBy","CreatedById","ModifiedById"],
          "RowLimit": 500,
//          "StartRow": 0,
          "ClientType": "ContentSearchRegular",
          TrimDuplicates: false, //This is needed in order to also get the hub itself.
        })
          .then( ( res: SearchResults) => {
    
            console.log('associated sites with URL/Desc', res);
            console.log(res.RowCount);
            console.log(res.PrimarySearchResults);
            entireResponse.hubs = res.PrimarySearchResults;

            entireResponse.hubs.map( h => {
                h.sourceType = hubsCategory;
            });
            callback( entireResponse, custCategories, newData );

    });

    return;

}
```

**Comment by bcameron1231** [comment]
You can find all of the hubs in a hub of hubs by pulling the "RelatedHubSites' property from a hub directly. This value is a semi-colon delimited string of IDs of IDs for all hubs (including the parent hub id).


Outside of the Search API, this data is also available on the web object. RelatedHubIds and ParentHubSiteId are available.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
