### ISSUE TITLE
[2.9.0] [Graph] `search` query incorrect wraps in double quotes

### ISSUE THREAD

**Issue by JakeStanger** [pnp/pnpjs#1903]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.9.0]

Please specify what version(s) of SharePoint you are targeting: [SPO, Graph]

### Expected / Desired Behavior / Question

The query should not be entirely wrapped in double quotes as this is invalid syntax.

### Observed Behavior

Search queries are always wrapped in double quotes, regardless of whether they should be or not.

### Steps to Reproduce

Use search query on directory object, correctly wrapping clause in quotes:

```ts
graph.users
  .search('"displayName:john"')
  .get();
```

Observe 400 error as this is invalid syntax:

```
https://graph.microsoft.com/v1.0/users/$search=""displayName:john""
```

---

This is caused by one of my own additions [here](https://github.com/pnp/pnpjs/blob/e24e8134590b473256878992256b3e548a0e298a/packages/graph/graphqueryable.ts#L281) and is a very simple fix, BUT doing so would technically be a breaking change*. I can see that this is fixed in V3, so I'm logging it here for posterity.

\* if you feel different I'll happily submit a PR

A workaround is to just set the search query yourself:

```ts
const request = graph.users
  .search('"displayName:john"');
request.query.set('$search', '"displayName:john"');
request.get();
```

**Comment by juliemturner** [comment]
Hey @JakeStanger thanks for pointing it out.  Since I'm in the code base prepping for 2.10 release I figured it's best to just fix it, since it's so simple... Thanks!!
