### ISSUE TITLE
PnP Js CopyByPath and MoveByPath in SPOnline in SPFx Webpart

### ISSUE THREAD

**Issue by Somanathan1987** [pnp/pnpjs#1904]
Hi 
We are using PNP js for copying file from one site collection to another site collection but it is working fine for full control users  but it is not working for Contribute with no delete custom permission level users permission.

Issue : It is not overwriting more than one time and getting access denied error
Expected result: It has create incremental version whenever copy is doing.
Note:
Need to know permission limitations for both CopyByPath and MoveByPath in PNPJs in SPFx .

**Priority : High**

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
