### ISSUE TITLE
Recycle bin?

### ISSUE THREAD

**Issue by wmertens** [pnp/pnpjs#1907]
### Category
- Question

### Version

Please specify what version of the library you are using: [    2    ]

Please specify what version(s) of SharePoint you are targeting: [    online & 2013     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question

I found the `.recycle()` function, but I'm not seeing a way to list items in the Recycle Bin and undelete them using the library. The URLs are a bit weird and I wonder if it's possible to do this, even with a workaround somehow? I would only need it for an automated test.

**Comment by juliemturner** [comment]
So there is a RecycleBin property on web.

Via a rest api I can see that both of these work but I don't think the library has exposed those endpoints... or at least I don't see them on my first scan through. I can look into it.

https://contoso.sharepoint.com/sites/PnPJS/_api/web/RecycleBin
https://contoso.sharepoint.com/sites/PnPJS/_api/site/RecycleBin

**Comment by patrick-rodgers** [comment]
We can look to add it, but will be super low priority behind all the v3 work. Especially as the use case here to to automate tests.

**Comment by patrick-rodgers** [comment]
A possibility to add for v3.

**Comment by patrick-rodgers** [comment]
Going to move this to help wanted. Happy to accept a PR for this functionality.

**Comment by wmertens** [comment]
Thanks! ❤️
