### ISSUE TITLE
Issue with SearchResult interface ViewsLifetime property

### ISSUE THREAD

**Issue by c-eiser13** [pnp/pnpjs#191]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  @pnp/sp 1.1.3-1       ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
In a new office 365 tenant, and a secondary one that I checked, the ViewsLifetime property is returned as spelled here (lower case t in time). In the SearchResult interface the property is spelled ViewsLifeTime (capital T). Expect to be able to use this property but returns an undefined result because of the spelling difference.

### Observed Behavior
I am not certain this is a bug and I am relatively new to typescript and the @pnp/sp library. I am helping my team move from AngularJS to Angular 6 and we have an Angular CLI application that is configured to work with @pnp/sp library. We are trying to access the ViewsLifetime property and when we try and access the property name associated with the SearchResult interface (with the capital T), the result is undefined. However in dev tools, we can see the property is there, but with a lowercase t. Please see below screens (querytext was removed because of URL):

When using the property name provided by the interface:

![5](https://user-images.githubusercontent.com/42096464/43687697-6ee5fafc-989f-11e8-93b4-9a8379f14555.PNG)

In dev tools, this property is undefined:

![4](https://user-images.githubusercontent.com/42096464/43687701-7e399d56-989f-11e8-89e8-b0bc202be6fa.PNG)

In dev tools you can see the property contains the lowercase t:

![2](https://user-images.githubusercontent.com/42096464/43687573-c7135204-989c-11e8-9ce8-c87c570b3d99.PNG)

If I change it to the correct spelling:

![1](https://user-images.githubusercontent.com/42096464/43687559-9ce241d4-989c-11e8-8332-e2c34244aeb9.PNG)

I was able to get around this by extending the SearchResult interface and including a property of ViewsLifetime. 

![3](https://user-images.githubusercontent.com/42096464/43687597-4eea5b5a-989d-11e8-9fc6-218bcd91c8f9.PNG)

I'm not certain is this is the recommended approach, or not, but it is working correctly now. I have not yet tried accessing custom managed properties, but is extending the interface the way to do so? The documentation does not have examples of accessing properties.  Thanks again for this library, it has made our transition much easier.

### Steps to Reproduce
1. Create new Angular CLI application
2. Setup a service and install pnp libraries. 
3. Create a basic query and include ViewsLifetime property.

If more info or screenshots are needed, let me know. Thanks!

**Comment by koltyakov** [comment]
Thanks, it's definitely a typo in `SearchResult` interface.

**Comment by koltyakov** [comment]
Fixed within the PR. Please use your workaround before the update is published.

**Comment by c-eiser13** [comment]
@koltyakov Thanks for the quick response!
