### ISSUE TITLE
Update Web Title with member user only updates the user's web title

### ISSUE THREAD

**Issue by cneSPFX0815** [pnp/pnpjs#1912]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.9.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
When updating a webs title with a user with member permissions, this only updates the user's web title and not the web title.

I'm using the following code:
`
let myWeb= Web(webUrl);
myWeb.update({ Title: title })then(() => { resolve(true); return; }).catch(() => { resolve(false); return; });`

When i execute the code with a user with admin rights (Member of owner group or site collection administrator) the title of the web is updated and all user see the new title. When executing the code with a user with member rights (member of member group) the title is updated for the user, but not for all users. Only the current user see's the new title, all other user see the old title.

Maybe this an issue with rest api of SP Online and not with PNPJS...

### Observed Behavior
When executing the code with a user with member or owner rights (member of member group) the title is updated for all users.

### Steps to Reproduce

see Expected / Desired Behavior / Question

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
