### ISSUE TITLE
Calling file.getItem() directly after uploading the file causes a timeout

### ISSUE THREAD

**Issue by krystianfowler** [pnp/pnpjs#1914]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.9.0     ]

Please specify what version(s) of SharePoint you are targeting: [  online   ]

### Expected / Desired Behavior / Question
Uploading a file to sharepoint will result in receiving a file object. Calling file.getItem() on this directly after uploading the file should work so that the file ID on sharepoint can be checked. 

### Observed Behavior
Calling file.getItem() directly after uploading the file will cause a timeout. 

### Steps to Reproduce
Code below always results in a timeout on file.getItem()
```
  const { file } = await sp.web
      .getFolderByServerRelativeUrl('/sites/krystian-test/Shared Documents/Test')
      .files.configure({ headers: { 'Content-Length': `${size}` } })
      .add('pug.jpg', stream, true);

      const fileMetadata = await file.getItem();
```

In my testing this always resulted in a timeout. 

On the other hand if another method is used to access file data it will work. For comparison the code below called right after uploading works fine.
```
  const fileMetadata = await sp.web
    .getFileByServerRelativeUrl(
      '/sites/krystian-test/Shared Documents/Test/pug.jpg'
    )
    .getItem();
```

**Comment by brightchip** [comment]
Can you post the parts of how you upload a file ?  Why mine got 403 when I can upload without the package. But I have to use it as it supports chunks uploading.
What is `.files.configure({ headers: { 'Content-Length': `${size}` } })` Can I put `authentication Bear ${token}` here too ?

**Comment by juliemturner** [comment]
I'm fairly sure that when working on V3 @patrick-rodgers found that the stream code wasn't working and rewrote it, but I could be mixed up...

**Comment by aaademosu** [comment]
I had a similar experience debugging the library to resolve SP list item threshold if i call the getItem function after a file upload.

@Dzieni i was able to reproduce the error using the snippet you provided. The test results can be seen in the [gist](https://gist.github.com/aaademosu/8db670a080d996cfed367b80b71c3e52)

I have been able to patch the library to resolve this issue and would submit a PR that hopefully closes this.
