### ISSUE TITLE
Does getItemsByCAMLQuery support ProjectedFields?

### ISSUE THREAD

**Issue by PowellT** [pnp/pnpjs#1928]
Trying to use getItemsByCAMLQuery (in a spfx webpart), doing a join of two lists, which seems to work, but ProjectedFields never works, I am wondering if it is supported?  I could find no examples.  Any help greatly appreciated!

snippet:

const caml: ICamlQuery = {
    ViewXml: "<View><ViewFields><FieldRef Name='ID' /><FieldRef Name='Changereq' /><FieldRef Name='Title' /></ViewFields><Joins><Join Type='LEFT' ListAlias='Change Requests'><Eq><FieldRef Name='Changereq' RefType='Id' /><FieldRef Name='ID' List='Change Requests' /></Eq></Join></Joins><ProjectedFields><Field ShowField='Title' Type='Lookup' Name='Ed' List='Change Requests' /></ProjectedFields></View>",

### Category
- [ ] Enhancement
- [ ] Bug
- [ X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     latest    ]

Please specify what version(s) of SharePoint you are targeting: [    Online     ]

**Comment by koltyakov** [comment]
Hi @PowellT,

Last time I used advanced CAML DSL features I did it via `renderListData` and `renderListDataAsStream`.

**Comment by PowellT** [comment]
Hey @koltyakov 
Thank you so much for your response, this definately helps.  I will give renderListDataAsStream a go

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
