### ISSUE TITLE
Add item comments with mentions not working

### ISSUE THREAD

**Issue by fonbrauzen** [pnp/pnpjs#1933]
### Category
- [ ] Enhancement
- [ x] Bug
- [ ] Question
- [ x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.10.0 ]

Please specify what version(s) of SharePoint you are targeting: [ SPO ]

### Observed Behavior
from docs:
```TypeScript
// or you can add it as an object to include mentions
item.comments.add({ text: "comment from object property" });
```
but in types there:
```TypeScript
add(info: string | ICommentInfo): Promise<IComment & ICommentInfo>;
//and interface is:
export interface ICommentInfo {
    author: ICommentAuthorData;
    createdDate: string;
    id: string;
    isLikedByUser: boolean;
    isReply: boolean;
    itemId: number;
    likeCount: number;
    listId: string;
    mentions: {
        loginName: string;
        email: string;
        name: string;
    } | null;
    parentId: string;
    replyCount: number;
    text: string;
}
```
the question is - how I can post a new comment with mentions with an id, which does not yet exist?

### Expected / Desired Behavior
make most of props of this interface optional or use for adding another interface where will be needed only text and mentioned, e. g. used in spfx reusable controls:
```TypeScript
const addComment = useCallback(
    async (comment: IAddCommentPayload): Promise<IComment> => {
      const spHttpClient = serviceScope.consume(SPHttpClient.serviceKey);
      if (!spHttpClient) return;
      const _endPointUrl = `${
        webUrl ?? _webUrl
      }/_api/web/lists(@a1)/GetItemById(@a2)/Comments()?@a1='${listId}'&@a2='${itemId}'`;
      const spOpts: ISPHttpClientOptions = {
        body: `{ "text": "${comment.text}", "mentions": ${JSON.stringify(comment.mentions)}}`,
      };
      const _listResults: SPHttpClientResponse = await spHttpClient.post(
        `${_endPointUrl}`,
        SPHttpClient.configurations.v1,
        spOpts
      );
      const _commentResults: IComment = (await _listResults.json()) as IComment;
      return _commentResults;
    },
    [serviceScope]
  );
// where mentions & text come from:
export interface IAddCommentPayload {
  text: string;
  mentions: IAddMention[];
}
export interface IAddMention {
  email: string;
  name: string;
}
```

### Steps to Reproduce
try to post new comment with mentions
```TypeScript
await  item.comments.add({ text: comment, mentions: mentions });
//where mentions
//ICommentInfo.mentions
 const mentions = {loginName: user.LoginName, email: user.Email, name: user.Title };
```

**Comment by fonbrauzen** [comment]
Also, mentions might be array, or? Just one of the implementations (working one) is with an array...

**Comment by juliemturner** [comment]
@fonbrauzen 

This `add(info: string | ICommentInfo)` construct in typescript means of type string or type ICommentInfo... so you can essentially pass the string, like the docs say or construction an object of type ICommentInfo and pass that.

You cannot add a comment to an item that doesn't exist yet.  So that's the short answer.

Effectively you're going to have to add the item like this:

``` TS
   const iar: IItemAddResult = await sp.web.lists.getByTitle("My List").items.add({
       Title: "Title",
       Description: "Description"
   });
   // you can add a comment as a string
   const comment1 = await iar.item.comments.add("string comment");

   // or you can add it as an object to include mentions
   const comment2 = await iar.item.comments.add({ text: "comment from object property" });
```

**Comment by fonbrauzen** [comment]
@juliemturner I have an item, the question is, how to post a comment with mention? With example above it's not possible. Also object if I set there the proper type have lots of mandatory fields, which are not needed for creation

**Comment by juliemturner** [comment]
Sorry this 
>`the question is - how I can post a new comment with mentions with an id, which does not yet exist?` 

made me think that your question was you didn't have a list item yet.  I'm still not sure I follow the problem but maybe it's because the interface doesn't make the fields optional? 
If that's the case, have you tried just setting them to null or undefined? I honestly have never used this interface so I'm not sure how it works but if they are optional then obviously an enhancement could be made to make them thus.

**Comment by fonbrauzen** [comment]
@juliemturner "because the interface doesn't make the fields optional" - probably.
I think should be 2 adjustments:

1. make interfaces for comment creation:
```TypeScript
export interface ICommentCreationInfo {
    text: string
    // it's totally possible to have multiple mentions, so I think here and in original interface should be array.
    mentions?: ICommentMention[] | null;
    // not sure about this one, for items it's not visible in UI anyway, might be relevant only for pages
    isReply?: boolean; 
}
export interface ICommentMention {
// not sure if we need login, because in example above it works just fine without it
   loginName?: string;  
   email: string;
   name: string;
}
``` 
2. ICommentInfo interface leave for getting info about existing comments (and change their mentions to an array)

In ICommentInfo probably almost everything is fine, it's just relevant for existed comments.

**Comment by juliemturner** [comment]
Ok, well we'd have to test it out but likely would only go the route of making parameters optional vs adding extra interfaces. I cannot promise when we'd get to it.  In the mean time i would test out adding parameters with null values and see if that doesn't work for you.

**Comment by patrick-rodgers** [comment]
I marked the interface Partial in the add method making all the props optional.

You can always get around typing issues by casting as <any> so things like this shouldn't be a blocker, but good to get the cleaned up in the library.
