### ISSUE TITLE
Update Modern Site Page page Author by line  using pnpjs 

### ISSUE THREAD

**Issue by shashank11sharma** [pnp/pnpjs#1943]
Modern pages have a field called _AuthorByLine. When we set the value of this field of a page to the login name (or the email address) of a user, we will see the user details appear in the page header byline. However, as soon as we edit the page those details disappear.

we can set the author byline of a modern SharePoint page using PnP PowerShell.

How we can set author byline using pnp js ..

**Comment by patrick-rodgers** [comment]
As [covered in the docs](https://pnp.github.io/pnpjs/sp/clientside-pages/#get-set-author-details). Just tested and works as expected.
