### ISSUE TITLE
Can't add item to SP 2013 On-prem

### ISSUE THREAD

**Issue by MudulOzan** [pnp/pnpjs#1944]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   ^2.10.0      ]

Please specify what version(s) of SharePoint you are targeting: [    2013 On-Prem     ]

### Expected / Desired Behavior / Question
```js
web.lists.getByTitle("ListName").items.add({Title:"test title"})
```
to add the item to my custom list

### Observed Behavior
Instead, I had a get result selecting the field ListItemEntityTypeFullName
No idea why I achieved to add the item to my other list, I can't add items to my newly created lists. (maybe there is some config that our company did that I don't know)

### Steps to Reproduce
The code I provide doesn't work as intended or I am missing something. I tried with postman adding content-type ``application/json;verbose=odata`` and adding ``__metadata: {type:"SP.List"}``  solved for postman. I know I could do 
```js
sp.setup({
    sp: {
        headers: {
             Accept: "application/json;odata=verbose"
        }
    } 
})
```
however I would like to learn it well. Am I on the right track with this?

**Comment by koltyakov** [comment]
Hi @MudulOzan,

The setup/headers section has a issue. Should be instead:

```typescript
sp.setup({
  sp:{
    headers: {
      "Accept": "application/json; odata=verbose"
    }
  }
});
```

**Comment by MudulOzan** [comment]
> Hi @MudulOzan,
> 
> The setup/headers section has a issue. Should be instead:
> 
> ```typescript
> sp.setup({
>   sp:{
>     headers: {
>       "Accept": "application/json; odata=verbose"
>     }
>   }
> });
> ``` 

Sorry, I forgot to add accept. Is it mandatory to add accept header? I worked on sharepoint online mostly. I don't know how 2013 and on prem works. Can you enlighten me please?

**Comment by koltyakov** [comment]
In SP 2013 there is no OData extensions installed by default. So switching to `odata=verbose` is mandatory.
In SPO, the default is `odata=minimalmetadata` which is a bit more effective.

**Comment by MudulOzan** [comment]
> In SP 2013 there is no OData extensions installed by default. So switching to `odata=verbose` is mandatory. In SPO, the default is `odata=minimalmetadata` which is a bit more effective.

Thank you, I am going to close this now. Finally, I ended up with adding my defined headers to the chained function like this: ``web.lists.configure({headers}).items.add...``

**Comment by MudulOzan** [comment]
@koltyakov may I ask one more thing? I have 2 custom lists, one of them requires this header but the other does not? What may cause this?

 I am pretty confused I have to add headers for one custom list but not the other.

**Comment by MudulOzan** [comment]
> Theoretically it won't work in SP 2013 until WCF OData Extensions are installed in the farm.
> 
> Can it be that sp.setup is called in multiple places? E.g. 1) setup with verbose; 2) 1st list query; 3) breaking setup; 4) call to 2nd list.

Alrighty, I clearly see now sp.setup was called in multiple places. Great thanks for your efforts. Much appreciated!
