### ISSUE TITLE
Batch recycling fails with 400 Bad Request

### ISSUE THREAD

**Issue by johannes-z** [pnp/pnpjs#1948]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.11.0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
I'm trying to delete multiple items in a batch request, using this code:

```js
  const batch = webRef.createBatch()
  itemId.forEach(itemId => listRef.items.getById(itemId).inBatch(batch).recycle())
  return batch.execute()
```

### Observed Behavior
I get a 400 Bad Request (`Microsoft.SharePoint.Client.InvalidClientQueryException`) in the Response of the batch request. I did a comparison with the request that's sent, when you delete multiple files in a document library. As far as I can tell, the only thing that's different is, that pnpjs doesn't include `Content-Length` nor `Content-Transfer-Encoding` in the batch header.

#### SharePoint
```
--batch_6f84b544-e5e8-4d63-b0b9-386328123daf
Content-Type: multipart/mixed; boundary="changeset_9622eee3-532b-42a2-beaa-f67bd8f20aa9"
Content-Length: 740
Content-Transfer-Encoding: binary

--changeset_9622eee3-532b-42a2-beaa-f67bd8f20aa9
Content-Type: application/http
Content-Transfer-Encoding: binary

POST https://TENANT.sharepoint.com/sites/SITE/_api/web/Lists(@a1)/GetItemById(@a2)/recycle?@a1='%7B46DC66B3%2D6963%2D4E46%2DB16A%2DD7CE6673125D%7D'&@a2='37' HTTP/1.1
Content-Type: application/json;odata=verbose

--changeset_9622eee3-532b-42a2-beaa-f67bd8f20aa9
Content-Type: application/http
Content-Transfer-Encoding: binary

POST https://TENANT.sharepoint.com/sites/SITE/_api/web/Lists(@a1)/GetItemById(@a2)/recycle?@a1='%7B46DC66B3%2D6963%2D4E46%2DB16A%2DD7CE6673125D%7D'&@a2='39' HTTP/1.1
Content-Type: application/json;odata=verbose

--changeset_9622eee3-532b-42a2-beaa-f67bd8f20aa9--

--batch_6f84b544-e5e8-4d63-b0b9-386328123daf--
```

#### pnpjs
```
--batch_85111688-a077-4779-a700-2b5eb62741e6
Content-Type: multipart/mixed; boundary="changeset_9fc8c6bf-dd7f-4b31-9a2d-f27d62fb77f2"

--changeset_9fc8c6bf-dd7f-4b31-9a2d-f27d62fb77f2
Content-Type: application/http
Content-Transfer-Encoding: binary

POST https://TENANT.sharepoint.com/sites/SITE/_api/web/getList('%2Fsites%2FSITE%2FLIBRARY')/items(37)/recycle HTTP/1.1
accept: application/json
content-type: application/json;odata=verbose;charset=utf-8
x-clientservice-clienttag: PnPCoreJS:@pnp-2.11.0:batch
x-pnpjs-tracking: i.recycle

--changeset_9fc8c6bf-dd7f-4b31-9a2d-f27d62fb77f2
Content-Type: application/http
Content-Transfer-Encoding: binary

POST https://TENANT.sharepoint.com/sites/SITE/_api/web/getList('%2Fsites%2FSITE%2FLIBRARY')/items(39)/recycle HTTP/1.1
accept: application/json
content-type: application/json;odata=verbose;charset=utf-8
x-clientservice-clienttag: PnPCoreJS:@pnp-2.11.0:batch
x-pnpjs-tracking: i.recycle

--changeset_9fc8c6bf-dd7f-4b31-9a2d-f27d62fb77f2--

--batch_85111688-a077-4779-a700-2b5eb62741e6--
```

### Steps to Reproduce
Execute the code above.

**Comment by juliemturner** [comment]
The issue of course is that batching in V2 is a generic solution to batch any requests.  It appears that you're finding that the recycle method requires custom headers and so effectively you would need a custom implementation of batching to support this. Certainly, that's an enhancement that could be made but given where we are with V3 it's my opinion that we wouldn't try and address it in V2 but rather it could be addressed in V3 either in the batching behavior or in a more specialized batching behavior.

**Comment by johannes-z** [comment]
Is there an easy way to add these custom headers manually, while still using the `inBatch` method`. Normal queries can have custom headers by chaining `configue`.

**Comment by juliemturner** [comment]
Batching in V2 is a beast... I would have to dig into the source code to figure that out.. and then test it, which I can do but not sure exactly when I'll have the time.  You can certainly try it out.

**Comment by patrick-rodgers** [comment]
Retested this in v3 and cannot duplicate the issue. Unsure what changed/was fixed/is different, but based on the information shared here I no longer believe this is an issue.

```TS
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/batching";


const itemIds = [
  10,
  11,
  12,
  13,
  14,
  15,
]

const [batched, execute] = sp.batched();

const list = batched.web.lists.getByTitle("Generic");

itemIds.forEach(itemId => list.items.getById(itemId).recycle())

try {
      
  await execute();

} catch (e) {

  console.error(e)
}

```

**Comment by johannes-z** [comment]
@patrick-rodgers Nice! I will try v3 in the future, but I'm not quite ready yet to upgrade. As per my initial post, I think the only thing different was the missing `Content-Length` and `Content-Transfer-Encoding` when batch recycling via pnpjs. Are those headers included now in v3? If not, it must be something else 🤔

**Comment by patrick-rodgers** [comment]
They are not included.

**Comment by patrick-rodgers** [comment]
Going to close this, if you get a chance to try it out for v3 and still see issues please let us know. Thanks!
