### ISSUE TITLE
Get item version

### ISSUE THREAD

**Issue by mame13fr** [pnp/pnpjs#195]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ last version ]

------------------

Hi all,

I have a question, I want to get all version of an sp list item (SP2013)

My code is : 
```
public getVersions(idList: string, idListItem: number): void {

        const list = pnp.sp.web.lists.getById(idList);
        const item = list.items.getById(idListItem);

        item.versions.get().then(ver => {            
                console.log(JSON.stringify(ver, null, 4));
            });
    }
```

But the error message is : 
{"error":{"code":"-1, Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"fr-FR","value":"La ressource est introuvable pour la demande versions."}}}

If anyone have an idea to help me... :)

Thanks a lot !!!

**Comment by koltyakov** [comment]
Hi @mame13fr,

Versions REST API is absent in SP 2013, it was introduced not far ago in SPO.

**Comment by mame13fr** [comment]
Oh ok :(

Do you have an another way to get version ?

Thanks a lot !!

**Comment by patrick-rodgers** [comment]
A quick search brought up [this article](https://stackoverflow.com/questions/24423657/sharepoint-2013-get-splistitem-versions-via-rest) which outlines a few techniques. Unfortunately there isn't an easy way to achieve this in SP2013.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. If you need further assistance, please _reopen_ the issue. Thanks!
