### ISSUE TITLE
getAllChildrenAsOrderedTree does not returns reused terms

### ISSUE THREAD

**Issue by MichielLeysen** [pnp/pnpjs#1950]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.11.0 ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I want to get all child terms of a termset, via the "getAllChildrenAsOrderedTree" method, and I want to receive all terms, including reused terms. 

### Observed Behavior
The "getAllChildrenAsOrderedTree" returns all child terms, that are created directly underneath this termset, but the reused terms are not included. 

### Steps to Reproduce
Create a termset, add some reused terms into this termset, and try to get all terms via the getAllChildrenAsOrderedTree method. 

Thank you for your feedback!

**Comment by juliemturner** [comment]
Can you validate that the "reused terms" show up in the set you're passing to getAllChildrenAsOrderedTree?

**Comment by MichielLeysen** [comment]
@juliemturner If i get all terms from the selected termset, the reused terms are indeed included in the result.

**Comment by juliemturner** [comment]
Um... that *may* be the answer to my question but I'm not sure.  What I'm asking is, if based on this sample:
https://pnp.github.io/pnpjs/sp/taxonomy/#getallchildrenasorderedtree
As an example this line:
`const childTree = await sp.termStore.groups.getById("338666a8-1111-2222-3333-f72471314e72").sets.getById("338666a8-1111-2222-3333-f72471314e72").getAllChildrenAsOrderedTree();`

What I'm asking is if you make this call (leaving off the getAllChildrenAsOrderedTree):
`const childTree = await sp.termStore.groups.getById("338666a8-1111-2222-3333-f72471314e72").sets.getById("338666a8-1111-2222-3333-f72471314e72")`

Are all the "reused terms" in that resultset?

**Comment by MichielLeysen** [comment]
@juliemturner  Below you can find my sample code


  public async LoadFieldOptions(termSetId:string):Promise<any>{
    let ts = await sp.termStore.groups.filter("scope eq 'siteCollection'").get();
    const childTree = await sp.termStore.groups.getById(ts[0].id).sets.getById(termSetId).getAllChildrenAsOrderedTree();
    console.log(childTree);
    const childTree2 = await sp.termStore.groups.getById(ts[0].id).sets.getById(termSetId).terms();
    console.log(childTree2);
    let res = await sp.termStore.groups.getById(ts[0].id).sets.getById(termSetId).terms();
    return res;
  }

the childTree shows the tree, and in one of the childs, the childrenCount shows 14 items in my case, and the children property is empty here. So it looks like it knows that there are some children somewhere, but they are not shown... If I manually add a term (not a reused one) below that specific child,the childrenCount becomes 15, but in the children, I only get the added term.

The childTree2 show a flat lists with all my terms, including my reused terms.

**Comment by juliemturner** [comment]
Thank you, that really helps frame the issue better. We will try and look into it as soon as we can.

**Comment by MichielLeysen** [comment]
@juliemturner For now, I took part of your source code, and made some changes to it, to make it work for our solution. Below you can find my code. Maybe this can help you finding the issue. 
` let ts = await sp.termStore.groups.filter("scope eq 'siteCollection'").get();
    const selects = ["*", "customSortOrder", "properties","localProperties"];
    const tree: IOrderedTermInfo[] = [];
    const ensureOrder = (terms: IOrderedTermInfo[]): IOrderedTermInfo[] => {
      return terms;
    };
    const recursive = async (source: { children: IChildren }, parent: IOrderedTermInfo[]) => {
      const children = await source.children.select(...selects)();
      for (let i = 0; i < children.length; i++) {

        const child = children[i];

        const orderedTerm = {
            children: <IOrderedTermInfo[]>[],
            defaultLabel: child.labels.filter(l => l.isDefault)[0].name,
            ...child,
        };

        if (child.childrenCount > 0) {
          let term = await sp.termStore.groups.getById(ts[0].id).sets.getById(termSetId).terms.getById(children[i].id).children;
          await recursive({children:term}, orderedTerm.children);
            orderedTerm.children = ensureOrder(orderedTerm.children);
        }

        parent.push(orderedTerm);
      }
    };
    if(anchorId!= "00000000-0000-0000-0000-000000000000"){
      let ci = await sp.termStore.groups.getById(ts[0].id).sets.getById(termSetId).terms.getById(anchorId).children;
      await recursive({children:ci}, tree);    
      return ensureOrder(tree);
    }
    else{
      let ci = await sp.termStore.groups.getById(ts[0].id).sets.getById(termSetId).children;
      await recursive({children:ci}, tree);    
      return ensureOrder(tree);
    }`

**Comment by juliemturner** [comment]
Ok, we'll take a look at it when we can, but if you feel like you have a solution that works for instances where there are and are not reused terms, we happily accept PRs.

**Comment by patrick-rodgers** [comment]
I think for now we will not include this in v2, if it comes up again as an issue we'll look to add it to v3 but not a common ask and introduces a lot of added complexity. As well we don't have handy the "anchorId" which the logic here is based on.

**Comment by zshane15** [comment]
I'm having the same issue. I'm reusing a large # of terms across term groups and really don't want to recreate them for maintenance reasons. The terms are used for navigation in SharePoint and there are 2 separate term groups to manage Modern and Classic SharePoint. I want my client to be able to disable terms across both term groups/sets. This limitation in the getAllChildrenAsOrderedTree is preventing that.

Can this please be reopened?
