### ISSUE TITLE
How to register Remote Event Receiver by PNP in SPFX

### ISSUE THREAD

**Issue by enti333** [pnp/pnpjs#1951]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [ Latest ]
Please specify what version(s) of SharePoint you are targeting: [ SharePointOnline ]

### Expected / Desired Behavior / Question
I want to register the event receiver (not webhooks:) directly from the SPFX application via SharePoint Rest API or with PNP. It is possible to register event receiver (Which is Azure Function) via PNP because I try to test it via SharePoint Rest Api Directly and it doesn't work. 

`const body: string = JSON.stringify({
  '__metadatatype': { 'type': 'SP.EventReceiverDefinition' },
  'EventType': 1,
  'ReceiverName': "My Remote Event Receiver",
  'ReceiverUrl': "https://XXXXXXXXXXXXXXXXXXXXXXXXXX",
  'SequenceNumber': 10000
});

const requestHeaders: Headers = new Headers();
requestHeaders.append('Content-type', 'application/json');

enter code here
const httpClientOptions: ISPHttpClientOptions = {
  body: body,
  headers: requestHeaders
};

let currentWebUrl = this.props.context.pageContext.web.absoluteUrl;

let requestUrl = currentWebUrl.concat("/_api/web/Lists/GetByTitle('XXXXXX')/eventreceivers")

this.props.context.spHttpClient.post(requestUrl, SPHttpClient.configurations.v1, httpClientOptions)
  .then((response: SPHttpClientResponse) => {
    if (response.ok) {
      response.json().then((responseJSON) => {
        if (responseJSON != null && responseJSON.value != null) {
          alert(responseJSON.value.toString());
        }
      });
    }
  });`

Every time I get the error: 400. So the question is this possible with PNP. And if not why this is not supported. Thank you for your help.

**Comment by patrick-rodgers** [comment]
Yes, you can see [an example here](https://github.com/pnp/pnpjs/blob/version-2/packages/sp/column-defaults/list.ts#L208)

**Comment by enti333** [comment]
Hello. Thank you very much for the link. I have checked the code but in this code is missing the ReciverUrl. Why? I have found another link https://github.com/pnp/pnpjs/issues/921 but the Receiver URL is again missing. Maybe I do not understand something? I have no problem with registering event receivers by CSOM (there is ReceiverUrl) but in this project, I am not able to use CSOM only Rest Api or Graph API. And web hooks or GraphApi notifications can not be used because I am not able to get information about the ListItem ID on which was triggered....I know that there is change query that you can use in azure function but again the problem is that for security reasons I am not able to use CSOM (In azure function) which has ChangeQuery and GraphApi doesn't have a change query...I am in some vicious circle:) Thank you for your help.

**Comment by koltyakov** [comment]
There is change API in REST - https://pnp.github.io/pnpjs/sp/lists/#get-changes-on-a-list

Just wondering, what’s the security reasons preventing using CSOM? It can be used in a Node.js Azure Function.

Did you try ReceiverUrl property to pass RER endpoint?

**Comment by enti333** [comment]
Hello Andrew. The main problem is that if you want to use CSOM in the azure function (v.3 - AppRegistration...) you need to setup the permissions for that. And there is no possibility to specify on which site collection you want to have permission for this application. If you are using Graph Api in Azure Function you can use Sites.Selected so the application will have permission only on sites which you want.  
About the event receiver: I have tested everything but every time I get 400 error if I want to register this event receiver via Rest Api. I know that this approach is also not best because there will be problem with unregistering the event receiver (I need to use the same account) but at least I will be able to register the ER and in my azure function I can use the GraphApi calls. Thank you for your help.

**Comment by enti333** [comment]
> Yes, you can see [an example here](https://github.com/pnp/pnpjs/blob/version-2/packages/sp/column-defaults/list.ts#L208)

Hi Patrick. On your link is not provided ReceiverURL how does it work? Thank you.

**Comment by enti333** [comment]
Hi All. I was able to add remote event receiver by this code:

`    let currentWebUrl = this.props.context.pageContext.web.absoluteUrl;
    let listErUrl = currentWebUrl.concat("/_api/web/Lists/GetByTitle('Documents')/eventreceivers/add"); 

    const eventReceivePayload: any = {
      eventReceiverCreationInformation: {
        EventType: 10001,
        Synchronization: 1,
        ReceiverAssembly: 'Microsoft.Office.DocumentManagement, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c',
        ReceiverClass: 'Microsoft.Office.DocumentManagement.LocationBasedMetadataDefaultsReceiver',
        ReceiverName: 'LocationBasedMetadataDefaultsReceiver ItemAdded',
        ReceiverUrl: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        SequenceNumber: 1000
      }
    };

    var response = await this.props.context.spHttpClient.post(listErUrl, SPHttpClient.configurations.v1, {
      body: JSON.stringify(eventReceivePayload)
    });`

Everything is working and the event receiver is triggered. 

What is strange if I call this code:

`const res = await sp.web.lists.getByTitle("Documents").eventReceivers(); `

I can not see my event receiver but when I call information about event receivers by CSOM I can see this event receiver.
The second question is how to remove this event receiver from a list. 
And Maybe the third question is why this is not documented by Microsoft? Thank you

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
