### ISSUE TITLE
How to make a custom POST request using PnP Js Graph

### ISSUE THREAD

**Issue by Nootvar** [pnp/pnpjs#1955]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: @pnp/graph-commonjs 2.11.0

Please specify what version(s) of SharePoint you are targeting: Online

### Question

Hello,

I want to add a columns to a site content type using the graph endpoint.
I have setup pnp graph and I am using the common-js module due to the project setup.

I can recover the columns of my content type via this code without any issues :

````typescript
import { graph, GraphQueryable, GraphQueryableCollection } from "@pnp/graph-commonjs";

let siteContentTypeQuery = GraphQueryable(
    graph.groups.getById("a group id"),
    `sites/root/contentTypes/0x0101`
);

// Recover the content type properly
let documentContentType = await siteContentTypeQuery.get();

let columnsQuery = GraphQueryableCollection(siteContentTypeQuery, '/columns');

// Recover the content type columns properly
console.log(await columnsQuery.get());
````

However there is not post method in GraphQueryable to add a new column. I search how to make custom post request with pnp graph and found nothing except an old issue about the 1.* release. It was suggesting to cast the query to `any` an call the `post` method in it. This is not a solution with the 2.* release.

So how can I make a custom POST request with pnp graph ?

Regards,

**Comment by juliemturner** [comment]
@Nootvar - an example can be found here: https://github.com/pnp/spfx-reference-scenarios/blob/main/samples/ace-teams-worldclock/world-clock-spfx/src/webparts/worldClock/services/wc.service.ts - Line 244

You can do graphGet, graphPut, graphPost, etc...

**Comment by Nootvar** [comment]
Just to clarify the answer for people searching the same topic.

````ts
// use graph{method} from "@pnp/graph"
import { graph, graphGet, GraphQueryable, graphPut } from "@pnp/graph";
// then apply it to a queryable
let result = await graphPut(GraphQueryable(...), { body: JSON.stringify({...}) });
````
