### ISSUE TITLE
setMyProfilePic does't update picture

### ISSUE THREAD

**Issue by gabsnery** [pnp/pnpjs#1959]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.11.0 ]

Please specify what version(s) of SharePoint you are targeting: [ Online ]

### Expected / Desired Behavior / Question
Calling the method `sp.profiles.setMyProfilePic` with the blob should upload the selected image as a new profile picture

### Observed Behavior
Request returns with no error but it looks that is taking almost 1 day to see the new image in the profile (Manage User Profiles)
It happens only in some tenants, others are working fine.
### Steps to Reproduce
```
sp.web.lists.getByTitle("Documentos").rootFolder.files.getByName("profile.jpg").getBlob().then((blob)=>{
    sp.profiles.setMyProfilePic(blob).then((x)=>{
        let userProfilePic = `/_vti_bin/DelveApi.ashx/people/profileimage?size=L&userId=${this.props.userProperties.UserName}`;
        resolve(userProfilePic);
        console.log("return",x)
       });
});
```

**Comment by patrick-rodgers** [comment]
Hi @gabsnery - it doesn't sound like there are any errors, just that it takes some time for the photo to update? That feels like something in the service taking time to update vs something we can control. If the picture eventually updates, I think we've done what we can from within this library.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
