### ISSUE TITLE
Create File from File Lib template.

### ISSUE THREAD

**Issue by Korigoth** [pnp/pnpjs#196]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [X] Documentation gap/issue

### Version

    "@pnp/common": "1.1.2",
    "@pnp/logging": "1.1.2",
    "@pnp/odata": "1.1.2",
    "@pnp/sp": "1.1.2",

### Expected / Desired Behavior / Question

I need to create/add a new File from Files Lib, then i need to set the name of the file with an unique ID and update other fieds. I can update the fields without any problems, but i couldn't find a way to create the file.

How can i possibly achieve the    New => Create from template like in the image below
![newfilefromtemplate](https://user-images.githubusercontent.com/10915055/43729833-7f014aee-9977-11e8-9be9-9e1d0bdf6ca7.png)

I've tried many ways but nothing fullfill my request.

#1
this.web.lists.getByTitle('myFilesLib').items.add() => i get an error about the need to use SPFileCollection.Add()

#2
this.web.getFolderByServerRelativeUrl(url).files.addTemplateFile => there is nothing for custom template

#3 
this.web.getFolderByServerRelativeUrl(url).files.add => i need to provide a file. 

### Observed Behavior
I didn't find any documentation or questions related to this topic, that's why i've opened this ticket.

**Comment by Korigoth** [comment]
There is some problems with the code you provided.

First, the file uploaded is always corrupted. (We use .docx file as template)
The template is not corrupted and i've tried with a new docx file with a single word in it.

Second the item.validateUpdateListItem doesn't use the url set with our    new Web we created to upload the file.

**Comment by koltyakov** [comment]
@Korigoth, what is SP version do you use? Where do you execute the code (browser or Node.js)?

The code works just fine for me with v1.1.2/browser/SPO. Created file is not corrupted. Before posting the answer, the code was tested of course.

With 1.1.3, `await file.getItem()` ends up with the wrong URL for me too now - we'll take a look at what change might introduce the error.

@patrick-rodgers, I'm wondering doesn't it correlate with this [issue](https://github.com/pnp/pnpjs/issues/190)?

This is how _parentUrl and _url looks like now:

![image](https://user-images.githubusercontent.com/7816483/43735667-dbbb5288-99c3-11e8-94dd-dcca2f90ed3f.png)

**Comment by patrick-rodgers** [comment]
Yes, that is it. The service changed what it was sending back for odata.id from the url to a guid. We are going to have to release another version. I will do that today, this will impact a lot of operations in the library.

**Comment by Korigoth** [comment]
@koltyakov i use 1.1.2 / browser / Share Point Online for Dev but SharePoint OnPremise for Prod.

I've tried with a docx, is it possible to test on your side to see if docx get uploaded without being corrupted ?
I will test tomorrow at job with xlsx, just to be sure that i can isolate the problem.


@koltyakov @patrick-rodgers 
Why does calling item.validateUpdateListItem() doesn't use the same Web object as i've created to get template and upload it as new file?

my request are made on localhost:8080 (for my proxy) 
but when i get to call item.validateUpdateListItem it send the request on localhost:4200 (where my front-end app live) but it should take the URL i've put in Web!?

**Comment by patrick-rodgers** [comment]
@Korigoth - would you please test with latest release, 1.1.4 put out today. There was a change in the service that affected a number of scenarios. We believe that is now fixed - but if you could verify with the latest version we can help ensure that we got it fixed or this is a separate bug. Thanks!

**Comment by Korigoth** [comment]
@patrick-rodgers 
I've tested with 1.1.4 and i'm getting the same problems, the file is corrupted.

```    
"@pnp/common": "1.1.4",
"@pnp/logging": "1.1.4",
"@pnp/odata": "1.1.4",
"@pnp/sp": "1.1.4",
```

I've tried with an empty words file (docx) and an empty excel file (xlsx).

I use Office 2010 on my machine for info (in case it change something)

Doing new File in the Lib is working perfectly but using the getBuffer() and add() doesn't work.

Code Used:

```
templateUrl = '/sites/App/Template/Forms/Template/test.xlsx'
name = 'test.xlsx'
depositUrl = '/sites/App/Template'

this.web.getFileByServerRelativeUrl(this.templateUrl)
    .getBuffer()
    .then((templateData: ArrayBuffer) => { 
        this.web.getFolderByServerRelativeUrl(depositUrl).files.add(name, templateData)); 
});

```

**Comment by koltyakov** [comment]
@Korigoth,

Can you check if a file created this way is corrupted while executing the code on SharePoint (not a local workbench) page?

It can be easily proxy's issue. If so, please post a separate issue in proxy's repo.

I can take a look tonight if it's a proxy's error.

**Comment by koltyakov** [comment]
Nope, just run the same part of the code you're dealing with in a browsers console being on a SharePoint page.

**Comment by Korigoth** [comment]
I'm not sure, how can i achieve this ?

**Comment by Korigoth** [comment]
@koltyakov 
Ok, i've tried something and it worked!

I've sent my code on SharePoint Online, because it doesn't have any proxy there.
It worked as expected!

I will create an issue on sp-rest-proxy

**Comment by koltyakov** [comment]
Thanks for letting me know. Closing this one.

**Comment by ncmadhan1989** [comment]
When Uploading Large file (300MB),i cant able to upload using pnp js, but the same code is working in onpremise 2016 not in onpremise 2019,i also checked maximum upload size in site collection general settings its setted to 10240mb,kindly help me
![file error](https://user-images.githubusercontent.com/44596222/60509583-ecc31900-9cea-11e9-8a59-f92959a29a41.png)

**Comment by ncmadhan1989** [comment]
and plz provide me the code for addchucked with metadata update,currently i didn't able to get the value for filedata.file.getItem()

   newweb.getFolderByServerRelativeUrl("/VideoGallery/").files.addChunked(newfile.name, newfile, function(filedat) {}, true).then(function(filedata){
          
           filedata.file.getItem().then(function(item) {
        item.update(VideoData);
     
    });
          });
