### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by nicholasp** [pnp/pnpjs#197]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Sharepoint 2016 On-Prem
pnp sp 1.1.3

### Question
Is there a way to do pagination at sharepoint list without knowing/handling the last id?

e.x. with offset or page number?

**Comment by koltyakov** [comment]
Hi @nicholasp,

It's better using `items.getPaged`, `hasNext` and `getNext` utilities. As knowing the last ID is not enough for correct paging, next page token also includes sorting information which is required for correct pagination.

P.S.
There was an issue in 1.1.3 which force us to publish 1.1.4, I'd recommend upgrading to 1.1.4.

**Comment by patrick-rodgers** [comment]
The getPaged is the best way to do paging as we handle all the plumbing. I did just look and we don't have a section for that in the docs - I thought we did. Will leave this open as a reminder to add one.

**Comment by patrick-rodgers** [comment]
[Updated docs](https://github.com/pnp/pnpjs/blob/dev/packages/sp/docs/items.md#get-paged-items), will be published with next release:

**Comment by nicholasp** [comment]
thanks! I just test it. its a wonderful implementation for endless loading or on scrolldown load 👍 

what's your opinion about _vti_bin/listdata.svc if i must do standard pagination with count and pages? is it worth trying ?

_vti_bin/listdata.svc/MyList/?&$inlinecount=allpages&$skip=2&$top=2&$orderby=Id%20desc

thanks a lot!

**Comment by nicholasp** [comment]
working perfect thanks again!

**Comment by cjnanamurthy** [comment]
is there any way to move backward to collection ??

**Comment by koltyakov** [comment]
REST API doesn't provide previous page pagination token, but the one can be implemented by your own, e.g. [getPrev](https://github.com/pnp/pnpjs/issues/440#issuecomment-450115251).

Another approach is keeping previous pages tokens in the application memory.
