### ISSUE TITLE
Dark theme issue with PnPJS Controls (specifically file picker)

### ISSUE THREAD

**Issue by tendau** [pnp/pnpjs#1973]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.11.0 ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
When using a dark themed SPO site some controls inherit some styles but not text. This makes for an unusable control. Please see below.

![image](https://user-images.githubusercontent.com/3698780/146253632-169b8d8d-37f4-417c-b49a-b45ac877df8b.png)

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
Create an SPO site. Select a theme with a dark background. Add a webpart with the PnPJS filepicker.

**Comment by koltyakov** [comment]
Wrong repo

**Comment by tendau** [comment]
> Wrong repo

My apologies will move this
