### ISSUE TITLE
sp fields import scenario documentation is wrong

### ISSUE THREAD

**Issue by MudulOzan** [pnp/pnpjs#1975]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.1.0     ]

Please specify what version(s) of SharePoint you are targeting: [  Sharepoint Online  ]

### Expected / Desired Behavior / Question
https://pnp.github.io/pnpjs/sp/fields/#ifields
According to [this link](https://pnp.github.io/pnpjs/sp/fields/#ifields) core preset has Fields 
```js
import { sp, Fields, IFields } from "@pnp/sp/presets/core";
```
![image](https://user-images.githubusercontent.com/29442243/146373324-5b4b1b39-ddbd-4dbf-be31-5a487296186b.png)

However when I tried to import it I faced an issue.
![image](https://user-images.githubusercontent.com/29442243/146372643-e649b6ef-1a44-4cd1-b3f0-711125b796eb.png)

### Observed Behavior
Either I should be able to use it or it should be removed from documents

**Comment by patrick-rodgers** [comment]
The docs are wrong, updated to remove the line about fields in core.
