### ISSUE TITLE
[Question] - Is it possible to download a large file from SharePoint in chunks?

### ISSUE THREAD

**Issue by pmatthews05** [pnp/pnpjs#1978]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   ^2.11.0      ]

Please specify what version(s) of SharePoint you are targeting: [   Online      ]

###  Question
We are currently using PNP in a node Azure Function. We need to download a SharePoint file, and upload it again into a Azure blob storage. 
We have been able to do this successfully, however, it appears to grab the entire file into a buffer, then writes that buffer to the Azure Blob storage. This is all well and good for small files, however anything over 2GB in size requires a very large & expensive App Service plan just to handle the odd files that are that large.

Looking through the PNP code and documentation, I can see you can upload in chunks, but not finding anything that allows you to download in chunks. If we did this with C# it looks like we could do something similar to this following this example.
 https://pnp.github.io/pnpcore/using-the-sdk/files-large.html#downloading-large-files

### Steps to Reproduce
Our current code is similar to below.
```
let blobServiceClient: BlobServiceClient = BlobServiceClient.fromConnectionString(connectionString);
let container: ContainerClient =  blobServiceClient.getContainerClient(containerName);
container.getBlockBlobClient(pathName);

#TODO: Download in chunks
let buffer = await sp.web.lists.getByTitle(listTitle).items.getById(itemId).file.getBuffer();
#TODO: Update this to upload in chunks.
await blockBlobClient.uploadData(buffer);

```
Is this possible in pnpjs?

**Comment by juliemturner** [comment]
At this time, we support the following methods for "getting" a file: Blob, Buffer, JSON, or Text

I've added the request to the backlog, and we'd happily take a pull request (to the V3 branch) if anyone would like to invest some time to build this new feature.

**Comment by patrick-rodgers** [comment]
We have existing [stream support](https://pnp.github.io/pnpjs/nodejs/sp-extensions/#ifilegetstream) in v2 today which should give you the same options as what you linked to above.

**Comment by patrick-rodgers** [comment]
@pmatthews05 - that is just an example of reading the stream, you are free to read/process it however you want. Yes, in this simple example the whole stream would be in memory once the promise resolved. Going to close this as answered.
