### ISSUE TITLE
Issues on classic pages and referencing PnP JS

### ISSUE THREAD

**Issue by Sartor87** [pnp/pnpjs#198]
### Category
- [ ] Enhancement
- [ X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.1.4]

### Expected / Desired Behavior / Question
Expect that the library loads properly.

### Observed Behavior
The library throws errors in the console:

### Steps to Reproduce
1. Use a classic publishing site
2. Create a page
3. Add a content editor web part
4. Create an HTML page and add it to Style Library
5. Add the following content
`<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.1.1/es6-promise.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.4/fetch.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnp-common/1.1.4/common.es5.umd.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnp-config-store/1.1.4/config-store.es5.umd.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnp-logging/1.1.4/logging.es5.umd.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnp-odata/1.1.4/odata.es5.umd.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnp-sp/1.1.4/sp.es5.umd.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnp-sp-clientsvc/1.1.4/sp-clientsvc.es5.umd.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnp-sp-taxonomy/1.1.4/sp-taxonomy.es5.umd.js"></script>

<script type="text/javascript">
    (function (window, $, undefined) {
        $(document).ready(function () {

            window.MyApp || window.MyApp|| {};

            MyApp= {
                init: function () {

                }
            }

            SP.SOD.executeFunc('sp.js', 'SP.ClientContext', function () {
                MyApp.init();
            });
        });
    })(window, jQuery);
</script>`
6. Reference the new HTML file in the content editor web part
7. Save the publishing page and open the Dev console. The following issues are shown:

Chrome (Version 68.0.3440.106 (Official Build) (64-bit)):
netutil.ts:68 Uncaught TypeError: Cannot read property '__extends' of undefined
exceptions.ts:3 Uncaught TypeError: Cannot read property '__extends' of undefined
caching.ts:37 Uncaught TypeError: common.PnPClientStorage is not a constructor
odata.ts:29 Uncaught TypeError: Cannot read property '__extends' of undefined
batch.ts:19 Uncaught TypeError: Cannot read property 'Queryable' of undefined
labels.ts:122 Uncaught TypeError: Cannot read property 'ClientSvcQueryable' of undefined

Edge:
common.es5.umd.js (391,8) Unable to get property '__extends' of undefined or null reference 
odata.es5.umd.js (33,8) Object doesn't support this action
sp.es5.umd.js (50,8) Unable to get property '__extends' of undefined or null reference
sp-clientsvc.es5.umd.js (586,4)  Unable to get property 'Queryable' of undefined or null reference
sp-taxonomy.es5.umd.js (18,4) Unable to get property 'ClientSvcQueryable' of undefined or null reference

**Comment by koltyakov** [comment]
I would suggest including the version of the scripts with 'bundle' in the name, or even `https://cdnjs.cloudflare.com/ajax/libs/pnp-pnpjs/1.1.4/pnpjs.es5.umd.bundle.min.js` this one which includes other peer dependencies (sp-clientsvc and sp-taxonomy are the exceptions).

**Comment by patrick-rodgers** [comment]
[This page](https://pnp.github.io/pnpjs/package-structure.html#dist) in the docs outlines the package structure and what is in each file.

**Comment by Sartor87** [comment]
Ok, it seems that has fixed the issue, if I do not include the Taxonomy libraries. Any suggestion on how to include the Taxonomy package?

**Comment by patrick-rodgers** [comment]
You can do it the same way, they should also be available on cdnjs.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Please _reopen_ the issue if you need to continue the discussion. Thanks!

**Comment by stact** [comment]
Hi @patrick-rodgers 
`You can do it the same way, they should also be available on cdnjs.`
What are the steps to include sp-taxonomy and bundle a package like pnpjs manually, without webpack? It seems there is no package with all packages.

I figured out with an issue when I'm including @pnp/sp-taxonomy: the pnp.sp is undefined. But pnp.taxonomy is working.
I tried also to use https://github.com/pnp/pnpjs/tree/dev/tools/generator-package
but no documentation or a sample to allow us to understand this tool.

Thank you for your help!

**Comment by patrick-rodgers** [comment]
@stact - please open a new issue if you are having trouble, thanks!

**Comment by stact** [comment]
Thanks @patrick-rodgers!
You could find the issue here: #464
