### ISSUE TITLE
How to use PnP webpart in SharePoint server 2019

### ISSUE THREAD

**Issue by DJoshi23** [pnp/pnpjs#1983]
Hi,

I want to use PnP webpart in SharePoint server 2019. Can someone guild me on that.
### Category
- [ ] Enhancement
- [ ] Bug
- [*] Question
- [ ] Documentation gap/issue

### Version

Please specify what version(s) of SharePoint you are targeting: [ Sharepoint Server 2019]

Thank you for your feedback!

**Comment by koltyakov** [comment]
Wrong repo

**Comment by juliemturner** [comment]
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2019-support

Please use the [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs) repo for any issues/questions.
