### ISSUE TITLE
Uncatchable promise rejection when the User has no access to a list

### ISSUE THREAD

**Issue by dvTB** [pnp/pnpjs#1984]
### Category
- [ ] Enhancement
- [x ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.11.0  ]

Please specify what version(s) of SharePoint you are targeting: [online ]

### Expected / Desired Behavior / Question
Using try-catch when awaiting the request should catch all exceptions that occur for the request. 

### Observed Behavior
When you try to get a list via IWeb.getList(serverRelativeListUrl).get() and the user has no access to the list (you don't know until you try) you get an exception. This behaviour is expected (even if I don't like that behavior it is even normal for the currentUserHasPermissions-function but that's ok so far ). The exception is handled by the try-catch block around  the logic like it should. But after this expected exception is handled an additional exception will occur that cannot be catched in the logic, but only by a global exception handler.

The error that occurs looks like this:
Error making HttpClient request in queryable [403] Forbidden ::> {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Attempted to perform an unauthorized operation."}}}
at new HttpRequestError (/packages/odata/parsers.ts:132:9)
at Function.<anonymous> (/packages/odata/parsers.ts:138:16)
at step (/node/node_modules/tslib/tslib.js:143:27)
at Object.next (/node/node_modules/tslib/tslib.js:124:57)
at fulfilled (/node/node_modules/tslib/tslib.js:114:62)
at processTicksAndRejections (internal/process/task_queues.js:95:5) 

It seems like the odata parser class trys to parse something even when the request fails, which seems to lead to the problem.

### Steps to Reproduce
I'm using the isolated instances (createIsolated) for all objects inside of a node.js process.

try{
await isolatedSP.web.getList(serverRelativeListUrl).get() 
}
catch(e){
// expected exception if the user has no access
}

Yes, you can catch it with a global event receiver for uncatched exceptions (which saves the process from crashing) but that shouldn't be necessary to catch these.

**Comment by patrick-rodgers** [comment]
Can you share a minimal repro where we can see the issue? Based on the information you shared the error should be catchable - the parser itself does the error check and produces the HttpRequestError so that all looks to be correct.

**Comment by dvTB** [comment]
I really don't know what you mean, the sample, was already reduced so here it is a bit longer, running in a node-process (node 14.18.1)

	export const test = async () : Promise<IList> {
		const baseURL ="https://yourSPOnelineSite.sharepoint.com";
		const serverRelativeListUrl = "/lists/mylist"; // list url you don't have access to.
		const config = {
            sp: {
                baseUrl: baseURL,
                headers: {
                    Accept: "application/json;odata=verbose",
                    "User-Agent": "ISV|...",
                },
                fetchClientFactory: (): IHttpClientImpl =>
                    new FetchClientProxy(this._baseParams, async() => // fetchclient to set the token
                        getSharePointAccessToken(baseURL)
                    ),
            },
            globalCacheDisable: true,
            cacheExpirationIntervalMilliseconds: 2000,
        };
		
		const isolatedSP = await sp.createIsolated({
            cloneGlobal: false,
            config: config,
            baseUrl: config.sp.baseUrl,
            options: {
                cache: "no-cache",
            },
        });
		
		isolatedSP.setup(config); // just to be sure it is really set
		const web = this.isolatedSP.web;
		try{
			const list = await web.getList(serverRelativeListUrl)
		}
		catch(e){
			// expected exception if the user has no access
			// this exception is thrown, but another one after outside of the normal catchable stuff
		}
	}


In the server.ts there is a global catch-handler that catches the exception
process.on("uncaughtException", (error: Error) => {
....
});

**Comment by patrick-rodgers** [comment]
For example, how is "test" invoked? Typically, a minimal repro would be a repository we can clone/run to immediately see the issue. So far as I am aware the library only throws a single exception on errors and not "another one after outside". Certainly, we could have a bug here - I am asking for your help in figuring it out.

**Comment by dvTB** [comment]
Finally found the error. And it wasn't inside of pnp-js even if the stacktrace pointed to this.
There was a promise-cache active that attached to the ".finally(() =>....)" which lead to the uncatched exception, because there should have been a ".catch(" on that promise in that place, too.
I didn't see this, because the code was no longer there in typescript but it seems that it was still present in the compiled javascript ... :(

So this issue can be closed.
