### ISSUE TITLE
Multiline JSON response in batch request breaks parsing

### ISSUE THREAD

**Issue by johannes-z** [pnp/pnpjs#1985]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.11.0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
`renderListDataAsStream` should work as part of a batch request.

### Observed Behavior
`renderListDataAsStream` fails, because it returns JSON on multiple lines:

```
--batchresponse_5cf53335-86b4-4b26-9eb0-c95c494e1401
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 200 OK
CONTENT-TYPE: application/json; charset=utf-8

{"wpq":"","Templates":{},"ListData":null,"ListSchema":{ "Field": [ 
{"Name": "Title",
"FieldType": "Text",
...
```

 The parser only looks at each line individually, causing the following error:

```
Error: Invalid response, line 16
    at Function.SPBatch2.ParseResponse (batch.ts:42)
    at SPBatch2.<anonymous> (batch.ts:222)
    at step (tslib.es6.js:102)
    at Object.next (tslib.es6.js:83)
    at fulfilled (tslib.es6.js:73)
```

### Steps to Reproduce
Add `renderListDataAsStream` to a batch request and execute it.

### Question
Do you have pointers how to overwrite/extend the SPBatch class to add a custom implementation for batching that can handle these type of requests? Related #1948

**Comment by johannes-z** [comment]
I could get the batching to work by overwriting the default implementation of SPBatch's ParseResponse:

```ts
SPBatch.ParseResponse = (body: string): Response[] => {
  const batchResponses = body.split(/--batchresponse.*\r\n/gmi).filter(e => e)
  // eslint-disable-next-line prefer-regex-literals
  const statusRegExp = new RegExp('^HTTP/[0-9.]+ +([0-9]+) +(.*)', 'i')

  return batchResponses.map(batch => {
    const [_, httpStatus, body] = batch.split(/\r\n\r\n/)

    const parts = statusRegExp.exec(httpStatus)
    if (!parts || parts.length !== 3) {
      throw Error(`Invalid status, ${httpStatus}`)
    }
    const status = parseInt(parts[1], 10)
    const statusText = parts[2]

    return (status === 204)
      ? new Response()
      : new Response(body.replace(/\r\n/g, '').replace(/\n/g, ''), { status: status, statusText: statusText })
  })
}
```

**Comment by juliemturner** [comment]
That makes sense since batching was meant to handle the 80/20 rule and renderListDataAsStream is definitely a different beast. I assume you're doing other things in the batch that make that a worthwhile endeavor.  Glad you found a solution.
