### ISSUE TITLE
renderListDataAsStream cannot be batched

### ISSUE THREAD

**Issue by johannes-z** [pnp/pnpjs#1987]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.11.0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
`.renderListDataAsStream` should be able to call `.inBatch`.

### Observed Behavior
`.renderListDataAsStream` can only be batched, if the whole `IList` is batched. This means, all subsequent calls are also in the batch, requiring `batch.execute()` to be called at some point.

I also could not get cloning the list to work, and couldn't find documentation about it. I guess it's an internal function? 

```js
const listRef = sp.web.getList('...')
const clone = listRef.clone() // throws: An argument for 'factory' was not provided.
```

In my use case I use vuejs, and `listRef` is a reactive property that automatically updates based on the props the component receives. This is why I can't (or don't want to have to) call `sp.web.getList(...)` for all my calls.

### Steps to Reproduce

```js
const batch = sp.web.createBatch()

const listRef = sp.web.getList('...')
const listMetadataRef = listRef.select('Title').inBatch(batch).get() // ok
const listDataRef = listRef.renderListDataAsStream(...) // no .inBatch
// workaround that breaks subsequent calls
const listDataRef = listRef.inBatch(batch).renderListDataAsStream(...)
```

Related #1985

**Comment by juliemturner** [comment]
Duplicate #1985
