### ISSUE TITLE
Search types problem

### ISSUE THREAD

**Issue by EA12** [pnp/pnpjs#1992]
### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [@pnp/sp@1.3.11]
Please specify what version(s) of SharePoint you are targeting: [ Online ]

I cannot use the the latest release because of the peer depenency of pnp taxonomy.

### Question
How to overcome the type problem with Rows when doing a search?

As the browser does return ...Rows.results, I cannot map on the results because the type of Rows is: 
`(property) Rows: {
    Cells: {
        Key: string;
        Value: any;
        ValueType: string;
    }[];
}[]`

`const resultRows = this._initialSearchResult.RawSearchResults.PrimaryQueryResult!.RelevantResults!.Table!.Rows;`

Build-Error here: `const rr = resultRows.**results**;`

error TS2339: Property 'results' does not exist on type '{ Cells: { Key: string; Value: any; ValueType: string; }[]; }[

I hope this is enough information to have a look on it.
Do I have to write my own Taxonomies-Routines and install the latest version of pnp/sp?

Thank you

New Finding: I uninstalled pnp taxonomy 1.3.11 and also pnp 1.3.11 and installed the latest version of pnp which now includes even Types for Taxonomies. But still results is not a property of Rows from the search part of pnp. I need to call the index accessor like so to get it to work:
`const resultRows = this._initialSearchResult.RawSearchResults.PrimaryQueryResult!.RelevantResults!.Table!.Rows;`
`resultRows["results"]`

Am I missing something or is this the solution?

**Comment by patrick-rodgers** [comment]
Hello, v1.* is no longer supported so we won't be making updates there.

Would certainly recommend you to update to newer versions if possible. We have taxonomy support in [v2](https://pnp.github.io/pnpjs/sp/taxonomy/) but is not a direct match with v1 as the API on the server changed.

You can always ignore typings using <any> on your objects to overcome such an obstacle.

**Comment by EA12** [comment]
Hi Patric,
as I already wrote, I am using the latest version now and the problem is the same.
But using resultRows["results"] is working for me.
Thx, Ronny
