### ISSUE TITLE
Getting issue when using @pnp/nodejs

### ISSUE THREAD

**Issue by gauravgoyal5** [pnp/pnpjs#2000]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.11.0  ]

Please specify what version(s) of SharePoint you are targeting: [ SPO ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I am using @pnp/nodejs version 2.11.0. In the code, I was trying to get data from a list with Client Id & Secret.
`import { SPFetchClient } from "@pnp/nodejs";
import { sp } from "@pnp/sp/presets/all";

export class TestingOfClientId{
    public constructor(){
        sp.setup({
            sp: {
                fetchClientFactory: () => {
                    return new SPFetchClient("https://mytesttenant.sharepoint.com/sites/test", "2a4f2a4f-2a4f-2a4f-2a4f-2a4f2a4f2a4f", "2a4f2a4f2a4f2a4f2a4f2a4f2a4f2a4f2a4f2a4f2a4f");
                },
            },
        });
    }

    public Get=async()=>{
        let items=await sp.web.lists.getByTitle("MyList").items.getAll();
        console.debug(items);
        return items;
    }
}`

### Observed Behavior
When I am compiling , I am getting following error :
`[21:38:04] Error - [webpack] 'dist':
./node_modules/.pnpm/https-proxy-agent@5.0.0/node_modules/https-proxy-agent/dist/agent.js
Module not found: Error: Can't resolve 'net' in 'D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\dist'
resolve 'net' in 'D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\dist'
  Parsed request is a module
  using description file: D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\dist\node_modules doesn't exist or is not a directory
      D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\dist\lib doesn't exist or is not a directory
      D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\node_modules doesn't exist or is not a directory
      D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\lib doesn't exist or is not a directory
      D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\node_modules doesn't exist or is not a directory
      D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\lib doesn't exist or is not a directory
      D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\lib doesn't exist or is not a directory
      D:\SPFx\node_modules\.pnpm\lib doesn't exist or is not a directory
      D:\SPFx\node_modules\node_modules doesn't exist or is not a directory
      D:\SPFx\node_modules\lib doesn't exist or is not a directory
      D:\SPFx\node_modules doesn't exist or is not a directory
      D:\SPFx\lib doesn't exist or is not a directory
      D:\SPFx\node_modules doesn't exist or is not a directory
      D:\SPFx\lib doesn't exist or is not a directory
      D:\SPFx\node_modules doesn't exist or is not a directory
      D:\SPFx\lib doesn't exist or is not a directory
      D:\Gaurav\node_modules doesn't exist or is not a directory
      D:\Gaurav\lib doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
      D:\lib doesn't exist or is not a directory
      looking for modules in D:\SPFx\node_modules
        using description file: D:\SPFx\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in D:\SPFx\lib
        using description file: D:\SPFx\package.json (relative path: ./lib)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in D:\SPFx\node_modules\.pnpm\node_modules
        using description file: D:\SPFx\package.json (relative path: ./node_modules/.pnpm/node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules
        using description file: D:\SPFx\package.json (relative path: ./node_modules/.pnpm/https-proxy-agent@5.0.0/node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\SPFx\package.json (relative path: ./node_modules/net)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\SPFx\package.json (relative path: ./lib/net)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\net doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\lib\net doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\SPFx\package.json (relative path: ./node_modules/.pnpm/node_modules/net)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\net.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\lib\net.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\SPFx\package.json (relative path: ./node_modules/.pnpm/https-proxy-agent@5.0.0/node_modules/net)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\node_modules\net doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\net.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\lib\net.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\net doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\node_modules\net.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\net.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\lib\net.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\net.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\node_modules\net.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\net.json doesn't exist
              D:\SPFx\lib\net.json doesn't exist
            as directory
              D:\SPFx\node_modules\net doesn't exist
            as directory
              D:\SPFx\lib\net doesn't exist
              D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\net.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\node_modules\net.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\net.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\node_modules\net.json doesn't exist
            as directory
              D:\SPFx\node_modules\.pnpm\node_modules\net doesn't exist
              D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\net.json doesn't exist
            as directory
              D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\net doesn't exist
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\dist\node_modules]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\dist\lib]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\node_modules]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\lib]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\node_modules]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\lib]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\lib]
[D:\SPFx\node_modules\.pnpm\lib]
[D:\SPFx\node_modules\node_modules]
[D:\SPFx\node_modules\lib]
[D:\SPFx\node_modules]
[D:\SPFx\lib]
[D:\SPFx\node_modules]
[D:\SPFx\lib]
[D:\SPFx\node_modules]
[D:\SPFx\lib]
[D:\Gaurav\node_modules]
[D:\Gaurav\lib]
[D:\node_modules]
[D:\lib]
[D:\SPFx\node_modules\net]
[D:\SPFx\lib\net]
[D:\SPFx\node_modules\net.wasm]
[D:\SPFx\lib\net.wasm]
[D:\SPFx\node_modules\.pnpm\node_modules\net]
[D:\SPFx\node_modules\net.mjs]
[D:\SPFx\lib\net.mjs]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\net]
[D:\SPFx\node_modules\.pnpm\node_modules\net.wasm]
[D:\SPFx\node_modules\net.js]
[D:\SPFx\lib\net.js]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\net.wasm]
[D:\SPFx\node_modules\.pnpm\node_modules\net.mjs]
[D:\SPFx\node_modules\net.json]
[D:\SPFx\lib\net.json]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\net.mjs]
[D:\SPFx\node_modules\.pnpm\node_modules\net.js]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\net.js]
[D:\SPFx\node_modules\.pnpm\node_modules\net.json]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\net.json]
 @ ./node_modules/.pnpm/https-proxy-agent@5.0.0/node_modules/https-proxy-agent/dist/agent.js 15:30-44
 @ ./node_modules/.pnpm/https-proxy-agent@5.0.0/node_modules/https-proxy-agent/dist/index.js
 @ ./node_modules/.pnpm/@pnp+nodejs@2.11.0/node_modules/@pnp/nodejs/net/proxy.js
 @ ./node_modules/.pnpm/@pnp+nodejs@2.11.0/node_modules/@pnp/nodejs/index.js
 @ ./lib/SPS/common/services/SPSLicense.js
 @ ./lib/webparts/spsButton/components/SPSButtons.js
 @ ./lib/webparts/spsButton/SpsButtonWebPart.js
./node_modules/.pnpm/https-proxy-agent@5.0.0/node_modules/https-proxy-agent/dist/agent.js
Module not found: Error: Can't resolve 'tls' in 'D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\dist'
resolve 'tls' in 'D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\dist'
  Parsed request is a module
  using description file: D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\dist\node_modules doesn't exist or is not a directory
      D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\dist\lib doesn't exist or is not a directory
      D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\node_modules doesn't exist or is not a directory
      D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\lib doesn't exist or is not a directory
      D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\node_modules doesn't exist or is not a directory
      D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\lib doesn't exist or is not a directory
      D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\lib doesn't exist or is not a directory
      D:\SPFx\node_modules\.pnpm\lib doesn't exist or is not a directory
      D:\SPFx\node_modules\node_modules doesn't exist or is not a directory
      D:\SPFx\node_modules\lib doesn't exist or is not a directory
      D:\SPFx\node_modules doesn't exist or is not a directory
      D:\SPFx\lib doesn't exist or is not a directory
      D:\SPFx\node_modules doesn't exist or is not a directory
      D:\SPFx\lib doesn't exist or is not a directory
      D:\SPFx\node_modules doesn't exist or is not a directory
      D:\SPFx\lib doesn't exist or is not a directory
      D:\Gaurav\node_modules doesn't exist or is not a directory
      D:\Gaurav\lib doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
      D:\lib doesn't exist or is not a directory
      looking for modules in D:\SPFx\node_modules
        using description file: D:\SPFx\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in D:\SPFx\lib
        using description file: D:\SPFx\package.json (relative path: ./lib)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in D:\SPFx\node_modules\.pnpm\node_modules
        using description file: D:\SPFx\package.json (relative path: ./node_modules/.pnpm/node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules
        using description file: D:\SPFx\package.json (relative path: ./node_modules/.pnpm/https-proxy-agent@5.0.0/node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\SPFx\package.json (relative path: ./node_modules/tls)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\SPFx\package.json (relative path: ./lib/tls)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\tls doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\lib\tls doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\SPFx\package.json (relative path: ./node_modules/.pnpm/node_modules/tls)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\tls.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\lib\tls.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\SPFx\package.json (relative path: ./node_modules/.pnpm/https-proxy-agent@5.0.0/node_modules/tls)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\node_modules\tls doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\tls.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\lib\tls.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\tls doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\node_modules\tls.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\tls.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\lib\tls.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\tls.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\node_modules\tls.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\tls.json doesn't exist
              D:\SPFx\lib\tls.json doesn't exist
            as directory
              D:\SPFx\node_modules\tls doesn't exist
            as directory
              D:\SPFx\lib\tls doesn't exist
              D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\tls.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\node_modules\tls.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\tls.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\SPFx\node_modules\.pnpm\node_modules\tls.json doesn't exist
            as directory
              D:\SPFx\node_modules\.pnpm\node_modules\tls doesn't exist
              D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\tls.json doesn't exist
            as directory
              D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\tls doesn't exist
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\dist\node_modules]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\dist\lib]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\node_modules]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\https-proxy-agent\lib]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\node_modules]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\lib]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\lib]
[D:\SPFx\node_modules\.pnpm\lib]
[D:\SPFx\node_modules\node_modules]
[D:\SPFx\node_modules\lib]
[D:\SPFx\node_modules]
[D:\SPFx\lib]
[D:\SPFx\node_modules]
[D:\SPFx\lib]
[D:\SPFx\node_modules]
[D:\SPFx\lib]
[D:\Gaurav\node_modules]
[D:\Gaurav\lib]
[D:\node_modules]
[D:\lib]
[D:\SPFx\node_modules\tls]
[D:\SPFx\lib\tls]
[D:\SPFx\node_modules\tls.wasm]
[D:\SPFx\lib\tls.wasm]
[D:\SPFx\node_modules\.pnpm\node_modules\tls]
[D:\SPFx\node_modules\tls.mjs]
[D:\SPFx\lib\tls.mjs]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\tls]
[D:\SPFx\node_modules\.pnpm\node_modules\tls.wasm]
[D:\SPFx\node_modules\tls.js]
[D:\SPFx\lib\tls.js]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\tls.wasm]
[D:\SPFx\node_modules\.pnpm\node_modules\tls.mjs]
[D:\SPFx\node_modules\tls.json]
[D:\SPFx\lib\tls.json]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\tls.mjs]
[D:\SPFx\node_modules\.pnpm\node_modules\tls.js]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\tls.js]
[D:\SPFx\node_modules\.pnpm\node_modules\tls.json]
[D:\SPFx\node_modules\.pnpm\https-proxy-agent@5.0.0\node_modules\tls.json]
 @ ./node_modules/.pnpm/https-proxy-agent@5.0.0/node_modules/https-proxy-agent/dist/agent.js 16:30-44
 @ ./node_modules/.pnpm/https-proxy-agent@5.0.0/node_modules/https-proxy-agent/dist/index.js
 @ ./node_modules/.pnpm/@pnp+nodejs@2.11.0/node_modules/@pnp/nodejs/net/proxy.js
 @ ./node_modules/.pnpm/@pnp+nodejs@2.11.0/node_modules/@pnp/nodejs/index.js
 @ ./lib/SPS/common/services/SPSLicense.js
 @ ./lib/webparts/spsButton/components/SPSButtons.js
 @ ./lib/webparts/spsButton/SpsButtonWebPart.js`

### Steps to Reproduce
Just created a SPFx project with version 1.13.1. Here is my Package.json
{
  "name": "spfx",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "cls && gulp clean && gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test",
    "preversion": "node ./tools/pre-version.js",
    "postversion": "gulp dist",
    "load": "cls && gulp clean && npm run serve",
    "openBrowser": "start https://mytenant.sharepoint.com/_layouts/15/workbench.aspx",
    "serve": "gulp bundle --custom-serve --max_old_space_size=4096 && fast-serve"
    
  },
  "dependencies": {
    "@microsoft/loader-load-themed-styles": "^1.9.55",
    "@microsoft/sp-component-base": "1.13.1",
    "@microsoft/sp-core-library": "1.13.1",
    "@microsoft/sp-http": "1.13.1",
    "@microsoft/sp-lodash-subset": "1.13.1",
    "@microsoft/sp-office-ui-fabric-core": "1.13.1",
    "@microsoft/sp-property-pane": "1.13.1",
    "@microsoft/sp-webpart-base": "1.13.1",
    "@pnp/graph": "^2.11.0",
    "@pnp/logging": "^2.11.0",
    "@pnp/nodejs": "^2.11.0",
    "@pnp/odata": "^2.11.0",
    "@pnp/sp": "^2.11.0",
    "@pnp/spfx-controls-react": "3.5.0",
    "@pnp/spfx-property-controls": "3.3.0",
    "date-fns": "^2.21.3",
    "office-ui-fabric-react": "7.156.0",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "typestyle": "^2.1.0"
  },
  "devDependencies": {
    "@microsoft/mgt": "^1.3.5",
    "@microsoft/microsoft-graph-types": "^1.12.0",
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "@microsoft/rush-stack-compiler-3.7": "0.2.3",
    "@microsoft/rush-stack-compiler-3.9": "^0.4.x",
    "@microsoft/sp-build-web": "1.13.1",
    "@microsoft/sp-module-interfaces": "1.13.1",
    "@microsoft/sp-tslint-rules": "1.13.1",
    "@types/react": "16.9.36",
    "@types/react-dom": "16.9.8",
    "@types/webpack-env": "1.13.1",
    "ajv": "~5.2.2",
    "gulp": "4.0.2",
    "gulp-sequence": "1.0.0",
    "lodash": "^4.17.20",
    "spfx-fast-serve-helpers": "~1.13.0",
    "spfx-uifabric-themes": "^0.8.0",
    "typescript": "~3.9.x",
    "webpack-bundle-analyzer": "^3.8.0"
  }
}

**Comment by koltyakov** [comment]
SPFx is a client side, Node.js is a server side technology. You can't use a Node.js package in SPFx.

**Comment by patrick-rodgers** [comment]
To expand on what @koltyakov says, you should not use client id and secret on the client side as both are then available in the browser. Please have a look at the [getting started guide](https://pnp.github.io/pnpjs/getting-started/#getting-started-with-sharepoint-framework).

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
