### ISSUE TITLE
Get List Items query encoding query chars

### ISSUE THREAD

**Issue by Dangerous-Mind** [pnp/pnpjs#2001]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.11.0 ]

Please specify what version(s) of SharePoint you are targeting: [ Online ]

### Expected / Desired Behavior / Question
The rest query should not return a error.

### Observed Behavior
When making a call to get list items it started giving the message 
```xml
<m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<m:code>-1, Microsoft.SharePoint.Client.InvalidClientQueryException</m:code>
<m:message xml:lang="en-US">The expression "ID,Title,*&cache=2022-01-06T23:07:24.331Z" is not valid.</m:message>
</m:error>
```
This started after updating to the @pnp/sp version 2.11.0 from the 2.0.5

The problem seams to be on the encoding of the query string.
The parameter I use to force SharePoint not to use Cache "*&cache=2022-01-06T22:47:44.068Z" is now being encoded on the query string and changing the & char to %26. This ruins the query.

### Steps to Reproduce
Create a solution
Add a query to a list
```typescript
sp.web.lists.getById(this.ListID).items
      .select("ID",
        "Title",
        `*&cache=${new Date().toISOString()}`
      ).get()
```
Check the call on the console/Network.
The generated query is :

`https://contoso.sharepoint.com/sites/Test/_api/web/lists('3519a07c-cd7d-3412-af4d-4e88c7a1d5e0')/items?$select=ID,Title,*%26cache%3D2022-01-06T23%3A07%3A24.331Z
`
Decoding the %26 back to & fixes the query.

**Comment by patrick-rodgers** [comment]
If you want to append something to the query string you can do the following:

```TypeScript
const items = sp.web.lists.getById(this.ListID).items.select("ID", "Title");

// just set it in the query
items.query.set("cache", new Date().toISOString());

const values = items();
```

That should correctly add it to the query string of the request. What you were doing was attempting to append your values to the end of the "$select" odata operator.

**Comment by patrick-rodgers** [comment]
Right on, I had forgotten or wasn't aware of that so wasn't a use case I knew we were supporting. Select was only ever meant to support the select props.

**Comment by Dangerous-Mind** [comment]
Since get items with expand elements creates a cache in SharePoint and will return exactly the same value even if we change one of the items.

We have a cache option on pnp (usingCaching). 
Can we add a option with Force No-Cache to it?

**Comment by koltyakov** [comment]
I'm not sure about situations when expand and selecting fields would cause any caching issues at all. It's not cached generally or in other words forcing a unique URL parameter is a very rarely needed workaround. 

The only case I can recall from top of my head is getting file's item by URL, when a file is removed and re-uploaded with the same name.

**Comment by patrick-rodgers** [comment]
usingCaching and what you are trying to do are unrelated. usingCaching places data in the local/session storage. I don't see much value in introducing something in v2 to force add a param like that to the query string. If it is something you need to do frequently it will be easier in v3 to do so consistently and we can add an example to the docs.

**Comment by koltyakov** [comment]
Found a case then a request actually cached in latest SPO.

- List A
  - Title
  - Lookup to List B
- List B
  - Title
  
 A request:
 
 ```typescript
 const data = await sp.web.lists
  .getByTitle('ListA')
  .items.getById(1)
  .select('Title,ListB/Title')
  .expand('ListB')
  .get();

console.log(data);
```

**Case 1**:

- Request List A item
- Change a title in List B item
- Request List A item
- ListB/Title value is cached

**Case 2**:

- Request List A item
- Change a title in List B item, change List A item (e.g. Title)
- Request List A item
- ListB/Title value is not cached
-
**Case 3**:

- Request List A items (not a single one)
- Change a title in List B item
- Request List A items (not a single one)
- ListB/Title value is not cached

**Comment by Dangerous-Mind** [comment]
I don't know if they fixed it. 
But it was so bad that if I made the same query on the browser console and received a xml response it would reply the same xml instead of json on the SPFx application although the header requested a json and that would crash the application.

At the time I posted a bug report in here to get a way to cancel the cached and I was advised to use the `*&cache=${new Date().toISOString()}` workaround.

> usingCaching and what you are trying to do are unrelated. usingCaching places data in the local/session storage. I don't see much value in introducing something in v2 to force add a param like that to the query string. If it is something you need to do frequently it will be easier in v3 to do so consistently and we can add an example to the docs.

You probably right and that might not be the best location to add something like this. 

I do a lot of lookups on my solutions and it's very bad to see that a value has not changed after you have saved it. 
For me is a big bug if we get a wrong information from the server. But that's on MS... Unfortunately we can't do much. Just find workarounds. 

Do you know what is the PNP previous version before started encoding the query string so that I can put my solution to work again?  
I would go back to V2.0.5 but I need to add some graph calls that were not appearing in the old version.

**Comment by koltyakov** [comment]
@Dangerous-Mind,

Please check this comment from Patrick: https://github.com/pnp/pnpjs/issues/2001#issuecomment-1007440585 

It is the way how to add a custom parameter with the recent PnPjs. Just the same approach forcing no-cache but a different way to add a parameter.

**Comment by Dangerous-Mind** [comment]
Thanks @koltyakov 
Almost forgot that comment from @patrick-rodgers.

Just started to test it and it seams that did the trick. It's solved. 
Thanks @patrick-rodgers
