### ISSUE TITLE
sp.search to get Hub's Associated Sites no longer works

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#2005]
### Category
- [x] Bug ?  I marked it as a bug but it might be on the sp side since my code has not changed.

### Version

Please specify what version of the library you are using: [     "@pnp/sp": "^2.0.12",    ]

Please specify what version(s) of SharePoint you are targeting: [    SP Online     ]

### Expected / Desired Behavior / Question
I have a webpart in production which uses sp.search and the current site's "departmentId" to get all sites related to the hub site my site is tied to... like "sibling associated sites".
It's in production and worked as of yesterday.

### Observed Behavior
Today, it no longer gives any results.  As of right now, it does work fine on my dev tenant but if it's a rolling change, I can't really tell what is different between the 2 tenants.... ie my dev tenant may not have received the same update as our corporate tenant.

The query is based on the 'departmentId' property found in the context._legacyPageContext and as shown in the screenshots of the results.  I did double check the Ids are the same so the departmentId is on the site.  what is happening on the search side.

NOTE:  I do use sp.search to search libraries in another webpart and that seems to still work.  So I'm thinking it's somehow related to the departmentId part of the query.

I also tested the PnpSearchV4 webparts and that does return some hub related files but also as of today, if I try to get the sites related to the hub it returns nothing.  Meaning, when I last tested, I was getting some results when searching for only associated sites and now I'm not.

### Steps to Reproduce
The function below usually returns the results in the screenshot.  Now, it just returns no items.  There is no error message and I have tested on multiple hub sites with multiple users.

```typescript

export function getAssociatedSites(departmentId: string, callback: any, entireResponse: any , custCategories, hubsCategory, ascSort: boolean, newData ) {

    //var departmentId = departmentId;
    // do a null check of department id
    //366df2ee-6476-4b15-a4fd-018dfae71e48 <= SPHub

    //Sort ascending by default
    let sortDirection = ascSort === false ? 1 : 0;

    console.log('current department ID:', departmentId );

    /**
     *  Updated search query per pnpjs issue response:
     *  https://github.com/pnp/pnpjs/issues/1552#issuecomment-767837463
     * 
     * GET Managed properties here:  https://tenanat-admin.sharepoint.com/_layouts/15/searchadmin/ta_listmanagedproperties.aspx?level=tenant
     */
    let sentToCallback = false;
    sp.search(<ISearchQuery>{
        Querytext: `contentclass:STS_Site AND departmentId:{${departmentId}}`,
          SelectProperties: ["*","Title", "SPSiteUrl", "WebTemplate","departmentId","SiteLogo","SiteDescription",
          "ContentModifiedTime","LastModifiedTime", "LastModifiedTimeForRetention","ModifiedBy","Created","Modified","CreatedBy","CreatedById","ModifiedById"],
          "RowLimit": 500,
//          "StartRow": 0,
          "ClientType": "ContentSearchRegular",
          TrimDuplicates: false, //This is needed in order to also get the hub itself.
        })
          .then( ( res: SearchResults) => {
    
            console.log('associated sites with URL/Desc', res);
            console.log(res.RowCount);
            console.log(res.PrimarySearchResults);
            entireResponse.hubs = res.PrimarySearchResults;

            entireResponse.hubs.map( h => {
                h.sourceType = hubsCategory;
            });
            sentToCallback = true;
            callback( entireResponse, custCategories, newData );

    }).catch((e) => {
        let errMessage = getHelpfullError(e, false, true);
        console.log('HubSiteFunctions: DID NOT FIND ANY ASSOCIATED SITES!');
        //alert( errMessage );
        entireResponse.hubs = ['Error',`Possible Network Error? --- ${errMessage}` ];
        callback( entireResponse, custCategories, newData ); 
    });

    return;

}
```
## Screenshot of results from prod tenant which
Should be showing a number of Associated sites but is not returning any items.
![image](https://user-images.githubusercontent.com/49648086/149233399-a1cdaa8a-f886-4cf4-8f54-e4fdcf350eb9.png)

## Screenshot of results from my dev tenant showing 6 "Associated sites"
![image](https://user-images.githubusercontent.com/49648086/149233464-0a9c5400-7819-4d09-aa00-7cb709c19fc1.png)

**Comment by sympmarc** [comment]
@mikezimm - Best for you to file a ticket with Microsoft to escalate.  Best way to push on this one.

@wobba- This seems to be hitting a lot of people.
