### ISSUE TITLE
Adding a file using Nodejs Streams - destination file empty

### ISSUE THREAD

**Issue by beyond94** [pnp/pnpjs#2007]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [^2.11.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
I'm implementing an SPFx webpart that allows users to download a page _and all its linked documents in HTML_ locally so it's available on their device when there is no internet connection. I've tried implementing the PnPJS "adding a file using nodejs streams" code for this, which should generate a stream from an existing file and then upload it to a SharePoint location.
[https://pnp.github.io/pnpjs/sp/files/#adding-a-file-using-nodejs-streams](url)

### Observed Behavior
When simply copy pasting the code from the documentation site, changing only the location / name of the file, the stream gets generated through the _.getStream()_ action and clearly has content (see _sr.knownLength_ in below screenshot):

![image](https://user-images.githubusercontent.com/5575507/149329535-e773d491-43ec-4cb8-9cf4-6f4e5640a2d0.png)

However, when the next line in the screenshot gets executed (_files.configure.add_), the file does get added to the document library with the correct name, but always only with 23 bytes of data (the original file is a couple of megabytes large). When opening the file, it obviously says the file is corrupt.

![image](https://user-images.githubusercontent.com/5575507/149330383-7952cb99-8c1d-444c-9e89-65b5a0b9116a.png)

![image](https://user-images.githubusercontent.com/5575507/149331234-c6315c42-7fb0-4a4d-85e2-b82ef90c5280.png)

### Steps to Reproduce
You can reproduce this issue simply by installing the @pnp/sp module in an SPFx webpart project and adding the sample code from [https://pnp.github.io/pnpjs/sp/files/#adding-a-file-using-nodejs-streams](url)

Thank you for your help with this issue!
Kind Regards

**Comment by patrick-rodgers** [comment]
Sounds like a bug, we'll have a look. Thanks for letting us know, sorry you hit that.

**Comment by patrick-rodgers** [comment]
I can't duplicate this so not sure it is a bug. I copied the code exactly from the example, updated the paths as you outline, and ran it on a 63 MB pptx file. All works fine and I am able to open the new file in SPO with no issues. Can you provide any additional details for this issue?

**Comment by beyond94** [comment]
> I can't duplicate this so not sure it is a bug. I copied the code exactly from the example, updated the paths as you outline, and ran it on a 63 MB pptx file. All works fine and I am able to open the new file in SPO with no issues. Can you provide any additional details for this issue?

Hello Patrick,

Thanks for trying to duplicate the bug - I ended up using a different technique to copy the files (pnpjs copy file from drive to another drive) as these were all located in Office 365 anyway (Onedrive for Business / SharePoint Online).
It may have been a misconfiguration on my end, which I assume since you've duplicated the code and don't have the same issue.
I'll close this issue for now, thanks anyway!

Kind Regards
