### ISSUE TITLE
[Question] Start a Workflow

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/pnpjs#2016]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

Hi,
Just wondering if there is any way to start a workflow with pnp js?
Thanks in advance!

**Comment by juliemturner** [comment]
Do you mean a SharePoint Design Workflow? What version of SharePoint are you referencing?

**Comment by YuriySamorodov** [comment]
hi @juliemturner , correct, SP Designer Workflow. Version does not matter much - we might go way with either one.

**Comment by juliemturner** [comment]
Here's the answer, I just googled, "launch sharepoint designer workflow through rest". You can do this with pnpjs by extending the spPost method for the endpoint but effectively it's just a rest call... https://dattabase.com/blog/start-workflow-using-rest
