### ISSUE TITLE
System.UnauthorizedAccessException for current user in AD Group

### ISSUE THREAD

**Issue by roberto-ajolfi** [pnp/pnpjs#2017]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version 

Please specify what version of the library you are using: [   1.13.1      ]

Please specify what version(s) of SharePoint you are targeting: [   SPO     ]

### Expected / Desired Behavior / Question
I'm using the library to get files from a folder in SiteAssets:

```
const folderItem = await sp.web.rootFolder
      .folders.getByName("SiteAssets")
      .folders.getByName("subfolder")
      .files.expand('listItemAllFields').get();
```

It's working fine when the current user is a SP Users or a user in a SP Groups but I get an UnauthorizedAccessException when the current user is part of an AD group used to provide access to that same folder (if I browse the library, the user can access the folder).

### Observed Behavior
The code works file except when the current user has granted access because it's part of an AD Group.

### Steps to Reproduce
- add a user to an AD Group used to provide assess in SP
- try to run the code above and it fails

**Comment by koltyakov** [comment]
It's not an issue with PnPjs or REST/API. And obviously nothing can be amended in the library when platform denies access.

When granting access via AD groups it's important to know that the permissions are not applied instantly, but synced. Sometimes this sync might take long or stuck.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
