### ISSUE TITLE
Shouldn't verbose logging execute a console.debug ?

### ISSUE THREAD

**Issue by kellywahl** [pnp/pnpjs#2019]
https://github.com/pnp/pnpjs/blob/bb2e5afc24c7c4ec133d8f790c8bcd36fe17b7d0/packages/logging/listeners.ts#L19

**Comment by kellywahl** [comment]
Shouldn't the log level of Verbose execute a console.debug instead of just copying the Information logging of console.log?

**Comment by juliemturner** [comment]
It certainly could, this is our default implementation. If you want to write a custom version and do things differently, please check out [this documentation](https://pnp.github.io/pnpjs/logging/#create-a-custom-listener).
