### ISSUE TITLE
Microsoft Graph: Getting the groups I belong to

### ISSUE THREAD

**Issue by miguelisidoro** [pnp/pnpjs#2025]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

2.11.0

Please specify what version(s) of SharePoint you are targeting: [         ]

SharePoint Online

### Question

Is there any way to use PnP Js to get the groups I belong to?

The endpoint is https://graph.microsoft.com/v1.0/me/transitiveMemberOf

I don't see it at https://pnp.github.io/pnpjs/graph/groups/.

If it possible, how can call that endpoint?

Thanks
Miguel

**Comment by juliemturner** [comment]
If we haven't yet implemented an endpoint, you can supplement the library by using an extension method, so in this case that would be:

```const groups = await graphGet<T>(GraphQueryable(graph.me.toUrl(), "transitiveMemberOf"));```

Where T is the typing of the resulting array of groups.

Aside, when this endpoint is implemented, it would be documented under users not groups as the me endpoint is a user.

**Comment by tavikukko** [comment]
You can also extend the query with that missing endpoint like this:

```typescript
const me = await graph.me.concat("/transitiveMemberOf")();
console.log(me)
```

**Comment by patrick-rodgers** [comment]
Added the transitiveMemberOf property to User. Will be part of 3.2
