### ISSUE TITLE
inBatch seems to not support addValidateUpdateItemUsingPath

### ISSUE THREAD

**Issue by trueleader** [pnp/pnpjs#2031]
### Category
- Question

### Version
Please specify what version of the library you are using: 2.11.0
Please specify what version(s) of SharePoint you are targeting: SPO

### Expected / Desired Behavior / Question
Create two items in list subfolder via batch call

### Observed Behavior
Error message: *This query is already part of a batch.*

### Steps to Reproduce
- Created new List "TestList"
- Activated folder creation
- Added folder "subfolder"
- Executed
```
	public async createTestItems(): Promise<void>
	{
		const list = sp.web.lists.getByTitle("TestList");
		const listUrl = await list.rootFolder.serverRelativeUrl.get();
		const targetFolder = `${listUrl}/subfolder`;

		// create single item in subfolder via batch: working
		let batch = sp.web.createBatch();
		list.inBatch(batch).addValidateUpdateItemUsingPath([
			{ FieldName: nameof<ISpAgendaItemPost>("Title"), FieldValue: "test item 1" }
		], targetFolder);
		await batch.execute();

		// create two items in subfolder via batch
		batch = sp.web.createBatch();
		list.inBatch(batch).addValidateUpdateItemUsingPath([
			{ FieldName: nameof<ISpAgendaItemPost>("Title"), FieldValue: "test item 2a" }
		], targetFolder);
		list.inBatch(batch).addValidateUpdateItemUsingPath([
			{ FieldName: nameof<ISpAgendaItemPost>("Title"), FieldValue: "test item 2b" }
		], targetFolder);
		await batch.execute();
	}
```

**Comment by trueleader** [comment]
Edit: fixed test-code

**Comment by patrick-rodgers** [comment]
if you replace "list" with "sp.web.lists.getByTitle("TestList")" your example should work. Under the hood the library thinks you are adding the list instance to a batch a second time. I get it doesn't appear that way and is a bit confusing, but we won't be working to change this behavior as it relates to how the entire pipeline works. Can you give the suggestion a try?

**Comment by trueleader** [comment]
wow, this really solves the issue.
It´s definitly something what must be known.

Most samples about programming includes some things as:
```
obj.callMethod1().callMethod2().callMethod3a();
obj.callMethod1().callMethod2().callMethod3b();
for (i=0; i < obj.callMethod1().callMethod2().callMethod3c(); i++) {}
```
Where nobody knows what resources (cpu, ram, time, ...) each callMethod1/callMethod2/callMethod3c require. And what things will internally change when methods are called multiple times.
So the better solution normally is
```
short = obj.callMethod1().callMethod2();
short.callMethod3a();
short.callMethod3b();
n = short.callMethod3c();
for (i=0; i < n; i++) {}
```
Its type of micro-optimization but most of the time my/our programms have some kind of performance problems. Batching is a solution of such a kind of problem too 😆 


My service contains accessors for all lists, only ´addValidateUpdateItemUsingPath´ seems to have broblems. 
What are the rules we have to follow?

The following batch works - is it, because the items are already an awaited result?:
```TypeScript
const agendaItemsFolderItem = await this._agendaItems.rootFolder
	.folders.getByName(containerFolderName).getItem();
const documentsFolderItem = await this._documents.rootFolder
	.folders.getByName(containerFolderName).folders.getByName(agendaItemFoldersContainerName).getItem();

const batch = sp.web.createBatch();
agendaItemsFolderItem.inBatch(batch).breakRoleInheritance(false);
agendaItemsFolderItem.roleAssignments.inBatch(batch).add(adminTeamGroupId, SpRolePermissionLevelEnum.FullControl);
agendaItemsFolderItem.roleAssignments.inBatch(batch).add(everyoneUserId, SpRolePermissionLevelEnum.Read);
documentsFolderItem.inBatch(batch).breakRoleInheritance(false);
documentsFolderItem.roleAssignments.inBatch(batch).add(adminTeamGroupId, SpRolePermissionLevelEnum.FullControl);
documentsFolderItem.roleAssignments.inBatch(batch).add(everyoneUserId, SpRolePermissionLevelEnum.Read);
await batch.execute();
```

**Comment by trueleader** [comment]
The initial quesion was related V2. 
V3 semantic does have a clear start, were an that should be batched beginns
