### ISSUE TITLE
How can I create an item and populate _ShortcutUrl?

### ISSUE THREAD

**Issue by svermaak** [pnp/pnpjs#2043]
### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    latest     ]

Please specify what version(s) of SharePoint you are targeting: [   online      ]

### Expected / Desired Behavior / Question
I can do this in PowerShell
$stream = [IO.MemoryStream]::new([Text.Encoding]::UTF8.GetBytes("[InternetShortcut]URL=https://xxx"))
Add-PnPFile -FileName "xxx.url" -Folder "Shared Documents" -Stream $stream -Values @{_ShortcutUrl="https://xxx"}

I cannot do the same in PnPJS (entirely possible that I am using the wrong approach)
    const file = await sp.web.getFolderByServerRelativeUrl(folderRelativeUrl).files.add(`${filename}.url`, `[InternetShortcut]\nURL=${destinationUrl}`, true);
    const item = await file.file.getItem();
    await item.update({
      "_ShortcutUrl": destinationUrl,
    });

### Observed Behavior
Console reports that _ShortcutUrl does not exist

### Steps to Reproduce
The above snippet

**Comment by juliemturner** [comment]
So the PowerShell library uses C#(CSOM) not REST to do it's work... which can often be different.  Since I'm not 100% sure what you're trying to accomplish I did some googling but am not sure I found the answer.  Effectively I found some solutions that pointed to the PowerShell you reference but there were others about [adding a link item in a document library](https://techcommunity.microsoft.com/t5/sharepoint-developer/sharepoint-365-rest-api-add-a-link-item-in-a-document-library/m-p/731247), although I'm not sure that's your goal.  I don't see how to update that field either, maybe others will have ideas.

**Comment by svermaak** [comment]
Thank you Julie

I am tying to create stubs (not links) as-in the same shortcuts Record Center left after declaring a file as a record

The PowerShell process is not doing exactly what I want either but it's my starting point

Any ideas welcome

**Comment by sympmarc** [comment]
I just added a Link to a Document item pointing to this issue into a Document Library called **Testing** and retrieved it via the API in the browser. 
`/_api/web/lists/getbytitle('Testing')/items`

It looks like the column for the link is just called `URL`.

![image](https://user-images.githubusercontent.com/1295627/152250818-614ec595-6529-4ed6-b1fd-4363c495704d.png)

**Comment by svermaak** [comment]
I managed to get links working

Ideally I would like to be able to create stub like Record Center and IBM Content Collector. After these things passes over a library the file looks the same (it has the same extension and application icon) except the icon gets a little arrow much link Windows Explorer shortcuts.

I don't know if this is possible anymore

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
