### ISSUE TITLE
Can I get SharePoint List's Power BI Report links visible in the list command bar?

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#2044]
### Category
- [x] Question

### Version

Please specify what version of the library you are using: [    Latest     ]
Please specify what version(s) of SharePoint you are targeting: [    Online     ]

### Expected / Desired Behavior / Question
Is it possible through pnpjs web lists api to get the link(s) to Power BI "Visualize the list" reports?
https://docs.microsoft.com/en-us/power-bi/create-reports/service-quick-create-sharepoint-list

I know I can manually get the link from the UI but I would like to bake it directly into a webpart.

![image](https://user-images.githubusercontent.com/49648086/152272179-3557108b-4030-429c-8897-6f9aba0ba328.png)

Thanks!

**Comment by patrick-rodgers** [comment]
I think you want to look at [SharePoint Framework's listview command set](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api).

**Comment by mikezimm** [comment]
@patrick-rodgers ,
I'm not sure if you understood my question.

In this case, I am not interested in making a command bar extension.

I am to get this list of already created "Visualize the list" reports that exist on the list.
Kind of like fetching the list items or settings.  Just want the links in a json object.

## My use case for the links:
I have a webpart that automatically shows many types of site/list related links all in one place.
I want to automatically get the report Urls to those reports so that they are all in one place.

In the case of these particular links, I have to actually go to a specific list to get them... can't even see them in the command bar when I have a list view webpart.

Does this make sense?
