### ISSUE TITLE
Support to use graph api Search on SharePoint lists items

### ISSUE THREAD

**Issue by miguelisidoro** [pnp/pnpjs#2050]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.11.0   ]

Please specify what version(s) of SharePoint you are targeting: [     SharePoint Online    ]

Hello,

Is it possible to use PnP JS to make Graph Search calls on SharePoint lists to retrieve items from a SharePoint List?
My end goal is to get items from a SharePoint List filtered by a date range.
SharePoint REST API is an option but I would prefer to use Graph Search if possible, using PnP JS.

The documentation at https://pnp.github.io/pnpjs/graph/search/ is not very clear.

Can you provide an example if possible?

Thanks
Miguel

**Comment by juliemturner** [comment]
Our documentation does not "redocument" the graph endpoints.  So, to see what can be done with a particular endpoint you should refer to the graph documentation, for Search (v1.0) that is here: https://docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0

**Comment by miguelisidoro** [comment]
@juliemturner , I understand and agree with you but it would be interesting to have 2 or 3 examples like almost all other pages in the PnP JS documentation that is generally good.

One of the most important examples would be how to get data from SharePoint list items using Microsoft Graph Search.

Do you think it is possible?

Thanks

**Comment by tavikukko** [comment]
Here is something to get started:

Go to [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer), log in and open the Search section:

![image](https://user-images.githubusercontent.com/2223355/152962483-14747523-989a-4cb3-911c-66d99db8e0ec.png)

Select "search listitems" and you will get the payload what to use when searching listitems.

```
{
    "requests": [
        {
            "entityTypes": [
                "listItem"
            ],
            "query": {
                "queryString": "issue"
            },
            "fields": [
                "id",
                "name",
                "contentclass",
                "title",
                "fooCustomProperty"
            ]
        }
    ]
}
   ```

Now paste that payload to your PnPJS graph search:

```
import { graph } from "@pnp/graph";
import "@pnp/graph/search";

const results = await graph.query({
    "requests": [
        {
            "entityTypes": [
                "listItem"
            ],
            "query": {
                "queryString": "issue"
            },
            "fields": [
                "id",
                "name",
                "contentclass",
                "title",
                "fooCustomProperty"
            ]
        }
    ]
});
```

Now it's up to you how to create the right query to retrieve relevant results.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
