### ISSUE TITLE
getFileByServerRelativeUrl  from other site reports "File not found"

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#2051]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.11.0   ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]
### Expected / Desired Behavior / Question
On a web part imbedded in the root site of the tenant the code:
`blob = await sp.web.getFileByServerRelativeUrl('/teams/1462.401/DPCDocuments/ATR%20Test%2027.docx').getBlob(); `
Should not not report `The file /teams/1462.401/DPCDocuments/ATR%20Test%2027.docx does not exist.` 

### Observed Behavior
Should not not report `The file /teams/1462.401/DPCDocuments/ATR%20Test%2027.docx does not exist.` 

Can I change the context of sp to the current site collection?  

Thank you

**Comment by juliemturner** [comment]
I'm gathering that the file is in a different site at the url `/teams/1462.401`. If that is a correct interpretation of your issue, then please see the docs on [Web](https://pnp.github.io/pnpjs/sp/webs/#access-a-web), then specifically the heading "Create a web instance using the factory function". After that then you can use that web to get the file.

**Comment by Ofer-Gal** [comment]
const sourceWeb = Web(window.location.origin +'/teams/1462.401/'); 
and blob = await sourceWeb.getFileByServerRelativeUrl( 

Solve it for me. Thank you
