### ISSUE TITLE
 TypeError when using @pnp/sp/utilities

### ISSUE THREAD

**Issue by sandrokahn** [pnp/pnpjs#2082]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   3.0.0      ]

Please specify what version(s) of SharePoint you are targeting: [     SharePoint Online    ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
In a ListView Command Set  `sp.utility.getCurrentUserEmailAddresses(); ` and  `sp.utility.sendEmail()` are called to send an email to the current user.

### Observed Behavior
The function `sp.utility.getCurrentUserEmailAddresses(); `  fails with the message:
> TypeError: Cannot read properties of undefined (reading 'getCurrentUserEmailAddresses')

If I hardcode the email address  `sp.utility.sendEmail()` fails with the following message:
> TypeError: Cannot read properties of undefined (reading 'sendEmail')

I used the same code minus the line `const sp = spfi().using(SPFx(this.context));` on version 2 and it worked. Do I need to call it differently in version 3? I couldn't find anything in the documentation of @pnp/sp/utilities regarding that.

### Steps to Reproduce
Call the following function in a ListView Command Set
```
private async _sendMail() {
    try {
      const sp = spfi().using(SPFx(this.context));
      const currentWeb = await sp.web();   
      let addressString: string = await sp.utility.getCurrentUserEmailAddresses();   
      const emailProps: IEmailProperties = {
        To: [addressString],
        Subject: currentWeb.Url,
        Body: "This is the body.",
        AdditionalHeaders: {
          "content-type": "text/html"
        }
      };
      await sp.utility.sendEmail(emailProps)
    } catch (e) {
      console.log(e);
    }
  }
```

**Comment by patrick-rodgers** [comment]
We'll have a look, thanks for reporting this.
