### ISSUE TITLE
What is the latest version of PNP/SP for SharePoint 2019 ?

### ISSUE THREAD

**Issue by bkvwilson** [pnp/pnpjs#2088]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [        ]
Please specify what version(s) of SharePoint you are targeting: [  1.4.1  for SP 2019     ]

### Question

For SPFX projects targetting SharePoint 2019 on premise, what is the latest version of @PNP/SP that is recommended to target 1.4.1 SPFX / SP 2019 ?

For example,

```import { ISiteUserInfo } from '@pnp/sp/site-users/types'; ``` 

This only appears in V2  of @PNP/SP but is not available in V1

Thanks for your help. 
Brian

**Comment by juliemturner** [comment]
Please see documentation for Version 2 here: https://pnp.github.io/pnpjs/v2/SPFx-on-premises/ 
We have had [reports](https://github.com/pnp/pnpjs/issues/1965) that version 2.0.9 is the last version that could use used with SPFx 1.4.1 but this has not been tested by anyone else.

**Comment by bkvwilson** [comment]
Thanks Julie, will give it a go and report back with results from my 2019 dev environment
