### ISSUE TITLE
Get Presence of IUser

### ISSUE THREAD

**Issue by foxxycodes** [pnp/pnpjs#2090]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.0.1]

Please specify what version(s) of SharePoint you are targeting: [1.13.1]

### Question
`Presence` is not available on the `IUser` object anymore. What am I expected to do instead?

**Comment by aaademosu** [comment]
You could either do
```
    const u = await graph.users.getById('GUID')();
    console.log( u.presence );
```
or 

```
    const u: IUser = graph.users.getById('GUID');
    const p = await u.select('presence')();
```

**Comment by foxxycodes** [comment]
@aaademosu This always returns `undefined`.
Before i migrated to @pnp/grpah to v3, i wrote it like this:

``` typescript
export const getUserPresence = async (user: ExtendedUser) => {
  if (user.id) {
    return await graph.users.getById(user.id).presence();
  }
};
```

**Comment by aaademosu** [comment]
@foxxycodes  Will run some tests and see if i have a similar experience.

**Comment by patrick-rodgers** [comment]
If there was a method "presense" previously removing it was a miss, we'll need to get that back in. Sorry about that hiccup.

**Comment by aaademosu** [comment]
@patrick-rodgers [this](https://github.com/pnp/pnpjs/blob/version-2/packages/graph/cloud-communications/types.ts) used to exists in v2 but is missing in v3.
