### ISSUE TITLE
Property 'lists' does not exist on type 'IWeb & IInvokable<any> v3.0.0 upgrade

### ISSUE THREAD

**Issue by asith-w** [pnp/pnpjs#2094]
### Category 
-  Question 

### Version

Please specify what version of the library you are using: [     "@pnp/sp": "^3.0.1"    ]

Please specify what version(s) of SharePoint you are targeting: [   Online  ]

 
### Expected / Desired Behavior / Question
I was trying to below convert pnp v2 code to v3 . it is taken from this [sample ](https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-news/src/webparts/reactNewsWebpart/components/Service/SPServices.tsx#L16)which was i am testing 
```
 let siteWeb = new Web(Site);
 let Likes: any = await siteWeb.lists.getByTitle("Site%20Pages").items.getById(ID).getLikedByInformation();
```
I replaced thee Web object with spfi() as v3 doc. but still getting error .how do i fix this issue 

```  
const siteWeb = spfi("Site URL ").using(SPDefault(this.context));   
```   

![image](https://user-images.githubusercontent.com/5784846/154496084-f7b395dc-4a74-400c-abb6-1d955cfaaae9.png)

**Comment by juliemturner** [comment]
That sample doesn't show any imports in that particular file... they may have done it in another way.
Did you import `import "@pnp/sp/lists";`

**Comment by asith-w** [comment]
@juliemturner thanks error goes away after importing the import "@pnp/sp/lists"
