### ISSUE TITLE
Folder.copyTo results in 403

### ISSUE THREAD

**Issue by barkdoll** [pnp/pnpjs#2096]
Greetings PnpJS team,

My research did not yield any results related to the issue with `Folder.copyTo`, but I did run into a nearly identical issue with `Folder.moveTo` (#1686). 

[I have submitted a pull request](https://github.com/pnp/pnpjs/pull/2093) to address this issue for `copyTo`— in the same way that #1686 was fixed.

- #2093

### Category
- [ ] Enhancement
- [x] Bug ?
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.12.0 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

### Expected / Desired Behavior / Question
Trying to copy a folder within one library from
`/sites/my-site/library/my-folder` to
`/sites/my-site/library/subfolder/my-folder`
should yield a successful result.

### Observed Behavior
The copy action results in a 403 response with the following body:
```txt
{ 
  Error: Error making HttpClient request in queryable [403] Forbidden ::> 
  {
    "error": {
      "code": "-2147024891, System.UnauthorizedAccessException",
      "message": { 
        "lang": "en-US",
        "value": "Access denied. You do not have permission to perform this action or access this resource."
      }
    }
}
```

### Steps to Reproduce
```ts
import { SPFetchClient } from "@pnp/nodejs-commonjs";
import { sp, Web } from "@pnp/sp-commonjs";

sp.setup({
  sp: {
    baseUrl: "https://xxx.sharepoint.com/sites/site1",
    fetchClientFactory: () => {
      return new SPFetchClient(
        "https://xxx.sharepoint.com/sites/site1",
        "clientID",
        "clientSecret"
      );
    },
  },
});

const f = async () => {
  const source = "/sites/site1/Docs/folder-target";
  const target = "/sites/site1/Docs/nested/folder-target";
  try {
    const r = await sp.web.getFolderByServerRelativeUrl(source).copyTo(target);
    console.log("ok");
    return true;
  } catch (ex) {
    console.log("error");
    console.log(ex);

    return ex;
  }
};

f().then((r) => {
  console.log("done");
});
```

**Comment by patrick-rodgers** [comment]
Thanks for finding this and submitting a fix! We'll have a look and get it merged in for the next release.
