### ISSUE TITLE
'Module "@pnp/sp" has no exported member 'sp'

### ISSUE THREAD

**Issue by zachroberts8668** [pnp/pnpjs#2098]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     v3    ]

Please specify what version(s) of SharePoint you are targeting: [     Online    ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

Expecting SP import from "@pnp/sp" following documentation on site.

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

VS Code says 'Module "@pnp/sp" has no exported member 'sp'

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

Create new SPFx package install PnPJS and attempt to import SP

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!
![UBgyH1lwzx](https://user-images.githubusercontent.com/19337142/154742670-64e423a3-7e5d-4aa4-9f6b-752e0a512501.png)

**Comment by juliemturner** [comment]
Please review the [transition guide](https://pnp.github.io/pnpjs/transition-guide/) for moving from v2->v3. And then review [getting started](https://pnp.github.io/pnpjs/getting-started/) and that should help you resolve your issue.

**Comment by gertperdZA** [comment]
I am having the same problem as of today. This must have been a recent update.

**Comment by AritzAzkondo** [comment]
I've used the sp import on a project created back in November 2021, and worked fine, created a new project today, and i'm running the same issue.

![image](https://user-images.githubusercontent.com/89973161/156385627-34c31723-3f0f-4171-a1fc-f2abbf8ee5c3.png)
