### ISSUE TITLE
@pnp/sp/views Fold in JSON List Formatting

### ISSUE THREAD

**Issue by Arknev** [pnp/pnpjs#210]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [1.1.4]

### Expected / Desired Behavior / Question
In the community call (SharePoint Dev Ecosystem (PnP)) on 23Aug18, JSON list formatting was discussed and demonstrated. I asked if this functionality could be folded into @pnp/sp/views. Peter Rodgers suggested that I add an issue to address this request.

**Comment by patrick-rodgers** [comment]
Thanks for the idea, we will have a look at implementing it for the October release.

**Comment by patrick-rodgers** [comment]
Had a quick look at this, it seems like you just need to [update a property of the field](https://github.com/SharePoint/sp-dev-solutions/blob/master/solutions/ColumnFormatter/src/webparts/columnFormatter/components/ColumnFormatterEditorCommands.tsx#L642) as shown in @thechriskent 's column formatter. You can already do that, so what other functionality are you suggesting we add? There doesn't look to be anything special I see behind the scenes we aren't supporting?

**Comment by patrick-rodgers** [comment]
Going to close this as I am not sure what work we need to do to enable this scenario. It seems like this is already supported as mentioned above. Please _reopen_ the issue if I've missed something and we'll circle back and see what we need to add. Thanks!
