### ISSUE TITLE
Authentication without redirect, not popup possible?

### ISSUE THREAD

**Issue by jimmyalfSoleil** [pnp/pnpjs#2101]
### Category
- [ ] Enhancement
- [ ] Bug
- [ X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    3.0.1     ]

Please specify what version(s) of SharePoint you are targeting: [       Online  ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

Is there a way to use login redirect and not popup login with:
const sp = spfi("https://tenant.sharepoint.com/sites/dev").using(SPBrowser(), MSAL(configuration, authParams));
like you were able to do with msaljsclient:
this.myMSALObj.loginRedirect(...

I'm building a standalone NodeJS-app and popup-blockers is an issue.

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!

**Comment by juliemturner** [comment]
Maybe I'm confused, if you're building a stand-alone NodeJS app then it's not a "Browser", so I think you'd just want to use the NodeJS + MSAL + SP/Graph auth methods... https://pnp.github.io/pnpjs/concepts/authentication/#msal-nodejs

**Comment by jimmyalfSoleil** [comment]
My bad, lacking some knowledge :-) 
Is it possible to do a redirect instead of popup with with NodeJS + MSAL + SP/Graph?

**Comment by koltyakov** [comment]
Please check if redirect options works for you https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-sign-in?tabs=javascript2

**Comment by jimmyalfSoleil** [comment]
Thanks! I used similar stuff in pnpjs v2, I used libraries:
import { UserAgentApplication } from "msal";
import { MsalClientSetup } from "@pnp/msaljsclient";
and then using: 
myMsal.loginRedirect()
followed by
    sp.setup({
        sp: {
          baseUrl: baseURL,

          fetchClientFactory: MsalClientSetup(
            {
              auth: msalConfig,
            },
            [baseURL +"/.default"]
          ),
        }

But from what I can see its not possible to combine msaljsclient library with authentication in pnpjs v3, or is it?

**Comment by patrick-rodgers** [comment]
The @pnp/msaljsclient lib is for use in the browser, you can use the [SPDefault](https://pnp.github.io/pnpjs/concepts/authentication/#msal-nodejs) in node, which uses msal-node under the hood. We used a fairly generic msal flow, you can [write your own behavior modeled on ours](https://github.com/pnp/pnpjs/blob/version-3/packages/nodejs/behaviors/msal.ts) to match your needs for supporting other flow types.

We don't have plans to support every possibility within the library, that is the power of the new behavior based model you can customize it to match your needs.

**Comment by jimmyalfSoleil** [comment]
Thank you so much! You're doing a great job!
