### ISSUE TITLE
confused about pnpclient storage

### ISSUE THREAD

**Issue by kongmengfei** [pnp/pnpjs#2109]
I am developing a spfx solution, which contains a lot of webparts. some data/requests are all the same. I notice that there is pnpclient storage: https://pnp.github.io/pnpjs/core/storage/

In react webpart A, I make a request then store data into pnpclient storage  in `componentDidMount()` method.  Then I want to consume this data in webpart B,

But there is a concern:  

Since the request will take some time, webpart b may try to get the data from pnpclient storage before the data is available.

So what's the best practice to store the data?

thanks

**Comment by juliemturner** [comment]
What you're looking to do is a fairly advanced architecture... effectively what you need to do is create a service as an external library that both of your web parts reference (you would either host this in some sort of CDN -- like Azure etc) or use an [SPFx library component](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/library-component-overview) (which I'm not a fan of but you should make your own judgement)... effectively you create a function that gets an instance of the service and then internal properties that tell you if the data is ready to be consumed and whomever calls the service first, starts the process.... 

```TypeScript
export default class MyService {
  private static _instance: MyService = null;

  public static getInstance(): MyService {
      if (!MyService ._instance) {
        MyService._instance = new MyService();
      }
      return MyService._instance;
    }
}
```

I did a talk on this topic but it was only a 30 min one so it's not as deep as it could be: https://www.youtube.com/watch?v=7dZ_tBqvyr8

**Comment by patrick-rodgers** [comment]
This question deals with things outside of this library's scope - BUT it's a good question. [I've created this sample](https://github.com/pnp/spfx-reference-scenarios/tree/main/samples/ace-shared-state) showing one way to achieve this using an SPFx library component.

As well I will demo and explain it on the March 29 Platform call ([invite](https://aka.ms/m365-dev-call)). If you can't make the call the recording will be available shortly after.
