### ISSUE TITLE
TypeError: sp.profiles.myProperties is not a function

### ISSUE THREAD

**Issue by kofrimpong** [pnp/pnpjs#2116]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.0.1 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online]

### Expected / Desired Behavior / Question
Should be able to retrieve currently logged-in user profile properties

### Observed Behavior
TypeError: sp.profiles.myProperties is not a function

### Steps to Reproduce
``` ts
import { spfi, SPFx } from "@pnp/sp";

// ...

protected async onInit(): Promise<void> {
    await super.onInit();
    const sp = spfi().using(SPFx(this.context));
    const profile = await sp.profiles.myProperties();
}

// ...
```

**Comment by juliemturner** [comment]
I can't tell from your code snippet, but the error would imply you're missing imports. Profile documentation here: https://pnp.github.io/pnpjs/sp/profiles/#profiles

**Comment by kofrimpong** [comment]
This
```js
import "@pnp/sp/profiles";
```
doesn't resolve it.

**Comment by juliemturner** [comment]
Ok, I will have a look at it. Thank you for reporting the issue.

**Comment by juliemturner** [comment]
So I tested this with the latest version 3.0.2 and couldn't replicate the issue. We did fix this in the 3.0.1 release, is it possible that you didn't actually get that version installed? Regardless now that you have the import I might try upgrading to 3.0.2 and see if your issue is fixed.

**Comment by kofrimpong** [comment]
@juliemturner Just updated to version 3.0.2 and experiencing the same issue. I am using it in SPfx v1.13.1. Did you do your test it in SPFx app?
![image](https://user-images.githubusercontent.com/4720269/155223665-b19c8b97-0286-4ab2-9055-67bdef11503a.png)

**Comment by patrick-rodgers** [comment]
myProperties isn't a function - so this is a bug in two ways. First in the docs I suspect but also in the update to v3 we are invoking the queryable:

```TypeScript
    /**
     * Gets user properties for the current user
     *
     */
    public get myProperties(): ISPInstance {
        return <any>Profiles(this, "getmyproperties")();
    }
```

It is meant to be a property so you can select the properties you want to return. We'll get this fixed, but this is the source of your error.
