### ISSUE TITLE
Interface missing error (nodejs 3.0.1)

### ISSUE THREAD

**Issue by WhatzzUp** [pnp/pnpjs#2117]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   3.0.1      ]

Please specify what version(s) of SharePoint you are targeting: [    SharePoint Online     ]

### Observed Behavior
I followed the nodejs instruction under https://pnp.github.io/pnpjs/getting-started/#getting-started-with-nodejs and added the packages via

`npm i @pnp/sp @pnp/nodejs`.

After starting our services the interfaces `IFileUploadProgressData` `IFileAddResult` at `@pnp/nodejs/sp-extensions/stream.d.ts`  seems to be missing. May i have forgot something? Thanks for helping :-) 

<img width="1618" alt="Screenshot 2022-02-22 at 20 14 18" src="https://user-images.githubusercontent.com/23344282/155202639-09c8d3e4-ee2e-43df-90f3-60daaff6fd6b.png">
<img width="1616" alt="Screenshot 2022-02-22 at 20 13 42" src="https://user-images.githubusercontent.com/23344282/155202646-b0a5dbe1-41e6-436a-a55a-6e465a8dc96e.png">

### Steps to Reproduce
- `npm i @pnp/sp @pnp/nodejs` (3.0.1)

**Comment by juliemturner** [comment]
I don't see where you're importing them?
i.e. 
`import {IFileUploadProgressData } from "@pnp/sp/files";

**Comment by WhatzzUp** [comment]
@juliemturner me either - the import is missing in `@pnp/nodejs/sp-extensions/stream.d.ts`

**Comment by juliemturner** [comment]
I'm sorry I cannot replicate what you're seeing. Maybe try updating to the 3.0.2 release that we just pushed... I would need more information to replicate your issue.

**Comment by patrick-rodgers** [comment]
Confused on what's happening here. If you look at our source for the stream extensions those [interfaces are indeed imported](https://github.com/pnp/pnpjs/blob/version-3/packages/nodejs/sp-extensions/stream.ts#L3). But in the .d.ts file (I checked the package) it seems to be stripped out. No idea why.

You are I assume based on the screen shots using TypeScript - can you try setting `"skipLibCheck": true,` in your tsconfig and see if that helps?

**Comment by patrick-rodgers** [comment]
I can reproduce this and skipLibCheck removes the errors. Would suggest including that in your tsconfig.json. It helps with stuff like this and speeds up your transpiling as all the deps are ignored for type checking.

**Comment by WhatzzUp** [comment]
@patrick-rodgers yes, it works with "skipLibCheck" - thx!
