### ISSUE TITLE
Issue with getAll() SP2013 on-prem

### ISSUE THREAD

**Issue by c-eiser13** [pnp/pnpjs#212]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  1.1.5-3       ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Ability to use getAll() in SP2013 on prem.

### Observed Behavior
In the beta release, the addition of the header parameter has gotten me past the 406 invalid header issue. However, there now appears to be an issue with the $top parameter where a ? is added at the end.

![1](https://user-images.githubusercontent.com/42096464/44734102-c02ce800-aaae-11e8-92bf-1abe225574dc.PNG)

This is the URL in the network tab of the browser:

![2](https://user-images.githubusercontent.com/42096464/44734118-ccb14080-aaae-11e8-8387-8b679cc48b60.PNG)

Removing the ?, the call is successful.

### Steps to Reproduce
Running 1.1.5-3 in Sp2013 on prem, use the getAll() function against a list.

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
Thanks for reporting this, was able to confirm the bug and got it fixed in the uber PR sitting there for the next release. Thanks for testing the beta, you helped us catch this bug before it got out. Appreciate it!

**Comment by patrick-rodgers** [comment]
Just published an updated beta with the fix, 1.1.5-4. If you get a chance please give that a shot, should have to back to working.

**Comment by c-eiser13** [comment]
Thanks @patrick-rodgers , tested the beta and its working great!
