### ISSUE TITLE
[Question] CommonJS LTS 

### ISSUE THREAD

**Issue by WhatzzUp** [pnp/pnpjs#2123]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    3.0    ]

Please specify what version(s) of SharePoint you are targeting: [    Online     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Thanks a lot for your great work! A general question we have is whether the commonJS version of pnpjs has LTS or only the ESM version is still being developed? Actually we have to use commonJS base.

Background: Currently it is difficult for us to switch to ESM. Currently we check if and how it is possible to integrate single npm modules on ESM basis on typescript (commonJS) . If anyone has an clue for me to run pnpjs v3 under typescript (4.3.X), I would be very grateful.

tsconfig.json
```json 
{
  "compilerOptions": {
    "module": "commonjs",
.
.
.

```

Thank you for your time!

**Comment by patrick-rodgers** [comment]
You are running in node? What version?

**Comment by WhatzzUp** [comment]
@patrick-rodgers thx for your fast reply

we use node v16.13.2

**Comment by patrick-rodgers** [comment]
After some research I have [added section to the docs](https://pnp.github.io/pnpjs/getting-started/#node-project-using-typescript-producing-commonjs-modules) and a sample showing how to do what you want. This is not specific to pnpjs, rather how to deal with your need to output commonjs while importing esm inside a TS project.

Give that a shot and let us know if it works for you. This would work well with our [project-preset pattern](https://github.com/pnp/pnpjs/tree/version-3/samples/project-preset) as well.

**Comment by WhatzzUp** [comment]
@patrick-rodgers thank you so much for your research! I will check it out if we can use the experimental flag in our project -> need green light from our architects.

Maybe you can answer my general question: [...] if the commonJS  (2.X) version of pnpjs has LTS or only the ESM (3.X) version is still being developed. Or maybe better: if we use 2.X, are there any feature differences with 3.X?
