### ISSUE TITLE
Search throws error in v3

### ISSUE THREAD

**Issue by h3nn3** [pnp/pnpjs#2124]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ v3 ]

Please specify what version(s) of SharePoint you are targeting: [ SPO ]

### Expected / Desired Behavior / Question
Using getSP().search("test") should return something or at least Code 200

### Observed Behavior
Getting following error: query is not a method inside postquery.

### Steps to Reproduce
Create spfx webpart, install pnp/sp, set up spfx context, try to call search endpoint with getSP().search("test"). Watch network in console.

Not sure what i did wrong. Getting web or list items is no problem and works just fine. Just the search endpoint doesnt work.

**Comment by juliemturner** [comment]
Yes, this is a known issue and a [PR](https://github.com/pnp/pnpjs/pull/2103) has been submitted to fix it. It will be reviewed and incorporated soon.
