### ISSUE TITLE
let  changeTokenStart:IChangeToken - what kinda a date to use if i need changes the last 5 days?

### ISSUE THREAD

**Issue by trillian74** [pnp/pnpjs#2125]
- [ x] Question

Sharepoint online
"@pnp/nodejs-commonjs": "^2.12.0",
"@pnp/sp-commonjs": "^2.12.0"

I am really struggling finding an example on correct use of the changetokenstart in a query - everything i try fails
It's the date that seems tricky - i can see that this works in c#, but i'm looking for the js/ts side of if

this is probably very easy, but i can't seem to get it right

```
let l = await sp.web.lists.getById(notification.resource);
let historyList = await (await sp.web.lists.ensure("Deltas", "", 100, false)).list;
let  changeTokenStart:IChangeToken =  {StringValue : `1;3;${notification.resource};${HOW SHOULD THIS ACTUALLY BE IN JS/TS};-1`};
      let chngQry: IChangeQuery = {
        Add: true,
        // Update: true,
        // DeleteObject: true,
        Item: true,
        // File:true,
        // SystemUpdate: true,
        ChangeTokenStart: changeTokenStart,
      };

      let data = await l.getChanges(chngQry);
      context.log(data);
    } catch (error) {
        context.log(error);
        context.done(error);
    }
```

thx for all the great work
Ole

**Comment by trillian74** [comment]
i think i found a helping hand https://github.com/pnp/sp-dev-fx-extensions/blob/676dcc2b7098af9387e6f9f13a9704c8dd014094/samples/react-application-webhooks-notification/src/extensions/webhooksToastNotifications/WebhooksToastNotificationsApplicationCustomizer.ts#L124 toTicks


using this toTicks method solved my problems... It seemed to be the only place that had any sample or documentation on this... SOLVED:)

**Comment by juliemturner** [comment]
@trillian74 -- please feel free to submit a sample to the docs for future users.
