### ISSUE TITLE
node_modules/@pnp/queryable/queryable.d.ts(10,115): error TS1005: ',' expected.

### ISSUE THREAD

**Issue by snehasis-samal-sharepoint** [pnp/pnpjs#2126]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [Yes ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    

Node: **14.15.0**, other versions can be found as follows:
  "dependencies": {
    "@microsoft/sp-core-library": "1.13.1",
    "@microsoft/sp-lodash-subset": "1.13.1",
    "@microsoft/sp-office-ui-fabric-core": "1.13.1",
    "@microsoft/sp-property-pane": "1.13.1",
    "@microsoft/sp-webpart-base": "1.13.1",
    **"@pnp/graph": "^3.0.2",
    "@pnp/sp": "^3.0.2",**
    "office-ui-fabric-react": "7.174.1",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  },
  "devDependencies": {
    "@types/react": "16.9.51",
    "@types/react-dom": "16.9.8",
    "@microsoft/sp-build-web": "1.13.1",
    "@microsoft/sp-tslint-rules": "1.13.1",
    "@microsoft/sp-module-interfaces": "1.13.1",
    "@microsoft/rush-stack-compiler-3.9": "0.4.47",
    "gulp": "~4.0.2",
    "ajv": "~5.2.2",
    "@types/webpack-env": "1.13.1"
  }     ]

Please specify what version(s) of SharePoint you are targeting: [     SharePoint Online    ]

### Expected / Desired Behavior / Question
Q: Build failed after installing "**npm install @pnp/sp --save**" as I am using the below codes

```
import { useEffect, useReducer, ReducerAction, Dispatch } from "react";
import { sp } from "@pnp/sp";
import { IHero, IHeroImage } from "../models/Hero";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
```

Please check screenshots attached
![Error1-Screenshot](https://user-images.githubusercontent.com/100408026/155684643-8a98d612-8b25-448f-af87-88bcf55d676b.png)
![Error2-Screenshot](https://user-images.githubusercontent.com/100408026/155684676-118633c0-ecdf-43eb-a452-ae11965db886.png)

**Comment by quantrpeter** [comment]
i got this too

**Comment by juliemturner** [comment]
Based on your package.json I think you're missing the updates to Typescript that are needed... can you please refer to [this guidance](https://github.com/pnp/pnpjs/issues/1636) and see if that helps? now that 1.14 is released we really need to finalize the docs on getting started but I just haven't had time....

**Comment by Miky971** [comment]
I tried it. It works for me. Thanks @juliemturner

**Comment by snehasis-samal-sharepoint** [comment]
Thank you very much @juliemturner !!

I tried with the above steps, it worked fine, though having some other issues & hope its due to the other syntax change to get the data as it seems no .get() or getAll().

`        const allItems: ITeam[] = await sp.web.lists
          .getByTitle("Hero Teams")
          .items.filter(
            'FrontHeroId eq ${hero.Id} or MiddleHeroId eq ${hero.Id} or BackHeroId eq ${hero.Id}'
          )
          .get();`

Found the [Transition guide](https://pnp.github.io/pnpjs/transition-guide/), will follow the same to resolve the below issues.

![Error3-Screenshot](https://user-images.githubusercontent.com/100408026/155845494-59711e01-d1c4-4317-96d3-bd401b8447d1.png)

**Comment by aychaudh** [comment]
this @pnp/sp version **resolved** my issue try to uninstall @pnp/sp and install the below version

- **npm uninstall @pnp/sp**
then run below command
- **npm i @pnp/sp@2.11.0**

**Comment by juliemturner** [comment]
@aychaudh -- That's fine but you are now using version 2 of the library, not version 3.... which is totally your option, but be aware there is no LTS for version 2.

**Comment by aychaudh** [comment]
> @aychaudh -- That's fine but you are now using version 2 of the library, not version 3.... which is totally your option, but be aware there is no LTS for version 2.

ok, but if I am using version 3 I am getting this error

**Comment by juliemturner** [comment]
@aychaudh Given that others with the issue were able to fix it by following the detailed guidance in our [getting started documentation](https://pnp.github.io/pnpjs/getting-started/#getting-started-with-sharepoint-framework) I suspect that you're just missing something, but I cannot tell based on what you have shared at this point.  This issue is closed, so if you want to make another attempt to use V3 and are still having issues please submit a new issue with the details of your problem and we'll try and help you out.
