### ISSUE TITLE
How to identify the reply as in response to post for the discussion using PnP JS?

### ISSUE THREAD

**Issue by spvjebaraj** [pnp/pnpjs#2133]
Team, I am working on the SPFx project to get the items from the discussion board list using PnP. I am using the below code to get the reply items of the particular discussion.

`
const fileRef = "/sites/sitename/Lists/MyDiscussion/Discussion1";
const result = await list.renderListDataAsStream({
      ViewXml: "<view></view>",
      FolderServerRelativeUrl: fileRef,
    });`

I am able to get the result without any issues, from the result, how can I know the reply is in response to the post? Please see the screenshot below for your reference.
<img width="366" alt="Screenshot 2022-02-28 at 2 42 41 PM" src="https://user-images.githubusercontent.com/25079793/155956261-9d089b3b-bd76-4564-9e9d-6e14f595edc3.png">

Could you please share the details to get the in response post for the discussion?

**Comment by spvjebaraj** [comment]
Team,

Please provide the solution to my question.

**Comment by patrick-rodgers** [comment]
Google gives you [this](https://stackoverflow.com/questions/48319207/sharepoint-rest-api-to-get-discussion-list-questions-and-replies-separately).

```TypeScript
  const messages = await list.items.filter("ContentType eq 'Message'")();

  const discussions = await list.items.filter("ContentType eq 'Discussion'")();
```
messages will include a `ParentItemID` property.
