### ISSUE TITLE
type IFieldInfo have missing information

### ISSUE THREAD

**Issue by MudulOzan** [pnp/pnpjs#2134]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ ^2.11.0 ]

Please specify what version(s) of SharePoint you are targeting: [Sharepoint Online]

### Expected / Desired Behavior / Question
when we get fields using ``sp.web.lists.getByTitle('List').fields.getByTitle('FieldName').get()`` I expect to see result.Choices 
![image](https://user-images.githubusercontent.com/29442243/155995227-5ac6a4ad-31e8-4d73-b619-bb459c697a2b.png)

### Observed Behavior
However, it isn't included in the type, we have to declare any type to get Choices
https://github.com/pnp/pnpjs/blob/35160086408efb8dff590cb1050d29b01f581be7/packages/sp/fields/types.ts#L665-L697

Code is working as intended but the type is missing and typescript complains about it if we don't declare as any type

**Comment by patrick-rodgers** [comment]
Got this updated for v3 - you can always submit a pr for v2. Alternatively, instead of `any` you can patch this in your code and maintain types with:

```
sp.web.lists.getByTitle('List').fields.getByTitle('FieldName').get<IFiledInfo & { Choices: any }>()
```

**Comment by MudulOzan** [comment]
> Got this updated for v3 - you can always submit a pr for v2. Alternatively, instead of `any` you can patch this in your code and maintain types with:
> 
> ```
> sp.web.lists.getByTitle('List').fields.getByTitle('FieldName').get<IFiledInfo & { Choices: any }>()
> ```

Thanks but I don't know how to PR on github. Also I already checked v3 but currently our project is too big and it will cost too much to upgrade this soon. If you show me I can submit a PR. Thanks for your efforts and making our lives easier :)

**Comment by juliemturner** [comment]
@MudulOzan - To get assistance with contributing to the PnP I suggest you attend one of the [Sharing is Caring](https://pnp.github.io/sharing-is-caring/) sessions specifically for First Time Contributors. I see they don't have any dates/times posted at hte moment but I'm sure they will soon, and you can sign up for the newsletter to get notified.
