### ISSUE TITLE
TypeScript 4.x compabilitity with SPFx 1.12.1 and later versions

### ISSUE THREAD

**Issue by miguelisidoro** [pnp/pnpjs#2135]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

Hello,

At https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility, SPFx 1.12.1 says that supported TypeScript version is 3.7 and SPFx 1.13 and later is TypeScript 3.9.

At https://pnp.github.io/pnpjs/getting-started/, says that we must use TypeScript 4.x.

Is this information correct? And if yes, from which SPFx versions is TypeScript 4.x compatible?

Should Microsoft update the documentation?

And is really node v14 or later required?

Thanks
Miguel

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
