### ISSUE TITLE
ClientSidePage.setBannerImageFromExternalUrl with .img extension does not save image properly

### ISSUE THREAD

**Issue by c-eiser13** [pnp/pnpjs#2136]
**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.12.0     ]

Please specify what version(s) of SharePoint you are targeting: [     SPO    ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
The scenario here is we are creating a customized version of Repost page where a user can point to a news article on the web and it will pull the title, description and image using the /_api/SP.Publishing.EmbedService/EmbedData endpoint. So far, this issue has been unique to folks linking to MSN news articles where the URL of the external image is pointing to a file with .img file extension, which when shown as a preview in an img tag works properly.
![Image extension](https://user-images.githubusercontent.com/42096464/156386757-e76c2bad-eece-43a7-b7c4-401f54907329.png)

The issue happens when we call setBannerImageFromExternalUrl on this link, it creates the file in the site assets library, but with a .img file extension and is basically a broken link since it thinks it is a disc image file.
![image3](https://user-images.githubusercontent.com/42096464/156387073-0d8cfe31-d36f-42f5-a731-eeab9dafe9f2.png)
![image4](https://user-images.githubusercontent.com/42096464/156387084-cc63f7ae-2eef-43f5-97c6-f8ba61c949fc.png)

I tested this same news item in the OOB news link functionality and whatever the internal service is calling on the back end to store the image, it is storing it as a jpeg and it works correctly. I understand most of these page API's are reverse engineered and I am not at a place where I can upgrade to 3.x, but did look at the code and the setBannerImageFromExternalUrl looks to be identical to the 2.x code, but wanted to see if there was any way to get this to work.

### Observed Behavior
See above

### Steps to Reproduce
Try and call setBannerImageFromExternalUrl  against a URL coming from an image on any MSN news article where the URL points to a file with .img extension.

Thank you for your feedback!

**Comment by juliemturner** [comment]
Based on your inpsection of the OOB UI then I suspect they're doing some type of conversion. We don't provide that extensibility in this library, so you would have to figure out a way to do the conversion and then set the banner image.

**Comment by c-eiser13** [comment]
Thanks @juliemturner, seems to be isolated to one news service so we will work around it.
