### ISSUE TITLE
Comparison table

### ISSUE THREAD

**Issue by JaeEmAre67** [pnp/pnpjs#2137]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 6.14.13 ]

Please specify what version(s) of SharePoint you are targeting: [ Online ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*
Question: Our team uses both PowerShell PnP and PnPJS. Is there any kind of comparison table that indicates if I can do XXX in PowerShell PnP, the corresponding function in PnPJS is YYY? Our team is more well-versed in the PowerShell PnP.

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
No such table exists and that isn't something we would have time to develop in the near-medium term. Welcome community contribution of such a thing, of course.
