### ISSUE TITLE
Not able to update properties of client side text webpart to display collapsible sections

### ISSUE THREAD

**Issue by Praveen-S2** [pnp/pnpjs#2138]
We are trying to provision a collapsible section using text webpart programmatically through pnp js client side pages library. After provisioning the text webpart, we are unable to set its properties. Screenshot below
<img width="539" alt="error" src="https://user-images.githubusercontent.com/98511440/156580230-535e5628-e746-4e14-a5e2-1d432d3274d1.png">

Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- Bug
- 

### Version

Please specify what version of the library you are using: [    2.5.0     ]

Please specify what version(s) of SharePoint you are targeting: [      SharePoint Online   ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!

**Comment by juliemturner** [comment]
Please check out our advanced guidance on the pages api: https://pnp.github.io/pnpjs/concepts/adv-clientside-pages/

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
