### ISSUE TITLE
Unable to add "News" webpart programatically in modern page. 

### ISSUE THREAD

**Issue by pavan2920** [pnp/pnpjs#214]
Hi Team, 

I am trying to add the default News webpart in the modern page but unable to get the webpart. 

By debugging i got the default id for "News" webpart - "8c88f208-6c77-4bdb-86a0-0c47b4316588"

When i try to find this id in the available web parts using below code, i am unable to find the same. 
const partDefs = await mySP.web.getClientSideWebParts();

Could any one help me. 

Thanks & Regards, 
Pavan.

**Comment by koltyakov** [comment]
Hey @pavan2920, 

The simplest approach is:

* Create webpart manually
* Configure it with settings you need
* Switch to `?maintenancemode=true`
* Check parameters, tweak them for your case

![image](https://user-images.githubusercontent.com/7816483/44905613-48172a00-ad1b-11e8-9b37-b5cfc0f97992.png)

Then with PnPjs:

```typescript
import { sp, ClientSidePage, ClientSideWebpart, ClientSideText } from '@pnp/sp';

(async () => {

  // Create new page
  const page = await sp.web.addClientSidePage('News.aspx', 'Sample News Rollup Page');

  // Getting existing page
  // const webUri = `get from SPFx context or somehow`;
  // const pageFile = sp.web.getFileByServerRelativeUrl(`${webUri}/SitePages/News.aspx`);
  // const page = await ClientSidePage.fromFile(pageFile);

  page.sections = [];
  const section = page.addSection();

  // News webpart
  section.addControl(
    new ClientSideWebpart('News', null, {
      carouselSettings: {
        autoplay: false,
        autoplaySpeed: 5,
        dots: true,
        lazyLoad: true,
        metadata: true,
        swipe: true
      },
      showChrome: true,
      layoutId: 'FeaturedNews', // 'NewsHub',
      prefetchCount: 12,
      newsDataSourceProp: 2,
      dataProviderId: 'viewCounts',
      renderItemsSliderValue: 4
    }, '8c88f208-6c77-4bdb-86a0-0c47b4316588')
  );

  await page.save();

})()
  .then(_ => console.log('Done'))
  .catch(console.log);
```

Cheers!

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please _reopen_ if you need to continue the conversation. Thanks!

**Comment by pavan2920** [comment]
Hi @koltyakov, That's really great solution.
This helped me in tweak other webpart as well :)
