### ISSUE TITLE
V3 changes to user fields?

### ISSUE THREAD

**Issue by kjdahldev** [pnp/pnpjs#2142]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [#] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.02  ]

Please specify what version(s) of SharePoint you are targeting: [ SPO ]

### Expected / Desired Behavior / Question
https://pnp.github.io/pnpjs/sp/items/
User Fields
const i = await sp.web.lists.getByTitle("PeopleFields").items.add({
  Title: getGUID(),
  User1Id: 9, // allows a single user
  User2Id: {
    **results**: [16, 45] // allows multiple users
  }
});

### Observed Behavior
Above code does not work. Removing results seem to work though. Has this been changed? 
That is: {UserId: [16, 45] } is working.

**Comment by patrick-rodgers** [comment]
Yes, we switched to minimal metadata mode, will need to update this docs example.

**Comment by patrick-rodgers** [comment]
Got this updated in the docs, will go out in next release.
