### ISSUE TITLE
Add/Update External Data value to SharePoint List Item

### ISSUE THREAD

**Issue by necik11** [pnp/pnpjs#2143]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.0.2]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
I was trying to add an item with the "external data" (BCS) field.
```
await this._sp.web.lists.getByTitle("Test").items.add({
      Title: "Title " + getRandomInt(999),
      "Produkt": "Změna22",
      ProductIinfo_ID: "__bgc000630083000300",
      Produkt2: "HL Road Frame - Red, 58",
      ProductIinfo_ID0: "__bgc000730003006300",
  }).then(result => {
      console.log("result", result);
  }).catch(error => {
      console.log("error", error);
  });
```

The item is created correctly, but the hidden column 'ProductIinfo_ID' does not store the string value.

I tried saving via PnP.PowerShell and when calling:

```
$itemp["ProductIinfo_ID"] = "__bgc000630083000300"
$itemp.Update()
```

The hidden column fills up and everything works.

### Observed Behavior
To show a hidden column, I need to add .select ():
```
const item any = await this._sp.web.lists.getByTitle("Test").items.getById(16)();   
const itemWithSelect any = await this._sp.web.lists.getByTitle("Test").items.getById(16).select('*,ProductIinfo_ID')();
```
I also tried to go through the metadata:
/sites/BCSTest/_api/$metadata#SP.ListData.TestListItems/@Element

But I didn't find anything wrong here, the column is hidden, but it's a string, so I don't understand why the value isn't saved:
```
<EntityType Name="TestListItem" BaseType="SP.ListItem">
<Property Name="ID" Type="Edm.Int32"/>
<Property Name="ContentTypeId" Type="Edm.String"/>
<Property Name="Title" Type="Edm.String"/>
..
..
..
<Property Name="Produkt" Type="Edm.String"/>
<Property Name="ProductIinfo_ID" Type="Edm.String"/>
<Property Name="Produkt2" Type="Edm.String"/>
<Property Name="ProductIinfo_ID0" Type="Edm.String"/>
```

**Comment by juliemturner** [comment]
Have you tried an update to that field only?

**Comment by necik11** [comment]
**Tried and the value is not saved.** 

Code:
```
 await this._sp.web.lists.getByTitle("Test").items.getById(18).select('*,BdcIdentity').update({
            ProductIinfo_ID: "__bgc000630083000300",
  })
```
Check directly in SHP Online and via REST API:
/sites/BCSTest/_api/lists/getbytitle('Test')/items?$select=Id,Produkt,ProductIinfo_ID,Produkt2,ProductIinfo_ID0

Result:
`<d:Produkt>Změna33</d:Produkt><d:ProductIinfo_ID m:null="true" />`

**Comment by juliemturner** [comment]
@necik11 -- Just so there is no confusion, PnP PowerShell uses CSOM library not the REST API's so it's not an apples-to-apples comparison although I get that it should work in both. It's absolutely possible that there is a bug with the REST endpoint's ability to update a BCS field.  Unfortunately, I don't personally have access to an environment with a BCS connection to test it out quickly. 

If you update the value with PnP PowerShell or through the UI for that matter and then "get" the list item, I assume it has a value and that you're sure the internal name reference is the same?

**Comment by necik11** [comment]
I definitely don't confuse or compare anything. I'm just pointing out how it works properly in PnPPowerShell, and I'd expect it here anyway.

I created the BDC Model based on this service:
https://services.odata.org/V3/Northwind/Northwind.svc/
This is version3 that works for me, it seems that odataV4 are no longer supported ...
Just import the model in the administration (you need to add Set metadata store permission for the admin account or acc which will upload this bdc model file, although it should probably work correctly anyway, otherwise you will see an error on the row and column 0...)
![secure](https://docs.microsoft.com/en-us/sharepoint/sharepointonline/media/d78e7a3f-6199-4c5e-bbfd-dfa8d05c9826.png)

Then add an external data column in any list.
Last but not least, it is necessary to use the classic sharepoint and select an item in NewForm.

I use REST precisely to find out if I am using the correct internal name, see figure1 and figure2.

![picture1](https://i.ibb.co/hYw6Tfj/snip1.png)
![picture2](https://i.ibb.co/zf9Wn15/snip2.png) 

Figure 2 shows the correctly stored value, I can't reach that goal. 
I forgot to thank you for the quick response, thanks :)

**Comment by necik11** [comment]
Unfortunately, there was probably a misunderstanding. 

I don't know exactly how the "external data" field works in the background, but I do know that this record is stored in 2 columns. 1 column is a text value (This is the one that works for you and stores the text value) and the second column is a key-which looks something like this: __bgc000730003006300 (and this column is created in the background and is hidden-its created from bdcm model=xml which you import).

This is why I used this query:
items?$select=TextValue,HiddenKeyValue(this )
In your case something like this(you can see VIA powershell and item.FieldValues):
items?$select=External,Customers_ID.

I would add that the modern UI does not have support for it or does not work properly, but after switching to the classic sharepoint exper. - New Form / Edit Form everything works.

**Comment by bcameron1231** [comment]
Ah, yes I misunderstood what you were saying. My apologies. So this took some digging and I was not able to update the field using the standard /items() REST endpoint.

However, I was able to successfully update the value using the validateUpdateListItem endpoint. 

```
const update = await sp.web.lists.getByTitle("Price").items.getById(7).select('*,External').validateUpdateListItem([
      {FieldName:"External",FieldValue:"Fauntleroy Circus"},
      {FieldName:"Customers_ID", FieldValue:"__bk410024003500240054006500"}
    ]); 
```

Could you give this a try and let me know if it works for you?

**Comment by necik11** [comment]
Although I have to create the item first and then update it, so it's not in one step, but otherwise it's exactly what I wanted to thank you so much!

**Comment by juliemturner** [comment]
I'm reopening this issue because this is clearly a gap in our [documentation of list item updating](https://pnp.github.io/pnpjs/sp/items/).  Want to keep it in the backlog for things that should get addressed but it'd be great if someone wants to tackle a PR.

**Comment by patrick-rodgers** [comment]
I am updating the docs.
