### ISSUE TITLE
`SPFI#web` field is undefined without side-effect import of `@pnp/sp/webs`

### ISSUE THREAD

**Issue by thw0rted** [pnp/pnpjs#2145]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: **3.0.3**

Please specify what version(s) of SharePoint you are targeting: **2016 on-prem**

### Expected / Desired Behavior / Question
I'm trying to follow the [transition guide](https://pnp.github.io/pnpjs/transition-guide/#web-spfi).  My previous code looked like `Web(url).configure({headers, credentials, mode})`, which I'm replacing with `spfi(url).using(DefaultHeaders(), InjectHeaders(headers))`.

### Observed Behavior
If you `import {spfi} from "@pnp/sp"`, the return value from `spfi(url)` appears to have an always-defined `web` property, but this value is undefined at runtime.  Eventually, I found some examples on the [pnp/sp/webs](https://pnp.github.io/pnpjs/sp/webs/) documentation that show a side-effect `import "@pnp/sp/webs";`, which fixes the problem.

### Steps to Reproduce
````ts
import {spfi} from "@pnp/sp";

console.log(spfi("some/url").web); // undefined
````

### Desired outcome
The `web` property should be added using module augmentation in the `pnp/sp/webs` declaration, as with other fields, so that if I don't have a side-effect import statement, the typechecker will tell me that SPFI does not have a "web" property, as happens with various other dynamically-augmented interfaces.

Also, ideally, the transition doc examples should be updated to include minimum required `import` statements.

**Comment by patrick-rodgers** [comment]
We've seen at times in various IDEs they will pick up things even if not imported. Not much we can do about that from within this library.

Can you expand on this: "Also, ideally, the transition doc examples should be updated to include minimum required import statements."? What sections specifically need adjustment/expansion?

**Comment by thw0rted** [comment]
I'll try to track down the "non-imported import" thing.  Yours is the only project I use that does side-effect import module augmentation.  (I think a few major versions ago, RxJS refactored to avoid doing this, because it caused them a lot of problems...)

Re: docs, I was referring to the transition section I linked to -- there's an example of using `spfi` instead of `Web` but there are no import statements in the example.

**Comment by patrick-rodgers** [comment]
Updated the transitions guide to have the imports, going to close this as resolved. If you discover a reason in our code that is affecting the IDE intellisense happy to update it. Thanks!

**Comment by thw0rted** [comment]
Hi @patrick-rodgers , per [the linked issue](https://github.com/microsoft/TypeScript/issues/48222), the TS team "declines to treat files differently based on how they were included", meaning that this bug will always occur when interfaces are exported from the file that causes side-effect augmentation.  Their guidance is:

> the upstream library should not mix types with augmentations if those augmentations need to be conditionalizable

i.e., it would be better if the interface export came from somewhere other than `@pnp/sp/webs`.  Perhaps all interfaces could come from `@pnp/sp`?  I don't expect you to go back in and make yet more breaking changes after your big rewrite, but maybe something for the 4.x roadmap?  In the meantime, maybe there's an appropriate place to document this behavior?  (At least this issue should turn up in search resutls....)

**Comment by patrick-rodgers** [comment]
I don't think anyone is "wrong" other than you encountered something unexpected. Type only imports are indeed removed at transpile time, that is how TS behaves. I disagree that placing all of the interfaces in the root is the right solution. We show this in the selective imports article, but don't call it out. We will add something there to explicitly call it out.
