### ISSUE TITLE
Cannot successfully authenticate (401) using client credentials.

### ISSUE THREAD

**Issue by barkdoll** [pnp/pnpjs#2148]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.0.2 ]

Please specify what version(s) of SharePoint you are targeting: [ SPO ]

### Expected / Desired Behavior / Question
Expecting to authenticate to SharePoint using client credentials— client ID and client secret. My client is shown as invalid. 

- Have I incorrectly configured the client for making requests within PnpJS? 
- If so, how can I properly configure the client id and secret to authenticate successfully and handle SPO data?

### Observed Behavior
Instead of a success response, I receive a `401 Unauthorized` response back from the API.

### Steps to Reproduce

- Using the [nodejs-commonjs sample](https://github.com/pnp/pnpjs/tree/version-3/samples/nodejs-commonjs) with ESM, I have successfully dynamic imported the PnpJS modules.

```ts
export const settings = {
    testing: {
        sp: {
            url: "https://{tenant}.sharepoint.com/sites/{site-name}",
            msal: {
                init: {
                    auth: {
                        authority: "https://login.microsoftonline.com/{tenant-id}",
                        clientId: "{client-id}",
                        clientSecret: "{client-secret}",
                    },
                },
                scopes: ["https://{tenant}.sharepoint.com/.default"],
            },
        },
    },
};
```
```ts
import { settings } from "./settings.js";

// this is a simple example as async await is not supported with commonjs output
// at the root.
setTimeout(async () => {

    const { spfi } = await import("@pnp/sp");
    const { SPDefault } = await import("@pnp/nodejs");
    await import("@pnp/sp/webs");
    
    const sp = spfi(settings.testing.sp.url).using(SPDefault({
        msal: {
            config: settings.testing.sp.msal.init,
            scopes: settings.testing.sp.msal.scopes
        }
    }));

    const w = await sp.web.select("Title", "Description")();
    console.log(JSON.stringify(w, null, 4));
}, 0);
```

- Executing the code gave me the following response— logged inside of the error parser,
`@pnp/packages/queryable/behaviors/parsers.js` in the `HttpRequestError.init()` method.
```js
{
  size: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      // ...
    },
    stream: PassThrough {
      // ...
    },
    boundary: null,
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    type: 'default',
    url: 'https://{tenant}.sharepoint.com/sites/{site-name}/_api/web?$select=Title,Description',
    status: 401,
    statusText: 'Unauthorized',
    headers: {
      'cache-control': 'private',
      connection: 'close',
      'content-length': '74',
      'content-security-policy': "frame-ancestors 'self' teams.microsoft.com *.teams.microsoft.com *.skype.com *.teams.microsoft.us local.teams.office.com *.powerapps.com *.yammer.com *.officeapps.live.com *.office.com *.stream.azure-test.net *.microsoftstream.com *.dynamics.com;",
      date: 'Thu, 10 Mar 2022 15:08:20 GMT',
      microsoftsharepointteamservices: '16.0.0.22223',
      'ms-cv': 'oChoyCJAABB4S6R9lHzbrw.0',
      p3p: 'CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"',
      'request-id': 'c86828a0-4022-1000-784b-a47d947cdbaf',
      server: 'Microsoft-IIS/10.0',
      spiislatency: '0',
      sprequestduration: '31',
      sprequestguid: 'c86828a0-4022-1000-784b-a47d947cdbaf',
      'strict-transport-security': 'max-age=31536000',
      'www-authenticate': 'Bearer realm="{tenant-id}",client_id="00000003-0000-0ff1-ce00-000000000000",trusted_issuers="00000001-0000-0000-c000-000000000000@*,D3776938-3DBA-481F-A652-4BEDFCAB7CD8@*,https://sts.windows.net/*/,00000003-0000-0ff1-ce00-000000000000@90140122-8516-11e1-8eff-49304924019b",authorization_uri="https://login.windows.net/common/oauth2/authorize"',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-ms-diagnostics': '3001000;reason="There has been an error authenticating the request.";category="invalid_client"',
      'x-ms-invokeapp': '1; RequireReadOnly',
      'x-powered-by': 'ASP.NET'
    },
    counter: 0,
    highWaterMark: 16384
  }
}
```

I looked at this to research on the issue further, mainly noting the `www-authenticate` and the `x-ms-diagnostics` property values.

**Comment by patrick-rodgers** [comment]
I've not tried it with client secret - we've transitioned to certs, which we [outlined here](https://pnp.github.io/pnpjs/v2/authentication/server-nodejs/#call-sharepoint) and forgot to move to the v3 docs. That's our bad and we'll get that fixed up. I believe you are required to use certs now to call SP APIs via MSAL.

**Comment by barkdoll** [comment]
I see. Thank you for clarifying. I will see if I can get transitioned to certificates instead. I do believe others would benefit as well from it in the docs too.

**Comment by patrick-rodgers** [comment]
Yep, now in the [getting started guide](https://pnp.github.io/pnpjs/getting-started/#getting-started-with-nodejs) for v3. Sorry about missing including that. Going to close this, but please report if you continue to have issues. Thanks!
