### ISSUE TITLE
Errors importing using v3 (ESM) inside of Node (CommonJS) project

### ISSUE THREAD

**Issue by barkdoll** [pnp/pnpjs#2154]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.0.3 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

### Expected / Desired Behavior / Question
I would like to properly import the PnpJS ESM packages into a CommonJS (Node) project. I have been referencing [the docs](https://pnp.github.io/pnpjs/getting-started/#node-project-using-typescript-producing-commonjs-modules) in order to get this far.

### Observed Behavior

Here is some example [nearly identical] logic to demonstrate how I am attempting to import ESM PnpJS packages:
```ts
class MySharePointHandler {

  config = { 
    siteUrl: 'https://{tenant}.sharepoint.com/',
    auth: /* auth config */,
  }
    
  async pnpInstance() {
    const {SPDefault} = await import('@pnp/nodejs/index.js');
    const {spfi} = await import('@pnp/sp/index.js');
    await import('@pnp/sp/webs/index.js');

    const instance = spfi(this.config.siteUrl).using(SPDefault({
      msal: {
        config: this.config.auth,
        scopes: ["https://{tenant}.sharepoint.com/.default"]
      },
    }));
    return {
      instance
    };
  }
}

const spHandler = new MySharePointHandler();
const instance = await spHandler.pnpInstance();
```

The following is the error output.
```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/path/to/node_modules/@pnp/sp/files' is not supported 
resolving ES modules imported from /path/to/node_modules/@pnp/nodejs/sp-extensions/stream.js

Did you mean to import @pnp/sp/files/index.js?
    at DocumentLibraryRepository.create (/path/to/document-library.repository.js:43:19)
    ...
```

The issue is that even though I can use dynamic imports inside of async code blocks to get them with the current TypeScript configuration, the internal PnpJS module resolutions seem to be failing. 

I am assuming this to be the case because the code never attempts to import `@pnp/sp/files`, nor does it make any calls for `@pnp/nodejs/sp-extensions/stream.js`.

Here are some relevant properties set in our TS config file. Please let me know if specifying more of them will be helpful to understanding the issue.

#### package.json (partial)
```json
{
  "devDependencies": {
    "typescript": "^4.7.0-dev.20220308"
  }
}
```
#### tsconfig.json
```js
{
  "module": "commonjs",
  "moduleResolution": "node12",
  "target": "es2017",
  "esModuleInterop": true,
  // ...
}
```

**Comment by juliemturner** [comment]
At its root, this is a duplicate issue of #2141 but I'm going to leave it open as it has different information.

**Comment by barkdoll** [comment]
I seem to have forgotten to pass in the `--experimental-specifier-resolution=node` flag. Not noticing it after passing this in, but it may still be an issue if the flag is not a catch all for these kind of imports.

**Comment by patrick-rodgers** [comment]
@barkdoll - we are evaluating things around modules. Anticipated that the transition to esm would be easier, but this is the largest friction point so far with v3 release. Might go back to releasing commonjs, or revisit bundling it together. Previously this didn't work, but haven't investigated since node firmed up esm support. Anyway, sorry for the troubles here, we're working on it.

**Comment by juliemturner** [comment]
We add milestones for each month so there is no correlation between the timeline for answers to issues and the addition of a milestone.

This is a fairly big issue and as @patrick-rodgers mentioned above one that will take us time to resolve a good outcome for. So, that said, we do not have an answer at this time and I can't give you a timeline when we will have one as working on this project is something we do in our spare time, not a full-time job.

**Comment by barkdoll** [comment]
@juliemturner I understand. Thanks for that.

**Comment by patrick-rodgers** [comment]
Please see the [latest update](https://github.com/pnp/pnpjs/issues/2141#issuecomment-1076562879) in the first issue, going to close this one as a duplicate so we can focus on updating a single conversation. Thanks!
