### ISSUE TITLE
Expand multiselect  person field should bring back an array of items line version 2 did

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#2155]
### Category
- [ ] Enhancement
- [? ] Bug
- [ ?] Question
- [ ?] Documentation gap/issue

### Version using: [   3.0.3    ]
Please specify what version(s) of SharePoint you are targeting: [  SPO ]

### Expected / Desired Behavior / Question
Expand multiselect  person field should bring back an array of items
In version 2.X 
code such as :
```
 const items = await dpcWeb.lists.getByTitle("DPC-Job-Other-Data").items
            .expand('AdditionalRecipients').filter(filter)
            .select('SendCompletedFiles,AdditionalRecipients/Title,AdditionalRecipients/EMail,AdditionalRecipients/Id,')
            .top(1).get();
```
Returned a AdditionalRecipients array with 0 to n items each with Id, Title and EMail.
### Observed Behavior
in version 3.0.3
same code without the .get() just () and following the example [here](https://pnp.github.io/pnpjs/sp/items/#retrieving-lookup-fields)
doesn't return the array but instead has a link that may bring the info
```
AdditionalRecipients@odata.navigationLinkUrl:'Web/Lists(guid'8bed4fa8-6484-4817-b030-d27fc1d905c1')/Items(593)/AdditionalRecipients'
```
### Steps to Reproduce
Just use similar code to get multiselect person field from any list
Should I use the link to retrieve the values or there is another syntax to do it? 
Will there be another version that will do the same?

Thank you

**Comment by aaademosu** [comment]
Unable to reproduce this. Using the same snippet, the multiselect person field gets expanded. I ran this test with v3.1.0, you could try that. 

```js
    const sp = spfi("https://xxx.sharepoint.com/sites/dev").using(SPFx(this.content));

    const item = await sp.web.lists.getByTitle("SelfStudy").items
    .expand('Approver, testpeople').filter("filtered")
    .select('Id,Title,Approver/Title,Approver/EMail,Approver/Id,testpeople/Title,testpeople/EMail,testpeople/Id')
    .top(1)();

    console.log(JSON.stringify(item, null, 2));
```

![image](https://user-images.githubusercontent.com/2017630/158013349-56b36342-c92b-43b8-ac29-dcc96d8899b9.png)

**Comment by Ofer-Gal** [comment]
Thank you much. Works fine now
It was either my mistake or version 3.1.0.
