### ISSUE TITLE
SP.Utilities sendEmail Error - An unexpected 'StartObject' node was found when reading from the JSON reader. 

### ISSUE THREAD

**Issue by kofrimpong** [pnp/pnpjs#2162]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.1.0]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint online]

### Expected / Desired Behavior / Question
Should be able to send email without error.

### Observed Behavior
Receiving error: `{"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'StartArray' node was expected."}}}`

### Steps to Reproduce
```typescript
import { spfi, SPFx } from "@pnp/sp";
import "@pnp/sp/sputilities";
import { IEmailProperties } from "@pnp/sp/sputilities";

const sp = spfi("{tenant url}").using(SPFx(this.context));

const emailProps: IEmailProperties = {
    To: ["user@site.com"],
    CC: ["user2@site.com", "user3@site.com"],
    BCC: ["user4@site.com", "user5@site.com"],
    Subject: "This email is about...",
    Body: "Here is the body. <b>It supports html</b>",
    AdditionalHeaders: {
        "content-type": "text/html"
    }
};

await sp.utility.sendEmail(emailProps)
```

**Comment by juliemturner** [comment]
Duplication #2156
