### ISSUE TITLE
V3 - Batching against different sources at the same time. No longer possible or insufficient documentation

### ISSUE THREAD

**Issue by Vertamin** [pnp/pnpjs#2164]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    3.1     ]
Please specify what version(s) of SharePoint you are targeting: [    SharePoint Online     ]

### Expected Behavior

I'm no longer available to query multiple lists on the same Batch.

The new Batching mechanic requires initializing in base of something. 

Before I could do:

var Batch = this.sp.createBatch();

var ItemsList1 =this.web.lists.getByTitle("LIST1")
.items
**.inBatch(Batch)**
.get()

var ItemsList2 = this.web.lists.getByTitle("LIST2")
.items
**.inBatch(Batch)**
.get()

**await Batch.execute()**

console.log(ItemsList1,ItemsList)
**//Data loaded, you can see on network that it gets batched on the same query**

### Observed Behavior

Since you have to initialize the type on the Batch, you can no longer pass the same Batch to different sources.

const list: IList = sp.web.lists.getByTitle("LIST1");
const [batchedListBehavior1, execute1] = createBatch(list1);
list
**.using(batchedListBehavior1);**

const list: IList = sp.web.lists.getByTitle("LIST2");
const [batchedListBehavior2, execute2] = createBatch(list2);
list
**.using(batchedListBehavior2);**

**await execute1();
await execute2();**

## Comments

If there is a way to do this, I am not able to find it on the documentation https://pnp.github.io/pnpjs/concepts/batching/
And I'm not able to find it by looking through the typescript definitions.

Thank you!

**Comment by juliemturner** [comment]
Is there a reason this won't work for you?

```ts
const [batchedWeb, execute] = sp.web.batched();
batchedWeb.lists.select("List1")().then(r => res.push(r));
batchedWeb.lists.select("List2")().then(r => res.push(r));
await execute();
```

**Comment by Vertamin** [comment]
Thank you! I guess I can start from there.

I lost some flexibility from before, since I could choose when or when not to batch and Api Query:

Example:

```ts
var ItemsList1 =this.web.lists.getByTitle("LIST1")


var Batch = this.sp.createBatch();

var Items 1 = await ItemsList1 
.items
.get()

var ItemsList1SecondQuery = ItemsList1 
.items
.inBatch(Batch)
.get()

await Batch.execute()


```

As you can see, before I could have the same object list stored on a variable and choose when to batch or do a normal query. Now I have to either re-initialize the list variable or keep 2 different variables depending on if i need to batch it or not.

¿What utility did this have for me?

Well, I did have a List "Class" with a .GetItems(Batch?) function. I could decide to send the "Batch" variable . The same function would give me the same response but would either give me immediate results or would stay in a Promise state until the Batch was resolved:

This is a simpified version of that class:



```ts
import CustomItem from "./CustomItem";

export class CustomList {
    public ListName = "";
    public SelectAllFields: string[] = ["*"];
    public ExpandAllFields: string[] = [];
    public web: IWeb;
    public Context: WebPartContext;
    public List: IList;

    constructor(
        web: IWeb,
        context: WebPartContext,
        ListName: string,
        SelectAllFields: string[],
        ExpandAllFields: string[],
    ) {
        if (ListName == null)
            throw new Error("List name cannot be empty");
        this.web = web;
        this.Context = context;
        this.ListName = ListName;
        this.List = this.web.lists.getByTitle(this.ListName);
        this.SelectAllFields = SelectAllFields;
        this.ExpandAllFields = ExpandAllFields;
    }

    public async LoadByID(
        ID: number,
        Batch?: SPBatch
    ): Promise<CustomItem> {
        if (ID == null || isNaN(ID)) throw "Its not a valid ID";

        var Item: Promise<IItem> = this.List.items
            .inBatch(Batch)
            .filter(`ID eq ${ID}`)
            .expand(this.ExpandAllFields.join())
            .select(this.SelectAllFields.join())
            .get()
            .then((Data: IItem[]) => {
                if (Data.length == 0) return null;
                else return Data[0];
            });

        if (Item == null)
            throw new Error(
                `Cannot find the element with ID ${ID} on the list ${this.ListName}`
            );

        return new CustomItem(await Item, this);
    }


}
```

As you can see on my "LoadByID" function. If "Batch" is null, pnpjs would solve it straight away, but if i did pass a Batch. It would stay on a "Promise" state until it resolved and give me the same value.

This did have a lot of flexibility on my code and classes, since I could re-use the same functions easily depending on my needs.

I'll have to adapt to the new system and see how I can make something similar.

Thanks for giving me a solution!

**Comment by patrick-rodgers** [comment]
Hi @Vertamin - that is an interesting usage of the batching from v2. It was never intended to be used like that with an optional batch, but certainly would work. This wasn't a use case we considered in our v3 design.

I think you could accomplish the same thing by passing the "register" behavior as an optional object. How to work with these more directly is covered under [advanced batching](https://pnp.github.io/pnpjs/concepts/batching/#advanced-batching), which this would fall under. Please give that a try.

For now will close this as answered, please open a new issue if you encounter other issues. Thanks!
