### ISSUE TITLE
how can i do display sharepoint home page content within my site page

### ISSUE THREAD

**Issue by neozhu** [pnp/pnpjs#2166]
step1: https://{{targetHost}}/sites/10000916/_api/web/lists/GetByTitle('Site Pages')/items(1)  with rest api I get home page object.
<img width="1604" alt="image" src="https://user-images.githubusercontent.com/1549611/159102753-b6742d1c-9cdd-4dfe-995d-5ee8e61c452f.png">
I think that's what I want in this property ConvasContent1, right?
now how should do display this content in HTML correctly.

please give me hand.

**Comment by juliemturner** [comment]
Given the way you've asked your question I'm not exactly sure you realize whom you're asking as you're not asking a question about this library.  That said, I will tell you that there is no third party, Microsoft supported APIs for modern pages.  

That said, this library has reverse engineered the first party APIs to provide as best a solution as we can, but it comes with the caveat that the api could break at any time and that there is no implied SLA for us to be able to fix it as we are volunteers only.

So, if all of that works for you then here's a link to our [Client-Site Pages](https://pnp.github.io/pnpjs/sp/clientside-pages/) support as well as an [advanced article](https://pnp.github.io/pnpjs/concepts/adv-clientside-pages/) on working with web parts on modern SharePoint pages.

**Comment by patrick-rodgers** [comment]
Agree with @juliemturner - have a look at the client side page docs as a starting point.

Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
