### ISSUE TITLE
Add multiple attachments batched

### ISSUE THREAD

**Issue by kkazala** [pnp/pnpjs#2167]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.1.0

Please specify what version(s) of SharePoint you are targeting: SPO, SPFx 1.14

### Expected / Desired Behavior / Question
I want to bulk copy items with attachments. 
Since there's no `attachmentFiles.addMultiple` any more, I'm using [this approach](https://pnp.github.io/pnpjs/v2/sp/attachments/#add-multiple). 

In my code, I first copy all the items. The batch returns an object with the following info: sourceItemID (for reporting), sourceItemAttachments and the batch result which I will use to add attachment to the newly created item:
```
const sp: any = spfi().using(SPFx(context));
const targetList: IList = sp.web.lists.getByTitle(listTitle);
//Use baching to copy items
const [batchedListBehavior, execute] = createBatch(targetList);
targetList.using(batchedListBehavior);

let batchCopyResult: ICopyItemResult[] = [];
// copy items without attachments
sourceSPItems.forEach(sourceItem => {
    targetList.items.add(sourceItem.item)
        .then(itemAddResult => {
            let res2: ICopyItemResult = { sourceItem: sourceItem.item["Title"], sourceItemID: 1, itemAddRes: itemAddResult, attachmentInfo: sourceItem.attachmentInfo };
            batchCopyResult.push(res2);
        })
        .catch(err => {
            let res2: ICopyItemResult = { sourceItem: sourceItem["Title"], sourceItemID: 1, itemAddErr: err  };
            batchCopyResult.push(res2);
        });
});
await execute();

```

Add the attachments:
```
let batchCopyAttResult: ICopyAttachmentResult[] = [];
for (let i = 0; i < batchCopyResult.length; i++) {
    if (batchCopyResult[i].attachmentInfo) {
        const newItem = batchCopyResult[i].itemAddRes.item;
        const [batchedSP, executeBatchedAtt] = sp.batched();

        batchCopyResult[i].attachmentInfo.forEach(attInfo => {
            newItem.attachmentFiles.add(attInfo.fileName, attInfo.content)
                .then(attAddResult => {
                  let res2att: ICopyAttachmentResult = { sourceItem: batchCopyResult[i].sourceItem, sourceItemID: batchCopyResult[i].sourceItemID, sourceAttachment: attInfo.fileName, attAddRes: attAddResult };
                  batchCopyAttResult.push(res2att);
            })
                .catch(err => {
                  let res2att: ICopyAttachmentResult = { sourceItem: batchCopyResult[i].sourceItem, sourceItemID: batchCopyResult[i].sourceItemID, sourceAttachment: attInfo.fileName, attAddErr: err }
                  batchCopyAttResult.push(res2att);
             });
       });
       await executeBatchedAtt();
  }
```

### Observed Behavior
Most of the times the above code completes without any problem, but every few times I get an error when copying the attachments: 
`Error: Error making HttpClient request in queryable [409]  ::> {"odata.error":{"code":"-2130575305, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"Save Conflict[.\n\nYour]() changes conflict with those made concurrently by another user. If you want your changes to be applied, click Back in your Web browser, refresh the page, and resubmit your changes."}}}`

The same happens if a **target already existing item.** 

### Steps to Reproduce

First, retrieve attachment information from already existing item:
```
  private async getAttachments(listName:string,  sourceItem:any, context: any ): Promise<ISpAttachmentInfo[]> {

    const fNames = sourceItem["AttachmentFiles"].map((f: IAttachmentInfo) => { return f.FileName; });
    ///get item to access attachmentFiles()
    const sp = spfi().using(SPFx(context));
    const item: IItem = sp.web.lists.getByTitle(listName).items.getById(**383**);

    const results: { fileName: string, content:any }[] = await Promise.all(fNames.map(async (name) => {
      const result = await item.attachmentFiles.getByName(name).getBuffer();
      return { fileName: name, content: result };
    }));
    return results;
  }

```
I'm testing with three documents:
DOCX: 445KB
XLSX: 521KB
PPTX: 66KB

Then, execute the above code to add attachments. To simplify, use existing item without attachments, and replace `const newItem = batchCopyResult[i].itemAddRes.item;` with `const newItem  = await sp.web.lists.getByTitle(listTitle).items.getById(**XXX**);`

**Comment by juliemturner** [comment]
@kkazala -- So this is an issue with the fact that you're using batching.  When we looked into the issue we realized that the documentation was out of date and incorrect. I've removed the reference to using batching for multiple attachments and added a tag in the documentation for all the methods that do not support batching. The doc will reflect this when we release 3.2.
