### ISSUE TITLE
getWebUrlFromPageUrl on subsite does not return site collection URL , but rather subsite URL 

### ISSUE THREAD

**Issue by BitmapBrothers** [pnp/pnpjs#2170]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [ x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   pnpjs.es5.umd.bundle.js  v1.3.9  ]

Please specify what version(s) of SharePoint you are targeting: [ 365 ]

### Expected / Desired Behavior / Question
Return site collection URL as per documentation (https://pnp.github.io/pnpjs/sp/sites/#get-site-collection-url-from-page)

### Observed Behavior
Returns subsite URL

### Steps to Reproduce
```
var d  = await pnp.sp.site.getWebUrlFromPageUrl("https://my.sharepoint.com/sites/sc/ss/SitePages/test.aspx");
console.log(d);  //returns https://my.sharepoint.com/sites/sc/ss not https://my.sharepoint.com/sites/sc
```

**Comment by tavikukko** [comment]
I think it works as expected, it returns the **web object** where the **page lives.**

**Comment by BitmapBrothers** [comment]
Web URL yes, but the documentation says that it returns the site collection URL, which it doesn't.

**Comment by tavikukko** [comment]
Yes, the documentation is **incorrect**, that endpoint returns the **web url**.

**Comment by patrick-rodgers** [comment]
Sure, updated the docs to say web url.
