### ISSUE TITLE
Batching does not work when connecting to a different site collection

### ISSUE THREAD

**Issue by russgove** [pnp/pnpjs#2172]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.1.0         ]

Please specify what version(s) of SharePoint you are targeting: [ online        ]

### Expected / Desired Behavior / Question
When I connect to another site collection I should be able to use batching

### Observed Behavior
When I connect to a different site collection batching fails with an 'Invalid Request' error.
### Steps to Reproduce
repro is at https://github.com/russgove/testbatch
If you run webpart in the workbench and pass in a query parameter of '?site=tenant.sharepoint.com/sites/someothersite'
the app connects to tenant.sharepoint.com/sites/someothersite but the calls made via the batch fail with  'Invalid Request'
### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
Hi @russgove - tested this out. Can you confirm that when you supply the `site` query param it is absolute including the "https://" at the front? I can duplicate your issue if it is not there, but things seem to work as expected otherwise.

**Comment by russgove** [comment]
Hi,
Yes, i am passing the full url to the other site collection, including the
https://

The non-batched call works fin, but not the batched one.

Are you runnin from my sample repro?

**Comment by russgove** [comment]
here is the url that fails
https://tenant.sharepoint.com/sites/KZNEDMSSCM20220302-D/Inve/_layouts/15/workbench.aspx?site=https://tenant.sharepoint.com/sites/trondocs

Would like to install a webpart once and be able to use it across all sites,

**Comment by patrick-rodgers** [comment]
Running your code I am not able to duplicate the issue. If I supply a valid absolute site url such as "site=https://tenant.sharepoint.com" everything works as expected.

If I supply an invalid domain, such as "site=tenant.sharepoint.com" I get errors.

If you can provide steps to reproduce this we can have another look - but based on everything in this thread there is no issue currently.

**Comment by russgove** [comment]
Yes , it works for me too if i put in site=https://tenant.sharepoint.com.

But if i put in  site=https://tenant.sharepoint.com/sites/someothersite

thats when it fails

**Comment by russgove** [comment]
issue does not happen if I install the app in an app catalog. Only on the workbench of my production envirnonment.
