### ISSUE TITLE
Issue with sp-news reel webpart when add it in to page

### ISSUE THREAD

**Issue by VinodhNarayanan** [pnp/pnpjs#218]
### Category
- [x] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: ["@pnp/pnpjs": "^1.1.5-4   ]

Am add spfx components to page programmatically only news reel webpart throws error

My code:

```typescript
let wapify = new Web("https://sharepointtechie.sharepoint.com/sites/" + title + "");

const pageHome = await ClientSidePage.fromFile(wapify.getFileByServerRelativeUrl("/sites/" + title + "/SitePages/Home.aspx"));

const homepartDefs = await pnp.sp.web.getClientSideWebParts();
console.log(homepartDefs);
const partDef = homepartDefs.filter(c => c.Name === "a5df8fdf-b508-4b66-98a6-d83bc2597f63");
console.log(partDef);
// const partDef = homepartDefs.filter(c => c.Name === "a5df8fdf-b508-4b66-98a6-d83bc2597f63");
if (partDef.length < 1) {
  // we didn't find it so we throw an error
  throw new Error("Could not find the web part");
}
const homeparty = ClientSideWebpart.fromComponentDef(partDef[0]);
// const Homesection = pageHome.addSection();
//const Homecolumn = Homesection.addColumn(4);
const homesection = pageHome.addSection();
homesection.addColumn(4).addControl(homeparty);
await pageHome.save();
```

![image](https://user-images.githubusercontent.com/38123307/44979112-dd1f5a80-af89-11e8-9622-0b95150e8587.png)

For other webparts working fine only issues with news reel webpart and news list webpart

**Comment by koltyakov** [comment]
Changed the original text for readability purposes.

**Comment by koltyakov** [comment]
@VinodhNarayanan, so you need to provision News WebPart but not to recreate a copy of webpart from page A to page B?

In this case, you can use [this](https://github.com/pnp/pnpjs/issues/214#issuecomment-417612376) example, how to add news webpart from the question which was recently asked.

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please _reopen_ if you need to continue the conversation. Thanks!
