### ISSUE TITLE
Without using User IDs, How to Insert multiple users or groups in a user field of a SharePoint Online list using Email IDs only

### ISSUE THREAD

**Issue by Naveen-Rangarajan** [pnp/pnpjs#2181]
### Category
[ ] Question

### Version

Please specify what version of the library you are using: [   pnp/sp 2.0.5  ]

Please specify what version(s) of SharePoint you are targeting: [   Online   ]

Question

I have some 5000+ items in an object where one of the property is an Email which has the data as described below

"Email":"FirstName1.LastName1@Tenant.com|FirstName1.LastName1;FirstName2.LastName2@Tenant.com|FirstName2.LastName2;FirstName3.LastName3@Tenant.com|FirstName3.LastName3;FirstName4.LastName4@Tenant.com|FirstName4.LastName4;............................................................;FirstName10.LastName10@Tenant.com|FirstName10.LastName10;........................................;FirstName15.LastName15@Tenant.com|FirstName15.LastName15;..............."

In the documentation, it is stated that we need to pass an array of user ids or group ids. 
User2Id: {
        results: [ 16, 45 ] // allows multiple users
}

So, for each of the 5000+ items, I need to loop through Email Property to retrieve User IDs of ~10-15 Users. As an alternative, is it feasible to pass Email IDs separated by comma in the array instead of User ID Array? 

If not, please suggest an alternative on how to achieve this.

Thank you for your help and support!

**Comment by Naveen-Rangarajan** [comment]
Any updates on this request?

**Comment by juliemturner** [comment]
I would suggest that you make batch calls to get the user objects from the web for the users you want to add so that you have an in memory map of the users by email and their corresponding id's for the web, then do batch updates with the ids.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
