### ISSUE TITLE
Get Tenant Property gives stale value

### ISSUE THREAD

**Issue by JarialAnkur** [pnp/pnpjs#2190]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category

- [ ] Bug

### Version

Please specify what version of the library you are using: 3.0.2

Please specify what version(s) of SharePoint you are targeting: 1.12.1

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I am using "setStorageEntity" function to set the value to a tenant property. and using "getStorageEntity" to retrieve the value of that tenant property. If I update the value of Tenant Property, then I should get the updated value of the tenant property when I am retrieving it using "getStorageEntity" function.

### Observed Behavior
But what is actually happening is, once I start updating the Tenant Property value and then I retrieve the value of that Tenant Property, some time I get old values. I am getting inconsistent result.
### Steps to Reproduce
Write the code to set stporage entity, and then use the same function to update the value of Tenant Property with new Value. Use the 'getStorageEntity" function and put it calling on a clickable button. and start clicking that button continuosly and console log the result that you get from "getStorageEntity" function. You will see that you are not getting consistent result. instead some time you get correct result and sometimes you get wrong result

import * as React from 'react';
import { spfi, SPFx } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/appcatalog";
const Test=(props)=>{
    const sp = spfi(`${props.context.pageContext.web.absoluteUrl}`).using(SPFx(props.context));
    const CreateTenantProperty = async (PropertyValue) => {
        const w = await sp.getTenantAppCatalogWeb();
        await w.setStorageEntity("TenantProperty_Contoso", PropertyValue).then((res) => {
        })
    }
    const GetTenantProp=async(TenantPropName:string)=>{
        await sp.web.getStorageEntity(TenantPropName).then((res)=>{
          console.log("got this from Get function for TenantProperty_Contoso =>", res);
          settenantpropertyValue(res.Value);
        });
      }
      
const [input1,setinput1]=React.useState("");
const [tenantpropertyValue,settenantpropertyValue]=React.useState("");

return(
    <>
    <h4>Value of tenant property</h4><input type="text" onChange={(e)=> setinput1(e.target.value)} />
    <button onClick={()=>GetTenantProp("TenantProperty_Contoso")}>Click to retrieve the tenant property Value in console</button>
    <br/>
    <button onClick={()=>CreateTenantProperty(input1)}>Click to give the value to TenantProperty_Contoso tenant property value</button>
    <h2>this is value of the TenantProperty_Contoso = {tenantpropertyValue}</h2>
    </>
)

}

export default Test;

This is the code that I am using to call and get the tenant value.
Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
If you aren't using our caching (and its very hard to tell based on how your code is formatted above) then this is likely due to caching within the service itself. The storage entities aren't intended to store frequently updated data so are likely optimized for performance on the sever side.

Clicking a button continuously to update a value and then read it is exactly the kind of thing that would be affected by caching on the server.

**Comment by JarialAnkur** [comment]
Thankyou for the reply, I got the point its not a pnpJs issue. Its about the service at the backend.
