### ISSUE TITLE
Property 'fields' does not exist on type 'IList'.ts(2339) when trying to update taxonomy

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#2191]
### Category
- [ ] Enhancement
- [? ] Bug
- [ ?] Question
- [ ?] Documentation gap/issue

Please specify what version of the library you are using: [  3.1.0 ]

Please specify what version(s) of SharePoint you are targeting: [  1.14.0       ]

### Expected / Desired Behavior / Question
[following the documentation ](https://pnp.github.io/pnpjs/sp/items/#update-multi-value-taxonomy-field)
The line:
```
  const fields = await spAppSite.web.lists.getByTitle("TestList").fields.filter("Title eq 'MultiMetaData_0'").select("Title", "InternalName")();
```
Should be valid

### Observed Behavior
Getting TypeScript error
```
[{
	"resource": "/c:/Users/ogal/source/repos/SPFx/SPFx14/DPCOneJobScreen/src/hooks/useSPProject.ts",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'fields' does not exist on type 'IList'.",
	"source": "ts",
	"startLineNumber": 38,
	"startColumn": 69,
	"endLineNumber": 38,
	"endColumn": 75
}]
```
### Steps to Reproduce
Just implement the documentation

Thank you

**Comment by patrick-rodgers** [comment]
Hi @Ofer-Gal - I am not able to reproduce this using the code from the sample. Can you double check you have the line `import "@pnp/sp/fields";` included? That should attach the fields to web and list, and when I test it locally it works.

Are there any other factors you can think of that might be affecting things?

**Comment by Ofer-Gal** [comment]
No I did not have  `import "@pnp/sp/fields";` my bad.
Sorry
