### ISSUE TITLE
403 Forbidden with Firefox when trying to get term details

### ISSUE THREAD

**Issue by stevebeauge** [pnp/pnpjs#2193]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: *3.1.0*

Please specify what version(s) of SharePoint you are targeting: SharePoint Online + SPFX v1.14

### Expected / Desired Behavior / Question
PnP JS provide ability to get term details (from term ID to label for example). It should works whatever the browser is.

### Observed Behavior
Using EDGE (chromium), it's working.
Using Firefox however, it's failing with 403 error.

Specifically, this request emits a 403 error:

````
GET /sites/somecollection/_api/v2.1/termstore/sets/83b25cdb-71ca-4f06-a80d-2176347d2413/terms/dc7aadbd-5398-4234-9223-d2613a70eac9 HTTP/1.1
Host: mycorp.sharepoint.com
User-Agent: NONISV|SharePointPnP|PnPjs
Accept: application/json
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/json;charset=utf-8
.... other header removed ...
````

Results in :

````
HTTP/1.1 403 Forbidden
Cache-Control: private
Content-Type: application/json
.... other header removed ...

{"error":{"code":"notAllowed","message":"OAuth only flow is enabled and the call has not been issued from an app."}}
````

My analysis reveals it's related to the User-Agent. Emitting the same query with the standard UserAgent results in a success response HTTP 200 with term details

### Steps to Reproduce

In a SharePoint SPFX WebPart, add this code:

````typescript
const sp = spfi().using(SPFx(this.context));
const terminfo: ITermInfo = await sp .termStore.sets.getById('some id').getTermById('some id')();
````

### Workaround

Because the User Agent seems to be the guilty, we managed to workaround the issue by resetting the User Agent

````
import { InjectHeaders } from "@pnp/queryable";

// Later
const sp  = spfi()
            .using(SPFx(context))
            .using(InjectHeaders({ "User-Agent": navigator.userAgent}));
````

**Comment by juliemturner** [comment]
Odd situation, and I will totally have a discussion around this issue... but yay, this is the first manifestation of how our new V3 internals make this fix simple. Thanks for sharing!

**Comment by juliemturner** [comment]
To clarify that header is there on purpose because it helps with [throttling](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md#what-are-the-recommendations)... so, I don't think it's something we can remove. What would help is if you shared your research on why Firefox is being so opinionated about the header so we can look into that aspect further.

**Comment by stevebeauge** [comment]
I have no idea why FF behaves likes this. I discovered the issue is from the user agent because I compared with fiddler requests from the pnpjs and from pasting the url directly in the browser. Not sure I'm able to help

Regarding the throttling, doe)s it actually applies to spfx ? Because if yes, anyone may override Microsoft checks simply by faking a user agent of a well known product

**Comment by stevebeauge** [comment]
From another [issue][https://github.com/pnp/pnpjs/issues/867#issue-503475338) :

> The recommendation is to tag the User Agent with ISV and other information. However, when making these calls in the browser, setting the User Agent is not allowed.

**Comment by stevebeauge** [comment]
From another [issue][https://github.com/pnp/pnpjs/issues/867#issue-503475338) :

> The recommendation is to tag the User Agent with ISV and other information. However, when making these calls in the browser, setting the User Agent is not allowed.

**Comment by patrick-rodgers** [comment]
I haven't tried debugging this in FF but after checking internally the guidance has changed an we no longer need to include a custom user agent as it has no bearing on throttling. We'll take it out as that is the only reason we included it.
