### ISSUE TITLE
Getting error when attempting to add multiple files using @pnp.sp: 3.1.0

### ISSUE THREAD

**Issue by cardinalpipkin** [pnp/pnpjs#2195]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  "@pnp/sp": "^3.1.0", ]

Please specify what version(s) of SharePoint you are targeting: [ SPO, SPFX, Webpart ]

### Expected / Desired Behavior / Question
To upload multiple files to a SPO list item without error.

### Observed Behavior
When trying to add 2 files to a sharepoint list item it successfully adds 1 file but the second gives this error:
       
`Uncaught (in promise) Error: Error making HttpClient request in queryable [500]  ::> {"odata.error":{"code":"-2147467259, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"Cannot complete this action.\n\nPlease try again."}}}`

### Steps to Reproduce
Here is the util I'm using to create a list item, then add the multiple files:
![image](https://user-images.githubusercontent.com/7973051/161574907-0b8f3ace-2f40-4ea1-9b49-92443056aac1.png)

You can see in the commented code I have tried the latest versions sp.batched() but this only gives `Save conflict` errors.
I hope this is enough info?

**Comment by aaademosu** [comment]
Change the line where you are adding the attachments to this. Waiting for each file to be uploaded completely, would address the issue experienced. 

 `const addResult = await recordtoaddto.attachmentFiles.add(file.name, file);`

**Comment by cardinalpipkin** [comment]
@aaademosu - Just update code but now getting this error:

`Your changes conflict with those made concurrently by another user. If you want your changes to be applied, click Back in your Web browser, refresh the page, and resubmit your changes.`

**Comment by juliemturner** [comment]
I'm fairly sure forEach doesn't support promises... (i.e. you cannot await inside a forEach loop)

**Comment by aaademosu** [comment]
As julie correctly mentioned, we can't await inside a forEach. I do something similar using the code below, do try that.

```js
const attachments = await Promise.all(files.map(async (file) => {
      return await recordtoaddto.attachmentFiles.add(file.name, file);
 }));
```

**Comment by cardinalpipkin** [comment]
Hi - still getting a Save Conflict. This error is referencing the second file. Any other ideas?
Here is the latest version of the function:
`
export const CreateListItem = async (listName: string, item: any, files: File[]) => {
    const record = item as unknown as Record<string, any>;
    let newRecord = await sp.web.lists.getByTitle(listName).items.add(record);
    if (files) {
        console.log(files, 'files');
        let newItemId = newRecord.data.Id;
        const recordtoaddto = sp.web.lists.getByTitle(listName).items.getById(newItemId);
        const attachments = await Promise.all(files.map(async (file) => {
            return await recordtoaddto.attachmentFiles.add(file.name, file);
       }));
      }
    };
`

**Comment by cardinalpipkin** [comment]
export const AddFiles = (listName: string, itemId: number, files: File[], index:number = 0) => {
    if (files && index < files.length) {
        const file = files[index];
        const recordtoaddto = sp.web.lists.getByTitle(listName).items.getById(itemId);
        recordtoaddto.attachmentFiles.add(file.name, file).then(r=>{
            index++;
            AddFiles(listName,itemId,files,index);
        });
    }
};
This was the only solution that worked. Recursion. Thanks for your input.
