### ISSUE TITLE
Error: Cannot Find Resource for the Request $Batch

### ISSUE THREAD

**Issue by simkessy** [pnp/pnpjs#220]
I'm trying to batch add items to a list but keep getting the error: "Cannot find resource for the request $batch."

![image](https://user-images.githubusercontent.com/5871660/45001230-4601d500-af80-11e8-9f13-d39b3bddb3d7.png)

Any ideas as to what might be the issue, other than updating to the new version of pnp? 

This is on SharePoint 2013 on Premises and this is the setup configs: 

```
$pnp.setup({
    sp: {
        headers: {
            Accept: "application/json; odata=verbose"
        }
    },
    defaultCachingStore: "session", // or "local"
    defaultCachingTimeoutSeconds: 30,
    globalCacheDisable: false, // or true to disable caching in case of debugging/testing
    enableCacheExpiration: true, // added in 2.0.8
    cacheExpirationIntervalMilliseconds: 1000 // added in 2.0.8
});
```

These are what the requests look like: 

```
POST https://pmo.corp.firstrepublic.com/sites/epml/_api/web/lists/getByTitle('r3ProjectActions')/items HTTP/1.1
accept: application/json; odata=verbose
content-type: application/json;odata=verbose;charset=utf-8
x-clientservice-clienttag: PnPCoreJS:3.0.10

{"__metadata":{"type":"SP.Data.R3ProjectActionsListItem"},"Title":"My Item Title2"}

--changeset_57b2e269-f95b-4c38-8278-8a8226fd00ff
Content-Type: application/http
Content-Transfer-Encoding: binary
```

**Comment by koltyakov** [comment]
SharePoint 2013? There is batch API in 2013, it was introduced in SPO and went to 2016.

**Comment by simkessy** [comment]
Hi @koltyakov so there **isn't** in 2013, I see. Thank you.

**Comment by koltyakov** [comment]
Typo ;) Sure, there is no batch endpoint in 2013.
