### ISSUE TITLE
Batching terms from Termstore - Invalid request

### ISSUE THREAD

**Issue by sliziky** [pnp/pnpjs#2202]
### Category
- [ ] Enhancement
- [X] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   2.0.6      ]

Please specify what version(s) of SharePoint you are targeting: [   SHO      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
The problem I have is that I need to access the children of the terms in the term store. Sounds good except for the fact that I have more than 1,000 terms in this term store and iterating them would probably cause the Sharepoint throttling.

I also tried `getAllChildrenAsOrderedTree()` which is exactly what I need but it iterates too (1 term = 1 request).

Therefore I would like to use `batch` but I can't get it to work. Here is my code
```
this._configuredSp = sp.configure(null, this._context.pageContext.web.absoluteUrl);
const terms: ITermInfo[] = await this._configuredSp.termStore.groups.getById(groupId).sets
.getById(setId).children.top(10).get(); 
let batch = this._configuredSp.createBatch();
for(const term of terms) {
    this._configuredSp.termStore.groups.getById(groupId).sets.getById(setId).getTermById(term.id).inBatch(batch).get();
}
const res = await batch.execute();
```

The error I get in the console
`Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The expression \"v2.1/termstore/groups/afc5a824-61ac-4013-a10c-c7375833exyz/sets/b64ffxyz-170c-4c07-b0x6-f46efc2a0b6b/terms/6a0b2xyz4-3xyf0-zd3c-5bfd-a7ebcde02ddb\" is not valid."}}}`

Here is a part of the response
```HTTP/1.1 400 Bad Request
CONTENT-TYPE: application/json;odata=minimalmetadata;streaming=true;charset=utf-8

{"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The expression \"v2.1/termstore/groups/afc5a824-61ac-4013-a10c-c7375833exyz/sets/b64ffxyz-170c-4c07-b0x6-f46efc2a0b6b/terms/6a0b2xyz4-3xyf0-zd3c-5bfd-a7ebcde02ddb\"  is not valid."}}}
--batchresponse_08cf60e4-bfe5-4783-a530-b2aa6f341bf7
Content-Type: application/http
Content-Transfer-Encoding: binary
```

Is this the right approach or is there any other method I do not know about?

Thank you for your feedback!

**Comment by sliziky** [comment]
I found out that there is the endpoint to find a specific term inside the term store `_api/v2.1/termStore/searchTerm(label='XYZ,languageTag='en-US')?$expand=set` which solved this for me. Is this already in the PnP library ? Because I could not find it

**Comment by juliemturner** [comment]
No it isn't... I'll mark this as an enhancement request.
