### ISSUE TITLE
Retrieving items from SPO list with .select()

### ISSUE THREAD

**Issue by DmitriyVdE** [pnp/pnpjs#2204]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.1.0 ]

Please specify what version(s) of SharePoint you are targeting: [ SPO ]

### Expected / Desired Behavior / Question
I'm creating a new webpart and I need to retrieve items from a list. I use the following code to do so:

```
const spCurrentSite = spfi(sp).using(SPFx(context));

const listData: NavigationItem[] = await spCurrentSite.web.lists
  .getByTitle('listname')
  .items
  .select('field1', 'field2', 'field3', 'field4', 'field5')();
```

### Observed Behavior
Using the above snippet the query URL results to the following:

`https://tenantname.sharepoint.com/sites/sitename/_api/web/lists/getByTitle('listname')/items?$select=field1,field2,field3,field4,field5`

This returns a 400-status code.

Notice the '$'-sign in the URL, removing this causes the query URL to return XML.

I can however just use the following snippet, which works, without the '.select()' operator to retrieve all fields from the list:

```
const spCurrentSite = spfi(sp).using(SPFx(context));

const listData: NavigationItem[] = await spCurrentSite.web.lists
  .getByTitle('listname')
  .items();
```

Which results in the following query URL:

`https://tenantname.sharepoint.com/sites/sitename/_api/web/lists/getByTitle('listname')/items`

This correctly returns all items from the list.

Am I doing something wrong? This used to work fine in PnPSP v2, although with different syntax, etc...

I do notice the '$'-sign in the source in the following file: https://github.com/pnp/pnpjs/blob/version-3/packages/sp/spqueryable.ts

### Steps to Reproduce
Create a list and use the above code snippets, with replaced values, to query the SPO list.

**Comment by DmitriyVdE** [comment]
This was a really weird problem but I found the culprit. For some reason it just refused to retrieve a column from my list I called 'Url'. No matter how many times I renamed it, it just kept erroring on the fact that the column name didn't exist. I created a new column and just called it 'Link' and it retrieves the items just fine.
I also dropped the 'sp' from the spfi() I got from the following [Microsoft guide](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts) and just using the following code works, no fancy functions required: 
```
const spCurrentSite = spfi().using(SPFx(context));
const listData: NavigationItem[] = await spCurrentSite.web.lists
  .getByTitle('listname')
  .items.select('field1', 'field2', 'field3', 'field4', 'field5')();
```
Still weird that it doesn't throw any errors though and that the query returns XML when I remove the '$'-sign. Anyone know why?

**Comment by patrick-rodgers** [comment]
Cool, sounds like you're all set.

I don't know why removing the $ returned XML - was that XML an HTML error page by chance? Sometimes you can hit errors that return the full HTML error page as the response.

**Comment by DmitriyVdE** [comment]
> Cool, sounds like you're all set.
> 
> I don't know why removing the $ returned XML - was that XML an HTML error page by chance? Sometimes you can hit errors that return the full HTML error page as the response.

I checked and it returns actual data. So I'm just really confused, did something change about the API or MS trying to move to some new syntax/URL form?

**Comment by juliemturner** [comment]
Sorry, we have no visibility into what Microsoft may or may not have changed with their REST APIs.  If you want to ask them directly and can provide an example of using the REST endpoint without PnPjs in the middle, you can post your query to the [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues).

I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
