### ISSUE TITLE
Uncaught (in promise) TypeError:  ... .filter is not a function

### ISSUE THREAD

**Issue by bdking71** [pnp/pnpjs#2207]
### Category
- [ ] Enhancement
- [ ] Bug
- [ X ] Question
- [ X ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  3.1.0 / 3.1.0-v3nightly.20220307       ]

Please specify what version(s) of SharePoint you are targeting: [    SPO    ]

### Expected / Desired Behavior / Question

When I add .fliter() to my code... 

await this.sp.web.lists
   .getByTitle(<LIST NAME>)                        
    .items()
    .filter('fRecurrence eq "true"')                  
    .then((event) => {

### Observed Behavior

ERROR: Uncaught (in promise) TypeError:  this.sp.web.lists.getByTitle(...).items(...).filter is not a function

### Steps to Reproduce

I am importing: 

    import { spfi, SPFx } from "@pnp/sp";
    import "@pnp/sp/webs";
    import "@pnp/sp/lists";
    import "@pnp/sp/items";

I am guessing I am missing something, but I haven't found a lot of documentation on version 3.1.  I have also tried the nightly release (3.1.0-v3nightly.20220307) 

Thanks.

**Comment by bdking71** [comment]
I figured it out.  

await this.sp.web.lists
  .getByTitle(<LIST TITLE>)                        
  .items()
  .getItems(["fRecurrence eq 'true'"])                        
  .then((spEvents) => {

**Comment by patrick-rodgers** [comment]
I haven't found a lot of details in your post but [this might help](https://pnp.github.io/pnpjs/sp/items/#basic-get). It doesn't show filter, but does `select` and `top`. I believe you need to remove the `()` from items. That indicates you are making the call, which would return a promise, which does not have a filter method.

This should work:

```TypeScript
await this.sp.web.lists
.getByTitle()
.items
.filter('fRecurrence eq "true"')
.then((event) => {
```

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
