### ISSUE TITLE
PnPJS Search, `SourceId` is being ignored

### ISSUE THREAD

**Issue by JoshuwayMorris** [pnp/pnpjs#2210]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.2.0 ]

Please specify what version(s) of SharePoint you are targeting: [ Sharepoint Online ]

### Expected / Desired Behavior / Question
[PnPJS Search](https://pnp.github.io/pnpjs/sp/search/) is ignoring `SourceId`.

### Observed Behavior
After specifying `SourceId` as part of the [PnPJS Search](https://pnp.github.io/pnpjs/sp/search/) `ISearchQuery` interface, the results returned are not from the expected source. Instead, they default to the SharePoint Online default _"Local SharePoint Results"_.

Please find below a screenshot of the response object after executing the search. 

As you can see, the correct `SourceId` (403cc987-1997-4f4a-9271-0a3815e3d7b4) appears in the `_query` property.

However, the `SourceId` in the `_raw` property has defaulted to the SharePoint Online default _"Local SharePoint Results"_ 
 (8413cd39-2156-4e00-b54d-11efd9abdb89).

This implementation **was working**, and only **stopped working  in the last few days**, suggesting Microsoft have potentially changed the implementation?

Thank you!

<img width="2022" alt="Response Object" src="https://user-images.githubusercontent.com/48333553/162935839-f677a9e1-b0a8-4b90-98ed-1bb9989ac329.png">

### Steps to Reproduce
Please find below a screenshot of the code executed.

```
// Populate search query
const searchQuery: ISearchQuery = {
    RowLimit: searchService.ItemsPerPage,
    SourceId: sourceId, // 403cc987-1997-4f4a-9271-0a3815e3d7b4
    SelectProperties: searchService.SelectProperties,
    SortList: searchService.SortList,
    TrimDuplicates: false,
    StartRow: request.Page * searchService.ItemsPerPage,
    Refiners: searchService.Refiners.join(','),
    RefinementFilters: request.RefinerTokens,
    RankingModelId: rankingModelId,
    EnableNicknames: true,
    EnablePhonetic: true,
    EnableInterleaving: true,
};

// Prepare query
const query = SearchQueryBuilder(querytext, searchQuery)

// Retrieve results
const results: SearchResults = await ConfigService.sp.search(query);
```

<img width="615" alt="Code" src="https://user-images.githubusercontent.com/48333553/162935849-08048364-48f5-4021-b029-3d76f9f9b884.png">

**Comment by patrick-rodgers** [comment]
Haven't tested it yet, and I believe you - but unsure what we can do to help? It doesn't sound like we've changed anything on our side, and it seems like we are sending the query you expect to the server - are there steps we can do to assist?

If the API changed that sounds like a regression in the service, which you can [report here](https://github.com/SharePoint/sp-dev-docs/issues).

**Comment by JoshuwayMorris** [comment]
Thank you @patrick-rodgers for your reply.

I have [raised an issue on the sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues/7883) to try and see if their team can shed any light on the issue.

As the issue had only started occurring in the last few days, I wasn't sure if anyone else had experienced the issue. Or, if the API had recently changed, that I needed to update my code in some way. For example, by wrapping my `sourceId` within a new object called `Properties` or something to that affect.

I appreciate your reply, and hopefully the sp-dev-docs may shed some light.

**Comment by JoshuwayMorris** [comment]
Thank you all for your reply @patrick-rodgers,

We logged the issue with Microsoft, but we have not received a reply yet. However, our services started working again as expected last week. So we can only assume that Microsoft resolved the issue on their end.

Therefore, I am going to close this issue, but thank you for all your help.
