### ISSUE TITLE
Unable to query other site

### ISSUE THREAD

**Issue by quantrpeter** [pnp/pnpjs#2212]
Hi
   I am unable to retrive list items from other site, this doesn't work, no error come out, the lines just don't run.

let web = Web(linkPath);
let tags: any[] = await web.lists.getByTitle("Tag").items();

please help
thanks
Peter

**Comment by patrick-rodgers** [comment]
Have you added any observers? By default using the Web factory would give you an object with no associated observers.

Have a look at: https://pnp.github.io/pnpjs/getting-started/

**Comment by Mike-tech** [comment]
@quantrpeter I stumbled with this one initially too and I was doing what you did. Looking through the documentation, which wasn't made clear in the Webs section, I was able to call another site using this code:

`const w = spfi("https://domain.sharepoint.com/sites/somesite").using(SPFx(this.props.webpartContext)).web;`

Use w as you wish. Hope this help
