### ISSUE TITLE
File.copyByPath() - Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by jpalo** [pnp/pnpjs#2215]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [2.13.0]

Please specify what version(s) of SharePoint you are targeting: [online]

### Expected / Desired Behavior
File.copyByPath() working as described in the [documentation](https://pnp.github.io/pnpjs/sp/files/#copy-by-path) and copying a file from one site collection to another.

### Observed Behavior
Following errors are thrown:

```
{"odata.error":{"code":"-1, System.UriFormatException","message":{"lang":"en-US","value":"Invalid URI: The format of the URI could not be determined."}}}
```

### Steps to Reproduce
Create a SPFx web part, add pnp and deploy on a site. Get a file with files from a folder. Try to copy a file with .copyByPath() using either absolute url (https://xxx.sharepoint.com/sites/b/doclib/test.docx) or relative url (sites/b/SitePages/doclib/test.docx) as parameter and providing either true or false as second parameter.

```

const files: IFile[] = await sourceWeb.getFolderByServerRelativePath(sourceRootFolderPath).files.select('Name,ServerRelativeUrl')();
                  
for (let i = 0; i < files.length; i++) {             
   let sourceFileUrl: string = files[i]['ServerRelativeUrl']; 
   await sourceWeb.getFileByServerRelativePath(sourceFileUrl).copyByPath(listUrl + "/" + files[i]['Name'], true, true);
}
```

This is the generated POST call: `https://xxx.sharepoint.com/sites/b/_api/SP.MoveCopyUtil.CopyFileByPath(overwrite=@a1)?@a1=true`

with body:
```
{
    "destPath": {
        "DecodedUrl": "/sites/b/JTest2/02 Angebot/test EGG.xlsx",
        "__metadata": {
            "type": "SP.ResourcePath"
        }
    },
    "options": {
        "KeepBoth": true,
        "ResetAuthorAndCreatedOnCopy": true,
        "ShouldBypassSharedLocks": true,
        "__metadata": {
            "type": "SP.MoveCopyOptions"
        }
    },
    "srcPath": {
        "DecodedUrl": "/sites/a/ProjectFolder_Folders/DEU/MOD/test EGG.xlsx",
        "__metadata": {
            "type": "SP.ResourcePath"
        }
    }
}
```

If I test this with Postman and change relative URLs in body to absolute URLs, it works. 

Why are relative URLs not working? There are few issues related to this, but all are at least 2 years old so I'm wondering if I'm missing something obvious as I'm still getting the error.

**Comment by patrick-rodgers** [comment]
Yes, this looks like a bug, but we are no longer maintaining version 2. If you want to submit a PR [this is the function that needs fixed](https://github.com/pnp/pnpjs/blob/version-2/packages/sp/files/types.ts#L227).

You can see [how it was done in version 3 here](https://github.com/pnp/pnpjs/blob/version-3/packages/sp/files/types.ts#L194).

I did confirm this works in version 3. Beyond time are they any blockers such as missing functionality stopping you from upgrading?

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
