### ISSUE TITLE
V3 - Add Files not working as expected

### ISSUE THREAD

**Issue by omarelanis** [pnp/pnpjs#2217]
### Category
- [ ] Enhancement
- [X] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    V3     ]

Please specify what version(s) of SharePoint you are targeting: [  SharePoint Online - SPFx version 1.13.1   ]

### Expected / Desired Behavior / Question
Following the guide here https://pnp.github.io/pnpjs/sp/files/ for the new V3 version on uploading files I expect to be able to create a new file within a document library by targeting a site using the following code:

      let siteUrl = "https://tenant.sharepoint.com/sites/mysite";
      let web = Web(siteUrl);

      let file = fileMeta[0];
        // you can adjust this number to control what size files are uploaded in chunks
        if (file.size <= 10485760) {
            // small upload
            await web.getFolderByServerRelativePath("myLibrary").files.addUsingPath(file.name, file.content, {Overwrite: true});
        } else {
            // large upload
            await web.getFolderByServerRelativePath("myLibrary").files.addChunked(file.name, file.content as Blob, data => {
            }, true);
        }

### Observed Behavior
Using the above code does not actually create a file, when it hits web.getFolderByServerRelativePath nothing happens

In my original code I was using the following which has the same effect but just scoped to the current site:

        let currentWeb = await sp.web();
        let web = Web(currentWeb.Url);

       let file = fileMeta[0];
        // you can adjust this number to control what size files are uploaded in chunks
        if (file.size <= 10485760) {
            // small upload
            await web.getFolderByServerRelativePath("myLibrary").files.addUsingPath(file.name, file.content, {Overwrite: true});
        } else {
            // large upload
            await web.getFolderByServerRelativePath("myLibrary").files.addChunked(file.name, file.content as Blob, data => {
            }, true);
        }

In both cases when it hits the line with web.getFolderByServerRelativePath nothing actually happens, no POST request is sent out within the browser, the subsequent code does not run either as the await action never completes.

However, if I change the code and instead of using the Web target I use the SP constant which was declared using
 const sp = spfi().using(SPFx(spfxContext)); then everything works as expected and the file is created

 await sp.web.getFolderByServerRelativePath("myLibrary").files.addUsingPath(file.name, file.content, {Overwrite: true});

i.e:

        let file = fileMeta[0];
        // you can adjust this number to control what size files are uploaded in chunks
        if (file.size <= 10485760) {
            // small upload
            await sp.web.getFolderByServerRelativePath("myLibrary").files.addUsingPath(file.name, file.content, {Overwrite: true});
        } else {
            // large upload
            await sp.web.getFolderByServerRelativePath("myLibrary").files.addChunked(file.name, file.content as Blob, data => {
            }, true);
        }

Not sure if this is a bug or just that the documentation needs updating but I can't get the suppled code in the help docs to work

### Steps to Reproduce
Add the code from the section "Adding Files" on the page https://pnp.github.io/pnpjs/sp/files/ and try to create a file in a SharePoint library

**Comment by wmertens** [comment]
FWIW I use `sp.web` as well and it works for me.

**Comment by juliemturner** [comment]
Sorry, that's a documentation miss.  I thought we caught all of the stragglers but that's a somewhat different "sample" and slipped through the cracks.  You can use Web() but you have to add observables to it for it to work... see the [documentation](https://pnp.github.io/pnpjs/sp/webs/#iweb) on how that works. Long story short you either need to add observables to the Web() or pass them in... this should work as well:

```TypeScript
const currentWeb = await sp.web();
let web = Web(currentWeb);
```
Because then `web` will have a copy of the observables from `currentWeb`.

Regardless, I'll get the sample updated.

**Comment by omarelanis** [comment]
> ```ts
> const currentWeb = await sp.web();
> let web = Web(currentWeb);
> ```

Thanks for the quick reply @juliemturner, I did try with below code as well but neither that not directly passing in the URL would work which is why I reverted to using the sp.web method

const currentWeb = await sp.web();
let web = Web(currentWeb);

**Comment by juliemturner** [comment]
How did you create the sp object?
like this: `const sp = spfi().using(SPFx(spfxContext));`?

**Comment by omarelanis** [comment]
Yep thats correct, used the same code const sp = spfi().using(SPFx(spfxContext)); further up in my code.

So the first two samples in my original submission wouldnt work, however just adding sp.web without any other changes makes it work.

**Comment by juliemturner** [comment]
Yes, that is the correct way, but my example should also work as you can pass an SPQueryable to Web and it should copy the observables... We'll look into it.

**Comment by juliemturner** [comment]
OMG, my bad, I'm sorry I didn't edit the sample I posted correctly... maybe I should not answer questions after a full days work 😜

Anyway, let me correct the sample above.
```TypeScript
const currentWeb = sp.web;
let web = Web(currentWeb);
```
Note that we're not invoking or awaiting web.  So now currentWeb is an SPQueryable and therefore you can pass it to the constructor of Web.  To me, this pattern is only really useful when you want to add other behaviors.  Honestly, this patttern seems more useful, where you want the observables but want to switch webs... so this assumes that sp.web is connected to a web other than `otherweb`.

```TypeScript
const web = Web([sp.web, "https://mytenant.sharepoint.com/sites/otherweb"]);
const w = await web();

```

**Comment by omarelanis** [comment]
> OMG, my bad, I'm sorry I didn't edit the sample I posted correctly... maybe I should not answer questions after a full days work 😜
> 
> Anyway, let me correct the sample above.
> 
> ```ts
> const currentWeb = sp.web;
> let web = Web(currentWeb);
> ```
> 
> Note that we're not invoking or awaiting web. So now currentWeb is an SPQueryable and therefore you can pass it to the constructor of Web. To me, this pattern is only really useful when you want to add other behaviors. Honestly, this patttern seems more useful, where you want the observables but want to switch webs... so this assumes that sp.web is connected to a web other than `otherweb`.
> 
> ```ts
> const web = Web([sp.web, "https://mytenant.sharepoint.com/sites/otherweb"]);
> const w = await web();
> ```
> 
> Anyway, yes still a documentation issue, we're working on trying to get everything we missed cleaned up....

Awesome that makes perfect sense :)

Thank you for looking at it so quickly and for the detailed reponses. Keep up the amazing work you're all doing, it's making our lives so much easier!
