### ISSUE TITLE
PnP JS v3 Complete Guide to Getting and Setting SharePoint Fields Values using PnP JS in SPFx

### ISSUE THREAD

**Issue by miguelisidoro** [pnp/pnpjs#2219]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

PnP 3

Please specify what version of the library you are using: [ 3.2.0 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online  ]

Hello.

Is it possible to update the PnP JS for v3 with all the examples of reading and writing operations in SharePoint List Items in a similar way to https://ravichandran.blog/2020/06/24/a-complete-guide-to-getting-and-setting-fields-value-using-pnp-js-in-spfx/ (valid for v2) in the PnP JS official documentation?

The way SharePoint fields are read and set was changed for some field types and it would be great to have examples on how to read and write data for all field types. 

Do you think it is possible?

Thanks

**Comment by juliemturner** [comment]
It's completely possible... but nothing in that list, other than how to establish the sp context, has changed from v2->v3... we happily take PRs for anything you think needs updating.

**Comment by miguelisidoro** [comment]
Thanks @juliemturner.

From our tests on migrating from PnP v2 to PnP v3, there is a difference setting the SPFx context but we also noticed a difference setting a  People or Group (multiple selection).

We changed from:
const i = await list.items.getById(1).update({
  OwnersId: { results: usersvalue }
});

To:
const i = await list.items.getById(1).update({
  OwnersId: usersvalue
});

Can you confirm this change and that there are no other changes?

Thanks

**Comment by juliemturner** [comment]
What you're experiencing is the change we made to move to minimal metadata as referenced in the [changelog](https://github.com/pnp/pnpjs/blob/version-3/CHANGELOG.md#300---2022-feb-14)... so yes, there are a few places where that manifests but 99% of the calls remain unchanged as we addressed in our [transition guide](https://pnp.github.io/pnpjs/transition-guide/).  We made every effort to update the documentation accordingly but it's a big job and we may have missed some things.  Please feel free to submit PR's for any changes that you find that we missed,.

**Comment by miguelisidoro** [comment]
Thanks Julie for the feedback. It is indeed a big effort and
congratulations on the team for this achievement.

In another topic, do you know if is there any PnP library for c# and .NET
Framework and .NET Core and if there is what is the Nuget Package?

Thanks

**Comment by juliemturner** [comment]
Please use this URL for information on all the content provided by community and managed by the PnP team: https://pnp.github.io/#sdks

I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
