### ISSUE TITLE
Modern page loses PageContext on click back, and site.getRootWeb() method fails 

### ISSUE THREAD

**Issue by SapiensID** [pnp/pnpjs#2221]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.2.0 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online - modern pages ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I set up a configuration file as suggested in [Add a project configuration file](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts).  My configuration page is [here](https://github.com/SapiensID/test-rootWeb/blob/main/src/webparts/testRootweb/pnpjsConfig.ts) 
I use this in a [provider file](https://github.com/SapiensID/test-rootWeb/blob/main/src/webparts/testRootweb/components/providers/RootProvider.ts) that has a method the instantiates  a site's root site using sp.site.getRootWeb() . For simplicity, I'm just getting the root web's Title, and returning it to a component that displays the title. 

```js
export class RootProvider {
    private _sp: SPFI;

    constructor() {
        this._sp = getSP();
    }

    public getRootTitle = async ():Promise<string> => {
        const rootweb = await this._sp.site.getRootWeb();
        const { Title } = await rootweb.select("Title")();
        return Title;
    }
}
```

Everything works when first rendering the app in a modern page. The problem I'm having is, when I navigate to another page in the site (in this case, another modern site page) and then I get back to the page hosting the app, by clicking the back button, getRootWeb() fails because pageContext is undefined. The error message I get is:

`uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'web')`

I'm not sure if this a problem with how I architected the solution or if this is a bug. Following the suggestion of the Microsoft's article I mentioned, I'm passing the web part context on the onInit method:

```js
    return super.onInit().then(()=>{
      getSP(this.context);
    });
```

### Steps to Reproduce
I created a very [simple repository](https://github.com/SapiensID/test-rootWeb) to reproduce the problem. The web part displays the title of the root web, and has a link to navigate away from this page (the href for this link can be added in the web part property pane). The link should go to another page in your site (in my case, I navigate to another modern pages). 

I installed the web part on a sub site (https://mytenant.sharepoint.com/subsite) On first render, the web part will display the title of your root tenant, as expected. 

After clicking on the link and then returning to the previous page hosting the web part,  by clicking the back button on your browser, you will see the error message in the developer console, and the root web's title will not display.

**Comment by juliemturner** [comment]
Ok, well yeah, the scenario you're invoking requires a bit more thinking than the sample we provided... You need to handle the case on a partial page repaint which isn't really going to a new page but actually just refreshing part of the page.  In that scenario the var _sp retains its value between pages and the pageContext isn't reset in the context object that was originally passed.  Your scenario would actually be better solved with a service implementation... but that's another conversation.

To solve your issue using this pattern you need to expand the implementation a bit by adding a dispose method.

Ergo add the following to your pnpjsConfig.ts file
```TypeScript
export const disposeSP = () => {
  _sp = null;
}
```

And then call it by adding to the onDispose method
```TypeScript
  protected onDispose(): void {
    disposeSP();
    ReactDom.unmountComponentAtNode(this.domElement);
  }
```

**Comment by SapiensID** [comment]
ok, thanks a lot - I think I wasn't aware of the partial page repaint. I used your suggestion and it worked. Will update my test repository for reference.
