### ISSUE TITLE
Uploads are not checked for content length

### ISSUE THREAD

**Issue by wmertens** [pnp/pnpjs#2225]
### Category
- Enhancement

### Version

Please specify what version of the library you are using: [        v3 ]

Please specify what version(s) of SharePoint you are targeting: [ online        ]

### Expected / Desired Behavior / Question

See #2218 for background.

When uploading data via HTTP, it is safer to provide the size of what you will upload so the receiver knows when it is incomplete. To do this, a Content-Length header should be added.

None of the sp upload methods add the header. Since none of the methods use streams (directly), the size is always known and it would be safer to add it.

**Comment by patrick-rodgers** [comment]
We've not done this for years, happy to not change it now.
