### ISSUE TITLE
files.addUsingPath() error handling for network disconnect

### ISSUE THREAD

**Issue by omarelanis** [pnp/pnpjs#2226]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    V3     ]

Please specify what version(s) of SharePoint you are targeting: [ SP Online ]

### Expected / Desired Behavior / Question
When an error occurs like the network dropping whilst I am attempting to upload a file I expect an error to be thrown

### Observed Behavior
Instead the PnP JS library just keeps retrying the connection without any timeout

![image](https://user-images.githubusercontent.com/35841910/164190980-a9e24199-a464-4937-a8c1-4f43626b7fa1.png)

### Steps to Reproduce

Add the PnP JS code to upload a file and then in the Network tab set the throttling to No Network (or disconnect the internet) and then try submitting the file for upload

file= await sp.web.getFolderByServerRelativePath("somelibrary").files.addUsingPath(file.name, file.content, {Overwrite: true}).catch( (err) => { console.log(err) })

I have tried both a try catch method and the above promise catch and neither work, leaving it to run results in hundreds of thousands  of errors in the console, only when

**Comment by patrick-rodgers** [comment]
Going to call this an enhancement. Updated the retry logic to handle this case where network connectivity is lost after the page has loaded. It will now respect the number of specified retries and throw the error from the failed network request maintaining the correct stack information.
