### ISSUE TITLE
Feature request: make chuncked upload cancellable

### ISSUE THREAD

**Issue by stevebeauge** [pnp/pnpjs#2228]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   3.2  ]

Please specify what version(s) of SharePoint you are targeting: [    Online with SPFX 1.14     ]

### Expected / Desired Behavior / Question

Uploading large files should be cancelable when using chunk upload.

If a file upload is cancel, the [CancelUpload method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.client.file.cancelupload?view=sharepoint-csom) should be called.

### Observed Behavior
Currently, when the upload is triggered, there's no way to stop uploading, except closing the browser tab.

### Implementation

Ideally, the [addChunked function](https://github.com/pnp/pnpjs/blob/94c8345b03a830628695af75824d3f8fe90cb3b1/packages/sp/files/types.ts#L82) should return an object that contains both the Promise and a callable method that can signal the cancel request (by putting a flag the setContent function can monitor).

However, I guess changing the signature of the function would break existing code.

Possible ways (quick thoughts):
* adding a new `addChunkedCancelable` that return promise and callback
* add a new class "CancelationToken" that contains the desired state (Continue or Cancel), and add an optional argument to the addChunked and setContentChunked functions to provide this cancalation token
* add new propertie to the report progress data, allowing the caller to set the cancel flag.

**Comment by patrick-rodgers** [comment]
Got it. We'll think about how best to do this - doubt it would make it to 3.3 but let's see.

**Comment by stevebeauge** [comment]
Maybe this can help too : https://stackoverflow.com/a/46465935/588868

**Comment by patrick-rodgers** [comment]
Just a small update, talking through this with @juliemturner in our weekly meeting and we are going to try and make a new behavior that will make ALL requests cancellable through a `cancel` method injected into the promise. Not going to promise you (haha) it will work, but we are going to give it a shot. Then methods that have some specific cancel logic, like the chunked uploads can subscribe to an internal event to know it was cancelled. This way we are solving the more general case and making a bigger enhancement to the library.

MIGHT make it into the next release in a beta capacity, but depends on how much time I can invest between now and then.

**Comment by wmertens** [comment]
FYI I had a look at ECMA cancellation proposals, and there was one for Promise which was withdrawn and another more general one hasn't been updated in 5 years. So whatever API you come up with should be good.

Interesting thoughts to consider at https://github.com/tc39/proposal-cancellation#architecture

**Comment by patrick-rodgers** [comment]
@stevebeauge - for this I have things mostly working, have some testing left to do. CancelUpload is wired up and working.

One questions for you, addChunked creates an empty file into which the chunked content is uploaded. cancel upload does NOT delete this empty container. Would you expect that if you cancel an addChunked request that empty file is deleted? This question would only affect add operations - setContentChunked would leave the file in place but cancel the upload (which should leave the file unchanged).

**Comment by stevebeauge** [comment]
I guess deleting the empty file would be fine. In perspective of using the library, I wouldn't have to bother with cleanup of internal details of implementation.
