### ISSUE TITLE
EnsureSitePagesLibrary / select is not working.

### ISSUE THREAD

**Issue by Dangerous-Mind** [pnp/pnpjs#2232]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.2.0 ]

Please specify what version(s) of SharePoint you are targeting: [ Online ]

### Expected / Desired Behavior / Question
Item should return a value.

### Observed Behavior
When the transaction tries to do the `await siteAssetsList.select("Title")()` It ddisappears.
No error, no message the transaction just disappears.

By the way. I'm trying to implement the 3.2.0 but there are a lot of silent errors that don't allow us to know that something is not working properly.

### Steps to Reproduce
```
import { spfi } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";

const sp = spfi().using(SPFx(This.Context));

// get Site Pages library
const siteAssetsList = await sp.web.lists.ensureSitePagesLibrary();

// get the Title
const r = await siteAssetsList.select("Title")();

// log Title
console.log(r.Title);
```

**Comment by Dangerous-Mind** [comment]
Hi @patrick-rodgers @juliemturner,

Can you take a look at this issue please?
Is there a way to have the error messages on console so that we can verify if any sp call is crashing?

**Comment by Dangerous-Mind** [comment]
Hi @patrick-rodgers, 

I didn't understood the 👎 reaction.

Is it something wrong in the post?
The code was taken from the [documentation](https://pnp.github.io/pnpjs/sp/lists/#ensure-site-pages-library-exist).
So it should be working, I guess.

In the mean time, we decided to rollback to V2. It's much to dangerous to use this one since it doesn't throw any message and it cancels the transaction in several type of calls, not just this one. The catch or try catch will not be triggered also.

There is no hurry at this time.

Thanks

**Comment by patrick-rodgers** [comment]
> I didn't understood the 👎 reaction.

This library is maintained by volunteers in their spare time. There is no one whose job is fixing issues or responding to questions. When you post things like "Can you take a look at this issue please?" you are saying, "please drop whatever else you are doing in your life & job and deal with my issue immediately.". We work through the issues as we have time, typically oldest to newest. Not saying it isn't an issue, haven't had a chance to look.

**Comment by Dangerous-Mind** [comment]
Nice, Thanks @patrick-rodgers ,

It was not my intention to control your time. I know you are volunteers.

My previous post was mainly me trying to get information to how find this issues since they don't throw any message and don't return to our code.
Since our solution has a lot of webparts and extensions is very dificult and risky to validate everything is working fine if the process disappears.

I'll pick up a old V3 branch and test it tomorrow.  
Once again, thanks 👍

**Comment by Dangerous-Mind** [comment]
Tested, It's working fine.
