### ISSUE TITLE
graph.user.getById does not work for external users

### ISSUE THREAD

**Issue by nbelyh** [pnp/pnpjs#2238]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.11]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question

The function graph.users.getById() does not seem to url-encode the ID. 
Therefore, it errors for external users like: "meganb_m365x83713278.onmicrosoft.com#ext#@somedomain.onmicrosoft.com"
Important: The parameter "id" for "getById" may be a login name, and there may be hash "#" symbols in it.

Not sure if this case is by design, or maybe overlooked.

Library call:
```
graph.users.getById('meganb_m365x83713278.onmicrosoft.com#ext#@somedomain.onmicrosoft.com')
```

Expected request to graph:
```
GET https://graph.microsoft.com/v1.0/users/meganb_m365x83713278.onmicrosoft.com%23ext%23@somedomain.onmicrosoft.com
```

Actual request to graph:
```
GET https://graph.microsoft.com/v1.0/users/meganb_m365x83713278.onmicrosoft.com
```

The second one results in error.

**Comment by patrick-rodgers** [comment]
Thanks for letting us know, we'll have a look.

**Comment by nbelyh** [comment]
Thanks! I understand this may be a bit of an odd case and normally "id" in getById() is a guid.
