### ISSUE TITLE
Documentation gap/issue for multiple values User Fields

### ISSUE THREAD

**Issue by HarminderSethi** [pnp/pnpjs#2241]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ V3 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*For multiple value User field the documentation text should say - "For multiple value fields, you need to supply an array" *

### Observed Behavior
*It seems there is issue in the documentation update on the website and for the multiple value user field the documentation text is still "For multiple value fields, you need to supply an object with a "results" property and an array" I pulled the latest documentation from the git repo and it contains the updated text but not sure why [*https://pnp.github.io/pnpjs/sp/items/#user-fields*](https://pnp.github.io/pnpjs/sp/items/#user-fields) section showing old content*

### Steps to Reproduce
[*https://pnp.github.io/pnpjs/sp/items/#user-fields*](https://pnp.github.io/pnpjs/sp/items/#user-fields)

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
This is already [updated in the docs](https://github.com/pnp/pnpjs/blob/version-3/docs/sp/items.md#user-fields) from a previous issue and will be published with the next release. Thanks for letting us know.
