### ISSUE TITLE
sendmail does not return erorrs?

### ISSUE THREAD

**Issue by evlo** [pnp/pnpjs#2243]
Hi,

I have spfx application here that uses `sp.utility.sendEmail`. Is it possible to catch errors? Users are reporting that sometimes they do not receive email, nothing in exchange log (not even anything about received email from no-reply@sharepointonline.com), nothing in their spam. I tried /_api/SP.Utilities.Utility.SendEmail directly and i'm not able tu simulete it

### Category
- [x]  Enhancement
- [ ]  Bug
- [x]  Question
- [ ]  Documentation gap/issue

### Version

Please specify what version of the library you are using: [     3.2.0    ]

Please specify what version(s) of SharePoint you are targeting: [   online      ]

### Expected / Desired Behavior / Question
I would like to be catch any errors returned by sendMail if possible and if there are any

**Comment by evlo** [comment]
That is pretty much my question, i was not able to get any error from /_api/SP.Utilities.Utility.SendEmail when i successfully called it. How would catch exception in `await sp.utility.sendEmail({` in typescript, i'm probably missing some basic concept here I think try catch does not work in js especially when using async calls, but maybe i'm wrong.

**Comment by patrick-rodgers** [comment]
You can [review our article on handling errors ](https://pnp.github.io/pnpjs/concepts/error-handling/)as a start. try...catch should work as expected.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
