### ISSUE TITLE
AddValidateUpdateItemUsingPath() in a advanced batch request returns status code 200 but fails to add item to the list

### ISSUE THREAD

**Issue by NewGHUser4321** [pnp/pnpjs#2249]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.2.0 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question

> When a return status code is 200, item should be added to the list. But it is not being added. Either the list item should be added to the list or return the status code 500.

### Observed Behavior

**1. When a invalid short URL is sent in the AddValidateUpdateItemUsingPath request using advanced batching, it is returning status code 200 but the list item is not added to the list.** 

> Example field value: 
> `"FieldValue": "Item"`
> 
> **Individual Response:**

```--batchresponse_1c2c41f0-0401-4e2a-8b4a-4720e5c340d9
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 200 OK
CONTENT-TYPE: application/json;odata=minimalmetadata;streaming=true;charset=utf-8

{
  "odata.metadata": "https://somespo.sharepoint.com/sites/group/_api/$metadata#Collection(SP.ListItemFormUpdateValue)",
  "value": [
    {
      "ErrorCode": 0,
      "ErrorMessage": null,
      "FieldName": "Date_x0020_First_x0020_Played",
      "FieldValue": "10/23/2015",
      "HasException": false,
      "ItemId": 0
    },
    {
      "ErrorCode": 0,
      "ErrorMessage": null,
      "FieldName": "Amount_x0020_in_x0020_Local_x002",
      "FieldValue": "125000",
      "HasException": false,
      "ItemId": 0
    },
    {
      "ErrorCode": 0,
      "ErrorMessage": null,
      "FieldName": "Match_x0020_Fee",
      "FieldValue": "25000",
      "HasException": false,
      "ItemId": 0
    },
    {
      "ErrorCode": 0,
      "ErrorMessage": null,
      "FieldName": "City",
      "FieldValue": "4;#Title",
      "HasException": false,
      "ItemId": 0
    },
    {
      "ErrorCode": 0,
      "ErrorMessage": null,
      "FieldName": "St",
      "FieldValue": "6;#State",
      "HasException": false,
      "ItemId": 0
    },
    {
      "ErrorCode": -2146232832,
      "ErrorMessage": "Invalid URL: 1234.",
      "FieldName": "Website_x0020_Link",
      "FieldValue": "1234",
      "HasException": true,
      "ItemId": 0
    },
    {
      "ErrorCode": 0,
      "ErrorMessage": null,
      "FieldName": "Id",
      "FieldValue": "0",
      "HasException": false,
      "ItemId": 0
    }
  ]
}
```
> **From the above we can see URL field level error message is:**
> 
```
    {
      "ErrorCode": -2146232832,
      "ErrorMessage": "Invalid URL: 1234.",
      "FieldName": "Website_x0020_Link",
      "FieldValue": "1234",
      "HasException": true,
      "ItemId": 0
    }
```
> **AND the Payload is**
```
--changeset_9978dc69-9b3a-47f6-89ab-275a7a524f6b Content-Type: application/http Content-Transfer-Encoding: binary POST
https://somespo.sharepoint.com/sites/group/_api/web/lists/getByTitle('Test%20Excel%20Import')/AddValidateUpdateItemUsingPath() HTTP/1.1 accept: application/json content-type: application/json;charset=utf-8

{
  "bNewDocumentUpdate": false,
  "formValues": [    
    {
      "FieldName": "Date_x0020_First_x0020_Played",
      "FieldValue": "10/23/2015"
    },
    {
      "FieldName": "Amount_x0020_in_x0020_Local_x002",
      "FieldValue": "125000"
    },
    {
      "FieldName": "Match_x0020_Fee",
      "FieldValue": "25000"
    },
    {
      "FieldName": "City",
      "FieldValue": "4;#Title"
    },
    {
      "FieldName": "St",
      "FieldValue": "6;#State"
    },
    {
      "FieldName": "Website_x0020_Link",
      "FieldValue": "1234"
    }
  ],
  "listItemCreateInfo": {
    "FolderPath": {
      "DecodedUrl": "https://somespo.sharepoint.com/sites/group/Lists/Test Excel Import"
    }
  }
}

```

**2. When a invalid Very Long URL is sent in the AddValidateUpdateItemUsingPath request using advanced batching, it is returning status code 500 and the list item is not added to the list which is working as expected.** 

> Example field value: 
> `"FieldValue": "SomeLongUrlWithAllTheQueryStringParametesAsWell"`
> 
> **Individual Response:**

```
--batchresponse_1c2c41f0-0401-4e2a-8b4a-4720e5c340d9
Content-Type: application/http
Content-Transfer-Encoding: binary
HTTP/1.1 500 Internal Server Error
CONTENT-TYPE: application/json;odata=minimalmetadata;streaming=true;charset=utf-8

{
  "odata.error": {
    "code": "-2130575328, Microsoft.SharePoint.SPException",
    "message": {
      "lang": "en-US",
      "value": "Invalid URL value.\n\nA URL field contains invalid data. Please check the value and try again."
    }
  }
}
```

> **AND the Payload is**
```
--changeset_9978dc69-9b3a-47f6-89ab-275a7a524f6b Content-Type: application/http Content-Transfer-Encoding: binary POST 
https://somespo.sharepoint.com/sites/group/_api/web/lists/getByTitle('Test%20Excel%20Import')/AddValidateUpdateItemUsingPath() HTTP/1.1 accept: application/json content-type: application/json;charset=utf-8

{
  "bNewDocumentUpdate": false,
  "formValues": [    
    {
      "FieldName": "Date_x0020_First_x0020_Played",
      "FieldValue": "4/3/2011"
    },
    {
      "FieldName": "Amount_x0020_in_x0020_Local_x002",
      "FieldValue": "653200"
    },
    {
      "FieldName": "Match_x0020_Fee",
      "FieldValue": "10000000"
    },
    {
      "FieldName": "City",
      "FieldValue": "3;#Title"
    },
    {
      "FieldName": "St",
      "FieldValue": "1;#State"
    },
    {
      "FieldName": "Website_x0020_Link",
      "FieldValue": "https://somespo.sharepoint.com/sites/group/Lists/Test%20Excel%20Import/AllItems.aspx?debugManifestsFile=https%3A%2F%2Flocalhost%3A3241%2Ftemp%2Fmanifests%2Ejs&loadSPFX=true&customActions=%7B%225dbeb41d%2De2a5%2D4716%2D894a%2D6bb8911545b3%22%3A%7B%22location%22%3A%22ClientSideExtension%2EListViewCommandSet%2ECommandBar%22%2C%22properties%22%3A%7B%22sampleTextOne%22%3A%22One%20item%20is%20selected%20in%20the%20list%22%2C%22sampleTextTwo%22%3A%22This%20command%20is%20always%20visible%2E%22%7D%7D%7D"
    }
  ],
  "listItemCreateInfo": {
    "FolderPath": {
      "DecodedUrl": "https://somespo.sharepoint.com/sites/group/Lists/Test Excel Import"
    }
  }
}
```
**3. List item is added successfully when I used a valid URL with same payload as above using advanced batching.**
> Example valid URL: https://somespo.sharepoint.com/sites/group/Lists/Test%20Excel%20Import/AllItems.aspx

### Steps to Reproduce

> 1. Create a list with URL field.
> 2. Send an advanced batch request to add list items to the list using AddValidateUpdateItemUsingPath()
> 3. Observe that list item is not added but the status code is 200 when a invalid short URL is sent. **This is not Expected.**
> 4. Observe that list item is not added but the status code is 500 when a invalid long URL is sent. **This is Expected.**
> 5. Observe that list item is added with the status code is 200 when a valid URL is sent. **This is expected.**

Thank you.

@patrick-rodgers

**Comment by juliemturner** [comment]
The library only passes through the errors that the api generates... I think, if I'm reading this correctly that you're saying the API returns 200 even though there are errors in the response, is that the issue? If so then this is not something this library can address and you would need to submit your issue to the sp-dev-docs issue list so that someone in engineering can comment on why the api returns 200 in that situation.

If I've misunderstood your issue and you're seeing that the call in the network tab of the browser, or by monitoring using fiddler or some other tool, shows that the API status code is an error and the library is then returning 200 then we can see if something is up.

**Comment by NewGHUser4321** [comment]
You understood it right. the API returns 200 even though there are errors in the response and the item is not added to the list.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
