### ISSUE TITLE
Using sendEmail with AdditionalHeaders param results in HTTP 400 error

### ISSUE THREAD

**Issue by LastGunslinger** [pnp/pnpjs#2253]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.2.0 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Using the sendEmail function with the AdditionalHeaders param should send an email without issue.

### Observed Behavior
Calling sendEmail with the AdditionalHeaders param results in the following error:

```
Error: Error making HttpClient request in queryable [400] Bad Request ::> {"odata.error":{"code":"-1, Microsoft.Data.OData.ODataException","message":{"lang":"en-US","value":"An unexpected 'StartObject' node was found when reading from the JSON reader. A 'StartArray' node was expected."}}}
```

This error does not occur when the AdditionalHeader param is omitted, and was not present in version 2.11.x

### Steps to Reproduce

This produces the error:
```javascript
import { spfi, SPFx } from '@pnp/sp'
import '@pnp/sp/sputilities'

const sp = spfi().using(SPFx(this.context))
sp.utility.sendEmail({
    To: ['user@email.com'],
    Body: 'TEST',
    Subject: 'Subject',
    AdditionalHeaders: { 'content-type': 'text/html' },  // This is taken directly from the docs
})
```

This, however, does not produce the error:
```javascript
import { spfi, SPFx } from '@pnp/sp'
import '@pnp/sp/sputilities'

const sp = spfi().using(SPFx(this.context))
sp.utility.sendEmail({
    To: ['user@email.com'],
    Body: 'TEST',
    Subject: 'Subject',
})
```

**Comment by patrick-rodgers** [comment]
Sure enough, that's a bug. Got it fixed and will be part of the 3.3.0 release. Thanks for letting us know!
