### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'zoneEmphasis')

### ISSUE THREAD

**Issue by ManuhinSPalath** [pnp/pnpjs#2254]
Category - Bug
PnP Version - 1.3.11
SharePoint targeting - SharePoint Online

Getting below error -
Webpart Error:  TypeError: Cannot read properties of undefined (reading 'zoneEmphasis')
    at ClientSidePage.5UI3.ClientSidePage.mergeColumnToTree (sp.es5.js:8518:1)
    at ClientSidePage.5UI3.ClientSidePage.setControls (sp.es5.js:8383:1)
    at ClientSidePage.5UI3.ClientSidePage.fromJSON (sp.es5.js:8061:1)
    at sp.es5.js:8073:1
    at e.invoke (chunk.2_7bf73534e6cc2e34ed8e.js:1:8348)
    at t.run (chunk.2_7bf73534e6cc2e34ed8e.js:1:3551)
    at chunk.2_7bf73534e6cc2e34ed8e.js:1:14998
    at e.invokeTask (chunk.2_7bf73534e6cc2e34ed8e.js:1:9032)
    at t.runTask (chunk.2_7bf73534e6cc2e34ed8e.js:1:4214)
    at m (chunk.2_7bf73534e6cc2e34ed8e.js:1:11299)

Code using - 
const file = sp.web.getFileByServerRelativePath(location.pathname);
const page = await ClientSidePage.fromFile(file);

file object received with correct url.
![image](https://user-images.githubusercontent.com/43960039/167416020-fb48ad43-f3a1-450d-b614-a00b4e697ec6.png)

Thank you.

**Comment by patrick-rodgers** [comment]
Hi @ManuhinSPalath - we are no longer supporting v 1 or 2. Is there anything blocking you from updating to the latest version?

**Comment by ManuhinSPalath** [comment]
Updated to latest version 3.2.0 and getting the below error while running gulp serve.

![image](https://user-images.githubusercontent.com/43960039/167611897-6ab4398b-19d1-4a09-bdb4-e9a67ced5646.png)

**Comment by ManuhinSPalath** [comment]
After resolving the above using @microsoft/rush-stack-compiler-4.2 getting below error:

"@pnp/sp"' has no exported member 'sp'.
"@pnp/sp"' has no exported member 'ClientSidePage'

**Comment by patrick-rodgers** [comment]
There are two versions of the transition guide you'll need to work through to update your code from version 1 to 3.

- [version 1 -> 2](https://pnp.github.io/pnpjs/v2/transition-guide/)
- [version 2 -> 3](https://pnp.github.io/pnpjs/transition-guide/)

Going to close this issue as answered, please work through updating your code and let us know if you encounter any issues not covered in the docs. Thanks!
