### ISSUE TITLE
How to check if the current user do not have permissions to delete at least one of the items in the list.

### ISSUE THREAD

**Issue by NewGHUser4321** [pnp/pnpjs#2255]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.2.0 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online]

### Question
I'm trying to check if the current user do not have permissions to delete at least one of the items in the list. 
To achieve this, I'm trying to get all the list items which have `HasUniqueRoleAssignments eq true` and then check if the user have delete permissions on each one of them?
I tried 
`sp.web.lists.getByTitle("listTitle").items.filter("HasUniqueRoleAssignments eq true").select("ID").top(50).getPaged()`

but getting error saying

> the column `HasUniqueRoleAssignments` does not exist or it might have been deleted by another user.

Can you help me on this?

Thank you,

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
