### ISSUE TITLE
Getting the file contents as base64

### ISSUE THREAD

**Issue by MarioZagreb** [pnp/pnpjs#2256]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.0.10 ]

Please specify what version(s) of SharePoint you are targeting: [  SharePoint Online  ]

### Question

Is it possible to get the file contents (PDF) as a base64 string from SP?

I tried using this:
var text = sp.web.getFileByServerRelativePath("/mypath/a.pdf").getText();

var base64 = btoa(unescape(encodeURIComponent(text)));

But, when I copy the contents of variable "base64" to online "Base64 to PDF converter", all I get is blank PDF.

How can I get file contents in base64 so I can send it to a web service so that web service on the other side can actually read that PDF?

**Comment by juliemturner** [comment]
I don't have a ready sample but if it were me I would use the [getBuffer method](https://pnp.github.io/pnpjs/sp/files/#reading-files) and then get base64 encoding from that... if you google buffer to base64 there are lots of examples.

**Comment by MarioZagreb** [comment]
I tried that, but it isn't working.
Actually, I don't know what exactly is the problem.

If I go to an online "PDF to base64", I get usable base64 of that PDF which I can send to other software which they can use.

But, when I read binary data from SP, I have this gibberish and I try to convert that to base64 and send to other software, that gibberish isn't useable.

What I have so far (my almost usable solution):
`$.ajax({  
      url: "https://mySPtenant.sharepoint.com/_api/web/getfilebyserverrelativeurl('/MyDocLib/" + fileName  +"')/openbinarystream",
      type: "GET",
      async:false,
      success: function(data, textStatus, xhr) 
      {
        console.log(data);
        // convert to base64
        var s = btoa(unescape(encodeURIComponent(data)));
        console.log(s);
      },  
      error: function r(xhr, textStatus, errorThrown) 
      {  
        alert("error:" + JSON.stringify(xhr));  
      }  
    }); `

In line
console.log(data);

I get something like:
%PDF-1.7
%����
2 0 obj
<<
/Metadata 4 0 R
/Pages 5 0 R
/Type /Catalog
>>
endobj
4 0 obj
<<
/Length 2979
/Subtype /XML
/Type /Metadata
>>
stream
<?xpacket beg...

In line  
console.log(s);

I get base64, but it isn't something that online "base64 to PDF" converter can convert to actual PDF. It can convert it back to gibberish I mentioned.

**Comment by MarioZagreb** [comment]
Ok, I managed to resolve this, but with jQuery.
It was necessary needed to remove async and define responseType, and then (in the success part) read file as blob and then convert it.

$.ajax({  
      url: "https://mySPtenant.sharepoint.com/_api/web/getfilebyserverrelativeurl('/MyDocLib/" + fileName  +"')/openbinarystream",
      type: "GET",
      // async:false,
      xhrFields: {
        responseType: 'blob' 
     },
      
      success: function(data, textStatus, xhr) 
      {
        var file = new Blob([(data)], {type: 'application/pdf'});
        var reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onloadend = function () {
          var base64String = reader.result;
},  
      error: function r(xhr, textStatus, errorThrown) 
      {  
        alert("error:" + JSON.stringify(xhr));  
      }  
    });
