### ISSUE TITLE
Small issue in documentation

### ISSUE THREAD

**Issue by Crossmax14** [pnp/pnpjs#2257]
Hi, you have a small issue in the documentation, which is most likely due to a problematic merge somewhere in the documentation files :)

![image](https://user-images.githubusercontent.com/34413296/167598619-078f9d08-4bed-43d2-9578-3c614e55a8e3.png)

### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [not applicable]

Please specify what version(s) of SharePoint you are targeting: [not applicable]

### Expected / Desired Behavior / Question
The text should probably look different

### Steps to Reproduce
Enter the [Site Groups - PnP/PnPjs](https://pnp.github.io/pnpjs/sp/site-groups/) page and go to the ISiteGroup section.

**Comment by patrick-rodgers** [comment]
Thanks - looks like @juliemturner fixed this a few days ago. Thanks for letting us know!
