### ISSUE TITLE
ISiteUserProps are not available using sp.web.siteUsers.getBy...

### ISSUE THREAD

**Issue by jagopauwels** [pnp/pnpjs#2259]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.2.0]

Please specify what version(s) of SharePoint you are targeting: [1.14.0]

### Expected / Desired Behavior / Question
Using `sp.web.siteUsers.getByLoginName("xyz")`, the expected return object ISiteUser should give access to the properties defined in ISiteUserProps.

### Observed Behavior
In contrary to `sp.web.currentUser()`, the returned object of `sp.web.siteUsers.getByLoginName("xyz")` does not have access to the properties. This is also the case with the other `sp.web.siteUsers.getBy...(...)` methods.

### Steps to Reproduce
```
import { spfi } from "@pnp/sp";
import { ISiteGroupInfo, ISiteUserInfo } from "@pnp/sp/presets/all";
import "@pnp/sp/webs";
import "@pnp/sp/site-users/web";
[...]
let currentUser = await sp.web.currentUser();
currentUser.Title; // Works
let userByLoginName = await sp.web.siteUsers.getByLoginName("xyz");
userByLoginName.Title; // Property 'Title' does not exist on type 'ISiteUser'.ts(2339)
```

**Comment by patrick-rodgers** [comment]
Different methods return different default properties from the server. I did a quick test though, and currentUser, getByLoginName, and getById all return "Title".

I think the issue is you need to execute the request:

```TS
let userByLoginName = await sp.web.siteUsers.getByLoginName("xyz")();
```

This allows you to select props before executing the request:

```TS
let userByLoginName = await sp.web.siteUsers.getByLoginName("xyz").select("Title")();
```

**Comment by patrick-rodgers** [comment]
And I just checked the docs and they are wrong so will get those updated.
