### ISSUE TITLE
error: associatedOwnerGroup is not a function

### ISSUE THREAD

**Issue by jagopauwels** [pnp/pnpjs#2261]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.2.0]

Please specify what version(s) of SharePoint you are targeting: [1.14.0]

### Expected / Desired Behavior / Question
According to the documentation `const ownerGroup = await sp.web.associatedOwnerGroup();` should work

### Observed Behavior
I get `Uncaught TypeError TypeError: sp.web.associatedOwnerGroup is not a function`
Is this a bug? Or am I using the function incorrectly?

### Steps to Reproduce
```
import { spfi, SPFx } from "@pnp/sp";
import { ISiteGroupInfo, ISiteUserInfo } from "@pnp/sp/presets/all";
import "@pnp/sp/webs";
import "@pnp/sp/site-users/web";
[...]
const sp = spfi().using([...]);
const test = (await sp.web.currentUser()).Title;
console.log(test); // Works

const ownersGroup = await sp.web.associatedOwnerGroup(); // Error
```

**Comment by juliemturner** [comment]
I'm fairly sure you have an issue with your imports... you need
`import "@pnp/sp/site-groups/web";`
And also, I would suggest you import ISiteGroupInfo and ISiteUserInfo from their locations vs presets/all

**Comment by jagopauwels** [comment]
Hi Julie, thank you for your reply. I indeed mistook the import "@pnp/sp/site-users/web" for "@pnp/sp/site-groups/web".
After changing this everything works perfectly.
