### ISSUE TITLE
addFolder results in error: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by Xunrel** [pnp/pnpjs#2262]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.2.0]

Please specify what version(s) of SharePoint you are targeting: [ SP Online, SPFx 1.14.0 & graph ]

### Expected / Desired Behavior / Question
When I try to add a folder to onedrive given the following code (from within an SPFx webpart):
```
const graph = graphfi().using(graphSPFx(this.context));
const folderAddResult = await graph.me.drives.getById(defaultDrive.id).root.children.addFolder(
  "My new folder"
);
```
I would expect to have created a new folder named "My new folder" within my onedrive

### Observed Behavior
I get the error
`Error: Unhandled Exception: TypeError: Failed to construct 'URL': Invalid URL`

getting the default drive via graph.me.drive() or getting all graph.me.drives() works without issues

### Steps to Reproduce
```
const graph = graphfi().using(graphSPFx(this.context));
const folderAddResult = await graph.me.drives.getById(defaultDrive.id).root.children.addFolder(
  "My new folder"
);
```

Further notices:
This is an SPFx app which is mainly used within Teams as an Personal Teams App.
I also set the scope to Files.ReadWrite.

**Comment by juliemturner** [comment]
So, not exactly sure, your code example isn't really complete so I'm not sure what you're doing to get `defaultDrive.id`.

I tested this:
`conse folderAddResults = await graph.users.getById({user id}).drive.root.children.addFolder("My new folder");`

and this:
`const folderAddResults = await graph.me.drive.root.children.addFolder("My new folder");`

and both executed fine.  If you could provide a more complete example I might be able to figure out what's wrong.

**Comment by Xunrel** [comment]
Thanks for responding and sorry for the incomplete code 😰

But it's actually not far off. I just separated it:
```
const defaultDrive = await graph.me.drive();
const folderAddResults = await graph.me.drives.getById(defaultDrive.id).root.children.addFolder("My new folder");
```

**Comment by juliemturner** [comment]
Ok, i think I see the issue... thanks for the additional detail.
