### ISSUE TITLE
All Sites in Tenant

### ISSUE THREAD

**Issue by amirmsai** [pnp/pnpjs#2263]
Hi all, 
it's not possible to return all Sites from Tenant using pnp/js + ad Token. Receive only sites where the user have permissions.
Any Idea ?
Thanks

**Comment by juliemturner** [comment]
You will need to look into using search (either SharePoint or Microsoft) for this as it'll security trim the sites for the user context you're running it for.

It would be too big of a task for me to do this job for you, but I can get you started by pointing you to the following information:
- SharePoint Search: https://pnp.github.io/pnpjs/sp/search/
- Microsoft Search via the Graph: https://pnp.github.io/pnpjs/graph/search/
   - Graph documentation for search (PnPjs is only a proxy): https://docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0

**Comment by amirmsai** [comment]
@juliemturner Graph Search dont return all sites in tenant.
the admin can only return sites where he has permission.

**Comment by juliemturner** [comment]
You said:
>Receive only sites where the user have permissions.

So, I took that as you wanted a list of sites under the current user's context... 

If you want all the sites in the tenant all up that's a completely different task, and PnPjs doesn't support it currently.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
