### ISSUE TITLE
Error installing pnp/sp@3.3.1 on MacOS

### ISSUE THREAD

**Issue by Goncaloo42** [pnp/pnpjs#2271]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [@pnp/sp@3.3.1]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
Install PnPjs packages on MacOS. (https://pnp.github.io/pnpjs/)

### Observed Behavior
When installing the **@pnp/sp@3.3.1** dependency on MacOS, an error occurs when running the postinstall script. 
No package.json file is found on path **'/project/example/path/test\\\package.json'** (check image below)
![Captura de ecrã 2022-05-18, às 11 45 33](https://user-images.githubusercontent.com/24626264/169023168-84dba4bc-38e5-41fc-b009-7cb5307b1a7e.png)

post-install.cjs (https://github.com/pnp/pnpjs/blob/version-3/packages/sp/post-install.cjs)
<img width="1210" alt="Captura de ecrã 2022-05-18, às 11 57 37" src="https://user-images.githubusercontent.com/24626264/169023534-79af9edd-03cf-46de-8c8d-cc7ecac0979f.png">

**Comment by patrick-rodgers** [comment]
Shoot, ok, thanks for letting us know. We'll try and get another patch out shortly to resolve this. Sorry about that. You can for now install with:

```
npm install @pnp/sp --ignore-scripts
```

**Comment by patrick-rodgers** [comment]
@Goncaloo42 - just published 3.3.2 that we believe fixes this, can you verify?

**Comment by Goncaloo42** [comment]
@patrick-rodgers - just tested again and everything is working as expected! Thank you!

**Comment by juliemturner** [comment]
Thanks all, sorry for the issues.
