### ISSUE TITLE
sp.utility.sendEmail occasionally does not send email, without exception

### ISSUE THREAD

**Issue by carletto75** [pnp/pnpjs#2275]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ "^1.3.9" ]

Please specify what version(s) of SharePoint you are targeting: [Sharepoint online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
My webpart uses sp.utility.sendEmail() to send html email to small (1-5) groups of users in my organization.
Hundreds of emails are successfully sent.
Occasionally, some email does not arrive (about 1 on 15) but no error or exception is caught.

### Observed Behavior
I would like all email are sent, or an exception is thrown.

### Steps to Reproduce
my code (fails about 1 on 15, or less):

`try{
      const email:EmailProperties = {
              To:['INTERNAL_EMAIL_ADDRESS'],
              Body:'LONG HTML STRING',
              Subject: 'SIMPLE STRING',
          }
      sp.utility.sendEmail(email).then(()=>{
          console.log("email sent:" + email.Subject);
          resolve();
      }).catch(reason=>{
          console.log('email NOT sent, reason: ' + JSON.stringify(reason));  //NEVER ENTER HERE, EVEN IF EMAIL DOES NOT ARRIVE
          reject();
      });
  } catch(ex) {
      console.log(ex); //NEVER ENTER HERE, EVEN IF EMAIL DOES NOT ARRIVE
  }`

I know that email does not attive because I monitor recepient box, spam, ecc.
If make a new try with exactly same HTML body, Subject, etc.. the email arrives.

**Comment by juliemturner** [comment]
I'm sorry but the issue you're having isn't really related to PnPjs library but SharePoint. If the REST call is successfully being made, which you're indicating it is, if the emails are sent or not is not something the library can control, it is simply a proxy for making those RESTful calls to trigger the process.

**Comment by carletto75** [comment]
Yes, that's what I was thinking.
May ever happen, with my version of the library, that sharepoint Rest service throws an exception and the library sees everything successful ?

**Comment by juliemturner** [comment]
No, if the REST endpoint throws and exception than that exception would pass through.

**Comment by carletto75** [comment]
Thank you for your response.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
