### ISSUE TITLE
SchedulePublish Date

### ISSUE THREAD

**Issue by tukutela** [pnp/pnpjs#2278]
Not sure if this is an Issue, its something I would really use but not yet available in the library so I wouldn't call it an issue. 

According to [clientsite-pages/types.ts#schedulePublish](https://github.com/pnp/pnpjs/blob/907c5d194851d2a08e2130cfa95e859881676f10/packages/sp/clientside-pages/types.ts#L699) this method is not yet available, any chance of any update? We'd really love to be able to do this.

**Comment by tukutela** [comment]
awesome! thanks @juliemturner will play with next week.

**Comment by juliemturner** [comment]
The nightly build from last night will also have it included if you want to use it now.
