### ISSUE TITLE
Missing Import From Update Multiple Items Documentation

### ISSUE THREAD

**Issue by 6gal6ler6** [pnp/pnpjs#2279]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Version 3

### Expected

The following documentation has a missing import on its example https://pnp.github.io/pnpjs/sp/items/#update-multiple-items

### Documentation Section

--------

### Update Multiple Items

This approach avoids multiple calls for the same list's entity type name.

```TypeScript
import { spfi } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/batching"; //this is the missing import

const sp = spfi(...);

const [batchedSP, execute] = sp.batched();

const list = batchedSP.web.lists.getByTitle("rapidupdate");

list.items.getById(1).update({ Title: "Batch 6" }).then(b => {
  console.log(b);
});

list.items.getById(2).update({ Title: "Batch 7" }).then(b => {
  console.log(b);
});

// Executes the batched calls
await execute();

console.log("Done");
```
--------

**Comment by juliemturner** [comment]
Thanks, I fixed the oversight.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
