### ISSUE TITLE
convert SharePoint online .aspx page to .pdf

### ISSUE THREAD

**Issue by iamrealvinod** [pnp/pnpjs#2282]
### Category
- [x] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Expected / Desired Behavior / Question
Is it possible to convert the .aspx SharePoint online page to pdf using only pnpjs and without the use of third-party tools?

**Comment by koltyakov** [comment]
This is not what SharePoint API provides. However, you can achieve this by sending page print command and choosing print to PDF. Or using PDF.js and crafting the layout. Also an automation with a headless browser like Puppeteer or Playwright on a server might solve what you need.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
