### ISSUE TITLE
How can i have types definitions on V3

### ISSUE THREAD

**Issue by tioger** [pnp/pnpjs#2288]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

PnpVersion : 3.3.2    

SharePoint  targeted: online  

Typescript :  4.7.0-dev.20220223

### Expected / Desired Behavior / Question
When i use the node sample for v3 i dont have types for all pnp libraries.
![image](https://user-images.githubusercontent.com/11294405/171010031-d964473c-3b83-4121-83c1-4b32304ae548.png)
I miss something ?

### Steps to Reproduce
download and npm install this sample
[Sample link](https://github.com/pnp/pnpjs/tree/version-3/samples/nodejs-commonjs)

**Comment by juliemturner** [comment]
> i dont have types for all pnp libraries.

I don't really follow the question.

**Comment by patrick-rodgers** [comment]
The types are included in the package. Did a quick test and everything works as expected for me using your code above. We have no plans to publish a separate typings package. As silly as it sounds, sometimes closing and reopening vs code will resolve this type of thing.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
