### ISSUE TITLE
Proxy undefined on IE10

### ISSUE THREAD

**Issue by SpliceVW** [pnp/pnpjs#229]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.1]

### Expected / Desired Behavior / Question
Can create a SearchQueryBuilder instance on IE10.

### Observed Behavior
Throws exception `"ReferenceError: 'Proxy' is undefined`.

### Steps to Reproduce

1. Create a new SearchQueryBuilder instance
2. Execute sp.search(<builderHere>)

**Comment by SpliceVW** [comment]
Appears to be caused by commit b1d6bed96fa41f2e6ed110ff2880b85be6ba2fa2. [Proxy doesn't exist on IE10](https://caniuse.com/#feat=proxy), so if you're going to continue to use it then should it be another documented polyfill (like Fetch and Promise)?

**Comment by SpliceVW** [comment]
You target IE11 and SP2013 though, right? Because SP2013 gives the directive that pages should load in IE10 compatibility mode, hence why I mentioned IE10, but [Proxy is similarly not implemented in IE11](https://caniuse.com/#feat=proxy).

**Comment by SpliceVW** [comment]
It still does not work with using [Google's proxy polyfill](https://github.com/GoogleChrome/proxy-polyfill). The constructor method works but the resulting object is missing all of its methods (e.g. `RowLimit`).

Per this [StackOverflow article](https://stackoverflow.com/questions/45285992/es6-proxy-polyfill-for-ie11):

> Proxies require support on the engine level and it is not possible to polyfill Proxy.

So, as a workaround, I'm just avoiding `SearchQueryBuilder` in its entirety.

**Comment by patrick-rodgers** [comment]
Please have a look at #246 and let us know if that makes things more clear. Thanks!

**Comment by patrick-rodgers** [comment]
Going to close this based on the updated article that now calls out the limitations with older browsers.
