### ISSUE TITLE
How to get list of users and their permissions on a list item?

### ISSUE THREAD

**Issue by thinkdaniel** [pnp/pnpjs#2299]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  3.2.0  ]

Please specify what version(s) of SharePoint you are targeting: [ Online  ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

To read list of users and their permissions on a list item.

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

An error is thrown saying `roleAssignments` is not available on item.  The documentation says it should work on any securable (https://pnp.github.io/pnpjs/sp/permissions/).

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

```
const response = await sp.web.lists
  .getByTitle("MyList")
  .items.getById(1)
  .roleAssignments();
```

**Comment by juliemturner** [comment]
And you've validated that you have the correct imports, specifically

```ts
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/security";
```

**Comment by thinkdaniel** [comment]
Thanks Julie, I missed that!
