### ISSUE TITLE
RenderListDataOptions-Enum is a bit outdated for RenderListDataAsStream

### ISSUE THREAD

**Issue by Mulando** [pnp/pnpjs#2310]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.3.2 ]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
The RenderListDataOptions is no longer up to date. The Enum only contains flags up to 32768 (ClientSideComponentManifest). 

### Observed Behavior
 The Problem that now occurs is, that values in the result get no longer translated (e.g. Managed Metadata fields in the result)  if you are just used "ListData" (2). That seem to have changed in SharePoint Online in the last few month.

I fixed the issue in my code by looking at how SharePoint calls the RenderListDataAsStream method. It seems that the flags has been updated on SharePoint side as SharePoint set the Options to 5707527 (010101110001011100000111) which is way higher than the current Enum allows.

If I now send 
RenderOptions: 5701632 | RenderListDataOptions.ListData
(binary: 010101110000000000000010; only the unknown values + the "ListData"-flag)
Managed Metadata fields in the result are translated again.
Problem is, I don't know what those flags mean and the official documentations (https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.client.renderlistdataoptions?view=sharepoint-csom) does also not provide any information about the new flags.

Maybe someone here has more insights into what the flags above 32768 mean. At least it might be a good idea to include it in the documentation as known issue or something like this.

### Steps to Reproduce
You need a List with a Managed Metadata field which allows multiple languages. And a user that has another default language.
Just make a simple search for all listitems in the list while the Managed Metadata field is in the default view.
list.renderListDataAsStream({ RenderOptions: RenderListDataOptions.ListDataa }

The result of the Managed Metadata field should no longer be translated :(

Btw, the "accept-language" header must also be set. Without the header it won't translate and without the undocumented flags it also won't translate.

**Comment by patrick-rodgers** [comment]
I updated the options class and the enum, as well I added code comments where I could find the information. You can check it out in the [PR](#2320). None of those options are "translate these fields" so you'll need to play around with it. As well for the header, that's something you'd need to add to the request using [InjectHeaders](https://pnp.github.io/pnpjs/queryable/behaviors/#injectheaders) behavior. Changes will be in a [nightly build](https://pnp.github.io/pnpjs/concepts/nightly-builds/) tomorrow if you want to try them out.
