### ISSUE TITLE
no way to read the FileRef / EncodedAbsUrl  value of the document 

### ISSUE THREAD

**Issue by techakki81** [pnp/pnpjs#2311]
while using pnp ver 3 to talk to a sharepoint library  these two function do not return the url to the document(s) 

sp.web.lists.getByTitle("someDocumentName").getItemsByCAMLQuery
sp.web.lists.getByTitle("someDocumentName").items

tried setting this in the ViewXml property but still no url is returned 
<ViewFields> <FieldRef Name='Title' /> <FieldRef Name='EncodedAbsUrl' />  <FieldRef Name='FileRef' /></ViewFields>

**Comment by koltyakov** [comment]
It's not expected to have FileRef in items response by default, until explicitly selected `.select('FileRef')`.

**Comment by techakki81** [comment]
Thanks !! that did the trick :-) 
Though me wonders why not respect the ViewFields node of CAML query in  getItemsByCAMLQuery method. 
Any idea how to achieve this via camlQueryMethod?

**Comment by koltyakov** [comment]
Please check this approach https://github.com/pnp/pnpjs/issues/383#issuecomment-442478856

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
