### ISSUE TITLE
Unable to Like a Comment in Events list using PnPJs

### ISSUE THREAD

**Issue by chaitanya-SharePoint** [pnp/pnpjs#2313]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Bug

### Version

[2.10.0 ]

[SPOnline]

### Expected / Desired Behavior / Question
*User should be able to like the comments of an Events list item*
*Same is working with other lists.

### Observed Behavior
*Unable to like a comment of an item in the Events list.*

### Steps to Reproduce
```
import { sp } from "@pnp/sp/presets/all";

(async () => {

  const item = await sp.web.lists.getByTitle('Events').items.getById(1);
  const comm = await item.comments.getById(1);
  await comm.like();
})().catch(console.log)
```

####Error
```
Error: Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-1, System.InvalidOperationException","message":{"lang":"en-US","value":"Operation is not valid due to the current state of the object."}}}
    at new HttpRequestError (sp.es5.umd.bundle.js:2284:28)
    at Function.eval (sp.es5.umd.bundle.js:2299:47)
    at step (sp.es5.umd.bundle.js:1811:23)
    at Object.eval [as next] (sp.es5.umd.bundle.js:1792:53)
    at fulfilled (sp.es5.umd.bundle.js:1782:58)
```

**Comment by juliemturner** [comment]
So, first I would suggest you reconsider using the presets/all import... but putting that aside...

you need to invoke your requests... try this...
```ts
const item = await sp.web.lists.getByTitle('Events').items.getById(1)();
const comm = await item.comments.getById(1)();
await comm.like();
```

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.

**Comment by chaitanya-SharePoint** [comment]
@juliemturner : Thanks for your response. Even afer invoking the requests. It is failing. Please let me know if you are able to like the Comments in the Events list with the same code that you provided.

**Comment by juliemturner** [comment]
Um, it doesn't seem like it's possible to like an item comment... https://support.microsoft.com/en-us/office/add-and-reply-to-comments-in-list-items-9407aab9-6d43-4756-af72-d38177814a6e

I can see where you like page comments but not item ones, do you have contrary information?

**Comment by chaitanya-SharePoint** [comment]
**Use Case**: User should be able to like the comment of a list item (it can be page comments/list item comment/events list item comments).
1. I'm able to like a comment of  a regular list item
![image](https://user-images.githubusercontent.com/28508253/173670149-44e54dba-37aa-4dbf-8bcb-8749328fe70f.png)
![image](https://user-images.githubusercontent.com/28508253/173670070-301eb3ff-71ba-4907-ae81-fd0d71adce93.png)

2. I'm not able to like a comment of a Events list item using same code.
![image](https://user-images.githubusercontent.com/28508253/173670510-b699f97b-f5bf-4492-b72b-3d54a454bed3.png)
![image](https://user-images.githubusercontent.com/28508253/173670546-3a15dfd8-af27-40c9-a1c5-ea2988aaa064.png)

Is this because Events are not modern yet? Any insights would be really appreciated.

**Comment by juliemturner** [comment]
What do you mean:
 > I'm able to like a comment of a regular list item

Does that mean that the code runs without error or that somewhere in the UI it actually shows that the item was liked, because I cannot find any documentation etc that shows you can like an Item, if you can great, I just don't see it and your screen shot is not showing me how it's actually manifesting in the UI.

Regardless, yeah I would suspect that if indeed you are able to like a comment on an item the reason you can't on an event list is because it's not modern.

**Comment by chaitanya-SharePoint** [comment]
@juliemturner : I meant, I was able to like a Custom list item's comment but not Event list item's comment.

Thank you so much for your prompt response @juliemturner. 👍
