### ISSUE TITLE
Typescript examples

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#2314]
Is it possible to have the examples with fully typed statements? 
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   3.4.0]

I am using SPFx 1.15 RC1 and Eslint shows all the missing types.
For example:
```
const file = await projWeb.getFileByServerRelativePath(`UserUploads`).files.addChunked
```
Requires that file will have a type.  I guessed it was 'IFileAddResult' so:
```
const file:IFileAddResult = await projWeb.getFileByServerRelativePath(`UserUploads`).files.addChunked
```
But then it errors with "Property 'files' does not exist on type 'IFile'."  
How do I select the right type then?

Thank you much

**Comment by juliemturner** [comment]
Can you please provide a more complete example of the issue?
e.g. addChunked is a method not a property... and what imports have you included?

**Comment by Ofer-Gal** [comment]
I should have used .getFolderByServerRelativePath for .files.addChunked to work. But I still have an issue with:
```
const fileAddResult:IFileAddResult = await projWeb.getFolderByServerRelativePath(`/teams/${projectNumber}/UserUploads/`).files.addChunked(fixFileName, blob, data => {
	setcurrentMessage(`Wait,  part #${data.blockNumber} of ${chunks}`);
	setPercentComplete(((data.blockNumber / chunks))); 
}, false);
```
Eslint is OK with it now. But at run time, It returns:"Error:Cannot read properties of undefined (reading 'addChunked')" 
I checked and there is a library in URL https://ecgmcdev.sharepoint.com/teams/0100.017/UserUploads/

Can you tell what can be wrong with it?
The point was that we mostly use TypeScript so I would love for the examples in the documentation to be TypeScript with types.

Thank you for answering so early on a Saturday :-)

**Comment by Ofer-Gal** [comment]
Got it!
```
            const myFolder: IFolder = projWeb.getFolderByServerRelativePath("UserUploads");
            const fileAddResult:IFileAddResult = await myFolder.files.addChunked(fixFileName, blob, data => {
                setcurrentMessage(`Wait,  part #${data.blockNumber} of ${chunks}`);
                setPercentComplete(((data.blockNumber / chunks))); //(data.blockNumber / chunks) * 100
            }, false);
```
Worked now :-)
I also stand corrected, https://pnp.github.io/pnpjs/sp/files/#adding-files does give Typescript example.
Thank you much
