### ISSUE TITLE
Graph Orderby : Syntax error: character '%' is not valid at position 8 in 'lastUsed%2FlastAccessedDateTime desc'."

### ISSUE THREAD

**Issue by raclettierer** [pnp/pnpjs#2316]
### Category
- [ ] Enhancement
- [ x ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   V 3.3.2      ]

Please specify what version(s) of SharePoint you are targeting: [    V 1.14     ]

### Expected / Desired Behavior / Question
When I request the lastUsed sites it works fine but when I add orderby I get an error. Maybe the lash escaping is wrong

**message: "Syntax error: character '%' is not valid at position 8 in 'lastUsed%2FlastAccessedDateTime desc'."**

Working
getGraph().me.insights.used.filter(`ResourceVisualization/containerType eq 'Site'`).top(40)() 

Error 
getGraph().me.insights.used.filter(`ResourceVisualization/containerType eq 'Site'`).top(40).orderBy('**lastUsed/lastAccessedDateTime**', false)();

Generated URL : https://graph.microsoft.com/v1.0/me/insights/used?$filter=ResourceVisualization/containerType eq 'Site'&$top=40&$orderby=lastUsed%2FlastAccessedDateTime desc

### Observed Behavior
https://graph.microsoft.com/v1.0/me/insights/used?$filter=ResourceVisualization/containerType eq 'Site'&$top=40&$orderby=lastUsed/lastAccessedDateTime desc

**Comment by juliemturner** [comment]
Tonight's [nightly build](https://pnp.github.io/pnpjs/concepts/nightly-builds/) will most likely fix this issue as it seems to be fixed in my initial testing. Please feel free to test it out yourself pre the 3.5 release happening in early July. I'll be doing more testing in the next few days and trying to expand out testing to address the issue.

**Comment by juliemturner** [comment]
@raclettierer -- It appears that the encoding is correct now, sadly I can't test this because for me even in graph explorer that query is a bad request... so if you could confirm by testing out the nightly build that would be wonderful.
