### ISSUE TITLE
Is it possible to refresh the page content with out reloading/refreshing modern page. 

### ISSUE THREAD

**Issue by pavan2920** [pnp/pnpjs#232]
Hi, 

Added a webpart in the modern page using the below 
**Reference : Unable to add "News" webpart grammatically in modern page. #214**

Is it now possible to refresh the page content after adding this webpart to the page without refreshing/reloading the page. 

Thanks & Regards, 
Pavan.

**Comment by koltyakov** [comment]
@pavan2920, 

Not sure that it's quite relevant to the REST API. As I understood, you're opening a page, detecting that a web part should be added, adding it via PnPjs and then desire to refresh the page's content area only?

Modern UI has the partial page load feature, not sure that it's exposed for customizations, it's better to ask here https://github.com/SharePoint/sp-dev-docs

**Comment by pavan2920** [comment]
Thanks @koltyakov, let me post a question here - https://github.com/SharePoint/sp-dev-docs.

**Comment by patrick-rodgers** [comment]
Going to close the issue, seems like it doesn't directly tie to the library. If needed please _reopen_ to continue discussion. Thanks!
