### ISSUE TITLE
Mission drive.special functionality in graph

### ISSUE THREAD

**Issue by raclettierer** [pnp/pnpjs#2323]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  3.4.1-v3nightly.20220614       ]

Please specify what version(s) of SharePoint you are targeting: [     SPFX 1.14    ]

### Expected / Desired Behavior / Question
Try to request **special** drive via graph, but interface is not available

getGraph().me.drive.**special**

I like to implement the application's personal folder.
`GET https://graph.microsoft.com/v1.0/me/drive/special/approot:/settings.json:/content`

`PUT https://graph.microsoft.com/v1.0/me/drive/special/approot:/settings.json:/content`
`content-type: text/plain`
`authorization: Bearer abc`

Explaind by waldek in this article
https://blog.mastykarz.nl/easiest-store-user-settings-microsoft-365-app/

**Comment by juliemturner** [comment]
Added this and will be available in tonight's nightly build.
