### ISSUE TITLE
Uploading multiple attachments to sp list item resuts in [409] "Save conflict"

### ISSUE THREAD

**Issue by erickalves-05** [pnp/pnpjs#2324]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.4.1 ]

Please specify what version(s) of SharePoint you are targeting: [ Online ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Expected to upload multiple files like the old ```.addMultiple``` method.

### Observed Behavior
Using a loop to upload multiple files to a SP list item results in [409] "Save conflict" after the first file is uploaded.

### Steps to Reproduce
```
let list = this._sp.web.getList(`${this._spWebUrl}/Lists/Events`);

let iar: IItemAddResult = await list.items.add({
    Status: "Pending"
});

await Promise.all(attachments.map(async (attachment) => {
    await iar.item.attachmentFiles.add(attachment.File.name, attachment.File);
}))
```

Should I re-query the item for each file?

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
