### ISSUE TITLE
Filter SharePoint List Items for Target Audiences

### ISSUE THREAD

**Issue by tpf89** [pnp/pnpjs#2332]
### Category
- [x] Enhancement
- [x] Question

### Version

Please specify what version of the library you are using: [ 2.13.0 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

### Expected / Desired Behavior / Question
Is it possible to filter for List Items in a List via Target Audiences, using pnp/js? I enabled Target Audiences support in my list and added a Target Audiences column. 

If I am using the Highlighted Content webpart and activate Target Audiences, it will use the following KQL Query: 
`(ModernAudienceAadObjectIds:{User.Audiences} OR NOT IsAudienceTargeted:true)`

But afaik you can only use KQL via the search, but not in a normal SP List Item query. Any ideas? Future plans to add Target Audiences support in pnp/js?

Thanks in advance!

**Comment by juliemturner** [comment]
You can get the value of the Audience Target for a list (assuming it's enabled) by selecting the `OData__ModernAudienceTargetUserFieldId` field. If it has a value, it's an array of SharePoint user id's that you can look up in the siteUsers method of the web. In my quick attempt it doesn't seem that this field is expandable like a normal user column... but I could have just not taken enough time to get it right.

`const w = await sp.web.lists.getByTitle("pnplist").items.select("OData__ModernAudienceTargetUserFieldId")();`

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
