### ISSUE TITLE
implement missing folder getchanges

### ISSUE THREAD

**Issue by mdissel** [pnp/pnpjs#2336]
### Category
- [X ] Enhancement

### Version

3.*

### Desired Behavior

Implement the getChanges method for a folder object, exactly the same as for a List object. 
see the CSOM documentation https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/mt829510(v=office.15)

**Comment by juliemturner** [comment]
A folder is an item... have you tried anything yet? 

I would suspect getting the item for the folder and then getting changes for that is what you're looking for: https://pnp.github.io/pnpjs/sp/folders/#getitem

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
