### ISSUE TITLE
pnp sp batching module not found

### ISSUE THREAD

**Issue by idrtabd** [pnp/pnpjs#2338]
### Category
- [x] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   3.4.1    ]

Please specify what version(s) of SharePoint you are targeting: [   not applicable, node js script wont load modules      ]

### Expected / Desired Behavior / Question
I'm expecting that @pnp/sp/batching import works.  I'm referencing https://pnp.github.io/pnpjs/concepts/batching/
### Observed Behavior
My other @pnp imports resolve, they are also present in the node_modules folder.  However, batching is not in my local  node_modules folder.  I also see it's not in the git repo - https://github.com/pnp/pnpjs/tree/version-3/packages/sp

import { spfi } from "@pnp/sp";
import * as webs from "@pnp/sp/webs/index.js";
import * as lists from "@pnp/sp/lists/index.js";
import * as items from "@pnp/sp/items/index.js";
import * as batching from "@pnp/sp/batching";

**Comment by juliemturner** [comment]
I am not seeing any issues... and the file is here: https://github.com/pnp/pnpjs/blob/version-3/packages/sp/batching.ts
