### ISSUE TITLE
Node.js: addChunked-Error 'safe_global_js_1.safeGlobal.fetch is not a function'

### ISSUE THREAD

**Issue by meierdean** [pnp/pnpjs#2339]
### Category
- [ ] Enhancement
- [X] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.11.0]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

### Expected / Desired Behavior / Question
Hi,
I'm working with different SharePoint-Tenants and therefor I am using different isolatedRuntimes (sp). This works fine for all used functions except the "addChunked"-function. When I try to add a file to a specific folder, I get the following error:
`safe_global_js_1.safeGlobal.fetch is not a function`. I think the library tries to fetch the clientfactory from the global setup instead of the isolatedRuntime. As i mentioned above, I work with different SharePoint-Tenants and this is why I haven't setup a global instance/configuration. 

Is there a possible workaround for this issue?

Thank you for your feedback!

**Comment by juliemturner** [comment]
I could be that there is a bug.  Isolated Runtimes in v2 were a bit of a shoehorn and never felt like they worked as well as they could have, which is one of the fundamental reasons we rewrote the internals of the library for v3 which is much more suited to handle the scenario you're working on. Long story short, we are no longer actively supporting v2 of the library. However, if you can find the issue and would like to submit a PR we would merge and publish a new v2 version.

**Comment by patrick-rodgers** [comment]
Hi @meierdean - is there something preventing you from updating to v3? Missing functionality? v3 is so far pretty stable and folks seem to have not too much trouble updating, we as well have the [transition guide](https://pnp.github.io/pnpjs/transition-guide/) to assist there.

If you can't provide a PR then we won't update v2 as per our policy. I understand you'd like us to do this for you and continue to support the older version, but we just don't have the person power to cover everything.

**Comment by juliemturner** [comment]
A version 2 release with this fix was done today, thank you for your contribution.
