### ISSUE TITLE
Error while building a project with the latest version

### ISSUE THREAD

**Issue by SwagiWagi** [pnp/pnpjs#2340]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.4.1 ]

Please specify what version(s) of SharePoint you are targeting: [ Sharepoint 2013 ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

I get the error when building my app.

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

Running npx tsc, getting the following error:
node_modules/@pnp/queryable/queryable.d.ts:18:52 - error TS2344: Type '{ readonly pre: (observers: QueryablePreObserver[], url: string, init: RequestInit, result: any) => Promise<[url: string, init: RequestInit, result: any]>; ... 4 more ...; readonly data: (observers: QueryableDataObserver<...>[], ...args: any[]) => void; }' does not satisfy the constraint 'Moments'.
  Property 'pre' is incompatible with 
index signature.
    Type '(observers: QueryablePreObserver[], url: string, init: RequestInit, result: any) => Promise<[url: string, init: RequestInit, result: any]>' is not assignable to type '(this: Timeline<any>, handlers: ValidObserver[], ...args: any[]) => void'.
      Types of parameters 'observers' 
and 'handlers' are incompatible.      
        Type 'ValidObserver[]' is not 
assignable to type 'QueryablePreObserver[]'.
          Type 'ValidObserver' is not 
assignable to type 'QueryablePreObserver'.
            Type 'ObserverAction' is not assignable to type 'QueryablePreObserver'.
              Type 'void' is not assignable to type 'Promise<[string, RequestInit, any]>'.

18 export declare class Queryable<R> extends Timeline<typeof DefaultMoments> implements IQueryableInternal<R> {   
   
~~~~~~~~~~~~~~~~~~~~~ 

Found 1 error in node_modules/@pnp/queryable/queryable.d.ts:18

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*
npm i @pnp/js
npx tsx

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
Based on the fact you are targeting SP2013 I am not 100% certain what you are trying to do. Can you share a project we can clone that shows this error? At a minimum we need more details on your environment, how you are trying to run our library, what version of TS you are using - anything that would help us understand your issue.
