### ISSUE TITLE
SPHttpClient equivalent in PnPJS v3 

### ISSUE THREAD

**Issue by Syntarex** [pnp/pnpjs#2341]
Hey! I'm trying to update my spfx project to use version 3 of pnpjs. (v2->v3)

What's the equivalent of the `SPHttpClient`?

My code using version 2 of pnpjs:
```
import { DefaultRuntime } from "@pnp/common";
import { SPHttpClient } from "@pnp/sp";

const client: SPHttpClient = new SPHttpClient(DefaultRuntime);
```

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.4.1
Please specify what version(s) of SharePoint you are targeting: SPO only

**Thanks for your help and great work! PnPJS rocks!**

**Comment by juliemturner** [comment]
So V3 completely rewrote the internals of the library and at this point there is no real equivalent to that object.  If you want to completely rewrite the fetch client works so you're handling it on your own, then the equivalent for that in V3 is to write your own behavior and not use one of the default ones that we provide.

Some documentation that will get you started...

Understand the internals of the library: https://pnp.github.io/pnpjs/core/timeline/
Understand a behavior and look at some recipes: https://pnp.github.io/pnpjs/core/behaviors/ https://pnp.github.io/pnpjs/core/behavior-recipes/

If you share your use case I may be able to provide more direction.

**Comment by Syntarex** [comment]
Thanks! And big big thanks for developing those libs. They are really really helpful and make my day better. :)
