### ISSUE TITLE
SPFx 1.15 - sp.web - "Expected second tuple param to be an absolute url at new Queryable"

### ISSUE THREAD

**Issue by coreyroth** [pnp/pnpjs#2347]
Upgraded to SPFx 1.15 today.  After I fixed my plethora of TSLint errors (all 555 of them), I am down to this final issue with PnPJS.  Prior to today we were running on SPFx 1.14 and PnPJS 3.1.0.  Now I am on SPFx 1.15 and PnPJS 3.5.0 (also occurred on 3.1.0 I think as well).

Seeing an issue accessing sp.web as shown below.

### Category
- [ ] Enhancement
- [X] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    3.5.0     ]

Please specify what version(s) of SharePoint you are targeting: [ 1.15.0         ]

### Expected / Desired Behavior / Question
sp.web doesn't return an exception

### Observed Behavior
When accessing sp.web I get the following exception:

_"Expected second tuple param to be an absolute url at new Queryable"_

However, sp.hubSites looks ok.

### Steps to Reproduce
I have a pnpjsConfig.ts written mostly like the web part example customized to work with Web Parts or Application Customizers in the project:

`import { ApplicationCustomizerContext } from '@microsoft/sp-application-base';
import { WebPartContext } from "@microsoft/sp-webpart-base";

// import pnp and pnp logging system
import { spfi, SPFI, SPFx } from "@pnp/sp";
import { Caching } from "@pnp/queryable";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/comments";
import "@pnp/sp/hubsites";

let _sp: SPFI = null;

export const getSP = (context?: ApplicationCustomizerContext | WebPartContext): SPFI => {
    if (_sp === null && context !== null) {
        _sp = spfi().using(SPFx(context)).using(Caching({
            store: 'session'
        }));
    }
    return _sp;
};`

In onInit() of my Application Customer, I call getSP:
`getSP(this.context);`

Debugging the pnpjsConifg.ts file, I can see that sp.webs has the exception:
[Debugging Image](https://coreyroth.files.wordpress.com/2022/07/screen-shot-2022-07-12-at-2.08.11-pm.png)
[Image showing context object](https://coreyroth.files.wordpress.com/2022/07/screen-shot-2022-07-12-at-2.13.34-pm.png)

Call stack when trying to get a list item:
_Error: Expected second tuple param to be an absolute url
    at new Queryable (queryable.js:34:1)
    at Object.construct (invokable.js:22:18)
    at Object.construct (extendable.js:16:1)
    at new _SPQueryable (spqueryable.js:47:1)
    at new _SPInstance (spqueryable.js:161:8)
    at new _Web (types.js:84:1)
    at new <anonymous> (decorators.js:11:1)
    at queryable-factory.js:4:1
    at SPFI.create (fi.js:26:1)
    at SPFI.get [as web] (index.js:8:1)_

I don't know if this is a bug or not or just user error, but I've dug as deep into the PnPJS code as I could before not being sure what to look at next.

**Comment by patrick-rodgers** [comment]
Can you share the project or the full code where this happens? I know where that error is thrown but we haven't seen any issues related to the constructors. Not saying we don't have a bug but our tests run clean currently. I wonder if this is something else in SPFx 1.15 they changed in the context.

**Comment by coreyroth** [comment]
Yeah I was just about to post.  I'll see if I can put together a repro for it here shortly.  I just wanted to get it out there first in case anyone else was running into it.

**Comment by coreyroth** [comment]
I think something may have changed in the Context object with 1.15.  Here is a simple repo.
[https://github.com/coreyroth/SPFx1.15PnPJSException/tree/master](https://github.com/coreyroth/SPFx1.15PnPJSException/tree/master)

**Comment by patrick-rodgers** [comment]
Ok, I can repro it - something is different, not sure what, but it is in our library (not SPFx changes). Will work on it and get a 3.5.1 out once I feel it is fixed. For now as a work around you can:

```TS
spfi(context.pageContext.web.absoluteUrl).using(SPFx(context)
```

The issue didn't surface in our tests as we run them in node and set a url at the start so it never showed up.

**Comment by coreyroth** [comment]
Confirmed the work around works for me.

**Comment by DonKirkham** [comment]
@patrick-rodgers You, sir, are a rock star!! I am so impressed on how this was handled by "community."  This is why I love this community.

**Comment by mmsharepoint** [comment]
+1
And I can also tell the this (coming from the ServiceClass approach) works as well as a workaround:
const pageContext = serviceScope.consume(PageContext.serviceKey);
this._sp = spfi(pageContext.web.absoluteUrl).using(SPFx({ pageContext }));

**Comment by FaganSC** [comment]
> Ok, I can repro it - something is different, not sure what, but it is in our library (not SPFx changes). Will work on it and get a 3.5.1 out once I feel it is fixed. For now as a work around you can:
> 
> ```ts
> spfi(context.pageContext.web.absoluteUrl).using(SPFx(context));
> ```
> 
> The issue didn't surface in our tests as we run them in node and set a url at the start so it never showed up.

@patrick-rodgers Thank You for the fix! It saved my bacon on a project.
