### ISSUE TITLE
how to get "the presence" of a user by pnpjs API?

### ISSUE THREAD

**Issue by dudi44** [pnp/pnpjs#235]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

How to get "the presence" of a user by pnpjs API?  I'm using  PeoplePicker component from office-ui-fabric-react package and would like to set its presence flag (PersonaPresence enum)

thanks in advance

**Comment by simonagren** [comment]
As far as I know you cannot get the "presence" of the user from SharePoint.
If you wan't to have a look at an React SPFx example where they utilize the status from Skype, here it is:
https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-skype-status/src/webparts/skypePresenceReact

/Simon

**Comment by patrick-rodgers** [comment]
Thanks @simonagren this is correct.
