### ISSUE TITLE
V3 Throwing Error in SPFx Ext Field Customizer

### ISSUE THREAD

**Issue by jared-leddy** [pnp/pnpjs#2353]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.5.1 ]

Please specify what version(s) of SharePoint you are targeting: [ 1.13.1 ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Expecting the PNP library to execute REST API features. This code was copied from your sample project for v3 sample. Specifically where you started using the PNP config file, which I'm using.

Ref: [https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-pnp-js-sample](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-pnp-js-sample)

```js
// your sample class-based use
import { getSP } from "../pnpjsConfig";
import { SPFI, spfi } from "@pnp/sp";

// your class and constructor use 
export default class PnPjsExample extends React.Component<IPnPjsExampleProps, IIPnPjsExampleState> {
  private _sp: SPFI;
  constructor(props: IPnPjsExampleProps) {
    super(props);
    this._sp = getSP();
  }
  
  // inside a class method further down
      //Creating a new sp object to include caching behavior. This way our original object is unchanged.
      const spCache = spfi(this._sp).using(Caching({ store: "session" }));

      const response: IResponseItem[] = await spCache.web.lists
        .getByTitle(this.LIBRARY_NAME)
        .items
        .select("Id", "Title", "FileLeafRef", "File/Length")
        .expand("File/Length")();
}
```

Below are my files and there differences of usage compared to your initial sample file. In my project, I'm not using a class.
```js
import { SPFI, spfi } from '@pnp/sp';
const _sp: SPFI = getSP();

// inside an 'export const' arrow function
const spCache = spfi(_sp).using(Caching({ store: 'session' }));
const response: IResponseItem[] = await spCache.web.lists.getByTitle(FILE_LIST).items.select().getAll();

// my pnp js config file differences
import { ExtensionContext } from "@microsoft/sp-extension-base";
```

### Observed Behavior

Error logged to browser when the `spfi(_sp)` "_sp" variable is called. 
```
_getFilePlanData: error caught  TypeError: Reflect.has called on non-object
    at Reflect.has (<anonymous>)
    at spfi (fi.js:30:1)
    at getData.ts:150:29
    at Generator.next (<anonymous>)
    at ssic-cutoff-field-customizer.js:3991:71
    at new Promise (<anonymous>)
    at f41B.__awaiter (ssic-cutoff-field-customizer.js:3987:12)
    at _getFilePlanData (getData.ts:145:63)
    at SsicCutoffFieldCustomizer.<anonymous> (SsicCutoffFieldCustomizer.ts:48:41)
    at Generator.next (<anonymous>)
```

### Steps to Reproduce

`npm run start` & refresh page.
or 
`gulp serve` & refresh page.

**Comment by juliemturner** [comment]
My sample works because in the [PnPjsExampleWebPart.ts](https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-pnp-js-sample/src/webparts/pnPjsExample/PnPjsExampleWebPart.ts) file (line 33) I'm passing the web part context to my pnpjsConfig.ts file to establish the global variable _sp, so that when I call getSP() on line 36 of [PnPjsExample.ts](https://github.com/pnp/sp-dev-fx-webparts/blob/main/samples/react-pnp-js-sample/src/webparts/pnPjsExample/components/PnPjsExample.tsx) it's just returning the already initialized variable so that it can be used.  If you skip that step it's not going to work as it has no idea what context the code is running in.

You might want to watch the 5-part series that explains this sample in detail: https://youtube.com/playlist?list=PLR9nK3mnD-OWvmtj9TKE6tM7ZrUosV_vB

**Comment by jared-leddy** [comment]
> My sample works because...

Good Morning Ma'am,
Thank you for replying so quickly. That was actually flagged internally yesterday. We updated our project this morning and just finished testing it about 10 minutes ago with that context in place. We're still getting the same error.

**Comment by juliemturner** [comment]
Ok, well... not sure what to tell you.  If you can create a github repo that reproduces the issue I can try and guide you but the sample I shared is working (i tested it this morning again to verify).

**Comment by jared-leddy** [comment]
@juliemturner, I sent an email to you with the details that I can provide.

**Comment by jared-leddy** [comment]
Good Morning Ma'am,

I understand your position. It's just that I would get fired and likely go to jail if I shared the code as is.

My inquiry and mocked version was merely to see if I've got it setup correctly. Especially since I'm not using classes everywhere like you have done it.

If that's not possible, then I'll have to move on and figure it out myself.


If you have any questions, or concerns, please don't hesitate to ask.


Respectfully Sent,


Mr. Ledbetter, Jared M.
📧 Email: ***@***.***
📱Mobile: (704) 207-8313

"Semper Fidelis"
________________________________

**Comment by juliemturner** [comment]
I believe I already answered but effectively this line is wrong:

`const spCache = spfi(_sp).using(Caching({ store: 'session' }));`

It needs to be:

```TypeScript
import { spfi, SPFx } from "@pnp/sp";
const spCache = spfi().using(SPFx(this.context)).using(Caching({ store: 'session' }));
```

See the documentation on [getting started](https://pnp.github.io/pnpjs/getting-started/#using-pnpsp-spfi-factory-interface-in-spfx).

**Comment by jared-leddy** [comment]
> I believe I already answered but effectively this line is wrong:
> 

Good Afternoon Ma'am,

This solution in the docs is not the same as the sample. In the sample, you're using a custom config file called `pnpjsConfig.ts`, which I've found to be the best setup. In keeping with that, I set out to solve the problem "as is" with my version. 

Since this extension isn't using React, or JS Classes, we're working off the `export const` async arrow function setup. Here is the example usage:
```js
// copy-paste from the sample
const spCache = spfi(this._sp).using(Caching({ store: "session" }));

// since we don't have classes, the "this" keyword isn't available, so we've got a const setup for it. 
const _sp: SPFI = getSP();
// then we call it like so:
const spCache = spfi(_sp).using(Caching({ store: "session" }));
```

Since the `_sp` variable is where the error is being thrown, this is not viable. After much tinkering, our solution was changed slightly and is working beautifully. 

```js
const spCache = spfi(getSP()).using(Caching({ store: "session" }));
```
