### ISSUE TITLE
Question v2 to v3 upgrade - Web()

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#2355]
### Category
- [x] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [  "^3.5.1"  ]
Upgrading from "^2.11.0"

Please specify what version(s) of SharePoint you are targeting: [  SPO  ]

### Expected / Desired Behavior / Question
I'm trying to upgrade to the latest version... all my code is coming from v2.11.0.

Currently my biggest struggle is just getting a web.  I typically do not pass around the context so in the past I would just pass in whatever web I need as shown below.

I've tried a couple different ways but seem to always get an error about 'observables'.  I read the pages about this subject in the docs, but it's way above my head (observables, moments etc).  I live by seeing real examples so I'm hoping someone can show a very simple stand-alone function.

Sample of my current function
```typescript
import { Web, } from "@pnp/sp/presets/all";
export async function doSomething( webURL: string, userEmail: string ) {
    let thisListWeb = Web(webURL);
    let result = await thisListWeb.ensureUser(userEmail);
    console.log('userInfo', result );
    
    // OR - The docs are pretty clear on changing the .get() to just ()  :)
    allItems = await thisListWeb.lists.getByTitle("ListTitle").items.top(300).get();
    
}
```

### Observed Behavior
This is one of the errors of many.
![image](https://user-images.githubusercontent.com/49648086/179628671-c27b740f-941e-44e5-a4c0-adc5c0fc674e.png)

Thanks for any answers you can provide!

**Comment by sympmarc** [comment]
I always use the M365 CLI. The

`spfx project upgrade`

command gives you all the steps, and even automates some of them for you.

https://pnp.github.io/cli-microsoft365/cmd/spfx/project/project-upgrade/

**Comment by mikezimm** [comment]
Hi Mark,
I tried to click 'view it on github' but it does not show this post.

Anyway, I tried using the cli per your suggestion but did not have any success.

I tried it a second time after authenticating and got the same error message in the screenshot.

Looking back at how I got through the 'first part' of the upgrade, I found I had this report.md file.  Not sure if it helps though.  Can not find any reference to the .ts file(s) where I am doing the crud functions.

If anyone does know of any good examples, I do all the crud functions in separate ts libraries I created so that I can easily re-use the code across projects.  Because of that I avoid passing context and other objects if I can just pass in the web url where I need to connect to.

Thanks again for any input!
Mike

[cid:45991007-a2b1-477b-8da0-fbd9f59f05c8]
________________________________

**Comment by sympmarc** [comment]
Sorry - I had typed an answer and as soon as I hit submit I realized it wasn't germane to your issue, so I deleted it. I thought I would have beaten the notification.

**Comment by jacksonv1lle** [comment]
I am currently doing an upgrade from v2. I also had a lot of instances where I create a Web using just the absolute URL.

I am using the Service Locator Pattern for SPFx (serviceScopes) so the web part context is not always available when I need to use the PnP library. 

I followed the format of the Sample Service Class (Option 2) from [this page in the documentation](https://pnp.github.io/pnpjs/concepts/project-preset/#use-a-service-class). As you can see, you do not need to pass the entire web part context to create the SP instance - only the page context is necessary in most of my cases.

`this._sp = spfi().using(SPFx({ pageContext }));`

Once you have the instance of the SP, then you can [get access to a web](https://pnp.github.io/pnpjs/sp/webs/#access-a-web) using the absolute URL using the SP instance:

`const web = Web([this._sp.web, "https://tenant.sharepoint.com/sites/otherweb"]);`

**Comment by patrick-rodgers** [comment]
@juliemturner - let's talk about this when you're back, maybe there is something we can do to make it easier - though this is exactly what the tuple constructor @jacksonv1lle shows above was made for. Because there is no global sp Web when used directly has no registered observers. It would be totally valid to create a web `Web("ur;")` but you'd then need to attach the needed observers to make it work.

**Comment by patrick-rodgers** [comment]
Been thinking about this and we aren't going to make any changes to the library to support calling just Web(). In fact I am not certain we can without going back to the global style configuration, something we made a choice to avoid.

Instead I'd recommend creating a function similiar to:

```TS
function GetWeb(url: string): IWeb {
  return Web(url).using(...[your behaviors]);
}
```

Then replace `Web()` calls across your application with `GetWeb()`. That way you can still centrally configure all web's observers - but not need to refence them across your application.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
