### ISSUE TITLE
IViewInfo typing misses some properties

### ISSUE THREAD

**Issue by martinlingstuyl** [pnp/pnpjs#2357]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.5.0

Please specify what version(s) of SharePoint you are targeting: SharePoint Online

### Expected / Desired Behavior / Question
The `IViewInfo` type should include the following extra properties: 
- `AssociatedContentTypeId` as nullable string. This can contain a (site) content type id when the view was created based on a content type.
- `CalendarViewStyles` as nullable string. This can contain a string XML value.
- `CustomFormatter` as nullable string. This can contain an encoded json string when View Formatting is implemented in the view.
- `DefaultView` as boolean.
- `DefaultViewForContentType` as boolean. 
- `ViewType2` as nullable string. It can contain the following values: KANBAN, TILES, COMPACTLIST, MODERNCALENDAR or null

### Observed Behavior
They are not included

### Steps to Reproduce
View the types at `@pnp/sp/views/types.d.ts`

15-08-2022: Updated for ModernCalendar view type

**Comment by martinlingstuyl** [comment]
I've running into missing fields as I go 😂

**Comment by martinlingstuyl** [comment]
Hi @juliemturner, absolutely not to hurry you guys along, but seeing the labels: did you notice the PR I submitted on this issue? I'd like to contribute, even if it's just in a little way 😇

**Comment by juliemturner** [comment]
Yes, that's what the label means in that we have not found the time to review and merge it in yet, ergo, it's in progress. Assuming when we do there are no issues it will be in the next release.

**Comment by martinlingstuyl** [comment]
Awesome! Again: no no hurries! Have a good week👍
