### ISSUE TITLE
Please clarify what  const sp = spfi(...); is?

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#2361]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    3.5.1     ]

Please specify what version(s) of SharePoint you are targeting: [     SPO    ]

### Expected / Desired Behavior / Question
My day job is not a professional developer, so this sounds like a dumb question to me, but I have to ask.

What exactly do I need to do when I see this statement because no matter how I try to use it, I get an error in the screenshot.
Note:  Typically I move all my calls into separate typescript files so I can easily re-use across projects.  Because of that I typically do not  have the context readily available.

I've also tried replacing the ... with the full Url of the site and still get a 404 error.

```
const sp = spfi(...);
```
![image](https://user-images.githubusercontent.com/49648086/180291232-567492dc-2383-468a-aedc-289ec541b677.png)

## In the past (v2.x)
I could use this great library with ease just by calling any web in the tenant using:
let thisListWeb = Web(webUrl);

Then do something like thisListWeb.ensureUser(blablabla)

It just seemed so much easier.  Not sure if I am just missing something obvious.

Thanks for any input.

**Comment by NewGHUser4321** [comment]
@mikezimm - Try this as shown [here](https://pnp.github.io/pnpjs/transition-guide/#web-spfi)
```
import { spfi, SPFx } from "@pnp/sp";
const sp = spfi().using(SPFx(this.context));
```
Thanks,

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
