### ISSUE TITLE
Bug: SharePoint Column named "d"

### ISSUE THREAD

**Issue by tknaller** [pnp/pnpjs#2362]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     any    ]

Please specify what version(s) of SharePoint you are targeting: [   any      ]

### Expected / Desired Behavior / Question
Successfully adding a list item 

### Observed Behavior
When adding a list item to a list with a column named "d" without adding data to that column, the query fails, because json hasOwnProperty "d" but json.d is null/not an object, see https://github.com/pnp/pnpjs/blob/af3d8131224de6d8c8925576f091ba20608098d8/packages/queryable/behaviors/parsers.ts#L61

### Steps to Reproduce
* Create SP List with a column named "d"
* add new List item to that listwith list.items.add(), but don't include a value for column "d"
* see TypeError Cannot convert undefined or null to object

**Comment by tknaller** [comment]
well scenario/use case is a bit far fetched - I created a few columns with random column names for some testing and was suddenly stuck with a very meaningless error message which costed me a few hours and some additional grey hair.

changing it to `` if (json.d && hOP(json.d, "results")) { `` would already suffice to work around that issue.

**Comment by patrick-rodgers** [comment]
We're going to leave this as-is. Sorry you ran into the issue and got a few extra grey hairs. Thanks!
