### ISSUE TITLE
How do I set context using sp pnp v3 - getting undefined Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pageContext')

### ISSUE THREAD

**Issue by cardinalpipkin** [pnp/pnpjs#2364]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  "@pnp/sp": "^3.5.1"  and   "@microsoft/rush-stack-compiler-4.2": "^0.1.2" ]

Please specify what version(s) of SharePoint you are targeting: [ 1.15.0 ]

Question:
How do I set context in a Utility file?

### Observed Behavior
I see:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pageContext')
    at Proxy.<anonymous> (erp-web-part.js:43266:89)
    at erp-web-part.js:25329:73`
when serving the app.

### Steps to Reproduce
I cannot create a code example using JSfiddle or similar as I just don't understand how to use them with this framework.

Here's the code on the root .ts file:
```
public async onInit(): Promise<void> {
    await super.onInit();
    getSP(this.context);
  }
```

Here's the code on the Parent Component:

```
const GetERPs = async () => {
    const allItems = await Utils.ReadListItems("ERPs").then(r => {
      let returnedCapex: IListItem[] = r.map((item) => {
        return {
          Id: item.Id,
          Modified: item.Modified,
          Title: item.Title,
        };
      });
      return returnedERP;
    });
    let sortedERP = allItems.sort((a, b) => a.Id < b.Id ? 1 : -1);
    let sortedERPLength = sortedERP.length;
    let howManyPagesCalc = Math.ceil(sortedERPLength / 50);
    setHowManyPages(howManyPagesCalc);
    return sortedERP;
  };

  const _getListItemsFromSP = async () => {
    await GetERPs().then(r => {
      setERPs(r);
    });
  };
```

Here is the utility file which is using sp.web etc..
```import { getSP } from "../webparts/erp/components/pnpjsConfig";
import { SPFI, spfi } from "@pnp/sp";
import { WebPartContext } from "@microsoft/sp-webpart-base";
import { PagedItemCollection } from "@pnp/sp/items";

let sp: SPFI;

sp = getSP();
console.log(sp, 'sp');

export const ReadListItems = async (listName: string, filter?: string) => {

    let listItems: any[] = [];
    let pagedItems: PagedItemCollection<any[]> = undefined;
    do {
        if (!pagedItems) {
            pagedItems = await sp.web.lists.getByTitle(listName).items.select(
                `*, Author/Id,
                CompletedBy/UserName, CompletedBy/Title, CompletedBy/Id, 
                BURepresentative/UserName, BURepresentative/Title, BURepresentative/Id
                `
            )
                .filter(filter)
                .expand('Author, CompletedBy, BURepresentative').getPaged();

        } else {
            pagedItems = await pagedItems.getNext()
        }
        if (pagedItems.results) {
            listItems = listItems.concat(pagedItems.results);
        }
    }
    while (pagedItems.hasNext)
    return listItems;
};
```

As mentioned I'm getting an Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pageContext') error. 
Am I using it right? Need some help please.

**Comment by juliemturner** [comment]
I'm sorry, there are so many things that I question about these snippets it's really hard to tell what you're doing.  If you can create a small sample project that reproduces your issue and share a link we can try and assist.

**Comment by cardinalpipkin** [comment]
Thanks - can you tell me way to create a code sample? Is there a website or would it be a zipped file I attach??

**Comment by cardinalpipkin** [comment]
Managed to get it working using the pnpJSconfig file method as outlined here:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts
The approach I supplied above just wouldn't work for me.
