### ISSUE TITLE
Add comment to a file as a specified user

### ISSUE THREAD

**Issue by Saintenr** [pnp/pnpjs#2366]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [
@pnp/sp: ^3.5.1,
"@pnp/nodejs-commonjs": "^2.14.0",
"@pnp/sp-commonjs": "^2.14.0",
]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
Is it possible to make a comment to a file as a different user? 
e.g. the user at our site have only read permissions to items. We use an azure function to perform edit actions. In case that comment is an edit action, i want to let my service user (azure app registration) perform this action.

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### App code to create ICommentInfo

`const comment = 'Test';
const author: Partial<ICommentAuthorData> = {
            id: 15,
            email: 'john.doe@contoso.com', 
            loginName: 'i:0#.f|membership|john.doe@contoso.com',
            name: 'John Doe', 
        };
const commentInfo: Partial<ICommentInfo> = {
            author: author,
            text: comment,
        };`

### App code to run azure function

`
const url = 'azure function post url'
const requestHeaders: Headers = new Headers();
requestHeaders.append('Content-type', 'application/json');
requestHeaders.append('Cache-Control', 'no-cache');

const postOptions: IHttpClientOptions = {
            headers: requestHeaders,
            body: JSON.stringify({
                id: id,
                commentInfo: commentInfo,
            }),
        };

const res = await httpClient.post(url, HttpClient.configurations.v1, postOptions);
`

### Azure function code

`import { AzureFunction, Context, HttpRequest } from "@azure/functions";
import { SPFetchClient } from "@pnp/nodejs-commonjs";
import { ICommentInfo, IItem, sp } from "@pnp/sp-commonjs";

type body = {
    id:string,
    commentInfo:ICommentInfo,
}

const httpTrigger: AzureFunction = async function (context: Context, req: HttpRequest): Promise<void> {

    async function setupSp(): Promise<SPFetchClient> {
        const SPClient = new SPFetchClient(
            process.env.SiteUrl,
            process.env.ClientId,
            process.env.ClientSecret
        );

        return new Promise(async (resolve) => {
            const setup = sp.setup({
                sp: {
                    fetchClientFactory: () => {
                        return SPClient;
                    },
                },
            });
            context.log("Client Setup done");
            resolve(SPClient);
        });
    }
    
    try {
        context.log('HTTP trigger function processed a request.');
        const body :body = req.body;
        await setupSp();
        context.log(body)
        context.log(body.id)
        const item = await sp.web.getFileById(body.id).getItem();
        const comment = await item.comments.add(body.commentInfo)
        context.log(comment)
        context.res = {
            status: 200, /* Defaults to 200 */
            body: JSON.stringify(comment)
        };
    } catch (err) {
        context.log(err)
        context.res=err
    }

};

export default httpTrigger;`

Sadly this create the comment as "SharePoint App" and not as the provided user.
Is this not possible or am i wrong at some points?

I am facing the same result if i do this from the app with my admin user that has edit permissions. Then i creates the comment with my name.

Thanks for your feedback

**Comment by juliemturner** [comment]
That's because your Azure Function is updating SharePoint as the app not as the user... 

What you're looking to do is impersonate the user.  A google search turned up this article from Vardhaman Deshpande, but I have not personally tried this so I cannot tell you if it's going to work.

https://www.vrdmn.com/2018/05/spfx-calling-back-to-sharepoint-from.html

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
