### ISSUE TITLE
shareWith-Error No observers registered for this request.

### ISSUE THREAD

**Issue by ravikadri** [pnp/pnpjs#2372]
@juliemturner 

### Category

- [ ] Bug

### Version

Please specify what version of the library you are using: [ 3.5.1        ]

Please specify what version(s) of SharePoint you are targeting: [    SPO with SPFx 1.15  ]

### Expected / Desired Behavior / Question
*Should be able to share the site with the specified user

### Observed Behavior
*queryable.js:84 Uncaught (in promise) Error: No observers registered for this request. (https://pnp.github.io/pnpjs/queryable/queryable#No-observers-registered-for-this-request)

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/104390320/183718941-ec041708-d82e-47fd-a9a9-9f763a64743e.png)

![image](https://user-images.githubusercontent.com/104390320/183717788-bc586a4b-f329-4061-84c0-9b01bbf4f33b.png)

**Comment by miketran13** [comment]
I got the same error when trying with both shareWith and shareObject, both got the same error.
![image](https://user-images.githubusercontent.com/4388577/183814552-b5015dc3-d3d9-4dec-bef8-dd8c9b1bf038.png)

**Comment by patrick-rodgers** [comment]
This is fixed and will be in the next release, 3.6 - we've delayed the release to (currently) Monday August 15th. Mostly because we hadn't time to get to these issues yet and it didn't make sense to make them wait another month. Thanks for your patience and reporting the issues!
