### ISSUE TITLE
Issue with Paging when used with $orderby or $search parameter

### ISSUE THREAD

**Issue by Tripplefix** [pnp/pnpjs#2373]
### Category
- [x] Enhancement
- [x] Bug

### Version

Please specify what version of the library you are using: [3.5.1]

Please specify what version(s) of SharePoint you are targeting: [1.15.2]

### Expected / Desired Behavior / Question
When using the [Paged behaviour with graph](https://pnp.github.io/pnpjs/graph/behaviors/#paged), it should be possible to use the parameters $filter in combination with $orderBy. Additionally, the parameter $search should be supported, as well.

### Observed Behavior
When trying to use the $orderBy parameter in combination with the $filter parameter, an error is thrown: 

`Emitting error: "Error making HttpClient request in queryable [400] Bad Request ::> {"error":{"code":"Request_UnsupportedQuery","message":"Sorting not supported for current query."`

This is because the $count parameter is not included in the request URL. 

The parameter $search is simply ignored with no error messages. It is not included in the request URL either.

### Steps to Reproduce
The following code will reproduce both issues:

```
public async searchUsers(q: string, department: string): Promise<IPagedResult> {
    
    let users = this._graph.users

    users.query.set("$count", "true")
    users = users.top(5)

    users = users.filter(`department eq '${department}'`);
    users = users.search(`displayName:${q}`)
    users = users.orderBy("displayName")

    return users.paged()
}
```

### Solution / Suggestion
In the file packages/graph/behaviours/paged.ts update the following line to include $search and $count:

line 21: `const queryParams = ["$search", "$count", "$top", "$select", "$expand", "$filter", "$orderby"];`

**Comment by Tripplefix** [comment]
I have noticed that there is a similar issue with the "count()" method. It only returns the total count without the $filter or $search parameter applied. The solution could be to add the parameters dynamically in the same way you do in the "AsPaged" method:

```
/**
 * 	Retrieves the total count of matching resources
 */
public async count(): Promise<number> {
    const q = GraphQueryableCollection(this).using(ConsistencyLevel(), JSONParse());
    
    // This line is not necessary anymore
    //q.query.set("$count", "true");

    // START new code
    const queryParams = ["$search", "$count", "$top", "$select", "$expand", "$filter", "$orderby"];

    for (let i = 0; i < queryParams.length; i++) {
        const param = q.query.get(queryParams[i]);
        if (objectDefinedNotNull(param)) {
            q.query.set(queryParams[i], param);
        }
    }
    // END new code

    const r = await q.top(1)();
    return parseFloat(r["@odata.count"]);
}
```

**Comment by patrick-rodgers** [comment]
Awesome, thank you - I see you opened a PR for this. Nice work digging into the code, we'll have a look and get that merged for the next release, 3.6.

Thank you!!!

**Comment by Tripplefix** [comment]
Sure!
I just had another thought: we could add a member "count" or "totalCount" to the IPagedResult interface and populate it in the Paged() function since MS Graph returns this value in the metadata ("@odata.count"). It would save an API call. Or was there a specific reason to have a separate "count()" function?

**Comment by patrick-rodgers** [comment]
Ok, just got this merged, thanks again! I did make a few changes to what you did:

- Took your suggestion and paged now includes the count
- Updated the count method to use paged to get the count
- Few other small changes to ensure $count is set properly

This was mostly to move all the logic that we were duplicating in count all into the Paged code so there is one place to update it in the future.

We have a count method originally because someone asked for it, and there would be cases where you might just want the total count of a collection.

This will be in tomorrow's nightly build if you want to try it out and part of the 3.7 release.

Thanks!!
