### ISSUE TITLE
Request to https://accounts.accesscontrol.windows.net failed (on a closed network)

### ISSUE THREAD

**Issue by SwagiWagi** [pnp/pnpjs#2378]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     1.1.14    ]

Please specify what version(s) of SharePoint you are targeting: [    2016     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

I am trying to use the sp.setup method to authenticate using client ID and secret, but since I am in a closed network I do not have access to the hardcoded URL the pnp is trying to access, what can I do to solve this?

Thank you for your feedback!

**Comment by juliemturner** [comment]
I'm sorry but we're not really supporting version 1 of the library anymore. That said you haven't really provided any information to help us understand what your configuration is or what you've attempted thus far.

**Comment by SwagiWagi** [comment]
Sorry, I am running an Express (4.18.1) server using PnP (1.1.14).
Correct me if I'm wrong since I couldn't find any documentation for this, but I can't update to the newer versions on PnP since they don't support this kind of authentication: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs

**Comment by SwagiWagi** [comment]
Any update?

**Comment by patrick-rodgers** [comment]
I can't find where we have that url hard coded in v1 of the library. Is it perhaps part of `adal-node`?

Can you share more of your code where you setup the library?

**Comment by patrick-rodgers** [comment]
Nevermind, found it. My memory for v1 isn't so sharp anymore. So you could write your own client and stuff but would much rather you update to v3. If the only thing blocking you is the ACS auth support, here is a sample implementation I am adding to the docs with the next release:

```TS
export function ACS(clientId: string, clientSecret: string, authUrl = "https://accounts.accesscontrol.windows.net"): (instance: Queryable) => Queryable {

  const SharePointServicePrincipal = "00000003-0000-0ff1-ce00-000000000000";

  async function getRealm(siteUrl: string): Promise<string> {

    const url = combine(siteUrl, "_vti_bin/client.svc");

    const r = await nodeFetch(url, {
      "headers": {
        "Authorization": "Bearer ",
      },
      "method": "POST",
    });

    const data: string = r.headers.get("www-authenticate") || "";
    const index = data.indexOf("Bearer realm=\"");
    return data.substring(index + 14, index + 50);
  }

  function getFormattedPrincipal(principalName: string, hostName: string, realm: string): string {
    let resource = principalName;
    if (hostName !== null && hostName !== "") {
      resource += "/" + hostName;
    }
    resource += "@" + realm;
    return resource;
  }

  async function getFullAuthUrl(realm: string): Promise<string> {

    const url = combine(authUrl, `/metadata/json/1?realm=${realm}`);

    const r = await nodeFetch(url, { method: "GET" });
    const json: { endpoints: { protocol: string; location: string }[] } = await r.json();

    const eps = json.endpoints.filter(ep => ep.protocol === "OAuth2");
    if (eps.length > 0) {
      return eps[0].location;
    }

    throw Error("Auth URL Endpoint could not be determined from data.");
  }

  return (instance: Queryable) => {

    instance.on.auth.replace(async (url: URL, init: RequestInit) => {

      const realm = await getRealm(url.toString());
      const fullAuthUrl = await getFullAuthUrl(realm);

      const resource = getFormattedPrincipal(SharePointServicePrincipal, url.host, realm);
      const formattedClientId = getFormattedPrincipal(clientId, "", realm);

      const body: string[] = [];
      body.push("grant_type=client_credentials");
      body.push(`client_id=${formattedClientId}`);
      body.push(`client_secret=${encodeURIComponent(clientSecret)}`);
      body.push(`resource=${resource}`);

      const r = await nodeFetch(fullAuthUrl, {
        body: body.join("&"),
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
        },
        method: "POST",
      });

      const accessToken: { access_token: string } = await r.json();

      init.headers = { ...init.headers, Authorization: `Bearer ${accessToken.access_token}` };

      return [url, init];
    });

    return instance;
  };
}
```

This doesn't cache the tokens or perhaps implement every possibility - but should allow you to get going.

**Comment by SwagiWagi** [comment]
Thank you very much! I'll upgrade to v3 now.
Don't close the issue yet as I will let you know in a week or two if it works in my environment.

**Comment by SwagiWagi** [comment]
I am getting an error in this line:
```
  return (instance: Queryable) => {

    instance.on.auth.replace(async (url: URL, init: RequestInit) => {
```
`
Property 'on' does not exist on type 'Queryable<any>'
`
@patrick-rodgers

**Comment by patrick-rodgers** [comment]
Have you reviewed the documentation for v3? Here is the section on [SPDefault](https://pnp.github.io/pnpjs/nodejs/behaviors/#spdefault) for node.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
