### ISSUE TITLE
Util.getUrlParamByName 

### ISSUE THREAD

**Issue by jonathanhotono** [pnp/pnpjs#238]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.2.1      ]

Where do I get `Util.getUrlParamByName` ? I tried to look within @pnp/common and it doesn't seem to be there anymore like in the old pnpjs-core
https://github.com/SharePoint/PnP-JS-Core/blob/master/src/utils/util.ts

**Comment by koltyakov** [comment]
Please check [this docs section](https://github.com/pnp/pnpjs/blob/a2929ee22c3da27debdf8fa58645a1d2d1ecc14e/packages/common/docs/util.md#removed).

**Comment by jonathanhotono** [comment]
Thanks @koltyakov. I'm importing it manually.
