### ISSUE TITLE
Problem updating list item with Taxonomy field

### ISSUE THREAD

**Issue by pothitos-baikas** [pnp/pnpjs#2380]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.6.0]

Please specify what version(s) of SharePoint you are targeting: [online]

### Expected / Desired Behavior / Question
I am trying to update a single value Taxonomy field of a custom document content type using the code below:
await this.props.sp.web.lists.getById(this.props.listGuid.toString()).items.select('ID', 'Title', 'OData__dlc_DocId', 'TypeOfDocument')
            .getById(this.props.itemId)
            .update({
            Title: this.state.title,
            TypeOfDocument: {
                "__metadata": { "type": "SP.Taxonomy.TaxonomyFieldValue" },
                "Label": this.state.terms[0].name.trim(),
                'TermGuid': this.state.terms[0].key.trim(), // field guid
                'WssId': '-1' // fake
              }
        }); 

### Observed Behavior
The code above, updates he 'Title' field, but not the Taxonomy one (TypeOfDocument in my case) I get the following error:
Uncaught (in promise) Error: Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The property '__metadata' does not exist on type 'SP.Taxonomy.TaxonomyFieldValue'. Make sure to only use property names that are defined by the type."}}}

If I comment out the "__metadata" property, I get no error, but the field still does not get updated

The sample code was used after searching for related articles - no example for single value taxonomy fields are provided in the documentation.

I also considered setting Headers (content-type:'application/json;odata=verbose'), but the documentation is not clear for V3 in this area

### Steps to Reproduce
Can be reproduced with hard coded vales for GUID

**Comment by juliemturner** [comment]
Maybe this will help... https://pnp.github.io/pnpjs/sp/items/#update-multi-value-taxonomy-field

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
