### ISSUE TITLE
Error [423]

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#2381]
### Version
Please specify what version of the library you are using: [^3.6.0]
Please specify what version(s) of SharePoint you are targeting: [ SPO ]
### Expected / Desired Behavior / Question
Successful replace of a file with ".setContentChunked(blob);"

### Observed Behavior
in my application, all files have unique permission by 2 SharePoint groups. 
To replace a file, I call an Azure Function that resets to inherit from the library  (ResetRoleInheritanceAsync from PnP.Core.Model.SharePoint) 
Then I use:
```
const fileChange: IFileAddResult = await projWeb.getFileByServerRelativePath(`${siteUrl}/DPCDocuments/${sameNumberFileName}`).setContentChunked(blob); 
```
to replace the file.
Most of the time it works fine.
Yesterday it errored with a locking error:
```
Error making HttpClient request in queryable [423]  ::> {"odata.error":{"code":"-2147023436, Microsoft.SharePoint.SPFileLockException","message":{"lang":"en-US","value":"The operation on file \"https://ecgmcaz.sharepoint.com/teams/0100.109/DPCDocuments/UCF ECG Ambulatory Strategic Planning 8-19-22 .docx\" cannot be completed because the specified lock arguments are not valid."}}}
```
Is there anything I can do it the Azure Function or the .setContentChunked call,  to prevent that from happening? 

Thank you much

**Comment by patrick-rodgers** [comment]
This feels like the file is checked out or otherwise in use? I am not aware of anything that can be done in the setContentChunked call to override this.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
