### ISSUE TITLE
When moving a file with the "moveByPath" method, the creator and creation / modification date is not preserved

### ISSUE THREAD

**Issue by fabiofranzini** [pnp/pnpjs#2382]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [latest]
Please specify what version(s) of SharePoint you are targeting: [Online]

### Description
Hi, I noticed that when moving a file with the "moveByPath" method, the creator and creation / modification date is not preserved.
Checking the sources, I realized that on this line:
https://github.com/pnp/pnpjs/blob/fff7cfaecc9f2bf5703c957cf1e4151fe71af625/packages/sp/files/types.ts#L264
the 'RetainEditorAndModifiedOnMove' parameter is not set to true, but it's only setted the 'ResetAuthorAndCreatedOnCopy' at false.

Can you confirm if it is a bug or is it correct?
If I try to use the native SharePoint move feature, the fields are preserved.
Thanks

**Comment by fabiofranzini** [comment]
Thanks @patrick-rodgers

**Comment by patrick-rodgers** [comment]
Added overloaded signatures that take as a second param the full set of options available for both moveByPath and copyByPath. Will be in the next release.
