### ISSUE TITLE
Favorites (followedSites and followedListItems)

### ISSUE THREAD

**Issue by wilecoyotegenius** [pnp/pnpjs#2383]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.6        ]

Please specify what version(s) of SharePoint you are targeting: [ SPO        ]

### Expected / Desired Behavior / Question
I propose adding support for followed sites and list items. Both elements are available in SharePoint API v2.1. And all related requests are very simple.

__Getting followed sites:__
`GET https://tenant.sharepoint.com/_api/v2.1/favorites/followedSites`

__Getting followed list items:__
`GET https://tenant.sharepoint.com/_api/v2.1/favorites/followedListItems`

__Adding new followed list item:__
```
POST https://tenant.sharepoint.com/_api/v2.1/favorites/followedListItems/oneDrive.add

{
    "value": [{
        "siteId": "4290a6a4-d96f-4b11-a7bc-5045d5f2e0f2",
        "webId": "b6e1ec6b-445b-4ab4-acb9-57d390df7730",
        "listId": "c1503a15-1124-4882-97b5-022c22a8e4e0",
        "listItemUniqueId": "e95cd710-daee-45c4-b8ed-56e2e409acb8"
    }]
}
```

__Removing a followed list item:__
```
POST https://tenant.sharepoint.com/_api/v2.1/favorites/followedListItems/oneDrive.remove

{
    "value": [{
        "siteId": "4290a6a4-d96f-4b11-a7bc-5045d5f2e0f2",
        "webId": "b6e1ec6b-445b-4ab4-acb9-57d390df7730",
        "listId": "c1503a15-1124-4882-97b5-022c22a8e4e0",
        "listItemUniqueId": "e95cd710-daee-45c4-b8ed-56e2e409acb8"
    }]
}
```

I wanted to submit a pull request myself and even spent some time looking at the repo, but complexity of this project's source code is beyond my level of understanding - I wasn't able to get it to work even when trying to do it based on already existing pieces.

**Comment by patrick-rodgers** [comment]
Closing with merge of #2392 - thank you!!
