### ISSUE TITLE
In browser debugging not working?

### ISSUE THREAD

**Issue by wilecoyotegenius** [pnp/pnpjs#2385]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ fork of a latest version-3 branch  - release 3.6 ]

Please specify what version(s) of SharePoint you are targeting: [  SPO  ]

### Expected / Desired Behavior / Question
I have just forked a version-3 branch and tried to develop an enchancement. Unfortunately, I am unable to get in browser debugging to work. I have followed a guidance from documentation and actually got pnp.js available on a page. However, code from main.ts fails to execute.
Does anyone have the same issue? What am I missing??

### Steps to Reproduce
- ran `npm install` and `npm run serve` on a project
- confirmed that pnp.js is served via webpack dev server at https://localhost:8080/assets/pnp.js.
- confirmed that pnp.js served does contain main.ts code and there are no errors in browser's dev tools console.
- created a page in classic SharePoint
- added Script Web Part to the page
- appended code from documentation to reference pnp.js in the web part
- updated code in main.ts (only changed tenant name from example provided).
- ensured that pnp.js loads on a page (via `chrome://flags/#allow-insecure-localhost` flags and disabling Network request blocking in Chrome).
- set a breakpoint in main.ts (it's available in Source tab of dev tools, so source maps work fine)
- refreshed page multiple times - breakpoint is not getting hit.

**Comment by juliemturner** [comment]
I think you're referencing in browser debugging which I've never done so I can't speak to that.

I use debugging in visual studio code and all that I really need to make sure I've done is created the settings.js file, there is an example here: https://github.com/pnp/pnpjs/blob/version-3/settings.example.js

and then debugging is via VSC:

![image](https://user-images.githubusercontent.com/7570936/187318747-1e652e95-d240-4770-9a7f-8934a32069c9.png)

![image](https://user-images.githubusercontent.com/7570936/187318820-61921924-167a-41b2-b8ee-da212fdd25cc.png)

**Comment by wilecoyotegenius** [comment]
Thanks Julie,
The problem is that debugging in VSC uses MSAL and application permissions. So there's no way to test features that rely on user context. And what I am trying to test (#2383) requires a user context.

**Comment by patrick-rodgers** [comment]
The browser debugging works for me, so not sure. It reads like you've setup everything correctly.

Here is the exact content I have in my script editor webpart:

```
<script src="https://localhost:8080/assets/pnp.js" type="text/javascript"></script>
<div id="pnp-test"></div>
```

Does it run if you make no changes in main.ts?

**Comment by wilecoyotegenius** [comment]
I have just cloned a main repo, and ran without making any changes to main.ts. Unfortunately, code does not get triggered either. I am using exactly the same script as you in my script editor webpart. And pnp.js is correctly referenced on a page:

![image](https://user-images.githubusercontent.com/22167638/187463382-d44833ad-130d-40ca-a643-403aea287394.png)

I have tried adding breakpoint in multiple places in pnp.js. When I put one in a first lines of pnp.js, breakpoint gets hit (resolves to universalModuleDefinition by source maps). However, when I put a breakpoint somewhere later in the file, it's not triggering. Tried breakpoints in 20-30 places in different sections of the file - sourcemaps look up the actual source files correctly, but they're somehow not executing,

**Comment by patrick-rodgers** [comment]
Are [custom scripts](https://docs.microsoft.com/en-us/sharepoint/allow-or-prevent-custom-script) turned off?

**Comment by wilecoyotegenius** [comment]
Custom scripts are on:

![image](https://user-images.githubusercontent.com/22167638/187650984-42383625-7241-4ca3-9955-527720e5c50b.png)

**Comment by patrick-rodgers** [comment]
If the script is loading in the page correctly, and being served correctly, I am not certain what more help we can offer. You might see if there are any extensions, anti-virus things, or something blocking script execution. As you mentioned the source maps are even resolving correctly so it doesn't seem like an issue with the library or the debug serve.

**Comment by wilecoyotegenius** [comment]
Okay, I got it working, although it's more of a workaround than a long term solution. 
I each time webpack dev server generates pnp.js, I copy it's contents (along with pnp.js.map) and upload to site assets.
Once files are served from site assets, code executes without any issues.

Thank you again for your help.
