### ISSUE TITLE
how to get a drive and a driveitem from a sharepoint site using graph

### ISSUE THREAD

**Issue by russgove** [pnp/pnpjs#2386]
### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   3.6.0      ]

Please specify what version(s) of SharePoint you are targeting: [     SPO    ]

### Expected / Desired Behavior / Question
According to the docs at https://pnp.github.io/pnpjs/v1/graph/docs/sites/#get-all-of-the-drives

i shouild be able to use this code to get all the drive/libraries in a site
const xxx=await graph.sites.getById(props.context.pageContext.site.id.toString()).drives()

my imports include 
import { graphfi, SPFx as SPFxGR } from "@pnp/graph";
import "@pnp/graph/";
import "@pnp/graph/groups";
import "@pnp/graph/sites";
import "@pnp/graph/teams";
import "@pnp/graph/users";

import { SPFI, spfi, SPFx } from "@pnp/sp";
import "@pnp/sp/folders";
import "@pnp/sp/items";
import { IItem } from "@pnp/sp/items";
import "@pnp/sp/lists";
import "@pnp/sp/security";
import { IRoleDefinitionInfo, PermissionKind } from "@pnp/sp/security";
import "@pnp/sp/security/web";
import { ISiteUserProps } from "@pnp/sp/site-users/types";
import "@pnp/sp/site-users/web";
import "@pnp/sp/sites";
import "@pnp/sp/views";
import { IViewInfo } from "@pnp/sp/views";
import "@pnp/sp/webs";

What am I doing wrong?

### Observed Behavior
When i put that code in my solution I get a compile error saying Property 'drives' does not exist on type 'ISite'.

**Comment by juliemturner** [comment]
I haven't looked further but I can see right away you shared a documentation page from v1... this is the updated documentation on getalldrives.  https://pnp.github.io/pnpjs/graph/onedrive/#get-all-of-the-drives

**Comment by juliemturner** [comment]
Also based on your imports you're not listing onedrive as an import in the graph area.

**Comment by russgove** [comment]
thanks Julie,
I will have a look at the right docs tomorrow and get back to you if I still have issues…
Russell

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
