### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'pageContext')

### ISSUE THREAD

**Issue by cardinalpipkin** [pnp/pnpjs#2388]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [ Y ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ ^3.6.0 ]

Please specify what version(s) of SharePoint you are targeting: [  1.15.0       ]

I'm attempting to use the pnpjs-config.ts config file to create a reuseable sp.web.lists etc.. so I can easily use REST CRUD operations in an SPFX webpart. I have followed the[ youtube tutorials](https://www.youtube.com/playlist?list=PLR9nK3mnD-OWvmtj9TKE6tM7ZrUosV_vB) and also read the [documentation ](https://pnp.github.io/pnpjs/concepts/project-preset/)thoroughly.

When using ```gulp serve --nobrowser``` with the URL: ```https://myDomain.sharepoint.com/sites/myApps/Caps/_layouts/15/workbench.aspx``` I get the error:
```TypeError: Cannot read properties of undefined (reading 'pageContext')```
And no data is read from SharePoint Online.
I'm obviously doing something wrong - can anyone help please?

I have provided a public repo of the code I'm using here:
https://github.com/cardinalpipkin/sppnp

**Comment by patrick-rodgers** [comment]
Had a look at this and found the issue. In your [utils.tsx](https://github.com/cardinalpipkin/sppnp/blob/master/src/webparts/sppnp/utils.tsx#L8) you are executing the highlighted line outside any function/lifecycle so it is executed when the code is first loaded. That doesn't allow the context to be set in the init, so the _sp in the utils.tsx closure is always going to fail as it gets an SP without a context set. I fixed this by moving the call inside the ReadListItems method closure to ensure it is run after the init is run.

```TS
export const ReadListItems = async (listName: string, filter?: string) => {

    const _sp = getSP();

...
}
```

**Comment by cardinalpipkin** [comment]
@patrick-rodgers - thanks. So if I want to add more functions to that utils.tsx, then would each function need const _sp = getSP() within it?

**Comment by patrick-rodgers** [comment]
That would be one way to do it and certainly the easiest way. You would just need to ensure that init runs before any subsequent calls to `getSP`.
