### ISSUE TITLE
MSAL + SP + Browser authentication and 401 Error

### ISSUE THREAD

**Issue by frankmatull** [pnp/pnpjs#2399]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   3.7.0     ]

Please specify what version(s) of SharePoint you are targeting: [    Sharepoint Online     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Question

I'm trying to get MSAL + SP + Browser authentication working, to be able to read and write to Sharepoint lists.  

I have done an App Registration, and have set it up for Implicit Flow with both:  Access tokens and 
ID tokens boxes checked. 

I also included a Single Page Application Redirect URL with the  https url where the request is originating from.

I set things up based on the documentation:

import { spfi, SPBrowser } from "@pnp/sp";
import { MSAL } from "@pnp/msaljsclient";
import "@pnp/sp/webs";
import { Configuration, AuthenticationParameters } from "msal";

const configuration: Configuration = {
  auth: {
    authority: "https://login.microsoftonline.com/[my tenant id here]/",
    clientId: "[my client id here]"
  }
};

const authParams: AuthenticationParameters = {
  scopes: ["https://graph.microsoft.com/.default"] 
};

const sp = spfi("https://[my tenant name here].sharepoint.com/sites/[my site name here]").using(SPBrowser(), MSAL(configuration, authParams));

const webData = await sp.web();

When I do this get a 401 error:  Uncaught (in promise) Error: Error making HttpClient request in queryable [401]  ::> {"error_description":"Exception of type 'Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException' was thrown."}

But when I go to the actual url for the request I do get the content output to the browser (as I am logged in).  

I don't know if I need to change the scopes in the AuthParams?  I did try adding the following API delegated permissions to the App Registration -> API Permissions to include Microsoft Graph:   openid, profile, Sites.Manage.All, Sites.Read.All, Sites.ReadWrite.All, User.Read.

But still get the 401 error.  Not sure what I'm missing here and any insight would be greatly appreciated...

**Comment by juliemturner** [comment]
Your issue I think is that you're giving graph permissions, and saying the scope is graph when in fact you're trying to make a SharePoint api call.  

I believe if you've given delegated SharePoint permissions in your app registration and you either add or replace these scopes settings to "https://{yourtenant}/sharepoint.com/.default" it would probably work... 

```typescript
const authParams: AuthenticationParameters = {
  scopes: ["https://graph.microsoft.com/.default"]
};
```
but I don't have exactly the full picture so maybe not.

**Comment by frankmatull** [comment]
Thanks so much for your help., by using:  https://{yourtenant}/sharepoint.com/.default in the scopes it works now. I had tried some other ways for a sharepoint scope, but didn't realize I needed to have my tenant in the url of the scope.
