### ISSUE TITLE
Is there a way to get the default ComplianceTag for a library

### ISSUE THREAD

**Issue by mikezimm** [pnp/pnpjs#2400]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    latest     ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]

### Expected / Desired Behavior / Question
I would like to be able to get the default label setting for a library as shown here.

I know there is a property on the file level such as _ComplianceTag... I'm looking to just see what that default setting is on all the libraries in a site.

![image](https://user-images.githubusercontent.com/49648086/189505305-fe0f5453-66ea-4c71-adad-2362bbfd9091.png)

**Comment by juliemturner** [comment]
I'm not sure what the question is?

**Comment by mikezimm** [comment]
> I'm not sure what the question is?

Hi @juliemturner , We are starting to use labels at our company and would like an easy way:
To show a site owner a list of all their libraries with the default library label as shown in the screenshot above.

## So the web part would show something like this:

**Library**                      **Default Label**
Documents               GEN-10
Other Library            HUM-10

GEN-10 and HUM-10 are just some examples of our Labels for retention.

I know pnpjs can help me get a list of libraries from the site along with typical properties like Title, versioning, etc...

What I can't figure out is how to get that library setting.  Since I do not see it when I use select '*', I'm guessing I need to add that specific property but do not know what it is.

Does that help?

**Comment by juliemturner** [comment]
It does, although I don't know the answer either I'd have to research it.  I'll mark this as a coding request maybe someone in the community has already figured it out.

**Comment by bcameron1231** [comment]
The only method I'm aware of is to use the Policy APIs. This method is used in the O365 CLI to get the Compliance Tag. 

Check out this file at line 106 for the REST implementation
https://github.com/pnp/cli-microsoft365/blob/4bd430dfd6cb1e3a52b73595e2e3971760b0c3a7/src/o365/spo/commands/list/list-label-get.ts

**Comment by mikezimm** [comment]
@bcameron1231 ,
Thanks for the hint.  

Sure would be nice though to be able to get it right on the lists object so we could get an easy picture of the entire site.
'We' meaning the site owners who I don't think have access to the compliance center.

But I will try to use it in the next web part idea I have.

For reference, this is my Contents web part where I would try to use it.
Just not sure how I would batch that request for cases where you have 20+ libraries. :(

![image](https://user-images.githubusercontent.com/49648086/194938164-906cfc33-8b7c-4c66-8008-01263b261d97.png)

**Comment by patrick-rodgers** [comment]
We can have a look at adding some support here - I haven't used this API previously so will need to investigate.
