### ISSUE TITLE
Updating file's extension

### ISSUE THREAD

**Issue by Karolis-Stoncius** [pnp/pnpjs#2401]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.8.0]

### Question
How do I update library file's extension?

### Observed Behavior
Changing the `FileLeafRef` only changes file's name and updating the file's content (with `getFileByServerRelativeUrl(url).setContentChunked(file)`) only changes the content.

**Comment by Karolis-Stoncius** [comment]
Basically yeah. When first uploaded this file was .txt, but I have a webpart, which updates the file item's info and the file content itself. When the file is changed to an image, this happens (because the extention is still .txt I presume) 
![image](https://user-images.githubusercontent.com/108655466/190192685-e2282160-6b14-4868-8bfb-9bf7305b3ba5.png)

**Comment by juliemturner** [comment]
Yeah I hear you but that's really not the way to go about solving that issue... what you want is more to replace the item with a new item and delete the old one....

**Comment by juliemturner** [comment]
And the issue you're showing me seems like an encoding problem but given the thing you're trying to do that may not be the case.  Have you tried uploading the new file into its own new item and has that worked...start there.  But I also would like to see you rethink the architecture of your solution.

**Comment by Karolis-Stoncius** [comment]
Yeah, I thought about that. Was just wondering if it's possible to avoid creating a new item.

**Comment by juliemturner** [comment]
I would validate that you have the syntax right by trying to upload the replacing file into a new item... if that works then yeah I'd say replacing the item in that drastic a manner isn't going to work.... but I also haven't tried playing around with it.

**Comment by Karolis-Stoncius** [comment]
I will take a look next week. Closing this for now
