### ISSUE TITLE
Get resulting file from copyByPath

### ISSUE THREAD

**Issue by Leif-Frederiksen** [pnp/pnpjs#2402]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [      3.7.0   ]

Please specify what version(s) of SharePoint you are targeting: [      SharePoint online   ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I use copyByPath to copy a file from one sitecollection to another. I need to grab the resulting file and do something with it (for example open it, so the user can edit the file). How can I get a hold of the new file? The result returned from the copyByPath operation is not very informative.

**Comment by juliemturner** [comment]
If you're using copy by path then you're essentially providing the url for the destination, so then you can open the file by using that url.

https://pnp.github.io/pnpjs/sp/files/#copy-by-path
and then either:
https://pnp.github.io/pnpjs/sp/files/#getfilebyurl
or
https://pnp.github.io/pnpjs/sp/files/#filefromserverrelativepath

**Comment by juliemturner** [comment]
Yep, good point @patrick-rodgers that would be something like returning a invokable method prepopulated with https://pnp.github.io/pnpjs/sp/files/#filefromserverrelativepath

**Comment by patrick-rodgers** [comment]
Just merged this, will be part of the next nightly build and v3.8 when we do that release. Thanks!
