### ISSUE TITLE
Not able to fetch sharepoint online list items using "@pnp/sp@3.6.0"

### ISSUE THREAD

**Issue by GirishGulve** [pnp/pnpjs#2403]
### Category
- [ ] Bug

### Version

Please specify what version of the library you are using: [ 3.6.0 ]

Please specify what version(s) of SharePoint you are targeting: [  Online  ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
When I am trying to fetch SharePoint list items, I'm getting below response -
Proxy {moments: {…}, observers: {…}, _onProxy: null, _emitProxy: Proxy, _inheritingObservers: true, …}

### Steps to Reproduce

let sp: SPFI;
sp = getSP(this.context);
const items = sp.web.lists.getByTitle(listName).items .select("ID","Title")

**Comment by aaademosu** [comment]
That's the correct behaviour. You need to invoke the object returned. See code change

```js
const items = await sp.web.lists.getByTitle(listName).items.select("ID","Title")()
```

**Comment by GirishGulve** [comment]
@aaademosu 
Thanks for the response. It worked
Silly mistake from my end.
