### ISSUE TITLE
Get size of Folder

### ISSUE THREAD

**Issue by JarialAnkur** [pnp/pnpjs#2404]
### Category
- [ ] Question

Please specify what version of the library you are using: [ 3.5.1 ]

Please specify what version(s) of SharePoint you are targeting: [    1.15.0     ]

### Expected / Desired Behavior / Question
How can I get the size of a folder in the SharePoint Document Library? 
I am getting the size of Files using the API request by passing Length in the "select" query parameter. But I am unsure how to get the size of folders from API.
Passing length in the "select" query parameter of the "getFolderByServerRelativeUrl" API is not helping.
API that I am using to get the folders is getFolderByServerRelativeUrl

**Comment by patrick-rodgers** [comment]
Turns out there is, but we don't include it in the interface currently for IFolder. Storage Metrics will give you sise information. We'll look at adding it to the library for the next release.

```TS
  const w = await sp.web.getFolderByServerRelativePath("/sites/dev/shared documents/target")
  .expand("StorageMetrics").select("StorageMetrics")();
```

**Comment by JarialAnkur** [comment]
Thank you so much @patrick-rodgers. You saved the day for me. It will be great to see this in the next version.

**Comment by patrick-rodgers** [comment]
Just merged this, will be part of the next nightly build and v3.8 when we do that release. Thanks!
