### ISSUE TITLE
Access SharingAllowedDomainList   for a site using pnpjs

### ISSUE THREAD

**Issue by russgove** [pnp/pnpjs#2405]
### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ latest     ]

Please specify what version(s) of SharePoint you are targeting: [   online      ]
Is it possible to get the SharingAllowedDomainList  for a site collection using pnpjs? You know the list that specifies what domains the site can be shared with.

**Comment by russgove** [comment]
I think i found it in ItenantSiteProperties in the sp-admin package, so i guess the question is what permissions does the user need to access this api. I want to let site owners see whats alloed.

**Comment by juliemturner** [comment]
The title sort of tells you the answer, you need to be a SharePoint admin to access those endpoints.

**Comment by russgove** [comment]
yup, thanks
