### ISSUE TITLE
getting files from library with filter on list item properties 

### ISSUE THREAD

**Issue by hamedy** [pnp/pnpjs#2411]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

SP Online

### Expected / Desired Behavior / Question

I'm wondering if it's possible to get files from a library and apply a filter on the associated list item properties? 
something like:
sp.web.getFolderByServerRelativePath("/sites/test/documents").files.filter("Title eq 'test'").getAll()

thanks, 
Hamed

**Comment by juliemturner** [comment]
No I wouldn't think it would as Files are not ListItems... You'd have to get the list items with that filter and then get their corresponding files. You probably can get the files by batch after, but I haven't tested that.

**Comment by patrick-rodgers** [comment]
You might can do something with expands - not sure, what else have you tried?

**Comment by patrick-rodgers** [comment]
I had a few minutes, this works:

```TS
const r = await sp.web.getFolderByServerRelativePath("/sites/dev/shared documents").files
    .select("ListItemAllFields/Title")
    .expand("ListItemAllFields")
    .filter("substringof('Updated', ListItemAllFields/Title)")();
```
with your values:

```TS
const r = await sp.web.getFolderByServerRelativePath("/sites/test/documents").files
    .select("ListItemAllFields/Title")
    .expand("ListItemAllFields")
    .filter("Title eq 'test'")();
```

We do not currently support a `getAll` for files like we do for items.

**Comment by hamedy** [comment]
thanks a lot, I'll test it out

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
