### ISSUE TITLE
getAllChildrenAsOrderedTree not returning copied/reused terms

### ISSUE THREAD

**Issue by ohermans1** [pnp/pnpjs#2414]
Hi team, this is my first ever issue, so please let me know if any additional information is required.

Related to - https://github.com/pnp/pnpjs/issues/1950, but I couldn't see a resolution there, so I though I might create a new one. I'm relatively new to the SharePoint world, so apologies if I'm missing something obvious. 

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.7.0 ]

Please specify what version(s) of SharePoint you are targeting: [ Sharepoint Online ]

### Expected / Desired Behavior / Question
I am currently using getAllChildrenAsOrderedTree on a web part. Everything works fine with general terms, but when reused terms are used, nothing is returned. 

Once I copy a term set, the original terms still work, but the new copied version does not. 
![image](https://user-images.githubusercontent.com/50157976/193151478-988ac85a-cef5-47c9-89df-4319bff03437.png)

`  const childTree: IOrderedTermInfo[] = await sp.termStore.sets
      .getById(props.processZoneTermSetId)
      .getAllChildrenAsOrderedTree({ retrieveProperties: true });
    console.log("🚀 ~ file: ProcessZonesSelector.tsx ~ line 45 ~ getTerms ~ childTree", childTree);`

### Observed Behavior
I would expect the ordered term tree to be returned regardless of whether the terms are reused or not.

### Steps to Reproduce
1. Create a termset
2. Copy the termset
3. Try to retrieve the tree for both using getAllChildrenAsOrderedTree - You will notice that only the original termset works.

**Comment by ohermans1** [comment]
Thanks for adding these labels @patrick-rodgers. Feel free to reach out if you need anything from me!

**Comment by patrick-rodgers** [comment]
This is working as intended - the method `getAllChildrenAsOrderedTree` uses the `children` part to load the terms under the set. These copied terms are not considered children of that set, so they are not returned. Using "terms" instead would get ALL the terms under the set - but would be a breaking change to the `getAllChildrenAsOrderedTree` so we can't just do that.

Is anything blocking you from using `terms` to get the terms under the set?

I guess we could have another method to get all the terms under the set as ordered tree but this is the first time its come up. Is this supporting a real-world scenario or just something you found in testing?

**Comment by patrick-rodgers** [comment]
Talked with @juliemturner this morning and we are going to add a second method `getAllTermsAsOrderedTree`. It *should* behave how you expect here, we'll need to test to ensure, but then you will be able to use that to (I hope 😄) get all the terms and not just the direct children. Calling pattern should be the same. Will update once I can spend some time there. Thanks for opening this issue, not something we had caught before.

**Comment by ohermans1** [comment]
Hey @patrick-rodgers - Thanks for the update. 

This has come up from a real world application, I most likely could use `terms`, but a `getAllChildrenAsOrderedTree` type method is preferred - as I require a ordered tree of all the children. 

Happy to test the new `getAllTermsAsOrderedTree `if needed :)

**Comment by patrick-rodgers** [comment]
After investigating this I decided it is a bug in the original getAllChildrenAsOrderedTree. So I fixed that. It turns out calling .terms on the set gives you all the top level terms, and then you can drill down into those. Please give that a try in the next release, in my limited testing it is fixed. If it works I want to come back and do some optimization on the method, but want to see if the fix works first. Thanks!

**Comment by ohermans1** [comment]
Hi @patrick-rodgers - thanks so much for investigating this for me. 

I have updated to v3.8 and have run a little testing on my end and have run across some potentially odd behavior. 

First of all, for some context, for this test I am creating an ordered list using the following:
![image](https://user-images.githubusercontent.com/50157976/196073265-48d31a91-4c1e-4f0f-91da-92b70adf94fd.png)

Which is pointed to the 'Process Zone' termset
![image](https://user-images.githubusercontent.com/50157976/196073307-93bafca3-9001-4a80-ab47-8a684cf119b5.png)

What I'm finding when I run this code and print it to the console is that 'Child 1' and 'Child 2' are appearing at the top level, rather than under 'Term 3', but this doesn't seem to occur for 'Term 1.1' and 'Term 1.2' (Which sit as expected under 'Term 1')

![image](https://user-images.githubusercontent.com/50157976/196073838-5c49efed-959e-4fb3-804d-db2b91ff0a7b.png)



Any ideas?
