### ISSUE TITLE
CRUD to SharePoint list without SPFx or ClientID authentication

### ISSUE THREAD

**Issue by divewoot** [pnp/pnpjs#2415]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ @pnp/sp 2.11.0  ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint in Microsoft 365 ]

### Question
With an existing React App (basic form) that is loaded to a SharePoint page via a Content Editor WebPart . . . is there sample code for how to add in CRUD operations to a SharePoint list to be used with the form? Constraints are 1) cannot use SPFx to deploy 2) cannot use clientID for authentication (user is already authenticated on the page where the React App is loaded via the Content Editor WebPart).

This code was used for a similar use case (no SPFx and no clientID for authentication) 5 years ago but no longer works with current PnP libraries. 

```
import pnp from 'sp-pnp-js'

export default class SharePointService
{
    static GetListItems(listTitle:string):any
    {
        return pnp.sp.web.lists.getByTitle(listTitle).items.orderBy("Title").get();
    }
    static AddListItem(listTitle:string, item:any):any
    {
        return pnp.sp.web.lists.getByTitle(listTitle).items.add(item);
    }
}
```

**Comment by patrick-rodgers** [comment]
Have a look at the [SPBrowser](https://pnp.github.io/pnpjs/sp/behaviors/#spbrowser) behavior and see if that works for you. You may need to somehow auth the requests, unsure how you have then signed in. Here is an example of [doing that with MSAL](https://pnp.github.io/pnpjs/concepts/authentication/#msal-sp-browser).

**Comment by divewoot** [comment]
using SPBrowser worked! 
having trouble getting await to work but set a timeout instead. this is the error when I use:
await sp.web()

"Module parse failed: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)"

this is what currently works:
 const sp = spfi().using(SPBrowser({ baseUrl: "https://mysite.sharepoint.com/sites/mytestsite" }));

setTimeout(function(){
  sp.web();
}, 1000);

**Comment by juliemturner** [comment]
You need to decorate your containing function with the async keyword.  Here's a basic tutorial on Async/Await and Promises: https://youtu.be/Bydi3zQY9xI

**Comment by divewoot** [comment]
that video was a HUGE help! Thank you.
