### ISSUE TITLE
What happened to the config-store package in version 2 ?

### ISSUE THREAD

**Issue by rogramko** [pnp/pnpjs#2416]
### Category
- [ ] Enhancement
- [ ] Bug
- [:heavy_check_mark:] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    pnp/pnpjs     ]

Please specify what version(s) of SharePoint you are targeting: [         ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

###  Question
pnpjs/version3/CHANGELOG.md
Why is there no information here that the config-store package has been removed or what it is?
For example, it says that the sp-addinhelpers package was removed in version 3; Okay nice. https://github.com/pnp/pnpjs/blob/1dc5a133d93702099072d65a5493777f686ec49a/CHANGELOG.md?plain=1#L321

**Comment by juliemturner** [comment]
I suspect it was an oversight, there were a lot of moving parts, and we absolutely could have missed adding that information to the change log.
