### ISSUE TITLE
IFolder: list all files inside a folder

### ISSUE THREAD

**Issue by sintetico82** [pnp/pnpjs#2417]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    @pnp/sp  3.6.0     ]

Please specify what version(s) of SharePoint you are targeting: [    SharePoint in Microsoft 365     ]

### Question

Hi, I just want to list all the files in a Document Library folder. How can I get this information starting from the `getFolderByServerRelativePath` the return an `IFolder` interface?

I am starting from this:

```
const folderUrl = "/sites/mySite/Documents title/folder inside document library root""

const folder : IFolder = sp.web.getFolderByServerRelativePath(folderUrl)

// TODO: list all files in the folder ....

```
thank you

**Comment by patrick-rodgers** [comment]
Have you tried [`.files`](https://pnp.github.io/pnpjs/sp/files/#reading-files)?

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
