### ISSUE TITLE
[Enhancement] Add ThumbnailUrl to updateSiteDesign and createSiteDesign

### ISSUE THREAD

**Issue by kbeeveer46** [pnp/pnpjs#2418]
This property is missing from the PnP library but it exists in the Microsoft SharePoint PowerShell. This property is used to show a thumbnail instead of the default SharePoint image when selecting a template from your organizations as seen in this screen shot 
![image](https://user-images.githubusercontent.com/12972554/193485804-e5253f2a-3088-47ed-b96c-d9fa9b84ac80.png)

See the links below for information regarding the ThumbnailUrl property
[add-spositedesign](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/add-spositedesign?view=sharepoint-ps#-thumbnailurl)
[set-spositedesign](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spositedesign?view=sharepoint-ps#-thumbnailurl)

### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.7.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
A new property should be added to the interfaces ISiteDesignCreationInfo and ISiteDesignUpdateInfo which would then be used in the create and update site design methods.

**Comment by patrick-rodgers** [comment]
Added thumbnail url and some other new props not included.
