### ISSUE TITLE
 pnp js version[ "@pnp/sp": "^3.6.0"] : items.add using hooks error:"The security validation for this page is invalid and might be corrupted"

### ISSUE THREAD

**Issue by kandharithirumalreddy** [pnp/pnpjs#2423]
items.add using hooks error:
"The security validation for this page is invalid and might be corrupted"

 pnp js version is  [ "@pnp/sp": "^3.6.0"]

**Comment by juliemturner** [comment]
This issues is being closed because it did not follow any of our issue templates. If you are still having an issue related to the PnPjs library please submit a new issue and fill out the issue template as completely as possible providing examples and details so that we can assist you.
