### ISSUE TITLE
How to add a list item with verbose content

### ISSUE THREAD

**Issue by martinlingstuyl** [pnp/pnpjs#2426]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.6.0]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online ]

### Question
Say I have some JSON content that should be posted with `content-type: application/json;odata=verbose` and combined with ListItemEntityTypeFullName added to a `__metadata` property. How would I go about that?

I noticed a summary param in the types of `add()`, so I thought that might be the way into this. But the actual param cannot be set on the function:

```typescript
/**
 * Adds a new item to the collection
 *
 * @param properties The new items's properties
 * @param listItemEntityTypeFullName The type name of the list's entities
 */
add(properties?: Record<string, any>): Promise<IItemAddResult>;
```
This is found in `node_modules/@pnp/sp/items/types.d.ts`

**Comment by aaademosu** [comment]
You could do that by injecting into the headers during the setup phase. Refer to the sections of docs linked below.

https://pnp.github.io/pnpjs/sp/behaviors/#defaultheaders

https://pnp.github.io/pnpjs/core/behaviors/#composing-behaviors

**Comment by patrick-rodgers** [comment]
@aaademosu is correct. You can do something like:

```TS
{myQueryable}.using(InjectHeaders({
    "content-type": "application/json;odata=verbose",
}));
```

So long as it is added after the defaults it should take precedence and be the one that is sent.

For adding the `__metadata` part I think you would need to include it in your `properties` param.

Curious though - what is causing you to require having the metadata/verbose mode?

**Comment by martinlingstuyl** [comment]
Thanks @aaademosu, @patrick-rodgers,

This will get me up and running just fine! 

As for the reason:
I'm working on a bit of an edge case. I'm using a [Dynamic Form](https://pnp.github.io/sp-dev-fx-controls-react/controls/DynamicForm/) to prepare a new list item, but I want to post the data myself instead of letting the Dynamic Form do it. 
As it turns out, the form gives me the data in verbose form. Instead of changing the JSON-object before posting it, I'd like to just post it as it is.

**Comment by martinlingstuyl** [comment]
You can close this as answered, @patrick-rodgers.

**Comment by patrick-rodgers** [comment]
Awesome, glad its working for you!
