### ISSUE TITLE
sp.web.lists - how to select field values

### ISSUE THREAD

**Issue by divewoot** [pnp/pnpjs#2427]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  @pnp/sp 3.7.0  ]

Please specify what version(s) of SharePoint you are targeting: [  SharePoint in Microsoft 365  ]

### Question
with the following request and the console log, field values from the list are seen in the console but accessing those field values is not working as expected. The SPA react app will not be deployed using SPFx but rather is loaded from inside a Content Editor webpart. Here is the code for the console.log

```
   useEffect(() => {
    setLoading(true);
    try {
      const data = sp.web.lists
        .getByTitle("ProjectContacts")
        .items
        .expand("FieldValuesAsText")
        .select(
          "Title"
        )
        .top(5000)
        .orderBy("Title")
        ()
        ; //        <{Title: string}[]>
      setLoading(false);
      setData(data);
    } catch {
      console.log('sp.web.lists.getByTitle did not work')
    }
  }, []);
  if (data)
    console.log('some data was returned: ', data);
```

have tried several things all yield null:
data.promise
data[0]
data.values

**Comment by patrick-rodgers** [comment]
Couple of general points, and then I'll try and answer your question:

- Curious why you think you need 5000 items out of a list every time a page loads. At a minimum I'd cache it and revisit the requirement. Going to be a big performance hit.
- There are some recent articles about not using useEffect for async data fetching. I don't really have an opinion but might be worth reading and making your own call.

Now for your issue:

- How are you setting up/auth'ing the requests, you don't show any of that
- Is there a reason you are using this pattern? You could create an SPFx application or Teams app and avoid loading inside a content editor
- Regardless of all that you want an `await` for the data request. [See here for an example](https://pnp.github.io/pnpjs/sp/items/#basic-get)
- You also need to select "FieldValuesAsText" - just expanding it does not bring back the values.

This works for me:

```TS
  const data = await sp.web.lists
    .getByTitle("Generic")
    .items
    .expand("FieldValuesAsText")
    .select("Title", "FieldValuesAsText")();
```

**Comment by bcameron1231** [comment]
Just wanted to add some more information, if you add the await. You may be tempted to make the useEffect asynchronous, which you definitely wouldn't want to do. The reason people are against async calls in useEffects is because the hook should either return nothing, or a cleanup function. Calling _raw_ async methods in the useEffect actually makes it return a promise. It will have unintended consequences in your component flow, especially if a component unmounts before the async is completed.

Given that you are using an empty dependency array, I would wrap your calls in an auto invokable function before making the call.

At a minimum your code should look more like this.

  ```
 // initialize this when the component loads
  useEffect(() => {
    setLoading(true);
    (async () => {
      try {
        const data = await sp.web.lists
          .getByTitle("Generic")
          .items.expand("FieldValuesAsText")
          .select("Title", "FieldValuesAsText")();

        setLoading(false);
        setData(data);
      } catch {
        console.log("sp.web.lists.getByTitle did not work");
      }
    })();
  }, []);
 
```

Subsequent code quality notes I'd probably add.
1. I'd initialize your setLoading outside of the useEffect and directly in the component default set to true or if data
2. I'd make sure to setLoading(false) in the catch as well. Just in case you have areas in your code where this may be referenced.
3. It's also good practice to unmount the side effect... because _it is possible_ that as component could unmount before an async call is completed (the reason people say don't use asyncs in useEffect). Check out using AbortController to handle this.

**Comment by divewoot** [comment]
Thanks for all the great tips. How does this look for an approach? This code is working as expected and is loading only once as expected.

**Comment by bcameron1231** [comment]
Hi. Unfortunately your code still has some issues.  There is no need to have the firstLoad logic. The empty dependency array handles this in our useEffect. Additionally, moving the call outside the useEffect won't make a difference because it's still called within the useEffect which can have unintended consequences on your state. 

Checkout my latest update to my previous comment.  This is all you need to make sure you don't have any memory leaks or incorrect updates to unmounted states.

```
  useEffect(() => {
  //Assume we're still mounted
    let mounted = true;
    setLoading(true);
    (async () => {
      try {
        const data = await sp.web.lists
          .getByTitle("Generic")
          .items.expand("FieldValuesAsText")
          .select("Title", "FieldValuesAsText")();

        //make sure we are still mounted before updating state
        if(mounted){
            setLoading(false);
             setData(data);
        }
      } catch {
        console.log("sp.web.lists.getByTitle did not work");
      }
      
      //set mount to false to prevent updates to state if component unmounts
      return () => (mounted = false);
    })();
  }, []);
```

**Comment by divewoot** [comment]
Is this looking better?

>  const sp = spfi().using(SPBrowser({ baseUrl: "https://"+myTenant+".sharepoint.com/sites/"+mySite }));
> 
> 
> const SPListItems = () => {
>   let [jsxlistItems, setListItems] = useState([]);
>   
>   useEffect(() => {
>     //Assume we're still mounted
>       let mounted = true;
>       (async () => {
>         try {
>           let response = await sp.web.lists
>           .getByTitle('ProjectContacts')
>           .items
>           .expand("FieldValuesAsText")
>           .select(
>             "Title",
>             "FieldValuesAsText"
>           )
>           .top(10)
>           .orderBy("Title")
>           (); 
>           let items: any[] = [];
>           response.forEach(element => {
>             items.push({title: element.Title})
>           });
>           console.log('this is the title array: '+ items);
>           console.log('is this an array? '+ Array.isArray(items));
>           console.log('this is the title array json: '+ JSON.stringify(items))
>           //   const itemsj: string = JSON.stringify(items);
>           const jsxlistitems = items.map((item) => 
>             <li>
>               {item.title}
>             </li>
>           );  
>           //make sure we are still mounted before updating state
>           if(mounted){
>             setListItems(jsxlistitems);
>           }
>         } catch {
>           console.log("sp.web.lists.getByTitle did not work");
>         }
>         
>         //set mount to false to prevent updates to state if component unmounts
>         return () => (mounted = false);
>       })();
>     }, []);
> 
>     return (
>       <>
>         <div>These are the PTN's returned from the SharePoint list: 
>           <ul>
>             <li>{jsxlistItems}</li>
>           </ul>
>         </div>
>       </>
>     )
> }
> 
> export default SPListItems;

**Comment by bcameron1231** [comment]
This looks better. A couple questions & thoughts

1. Where is your sp object being initialized? I hope it's the root of your Web Part .ts file and not in the component's file. If it's not in the root, this is a change I think you should make. You should initialize it in the root Web Part .ts file, and then access the context using getSP(). Then if you need access to another web, you can use the AssignFrom method outlined in the transition guide [here](https://pnp.github.io/pnpjs/transition-guide/#assignfrom-and-copyfrom). 

I've created a sample here that shows how to use the getSP() and the AssignFrom functions [here ](https://github.com/bcameron1231/sp-dev-fx-webparts/tree/custom-hooks-dynamic-passed-in-web/samples/react-pnp-js-hooks-sample)

2. **Recommended** - I wouldn't assemble your component html in the useEffect. Set your state data, and just render out that state data in the return. What you currently have is rendering out invalid html (you've nested an li inside of an li). It will clean up your useEffect a bit.

```
const SPListItems = () => {
    let [items, setListItems] = useState([]);
    
    useEffect(() => {
      //Assume we're still mounted
        let mounted = true;
        (async () => {
          try {
            let response = await sp.web.lists
            .getByTitle('ProjectContacts')
            .items
            .expand("FieldValuesAsText")
            .select(
              "Title",
              "FieldValuesAsText"
            )
            .top(10)
            .orderBy("Title")
            (); 

            //make sure we are still mounted before updating state
            if(mounted){
              setListItems(items);
            }
          } catch {
            console.log("sp.web.lists.getByTitle did not work");
          }
          
          //set mount to false to prevent updates to state if component unmounts
          return () => (mounted = false);
        })();
      }, []);
  
      return (
          <div>These are the PTN's returned from the SharePoint list: 
            <ul>
              {items.map((item) => {
                return (<li>{item.Title}</li>)
              })}
            </ul>
          </div>
      )
  }
```

**Comment by bcameron1231** [comment]
@divewoot  Have we resolved your issue?

**Comment by divewoot** [comment]
Yes issue resolved. Will continue to work on implementing the recommendations.
