### ISSUE TITLE
Graph paged behavior for list-items

### ISSUE THREAD

**Issue by trueleader** [pnp/pnpjs#2432]
### Category
- Enhancement
- Bug

### Version
Please specify what version of the library you are using: 3.7
Please specify what version(s) of SharePoint you are targeting: SPO

### Expected / Desired Behavior / Question
Return page-able list-items via graph after `.paged()` call

### Observed Behavior
Error response `$count is not supported on this API. Only URLs returned by the API can be used to page.`

### Steps to Reproduce
Try in graph explorer via sample tenant: `https://graph.microsoft.com/v1.0/sites/root/lists/ab8a20c1-2adc-4486-8088-16b77df6e767/items?$count=true`

It seems that only a limited set of graph endpoints support the [$count parameter](https://learn.microsoft.com/en-us/graph/query-parameters#count-parameter) which was added in [PR 2374](https://github.com/pnp/pnpjs/pull/2374).
Maybe `.paged()` method and `AsPaged(col)`+`Paged()` functions can get arguments to configure the $count usage.

**Comment by patrick-rodgers** [comment]
This is fixed and will be in the next release. Thanks for letting us know!
