### ISSUE TITLE
Batching always result in a null.

### ISSUE THREAD

**Issue by aveinca** [pnp/pnpjs#2437]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    3.3   ] //I'm not sure, used npm i a month ago

Please specify what version(s) of SharePoint you are targeting: [    SPO    ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
This is probably a dumb question, and I'm new to PnPJs but I can't seem to make batching works. 
In my code, I used a service class to get WebPartContext, in this class, there's a function to get several different-filtered items from a list. 

```typescript
export default class ServiceClass {
  private _sp: SPFI;

  constructor(private context: WebPartContext) {
    this._sp = spfi().using(SPFx(this.context)).using(PnPLogging(LogLevel.Warning));
  }
  public fetchMultiListsData =async (listName:string, folderName: string[], column:string[], filterString?: string, order?: string, orderAscending?: boolean, count?: number):Promise<any> => {
    
    const [batchedSP, execute] = this._sp.batched();
    
    folderName.forEach(async (folder) => {
      batchedSP.web.lists
      .getByTitle(listName).items
      .select(column.toLocaleString())
      .orderBy(order, orderAscending)
      .filter("FolderPath eq '" + folder + "'")
      .top(count)().then(r => result.push(r));
    })
    try {
      await execute();
    } catch(e){
      console.error(e);
    }
      
    console.log(result);
    return result;
  }
```
and in a WebPartClass, there's a function to get the result: 
```typescript
async componentDidMount(): Promise<void> {
    try {
      const result: any[] = await this._serviceClass.fetchMultiListsData(listName, folderName, columns, filterString, order, orderAscending, takeRecords);
    } catch(e) {
      console.error(e)
    }
}
```

### Observed Behavior
try and catch in the service class function never output anything, the error always come from the const result in the web part. It's always null, even when I tried to remove the filter. There's nothing wrong with the list on SPO because I used other get method and succeeded. 

On the network tab in workbench, when I put on the Web part, there's no Batch request, only some ReadOrCreateCache and WriteCache show up. 

![image](https://user-images.githubusercontent.com/66676165/195790388-49e95667-3d84-478c-9bca-4d1a5d33e7cf.png)

Maybe it's an error on my code. Please help.

**Comment by aveinca** [comment]
Thank you for helping, my Pnp/Js version is 3.8.0. But unfortunately, after changed the syntax to for, the results remained the same as before. Still null at the componentDidMount() function and the calls doesn't output anything. 

This is the code I used: 
```typescript
public fetchMultiListsData =async (listName:string, folderName: string[], column:string[], filterString?: string, order?: string, orderAscending?: boolean, count?: number):Promise<any> => {
    
    const [batchedSP, execute] = this._sp.batched();
    let result: any[];

    for (let i = 0; i < folderName.length; i++){
      batchedSP.web.lists
      .getByTitle(listName).items
      .select(column.toLocaleString())                        
      .orderBy(order, orderAscending)
      // .filter("FolderPath eq " + `${folderName[i]}`)
      .top(count)()
      .then(r => result.push(r));
    }

    await execute();
    for (let i = 0; i < result.length; i++){
      console.log(result[i]);
    }
    console.log(result);
    return result;
    }
}
```

**Comment by juliemturner** [comment]
I'm sorry, I can confirm that this is in general working, so I suspect there is something else wrong with your code.  If you could provide a full sample that replicates the problem, I may be able to help you further but without that in general I don't see an issue with your code that jumps out at me.

**Comment by aveinca** [comment]
@juliemturner Oh now it works! Turns out I was missing a line to get WebPartContext in the webpart. Now it's running fine. Thank you for taking your time helping me.
