### ISSUE TITLE
Search Query with Refinement Filters - string vs array

### ISSUE THREAD

**Issue by cverhelst** [pnp/pnpjs#244]
### Category
- [ ] Enhancement
- [*] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   @pnp/sp@1.2.1      ]

### Expected / Desired Behavior / Question
When using sp.search and the SearchQueryBuilder to query search with refinement filters using an array with 1 string value, the array format should translate as such correctly to the request body ( RefinementFilters > results > array of 1 string )
![image](https://user-images.githubusercontent.com/1067868/45689139-771eff80-bb53-11e8-822e-8e6283ce0749.png)

### Observed Behavior
When using sp.search and the SearchQueryBuilder to query search with refinement filters using an array with 1 string value, the array format does not translate as such correctly to the request body ( RefinementFilters > results > string )
![image](https://user-images.githubusercontent.com/1067868/45689590-ae41e080-bb54-11e8-9d74-490a4a219f2f.png)

### Steps to Reproduce

1. Build a search query using SearchQueryBuilder.
2. Set the refinement filters using .refinementFilters("myRefinementFilter")
![image](https://user-images.githubusercontent.com/1067868/45689339-04625400-bb54-11e8-8ab7-782ae44270e3.png)
3. Convert to a search query using .toSearchQuery()
4. Initiate the query using sp.search(searchQuery)
5. Observe the post request body in the browser dev tools

**Comment by cverhelst** [comment]
I don't have this issue with @pnp/sp@1.1.2 and relevant common/odata packages of the same version

**Comment by patrick-rodgers** [comment]
Can you share the code you are using that generates this error? Thanks!

**Comment by patrick-rodgers** [comment]
Nevermind, I see what happened here. Sorry about that, it is a regression from refactoring the SearchQueryBuilder. Working on a fix.

**Comment by patrick-rodgers** [comment]
If you get a chance can you pull down and test the fix in [this PR](#246)? I think this is resolved in that change.

**Comment by cverhelst** [comment]
Not proficient with GitHub pull requests and didn't manage to use this PR in my project without a bunch of errors, I'm probably doing it wrong (I used GitHub desktop to get the version with the specific pr, then "linked" to that repo's individual packages folder).

I'll wait for the 1.2.2 release :). Thx for the quick reply & action!
