### ISSUE TITLE
How to delete a term from term store using PnP JS

### ISSUE THREAD

**Issue by miguelisidoro** [pnp/pnpjs#2444]
- [ ] Enhancement
- [ ] Bug
- [ X ] Question
- [ ] Documentation gap/issue

Please specify what version of the library you are using: [     2.12.0    ]

Please specify what version(s) of SharePoint you are targeting: [      SharePoint Online   ]

Hello,

How can we delete a term from a term store using PnP JS?
I took a look at https://pnp.github.io/pnpjs/sp/taxonomy/ and found nothing,

Can you help?
If it is not possible, what is the alternative? Call SharePoint REST API? Call old SOAP web services from javascript?

Thanks

**Comment by patrick-rodgers** [comment]
We currently haven't implemented any of the taxonomy stuff for CUD parts of CRUD. When the API was first available those operations were not yet available. We can have a look and see if they are now and add implementation.

**Comment by miguelisidoro** [comment]
That would be great.
Found out that Graph API allows term deletion: https://learn.microsoft.com/en-us/graph/api/termstore-term-delete?view=graph-rest-1.0&tabs=http

Will use this approach since PnP JS still doesn't allow CUD operations for taxonomy operations.

Thanks

**Comment by juliemturner** [comment]
You can either use the SPFx built-in Graph client: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial

or you can manually extend the library by issuing the command this way:

```TypeScript
await graphDelete(GraphQueryable("URL TO TERM")
        .using(GraphDefault({
            msal: {
                config: settings.testing.graph.msal.init,
                scopes: settings.testing.graph.msal.scopes,
            },
        }))
    );
```

**Comment by patrick-rodgers** [comment]
Added support for the various operations Add/Update/Delete as supported by the API, will be part of 3.10

**Comment by miguelisidoro** [comment]
Thanks @patrick-rodgers! It is an important improvement to PnP JS!
