### ISSUE TITLE
Error: No observers registered for this request. Web(siteURL).lists.getbytitle("listname").items.add({})

### ISSUE THREAD

**Issue by leodak** [pnp/pnpjs#2449]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [        "@pnp/common": "^2.14.0",
    "@pnp/graph": "^3.8.0",
    "@pnp/logging": "^3.8.0",
    "@pnp/sp": "^3.8.0", 
"Yeoman Generator version": "1.15.2",  
node: 16.17.0   ]

Please specify what version(s) of SharePoint you are targeting: [     SharePoint Online    ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Observed Behavior

```
Uncaught (in promise) Error: No observers registered for this request. (https://pnp.github.io/pnpjs/queryable/queryable#No-observers-registered-for-this-request)
    at Proxy.execute (queryable.js:83:1)
    at Proxy.start (timeline.js:135:1)
    at Proxy.post (operations.js:8:1)
    at op (operations.js:20:1)
    at spPost (operations.js:5:38)
    at Proxy.add (types.js:60:22)
```

Above error occurs at items.add(item) line in the below method

tried both of the imports

    import { Web } from "@pnp/sp/webs"; 
    import { IItemAddResult, IList, Web } from "@pnp/sp/presets/all";

    public async addItem<T>(item: T, listName: string, siteURL: string): Promise<IItemAddResult> {  
        let siteWeb = Web(siteURL);
        return await siteWeb.lists.getByTitle(listName).items.add(item);
    }

### Steps to Reproduce
Add SPO list item in another site collection using the above method

**Comment by patrick-rodgers** [comment]
Please see [this section](https://pnp.github.io/pnpjs/sp/webs/#access-a-web) a bit down from that link is a section "Access a web using the Web factory method" should have the info you need. Please let us know if that helps.

**Comment by leodak** [comment]
I have used this and it didn't throw me any error.
`const siteWeb = Web(siteURL).using(CopyFrom(this._sp.web));
`
