### ISSUE TITLE
Copy/Create Search object results in undefined _root exception

### ISSUE THREAD

**Issue by mdissel** [pnp/pnpjs#2450]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [X] Documentation gap/issue

### Version

3.8

Please specify what version(s) of SharePoint you are targeting: [         ]

Sharepoint Online

### Expected / Desired Behavior / Question
Inside a webpart I'm using the webpart context to create the sp object like this:
`sp = spfi().using(SPFx(context)).using(PnPLogging(LogLevel.Warning));`

In other classes I can use the `sp.search` method to run a sharepoint seach, but this not working:
```
const searcher = sp.search;
const result = await searcher(querybuilder);
```
this results in the exception (at the line see below): 
```
TypeError: Cannot read properties of undefined (reading '_root')
    at _fi_js__WEBPACK_IMPORTED_MODULE_0__.SPFI.search (index.js:8:18)

```
![image](https://user-images.githubusercontent.com/126084/197388797-2f9548cb-49cc-48c3-a5ef-608bf1d212bd.png)

We get the same error when we want to create a new Search instance via:
`const search = Search("http://xxxx.sharepoint.com/sites/search");`

In the end this is the helper function that we try to get working:
```
	async getSearcher() :Promise<ISearch> {
		if (this._searcher === null){
			const settings = await .getSettings();
			if (settings.advancedSearch.searchUrl)){
				this._searcher = Search(this.getUrl(settings.advancedSearch.searchUrl));
			} else {
				this._searcher = this.sp.search;
			}
		}
		return this._searcher;
	}
```

**Comment by patrick-rodgers** [comment]
### const searcher = sp.search;
I am not sure you can destructure the library like that and have it work. The `searcher` function loses the "this" from which it initializes. 

### const search = Search("http://xxxx.sharepoint.com/sites/search");
This doesn't work because Search is a bit of a special case optimized to make the fluent UI easier to invoke the search request.

So - can you describe a bit more on what you want to achieve? What is your scenario? With that we can see how best we can help.

**Comment by mdissel** [comment]
> `const searcher = sp.search;`
> I am not sure you can destructure the library like that and have it work. The `searcher` function loses the "this" from which it initializes.

I'm currently recreating the full object, that seem to work, but wonder if there's quicker way (this.sp.web contains an authenticated instance via the SPFXContext)

```
async search(queryInit: SearchQueryInit): Promise<SearchResults>{
  if (settings.advancedSearch?.searchUrl)) {
	return await spfi(this.getUrl(settings.advancedSearch.searchUrl)).using(AssignFrom(this.sp.web)).search(queryInit);
  }
  return await spfi(this.getRoot()).using(AssignFrom(this.sp.web)).search(queryInit);
}
```

> 
> ### const search = Search("http://xxxx.sharepoint.com/sites/search");
> This doesn't work because Search is a bit of a special case optimized to make the fluent UI easier to invoke the search request.

I'm just following the documentation, see https://pnp.github.io/pnpjs/sp/search/#search-factory.. 

> 
> So - can you describe a bit more on what you want to achieve? What is your scenario? With that we can see how best we can help.

See my last helper function sample for what my goal is. This function will be called from various places where we execute a search request. In some setups we will use a special sitecollection that contains a different search configuration.

**Comment by patrick-rodgers** [comment]
Oh and yes, those docs are fully wrong for v3 - we missed it in the transition, will get those updated as well.

**Comment by patrick-rodgers** [comment]
Ok, updated Search and Suggest to be true invokable factories, so they will work how you expect now. Updated the search and searchSuggest method logic. As well updated the docs so they now reflect reality.
