### ISSUE TITLE
Using PnP to read/write to M365 list in Onedrive

### ISSUE THREAD

**Issue by raytri** [pnp/pnpjs#2453]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     3.8    ]

Please specify what version(s) of SharePoint you are targeting: [    Online     ]

### Expected / Desired Behavior / Question

Does PnPJS support reading/writing to M365 Lists saved in the **tenant-my.sharepoint.com/personal/{userid}** site collection?

I want to store user data in a custom list in each user's personal site, and be able to read/write to that list from an SPFX webpart or extension.

With Microsoft Lists, I can create a list and save it to "My Lists", which puts it in the personal site.

With **@pnp/graph**, I can access the OneDrive document library like this:

```
      const graph = graphfi().using( graphSPFx( this.context ) );
      const oneDrive = await graph.me.drive();
```
But this returns a blank array:

`     graph.sites();
`

If I try to use graph to get the site collection, I get a CORS error:

```
    const oneDriveCollection = graphfi( 'https://tenant-my.sharepoint.com/personal/{userid}' ).using( graphSPFx( this.context ) );
    const sites = await oneDriveCollection.sites();
```
And if I try to go the SP route, I get an "Attempted an unauthorized operation" error:

```
    const oneDriveCollection = spfi( 'https://tenant-my.sharepoint.com/personal/{userid}' ).using( spSPFx( this.context ) );
    const lists = await oneDriveCollection.web.lists();
```

**Comment by patrick-rodgers** [comment]
No idea, I have never tried. I'll have to see if there's a way.

**Comment by raytri** [comment]
Some follow up: I'm also trying an alternative method of reading/writing a text/json file to the OneDrive documents library. That seems like it should be straightforward, based on the documentation.

I have no problem reading data, but I get an "Access token is empty" error when I try to write.

Common code that successfully gets the drive and its id:

```
    const graph = graphfi().using( graphSPFx( this.context ) );
    const oneDrive = await graph.me.drive();
    const driveID = oneDrive.id;
```

This works, returning a children object containing all the items in the drive:

`    const children = await graph.me.drives.getById( driveID ).root.children();
`    
But using add() fails: 
`      const add2 = await graph.me.drives.getById( driveID ).root.children.add( "TestFile.txt", "Test content" );
`
The request URL:

`https://graph.microsoft.com/v1.0/me/drives/b!ym6UhosyjUOIP0DhDTyilJ9im400bfxPghtcjG396vmB4LcwSM-BTJvbc1R6FLqB/root:/TestFile.txt:/content?
`
The error message in inspector:

`Error: Error making HttpClient request in queryable [403] Forbidden ::> {"error":{"code":"accessDenied","message":"Access denied","innerError":{"date":"2022-10-26T15:00:59","request-id":"3e97b8b3-e434-4469-b19b-82a830f9539e","client-request-id":"3e97b8b3-e434-4469-b19b-82a830f9539e"}}}
`
The error message when I paste the API request URL in a browser:

`{"error":{"code":"InvalidAuthenticationToken","message":"Access token is empty.","innerError":{"date":"2022-10-26T15:21:46","request-id":"238bcc98-5eb1-4363-9741-d3d11d1fcaeb","client-request-id":"238bcc98-5eb1-4363-9741-d3d11d1fcaeb"}}}
`
Based on the documentation, I don't think I'm supposed to have to manually authenticate here.

**Comment by juliemturner** [comment]
Forbidden means the credentials you're using don't have access to that location, not that you're not authenticated... further you cannot paste a graph call in the browser it doesn't work only SharePoint API calls work directly in the browser because it requires an auth token for all calls.

I guess my only suggestion is that you haven't granted rights to Read/Write files through the application registration you're using. In SPFx that would mean adding webApiPermissionRequests to the package-solution and then making sure they are approved in the SharePoint admin center...

**Comment by raytri** [comment]
> Forbidden means the credentials you're using don't have access to that location, not that you're not authenticated... further you cannot paste a graph call in the browser it doesn't work only SharePoint API calls work directly in the browser because it requires an auth token for all calls.
> 
> I guess my only suggestion is that you haven't granted rights to Read/Write files through the application registration you're using. In SPFx that would mean adding webApiPermissionRequests to the package-solution and then making sure they are approved in the SharePoint admin center...

Thanks, that solved the problem of reading/writing to the OneDrive documents library!

**Comment by raytri** [comment]
Um, my initial question has not been answered, just the follow up.

**Comment by juliemturner** [comment]
Ok, sorry... in the future it's probably safer to submit your questions as separate issues.  I'll reopen this.

**Comment by patrick-rodgers** [comment]
Having done some research this is indeed possible to access Microsoft Lists in user's OneDrives. You need to:

set the MSAL scopes to the onedrive base url for the org:
```TS
msal.scopes = ["https://{tenant}-my.sharepoint.com/.default"];
```

set the base url of the requests to the OD of the user whose list you want to access:
```TS
url = "https://{tenant}-my.sharepoint.com/personal/{user OD path}";
```

Then you can use the library as you would expect:
```
sp.web.lists.getByTitle("{list title}")();
```

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
