### ISSUE TITLE
Batching Error "Invalid Response, line 8" in batching.js when using lists.getById(id).renderListDataAsStream()

### ISSUE THREAD

**Issue by NewGHUser4321** [pnp/pnpjs#2454]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.2.0

Please specify what version(s) of SharePoint you are targeting: SharePoint Online

### Expected / Desired Behavior / Question
There should be no errors when using batching with lists.getById(id).renderListDataAsStream()

### Observed Behavior
Getting an error in batching.js. When I see console tab in Chrome DEV tools, I see below error. The batch response in the dev tools network tab is successful with no errors.
![image](https://user-images.githubusercontent.com/105061286/197906621-8ddc4145-b5d7-424c-a3cf-051c973b1fb7.png)

Same thing with Advanced Batching as well. When I do individual renderListDataAsStream() requests, everything works as expected.

### Steps to Reproduce
Try to fetch data using batching and renderListDataAsStream()

**Comment by patrick-rodgers** [comment]
I am not sure if that is supported in batches, but we'll have a look. Thanks for reporting

**Comment by patrick-rodgers** [comment]
Got this working. Turns out that renderListDataAsStream returns a response with line breaks included. The batching logic was designed to understand batches whose bodies were on a single line. Updated the logic to collect the body across multiple lines and that seems to have fixed it. Also added a test to catch this in the future. Thanks!

**Comment by NewGHUser4321** [comment]
Could you suggest any workaround in my current version to overcome this issue?

**Comment by juliemturner** [comment]
You can use the nightly build tomorrow which will include the merged updates -> https://pnp.github.io/pnpjs/concepts/nightly-builds/

**Comment by NewGHUser4321** [comment]
Thank you.
