### ISSUE TITLE
Getting and reading files in the OneDrive Document library

### ISSUE THREAD

**Issue by raytri** [pnp/pnpjs#2455]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     3.8    ]

Please specify what version(s) of SharePoint you are targeting: [   Online      ]

### Expected / Desired Behavior / Question

This is both a question, and a call-out of some errors in the pnpjs/onedrive documentation, because they relate to my question.

##### Search
The sample code under "Search items" doesn't work for me:
https://pnp.github.io/pnpjs/graph/onedrive/#search-items

Both `const search =` lines have a typo -- a missing period before "root".

But even with that fixed, the code doesn't work. This gives a "search is not a function" error:

```
import { graphfi, SPFx as graphSPFx } from "@pnp/graph";
import "@pnp/graph/users";
import "@pnp/graph/onedrive";

const graph = graphfi().using( graphSPFx( this.context ) );
const search = await graph.me.drives.getById(driveID).root.search('queryText')();

```
##### Get specific item in drive
The sample code also doesn't work for me:
https://pnp.github.io/pnpjs/graph/onedrive/#get-specific-item-in-drive

After digging through the node files, it appears that this line:

`const item = await graph.me.drives.getById('driveId').items.getById('itemId');
`

Should instead read:

`const item = await graph.me.drives.getById('driveId').getItemById('itemId')();
`

#### Question

So this leads up to my question. How do I get the content of a file in OneDrive?

The code to create a file and add it to the library works great.
https://pnp.github.io/pnpjs/graph/onedrive/#add-item

But having added a file, I am unable to then read it.

I am able to get a list of children in the OneDrive Documents library with this:

`const children = await graph.me.drives.getById( driveID ).root.children();
`

But the exposed properties don't include the file content.

I can loop through the children to find the file I want by title (checking the "name" property). And that lets me get the file's id.

I can use that Id to get the item:

`const item = await graph.me.drives.getById( driveID ).getItemById( ItemId )();
`

But the returned object provides the same information available in the children list.

Any attempt to use regular SP context gives a CORS error because of the "tenant-my" domain.

**Comment by juliemturner** [comment]
The search endpoint was definitely broken, and I've created a fix for that. In addition, I've corrected the issues with the documentation around search and getItemById and added a sample for how to getContent from a drive item. The documentation will go live during the next release, but the bug fix for search will be available in tomorrow's [nightly build](https://pnp.github.io/pnpjs/concepts/nightly-builds/) if you would like to test it out.
