### ISSUE TITLE
Confused on what's happening here. If you look at our source for the stream extensions those [interfaces are indeed imported](https://github.com/pnp/pnpjs/blob/version-3/packages/nodejs/sp-extensions/stream.ts#L3). But in the .d.ts file (I checked the package) it seems to be stripped out. No idea why.

### ISSUE THREAD

**Issue by leodak** [pnp/pnpjs#2456]
Confused on what's happening here. If you look at our source for the stream extensions those [interfaces are indeed imported](https://github.com/pnp/pnpjs/blob/version-3/packages/nodejs/sp-extensions/stream.ts#L3). But in the .d.ts file (I checked the package) it seems to be stripped out. No idea why.

You are I assume based on the screen shots using TypeScript - can you try setting `"skipLibCheck": true,` in your tsconfig and see if that helps?

_Originally posted by @patrick-rodgers in https://github.com/pnp/pnpjs/issues/2117#issuecomment-1048367389_

**Comment by leodak** [comment]
I have tried this, still it throws me same error

**Comment by patrick-rodgers** [comment]
I have no idea what you are asking? Can you show some code or complete the issue template fully?

**Comment by juliemturner** [comment]
This issues is being closed because it did not follow any of our issue templates. If you are still having an issue related to the PnPjs library please submit a new issue and fill out the issue template as completely as possible so that we can assist you.
