### ISSUE TITLE
Search for Translated Page using `filter`

### ISSUE THREAD

**Issue by tukutela** [pnp/pnpjs#2458]
Hi all, hoping you can help.... 

We're making use of translations or the `multi-language` feature of sharepoint, having some fun! We have an engine that is automatically performing the translations for us and using PnpJS to put translated elements back into files as the Source content is updated. To date we've been using a `does file exist (by filename)` pattern to determine if a translated file exists, however it's dependant upon the `Source` file name not being changed. For example if you start out with:

Source File: Source.aspx `/sites/[sitename]/SitePages/Source.aspx`
Target File (Spanish): `/sites/[sitename]/SitePages/es/Source.aspx`

However if the source file changes name, the source file would be:
Source File: SourceChanged.aspx `/sites/[sitename]/SitePages/SourceChanged.aspx`

and when we look for the file we look for (which fails):
Target File (Spanish): `/sites/[sitename]/SitePages/es/SourceChanged.aspx`

What we would love to do is take the `UniqueId` of the source file and search in the `es` directory for the file that points back to it, like so:

```
import { folderFromServerRelativePath } from "@pnp/sp/folders/index.js";
await folderFromServerRelativePath('/sites/[sitename]/SitePages/es')
            .files
            .filter(`ListItemAllFields/_SPIsTranslation eq true`)
            .filter(`substringof('es-es', ListItemAllFields/_SPTranslationLanguage')
            .filter(`ListItemAllFields/SPTranslationSourceItemId eq '${SharepointSourcePage.UniqueId}'`)
            .expand('ListItemAllFields)()
```
If I use the first two of the filters (eg. exclude the UniqueId filter) then it returns what I expect, however when I use the UniqueId filter it returns nothing (not an error). I've quadruple checked what ID I'm passing, and when I review the expanded `ListItemFields` the ID is definitely there. 

What I'm hoping for is there is some magical 'odata' search search operator I'm not using that works with GUID fields, however I can't see it anywhere. Iv'e tried using the `substringof` function but no joy. Can anyone help?

**Comment by juliemturner** [comment]
To review the internal field names that are used for Multilingual pages you can review this solution that I build to convert pages from the interim multilingual page's community implementation to the released OOB pages... 

https://github.com/pnp/sp-dev-solutions/blob/master/solutions/MultilingualPages/Converter/MultilingualPagesConverter/Program.cs

Essentially there are four fields in the pages library that you can interrogate... 
- _SPTranslatedLanguages
- _SPIsTranslation
- _SPTranslationLanguage
- _SPTranslationSourceItemId

Each page in the library has a "UniqueId" property that can help you identify the file not relying on the file name.

Hope that helps.

**Comment by juliemturner** [comment]
Sorry, just re-read your post and realized you were asking a filter question... 

I think the issue is you need to filter on items not files... the metadata is associated with the pages item.. once you have the item then get the related file.

**Comment by tukutela** [comment]
Hey @juliemturner 

Got it figured out! Searching for items gave me another idea to solve it using a CAML query, just in case anyone is hoping on doing the same thing here's what I used. 

Desired Outcome: Based upon a Source file (say English), find the Spanish file URL and UniqueID that has been created already. Note: Could be in any folder, the three pieces of information you have are:
- The UniqueID of the Source File
- The language of the translated file
- The knowledge that it has been created already (will return nothing if it isnt) and placed in any directory in the site.

```
const TranslatedFileExists = await sp.web.lists.getByTitle("Site Pages").getItemsByCAMLQuery({
        ViewXml: `
          <View Scope="RecursiveAll">
            <ViewFields>
              <FieldRef Name="FileRef"/>
              <FieldRef Name='UniqueId' />
            </ViewFields>
            <Query>
              <Where>
                <Eq>
                  <FieldRef Name="_SPTranslationLanguage"/>
                  <Value Type="Text">es-es</Value>
                </Eq>
                <Eq>
                  <FieldRef Name="_SPTranslationSourceItemId"/>
                  <Value Type="Lookup">[SOURCEFILE_UNIQUEID]</Value>
                </Eq>
              </Where>
            </Query>
          </View>`
      }, ['FileRef', 'UniqueId'])
```
The additional parameters (array of FieldRef, UniqueId) adds those fields to the items results, so essentially in a single result you can get the item result + the specific file identfiers (note: FileRef is the same as ServerRelativeURL).
