### ISSUE TITLE
Best way to retrieve paginated and ordered items by caml query

### ISSUE THREAD

**Issue by DonatoDev90** [pnp/pnpjs#2464]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: "^3.8.0"

Please specify what version(s) of SharePoint you are targeting: O365

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I'm trying to retrieve paginated results from pages in "Site Pages" document library. I want these results are ordered by a DateTime field.

This is my CAML Query by now:

```typescript
const caml: ICamlQuery = {
        ListItemCollectionPosition: "Paged=TRUE&p_EventDate=" + lastEventDate,
        ViewXml: 
                "<View>" + 
	                "<Query>" +
	                      "<Where>" +
                                   "<Eq>" +
                                         "<FieldRef Name='ContentType'/>" +
                                         "<Value Type='Text'>MyCustomContentType</Value>" +
                                  "</Eq>" +
                             "</Where>" +
                             "<OrderBy>" +
                                    "<FieldRef Name='EventDate' Ascending='False'/>" +
                             "</OrderBy>" +
                       "</Query>" +
                       "<RowLimit>10</RowLimit>" +
                "</View>"
}

const results = await sp.web.lists.getByTitle("Site Pages").getItemsByCAMLQuery(caml);

lastEventdate = results[result.length-1].EventDate;
```

The problem occurs when there are 2 or more items to retrieve with the same value for the "EventDate" field. In this case it retrieves only the first item with that value, ignoring the others.

I was trying to achieve my goal without the caml query, using this PnpJS call:
```typescript
const results = await sp.web.lists.getByTitle("Site Pages").items.skip(10 * pageNumber).top(10)();
```
However I have a doubt on the working process of this call behind the scenes. That is to say, I don't know if the retrieve and then the filtering of the items happen completely server side or it is just the retrieve of the items and then the filtering happens client side.

I'm evaluating what is the more efficient way to retrieve paginated items between the first or the second approach.

Thank you.

**Comment by patrick-rodgers** [comment]
The library is open source, you can see exactly how things work "behind the scenes". You should avoid CAML when possible.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
