### ISSUE TITLE
PnPJS "Set-sposite -denyaddandcustomizepages 0" Alternative

### ISSUE THREAD

**Issue by Dopsterinho** [pnp/pnpjs#2465]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version 3

Please specify what version of the library you are using: [    3     ]

Please specify what version(s) of SharePoint you are targeting: [   Online      ]

### Question
Hi,

Is there an alternative to **Set-Sposite -denyaddandcustomizepages 0** for PnPJS v3 ?

I am building a SPFX Solution and need to upload a custom ASPX Page to SitePages Library -> I get "Access Denied".

How can I permission for Add and Customize Pages ?

Thank you in advance !

Thank you for your feedback!

**Comment by juliemturner** [comment]
I would ask, why are you uploading vs building, copying, or moving?

**Comment by Dopsterinho** [comment]
Exactly Patrick 
"Access Denied" when programatically uploading an ASPX File to "Site Pages" Library has nothing to with my Permissions. I am Global Admin/Sharepoint Admin/ Owner of the Site. 

It has to do with "DenyAddAndCustomizePages" which is set to $true. I need to disable that temporarly with Typescript/PnPJS.

**Comment by Dopsterinho** [comment]
Hello,

Is there some kind of solution to this, please ?

Thank you !

**Comment by patrick-rodgers** [comment]
You cannot via REST update these properties. You can read them through our [sp-admin library](https://github.com/pnp/pnpjs/tree/version-3/packages/sp-admin), note the [property](https://github.com/pnp/pnpjs/blob/version-3/packages/sp-admin/types.ts#L971) on [this class](https://github.com/pnp/pnpjs/blob/version-3/packages/sp-admin/types.ts#L819).

This is however not something you should expose generally on the client side due to the elevated level of permissions required to read this API.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
