### ISSUE TITLE
What is the correct way to delete columns from a section and change/readjust the layout?

### ISSUE THREAD

**Issue by rzempo** [pnp/pnpjs#2466]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [^3.8.0]
Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
I am able to delete a column using the remove() from a CanvasColumn. All good there. However, if a web part is present in the other column that wasn't deleted, that column, and that web part keep the factor they had before being deleted. I.e., if I had a One-third right section layout, and I deleted the right column, the left column and its web parts keep the 8 factor after the right column is deleted. I can manually change the factor of the column and the web part, which makes the correct layout visually, but then that makes any future layout changes unusable. I.e., if I have the previous scenario and I change the section layout back to One-third right, and I try to manually add a web part to the right part of the section, that web part doesn't get added to the correct area. I also can't move the web part on the left area to another section. The end result is messy. Which is why I am assuming that changing the factor isn't the correct approach for this. 

Has anyone tried something like this successfully?

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!

**Comment by juliemturner** [comment]
Couple of questions...
First, what do you mean specifically when you say "factor".
Second, are you deleting the column, saving the page, and then reloading it or are you just doing this all in memory?

**Comment by rzempo** [comment]
Hi Julie,

1) In a One-third right section layout, the left column has a factor value of 8, and the right column has a factor value of 4. A One column section layout has a value of 12. This is how I change the factor of a column or a web part: 
[ColumnCanvas].factor = 12
CanvasColumn.factor = 12.

2) I have tried both saving first and in memory.

**Comment by juliemturner** [comment]
Ok, thanks for clarifying what you meant... essentially the answer is no idea. We can add to the backlog looking into how 1st part does this and see if we can figure out why what you're doing is not working but other than that I don't have much to suggest other than maybe creating a new section with the right number of columns and moving the web parts where you want them and then deleting the old section.

**Comment by rzempo** [comment]
Yes. That is my work around. Looking forward to seeing what you guys find out. Thanks.

**Comment by juliemturner** [comment]
If you have a work around, I suspect we won't put much effort here as this is not an official API for client-side pages and as I understand it they intend to give us one, but I'll leave it tagged in case someone has some cycles to inspect the calls.

**Comment by rzempo** [comment]
Thanks, @juliemturner.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
