### ISSUE TITLE
POST requests fail with error: The security validation for this page is invalid and might be corrupted

### ISSUE THREAD

**Issue by RaphaelFelten** [pnp/pnpjs#2467]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.8.0

Please specify what version(s) of SharePoint you are targeting: Online

### Expected / Desired Behavior / Question
POST requests should not fail.

### Observed Behavior
When executing POST requests (either updating or adding items), I'm running into the error "The security validation for this page is invalid...". That error is most likely related to the request digest not being set in the request. GET requests, such as getting items from a list works withour any errors.
I'm already using the [RequestDigest](https://pnp.github.io/pnpjs/sp/behaviors/#requestdigest) behavior.
Maybe it's got something to do with the way I'm authenticating to SharePoint. Here's my setup:

```js
import * as spauth from 'node-sp-auth';
import { DefaultHeaders, DefaultInit, RequestDigest, spfi } from '@pnp/sp';
import { DefaultParse, InjectHeaders } from '@pnp/queryable';
import '@pnp/nodejs';
import '@pnp/sp/webs';
import '@pnp/sp/lists';
import '@pnp/sp/lists/web';
import '@pnp/sp/items';
import '@pnp/sp/items/get-all';
import '@pnp/sp/folders';
import '@pnp/sp/recycle-bin';

const authData = {
  siteUrl: "https://[tenant].sharepoint.com",
  username: "username",
  password: "password",
  online: true
}

const site = 'mySite';

const fullSiteUrl = `${authData.siteUrl}/sites/${site}`;
const options = await spauth.getAuth(fullSiteUrl, authData); // Getting the headers that will be injected into the request
const sp = spfi(fullSiteUrl).using(DefaultBehavior(options));

// This works
const item = await sp.web.lists.getByTitle('Documents').items.getAll();

// This does not work
const updatedObject = await sp.web.lists.getByTitle('Documents').items.getById(1).update({ Title: 'newTitle' }};

// Default behavior
function DefaultBehavior(options) {
  return (instance) => {
    instance.using(
      DefaultHeaders(),
      DefaultInit(),
      NodeFetchWithRetry(),
      DefaultParse(),
      RequestDigest(),
      InjectHeaders(options.headers)
    );
    return instance;
  };
}
```

As you can see, I'm using the package `node-sp-auth` to authenticate to SharePoint with a username and password. Not sure if that's the problem, but as I said GET requests work without any issues.

Maybe it's just something simple that I'm missing. Or maybe the RequestDigest behavior does not work with the way I'm authenticating?

### Steps to Reproduce
You can try to make requests to SharePoint using the provided code.

Thanks for looking into this :)

**Comment by juliemturner** [comment]
Maybe check out these docs... https://pnp.github.io/pnpjs/concepts/authentication/#msal-nodejs

**Comment by patrick-rodgers** [comment]
What is in the headers you are adding?

**Comment by RaphaelFelten** [comment]
Excuse me, I should have maybe explained a little further.
We would like, if possible, avoid using MSAL for authentication since we're managing a SharePoint integration for multiple clients. Up to this point, we used v2 of this package while authenticating with [pnp-auth](https://github.com/SharePoint-NodeJS/pnp-auth) and everything has worked flawlessly. And we only had to specify a username and a password, which was pretty great.
Now we wanted to upgrade our application to v3 and that's when I ran into this problem.
Is there any way we might be able to solve this without having to use MSAL?

**Comment by RaphaelFelten** [comment]
> 

The headers I'm adding look like this: [Headers](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint-Online-user-credentials-authentication#resolving-object)

**Comment by RaphaelFelten** [comment]
I've just inspected the headers using a behavior, maybe this helps:
![1](https://user-images.githubusercontent.com/22978583/200599966-d959a987-458f-415d-93bd-bf377f2c5683.png)
![2](https://user-images.githubusercontent.com/22978583/200599969-56e40e83-10a5-4a3e-96e4-7362f083ee15.png)

**Comment by RaphaelFelten** [comment]
Hey,
I decided to try and fetch the request digest myself and inject it into the headers. 
And to my surprise it was pretty easy to do. Here's what I did:

```js
// Defining the default behavior for PnP
function DefaultBehavior(siteUrl, options) {
  return (instance) => {
    instance.on.auth(async function (url, init) {
      if (init.method === 'POST') {
        init.headers['X-RequestDigest'] = await getRequestDigest(siteUrl, init);
      }
      return [url, init];
    });
    instance.using(
      DefaultHeaders(),
      DefaultInit(),
      NodeFetchWithRetry(),
      DefaultParse(),
      InjectHeaders(options.headers)
    );
    return instance;
  };
}

const requestDigestData = {
  digest: null,
  timeout: null,
  lastUpdate: null,
};

async function getRequestDigest(siteUrl, init) {
  let digest = null;
  // Digest found, checking if it's still valid
  if (requestDigestData.digest) {
    const diff = Date.now() - requestDigestData.lastUpdate;
    if (diff < requestDigestData.timeout - 10000) { // 10 seconds before it expires, just to be safe
      digest = requestDigestData.digest;
    }
  }
  // If we don't have a digest at this point, we need to fetch a new one
  if (!digest) {
    const res = await fetch(siteUrl + '/_api/contextinfo', {
      method: 'POST',
      headers: init.headers,
    });
    const data = await res.json();
    if (!data.FormDigestValue) {
      throw new Error(
        `Unable to fetch RequestDigest for site: ${siteUrl} - ${JSON.stringify(
          data
        )}`
      );
    }
    requestDigestData.digest = data.FormDigestValue;
    requestDigestData.timeout = data.FormDigestTimeoutSeconds * 1000;
    requestDigestData.lastUpdate = Date.now();
    digest = requestDigestData.digest;
  }
  return digest;
}
```

Sorry to bother you with this. A little more digging on my part could have avoided this.
