### ISSUE TITLE
Is there a way to get who has open or downloaded a document?

### ISSUE THREAD

**Issue by rzempo** [pnp/pnpjs#2468]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [^3.8.0]
Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
Is there a way to get who has open or downloaded a document?
The goal would be to have a web part that displays a list of documents with an expandable section, and once expanded it'll show who has open/downloaded that document.

**Comment by juliemturner** [comment]
I believe the only answer to this (if not the activity enpoint) is to download audit logs and parse them. I'm sorry other than that I don't have more information for you. 

I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
