### ISSUE TITLE
Is there a way to get a document stats?

### ISSUE THREAD

**Issue by rzempo** [pnp/pnpjs#2469]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [^3.8.0]
Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
Is there a way to get document stats? This is what I see in the file stats. Ideally I can also see who those users are and the dates they saw it. 
![image](https://user-images.githubusercontent.com/20348540/200566934-8b129d35-7cb0-4fab-9a8e-95fd4a5844f3.png)

The goal would be to have a web part that displays a list of documents with an expandable section, and once expanded it'll show stats for that document.

Note:  might be similar to https://github.com/pnp/pnpjs/issues/2468.

**Comment by patrick-rodgers** [comment]
What have you tried so far? Your two issues read like you got handed some requirements and asked us to solve it for you - can you share what you've tried or the research you've done? Where are you stuck?

**Comment by juliemturner** [comment]
Might take a look at graph: https://learn.microsoft.com/en-us/graph/api/resources/itemanalytics?view=graph-rest-1.0

**Comment by patrick-rodgers** [comment]
The page is making this call behind the scenes:

`/_api/v2.1/drives/{drive id}/items/{item id}/oneDrive.getActivitiesByInterval?startDateTime=2022-08-24T14%3A02%3A37.719Z&endDateTime=2022-11-22T00%3A00%3A00.000Z&interval=720`

Which appears to be [public on the graph docs here](https://learn.microsoft.com/en-us/graph/api/itemactivitystat-getactivitybyinterval?view=graph-rest-1.0&tabs=http).

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
