### ISSUE TITLE
How can I limit the getSharingInformation endpoint?

### ISSUE THREAD

**Issue by plamber** [pnp/pnpjs#2471]
Hello,
I am trying to use the getSharingInformation endpoint for a specific folder.

I am using this call.
```
sp.web.getFolderById(item.UniqueId).getSharingInformation()
```

I haven't found a way to limit the output of the getSharingInformation() endpoint with a select. I was expecting to be able to perform this type of query.
```
sp.web.getFolderById(item.UniqueId).getSharingInformation.select("listofProperties")()
```

Furthermore, I am trying to expand the "permissionsInformation" using the getSharingInformation() endpoint. So far, I could do it only with this command.
```
sp.web.getFolderById(item.UniqueId).getSharingInformation(undefined, ["permissionsInformation"]);
```

Is it a configuration issue on my end, or is it currently not supported to perform the select and expansion for getSharingInformation? I thought I might be able to do it like this.
```
sp.web.getFolderById(item.UniqueId).getSharingInformation.select("permissionsInformation").expand("permissionsInformation")();
```

Thank you. I appreciate your help,
Patrick

**Comment by juliemturner** [comment]
If you want to share the direct REST call that you make where you can do what you're suggesting, then I can look at changing the endpoint. It may be that the endpoint has matured since the implementation was done.

**Comment by plamber** [comment]
Hi @juliemturner,
I can perform such a query.
```
POST
https://nuborocks.sharepoint.com/sites/blankteam/_api/lists('f090f07a-8003-45eb-9c6b-91d644eba2f2')/getItemById(2)/GetSharingInformation?$select=permissionsInformation,anyoneLinkTrackUsers&$expand=permissionsInformation
```
Is there a way for SDK users to pass and override select and expand statements in case these are not supported "yet"?

Thank you for your help,
Patrick

**Comment by patrick-rodgers** [comment]
OK, we had a look at this and understand the request - but for "reasons" it is not a simple change in a non-breaking way. We'll think about it and see if we can come up with a way. In the meantime, you can work around this by doing:

```TS
import { body } from "@pnp/queryable";
import { spPost, SPInstance } from "@pnp/sp";
import { ISharingInformationRequest } from "@pnp/sp/sharing";

const folder = {some IFolder got from somewhere};

const o = SPInstance(folder, "getSharingInformation");

const request: ISharingInformationRequest = {};

return spPost(o.select(...selects).expand(...expands), body({ request }));
```
> I might have missed a detail, but the above will work for you as a pattern.
