### ISSUE TITLE
moveByPath and copyByPath don't maintain item's Created and Modified dates

### ISSUE THREAD

**Issue by logol-abertoletti** [pnp/pnpjs#2474]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
We are using version 3.8.0 and SharePoint online

### Expected / Desired Behavior / Question
We are working to a SharePoint extension that helps the user to move or copy file between sites collection. We would maintain the item's "Created" and "Modified" fields where possible.
In order to move or copy, we are using the methods "moveByPath" and "copyByPath" with the options "RetainEditorAndModifiedOnMove" = "true" and "ResetAuthorAndCreatedOnCopy" = "false".

What we expected:
 - on the move, the fields "Created" and "Modified" maintain the original value
 - on the copy, the field "Created" maintains the original value 

```
public async execute(): Promise<void> {
        try {
            let source = (this.rowData.isFolder)
                ? this.sp.web.getFolderByServerRelativePath(this.rowData.url)
                : this.sp.web.getFileByServerRelativePath(this.rowData.url);
            
            if (this.isCopy) 
                await source.copyByPath(`${this.destinationFolderUrl}/${this.rowData.title}`, false, {
                    KeepBoth: true,
                    ResetAuthorAndCreatedOnCopy: false,
                    ShouldBypassSharedLocks: true
                });
            else 
                await source.moveByPath(`${this.destinationFolderUrl}/${this.rowData.title}`, false, {
                    KeepBoth: true,
                    RetainEditorAndModifiedOnMove: true,
                    ShouldBypassSharedLocks: true
                });
                
        } catch (e) {
            this.hasError = true;
            this.errorMessage = e.statusText;
        }
}
```

### Observed Behavior
The "Created" and the "Modified" fields are reset in both the situations.

### Steps to Reproduce
Use the methods "copyByPath" and "moveByPath", with the options described above, to move a file between two different sites collection.

### Submission Guidelines
We tried to use the native button "Move to" and it preserves the item's metadata.

Thank you!

**Comment by patrick-rodgers** [comment]
This is correct. If you change the file name on a move, that is an edit and will update the modified information. If you keep the same file name, the modified by info remains unchanged. As you will see in the moveTo dialog there is no option to change the filename.

**Comment by logol-abertoletti** [comment]
Hi Patrick,
thank you for your answer.
Sorry, but I don't get you. We don't change the file name. Do you mean that if I use the method copyByPath or moveByPath inherently I will change the file name?

**Comment by logol-abertoletti** [comment]
We do not change the file name: the file name is still the same.
Did you try copying or moving a file in different sites? We are seeing the Modified and Created fields change if you copy or move a file in a different site.
If you copy or move a file in the same site, the Modified and Created fields don't change.

**Comment by Mruffo** [comment]
Hi, I actually have the exact same problem, do you have any news on that?

**Comment by juliemturner** [comment]
I think the missing piece here is that the ability to copy/move between site collections is somewhat new... and SharePoint has a new first party api to do that task
`https://contoso.sharepoint.com/sites/pnpjs/_api/site/CreateCopyJobs`
The copyByPath and moveByPath work as expected and those are the only supported endpoints.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
