### ISSUE TITLE
Get SpotLighted Items information from list or document library

### ISSUE THREAD

**Issue by JarialAnkur** [pnp/pnpjs#2479]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

- [x] Enhancement
- [x] Question

3.8.0 Version

Please specify what version of the library you are using: [   3.8.0      ]

Please specify what version(s) of SharePoint you are targeting: [    1.15.0     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I am expecting that, I get the data of spotlighted items in a list or document library in the API when I do a get request for all the files or the items in a list or document library. 
By Spotlighted items I mean, the items that we "Pin To Top". Those come in **Microsoft.SharePoint.Client.Utilities.SpotlightResult**. 

### Observed Behavior
I am not able to retrieve them in the API of get files or get items.*

### Steps to Reproduce
await web.getFolderByServerRelativeUrl (I am using this API to get the data inside a folder, which includes folder and files, But I want the items that are spotlighted or pinned to the top as well)
![pin to top files](https://user-images.githubusercontent.com/49793242/203072794-5caf1567-5ec7-4108-93fe-6f73212d6b9f.jpg)

Thank you for your feedback!

**Comment by juliemturner** [comment]
Not sure there's an REST API endpoint that provides that, but we can look into it at some point.

**Comment by JarialAnkur** [comment]
So, for now, there is no endpoint that can give me that value, as in which files/items are pinned and which are not

**Comment by juliemturner** [comment]
I don't know of one... if you do the research and find the answer, we accept PRs and/or we'll investigate it as an enhancement request when we have time.

**Comment by patrick-rodgers** [comment]
You can use the `renderListDataAsStream` method to get the spotlighted items. They are tied to the view information so your request would look something like the below. Obviously you can include other options, but the `RenderOptions: 256` is the key to get back the SpotlightInfo.

```TS
const info = await sp.web.lists.getByTitle("{List Title}").renderListDataAsStream({
    ViewXml: "<View Name='{view GUID id}'></View>",
    RenderOptions: 256,
});
```

That request will get you just the spotlight information. You can of course get more list info back for a more efficient process depending on your needs.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
