### ISSUE TITLE
Hidden field _SPTranslatedLanguages does not update

### ISSUE THREAD

**Issue by Nevinia210** [pnp/pnpjs#2482]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.6.0]

Please specify what version(s) of SharePoint you are targeting: [1.12.1]

### Expected / Desired Behavior / Question
Hello,
recently i get task in my work to update Translated Languages field to reflect real values (in case some translations were deleted and old values were stucked in original sp item property translation languages)

```js
await sp.web
            .getList(`${this._context.web.serverRelativeUrl}/SitePages`)
            .items
            .getById(listItem["id"])
            .update({

                    "__metadata": {  
                        "type": 'SP.Data.SitePagesItem'
                    },  
                       "OData__SPTranslatedLanguages": 
                       { 
                           '__metadata': 
                           {
                               'type' : 'Collection(Edm.String)'
                           },
                        results: realTranslationsArray 
  }});
```
- In network i can see that call returns 204 and runs without problem, but values in field were not updated
- After publish invalid value is still there

**Comment by juliemturner** [comment]
Duplicate #2300
