### ISSUE TITLE
Spfi(...) expression expected

### ISSUE THREAD

**Issue by RomanoZumbe** [pnp/pnpjs#2484]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     v3    ]

Please specify what version(s) of SharePoint you are targeting: [    sharepoint online     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Question
I switched to version 3 today and changed my code according to the getting started guide. The first part where I pass the context to the spfi factory works as described but when I try to create a new spfi object in a another component like this:
const sp = spfi(...);
I get a compiler error "expression" expected. I checked the demo project and noticed that there was another approach used. I'm using the latest spfx version (as of today). The project makes use of the react framework.
Am I missing something there?

**Comment by patrick-rodgers** [comment]
Can you share the code you're using? We have a section in the [docs on using spfi factory](https://pnp.github.io/pnpjs/getting-started/). Depending on what dev platform you are targeting (you don't tell us) there should be examples there of setting things up. If you used the literal string `spfi(...)` that won't work as it is just a placeholder we use in the docs.

**Comment by RomanoZumbe** [comment]
By dev platform, do you mean spfx or node? If so I'm developing for spfx. But if it is just a placeholder I will just follow the approach from the demo project. Is that described in the docs? Am I blind? Thank you a lot for your help!

**Comment by patrick-rodgers** [comment]
https://pnp.github.io/pnpjs/getting-started/#getting-started-with-sharepoint-framework

**Comment by RomanoZumbe** [comment]
The part I'm missing is how I get the equivalent to the old sp object in a child component where I have no context object. In the old version I initialized sp once and it was readily available with an import through out the whole project

**Comment by RomanoZumbe** [comment]
I found the in depth explanation in the transition v2 -> v3 docs and the library usage tips
