### ISSUE TITLE
clientPeoplePickerSearchUser filter users by additional attributes

### ISSUE THREAD

**Issue by jyothi530** [pnp/pnpjs#2485]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.14.0 ]

Please specify what version(s) of SharePoint you are targeting: [SPO 2019]

### Expected / Desired Behavior / Question
I am using the `sp.profiles.clientPeoplePickerSearchUser` API to search users. Along with searching the users by their Name/Email, on top of it I want to apply additional filters based on user attributes like for example, users belonging to Sales/IT department or the UserType (Member vs Guest) etc.

I see most of the examples provided are passing search term but not with additional filters. I wanted to filter by additional attributes like "SPS-Manager" or "SPS-UserType", etc.

I know I could use PnP/Graph to achieve what I am looking for. The limitation for us is we are using a non-spfx solution. And we don't have all the attributes setUp in Azure AD like "ApplicationId", "ApplicationSecret" to use it. Also we are using WS_Federation authentication mechanism.

Please let me know if I can achieve what I am looking for.

**Comment by juliemturner** [comment]
You can try using Search endpoint with the People result source. That will give you access to all the user profile properties.
https://pnp.github.io/pnpjs/sp/search/
https://learn.microsoft.com/en-us/sharepoint/search/understanding-result-sources-for-search -> People is already configured you just need the guid.

**Comment by jyothi530** [comment]
I tried below but the search is not returning any results.
`sp.search({
      SourceId: SearchBuiltInSourceId.LocalPeopleResults,
      Querytext: 'displayname:t*'
    })`
`sp.search({
      SourceId: SearchBuiltInSourceId.LocalPeopleResults,
      Querytext: 't'
    })`

**Comment by juliemturner** [comment]
The following is in my code right now... and works perfectly.
```ts
const q: SearchQueryInit = SearchQueryBuilder(`*${searchString}*`)
        .sourceId(this.PEOPLE_SOURCE_ID)
        .selectProperties("SipAddress", "PreferredName", "AccountName")
        .trimDuplicates;
const people: SearchResults = await this._sp.search(q);
```

**Comment by jyothi530** [comment]
Thank you for the response. Even this doesn't work for me. Might be I am missing something. I am a novice in SharePoint. Do I have to enable the search against People data source in SharePoint? Since people is already configured by default, I was thinking we don't have to enable anything.
When the People data source is preconfigured will it come with fields (LastName, FirstName, Email, etc) indexed by default or I have to add them to the index?

**Comment by juliemturner** [comment]
No setup necessary, no special indexing, this just works. You're not really sharing any code samples so I guess I don't know what "doesn't work for me" means.

**Comment by jyothi530** [comment]
I am able to find the root cause why it is not working for me. I think it is nothing to do with code. We have a root SharePoint site `domian.sharepoint.com` and another SharePoint site `xyz-dev.domain.com`. `sp` is set up for `xyz-dev.domain.com`. When I am issuing the People search against `domain.sharepoint.com` it is returning me the results whereas issuing same search queries using the `sp` object or the direct ajax call to `_api/search/query` endpoint I am not getting results for `xyz-dev.domain.com`. I used the same authentication cookie generated for `xyz-dev.domain.com` to issue a search against `xyz-dev.domain.com`.
Can you please let me know do we need to make any enablement for the second site

**Comment by juliemturner** [comment]
I'm not sure exactly what to tell you as I don't really think I follow how your SP environment is configured... but it does sound complicated.  Regardless, if you want to connect to a different host with version 2 of this library it's not particularly supported, this type of request was the major update for version 3, unfortunately version 3 doesn't work with SP 2019.  

Maybe take a look at the precursor feature [Isolated Runtimes](https://pnp.github.io/pnpjs/v2/concepts/configuration/#isolated-runtimes). That said I suspect you may need auth in addition as I'm not sure how you've got your environment configured.

**Comment by jyothi530** [comment]
Thank you. Appreciate your quick responses. In the first place I didn't know that there is a search API that I could use for searching user profiles. You pointed me in that direction. I prefer using PnP/Graph for searching users but that required extra setup. Now I have the search API option too. I will work with my SP team.
I will close the issue. Thanks!
