### ISSUE TITLE
Updating multi taxonomy fields not working

### ISSUE THREAD

**Issue by kolanicpa** [pnp/pnpjs#2489]
Hi all, after a while and numerous articles I read, I really need some help with this topic. I did exactly as PnPJs library said, but with no lucky to update these fields. After I was able to create item, updating same item with taxonomy field was unsuccessful.

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   3.9.0    ]

### Expected / Desired Behavior / Question
```
       const listName = "Some List"
            const fields = await sp.web.lists.getByTitle(listName).fields.filter("Title eq 'PROCEDIMENTIOGGETTO_0'").select("Title", 
                "InternalName")();
        const updateVal = {};
        Object.defineProperty(updateVal, fields[0].InternalName, {
            value: '-1;#Appalti - Acquisti di forniture e servizi|2027913f-aed8-4187-bfe3-3a2f591ff8c3;#'
        });
        await newItem.item.update(updateVal);
```

### Observed Behavior

There is no error related to this functionality

**Comment by juliemturner** [comment]
I think the issue is that the above sample set the property to an object with a value property and I think that was needed in v2 for verbose odata settings in REST. 

I too had trouble getting this to work, essentially it's fiddly, but the following code works for me:

```ts
const id = 1; //Item Id
const taxValues = [
`-1;#${term1.Label}|${term1.TermGuid}`,
`-1;#${term2.Label}|${term2.TermGuid}`,
]
const newTaxValue = taxValues .join(";#");
const updateObject = {};
const listName = "Some List"
const fields = await sp.web.lists.getByTitle(listName).fields.filter("Title eq 'MyTaxField_0'").select("Title", "InternalName")();
if (fields?.length > 0) {
  updateObject [fields[0].InternalName] = newTaxValue;
}
response = await this._sp.web.lists.getById(listName).items.getById(id).update(updateObject);
```

**Comment by kolanicpa** [comment]
@juliemturner thank you for sharing solution to me. I was able to submit taxonomies once I removed 'defineProperty' from object...
Thank you for your help, saved my time!
