### ISSUE TITLE
sp.utility.searchPrincipals On-Prem 2013 returns -1 for PrincipalId

### ISSUE THREAD

**Issue by c-eiser13** [pnp/pnpjs#249]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  1.2.1 ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Use this utility function to create a people picker where I can get the ID of the user as part of the results.

### Observed Behavior
I am using the sp.utility.searchPrincipals function along with a typeahead control to create a people picker. This function returns DisplayName, Email, LoginName, etc. correctly, but for every user I have tried, PrincipalId is -1. In SPO, this works correctly and PrincipalId is a correct value. Additionally, I've implemented a workaround to get the users ID based on their login name, so I know they have a valid ID.

![inkedon-prem-resolve-principal](https://user-images.githubusercontent.com/42096464/45780553-6ccc3680-bc23-11e8-917b-f511cfbf3ab3.jpg)

In the image above, I also have to convert the response to "any" because it is types as "PrincipalInfo[]", but it is actually coming back as an object with a property of "SearchPrincipalsUsingContextWeb" that contains the results array. This is not a big issue, but wanted to point it out in case I am doing something wrong or if this function is returning the wrong type.

### Steps to Reproduce
Angular 6 CLI application with @pnp/sp 1.2.1 and call sp.utility.searchPrincipals in SharePoint 2013 on-prem environment.

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
I don't have a 2013 environment available currently to test this. If in SPO things work as expected this might just be a difference between 2013 and SPO. I can't really find anything on the "SearchPrincipalsUsingContextWeb" property and that doesn't seem to appear anywhere in the CSOM dlls either. Appreciate you reporting this, but might be a case where you'll just have to use the work around. Would make a great blog post for you :)

**Comment by c-eiser13** [comment]
Thanks @patrick-rodgers  for the quick response. In case I do not get to the blog, all I am doing is passing the account name that I get from searchPrincipals to the function below to get the ID for that user. If account ID is not needed, all other properties are returned correctly.

![capture](https://user-images.githubusercontent.com/42096464/45823325-0f7fc600-bcb3-11e8-9b65-74e6c139d1e8.PNG)

**Comment by patrick-rodgers** [comment]
Thanks @c-eiser13 - going to close this as answered. Appreciate you posting the follow up details. Thanks!
