### ISSUE TITLE
Create and GetItem with all properties in same Batch query.

### ISSUE THREAD

**Issue by Vertamin** [pnp/pnpjs#2491]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
[SharePoint Online]

### Expected / Desired Behavior / Question
I would like to be able to create a list item and obtain it with all its properties in one unique Batch call.

### Observed Behavior

This is possible with Update and Get:

````
const [Batchedweb, execute] = web.batched();
let List = BatchedWeb.lists.getByTitle("yourlist");

List.items
  .getById(CurrentItemID)
  .update(
      UpdateFields,
  );

var UpatedItem = List.items
  .getById(CurrentItemID)
  .expand(ExpandAllFields)
  .select(SelectAllFields)()

await execute()

````

But since you need the Item ID to make a Get With Select and Expand fields, you cannot make this in the same Batched call after while creating the item. Because the ID is obtain after the item creation.

````

List.items
  .add(UpdateFields)
  .then(async (R) => {
      var ID = R.data["ID"];
  });

``

The IItemAddResult.data does have *some* properties, but no the same as a normal get with Select and Expand call, so if you need any of those properties you will have to make an individual Get call again.

¿Could there be any way to improve this process?


Thank you!

**Comment by patrick-rodgers** [comment]
Not sure exactly what your needs are but:

1. No, the only way to get the item would be by id. For files you might be able to predict the path but I haven't tested that so unsure if would work.
2. If you just want the item's information that comes back with the [add call](https://github.com/pnp/pnpjs/blob/version-3/packages/sp/items/types.ts#L357) in the "data" property. If you want to immediately operate on that item you get it back in the "item" property.

If you have a lot of expands/selects you want to make on the new item, then yes that would be another call.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
