### ISSUE TITLE
Fixing #2448 appears to have reverted #2414

### ISSUE THREAD

**Issue by ohermans1** [pnp/pnpjs#2492]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: **3.9.0-v3nightly.20221201**

Please specify what version(s) of SharePoint you are targeting: **Online** 

### Expected / Desired Behavior / Question
Hi team, so sorry, but it's pesky old Ollie and his OrderedTree issues again! I've just been doing some testing for @patrick-rodgers's fix for #2448, and I've realized that it's potentially reverted the other fix for #2414!

The getAllChildrenAsOrderedTree function should return standard and reused terms in an ordered tree.

### Observed Behavior
The function is now returning the terms in order but is once again missing the reused terms. 

### Steps to Reproduce

To reproduce, update to that latest nightly build, and use getAllChildrenAsOrderedTree() on a termset that has reused terms. 

Please let me know if you need any extra information. 

Sorry again for the multiple issues!!

**Comment by patrick-rodgers** [comment]
Ok, figured this out and have it fixed. I'll say the getAllChildrenAsOrderedTree method has gotten quite complex so unless there is a bug likely won't look to add more enhancements. We should have kept it to just children as originally envisioned, but the cat's out of the bag. This now works with reused terms and children as well as ordering.

A few notes:

- Reused terms do not express "children" in the sets where they are reused, this how it works in the UI as well
- If there is no custom sort we leave the ordering as it is returned to us, meaning reused terms will always be appended to the end of the array. If custom sort is enabled we respect that ordering.

**Comment by ohermans1** [comment]
Awesome, thanks @patrick-rodgers - Sorry for over complicating this one!

**Comment by patrick-rodgers** [comment]
All good, always happy to help, the underlying API doesn't give us a lot of help here
