### ISSUE TITLE
upload document

### ISSUE THREAD

**Issue by RaulAlcaraz** [pnp/pnpjs#2493]
**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   3.9.0      ]

Please specify what version(s) of SharePoint you are targeting: [    sharepoint online??     ]

### Question
How can a user upload a file using pnpjs?

I tried using `web.rootFolder.files.addChunked(...)` but doens't work, I always get a 403 error and this way I don't know who uploaded the file. 

What do I have to do to upload a file here using nodejs?
![image](https://user-images.githubusercontent.com/85160445/205322844-024eb303-b55e-4ea9-93c7-cc0f4ba972e8.png)

Why the api have more calls that this package? 
https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=javascript#example-updating-an-existing-file

sharepoint is incredibly difficult to work with.

**Comment by patrick-rodgers** [comment]
Can you share your code, its a little hard to guess what you're doing. We do have a whole section on [uploading files](https://pnp.github.io/pnpjs/sp/files/#adding-files) and the methods do work.

Also, unsure what you mean by comparing the sp apis to the graph apis? Can you elaborate?

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
