### ISSUE TITLE
renderExtendedListFormData missing and RenderListFormData has no option to return all Dates in utc

### ISSUE THREAD

**Issue by Link631** [pnp/pnpjs#2495]
Hi,

I am using the library @pnp/sp-commonjs.
I need to use renderListFormData endpoint to retreive from information of an listitem.

The Problem: I do get all Dates in a locale, but the locale is not part of the response.

RenderListDataAsStream for instance supports options to get all dates in utc.

How do i get information about the date format which sharepoint returned via renderListFormData?

SharePoint Online does consume renderExtendedListFormData. This is not documented or  at least I did not find something about that. Should I better switch to that one although it is not part of pnp? What is the exact difference to renderListFormData?

Thanks.

Regards.

**Comment by patrick-rodgers** [comment]
@pnp/sp-commonjs is from v2 and no longer supported. Is there something blocking you from upgrading to v3?

So we have a whole template for issues you can use to help us understand what you want.

It looks like this is a request for us to add more functionality to the library? Or do some research on the two methods for you?

**Comment by Link631** [comment]
Hi... you can close this issue.

SharePoint returns both dates, the display format and the iso format

for example:

{
     createdDate : 22.12.2022,
     createdDate. : date in iso format
}

the only thing you could eventually do is, to include the endpoint renderExtendedListFormData into the pnpjs client.
RenderExtendedListFormData(itemId=1,formId='editform',mode='2',options=30,cutoffVersion=0)

You have actually included RenderListFormData.

One of the differences is, that extendedListFormData returns dates in iso and in display format and it has the row property with same format like renderListDataAsStream does. This is not included in RenderListFormData but comes with RenderExtendedListFormData.

Due to the fact, that everyone is free to use sphttpclient, it is not urgent but it would be nice to have:-)

Thanks.
