### ISSUE TITLE
The field or property 'TaxCatchAll' does not exist.

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#2499]
### Category
- [ ] Enhancement
- [ ] Bug
- [X ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   3.9.0      ]

Please specify what version(s) of SharePoint you are targeting: [ 1.15.2       ]

### Expected / Desired Behavior / Question
The code:
```
const f: any[] = await projWeb.getList("/Teams/" + projectNumber + "/DPCDocuments").items
            .orderBy('Created').expand("File,TaxCatchAll")
.select("DPCNotes,ServerRedirectedEmbedUrl,Id,DocumentNumber,Modified,File/Name,File/ServerRelativeUrl,File/Length,File/UniqueID,TaxCatchAll/Term,TaxCatchAll/IdForTerm,TaxCatchAll/IdForTermSet")
            .top(4990).filter("RequestNumber eq '" + job + "'")();
```
Works fine on most sites but on some sites it errors with "The field or property 'TaxCatchAll' does not exist."
The SharePoint UI has no problem with the taxonomy field. Only the FPFx web part.

Is there another way to get the label of the taxonomy without  "TaxCatchAll" ? 

Thank you

**Comment by sympmarc** [comment]
Only sites which have Managed Metadata columns will have the TaxCatchAll list. It's created when you add the first one and contains a sort of cache of the Term Sets involved.

**Comment by Ofer-Gal** [comment]
All my sites are made with the same site script. 99% of them are OK 
Every now and then I get this error when running the PnPjs or the sharepoint Api .  
Any way to fix it? Do I need to remove the taxonomy site column and then recreate it?

**Comment by Ofer-Gal** [comment]
Yes

**Comment by mdissel** [comment]
Can you confirm you're not using sub-sites?

**Comment by Ofer-Gal** [comment]
No sub site.
Based on @sympmarc explanation, I recreate the taxonomy site column. then the error was gone.
Thank you all
