### ISSUE TITLE
Multigeo request not working

### ISSUE THREAD

**Issue by mdissel** [pnp/pnpjs#2501]
See the closed isse #2445.

We have updated the code like this:
```
// url :string = <other multitenant>
const web = spfi(url).using(
			DefaultHeaders(),
			DefaultInit(),
			BrowserFetchWithRetry(),
			DefaultParse(),
			PnPLogging(LogLevel.Warning)
		).web;
const scope = this;
web.on.auth.replace(async function (url: URL, init: RequestInit) {
	const provider = await scope.context.aadTokenProviderFactory.getTokenProvider();
	const token = await provider.getToken(`${url.protocol}//${url.hostname}`);
	// eslint-disable-next-line @typescript-eslint/dot-notation
	init.headers["Authorization"] = `Bearer ${token}`;
	return [url, init];
});

```

In the browser we see a redirect to:

```
https://login.microsoftonline.com/{maintenant}/oauth2/v2.0/authorize?
response_type=token&
scope=https%3A%2F%2F<other-tenant>.sharepoint.com%2F.default%20openid%20profile&
client_id=5cdd2cef-7908-44c5-a3e0-d85a4eaafd5a&
redirect_uri=https%3A%2F%2F{main-tenant}.sharepoint.com%2F_forms%2Fspfxsinglesignon.aspx&
state=eyJpZCI6ImZmMWUzNDBmLTczNjAtNDc5ZS04ZTE3LWJmY2FjYmYzYWNmOCIsInRzIjoxNjcwNTk1ODYyLCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9&
nonce=df402f03-9bd3-4773-920e-8ab7ed2b1214&
client_info=1&
x-client-SKU=MSAL.JS&
x-client-Ver=1.4.12&
sid=c5431dae-72b0-45ed-a465-715cf6df7ebe&
client-request-id=b0c75243-76f2-4875-8b5b-9353149fb544&
prompt=none&
response_mode=fragment

```
It's returning a token and the token is passed to the API request on the other-mutli-geo-tenant, but we still get a 403 / {lang: "nl-NL", value: "Attempted to perform an unauthorized operation."}

We copied the token and manually started a request (via PostMan) using the token to the main site (to assure we didn't get a token from the main tenant), the request returned: {"error_description":"Exception of type 'Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException' was thrown."

Is the redirect_uri in the /authorize request correct? it's set to the {main-tenant} and not to the {other-teant}.?

We currently have access to multi-geo environment to run more test, so any suggestions are welcome!

**Comment by patrick-rodgers** [comment]
Closing due to age.
