### ISSUE TITLE
How to get the UTC Date and Time of Created and Modified of files and folders.

### ISSUE THREAD

**Issue by JarialAnkur** [pnp/pnpjs#2503]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

### Category
- [ ] Question

### Version

Please specify what version of the library you are using: [  3.5.1  ]

Please specify what version(s) of SharePoint you are targeting: [ 1.15.0  ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
 I am using the API "getFolderByServerRelativeUrl" in this i am getting details about all the files and folders in that folder. 
I am getting the created and modified dates in the "ListItemAllFields" but those are not in UTC Timezone. 
I want to know how can I get the UTC Timezone time for created and modified of folder and file.

Thank you for your feedback!

**Comment by juliemturner** [comment]
You haven't shared enough information for us to help you, can you please share a code sample.

**Comment by juliemturner** [comment]
This is not a code sample this is a screen shot of the response... which is fine but since I don't know how you got those responses I still cannot help you. If you would like to share a code sample I can try help you

**Comment by aman-sharma24** [comment]
`
export const fileFolder = async () => {
  return await web
    .getFolderByServerRelativeUrl("TenetFiles/AGENCY")
    .select(
      "*",
      "StorageMetrics",
      "Name",
      "UniqueId",
      "Folders/StorageMetrics",
      "Folders/UniqueId",
      "Files/UniqueId",
      "Editor/ID",
      "Editor/Title",
      "Author/Title",
      "Author",
      "Title",
      "Folders/Name",
      "FileSystemObjectType",
      "Files/Name",
      "ServerRelativeUrl",
      "Folder/ListItemAllFields/ServerRelativeUrl",
      "ListItemAllFields",
      "Folders/ServerRelativeUrl",
      "File/ParentFolder",
      "FileSystemObjectType",
      "Files/ServerRelativeUrl",
      "Files/Author",
      "Folders/Author",
      "Files/Editor/ID",
      "Folders/Editor",
      "Length",
      "Folders/Length",
      "Files/Length"
    )
    .expand(
      "ListItemAllFields",
      "StorageMetrics",
      "Folders/StorageMetrics",
      "ParentFolder",
      "Folders/UniqueId",
      "Files/UniqueId",
      "Folders/Name",
      "Files/Name",
      "Folders",
      "Files",
      "Files/ListItemAllFields",
      "Folders/ListItemAllFields",
      "Folders/ServerRelativeUrl",
      "File/ParentFolder",
      "FileSystemObjectType",
      "Files/ServerRelativeUrl",
      "Files/ListItemAllFields/File_x0020_Type",
      "Files/Author",
      "Folders/Author",
      "Files/Editor",
      "Folders/Editor",
      "Files/Length",
      "Folders/Length",
      "Editor/ID"
    )
    .get()
    .then(async (items) => {
      console.log("Items", items);
      return items;
    });
};
`
Above is the function I am using to get the response.
![netWorkCall](https://user-images.githubusercontent.com/84671380/207098151-02770256-82e4-41f8-8cc7-3f95462d052d.PNG)
This is the network request for above call.

**Comment by juliemturner** [comment]
I still don't think I understand your actual question. Have you tried selecting Created and Modified?  You're not showing it in the code sample so I'm assuming you have not?

**Comment by aman-sharma24** [comment]
I want the "Created" & "Last Modified Time" of files & folders in UTC Time format. i.e "2022-12-12T15:06:47Z". 

Only place I could found It was in "StorageMetrics" property but this property was only available for folders, not for files.
And even in Folders only the "Last Modified Time" is provided in UTC Time Format.

![drescribedStorageMetric](https://user-images.githubusercontent.com/84671380/207129131-3905dda4-6d96-4ee5-b4e7-fdc8e5ab53b3.png)

**Comment by patrick-rodgers** [comment]
Can you not convert that date string to the format you need? I am not sure this is something for the library to address, these are the values that come back from the server.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
