### ISSUE TITLE
Folder.MoveByPath results in 403

### ISSUE THREAD

**Issue by benhell** [pnp/pnpjs#2504]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.9.0

Please specify what version(s) of SharePoint you are targeting: Online via O365

### Expected / Desired Behavior / Question

When using an account that does not have permissions to tenant root (e.g., Site Collection admin), a call to "moveByPath" on a Folder object within the same site should succeed. 

### Observed Behavior

moveByPath throws a 403 Unauthorized error. 

### Steps to Reproduce

1. Connect to Sharepoint Instance using an account that does not have permissions to the root. 
2. Call "moveByPath" in a simple scenario (such as merely renaming a leaf folder in the same site). 

This appears to be the same underlying cause as [Issue #1686](https://github.com/pnp/pnpjs/issues/1686) and I was able to fix the issue locally with a similar patch [as this one](https://github.com/pnp/pnpjs/commit/422371ab85789c83f4470796623d7ed451ac78d9) (i.e., changing from "url.origin" to "urlInfo.ParentWeb.Url" in the call). 

Not sure if it is important as a use case to be able to specify whether the operation is being carried out on the root web or the site's web, but flagging for consideration as an option to be specified in the API call.

**Comment by juliemturner** [comment]
The source code for [moveByPath ](https://github.com/pnp/pnpjs/blob/120e840bf3a8f6493ba41d6daceed089579a8537/packages/sp/folders/types.ts#L151) and [copyByPath ](https://github.com/pnp/pnpjs/blob/120e840bf3a8f6493ba41d6daceed089579a8537/packages/sp/folders/types.ts#L199) look to be the same to me, but I might be overlooking something. The PR you reference doesn't exist in the code in that exact way it was somewhat refactored. If you want to share more specifics (like a code sample) we can try and address this or if you think there's a change that needs to be made please feel free to submit a PR of your own.

**Comment by benhell** [comment]
Thanks, Julie. I appreciate the quick response.

The issue isn't that moveByPath and copyByPath are different. The issue is instead that moveByPath and copyByPath both use "this.origin" as the basis for the call to "SP.MoveCopyUtil.MoveFolderByPath()."

I understand this only works if the user has permissions to the root tenant (I think that's the term). The call fails with 403 Unauthorized if the user does not have those permissions. Moreover, the user shouldn't need those permissions to use the "moveByPath" functionality to move things around locally (i.e., within the same site to which they have admin permissions).

In v2 of pnpjs, "moveTo" and "copyTo" also used to use "this.origin" as the basis for the call to "SP.MoveCopyUtil.CopyFolder()" and had a similar issue of triggering a 403 Unauthorized. The patches I refer to above fixed this by changing the parameter from "this.origin" to "urlInfo.ParentWeb.Url" (presumably the URL of the site rather than the root site).

I've verified this works by manually changing line 125 of @pnp\sp\folders\types.js as follows:


        // await spPost(Folder([this, uri.origin], "/_api/SP.MoveCopyUtil.MoveFolderByPath()"), body({

        await spPost(Folder([this, urlInfo.ParentWeb.Url], "/_api/SP.MoveCopyUtil.MoveFolderByPath()"), body({

Recognizing that there may be scenarios where you DO need root tenant permissions (e.g., perhaps moving files between sites) my thought is that this could be parameterized. Something like "RequiresRootTenantAccess" defaulting to true with the option to set to false for local-only moves? I defer to you all on overall design. I just need to address the fact that moveByPath always fails for me since my account does not have root tenant permissions and I don't see another API option for moving folders around.

Hope this clarifies. Please let me know if you have further questions.
________________________________
