### ISSUE TITLE
.setImageField results in TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by brian-lagerman** [pnp/pnpjs#2509]
I'm trying to use the setImageField method on a list item, but when I do I get an exception from queryable.js:

Uncaught (in promise) Error: Unhandled Exception: TypeError: Failed to construct 'URL': Invalid URL
    at Proxy.<anonymous> (timeline.js:145:1)
    at Proxy.error (timeline.js:131:1)
    at queryable.js:132:1

I can find any setup documentation for the function, so I'm assuming I'm missing an import but I can't tell which.

I have:
import { SPFI, spfi } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/fields";

and the offending call:

   await spfi(this._sp).web.lists
        .getByTitle("ListName").items
        .getById(itemId)
        .setImageField("PhotoFieldName", "test.jpg", this.state.image);

All my other calls seem to be fine so I do think I have pnp setup properly in general (unless of course this method needs something special).

        Added addImageField to the fields module and setImageField to item allowing you to easily add image fields to a list and then set the value of that field. Will be released in 2.8

_Originally posted by @patrick-rodgers in https://github.com/pnp/pnpjs/issues/1612#issuecomment-891995347_

**Comment by juliemturner** [comment]
Interesting. This is a new feature from v2, looks like it wasn't documented but yes there may be something broken, will have a look.
