### ISSUE TITLE
How to add custom request headers (e.g "X-ClientTag") to sp request. 

### ISSUE THREAD

**Issue by mmohamedbasith** [pnp/pnpjs#2511]
Using sp pnp version 3 package, How to add custom request headers (e.g "X-ClientTag") to sp request. There is no clear sample available explaining adding custom header or a way to opt out of pnp telemtry in sp pnp version 3

Can you provide a sample 

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    v3     ]

Please specify what version(s) of SharePoint you are targeting: [     v3    ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

**Comment by juliemturner** [comment]
How to inject header docuementation: https://pnp.github.io/pnpjs/queryable/behaviors/#injectheaders

We don't do telemetry in the way many of the other libraries do, but we do metrics by creating an acronym about the method used (not who used it or what tenant or anything just an acronym, like sp.web.list.getbyTitle... becomes "wlg" and include that in a header. If you're really set on removing that from our metrics (which we use to understand if certain endpoints are being used) then you will have to roll your own version of the SPFx behavior. You can do that by cobbling together the usings manually, [this auth documentation](https://pnp.github.io/pnpjs/concepts/authentication/#msal-sp-browser) gives you a starting point, the [SPFX behavior code](https://github.com/pnp/pnpjs/blob/version-3/packages/sp/behaviors/spfx.ts) gives you a listing of what we add for you in the spfx beahvior.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
