### ISSUE TITLE
Link Document (.Url) Thumbnail

### ISSUE THREAD

**Issue by I-BhushanSalunkhe** [pnp/pnpjs#2512]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 2.4.0

Please specify what version(s) of SharePoint you are targeting: SharePoint Online

### Question
1) How to get thumbnail of link document (.Url)?
    We are able to get it for other files like Word, Excel or PPT using below Url.
    https://contoso.sharepoint.com/_api/v2.0/sharePoint:/sites/mySite/Archive/SampleWordDocument.docx:/driveItem/thumbnails/0/medium/content?preferNoRedirect=true

   But, if we try the same for link document, it does not work.

   Sample Link: https://contoso.sharepoint.com/_api/v2.0/sharePoint:/sites/mySite/Archive/SampleWordDocument.Url:/driveItem/thumbnails/0/medium/content?preferNoRedirect=true

2) How to get actual document Url of a link document (.Url)?

**Comment by juliemturner** [comment]
It would make sense that you couldn't get a thumbnail for a .url... so it makes sense that it isn't something that is supported. 

Also, just from a supportability perspective is there anything specific preventing you from upgrading to version 3.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
