### ISSUE TITLE
jsonwebtoken vulnerability in @azure/msal-node@1.13.0

### ISSUE THREAD

**Issue by inkbiegel** [pnp/pnpjs#2513]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    @pnp/nodejs@3.10.0     ]

Please specify what version(s) of SharePoint you are targeting: [    SharePoint Online     ]

### Expected / Desired Behavior / Question
Compiling my app without high severity vulnerabilities.

### Observed Behavior
High security vulnerabilities detected in my Angular app. It seems this version of pnp/nodejs depends on @azure/msal-node@1.13.0 which uses jsonwebtoken@8.5.1. npm informs me jsonwebtoken =< 8.5.1 has 3 high security vulnerabilities:

`jsonwebtoken has insecure input validation in jwt.verify function - https://github.com/advisories/GHSA-27h2-hvpr-p74q
jsonwebtoken's insecure implementation of key retrieval function could lead to Forgeable Public/Private Tokens from RSA to HMAC - https://github.com/advisories/GHSA-hjrf-2m68-5959
jsonwebtoken vulnerable to signature validation bypass due to insecure default algorithm in jwt.verify() - https://github.com/advisories/GHSA-qwph-4952-7xr6
jsonwebtoken unrestricted key type could lead to legacy keys usage  - https://github.com/advisories/GHSA-8cf7-32gw-wr33
fix available via `npm audit fix --force`
Will install @pnp/nodejs@2.0.10, which is a breaking change
node_modules/jsonwebtoken
  @azure/msal-node  *
  Depends on vulnerable versions of jsonwebtoken
  node_modules/@azure/msal-node
    @pnp/nodejs  >=2.0.11
    Depends on vulnerable versions of @azure/msal-node
    node_modules/@pnp/nodejs`

### Steps to Reproduce
Install the latest version of pnp/nodejs and run `npm audit`

The latest version of @azure/msal-node is currently 1.14.5. I'd rather not `npm audit fix --force` unless I really have to, as it would bump the version of pnp/nodejs down to 2.0.10 which will probably break a bunch of things.

I'm very new to node and Angular so if this is not the correct place for this I apologize in advance.

**Comment by juliemturner** [comment]
Thanks for letting us know. An oversight in our last release -- we missed updating the child package.json files in each of the packages, sorry about  that. The update will be in the nightly release or if you'd rather wait the monthly release in January.
