### ISSUE TITLE
Replace the `office365Tenant.call` method example as it's not working as expected?

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/pnpjs#2518]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.10.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question

When using the `createGroupForSite` method provided as an example in the `call` method [here](https://pnp.github.io/pnpjs/sp-admin/#call), it's supposed to work as expected.

### Observed Behavior

When trying to use the `createGroupForSite` method provided as an example in the `call` method [here](https://pnp.github.io/pnpjs/sp-admin/#call), I got the following error:

**The method CreateGroupForSite cannot be invoked as its parameter optionalParams is not supported.**

This behavior is observed whether I add or omit the mentioned parameter.

Moreover, when querying the _https://contoso.sharepoint.com/_api/$metadata_ endpoint, it seems that this method had disapeared or isn't exposed anymore.

### Steps to Reproduce

* Take the `call` method example and replace it with your own tenant context

### Proposal

What I'm suggesting is to replace the `call` example with another method like `getExternalUsers` or `addTenantCdnOrigin` which are currently working as expected.

I can give a try on it if you're ok 🙂

**Comment by patrick-rodgers** [comment]
Sure, if the method no longer exists and you have time to update the docs that would be great. It worked whenever it was written, I guess that class has changed since so great to get it updated.
