### ISSUE TITLE
need to add $count=true for a managementchain request in graph, but can't understand where to add it

### ISSUE THREAD

**Issue by trillian74** [pnp/pnpjs#2526]
I'm getting the management chain for a user, but can't understand where to put it in my request. 

Tried to find it in the documentation or elsewhere - hopefully it's just me not seeing it?

` managementChain = await graph.using(ConsistencyLevel("eventual")).users.getById(difference[0].id).expand("manager($levels=max;$select=id,displayName,userPrincipalName)").select('id,displayName,userPrincipalName')();`

ref this rest that works
`https://graph.microsoft.com/v1.0/users/bottomLine@myorg.com?$expand=manager($levels=max;$select=id,displayName,userPrincipalName)&$select=id,displayName,userPrincipalName&$count=true`
                   

### Category
- [x ] Enhancement
- [ x] Bug
- [x ] Question
- [ x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.9]

Please specify what version(s) of SharePoint you are targeting: [Online]

**Comment by patrick-rodgers** [comment]
You can use `.query`:

```TS
const managementChain = graph.using(ConsistencyLevel("eventual")).users.getById(difference[0].id).expand("manager($levels=max;$select=id,displayName,userPrincipalName)").select('id,displayName,userPrincipalName');

managementChain.query..set("$count", "true");

const result = await managementChain();
```

**Comment by trillian74** [comment]
Worked perfectly. Thanks alot for the swift response @patrick-rodgers
