### ISSUE TITLE
Can sp.utility.sendEmail send emails to shared emails or distribution lists?

### ISSUE THREAD

**Issue by rzempo** [pnp/pnpjs#2527]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.7.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Send emails to shared emails or distribution lists using sp.utility.sendEmail

### Observed Behavior
Email isn't sent. No error is thrown. 

### Steps to Reproduce
Send email to shared emails or distribution lists using sp.utility.sendEmail

**Comment by rzempo** [comment]
[1471](https://github.com/pnp/pnpjs/issues/1471) back in 2022 mentioned is an API limitation. Just wondering if that's still the case.

**Comment by juliemturner** [comment]
I'm sure it is those API's rarely if ever change... but you could check.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
