### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by NigelWit** [pnp/pnpjs#2529]
### Category
- [X] Bug

### Version
Please specify what version of the library you are using: [  2.10  ]
Please specify what version(s) of SharePoint you are targeting: [  SharePoint Online / SPfx 1.12.1 ]

### Issue Description

I am suddenly getting a failed response form the SharePoint Search API when calling it using "sp.search()". The code being used is:

`
// Set search query settings
const searchQuerySettings = {
      Querytext: query ? query : "*",
      EnableFQL: false,
      ClientType: "ContentSearchRegular",
      TrimDuplicates: false,
      RowLimit: 500,
      EnableSorting: true,
      SortList: [
        {
          Property: "LastModifiedTime",
          Direction: SortDirection.Descending,
        },
      ],
      RefinementFilters: [refinementFilter],
      SelectProperties: [
        "Title",
        "ListID",
        "ListItemID",
        CrawlProperties.Centre,
        CrawlProperties.CommencementDate,
        CrawlProperties.DocumentType,
        CrawlProperties.ExpiryDate,
        CrawlProperties.Lessee,
        CrawlProperties.ShopNo,
        CrawlProperties.TradingName,
        CrawlProperties.Version,
        "Created",
        "Modifed",
        "SPSiteUrl",
        "ParentLink",
        "OriginalPath",
        "Author",
        "Path",
        "DocId",
      ],
    };

    // DEBUG
    Log(SRC, "Calling search API...");

    return sp.search(searchQuerySettings).then((res) => {
     // Do stuff
    }
`

Calling the "sp.search" function results in an error:

"Error making HttpClient request in queryable [500]  ::> {"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}"

I have confirmed the search (query and refinement filters) works using Mikael Svenson's "SharePoint Search Query Tool", and the fact that this error is being reported by multiple different solutions leads me to believe some issue has been introduced in the PnP library?

Any help would me GREATLY APPRECIATED as this issue is being reported in multiple production solutions.

Thanks!

**Comment by juliemturner** [comment]
A 500 server error is a server error, and thereby an internal error with the REST API so this would not be a PnPjs issue. There is nothing really you can do about it when the issue happens except handle it gracefully and submit an issue to Devolutions/or open a ticket with Microsoft support.

**Comment by NigelWit** [comment]
Thanks Julie - I'll raise a ticket with them now
