### ISSUE TITLE
renderListDataAsStream doesn't work in v3 as it used to in v2

### ISSUE THREAD

**Issue by rzempo** [pnp/pnpjs#2530]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [^3.7.0]
Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
renderListDataAsStream returns data in v3 following https://pnp.github.io/pnpjs/sp/lists/#render-list-data-as-stream as it used to in v2

### Observed Behavior
The code below used to work on v2 (^2.11.0)
```
import { Web } from "@pnp/sp/webs";

const list = Web([url of site different than current site]).lists.getById([listId]);
const listViewXml = await (await list.views.getById(viewId).select("*").get()).ListViewXml;

const resultsViewItems = await list.renderListDataAsStream({
  DatesInUtc: true,
  OverrideViewXml: listViewXml
});

resultsViewItems.Row.forEach(item => {
  console.log(item);
});
```

The code above adapted to v3 doesn't work at renderListDataAsStream throwing a "Cannot read properties of undefined (reading 'web')" error. 
```
import { Web } from "@pnp/sp/webs";

const list = Web([url of site different than current site]).lists.getById(listId);
const view = list.views.getById(viewId);

const listViewXml = await (await view()).ListViewXml;

const resultsViewItems = await list.renderListDataAsStream({
  DatesInUtc: true,
  OverrideViewXml: listViewXml
});

resultsViewItems.Row.forEach(item => {
  console.log(item);
});
```

I also tried initializing the list using  spfi instead but same result
```
const sp: SPFI = spfi([url of site different than current site]).using(SPFx(this.props.context as any));
const list = sp.web.lists.getById(config.ListId);
```

### Steps to Reproduce
```
import { Web } from "@pnp/sp/webs";

const list = Web([url of site different than current site]).lists.getById(listId);
const view = list.views.getById(viewId);

const listViewXml = await (await view()).ListViewXml;

const resultsViewItems = await list.renderListDataAsStream({
  DatesInUtc: true,
  OverrideViewXml: listViewXml
});

resultsViewItems.Row.forEach(item => {
  console.log(item);
});
```

**Comment by juliemturner** [comment]
Can you review this section in the transition documentation on using Web in V3 and see if that solves your issue?

https://pnp.github.io/pnpjs/transition-guide/#web-spfi

**Comment by rzempo** [comment]
Thanks for the quick reply @juliemturner. I'll try and report back.

**Comment by rzempo** [comment]
Using the code as in the transition guide resolved my issue. Thanks @juliemturner. This ticket can be closed now.
```
const spWebA = spfi().using(SPFx(this.context));
const spWebE = Web([spWebA.web, "{Absolute URL of Other Web}"]);
```
