### ISSUE TITLE
Expiring request digest after 30 minutes

### ISSUE THREAD

**Issue by Tanddant** [pnp/pnpjs#2531]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.9.0 ]
-Will update to 3.10.0 and get users to confirm the issue is still ongoing

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online (Using SFPx Version 1.14.0) ]

### Expected / Desired Behavior / Question
When calling

    sp.lists.getByTitle(LIST_NAME).Items.add({Title: "Testing"});

I expect to be able to create a listitem - and that works

### Observed Behavior
If however the user waits idle for 30 minutes (goes to a different tab) I'll get the following error 

``` JSON
{
    "odata.error": {
        "code": "-2130575252, Microsoft.SharePoint.SPException",
        "message": {
            "lang": "en-US",
            "value": "The security validation for this page is invalid and might be corrupted. Please use your web browser's Back button to try your operation again."
        }
    }
}
```

I've tried both spfi setup as suggested in #2186 

    spfi().using(SPFx(props.context));
and

    spfi().using( SPBrowser({ baseUrl: context.pageContext.web.absoluteUrl }) );

### Steps to Reproduce

The following snippet should create a list item and try again 35 minutes later where it'll fail.

``` TypeScript
const sp = spfi().using(SPFx(context));
const item = sp.web.lists.getByTitle(LIST_TITLE).items.add({ Title: "Test 1" });
setTimeout(() => {
  const item1 = sp.web.lists.getByTitle(LIST_TITLE).items.add({ Title: "Test 2" });
}, 35 * 60 * 1000);
```

---

### Additional info

There are two older issues regarding the same issue:
- #2186 
- #2102

I know this is a far fetched edge case, but I've had it come up in several cases, especially when building dashboard tools that users will have open all day, and maybe only need to interact with seldomly, like a overview of their tasks, they'll open it in the morning, get to working and maybe 2 hours later go back and write a comment to a task which will then fail.

&nbsp;

Now of course since my code is so flawless it'll cache their inputs before telling them their session has expired and to please refresh and try again .... or well realistically they loose their work and call me very frustrated - your guess is as good as mine, but here I am writing this issue 😅

---

I've considered a simple hack being using a timer to reinitialize my context:

``` TypeScript
const sp: SPFI = null;
const refreshContext: () => void = () => { sp = spfi().using(SPFx(context)) };
refreshContext();
setInterval(() => refreshContext(), 15 * 60 * 1000);
```

But that feels way to sketchy, and I'm very much unsure if that's even a solution

**Comment by juliemturner** [comment]
Thanks for your question, that said there isn't really enough information here for us to reproduce the issue. We did in the past have a bug in the code with not getting a fresh token and using the one that is on the page which caused a timeout issue but that has been fixed, as you referenced. 

If you can provide a sample application that we could take a look at we might be able to offer you more assistance but at this point I'm not sure how we can help.

**Comment by bcameron1231** [comment]
Typically we see this when you're instantiating your SPFI object and SPFx behavior over and over again. It's hard to tell from the information in the issue, but it looks like this may be the case as well. Agreed with @juliemturner  if you could share a solution that would be helpful and I'd happily take a look.

Based on the provided code, I would suggest taking a look at the samples on this page.
https://pnp.github.io/pnpjs/getting-started/#getting-started-with-sharepoint-framework

Check out how the context is being instantiated once at a higher level in the pnpjsConfig.ts file and being re-used within the application.

**Comment by Tanddant** [comment]
Thanks for the input - wasn't sure how much code you wanted, I'll try and create an as isolated sample as possible (and look over the code I already have, to see if maybe that's whats happening) 😊

**Comment by Tanddant** [comment]
I can confirm from a very simple test that even after a few hours it works - and calls contextinfo prior, I'm not sitting with the code where I'm experiencing the issue right now, I'll check with my colleague on monday if there some kind of loop where the "provider" class's constructor is somehow being run serveral times - I'll report back, but as of now it looks like it's not a PnPJS issue, sorry for the inconvenience, I'll close the issue as soon as I've verified

**Comment by bcameron1231** [comment]
Sounds great! Also I don't know if you're using React, but re-renders of components also come into play as a possible issue.

Thanks for the update and keep us posted.
