### ISSUE TITLE
New feature: create a M365 Group for a site (or implement whole `GroupSiteManager` endpoint?)

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/pnpjs#2535]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.11.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question

Raised from #2534, the idea is to add a new method to create a M365 Group for a specific site, from the `GroupsiteManager` endpoint, which is `CreateGroupForSite` (full endpoint method call: `/_api/GroupSiteManager/CreateGroupForSite`). I've tested this one recently and it's working.

Furthermore, I was wondering if it would be relevant to add a new class in the `@pnp/sp-admin` (or `@pnp/sp`?) node for the `GroupSiteManager` which would include all the methods available? This would include the generic `call` method like for the `@pnp/sp-admin` node.

Finally, the existing `office365Tenant.createGroupForSite` method would be deleted from the source code, as it's not available anymore.

**Comment by patrick-rodgers** [comment]
That all sounds good to me. IMO I'd add it to the `@pnp/sp-admin` library and implement it following the patterns in there. Should be a great addition!

**Comment by michaelmaillot** [comment]
Great, thanks for assigning it to me! I'll do my best for this first time.

Just to be sure (I know I've probably put some confusion): are we talking about adding a `CreateGroupForSite` method or implementing a whole new class (`GroupSiteManager`)?

**Comment by patrick-rodgers** [comment]
A whole new class works for me, or if you want to start with just adding the method that is also OK. The group manager API isn't one I am super familiar with off the top of my head so trust your work.

**Comment by michaelmaillot** [comment]
Thanks for this feedback @RoelVB, I was just starting to test out a method or two when I realized the "context" stuff:

`Authentication method is not allowed.`

Like you said, it's not documented, welcome to the deep world of SharePoint undocumented REST API 😆 

I'll try to document methods based on my own experience / tests.

But from what I see on your PR, you already include a method from `groupsitemanager` endpoint (the `createGroupEx` method), so I don't know how to handle this. @patrick-rodgers should I exclude this one from what I'm working on? Or keep going and we'll see once I'll submit the PR (since the one from @RoelVB is already under review)?

**Comment by michaelmaillot** [comment]
Right but I'm not mistaken, the `groupsitemanager` doesn't require API permissions, unlike Graph. It relies on the current user's permissions. But I will dig that.

**Comment by juliemturner** [comment]
I understand that but you probably can circumvent some of the application permission limitations with Graph, but again not exactly sure what methods you're implementing.

**Comment by RoelVB** [comment]
@juliemturner, indeed the Graph doesn't offer the same options as the `GroupSiteManager`.
It can for example transform an existing site to a group connected site ([`CreateGroupForSite`](https://s-kainet.github.io/sp-rest-explorer/#/_api/groupsitemanager/CreateGroupForSite)).

And like @michaelmaillot says. the `GroupSiteManager` doesn't require any extra API permissions.

**Comment by michaelmaillot** [comment]
So I've got time to move forward on this improvment, time to share some feedback / questions before pushing the code 🙂 

First:

> Thanks for this feedback @RoelVB, I was just starting to test out a method or two when I realized the "context" stuff:
> 
> `Authentication method is not allowed.` 

So it appears that this message is raised when you don't use the "X-RequestDigest" header. So I've documented the methods accordingly when needed.

Secondly, it seems that for some methods, no matter what I tried, I'm facing an error which I couldn't get through. I plan to not include them in the available methods. And if someone manage to make them work (through the generic `call` method let's say), they will be free to implement them in the code through a PR.

Thirdly:

> But from what I see on your PR, you already include a method from `groupsitemanager` endpoint (the `createGroupEx` method), so I don't know how to handle this. @patrick-rodgers should I exclude this one from what I'm working on? Or keep going and we'll see once I've submited the PR (since the one from @RoelVB is already under review)?

Any opinion about this everyone?

And lastly, I didn't plan to add some tests because since we're working with undocumented APIs, we have no guarantee that Microsoft will not update their interface contracts anytime, so even if I write tests that would work right now, I can't assure that they will work in the future. But maybe I'm wrong?


I will submit my PR once we've covered everything if that's ok for you.

**Comment by juliemturner** [comment]
>But from what I see on your PR, you already include a method from groupsitemanager endpoint (the createGroupEx method), so I don't know how to handle this. @patrick-rodgers should I exclude this one from what I'm working on? Or keep going and we'll see once I've submited the PR (since the one from @RoelVB is already under review)?

I don't know how to answer that as I don't know what your structure is, I would say obviously don't implement the endpoint twice. Maybe you should submit a PR in its working state, so we have something to discuss.

>And lastly, I didn't plan to add some tests because since we're working with undocumented APIs, we have no guarantee that Microsoft will not update their interface contracts anytime, so even if I write tests that would work right now, I can't assure that they will work in the future. But maybe I'm wrong?

I'm not sure I follow this logic. I would consider the fact that the API could change at any point MORE of a reason to implement tests, not less. Adding undocumented APIs is something @patrick-rodgers and I have been discussing lately. There is a part of me that feels like we shouldn't do it, but at the same time, when you need to get something done then sometimes, depending on the criticality of the system, the risk is worth the benefit. It's a tricky since Microsoft hasn't really made a public statement about the use of undocumented APIs. Regardless, that is not a reason not to write tests.

**Comment by michaelmaillot** [comment]
> I don't know how to answer that as I don't know what your structure is, I would say obviously don't implement the endpoint twice. Maybe you should submit a PR in its working state, so we have something to discuss.

Got it.
 
> I'm not sure I follow this logic. I would consider the fact that the API could change at any point MORE of a reason to implement tests, not less. Adding undocumented APIs is something @patrick-rodgers and I have been discussing lately. There is a part of me that feels like we shouldn't do it, but at the same time, when you need to get something done then sometimes, depending on the criticality of the system, the risk is worth the benefit. It's a tricky since Microsoft hasn't really made a public statement about the use of undocumented APIs. Regardless, that is not a reason not to write tests.

I probably misspoke about my thoughts. It's not the fact of API changes which is problematic for me, but the fact that since it's not documented, we won't be notified in case of changes (the example of #2518 is a proof according to me), and if those are mocked (I didn't check how tests were written tbh), we can't guarantee that they will still be valuable in their state in the future (I mean expected results vs potential updated ones). Furthermore, I've noticed that there wasn't tests written for the other `@pnp/sp-admin` so I was assuming (wrongly?) that it wasn't relevant. That said, I can still write tests that reflect the actual behavior.

And regarding implementing undocumented API in general I still think it's valuable, including for reasons you mentioned 🙂

**Comment by juliemturner** [comment]
>It's not the fact of API changes which is problematic for me, but the fact that since it's not documented, we won't be notified in case of changes

Again, IMHO all the more reason to write tests... that's how we're notified if something changes because the tests would break.

>Furthermore, I've noticed that there wasn't tests written for the other @pnp/sp-admin so I was assuming (wrongly?) that it wasn't relevant.

So first, that's a different package, but second, they we're created not because we didn't think they were needed, it was because we didn't want to change the behavior of our test tenant at that level. Unfortunately, we don't have a separate tenant test test the admin APIs.

**Comment by michaelmaillot** [comment]
Ok so in the meantime I've had a look at the library's tests and I better understand your point. Since many tests aren't mocked, it makes sense to write them in order to ensure that the expected results still occur when running locally.

I will give a try on writing tests based on what's feasable / removable.
