### ISSUE TITLE
Header settings for cross domain from SPO to SP 2013 hosted app

### ISSUE THREAD

**Issue by arma78** [pnp/pnpjs#2537]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  "sp-pnp-js": "^3.0.10",       ]

Please specify what version(s) of SharePoint you are targeting: [  SP 2013 ]

Hi there,
I am trying to make get request from SPO to 2013 SP  hosted app. (Same creds on both domains)
Getting 401 error. What I have to change in headers? Thank you. 

 const listOptions: IDropdownOption[] = [];
    let MyWeb = new Web("https://xxxxxxxx.eu");
    const docLibs: IDocumentLibraryInformation[] = await MyWeb.lists.filter("(BaseTemplate eq 101) and (Hidden eq false)").configure({
      cache: "no-cache",
      mode:"no-cors",
      headers: {
        "Accept":"application/json;odata=verbose",
        "Access-Control-Allow-Methods": "GET,HEAD,OPTIONS,POST,PUT",
        "Access-Control-Allow-Headers": "Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Headers",
      },
  }).get();

<img width="566" alt="t13" src="https://user-images.githubusercontent.com/37850817/212730020-ae36fa18-4731-4571-9451-d8b897eaa46c.png">

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!

**Comment by arma78** [comment]
Thank you Patrick.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
