### ISSUE TITLE
Property 'get' does not exist on type 'IFields'

### ISSUE THREAD

**Issue by leodak** [pnp/pnpjs#2538]
**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

"@pnp/sp": "^3.11.0"
"@pnp/common": "^2.15.0",
"@pnp/logging": "^3.11.0",
"@pnp/nodejs": "^3.11.0",
"@pnp/odata": "^2.15.0",
"react": "16.13.1"
SharePoint Online

### Expected / Desired Behavior / Question
`var spListColumns = _sp.web.lists
          .getById(this.properties.listId)
          .fields.filter(
            "ReadOnlyField eq false and Hidden eq false and TypeAsString eq 'Choice'"
          ).get();`
to get all fields

### Observed Behavior
`Property 'get' does not exist on type 'IFields'.`

### Steps to Reproduce
* Create SPFx webpart and in webpart properties showing all list from the current site collection.
* After a list is selected, trying to fetch a list fields based on the selection.

**Comment by juliemturner** [comment]
In version there you wouldn't use the .get() modified, it was [deprecated](https://pnp.github.io/pnpjs/transition-guide/#dropping-get).

I see that you're mixing versions, that's not going to be supported as they are all peer dependencies. You could reduce this list to:

"@pnp/sp": "^3.11.0"
"@pnp/logging": "^3.11.0",
"@pnp/nodejs": "^3.11.0"

**Comment by leodak** [comment]
@juliemturner thank you, so what's alternative.
Instead of .get() I can use 
`var spListColumns = _sp.web.lists .getById(this.properties.listId) .fields.filter( "ReadOnlyField eq false and Hidden eq false and TypeAsString eq 'Choice'" )

spListColumns.???`

**Comment by juliemturner** [comment]
You just invoke it... spListColumns();

**Comment by leodak** [comment]
Thank you
