### ISSUE TITLE
Adding a moment to a timeline

### ISSUE THREAD

**Issue by wmertens** [pnp/pnpjs#2542]
### Category
- [x] Question

### Version

Please specify what version of the library you are using: [latest]

Please specify what version(s) of SharePoint you are targeting: [online]

### Question

We are using a semaphore to rate-limit Queryable requests, and for that we need to know when a request is completed.

We tried some approaches, including having our own `parse` moment that releases the semaphore, but several methods replace the `parse` moment silently.

So now we tried adding our own moment, by having a custom `send` moment that determines when the `fetch` is done (including downloaded streams) and then doing `this.emit.fetchCompleted`, but then typescript complains because that's a protected method.

However, it works, and we can't think of a better way. Is there a better way? Maybe `.emit` can become a public method?

**Comment by patrick-rodgers** [comment]
This should work fine:

```TS
sp.web.on.send.replace(async function (this: ISPQueryable, url, init) {

  this.emit["MyCustomThing"]

  return null;
});
```

**Comment by wmertens** [comment]
Hmm, when I do

```ts
const FetchExtra = (
	props: INodeFetchWithRetryProps
): TimelinePipe<Queryable> => {

	return instance => {

		instance.on.send(async function (_url, init) {
			// ...
			const fetchP = fetch('...')

			// release sema
			fetchP
				.then(r => {
					this.emit.fetchCompleted()
				})
```

Then TS complains that `Property 'emit' is protected and only accessible within class 'Timeline<T>' and its subclasses.ts(2445)`

**Comment by patrick-rodgers** [comment]
You need to type the `this` as shown in the example I gave.

**Comment by wmertens** [comment]
Ah yes I missed that, apologies.

It does complain about the unknown moment though, so it's not fixed entirely. I tried to fix it with this:

```ts
type FCTimeline = Timeline<{
	fetchCompleted: (
		observers: ((err?: string | Error, info?: any) => void)[],
		err?: string | Error,
		info?: any
	) => void
}>

// Argument of type '(this: FCTimeline, _url: URL, init: RequestInit) => Promise<any>' is not assignable to parameter of type 'QueryableSendObserver'.
instance.on.send(async function (this: FCTimeline, _url, init) {
```

which does make the `this.emit.fetchCompleted(...)` work properly but gives the above error.

Is there a way to add the moment to the type?

**Comment by patrick-rodgers** [comment]
You can subclass it and recreate Queryable with the moments you want.

You can also see how we've done the same thing using Symbols, but you will need to use the [] vs dot notation.

https://github.com/pnp/pnpjs/blob/version-3/packages/queryable/behaviors/resolvers.ts#L10

https://github.com/pnp/pnpjs/blob/version-3/packages/queryable/queryable.ts#L45

https://github.com/pnp/pnpjs/blob/version-3/packages/queryable/queryable.ts#L213

**Comment by wmertens** [comment]
Hmm, with the `[]` notation you basically turn off type checking for that function call, right?

How would I subclass it while also adding moments to the timeline, since you can only subclass a single class? Or would I have to copy Queryable entirely?

Maybe Queryable can take an extra generic? Something like
```ts
export declare class Queryable<R, M = {}> extends Timeline<typeof DefaultMoments & M> implements IQueryableInternal<R> {
```
but with helpers for more easily defining moment arguments?

**Comment by patrick-rodgers** [comment]
You are free to fork the library and add anything you'd like. Spending hours to enable you to use dot notation isn't really something I'm interested in. Going to close this as answered as you've got a way to achieve the outcome you need.

**Comment by wmertens** [comment]
Ok makes sense, it's not worth spending a lot of time on. Thank you for your help :pray:
