### ISSUE TITLE
[SP Search] Why do deleted sites show up in my results?

### ISSUE THREAD

**Issue by kbeeveer46** [pnp/pnpjs#2544]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.11.0]

Please specify what version(s) of SharePoint you are targeting: [1.16.1]

### Expected / Desired Behavior / Question

I have the following Querytext which returns all sites on a hub except the hub site and a few specific sites I don't want returned. The problem is that it's returning sites that have been deleted and even permanently deleted from the "deleted" section in SharePoint admin. Is it a bug in PnP? Are the results being cached even though I tell it to never cache? Is there a way to not return deleted sites? It's been over 24 hours since they've been deleted.

Unrelated issue 1: I've also noticed that random sites don't get returned in the results unless I have TrimDuplicates = false. It's completely random. We have a web part that lists out all the sites and one day I noticed it wasn't returning a certain site out of several hundred and then a few days later it did the same thing but a different site that time. They only common theme between them is that I was viewing both of them quite often around that time. It also happened to another user and not just me.

Unrelated question 2: Why does it take 15+ minutes for a new site to be returned in this query? I assume it's from caching. Is there a way to have this query always return result in real time?

Is there a better way to get all sites on a hub that doesn't have all these weird quicks that I outlined above?

```
spfi().using(SPFx(this._context), CacheNever()).search({
Querytext: `
contentclass:STS_Site 
AND departmentid:${hubSiteId}  
AND NOT siteid:${hubSiteId}  
AND NOT siteid:b29f5fd1-fbab-4e5c-bba8-f8c86859dad8 
AND NOT siteid:a4b13f03-4ca7-4b2c-9c0e-1f3a6ebaf5cb 
AND NOT siteid:04f7b2ef-6c21-425a-b8ec-a7358a9d5a50`,
RowLimit: 10000,
SelectProperties: ["Path", "Title", "SiteLogo"],
TrimDuplicates: false
}).then(results =>
{
........

});
```

**Comment by juliemturner** [comment]
This would not be a bug in PnP as we pass through the results from the API. You can verify this by inspecting the call in the network tab of the browser's development console.  I will tell you that when you delete a site in Microsoft 365 that's considered a "soft delete" and the site doesn't actually get deleted right away.  You can see this by going into the SharePoint admin center and looking at the deleted sites.

![image](https://user-images.githubusercontent.com/7570936/213878985-92776d8f-e217-4972-b995-a74953b9e78a.png)

If the site is associated with a M365 group (i.e. a modern team site) you can also see the associated group in the deleted groups section of the Microsoft 365 admin center.

![image](https://user-images.githubusercontent.com/7570936/213879012-ae7c62f8-9a7b-4133-8f14-a89183441aee.png)

**Comment by kbeeveer46** [comment]
@juliemturner Gotcha. Do you think it's a bug with SharePoint? We have a web part that shows a blue "card" for every site as you can see below. I also posted 4 screen shots showing there are no active or deleted groups or sites with "abc" in it. But the site is still being returned from the API. Since it's not in any of the active or deleted lists, I don't know where SharePoint is getting it from. I've tried viewing the page on several computers and the ABC site is always in the list.

![List](https://user-images.githubusercontent.com/12972554/213879427-36b60bfc-30a7-4c66-9ef9-85463658bce6.png)
![Active Groups](https://user-images.githubusercontent.com/12972554/213879430-8c22d6e6-831d-4de2-9274-5dece58e74bc.png)
![Deleted Groups](https://user-images.githubusercontent.com/12972554/213879432-99683ee6-cda9-40dc-aa1a-9610e0253fbc.png)
![Active Sites](https://user-images.githubusercontent.com/12972554/213879438-033f5d68-97c1-4063-9629-cff5be0304dd.png)
![Deleted Sites](https://user-images.githubusercontent.com/12972554/213879445-bb67ae74-23d4-476f-a5f0-cb0109dcfb80.png)

**Comment by juliemturner** [comment]
Seems most likely it's an issue with your search index. The problem is testing it.  The search bar in the product now uses Microsoft 365 search and not SharePoint search which is what the API you're using uses. I would suggest Microsoft support, but I've dealt with them with Search issue and after having to spend the first hour of the call explaining to support what SharePoint search is vs Microsoft 365 search, I pretty much don't have much confidence they can help.

Maybe there's some metadata on the search results that can help you filter it out.  I honestly don't have a ready answer as this isn't an issue I've ever had and without researching it I can't say I have a lot of ideas.

**Comment by kbeeveer46** [comment]
@juliemturner Thanks. I'll go ahead and close this ticket.
