### ISSUE TITLE
Read Tenant wide Extensions - Component Properties

### ISSUE THREAD

**Issue by Nevinia210** [pnp/pnpjs#2547]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.15.2]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

### Expected / Desired Behavior / Question
Is it possible to read Tenant Wide Extensions - component properties directly from spfx application customizer solution?
if yes, how? :)

**Comment by patrick-rodgers** [comment]
I believe this is a question for [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues).

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
