### ISSUE TITLE
How to retrieve item after update?

### ISSUE THREAD

**Issue by simkessy** [pnp/pnpjs#255]
Hey, 

I'm looking at the update documentation after updates: 

```
list.items.getById(1).update({
    Title: "My New Title",
    Description: "Here is a new description"
}).then(i => {
    console.log(i);
});
```

i'm trying to get the item I just updated back, I'm not sure what I can do with the response I get here: 

![image](https://user-images.githubusercontent.com/5871660/45933753-df9d2080-bf47-11e8-98dd-e7d07da14682.png)

I was looking for something like this back: 

![image](https://user-images.githubusercontent.com/5871660/45933757-ffccdf80-bf47-11e8-8525-77f87223cfde.png)

**Comment by koltyakov** [comment]
Hi @simkessy,

Didn't get the question. `ItemUpdateResult` return data type was there for ages. It contains `data` object with etag and `item` object which can be used for chaining. E.g.:

```typescript
list.items.getById(11)
    .update({ Status: 'Updated' })
    .then(({ item }) => item.get())
    .then(console.log)
```

![image](https://user-images.githubusercontent.com/7816483/45940144-f2fbca80-bfdf-11e8-843b-f716a5b8c0cb.png)

![image](https://user-images.githubusercontent.com/7816483/45940097-a7492100-bfdf-11e8-83dc-89ab9c3916cc.png)

**Comment by koltyakov** [comment]
After the request, the context object can be used for whatever purposes needed (getting data, permissions manipulation, further update, deletion, etc.). IMO, it's not so interesting in update situation as we already have an item to update, but can be handy with creating operations.

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please _reopen_ the issue if there is a need to continue the conversation. Thanks!
