### ISSUE TITLE
Request digest not renewed after re-activation of sleeping tab

### ISSUE THREAD

**Issue by jacksonv1lle** [pnp/pnpjs#2550]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

PnPJS - 3.11.0
SharePoint Online
Microsoft Edge

### Expected Behavior
If a tab in MS Edge has been left for over 30 minutes and the browser tab has been put to sleep (sleeping tabs), when the user returns to the tab and performs an API request (without refreshing the page), a new digest should be fetched from `/_api/contextinfo` and provided in the header of the request.

### Observed Behavior
Upon returning to the sleeping tab after 30 minutes and performing an API request, the expired digest is taken from the page context and the request fails.

[In this file](https://github.com/pnp/pnpjs/blob/ae854e40a754b4f1dff5ea3a5d9e19779d28d2db/packages/sp/behaviors/spfx.ts#L34), when generating a new expiry date for the digest, we are using `performance.now()` to determine the lifetime of the page. The problem is that when a sleeping tab has been re-activated, the `performance.now()` value is reset to 0 so the lifetime of the page is not interpreted correctly and the digest is not renewed.

### Steps to Reproduce
It is difficult to reproduce this as it involves a lot of waiting around and hoping the tabs go to sleep...

However, the behavior can be reproduced manually by simply setting the value of the `formDigestValue` to an expired value before making a request. 

In the initialization method of a web part, set the value of the digest to an expired value then perform a request using pnpjs

    const sp = spfi().using(SPFx(this.context));

    this.context.pageContext.legacyPageContext.formDigestValue ="0xB3E30D5261D4A722618E2A4A0EA9749903CA3DCC61FE31E9D1064B78E187DC0667A52491B31B9B2F4896DECFF91B5D08349E93DB4354203251F351D7CD2C0FAA,24 Jan 2023 12:41:21 -0000";
    
    sp.search("test").then(console.log).catch(console.error);

I think the timestamp at the end of the digest should be used to determine how old the token is

![error](https://user-images.githubusercontent.com/2648490/214413153-b223ee26-2fd7-41ab-b139-8746c5affbbe.png)

**Comment by NewGHUser4321** [comment]
I did this when I had this issue.

```
import { DigestCache, IDigestCache, } from '@microsoft/sp-http';
const digestCache: IDigestCache = this.context.serviceScope.consume(DigestCache.serviceKey);
```
Whenever I send a request, I do this

```
sp.using(InjectHeaders({ "X-RequestDigest": await digestCache.fetchDigest(props.context.pageContext.web.serverRelativeUrl) })).web.lists.getById(listId)
```

Hope this helps.
