### ISSUE TITLE
Adding taxonomy terms from a SharePoint Framework web part fails with a 403 error

### ISSUE THREAD

**Issue by ekdegerman** [pnp/pnpjs#2552]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version
Please specify what version of the library you are using: [3.11.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
I'm trying add a term to an open site scoped term set from a SharePoint Framework web part on a modern page in SharePoint Online. The documentation for sp/Taxonomy seems to indicate that adding children to a term set should still be possible in v3, though it is not completely clear if there are limitations to where this can be used.  

### Observed Behavior
Reading the term store works fine, but trying to add new terms results in the error below:
`Error making HttpClient request in queryable [403] ::> {"error":{"code":"notAllowed","message":"OAuth only flow is enabled and the call has not been issued from an app."}}`
Adding terms used to work way back in v1, but I know v3 uses different APIs to talk to SharePoint, so I'm not sure if this is a limitation in the API when used from SPFx or if it is something that can be fixed in PnPjs?

### Steps to Reproduce
sp is initialized for SPFx (tested with components based on 1.15.2 and 1.16.1):
`sp = spfi().using(SPFx(context));`
The attempt to add the a term looks like this:
`termData = await sp.termStore.sets.getById(termSetId).children.add({labels:[{isDefault: true, languageTag: context.pageContext.web.languageName, name: termLabel}]});`

**Comment by patrick-rodgers** [comment]
Hi @ekdegerman - having a look at this and am able to duplicate it. I also validated that my SP application has the Taxonomy permissions correctly applied for delegated mode. Given this I don't believe at least initially this is something we can fix in the library - but let us do some research to understand what might be happening behind the scenes. According to the docs, things should work.

**Comment by patrick-rodgers** [comment]
Welp, I've got some good news. It turns out we can fix it. Currently as the library is published we rely on cookie authentication within SPFx. That has historically worked fine. Apparently SOME apis now do not take cookie auth into account, which is super weird to me since I can do a `GET` operation for a TermSet but not a `POST`.

The good news is that by adding the default SPFx token things work as expected and your example call above works now. This update will be in our release Friday (3.12).

One thing that concerns me is the case where I the user may have rights to do a thing, and previously that thing worked because cookie auth. I don't know if there is a case where the SPFx application may not have a certain right and if the token is considered before the cookie perhaps something would fail. Edge case for sure, but if we start to get a lot of reports that this is failing we'll have to back out this change.

To get you unblocked immediately you can add this to where you configure things. This won't be necessary after we do the release Friday.

```TS
function SPFxToken(context: ISPFXContext): TimelinePipe<Queryable> {

    return (instance: Queryable) => {

        instance.on.auth.replace(async function (url: URL, init: RequestInit) {

            const provider = await context.aadTokenProviderFactory.getTokenProvider();
            const token = await provider.getToken(`${url.protocol}//${url.hostname}`);

            // eslint-disable-next-line @typescript-eslint/dot-notation
            init.headers["Authorization"] = `Bearer ${token}`;

            return [url, init];
        });

        return instance;
    };
}

sp = spfi().using(SPFx(context), SPFxToken(context));
```

**Comment by ekdegerman** [comment]
Thanks Patrick! I'll can wait for the release and test again once it is out. Seems I am missing some of the dependencies to just copy the code as is. Just to clarify, what are there requirements for webApiPermissionRequests in package-solution.json with this new API version after 3.12 is released? I noticed that our old app that was using v1 didn't have anything configured but it was still able to write to the term store through the APIs v1 was using. I tried adding both the graph and SharePoint versions of TermStore.ReadWrite.All before reporting this but before your change neither helped...

**Comment by patrick-rodgers** [comment]
The permissions haven't changed, and what you set is correct. Issue is we were not including the Bearer token on SPFx requests and this API requires it apparently. By including the token what you thought should work should now work with no other changes to your code. That's the goal anyway.

**Comment by patrick-rodgers** [comment]
You can still make your requests work by adding manually the behavior as needed:

```TS
import { SPFxToken, SPFx } from "@pnp/sp";

sp = spfi().using(SPFx(context), SPFxToken(context));
```

We'll figure out something more long-term for the next release.

**Comment by patrick-rodgers** [comment]
Going to close this. A workaround is provided, and we can't require tokens for the sp library as that is a breaking change. In v4 our plan is to move the taxonomy support to the graph library, which always requires tokens so this challenge will go away. Thanks!
