### ISSUE TITLE
[Question] Is there a way to get property bag values without hitting the throttle limit?

### ISSUE THREAD

**Issue by kbeeveer46** [pnp/pnpjs#2554]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.11.0]

Please specify what version(s) of SharePoint you are targeting: [1.16.1]

### Expected / Desired Behavior / Question

We have a web part that lists all the sites on a hub (200+ sites). Each site has some meta data we've store on them as a property bag value. I'm using the following code while looping through the sites to get the value for each site but after a few refreshes of the page I get throttled by SharePoint and the entire site the web part is on is inaccessible for about 5 minutes. I get redirected to https://tenant.sharepoint.com/_layouts/15/Throttle.htm

`const props = await spfi(siteUrl).using(SPFx(this._context)).web.allProperties.select("PropertyBagKey")();`

The web part is used by hundreds of people so I don't think caching will help since it will hit the limit as soon as a few people view the page. Does PnP have a way to get data for **many** sites in 1 call? I believe PnP batching only works for one site.

Is there a better way to set/get meta data on a site?

**Comment by juliemturner** [comment]
Yeah, this isn't a PnP issue, and I would tell you architecturally what you're trying to do in client-side code isn't advised. If you wanted to have a list of maybe 10-20 sites and then hitting the property bag for each might work out ok, but getting over 200 sites isn't going to end well, the APIs were just not designed to be used that way.

I would suggest you rethink the architecture of how you're storing the metadata for sites so you can reimagine this implementation.

**Comment by kbeeveer46** [comment]
@juliemturner Thanks. I wasn't even aware throttling existed until now and we're 1.5 years into development so changing the architecture isn't a small task. I'll go ahead and close the ticket.

**Comment by juliemturner** [comment]
Even moving the data to a sharepoint list would be better than what you're doing, so honestly I don't think it's as big a deal as you might think... use your existing code to write everything to a sharepoint list (site name, site url, and metadata) and then change your code to read from the list...

**Comment by kbeeveer46** [comment]
Yeah, I've thought about that or storing the values in a database. Just seems odd Microsoft would let you create hundreds or thousands of sites and then throttle you if you try to access them via APIs. Especially when it's not obvious which calls count towards throttling (or maybe I haven't looked hard enough). Seems like this would be a prime opportunity to add an extra paid feature if for tenants who want to use more resources like they do for other clouds services.

We're using SharePoint online as a client portal and every client has a communication. Each site might have various divisions of our company on them (which we store as a property bag value). We're building an "admin" tool so someone can manage all the sites and easily change pages, navigation items, permissions, O365 groups and their external user members etc. PnPJS and PnPPowershell has really made things easy in that regard so thank you for that.

**Comment by juliemturner** [comment]
You could keep it the way it is and just modify the UX so that you select a site and then load the information about that one site vs loading them all at once. I'm guessing you probably want to search/filter on that data... again moving as you said to a database or even a SharePoint list would make this significantly better/easier.
