### ISSUE TITLE
Unable to catch 404 HttpRequestError when a user doesn't have a photo

### ISSUE THREAD

**Issue by bivory** [pnp/pnpjs#2556]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.11.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question

I'm attempting to get the photo for a user using the Graph API but some users don't have photos set. I'd like to be able to catch the 404 HttpRequestError in those cases to handle them.

### Observed Behavior

I'm seeing that one exception is caught but there seems to be another uncatchable exception.

### Steps to Reproduce

> try {
>   const graph: GraphFI = graphfi().using(GraphDefault({...}));
>   const photoInfo = await graph.users.getById('ID').photo();
>   console.info('Photo');
> } catch (e) {
>   console.error('No photo - try/catch');
> }
> 
> process.on('unhandledRejection', function (e) {
>     log.error('Unhandled rejection');
>     process.exit(1);
> });

**Comment by patrick-rodgers** [comment]
If you have a chance can you try a nightly build, I believe this was brought up and addressed in #2540.

Nightly build info here: https://pnp.github.io/pnpjs/concepts/nightly-builds/

**Comment by bivory** [comment]
Sorry I missed that issue before opening this one! I tried the nightly builds with the fix for #2540 and that solved this issue.

Thanks for the quick response!
