### ISSUE TITLE
`IWeb.getParentWeb` throws 404 when coming from subweb of root site collection

### ISSUE THREAD

**Issue by viceice** [pnp/pnpjs#2558]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.11.0]

Please specify what version(s) of SharePoint you are targeting: [2019]

### Expected / Desired Behavior / Question
Trying to get the parent web of a subweb insite root sitecollection should work and not throw a 404.

### Observed Behavior

Having a site collection at `https://some.domain.com` and a sub site at `https://some.domain.com/sub`.
If I've a `IWeb` from the sub site and call `getParentWeb`, the web url is wrongly computed at 
https://github.com/pnp/pnpjs/blob/e2f1645915ea32fa4461f223260ff661c05fd679/packages/sp/webs/types.ts#L141-L147

Because `ParentWeb.ServerRelativeUrl` is equal to `/` for the root web inside the root site collection, the trimmed Url will be `https:/` instead of `https://some.domain.com/`.

### Steps to Reproduce

```ts
const sp = spfi().using(SPBrowser({baseUrl: 'https://some.domain.com'}));
const sub = Web([sp.web, '/sub');

const parent = await sub.getParentWeb();

// this throws
await parent();
```

**Comment by patrick-rodgers** [comment]
Ah yes, indeed a bug. Good catch. We were able to get this resolved pretty quickly, please try tomorrow's nightly build to see if it is working for you. Thanks!
