### ISSUE TITLE
addUsingPath with a path containing a "&" character causes errors

### ISSUE THREAD

**Issue by svenkonings** [pnp/pnpjs#2560]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.11.0]

Please specify what version(s) of SharePoint you are targeting: [Online (SPFx 1.16.1)]

### Expected / Desired Behavior / Question
Within SharePoint you can create folders containing "&" characters. However, when creating a folder with `addUsingPath` and that folder contains a "&" character, it is rejected with a message saying the folder contains invalid characters. I expected that it would be possible to create these kinds of folders (and files).

### Observed Behavior
When you create a folder called `Test & test` in the shared documents folder using the command bar, the following API-call is made:
```
/_api/web/folders/AddUsingPath(DecodedUrl=@a1,overwrite=@a2)?@a1='/sites/test/Shared Documents/Test & test'&@a2=false
```
This results in the folder being created

When you try to create the same folder using PnP JS the following API-call is made:
```
/_api/web/folders/addUsingPath(DecodedUrl='%2Fsites%2Ftest%2FShared%20Documents%2FTest%20%26%20Test%2F',overwrite=false)
```
This results in tan error 500 response saying the folder contains invalid characters

### Steps to Reproduce
1. Call `addUsingPath` with a path containing a `&`

**Comment by patrick-rodgers** [comment]
I just tested this and it worked without issue:

```TS
import "@pnp/sp/webs";
import "@pnp/sp/folders";
import "@pnp/sp/lists";

const w = await sp.web.folders.addUsingPath("/sites/dev/My Title/Test & Value");
```

Is there anything else you can share that might help us understand what is failing?

**Comment by svenkonings** [comment]
Hi Patrick,

You're right, for some reason my tests with the & character had a trailing slash where the other tests didn't. I can confirm this works without the trailing slash so I'm closing the issue. Sorry for the mistake and thanks for your help!
