### ISSUE TITLE
401 Unauthorized when performing write operations

### ISSUE THREAD

**Issue by Sarctiann** [pnp/pnpjs#2563]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Using @pnp/sp@3.11.0 @pnp/msaljsclient@3.11.0 msal@1.4.17

I am using these packages in a "build react app" project with react@18.2.0. I am NOT using SPFx. or any extra configuration.

### Expected / Desired Behavior / Question

I want to be able to perform Write operations with my `sp` instance.

### Observed Behavior

When I try to update an item, I get an 401 unauthorized error on `.../_api/contextInfo POST`
 
### Steps to Reproduce

* My SP instance: 
  ```js
  import { MSAL } from "@pnp/msaljsclient";
  import { SPBrowser, spfi } from "@pnp/sp/presets/all";
  import { AuthenticationParameters, Configuration } from "msal";
  import "@pnp/sp/presets/all";
  import "@pnp/core";
  import * as env from ".";
  
  const configuration: Configuration = {
    auth: {
      authority: `https://login.microsoftonline.com/myTenant`,
      clientId: myClientId,
    },
    cache: {
      cacheLocation: "localStorage",
    },
  };
  
  const authParams: AuthenticationParameters = {
    scopes: ["https://myTenant.sharepoint.com/.default"],
    redirectUri: myDesiredRedirectRoute,
  };
  
  // my sp instance
  export const sp = spfi(mySharePointURL).using(SPBrowser(), MSAL(configuration, authParams));
  ```
  
* How I get an user item (ex.)
  ```js
  // This works
  const userResult = await sp.web.lists
    .getByTitle("Users")
    .items.filter(`Email eq '${someEmail}'`)();
  // do something with userResult obj
  ```

* How I try to do an update:
  ```js
  // This doesn't works
  const result = await sp.web.lists
    .getByTitle("Users")
    .items.getById(someUserId)
    .update(modifiedUserObj);
  // do something with result
  ```
 I also tried to get the list or item first and then "wait" for the "update" method as it is in the [documentation](https://pnp.github.io/pnpjs/sp/items/#update-items) . But it didn't work either.

**Comment by patrick-rodgers** [comment]
This I believe is fixed in [this PR](https://github.com/pnp/pnpjs/pull/2549). You could try a nightly build but we are doing a release today (Friday, Feb 10) so after that is live version 3.12 should contain the fix for this.
