### ISSUE TITLE
How to programmatically set site logo thumbnail?

### ISSUE THREAD

**Issue by heesungjang** [pnp/pnpjs#2565]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.3.9     ]

Please specify what version(s) of SharePoint you are targeting: [  SharePoint Online ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

###  Question

![Screenshot 2023-02-11 161643](https://user-images.githubusercontent.com/68782077/218243746-d315ef62-2d18-40fd-ad1a-4075921233d9.png)

I am able to update the site logo with `sp.web.update() ` and pass `{SiteLogUrl:"/path/to/assets"}`.

However, It seems that **IWebUpdateProps** do not expose property for site logo thumbnail. Any suggestions that I could take to change the thumbnail logo of the site?

Any help would be very appreciated!! 

Thank you for your feedback!

**Comment by juliemturner** [comment]
Actually, you have it backwards, although I can completely understand why... the web property update you reference updates the Site logo thumbnail. I've added a new method to sites that updates the Site Logo. The confusing part is that when you update the web property it sets the site logo as well... If you separately set the site logo using this new method that affects only the site logo not the site logo thumbnail.  Also, the thumbnail should not have a transparent background while the site logo can/should (depending on your goal).

![image](https://user-images.githubusercontent.com/7570936/228063996-378c45e3-3dbb-4753-8d87-f1f6c01b37bf.png)
