### ISSUE TITLE
Form Customizer with hook - Error => Cannot read properties of undefined (reading 'pageContext')

### ISSUE THREAD

**Issue by MarkusLanger** [pnp/pnpjs#2566]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.12.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
I followed the project with PnPjs and hooks => https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-pnp-js-hooks/src/webparts/pnPjsExample

In the onInit function of the form customizer class the PnPjs works without any problem:
Code => https://github.com/MarkusLanger/pnpjs-error-pagecontext/blob/main/src/extensions/company/CompanyFormCustomizer.ts#L17
Result in console
![image](https://user-images.githubusercontent.com/12131918/218452930-c95660e0-4f83-4296-9c1f-0b66c1476ab4.png)

In the hook there is the same PnPjs call:
Code => https://github.com/MarkusLanger/pnpjs-error-pagecontext/blob/main/src/extensions/hooks/useFetchCompany.ts#L33

But I get an error insted of the listitem:
![image](https://user-images.githubusercontent.com/12131918/218453211-3a86f42b-f0a7-4f81-86b1-40d1108643fe.png)

### Steps to Reproduce
- clone repository https://github.com/MarkusLanger/pnpjs-error-pagecontext
- build and deploy in SharePoint
- connect list with form customizer
- see browser console for the error

**Comment by juliemturner** [comment]
@bcameron1231 ... do you have time to assist?

**Comment by MarkusLanger** [comment]
I fixed it in my repo. The context could also be "undefined".
https://github.com/MarkusLanger/pnpjs-error-pagecontext/commit/c15718a5ed31786cf4649b50339636b3e61d2ff9

**Comment by bcameron1231** [comment]
It looks like our sample guidance in the Samples repo aren't checking the context correctly. I have fixed that and made a PR and hopefully this issue doesn't happen in the future :) Thank you Markus
