### ISSUE TITLE
SharePoint APIs stability

### ISSUE THREAD

**Issue by ahmed-asiri** [pnp/pnpjs#2574]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

Hi guys, 
currently we are consuming the SharePoint list items using the SharePoint APIs:
`GET https://{org}.sharepoint.com/_api/web/lists/GetByTitle('List Title')`

And we have heard that the SharePoint APIs are deprecated, and we should use MS Graph APIs to retrieve any thing from SharePoint.

Our question, is the SharePoint APIs gonna be dropped(removed or turned-of)? Or it's only deprecated by stopping the support on the APIs?

Thank you for your feedback!

**Comment by juliemturner** [comment]
No, the SharePoint APIs are not deprecated, and support has not stopped for them. That said, Microsoft would love for you to use the Microsoft Graph APIs in lieu of the SharePoint APIs but in my personal opinion that doesn't make a ton of sense when building for the SharePoint Framework... if you're building outside of that then yes, it's good to try and use the Microsoft Graph APIs as much as you can but also be aware there isn't full fidelity, you'll have to fall back to SharePoint APIs (and sometimes even old SOAP calls) to do everything that can be done programmatically in SharePoint.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
