### ISSUE TITLE
getFolderByServerRelativeUrl(DestinationUrl).getItem()) giving old value

### ISSUE THREAD

**Issue by JarialAnkur** [pnp/pnpjs#2576]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category

- [ ] Bug

### Version 

Please specify what version of the library you are using: [  3.8.0      ]

Please specify what version(s) of SharePoint you are targeting: [  1.15.0       ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I am moving files between two libraries frequently. For Example, if File A is in Library A, 
I move it to Library B and it will retain the name and description of the file. 
Now, without waiting If I move the file back using the "moveTo" API, it will get moved. Now, If I get the properties of the file it should give me the latest information on the file. 

### Observed Behavior
I am moving files between two libraries frequently. For Example, if File A is in Library A, I move it to Library B and it will retain the name and description of the file. Now, without waiting If I move the file back using the "moveTo" API, it will get moved, but I Will not get the right Item ID for the file. Instead, I get the old Item ID. 
If this is a SharePoint networking cache issue, is there any workaround?

Thank you for your feedback!

**Comment by juliemturner** [comment]
Did you inspect the network traffic to see what's coming back from the API? Are you using PnPjs caching? If what's coming back from the API is the old value there isn't really much that can be done from the perspective of this library.

**Comment by JarialAnkur** [comment]
await web.getFolderByServerRelativeUrl(DestinationUrl).getItem()), This is the exact API that we are using. And this API gets the properties related to the file by using the relative URL, and in the network call this API is getting me the old or cached properties of the file, because of which I am getting the wrong ID of the file in Document Library. So, when I try to update the properties against this file. It says "404" item not found. 
This might be an issue of network caching done by SharePoint on the server side. But is there any other way we can get the non-cached properties against the file?

**Comment by JarialAnkur** [comment]
For reference , this  is another issue that was opened which had the same problem, but no resolution was given at that time. 
[https://github.com/pnp/pnpjs/issues/160](url)

**Comment by JarialAnkur** [comment]
I tried and dug through the documentation of pnp and found the attribute "configure" 
So, this is how I used it.
 `const headers = {
    "Cache-Control": "no-cache"
};
 return await web.getFolderByServerRelativeUrl(DestinationUrl).listItemAllFields.configure({
                        headers
                      }).get()
`
and this solved my problem. If anyone is having this problem, this might be helpful.

**Comment by patrick-rodgers** [comment]
@JarialAnkur - a bit confused, the configure method isn't present in v3? As well we already set the `no-cache` value [as part of the defaults](https://github.com/pnp/pnpjs/blob/version-3/packages/sp/behaviors/defaults.ts#L11).

The other issue, #160, didn't have a resolution because it is a server side thing. The service does some caching, so while the data is always updated correctly you may see old data if you immediately make a request for the same item by path. As mentioned in that issue if you wait a bit before reaccessing the file you are moving back and forth it should be fine.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
