### ISSUE TITLE
pnp/sp-admin tenant method getHomeSitesDetails call shows "experimental...not supported" error.

### ISSUE THREAD

**Issue by heesungjang** [pnp/pnpjs#2578]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Questions

Hi, first of all, thanks for the great package!!

invoking await `_sp.admin.tenant.getHomeSitesDetails()` returns error message that says

"The requested operation is part of an experimental feature that is not supported in the current environment."

is this feature soon to be available? or this is not something that is on priority list?

**Comment by juliemturner** [comment]
I'm fairly sure that isn't our message that's the SharePoint REST API message, you can verify by looking at the network console.  I honestly don't have enough visibility into Microsoft to know exactly if/when that feature will be available.

**Comment by heesungjang** [comment]
> I'm fairly sure that isn't our message that's the SharePoint REST API message, you can verify by looking at the network console. I honestly don't have enough visibility into Microsoft to know exactly if/when that feature will be available.

Thank you @juliemturner.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
