### ISSUE TITLE
Addchunked followed by .update or .validateUpdateListItem error

### ISSUE THREAD

**Issue by omarelanis** [pnp/pnpjs#2580]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [V3]

Please specify what version(s) of SharePoint you are targeting: [1.16.1]

### Expected / Desired Behavior / Question
After creating a file using the .addchunked method as per the documentation here https://pnp.github.io/pnpjs/sp/files/#setting-associated-item-values I would expect to then be able to update the file metadata using the .update or .validateUpdateListItem methods of the associated list item of the file

### Observed Behavior
After the file is created the list item is not updated, for the .update method it returns a 403 error and for the validateUpdateListItem it returns a 404 error.
In both cases instead of the list (document library in this case) being targeted in the http request it is actually just targeting the top level site, for example: 

https://mytenant.sharepoint.com/sites/GlobalMobility/validateupdatelistitem

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/35841910/220466983-d5a793ec-7d9c-40df-bcec-970bc884490d.png">

### Steps to Reproduce

Create a file using the below code and then pass a value to update the list item

```
return await _sp.web.getFolderByServerRelativePath(FolderRelativePath)
    .files.addChunked(file.name, fileContent, data => {}, true)
     .then( async fileResult => {
      const item = await fileResult.file.getItem();
      await item.validateUpdateListItem([
            {
              FieldName:"Title",FieldValue: "Test"
            }
          ]);
     })
     .catch( err => {throw Error(err)})
```

Same applies if trying using:

```
return await _sp.web.getFolderByServerRelativePath(FolderRelativePath)
    .files.addChunked(file.name, fileContent, data => {}, true)
     .then( async fileResult => {
      const item = await fileResult.file.getItem();
      await item.update(
            {
              Title: "Test"
            }
          );
     })
     .catch( err => {throw Error(err)})
```

When looking at the debugger the constant item does contain the correct item metadata and appears fine.

So for some reason instead of the HTTP rest call being made to the actual list URL it is calling the server relative URL without adding the list details to the query

**Comment by omarelanis** [comment]
Appears the same error happens when calling a file directly and then trying to update the file item:

const item = await _sp.web.getFileByServerRelativePath(`${FolderRelativePath}/${fileResult.data.Name}`).getItem();
item.validateUpdateListItem( metaData );

**Comment by patrick-rodgers** [comment]
Will have a look. How are you configuring the _sp object?

**Comment by patrick-rodgers** [comment]
I am not able to duplicate this as described. Can you show how you are configuring your _sp object? That might help.

**Comment by omarelanis** [comment]
> 

Thanks for looking into the issue, I'm defining it like so:

`let _sp: SPFI = null;
export const NoOdata = InjectHeaders({ "Accept": "application/json;odata=nometadata" });

export const getSP_Webpart = (context?: WebPartContext): SPFI => {
  if (_sp === null && context !== null) {
    //You must add the @pnp/logging package to include the PnPLogging behavior it is no longer a peer dependency
    // The LogLevel set's at what level a message will be written to the console
    _sp = spfi().using(SPFx(context), NoOdata, PnPLogging(LogLevel.Warning));
  }
  return _sp;
};
`

As a workaround I've just changed the code to directly update the Item itself through .web.lists and that works:

`return await _sp.web.getFolderByServerRelativePath(FolderRelativePath)
    //eslint-disable-next-line @typescript-eslint/no-empty-function
    .files.addChunked(file.name, file.content as Blob, data => {}, true)
     .then( async fileResult => {
      const item: {Id: number} = await fileResult.file.getItem();
      await _sp.web.lists.getById(listId).items.getById(item.Id).validateUpdateListItem( metaData );
      return fileResult;
     })
     .catch( err => {throw Error(err)})`

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
