### ISSUE TITLE
Files/Folders not returning a value for Editor when using expand

### ISSUE THREAD

**Issue by kbeeveer46** [pnp/pnpjs#2583]
### Category
- [ ] Enhancement
- [X] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.12.1]

Please specify what version(s) of SharePoint you are targeting: [1.16.1]

### Expected / Desired Behavior / Question

I'm not sure if this is a question or bug. I'm using the following code to get all the files and folders in a library.

```
const filesAndFolders: IFilesAndFolders = await sp.web.getFolderByServerRelativePath(path)
    .expand("Folders, Files, Folders/listItemAllFields, Files/listItemAllFields, Folders/Author, Files/Author, Folders/Editor, Files/Editor")
    .select("Folders, Files")();
```

1. Is Files supposed to be returning an Editor property like it does Author? You can see there's an editorId value in the screen shot below.
2. Is there a reason Folders doesn't return Author _or_ Editor? Is it supposed to?

The reason I want to get the Author and Editor on both Folders and Files is because it contains the users email. I recently ran into an issue when a user was removed from a site so their ID in the AuthorId/EditorId field is invalid and throws an error when using sp.web.siteUsers.getById(). SharePoint stores their email in the Author/Editor properties even after they are removed from the site. I put a screen shot at the bottom of the Author/Editor properties I'm trying to get.

**Files:**
![Results](https://user-images.githubusercontent.com/12972554/221081277-641cc589-23c7-4ebf-9ebc-18f4218c12f6.png)

**Folders:**
![Results 2](https://user-images.githubusercontent.com/12972554/221082734-8878629a-4945-438b-bcce-27524e5debf6.png)

**I'm trying to get this data that SharePoint returns in /_api/web/GetListUsingPath(DecodedUrl=@a1)/RenderListDataAsStream**
![SharePoint Result](https://user-images.githubusercontent.com/12972554/221084850-de82b0d2-5d4c-4497-983b-41117f637381.png)

**Comment by juliemturner** [comment]
You are correct in that Editor should expend. If it's not working on that specific method that could be the case. Unfortunately, that would be an issue with the SharePoint API directly not the library as we just pass through the results. You can verify this by looking at the network console at the call itself vs what is returned from the object.

>SharePoint stores their email in the Author/Editor properties even after they are removed from the site. I put a screen shot at the bottom of the Author/Editor properties I'm trying to get.

This is probably true, up to a point, I suspect if anything on the item is updated/modified that might get cleared out, although it may not, so just be careful making that assumption. 

If you can't get it to work that way I suspect you may have to get the folder's item, and then make the additional call to expand editor.

**Comment by kbeeveer46** [comment]
@juliemturner Is this the correct syntax for getting the "item" for a file?

`const item = await (await sp.web.getFileByServerRelativePath(file.ServerRelativeUrl).getItem()).expand("File/Author, File/Editor").select("File/Author, File/Editor")();`

When I use that code it returns the Author but no Editor like before. If that is the correct code then it doesn't look like Editor gets returned using the method in my original post or the get item method.

![Item](https://user-images.githubusercontent.com/12972554/221437108-1f8be9fb-373c-4afd-bf75-0876a4fbbcdb.png)

**Comment by bcameron1231** [comment]
Hi! You're close. You're still selecting the File in your expand. I think what you're after is to get the Item and the Author/Editor information. Editor is not available on the File via REST API through SharePoint, it's from the Item. 

Here is an update your call pulling in the Email property of the Editor and Author on the List Item of the file.

`await(await sp.web.getFileByServerRelativePath("/sites/mySite/Library/MyFile.docx").getItem()).expand("Author,Editor").select("Author/EMail, Editor/EMail")()`

**Comment by kbeeveer46** [comment]
> Hi! You're close. You're still selecting the File in your expand. I think what you're after is to get the Item and the Author/Editor information. Editor is not available on the File via REST API through SharePoint, it's from the Item.
> 
> Here is an update your call pulling in the Email property of the Editor and Author on the List Item of the file.
> 
> `await(await sp.web.getFileByServerRelativePath("/sites/mySite/Library/MyFile.docx").getItem()).expand("Author,Editor").select("Author/EMail, Editor/EMail")()`

Thanks, it worked!
