### ISSUE TITLE
WebPack 5.0.0  compiling issue with Pnp JS

### ISSUE THREAD

**Issue by Phentrin** [pnp/pnpjs#2585]
I implemented a SharePoint 2019 SPFx webpart using the following [Blog post](https://spblog.net/post/2019/08/08/build-sharepoint-framework-solutions-for-on-premises-sharepoint-with-any-version-of-react-typescript-or-office-ui-fabric-react)

With this approach I can use Fluent UI React/Spfx fx-controls-react components 
[DragDropFiles](https://pnp.github.io/sp-dev-fx-controls-react/controls/DragDropFiles)

Everything works fine. But when I try to import the Pnp/js module and try to compile the project, I receive the following error at "WebPack" step during gulp serve

**Error - [webpack] 'dist': ../external/dist/formulaire-examen-Renforce-web-part.js Module parse failed: E:\PROJETS\Temp\spfx\node_modules\source-map-loader\index.js!E:\PROJETS\Temp\external\dist\formulaire-examen-Renforce-web-part.js Unexpected token (37245:8) 
You may need an appropriate loader to handle this file type. | const { replace } = { | replace: true, | ...props, | }; | return (instance) => { @ ./lib/webparts/formulaireExamenRenforce/FormulaireExamenRenforceWebPart.js 2:17-89**

Any idea how to resolve this ?

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### PNP JS Version
3.3.2

Please specify what version of the library you are using: [    ]
here is my Package.json file
{
  "name": "spfx-external",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "watch-webpack": "webpack --config webpack/webpack.dev.js --watch",
    "lint": "eslint src/",
    "watch-gulp": "gulp watch",
    "watch": "concurrently \"npm:watch-*\"",
    "dev": "webpack --config webpack/webpack.dev.js",
    "build": "webpack --config webpack/webpack.prod.js",
    "postinstall": "npx rimraf node_modules/@microsoft/**/node_modules/@types/react/ && npx rimraf node_modules/@microsoft/**/node_modules/@types/react-dom/"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@fluentui/react": "^8.104.5",
    "@microsoft/generator-sharepoint": "^1.10.0",
    "@microsoft/sp-core-library": "1.4.1",
    "@microsoft/sp-lodash-subset": "1.4.1",
    "@microsoft/sp-office-ui-fabric-core": "^1.8.2",
    "@microsoft/sp-webpart-base": "^1.16.1",
    "@pnp/spfx-controls-react": "^3.8.0",
    "@pnp/js": "^3.3.2",
    "@types/jquery": "^2.0.47",
    "@types/react": "^16.9.34",
    "@types/react-dom": "^16.9.6",
    "@uifabric/styling": "^7.11.1",
    "@uifabric/utilities": "^7.15.4",
    "filepond": "^4.30.4",
    "filepond-plugin-image-exif-orientation": "^1.0.11",
    "filepond-plugin-image-preview": "^4.6.11",
    "gulp-cli": "^2.3.0",
    "jquery": "^3.6.3",
    "libraries": "file:../libraries",
    "office-ui-fabric-react": "^7.105.7",
    "react": "^16.13.1",
    "react-datepicker": "^4.8.0",
    "react-dom": "^16.13.1",
    "react-dropzone-component": "^3.2.0",
    "react-filepond": "^7.1.2",
    "react-router-dom": "^6.8.1",
    "react-select": "^5.7.0"
  },
  "devDependencies": {
    "@microsoft/loader-cased-file": "^1.10.0",
    "@microsoft/loader-load-themed-styles": "^1.7.160",
    "@rushstack/set-webpack-public-path-plugin": "^2.4.7",
    "@types/es6-promise": "^3.3.0",
    "@types/webpack-env": "^1.15.1",
    "@typescript-eslint/eslint-plugin": "4.31.2",
    "@typescript-eslint/parser": "4.31.2",
    "concurrently": "^5.1.0",
   "css-loader": "^3.5.2",
    "css-modules-typescript-loader": "^4.0.0",
    "eslint": "7.32.0",
    "eslint-plugin-react": "7.26.0",
    "eslint-plugin-react-hooks": "4.2.0",
    "eslint-webpack-plugin": "^3.0.1",
    "fork-ts-checker-webpack-plugin": "^4.1.3",
    "gulp": "^4.0.2",
    "node-sass": "^4.12.0",
    "npm-force-resolutions": "0.0.10",
    "rimraf": "^3.0.0",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.1.3",
    "ts-loader": "^6.2.2",
    "typescript": "^3.6.4",
    "webpack": "^5.0.0",
    "webpack-cli": "^3.3.11",
    "webpack-merge": "^4.2.2",
    "webpack-visualizer-plugin": "^0.1.11"
  }
}

Please specify what version(s) of SharePoint you are targeting: [   1.4.1     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Import the pnp/js node module and use it  on the project with compiling error

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

**Comment by patrick-rodgers** [comment]
[v3 is not supported](https://pnp.github.io/pnpjs/getting-started/#spfx-version-1110-earlier) for older versions of SPFx. In order to use newer features in TS we cannot maintain back-compat through the entire history.
