### ISSUE TITLE
Attempted to perform an unauthorized operation while copyByPath using @pnp/sp

### ISSUE THREAD

**Issue by deep-ponkiya-web** [pnp/pnpjs#2586]
I have created functionality for folder creation under the SharePoint document library nested folder and copied files from another folder to a recently created folder.

I have used the "@pnp/sp":"2.11.0" library for performing the folder creation and copy folder operations.

It is working as expected for one user but it throws an error for the second user. I have added both users to the Site Owners group.

Below is the error screenshot while the second user performing the action.

![rAVZ8](https://user-images.githubusercontent.com/64422241/222347561-d3150d6c-dafe-4b4f-b1ca-d7dbc76cdefa.png)

Below is my code snippet for the same,

```
import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/files";
import "@pnp/sp/folders";

export const copyFilesInDocLibFolder = async (
    const copyFiles = await sp.web.getFolderByServerRelativePath(sourcePathUrl).copyByPath(destinationPathUrl, false);

    return copyFiles;
}
```

Can anyone help me with the same?

Thanks

**Comment by deep-ponkiya-web** [comment]
@bcameron1231 @juliemturner : Can you please look into it? Hope you have a solution. Thanks

**Comment by deep-ponkiya-web** [comment]
@juliemturner : Kindly note that Both users are in the Owner group. So, both users have the same permission.

**Comment by deep-ponkiya-web** [comment]
@juliemturner  Kindly note that Both users are in the Owner group. So, both users have the same permission.

**Comment by bcameron1231** [comment]
@deep-ponkiya-web  As Julie mentioned, this is out of our control. PnPJs is just a proxy for the SharePoint APIs. In addition to what Julie mentioned, 403's can also happen if your destination paths are inaccurate as well. Are you trying to make the same request between both accounts that are having issues?

If you inspect your network tab for the 403 call. You should be able to copy as fetch.
![image](https://user-images.githubusercontent.com/7944457/228240193-e3e5ecef-8539-40a2-ac3e-8a6e6e1985e9.png)

Then go to console and paste it in there, you'll see the full FETCH request. Notice how it's just using the SharePoint API, and if you execute this, you'll also receive the 403.
![image](https://user-images.githubusercontent.com/7944457/228240584-27ae8039-ba11-4ed6-aeea-801a6e1d0048.png)

I would suggest putting in an issue on the SP-Dev-Docs repository if you have further issues. As this is a generic SharePoint REST API issue, and not something specific to the PnPjs Library.
https://github.com/SharePoint/sp-dev-docs

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
