### ISSUE TITLE
Uploading file to sharepoint content not work

### ISSUE THREAD

**Issue by arifpermadi999** [pnp/pnpjs#2593]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: 
"@pnp/common": "^2.15.0",
"@pnp/logging": "^3.12.1",
"@pnp/odata": "^2.15.0",
"@pnp/sp": "^3.12.1",
"pnp-auth": "^2.0.0",

Please specify what version(s) of SharePoint you are targeting: [  SharePoint in Microsoft 365   ]
please help me , i want to upload my file to sharepoint , it has upload but the content not show like what i expected : 

<img width="931" alt="image" src="https://user-images.githubusercontent.com/38675805/224661054-e887403c-f8b6-4869-99ea-c536e65d5773.png">

  public async testUpload({request,response}: HttpContextContract) {
    try {

        const file = request.file(`file`)

        //console.log(file)
        const relativeUrlFile  = await uploadFileSharepoint("TEST","test.pdf",file);
        
      return responseData(response, 200, true, 'retreived data success',relativeUrlFile)
    } catch ( e ) {
      return responseData(response, 200, false, e.message )
    }
  }
   

and here for uploadFileSharepoint function

import { sp } from '@pnp/sp-commonjs'
import { bootstrap } from 'pnp-auth';

export async function uploadFileSharepoint (folderName : string , fileName:string,file : any) : Promise<String> {
    try {

        // ====== auth ========
          // set the credentials for authentication
          const siteUrl = "my site";
          const username = "username ";
          const password = "password";
          
          const authData = {
            username: username,
            password: password
          };
        bootstrap(sp, authData,siteUrl);
        // ====== end of auth ======== 
    
        // ====== get main folder ========
        const mainFolder = await sp.web.lists.getByTitle("Invoice Document");
        // ====== end of get main folder ========
        
        // create folder
        const folderInfo = await mainFolder.rootFolder.folders.add(folderName);
        // ====== end of create folder ========
    
        // ====== upload file ========
        //const fileContent = "Hello, World!";
        const folderNameUpload = folderInfo.data.Name;
        const folderRelativeUrl = folderInfo.data.ServerRelativeUrl;
        //const fileUrl = `${folderNameUpload}/${fileName}`;
    
        if (file.size <= 10485760) {
            // small upload
            const result = await sp.web.getFolderByServerRelativeUrl(folderRelativeUrl).files.addUsingPath(fileName, file, {Overwrite:true});
            
        } else {
            // large upload
            const result = await sp.web.getFolderByServerRelativeUrl(folderRelativeUrl).files.addChunked(fileName, file, data => {
            //console.log(`progress`);
            }, true);
        }
        // ====== end of upload file ========
    
        // ====== end of get file data ========
        return folderRelativeUrl + "/" + fileName;
    
    } catch (error) {
        Logger.error(error.message);
        return "";
    }    
}          

<img width="771" alt="image" src="https://user-images.githubusercontent.com/38675805/224662165-82c6c9a5-349b-494c-9b46-72fac1cf2b12.png">
when i open it 
<img width="647" alt="image" src="https://user-images.githubusercontent.com/38675805/224662262-3e83e349-fb08-4cd5-a260-9686743bbd65.png">

please help me

**Comment by arifpermadi999** [comment]
import { sp } from '@pnp/sp-commonjs'

import { bootstrap } from 'pnp-auth';

**Comment by arifpermadi999** [comment]
file can't be open correctly , could you give a example for upload sharepoint using an auth username and password , because i didn't find an example to upload it

**Comment by patrick-rodgers** [comment]
We don't support user/password auth through the library. You'd need to check with the authors of `pnp-auth` for questions related to that.

[Adding files is supported](https://pnp.github.io/pnpjs/sp/files/#adding-files) in several ways, all of which work so far as we are aware.
