### ISSUE TITLE
How to create a service scope using a sharepoint url passed in from an spfx property pane value

### ISSUE THREAD

**Issue by JonoSuave** [pnp/pnpjs#2594]
### Category
- [x ] Question

### Version

Please specify what version of the library you are using: [  3     ]

Please specify what version(s) of SharePoint you are targeting: [      1.15.2     ]

I'm using the service template found in the PnP JS documentation:

export class SampleService {

    public static readonly serviceKey: ServiceKey<ISampleService> = ServiceKey.create<ISampleService>('SPFx:SampleService', SampleService);
    private _sp: SPFI;

    constructor(serviceScope: ServiceScope) {

        serviceScope.whenFinished(() => {

        const pageContext = serviceScope.consume(PageContext.serviceKey);

        //SharePoint
        this._sp = spfi().using(spSPFx({ pageContext }));

    }

    public getLists(): Promise<any[]> {
        return this._sp.web.lists();
    }
}

When setting up this._sp = spfi().using(spSPFx({ pageContext })) I'd like to pass in the context of another url (provided from one of the webpart's property pane fields) that's from a different site. How would I set that up?

**Comment by juliemturner** [comment]
```
this._rootSite = {URL to some other site collection};
this._sp = spfi(this._rootSite).using(spSPFx({ pageContext }))
```

**Comment by JonoSuave** [comment]
> ```
> this._rootSite = {URL to some other site collection};
> this._sp = spfi(this._rootSite).using(spSPFx({ pageContext }))
> ```

So do I call this from within the render() method of the WebPart.ts? How do I inject this to create a new serviceScope? Here's the service file I created:

import { ISharePointService } from "./ISharePointService";
import { ServiceKey, Environment, EnvironmentType, ServiceScope } from "@microsoft/sp-core-library";
import { SPFI, spfi, SPFx as spSPFx } from "@pnp/sp";
import { PageContext } from "@microsoft/sp-page-context";
import { Guid } from "@microsoft/sp-core-library";
import { List, ListItem } from "@microsoft/microsoft-graph-types";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

export class SharePointService implements ISharePointService {
	public static readonly serviceKey: ServiceKey<ISharePointService> =
		ServiceKey.create<ISharePointService>(
			"JT:JtSpTaskKickoff:SharePointService",
			SharePointService
		);
	private _sp: SPFI;
	constructor(serviceScope: ServiceScope, private webUrl?: string) {
		if (this.webUrl) {
			serviceScope.whenFinished(() => {
				const pageContext = serviceScope.consume(PageContext.serviceKey);
				//SharePoint
				this._sp = spfi(webUrl).using(spSPFx({ pageContext }));
			});
		}
	}

	public async getManifestTasks(
		listId: Guid,
		selectedColumns: string,
		siteId: Guid,
		webId: Guid
	): Promise<ListItem[]> {
		const manifestTasks = this._sp.web.lists
			.getById(`${listId}`)
			.items.expand(`fields($select=${selectedColumns})`)<ListItem[]>();

		return manifestTasks;
	}
}

Here's what I'm attempting in the initial render that creates my parent component:

public render(): void {
		
		const childService = this.context.serviceScope.startNewChild();
		const childScope = childService.createAndProvide(
			SharePointService.serviceKey,
			"url to some other site collection"
		);
		childScope.finish();
//then pass the child service as one of the props in the React.createElement(component, {props})
}

That's my attempt to initialize a service scope with a passed in url, but I'm not setting up the new scope correctly.

**Comment by juliemturner** [comment]
Maybe try reviewing this article about using service scopes and see if that helps you. It's using an older version of PnPjs but the theory is there.

https://www.vrdmn.com/2017/05/getting-current-context-sphttpclient.html

**Comment by JonoSuave** [comment]
Sorry if I missed it, but I'm not seeing in that article how to dynamically pass in a weburl when creating a new child Scope of the parent serviceScope on the page.

**Comment by JonoSuave** [comment]
I think the part I'm missing is how to call the finish() method on the new service scope:

		const childService = this.context.serviceScope.startNewChild();
		const scopedService = childService.provide(
			SharePointService.serviceKey,
			new SharePointService(childService, "url")
		);

**Comment by JonoSuave** [comment]
Figured out that I needed to call childService.finish() after the provider. I can now dynamically add the url to my service from the propertyPane -- woohoo!
