### ISSUE TITLE
Enable the "Make "New Folder" command available?" option with Sharepoint using @pnp/sp

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2596]
I need to create folder under Site Pages library under SharePoint Online site. I need to create new page under child folder in Site Pages library.

I have tried to create the folder programmatically using **@pnp/sp** library. But it thrown me Access Denied error.

New Folder option is missing while click on New. Please check below screenshot,

<img width="526" alt="z4nEI" src="https://user-images.githubusercontent.com/99523338/224896341-e26a720d-baec-48a0-a139-ee3ff07b9ecd.png">

I have check the solutions for the same and I got the solution if New folder option will enable then I can create new page.

So, I need to enable New Folder option programmatically using **@pnp/sp** library as per the below screenshot,

<img width="401" alt="Upszr" src="https://user-images.githubusercontent.com/99523338/224896465-4876cd25-0184-43bc-b835-fc9c0543cc68.png">

Can anyone help me with the same?

**Comment by patrick-rodgers** [comment]
Did you [look at the docs](https://pnp.github.io/pnpjs/sp/folders/#add)?

**Comment by patrick-rodgers** [comment]
These docs show [how to create a folder](https://pnp.github.io/pnpjs/sp/folders/#add).

**Comment by bhoomesh-spe** [comment]
@patrick-rodgers Thanks for your response. I have create a new folder same as the way as you have suggested.
