### ISSUE TITLE
Batching on list field update triggering individual requests along with batched request.

### ISSUE THREAD

**Issue by NewGHUser4321** [pnp/pnpjs#2597]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.10.0

Please specify what version(s) of SharePoint you are targeting: SharePoint Online

### Expected / Desired Behavior / Question
When using batching, individual requests should not be triggered for list field updates.

### Observed Behavior
Observed that when doing batching on list field update, along with batch request, individual requests are also getting triggered. And this is becoming a problem because, the requests are failing due to concurrent updates.

### Steps to Reproduce
Try batching on list field update. Sample code I'm trying shown below
```
const [batchedWeb, execute] = sp.web.batched();    
fieldsArray.forEach(field => batchedWeb.lists.getById(ListId).fields.getByTitle(field.InternalName).update({ Title: field.Title }));
await execute();
```

Please see the screenshot from devtools Network tab.

![image](https://user-images.githubusercontent.com/105061286/224919724-829024fb-b368-4ca7-a468-19d391b8303b.png)

Thank you.

**Comment by patrick-rodgers** [comment]
Yes, this is a biproduct of the fields API. Only a subset of properties are supported when creating a new field, we then need to update the field with the rest of the properties. We can't do all that in the single batch, or at least in the past it hasn't worked in the same batch. For field creation you might need to avoid batches. Def a place the API can improve.

**Comment by NewGHUser4321** [comment]
Thanks for the quick reply. I do not have issues when creating the fields in a batch though. Issue is only with updating. Also as you said, I too feel its better to avoid batching for fields as I have seen couple other issues as well. I'll try to do it on the server side.

**Comment by patrick-rodgers** [comment]
Ah, I read too fast. You can [see here](https://github.com/pnp/pnpjs/blob/version-3/packages/sp/fields/types.ts#L81) that to return the data folks expect we do another call. Perhaps this is a candidate for v4 to not do that.

**Comment by juliemturner** [comment]
I actually would agree that I would prefer we didn't make that extra call... 90% of the time I don't need it.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
