### ISSUE TITLE
Will SourceId be deprecated in the ISearchQuery interface?

### ISSUE THREAD

**Issue by erkanch** [pnp/pnpjs#2601]
I've seen the bulletin below from Microsoft. We use SourceId in our SP Search queries. For instance, we use the built-in "B09A7990-05EA-4AF9-81EF-EDFAB16C4E31" ID to search for user profiles, etc. Will the sp.search API fail if the result sources are retired? 

(Updated) Retirement of custom default result sources in Microsoft Search for modern search experiences
Classic SharePoint search supports the feature of result sources where you can define custom KQL filters on what items should be returned for your search result. This feature has been honored in Microsoft Search, but as the same result source is used across all verticals with SharePoint content it limits the flexibility and intention of the feature.
In November 2021 Microsoft shipped the capability for administrators to add KQL to the verticals in Microsoft Search. Vertical configuration succeeds the classic result source rewrite capability and allows for greater flexibility per vertical, and the change reflects what has been documented in Differences between the classic and modern search experiences in SharePoint.
When this will happen:
We will be rolling out this change in mid-April 2023.
How this affects your organization:
Starting mid-April 2023, customers using a custom default result source for KQL rewrite of the modern search experience should move KQL rewrites from those sources over to the vertical administration configuration.
What you can do to prepare:
If your organization is utilizing a custom default result source for KQL rewrites of the modern search experience, you should move KQL rewrites to the vertical administration configuration.
•	Manage search verticals
Note: Query rules at site or hub site scoped searches with promoted results are not affected as promoted results are returned in the modern search experience for sites regardless of the result source. See Manage query rules for more information on query rule behavior. Classic search experiences and experiences built on the SharePoint search API’s are not affected by the retirement.

**Comment by juliemturner** [comment]
This community lead library doesn't have insights into the internals for Microsoft so I would say this is probably not the place you want to ask this question; I would submit this to [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues) instead.

That said, this line:
>Classic search experiences and experiences built on the SharePoint search API’s are not affected by the retirement.

implies that if you're using the SharePoint search api then things will continue to work fine.

**Comment by erkanch** [comment]
Thanks @juliemturner. I wasn't sure to raise it here or there as it involved ISearchQuery. I wanted to make sure other PnP JS developers and users are also aware of this upcoming change. Please feel free to close this issue. Thanks!
