### ISSUE TITLE
Issue with ALM api, Property 'getAppCatalog' does not exist

### ISSUE THREAD

**Issue by PowellT** [pnp/pnpjs#2602]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  3.2.1       ]

Please specify what version(s) of SharePoint you are targeting: [      Sharepoint Online   spfx 1.16]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I am trying the ALM api examples, specifically the following:
```
import { spfi } from "@pnp/sp";
import "@pnp/sp/appcatalog";
import "@pnp/sp/webs";

const sp = spfi(...);

// you can get the tenant app catalog (or any app catalog) by using the getTenantAppCatalogWeb method
const appCatWeb = await sp.getTenantAppCatalogWeb()();
const appCatalog = await appCatWeb.getAppCatalog()();

// you can get the tenant app catalog (or any app catalog) by passing in a url
// get the tenant app catalog
const tenantCatalog = await sp.web.getAppCatalog("https://mytenant.sharepoint.com/sites/appcatalog")();

// get a different app catalog
const catalog = await sp.web.getAppCatalog("https://mytenant.sharepoint.com/sites/anothersite")();
```

I cant get past 'error TS2339: Property 'getAppCatalog' does not exisit on type 'IWeb'
Any help greatly appreciated!

I am new to 3.x I am wondering if this needs something special similar to logging ref : [sp-dev-fx-webparts](https://github.com/pnp/sp-dev-fx-webparts)/[samples](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples)/[react-pnp-js-sample](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-pnp-js-sample)/[src](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-pnp-js-sample/src)/[webparts](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-pnp-js-sample/src/webparts)/[pnPjsExample](https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-pnp-js-sample/src/webparts/pnPjsExample)/pnpjsConfig.ts

**Comment by juliemturner** [comment]
I think that's a missed update in the docs with v3, can you try changing getAppCatalog as a method to appcatalog as a property...

**Comment by juliemturner** [comment]
it should

**Comment by PowellT** [comment]
I dont see how I can get the site collection app catalog for a web in V3.

If I get a web, 
const myweb:IWeb=await Web("https://blah.com/sites/sitecollection/subsite");
const webcat:IAppCatalog=await  myweb.appcatalog
console.log(myweb.toUrl())
output: 
https://blah.com/sites/sitecollection/subsite/_api/web/tenantappcatalog/AvailableApps.

it look like it is using the tenant app catalog, I need to use the site collection app catalog.
There used to be a getSiteCollectionAppCatalog method on Web.   It is not clear how I can do the same in V3.

Any guidance appreciated.

**Comment by PowellT** [comment]
I still get the tenantapp catalog using either of those methods.

In v2 you could do this:

const catalog = await sp.web.getAppCatalog(undefined, 'sitecollection')();

I need to do the same in V3 with the now property based .appcatalog, but I am just not seeing it.

Otherwise I have to do it with rest directly or switch back to v2, neither are great options.

Thank you for the help!

**Comment by bcameron1231** [comment]
Quick update, I believe you may have found a bug for us. It does appear we're not providing the proper scope for the site collection app catalog. Will keep you posted as we investigate this further.

**Comment by PowellT** [comment]
Thank you for the update and help.
I appreciate youalls work on this project!
