### ISSUE TITLE
Add page comments with mentions

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2604]
I have tried to add comment with mentions   I am using @pnp/sp: ^3.12.1 and @pnp/logging: ^3.12.1 versions.

I have take reference for add page comment from [add-comment.](https://pnp.github.io/pnpjs/sp/comments-likes/#add-comment)

I have faced **Property 'addComment' does not exist on type 'IItem'. Did you mean 'comments'?** error while using **addComment** function. Below is my code snippet,

```
    import { IComments } from "@pnp/sp/comments";
    import { ICommentInfo } from "@pnp/sp/comments";
    
    const sp: SPFI = getSP();
    var page = await sp.web.getFileByServerRelativePath(pageServerRelativeUrl).getItem()
    const commentInfo: Partial<ICommentInfo> = {
        text: "This is the test comment with at mentions",
        mentions: [{ loginName: 'test@contoso.com', email: 'test@contoso.com', name: 'Test User' }],
    };
    const comment = await page.addComment(commentInfo);
```

As an alternative I have used loadClientsidePage function instead of getFileByServerRelativePath function. I have resolved **Property 'addComment' does not exist on type 'IItem'. Did you mean 'comments'?** error while using **addComment** function. Comment data is added successfully. But mention is not added in comment. Below is the code snippet,

```
    import { IComments } from "@pnp/sp/comments";
    import { ICommentInfo } from "@pnp/sp/comments";
    
    const sp: SPFI = getSP();
    var page = await sp.web.loadClientsidePage(pageServerRelativeUrl)
    const commentInfo: Partial<ICommentInfo> = {
        text: "This is the test comment with at mentions",
        mentions: [{ loginName: 'test@contoso.com', email: 'test@contoso.com', name: 'Test User' }],
    };
    const comment = await page.addComment(commentInfo);
```

Can anyone help me with the same?

Thanks

**Comment by juliemturner** [comment]
Looks like the sample is missing an import... 

@import "@pnp/sp/comments";

**Comment by bhoomesh-spe** [comment]
I have already added below imports but it is not working as expected.

import "@pnp/sp/clientside-pages/web";
import "@pnp/sp/comments/clientside-page";
import "@pnp/sp/comments";

**Comment by juliemturner** [comment]
Ok, now I'm confused, are you trying to add a comment to a page or a list item? They are different. Your import implies a page, if that is the case then your issue is that you're calling .getItem() on the page, so the page variable isn't a page but an item...

**Comment by bhoomesh-spe** [comment]
I have created a page using the sp/pnp library.

I need to add a comment on the page using the sp/pnp library.

Please check the below screenshot for a better understanding,

![ZZZ](https://user-images.githubusercontent.com/99523338/226643999-29cb341f-2b64-47dd-b99a-7460a63387ae.png)

**Comment by bhoomesh-spe** [comment]
Hi @juliemturner

Thanks for the quick response.

I have created a page using the sp/pnp library.

I need to add a comment on the page using the sp/pnp library.

Please check the below screenshot for a better understanding,

![ZZZ](https://user-images.githubusercontent.com/99523338/226657319-1cf7f9b7-2f34-4090-86ef-e4ebe426ebf2.png)

**Comment by bcameron1231** [comment]
Hi. So in order for the actual mention to appear in the text, you also have to set the value of mention in the text body. Otherwise it won't visibly show. 

Each mention in the text is an anchor tag with the following format.

`<a data-sp-mention-user-id=\"{email}\" href=\"mailto&#58;{email}\" tabindex=\"-1\">{name}</a>
`

So if I wanted to tag myself in a comment and include my name as a mention, I'd have to add myself to the mentions object, but also include the mention anchor in the text body. See below.
```
var page = await sp.web.loadClientsidePage("/sites/contoso/sitepages/Test.aspx")
const commentInfo: Partial<ICommentInfo> = {
    text: "<a data-sp-mention-user-id=\"beau@CameronCode.onmicrosoft.com\" href=\"mailto&#58;beau@mycompany.onmicrosoft.com\" tabindex=\"-1\">Beau Cameron</a> This is the test comment with at mentions",
    mentions: [{ loginName: "i:0#.f|membership|beau@mycompany.onmicrosoft.com", email: 'beau@mycompany.onmicrosoft.com', name: 'Beau Cameron' }],
};
const comment = await page.addComment(commentInfo);
```
![image](https://user-images.githubusercontent.com/7944457/226709198-627ae783-1891-4959-b367-8af57fca29aa.png)

**Comment by bhoomesh-spe** [comment]
Hi @bcameron1231 

Thanks for the response. I have successfully added page comment with mention as you have suggested.

When I retrieve that page and comment the response of comment return like below,

```
{
    "odata.type": "Microsoft.SharePoint.Comments.comment",
    "odata.id": "https://contoso.sharepoint.com/sites/testsite/_api/web/lists('76bdcccf-3587-4600-5323-6c14fc86fca0')/GetItemById(787)/Comments(4)",
    "odata.editLink": "https://contoso.sharepoint.com/sites/testsite/_api/web/lists('76bdcccf-3587-4600-5323-6c14fc86fca0')/GetItemById(787)/Comments(4)",
    "author": {
        "directoryObjectId": null,
        "email": "testuser@contoso.com",
        "expiration": null,
        "id": 6,
        "isActive": true,
        "isExternal": false,
        "jobTitle": null,
        "loginName": "i:0#.f|membership|testuser@contoso.com",
        "name": "Test User",
        "principalType": 1,
        "userId": null,
        "userPrincipalName": null
    },
    "createdDate": "2023-03-22T04:41:33.47Z",
    "id": "4",
    "isLikedByUser": false,
    "isReply": false,
    "itemId": 787,
    "likeCount": 0,
    "listId": "76bdcccf-3587-4600-5323-6c14fc86fca0",
    "mentions": [], <---- Why there is no data in mentions?
    "modifiedDate": null,
    "parentId": "0",
    "replyCount": 0,
    "text": "<a data-sp-mention-user-id=\"testuser@contoso.com.com\" href=\"mailto&#58;testuser@contoso.com\" tabindex=\"-1\">Test User</a> This is the test comment with at mentions"
}
```

There is no data in mentions under comment response. This is a default behavior or am I doing something wrong?

**Comment by bcameron1231** [comment]
This is not the behavior that should happen. It should return the mentions, and it does so for me when I test it.

Please make sure the value of the **data-sp-mention-user-id** attribute is a valid user account in your tenant. If it's not, it will show it in the UI, but it won't be able to resolve it and it will have no mentions. If you look at your mention it should appear **bold** see below. Notice the two differences in the font.

![image](https://user-images.githubusercontent.com/7944457/226905314-34a0cd4f-5f57-499a-825d-1b8b6c21b0f5.png)

**Comment by bhoomesh-spe** [comment]
Hi @bcameron1231 ,

Thanks for response.

In my comment mentions appears bold and when I click on that pop-up menu will opened and show the details of that user.

When I get the comments the text of comments and mentions both appears under text key which I have share in my last reply. Hope this is default behavior of SharePoint.

` "text": "<a data-sp-mention-user-id=\"testuser@contoso.com.com\" href=\"mailto&#58;testuser@contoso.com\" tabindex=\"-1\">Test User</a> This is the test comment with at mentions"`

Thanks

**Comment by bcameron1231** [comment]
Hmm okay. Unfortunately, I can't reproduce, as it is working correctly for me.

**Comment by bhoomesh-spe** [comment]
HI @juliemturner ,

Thanks for quick response.

Can you please get the page using sp/pnp ?

Are you got mentions name under comments or not?

Thanks

**Comment by bcameron1231** [comment]
Hi. Yes I was able to get the mentions to show up. It is working for me. See below.

```
const w = await Web([sp.web, "https://cameroncode.sharepoint.com/sites/contosogroup7"]);

var page = await w.loadClientsidePage("/sites/contosogroup7/sitepages/Test.aspx");
const commentInfo: Partial<ICommentInfo> = {
    text: "<a data-sp-mention-user-id=\"beau@CameronCode.onmicrosoft.com\" href=\"mailto&#58;beau@CameronCode.onmicrosoft.com\" tabindex=\"-1\">Beau Cameron</a> Mention Me Please",
    mentions: [{ loginName: "beau@cameroncode.onmicrosoft.com", email: 'beau@cameroncode.onmicrosoft.com', name: 'Beau Cameron' }],
};
const comment = await page.addComment(commentInfo);

const comments = await page.getComments();
```
Results in

![image](https://user-images.githubusercontent.com/7944457/226925497-49b5bf35-65d9-42be-92c1-2d4d97763d67.png)

**Comment by bhoomesh-spe** [comment]
Hi @bcameron1231 

Thanks for quick reply.

I will check my code with your code.

Thanks

**Comment by bcameron1231** [comment]
Hi. Yes I will update the documentation.

Additionally, here is the code below that is working for me. I get the page, add the comment, and then retrieve the comments.

```
const w = await Web([sp.web, "https://cameroncode.sharepoint.com/sites/contosogroup7"]);

var page = await w.loadClientsidePage("/sites/contosogroup7/sitepages/Test.aspx");
const commentInfo: Partial<ICommentInfo> = {
    text: "<a data-sp-mention-user-id=\"beau@CameronCode.onmicrosoft.com\" href=\"mailto&#58;beau@CameronCode.onmicrosoft.com\" tabindex=\"-1\">Beau Cameron</a> Hello",
    mentions: [{ loginName: "beau@cameroncode.onmicrosoft.com", email: 'beau@cameroncode.onmicrosoft.com', name: 'Beau Cameron' }],
};
const comment = await page.addComment(commentInfo);
const comments = await page.getComments();
```

![image](https://user-images.githubusercontent.com/7944457/226929885-488b3514-145d-421d-89b9-c0faa4aea284.png)

**Comment by bhoomesh-spe** [comment]
HI @bcameron1231 

Thanks again.
