### ISSUE TITLE
Batching and Caching on Graph

### ISSUE THREAD

**Issue by BollietMZK** [pnp/pnpjs#2615]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.13.0]
Please specify what version(s) of SharePoint you are targeting: [1.15.2]

### Expected / Desired Behavior / Question
The desired behavior is to get a cached value for a batched request with graph package.

### Observed Behavior
The batch is correctly executed the first time to get results from Microsoft Graph.
The cache correctly works (correct results stored into Local Storage)
The execution is stopped on `await execute()` on next execution of the batch.
No error is logged into the console.

On the screenshot below, the line 167 is never reached on the next executions of the batch (first time worked correctly):
![image](https://user-images.githubusercontent.com/87386292/227906893-7e2bee16-e764-4e78-9497-9cbe8d9af3c5.png)

### Steps to Reproduce

- I copy/paste the code from Batching Graph example from docs: https://pnp.github.io/pnpjs/concepts/batching/#graph-example
- I use the `SPFx` behavior because the code is run for a SharePoint WebPart
- I add the `Caching` behavior for the batch

```
import { graphfi, SPFx } from "@pnp/graph"; // this line has been updated to add SPFX
import { Caching } from '@pnp/queryable'; // this line has been added
import "@pnp/graph/users";
import "@pnp/graph/groups";
import "@pnp/graph/batching";

const graph = graphfi().using(SPFx(this.context)); // this line has been updated to add SPFX

const [batchedGraph, execute] = graph.batched();
batchedGraph.using(Caching()); // this line has been added

let res = [];

// Pushes the results of these calls to an array
// you need to use .then syntax here as otherwise the application will stop and await the result
batchedGraph.users().then(r => res.push(r));

// you need to use .then syntax here as otherwise the application will stop and await the result
// ODATA operations such as select, filter, and expand are supported as normal
batchedGraph.groups.select("Id")().then(r => res.push(r));

// Executes the batched calls
await execute();

// Results for all batched calls are available
for(let i=0; i<res.length; i++){
    // Do something with the results
    console.log(res[i]);
}
```

**Comment by patrick-rodgers** [comment]
Hi @BollietMZK - thanks for reporting this. We'll investigate, one clarifying question - when you say "The execution is stopped on await execute() on next execution of the batch." you mean on the next page load? So first page load things work then second page load they don't - BUT you see the results in local storage?

I think we fixed a similar thing in SP batching, but must not have also updated the graph batching logic.

**Comment by patrick-rodgers** [comment]
It was the same issue, just missed update the graph library when we fixed it for SP.
