### ISSUE TITLE
Need support on retrieving subfolders from SP doc library

### ISSUE THREAD

**Issue by ncmadhan1989** [pnp/pnpjs#2616]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category

- [ ] Question

### Version :3.13

Please specify what version of the library you are using: [     3.13    ]

Please specify what version(s) of SharePoint you are targeting: [     SP Online   ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
 const spApi = spfi(this._sp);
 
        const url = `/Shared Documents`;

        const GetFolderDetails = folderFromServerRelativePath(spApi.web, url).expand('Folders,Files');
        const folderInfo = await GetFolderDetails();

this code doesn't returns the recursive folders and files ,only returning the top level folders and files(I need subfolders and corresponding files too)

**Comment by patrick-rodgers** [comment]
I believe that [the code in this sample](https://github.com/pnp/sp-dev-solutions/blob/847e54491cfb08f28f979709cd359d30c77b60bb/solutions/MultilingualPages/SPFxExt/src/extensions/multilingualExtension/services/InitService.ts#L148) does what you are needing. You'll need to play with the exact query but should get you started.
