### ISSUE TITLE
Unable to create Choice Column Using sp/pnp

### ISSUE THREAD

**Issue by deep-ponkiya-web** [pnp/pnpjs#2620]
Hello Everyone,

I have created an SPFx solution. I have used  "@pnp/sp": "^3.8.0" version.

I am unable to create a choice column using [sp/pnp.](https://pnp.github.io/pnpjs/v2/sp/fields/#add-a-choice-field)

I have faced the **The specified program requires a newer version of Windows.** error.

Below is my code snippet.

```
if (actionListColumnArray.indexOf("TypeOfIncident") == -1) {
          const typeOfIncident = ["Incident", "Vulnerability", "Event", "N/A"];

          await sp.web.lists
            .getByTitle("Actions")
            .fields.addChoice("TypeOfIncident", {
              Choices: typeOfIncident,
              EditFormat: ChoiceFieldFormatType.Dropdown,
              FillInChoice: false,
              Group: "Incident Group",
            })
            .then(() => {
              sp.web.lists
                .getByTitle("Actions")
                .defaultView.fields.add("TypeOfIncident");
            });
        }
```

**Comment by bcameron1231** [comment]
You should fix your code just to use async awaits only, but it is correct.

```
  const typeOfIncident = ["Incident", "Vulnerability", "Event", "N/A"];

  await sp.web.lists.getByTitle("Actions").fields.addChoice("TypeOfIncident", {
    Choices: typeOfIncident,
    EditFormat: ChoiceFieldFormatType.Dropdown,
    FillInChoice: false,
    Group: "Incident Group",
  });

  await sp.web.lists
  .getByTitle("Actions")
  .defaultView.fields.add("TypeOfIncident");
```

With that said, the error you are receiving is unrelated to the PnPjs Library. Sounds like a compatibility issue with the version of Visual Studio (I'm using that's what your using based on the error). As such there isn't much we can do to help you. I would suggest finding a Visual Studio repository and see if someone can help you over there.

**Comment by deep-ponkiya-web** [comment]
@bcameron1231  Thank You So much For This Solution Works For me.
