### ISSUE TITLE
Recommended way to check if guests can be invited on the current SPWeb?

### ISSUE THREAD

**Issue by plamber** [pnp/pnpjs#2621]
I am looking for a way to identify if the current user is allowed to invite a guest account to a SharePoint site or not. Do you have a recommended way to do this using the SDK?

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version
The latest version of the library in SharePoint Online.

Thank you for your feedback!

**Comment by juliemturner** [comment]
You need to send an invitation unless they already are a guest in your AAD... then you just have to add their guest account to the membership of the group the site is associated with. There is way more involved with guest access and when/where you can and can't use it so I would suggest you make sure you're familiar with all those limitations as well if you are not.

https://learn.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&tabs=http

**Comment by plamber** [comment]
Thank you, @juliemturner, for coming back.

I am trying to determine whether I can invite a guest to a SharePoint site based on the site's criteria. I'm interested in exploring the sharing capability of the site to get more information.

After some research, I discovered that the REST API provides an endpoint that can help with this. The endpoint is /_api/SP.Web.GetObjectSharingSettings?$expand=ObjectSharingInformation,SharePointSettings/PickerProperties, and it's called when the sharing experience is opened in a SharePoint site.

Based on my understanding, the "IsSharedWithGuest" property in the ObjectSharingInformation should indicate whether guests are allowed to be invited. I found this property in the screenshot below:

![image](https://user-images.githubusercontent.com/18241305/228278259-8b11ca72-8a28-4bc8-9bff-0357e24cc100.png)

I'm wondering if there's a way to perform a custom query using the SDK to call this endpoint or if there's a better approach to achieve this goal. Can you suggest any ideas or solutions?

Thank you,
Patrick

**Comment by plamber** [comment]
Thank you @juliemturner. I will give it a try.
