### ISSUE TITLE
Error 400 fetching a new file and when updating its metadata.

### ISSUE THREAD

**Issue by ishaisagi** [pnp/pnpjs#2622]
Hi all,
I have a strange one here - works in DEV but not in PROD with same code.
The code creates a file by using the 
`await sp.web.getFileByServerRelativePath(destinationUrl).moveTo(copyToURL);`
The file gets created, and no error is thrown.

but then (in prod only) I try to update the new file's metadata by doing
`sp.web.lists.getByTitle(this.props.documentLibraryName).items.getById(itemID).update(metadata);`

which errors out.

There are actually two errors (both 400) - one from the getbyid (it shows the query url and returns a 400 as if there is no data, but if I open that url I see the metadata for the file) and then another error for the update saying "InvalidClientQueryException" and "expected a primitivevalue" (does not specify on which field). 

To make sure this is not a field mis-configuration I removed all metadata except the "Title" field and it still gives me the same error. 

I think it may be related to the list entity type name being ommitted from the update - I will try to add it manually instead of relying on the pnp code to get it right.

At this point I am worried about the first error - why is it failing the getbyid even though the file is there? 

I am running on an older version of the library as I cannot currently upgrade my solution. Any insights will be most welcome.

**Comment by ishaisagi** [comment]
just to clarify - the "moveTo" isnt actually creating a file, it just renames an existing one. So long before the getitembyid happens the file is already there.

**Comment by patrick-rodgers** [comment]
What version of our library, version of SharePoint, and how are you deploying?

**Comment by ishaisagi** [comment]
ignore this - I have no idea why, but my test of only updating the "title" field was not valid. I retested and found that one of the fields was indeed misconfigured. All good now.
