### ISSUE TITLE
Unsupported security token when calling endpoints

### ISSUE THREAD

**Issue by vamsi981** [pnp/pnpjs#2623]
- [ X] Bug

### Version

`"@pnp/nodejs": "^2.14.0",
 "@pnp/sp": "^2.14.0",`

Please specify what version(s) of SharePoint you are targeting: [    spOnline    ]

1. **Index.ts** where sp setup is happening
`sp.setup({
 sp: {
      fetchClientFactory: () => {
        let spFetchClient;
        try {
          spFetchClient = new SPFetchClient(
            config.spSiteUrl,
            config.clientId,
            config.clientSecret
          );
        }
        catch (error) {
          process.exit(1);
        }
        return spFetchClient
      },
    },
  });`

2. **webpartHelper.ts** where calling to  retrive webparts

`const webPartDefs = await sp.web.getClientsideWebParts();`

when calling above getting 401 unauthorized. But it is succesfull when calling other operation 
`await sp.web.getFileByServerRelativeUrl(fileServerPath).exists();`

 Error making HttpClient request in queryable [401] Unauthorized ::> {"error_description":"Unsupported security token."}
`await sp.web.getClientsideWebParts()`

**Comment by juliemturner** [comment]
Sorry to hear you're having a problem. That said, this doesn't seem to be a problem with the library but rather a problem with your security configuration based on the scenario you're trying to execute. This library is simply a pass-through proxy to the SharePoint APIs so any security issues of the nature your describing would be an issue with the way you have things configured and how you're trying to access. With what you've shared I'm not sure how to help you.

Seperately, out of curiosity is there a reason you're still using version 2 of the library and havent made the switch to version 3?

**Comment by bcameron1231** [comment]
Possible Duplicate https://github.com/pnp/pnpjs/issues/1501

Check and see if you've got the proper client id/secret + auth combination.
