### ISSUE TITLE
set clientside page as homepage?

### ISSUE THREAD

**Issue by PowellT** [pnp/pnpjs#2625]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version v2.1 or v3
Please specify what version(s) of SharePoint you are targeting: [  SPO ]

###Question
Does pnpjs support/provide for setting the homepage/default page/Welcomepage in a site?
Specifically I am creating a modern client side page, adding webpart to it , and need to set  it as the homepage for a web.

Pretty sure the rest api can (used to be able to).   Any help greatly appreciated!

-Thanks,
Powell

**Comment by bcameron1231** [comment]
Updating the Welcome Page is done by updating the Web's Root folder.

` await sp.web.rootFolder.update({WelcomePage:"SitePages/NewHomePage.aspx"});`

**Comment by PowellT** [comment]
You saved the day!
Thank you!
