### ISSUE TITLE
Owners Group Full Control User but getting [403] Forbidden on Insert/Update only in app

### ISSUE THREAD

**Issue by acksoft** [pnp/pnpjs#2626]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [x] Documentation gap/issue (maybe?)

### Version
Please specify what version of the library you are using: [3.12.0]
Here are all the packages currently in my new project
![npm-list-blur](https://user-images.githubusercontent.com/13240477/229178433-55dde5e1-8653-4be8-a9d7-e6c90ae53429.png)

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

My apologies for re-ordering the topics below:
### Observed Behavior
I've built a web part that I run and test in workbench.aspx on a site collection where I am in the Owners security group with Full Control permissions.  When updating and inserting records in a list via the Out-of-Box SharePoint UI, everything works as expected and SharePoint respects my status as a full control user.

While developing the web part, I created read operations without incident and everything behaved as expected.  However, as soon as I begin to add insert and update code, I being receiving **[403] Forbidden** errors that display in the console and cause the web part to cease functioning.

### Steps to Reproduce
Add 
`sp.web.lists.getByTitle(listName).items.add(newData)` 
or 
`sp.web.lists.getByTitle(listName).items.getById(itemId).update(newData)`
to the code in the web part

### Expected / Desired Behavior / Question
Up-front apologia/context: while I hope this doesn't reach tl;dr levels of detail, I feel that it should be noted that **I am a consultant returning to SPFx/PnP development after almost 2 years away** (having spent the interim time consulting on issues of SharePoint Governance and Adoption).  I have read the V3 docs, and watched the 5 part video series explaining the sample application on YouTube.

In my previous experience, it was always "known" that SPFx web parts executed in the context of the current user, and therefore would pass the logged-in user's credentials/permissions to the site where the web part was running to determine permitted operations.  Given the issue I am experiencing, I am guessing that things may have changed in my absence.

I vaguely remember that projects that relied on "app only" security required some extra steps on the server side in order to run successfully.  So my first question is: _**are those steps (or something like them) now required for all SPFx web parts?**_

If the answer to that question is some version of _yes_, then it feels like there is indeed some gap in the documentation for developers making the transition from version 2 to version 3, particularly for developers like myself who will happily code all day but for whom any sort of server configuration leaves us cross-eyed and/or dependent on our administrators in environments where we do not have control (which is reserved by "corporate IT and Security" for themselves).

The transition guide (2->3) deftly punts on the subject Authentication (which I am assuming is the heart of the issue here), and understandably so as it is not a trivial topic, but _the end result is that there is additional friction in the development process_ and at present no really clear path to removing it.  Some additional information and step-by-step guidance to avoid this issue would seem to be called for.

While I am aware that this is an issue that _can_ be categorized as "outside the scope of the library", the fact remains that it was the inclusion of the library's `.add()` and `.update()` methods that precipitated the error messages, and I am now in search of guidance to assist in my successful use of the library.

Any assistance/advice/guidance on 1) the fundamental assumptions that have changed and 2) the specific steps required to get this resolved will be gratefully received.

Thank you for your time and attention.

**Comment by juliemturner** [comment]
Known issue with version 3.12.0... please see changelog: https://github.com/pnp/pnpjs/blob/version-3/CHANGELOG.md#3121---2023-feb-14

**Comment by acksoft** [comment]
Julie, thank you for the quick response, it is much appreciated. I followed the link you provided and just to be clear, _the fix for me here is to update to using the 3.12.1 version of the library?_ Is that correct?

Thanks again

**Comment by juliemturner** [comment]
yes
