### ISSUE TITLE
Update community references and links 

### ISSUE THREAD

**Issue by DonKirkham** [pnp/pnpjs#2627]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ version 3 ]

Please specify what version(s) of SharePoint you are targeting: [ na ]

### Change needed / offered
The links in the documentation reference the SharePoint Patterns and Practices initiative and the aka.ms links are using sppnp*. 
 Recommend that they be changed to reference the Microsoft 365 and Power Platform Community and the aka.ms links updated to use the community/* links. While the old links are still functional, updates should be made to refence the new name and aka.ms links.

I am not sure if I can assign this to myself, so please assign it to me if I can't.
I will update the V3 documentation. I can also update the V1 & V2 docs, but I don't think that is needed since the links actually still work and those versions are not the active version.  Let me know.

**Comment by juliemturner** [comment]
Feel free to submit a PR.

**Comment by DonKirkham** [comment]
So you are good with V3 only in the update?  Just checking.  I am waiting to hear from D Warner if there is a new aka.ms url for https://www.youtube.com/@Microsoft365Community, then I'll submit the PR.

**Comment by juliemturner** [comment]
We are no longer supporting versions earlier than v3 so yes.
