### ISSUE TITLE
Facing error 403 when attempting to POST term to term set using SPFxToken

### ISSUE THREAD

**Issue by NikkiDilling** [pnp/pnpjs#2628]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version
PnP version "3.13.0",
SPFx version "1.16.1"

Please specify what version(s) of SharePoint you are targeting: [  Sharepoint Online  ]

### Expected / Desired Behavior / Question
Hello, I'm also facing an issue that was referenced in issue #2552 . I've looked closely at the documentation and possible solutions that have been provided in the issue, but still get error 403 when attempting to POST a term to term set via a custom web part using REST API.

### Observed Behavior
The console is giving me the following error:
![image](https://user-images.githubusercontent.com/94929966/229457980-c0123b0a-205f-4d79-8454-508856bb8611.png)

### Steps to Reproduce
I'm using SPFxToken function manually as was instructed in the issue #2552 but with a few changes to avoid TypeScript type errors:

```
import {spfi, SPFx } from "@pnp/sp";
import '@pnp/sp/webs';
import "@pnp/sp/taxonomy";
import { ITermInfo } from "@pnp/sp/taxonomy";
//import for SPFxToken
import { TimelinePipe } from "@pnp/core";
import { Queryable } from "@pnp/queryable";

export interface ISPFXContext {
pageContext: {
web: {
absoluteUrl: string;
};
legacyPageContext: {
formDigestTimeoutSeconds: number;
formDigestValue: string;
};
};

aadTokenProviderFactory?: {
getTokenProvider(): Promise<{
getToken(resource: string): Promise;
}>;
};
}

function SPFxToken(context: ISPFXContext): TimelinePipe {

return (instance: Queryable) => {
instance.on.auth.replace(async function (url: URL, init: RequestInit) {
const provider = await context.aadTokenProviderFactory.getTokenProvider();
const token = await provider.getToken(${url.protocol}//${url.hostname});

//new header object to be added to init.headers
  const myHeaders = new Headers();
  
  // setting header object with the token
  myHeaders.set("Authorization",`Bearer ${token}``);

  init.headers = myHeaders;
  
  return [url, init];
});

return instance;
};
} //end of SPFxToken
```

Then I'm initializing sp (Initializing sp using just SPFx or with the imported version of SPFxToken from the module is giving the same error in the console):

`private sp = spfi().using(SPFx(this.props.context),SPFxToken(this.props.context));`

Post Request:
```
try {  
     const newTermInfo = await this.sp.termStore.groups.getById("e0467185-dd14-4cd7-be5a-91d7436a2196").sets.getById("6abf5bea-0a43-4f52-b679-3a5982c7a0b6").children.add({
       labels: [
         {
           isDefault: true,
           languageTag: "en-us",
           name: "C",
         }
       ]
     });
   }catch (err) {
     console.log(err);
   }
```

Thank you in advance!

**Comment by patrick-rodgers** [comment]
Had a chance to test this and everything appears to work if I use the library's `SPFxToken` behavior. Can you give that a try?

```TS
// imports
import { SPFI, SPFx, spfi, SPFxToken } from '@pnp/sp';

// setup sp object
this.sp = spfi().using(SPFx(this.context), SPFxToken(this.context));


// make the call
const data = await this.sp.termStore.sets.getById("d1ddaf15-325b-4dec-8e9c-878e862443eb").children.add({
  labels: [
    {
      isDefault: true,
      languageTag: "en-us",
      name: "Hello I worked",
    },
  ],
});
```

**Comment by patrick-rodgers** [comment]
It sounds like you haven't granted the SharePoint principal the correct rights. With the token it is user+application rights, so the union of those. Meaning the app would have to also have the rights to perform the action. You can request the permissions in the manifest or set it directly in AAD.

[Docs on requesting permissions in SPFx](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#request-permissions-to-an-azure-ad-application).

**Comment by NikkiDilling** [comment]
Thank you again Patrick for taking time to look at this with me.
We have a large code base with multiple webparts, that we upgraded from PnP JS V2 to V3, so I really appreciate your help.

Just to be clear: We are currently testing your solution in an SPFx Webpart, created in version 1.16.1 with yeoman generator.
Normally we use the manifest to request MS Graph Permissions, but if I understand you correct, we should request the SharePoint permission for TermStore.ReadWrite.All as an Application Permission?

As I am not quite sure how it should be formatted in the manifest file, I have tried to do it manually in Azure.
Is it correct, that we should grant the permission for the App Registration named SharePoint Online Client Extensibility Web Application Principal?
(It is my understanding that granted permissions from applications end up here).

I tried to grant the permissions here (both Delegated and Application), but it does not seem like it fixed our problem:
 
![image](https://user-images.githubusercontent.com/94929966/231736521-107ff1f6-887e-42a5-937f-bbcd91f8d6a5.png)

Could you please verify if this was what you meant or specify what to grant.
If possible, provide the required request in the manifest.

Thank you very much in advance.

**Comment by patrick-rodgers** [comment]
Hmm...that looks right to me, you do want it as "delegated" on the app principal. And you've validated the user you're testing with can access and update the term store in the UI?

I'll have to do some more testing to see what might be not working.

**Comment by NikkiDilling** [comment]
Yes, as the user with full access, I can access and update the term store in the Sharepoint admin.
 
Thank you in advance for testing

**Comment by juliemturner** [comment]
@NikkiDilling - we really haven't been able to reproduce this issue, are you still having a problem?

**Comment by NikkiDilling** [comment]
After a while we updated to version 3 again, and the issue dissappeared. We do not know what was the issue unfortunately. Thank you for your help nonetheless 😊

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
