### ISSUE TITLE
Bug: Bad request when targeting specific item in recycle bin

### ISSUE THREAD

**Issue by milanholemans** [pnp/pnpjs#2629]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: `v3.13.0`

Please specify what version(s) of SharePoint you are targeting: `SharePoint Online`

### Expected / Desired Behavior / Question
Trying to remove/restore an item in a SharePoint site recycle bin. It should restore/remove the item.

### Observed Behavior
Bad request:

![image](https://user-images.githubusercontent.com/11723921/229637853-e463fb57-38dd-4391-866c-a451388cf46a.png)

This is because the ID should be surrounded in quotes: `recycleBin('b38e7b83-e405-4726-898f-774eda28543a')/Restore`

### Steps to Reproduce
```typescript
await sp.web.recycleBin.getById('<list item GUID>').restore();
```

**Comment by juliemturner** [comment]
Thanks for reporting this, we'll look into it.
