### ISSUE TITLE
Support for Classic Pages

### ISSUE THREAD

**Issue by coreyroth** [pnp/pnpjs#2634]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   3.13.0      ]

Please specify what version(s) of SharePoint you are targeting: [   Online      ]

### Expected / Desired Behavior / Question
This is not a common scenario, but I wanted to ask about it here since I was encouraged to.  I have some customers where I still have to support a handful of classic pages.  I am making use of @pnp/sp in TypeScript using webpack to generate a single javascript file that I can include from a CDN using a script reference in the master page (yeah, I know, but some people want it).  My question is how do I create a web or sp object for the current site without an SPFx context?  Is it possible?

My legacy 2.x implementation works fine.  I simply create a web object like this:
`const web = Web((window as any)._spPageContextInfo.webAbsoluteUrl);`

However, with 3.x, that doesn't work because there aren't any observers and I couldn't figure out how to create one given I don't have an SPFx context to work off of.

### Observed Behavior
Due to this being an edge case, I am definitely not asking for support for classic pages in 3.x.  I'm really just curious if it's possible or not.  This particular solution only has one pnp call in it so I just reverted back to 2.x for now which works fine.

**Comment by juliemturner** [comment]
Sure... the SPFx behavior that creates the observers takes a context object which is typed as [ISPFXcontext](https://github.com/pnp/pnpjs/blob/version-3/packages/sp/behaviors/spfx.ts#L6). You can certainly create your own instance of that object and as you can see from [line 55](https://github.com/pnp/pnpjs/blob/version-3/packages/sp/behaviors/spfx.ts#L55) you only really need to specify the absoluteUrl and ideally the formDigestValue I would think but you can make decisions based on what you have available....

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
