### ISSUE TITLE
Unable to set up PnP SP context for a specific site collection

### ISSUE THREAD

**Issue by Mohamedbg23** [pnp/pnpjs#2635]
Hello,

I'm currently using PnP SP to work with SharePoint site collections. I can successfully get the context of the current site where the web part is installed (let's call it Site A) using the following code:

`let _sp: SPFI = getSP(props.context);`

This getSP method is part of the pnpjsconfig.ts configuration.

Now, I want to get the context of another site collection (let's call it Site B). I've tried setting up the context with:

`const site = spfi("x.sharepoint.com/sites/siteb");`

Then, I attempted to fetch the list titles from Site B, but I'm not getting the correct context for Site B. I've searched extensively for a solution but haven't found any results. I would greatly appreciate any assistance or guidance you can provide.

Update:
i've tried this one:
const w = await sp.site.openWebById("111ca453-90f5-482e-a381-cee1ff383c9e") it seems there is an issue with the get api i've tried it on my browser i am getting nothing with a real web id of mine
![Capture](https://user-images.githubusercontent.com/123561528/230606655-e4c2b9cc-8504-4109-bc7d-dd4114ef92e1.PNG)

![Capture](https://user-images.githubusercontent.com/123561528/230607227-6506fb64-fddf-46b2-8afc-c1f9b25c6040.PNG)

![Capture](https://user-images.githubusercontent.com/123561528/230607311-984ba896-cacb-47fe-99da-ee58be488814.PNG)

Thank you in advance.

**Comment by juliemturner** [comment]
Documentation is here: https://pnp.github.io/pnpjs/getting-started/#connect-to-a-different-web
or here: https://pnp.github.io/pnpjs/sp/webs/ under `Access a web using the Web factory method`

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
