### ISSUE TITLE
sp.utility.sendEmail fails (Sometimes) with 500 error "Server does not support secure connections."

### ISSUE THREAD

**Issue by jduysen** [pnp/pnpjs#2636]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.11]

Please specify what version(s) of SharePoint you are targeting: [2019]

### Expected / Desired Behavior / Question
Sending email via sp.utility.sendEmail should send email successfully.

### Observed Behavior
Sending email via sp.utility.sendEmail fails about 75% of the time with 500 error "Server does not support secure connections."

Our share (via the share button on sp pages) email notifications seem to work without issue, but this seems to fail intermittently.  I am confused why it wouldn't fail 100% of the time if there were an smtp configuration issue.

Is there a workaround to disable ssl or a known issue I might be running into?

**Comment by juliemturner** [comment]
I'm sorry the issue you're having is not in the scope of this library as it is simply a proxy to the SharePoint APIs, in other words you would have the same issue if you were using this library or not. I'll tag it as such but I'm not sure you're going to get a response. I might suggest you try other forums.

**Comment by jduysen** [comment]
Thanks for the response. Sharepoint administrator seems to have found a solution. Closing.
