### ISSUE TITLE
RestrictedMode on Multi-line text

### ISSUE THREAD

**Issue by EagleWizard28** [pnp/pnpjs#2637]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

To add a multi-line text field, in the code example the "RestrictedMode" is set to false.
https://github.com/pnp/pnpjs/blob/version-3/docs/sp/fields.md#add-a-multi-line-text-field

However in the official documentation on Microsoft Learn, the following is stated:
https://learn.microsoft.com/en-us/sharepoint/dev/schema/field-element-field#elements-and-attributes 

<html>
<body>

RestrictedMode | Optional Boolean. TRUE to not allow the Note field to contain enhanced rich text formatting, such as pictures, tables, or hyperlinks, nor to allow pasting formatted text into the field.
-- | --

</body>
</html>

It is not clear, even from the official documentation what the `RestrictedMode` does, compared to the `RichTextMode`.
And an additional `RichtText` boolean property also doesn't help.

Could you help to clear up the confusion around these properties and maybe update the documentation accordingly?

**Comment by juliemturner** [comment]
I'm not sure what enhancement you're looking for here. We, quite deliberately, do not try and duplicate the official Microsoft documentation. If you have a particular question about that feature, I can try to answer it.

**Comment by EagleWizard28** [comment]
I'll address the unclarity of the Restricted Mode in the sp-dev-docs themselves. 
However, the confusion for the code example for the multi-line text still remains. There are 2 examples.

The "non-enhanced" version:
https://github.com/pnp/pnpjs/blob/version-3/docs/sp/fields.md#add-a-multi-line-text-field 

And the "enhanced" version:
https://github.com/pnp/pnpjs/blob/version-3/docs/sp/fields.md#add-a-multi-line-text-field-with-enhanced-rich-text

Why is in the first example, the `RestrictedMode` put to `false`, when from the Microsoft documentation that would indicate that it is allowed to contain enhanced rich text formatting? 

Which can mean different things:
- The `RestrictedMode` should be put to `true`, since it is a "non-enhanced" field.
- Or, SharePoint doesn't care about the value and then it can just be removed from the code example to avoid confusion

**Comment by juliemturner** [comment]
I think I finally understand your question. There were historically 3 modes to a text field. Plain Text, Rich Text, and Enhanced Rich Text. The way you manipulated them was to set the two properties `RichText` and `RestrictredMode` in some combination...

| Mode | RichText | RestrictedMode |
| --- | --- | --- |
| Plain Text | false | false |
| Rich Text | true | true |
| Enhanced Rich Text | true | false |

The UI no longer shows the option for just "Rich Text" mode but the APIs still support it.
