### ISSUE TITLE
SFPx 1.17.0 Caching has no properties in common with type 'ICachingProps'

### ISSUE THREAD

**Issue by jtlivio** [pnp/pnpjs#2638]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    3.13.0     ]

Please specify what version(s) of SharePoint you are targeting: [     1.17.0    ]

#### SPFX 1.16.1

``` ts
import { Caching } from "@pnp/queryable";
```

``` ts
//Extending our sp object to include caching behavior, this modification will add caching to the sp object itself
this._sp.using(Caching("session"));

//Creating a new sp object to include caching behavior. This way our original object is unchanged.
const spCache = spfi(this._sp).using(Caching("session"));
```

#### SPFX 1.17.0

``` ts
import { Caching } from "@pnp/queryable";
```

``` ts
//Extending our sp object to include caching behavior, this modification will add caching to the sp object itself
this._sp.using(Caching("session"));

//Creating a new sp object to include caching behavior. This way our original object is unchanged.
const spCache = spfi(this._sp).using(Caching("session"));
```

``` ts
error TS2559: Type '"session"' has no properties in common with type 'ICachingProps'.
```

### Workaround

``` ts
const response: IListModelResponse[] = await this._sp.web.lists
        .getByTitle(this.LIST_SOURCE)
        .items
```

**Comment by juliemturner** [comment]
I think the error points directly to the problem. The `Caching` behavior expects an object of type ICachingProps... [this section](https://pnp.github.io/pnpjs/queryable/behaviors/#custom-key-function) in the documentation shows a bit more about what that object looks like and you should also be able to `Go to Type Definition` to see the details of the type in Visual Studio Code.

**Comment by jtlivio** [comment]
Hello @juliemturner yes I can see the problem, just following the documentation. 

In version 1.16.1 no problems at all.
[MS Learn Here](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts)

**Comment by juliemturner** [comment]
@jtlivio Thank you very much for pointing out the issue in that Microsoft Learn documentation. We'll get that corrected.

**Comment by jtlivio** [comment]
@juliemturner Thank you for sharing, great work on the Pnpjs

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
