### ISSUE TITLE
How to enable likes on a list with pnpjs?

### ISSUE THREAD

**Issue by PowellT** [pnp/pnpjs#2642]
### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version
 v2.1.2 or v3

Please specify what version(s) of SharePoint you are targeting: [SPO  ]

I am trying to add a list, ala
sp.web.lists.add("Ideas","Ideas", 100, true);
works great, but I need to enable likes on this list
I assume it is passed in the addtionalSettings param, but not having much luck :(

Any help in this regard is greatly appreciated!

Thanks,
Powell

**Comment by bcameron1231** [comment]
Unfortunately, this is not something we support through PnPJs. This is also not a published & supported REST API from Microsoft. 

However, an undocumented endpoint exists if you care to use it. (Update your own list ID)

`POST _api/Microsoft.SharePoint.Portal.RatingSettings.SetListRating?listID='6b847372-cf23-4bbf-87b1-72ca6c8a4bc1'&ratingType=2`
