### ISSUE TITLE
Unable to update a SharePoint list item when field is a site column.

### ISSUE THREAD

**Issue by MacBoiler** [pnp/pnpjs#2643]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     ^2.5.0-beta2    ]

Please specify what version(s) of SharePoint you are targeting: [   SPO      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

Adding new item to an SPO list via the following function...

// add an item to the list
    async function addMilestone() {
      await web.lists.getById("24a5df3a-b842-422b-adbc-f170a8a14951").items.add({
        Title: initiative,
        Status: statusValue,
        MilestoneName: milestoneName,
        CompletionDate: completionDate
      });

The Status field is a site column and I'm getting the field not found error so I've reverted back to a list column and it all works fine.

Is this a limitation of PnPJS as in not being able to update site column fields in a list?

Regards

Gaz

**Comment by bcameron1231** [comment]
Hi. Thank you for submitting an issue. A couple things are jumping out at me. 

1. The Status Column is a reserved column in SharePoint. If you are using the out of the box Status column, the internal field value is actually **_Status**. It just sounds like you're using the wrong internal name. I would go to your site column and edit it in the browser, you should see the true internal name in the URL (this is what you'd use in your request, and not "Status").

![image](https://user-images.githubusercontent.com/7944457/232524651-092e5990-42e3-4f04-8a0d-edca4f5037b5.png)

2. Is there any reason you aren't using the V3 version of PnPJs? V2.x is a very old version of PnpJS and we'd recommend upgrading. Additionally, if you're going to stay on V2, I would recommend getting off from a beta release, and into use a more stable version.

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Comment by MacBoiler** [comment]
Thanks for the feedback @bcameron1231. I will have a closer look at the site column internal names next time and good to know that they can be accessed like a list column.

Also, I did try and build this particular solution with V3 initially but I just had so many other incompatibility issues happening (especially as my solution is heavily Material UI based) it was just easier due to time constraints to jump back to V2 and everything just worked.

It's also been a couple of years since I last built any SPFx solutions so I'm still catching up with all the changes etc. and not just with PnPJS but the whole jump from class to functional etc.

Thanks again for your comments.
