### ISSUE TITLE
Can I do a two level lookup?

### ISSUE THREAD

**Issue by rzempo** [pnp/pnpjs#2648]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [^3.14.0]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
Is there a way to query query two levels of lookup columns? I.e.

List: Countries
Items: US | Mexico

List: States (with County column looking up to countries)
Items: Minnesota, US | Utah, US | CDMX, Mexico | Yucatan, Mexico

List: People (with State column looking up to States)
Items: Ruben, CDMX | Timmy, Utah

Is there a way to query People and expand State and then County inside State?
Query would be similar to this
```
const { context } = this.props;
this._sp = spfi().using(SPFx(context));
this._sp.web.lists.getByTitle("PeopleState")
  .items
  .select(
    "Id"
    , "Title"
    , "State/Id"
    , "State/Title"
    , "State/Country/Id"
    , "State/Country/Title"
  )
  .expand("State", "State/Country")
  .orderBy("Title")
  .top(5000)
  ()
  .then(items => {

    items.forEach((item) => {

      console.log("item", item);
    });

  }).catch(error => {

    console.error("error", error);
  });
```

If I try this I get a "The query to field 'State/Country' is not valid." error.

Thanks in advance.
-Ruben

**Comment by bcameron1231** [comment]
Hi, to the best of my knowledge this is not possible and this is not a limitation of PnPjs, but a limitation of the SharePoint REST APIs.

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
