### ISSUE TITLE
How to filter insensitive case in pnp query for siteuser and groups

### ISSUE THREAD

**Issue by yogendermanral** [pnp/pnpjs#2649]
Not able to use lower inside substringof for siteusers and groups for insensitive case
My code is 

            var users = await pnpContext.web.siteUsers.filter(`substringof('Test', Title) or substringof('Test)`)();
Result give data only for "Test". Not for test or other case combination.

Finding :- substringof should give case insensitive data for list string type column but giving case sensitive data for siteusers and groups.

Requirement is :- Want case insensitive filter for user and group search.

Please help.

Early help will be appreciable

**Comment by bcameron1231** [comment]
Hi, thanks for the issue. Unfortunately, this is not supported by the SharePoint. Please see the REST documentation here in the String comparisons section.

https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests#odata-query-operators-supported-in-the-sharepoint-rest-service

**Comment by yogendermanral** [comment]
thanks @bcameron1231 for your reply.

I have gone through the shared link.

Is there any workaround for this?

I have the condition to filter users and groups.
Please help

**Comment by yogendermanral** [comment]
Thanks @juliemturner and @bcameron1231 for your valuable quick responses
