### ISSUE TITLE
Creating a Field and naming it.

### ISSUE THREAD

**Issue by Holden15** [pnp/pnpjs#265]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.2.1     ]

Please specify what version(s) of SharePoint you are targeting: [    1.6.0     ]

I would like to create a field in a list that has a Display name with spaces, and then the FieldName w/out spaces.  Some of my fields will have spaces in them and we don't want to have to deal with FieldNames with spaces. (MyField4_x0020_DISPLAY, don't want the x0020). 

I create the field:
```
let xml = `<Field DisplayName="MyField4 DISPLAY" Type="Text" Required="FALSE" StaticName="MyField4STATIC" Name="MyField4NAME" MaxLength="125" Group="~Example" />`;
listEnsureResult.list.fields.inBatch(batchCreate).createFieldAsXml(xml);
```
When the list and field are created, all the names are MyField4 DISPLAY:

![image](https://user-images.githubusercontent.com/43765678/46426857-63ec6200-c705-11e8-8a88-a7a74f4fe3b1.png)

![image](https://user-images.githubusercontent.com/43765678/46426870-6c449d00-c705-11e8-9d75-2c8459fa13c6.png)

Can I set the different names?

**Comment by koltyakov** [comment]
Hi @Holden15, 

This is REST API behavior nuance which we can't be amended in the library I'm afraid.

As an option, a field can be created with a display name equals to the internal name and then renamed to whatever display name is required:

```typescript
const schemaXml = `
    <Field 
        DisplayName="MyField15InternalName" 
        Name="MyField15InternalName" 
        Type="Text"
        Required="FALSE"
        MaxLength="125"
        Group="~Example"
    />
`;

list.fields.createFieldAsXml(schemaXml)
    .then(field => {
        return field.field.update({
            Title: 'MyField15 Display Name'
        })
    })
    .then(console.log);
```

**Comment by Holden15** [comment]
@koltyakov Ok, thanks for the info and appreciate the suggestion.

**Comment by Holden15** [comment]
@koltyakov , do you know if you cant batch updates?  I'm getting change conflict errors.

**Comment by koltyakov** [comment]
Yes, should be possible if retrieve newly created field by name. This works for me:

```typescript
const schemaXml = `
    <Field 
        DisplayName="MyField19InternalName" 
        Name="MyField19InternalName" 
        Type="Text"
        Required="FALSE"
        MaxLength="125"
        Group="~Example"
    />
`;

const batch = sp.web.createBatch();

list.fields.inBatch(batch).createFieldAsXml(schemaXml);
list.fields.getByInternalNameOrTitle(`MyField18InternalName`).inBatch(batch).update({
    Title: 'MyField18 Display Name'
});

batch.execute().then(_ => console.log('Done'));
```

On backend request sent in batches are executed sequentially.

**Comment by Holden15** [comment]
@koltyakov Ah, figured out my issue.  I had my `inBatch` before the `getByTitle`.  I move it to after and its running great.

```
ler.list.fields.inBatch(batchUpdate).getByTitle(kPropertyDamage).update({
    Title: "Property Damage"
});
```

Changed to:

```
ler.list.fields.getByTitle(kPropertyDamage).inBatch(batchUpdate).update({
    Title: "Property Damage"
});
```

Thanks for the help, truly appreciate it!
