### ISSUE TITLE
Login to Sharepoint

### ISSUE THREAD

**Issue by Hk1020** [pnp/pnpjs#2651]
I am using this in a nodejs project. How do I connect to SharePoint as my current Windows user?

I've been doing this with pnpjs V2 and the `pnp-auth` package but that package doesn't support `v3`.  pnp-auth asked me for a user and password once and saved the result. Perfect for my purpose. I used it like this:

```
import pkg from "@pnp/sp-commonjs";
const { sp, PrincipalType, PrincipalSource } = pkg;
import { bootstrap } from "pnp-auth";

class SimpleSpClient {
    constructor(sharepoint) {
        const authData = "./sp.config.json";

        const site = sharepoint.site;
        this.spList = sharepoint.spList;

        const siteUrl = `https://worksite.sharepoint.com/sites/${site}`;

        bootstrap(sp, authData, siteUrl);

        this.spClient = sp;

    }
   ...
}
```

How could the equivalent been achieved with `v3` alone?  `pnp-auth` doesn't support `v3`.

**Comment by juliemturner** [comment]
The package pnp-auth is not related to this library so I cannot comment on it. 

That said to do authentication with user I would point you to the msal wrapper package, here are the docs: https://pnp.github.io/pnpjs/concepts/auth-nodejs/#msal-nodejs and then you'll need to reference the MSAL documentation to configure it: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/README.md (probably the username and password flow)
