### ISSUE TITLE
Accessing Word Automation Services using pnpjs

### ISSUE THREAD

**Issue by gjblajian** [pnp/pnpjs#2654]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of SharePoint you are targeting: [         ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

We are investigating using SharePoint, SP, Word Automation Services, WAS, on demand to render Table of Contents, ToCs in word documents we are generating, prior to sending them to a third party vendor. Avoiding the need to open the Word Document to answer this prompt: 
![image](https://user-images.githubusercontent.com/5183939/234578174-2d5f057f-687f-4d79-b837-1539a1ac957c.png)

- See https://learn.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee558830(v=office.14) "Supports all automatic tasks that execute when a document opens, such as: Updating the Table of Contents, the Table of Authorities, and index fields."
- And https://learn.microsoft.com/en-us/sharepoint/dev/general-development/what-s-new-in-word-automation-services-for-developers#perform-file-conversions-on-streams for operating on streams "Perform file conversions on streams
The other new feature in Word Automation Services in Microsoft SharePoint is support for converting streams. In SharePoint 2010, you could only convert files that were stored in SharePoint libraries. Now you can also convert files that are stored outside SharePoint using streams."

We would like to know if there is some way to use pnpjs to make synchronous WAS calls to SP sending the word doc, as a stream, with the newly generated ToC, have SP process the ToC through WAS getting back the fully calculated ToC and then send the result to a 3rd party.

All code would be executed via a nodejs application and would require us setting up SP with WAS somewhere.

If someone knows of a better way to handle ToCs in Word without having to set up SP just for the WAS service we are certainly open to suggestions.

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

Thank you for your feedback!

**Comment by juliemturner** [comment]
@gjblajian I'll tag this as help wanted, but since PnPjs is simply a passthrough to the SharePoint REST API or the Microsoft Graph API I suspect the audience here won't have much insight and you might not get much traction. I would try finding a forum like on Stack Exchange or possibly Tech Community as you might get more coverage there.

**Comment by gjblajian** [comment]
To be clear, we are not asking someone to code a solution we are asking if pnpjs can even be used to call WAS related services [Microsoft.Office.Word.Server.Conversions.SyncConverter] on SharePoint

**Comment by juliemturner** [comment]
AFAIK those are not RESTful endpoints their .NET SDKs... and so therefore no... but I haven't looked into it very much. If you can find a reference that indicates that there's a flavor of WAS that is exposed via REST then we could potentially support it.

**Comment by patrick-rodgers** [comment]
Could in theory the library be used to call this service? Maybe. We have no plans to implement it, so it is likely in this case you're better off just writing the code you need. You can always use any of the libraries or copy any of our code you like (its all open source).

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
