### ISSUE TITLE
Create SharePoint Survey List and set the property (Show user names in survey results?-NO) @pnp/sp version 2.9

### ISSUE THREAD

**Issue by arunchinnaraj2310** [pnp/pnpjs#2664]
Create SharePoint Survey List and set the property (Show user names in survey results?-NO) @pnp/sp version 2.9

![image](https://user-images.githubusercontent.com/132877062/236749444-4fa7a4bc-659a-4b28-b1bb-b5e7f66c4924.png)

**Comment by patrick-rodgers** [comment]
You've skipped filling out the issue template. I am guessing from the title you are using v2 which is no longer supported. Is there something blocking you from moving to v3?

I assume this is exposed as a list property, which the library supports updating.

**Comment by bcameron1231** [comment]
AFAIK, this property on the list "ShowUsers" is not exposed on the REST API and so it can't be updated. 

The only way I could see this working is by creating the list using a SchemaXML.

**Comment by arunchinnaraj2310** [comment]
@bcameron1231 can you please guide me how to create the list using a schemaXML and JavaScript as i need it for an application developed with REACT SPFX.

I have seen a blog for doing it with C# CSOM.
https://piyushksingh.com/category/sharepoint-online-list/

**Comment by arunchinnaraj2310** [comment]
@patrick-rodgers we have developed the application with V2 and we can't change it V3 now. can you guide with the implementation in V2 for setting the **Show user names in survey results?** property to no

**Comment by bcameron1231** [comment]
Hi, in full transparency I haven't tested this, so I really don't know if it's possible to create a survey list from the SchemaXML. But you could spend some time to 

const list = await sp.web.lists.add("SurveyList","Description", 102,false, {
    SchemaXml: `<YourListSchemaDefinition>`,
    TemplateFeatureId:"{00bfea71-eb8a-40b1-80c7-506be7590102}"
})

Unfortunately, the rest is a bit out of our control and I'm not sure I'll be able to help you much further.

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
