### ISSUE TITLE
Unable to add items to a list

### ISSUE THREAD

**Issue by emaborsa** [pnp/pnpjs#2669]
Hi all,

I am trying to add an item to a list, the code is the following:

```
const sp = spfi("https://my.sharepoint.com/sites/IT"); 
const web = Web([sp.web, "https://my.sharepoint.com/sites/IT"]);
const list = web.lists.getById(vodafoneDispositiviListId);
const items = list.items;
try {
  const i = {
    Title: "Test",
  };
  const addResult = await items.add(i); // <-- here it stops
  console.log(addResult );
} catch (error) {
  console.log(error);
}
```

The code works until `items.add` is called, no errors in the console and no errors catched. The execution just stops.
Any idea?

I tested it without async await as well like following:

```
items
  .add(i)
  .then((addResult) => {
  res.push(addResult);
  return addResult;
})
.catch((error) => console.error(error));
```

Neither `then`, nor `catch` are called.

**Edit:**
I am sorry, forgot my code:

```
const sp = spfi("https://my.sharepoint.com/sites/IT").using(
  DefaultInit(),
  DefaultHeaders(),
  BrowserFetchWithRetry(),
  DefaultParse()
);
const web = Web([sp.web, "https://hgvbz.sharepoint.com/sites/IT"]);
const list = web.lists.getById(vodafoneDispositiviListId);
const items = list.items;
try {
  const res: IItemAddResult[] = [];
  const i = {
    Title: "Test",
  };
  items
    .add(i)
    .then((addResult) => {
      res.push(addResult);
      return addResult;
    })
    .catch((error) => {
      console.error(error);
    });
  console.log(res);
} catch (error) {
  console.log(error);
}
```

and the dependencies:

```
{
    "@microsoft/sp-core-library": "1.17.1",
    "@microsoft/sp-lodash-subset": "1.17.1",
    "@microsoft/sp-office-ui-fabric-core": "1.17.1",
    "@microsoft/sp-property-pane": "1.17.1",
    "@microsoft/sp-webpart-base": "1.17.1",
    "@pnp/sp": "^3.14.0",
}
```

Working on SPFx.

**Comment by patrick-rodgers** [comment]
It doesn't look like you've added any behaviors/observers to the timeline. Please see [here](https://pnp.github.io/pnpjs/core/timeline/#observer-inheritance) and [here](https://pnp.github.io/pnpjs/queryable/queryable/#no-observers-registered-for-this-request) for more information.

**Comment by emaborsa** [comment]
...using the UI the user is able to create listitems, using the code above:

```
Error: Error making HttpClient request in queryable [403]  ::> {"odata.error":{"code":"-2130575251, Microsoft.SharePoint.SPException","message":{"lang":"de-DE","value":"Die Sicherheits\überprüfung f\u00fcr die Seite ist ung\u00fcltig und möglicherweise fehlerhaft. Klicken Sie im Webbrowser auf die Schaltfläche 'Zurück', um den Vorgang zu wiederholen."}}}
    at HttpRequestError.init (parsers.js:96:1)
    at async Proxy.errorCheck (parsers.js:45:1)
    at async queryable.js:120:1
```

**Comment by emaborsa** [comment]
Well, I am not saying you do a bad work. I mean the whole SharePoint world is a mess.

> We have lots of [docs](https://pnp.github.io/pnpjs/)

That's the point, it is hard to find what you are looking for.

Because I need to access a list of another web, I started from [Connect to a different Web](https://pnp.github.io/pnpjs/getting-started/#connect-to-a-different-web). As mentioned in another [issue](https://github.com/pnp/pnpjs/issues/2665), it is buggy, because `SPDefault` does not take a `WebPartContext` as parameter.

I took a look to `observers` and `behaviors`, did not really understand if I need one/some, tried to run a code without, it runs and does not throw any error or warning, I added my code in the question. 

If an observer is required, why not to mention it in the [getting started guide](https://pnp.github.io/pnpjs/getting-started/)?

If you need further information to investigate the behavior of my snippet, please let me know.

**Comment by emaborsa** [comment]
Hi @bcameron1231,

thanks, I just fixed it doing like you posted.
> const sp = spfi("https://my.sharepoint.com/sites/IT").using(SPFx(this.context));
 await sp.web.lists.getByTitle("Test");

I am waiting to see if @patrick-rodgers is able to figure out why I don't get any error when no observers are set.

**Comment by juliemturner** [comment]
@emaborsa  - Are you saying you are wondering why you don't get a "pre" transpile error when no observers are set?
There are a multitude of closed issues in this repo proving out that you'll get runtime errors if you have no observers set, and the fact that you don't is shared in the error message itself.

**Comment by emaborsa** [comment]
> @emaborsa - Are you saying you are wondering why you don't get a "pre" transpile error when no observers are set? There are a multitude of closed issues in this repo proving out that you'll get runtime errors if you have no observers set, and the fact that you don't is shared in the error message itself.

Actually no. I said `no errors in the console and no errors catched. The execution just stops.`

**Comment by bcameron1231** [comment]
Thanks for noticing this. We found a bug where it wasn't always returning this error when it was supposed to. This has been fixed and is included in the release we did today.
