### ISSUE TITLE
Support for Project Server REST API

### ISSUE THREAD

**Issue by phawrylak** [pnp/pnpjs#267]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

I think it would be good to have Project Server REST API supported in pnp-js. I can work on it. @patrick-rodgers and @koltyakov, what do you think about it?

**Comment by patrick-rodgers** [comment]
Sure, that sounds great. I am personally not familiar with the project server api, but it seems like this would be a new package? Something like "@pnp/project" or something? I can help you set that up if that is the case. You would also probably want to create a set of base classes (you can use the sp or graph ones as examples).

**Comment by phawrylak** [comment]
In my opinion it should be in a new package. @pnp/project is what I had in mind. I think I will be able to set it up myself - I'm already familiar with pnpjs code.

My initial plan was to use [Odata V4 Client Generator for VSCode](https://github.com/apazureck/odatatools) to generate TypeScript proxy classes from /_api/$metadata endpoint and then refactor them to pnpjs convention. Unfortunately it doesn't support OData v3 that is used by SharePoint/Project Server REST API, so I would have to implement support for it first. Anyway, that should be faster than creating all manually as Project Server REST API is not so small. I'll try to do that. If it will not work, I will implement support for this API in pieces starting from the most important ones.

**Comment by patrick-rodgers** [comment]
There is a non-published yeoman generator to help you scaffold the project folder, but perhaps you have already done that. Might save you a little time. Also, in the last release I updated all the projects, so please check you've got the latest if you are building by hand to ensure it all matches up. Look forward to seeing what you come up with.

**Comment by phawrylak** [comment]
@patrick-rodgers, I have implemented basic support for getting, adding, updating and deleting projects. Within a week I should be able to add support for managing tasks. Then I will probably create a PR with these changes as it should be enough for first release of Project Online support.

Additionaly I have a question. Currently I use classes from @pnp/sp package (SharePointQueryable etc.) as it seems more reasonable to me than copying this code. Is it ok or should I remove dependency to @pnp/sp?

**Comment by patrick-rodgers** [comment]
Great news on the progress, excited to see it!

Regarding the use of the classes from sp - is there a reason not to create something like ProjectServerQueryable? I am not that familiar with the API but we do like to reduce the dependencies where possible. If folks would potentially use this library and not make SP requests it would be good to not have that dep. I haven't seen any of your work so can't make more than that general suggestion.

**Comment by Zireael** [comment]
Sorry for shameless plug, but would I be able to call SOAP operations using @pnp/project (from a .asmx or .svc)?
I have a Project server (2010) where I am able to get a response from http://srv03.mycompany.net/ProjectServerXY/_vti_bin/psi/project.asmx?wsdl with a list of usable commands, but I can't figure out how to submit a query to use them.
Trying to use these two methods does not work for me and I'm getting 404 response:
http://srv03.mycompany.net/ProjectServerXY/sites/pwa/_api/ProjectData http://srv03.mycompany.net/ProjectServerXY/_api/ProjectServer/Projects('xxxxxxxx-yyyy-zzzz-80df-ba9daa66272a').

I've tried asking on Stackoverflow (https://stackoverflow.com/questions/54796458/querying-ms-project-server-2010-through-soap-at-vti-bin-psi-project-asmx-with), but didn't get anywhere yet, so I'm looking for other solutions.
Thank you and sorry for off topic, but I appreciate your work here as there isn't much documentation/support for MsProject I could find.

**Comment by koltyakov** [comment]
@Zireael,
With `SPHttpClient` any custom endpoint including those legacies can be consumed. However, payloads should be crafted manually. I'd say that with a raw fetch, all the same, is feasible yet SPHttpClient has nice SharePoint specific features e.g. retries. And when the dependency is already in the project my recommendation is using SPHttpClient.

**Comment by Michael5011st** [comment]
Hello, I was curious if there are any updates on this package

**Comment by patrick-rodgers** [comment]
Going to close this issue as [Joel](https://twitter.com/JoelFMRodrigues) has released a [project for accessing project online](https://www.npmjs.com/package/pnpjs-project-online-package). It is not officially supported by PnP at this time, but builds on our work and provides a great foundation. Check it out!  Great work @joelfmrodrigues!
