### ISSUE TITLE
Unable to get Users Manager with @pnp/Graph 

### ISSUE THREAD

**Issue by sambilfinger** [pnp/pnpjs#2670]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using:
```
"dependencies": {
    "@microsoft/sp-core-library": "^1.17.2",
    "@microsoft/sp-lodash-subset": "^1.17.2",
    "@microsoft/sp-office-ui-fabric-core": "^1.17.2",
    "@microsoft/sp-property-pane": "^1.17.2",
    "@microsoft/sp-webpart-base": "^1.17.2",
    "@pnp/core": "^3.14.0",
    "@pnp/graph": "^3.14.0",
    "@pnp/logging": "^3.14.0",
    "@pnp/queryable": "^3.14.0",
    "@pnp/sp": "^3.14.0",
    "@pnp/spfx-controls-react": "^3.14.0"
     ...
}
```

### Expected / Desired Behavior / Question
I'm looking to get whoever is using the web part's, manager from graph.

### Observed Behavior
When requesting the user's manager I get a 403 (forbidden error). This did work previously so I don't know why it's no longer working.
```
// 20230510104509
// https://graph.microsoft.com/v1.0/me/manager

{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token is empty.",
    "innerError": {
      "date": "2023-05-10T09:45:09",
      "request-id": "023c54e1-d6c6-4682-b6b5-0ed0ce0b3f29",
      "client-request-id": "023c54e1-d6c6-4682-b6b5-0ed0ce0b3f29"
    }
  }
}
```
### To Reproduce
Using the following code (for context I am using context: any):
```
//imports
import { SPFx, graphfi } from "@pnp/graph";
import "@pnp/graph/users";

//main code block
const graph = graphfi().using(SPFx(props.context));


// get the default selected manager and set the email runs on useEffect
  const getDefaultManager = async () => {
    const graphManager = await graph.me.manager();
    setManagerEmail(graphManager.mail);
  };

```

**Comment by bcameron1231** [comment]
Hi, I am unable to reproduce your issue. 

Can you confirm that you've granted the proper API Permissions for your solution? At a minimum you'd need User.Read.All to get access to the User's Manager property.

**Comment by sambilfinger** [comment]
Hi, thanks for the prompt response.

Just confused as this has worked previously but I don't have all the admin controls of the SP site.
I've set the webApiPermissionsRequests in my package-solution.json but think I need to also get in touch with an admin to grant User.Read.All for Microsoft Graph to the site (wonder if it's been revoked).

```
  "webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read.All"
      }
    ],
```

**Comment by sambilfinger** [comment]
I've added that comment in and seems to have worked!

**Comment by bcameron1231** [comment]
Awesome! Glad it worked! Thanks.
