### ISSUE TITLE
 Is Jest unit testing supported in type script 4.5 ?

### ISSUE THREAD

**Issue by mohammadamer** [pnp/pnpjs#2671]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  3.14.0       ]
Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online      ]

### Expected / Desired Behavior / Question
The question: Is Jest testing support in type script 4.5 ?
I expected to be able to add unit tests using Jest unit testing like with the previous versions of SPFx and PnPJS. 

### Observed Behavior
I was not able to add unit tests in a SPFx WebPart.
I created a HelloWorld SPFx webpart then added the configurations for Jest to apply a unit testing, but I got warning and the unit test failed.

`ts-jest[versions] (WARN) Version 4.5.5 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=3.4.0 <4.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
 FAIL  src/webparts/helloWorld/components/Button/CustomActionButton.test.tsx
  `
  

    ● Test suite failed to run
    TypeError: setup-jest.js: Emit skipped for language service

      at compileFn (node_modules/ts-jest/dist/compiler/language-service.js:109:23)
      at Object.compile (node_modules/ts-jest/dist/compiler/instance.js:90:25)
      at TsJestTransformer.process (node_modules/ts-jest/dist/ts-jest-transformer.js:85:41)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:481:35)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:586:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:624:25)

```
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        13.952s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

### Steps to Reproduce
I'll attach the config files for my project and soon I'll share the link for the project in GitHub

Package.json

```
{
  "name": "hello-world-web-part",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "jest --runInBand"
  },
  "dependencies": {
    "@fluentui/react": "^8.109.2",
    "@microsoft/decorators": "^1.17.1",
    "@microsoft/rush-stack-compiler-4.5": "^0.5.0",
    "@microsoft/sp-core-library": "1.14.0",
    "@microsoft/sp-lodash-subset": "1.14.0",
    "@microsoft/sp-office-ui-fabric-core": "1.14.0",
    "@microsoft/sp-property-pane": "1.14.0",
    "@microsoft/sp-webpart-base": "1.14.0",
    "@pnp/graph": "^3.14.0",
    "@pnp/logging": "^3.14.0",
    "@pnp/sp": "^3.14.0",
    "office-ui-fabric-react": "7.174.1",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.14.0",
    "@microsoft/sp-module-interfaces": "1.14.0",
    "@microsoft/sp-tslint-rules": "1.14.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^12.1.5",
    "@types/jest": "^25.2.1",
    "@types/react": "16.9.51",
    "@types/react-dom": "16.9.8",
    "@types/webpack-env": "1.13.1",
    "ajv": "~5.2.2",
    "gulp": "~4.0.2",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^25.4.0",
    "jest-junit": "^16.0.0",
    "ts-jest": "^25.4.0"
  }
}
```

jest.config.js
```
module.exports = {
    "preset": "ts-jest/presets/js-with-ts",
    "testMatch": [
      "**/src/**/*.test.+(ts|tsx)"
    ],
    "collectCoverage": false,
    "collectCoverageFrom": [
      'src/**/*.{ts,tsx}',
      '!src/**/*.d.ts',
      '!src/webparts/helloWorld/HelloWorldWebPart.ts',
      '!src/**/*.scss.ts',
      '!src/**/Fake*.ts'
    ],
    "reporters": ["default", "jest-junit"],
    "coverageReporters": [
      "json",
      "lcov",
      "text",
      "cobertura"
    ],
    "coverageDirectory": "coverage",
    "moduleNameMapper": {
      "\\.(css|less|scss|sass|resx)$": "identity-obj-proxy",
      "@fluentui/react/lib/(.*)$": "@fluentui/react/lib-commonjs/$1",
      "@pnp/sp": "@pnp/sp-commonjs",
      "@pnp/sp/(.*)$": "@pnp/sp-commonjs/$1",
      "@pnp/graph/(.*)$": "@pnp/graph-commonjs/$1",
      "@pnp/nodejs": "@pnp/nodejs-commonjs"
    },
    setupFiles: ["<rootDir>/setup-jest.js"]
  };
```
  
setup-jest.js
setup-jest.js is empty

**Comment by juliemturner** [comment]
@mohammadamer it feels like you'd want to ask this question in a community for jest? Maybe another member of this community uses jest for testing and will have insight.

**Comment by mohammadamer** [comment]
Hi @juliemturner,

I thought about that but I got the warning says that:

```
(WARN) Version 4.5.5 of typescript installed has not been tested with ts-jest.
If you're experiencing issues, consider using a supported version (>=3.4.0 <4.0.0).
Please do not report issues in ts-jest if you are using unsupported versions.
```

One more thing, I've been using Jest with type script lower versions and it works.

**Comment by bcameron1231** [comment]
This message is from the Jest library itself. It's just a warning stating that jest hasn't been tested yet to run on this specific version. If you go to the ts-jest repo you'll see what versions they  have tested again (4.2.0, 4.3.0, 4.3.5, 5.0.0).

This doesn't mean Jest won't work. It just means they haven't specifically tested against this version of Typescript. If you have issues, as Julie mentioned, you should reach out to the ts-jest repo.

**Comment by juliemturner** [comment]
I'm sorry, I'm pretty confused... maybe I'm just missing your point. This is a repository for PnPjs and any issues related to using that library specifically. You seem to have an issue with (per the warning), or your question is related to, jest and typescript incompatibility... not sure how PnPjs is even involved yet other than you are using it in the same solution that you're trying to enable your unit testing in.

**Comment by mohammadamer** [comment]
hey @juliemturner and @bcameron1231,
I wanted to say that PnPjs V3 is relying on type script 4.0.0 then Jest issues arises. 
But, PnPjs previous versions were relying on lower versions of type script and Jest worked fine.

If you see that I should check for a solution in Jest then I'll go there and check. I asked the question to help me or direct me to the right way.

**Comment by juliemturner** [comment]
Thank you, I now understand your question. 

Yes, PnPjs v3 is dependent on TypeScript 4.0 because well in general code moves on and to utilize newer features when we make a major version change, we usually review the minimum version requirements of some of the dependencies. This feels pretty standard. In general, in this case this was done to minimize our dependence on tslib for backwards compatibility which helped us reduce our overall package size significantly. We think this was an important improvement. 

Personally, as I mentioned I don't use jest, so I don't have any insight for you, but maybe others in the community will.

**Comment by mohammadamer** [comment]
Hi @juliemturner and @bcameron1231,

Issue has been resolved by removing `"allowJs": true,` from tsconfig.json
You can close the issue :)
