### ISSUE TITLE
Property 'pre' is incompatible with index signature.

### ISSUE THREAD

**Issue by GermanBob** [pnp/pnpjs#2673]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

typescript 4.5.5

Please specify what version of the library you are using: [   3.14.0      ]

Please specify what version(s) of SharePoint you are targeting: [     SharePointOnline    ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
Everytime when I try to compile my Solution in VS Code but after I open queryable.js file the error while no longer marked in the queryable.d.ts file.

Thank you for your feedback!
---------------------------------------------------------------------------------------------------------------------------------------------------
 ERROR in .../node_modules/@pnp/queryable/queryable.d.ts
[1] 20:52 Type '{ readonly construct: (observers: QueryableConstructObserver[], init: QueryableInit, path?: string | undefined) => Timeline<any>; ... 5 more ...; readonly data: (observers: QueryableDataObserver<...>[], ...args: any[]) => void; }' 
does not satisfy the constraint 'Moments'.
[1]   Property 'pre' is incompatible with index signature.
[1]     Type '(observers: QueryablePreObserver[], url: string, init: RequestInit, result: any) => Promise<[url: string, init: RequestInit, result: any]>' is not assignable to type '(this: Timeline<any>, handlers: ValidObserver[], ...args: any[]) => void'.
[1]       Types of parameters 'observers' and 'handlers' are incompatible.
[1]         Type 'ValidObserver[]' is not assignable to type 'QueryablePreObserver[]'.
[1]           Type 'ValidObserver' is not assignable to type 'QueryablePreObserver'.
[1]             Type 'ObserverAction' is not assignable to type 'QueryablePreObserver'.
[1]               Type 'void' is not assignable to type 'Promise<[string, RequestInit, any]>'.
[1]     18 | };
[1]     19 | export declare type QueryableInit = Queryable<any> | string | [Queryable<any>, string];
[1]   > 20 | export declare class Queryable<R> extends Timeline<typeof DefaultMoments> implements IQueryableInternal<R> {
[1]        |                                                    ^
[1]     21 |     private _query;
[1]     22 |     protected _url: string;
[1]     23 |     protected InternalResolve: symbol;

**Comment by bcameron1231** [comment]
Hi, unfortunately there isn't much information here to go off off. Can you provide us a bit more information about what your solution is (are you just building the pnpjs solution?), what you're trying to do, and if you have any code samples to share that would help. 

It's a bit unclear. Thanks!

**Comment by GermanBob** [comment]
Hi,
I use this package in some different projects to select items from the lists and set permissions something like this but since this week I get this error message when I try to compile my projects and my select statements doesn't work anymore.
I work with VUE.js 2.6, VisualStudio Code Typescript 4.5.5 and your package in version 3.14.0
The interesting part is that it is normally working on an SPFX Project

Thanks!

**Comment by patrick-rodgers** [comment]
We really need to see your code that is causing the problem here. From what you've shared I have no idea how to help.

**Comment by GermanBob** [comment]
this is what I  try but I get also Test 1 in the console no error nothing at the end

<script lang='ts'>
import { Component, Prop, Vue } from "vue-property-decorator";
import { store } from './store/index';
import { MainState } from './store/MainState';


import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import '@pnp/sp';

import { spfi } from "@pnp/sp";

@Component({
  components: {},
})
export default class App extends Vue {
  public allListsNames: string[] = [];
  async created() {
    Helper.getAllListsOnWeb().then((results: any[]) => {
      this.allListsNames = [];
      results.forEach((one) => {
        this.allListsNames.push(one.Title);
      });
    });

    console.log("Test 1");
    try {
      const sp = spfi("URL of the page")
      let tmp = await sp.web.lists.getByTitle("MyList")
        .items.select("ID", "Title", "Author/ID", "Author/Title")
        .expand("Author")
        .top(4999)
        .orderBy("ID", false)();

      console.log("Test 2 ", tmp);

    } catch (error) {

      console.error("ERROR ", error);
    }
  }

}
</script>

**Comment by bcameron1231** [comment]
Looking at your code it seems your sp object has no observers attached. As such, none of your requests are going to be executed. Your SP object needs to have observers attached.  

` const sp = spfi("URL of the page")`

^^ This won't work.

Please check out the following documentation that should be useful dependant on your code is running. If this is a non-spfx project, you'll want to use something like SPDefault

https://pnp.github.io/pnpjs/getting-started/#using-pnpsp-spfi-factory-interface-in-spfx

**Comment by GermanBob** [comment]
Hi,
The project is not an SPfx project. The project is a normal Vue.js Application to customise the SharePoint Online. To use the normal URL of the Sharepoint has worked before too.
My Problem is when I try now to start the project that I get this error message and the select statement doesn't work anymore.
Thanks

**Comment by juliemturner** [comment]
>The project is not an SPfx project. 

I'm going to suggest trying this documentation on authenticating in a browser outside of SharePoint, maybe that's more what you're doing.

https://pnp.github.io/pnpjs/concepts/auth-browser/

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
