### ISSUE TITLE
Option to Search only the terms which are available for tagging is missing.

### ISSUE THREAD

**Issue by NewGHUser4321** [pnp/pnpjs#2674]
### Category
- [X] Enhancement
- [X] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.9.0

Please specify what version(s) of SharePoint you are targeting: SharePoint Online

### Expected / Desired Behavior / Question
When using `sp.termStore.searchTerm()`, expect an option to be available in `ISearchTermParams` to only search for the terms which are available for tagging. Am I missing something which is already available?

### Observed Behavior
When using `sp.termStore.searchTerm()`, there is no option present in `ISearchTermParams` to only search for the terms which are available for tagging.

### Steps to Reproduce
Try searching for the terms using `sp.termStore.searchTerm()`. The response you get includes all the terms irrespective of whether they are available for tagging or not.

Thank you.

**Comment by juliemturner** [comment]
I can't really say why the API works the way it does, but at this time (as far as I can tell) the ability to filter the results by available for tagging isn't an option. Keep in mind that this library is a pass through for Microsoft's REST interfaces, we don't really have any control over how they work. Given how often information you need to make these types of decisions isn't even available in the result, I'd be more inclined to celebrate the fact that the metadata is there and that I could write a quick filter function to filter out the ones that aren't available for tagging.

Also keep in mind that the taxonomy API we've implemented here is on the SharePoint v2.x endpoint, which is not officially documented. Microsoft would prefer that you use the Graph [taxonomy endpoints](https://learn.microsoft.com/en-us/graph/api/resources/termstore-store?view=graph-rest-1.0) to get this information and as far as I see (although I may have missed it), the ability to do a search for terms isn't exposed.

**Comment by NewGHUser4321** [comment]
I totally understand that this library is a pass through for MSFT's REST interfaces. I just wanted to know if there is an option available which I did not see. Of course, I'm filtering out the results and it works as expected.
