### ISSUE TITLE
Address OneDrive Analytics changes

### ISSUE THREAD

**Issue by juliemturner** [pnp/pnpjs#2677]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [x] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.15.0]

Please specify what version(s) of SharePoint you are targeting: [N/A]

### Expected / Desired Behavior / Question

Analytics endpoint in graph has changed and needs to be adjusted. Current implementation is broken.

**Comment by patrick-rodgers** [comment]
@juliemturner - did you fix it yet?

**Comment by juliemturner** [comment]
Based on changes to the endpoint it makes sense to make analytics it's own module since it works against not only drive items but list items and sites. For some reason drive analytics were removed. We'll leave v3 drive items analytics as it is, remove drive root analytics (which is broken) in v3, and look to make these updates fully in v4.
