### ISSUE TITLE
Handling of HTTP 4xx responses in SP Batches

### ISSUE THREAD

**Issue by nikolaiessel** [pnp/pnpjs#2679]
### Category
- [x] Question

### Version
Please specify what version of the library you are using: 3.15.0
Please specify what version(s) of SharePoint you are targeting: SPO

### Expected / Desired Behavior / Question
I actually save all Promises I added to a batch into an additional array, to ensure server errors are thrown. Something like this
```TypeScript
const [batch, execute] = sp.web.batched();
const promises = values.map(v=> batch.lists.getById(listId).items.getById(v.id).update(v)));
await execute();
await Promise.all(promises); // <-- HTTP 4xx inside batch will be thrown here
```

Are there any issues preventing that `execute` can throw an exception in case of HTTP 4xx?

In [sp/batching.ts](https://github.com/pnp/pnpjs/blob/5a867ddd19d0360ad6f433220f96241cc2635c8b/packages/sp/batching.ts#L256) the responses are iterated and `resolve`/`reject` are executed. If I don´t missed something, `resolve` is a simple promise resolver, which never will fail: couldn´t be there a check and reject call if the response contain HTTP 4xx?

Sidenote: 
```TypeScript
                // this small delay allows the promises to resolve correctly in order by dropping this resolve behind
                // the other work in the event loop. Feels hacky, but it works so 🤷
                setTimeout(res, 0);
```
setTimeout queues int macrotasks, promises into microtasks, thats why the setTimeout ensures all promises will be executed first: https://javascript.info/event-loop

**Comment by bcameron1231** [comment]
Hi, 
   Are you asking that we would reject the entire execute promise if one of the items in the batch fails? This is not something we want to do. Just like the SharePoint batch call itself, it will resolve the request (if the request is valid), even if specific items in the batch would fail, as there may be some items that were 200 OK. 
   
There is no need for your Promise.All as the Execute() already does the resolving of all the batch calls themselves (similar to Promise.All) for you.
  
 You can just grab the responses of the requests after the execute completes.
![image](https://github.com/pnp/pnpjs/assets/7944457/3a549bc6-6888-4aa0-9ccf-0e2dd1272219)


Please let me know if I'm misunderstanding your question.

**Comment by nikolaiessel** [comment]
No, you are absolutely correct. Thank you.

I wasn´t sure if this was intended: In all my scenarios a HTTP 4xx was something that is not fixable in the current process, so all doings must be stopped - regardless if any HTTP 200 were in the batch. As I wrapped all my previous single requests into batches, I didn´t noticed that now no errors had be thrown :D

The `await Promise.all(promises);` is the workaround to get the single-request behavior back - there is not a single batch but a dozend that are executed when the user creates/edits a "entity".
