### ISSUE TITLE
SPFx 1.16 load WebPart error r.default.acequire is not a function

### ISSUE THREAD

**Issue by Wagnerah** [pnp/pnpjs#2683]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

Please specify what version of the library you are using: [    1.16     ]

Please specify what version(s) of SharePoint you are targeting: [    SP Online    ]

I developed a WebPart using SPFx Framework 1.16 with no problems, but, when I add this WebPart with other custom WebParts in the same page, the others WebParts not loading with an error saying: 

-WebPartZone.LoadWebPart  r.default.acequire is not a function:

![image](https://github.com/pnp/pnpjs/assets/48843844/88cc4a0a-3763-4640-88e3-dc9457b22320)

Thanks in advance

**Comment by juliemturner** [comment]
I think that you've posted this issue to the wrong repository. Based on the information you shared I think you're looking for support with an issue with the SharePoint Framework version 1.16? If that's the case, you need to submit your issue to [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues) repository.

**Comment by Wagnerah** [comment]
Thank you @juliemturner :)
