### ISSUE TITLE
Unable to create Multiple Choice (Checkbox) column using pnp/sp

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2685]
I have created SharePoint Framework solution for custom development in SharePoint online.

I am using below versions of pnp
```
    "@pnp/logging": "^3.13.0",
    "@pnp/sp": "^3.13.0",
```

I have created dynamic lists while app add first time in the SharePoint page.

All columns are created successfully but Multiple Choice (Checkbox) column is not created.

Please refer to the below for my code snippet,

```
                 await sp.web.lists.getByTitle(listName).fields.addMultiChoice("Counseling", {
                    Choices: ["All Employees",
                        "Crew",
                        "Craft Specific",
                        "Employee", ,
                        "Foreman",
                        "General Foreman",
                        "Supervisor"
                    ], EditFormat: ChoiceFieldFormatType.Dropdown, FillInChoice: false
                });
                await sp.web.lists.getByTitle(listName).defaultView.fields.add("Counseling");
```

Can anyone help me with the same?

Thanks

**Comment by juliemturner** [comment]
Could you please share the details of any errors in the console or thrown?

**Comment by bcameron1231** [comment]
There is a couple issues with your request. 

1. You have a null value between Employee and Foreman.
2.  You can't set EditFormat on a multichoice field, it's not part of the [properties](https://learn.microsoft.com/en-us/previous-versions/office/sharepoint-visio/jj244791(v=office.15)) 

I realize looking through out docs, that we have samples showing this. We will fix that to be correct. 

Your request should look like this.

```
await sp.web.lists.getByTitle("Price").fields.addMultiChoice("Counseling", {
                    Choices: ["All Employees",
                        "Crew",
                        "Craft Specific",
                        "Employee",
                        "Foreman",
                        "General Foreman",
                        "Supervisor"
                    ], FillInChoice: false
                });
```

**Comment by bhoomesh-spe** [comment]
HI @bcameron1231 

Thanks  for the response and update the documentation.
