### ISSUE TITLE
Getting multiple sites in one request

### ISSUE THREAD

**Issue by hamedy** [pnp/pnpjs#2691]
Hi, 

I can't figure out how to get a bunch of sites by url in a batch request. 

I have an array of SP site URLs and want to get the site objects with the typical site properties. 
example list of sites (Teams and communication sites):

x.sharepoint.com/sites/a
x.sharepoint.com/sites/b
x.sharepoint.com/sites/c
x.sharepoint.com/sites/d
x.sharepoint.com/sites/e

Is it possible? appreciate your help :)
Hamed

### Category

- [x] Question

### Version

Please specify what version of the library you are using: [latest]

Please specify what version(s) of SharePoint you are targeting: [online]

**Comment by patrick-rodgers** [comment]
The best way would likely be through Graph, you can review the scan guidance which has some pointers for operating across lots of sites.

PnPjs is constructed such that each fluent instance (concrete spfi) represents a single site. If you wanted to do multiple sites you'd need to already know the urls.

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
