### ISSUE TITLE
Basic Authentication for SP2022 subscription edition

### ISSUE THREAD

**Issue by bamustafa** [pnp/pnpjs#2692]
Dear all,

I hope this email finds you well. I am currently working on utilizing the "@pnp/sp" package, specifically version 3.15.0, in conjunction with Node.js version 17. My objective is to authenticate SharePoint on-premise 2022 subscription edition using basic authentication. However, despite my efforts, I have been unable to make progress in this regard.

I would greatly appreciate any advice or guidance you can provide on this matter as the documentation doesn't help me much honestly.

Thank you in advance for your assistance.

Best regards,
Bilal Mustafa

**Comment by patrick-rodgers** [comment]
If by basic authentication you mean user/pass we don't support that in the library. [There is a package](https://www.npmjs.com/package/node-sp-auth), not built by us, but very good you can review and use - except I am not sure if it support 3.x. If it doesn't work with v3 you can possible take some of the code from it and craft a solution.

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
