### ISSUE TITLE
V3.15 and batching

### ISSUE THREAD

**Issue by jeanfgagnon** [pnp/pnpjs#2696]
I have problem with batching.  It freeze litterally.  I tried to install 3.15  and it's even worst as it kills my web-parts.  Problem persist even when I revert to 3.11.

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.15        ]

Please specify what version(s) of SharePoint you are targeting: [ SPO         ]

### Observed Behavior
![image](https://github.com/pnp/pnpjs/assets/2169469/88435b67-9bca-4643-a888-ce2433fe16ad)

**Comment by Vertamin** [comment]
Make sure you or importing the @pnp/sp module correctly. I was using another syntax and it was giving me the same error until I changed it to this.

`
import { spfi, SPFI, SPFx } from "@pnp/sp";
`

**Comment by jeanfgagnon** [comment]
Hi this is from documentation and I already did the same import order. 
Thx
Sent from Yahoo Mail on Android 
 
  On Mon., 29 May 2023 at 5:23, ***@***.***> wrote:   


Make sure you or importing the @pnp/sp module correctly. I was using another syntax and it was giving me the same error until I changed it to this.

import { spfi, SPFI, SPFx } from ***@***.***/sp";

**Comment by jeanfgagnon** [comment]
I've found the problem.  
import '@pnp/sp/site-users/web'; was not included at the right place.  Moving it to init file fixed the issue.
