### ISSUE TITLE
Batching for fileFromAbsolutePath not working

### ISSUE THREAD

**Issue by samrutur** [pnp/pnpjs#2698]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [ X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  3.13.0       ]

Please specify what version(s) of SharePoint you are targeting: [  SharePoint Online       ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.* fileFromPath when used with files from different site collections in the same tenant the batch operation doesn't work. 

### Steps to Reproduce

```
    const [batchedSP, execute] = await this.sp.batched();
    fileFromPath(batchedSP.web, 'document url').then( r=>  {
           
	array.push(r);
          
        });
```

The code never hits array.push and keeps waiting. Is this the correct method to use or is batching not supported?

**Comment by samrutur** [comment]
Thank you. Its helpful to know batching is not suported for across site collections. Here is the code:
	    const [batchedSP, execute] = await this.sp.batched();
    fileFromPath(batchedSP.web, 'document url').then( r=>  {          
	array.push(r);          
        });
     await execute();     
    
      for(let i=0; i<array.length; i++)
{
//This can also be batched
      const newItem = await array[i].getItem("Modified","File_x0020_Type").select("Modified","File_x0020_Type")();
    }

**Comment by bcameron1231** [comment]
I did some testing, this is indeed a bug. We'll take a look at addressing this for the next release.

**Comment by JarialAnkur** [comment]
I am also facing the same issue.

**Comment by patrick-rodgers** [comment]
Just out of curiosity what led you to use this method? Batching across site collection won't work as mentioned above - so just starting with the spfi instance pointing to the right site collection and using sp.web.getFileByServerRelativePath should work correctly in a batch. Is that an option for you?

**Comment by samrutur** [comment]
We have a list of links to documents in various site collections on the SharePoint Online tenant. These links could be sharing links.  Since there could be multiple links , to optimize performance we would like to batch requests to get metadata information on these documents. fileFromPath works if we send a link that is not in the current site, so that is great but batching is the issue here. I guess if we have to use batching the option is to create a batch request with all links within one site a time.

**Comment by patrick-rodgers** [comment]
ah - in that case you might be best served by [encoding them all into sharing links](https://learn.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http#encoding-sharing-urls) and hitting the [/shares](https://learn.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http#http-request) graph endpoint. That should work across the tenant and give you back the details on the file.

Your request would end up something like /shares/{share id}/driveitem

**Comment by patrick-rodgers** [comment]
Had a look at this and marking it by-design. What is happening is that we ignore batching within the `fileFromAbsolutePath` as it is used internally by a lot of things, so passing in the batched web has no effect. The code hits `fileFromPath` call, ends up at an await, goes back to the event loop and hits execute(), which will have zero requests inside the batch so returns.

For the scenario described using fileFromPath isn't the best approach. I am going to add a `shares` module to the graph library this morning as I just noted we don't have one.

**Comment by JarialAnkur** [comment]
So, in short, you are saying we cannot batch file or folder operation SharePoint APIs.  I need to batch multiple APIs for creating moving files.

**Comment by patrick-rodgers** [comment]
> So, in short, you are saying we cannot batch file or folder operation SharePoint APIs. I need to batch multiple APIs for creating moving files.

No, I am not saying that. I am saying using fileFromPath method in the way it was outlined above will not work, and it isn't a good choice to make it work because the scenario doesn't support it.

Depending on the operation you want to do there are ways to batch most file operations other than uploads and some reads. Have you tried batching file moves?
