### ISSUE TITLE
[Error]: Cannot access '_Web' before initialization

### ISSUE THREAD

**Issue by tor-axbit** [pnp/pnpjs#2699]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    3.15     ]

Please specify what version(s) of SharePoint you are targeting: [    1.16.1     ]

### Background
I have a solution with two web parts. One of them is successfully upgraded from SPFx 1.10 to 1.16, including PnPJs from version 2 to v3. Now I am upgrading the other web part in the same manner, refactoring the relevant PnP callsites. 

Unfortnuately, I can't disclose reproducible samples, since all code is proprietary. I can only provide generalized snippets, sorry.

In the solution, I use PnP project preset file which the web parts share:

```
import { WebPartContext } from "@microsoft/sp-webpart-base";

// import pnp and pnp logging system
import { spfi, SPFI, SPFx } from "@pnp/sp";
import { graphfi, GraphFI, SPFx as gSPFx } from "@pnp/graph";
import { LogLevel, PnPLogging } from "@pnp/logging";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/batching";
import "@pnp/sp/site-users/web";
import "@pnp/sp/items/get-all";
import "@pnp/sp/files";
import "@pnp/sp/sputilities";
import "@pnp/graph/users";
import "@pnp/graph/photos";

// eslint-disable-next-line no-var
var _sp: SPFI = null;
var _graph: GraphFI = null;

export const getSP = (context?: WebPartContext): SPFI => {
    if (!!context) { // eslint-disable-line eqeqeq
        //You must add the @pnp/logging package to include the 
        // PnPLogging behavior it is no longer a peer dependency
        // The LogLevel set's at what level a message will be written to the console
        // console.log("context from getSP", context)
        _sp = spfi("https://axessgroup.sharepoint.com/sites/quote")
            .using(SPFx(context))
            .using(PnPLogging(LogLevel.Warning));
    }
    return _sp;
};
```
which is initialized in the web part like this:

```
import { getSP } from "./pnpjsconfig";
....

protected async onInit(): Promise<void> {
  await super.onInit();

  getSP(this.context)

...
}
```

Throughout the code I use PnP, for example

```
import { getSP } from "./pnpjsconfig";

const sp = getSP();
user = await sp.web.ensureUser(userName);
```

Yesterday, I also upgraded `@pnp/spfx-controls-react` from version 3.13 to version 3.14, in a debugging attempt on the PeoplePicker component. The whole web part worked normally, until I started commenting out some of the components in the web part. Those components are now commented in, as they were.

### Observed Behavior
In local workbench, the web part is not loaded, instead:
```
ERROR:
Cannot access '_Web' before initialization

CALL STACK:
ReferenceError: Cannot access '_Web' before initialization
    at Module._Web (https://localhost:4321/dist/web-part.js:166615:96)
    at Module.pAcn (https://localhost:4321/dist/web-part.js:201600:44)
    at __webpack_require__ (https://localhost:4321/dist/web-part.js:20:30)
    at Module.GfGO (https://localhost:4321/dist/web-part.js:116404:70)
    at __webpack_require__ (https://localhost:4321/dist/web-part.js:20:30)
    at Module.UKGb (https://localhost:4321/dist/web-part.js:142447:87)
    at __webpack_require__ (https://localhost:4321/dist/web-part.js:20:30)
    at Module.dVsc (https://localhost:4321/dist/web-part.js:166623:67)
    at __webpack_require__ (https://localhost:4321/dist/web-part.js:20:30)
    at 0FKx (https://localhost:4321/dist/web-part.js:6281:72)
```

This is one of the code lines mentioned in call stack:
```
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "_Web", function() { return _Web; });
```

The whole web part seems broken, I can't even hit breakpoints in e.g. `onInit()` to start debugging. The behavior is the same in SPO test site, only difference is error message 
```
ERROR:
Cannot access '_' before initialization
```

I have reinstalled node modules, `gulp clean` etc. Nothing helps so far.

### Question
I wonder why this error is thrown, apparently before initializing the web part at all. Does anyone have the slightest clue towards at least a debugging direction?

**Comment by tor-axbit** [comment]
The error endures even after commenting out all `sp` package calls in the web part. The other web part in the solution works normally.

**Comment by juliemturner** [comment]
>Yesterday, I also upgraded @pnp/spfx-controls-react from version 3.13 to version 3.14, in a debugging attempt on the PeoplePicker component. 

I suspect your problem is that the @pnp/spfx-controls-react take a hard dependency on v2 of PnPjs. I personally have not had time to test it but in theory the two versions of PnPjs cannot be loaded into the same project. I think your path forward is either to revert to version 2 of PnPjs, although we are no longer making updates to it, or abandon the @pnp/spfx-controls-react components which take hard dependencies of that nature. 

My personal preference is to write my own service layer anyway, I was never a fan of controls doing their own data binding. In support of that preference I am a co-maintainer or another open-source project that is a pure components library that implements the Microsoft Fluent Design Framework called hTWOo. If you're interested, you can learn more about that [here](https://lab.n8d.studio/htwoo/)

**Comment by juliemturner** [comment]
That seems like a good idea, I will pass it on to that team!

**Comment by tor-axbit** [comment]
It turns out it was not that easy to solve the problem. I have

1. uninstalled @pnp/spfx-controls-react
2. `gulp clean`, reinstalled node modules etc.
3. deleted all files that contained @pnp/spfx-controls-react components

When trying to load the webpart, this happens (edited snippet):

```
Could not load MY-web-part in require. ReferenceError: Cannot access '_Web' before initialization
    at Module._Web (c:\Users\USER\source\repos\SharepointApp\dist\node_modules\@pnp\sp\webs\types.js:1:1)
    at Module.pAcn (c:\Users\USER\source\repos\SharepointApp\dist\packages\sp\batching.ts:41:1)
    at __webpack_require__ (c:\Users\USER\source\repos\SharepointApp\dist\webpack\bootstrap:19:1)
    at Module.GfGO (c:\Users\USER\source\repos\SharepointApp\dist\packages\sp\behaviors\request-digest.ts:1:1)
    at __webpack_require__ (c:\Users\USER\source\repos\SharepointApp\dist\webpack\bootstrap:19:1)
    at Module.UKGb (c:\Users\USER\source\repos\SharepointApp\dist\packages\sp\index.ts:1:1)
    at __webpack_require__ (c:\Users\USER\source\repos\SharepointApp\dist\webpack\bootstrap:19:1)
    at Module.dVsc (c:\Users\USER\source\repos\SharepointApp\dist\node_modules\@pnp\sp\webs\types.js:1:1)
    at __webpack_require__ (c:\Users\USER\source\repos\SharepointApp\dist\webpack\bootstrap:19:1)
    at 0FKx (https://localhost:4321/dist/MY-web-part.js:5626:72) {requireMap: {…}, 
requireModules: Array(1), requireType: 'define', stack: 'ReferenceError: 
Cannot access '_Web' before i…ost:4321/dist/MY-web-part.js:5626:72)', message: 
'Cannot access '_Web' before initialization'}
```

**Comment by juliemturner** [comment]
Ok, that issue is a new bug in 3.15 that was fixed but is not released yet, will be in 3.16. In the meantime, you can get around it by falling back to 3.14 or updating to the v3 nightly build... https://pnp.github.io/pnpjs/concepts/nightly-builds/. I'd go with the nightly build. When 3.16 drops later this month you can update to that.

**Comment by tor-axbit** [comment]
ah ok, in the mean time I actually downgraded to v3.14 and made it work. Thanks!

**Comment by bcameron1231** [comment]
Yup, as Julie said we a have fix in place. Stay tuned!

PR #2697
