### ISSUE TITLE
Question / Ideas for Unit of Work Pattern in PNPJS / Batching

### ISSUE THREAD

**Issue by mrpullen** [pnp/pnpjs#2701]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [ X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    pnp/sp     ]

Please specify what version(s) of SharePoint you are targeting: [    Online     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

###  Question
Just working through the best way to implement a Unit of Work pattern with pnp/js - I essentially want to be able to replicate an all or nothing when I am performing actions that require multiple REST API transactions. The specific use case is generating a copy of a document set - then making some updates to the metadata associated with the document set - if for example - something fails on the update - I want to clean up the document set as well. Currently just have some logic / try catch - but anyone have any good pattern of using / evaluating batch and the performing operations that we could then rollback..

**Comment by patrick-rodgers** [comment]
One challenge is that SharePoint itself doesn't support this. You could implement it yourself for specific requests, but we wouldn't have a generic way to "undo" anything someone might code, and I am not sure we'd want to try. You could check if the batch fails, check the result of each request individually, then custom-code how you'd like to clean it up.

**Comment by mrpullen** [comment]
I think in a service layer I could use what you've mentioned and create some generic "undos" - ie a CRUD around a specific ListItem / DocumentSet.

Create -> Append information enabling us to Delete the newly generated item
Update -> Capture previous state - append data - enabling us to process through and restore - or recover version.
Delete -> Capture the recyclebin id - enabling us to restore the item from the recycle bin.

But thanks - I think you've pointed me in the right direction on this.
