### ISSUE TITLE
Setting section background color?

### ISSUE THREAD

**Issue by PowellT** [pnp/pnpjs#2702]
### Category
- [ ] Enhancement
- [ ] Bug
- [X ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.12  ]

Please specify what version(s) of SharePoint you are targeting: [     Online    ]

### Expected / Desired Behavior / Question
Can I set the background color (background shading) of a vertical section with pnpjs,
I could not find a way to do this in the docs etc.

**Comment by juliemturner** [comment]
Probably... but it would be a matter of reverse engineering how it's done with the first party and then implementing that when building the page sections. Unless there's a new property needed on the 1st party api's that we don't currently expose then it should be doable. 

As a reminder: [Advanced information about Client-Side Pages](https://pnp.github.io/pnpjs/concepts/adv-clientside-pages/)

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
