### ISSUE TITLE
Error 403 when retrieving members on an AD Group

### ISSUE THREAD

**Issue by bhaidar** [pnp/pnpjs#2711]
> I am using the latest of all NPM packages

Hello, community,

I am using the Graph API for the first time to retrieve members on an AD Group.

The code is pretty simple:

```
const members = await getGraph().groups.getById('...').members();
```

I get a 403 Error:

```
{
   "error": {
        "code":"Authorization_RequestDenied",
        "message":"Insufficient privileges to complete the operation.",
        "innerError":{
              "date":"2023-06-09T11:06:20",
              "request-id":"3b844d7a-e7e8-4ca9-9414-4ac4ba5fafd2",
              "client-request-id":"3b844d7a-e7e8-4ca9-9414-4ac4ba5fafd2"
         }
    }
}
```

Inside the `config/package-solution.json` file, I have added the following permissions:

```
"webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "User.ReadBasic.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Group.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Directory.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "GroupMember.ReadWrite.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Group.ReadWrite.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Directory.ReadWrite.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "People.Read"
      }
    ],
```

This happens when I run the solution via `gulp serve`.

Is there any additional step I need to do to make it run locally with the `gulp serve` command? For instance, do I need to give the SP Site the above permissions via SP Admin or Graph API Admin? If yes, please do direct me to where I should go and give those permissions.

Thank you
Bill

**Comment by bcameron1231** [comment]
Hi. Yes, you need to actually grant consent for the permissions you are requesting. This is done by someone with a Tenant Admin permission. You need to deploy the solution first, then grant the permissions and then you can use the workbench.  This is outlined in the SPFx Documentation.

https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#deploy-the-solution-and-grant-permissions

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
