### ISSUE TITLE
Not able to use the NodeFetchWithRetry

### ISSUE THREAD

**Issue by Prakash-Ramasamy** [pnp/pnpjs#2712]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [V3]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

I am using the pnpjs V3. In this version I am generating the SPFi context based on the SharePoint App ID and Secret using the following code.

`import { spfi, DefaultHeaders, DefaultInit } from '@pnp/sp'
import { BearerToken, DefaultParse } from '@pnp/queryable';
import { NodeFetchWithRetry } from "@pnp/nodejs/behaviors/fetch.js";

// connect to sp
const sp = spfi(`https://${creds.tennant.name}.sharepoint.com/sites/${creds.site.name}`).using(
  BearerToken(addin_creds.data.access_token),
  DefaultHeaders(),
  DefaultInit(),
  NodeFetchWithRetry(),
  DefaultParse()
)

const w = await sp.web()`

In this code the issue is with the NodeFetchWithRetry. If I run this code I am getting the following error.
**"Module not found: Error: Can't resolve 'node:buffer' in '..\node_modules\@pnp\nodejs\node_modules\node-fetch\src' "**
If I install the buffer in the package.json then the code is not running. gulp serve stuck at webpack config step. 

For this I found the following work around.

Step 1 :  include 'node-fetch' : "^2.6.9" in the package.json
Step 2 : npm install
Step 3: Copy the node_modules from "C:\ProjectPath\node_modules\node-fetch" and paste it to "C:\ProjectPath\node_modules\@pnp\nodejs\node_modules\node-fetch". Basically we have to replace the files.

This work around will work during the development. But while configuring the build pipeline to deploy the solution using CICD then I will face the same problem. Please suggest me if there is any solution for this issue or any other work around. Thanks.

**Comment by patrick-rodgers** [comment]
Can you try importing NodeFetchWithRetry from the root of the package? It should be exported at that level:

```TS
import { NodeFetchWithRetry } from "@pnp/nodejs";
```

But, given that you are using webpack - do you intend this code to run in node, or the browser?

**Comment by Prakash-Ramasamy** [comment]
I am getting the same error even though I import the NodeFetchWithRetry from the root.

**Comment by patrick-rodgers** [comment]
Do you intend for this code to run in node, or the browser?

**Comment by Prakash-Ramasamy** [comment]
This code will run in browser via SPFx web parts

**Comment by patrick-rodgers** [comment]
Ah, then you very much don't want to node stuff here. I think you want [BrowserFetchWithRetry](https://github.com/pnp/pnpjs/blob/version-3/packages/queryable/behaviors/browser-fetch.ts#L39) which is exported from Queryable package.

```TS
import { BrowserFetchWithRetry } from "@pnp/queryable";
```

**Comment by Prakash-Ramasamy** [comment]
@patrick-rodgers Thank you, the code is working now after I have replaced with BrowserFetchWithRetry.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
