### ISSUE TITLE
How do you call a custom endpoint path

### ISSUE THREAD

**Issue by smolattack** [pnp/pnpjs#2714]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.15]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
The CanCurrentUserViewMembership API endpoint doesn't seem to be modeled so I can't make a call like this `web.siteGroups.getByName("").CanCurrentUserViewMembership()`

Is there an easier way to call any SPO endpoint than going back to `spHttpClient`?

**Comment by patrick-rodgers** [comment]
We have a [todo](#2639) for an article to cover just this scenario. @juliemturner, how close is that? Anything we can paste here to help?

**Comment by bcameron1231** [comment]
Additionally, see my comment here in a closed issue.

https://github.com/pnp/pnpjs/issues/2663#issuecomment-1557426139

**Comment by smolattack** [comment]
> Additionally, see my comment here in a closed issue.
> 
> [#2663 (comment)](https://github.com/pnp/pnpjs/issues/2663#issuecomment-1557426139)

Thanks, I'll have a look. It seems like a bit more ceremony than what you can do with graph https://github.com/pnp/pnpjs/issues/138#issuecomment-398782649

Let's say I already have an initialized SFPI object. Is there no way to just append a string to the queryable object's path (in my case, `/CanCurrentUserViewMembership`?

**Comment by patrick-rodgers** [comment]
easiest is to pass the thing you have as a base to Queryable with your new string. [Look here as an example](https://github.com/pnp/pnpjs/blob/version-3/packages/sp/items/types.ts#L100). The design of the library is to build out paths from parent paths.

**Comment by juliemturner** [comment]
This has been updated and merged in with PR #2737
