### ISSUE TITLE
Possible to configure new (Planner) Tab in Teams

### ISSUE THREAD

**Issue by liamlenholm** [pnp/pnpjs#2715]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.16]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Question
Info: I'm creating a WebPart that has a form that creates a Teams Team and a Planner Board which is connected to that Team. Right now it creates the Team along with the Board and adds a Planner Tab to the team's channel. 

This is how I add the Planner Tab

```
	const addedTab = await this._graph.teams
			.getById(teamId)
			.channels.getById(channelId)
			.tabs.add(
				"Planner",
				"https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.planner",
				<TeamsTab>{},
				
			);

```
			

Question:

Is it possible to automatically configure the Planner Tab to be linked with a planId? Because right now when I go to the Planner tab I have to press Configure and select that Planner Plan. 

I know this only takes a few seconds but would be great if its possible to do it automatic as there is a bunch of teams that get created.

Ref 
Add a new Tab https://pnp.github.io/pnpjs/graph/teams/#add-a-new-tab

**Comment by patrick-rodgers** [comment]
That last parameter is the configuration for the tab, I would assume you can set it there. I don't have all the configurations memorized - have you tried things and they haven't worked?

**Comment by liamlenholm** [comment]
> That last parameter is the configuration for the tab, I would assume you can set it there. I don't have all the configurations memorized - have you tried things and they haven't worked?
> 
> Edit, here is a search result: https://powerusers.microsoft.com/t5/Building-Flows/Creating-a-channel-tab-for-planner/td-p/774016

Hi,

Yes I tried and messed around with the configuration tab but couldn't figure out how to display the planner's tasks. Anyway, I got it working after the link you sent :)

Thank you very much!

And if anyone else comes across this in the future this is the code I used.
```
		const addedTab = await this._graph.teams
			.getById(teamId)
			.channels.getById(channelId)
			.tabs.add(
				"Planner",
				"https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.planner",
				<TeamsTab>{
					configuration: {
						entityId: planId,
						contentUrl: `https://tasks.office.com/(Tenant URL for Office)/Home/PlannerFrame?page=7&planId=${planId}`,
						removeUrl: "",
						websiteUrl: "",
					},
				}
			);
		return addedTab;
```
