### ISSUE TITLE
Update or ValidateUpdateListItem are not working with batched since @pnp/sp^3.15.0

### ISSUE THREAD

**Issue by Saintenr** [pnp/pnpjs#2716]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     3.16.0     ]

Please specify what version(s) of SharePoint you are targeting: [     Online    ]

### Expected / Desired Behavior / Question

Since version 2.15.0 update and validateUpdateListItem no longer works via the bateched function.
Version 2.14.0 is the last version where no error occurs.
The following error is issued when validateUpdateListItem is executed:

```
{
    "odata.error": {
        "code": "-1, Microsoft.Data.OData.ODataContentTypeException",
        "message": {
            "lang": "en-US",
            "value": "A supported MIME type could not be found that matches the content type of the response. None of the supported type(s) 'application/json;odata=minimalmetadata;streaming=true, application/json;odata=minimalmetadata;streaming=false, application/json;odata=minimalmetadata, application/json;odata=fullmetadata;streaming=true, application/json;odata=fullmetadata;streaming=false, application/json;odata=fullmetadata, application/json;odata=nometadata;streaming=true, application/json;odata=nometadata;streaming=false, application/json;odata=nometadata, application/json;streaming=true, application/json;streaming=false, application/json;odata=verbose, application/json' matches the content type 'multipart/mixed; boundary=batch_5a25be67-a8e2-435d-9ce9-3156dd11cf9e'."
        }
    }
}
```

### Steps to Reproduce

```
const [batchPatch, executePatch] = sp.web.batched();
const batchedList: IList = batchPatch.lists.getByTitle(‚MyList);
batchedList.items.add(obj.create).then((create) => {
create.item.validateUpdateListItem(obj.update)
}
executePatch();
```

**Comment by patrick-rodgers** [comment]
I am a bit confused, you mention 3.15 in the title, but say you are using v2? The code looks like v3 - just want to make sure we are on the same page.

**Comment by bcameron1231** [comment]
I was able to reproduce and it was introduced in 3.15.

With some of the adjustments to the timeline when we added BatchNever, the batching headers (content-type) are being copied back to the item when using CopyFrom.

**Comment by Saintenr** [comment]
> I am a bit confused, you mention 3.15 in the title, but say you are using v2? The code looks like v3 - just want to make sure we are on the same page.

hi patrick, yes im using v3, sorry

**Comment by patrick-rodgers** [comment]
Interesting that this is the first time this was found - we were adding an InjectHeaders into what was meant to be a reference query instance. Fixed it two ways, and tested. Should also fix what would likely be a bunch of other places potentially affected by this.
