### ISSUE TITLE
Batched Web is not working with moveByPath for files

### ISSUE THREAD

**Issue by JarialAnkur** [pnp/pnpjs#2717]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Bug

### Version

Please specify what version of the library you are using: [3.15.0]

Please specify what version(s) of SharePoint you are targeting: [1.15.0]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected Behavior
The files should get moved using a batch HTTP request

### Observed Behavior
The code line where I am calling the batchedWeb to send the HTTP request is not getting exexuted.
### Steps to Reproduce
```
 const [batchedWeb, execute] = sp.web.batched(); 
console.log("This is destination url = >", DestinationUrl)
        await batchedWeb.getFileByServerRelativePath(`!@p1::${FileOrFolder.ServerRelativeUrl}`).move(DestinationUrl, false, true).then((result)=>{
            console.log('This is result in move files =>',result)
            resFileMove.push(result)
        }).catch((error)=>{
            console.log('This is error in batchedWeb=>',error)
        })
    })
    await execute().then((res)=>{
        console.log('TYhis is response in batch execiute=>',res)
    }).catch((error)=>{
        console.log("This is error in batch execute=>",error)
    })
```

Here the line where I am using Batched Web to move files is not working. But the line just above that is a console is getting and after that, the code just stops executing and I cannot see any request in the network calls.

**Comment by JarialAnkur** [comment]
`const [batchedWeb, execute] = sp.web.batched();  
console.log("This is destination url = >", DestinationUrl) 
await batchedWeb.getFileByServerRelativePath(!@p1::${FileOrFolder.ServerRelativeUrl}).move(DestinationUrl, false, true)
.then((result)=>
{ 
console.log('This is result in move files =>',result) 
resFileMove.push(result) 
})
.catch((error)=>
{ 
console.log('This is error in batchedWeb=>',error)
 }) 
}) 
await execute()
.then((res)=>
{ 
console.log('TYhis is response in batch execiute=>',res)
 })
.catch((error)=>
{ 
console.log("This is error in batch execute=>",error)
})`

**Comment by JarialAnkur** [comment]
Will be giving this a try today. And will respond with my findings. Thanks for the help @bcameron1231.

**Comment by JarialAnkur** [comment]
I was able to batch the move files API but got into another issue. When I was trying to update the metradata of those files after moving them. 
`(await (batchedWebUpdate.getFileByServerRelativePath(`!@p1::${DestinationUrl}`).getItem())).update({"ContentStatus":Constants.Archive,ContentTypeId:PropsObject.portalFolderContentType}).then((result)=>{
            console.log('This is result in getItem files =>',result)
           // resFileMove.push(result)
        }).catch((error)=>{
            console.log('This is erropr in batchedWeb=>',error)
        })`

The batch is going through uptil getting item. But after that the call where I need to update the metadata, I get an error for headers.
**The HTTP header Content-Type is missing or its value is invalid.**

**Comment by juliemturner** [comment]
Unless I'm missing something you're still wrapping the batchedWebUpdate calls in an await... maybe I'm just not seeing the entire method.

**Comment by bcameron1231** [comment]
After a little review, I don't think we can directly support your implementation with the item property updates in the batch. To get the item for a File object, requires a call to SharePoint to get the item directly. So it is asynchronous, and needs the await. 

The best you'd probably get is you could move files in a batch, then get the files individually (not in a batch), you could store the items in an array, and re-process all the updates in a new batch.

**Comment by JarialAnkur** [comment]
Exactly, I understood this and I already did the same thing, and it's working perfectly. Get the items in an array and then batch-update them. Thanks for all the help @bcameron1231

**Comment by bcameron1231** [comment]
Fantastic. Thank you for letting us know!

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
