### ISSUE TITLE
Unable to get SharePoint list data which contains more than 12 lookups/people & groups columns

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2721]
Hello Everyone,

I am using Office 365 / SharePoint Online.

I have created a SharePoint list that contains 5 Lookups and 10 Person & Groups (Users) columns.

There is some limitation the SharePoint view does not load with more than 12 lookups (including people and groups) columns.

Below are the links for the same

1. [How to avoid Lookup Column Threshold limit on a view](https://sharepointmaven.com/how-to-avoid-lookup-column-threshold-limit-on-a-view/#:~:text=When%20you%20create%20lookup%20columns,column%20in%20a%20single%20view.)
2. [Lookup Limit 12](https://natechamberlain.com/2018/09/04/how-to-increase-lookup-column-limit-in-sharepoint-lists/)
 
I have created an SPFx solution with React for some development.

I need to get all column data from my Custom List and show that in the dashboard.

I have used the below versions of *pnp.sp*
```
"@pnp/logging": "^3.13.0",
"@pnp/sp": "^3.13.0",
```

Below is my code snippet,

```
import { spfi } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

const sp = spfi(...);

const items = await sp.web.lists.getByTitle("My Custom List").items.select("Title", "Lookup1/Title", "Lookup1/ID",  "Lookup2/Title", "Lookup2/ID", "Lookup3/Title", "Lookup3/ID","Lookup4/Title", "Lookup4/ID", "Lookup5/Title", "Lookup5/ID", "User1/Title", "User1/ID",  "User2/Title", "User2/ID", "User3/Title", "User3/ID","User4/Title", "User44/ID", "User5/Title", "User5/ID", "User6/Title", "User6/ID",  "User7/Title", "User7/ID", "User8/Title", "User8/ID","User9/Title", "User9/ID", "User10/Title", "User10/ID").expand("Lookup1", "Lookup2", "Lookup3", "Lookup4", "Lookup5", "User1", "User2", "User3", "User4", "User5", "User6", "User7", "User8", "User9", "User10")();
console.log("items....",items);
```

The above query does not work for me. It is not showing any results or errors.

Can anyone help me with the same?

@patrick-rodgers @juliemturner @bcameron1231 - Hope you have some solution.

Thanks

**Comment by patrick-rodgers** [comment]
Hi - I believe this affects the API calls as well. The limit is due to performance in SQL and the number of joins/queries that have to be done to surface all the data.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
