### ISSUE TITLE
Move `nodejs/sp-extensions` to `sp`

### ISSUE THREAD

**Issue by Dzieni** [pnp/pnpjs#2722]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

I've been wondering...

- we've got a [WHATWG streams API](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API) for browsers...
- ...that is [getting adopted to Node](https://nodejs.org/api/webstreams.html)...
- ...and we [already consume](https://github.com/pnp/pnpjs/commit/f6386aa0a2c6fc31ae685b43abeecd3823397245#diff-1292836cbb694f0d13d2a1512d9122e3e0e7142a24443a8e02e010156dc0a40aR42) Node streams through async iterators - the same way as WHATWG streams [can be consumed](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream#async_iteration)

So I think at this point all the contents of `sp-extensions` could be just a part of the `sp` package, right? Just a matter of typing (i.e. `setStreamContentChunked` should accept `ReadStream | ReadableStream`, etc).

Thanks to that we add new functionality for developers using the library on frontend.

It's not a huge prio, but I think it might be worth considering for v4 (CC #2678)

**Comment by juliemturner** [comment]
Unless I'm missing something, the "getting adopted to Node" is version 20. Although I see what you mean until this feature is stable in NodeJS in an LTS version I don't think we want to go there.

**Comment by patrick-rodgers** [comment]
This is done in #2953. Despite what is said in this thread, the streams implementations are sufficiently different that I needed to shim a lot. Perhaps someone with more expertise with streams across browsers and node can improve my work.
