### ISSUE TITLE
TypeError [ERR_INVALID_URL]: Invalid URL when use shareWith folder

### ISSUE THREAD

**Issue by thongbk83** [pnp/pnpjs#2726]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [/] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ ^3.16.0  ]

Please specify what version(s) of SharePoint you are targeting: [ online        ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
shareWith share folder

### Observed Behavior
Get error : 
folder upload failed: TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:560:13)
    at Proxy.<anonymous> (file:/Documents/learning/nodejs/node_modules/@pnp/sp/behaviors/telemetry.js:6:34)
    at file:Documents/learning/nodejs/node_modules/@pnp/queryable/node_modules/@pnp/core/moments.js:53:73
    at async Timeout._onTimeout (file:/Documents/learning/nodejs/node_modules/@pnp/queryable/queryable.js:103:43) {
  input: '_api/web/roledefinitions?%24select=Id&%24filter=RoleTypeKind+eq+2',
  code: 'ERR_INVALID_URL'
}

### Steps to Reproduce
1. use ClientID , Client Secret to authentication with fullControl for siteCollection 
2. create new folder :  await sp.web.folders.addUsingPath('/sites/dev/Shared Documents/Project/test1'); 
3. share permission with new folder 
await sp.web.getFolderByServerRelativePath('/sites/dev/Shared Documents/Project/test1').shareWith("i:0#.f|membership|user@example.com");

get error at step 3

**Comment by patrick-rodgers** [comment]
Was the folder in step 2 created where you think it was created?

**Comment by bcameron1231** [comment]
I can't reproduce this myself (using Node, Client ID/Cert). Agree with Patrick. Double check the folder is being created as you expect.

**Comment by thongbk83** [comment]
yes , at step 2  , the folder 'test1' is created success.
I also tried to create folder  then sharewith  that folder but still same error. 

for authentication I use Gostron's solution https://github.com/pnp/pnpjs/issues/2240#issuecomment-1183342309

What I use to import 
import { spfi } from "@pnp/sp";
import {SPAddIn, NoOdata} from './SPAddIn.js'
import "@pnp/sp/webs/index.js";
import "@pnp/sp/sharing/index.js";
import "@pnp/sp/folders/web.js";
import "@pnp/sp/files/web.js";

try {
  const folder = await sp.web.getFolderByServerRelativePath('/sites/dev/Shared Documents/Project/new4');
  const result = await sp.web.shareObject(folder, "i:0#.f|membership|nguyen.dinhquoc@vib.com.vn");
} catch (error) {
  console.error('folder share failed:',error);
}

**Comment by bcameron1231** [comment]
Thanks for the debugging! Ya looks like it fails because in node (server) the URL() needs an absolute path, or a base path parameter if relative.

https://nodejs.org/api/url.html#new-urlinput-base

Looks like it's in telemetry behavior. In the interim, if you remove the telemetry behavior from your code, I'd expect it to unblock you.

**Comment by thongbk83** [comment]
thanks @bcameron1231 
But I not sure how to remove the telemetry . 

As my understand the telemetry will split url to request parameters ?
I just try to use for test bit e 
 const { pathname } = new URL(url,'https://tenant.sharepoint.com/sites/dev'); 
but still get error 
older upload failed: TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:560:13)
    at Timeout._onTimeout (/nodejs/node_modules/@pnp/queryable/queryable.js:116:59) {
  input: '_api/web/roledefinitions?%24select=Id&%24filter=RoleTypeKind+eq+2',
  code: 'ERR_INVALID_URL'

log("Emitting auth");
    [requestUrl, init] = await this.emit.auth(new URL(url), init);
                log("Emitted auth");

**Comment by bcameron1231** [comment]
Telemetry is likely coming through the defaultInit behavior, (assuming that's what you're using based on your linked comment before).

Will take a closer look/review at this tomorrow.

**Comment by thongbk83** [comment]
Hi , 

As @bcameron1231  comment "(assuming that's what you're using based on your linked comment before)." , I changed the authentication with @patrick-rodgers  comment https://github.com/pnp/pnpjs/issues/2378 and the sharewith function work well . 

thanks guys for helping

**Comment by bcameron1231** [comment]
Glad you got it worked out. Any chance you can provide us your original initialization of your sp object? We have a suspicion that how you're setting up the sp object may be incorrect, as we try to ensure the absolute paths.

**Comment by thongbk83** [comment]
I research how to authentication and work  with sharepoint from nodejs
this is package i installed 
    "@pnp/nodejs": "^3.16.0",
    "@pnp/nodejs-commonjs": "^2.15.0",
    "@pnp/pnpjs": "^2.15.0",
    "@pnp/queryable": "^3.16.0",
    "@pnp/sp": "^3.16.0",
    "@pnp/sp-commonjs": "^2.15.0",
    "node-fetch": "^3.3.1",
    "node-sp-auth": **"^3.0.7",

First I used Gostron's solution https://github.com/pnp/pnpjs/issues/2240#issuecomment-1183342309 
but I use the js not ts 

import { DefaultHeaders, DefaultInit } from "@pnp/sp"
import { NodeFetchWithRetry } from "@pnp/nodejs"
import "@pnp/sp/presets/all.js"
import { getAuth } from "node-sp-auth"
//import { TimelinePipe } from "@pnp/core"
import { DefaultParse, InjectHeaders } from "@pnp/queryable"

// Gostron's code to js 
then I got the problem for shareobject , sharewith 
some function like upload file . add folder work well

then I change solution to @patrick-rodgers comment https://github.com/pnp/pnpjs/issues/2378 with js style then everything is OK
