### ISSUE TITLE
How to Sent Notification Email to external users with @pnp/sp/sputilities

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2728]
Hello Everyone,

I have created the SPFx solution for custom development into SharePoint.
Under the SPFX solution, I have created a custom form to add new data to the SharePoint list.
I need to send an email to that user whose email address is added by the end user.
If the end-user has added Office 365 internal user it is working as expected.
But if the end-user added the external email address or Gmail email address. It is not working as expected. 
No email was triggered under an external email address or Gmail email address.

I have used below @pnp versions,

```
 "@pnp/logging": "^3.8.0",
 "@pnp/sp": "^3.8.0",
```

Below is my code snippet,

```
import "@pnp/sp/sputilities";
import { IEmailProperties } from "@pnp/sp/sputilities";

const prepareEmailNotification = async () => {
	const emailProps: IEmailProperties = {
			To: ["johndoe@contoso.com"],
                        CC: ["janedane@gmail.com"],
                        Subject: "Data Added",
                        Body: `New data added to the SP list`,
                        AdditionalHeaders: {
                            "content-type": "text/html",
                        },
                    };
	sendEmailNotification(emailProps);
}

const sendEmailNotification = async (emailProps: IEmailProperties) => {
    const sp: SPFI = getSP();
    return sp.utility.sendEmail(emailProps).then((_) => {
        console.log("Email Sent!");
    });
};
```

Can anyone help me with the same?
@patrick-rodgers  @juliemturner  @bcameron1231  -  Hope you have some solution. :)
Thanks

**Comment by bcameron1231** [comment]
The SharePoint REST API doesn't allow this. You can only send emails to internal site users.

We don't have a method to email external users. I would use Microsoft Graph to do what you need.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
