### ISSUE TITLE
[pnp/logging] Log level not respected by console logger

### ISSUE THREAD

**Issue by heinrich-ulbricht** [pnp/pnpjs#2731]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: **`@pnp/logging` v3.16.0**

Please specify what version(s) of SharePoint you are targeting: **SharePoint Online**

### Expected / Desired Behavior / Question

When logging with Verbose level using the console logger I expect the log entries to appear as verbose in the browser console, so that they can be toggled on and off independently of other levels (Verbose seems to be hidden by default in Chrome/Edge, which is what I want).

### Observed Behavior

Log messages with level Info and Verbose seem to have the same level in the browser console.

Looking at the code it seems `console.log` is used and nothing else:

https://github.com/pnp/pnpjs/blob/3692937d57c6e4276c399b3467c4a6745698d00a/packages/logging/listeners.ts#L28-L34

Which is strange, since the [documentation](https://pnp.github.io/pnpjs/logging/#consolelistener) says `console.warn` is used as well. Or am I looking at the wrong code? I'd also expect [`console.debug`](https://developer.mozilla.org/en-US/docs/Web/API/console/debug) to be around.

### Steps to Reproduce

I basically followed the steps in https://pnp.github.io/pnpjs/logging/ to get a simple console logging going.

**Comment by patrick-rodgers** [comment]
Those levels are meant to correspond to the level of information the library will output when in logging mode - not necessarily the console.* method called. That said we could look at updating the logger to work how you want, though not a high priority - perhaps you can submit a PR if its something you need immediately?

**Comment by heinrich-ulbricht** [comment]
Thanks, that's good to know. Not the highest on the TODO list here, either 😅

**Comment by patrick-rodgers** [comment]
As a short cut you can always make your own [function listener](https://pnp.github.io/pnpjs/logging/#functionlistener) that calls whatever method.
