### ISSUE TITLE
Unable to create/update Multiple Choice (Checkbox) column data using pnp/sp

### ISSUE THREAD

**Issue by mahendran89** [pnp/pnpjs#2732]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Version: [PnPjs v3]

Version of SharePoint: [SharePoint Online]

### Expected / Desired Behavior / Question

When using PnPjs v3, I expect to be able to create a new list item with a multi-choice field by supplying an object with the `results` property containing an array of selected choice values. This works in older version PnPjs

### Observed Behavior

When attempting to create a new list item with a multi-choice field, I get the following error:
{
"odata.error": {
"code": "-1, Microsoft.SharePoint.Client.InvalidClientQueryException",
"message": {
"lang": "en-US",
"value": "An unexpected 'StartObject' node was found when reading from the JSON reader. A 'StartArray' node was expected."
}
}
}

This error prevents me from successfully creating a new list item with a multi-choice field using PnPjs v3.

### Steps to Reproduce

1. Create a SharePoint list with a multi-choice field.
2. Use the following code to create a new list item with a multi-choice field using PnPjs v3:

```
async function createItemWithMultiChoiceField(listTitle) {
  try {
    const selectedValues = { results: ['Choice #2', 'Choice #3'] };

    await sp.web.lists.getByTitle(listTitle).items.add({
      Title: 'New item',
      MultiChoiceField: selectedValues,
    });

    console.log('Item created successfully');
  } catch (error) {
    console.error('Error creating item:', error);
  }
}
```

I have referred [PnPjs documentation](https://pnp.github.io/pnpjs/sp/items) but dont find case for this scenario. Can anyone please help me on this?

**Comment by patrick-rodgers** [comment]
I believe you can just send the array vs the object with a results property. We are no longer using verbose json by default so the results shouldn't be needed anymore.

**Comment by mahendran89** [comment]
Worked! 

async function createItemWithMultiChoiceField(listTitle) {
  try {
    const selectedValues = ['Choice #2', 'Choice #3']

    await sp.web.lists.getByTitle(listTitle).items.add({
      Title: 'New item',
      MultiChoiceField: selectedValues,
    });

    console.log('Item created successfully');
  } catch (error) {
    console.error('Error creating item:', error);
  }
}
