### ISSUE TITLE
How to migrate Bearer Token Auth v2 -> v3

### ISSUE THREAD

**Issue by mplwork** [pnp/pnpjs#2733]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.16.0 ]
nodejs: v16.12.1

I am trying to migrate a v2 solution to v3 but can't figure out how to connect to SP. 
I have a **site url** and a **bearer token**, how do I use this to get a working sp connection I can do stuff with like `sp.web.lists.getByTitle("listname")`?

My old code is something like

```
const { BearerTokenFetchClient} = require("@pnp/nodejs-commonjs");
const { sp, PrincipalType, PrincipalSource } = require("@pnp/sp-commonjs/presets/all");

class SpClient {
    constructor(token, sharepoint) {
        const {SharePoint: tenant} = process.env;

        const site = sharepoint.site;
        this.spList = sharepoint.spList;

        sp.setup({
            sp: {
                fetchClientFactory: () => {
                    return new BearerTokenFetchClient(token);
                },
                baseUrl: `https://${tenant}/sites/${site}`
            }
        });

        this.spClient = sp;
    }
```

Anything I try just doesn't work. One attempt:

```
import { SPDefault, NodeFetchWithRetry } from "@pnp/nodejs";
import { BearerToken, DefaultParse } from "@pnp/queryable";
import { spfi, DefaultHeaders, DefaultInit, PrincipalType, PrincipalSource } from "@pnp/sp";

class SpClient {
    constructor(token, sharepoint) {
        const {SharePoint: tenant} = process.env;

        const site = sharepoint.site;
        this.spList = sharepoint.spList;
        this.templateList = sharepoint.templateList;


        this.baseUrl = `https://${tenant}/sites/${site}`;
        const sp = spfi(this.baseUrl)
            .using(
                BearerToken(token),
                DefaultHeaders(),
                DefaultInit(),
                NodeFetchWithRetry(),
                DefaultParse()
            );

// whatever I try here sp turns out `undefined`  or `sp.web()` is not a function....
        this.spClient = sp;

    }
```

**Comment by patrick-rodgers** [comment]
Your second example looks right except you still need to do the selective imports, so if you want to call `sp.web()` you need `import "@pnp/sp/webs";`

**Comment by mplwork** [comment]
Thanks for the very fast reply. The import helps - `await sp.web()` returns something useful now -  but I am still missing something. How do I get this to work, I haven't understood those imports it seems.

`return await this.spClient.web.currentUser();`

**Comment by mplwork** [comment]
Never mind, I figured it out. I had to import

```
import "@pnp/sp/webs/index.js";
import "@pnp/sp/site-users/index.js";
```

and then 
```
await this.spClient.web.currentUser();
```
got me what I wanted. Seems like I am on track now.

Is there a way to get rid of the `/index.js` in the imports?
