### ISSUE TITLE
sp.utility.sendEmail is not working.

### ISSUE THREAD

**Issue by meet2sujit** [pnp/pnpjs#2735]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

 

 

### Version

 

 

Please specify what version of the library you are using: [3.8]

 

 

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online]

 

 

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*
SP UTLIITY
### Expected / Desired Behavior / Question
Send email to specific recipient with all the details using sp.utility.sendEmail function of pnp/js.
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

 

 

### Observed Behavior
Getting an error while sending an email to the specified user using pnp js.Following are the error details:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sendEmail')
    at dataService.<anonymous> (DataService.ts:530:26)
    at new Promise (<anonymous>)
    at NE46.__awaiter (gi-review-web-part.js:96396:12)
    at NE46.dataService.SendEmail (DataService.ts:521:72)

 

*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

 

 

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

 

 

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

 

 

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
Can you share your code?

**Comment by meet2sujit** [comment]
It started working. Forgot to import import "@pnp/sp/sputilities";.

Thanks for quick response.
