### ISSUE TITLE
getblob() response empty

### ISSUE THREAD

**Issue by klindal73** [pnp/pnpjs#2740]
### Category
- [x] Question

### Version

Please specify what version of the library you are using: [  3.16.0       ]

Please specify what version(s) of SharePoint you are targeting: [  SPFX 1.16.1      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Question
Hi. I hope that this is ok to aske hear.
I’m trying to get a blob from a file, but it is coming up empty and without error. If I just query for the blob size I get the size of the blob.
Please tell me what I’m doing wrong hear??
 private DownloadAttacFile(fileUrl:string){   
  const sp = spfi("https://tenent.sharepoint.com/sites/"sitecollection").using(SPFx(this.props.context));   
   sp.web.getFileByUrl(fileUrl).getBlob().then((blob:Blob) =>{
     this.setState({blobs:[blob]});
   }).catch((error:any) =>{
    alert(error);
   });
     
  }

Thanks for any response.

**Comment by juliemturner** [comment]
Ok, but when you say "empty" are you sure? did you inspect it? What are you trying to do with it afterwards... for example: https://developer.mozilla.org/en-US/docs/Web/API/Blob#extracting_data_from_a_blob

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
