### ISSUE TITLE
How to update site properties?

### ISSUE THREAD

**Issue by mplwork** [pnp/pnpjs#2741]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     3    ]

I've managed to get site properties like so:
```
import "@pnp/sp/presets/all.js";
import { NodeFetchWithRetry } from "@pnp/nodejs";
import { BearerToken, DefaultParse } from "@pnp/queryable";
import { spfi, DefaultHeaders, DefaultInit, PrincipalType, PrincipalSource } from "@pnp/sp";
import "@pnp/sp-admin";

       const tenant=`oursite-admin.sharepoint.com`;

       const sp = spfi(`https://${tenant}`)
            .using(
                BearerToken(token),
                DefaultHeaders(),
                DefaultInit(),
                NodeFetchWithRetry(),
                DefaultParse()
            );


        const props = await this.spClient.admin.tenant.getSitePropertiesByUrl(`https://oursite.sharepoint.com/sites/siteName`);
        props.StorageMaximumLevel = 42; // or whatever

       // now how to write back?
```
Now I want to change them (`StorageMaximumLevel` and `StorageWarningLevel`) but I can't find any methods to do so. Would it be possible with PnPJS? Or is there another to achieve what I want (increase site Storage)?

**Comment by bcameron1231** [comment]
Hi! Not all methods are exposed via PnPjs, we expose the "call" method to allow you to execute any endpoint that doesn't exist. Please see documentation https://pnp.github.io/pnpjs/sp-admin/#call

Haven't tested, but you should be able to do...

```
    await sp.admin.tenant.call("Sites(<siteId>)",{
          StorageMaximumLevel:42
      });
```

**Comment by mplwork** [comment]
Wow, thank you so much, this is a very good start. But I am not quite there:

```
       await this.spClient.admin.tenant.call(`Sites('${site.Id}')`, {
            StorageMaximumLevel: '42'
        });
```
results in
```
odata.error
  code=-1, Microsoft.SharePoint.Client.InvalidClientQueryException
  message
    lang=en-US
    value=The parameter StorageMaximumLevel does not exist in method GetById.
```

I have an allegedly working powerautomate version which looks very similar but adds a header `X-HTTP-Method:  MERGE`. Could that be the reason? And if so how to add the header to the pnpjs call.

**Comment by bcameron1231** [comment]
Ah yea... that could be it. It's likely doing POST. 

Can you use the InjectHeaders() behavior to pass in the X-HTTP-Method header you need.

**Comment by mplwork** [comment]
Thanks again. This seems to be doing it:
```
  await this.spClient.using(InjectHeaders({
            'X-HTTP-Method': 'MERGE'
        })).admin.tenant.call(`Sites('${site.Id}')`, {
            StorageMaximumLevel: '42'
        });
```
It now complains about the silly numbers but that's ok. 
This gets me going, thanks a lot.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
