### ISSUE TITLE
IClientsidePage.getItem() - Can't access any values in spfx solution

### ISSUE THREAD

**Issue by sw00sh0r** [pnp/pnpjs#2745]
Hi all,

I use PnPJS 3.16 in my spfx webpart solution with typescript and unfortunately I am not able to get the value of any of the listitem`s fields (e.g. id, title, description etc.).
The webpart was generated by yeoman generator.

Example code:

```typescript
import { WebPartContext } from "@microsoft/sp-webpart-base";
import { SPFI, SPFx, spfi } from "@pnp/sp";
import { IClientsidePage } from "@pnp/sp/clientside-pages/types";
import "@pnp/sp/clientside-pages/web";
import "@pnp/sp/items";
import "@pnp/sp/lists";
import "@pnp/sp/webs";
import { Web } from "@pnp/sp/webs";
import { SpPageData } from "../types/SpPageData";

export class NewsService {
  private sp: SPFI;

  constructor(context: WebPartContext) {
    this.sp = spfi().using(SPFx(context));
  }

  private async getClientSidePage(
    absoluteWebUrl: string,
    siteRelativeNewsUrl: string
  ): Promise<IClientsidePage | undefined> {
    try {
      const page = await Web([this.sp.web, absoluteWebUrl]).loadClientsidePage(
        siteRelativeNewsUrl
      );
      return page;
    } catch (ex) {
      console.error(ex);
    }
    return undefined;
  }

  public async getListItemByUrl(
    absoluteWebUrl: string,
    siteRelativeNewsUrl: string
  ): Promise<SpPageData | undefined> {
    let spPageData: SpPageData = undefined;
    try {
      const page = await this.getClientSidePage(
        absoluteWebUrl,
        siteRelativeNewsUrl
      );      
      if (page !== undefined) {
        const listitem = await page?.getItem();
        spPageData = { clientSidePage: page, listItem: listitem };
      }
    } catch (ex) {
      console.error(ex);
    }
    return spPageData;
  }
}
```

As per your documentation and issues I read here, I should be able to access the items title value by:

```typescript
console.log(listitem.title)
```

In my VS Code solution, I can't select this or any other values:

![image](https://github.com/pnp/pnpjs/assets/68747426/bdff8bd0-a719-4560-b84b-66e58452ce62)

In the browser´s console I receive the proxy object and the selection of the title`s value works just fine:

![image](https://github.com/pnp/pnpjs/assets/68747426/cba58e99-5e16-4edd-902d-e6052da28aea)

What am I doing wrong?

In addition, here is my package.json:

![image](https://github.com/pnp/pnpjs/assets/68747426/c760b673-fdc1-49e9-9e4e-8d8dbe02cda6)

**Comment by bcameron1231** [comment]
Hi! First of all, THANK YOU for such a clear & concise issue submission. :) 

Second, yea, so IItem objects don't contain this information. In order to get proper intelligence in VSCode, you should use a generic typing parameter.

```
const listitem = await page.getItem<{ Title: string, Description:string }>("Title","Description");
console.log(listitem.Title);
console.log(listitem.Description);
```

**Comment by sw00sh0r** [comment]
Thank you very much, you saved my weekend.
Works like a charm!
