### ISSUE TITLE
Projected fields have stopped working on the SharePoint Stream API

### ISSUE THREAD

**Issue by marcus-atvero** [pnp/pnpjs#2746]
### Category
- [ ] Enhancement
- [X] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version(s) of SharePoint you are targeting: [   Online      ]

We use the SharePoint Stream API and write CAML queries to project fields from joined tables.  These queries have run successfully for years.

These projections stopped working on Thursday on our dev tenancies, and has started impacting customer tenancies today.

Was there a published / expected change to this API that we missed, or is this a regression?

Example CAML code below.

```
   <Joins>
        <Join Type='LEFT' ListAlias='Company'>
          <Eq>
            <FieldRef Name='ATVCompanyLookup' RefType='Id'/>
            <FieldRef List='Company' Name='ID'/>
          </Eq>
        </Join>
      </Joins>
      <ProjectedFields>
        <Field Name='ATVCompanyLookup_ID'
          Type='Lookup'
          List='Company'
          ShowField='ID'/>
        <Field Name='ATVCompanyLookup_ATVCompanyCode'
          Type='Lookup'
          List='Company'
          ShowField='ATVCompanyCode'/>

      </ProjectedFields>
```

**Comment by bcameron1231** [comment]
Hi. Have you tested this without using PnPjs? We're just a passthrough to the APIs, so if it's a regression on the API side, there isn't much we can do and I'd recommend submitting an issue this repo https://github.com/SharePoint/sp-dev-docs.

**Comment by marcus-atvero** [comment]
Thank you, I agree, it's most likely an API issue, so I've submitted it on the repo as suggested and I'll close this issue.
