### ISSUE TITLE
How to check the id is user id or group id in SPFx using pnp/sp?

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2752]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.15.0

### Target environment

SharePoint Framework

### Additional environment details

SPFx with React SharePoint Online

### Question/Request

Hello Everyone,

I have created an SPFx solution for custom development.

I have created one People & Groups column (which contains People & Groups) in the SharePoint list.

I have added some entries. Some of the entries contain users and some of the entries contain groups under the People & Groups column. 

I have fetched the all item data of that list and I found the id from the People & Groups column.

Now, I need to check if the id is the user id or the group id.

Can anyone help me with the same?

@patrick-rodgers @juliemturner @AJIXuMuK @bcameron1231 - Hope you have some solution.

Thanks

**Comment by bcameron1231** [comment]
Not sure off-hand, but a simple way would like be just to query the SiteGroups for the ID and see if it resolves or not. If it does, it's a group. 

Alternatively, you could use the resolvePrincipal functionality and use the email value to check the principal type.
https://pnp.github.io/pnpjs/v1/sp/docs/sp-utilities-utility/#resolveprincipal

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
