### ISSUE TITLE
Other Locales in Navigation

### ISSUE THREAD

**Issue by tukutela** [pnp/pnpjs#2758]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.16.0

### Target environment

NodeJS

### Additional environment details

Authentication is OK, accessing no problem. Using NodeJS to interact with Sharepoint Online. 

### Question/Request

Hi, 

I was wondering if someone has any examples of updating other Translations in the Navigation bar?

<img width="321" alt="image" src="https://github.com/pnp/pnpjs/assets/340768/a0db1d02-fc25-4a10-bcc4-0688b6e47283">

Any help greatly appreciated!

**Comment by bcameron1231** [comment]
Hi, unfortunately we currently don't support Translations as part of our Navigation package. 

However, the only way I know how to do it is by using the /SaveMenuState API, and passing in the Translations as part of the nodes you want to update. 

To do this with PnPjs currently, you would need to call the SaveMenuState endpoint and passing over the MenuState which includes the translations. Check out this documentation on how to call other endpoints. https://pnp.github.io/pnpjs/concepts/calling-other-endpoints/


Here is some sample code that gets the current menu state, updates the translation for node 6
```
import { SPFI, SPFx, SPQueryable, spPost, spfi } from '@pnp/sp';
import { body, InjectHeaders } from "@pnp/queryable";

const existingMenuState:any = await this.sp.navigation.getMenuState();

      // update the node you want with the Translations, include LCID and the string
      // this would be the 6 node in my menu. You can obviously update accordingly.
      existingMenuState.Nodes[6]["Translations"] = [{"LCID":1033,"Value":"Test2"},{"LCID":1036,"Value":"ParleFrancais4"}];

      // need to remove this property that came back from getMenuState() call.
      delete existingMenuState["odata.metadata"];

      // create an POST call, extending the navigation queryable with the /SaveMenuSate API.
      //pass over the augmented menustate.
      await spPost(SPQueryable(this.sp.navigation,"/SaveMenuState"), body(
        {menuState:
         existingMenuState
      }));
```

**Comment by tukutela** [comment]
Oh, thankyou! Will have to give that a go.

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
