### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'web') with getCurrentUserEffectivePermissions();

### ISSUE THREAD

**Issue by adam13hylo** [pnp/pnpjs#2760]
### Major Version

3.x

### Minor Version Number

^3.14.0

### Target environment

SharePoint Framework

### Additional environment details

I am using Node.js v14.15.0 with SPFx version 1.16.1

### Expected or Desired Behavior

When trying to get the current users effective base permissions I would expect to get returned the users effective high and low role assignments:

> High: "2147483647"
> Low: "4294705151"

### Observed Behavior

When trying to get the current users effective base permissions on a list I am getting the error: 

> TypeError: Cannot read properties of undefined (reading 'web')

This error goes away when I refresh the page, however, if I navigate away from the page hosting the web part to another page and then navigate back this error then returns.

https://github.com/pnp/pnpjs/assets/4320762/e8fda4a2-d714-4e57-9892-481ab6243e3a

I have the context of the web the list is successfully returned for example in my code I have the following that works: 

` const list = await this._sp.web.getList(`${listServerRelativeUrl}`);`

However on the next line when I run:

`const xp = await  list.getCurrentUserEffectivePermissions();`

The code then fails throwing the error as described. In the console I see the following error: 
![image](https://github.com/pnp/pnpjs/assets/4320762/7c0b4290-4ba6-466b-a34f-7bd107cc77cc)

This shows an error in spfx.js that when selecting goes to: 

![image](https://github.com/pnp/pnpjs/assets/4320762/e084fe26-633a-4c43-94b0-217dcc85feca)

### Steps to Reproduce

Here is the code I am running: 

```typescript
import { getSP } from "./PnpJsConfig";
import { SPFI } from "@pnp/sp";
import { FormCustomizerContext } from "@microsoft/sp-listview-extensibility";
import { IList } from "@pnp/sp/lists";
import "@pnp/sp/attachments";
import "@pnp/sp/lists/web";
import "@pnp/sp/items";
import "@pnp/sp/webs";
import "@pnp/sp";
import "@pnp/sp/lists";
import "@pnp/sp/security/list";
import "@pnp/sp/site-users/web";
import "@pnp/sp/items/get-all";
import { WebPartContext } from "@microsoft/sp-webpart-base";
import { PermissionKind } from '@pnp/sp/security';


export class SPService {
    private static _sp: SPFI;
    private static _context: FormCustomizerContext | WebPartContext;

    public static initialise(context: FormCustomizerContext | WebPartContext): void {
        this._context = context;
        this._sp = getSP(context);
    }

	/** resolves a site relative list/library url to a server relative list/library url
	 * @param  {string} sourceSiteUrl -- a server relative or absolute site url
	 * @param  {string} siteRelativeListUrl -- a site relative list/library url, e.g. Lists/ListName or SharedDocuments
	 * @returns string -- e.g. /sites/intranet/Lists/ListName, or /sites/intranet/SharedDocuments
	 */
	public static async ResolveToServerRelativeListUrl(sourceSiteUrl: string, siteRelativeListUrl: string): Promise<string> {
        console.log(`SPService:ResolveToServerRelativeListUrl(${sourceSiteUrl}, ${siteRelativeListUrl})`);

		let serverRelativeListUrl = "";
		if (sourceSiteUrl) {
			if (!sourceSiteUrl.match(/^http[s]?:\/\/[^/]*/gi)) {
				serverRelativeListUrl = `${sourceSiteUrl}/${siteRelativeListUrl.replace(/^\//gi, "")}`;
			} else {
				const url = new URL(sourceSiteUrl);
				serverRelativeListUrl = `${url.pathname}/${siteRelativeListUrl.replace(/^\//gi, "")}`;
			}
		} else {
			serverRelativeListUrl = `${this._context.pageContext.web.serverRelativeUrl}/${siteRelativeListUrl.replace(/^\//gi, "")}`;
		}
		return serverRelativeListUrl;
	}


    public static async GetListPermissions(siteRelativeListUrl: string, forPermissions: PermissionKind | PermissionKind[]): Promise<{ [key: number]: boolean; }> {
		console.debug(`SPService:GetListPermissions('${siteRelativeListUrl}') forPermissions=`, forPermissions);
		try {

            const _sp = getSP(this._context);

			const listServerRelativeUrl = await this.ResolveToServerRelativeListUrl(null, siteRelativeListUrl);
            console.log(`SPService:GetListPermissions('${listServerRelativeUrl}')`);
            const list = await this._sp.web.getList(`${listServerRelativeUrl}`);
            const xp = await  list.getCurrentUserEffectivePermissions();

			const requestedPermissions = Object.prototype.toString.call(forPermissions) === "[object Array]" ? [...(forPermissions as PermissionKind[])] : [forPermissions];

			const actualPermissions: { [key: number]: boolean; } = {};
			requestedPermissions.forEach((p: PermissionKind) => {
				actualPermissions[p] = this._sp.web.hasPermissions({ ...xp }, p);
			});

			return actualPermissions;
		} catch (error) {
			const errorTopic = `SPService:GetListPermissions('${siteRelativeListUrl}')`;
			console.error(`${errorTopic} ::>`, error);
			error.status = error.status || "Fetch Error";
			if (error.code || error.statusCode) {
				error.status = `${error.status} [${error.statusCode}/${error.code}]`;
			}
			error.statusText = `${errorTopic} ::> ${error.statusText || "Exception"}`;
			throw error;
		}
	}
}
```

The code fails on the line: 

>  const xp = await  list.getCurrentUserEffectivePermissions();

This code is called from within a react hook using 'useEffect' to check if a user has access.

**Comment by adam13hylo** [comment]
Please close this, I realised that the way I was initialising my "spfi()" was sometimes causing the context not to be passed through, as an example I had: 

```typescript
   if(_sp === null && context !== null) {
    _sp = spfi().using(SPFx(context)).using(PnPLogging(LogLevel.Warning));
  }
```

Removing the 'if' statement means that the context is always being passed now and the error has cleared. 

Apologies for wasting your time.

**Comment by patrick-rodgers** [comment]
All good, it happens - glad you were able to get it figured out!
