### ISSUE TITLE
The issue of excessively long duration in the Term data API requests

### ISSUE THREAD

**Issue by Lan-megumi** [pnp/pnpjs#2761]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.17.0

### Target environment

SharePoint Framework

### Additional environment details

I'm updating the dependencies of an old project, and one of them is upgrading from ` PnP v2 ` to `v3`. We'll be running it on the latest `SharePoint Online`.

During this upgrade process, we encountered an issue related to the speed of SharePoint term API requests 

### Question/Request

In `pnp v2`, i would write the code to retrieve a term like this:

```typescript
import { sp } from "@pnp/sp";
import { Session, ITermStore } from "@pnp/sp-taxonomy";

    const taxonomy = new Session(this.context.pageContext.web.absoluteUrl);
    const store: ITermStore = taxonomy.termStores.getById(termStoreName);
    return store.groups
      .getById(groupName)
      .termSets.getByName(termsetName)
      .terms.select(
       // select ...
      )
      .get()
      .then((data) => {
        // more code...
      })
```

In the old website, the request speed was somewhat satisfactory and acceptable

While going through the relevant documentation, I discovered that my colleague used a higher-cost request,  [getAllChildrenAsOrderedTree](https://pnp.github.io/pnpjs/sp/taxonomy/#getallchildrenasorderedtree)

```typescript
import '@pnp/sp/webs'
import '@pnp/sp/lists'
import '@pnp/sp/items'
import '@pnp/sp/taxonomy'
import { IOrderedTermInfo, ITermInfo } from '@pnp/sp/taxonomy'

this.sp.termStore.groups
        .getById(groupName)
        .sets.getById(termSetName)
        .getAllChildrenAsOrderedTree({ retrieveProperties: true })
        .then((res) => {
            // more code ...
        })
```

Indeed, as stated in the documentation, this request is known to have the longest execution time.

I suppose the difference between the two is that in v3, there are more API requests being made: 
```
{site url}/v2.1/termstore/groups/{ key }/terms/b{ key }/children?%24select=*%2CcustomSortOrder%2Cproperties%2ClocalProperties
```

I'm not sure if the issue is caused by us using the wrong API.

That's quite critical for this website because, due to the requirements, **I cannot implement code-level caching for the speed of the post-request as suggested in the documentation**.

So, my question is, are there any **other APIs** available to achieve similar functionality?( It seems like we might have used the wrong API for our needs.)  If the API usage is not incorrect，are there any other potential solutions available?

**Comment by Lan-megumi** [comment]
I think I found some answers in the documentation. I managed to retrieve all the child nodes I need using the following method, **but it doesn't maintain the relationship with the parent node.**

```typescript
 this.sp.termStore.groups
      .getById(this.resourceData['term-group'])
      .sets.getById(this.resourceData['term-name'])
      .terms.select(...['*', 'localProperties'])
      .then((res) => {
         // Todo...
      })
```

But I wish there were some additional parameters or options that could help me retrieve the parent node data. The [examples in the documentation](https://pnp.github.io/pnpjs/sp/taxonomy/#get-term-parent) seem to require iterating through all the child nodes to obtain their parent node data.

Are there any other better methods available?

**Comment by juliemturner** [comment]
I did not work on this endpoint, and I don't do much with it, but I know there are severe limitations of the underlying api's which is why we created the `getAllChildrenAsOrderedTree` helper function. Other than that one method everything we expose is a passthrough to the actual RESTful endpoints. This 2.1 endpoint is the endpoints behind the Microsoft Graph, so you can see the documentation on that implementation by going to the graph documentation (https://learn.microsoft.com/en-us/graph/api/resources/termstore-store?view=graph-rest-1.0). In v4 of the API we will be moving away from implementing these undocumented SharePoint REST endpoints and only exposing ones in the graph, so these will be deprecated at some point.

**Comment by Lan-megumi** [comment]
> I did not work on this endpoint, and I don't do much with it, but I know there are severe limitations of the underlying api's which is why we created the `getAllChildrenAsOrderedTree` helper function. Other than that one method everything we expose is a passthrough to the actual RESTful endpoints. This 2.1 endpoint is the endpoints behind the Microsoft Graph, so you can see the documentation on that implementation by going to the graph documentation (https://learn.microsoft.com/en-us/graph/api/resources/termstore-store?view=graph-rest-1.0). In v4 of the API we will be moving away from implementing these undocumented SharePoint REST endpoints and only exposing ones in the graph, so these will be deprecated at some point.

Thank you for your response. So, if I understand correctly, in the current (v3) version, to retrieve the parent node of a term, we have to use the [Get Term Parent](https://pnp.github.io/pnpjs/sp/taxonomy/#get-term-parent) method to fetch them one by one, is that right?

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
