### ISSUE TITLE
SP items not sorted when querying via getAll

### ISSUE THREAD

**Issue by nikolaiessel** [pnp/pnpjs#2762]
### Major Version

3.x

### Minor Version Number

17

### Target environment

All

### Additional environment details

-

### Expected or Desired Behavior

This was originally discussed in #499. 
At issue time the library was version 1.x. Nowadays the getAll function internal uses paging, so $orderby GET parameter would work.
An additional index may be required (especially if this functionality will be replaced by graph calls), but restrictions for large lists apply for the $filter param too

https://github.com/pnp/pnpjs/blob/125638703568df1bb3d3c28d3e45708457b520a4/packages/sp/items/get-all.ts#L27-L36

### Observed Behavior

Items are returned ordered by default

### Steps to Reproduce

`await sp.web.lists.getById("<LIST_ID>").items.orderBy("<ORDER_COLUMN>").getAll();`

**Comment by patrick-rodgers** [comment]
Ok, easy enough to add - but be aware this will likely fail for large lists and may impact throttling.

**Comment by nikolaiessel** [comment]
Yes, but the issue "fail" exist for "filter" as well, because indexes must be set correctly
The issue "throttling" always exists because of number of requests done ([complicated conditions .oO](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online)), regardless if server must sort data or not

**Comment by patrick-rodgers** [comment]
Well, you know better than me.
