### ISSUE TITLE
Need Help with Creating SharePoint client object using clientID, clientSectret and SiteURL using PNPJs V3. 

### ISSUE THREAD

**Issue by sivarampchandra** [pnp/pnpjs#2763]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.17.0

### Target environment

SharePoint Framework

### Additional environment details

I've been using PNPJs v2 to connect to SharePoint Client with Node16 and Typescript  4.8.4. Everything was working fine. Now there is a need to upgrade to NodeJs18. this is forcing me to move to PNPJs V3 as V2 is not compatible with NodeJs18.  Things are not working as expected with PNPJs V3. I could not find proper way to create SharePoint client object using clientId, clientSecret and SharePoint site URL.  Need help with it please.

### Question/Request

I'm working with ClientID and Client Secret to gain access to our SharePoint site to check items with approval status. Currently my approach to access SharePoint client object (using V2) is as follows:

```
p.setup({
          sp: {
            fetchClientFactory: () => {
              return new SPFetchClient(`spSiteURL`, `${clientid}`, `${client_secret}`);
            }
          }
        })
```

With PNP V3 this is not working.  So trying to use the suggested **ACS Authentication** approach at this  [behavior recipes](https://pnp.github.io/pnpjs/core/behavior-recipes/) site. But finding hard to make it work for my use case. 

Did anybody able to successfully implement the solution using this approach?  
What are the imports for this approach? I am using these imports...

```
import { spfi, SPFI } from '@pnp/sp';
import { DefaultHeaders, DefaultInit } from '@pnp/sp';
import { NodeFetchWithRetry } from '@pnp/nodejs';
import { DefaultParse, InjectHeaders, Queryable } from '@pnp/queryable';
```

However,  VS code says these imports are unused. 
There are methods like "combine", "nodeFetch", and references like "URL" and "RequestInit" are not found. 

The code is building. But at run time, this line is not returning a proper SharePoint object.

`const sp = spfi(siteUrl).using(SPDefault(), ACS(process.env.CLIENT_ID, process.env.CLIENT_SECRET));
`
 sp.web is throwing this error...

TypeError: Cannot read properties of undefined (reading 'lists')
    at getListItem (/home/chandra/workdir/approval-checker/out/src/approval-checker.ts:48:44)
    at processTicksAndRejections (/home/chandra/workdir/approval-checker/lib/internal/process/task_queues.js:96:5)
    at async Context.<anonymous> (file:///home/chandra/workdir/approval-checker/out/test/unit/unitTest.js:19:30) {stack: 'TypeError: Cannot read properties of undefine…oval-checker/out/test/unit/unitTest.js:19:30)', message: 'Cannot read properties of undefined (reading 'lists')'}

Any insights on how to use this approach will be very helpful. I am kind of new to nodejs, typescript and PNP JS.  Greatly appreciate for any help.

Thanks & Regards

**Comment by juliemturner** [comment]
Did you review the nodejs authentication docs? I use Azure Identity personally but the docs pretty much cover it although depending on if you decide to go pure MSAL or use Azure Identity you'll need to look up the configuration for your particular auth mode. https://pnp.github.io/pnpjs/concepts/auth-nodejs/

**Comment by patrick-rodgers** [comment]
Regarding: "Cannot read properties of undefined (reading 'lists')" you need an import for the lists module:

`import "@pnp/sp/lists";

**Comment by sivarampchandra** [comment]
Hi Julie & Patrick, Thank you very much for quick response and inputs. 
I might use this option. But, not clear on "config". How to construct this and pass it in. What info I need to add to this configuration? 

        _Use Nodejs MSAL behavior directly[¶](https://pnp.github.io/pnpjs/concepts/auth-nodejs/#use-nodejs-msal-behavior-directly)
        It is also possible to use the MSAL behavior directly if you are composing your own strategies.
        
        import { SPDefault, GraphDefault, MSAL } from "@pnp/nodejs";
        
        const sp = spfi("{site url}").using(SPDefault(), MSAL({
          config: configuration,
          scopes: ["https://{tenant}.sharepoint.com/.default"],
        }));_

I will try with the import Patrick is suggesting as well. 

Thank you!

Best Regards

**Comment by juliemturner** [comment]
Please have a look at this documentation a bit more closely. You can see the basics of the configuration object in that example. https://pnp.github.io/pnpjs/concepts/auth-nodejs/#msal-nodejs

**Comment by sivarampchandra** [comment]
Thank you very much, Julie! Yes. I see the configuration object construction. Appreciate your Help! Will try your suggested approach and see. Thank you!

**Comment by sivarampchandra** [comment]
Hi Julie & Patrick, This may not be PNP issue. However, you might know the answer and suggest me on this
My NodeJs project was using CommonJS modules. With PNP V3 some of the imports like @pnp/nodejs, @pnp/sp/lists seems to ES modules. Hence getting this error at run time.  Any thoughts on how to address this please?

Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/@pnp/nodejs/index.js from .../out/src/test.js not supported.
Instead change the require of index.js in ../out/src/test.js to a dynamic import() which is available in all CommonJS modules.

Thank you,

Best Regards

**Comment by sivarampchandra** [comment]
@juliemturner and @patrick-rodgers, I think I found the solution for  ES modules vs commonjs modules in this [#2141](https://github.com/pnp/pnpjs/issues/2141). Thank you very much. looks like things seems to be working for me. Appreciate all your invaluable help.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
