### ISSUE TITLE
Creating a list item with multiple taxonomy field

### ISSUE THREAD

**Issue by Foster117** [pnp/pnpjs#2764]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.17.0

### Target environment

SharePoint Framework

### Additional environment details

I use a library to work with SPFx Forms Customizer

### Question/Request

I need to create a new list item. The list has a field of type multiple metadata. I have no problem creating a list item that has a single metadata field. But I don't see an example anywhere that shows in what format I should provide data to add to a field of type multiple metadata. I found articles showing how to update similar list items but not create new ones.
I am hope for your help.

```
            const item = await sp.web.lists.getByTitle(listName).items.add({
                Titile: "New Title",
                [MetadataInternalName]: ???
            });
```

**Comment by Foster117** [comment]
Through trial and error, I have come to understand that the value should be an array of objects, but the next array is not suitable.
`            value= [
                    {
                        Label: "Label1",
                        TermGuid: "Label1 Guid",
                        WssId: "-1"
                    }
                    {
                        Label: "Label2",
                        TermGuid: "Label2 Guid",
                        WssId: "-1"
                    }
];
const item = await sp.web.lists.getByTitle(listName).items.add(
{ 
Titile: "New Title",
 [MetadataInternalName]: value
 }
);
`

**Comment by Foster117** [comment]
> https://pnp.github.io/pnpjs/sp/items/#update-multi-value-taxonomy-field

Thank you, but this article is about Updating Multi-value Taxonomy, and I need to Create. The method described in the article doesn't work for creating a new list element containing multi-value taxonomy field.

**Comment by Foster117** [comment]
> Hi. The instructions for adding an item with a multi-valued managed metadata field is the **same** as the update. You need to update the value using the hidden internal field of the managed metadata column. The article that is linked (created by yours truly) is the method to do so.
> 
> You get the internal name of the hidden field and them you add the item the same way.


Thank you for the detailed response! The field with metadata is called 'Audit object'. I discovered the internal name of the hidden field. 
Title: "Audit object_0"
InternalName: "h6bff5e66a084a00b4e039800eed499d"

Next, I formed a string with values:
-1;#AMC|92066971-4701-464b-94ca-a355911d1964;#,-1;#Accounting|b0b618e2-e64c-40f6-8cff-02ca985b7606
When I'm trying to create a new list item, the following code produces an error:

```
           const item = await sp.web.lists.getByTitle(listName).items.add({
                Title: "Test Title",
                "h6bff5e66a084a00b4e039800eed499d": "-1;#AMC|92066971-4701-464b-94ca-a355911d1964;#,-1;#Accounting|b0b618e2-e64c-40f6-8cff-02ca985b7606"
            });
```
 
 Error:
 One or more field types are not installed properly. Go to the list settings page to delete these fields.
 
I believe I did everything correctly. Perhaps you could suggest what might be causing this error?

**Comment by bcameron1231** [comment]
It doesn't look like you constructed your term string correctly. Terms aren't separated by a comma like you have.  Remove the comma between them

![image](https://github.com/pnp/pnpjs/assets/7944457/7cc622a8-dde8-4895-80b8-fc28c17feb79)

**Comment by Foster117** [comment]
> It doesn't look like you constructed your term string correctly. Terms aren't separated by a comma like you have. Remove the comma between them
> 
> ![image](https://user-images.githubusercontent.com/7944457/263008019-7cc622a8-dde8-4895-80b8-fc28c17feb79.png)

Thank you for your attention, I've corrected the sentence structure, but unfortunately, the error remains the same. :(

```
            const item = await sp.web.lists.getByTitle(context.list.title).items.add({
                Title: "New Title",
                h6bff5e66a084a00b4e039800eed499d: "-1;#BDM-Sales|598c5e0f-5213-45ca-be39-bdb0a5223d6b;#-1;#CP-IT-BYOD|371ce689-d60e-43fd-9158-28f70af7bc9b"
            });
```

` {"odata.error":{"code":"-2130575340, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"One or more field types are not installed properly. Go to the list settings page to delete these fields."}}}`

**Comment by bcameron1231** [comment]
Hi. Unfortunately, I'm not sure I have an answer for you. I've tested this code out and it works for me. I would suggest just double checking the Terms and IDs to make sure the values are correct.

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
