### ISSUE TITLE
How to get HireDate and Birthday from SharePoint Online User Information List?

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2766]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.15.0

### Target environment

SharePoint Framework

### Additional environment details

I am using SPFx with React

### Question/Request

I need to get the Birthday and HireDate data of all SharePoint Online users.

With the below code snippet I can successfully get the user information list data including ID, Title, Name, EMail, JobTitle, SipAddress, WorkPhone, MobilePhone column data.

```
let getSPUserInfoListData = async () => {
        const sp: SPFI = getSP();
        return sp.web.siteUserInfoList.items.select("*,ID,Title,Name,EMail,JobTitle,SipAddress,WorkPhone,MobilePhone")
            .filter("EMail ne null").orderBy("Title", true).top(5000)()
            .then(res => {
                console.log("res..", res);
                return res;
            }).catch((err) => {
                console.log("err..", err);
                return err;
            });
    };
```

Now I will need Birthday and HireDate data. So, I  have tried with the below code snippet but it is not working at my end.

```
let getSPUserInfoListData = async () => {
        const sp: SPFI = getSP();
        return sp.web.siteUserInfoList.items.select("*,ID,Title,Name,EMail,JobTitle,SipAddress,WorkPhone,MobilePhone,Birthday,HireDate")
            .filter("EMail ne null").orderBy("Title", true).top(5000)()
            .then(res => {
                console.log("res..", res);
                return res;
            }).catch((err) => {
                console.log("err..", err);
                return err;
            });
    };
```

Can anyone help with the same?

Thanks

**Comment by bcameron1231** [comment]
Hi. This information is not stored in the User Information List. So what you're trying to do isn't possible using that API.

Hire Date (SPS-HireDate) and Birthday (SPS-Birthday) are only available on the user profile from the user profile service. This can be retrieved from the Profiles REST API, Graph API or SP Search. 

https://learn.microsoft.com/en-us/sharepoint/dev/general-development/work-with-user-profiles-in-sharepoint
