### ISSUE TITLE
SSO error in Safari browser

### ISSUE THREAD

**Issue by akashkarda** [pnp/pnpjs#2771]
### Major Version

3.x

### Minor Version Number

17

### Target environment

SharePoint Framework

### Additional environment details

I am using SPFX 1.15.2  and PnpJS 3.17.
https://github.com/pnp/pnpjs/blob/8c80e1b99a15f8264e7c0d72e3a5af56fda3bd4a/docs/concepts/auth-spfx.md

### Expected or Desired Behavior

I am trying to get a user profile properties by calling graph api in SPFx webpart. The SSO for graphapi call should work in all browser and devices.

### Observed Behavior

The SSO for graphapi call works fine except for the safari browser in iPhone. We get an error in Safari browser as below 
"Seamless single sign on failed for the user. This can happen if the user is unable to access on premises AD or intranet zone is not configured correctly"

### Steps to Reproduce

1. Create a simple SPFx webpart
2. Use PnpJs to call graph api end point
3. Browse the page in safari browser on iPhone.
4. An SSO error will show up as below
"Seamless single sign on failed for the user. This can happen if the user is unable to access on premises AD or intranet zone is not configured correctly"

**Comment by bcameron1231** [comment]
Hi! After a bit of research, I _think_ this may be an issue with the aadTokenProviderFactory that ships with SPFx unfortunately, and not an issue with the PnPjs library. 

The underlying problem appears to be a result of Third Party Cookie blocking. Enabling Third Party cookies would remove this error.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
