### ISSUE TITLE
Empty response using sp.profiles.getPropertiesFor when user name has apostrophe

### ISSUE THREAD

**Issue by c-eiser13** [pnp/pnpjs#2772]
### What version of PnPjs library you are using

3.x

### Minor Version Number

7.0

### Target environment

SharePoint Framework

### Additional environment details

Using nodeJS 16.13.2 and SharePoint Framework 1.17.4. Using a pnpjs presets file and @pnp/sp/profiles is imported.

### Question/Request

Not sure if this is a bug or not, but when I query sp.profiles.getPropertiesFor and the upn I pass has an apostrophe, it generates an error. Looking online, there is a lot of guidance to use double apostrophe (''), which removes the error, but returns an empty response. Is this a known issue, or is there another way to get profile details for a user with an apostrophe in their UPN?

![image](https://github.com/pnp/pnpjs/assets/42096464/bdbe6f97-b1d6-498b-be84-62c3b4e5bca9)

![image](https://github.com/pnp/pnpjs/assets/42096464/f4cd625b-fe55-47b0-8aa2-8c7cb65d36e7)

![image](https://github.com/pnp/pnpjs/assets/42096464/34fbc493-3be0-443f-bca4-00d298cd9f02)

![image](https://github.com/pnp/pnpjs/assets/42096464/8a634b95-29e4-460a-a7a2-b86b5ee07853)

Everything in the above call looks correct, and API works fine for users without any sort of character in their user name.

**Comment by bcameron1231** [comment]
Hi. Looking at your code....it looks like your upn should be **i:0#.f|membership|chad.o'connell@company.com**

But your passed over value has a really long GUID or UUID of some type. Where is that UUID coming from? I feel like this may be your issue.

**Comment by c-eiser13** [comment]
@bcameron1231 thanks for the quick response! I completely missed that guid in the UPN and will find where that is coming from. I did some testing with hrad-coding the name correctly, and it works, as long as you do not try and encode the username, just passing as a plain string to getPropertiesFor() did the trick. Glad I was not going crazy :)
