### ISSUE TITLE
`web.getFileByServerRelativePath` and `web.loadClientsidePage` do not work for pages with `'` in their file name

### ISSUE THREAD

**Issue by majkelmichel** [pnp/pnpjs#2773]
### Major Version

3.x

### Minor Version Number

3.17.0

### Target environment

SharePoint Framework

### Additional environment details

I am building an extension for Sharepoint using SPFx and I am using `@pnp/sp` to communicate with SP APIs.

### Expected or Desired Behavior

`web.getFileByServerRelativePath` should return files containing `'` in their name without any additional work.
`web.loadClientsidePage` should correctly return pages with `'` in ther names

### Observed Behavior

Requests made using `web.getFileByServerRelativePath` fail with code 404. It's impossible to get a file with `'` in its name without using other tools to directly call Sharepoint API.
Same with `web.loadClientsidePage`

### Steps to Reproduce

Create a Sharepoint site page with a name ```Różne ciekawe rzeczy !@#$%^&*()_+~`-=[]{};':"<>?,./```.

Assume we have a simple SPFx extensions and this is the contents of asynchronus `onInit` method:

```ts
const sp = spfi()
            .using(SPFx(this.context))
            .using(Caching());

const file = await sp.web.getFileByServerRelativePath(window.location.pathname);
```

Running this script will result with a 404 response, as the request URL will be encoded incorrectly. Instead it will contain double `'` within `'` characters marking the start and the end of url string. This will result in following request URL: ```{someSite}/_api/web/getFileByServerRelativePath(decodedUrl='%2Fsites%2F0010101portalszablon%2FSitePages%2FR%25C3%25B3%25C5%25BCne-ciekawe-rzeczy-!%2540-%2524-%255E%2526-()_%252B~%2560-%253D%5B%5D%257B%257D%253B''-----%252C.-.aspx')```

**Comment by majkelmichel** [comment]
One fix I found for getting those methods to work is to call `decodeURIComponent` on e.g. `window.location.pathname` before passing it to them. Maybe this could help with fixing it internally?

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
