### ISSUE TITLE
SharingCapability - for specific SPSite - eg. Disabled, ExternalUserSharingOnly, etc

### ISSUE THREAD

**Issue by kachihro** [pnp/pnpjs#2774]
### Target environment

SharePoint Framework

### Additional environment details

PNP JS  1.36
SPFX  1.13.1

### Enhancement Idea

I'm creating an SPFX extension to show a banner - with the 'sharing' setting for a given site.
This is defaulted within the tenantProperties - but there should be a property for the Web, RootWeb or Site ?

Within PowerShell, the command is via 'Get-PnPTenantSite' - and the specific URL.
Property :  SharingCapability

Is this able to be used/retrieved within PNPJS ?   I've tried via the different objects - sp.web, site, etc.

**Comment by patrick-rodgers** [comment]
Howdy! Version 1 is no longer supported. Is there something blocking you using v3?

In v3 you can use the [admin library](https://pnp.github.io/pnpjs/sp-admin/) to get these settings, but permissions for calling this API is high and most users wouldn't (or shouldn't) have it.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
