### ISSUE TITLE
Incorrect typing on Term Sets `add` method in Taxonomy

### ISSUE THREAD

**Issue by majkelmichel** [pnp/pnpjs#2775]
### Major Version

3.x

### Minor Version Number

3.17.0

### Target environment

All

### Additional environment details

n/a

### Expected or Desired Behavior

`add` method of term store sets should return `ITermSetInfo`.

According to [docs](https://learn.microsoft.com/en-us/graph/api/termstore-set-post?view=graph-rest-1.0&tabs=http), the create action returns information about term set, not term group.

### Observed Behavior

`add` method returns `ITermGroupInfo`

### Steps to Reproduce

```ts
const sp = spfi(...);

await sp.termStore.sets.add({
        parentGroup: {
            id: "{groupId}",
        },
        localizedNames: [{
            name: "{name}",
            languageTag: "en-US"
        }],
        properties: [{
            key: "{key}",
            value: "{val}"
        }]
    });
```

**Comment by bcameron1231** [comment]
Closing as merged. Will be in next release. Thank you for the PR!
