### ISSUE TITLE
AllowIncrementalResults is missing in ICAMLQuery 

### ISSUE THREAD

**Issue by mdissel** [pnp/pnpjs#2777]
### Target environment

All

### Additional environment details

I'm having threshold problems when fetching a list of folders using the renderListDataAsStream. I wanted to switch to the getItemsByCAMLQuery but that call is missing the AllowIncrementalResults: bool property.

### Enhancement Idea

Add AllowIncrementalResults parameter to the getItemsByCAMLQuery function

**Comment by bcameron1231** [comment]
Hi. We'll take a look at adding this. In the meantime you can pass it over by casting the query object as "any"

```
  const r = await sp.web.lists.getByTitle("Test Documents").getItemsByCAMLQuery({
                ViewXml: `<View>
                <RowLimit Paged='TRUE'>2500</RowLimit>
                <Query>
                    <OrderBy Override='TRUE'><FieldRef Name='ID'/></OrderBy>
                    <Where><Eq><FieldRef Name='FSObjType' /><Value Type='Integer'>1</Value></Eq></Where>
                </Query>
                <ViewFields>
                    <FieldRef Name='FileLeafRef' />
                    <FieldRef Name='FolderChildCount' />
                    <FieldRef Name='ContentTypeId' />
                    <FieldRef Name='ProgId' />
                    <FieldRef Name='UniqueId' />
                </ViewFields>
            </View>`,
            AllowIncrementalResults:true
            } as any);
```

**Comment by Lino357** [comment]
Need this later

**Comment by bcameron1231** [comment]
> Need this later

I just merged it in, it will be in the nightly build if you need it immediately... otherwise it will be in October's release. Alternatively, you can use the sample above in my comment in the interim. Thanks!
