### ISSUE TITLE
Saving data to SP list through web parts but restrict users from accessing those lists

### ISSUE THREAD

**Issue by MarioZagreb** [pnp/pnpjs#2779]
### What version of PnPjs library you are using

3.x

### Minor Version Number

1.0

### Target environment

SharePoint Framework

### Additional environment details

SP Online

### Question/Request

I have a SP Online and bunch of site pages with Web Parts on them. These web parts store data to SP lists (via pnp js). Now, each user is not allowed to see data of other users (which is OK of he is accessing SP only through site pages), but every user has access on lists and can access all data. How can I restrict that?? If I restrict the access on lists for users, than Web parts throw error and cannot write to those lists. What is the the right way to solve this? MS Graph? What permissions in Azure I need to set for that? Or maybe not to store the data in SP lists?

**Comment by bcameron1231** [comment]
Hi. I would look into Item Level Permissions for your items. Please see [this blog ](https://sharepointmaven.com/how-to-enable-item-level-permissions-in-sharepoint/#:~:text=However%2C%20even%20if%20you%20set%20unique%20security%20for,and%20you%20will%20see%20Item%20Level%20Permissions%20section.) for more information.

There is nothing in PnPjs we can do. It's a client side library that executes on-behalf of the user. An alternative would be to remove all permissions and offload the work to an Azure Hosted API that could do that data CRUD operations for you. 

As this is unrelated to PnPJs and moreso a SharePoint specific question, if you have further questions, I suggest asking in some support forums such as:

https://www.reddit.com/r/sharepoint/
https://learn.microsoft.com/en-us/answers/tags/235/office-sp

**Comment by juliemturner** [comment]
Although @bcameron1231 is completely correct I've found in practice that item level permissions are a pandora's box you do not want to open. I would suggest instead you consider having a site collection to store your list data that only administrators of the application have access to. Then you use (perhaps) azure functions to build your own app level permissioned API endpoints to get/update data in those lists in that site collection that are then used by your custom web parts to provide a UI for that data.
