### ISSUE TITLE
shouldSetSpoSiteReadOnlyForMembers not working

### ISSUE THREAD

**Issue by raclettierer** [pnp/pnpjs#2780]
### Major Version

3.x

### Minor Version Number

3.17.0

### Target environment

SharePoint Framework

### Additional environment details

SPFX 

### Expected or Desired Behavior

await getGraph().teams.getById(props.groupId).archive(true);

URL https://graph.microsoft.com/v1.0/teams/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx/archive

Payload  :shouldSetSpoSiteReadOnlyForMembers: true

### Observed Behavior

The SharePoint site should be readonly 

### Steps to Reproduce

await getGraph().teams.getById(props.groupId).archive(true);

**Comment by juliemturner** [comment]
Can you please provide more information. Based on what you've put above I'm not sure if you got an error message or if the endpoint just didn't work. If it's the latter that is likely not something we can do much about, but it's also possible that the payload changed. Did you test the endpoint in the Microsoft Graph explorer, and does it work there?

**Comment by raclettierer** [comment]
I try it with the graph explorer and did not working :-( 
The Team is archived but SP is not in readonly mode. 

POST:  https://graph.microsoft.com/v1.0/teams/[GUID]/archive
Body:
{
    "shouldSetSpoSiteReadOnlyForMembers": true
}

**Comment by juliemturner** [comment]
> I try it with the graph explorer and did not working :-(

Ok, but you still haven't shared if you are getting an error message or not. If you are, I need to know what it is. If not, then I'm sorry I don't think we can help you as this library is only a proxy to the official Microsoft endpoints. By trying it in Graph explorer that essentially says to me there's a problem with the graph endpoint.

**Comment by raclettierer** [comment]
no error. but the sharepoint site is still not in readonly mode.

**Comment by juliemturner** [comment]
Sorry we cannot assist further. I would suggest that you follow the recommendations of [Microsoft Graph - Support](https://developer.microsoft.com/en-us/graph/support) for further assistance.
