### ISSUE TITLE
Regression: cannot add an image field to the list in PNP >= 3.15

### ISSUE THREAD

**Issue by Dzieni** [pnp/pnpjs#2783]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.15, 3.16, 3.17, 3.18

Please specify what version(s) of SharePoint you are targeting: online

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question

```javascript
await web.lists.getByTitle('Test list').fields.addImageField('Image test')
```

Such a call successfully creates an image field called "Image test" in PNP 3.14.

### Observed Behavior

In PNP 3.15 and newer, we get an HTTP error 400:
```
Microsoft.SharePoint.Client.InvalidClientQueryException A type named 'FieldMultiLineText' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.
```

I've traced the HTTP payloads and the difference is in extra `__metadata` field present in newer versions.

PNP 3.14:
```json
{
    "FieldTypeKind": 34,
    "Required": false,
    "Title": "Image test"
}
```
PNP 3.15 and newer:
```json
{
    "FieldTypeKind": 34,
    "Title": "Image test",
    "__metadata": {
        "type": "FieldMultiLineText"
    }
}
```

**Comment by juliemturner** [comment]
@Dzieni - I can confirm that this is a bug, which stems from an inconsistency in how field creation is implemented in SharePoint online. Essentially a fix which was correct for all historical field types doesn't work with new field types. In the mean time you can work around this bug by using the following:

```ts
import { spPost } from "@pnp/sp";

const fields = sp.web.lists.getByTitle('pnplist').fields;
const body = {
    Title: "My Image Field",
    FieldTypeKind: 34
};
const w = await spPost(fields, { body: JSON.stringify(body) });
```
