### ISSUE TITLE
Graph sendMail API Typing

### ISSUE THREAD

**Issue by tknaller** [pnp/pnpjs#2789]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.18.0

### Target environment

All

### Additional environment details

NodeJS (Azure Function), Certificate Authentication with MSAL. graphfi().using(GraphDefault({...}))

### Question/Request

`graph.me.sendMail` requires a IMessage object which can be created by calling Message(graph.me) but is still missing the actual message in it's type definition. Might be a regression from issue #829. Also, documentation is missing entirely.

**Comment by juliemturner** [comment]
The type comes directly from the graph's typings, which comes from `@microsoft/microsoft-graph-types` version 2.38.0. If it's not correct, then I would suggest [manually making the call](https://pnp.github.io/pnpjs/concepts/calling-other-endpoints/). We're working on revamping the graph section in v4, but I will say not much we can do about graph typings being incorrect, but I haven't looked at it more in depth yet.

**Comment by tknaller** [comment]
well the type from `@microsoft/microsoft-graph-types` is actually correct - but `@pnp/graph`'s `sendMail()` expects a pnp `Queryable` instead of the Message-Type from `@microsoft/microsoft-graph-types` - additionally there is the fact that that will need to be wrapped in another object as stated in the old issue

**Comment by juliemturner** [comment]
As I said we're revamping that section as many of those endpoints were implemented a long time ago by a contributor and have not been fully vetted or documented. So I'd follow my advice about making the call manually that will be easiest for now.

**Comment by bcameron1231** [comment]
Indeed there appears to be some typing issues. You could cast the object as any and it will still work.

```
 graph.me.sendMail({
      message:{
          subject: "Meet for lunch?",
          body: {
              contentType: "text",
              content: "The new cafeteria is open."
          },
          toRecipients: [
              {
                  emailAddress: {
                      address: "beau@company.onmicrosoft.com"
                  }
              }
          ]
      },
      saveToSentItems: true
      } as any);
```
