### ISSUE TITLE
registerCustomRequestClientFactory runtime cannot be passed to custom client

### ISSUE THREAD

**Issue by nob-b3** [pnp/pnpjs#2795]
### What version of PnPjs library you are using

2.x (No longer supported)

### Minor Version Number

2.14.0 (Common-JS-Version)

### Target environment

NodeJS

### Additional environment details

I'm using node js and sp with createIsolated setup.

### Question/Request
We're using a custom request client like described in https://pnp.github.io/pnpjs/v2/sp/custom-irequestclient/. The problem is, that the runtime gets not passed to the custom request client. The runtime is needed, to use our SPFetchClient in the sp.setup method (see coding). Because if I pass the runtime to the super constructor (of SPHttpClient) the this._impl variable gets set right. Otherwise a FetchClient is simply set in the this._impl variable and as a result the method this._impl.fetch (in the fetchRaw method) does not work in the CustomSPHttpClient (runs on error)

That's the reason why I've created a new register method within this pull request to register a request client factory with a runtime.

The problem is that the following thing does not work.

```
// registering
registerCustomRequestClientFactory((runtime) => new CustomSPHttpClient(runtime));

// sp.setup
conn.setup({
	sp: {
	        baseUrl: baseUrl,
		fetchClientFactory: spFetchClient,
		headers,
	}
});

// CustomSPHttpClient
class CustomSPHttpClient extends SPHttpClient {
	constructor(runtime) {
		super(runtime); // here the runtime is always empty
	}

	fetchRaw(url, options) {
                 this._impl.fetch...
                 
	}
}
```

**Comment by juliemturner** [comment]
I'll be blunt, V2 is completely out of support. Even building and releasing it is a huge task especially given we're in the midst of working on v4. However, we recognize that you're using commonjs version and that we don't support commonjs after this version so we're discussing if/how we can support you and will get back to this when we can figure out what is the best course forward. 

You also certainly can just build the packages yourself to get unblocked.

**Comment by patrick-rodgers** [comment]
Hi @nob-b3 - we've discussed this a few times now amongst the team and we are not going to merge the PR(s) and do an additional release. V2 has been in an unsupported state for a long time now, and if we make another release that sends the wrong message. As well, we have a concern that for existing solution using 2.* they would all start using this new version, meaning if there are issues, we'd have to engage and fix things.

I think you can monkey patch the library to support your needs. Not elegant but does get you there.

It sounds like your limitation is needing common js modules, something we hope to help address in v4 with the improvements to package.json support for multiple module types - but early days so don't want to overpromise.

Have you tried v3? We did a decent amount of work to make it function within node's es module resolution system.

I hope you understand our reason even if it's disappointing. I'll leave this issue open if you want to share any additional feedback, and thanks for your interest in our library.
