### ISSUE TITLE
Configuring fetchClientFactory for a single request

### ISSUE THREAD

**Issue by pedro-pedrosa** [pnp/pnpjs#280]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.3]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
In the context of a node.js web server, we are required to set the `fetchClientFactory` globally on the sp object. Because this is a global setup, I am unable to configure the `clientId` and `clientSecret` parts of the fetch client on a per-request basis, as due to the asynchronous nature of a node.js server, the global config may have been changed by a web request before a REST call is made on some other request.

This is problematic in the following scenarios for a node.js web server:

- Access a single SharePoint farm using two different app identifiers
- Access different SharePoint farms using the same app identifiers (the realm changes and the access tokens are not interchangeable)
- Access a single SharePoint farm in a user-aware scenario (assuming #277 is implemented)

Maybe this could be solved by allowing queryable objects to specify the fetchClientFactory:
```ts
sp.web.usingFetchClient(() => new SPFetchClient(url, id, secret)).get()
```

Or maybe do something like:
```ts
const sp = new ConfigurableSharePoint({
  //what one would pass to sp.setup
  sp: {
    fetchClientFactory: new SPFetchClient(url, id, secret)
  }
});
sp.web.get();
```

Modifying the global config before each REST call could be an option but maybe there's a better alternative?
Edit: actually I don't think setting the global config before the call would work, as the `SharePointQueryable.toRequestContext` method calls an asynchronous function `toAbsoluteUrl` before accessing the global config, so it could change before the request is executed.

**Comment by koltyakov** [comment]
Hi @pedro-pedrosa,

Thanks for the suggestion.

Even now you can achieve something similar using `.configure` for a single chain of operations:

```typescript
const web = new Web(props.webAbsoluteUrl).configure({
  headers: {
    Authorization: `Bearer ${props.token}`,
    Accept: 'application/json;odata=minimalmetadata'
  }
});
```

But you got to receive and provide authorization header and token manually. Maybe it'll solve your scenario problem.

**Comment by pedro-pedrosa** [comment]
Okay that works for my current case as I'm manually fetching the access tokens already. Is there any risk that the auth header gets overridden by something else?

**Comment by koltyakov** [comment]
Should be safely passed in the chains. The only thing to bother in such a setup is updating tokens when expired.

**Comment by pedro-pedrosa** [comment]
Yes, not sure if token management is something for this particular library to address, what do you think? Even in the "regular" scenario for nodejs environments, things are quite inefficient as I believe that (correct me if I'm wrong) for each request, the fetch client factory is called which creates a new client object which forces a new access token to be generated.

For anyone else stumbling into this, you also have to implement a fetch client that will use `node-fetch` instead of relying in the browser's `fetch` implementation:

```ts
declare var global: any;
import nodeFetch from 'node-fetch';
import { HttpClientImpl, combine, isUrlAbsolute } from "@pnp/common";

export class CustomFetchClient implements HttpClientImpl {

    constructor(public siteUrl: string) {

        // is this still needed?
        global._spPageContextInfo = {
            webAbsoluteUrl: siteUrl,
        };
    }

    public async fetch(url: string, options: any): Promise<Response> {

        if (!isUrlAbsolute(url)) {
            url = combine(this.siteUrl, url);
        }

        return nodeFetch(url, options) as Promise<any>;
    }
}
```

I still haven't tried this but it looks like it could work.

**Comment by koltyakov** [comment]
Nope, it doesn't retrieve new token each time. Of course, the token is cached and time to live and refresh is involved. 

When it comes to AAD, `authContext.acquireTokenWithClientCredentials` is smart enough to refresh a token only on expiration time.

With `SPFetchClient` caching and expiration time are also envolved.

So it's pretty much efficient.

**Comment by pedro-pedrosa** [comment]
Isn't the client factory called on each request though?

https://github.com/pnp/pnpjs/blob/95ae7b265d93d59140768ae5c74b2cbbc69cc203/packages/odata/src/pipeline.ts#L221

**Comment by koltyakov** [comment]
Good catch, let me check it over the weekend.

**Comment by patrick-rodgers** [comment]
The client factory is called on each request on purpose, the idea being that if you wanted to update the returned client with each request (say update a token) you had an opportunity to do so. This also handles the issue of ensuring the token is valid by always getting a new one. Now, this could be improved - but managing tokens gets complicated, especially if you are trying to juggle multiple sites as you mention above.

**Comment by pedro-pedrosa** [comment]
I think calling the factory on each request is correct, only the caching mechanism in `SPFetchClient` is not very efficient. 

Clearly making REST calls to multiple sites on the same process was not in the design goals of the library. That's acceptable as the basic usage scenario is the browser in an SPFx solution.

However, with the rise of cloud-based solutions, sometimes apps need to live outside of SharePoint. Because you can implement a provider-hosted app using node.js, and since the recommended way to access SharePoint is through the REST API, using this library for that goal seems reasonable.

Currently, there is no easy way of creating a provider-hosted app in node.js that uses this library. Maybe the particular use case that made me start this topic (having specific settings for a single request) can be solved on a low-level basis by instantiating `SPRest` with the `Authentication` header set.

It would make a lot more sense (in my opinion) that the `SPRestClient` should only do what it's supposed to do (use `node-fetch` instead of `fetch` from the Web API), token management is left to a separate component, and token caching (used by the token management component) would also be a configurable component so you would be able to cache your tokens in different ways.

**Comment by pedro-pedrosa** [comment]
Ideally:

```ts
//server start:
sp.setup({
  sp: {
    fetchClientFactory: () => new SPFetchClient(siteUrl) //doesn't do anything related to tokens
  },
  tokenManager: {
    cacheManager: new MapCache()
  }
});

//begin request:
const userEndpoint =  = new SPRest({ //extend the ConfigOptions type to include the accessToken prop
  accessToken: TokenManager.getUserAccessToken(siteUrl, clientId, clientSecret, refreshToken), //this will set the Authorization header
});
const addinOnlyEndpoint = new SPRest({
  accessToken: TokenManager.getAddinOnlyAccessToken(siteUrl, clientId, clientSecret),
});
const { Title: userName } = (await userEndpoint.web.currentUser.select('Title').get());
await addinOnlySP.web.lists.getByTitle('Restricted list').items.add({ Title: `Accessed by ${userName}` });
```

It would be useful for the TokenManager to also validate an incoming context token. This component would be similar in functionality to the `TokenHelper` class available to ASP.NET provider-hosted apps.

**Comment by patrick-rodgers** [comment]
I believe issues #275, #280, and #277 are all related and point to a need to improve the node client. The code involved hasn't been updated beyond the basic case since I first wrote it, so I am sure there are many improvements to be made. Will try and digest all three issues and come up with a plan.

**Comment by patrick-rodgers** [comment]
Going to close this, please see conversation in #277, and [this comment specifically](https://github.com/pnp/pnpjs/issues/277#issuecomment-434445961)
