### ISSUE TITLE
I cannot get 'Open Extension' from current user using PnPGraph

### ISSUE THREAD

**Issue by Wagnerah** [pnp/pnpjs#2803]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.18.0

### Target environment

SharePoint Framework

### Additional environment details

I'm using the default solution scalffolded from Spfx 1.18.0 Webpart.

### Question/Request

I'm strugling to get current user open extensions property using PnP Graph, this is my code:

```
const getGraphCurrentUser = async (): Promise<IUser> => {
    const userFields: string[] = ["extensions"];
    const currentUser: IUser = await graph.me.expand(...userFields);

    return currentUser;
  };

```
I have followed this post to create my user custom open extensions: https://joaojmendes.com/2020/04/14/microsoft-graph-open-extensions/

**Comment by bcameron1231** [comment]
It looks like you're missing the call signature.

**What you have**
` const currentUser: IUser = await graph.me.expand(...userFields);`
    
**What it should be**
` const currentUser: IUser = await graph.me.expand(...userFields)();`

**Comment by Wagnerah** [comment]
It works @bcameron1231, thanks a lot!

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
