### ISSUE TITLE
Graph Search query does not use Caching

### ISSUE THREAD

**Issue by BollietMZK** [pnp/pnpjs#2804]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.18.0

### Target environment

SharePoint Framework

### Additional environment details

I'm using the latest SharePoint Framework version.
I have created a new HelloWorld SPFx project with React.

### Question/Request

In a new HelloWorld SPFx project, I install `@pnp/graph` latest version.
In the `onInit` method, I create a new graph instance using caching.
Then, I execute a `search query` request.

The request is sent as expected 👍
But for each successively page refresh, the request is sent again and again, no response is stored in storage.

For information, all other requests than search query use correctly caching 👍

```
import { SPFx, graphfi } from "@pnp/graph";
import { Caching } from "@pnp/queryable";
import "@pnp/graph/search";

[...]

protected async onInit(): Promise<void> {
  await super.onInit();

  const graph = graphfi().using(SPFx(this.context), Caching());

  const results = await graph.query({
    entityTypes: ["site"],
    query: {
      queryString: "test",
    },
  });
  console.log("⚠️ results: ", results);
}
```

![image](https://github.com/pnp/pnpjs/assets/87386292/deec5c26-d706-4b3a-90d4-49748c3c464f)

**Comment by bcameron1231** [comment]
Hi this is as intended. Caching by default only caches GET Requests.  The Search Query is a POST request so it's not added to cache.  If you want to cache these requests, simplest approach would be to cache this specific call using CacheAlways()

import { SPFx, graphfi } from "@pnp/graph";
import { Caching, CacheAlways } from "@pnp/queryable";
import "@pnp/graph/search";

```

protected async onInit(): Promise<void> {
  await super.onInit();

  const graph = graphfi().using(SPFx(this.context), **Caching()**);

  const results = await graph.using(**CacheAlways()**).query({
    entityTypes: ["site"],
    query: {
      queryString: "test",
    },
  });
  console.log("⚠️ results: ", results);
}
```

Please see our Caching docs for [more information](https://pnp.github.io/pnpjs/queryable/behaviors/#caching)

**Comment by BollietMZK** [comment]
Wow!
Thank you very much @bcameron1231!
Until today, I'd never seen that `Caching` was only applied to GET requests by default!

`CacheAlways` works as expected for POST requests and fixes my problem.
Love it ❤️
