### ISSUE TITLE
Not able to save Person Information 

### ISSUE THREAD

**Issue by TapanKumarBarik** [pnp/pnpjs#2805]
### What version of PnPjs library you are using

3.x

### Minor Version Number

1.0

### Target environment

SharePoint Framework

### Additional environment details

PeopleDetails STORING ALL people picker

 const userIDs: [] = this.state.PeopleDetails.map(
      (user: { loginName: any }) => user.loginName
    ); 

const list = sp.web.lists.getByTitle("test");
      const itemToAdd = {
        Title: "New Item Title",
        Members: {
          results: userIDs,
        },
      };
      await list.items.add(itemToAdd);

Error adding item to SharePoint list: Error: Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"A node of type 'PrimitiveValue' was read from the JSON reader when trying to read the entries of a feed. A 'StartObject' or 'EndArray' node was expected."}}}
    at new HttpRequestError (parsers.js:130:1)
    at Function.<anonymous> (parsers.js:145:1)
    at step (tslib.es6.js:102:1)
    at Object.next (tslib.es6.js:83:45)
    at fulfilled (tslib.es6.js:73:42)

### Question/Request

Error adding item to SharePoint list: Error: Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"A node of type 'PrimitiveValue' was read from the JSON reader when trying to read the entries of a feed. A 'StartObject' or 'EndArray' node was expected."}}}
    at new HttpRequestError (parsers.js:130:1)
    at Function.<anonymous> (parsers.js:145:1)
    at step (tslib.es6.js:102:1)
    at Object.next (tslib.es6.js:83:45)
    at fulfilled (tslib.es6.js:73:42)

**Comment by juliemturner** [comment]
Please see the documentation on adding user field data: https://pnp.github.io/pnpjs/sp/items/#user-fields

Essentially you have to use their equivalent SharePoint User ID.

**Comment by TapanKumarBarik** [comment]
Hi @juliemturner ,

I don't know why it's still not working, even if I am hard coding thr userid still same issue

**Comment by juliemturner** [comment]
If you want to share how you've tried to fix it, I can try to help but the example I linked to shows what has always worked for me... that an array or integers that specifically represent the user's id as SharePoint knows it... so these are not guids these are integers.

**Comment by TapanKumarBarik** [comment]
Hi @juliemturner ,

Thanks for the response .
Now i am getting user ids and 

const list = sp.web.lists.getByTitle("test");
const itemToAdd = {
Title: "New Item Title",
Members: [1,2]
};
await list.items.add(itemToAdd);


This is also now working

**Comment by TapanKumarBarik** [comment]
I am not using react hooks , and 

CreateCommunity.tsx:131  Error adding item to SharePoint list: Error: Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"A node of type 'PrimitiveValue' was read from the JSON reader when trying to read the entries of a feed. A 'StartObject' or 'EndArray' node was expected."}}}
    at new HttpRequestError (parsers.js:130:1)
    at Function.<anonymous> (parsers.js:145:1)
    at step (tslib.es6.js:102:1)

This is the error

This in constructor 

  sp.setup({
      spfxContext: this.props.context,
    });


these are imports 

import "@pnp/sp/webs";
import { sp } from "@pnp/sp";
import "@pnp/sp/lists";
import "@pnp/sp/items";


in props 

context: any;

**Comment by TapanKumarBarik** [comment]
Hi @juliemturner  ,


sorry, i missed that, now i am using v3 completely ,. still the same issue 


CreateCommunity.tsx:120  Error adding item to SharePoint list: Error: Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"A node of type 'PrimitiveValue' was read from the JSON reader when trying to read the entries of a feed; however, a node of type 'StartObject' or 'EndArray' was expected."}}}



 "dependencies": {
    "@fluentui/react": "^7.199.1",
    "@microsoft/sp-component-base": "1.17.4",
    "@microsoft/sp-core-library": "1.17.4",
    "@microsoft/sp-lodash-subset": "1.17.4",
    "@microsoft/sp-office-ui-fabric-core": "1.17.4",
    "@microsoft/sp-property-pane": "1.17.4",
    "@microsoft/sp-webpart-base": "1.17.4",
    "@pnp/sp": "^3.18.0",
    "@pnp/spfx-controls-react": "^3.15.0",
    "axios": "^1.5.1",
    "bootstrap": "^5.3.2",
    "office-ui-fabric-react": "^7.199.1",
    "react": "17.0.1",
    "react-bootstrap": "^2.9.0",
    "react-dom": "17.0.1",
    "tslib": "2.3.1"
  },



import { spfi, SPFx } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

 try {
      const sp = spfi().using(SPFx(this.props.context));
      debugger;
      await sp.web.lists.getByTitle("test").items.add({
        Title: "t",

        Members: [11, 16],
      });
      console.log("Item added to SharePoint list.");
    } catch (error) {
      console.error("Error adding item to SharePoint list:", error);
    }

**Comment by juliemturner** [comment]
>sorry, i missed that, now i am using v3 completely 

But actually you're not because you using `@pnp/spfx-controls-react`. And because of that this
```
sp.setup({
spfxContext: this.props.context,
});
```
compiles which is the V2 implementation. Essentially if you want to use `@pnp/spfx-controls-react` you have to downgrade to v2 across the board.

**Comment by bcameron1231** [comment]
Additionally, once you get the versioning fixed up, make note that to update the person field, it must use the person field + ID (this is in our docs). So your code it would be MembersId and not Members. Like below.

```
const list = sp.web.lists.getByTitle("test");
const itemToAdd = {
  Title: "New Item Title",
    Members**Id**: {
    results: userIDs,
  },
};
await list.items.add(itemToAdd);
```

**Comment by TapanKumarBarik** [comment]
Hi @juliemturner @bcameron1231  ,

Thanks for the quick help and it is working now.

I got confused with the versioning.
