### ISSUE TITLE
sp.utility.emails delayed in recieving 

### ISSUE THREAD

**Issue by sachin717** [pnp/pnpjs#2808]
### What version of PnPjs library you are using

2.x (No longer supported)

### Minor Version Number

2.11.0

### Target environment

SharePoint Framework

### Additional environment details

i am trying to send emails with sp.utilitities.send emails to internal tenants 
but emails are getting delayed by 2 -3 hours this is causing a lot of problems 
 "@pnp/odata": "^2.14.0",
    "@pnp/pnpjs": "^2.10.0",
    "@pnp/sp": "^2.11.0",
    "@pnp/spfx-controls-react": "^3.6.0",  "react-dom": "17.0.1",

### Question/Request

 sp.setup({
      spfxContext: ContextService.GetFullContext(),
    });
    sp.utility
      .sendEmail({
        Body: body,
        Subject: subject,
        To: toOwner,
        From: from,
        CC: CC,
      })
      .then((i) => {

      })
      .catch((i) => {

      });

**Comment by bcameron1231** [comment]
Hi Unfortunately, there is nothing we can do to help here. The request is sent to SharePoint and then Microsoft owns the processes for being sent. I would check your filters and rules in exchange. The emails may be getting caught up. However, this is issue would be unrelated to the library.

**Comment by sachin717** [comment]
yes thank you so much for your respose
just want to confirm is the issue still presists in the newer verions if i try to update with newer verion
________________________________
From: Beau Cameron ***@***.***>
Sent: Wednesday, October 11, 2023 9:38 PM
To: pnp/pnpjs ***@***.***>
Cc: Sachin Gagneja ***@***.***>; Author ***@***.***>
Subject: [External] Re: [pnp/pnpjs] sp.utility.emails delayed in recieving (Issue #2808)


 Ext. email, don't open links / files unless sender is reliable.

Closed #2808<https://github.com/pnp/pnpjs/issues/2808> as completed.

**Comment by bcameron1231** [comment]
@sachin717  Yes, this still persists because it's not a PnPJs Library issue.
