### ISSUE TITLE
AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application

### ISSUE THREAD

**Issue by RoSchoe** [pnp/pnpjs#281]
### Category
- [ ] Enhancement
- [ ] Bug
- [ x] Question
- [ x] Documentation gap/issue

### Version

Please specify what version of the library you are using: 

 @pnp/common@1.2.3
+-- @pnp/graph@1.2.3
+-- @pnp/logging@1.2.3
+-- @pnp/nodejs@1.2.3
+-- @pnp/odata@1.2.3
+-- @pnp/sp@1.2.3

Please specify what version(s) of SharePoint you are targeting: 
---create webpart (spfx) with yo (sharepoint online only)

### Expected / Desired Behavior / Question
I want to use graph from pnp
in my constructor i do:
graph.setup({
        spfxContext: this.props.context
});

later in function i want to call  
graph.groups.get().then(groups => {
        console.log(groups);
    
 });

Question:
At first in chrome i get "blocked Popup" - solved that
now pop-up shows following error:

_AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'c58637bb-e2e1-4312-8a00-04b5ffcd3403'._

where is the place to put in the information for application ID for Azure AD? Or what i am doing wrong?

### Observed Behavior
I thought there is a silent way to use graph without login process again (or mayby in background)

Thank you for your feedback!

**Comment by RoSchoe** [comment]
Hi is there a workaround to get it running? 
I tried the way ["AdalFetchClient"](https://pnp.github.io/pnpjs/graph/docs/) but when i want to use this i get 

`graph.setup({
      graph: {
          fetchClientFactory: () => {
              return new AdalFetchClient("{tenant}.onmicrosoft.com", "AAD Application Id", "AAD Application Secret");
             
          },
      },
    });
`
I get following error in gulp serve:
Error - [webpack] 'dist':
./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in 'MYPATH\node_modules\request\lib'
resolve 'fs' in 'MYPATH\node_modules\request\lib'
  Parsed request is a module
  using description file: MYPATH\node_modules\request\package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: MYPATH\node_modules\request\package.json (relative path: ./lib)
    resolve as module......`

**Comment by patrick-rodgers** [comment]
The AdalFetchClient is designed to work in node so won't bundle for the browser. You could try the [adalclient](https://github.com/pnp/pnpjs/blob/dev/packages/common/src/adalclient.ts) from the common package.

https://pnp.github.io/pnpjs/common/docs/adalclient/

**Comment by patrick-rodgers** [comment]
Got a good fix for this coming hopefully for the release this Friday. Would require folks are on SPFx 1.6 but uses the new AADTokenProvider to smooth out this whole experience nicely. Things will still be a little rough in earlier SPFx or outside of SPFx but that is OK for now.

**Comment by RoSchoe** [comment]
Hi i anxiously looking forward to use it.  Do you have short "how to" script? Kind Regards

**Comment by patrick-rodgers** [comment]
Will update the docs with the release, but what I am working on isn't out yet. Just wanted to make sure you didn't think we forgot :)
