### ISSUE TITLE
I'm trying to create a message in a teams channel, but it expects a string.

### ISSUE THREAD

**Issue by 2atJanWillem** [pnp/pnpjs#2811]
### What version of PnPjs library you are using

3.x

### Minor Version Number

19

### Target environment

SharePoint Framework

### Additional environment details

I have created a SPFX tab and i'm trying to add a message via pnpjs.

### Question/Request

The following line expects a string, but in the example you have to create a object:
await this._graph.teams.getById('3a4cde81-84dc-4dac-bb77-310e2aa6e940').channels.getById('19:-8g_6dJnRLQn2S_dSNJOFW8fytxodsd4B4SqAL1Hyv81@thread.tacv2').messages.add(message);

If tried to stringify my json, so I could run my code. But then I get the following request URL and subsequent error in the browser:
Request URL:
https://graph.microsoft.com/v1.0/teams/3a4cde81-84dc-4dac-bb77-310e2aa6e940/channels/19:-8g_6dJnRLQn2S_dSNJOFW8fytxodsd4B4SqAL1Hyv81@thread.tacv2/messages

This URL seems to be good, but look at the body it tries to send:
{"description":"","displayName":"{\"body\":{\"content\":\"Hello World\"}}"}

This is the error:
Error making HttpClient request in queryable [400] Bad Request ::> {"error":{"code":"BadRequest","message":"Missing body content","innerError":{"date":"2023-10-23T22:17:54","request-id":"62b0d305-e781-40d5-906e-2b58b0c18dcd","client-request-id":"62b0d305-e781-40d5-906e-2b58b0c18dcd"}}}

The error also makes sense if I look at the request payload.

How can we fix this?

**Comment by patrick-rodgers** [comment]
Looks like someone copy/pasted the channel add code into the message add method. Appears to be a bug.

**Comment by bcameron1231** [comment]
Just submitted a PR for this. Will be fixed in the next release. In the meantime, if you need to send messages with PnPjs, you can extend the Graph library like we show in our docs. https://pnp.github.io/pnpjs/concepts/calling-other-endpoints/

```
 var messages = await graph.teams.getById('ecd70b09-3306-4bcd-bde4-06a8ab3c73b3').channels.getById('19:1c2b6aa334ad492898f21eb6081526c3@thread.tacv2').messages;

  var message = await graphPost(GraphQueryable(messages), body({
      "body": {
        "content": "Hello World"
      }
  }));
```
