### ISSUE TITLE
Convert ISiteUserInfo[] to SharePointUserPersona[]

### ISSUE THREAD

**Issue by Shmata** [pnp/pnpjs#2813]
### What version of PnPjs library you are using

3.x

### Minor Version Number

15.0

### Target environment

SharePoint Framework

### Additional environment details

I'm using pnp/sp/site-groups library in my SPFx project

### Question/Request

Hi guys,
I'm using the '@pnp/sp' library to fetch specific group members, and everything is working fine. It returns all members of a group as an ISiteUserInfo[]. Then, I need to merge these members to another group that a user will select, which is of type SharePointUserPersona[].

My question is: **How can I convert ISiteUserInfo[] to SharePointUserPersona[]?** I've written a function to do the conversion, but it's missing many important attributes. For example, in the definition of IUserEntityData (SharePointUserPersona uses  IUserEntityData  and a few others interfaces ), we can't find 'UserKey,' but as you can see in the screenshot, there is an attribute called 'UserKey.'

This is IUserEntityData definition
![Screenshot 2023-10-24 114216](https://github.com/pnp/pnpjs/assets/2398297/99ef23e3-f34f-4979-81fb-9490fa7d726c)
As you can see there is no 'UserKey', but it is in object when I log it in console. 
![Screenshot 2023-10-24 114243](https://github.com/pnp/pnpjs/assets/2398297/8039b41e-0a50-49aa-96a3-4e2beee4a65a)
So I can not add that to my function, but that is necessary. 
![1](https://github.com/pnp/pnpjs/assets/2398297/ec566f1b-517c-4048-a146-c4f17e4002aa)
And a lot things like that. 

**Could you help or guide me on how to convert ISiteUserInfo[] to SharePointUserPersona[]?**

**Comment by Shmata** [comment]
This is my function, and it works only in some cases. I would be thankful if you could help me to fix that issue. 

```    public convertSiteUserInfoToSharePointUserPersona(siteUserInfoArray: ISiteUserInfo[]): SharePointUserPersona[] {
        const userPersonas: SharePointUserPersona[] = [];
        siteUserInfoArray.forEach((siteUserInfo) => {
            const entityData: IUserEntityData | IClientPeoplePickerSearchUser | any = {
                IsAltSecIdPresent: 'False', 
                ObjectId: siteUserInfo.Id.toString(),
                Title: siteUserInfo.Title,
                Email: siteUserInfo.Email,
                MobilePhone: '',
                OtherMails: '',
                Department: '',
                PrincipalType: '',
                SPGroupID: null,
                UserKey: `i:0h.f|membership|${siteUserInfo.UserId.NameId}@live.com`
            };
            const ensurableUser: IEnsurableSharePointUser | IClientPeoplePickerSearchUser | any = {
                Key: `i:0#.f|membership|${siteUserInfo.Email}`,
                Description: siteUserInfo.Email,
                DisplayText:  siteUserInfo.Title,
                EntityType: "User",
                EntityData: entityData,
                ProviderDisplayName: 'Tenant',
                ProviderName: 'Tenant',
                IsResolved: true,
                MultipleMatches: [], 
                _users: siteUserInfo
            };
            userPersonas.push(new SharePointUserPersona(ensurableUser));
        });
    
        return userPersonas;
    }
    ```

**Comment by patrick-rodgers** [comment]
What is `SharePointUserPersona`? I don't find that in our code so unsure how to really guide you to map to it.

**Comment by Shmata** [comment]
> What is `SharePointUserPersona`? I don't find that in our code so unsure how to really guide you to map to it.

SharePointUserPersona is part of Fluent UI people picker component. If you select some users using Fluent UI people picker the type of those users would be SharePointUserPersona[]

**Comment by bcameron1231** [comment]
SharePointUserPersona is not a part of FluentUI. FluentUI components use IPersonaProps & IPersona.

The only references I've seen to this on the internet is a custom solution built by Giulano De Luca https://github.com/giuleon/SPFx-OfficeUIFabric-PeoplePicker and I have no idea about this solution, or why the models were extended the way they were. And some of your comments about IUserEntityData, that [doesn't exist on the interface ](https://github.com/giuleon/SPFx-OfficeUIFabric-PeoplePicker/blob/d34d24680574e69671d9f100ea608bb8d2017391/src/webparts/officeUiFabricPeoplePicker/models/OfficeUiFabricPeoplePicker.ts#L14C19-L14C19)in that solution.

Are you using that solution? Because these interfaces are not required or used in Fluent UI components.

**Comment by patrick-rodgers** [comment]
Yeah - you'd need to determine how to map to other libraries. We return what the APIs return, how that might map to another solution's interfaces/objects isn't something we can really commit time to assisting with. UserKey might be login name - or it could be a guid, or an integer id, or something custom to that library.
