### ISSUE TITLE
Azure Function with msal onBehalf says token expired but it is not expired

### ISSUE THREAD

**Issue by vreezy** [pnp/pnpjs#2814]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.16.0

### Target environment

Azure Function

### Additional environment details

listeExtension is calling a azure function

package.json azure function:
```
  "dependencies": {
    "@azure/msal-node": "^1.18.0",
    "@azure/storage-blob": "^12.14.0",
    "@pnp/graph": "^3.16.0",
    "@pnp/nodejs": "^3.16.0",
    "@pnp/queryable": "^3.16.0",
    "@pnp/sp": "^3.16.0",
    "image-size": "^1.0.2",
    "jimp": "^0.22.8",
    "jspdf": "^2.5.1",
    "jspdf-autotable": "^3.5.23",
    "validator": "^13.9.0"
  },
  "devDependencies": {
    "@azure/functions": "^3.0.0",
    "@types/node": "^16.x",
    "@types/validator": "^13.7.17",
    "rimraf": "^5.0.0",
    "typescript": "^5.2.0-dev.20230626"
  }
```

listextionson SPFX code:
the httpClient is created in the onInit and is passed throuth the components until:
```
const response: HttpClientResponse = await props.httpClient.get(
   url.toString(),
   AadHttpClient.configurations.v1,
);
```
(we have some parameters in the url)

listExtension package.json:
```
  "dependencies": {
    "@microsoft/decorators": "1.17.3",
    "@microsoft/sp-core-library": "1.17.3",
    "@microsoft/sp-dialog": "1.17.3",
    "@microsoft/sp-listview-extensibility": "1.17.3",
    "@pnp/common": "^2.15.0",
    "@pnp/sp": "^3.16.0",
    "office-ui-fabric-react": "^7.204.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "tslib": "2.3.1"
  },
  "devDependencies": {
    "@microsoft/eslint-config-spfx": "1.17.3",
    "@microsoft/eslint-plugin-spfx": "1.17.3",
    "@microsoft/rush-stack-compiler-4.5": "0.5.0",
    "@microsoft/sp-build-web": "1.17.3",
    "@microsoft/sp-module-interfaces": "1.17.3",
    "@rushstack/eslint-config": "2.5.1",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "eslint": "8.7.0",
    "gulp": "4.0.2",
    "typescript": "4.5.5"
  }
```

### Question/Request

the azure function code:
```
const authHeader = req.headers.authorization;
const token = authHeader.split(" ")[1];

// some validation code...

const oboRequest: OnBehalfOfRequest = {
  oboAssertion: token,
  scopes: [
    `https://${spfiOption.sharePointTenantName}.sharepoint.com/.default`,
  ],
};

// config has authority, clientId, clientSecret
const cca = new ConfidentialClientApplication(config);
const authenticationResult = await cca.acquireTokenOnBehalfOf(oboRequest)

if (debug) {
  context.log("debug authenticationResult");
  context.log(authenticationResult);
}

// spfiOption has sharePointServerRelativeUrl, sharePointTenantName
spfiOption.sharePointServerRelativeUrl = checkedParams.relativeUrl;

const spfi = spfi().using(
  SPDefault({
    baseUrl: `https://${option.sharePointTenantName}.sharepoint.com/${option.sharePointServerRelativeUrl}`,
  }),
  BearerToken(authenticationResult.accessToken)
  NodeFetchWithRetry({
    replace: false, // do not replace other Observer like BearerToken
    retries: 3,
  })
);

const web = await spfi.web.select("Title", "Description", "Url")();

/// .... much more code to work...
```

this code runs in a normal azure function with no problem. But in a premium it works for around 1 hour, then the get web runs in the error:

`Error making HttpClient request in queryable [401] Unauthorized ::> {"error_description":"Invalid JWT token. The token is expired."}`

the jwt token is checked on <jwt.io> and it is **NOT** expired.

current solution is to restart the azure function. than everything works fine again for 1 hour.

any ideas?

I don't know really if this place is better or node-msal is better. Please let me know.

**Comment by bcameron1231** [comment]
I'm a bit confused by the code. You're taking the token from the authorization header of the request and setting it to the token variable. 

And you have just setting the Bearer token for the new request here
`  BearerToken(token),`

However, that's not actually creating an OBO flow. you should be pulling the token out of the OBO request result.

```
const cca = new ConfidentialClientApplication(config);

const authHeader = req.headers.authorization;
const token = authHeader.split(" ")[1];

// some validation code...

const oboRequest: OnBehalfOfRequest = {
  oboAssertion: token,
  scopes: [
    `https://${spfiOption.sharePointTenantName}.sharepoint.com/.default`,
  ],
};

// config has authority, clientId, clientSecret
const cca = new ConfidentialClientApplication(config);
const authenticationResult = await cca.acquireTokenOnBehalfOf(oboRequest)

var yourNewToken = authenticationResult.accessToken;
```

**Comment by vreezy** [comment]
Omg sorry. I merged all function into one code and missed to rename this variable. It wouldnt run once with the entry token because it has only the user_impersonation scope.

I edited the post

**Comment by bcameron1231** [comment]
As this is going to be difficult to test on our side without a bit of setup. Have you been able to compare the Token you get back from the OBO flow, and the Token being sent in the request from PnPJs? Could you check that for me.

**Comment by vreezy** [comment]
Can you tell me a way how i can wireshark a azure function to get the outgoing token?

I Build it in a dev enviroment (dev tenant /MSDN Subscription) i can give u read access. if this helps

**Comment by patrick-rodgers** [comment]
I would just log it into the azure function log for testing purposes (take that code out for prod) and you can see it in the debug dashboard for the function in the azure portal.

**Comment by vreezy** [comment]
Hey guys,
Thanks for Support. 
i opened this after THRE other (and me) coder inspected my code. No one seen a problem. Today another one inspected and found a problem. we could resolve the problem. 

@bcameron1231 The next Coffee goes on me if you send me a link or you visit us in germany

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
