### ISSUE TITLE
Why I'm not able to get the FileRef using following snippet, it's working fine if I'm directly running with It's own list? 

### ISSUE THREAD

**Issue by kapildropani** [pnp/pnpjs#2815]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.18.0

### Target environment

SharePoint Framework

### Additional environment details

The issue is only occurring while I'm trying to access the field via lookup (Page->Site Pages) field in Sharepoint Online.

Issue with code:
```
const data = await this._sp.web.lists.getByTitle("NavigationList").items.select('Title, Page/FileRef').expand("Page")();
```
I'm getting this following response: 
```
{
    "odata.error": {
        "code": "-1, Microsoft.SharePoint.SPException",
        "message": {
            "lang": "en-US",
            "value": "The query to field 'Page/FileRef' is not valid."
        }
    }
}
```

### Question/Request

Here is my package.json file:

```{
  "name": "intranet",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=16.13.0 <17.0.0 || >=18.17.1 <19.0.0"
  },
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@fluentui/react": "^8.106.4",
    "@loadable/component": "^5.15.3",
    "@microsoft/decorators": "1.18.0",
    "@microsoft/sp-component-base": "1.18.0",
    "@microsoft/sp-core-library": "1.18.0",
    "@microsoft/sp-dialog": "1.18.0",
    "@microsoft/sp-lodash-subset": "1.18.0",
    "@microsoft/sp-office-ui-fabric-core": "1.18.0",
    "@microsoft/sp-property-pane": "1.18.0",
    "@microsoft/sp-webpart-base": "1.18.0",
    "@pnp/graph": "^3.19.0",
    "@pnp/logging": "^3.18.0",
    "@pnp/queryable": "^3.18.0",
    "@pnp/sp": "^3.18.0",
    "gulp-livereload": "^4.0.2",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "tslib": "2.3.1"
  },
  "devDependencies": {
    "@microsoft/eslint-config-spfx": "1.18.0",
    "@microsoft/eslint-plugin-spfx": "1.18.0",
    "@microsoft/rush-stack-compiler-4.7": "0.1.0",
    "@microsoft/sp-application-base": "^1.18.0",
    "@microsoft/sp-build-web": "1.18.0",
    "@microsoft/sp-module-interfaces": "1.18.0",
    "@rushstack/eslint-config": "2.5.1",
    "@types/loadable__component": "^5.13.6",
    "@types/react": "17.0.45",
    "@types/react-dom": "17.0.17",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "eslint": "8.7.0",
    "eslint-plugin-react-hooks": "4.3.0",
    "gulp": "4.0.2",
    "typescript": "4.7.4"
  }
}
```

**Comment by patrick-rodgers** [comment]
Lots of details missing - what is the field "Page"?

I think you want `.select("Title", "Page/FileRef")` - though it might net out OK in the end your way.

What is navigation list? A custom list or one of the OOTB ones?

**Comment by kapildropani** [comment]
> Page->Site Pages

Page-> *Is a Site Pages default library in Sharepoint online to handle the pages*

**Comment by juliemturner** [comment]
What that error then means is that FileRef is not a valid field in the lookup list you linked to... I figured this out by creating rest calls right in the browser, but you can also use a browser plug in list SP Editor to query the target list to find out what the exact field names are internally to your target list.  Try Page/Id...if that works then you're lookup is working but your field FileRef is not.

**Comment by juliemturner** [comment]
Also, in the end this will be ok (because of the ^), but you should consider being consistent in your package versions.

`json
"@pnp/graph": "^3.19.0",
"@pnp/logging": "^3.18.0",
"@pnp/queryable": "^3.18.0",
"@pnp/sp": "^3.18.0",
```

**Comment by kapildropani** [comment]
> What that error then means is that FileRef is not a valid field in the lookup list you linked to... I figured this out by creating rest calls right in the browser, but you can also use a browser plug in list SP Editor to query the target list to find out what the exact field names are internally to your target list. Try Page/Id...if that works then you're lookup is working but your field FileRef is not.

Yes, It's working when I write query to the "Site Pages" library itself. It's fetching the file-path against FileRef key, please consider following code.

const data = await this._sp.web.lists.getByTitle("Site Pages").items.select('Title, FileRef')();

***Note:***  *I have replaced 'NavigationList' with 'Site Pages'*

But the same column not working when I'm accessing using Lookup column (Page) in my "NavigationList" which is referencing to "Site Pages" library.

Is there any way where I can add which columns I can access using Lookup in the pnp or sp?

**Comment by juliemturner** [comment]
Ok, but did you try Page/Id? or Page/Title? That's the other step you need to know you have the right field name from your source list.

**Comment by kapildropani** [comment]
> Ok, but did you try Page/Id? or Page/Title? That's the other step you need to know you have the right field name from your source list.

Yes, other values are working fine like page title, created or modifiedby etc.

**Comment by juliemturner** [comment]
Ok, well I'm out of ideas at the moment. Maybe someone else can think of something.

**Comment by kapildropani** [comment]
The following is working code, getting the Title from reference list "Site Pages"
***Working Code:***
```const data = await this._sp.web.lists.getByTitle("Navigation").items.select('Title, Page/Title').expand("Page")();```
***Response: ***
<img width="682" alt="image" src="https://github.com/pnp/pnpjs/assets/143097045/a7104f94-e0d6-420a-90a6-f71bdb1df41b">

***Note: *** - What I want to get is URL like */SitePages/<page-name>.aspx* etc. 

Thanks

**Comment by patrick-rodgers** [comment]
Not every field is available via expand, you can usually tell what is when you edit the lookup field:

![image](https://github.com/pnp/pnpjs/assets/13154702/6408309c-df80-4894-a02a-0bef45cf5fd2)

**Comment by kapildropani** [comment]
> Not every field is available via expand, you can usually tell what is when you edit the lookup field:
> 
> ![image](https://user-images.githubusercontent.com/13154702/278085765-6408309c-df80-4894-a02a-0bef45cf5fd2.png)

Is there any way to add field somewhere so that can be available for the lookup. In my case I want URL of Page in Site Pages library?

**Comment by juliemturner** [comment]
I've had good luck with calculated fields, but I don't know that you could create a calculated field with the file name in it. Honestly, I think your better off getting a list of ID's from the page library that you need to backfill the navigation and then do a batch call to get the data... it'll take 2 passes but that would be easier. The other answer obviously is just store the Page URL instead of using a lookup field.

**Comment by bcameron1231** [comment]
Closing this issue as [answered](https://github.com/pnp/pnpjs/issues/2815#issuecomment-1779682042). If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
