### ISSUE TITLE
Type 'null' is not assignable to type 'SPFI'.

### ISSUE THREAD

**Issue by annafernandezh** [pnp/pnpjs#2816]
### What version of PnPjs library you are using

3.x

### Minor Version Number

^3.19.0

### Target environment

SharePoint Framework

### Additional environment details

Using the common package of Node JS for my development environment

### Question/Request

I am trying to configure the pnpjs-config.ts file adding the same code as it is posted in the [Pnp documentation guide](https://pnp.github.io/pnpjs/concepts/project-preset/). 
But as soon as I write it, or when I run gulp build, I get the error
`error TS2322: Type 'null' is not assignable to type 'SPFI'.`

I believe it is the same code that is suggested:
```
import { WebPartContext } from "@microsoft/sp-webpart-base";
import { LogLevel, PnPLogging } from "@pnp/logging";
import { SPFI, SPFx, spfi } from "@pnp/sp";

var _sp : SPFI = null;

export const getSP = (context?: WebPartContext): SPFI => {
    if (context != null) {
      //You must add the @pnp/logging package to include the PnPLogging behavior it is no longer a peer dependency
      // The LogLevel set's at what level a message will be written to the console
      _sp = spfi().using(SPFx(context)).using(PnPLogging(LogLevel.Warning));
    }
    return _sp;
  };
```

Any help would be extra helpful,
Thanks in advance!

**Comment by annafernandezh** [comment]
Just fixed with the help of the latest [Microsoft documentation](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts#add-a-project-configuration-file)!
```
/* eslint-disable eqeqeq */
/* eslint-disable @rushstack/no-new-null */
/* eslint-disable @typescript-eslint/no-non-null-assertion */
/* eslint no-var: 0 */
import { WebPartContext } from "@microsoft/sp-webpart-base";

// import pnp and pnp logging system
import { spfi, SPFI, SPFx } from "@pnp/sp";
import { LogLevel, PnPLogging } from "@pnp/logging";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/batching";

var _sp: SPFI | null = null;

export const getSP = (context?: WebPartContext): SPFI => {
  if (context != null) {
    //You must add the @pnp/logging package to include the PnPLogging behavior it is no longer a peer dependency
    // The LogLevel set's at what level a message will be written to the console
    _sp = spfi().using(SPFx(context)).using(PnPLogging(LogLevel.Warning));
  }
  return _sp!;
};
```

**Comment by juliemturner** [comment]
Glad you found the answer! The link to that information is also in our [documentation](https://pnp.github.io/pnpjs/concepts/project-preset/). I did make a slight adjustment to your comment for anyone who finds this post later, as you referenced "Microsoft Documentation", which I totally understand because the link you found was on the learn site, but I wanted to clarify because this is not a Microsoft sponsored solution this is a community resource, and I don't want people getting confused.
