### ISSUE TITLE
Sub Site Creation Permission in SharePoint Online

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2818]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.13.0

### Target environment

SharePoint Framework

### Additional environment details

SPFx with React, SharePoint Online, Sub Site Create

### Question/Request

Hello Everyone,

I have created an SPFx solution for custom development.

I need to create a sub-site under the current site where the SPFx application is added.

I have taken reference from the below link,
https://pnp.github.io/pnpjs/sp/webs/#add-web

Below is my code snippet of subsite creation

```
const sp: SPFI = getSP();

await sp.web.webs.add("Contoso", "contoso", "Contoso Description", "STS", 1033, true).then((res) => {
    console.log("Sub Site Created", res);
}).catch((err) => {
    console.log("Error in Sub Site Creation", err);
});
```

The sub-site is created successfully with my user. But if I create a sub-site with a test user it throws me an error. Can anyone help me with which permission should I give to the test user?

Below are the default groups which automatically created while I created the site. Can anyone help me with which group I add test user?

Test Site Owners
Test Site Members
Test Site Visitors

Thanks

**Comment by patrick-rodgers** [comment]
Owners group.

**Comment by bhoomesh-spe** [comment]
@patrick-rodgers - Thanks for the reply. Either I need to add a user in the Owner group or give Full Control permission to the user. Hope that is fine.

**Comment by juliemturner** [comment]
@bhoomesh-spe - I'm just going to throw out here that you really need to rethink using sub-sites... this is something you should be working to move away from especially in SharePoint online.

**Comment by bhoomesh-spe** [comment]
@juliemturner - Can you please elaborate?

**Comment by juliemturner** [comment]
@bhoomesh-spe -- Sub-sites are not supported in modern SharePoint sites. You can still create them with a modern communication site but it's a remnant from classic sites. I don't know that there is an official announcement, but you should consider them deprecated.

**Comment by bhoomesh-spe** [comment]
@juliemturner - Is subsite creation support available for the modern team site?

**Comment by juliemturner** [comment]
No.

**Comment by bhoomesh-spe** [comment]
@juliemturner - Currently above code is able to create a new subsite. If the user has Full Control permission for that site.

**Comment by juliemturner** [comment]
Yes, you can do it in code, no you shouldn't. At one point you couldn't do it through the UI (which was why I responded no), but it appears that has changed, when I can't exactly say as I am not in the UI doing these things all that frequently. I can tell you with 100% certainty that subsites are not going to be supported going forward and you should reconsider what you're doing. That said, I make suggestions, you make decisions.

**Comment by bcameron1231** [comment]
For clarity, Manage Web permission is the required in order to call the _api/web/webs endpoint.

Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
