### ISSUE TITLE
Uploading chunked file causes 'Unhandled Exception: TypeError [ERR_INVALID_URL]: Invalid URL'

### ISSUE THREAD

**Issue by Leo-at-PR** [pnp/pnpjs#2819]
### What version of PnPjs library you are using

3.x

### Minor Version Number

19.0

### Target environment

All

### Additional environment details

Using NodeJS with [node-sp-auth](https://www.npmjs.com/package/node-sp-auth) for authentication.

### Question/Request

Hi all,

I'm trying to upload a large file using the `addChunked` method to one of my Sharepoint folders. However, when I do this, I get the following stack trace:

```js
file:///(.../node_modules/@pnp/core/timeline.js:145
                        throw Error(`Unhandled Exception: ${args[0]}`);
                              ^

Error: Unhandled Exception: TypeError [ERR_INVALID_URL]: Invalid URL
    at Proxy.<anonymous> (.../node_modules/@pnp/core/timeline.js:145:31)
    at Proxy.error (.../node_modules/@pnp/core/timeline.js:131:23)
    at Timeout._onTimeout (.../node_modules/@pnp/queryable/queryable.js:132:22)
```

for Authentication, using node-sp-auth, I am doing the following:
```js
const spCreds = {
    username: process.env.SHAREPOINT_USERNAME,
    password: process.env.SHAREPOINT_PASSWORD,
};
const siteUrl = process.env.SITE_URL; // something like "example.sharepoint.com/sites/Example_Site"

await getAuth(siteUrl, spCreds).then((options) => {
    let headers = options.headers;
    const sp = spfi().using(InjectHeaders(headers));
});
```

Then, trying to upload the file:
```js
const fileName = "some-file-name.mp4";
const file = await getFile("/some local folder/" + fileName); // returns a `Blob` from a read stream
const result = await sp.web
    .getFolderByServerRelativePath(process.env.FOLDER_PATH) // something like "Shared Documents/Folder One/Folder Two/"
    .files.addChunked(fileName, file, () => console.log("working..."), true, 10 * 1024 * 1024)
    .catch((error) => {
        throw new Error(error);
    });
```

I haven't been able to fix this and I also haven't seen anywhere online that overcomes this issue. I have tried modifying the url paths (e.g. removing/adding trailing and following `/`s, changing the site url to the base site (removing the '/sites/...') and then setting appending the '/sites/...' to the folder path), even encoding the env values, and so on, but still no luck. I made sure all paths and the username & password are all correct.

Thanks in advance!

**Comment by patrick-rodgers** [comment]
I can't tell since this is all the information I have, but this line needs to be an absolute url and you indicate it is not. Please try including ` https://` and let us know if that helps.

```
const siteUrl = process.env.SITE_URL; // something like "example.sharepoint.com/sites/Example_Site"
```

**Comment by Leo-at-PR** [comment]
> I can't tell since this is all the information I have, but this line needs to be an absolute url and you indicate it is not. Please try including ` https://` and let us know if that helps.

Hi, my bad for that. The `https://` is already included. Please see here:
```env
SHAREPOINT_USERNAME=...
SHAREPOINT_PASSWORD=...
SITE_URL=https://example.sharepoint.com/sites/Example_Site
# The nested folders have varying casing and spaces, as shown below
FOLDER_PATH="Shared Documents/Folder One/foldertwo/folderthree/folderfour"
```

**Comment by patrick-rodgers** [comment]
You need at some point in node to give our library the full url. I just realized you never set that, it is only used for the auth call. You can [see here](https://github.com/pnp/pnpjs/blob/version-3/debug/launch/setup.ts#L10C6-L10C6) where we do it for testing. Just pass the absolute url into the `spfi({abs url here})` factory.

In node we have no way to "discover" where you want the call to go.

**Comment by Leo-at-PR** [comment]
Ah, well spotted, thanks. However, now I am getting another weird error, or rather, the program just exists. Here's the snippet:
```js
async function uploadFile() {
    try {
        const fileName = "some-file-name.mp4";
        const file = await getFile("/some local folder/" + fileName); // returns a `Blob` from a read stream

        console.log("uploading file...");
        const result = await sp.web
            .getFolderByServerRelativePath(process.env.FOLDER_PATH)
            .files.addChunked(fileName, file, () => console.log("working..."), true, 10 * 1024 * 1024);
            .catch((error) => { throw new Error("error uploading file: " + error) });
        
        console.log("getting id...");
        const id = result.data.UniqueId;        
        console.log("id: " + id);
    } catch (error) {
        console.log("An error occured: " + error);
    }
}
```
Not sure what is causing this. No error is shown or anything - the text "uploading file..." is logged to the console, then the program just exits? I also tried removing `await` from `const result = ...` and putting it in `const id = (await result).data.UniqueID`. If I do this, the text "getting id..." is logged, then the program stops.

It seems any time I try to await the upload, the program exits. Bear in mind, **neither** times does the "working..." text (from the `addChunked` method's progress function) get printed.

I don't think (?) my code is incorrect.
