### ISSUE TITLE
[Question] IFileInfo for fileFromServerRelativePath

### ISSUE THREAD

**Issue by fonbrauzen** [pnp/pnpjs#2820]
### What version of PnPjs library you are using

3.x

### Minor Version Number

19

### Target environment

SharePoint Framework

### Additional environment details

Node 18.18.2, SPFX 1.18, TS 4.7.4

### Question/Request

Situation: I need to get an UniqueId property of SP List Item Attachment file.

**REST API**
```TypeScript
const request = await fetch("SITE_URL/_api/web/GetFileByServerRelativeUrl('PATH_TO_FILE')",  {
            method: "GET",
            headers: {
              "Content-Type": "application/json",
              "Accept": "application/json"
            }});
            const response = await request.json();
response.UniqueId //needed value
```
**pnp.js:**
According to pnp.js documentation (under the hood using the same method as above):
```TypeScript
const file = fileFromServerRelativePath(sp.web, url);
```
How exactly could I receive the IFileInfo for this file in pnp.js?
I just see lots of methods but nothing like properties I could receive via REST API...

**Comment by patrick-rodgers** [comment]
Should do it:

```
const file = fileFromServerRelativePath(sp.web, url)();
```

But any reason you aren't using the fluent chain? `sp.web.getFileByServerRelativePath("/sites/dev/documents/blah.txt")()`

**Comment by fonbrauzen** [comment]
Well, I just followed the [docs](https://pnp.github.io/pnpjs/sp/files/#filefromserverrelativepath). Maybe would be nice to add this case there...
