### ISSUE TITLE
Failed to parse URL from at new Request

### ISSUE THREAD

**Issue by zionsg** [pnp/pnpjs#2823]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.15.0  ]

Please specify what version(s) of SharePoint you are targeting: [  Sharepoint Online       ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

Followed tutorial at https://pnp.github.io/pnpjs/v2/nodejs-support/ with code as follows:

```
const { SPFetchClient } = require('@pnp/nodejs-commonjs');
const { sp } = require('@pnp/sp-commonjs');

sp.setup({
    sp: {
        fetchClientFactory: () => {
            return new SPFetchClient(
                'https://xxxxx.sharepoint.com/sites/yyyyy', 
                'MY_CLIENT_ID', 
                'MY_CLIENT_SECRET'
            );
        },
    },
});

async function makeRequest() {
    let w = await sp.web();
    console.log(JSON.stringify(w, null, 2));
}

makeRequest();
```

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

Exception thrown:

```
TypeError: Failed to parse URL from
    at new Request (node:internal/deps/undici/undici:7043:19)
    at mergeHeaders (/home/user/sharepoint-test/node_modules/@pnp/common-commonjs/net.js:9:20)
    ... 5 lines matching cause stack trace ...
    at __awaiter (/home/user/sharepoint-test/node_modules/tslib/tslib.js:113:16)
    at SPHttpClient.fetch (/home/user/sharepoint-test/node_modules/@pnp/sp-commonjs/sphttpclient.js:29:38)
    at /home/user/sharepoint-test/node_modules/@pnp/odata-commonjs/pipeline.js:167:24 {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at new URL (node:internal/url:560:13)
      at new Request (node:internal/deps/undici/undici:7041:25)
      at mergeHeaders (/home/user/sharepoint-test/node_modules/@pnp/common-commonjs/net.js:9:20)
      at SPHttpClient.<anonymous> (/home/user/sharepoint-test/node_modules/@pnp/sp-commonjs/sphttpclient.js:39:51)
      at step (/home/user/sharepoint-test/node_modules/tslib/tslib.js:143:27)
      at Object.next (/home/user/sharepoint-test/node_modules/tslib/tslib.js:124:57)
      at /home/user/sharepoint-test/node_modules/tslib/tslib.js:117:75
      at new Promise (<anonymous>)
      at __awaiter (/home/user/sharepoint-test/node_modules/tslib/tslib.js:113:16) {
    input: '',
    code: 'ERR_INVALID_URL'
  }
}
```

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

The exception is triggered by `mergeHeaders(headers, options.headers);` in https://github.com/pnp/pnpjs/blob/version-2/packages/sp/sphttpclient.ts#L50C48-L50C48 - seems that `options.headers` was `{}`.

Traced the error to https://github.com/pnp/pnpjs/blob/version-2/packages/common/net.ts#L33 where an empty string is being passed for the url to `new Request()`. In this case, the `source` was `{}` due to the call above.

```
export function mergeHeaders(target: Headers, source: HeadersInit): void {

    if (objectDefinedNotNull(source)) {
        const temp = new Request("", { headers: source });
        temp.headers.forEach((value: string, name: string) => {
            target.append(name, value);
        });
    }
}
```

**Comment by patrick-rodgers** [comment]
Version 2 is no longer supported and we will not be publishing any updates for those packages. Is there something blocking you from moving to version 3?

**Comment by zionsg** [comment]
2 main blockers for my company.

Firstly, we are using CommonJS modules in our Node.js projects and not using TypeScript. It is mentioned in https://pnp.github.io/pnpjs/transition-guide/#dropping-commonjs-packages that V3 drops support for CommonJS modules but the workaround requires TypeScript.

Secondly, we need to support a variety of SharePoint versions for our clients. It is mentioned in https://pnp.github.io/pnpjs/getting-started/#getting-started-with-sharepoint-framework that "If you are running in 2016 or 2019 on-premises you will need to use [version 2](https://pnp.github.io/pnpjs/v2/SPFx-on-premises/) of the library."

**Comment by batovpasha** [comment]
@zionsg Hi! Thanks for describing this issue, I've faced it as well. 
What I found: it occurs during the migration to Node.js v18 where the [Request](https://nodejs.org/docs/latest-v18.x/api/globals.html#request) API becomes enabled by default, under the Node.js v18 you should enable it explicitly.
So, disabling this API using the `--no-experimental-fetch` CLI flag helped me.

**Comment by zionsg** [comment]
@batovpasha Thanks, the `--no-experimental-fetch` CLI flag worked!

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
