### ISSUE TITLE
reused terms problem: getAllChildrenAsOrderedTree fails. term/children endpoint does not rerurn reused terms

### ISSUE THREAD

**Issue by dorin2006** [pnp/pnpjs#2827]
### Major Version

3.x

### Minor Version Number

17

### Target environment

SharePoint Framework

### Additional environment details

Sharepoint online, SPFx

### Expected or Desired Behavior

I try to load term set with reused terms, reused terms are not returned :(

### Observed Behavior

getAllChildrenAsOrderedTree throws exception;

term/children endpoint works but does not return reused terms 

### Steps to Reproduce

create a term set with reused terms and try to load terms with reused child terms

**Comment by dorin2006** [comment]
hello people! 

I've found a way to make it work, kudos to bamboo:
https://bamboosolutions.com/blog/sharepoint-term-store-3/

/getlegacychildren REST endpoint fixes the problem with retrieving term items that are reused.

hope this helps to others facing the same issue and pnp team will extend pnp api using this REST endpoint to return reused terms

**Comment by bcameron1231** [comment]
Thanks for letting us know of your resolution!

**Comment by dorin2006** [comment]
yep but please do not mark it as completed - 

I've found a workaround via sp rest api, - would be awesome to have this fixed in the next release of pnp js

**Comment by bcameron1231** [comment]
Hi. We'll discuss internally, however, it's an undocumented endpoint. We've been trying to avoid using undocumented endpoints (from a support perspective).
