### ISSUE TITLE
How to update default value of a lookup field

### ISSUE THREAD

**Issue by pheidler** [pnp/pnpjs#2828]
### What version of PnPjs library you are using

2.x (No longer supported)

### Minor Version Number

0.6

### Target environment

All

### Additional environment details

React SPFx

### Question/Request

I'm unable to set the default value for a lookup field. What's the correct way to reference the item you want set as the default?

Here's the code: 
```
await web.fields
          .getByInternalNameOrTitle("Field_Name")
          .update(
            {
              DefaultValue: "(What goes here?)"
            },
            "SP.FieldLookup"
          );
```

**Comment by juliemturner** [comment]
Have you tried the ID of the item the lookup references?

**Comment by juliemturner** [comment]
I googled it for you... “1;#test1” where the 1 is the id ;# and then the title of the item (most likely) unless you used another field to display.

**Comment by pheidler** [comment]
That isn't working either, but it sounds like I've gone looking in the wrong place. I'll keep googling, thanks for your help.

**Comment by juliemturner** [comment]
If it were me, I'd do it in the UI, using the network tab of the dev tools to sniff out how it updates and then reverse engineer that.

**Comment by pheidler** [comment]
@juliemturner Will do. Thanks :)
