### ISSUE TITLE
I have created new column named as 'Company' of type people. Now, I'm trying select that component and Pnp V3 not allowing me?

### ISSUE THREAD

**Issue by kapildropani** [pnp/pnpjs#2830]
#Following is the sample code which is simply fetching the items from Document Library. It's working fine without 'Company' column. **I have already test the field name of 'Company' It's a Company**.

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   pnp v3     ]

Please specify what version(s) of SharePoint you are targeting: [ 16.0.0.12006 ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*Company should fetch the users or group I have added against each document or item*

### Observed Behavior
The response I'm getting using this url ***<domain>/_api/web/lists/getByTitle('Documents')/items?%24filter=IsFeatured+eq+1&%24select=Title%2C+FileLeafRef%2CFileRef%2CFile%2CCompany&%24expand=File***
 
**Response** <img width="776" alt="image" src="https://github.com/pnp/pnpjs/assets/143097045/be329404-ab27-4914-8aeb-af52ff61483d">

**Targeted List: (Document List):** 
<img width="854" alt="image" src="https://github.com/pnp/pnpjs/assets/143097045/005fa4d3-6bc1-4b42-be55-b75688ffa1cc">

### Steps to Reproduce
*1. Create a new column of type (People or Group)*
*2. Query list using pnp versoin 3 instance to Document list a code given above*

Please help #asap Thanks

**Comment by bcameron1231** [comment]
Hi. As the error message states, you must expand the query string to select from Company. Company is a People or Group field, also known as a Lookup field. In order to select values from a look field, you have to expand the Column, and select the fields you want. 

We have a example of this in our docs
https://pnp.github.io/pnpjs/sp/items/#retrieving-lookup-fields

**Example**
`  await sp.web.lists.getByTitle("ListName").items.select('Company/Title').expand('Company')()`

**Comment by kapildropani** [comment]
> Hi. As the error message states, you must expand the query string to select from Company. Company is a People or Group field, also known as a Lookup field. In order to select values from a lookup field, you have to expand the field, and select the field values you want.
> 
> We have a example of this in our docs https://pnp.github.io/pnpjs/sp/items/#retrieving-lookup-fields
> 
> **Example** ` await sp.web.lists.getByTitle("ListName").items.select('Company/Title').expand('Company')()`

***I have tried this and it works but I have little question. May expand query over multiple lookups? How can I achieve this may I write expand like following? ```.expand("Company, File")```***

```const documents: IDocument[] = await this._sp?.web?.lists
        .getByTitle("Documents")
        .items.filter("IsFeatured eq 1")
        .select("Title, FileLeafRef, FileRef, Created, Company/Title")
        .expand("Company")();```

**Comment by bcameron1231** [comment]
Yes. Just add what fields you want to the expands the expands. expand() is just an array of strings. See below.

    .getByTitle("Documents")
        .items.filter("IsFeatured eq 1")
        .select("Title, FileLeafRef, FileRef, Created, Company/Title")
        .expand("Company", "WhateverFieldYouNeedToExpand",)();```

**Comment by kapildropani** [comment]
> Yes. Just add what fields you want to the expands. expand() is just an array of strings. See below.
> 
> ```
> .getByTitle("Documents")
>     .items.filter("IsFeatured eq 1")
>     .select("Title, FileLeafRef, FileRef, Created, Company/Title")
>     .expand("Company", "WhateverFieldYouNeedToExpand")();```
> ```

Thanks again for quick response. It works for me! :)

**Comment by kapildropani** [comment]
> Yes. Just add what fields you want to the expands. expand() is just an array of strings. See below.
> 
> ```
> .getByTitle("Documents")
>     .items.filter("IsFeatured eq 1")
>     .select("Title, FileLeafRef, FileRef, Created, Company/Title")
>     .expand("Company", "WhateverFieldYouNeedToExpand")();```

Thanks again for quick response. It works for me! :)
