### ISSUE TITLE
Is there any way to make aliases of list columns in the select statement such as *.select("Id as myid, name as myname, created as announcementDate")

### ISSUE THREAD

**Issue by kapildropani** [pnp/pnpjs#2837]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.18.0

### Target environment

SharePoint Framework

### Additional environment details

I'm using Sharepoint online framework, developing webpart for some specific feature its quite essential for me to aliasing the column names. Here is the sample code?

```const announcements = await this._sp.web.lists
        .getByTitle(AnnoucementsList)
        .items
        .filter(`IsFeatured eq 1`)
        .select(
          `${strings.ListColumnAnnouncementTitle} as Title,${strings.ListColumnAnnouncementDetails} as Details,${strings.ListColumnAnnouncementButton} as BtnText,Link,Created,IsFeatured`
        )<IAnnouncement[]>();```

### Question/Request

It's just a question if there is any work-around to aliasing column names?

**Comment by juliemturner** [comment]
Not in the select. Since the column names are simply types, can you explain why it's essential, i.e. what's your use case, I might be able to offer a better answer.

**Comment by kapildropani** [comment]
> Not in the select. Since the column names are simply types, can you explain why it's essential, i.e. what's your use case, I might be able to offer a better answer.

I'm trying to dynamically fetch the **_'Title' for en-US_** and **_'TitleArabic' for ar-SA_** but column name must remained same as **'Title'** in either case.

I can make it conditionally but want to know the better way?

Thanks

**Comment by juliemturner** [comment]
Why does the title need to be the same in either case... I'm not following that logic.

**Comment by kapildropani** [comment]
> Why does the title need to be the same in either case... I'm not following that logic.

Because, I don't want to put a language condition I want formatted data from the query not parse item by item-by-item and change conditionally?

Thanks

**Comment by juliemturner** [comment]
Ok, I have a theory of what you're trying to do.... in that case (and this is what I do almost all the time anyway because I want to map date fields into actual javascript Date objects) you'd have a MyItemListObject type and a MyItem type... after you fetch MyItemListObject[] you need to map that into a new array of MyItem[] manipulating the object as you go, so in this case myItem.Title = myListItemObject.Title || myListItemObject.TitleArabic etc...

**Comment by kapildropani** [comment]
> Ok, I have a theory of what you're trying to do.... in that case (and this is what I do almost all the time anyway because I want to map date fields into actual javascript Date objects) you'd have a MyItemListObject type and a MyItem type... after you fetch MyItemListObject[] you need to map that into a new array of MyItem[] manipulating the object as you go, so in this case myItem.Title = myListItemObject.Title || myListItemObject.TitleArabic etc...

What I'm doing is currently mapping the keys but there are only few columns. I have an other list as well with so many columns. 

Here is what I'm doing now?

```
private mapFields = async (
    items: IAnnouncement[]
  ): Promise<IAnnouncement[]> => {
    if (items.length) {
      const finalItems: IAnnouncement[] = [];
      items.forEach((item: IAnnouncement) => {
        if (item.CoverPicture) {
          const pic = JSON.parse(item.CoverPicture);
          item.CoverPicture = `${pic.serverUrl}${pic.serverRelativeUrl}`;
        }

        finalItems.push({
          Id: item.Id,
          CoverPicture: item.CoverPicture ?? "",
          Title: item[
            strings.ListColumnAnnouncementTitle as keyof IAnnouncement
          ] as string,
          Details: item[
            strings.ListColumnAnnouncementDetails as keyof IAnnouncement
          ] as string,
          ButtonText: item[
            strings.ListColumnAnnouncementButton as keyof IAnnouncement
          ] as string,
          Link: item.Link,
          Created: item.Created,
          IsFeatured: item.IsFeatured,
        });
      });

      return finalItems;
    }
    return [];
  };
  ```

**Comment by juliemturner** [comment]
The SharePoint and Graph REST endpoint only returns an array of objects with the lists internal field names and their corresponding values. There is no way to ask the server, via a rest call, to do the manipulation you're describing. You need to take the json object you get back and manipulate it into the object you want to work with. This isn't really a language thing this is you have an object that looks like x but you want an object that looks like y.

**Comment by kapildropani** [comment]
> The SharePoint and Graph REST endpoint only returns an array of objects with the lists internal field names and their corresponding values. There is no way to ask the server, via a rest call, to do the manipulation you're describing. You need to take the json object you get back and manipulate it into the object you want to work with. This isn't really a language thing this is you have an object that looks like x but you want an object that looks like y.

@juliemturner Thanks
