### ISSUE TITLE
How to create custom section layout options for SharePoint online modern site pages?

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2839]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.13.0

### Target environment

SharePoint Framework

### Additional environment details

SPFx with React, SharePoint Online

### Question/Request

Hello Everyone,

SharePoint provides default layout options below as mentioned in the screenshot. How can we create custom section layout options as per our needs? If there are any ways to create custom section layout options then please let me know your thoughts on the same.

![image (1)](https://github.com/pnp/pnpjs/assets/99523338/be39bc40-bbef-4351-8415-d12eeb368f40)

Can anyone help me with the same?

Thanks

**Comment by juliemturner** [comment]
Here's some references: 
Docs: https://pnp.github.io/pnpjs/sp/clientside-pages/
Additional Docs: https://pnp.github.io/pnpjs/concepts/adv-clientside-pages/

**Comment by patrick-rodgers** [comment]
I do not believe custom section layouts is a supported feature.

**Comment by juliemturner** [comment]
My apologies I think I misunderstood. I thought you wanted to build a section manually not that you wanted to build a different layout. Yes I agree with Patrick that wouldn't be supported.
