### ISSUE TITLE
addUsingPath is missing EnsureUniqueFileName=true option

### ISSUE THREAD

**Issue by mdissel** [pnp/pnpjs#2840]
### Target environment

SPFX framework

### Enhancement Idea

the interface IAddUsingPathProps is missing an option to set the parameter EnsureUniqueFileName=true

also the AutoCheckoutOnInvalidData is missing

**Comment by bcameron1231** [comment]
I investigated this parameter, while documented, is breaking my API when I use it. 

We'll take a look further.

**Comment by mdissel** [comment]
> I investigated this parameter, while documented, is breaking my API when I use it.

I checked what parameters Sharepoint is using when you upload a file with the same name. Keep both with add this parameter (without the overwrite) to the request

> We'll take a look further.

Thanks!
