### ISSUE TITLE
How to set view as default view and re-arrange column under that view?

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2844]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.13.0

### Target environment

SharePoint Framework

### Additional environment details

SPFx with React, SharePoint Online

### Question/Request

Hello Everyone,

I need to set the view as a default view under the SharePoint list. Also, I need to add some columns in that view and re-arrange the order of the columns in that view.

I have found the below link for the set view as the default view in the SharePoint list. Is that the correct link?
https://pnp.github.io/pnpjs/sp/views/#setviewxml

Thanks

**Comment by bcameron1231** [comment]
Hi. Yes, using the View XML you can set the view to be Default, set your order of columns, etc. 

Additionally, if you already have views that you want to make default, you could use the Update method and set Default=true. If you need to move columns of an existing view, you can use the Move() method.
