### ISSUE TITLE
Updating CanvasContent1 for a Modern Page with validateUpdateListItem

### ISSUE THREAD

**Issue by CodingSinceThe80s** [pnp/pnpjs#2845]
### What version of PnPjs library you are using

3.x

### Minor Version Number

18.0

### Target environment

SharePoint Framework

### Additional environment details

Application Customizer working with SharePoint online in a Modern Communication Site (English template).

### Question/Request

Hi folks,

would really appreciate some input on this one: I am getting a page item for a newly created modern page from a template and currently only updating a custom managed metadata field using validateUpdateListItem and this is working fine (see code below). 
```TypeScript
//Current code - Working
const pageItem = sp.web.lists
                                       .getByTitle("Site Pages")
                                       .items
                                       .getById(pageId);
pageItem.validateUpdateListItem([{
                            FieldName: "custom_taxonomy_field",
                            FieldValue: `${termName}|${termId}`}]);
```
Now I want to also update CanvasContent1 because I have specific placeholder values to replace (I encode those as [some-placeholder] in the webparts themselves - note that I am using only OOTB-Webparts here).

If I get the old CanvasContent1 value as a string, do a replaceAll(currentCanvasContent1, "[some-placeholder]") then change the above code to below state it stops working and does not update ANY field. 
```TypeScript
//Changed code - Not working
const pageItem = sp.web.lists
                                      .getByTitle("Site Pages")
                                       .items
                                       .getById(pageId);
const transformedCanvasContent:string = currentCanvasContent1.replaceAll("[some-placeholder]","My String");
pageItem.validateUpdateListItem([{
                            FieldName: "custom_taxonomy_field",
                            FieldValue: `${termName}|${termId}`},
                            {
                              FieldName: "CanvasContent1",
                              FieldValue: transformedCanvasContent
                            }
                          ]);
```
How can I accomplish my goal of replacing CanvasContent1? I have looked into the IClientsidePage object but it does not seem to contain a way to update the entire contents, just sections, webparts etc. Perhaps I am missing something obvious here...

**Comment by juliemturner** [comment]
Updating that stuff is very tricky and took a lot of reverse engineering. I would look at the source code for how we're doing it https://github.com/pnp/pnpjs/blob/version-3/packages/sp/clientside-pages/types.ts

**Comment by CodingSinceThe80s** [comment]
Hi @juliemturner and thanks for the blazing fast reply 👍 I was afraid it was going to come down to that, but this confirms my suspicions, was hoping I just missed something. I'll get started then and see what I can find out and post my solution here.

**Comment by juliemturner** [comment]
I'm happy to have you find your solution but in general we know that this is not a supported way to create pages and are awaiting an official pages API. So, while we have the client-side pages reverse engineered solution in this library to support a huge gap that we all were feeling, I want to make sure we're not misleading people about the dangers in using an unsupported solution, i.e. that it could break at any time. Please see this post for more details: https://pnp.github.io/pnpjs/concepts/adv-clientside-pages/

**Comment by CodingSinceThe80s** [comment]
Yeah I know this is walking a fine line, but generally I noticed that the speed of Microsoft creating (documented) APIs is way lower than the change rate for those APIs, so I hope this feature request is heard. If I can support a UserVoice etc. for doing so I will

**Comment by CodingSinceThe80s** [comment]
All right I hear you, I am going to close this issue then and thanks again for the feedback.
