### ISSUE TITLE
ItemId is missing in IListItemFormUpdateValue interface

### ISSUE THREAD

**Issue by mdissel** [pnp/pnpjs#2847]
### Target environment

SharePoint Framework

### Enhancement Idea

The ItemId property is missing in the IListItemFormUpdateValue
see https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#create-list-item-in-a-folder

**Comment by patrick-rodgers** [comment]
Thanks, we accept PRs as well which can help get small changes like this in.

**Comment by mdissel** [comment]
Thanks!
