### ISSUE TITLE
How to set custom view as default view in SharePoint Online list?

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2848]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.13.0

### Target environment

SharePoint Framework

### Additional environment details

SharePoint Framework

### Question/Request

Hello Everyone,

I have created a SharePoint list. I had taken reference from the below link
https://pnp.github.io/pnpjs/sp/lists/#ensure-that-a-list-exists-by-title

I have added new fields under that list with taken reference from the below link
https://pnp.github.io/pnpjs/sp/fields/#add-a-new-field

I have created a new view using the below code.

```
import { spfi } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/views";

const sp = spfi(...);

const list = sp.web.lists.getByTitle("Test List");

// create a new view with default fields and properties
const result = await list.views.add("Custom View");
```

Now, I need to set the newly created custom view as the default view. So, I have found the below link 
https://pnp.github.io/pnpjs/sp/views/#setviewxml

Can I set the view as a default view without using XML schema? 

Thanks

**Comment by tavikukko** [comment]
Hi,
You need to update the properties of the **view** and set **DefaultView** to **true**

```typescript
sp.web.lists.getByTitle('TheList').views.getById('ce445b27-fcf6-4df0-9de9-86456ecd4189').update({ DefaultView: true}) 
```

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
