### ISSUE TITLE
Taxonomy terms() function returns a variable number of terms

### ISSUE THREAD

**Issue by Srutututu** [pnp/pnpjs#2849]
### Major Version

3.x

### Minor Version Number

3.20.1

### Target environment

SharePoint Framework

### Additional environment details

I'm using SPFX version 1.17.4 with pnpJS version 3.20.1

My dependencies from package.json:

![image](https://github.com/pnp/pnpjs/assets/47721846/dbb8d45b-77cb-468c-9069-97e4ec627d7b)

### Expected or Desired Behavior

I expect the method to return all terms without parent-child relationships (both active and deprecated)

### Observed Behavior

The method is returning either all top level terms (directly beneath the termset, both active and deprecated):

![image](https://github.com/pnp/pnpjs/assets/47721846/84fe94ed-5cc7-435f-9018-d2a12f706d5e)

or all of them, meaning all top level and child terms of active and deprecated terms.

![image](https://github.com/pnp/pnpjs/assets/47721846/93797a4b-caad-4642-85a9-1bc13e96794a)

### Steps to Reproduce

This is how my termset named "A" looks like:

![image](https://github.com/pnp/pnpjs/assets/47721846/242976bb-11f2-426c-a229-5ef334ba1d86)

This is how I setup my pnpJS package:

SPFI init:
```js
import { WebPartContext } from "@microsoft/sp-webpart-base";
import { spfi, SPFI, SPFx } from "@pnp/sp";
import { LogLevel, PnPLogging } from "@pnp/logging";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/batching";
import "@pnp/sp/taxonomy";

let _sp: SPFI | undefined = undefined;

export const pnpJs = (context?: WebPartContext): SPFI | undefined => {
  if (context !== undefined) {
    _sp = spfi().using(SPFx(context)).using(PnPLogging(LogLevel.Warning));
  }
  return _sp;
};
```

Then in xxxWebPart.ts in onInit:

```javascript
protected async onInit(): Promise<void> {
    // initialize PnPJs
    pnpJs(this.context);
  }
```
And this is how I call the terms() function:

```javascript
const alphabetTermSet = await pnpJs()?.termStore.sets.getById(<termset_id>).terms();
```

**Comment by juliemturner** [comment]
I'm not entirely sure I understand. Are you saying that this call:

`const alphabetTermSet = await pnpJs()?.termStore.sets.getById(<termset_id>).terms();`

is returning different results randomly? Your screen shots don't include the full method that was used to produce the results so I'm not able to answer you without further information.

That said, this SDK is in general a proxy for the SharePoint/Graph REST endpoints and so what's included or not is somewhat depending on the call you're making. The exception is [getAllChildrenAsOrderedTree](https://pnp.github.io/pnpjs/sp/taxonomy/#getallchildrenasorderedtree) which is a helper function because the new taxonomy endpoints don't support recursively getting all the children.

**Comment by Srutututu** [comment]
@juliemturner This is exactly what is happening. The function is returning results randomly. Sometimes with child terms of direct descendents of a termset, sometimes not.

Yes, in the screenshots I focused more on the varying number of results and not to show how I invoke the function.
To make things clear, this is how I do it:
```javascript
const alphabetTermSet = await pnpJs()?.termStore.sets.getById(<termset_id>).terms();
```
I had to switch to [getAllChildrenAsOrderedTree](https://pnp.github.io/pnpjs/sp/taxonomy/#getallchildrenasorderedtree) as it is returning all terms under a termset as expected.

**Comment by bcameron1231** [comment]
Unfortunately, this is an underlying issue the Taxonomy API and with term sets that include deprecated terms. As we are just a passthrough for the API, there isn't anything we can do on our end. It would need to be brought up as a ticket with the Microsoft Graph Team.

Glad you were able to find another endpoint to use to solve your problem.
