### ISSUE TITLE
SharePoint modern page scheduling is not working using PnPJs schedulePublish function

### ISSUE THREAD

**Issue by TajinderS18** [pnp/pnpjs#2855]
### What version of PnPjs library you are using

3.x

### Minor Version Number

1.4

### Target environment

SharePoint Framework

### Additional environment details

SPFx form customizer extension - 1.16.1
PnPJs - 3.14.0
NodeJs - v16.19.0

### Question/Request

Hello pnpJS community,

We have a requirement to schedule around 20-25 pages on daily basis with specific date and time using SPFx form customizer extension. To achieve this requirement, we are using PnPJs [schedulePublish ](https://pnp.github.io/pnpjs/sp/clientside-pages/#schedulepublish) function, but it is not working as expected, it seems. 
Code:
![image](https://github.com/pnp/pnpjs/assets/37292728/edf91c06-6089-4294-917a-538f9a7adbdd)

With this approach, 20% pages are not getting scheduled and we are seeing Schedule button on these pages and it is compelling us to click this button explicitly to schedule the page.
![image](https://github.com/pnp/pnpjs/assets/37292728/0669be78-6914-4120-89e0-d5d7e3083a5a)

We are unable to find any root cause of such behavior, so I would appreciate any help or advice on how to fix this issue.

Thank You.

**Comment by bcameron1231** [comment]
Code looks okay to me. Is there a possibility it's not getting inside the if statement and not trying to schedule the page? (Sorry, just trying to guess).

**Comment by TajinderS18** [comment]
We have observed three different scenarios with this code, and I can say that code is getting executed inside If block. 

1.  The page is getting scheduled successfully (80% cases).
2. The page is not getting scheduled and Schedule button is appearing (15% cases).
3.  The page is getting scheduled at the first moment but after couple of seconds, it is going back to un-scheduled stage with Schedule button enabled (5% cases).

Is it something related to any backend SharePoint job which is taking some time to update the page schedule status and giving us issues mentioned in step 2 & 3.

**Comment by bcameron1231** [comment]
I'm not aware of any scheduled job for this. We just call the /schedulePublish endpoint which is the exact same one that Microsoft UI uses when you schedule an item.  Suppose it's possible. 

So I would start by inspecting to see what the response is coming back for all your requests. Are you able to share that with us? Maybe there is something in the response to give you a hint as to what it is going on. 

You're also certain that no other processes exist on this library? e.g, a Flow.

**Comment by TajinderS18** [comment]
We are not using any flows on this library. Please find below the requests & responses

**Request & Response: 1,    Outcome: Page is scheduled successfully**

![image](https://github.com/pnp/pnpjs/assets/37292728/69c0d11a-b6fc-46d6-80bc-cfa74b8fd91e)
![image](https://github.com/pnp/pnpjs/assets/37292728/c7ea112d-d9ef-4778-84c2-6cb6bbdeef1c)
![image](https://github.com/pnp/pnpjs/assets/37292728/52a6105f-7c03-4d40-ae98-ff662686d32d)


**Request & Response: 2,    Outcome: Page is scheduled successfully**

![image](https://github.com/pnp/pnpjs/assets/37292728/9f1d1594-15c9-4ac9-b441-3064aec4f43f)
![image](https://github.com/pnp/pnpjs/assets/37292728/3bac1b7f-6bb8-402f-a07e-bf3de03a07b6)
![image](https://github.com/pnp/pnpjs/assets/37292728/338e271d-09ce-4ba1-b875-ed1822b3cc84)

**Request & Response: 3,    Outcome: Page is not scheduled and Schedule button is appearing**

![image](https://github.com/pnp/pnpjs/assets/37292728/c87e426e-fb2f-4445-80fd-e0a2268bf6f2)
![image](https://github.com/pnp/pnpjs/assets/37292728/c68eb804-0889-4adc-95e4-a4b01d2f78ff)
![image](https://github.com/pnp/pnpjs/assets/37292728/7b0d41f6-adc4-46e7-a376-1ca081ffd173)

In addition, we didn't get this issue when we schedule a page in SharePoint UI.

**Comment by bcameron1231** [comment]
Hi, thank you for sending over more information. I spent quite a bit of time testing this out, created close to 4,000 pages while doing so, and as far as I can tell, they were all scheduled successfully. So I really don't think there is anything we can do to help with the issues that you are having, as they appear to be unrelated to the PnPjs library itself.

The only other thing I could think of, is maybe the news you're publishing is checked out in a draft state by someone else, and it's not able to publish it.

**Comment by TajinderS18** [comment]
Thanks @bcameron1231 for an update. Below are the steps we are following from creating to scheduling the pages.

1. User opens SPFx custom form and create a modern page using a custom page template.

![image](https://github.com/pnp/pnpjs/assets/37292728/4971f708-275f-40a1-a5d2-e11dbae86cb2)

2. It creates a page with custom page template. The page will be in draft mode and checkout by the user who has created this page using custom form.
3. User then schedule this page using code (already shared above), which updates the page's metadata and then schedule it.

We are struggling a lot fix this issue. Do we have any alternate approach here.

**Comment by bcameron1231** [comment]
I don't have an alternative approach. Have you investigated your network tab just to confirm no updates are happening after you've done the schedulePublish? Something, somewhere appears to be updating the item after the schedule is happening.

 I wish I could provide more helpful information. At this point, we don't believe it has anything to do with PnPjs, so maybe there could another forum where others may  be able to provide more insight for you.

**Comment by bcameron1231** [comment]
Closing this issue as answered. We understand that we weren't able to reproduce the issue, and we do not believe this issue to be an issue with the PnPjs library. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
