### ISSUE TITLE
How to give the ability to the Group Members to add/delete users from the Group.?

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2856]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.13.0

### Target environment

SharePoint Framework

### Additional environment details

SPFx with React, SharePoint Online, Site Group Create

### Question/Request

Hello Everyone,

I have created an SPFx solution for custom development.

I need to create a group under the current site where the SPFx application is added.

I have taken reference from the below link,
https://pnp.github.io/pnpjs/sp/site-groups/#create-a-new-site-group

Below is my code snippet of group creation

```
import { spfi } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/site-groups/web";

export const adminGroup = async () => {
   const sp: SPFI = getSP();
   let groups = await sp.web.siteGroups.add({ "Title": "Test Group" });
}
```
The group is created successfully with the above code.

Only the group owner can add/delete the user from the group.

<img width="562" alt="Screenshot 2023-12-11 191020" src="https://github.com/pnp/pnpjs/assets/99523338/ae1dd9c4-f9d8-435c-9436-ca958c751462">

The other members of the group can not add/delete the user from the group. (Add button is missing)

![MicrosoftTeams-image (1)](https://github.com/pnp/pnpjs/assets/99523338/a05687bb-89ff-47bc-b4f3-62eefb92cf88)

Below is the screenshot of the group setting page. I need to select **Group Member** instead of **Group Owners** while creating a group programmatically using sp pnp.

<img width="680" alt="Screenshot 2023-12-11 184830" src="https://github.com/pnp/pnpjs/assets/99523338/16a301d5-02fa-405e-a001-1aa4a8fa3689">

Can anyone help me with the same?

Thanks

**Comment by bcameron1231** [comment]
You need to pass in AllowMembersEditMembership

` sp.web.siteGroups.add({AllowMembersEditMembership:true})`

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
