### ISSUE TITLE
EnsureUniqueFileName when using addChunked

### ISSUE THREAD

**Issue by mdissel** [pnp/pnpjs#2858]
### Target environment

SharePoint Framework

### Enhancement Idea

See similar issue #2840. I don't know if we can use the same solution.

**Comment by bcameron1231** [comment]
Hi. We cannot. AddChunked uses the /Add method and doesn't support this property.

**Comment by mdissel** [comment]
Ok and we can't use AddUsingPath(..) without the blob and append chunks when the file is created?

**Comment by bcameron1231** [comment]
Hi. It would be possible to do this, we'll discuss internally. Given the current implementation of addChunked we would have to add a brand new method, or update the existing and add IAddUsingPathProps... which would also mean a change to the method signature or having duplicate overwrite parameters... which is a bit kludgy. Neither of the options we totally love, but we'll chat internally and see if there is a path forward in V3.

**Comment by mdissel** [comment]
Thanks! (please re-open the issue to prevent it's getting lost)
