### ISSUE TITLE
Following example causes error "Can't resolve '@pnp/sp-admin'"

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#2859]
### Major Version

3.x

### Minor Version Number

21

### Target environment

SharePoint Framework

### Additional environment details

The example in https://pnp.github.io/pnpjs/sp-admin/#siteproperties shows:
```
import { spfi } from "@pnp/sp";
import "@pnp/sp-admin";
const sp = spfi(...);
// default props
const defaultProps = await sp.admin.siteProperties();
// all props
const allProps = await sp.admin.siteProperties.select("*")();
```
But there is an error "Can't resolve '@pnp/sp-admin'" 
Is the error in the documentation or the library?
Thanks

### Expected or Desired Behavior

Tring to get Site Name from SharePoint

### Observed Behavior

error "Can't resolve '@pnp/sp-admin'"

### Steps to Reproduce

import "@pnp/sp-admin";

**Comment by Ofer-Gal** [comment]
OS win 11
SPFx 1.17.2 (React 17.0.1)
node v16.19.0
SharePoint Online

**Comment by juliemturner** [comment]
Did you install the package in your package.json?

**Comment by Ofer-Gal** [comment]
Oops No.
I am used to everything in the 2

**Comment by juliemturner** [comment]
I'm assuming you understand that the package is really not intended for SPFx solutions. In that you need to be a SharePoint Admin for them to work. I suppose if you were going to write an admin dashboard or something, but the general idea was for nodejs "server" apps, i.e. automation scenarios.

**Comment by Ofer-Gal** [comment]
No I did not and thanks for the warning.
I was just looking for a way to get the site's  name from its URL. (for any user)
Guess, this isn't the way to do it then.
