### ISSUE TITLE
sp.profiles.getUserProfilePropertyFor promise fails 

### ISSUE THREAD

**Issue by ejvanderveen** [pnp/pnpjs#286]
### Category
- [ ] Enhancement
- [x] Bug ?
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ @pnp/sp/-/sp-1.2.3.tgz   ]

Please specify what version(s) of SharePoint you are targeting: [    O365 / SPFX version 1.6     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question

Expected behavior:
To get User's FirstName from user profiles using pnp/sp. Working across browsers. Chrome / IE11 

### Observed Behavior
On IE11 the promise for sp.profiles.getUserProfilePropertyFor fails with error: "object does not support this property or method"
As far as I am able to debug it fails somewhere inside the (minified)  pnp/sp code. **Might this contain some IE11 incompatability?**
Using developertools on both browsers I can see that IE doesn't get to the point where it would send the service request which is wrapped by this function. 
In Chrome this works flawless and I can see the servicerequest being sent and response received 

### Steps to Reproduce
I am using the following two functions inside a helperclass where during construction I also do the Init()
It doesn't matter if I use this async/await version or a version with promisses.

    public static async getUserId(email: string): Promise<string> {
        return sp.site.rootWeb.ensureUser(email).then((result: WebEnsureUserResult) => {
            return result.data.LoginName;
        });
    }

    public static async getUserLanguagePreference(): Promise<string> {
        const userId: string = await this.getUserId(this._context.pageContext.user.email);
        console.log("userId=",userId);  //for debugging
        const propertyValue: string = await sp.profiles.getUserProfilePropertyFor(userId, "FirstName");
        console.log ("propertyValue=",propertyValue); // for debugging (this line is never reached in IE11)
        return propertyValue;
    }

**Comment by koltyakov** [comment]
Hi @ejvanderveen, please make sure you're using [polyfills](https://pnp.github.io/pnpjs/documentation/polyfill/) for IE.

**Comment by ejvanderveen** [comment]
Hi @koltyakov,
You're my hero !
Didn't realize there actualy where polyfills,  although we mentioned the term polyfills in our daily when we discussed the issue  :-) . 
Works like charm now

Thanks!

I'll close the issue
