### ISSUE TITLE
Taxonomy: Obtaining description info on terms for other languages/lcid?

### ISSUE THREAD

**Issue by Kesudan** [pnp/pnpjs#287]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.3]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Question
@pnp/sp-taxonomy query:

Having some trouble finding how to get term description information for another language/lcid.

I'm able to access other language labels successfully from a term, but as for description I cannot seem to get description data for another lcid.

Is this not supported currently, or can someone point me in the correct direction?

**Comment by patrick-rodgers** [comment]
In the docs you can see [how to load terms](https://pnp.github.io/pnpjs/sp-taxonomy/docs/terms/#load-terms). You can control what terms come back by using the [label match information](https://github.com/pnp/pnpjs/blob/dev/packages/sp-taxonomy/src/types.ts#L20) in your query.

**Comment by simonagren** [comment]
@patrick-rodgers 
I believe @Kesudan wants to get the description in other lcids, not filter terms by labels :)

I don't believe there is support right now for getting the description of other LCIDs right now @Kesudan 

on term there is an setDescription, but not a getDescription.
the term also has term.Description (default language Description).

In old servercode atleast there is two methods:
GetDescription gets the description in the default LCID
GetDescription(LCID) gets the description of the supplied LCID.

@patrick-rodgers was thinking something. But I havn't gotten it to work. Any ideas?
In terms.ts
```
public get getDescriptionByLcid(lcid: number): IDescription {
            return this.getChild(Term, "GetDescription", MethodParams.build()
            .number(lcid));
        
    }
```

**Comment by patrick-rodgers** [comment]
When using getTerms() and setting the LCID in the label match info not bring back all the properties for that term in that lcid? If not than I am wrong on how that works.

If there are methods missing and available we can def look at adding them.

**Comment by simonagren** [comment]
I might be wrong aswell, gonna have a quick look

**Comment by simonagren** [comment]
Yeah. Tried to have one Label named TermOne in English, and a TermEtt label in Swedish.

Different labelmatchinginfo targeting both of them still retrieves the same data.
So the term.Description is in the Default language.

**Comment by patrick-rodgers** [comment]
Ah, my bad then, I thought it worked differently. So then I guess we need to add some methods to help here.

**Comment by simonagren** [comment]
Yeah sorry I couldn't help out with any of the methods right now. Lack of time and understanding how it works :)

**Comment by patrick-rodgers** [comment]
Working on this but actually found an issue with gulp serve so that is taking a bit of time to ensure that is working (unrelated to this issue) but that's the delay.

**Comment by simonagren** [comment]
Really would like to see how you solved it later 😀👍

**Comment by patrick-rodgers** [comment]
Just created #301. If you get a chance @Kesudan please pull that code and see if the new method works for you as expected. [Updated docs here](https://github.com/pnp/pnpjs/pull/301/files#diff-90002c2f4881f4e8ba5db270951d9cadR123)
