### ISSUE TITLE
siteUsers.getByLoginName and getByEmail throwing error when email has single quote

### ISSUE THREAD

**Issue by hermilanastacio** [pnp/pnpjs#2874]
### Major Version

3.x

### Minor Version Number

18.0

### Target environment

All

### Additional environment details

Sharepoint Webpart/Authentication

### Expected or Desired Behavior

I'm trying to get the user information using sp.web.siteUsers.getByLoginName("i:0#.f|membership|camp.o'donnell@contoso.com.au").get() and sp.web.siteUsers.getByEmail("camp.o'donnell@contoso.com.au").get() and passing login name/email with single quote

Ex. camp.o'donnell@contoso.com.au

### Observed Behavior

I'm getting

"The expression \"web/siteusers(@vdriscoll@contoso.com.au')\" is not valid."

### Steps to Reproduce

import { sp } from "@pnp/sp";

public async componentDidMount() {
    await sp.web.siteUsers.getByLoginName("i:0#.f|membership|camp.o'donnell@contoso.com.au").get().catch(e => 
    console.log(e));
}

**Comment by juliemturner** [comment]
The `.get()` method was used in v2 and completely removed in v3. So, the correct call, as [documented here](https://pnp.github.io/pnpjs/sp/site-users/#get-user) is:

`const su = await sp.web.siteUsers.getByLoginName("i:0#.f|membership|camp.o'donnell@contoso.com.au")()`

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
