### ISSUE TITLE
Unable to edit the SharePoint page after adding Google Translate

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2876]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.15.0

### Target environment

All

### Additional environment details

SPFx with React, SharePoint Online

### Question/Request

Hello Everyone,

I am unable to edit the SharePoint page after adding Google Translate.

I have faced the below error.
![image (2)](https://github.com/pnp/pnpjs/assets/99523338/cf91280e-2327-4355-8e4a-d937fd833a61)

Below are code snippets for googleTranslateElement used in the SPFx  React web part.

```
const initializeLanguageTranslateElement = async () => {
    const addScript = document.createElement('script');
    addScript.setAttribute(
      'src',
      '//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit'
    );
    document.body.appendChild(addScript);
    window["googleTranslateElementInit"] = await languageTranslateElementInit;
  }
const languageTranslateElementInit = async () => {
    new window["google"].translate.TranslateElement(
      {
        defaultLanguage: 'en',
        includedLanguages: 'en,fr,de,ja,es,ar,ru,zh-CN',
      },
      'google_language_translate_element'
    );
    await onChangeLanguageTranslation();
  };
 
const onChangeLanguageTranslation = () => {
    setTimeout(async () => {
      const languageDropdown = await document.querySelector('.goog-te-combo');
      if (languageDropdown) {
        languageDropdown["value"] = 'en';
        languageDropdown.addEventListener('change', () => {
          const selectedLanguageValue = languageDropdown["value"];
          // Translate the page immediately after changing the language
          window["google"].translate.TranslateElement({ pageLanguage: selectedLanguageValue }, 'google_language_translate_element');
        });
        languageDropdown.dispatchEvent(new Event("change"));
      }
    }, 1000);
  }
<div id="google_language_translate_element">
```

Can anyone help me with the same?

Thanks

**Comment by bcameron1231** [comment]
Hi. Unfortunately, I'm not sure how we will be able to help as the issue appears to be unrelated to PnPJs. The first error that is [linked ](https://requirejs.org/docs/errors.html#mismatch) implies that your issues are due to how you're loading Google Translate into the page, as there is a mismatch happening. As noted by the linked error to requirejs, you really **shouldn't be injecting the Google Translate script into the DOM like this**. You should be using a loader to do this. I believe SPFx documentation may have some samples on loading external libraries.

**Comment by princebagthariya** [comment]
Hi, Just you have to load require js file in SPComponentLoader only for spfx for example : 

- import { SPComponentLoader } from "@microsoft/sp-loader";
- SPComponentLoader.loadScript(your site url+ '/_layouts/15/require.js');
