### ISSUE TITLE
fetch _ColorHex property for each folder

### ISSUE THREAD

**Issue by mdissel** [pnp/pnpjs#2883]
### What version of PnPjs library you are using

3.x

### Minor Version Number

14

### Target environment

SharePoint Framework

### Additional environment details

SPFX

### Question/Request

I'm trying to list all the subfolders of a parent folder AND return the ColorHex property. Any tips?

/_api/web/getFolderByServerRelativePath(decodedUrl='%2Fsites%2F221229%2F18123456789%2FXXXX')/folders?&$select=*,ListItemAllFields&$expand=ListItemAllFields

This returns all properties, but the ColorHex property is not returned.

see https://pnp.github.io/script-samples/spo-create-colored-folder/README.html?tabs=pnpps

**Comment by bcameron1231** [comment]
Select the OData__ColorHex property

`await sp.web.getFolderByServerRelativePath("/sites/Contoso/Files").folders.select('*,ListItemAllFields/OData__ColorHex').expand('ListItemAllFields')();`

**Comment by mdissel** [comment]
Yes!! Thanks for the quick answer!
