### ISSUE TITLE
Batching get list items breaks without any error in catch

### ISSUE THREAD

**Issue by kaushalbcactus** [pnp/pnpjs#2888]
### Major Version

3.x

### Minor Version Number

3.21.0

### Target environment

NodeJS

### Additional environment details

I am using batching nodejs pnpjs library and MSAL authentication to fetch list items
/**********Update*************/

Just found that this behaviour is in my local machine only and working on azure .....so please suggest what could be problem with PNPjs local

### Expected or Desired Behavior

Get all list items (apx. 300 items)

### Observed Behavior

1. await execute() breaks without any error in catch when top limit is set to 24 but works fine when top limit is set to 23
2. Execute works for some other lists to fetch items more than 500 but for this list it breaks if top is more than 23 without any error in try catch or catch next to execute.

### Steps to Reproduce

1. Authenticate (working fine)
import { SPDefault, GraphDefault } from "@pnp/nodejs";
import { spfi } from "@pnp/sp";
import { Configuration, AuthenticationParameters } from "msal";
import "@pnp/graph/users";
import "@pnp/sp/webs";

const configuration: Configuration = {
  auth: {
    authority: "https://login.microsoftonline.com/{tenant Id}/",
    clientId: "{AAD Application Id/Client Id}",
    clientCertificate: {
              thumbprint: thumbprint,
              privateKey: secretValue.toString(),
            },
      }
};

const sp = spfi("{site url}").using(SPDefault({
    msal: {
        config: configuration,
        scopes: ["https://{tenant}.sharepoint.com/.default"],
    },
}));

2. Batch object(working fine)
const [batchedSP, execute] = sp.batched();

3. Query (ContentMT -> Multiple lines of text)
batchedSP.web.lists.getByTitle('abc').items.select('ID, ContentMT, UserNamePG/Title').expand('UserNamePG').top(25)().then(r => response.push(r));

4. execute
await execute().catch((ex) => { console.log('Batch error:', ex) });

**Comment by bcameron1231** [comment]
Hi. We're going to need a little bit more information. Can you describe what you mean by "it breaks"? What does that mean?

And for some clarity, there may be an error internally in the batch. The batch may return a 200 but have an error within one of the requests. If you could share the response back from Dev Tools, that would help further diagnose your issue.

**Comment by kaushalbcactus** [comment]
Hi. Thanks for prompt response. Today it started working not sure what was issue. Earlier execution used to stop without any error
I will close ticket for now. Thanks!
