### ISSUE TITLE
Calls wait endless since 3.21.0 (updated from 3.20.0)

### ISSUE THREAD

**Issue by dvTB** [pnp/pnpjs#2890]
### Major Version

3.x

### Minor Version Number

21.0 

### Target environment

NodeJS

### Additional environment details

Running a multi-tenant service using msal authentication on Node 20 with express.

### Expected or Desired Behavior

Calls should get answered and not wait indefinitly until timeout is reached. 

### Observed Behavior

When updating from 3.20.0 to 3.21.0 my service no longer responds because sporadically some promises from pnp.js just don't get answered (or would fail).
So far the only soltion I found is going back to 3.20.0

Now also tried 3.20.1 which also works. 

### Steps to Reproduce

So far I couldn't pinpoint the location of the problem. It just happens sporadic on different calls (getting web, site, items, list, ...).

**Comment by patrick-rodgers** [comment]
@dvTB - can you share some more details? We aren't aware of a change that would affect this - unless perhaps you are using caching? If so, can you remove it and see if that resolves the issue?

Can you perhaps share an example of code that is having sporadic issues? With what you've shared we aren't sure where to start looking.

**Comment by allanhvam** [comment]
I am also seeing some strange behavior with the latest version.

This works:
```
await sp.web.lists.getByTitle("Title")()
``` 

But:
```
await sp.web.lists.getByTitle("Title").items()
```
seems to never return.

From by debugging it seems to never get past the new emit rawData:
https://github.com/pnp/pnpjs/blob/d96c7be519e8588716ab0d9b10072601f10a5aac/packages/queryable/queryable.ts#L184

(but I could be wrong)

I am not using any caching behavior, and I am on NodeJS v16.

**Comment by bcameron1231** [comment]
Hi. I am having trouble reproducing. I have ran through an items() call a few hundred times and it's worked every time. I've set up a loop and ran this a few times, and the output has always been the same. 

```
   const listname = 'SPFx List';       
            for(var i = 0; i< 20; i++){
                const items = await sp.web.lists.getByTitle(listname).items();
                console.log(i + " - " + items.length);
            }
```
![image](https://github.com/pnp/pnpjs/assets/7944457/023f32cc-1e04-48ed-8fdc-eaa5227c05ba)

Are you seeing any errors any where in console? Could you give us a little information about your list, is this happening on every list?
