### ISSUE TITLE
Get hubSiteData from rootWeb

### ISSUE THREAD

**Issue by allanhvam** [pnp/pnpjs#2895]
### Major Version

3.x

### Minor Version Number

20.0

### Target environment

NodeJS

### Additional environment details

NodeJS v16.

### Expected or Desired Behavior

I am trying to get hub site data from a rootweb:

```
const hubSiteData = await sp.site.rootWeb.hubSiteData();
```

### Observed Behavior

Throws:

```
Error: Error making HttpClient request in queryable [404] Not Found ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot find resource for the request hubSiteData."}}}
```

Response url is `https://tenant.sharepoint.com/sites/site1/_api/site/hubSiteData(false)` but should be `https://tenant.sharepoint.com/sites/site1/_api/site/rootweb/hubSiteData(false)`

Note that this works:
```
const hubSiteData = await sp.web.hubSiteData();
```

### Steps to Reproduce

```
const hubSiteData = await sp.site.rootWeb.hubSiteData();
```

**Comment by bcameron1231** [comment]
Looks like we currently don't support the ability to do it directly off the rooteweb object. Could you use a new Web Queryable object instead?

const data  = await Web(sp.site.rootWeb).hubSiteData();

**Comment by allanhvam** [comment]
Sure I could use the working `sp.web.hubSiteData()`, but this just lead me to that `ensureUser` is also not working on `rootWeb`.

I have a fairly large code base migrating from v2 with almost 100 usages of `rootWeb` - it will take some effort changing and testing it.

**Comment by bcameron1231** [comment]
Understood. I will take a look, the issue is basically how we're rebasing the Web objects which is causing the problem here. Will keep you posted.
