### ISSUE TITLE
Unable to delete SharePoint list which contains more than 100000 items

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2909]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.15.0

### Target environment

SharePoint Framework

### Additional environment details

Sharepoint Online

### Question/Request

Hello All,

I have created a list under SharePoint Online that contains 100000+ items.

Now, I need to delete that list. So, I have tried to delete the list from List Settings.

It has thrown the below error message.

![MRPEX](https://github.com/pnp/pnpjs/assets/99523338/b62329ae-4b8b-408a-a1a0-fc2e74bf1b4d)

Can I delete that list using SP PnP?
https://pnp.github.io/pnpjs/sp/lists/#recycle-a-list

Thanks

**Comment by patrick-rodgers** [comment]
If this is a testing scenario you could try deleting the site collection.

Otherwise, you might need to delete a lot of items individually then the list.

**Comment by bcameron1231** [comment]
Agree with Patrick. This is a limitation of SharePoint. You'd have to remove all of the items to get < the 5,000 item limit first before deleting a list.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
