### ISSUE TITLE
[BUG] v3.22 broke photos in @pnp/graph

### ISSUE THREAD

**Issue by kbeeveer46** [pnp/pnpjs#2911]
### Major Version

3.x

### Minor Version Number

22.0

### Target environment

SharePoint Framework

### Additional environment details

Node 18.17.1
SPFx 1.18.2

### Expected or Desired Behavior

In version 3.21.0 the following code returns a blob

`await graphfi().using(SPFx(context)).me.photo.getBlob()`

In version 3.22 it returns an error message

```
message: 'Failed to execute 'blob' on 'Response': body stream already read'
stack: 'TypeError: Failed to execute 'blob' on 'Response': body stream already read\n    at eval (webpack-internal:///./node_modules/@pnp/graph/node_modules/@pnp/queryable/behaviors/parsers.js:45:25)\n    at async Promise.all (index 0)\n    at async Proxy.eval (webpack-internal:///./node_modules/@pnp/graph/node_modules/@pnp/queryable/behaviors/parsers.js:108:43)\n    at async eval (webpack-internal:///./node_modules/@pnp/graph/node_modules/@pnp/queryable/queryable.js:126:50)'
```

I can replicate the error every time by changing the @pnp/graph version number only and not any other code.

### Observed Behavior

Returns an error message

### Steps to Reproduce

See code above

**Comment by bcameron1231** [comment]
Thanks for reporting. This is a regression, and we will work on a fix.

**Comment by bcameron1231** [comment]
Hi, we just merged in a fix for this. It will be available in the nightly builds, and will be in the next release.
