### ISSUE TITLE
SPFx Teams app working locally but not working after being installed in Teams

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2917]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.15.0

### Target environment

SharePoint Framework

### Additional environment details

SharePoint Online, SPFx, Teams

### Question/Request

 have created the SharePoint Framework app for Microsoft Teams.

When I run the app locally, It is working as expected.

But when I generated a package for Teams using Teams Toolkit from VS Code and deployed the same package in Teams. It threw the below error.

<img width="694" alt="Temp" src="https://github.com/pnp/pnpjs/assets/99523338/a66bc37f-8255-4b38-9ab0-840c67f94d93">

Can anyone help me with the same?

Thanks

**Comment by patrick-rodgers** [comment]
Hi @bhoomesh-spe - this isn't an issue with this library and as such we won't be able to offer much assistance. Thanks!
