### ISSUE TITLE
Additional questions for user authentication (bearer token) on .NET REST API

### ISSUE THREAD

**Issue by necik11** [pnp/pnpjs#2918]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.20.1

### Target environment

All

### Additional environment details

SPFX Commands + Webpart - Browsers - Microsoft Edge  / Chrome
ASP .NET Core - REST API - (The REST API is exposed on the custom server [the customer did not want Azure API] - this API is published on the public web and is accessible via a certain port + HTTPS).

### Question/Request

Hello, I have additional questions about this issue: [#2860](https://github.com/pnp/pnpjs/issues/2860)

I have currently this situation:

1. SPFX Command sets + Webparts that call this API
2. This package runs on multiple customers eg 4 - and they all call this API
3. If they call e.g. EditSPListItemInBackground (itemId parameters).
4. The PNP SDK core runs in the background - which already has all the necessary permissions + resources for these operations ( sites - selected - approved by tenant admin consent)
5. All I need is to secure API input. Since this API is publicly accessible, I need to secure it so that only users from specific tenants can call it - for example, those I have added to CORS. 
6. For this i tried this code, which should send token to backend:

```
  var tokenId = 'https://graph.microsoft.com'
  let provider = this.context.aadTokenProviderFactory.getTokenProvider();
  console.log("provider", provider);
  let token = (await provider).getToken(tokenId);
  console.log("token", token);
```
7. And this Token is sent as a parameter. Similar code in this video: [Calling Dynamics 365 CRM APIs from SharePoint](https://www.youtube.com/watch?v=VXzYc6cfjuI) and similiar advice in this issue [#8071](https://github.com/SharePoint/sp-dev-docs/issues/8071#issuecomment-1152588958)
8. This is from video, i am using same: 
![image](https://github.com/pnp/pnpjs/assets/25322303/ce6c7b7f-d969-4fa4-9f5d-b13322788d7c)
and this is backend:
![image](https://github.com/pnp/pnpjs/assets/25322303/c3afc3ec-3f17-4be0-8c49-a3863ac98789)
9. After this setting, everything starts to work and I can capture users from the accces token in the background.
10. The only big problem is every call 
 `getToken("https://graph.microsoft.com")`
in Chrome/Mozilla - refresh full page - like F5
in Microsoft Edge - works fine, runs in the background

The only thing that reminded me of this problem is this thread:
[Or, if you’re using the web part in SharePoint Online and a user is using Safari with Intelligent Tracking Protection (ITP) enabled (which blocks third-party cookies), when your web part requests an access token, it will trigger a full page refresh.](https://www.voitanos.io/blog/sharepoint-framework-v1-17-whats-in-latest-update-of-spfx/)

a)
and even though I tried to rewrite the car according to the [documentation](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aadtokenprovider#handling-the-popupevent-1), no change.

b)
So I haven't tried this step:
Until SPFx v1.17, the AADTokenProvider API didn’t support the popup experience. But now it does. To take advantage of this, you need to set the argument IsEnabledAppAuthPopUpEnabled property on your tenant to true using the Set-SPOTenant PowerShell cmdlet.

Since it didn't feel right to order this to customers...

c) I even try set second parameter (useCachedToken) in method:
`aadTokenProvider.getToken("https://graph.microsoft.com", false)`
after this i get deadlock - never ending refreshing/reloading page.

Again, I'd appreciate any advice or insight.

**Comment by juliemturner** [comment]
@necik11 - Although I appreciate the lengths you've gone through to post this here, this is really not the forum as it's not related to this library in any way, so I suspect you're not going to get any visibility. I might suggest you post this question to [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues) repository instead.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
