### ISSUE TITLE
ClientSidePage.getComments() only returns 30 comments

### ISSUE THREAD

**Issue by c-eiser13** [pnp/pnpjs#2919]
### Major Version

3.x

### Minor Version Number

22

### Target environment

SharePoint Framework

### Additional environment details

I'm using a brand new 1.18.2 SPFx web part with @pnp/sp@3.22.0

### Expected or Desired Behavior

I'm trying to fetch all the comments for a site page.

### Observed Behavior

When calling getComments() on a Site Page, it only returns the top 30 comments, it does not return all comments. I do not see any way to page the response or get all, but the documentation says it should return all comments. See below for example:
![image](https://github.com/pnp/pnpjs/assets/42096464/46890340-bce7-4cd3-a1fb-8ffe4e42b542)

This is the page the above screen shot is calling getComments() on
![image](https://github.com/pnp/pnpjs/assets/42096464/b37f7bd8-a9d3-4b94-bb3e-d7f86c41ef92)

![image](https://github.com/pnp/pnpjs/assets/42096464/7b37124d-89cc-4114-9573-49eb62528f5d)

I've noticed the same behavior calling sp.web.lists.getById("").items.getById(10).comments(). This call also only returns the top 30.
![image](https://github.com/pnp/pnpjs/assets/42096464/bb517da3-b409-44d1-a47f-403dc141c63b)

If there is any further info I can provide, please let me know. Thanks!

### Steps to Reproduce

The code I am using can be seen in the screenshot in the observed behavior section. I'm simply getting a reference to a page that has 40 comments and calling the getComments() method, and it will only return 30 comments.

**Comment by bcameron1231** [comment]
Hi. After some investigation it appears that Microsoft's API defaults the limit to 30. If you want to pull more than 30, you need to use top();

` await sp.web.lists.getByTitle("Site Pages").items.getById(1).comments.top(500)();`

**Comment by c-eiser13** [comment]
@bcameron1231 appreciate the quick response! That will work for using the list item, but what if I only have access to the site page? It does not look like the page.getComments() supports the top param. Perhaps we could pass a value to getComments(500) to get more than 30? I've not had a chance to look through the source, but if it is something that could be implemented, I don't mind helping out.

**Comment by bcameron1231** [comment]
Correct, unfortunately getComments doesn't support the top param. `page.getComments()` is just a wrapper function which gets the item from the page, and then returns the comments for you. I'm sure this could be updated but unlikely in V3 as we're almost set on releasing V4 of PnPjs.

In the mean time to unblock you, I'd probably grab the item from the page and then the comments (which is what we are doing internally anyways).

```
  const page = await sp.web.loadClientsidePage(pageLink);
  const comments = (await page.getItem()).comments.top(5000)();
```

**Comment by c-eiser13** [comment]
@bcameron1231 thanks, I went and reviewed our code and realized we could grab the list item, will use this to get around the issue. Thanks!
