### ISSUE TITLE
ETIMEDOUT in Azure Function

### ISSUE THREAD

**Issue by Bobinho4711** [pnp/pnpjs#2920]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.17.0

### Target environment

NodeJS

### Additional environment details

IF script runs locally everything is fine.
If script runs as Azure Function under NodeJS@16 LTS the script runs into frequent ETIMEDOUT errors, when connecting to SharePoint only via PNP

For Authentication Im using an AppReg in Azure AD with a Client ID and a Client Certificate via MSAL.

The Function is on Runtime 4 and I upgraded it to an Elastic Premium EP1 Tier.

At the beginning of the script 2 SPFIs (one for HUB Site, one for current Site) are beeing created via
<code>
const getspfi = (siteUrl: string, executionPath: string) => {
  let baseUrl = siteUrl;
  if (baseUrl.toLowerCase().startsWith("/sites")) {
    baseUrl = process.env.SHAREPOINT_DOMAIN + siteUrl;
  }

  const privateKeySource = readFileSync(executionPath + "/sposupport.pem");
  const privateKey = Buffer.from(privateKeySource).toString();

  const config: Configuration = {
    auth: {
      authority:
        "https://login.microsoftonline.com/" + process.env.TENANT_ID + "/",
      clientId: process.env.CLIENT_ID,
      clientCertificate: {
        thumbprint: process.env.CLIENT_CERT_THUMBPRINT,
        privateKey: privateKey,
      },
    },
  };

  const sp = spfi().using(
    SPDefault({
      baseUrl: baseUrl,
      msal: {
        config: config,
        scopes: [
          "https://" + process.env.TENANT_NAME + ".sharepoint.com/.default",
        ],
      },
    })
  );
</code>

Those SPFIs are used for all the calls.

### Question/Request

Hi, 

I created a translation engine for SharePoint pages which I would like to run in an Azure function.
To make this work many HTTP calls need to be made, here you see an abstracted flow which shows the different HTTP calls needed (for SharePoint interaction). Due to the loops they are adding up, but I even get this error sometimes if the first loop is only beeing executed once.

<code>
get all pages
get default language property from web
get last changes
get site id

get all items from config list in associated Hub-Site

now in loop depending on the amount of changes - item = listItem of a Page
......................
	item update
	item.file publish
	
	loadClientSitePage from item
	
	now in loop for 5 times (5 languages):
	......................
	if specific page copy available
		validateUpdateListItem
	else
		copy page 
		get item of copied page
		validateUpdateListItem	

	loadClientSitePage page copy item
	[manipulate page copy content] -> external translation APIs are called frequently
	save clientsite page copy
</code>

I dont think I will be able to reduce the amount of HTTP calls, during the implementation I obviously paid attention to this and tried to avoid uneccesary calls whenever.

However, when lookup im this ETIMEDOUT issue in Azure, this seems to be quiete common because of SNAT settings in Azure.
Whenever it is popping up in the context of NodeJS, people recommend using to change the HTTP Agent to a keep alive:true.

So my questions would be:
I might be able to get rid of the validateUpdateListItem Call in case I can set page columns (like firstPublishedDate) while having the ClientSite Page Object open anyway. I saw that you are storing those fields in a JSON property of the page. Is it possible to edit this JSON and can I set there any fields I want (including stuff like PromotedState, firstPublishedDate, etc which via a normal update does not work and requieres validateListItem Update)?

Do I have a change to manipulate the HTTP Agent and set this keep alive setting, timeouts and max-sockets values as explained here: https://azureossd.github.io/2022/03/10/NodeJS-with-Keep-Alives-and-Connection-Reuse/
I could imagine that behaviours might be a good entry point, but to be honest I dont see how to do this.

Is there anything else you can recommend to bring in stability into this?

Your feedback is higly appreciated, Im a little bit desperate right now.

Regards René

**Comment by patrick-rodgers** [comment]
Hi @Bobinho4711 -

Many of your questions seem outside external to the library. For setting a custom agent you could register a "pre" observer and [set node-fetch's agent property in the init](https://github.com/node-fetch/node-fetch?tab=readme-ov-file#custom-agent).

It might look something like, though there are lots of options in agent libraries.

```TS
import https from 'node:https';

myObj.on.pre(async function(url: string, init: RequestInit, result: any) {

  const httpsAgent = new https.Agent({
	  keepAlive: true
  });

  init.agent = httpsAgent;

  return [url, init, result];
});
```

**Is it possible to edit this JSON**

You can try, but the pages API is its own thing and it might not work. We have paused working on the implementation as we are waiting to transition to the upcoming supported pages API in Graph.

**Comment by Bobinho4711** [comment]
Hi @patrick-rodgers ,

thanks for taking the time to answer this.
Actually this pre Oberver seems to be what I was looking for.
As I never used them I might have some follow-up questions, I hope this is ok.

I assume in your example myObj could be something like sp.web, correct?
If I set this observer on sp.web, is it enough doing so once per SPFI after initialization? Or do I have to do so before each call?

Also, you wrote that the RequestInit should have a property "agent", which is not available on my system.
But I see a "keepAlive" property instead.

<code>
  sp.web.on.pre(async (url: string, init: RequestInit, result: any) => {
    console.log("hi");
    init.keepalive = true;

    return [url, init, result];
  });
</code>
Is this the correct way of using the observer?

And last but not least: Do you see a chance how I can overwrite the entire http Agent, Im asking because in an http Agent I can set other things like maxSockets, timeouts etc, those properties are not available in the  RequestInit object.

Thank you very much.

René

**Comment by patrick-rodgers** [comment]
@Bobinho4711 please read the sample I gave you. It does exactly what you are asking for.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
