### ISSUE TITLE
How to hide title from a site?

### ISSUE THREAD

**Issue by kkazala** [pnp/pnpjs#2927]
### What version of PnPjs library you are using

3.x

### Minor Version Number

16.0

### Target environment

All

### Additional environment details

SPO

### Question/Request

Is there a way to hide site title using Pnp js?

Change the look / Header / Site title visibility:
![image](https://github.com/pnp/pnpjs/assets/22429087/9fd291ae-bd0c-4474-b57e-ac55154ed66a)

I see it's possible using PnP PowerShell but can't find this option in js

thank you in advance for your help =)

**Comment by bcameron1231** [comment]
Not something we natively support. But you can use our exposed methods to achieve this. 

```
import { spPost } from "@pnp/sp";
import "@pnp/sp/presets/all";
import { body } from "@pnp/queryable/index.js";
import { Web } from "@pnp/sp/webs";

const sp = spfi(...);
await spPost(Web(sp.web, "SetChromeOptions"), body({'hideTitleInHeader':true}));
```

For more info on calling other endpoints we don't have here. Check out our docs.
https://pnp.github.io/pnpjs/concepts/calling-other-endpoints/

**Comment by kkazala** [comment]
thank you @bcameron1231 ! This has been a great help indeed :)
