### ISSUE TITLE
Unable to make simple connection with sp.web

### ISSUE THREAD

**Issue by only1chi** [pnp/pnpjs#293]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [  1.2.3   ]
Please specify what version(s) of SharePoint you are targeting: [         ]

### Expected / Desired Behavior / Question
I am trying to access to a site collection and list the items in the "folder". This piece of code was working exactly fine in version 1.1.3 of @pnp/sp.
This piece of code worked perfectly fine in the previous version and I can print the title of a web:

```Web Title: Supplier Collaboration``` 

### Observed Behavior
In version 1.2.3 of @pnp/sp, this same piece of code yields the following error:

```Error making HttpClient request in queryable: [403] Forbidden```

### Steps to Reproduce

Here is the piece of code: 
```
  sp.setup({
    sp: {
      fetchClientFactory: () =>
        new SPFetchClient(process.env.SITE_URL, process.env.CLIENT_ID, process.env.CLIENT_SECRET)
    }
  });

  return sp.web
    .select("Title")
    .get()
    .then(w => {
      console.log(`Web Title: ${w.Title}`);
      return w;
    })
    .catch(error => {
      console.log(error);
      return error;
    });
```

**Comment by koltyakov** [comment]
Hi @only1chi,

Aren't you missing providing baseUrl?

```typescript
sp.setup({
  sp: {
    fetchClientFactory: () => new SPFetchClient(process.env.SITE_URL, process.env.CLIENT_ID, process.env.CLIENT_SECRET),
    baseUrl: process.env.SITE_URL
  }
});
```

or using `const web = new Web(process.env.SITE_URL);`

**Comment by only1chi** [comment]
Hi @koltyatov,

I had included the baseUrl before, it didn't seem to make a difference. I took the suggestions you made here, and I get the same problem. 

I added the Logger and made it verbose to provide more details:
```
Message: [ed606def-6352-4cc8-8806-0d313fe974f3] (1539956148706) Calling request pipeline method logStart.
Message: [ed606def-6352-4cc8-8806-0d313fe974f3] (1539956148706) Beginning GET request (https://becpsn.sharepoint.com/teams/shellpc/Supplier/_api/web?$select=Title) Data: {"batch":null,"cachingOptions":null,"isBatched":false,"isCached":false,"options":{"headers":{}},"parser":{},"pipeline":[null,null,null],"requestAbsoluteUrl":"https://becpsn.sharepoint.com/teams/shellpc/Supplier/_api/web?$select=Title","requestId":"ed606def-6352-4cc8-8806-0d313fe974f3","verb":"GET"}
Message: [ed606def-6352-4cc8-8806-0d313fe974f3] (1539956148707) Calling request pipeline method caching.
Message: [ed606def-6352-4cc8-8806-0d313fe974f3] (1539956148707) Calling request pipeline method send.
Message: [ed606def-6352-4cc8-8806-0d313fe974f3] (1539956148707) Sending request.
Message: Error making HttpClient request in queryable: [403] Forbidden Data: {"response":{"size":0,"timeout":0},"status":403,"statusText":"Forbidden","isHttpRequestError":true}

  Error --------------------------------------------------

  Error making HttpClient request in queryable: [403] Forbidden
```

Still getting the same error. 
I'm using webpack in my new configuration. Everything builds correctly but I get this error. Are you aware of any webpack related issues?

**Comment by only1chi** [comment]
I think this issue has something to do with fetch. I'm using node 8.10. Not sure what HttpClient uses to perform fetch operations.

**Comment by pedro-pedrosa** [comment]
Did you run appinv.aspx? Make sure you include the `AllowAppOnlyPolicy="true"` attribute as explained [here](https://pnp.github.io/pnpjs/documentation/debugging/) in `Grant Your Add-In Permissions`.
