### ISSUE TITLE
attachmentFiles.getByName does not encode the filename

### ISSUE THREAD

**Issue by nathan-prijot** [pnp/pnpjs#2931]
### Major Version

3.x

### Minor Version Number

3.22.0

### Target environment

SharePoint Framework

### Additional environment details

Typical SPFx v1.18.2

### Expected or Desired Behavior

If I have an attachments literally called `Lorem%20ipsum.docx` the following should work:
```TypeScript
const sp = spfi(...)
sp.web.lists.getByTitle("My List").items.getById(1).attachmentFiles.getByName("Lorem%20ipsum.docx").recycle();
// Should calls https://myorg.sharepoint.com/sites/MySite/_api/web/lists/getByTitle('My List')/items(1)/attachmentFiles('Lorem%2520ipsum.docx')/recycleObject 
``` 

### Observed Behavior

It does not encode the filename and calls `https://myorg.sharepoint.com/sites/MySite/_api/web/lists/getByTitle('My List')/items(1)/attachmentFiles('Lorem%20ipsum.docx')/recycleObject`. The filename is not recognized which generate a 400 error.

Since `attachmentFiles.add` nows encode the filename, this seems a bit odd to work with.

Note that SharePoint itself seems confused about it because the `ServerRelativeUrl` returned by the SharePoint API will also be invalid (as well as the `odata.id` and `odata.editLink`).

### Steps to Reproduce

1. Use the `attachmentFiles.add` with as a filename `Lorem%20ipsum.docx`.
2. Use the `attachmentFiles.getByName` with the same filename.

**Comment by nathan-prijot** [comment]
Additionally, `attachmentFiles.getByName` does not double the `'` in the file name while `attachmentFiles.add` does. It's quite funny because in v2, if I'm not mistaken, you had to encode the filename and double the `'` for `attachmentFiles.add` and not for `attachmentFiles.getByName`. So it's the opposite here.

**Comment by nathan-prijot** [comment]
For those wondering, here is what you need to do if you want `getByName` to work with the 'raw' file name:

```ts
const escapedFileName = encodeURIComponent(attachmentName.replace(/'/g, "''"));
attachmentFiles.getByName(escapedFileName).recycle();
```

Reminder that you have to do it for `attachmentFiles.getByName` but not for `attachmentFiles.add`.

**Comment by patrick-rodgers** [comment]
Fixed in v4, won't fix in v3.

**Comment by patrick-rodgers** [comment]
Closing with merge of fix for v4
