### ISSUE TITLE
SharePoint REST Batching

### ISSUE THREAD

**Issue by anthonywhite** [pnp/pnpjs#2933]
### What version of PnPjs library you are using

3.x

### Minor Version Number

Any

### Target environment

SharePoint Framework

### Additional environment details

Any

### Question/Request

More of a question about SharePoint, but I'm guessing the smart folks in PnPJSville will know...is JSON batching supported on the V2 SharePoint REST API? Or only on Graph API? If yes, is that documented somewhere?

**Comment by juliemturner** [comment]
I'm not sure I totally follow this question.. yes batching is supported and has been for some time... https://pnp.github.io/pnpjs/concepts/batching/

**Comment by anthonywhite** [comment]
Hi @juliemturner, thanks - I get that PnPJS supports batching, what I was trying to ask is whether SharePoint REST **V2.0** supports it, and especially if it supports the JSON format batching that Graph has now ([as documented here](https://learn.microsoft.com/en-us/graph/json-batching)) - which makes a lot more sense to me than the frankly awful MIME-based batch syntax of V1.

But I have just been told by MS support that JSON batch is Graph-only for now and the foreseeable. I suggested they start making this sort of divergence clearer with an update to [this page](https://learn.microsoft.com/en-us/sharepoint/dev/apis/sharepoint-rest-graph)...
