### ISSUE TITLE
utility.searchPrincipals() returns -1 for PrincipalId

### ISSUE THREAD

**Issue by ludes2** [pnp/pnpjs#2940]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.23

### Target environment

SharePoint Framework

### Additional environment details

I'm using PnP/js version 3.23 and working in SPFX Version 1.15.2

### Question/Request

I am currently working on a SPFX project and have encountered an issue. I have multiples Azure AD Security Groups that are assigned to a SharePoint Default Group. In order to set the correct roleAssignments, I need to obtain the Principal ID of a specific Security Group. However, when I search for the Principal, I am able to find it, but the ID is always -1. I am unsure if this is a bug or if there is a way to resolve this issue. While I am aware that using the Graph API is a possible solution, we would prefer to use the SharePoint REST API as our first option.

my Code:
```
const principals: IPrincipalInfo[] = await getSP().utility.searchPrincipals("XYZ", PrincipalType.All, PrincipalSource.All, "", 10); 
console.log("🚀 ~ getItem ~ principals:", principals);
...
await createResult.item.breakRoleInheritance(true, false);
await createResult.item.roleAssignments.add("HERE I NEED THE PRINCIPAL ID OF THE SECURITY GROUP", roleDefinitions.get(0).Id);
```
![PrincipalIDMinusOne](https://github.com/pnp/pnpjs/assets/17458678/1ce4408c-5c2c-407b-803f-191c8650a46f)

**Comment by patrick-rodgers** [comment]
I am mostly sure that it is -1 because there is not defined SharePoint PrincipalId. This would be the integer id for an sp user or group. If you are finding a security group it must not have an existing SP Principal ID or maybe can't - 🤷‍♂️.

If you resolve a user do you get an id?

**Comment by ludes2** [comment]
We have decided to use the GRAP API, thank you for the quick responses. I will mark the issue as resolved.
