### ISSUE TITLE
How to update SharePoint Online column type using pnp/sp?

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2944]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.15.0

### Target environment

SharePoint Framework

### Additional environment details

SharePoint Online, SPFx, React

### Question/Request

Hello Everyone,

I have created a SharePoint list and column programmatically using the below code.

```
import { spfi } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/fields";

const sp = spfi(...);
let listCreate = await sp.web.lists.ensure("MyList", "MyList Description", 100, false, { Hidden: false });
let addColumn = await sp.web.lists.getByTitle("MyList").fields.addText("Comment")
let addColumnInView = await sp.web.lists.getByTitle("MyList").defaultView.fields.add("Comment");
```

I have taken a reference from [Add a New Field](https://pnp.github.io/pnpjs/sp/fields/#add-a-new-field) and [Ensure that a List exists](https://pnp.github.io/pnpjs/sp/lists/#ensure-that-a-list-exists-by-title) links.

Now, I need to change the _Comment_ column type from single-line text to multi-line text. 
So, I have checked [Update a Field](https://pnp.github.io/pnpjs/sp/fields/#update-a-field) link but there is no option for changing the type of the existing column.

Can anyone help me with the same?

Thanks

**Comment by bhoomesh-spe** [comment]
@bcameron1231 - Thanks for the reply. It threw me an error NumberOfLines property is not present.

**Comment by bcameron1231** [comment]
@bhoomesh-spe  Ah, apologies, ya you can't set the number of lines until it's a multiline text field.

```
 //create multiline text field
  const field = sp.web.lists.getByTitle("Test").fields.getByTitle('SingleLine');
  await field.update({
     FieldTypeKind: 3
  }, "SP.FieldMultiLineText");
  
  // update multiline text field (optional)
   await field.update({
     NumberOfLines: 6,
  }, "SP.FieldMultiLineText");
```

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
