### ISSUE TITLE
How to keep deleted sites in to recycle bin instead of delete permanently?

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2946]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.15.0

### Target environment

SharePoint Framework

### Additional environment details

SharePoint Online, SPFx, React

### Question/Request

Hello All,

I need to keep deleted sites in to recycle bin instead of delete permanently.

I have checked that into [Delete a Web](https://pnp.github.io/pnpjs/v2/sp/webs/#delete-a-web) link.
But there is no operation which moves subsite to recycle bin.

Does anyone have any idea?

Thanks

**Comment by bcameron1231** [comment]
Hi, AFAIK, the REST API does not support deleting a site and having it moved to the Recycle Bin.

**Comment by bhoomesh-spe** [comment]
@bcameron1231 - Thanks for the reply. Can I perform with any other approach?

**Comment by bcameron1231** [comment]
Not that I'm aware of programmatically.

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
