### ISSUE TITLE
Can I send post/update request for GraphQueryableInstance objects?

### ISSUE THREAD

**Issue by pkmelee337** [pnp/pnpjs#295]
### Category
- [ ] Enhancement
- [ ] Bug
- [ X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.2.3 ]

Please specify what version(s) of SharePoint you are targeting: [ Modern SharePoint ]

### Question
Some objects which extend the GraphQueryableInstance (like a Group for example) do have an update function. In my case I am using the graph.me and I want to update my skills, however the Me object does not have an option to update. Is this coming in the future or do I have to update the User object? It might even be awesome to create some kind of a generic update function in the GraphQueryableInstance?

**Comment by patrick-rodgers** [comment]
The way the library is written updates etc need to be explicitly coded, i.e. we would need to add a method. It may be possible to add an update method directly to GraphQueryableInstance which could be shared, will have to take a look.

**Comment by patrick-rodgers** [comment]
I have added delete and update to the user object (which also applies to "me"). I don't want to add update to the base class as I am not certain it would apply to every object in the same way. Thanks for the suggestion.
