### ISSUE TITLE
CalendarView getDelta

### ISSUE THREAD

**Issue by kkazala** [pnp/pnpjs#2952]
### What version of PnPjs library you are using

3.x

### Minor Version Number

17

### Target environment

All

### Additional environment details

The question is not environment specific

### Question/Request

I want to retrieve changes to the calendar events as described in [Get delta](https://learn.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&tabs=http)
The [CalendarView](https://pnp.github.io/pnpjs/v2/graph/calendars/#get-calendar-view) doesn't return ` @odata.deltaLink`
I tried using `graphGet`:
```ts
const events = this.graph.users.getById(sharedMailbox); 
const eventsQuery = GraphQueryable(events, `/calendarView/delta?startDateTime=2024-03-04&endDateTime=2024-03-22&`);
const result= await graphGet(eventsQuery);
```
but the ` @odata.deltaLink` is also removed. 
Is there a way to retrieve it, using pnp js?

**Comment by bcameron1231** [comment]
Hi, the delta query may not always contain a deltaLink, it may contain a nextLink instead. You'll get one or the other depending on if you've completed the getting all the changes, or if there are still more changes you need to retrieve. 

Can you confirm if you have a `@data.nextLink` in the response?

**Comment by kkazala** [comment]
@bcameron1231  I don't. Neither `@odata.deltaLink` nor `@data.nextLink`
I have only 1 item that changed during this time span, so I should get `@odata.deltaLink`, but it looks like it's removed for some reason

**Comment by bcameron1231** [comment]
Hi @kkazala . Ah, my apologies. The reason is that the PnPjs default parser is used when using graphGet. This parser only returns the value from the response. In order to fix this, you can use the [JSONParse ](https://pnp.github.io/pnpjs/queryable/behaviors/#jsonparse)behavior on your spfi or Graph Queryable objects.


Here is an example of doing it right on the eventsQuery GraphQueryable object.
```
const events = this.graph.users.getById(sharedMailbox); 
const eventsQuery = GraphQueryable(events, `/calendarView/delta?startDateTime=2024-03-04&endDateTime=2024-03-22&`).using(JSONParse());
const result= await graphGet(eventsQuery);
```

This could also be done for all graph requests if you wish. 
`  const graph = graphfi().using(JSONParse());`

**Comment by patrick-rodgers** [comment]
We will also have better delta support in v4.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
