### ISSUE TITLE
Change file content without creating a new version

### ISSUE THREAD

**Issue by nob-b3** [pnp/pnpjs#2954]
### What version of PnPjs library you are using

4.x

### Minor Version Number

4.0.0

### Target environment

All

### Additional environment details

-

### Question/Request

I'm using a document list with files where versioning is enabled. Now i want to change the content of the file without creating a new version. 

The content update works with the setContent/setContentChunked methods (https://pnp.github.io/pnpjs/sp/files/#update-file-content), but those are creating a new version. Is this also possible without creating a new version?

In my research (on google) i only found ways to update the FileItem without a version change but not the file itself.

**Comment by patrick-rodgers** [comment]
Correct, if versioning is turned on, creating a new version of the document creates a new version in the library. If you'd like to not have versions you can always turn off versioning.

**Comment by nob-b3** [comment]
@patrick-rodgers The problem is, we need to make changes on the file exif data (in the file itself), but the end user should not see, that we've made such a change to a file. So we want to have versions but we also want to be able to change the file content without creating a new version.

Isn't there a possibility with pnp or with a plain call to the REST API or with CSOM?

Thank you in advance.

**Comment by patrick-rodgers** [comment]
There is not a capability in this library to make updates that does not create another version.
