### ISSUE TITLE
Access denied when adding a file.

### ISSUE THREAD

**Issue by LenoirRemi** [pnp/pnpjs#2955]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.22.0

### Target environment

NodeJS

### Additional environment details

I'm using NodeJS and certificate based MSAL for authentication.
I'm targeting a online SharePoint instance. 

### Question/Request

Hello,

I'm fairly new to SharePoint development and I'm facing an issue using this library.
I can do a bunch of actions on my SharePoint site but I can't upload a file. (a aspx page.)

This is how I authenticate using MSAL:
```javascript
const privateKey = fs.readFileSync(process.env.PRIVATEKEY_PATH);
const configuration = {
    auth: {
        authority: `https://login.microsoftonline.com/${process.env.TENANT_ID}`,
        clientCertificate: {
            thumbprint: process.env.THUMBPRINT,
            privateKey: privateKey,
        },
        clientId: process.env.CLIENT_ID,
    }
};
const sp = spfi(`https://${process.env.TENANT_NAME}.sharepoint.com/`).using(SPDefault({
    msal: {
        config: configuration,
        scopes: [`https://${process.env.TENANT_NAME}.sharepoint.com/.default`],
    },
}));
```

When i try to add a page like so: 
```javascript
await sp.web.getFolderByServerRelativePath(folderPath).files.addUsingPath(targetPath, data, { Overwrite: true });
```
I get this error: `HttpRequestError: Error making HttpClient request in queryable [403] Forbidden ::> {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied."}}}`
There is also this inside the response: `'917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically.'`

I have enable all the permissions for my application on Entra ID (Like `Sites.FullControl.All`.)

I'm pretty sure that I missed something, but after days of trying, I feel powerless. That's why I'm creating this issue.

Looking forward to hearing your answers.

**Comment by bcameron1231** [comment]
Hi, sorry you're having a tough time with this. Can you confirm that your permissions for Sites.FullControl.All have been granted by Tenant Admin for the Organization in Entra ID?

**Comment by LenoirRemi** [comment]
> Hi, sorry you're having a tough time with this. Can you confirm that your permissions for Sites.FullControl.All have been granted by Tenant Admin for the Organization in Entra ID?

Hi, yes I think so, this is what I can see:

![permissions](https://github.com/pnp/pnpjs/assets/12891980/4a660a48-e041-454f-b240-643a768a73cd)
