### ISSUE TITLE
Select ,expand and filter limits

### ISSUE THREAD

**Issue by praveendan** [pnp/pnpjs#2958]
### What version of PnPjs library you are using

2.x (No longer supported)

### Minor Version Number

13.0

### Target environment

All

### Additional environment details

The question is not environment specific

### Question/Request

I'm trying to find out the upper limit for Select ,expand and filter. If i understand it correctly, the pnpJS calls are translated to the SharePoint API calls to execute and the API calls have a limit of characters (2048 characters?).

I'm calling this function within a re-usable function I'm creating
(`splist `is the list instance , `selectList` is an array, `finalFilter` is a string,  `expandList` is an array and `SP_ITEMS_PER_CALL_LIMIT` is an upper bound)

For error handling purposes, I need to see what are the limits for the filter string (character limit) and the maximum lengths selectList  and expandList array should contain. I tried searching everywhere but could not find an answer

`spList.items.select(...selectList).filter(finalFilter).expand(...expandList).top(SP_ITEMS_PER_CALL_LIMIT)()`

**Comment by patrick-rodgers** [comment]
This doesn't appear to be a question related to the library. I believe those limits are defined by the browsers and the SP server applications.

**Comment by praveendan** [comment]
> This doesn't appear to be a question related to the library. I believe those limits are defined by the browsers and the SP server applications.

Thanks. So pnpJS is just generating the get calls and it's solely controlled by the browser and Server?
