### ISSUE TITLE
_parseResponse function in GraphBatch does not work as expected

### ISSUE THREAD

**Issue by pkmelee337** [pnp/pnpjs#296]
### Category
- [ ] Enhancement
- [ x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.2.3 ]

Please specify what version(s) of SharePoint you are targeting: [ Online, Modern Workbench]

### Expected / Desired Behavior / Question
I am executing an batch request with the GraphBatch object. (I kind of created a workaround for issue #294 ) My expectation is that I would retrieve skills after I retrieve them in a batch.

### Observed Behavior
When this request succeeds I am getting an error that this.request is undefined in the _parseResponse function from the GraphBatch object. I think this is because of the code on line 68 from batch.ts:
```
            .then(this._parseResponse)
```

When the code is executed like that 'this' is losing it's scope.

### Steps to Reproduce
Execute a batch request using pnpjs.

**Comment by patrick-rodgers** [comment]
Per my comment in the other issue, going to close this one and use #294 to track "make graph batching work". Thanks!
