### ISSUE TITLE
Property 'delete' does not exist on type 'DirectoryObject'

### ISSUE THREAD

**Issue by kbeeveer46** [pnp/pnpjs#2960]
### Major Version

3.x

### Minor Version Number

23

### Target environment

SharePoint Framework

### Additional environment details

SPFx 1.18.2

### Expected or Desired Behavior

The documentation says there is a delete method on directory objects https://pnp.github.io/pnpjs/graph/directoryobjects/#delete-directoryobject

When I use the sample code from the documentation it throws an error

### Observed Behavior

Error message. See screen shot below.

### Steps to Reproduce

```
import { graphfi, SPFx as graphSPFx } from "@pnp/graph";
import "@pnp/graph/groups";
import "@pnp/graph/directory-objects";

const graph = graphfi().using(graphSPFx(this._context));

const group = await graph.groups.filter(`displayName eq 'Client Portal MDP43838 GENERAL'`).select("id")();

if (group?.length && group[0].id)
{
      const deleted = await graph.directoryObjects.getById(group[0].id).delete()
}
```

![image](https://github.com/pnp/pnpjs/assets/12972554/8f33e5af-bfc9-4b84-8c78-bce6ce96e4c1)

**Comment by bcameron1231** [comment]
Hi. Our apologies, you are correct, this is a bug. I have just submitted a PR for this.
