### ISSUE TITLE
Bump nodejs dependencies version and engine version itself.

### ISSUE THREAD

**Issue by SPWizard01** [pnp/pnpjs#2967]
### Target environment

NodeJS

### Additional environment details

NodeJS v20

### Enhancement Idea

Hi,

We are using NodeJS with cert. authentication to connect to SharePoint, all seems to work but I get a lot of bad engine warnings because we are using Node v20 and it seems that is supported version for this library is Node v14+ ?

Not sure the rationale behind this but upgrading to 20+ would give you a benefit of not using node-fetch since its available(since v18) within node itself.

If that is not possible then is it possible to bump at least `@azure/msal-browser` and `@azure/msal-node`?

I have tried updating it myself on my fork, however the tests would not pass and I am not sure which node version I should use for test and build since the node types are from version v16 but the supported engine is from v14.

https://github.com/pnp/pnpjs/commit/396a121d02287c3bcf5185605a6ecec39e5792a5

**Comment by juliemturner** [comment]
Version 3 (the current version) is Node 16, Version 4 which we're hoping to release soon will be based in Node 18. This is done primarily to support the majority of the users who use the library with the SharePoint Framework which has that limitation.

**Comment by juliemturner** [comment]
Also yes, msal will be bumped in v4.

**Comment by SPWizard01** [comment]
Thanks for sharing, will wait for v4.
Meanwhile, I guess it does not hurt to copy the implementation and modify it a bit :)

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
