### ISSUE TITLE
How to retrieve all users using pnp/sp if the site contains more than 5000 users?

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#2970]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.15.0

### Target environment

All

### Additional environment details

SharePoint Online, SPFx, React

### Question/Request

Hello Everyone,

I have tried to get all site users programmatically using the below code.

```
import { spfi } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/site-users/web";

const sp = spfi(...);
// get the first 100 users
// const users = await sp.web.siteUsers();
// get upto 5000 users
const users = await sp.web.siteUsers.orderBy("Title", true).top(5000)();
console.log("users: ", users);
```

The above code is working as expected if the site contains less than 5000 users.

But if the site contains more than 5000 users what changes need to do in the above code?

Can anyone help me with the same?

Thanks

**Comment by bhoomesh-spe** [comment]
I have tried the below code but it is not `working.

```
import { spfi } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/site-users/web";

const sp = spfi(...);
const users = await sp.web.siteUsers.orderBy("Title", true).top(10000)();
console.log("users: ", users);`
```

**Comment by bcameron1231** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
