### ISSUE TITLE
Need help in understanding the Sharepoint Patterns and Policies.

### ISSUE THREAD

**Issue by RachitkumarJain** [pnp/pnpjs#2988]
### What version of PnPjs library you are using

3.x

### Minor Version Number

24.0

### Target environment

SharePoint Framework

### Additional environment details

I am using Nodejs

### Question/Request

Hi Community,
I am trying to getting started with Sharepoint Patterns and Policies. I have a small doubt regarding 
1) The users retrieval and creation, Will the user created will be synced in Office 365?
2) Is there any user creation in Sharepoint Pnp specfically.
3) Any operation done using the Sharepoint pnpjs package will reflect on the Sharepoint Online or is there a separate portal or application for Sharepoint Patterns and Policies.

Thank you for the assistance in advance.

Regards.

**Comment by juliemturner** [comment]
@RachitkumarJain - PnPjs is a collection of fluent libraries for consuming SharePoint, Graph, and Office 365 REST APIs in a type-safe way. You can use it within SharePoint Framework, Nodejs, or any JavaScript project. 

To understand the platform better you might want to review this documentation on the SharePoint REST APIs that we provide an typesafe interface for: https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service?tabs=http. In addition this is a link to the Microsoft Graph APIs which provide RESTful apis for not only SharePoint but all the other Microsoft 365 services as well: https://learn.microsoft.com/en-us/graph/

**Comment by RachitkumarJain** [comment]
@juliemturner - Thank you for the assistance. I will go through the documentation, I have a small doubt related to Sharepoint Online Rest API. I found there is no user creation API specifically for the Sharepoint, Is that correct or I am missing something. Can you please assist how to create a user in Sharepoint PnP.

Thank you in advance.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Comment by juliemturner** [comment]
@RachitkumarJain - you don't create users in SharePoint you create users in Microsoft Entra ID (fka Azure Active Directory)... you can do that with the Microsoft Graph APIs... I would STRONGLY recommend that you spend time in the platform and learn how it works before you try to extend it. If you have an MSDN license you can get a developer tenant and use that as a playground to learn about the platform. Once you clearly understand how it all fits together then maybe start trying to extend it.
