### ISSUE TITLE
Example showing creating custom lib for a custom api secured with AzureAD

### ISSUE THREAD

**Issue by patrick-rodgers** [pnp/pnpjs#30]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnp/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [latest]

### Expected / Desired Behavior / Question
Create a sample that shows extending pnp/odata for a custom REST API endpoint secured with AzureAD.

**Comment by umaknow-felix** [comment]
Hello @patrick-rodgers,

First of all, thank you for this wonderful library that I use everyday!

Were you able to produce the doc/sample? I've checked the repo/doc and haven't found anything regarding this enhancement.

Félix-Antoine

Regards

**Comment by patrick-rodgers** [comment]
Oh, no I hadn't had a chance yet. Didn't mean to close this, thanks.

**Comment by vipulkelkar** [comment]
Hi @patrick-rodgers  I have a created a simple CRUD API secured with Azure AD and built a custom library for it using the PnPJS odata classes. Works in SPFx and local node debug. 
Is this still open to share the sample ?

**Comment by patrick-rodgers** [comment]
Absolutely! Would love to see it, and perhaps you can demo on one of our calls?

**Comment by vipulkelkar** [comment]
Sure @patrick-rodgers . The basic working code is [here in my repo](https://github.com/vipulkelkar/CustomApiLibrary-PnP) however, there is some polishing/cleanup required and i wanted to add a small functionality to it as well. Also, haven't done detailed documentation to explain the setup and how the code works. I am away for two weeks however, I'll complete this soon as I am back and buzz here on the thread for you to take a look :)

**Comment by vipulkelkar** [comment]
Hi @patrick-rodgers I have done the documentation and cleaned up the code. The repo is [here](https://github.com/vipulkelkar/PnPCustomApiLibrary). Would you like to take a look and let me know if something needs to be added/changed ?

**Comment by vipulkelkar** [comment]
Hi @patrick-rodgers  have you had a chance to take a look at the sample ?

**Comment by patrick-rodgers** [comment]
Hi @vipulkelkar - I have not had a chance yet, let me bring in @PopWarner as he might have an opening before I do. It is the end of our FY so been a very busy month for me. Haven't forgotten you :)

**Comment by vipulkelkar** [comment]
I am sure :) Thanks for the update
Also if it is easier and saves time, I can jump on a call and explain the example on my setup when any of you find an opening.....cheers
