### ISSUE TITLE
Question: Setting property bag values (e.g. on folders) - possible at all via REST? 

### ISSUE THREAD

**Issue by frevds** [pnp/pnpjs#300]
Is it at all possible to update the properties (in the property bag, not object properties or item fields) of folders/items/webs via REST? A MERGE fails.

**Comment by koltyakov** [comment]
@frevds, this is currently NOT possible via REST. Property bags are readonly. But can be updated with JSOM or raw JSOM XML package sent with PnPjs's SPHttpClient.

**Comment by frevds** [comment]
Thank you for the quick reply and valueable information. I grabbed the XML sent from JSOM and will try that. It calls the SetFieldValue method on the properties object.

**Comment by koltyakov** [comment]
@frevds, this [sample](https://github.com/koltyakov/sp-sig-20180705-demo/blob/master/src/02-clientSvc/helper.ts) from SIG call demo can be handy. Also, there is an option of using [sp-clientsvc](https://github.com/pnp/pnpjs/tree/dev/packages/sp-clientsvc), but I can't provide you with a quick sample as I not so experiences with sp-clientsvc as @patrick-rodgers.

**Comment by frevds** [comment]
Thanks for the sampes. 

I was checking the Microsoft.SharePoint.dll with ILSpy. Turns out there is a SPFolder.Properties_Client property which returns an object of type SPFolderPropertyValues, having that SetFieldValue method. You can even trigger it using REST (`webURL + "/_api/web/lists(@listId)/RootFolder/Properties/SetFieldValue(fieldName=@name,value=@value)"`), but unfortunately the value parameter is of type object, and the call fails with `{"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":"The method SetFieldValue cannot be invoked as its parameter value is not supported."}}`. So that's almost, but still not possible. 

Until then I am going to send raw xml as you mentioned to `/_vti_bin/client.svc/ProcessQuery` like this:
![image](https://user-images.githubusercontent.com/5341447/47386231-6e01ef00-d70c-11e8-8782-3642584f258c.png)
