### ISSUE TITLE
SPFx Context supplied to SPFx Behavior is null or undefined

### ISSUE THREAD

**Issue by RichardPo** [pnp/pnpjs#3012]
### Major Version

4.x

### Minor Version Number

0.0

### Target environment

SharePoint Framework

### Additional environment details

I'm developing a client side web part.

### Expected or Desired Behavior

I'm trying to setup graph with the SPFx context. I expect to get back an graphfi object when the context is not null or undefined.

### Observed Behavior

While the context is not null and also not undefined, I get the error that the context is null or undefined. I debugged with console.log and saw that the context (this.context from the web part) is not null/undefined, it gives back the context object succesfully. Also, I downgraded to version 3 and it suddenly worked. But i need some functionality which is introduced in version 4. So downgrading is not an option.

### Steps to Reproduce

Here is the code i'm running: 
```typescript
import {graphfi, SPFx} from "@pnp/graph";
this.graph = graphfi().using(SPFx(this.context));
```

**Comment by bcameron1231** [comment]
Hi, thank you for finding this. It is indeed a bug. This issue is closed as we just deployed a Hotfix. Please find version 4.0.1 on npm.
