### ISSUE TITLE
Parsing verbose JSON

### ISSUE THREAD

**Issue by futurliberta** [pnp/pnpjs#3015]
### What version of PnPjs library you are using

4.x

### Minor Version Number

1.0

### Target environment

SharePoint Framework

### Additional environment details

In browser

### Question/Request

Hi,

I'm using pnpjs in the browser. My SP version is 2013 (can't upgrade...) and i have to use verbose JSON (only type supported in my version)

so, i injected this header in my config :

```ts
export const sp = spfi('/test').using(
  SPBrowser({
    baseUrl: '/test',
  }),
  Caching(),
  InjectHeaders({
    accept: 'application/json;odata=verbose',
  }),
).using(PnPLogging(LogLevel.Verbose));
```

But the JSON responses are wrapped into a d: like this :

```json
{
    "GetContextWebInformation": {
        "__metadata": {
            "type": "SP.ContextWebInformation"
        },
        "FormDigestTimeoutSeconds": 1800,
        "FormDigestValue": "..........",
        "LibraryVersion": "15.0.5545.1000",
        "SiteFullUrl": ".............",
        "SupportedSchemaVersions": {
            "__metadata": {
                "type": "Collection(Edm.String)"
            },
            "results": [
                "14.0.0.0",
                "15.0.0.0"
            ]
        },
        "WebFullUrl": "..............."
    }
}
```

And it looks like the parser didn't expect this cause when i post data, the digest inserted is undefined. 

![image](https://github.com/pnp/pnpjs/assets/10220170/86c08e21-0a62-4d89-b03b-b06c846a0b4c)

Any way to fix it without writing my own behavior ?

The problem is here if it can help :

![image](https://github.com/pnp/pnpjs/assets/10220170/e21978c5-9104-4526-af4d-5b0e64377dbd)

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
