### ISSUE TITLE
@pnp/graph - spfx msal v3 single sign on redirect

### ISSUE THREAD

**Issue by pmmarkley** [pnp/pnpjs#3018]
### Major Version

4.x

### Minor Version Number

0.1

### Target environment

SharePoint Framework

### Additional environment details

Node v18.20.2
Sharepoint Framework 1.18.2
@pnp/cli-microsoft365@7.6.0
corepack@0.25.2
gulp@4.0.2
npm@10.5.0
yo@5.0.0

### Expected or Desired Behavior

I have followed [Getting Started with PnpJs](https://julieturner.net/post/getting-started-pnpjs/)

I expect that 
```TypeScript
const _graph = getGraph(this.props.context);
const events = await _graph.me.calendar.events(); 
console.log(events.length);
```
returns the number of events in my calendar.

### Observed Behavior

The call to getGraph returns fine, however when attempting to retrieve the events from my calendar the page reloads, it looks like it is redirecting to msal v3 single sign on redirect before the page reloads.

### Steps to Reproduce

Here is the code I'm running:

**pnpjsConfig.ts**
```TypeScript
import { WebPartContext } from "@microsoft/sp-webpart-base";
import { spfi, SPFI,SPFx as spSPFx } from "@pnp/sp";
import { graphfi, GraphFI,SPFx as graphSPFx } from "@pnp/graph";
import { LogLevel, PnPLogging } from "@pnp/logging";

import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/batching";
import "@pnp/graph/calendars";
import "@pnp/graph/users";

//@ts-expect-error this is due to esLint being overactive
let _sp: SPFI = null;
//@ts-expect-error this is due to esLint being overactive
let _graph:GraphFI = null;

export const getSP = (context?: WebPartContext): SPFI => {
    
    if (context !== null && _sp === null) {
        //@ts-expect-error blerb
        _sp = spfi().using(spSPFx(context)).using(PnPLogging(LogLevel.Warning));
    }
    return _sp;
}

export const getGraph = (context?: WebPartContext): GraphFI => {
    
    if (context !== null && _graph === null) {
        //@ts-expect-error blerb
        _graph = graphfi().using(graphSPFx(context)).using(PnPLogging(LogLevel.Warning));
    }
    return _graph;
}
```
**CcgTimeRequestVisualizer.tsx**
```TypeScript
import * as React from 'react';
import styles from './CcgTimeRequestVisualizer.module.scss';
import type { ICcgTimeRequestVisualizerProps } from './ICcgTimeRequestVisualizerProps';
import { escape } from '@microsoft/sp-lodash-subset';
import { ICcgTimeRequestVisualizerState } from './ICcgTimeRequestVisualizerState';
import { getGraph } from '../pnpjsConfig';
import '@pnp/graph';
import { IUser } from '@pnp/graph/users';

export default class CcgTimeRequestVisualizer extends React.Component<ICcgTimeRequestVisualizerProps, ICcgTimeRequestVisualizerState> {
  
  
  constructor(props: ICcgTimeRequestVisualizerProps) {
    
    super(props);
  }
  
  private async _addToCalendar(): Promise<void> {
    const _graph = getGraph(this.props.context);
    const events = await _graph.me.calendar.events();
    console.log(events.length);
    
await _graph.me.calendar.events.add({
      "subject": "Katie Alley - Perk",
      "body": {
        "content": "Katie Alley - Perk"
      },
      "start": {
          "dateTime": "2024-05-10T08:00:00",
          "timeZone": "Eastern Standard Time"
      },
      "end": {
          "dateTime": "2024-05-10T17:00:00",
          "timeZone": "Eastern Standard Time"
      }
    });
  }
  public render(): React.ReactElement<ICcgTimeRequestVisualizerProps> {
    const {
      listName,
      userDisplayName
    } = this.props;

    return (
      <section className={`${styles.ccgTimeRequestVisualizer}`}>
        <div className={styles.welcome}>
          <h2>Well done, {escape(userDisplayName)}!</h2>
          <p>You have selected ${listName}</p>
        </div>
        <button type="button" onClick={ this._addToCalendar.bind(this)}>Add To Calendar</button>
      </section>
    );
  }
}

```

**Comment by juliemturner** [comment]
So, there are a couple of things, one I can see right away and the other I'm not sure because you didn't share enough code. But essentially, you're call in ``

```ts
private async _addToCalendar(): Promise<void> {
    const _graph = getGraph(this.props.context);
    const events = await _graph.me.calendar.events();
    console.log(events.length);
    ....
```

should not be passing `this.props.context`. The point of the `pnpjsConfig.ts` file implementation is that you initialize the variable when you're webpart first loads and then when you need an instance of the graphfi interface you can make a call (without context) to return it. Since it looks like you copied this from our sample, I would take a look at the onInit call in the root webpart ts file so you can see what I'm suggesting.

**Comment by bcameron1231** [comment]
I'm having trouble reproducing. I don't have any issues with reloading and it's working as expected. Can you provide a bit more context of your environment? What's your browser, are you loading just in SharePoint, Workbench, Teams?

Looking through some recent issues in the SP-Dev-Docs site, I wonder if it's an issue outside of the library, and a problem on Microsoft's side.

https://github.com/SharePoint/sp-dev-docs/issues/9485
https://github.com/SharePoint/sp-dev-docs/issues/9604

**Comment by pmmarkley** [comment]
My apologizes, to fix this issue I simply needed to login to SharePoint admin center and grant access for Microsoft Graph to Calendars.ReadWrite. Thanks for your help.
