### ISSUE TITLE
Async Iterator Pattern Type Error

### ISSUE THREAD

**Issue by c-eiser13** [pnp/pnpjs#3023]
### Major Version

4.x

### Minor Version Number

4.0.1

### Target environment

SharePoint Framework

### Additional environment details

Node 18.19.2
Windows 10
SPFx 1.18.2

### Expected or Desired Behavior

Use the async iterator pattern to get items in pages or get all items.

### Observed Behavior

When I attempt to use this pattern in a freshly scaffolded SPFx 1.18.2 project, I am getting the below error:

![image](https://github.com/pnp/pnpjs/assets/42096464/4381d3af-e023-4a29-ae0f-ee54db473e9c)

If I cast with as any, the code runs fine. I've checked my tsconfig settings and everything looks good there. 

### Steps to Reproduce

Create new SPFx project, install latest @pnp dependencies and copy the sample code from the async iterator docs.

**Comment by bcameron1231** [comment]
Hi, I am unable to reproduce. Have you tried to close out of VS Code and re-open it? I've seen scenarios where VS Code has had trouble interpreting some of our types, but restarting VS Code helps.

I don't have any iterator issues.
![image](https://github.com/pnp/pnpjs/assets/7944457/b8330b1e-17f2-476a-8e4c-14df5fccb394)

**Comment by c-eiser13** [comment]
@bcameron1231 thanks for the quick reply, ran into this late on Friday, fairly confident I closed VS code and restarted, even after a pc reboot this am, was still seeing type error until making a modification in tsconfig, saving, then it went away, strange for sure, but all good now. Thanks!
