### ISSUE TITLE
Why use the .js extension in imports?

### ISSUE THREAD

**Issue by Jonathan-Baldwin** [pnp/pnpjs#3028]
### What version of PnPjs library you are using

4.x

### Minor Version Number

4.0.0

### Target environment

All

### Additional environment details

Just reading the code base in GitHub 🧑‍💻

### Question/Request

I have a general question about the codebase.  

I notice that there are references to `.js` files in the import statements across many of the files in the [sp package](https://github.com/pnp/pnpjs/tree/version-4/packages/sp).  i am curious why the `.js` extension is needed here as this appears to be a TypeScript project.  For example https://github.com/pnp/pnpjs/blob/a111ec8f95bc5b3bea08e6df1043d80f3b35ac59/packages/sp/lists/types.ts#L16

Is there a reason that the extension cannot be omitted within the import statements in this project?

**Comment by patrick-rodgers** [comment]
This is done to help with the node module resolution rules between esm and commonjs.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
