### ISSUE TITLE
Email Notification delays while send email using @pnp/sp/utilities

### ISSUE THREAD

**Issue by bhoomesh-spe** [pnp/pnpjs#3029]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.15.0

### Target environment

SharePoint Framework

### Additional environment details

SharePoint Online, SPFx React

### Question/Request

Hello Everyone,

I need to send email notifications while adding/updating the SharePoint list items. So, I have used [@pnp/sp/utilities](https://pnp.github.io/pnpjs/sp/sp-utilities-utility/) for the same.

I have implemented the below call to send an email notification while adding/updating the SharePoint list items.

```
import { spfi } from "@pnp/sp";
import "@pnp/sp/sputilities";
import { IEmailProperties } from "@pnp/sp/sputilities";

export const sendMail = async (mailProperties) => {
    const sp: SPFI = getSP();
    const emailProps: IEmailProperties = mailProperties;
    await sp.utility.sendEmail(emailProps);
};
```

The email notifications functionality is working as expected but sometimes we face **delays** in the email notifications.

Can anyone help me with the same?

Thanks

**Comment by patrick-rodgers** [comment]
We don't send the emails, we just send the request to the server. It may be that the service is busy or something else happens that queues the emails for later delivery.

**Comment by bhoomesh-spe** [comment]
@patrick-rodgers   Thanks for the quick response. Is there any alternative to sending an email with a client-side code like @pnp/sp/utilities?

**Comment by juliemturner** [comment]
yes/no... No, you don't need to create a separate one you just need to add the permissions that you want to request for graph to the package-solution.json in the [webApiPermissionRequests](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#configure-the-api-permissions-requests) section and then get a SharePoint Admin to approve the api (if it's not already approved) in the SharePoint Admin center. Another option is to follow [Andrew Connell's advice](https://www.voitanos.io/blog/consider-avoiding-declarative-permissions-with-azure-ad-services-in-sharepoint-framework-projects) and skip the declarative permissions and use either PowerShell or the CLI for Microsoft 365 to grant permissions directly.

**Comment by bhoomesh-spe** [comment]
@juliemturner - Thank you again for the valuable feedback. I will try at my end and get back to you soon.
