### ISSUE TITLE
sendEmail from property not working

### ISSUE THREAD

**Issue by gkiss02** [pnp/pnpjs#3032]
### What version of PnPjs library you are using

1.x (No longer supported)

### Minor Version Number

3.2

### Target environment

All

### Additional environment details

I'm using the send email method authenticate with sp.

### Question/Request

The email successfully delivered, but it says from SharePoint Online, and not form tester

        await pnp.sp.utility.sendEmail({
            From: "Tester",
            To: ["test@example.hu"],
            Subject: "Test",
            Body: "Hi this is a test email",
        })

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
