### ISSUE TITLE
Next on cached pagination request

### ISSUE THREAD

**Issue by Kalshu** [pnp/pnpjs#3034]
### Major Version

3.x

### Minor Version Number

24.0

### Target environment

Browser App (Hosted external to Microsoft 365 platform)

### Additional environment details

N/A

### Expected or Desired Behavior

Get next on paged request from cache is not undefined

### Observed Behavior

Get next on paged request from cache is undefined
![image](https://github.com/pnp/pnpjs/assets/2726957/36b23dbf-940e-4220-8f83-b1104dcda3e1)

### Steps to Reproduce

Make a call to retrieve the top 20 user from pnp lib
/graph/users?$count=true&$top=20&$select=displayName%2cid%2cdepartment%2cjobTitle%2clocation%2cimageUrl%2cmail&$filter=accountEnabled+ne+false

Make a second call with same args to retrieve the request from the cache

In the result, next is not defined, but hasNext is true
/graph/users?$count=true&$top=20&$select=displayName%2cid%2cdepartment%2cjobTitle%2clocation%2cimageUrl%2cmail&$filter=accountEnabled+ne+false

In 3.21 version, next is defined but return the result from cached request.

I will try to push a minimum env to reproduce this behaviors

**Comment by bcameron1231** [comment]
Hi, Unfortunately we do not support pagination with caching. We did for a brief time with 3.21 but it had some negative side effects, so we had to revert it.

We may potentially bring it into version 4. 

Duplicate of https://github.com/pnp/pnpjs/issues/2938

**Comment by Kalshu** [comment]
Thanks, for this quick response.

We will plan the migration to v4!
