### ISSUE TITLE
version 4 - @pnp/sp/favorites doesn't exists

### ISSUE THREAD

**Issue by JamesDerrickHH** [pnp/pnpjs#3044]
### What version of PnPjs library you are using

4.x

### Minor Version Number

4.0.1

### Target environment

All

### Additional environment details

I'm building a sharepoint webpart (1.19) using react (17)

### Question/Request

I'm trying to pull back all items for a site that have been favourited
However, webpack gives me a compile error saying the module doesn't exist
I have imported it, as per the documents, 
import "@pnp/sp/favorites";
Looking at the code it seems to exist in version 3 but not version 4, is this intentional?
Is there anything I can do to work around this?

**Comment by juliemturner** [comment]
@JamesDerrickHH, yes it was intentional as noted in our changelog because those endpoints are better supported by graph calls. I think what you're looking for is [followed sites](https://pnp.github.io/pnpjs/graph/sites/#followedsites).

**Comment by JamesDerrickHH** [comment]
Thanks, I'm specifically looking to get followed items and folders, but knowing that graph is the way to go is more than enough to start investigating
