### ISSUE TITLE
Taxonomy is impossible to work with in v4

### ISSUE THREAD

**Issue by zumiek** [pnp/pnpjs#3054]
### What version of PnPjs library you are using

4.x

### Minor Version Number

1.0

### Target environment

SharePoint Framework

### Additional environment details

Node 18.18.2

### Question/Request

In the current documentation for working with taxonomy in v4.01 you say that it's possible to use graph.termStore.**searchTerm**()
which seems to be missing in the package, so how am I supposed to find the TermSetId of a term if I only have the label and the TermGUID?

The only reasonable way seems to be to go back to v3 where the taxonomy was still a part of SP package, but it feels a bit backwards.

Furthermore ITermInfo seems to be missing as well so the documentation for v4 taxonomy in the graph package seems to be well out of date and in need of an update...

**Comment by bcameron1231** [comment]
Hi. So apologies for some of the confusion, this is bad documentation that didn't get reflected when we made the transition to Graph from the SP library (we copied over most of the docs). 

The Microsoft Graph endpoints for Taxonomy do not support search and as a result we've had to removed that functionality from the library in v4 (we missed removing from the docs). There unfortunately isn't a way in Graph to get a Term Id by the Guid or Label.
