### ISSUE TITLE
Graph API me/OwnedObjects is missing with pnp js 3.0

### ISSUE THREAD

**Issue by ArunRajiv** [pnp/pnpjs#3056]
### What version of PnPjs library you are using

3.x

### Minor Version Number

24.0

### Target environment

SharePoint Framework

### Additional environment details

I'm struggling to get the endpoint me/ownedObjects with pnp js graph. I found this method is missing with directoryObject. what is the way around to achieve this?

### Question/Request

I'm struggling to get the endpoint me/ownedObjects with pnp js graph. I found this method is missing with directoryObject. what is the way around to achieve this?
![image](https://github.com/pnp/pnpjs/assets/19972139/7848be2f-43a0-46a7-935c-d4d1fad4c689)

**Comment by bcameron1231** [comment]
Hi. Take a look at our documentation for Calling Other Endpoints (endpoints that we currently don't have in the library).

https://pnp.github.io/pnpjs/concepts/calling-other-endpoints/

const user= graph.users.getById('jane@contoso.com');
const graphQueryable = GraphQueryable(user, "ownedObjects");
const ownedObjects = await graphGet(graphQueryable);

**Comment by ArunRajiv** [comment]
Thank you this was helpful :) I will try it out.
