### ISSUE TITLE
SortList Property not working in search Result

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/pnpjs#307]
```
  const _searchQuerySettings: SearchQuery = {
      //Search Properties
      TrimDuplicates: true,
      RowLimit: 500,
      EnableSorting:true,
      SortList:[{
        Property:'Title',
        Direction:SortDirection.Ascending
      }]
      
    }

```
It gives me following error : 
**Uncaught (in promise) Error: Error making HttpClient request in queryable: [400]  ::> {"responseBody":{"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"Invalid parameter: SortList."}}},"responseHeaders":{}}
    at parsers.ts:59**

**Comment by patrick-rodgers** [comment]
What version of the library are you using? What version of SharePoint are you targeting?

**Comment by harshdamaniahd** [comment]
Library Version : 1.2.1
SharePoint Online

**Comment by gautamdsheth** [comment]
You are trying to sort data on OOTB Title managed property which is set to unsortable and cant be changed in SPO. So, you need to create your own managed property or map the crawled properties to a RefinableStringXX property and use that property in your code.

![capture](https://user-images.githubusercontent.com/8832018/47504440-e346fe80-d889-11e8-8405-2394e5f0e73d.PNG)

**Comment by harshdamaniahd** [comment]
Thanks, I Get it now.
