### ISSUE TITLE
Get All method is missing in the version 4

### ISSUE THREAD

**Issue by thahirvly** [pnp/pnpjs#3078]
### What version of PnPjs library you are using

4.x

### Minor Version Number

4.2.0

### Target environment

SharePoint Framework

### Additional environment details

React app hosed in SharePoint site

### Question/Request

Hi,
**SP -> List Items -> Get All items** option is missing in the latest version. Please let me know how to retrieve all items using a single request.

**Comment by patrick-rodgers** [comment]
Get all never executed a single request, it just hid the paging for you. Now that we support the [async iterator](https://pnp.github.io/pnpjs/sp/items/#get-paged-items) pattern, paging is much simpler, and you can use a loop to gather all the items. If this is something you do often, easy enough to create a helper function.

I would, as always, point out there is often little reason to get all the items in a list for a client application. Better if you can just show the last 5 articles or similar.

**Comment by thahirvly** [comment]
> Get all never executed a single request, it just hid the paging for you. Now that we support the [async iterator](https://pnp.github.io/pnpjs/sp/items/#get-paged-items) pattern, paging is much simpler, and you can use a loop to gather all the items. If this is something you do often, easy enough to create a helper function.
> 
> I would, as always, point out there is often little reason to get all the items in a list for a client application. Better if you can just show the last 5 articles or similar.

Thank you for the suggestion. It looks like, [Async Paging](https://pnp.github.io/pnpjs/sp/items/) link is not working in the page. It should redirect to [Async Paging](https://pnp.github.io/pnpjs/concepts/async-paging/) I believe.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
