### ISSUE TITLE
ISearchQuery is missing EnableDynamicGroups

### ISSUE THREAD

**Issue by mdissel** [pnp/pnpjs#3088]
### Target environment

SharePoint Framework

### Enhancement Idea

The ISearchQuery interface and implementation is missing the EnableDynamicGroups option
See https://learn.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview#enabledynamicgroups

**Comment by bcameron1231** [comment]
Hi. So this documentation appears to be wrong, or a bug in the SharePoint API.

EnableDynamicGroups works when it's passed over as a query param, but it appears it is not supported on the POST Microsoft.Office.Server.Search.REST.Search Request. 

![image](https://github.com/user-attachments/assets/67dc64fa-c5da-4280-9829-4b916887a6ef)

**Comment by mdissel** [comment]
Thanks!. I'm wondering if the setting is enabled by default when using a POST request.
