### ISSUE TITLE
Access a Share's driveItem resource

### ISSUE THREAD

**Issue by necik11** [pnp/pnpjs#3091]
### Major Version

3.x

### Minor Version Number

3.20.1

### Target environment

All

### Additional environment details

I created a web part that I want to use in Teams or on the web.

### Expected or Desired Behavior

I am trying to get sharepoint Item from ShareLink. = [Access a Share's driveItem resource](https://pnp.github.io/pnpjs/graph/shares/#access-a-shares-driveitem-resource)

### Observed Behavior

![image](https://github.com/user-attachments/assets/f27281ad-d7db-4950-8206-522cad0753cb)

295 line give me undefined
302 not working

### Steps to Reproduce

This piece of code not working well:
```
import "@pnp/graph/shares";
... 
const graph = graphfi().using(graphSPFx(context)); 
const shareLinkEncoded: string = graph.shares.encodeSharingLink(shareLink);
const shareLinkInfo = {
    encodedSharingUrl: shareLinkEncoded,
    redeemSharingLink: false
};
const sharedDriveItem = (await graph.shares.useSharingLink(shareLinkInfo)).driveItem;
const driveItemInfo1 = await graph.shares.getById(sharedDriveItem.id).driveItem();
const driveItemInfo2 = await graph.shares.getById(shareLinkEncoded).driveItem();
```

I was searching docs: [Accessing shared DriveItems](https://learn.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http#example-single-file)  and it should call:
GET /shares/{shareIdOrUrl}/driveItem

and sharedDriveItem  call only:
GET /shares/{shareIdOrUrl}

when i try on[ grahp explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) its working well

**Comment by bcameron1231** [comment]
Hi. So looks like a couple issues. Our docs may be wrong, but we also have a typing issue in the shares module which is why you can't call driveItem().  Please see a full set of code which should work for you. In the mean time we'll update the library.

```
// my own encoding function
function encodeSharingLink(url) {
    return `u!${btoa(url).replace(/=$/, "").replace(/\//g, "_").replace(/\+/g, "-")}`;
}

var fileUrl="https://Test.sharepoint.com/sites/TestSite/Files/Test.txt";
var encodedUrl = encodeSharingLink(fileUrl);

const shareLink: IShareLinkInfo = {
    encodedSharingUrl: encodedUrl,
};
        
const sharedDriveItem =  await graph.shares.useSharingLink(shareLink);
const driveItem = await (graph.shares.getById(sharedDriveItem.id) as IShare).driveItem();
```

**Comment by necik11** [comment]
Little edit:
Conversion of type 'SharedDriveItem' to type 'IShare' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
Quick fix:
`const driveItem = await (graph.shares.getById(sharedDriveItem.id) as unknown as IShare).driveItem();`
After I have got driveItem object! 
Thanks much
