### ISSUE TITLE
Confusion with encodeURIComponent usage

### ISSUE THREAD

**Issue by pedro-pedrosa** [pnp/pnpjs#310]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.3]

Please specify what version(s) of SharePoint you are targeting: [any]

### Expected / Desired Behavior / Question
I was working with a SharePoint list called "How can we help?" and came across a problem. Basically I start by creating the list with the title "HowCanWeHelp" so I can control the URL of the list, then I update the title of the list to "How can we help?". Then I proceed with further changes to the list like adding fields and stuff.

Renaming the list worked fine, but then it started throwing errors because I'm using `lists.getByTitle()` and the question mark in the title throws it off.

Question: is it the responsibility of the user to know that the argument passed to `getByTitle` is used in a URL so they have to `encodeURIComponent` it? Do I have to know this is different from the `update` call I just made and worked because one is POST and the other is GET? _Do I even have to know one is POST and the other is GET?_

I've looked at the source code and it does `encodeURIComponent` the arguments passed to methods **in some places** but mostly I believe this is left to the user. Some tooltips on methods actually instruct the user to use `encodeURIComponent` on arguments if they contain URL characters.

Obviously right now adding `encodeURIComponent` to all methods would break a lot of existing code, just wanted to hear your opinion.

**Comment by patrick-rodgers** [comment]
See also #313.

**Comment by patrick-rodgers** [comment]
Closing this to have the discussion on #313.
