### ISSUE TITLE
Cannot find module '@pnp/sp/items/get-all'

### ISSUE THREAD

**Issue by abhishekjdgsl** [pnp/pnpjs#3101]
### Major Version

4.x

### Minor Version Number

3.0

### Target environment

SharePoint Framework

### Additional environment details

"version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=18.17.1 <19.0.0"
  },
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@fluentui/react": "^7.199.1",
    "@microsoft/decorators": "1.19.0",
    "@microsoft/sp-application-base": "1.19.0",
    "@microsoft/sp-component-base": "1.17.4",
    "@microsoft/sp-core-library": "1.17.4",
    "@microsoft/sp-dialog": "1.19.0",
    "@microsoft/sp-listview-extensibility": "1.19.0",
    "@microsoft/sp-lodash-subset": "1.17.4",
    "@microsoft/sp-office-ui-fabric-core": "1.17.4",
    "@microsoft/sp-property-pane": "1.17.4",
    "@microsoft/sp-webpart-base": "1.17.4",
    "@pnp/sp": "^4.3.0",
    "office-ui-fabric-react": "^7.199.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "tslib": "2.3.1"
  },
  "devDependencies": {
    "@microsoft/eslint-config-spfx": "1.20.1",
    "@microsoft/eslint-plugin-spfx": "1.20.1",
    "@microsoft/rush-stack-compiler-4.7": "0.1.0",
    "@microsoft/sp-build-web": "1.20.1",
    "@microsoft/sp-module-interfaces": "1.17.4",
    "@rushstack/eslint-config": "2.5.1",
    "@types/react": "17.0.45",
    "@types/react-dom": "17.0.17",
    "@types/webpack-env": "~1.15.2",
    "@typescript-eslint/parser": "^7.11.0",
    "ajv": "^6.12.5",
    "eslint": "8.7.0",
    "eslint-plugin-react-hooks": "4.3.0",
    "gulp": "4.0.2",
    "typescript": "4.7.4"
  }

### Expected or Desired Behavior

Based on [getAllItems](https://pnp.github.io/pnpjs/sp/items/#get-all-items) we should be able to leverage the below code to get all items for a list.

### Observed Behavior

ERROR:
Cannot find module '@pnp/sp/items/get-all'

CALL STACK:
Error: Cannot find module '@pnp/sp/items/get-all'
    at webpackMissingModule (https://localhost:4321/dist/client-details-form-web-part.js:325:50)
    at 2496 (https://localhost:4321/dist/client-details-form-web-part.js:325:146)
    at __webpack_require__ (https://localhost:4321/dist/client-details-form-web-part.js:37709:41)
    at 9710 (https://localhost:4321/dist/client-details-form-web-part.js:907:77)
    at __webpack_require__ (https://localhost:4321/dist/client-details-form-web-part.js:37709:41)
    at https://localhost:4321/dist/client-details-form-web-part.js:37791:87
    at https://localhost:4321/dist/client-details-form-web-part.js:37910:3
    at https://localhost:4321/dist/client-details-form-web-part.js:37913:12
    at Object.execCb (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d2d0d2e1b878580f3a2b5b3163b29183.js:199:10299), <anonymous>:30:41)
    at Z.check (eval at e (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d2d0d2e1b878580f3a2b5b3163b29183.js:199:10299), <anonymous>:18:439)

### Steps to Reproduce

import { spfi, SPFx, SPFxToken } from "@pnp/sp";
import { Web } from "@pnp/sp/webs";
import { IAttachmentFileInfo } from "@pnp/sp/attachments";
import { CommonConstants } from "../common/ICommon";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/fields";
import "@pnp/sp/content-types/list";
import "@pnp/sp/files";
import "@pnp/sp/folders";
import "@pnp/sp/batching";
import "@pnp/sp/items/get-all";

`await sp.web.lists.getByTitle(Item.listName).items.filter("Id ge 1000").select("*").getAll();`

**Comment by juliemturner** [comment]
Please see the [transition documentation from v3-v4](https://pnp.github.io/pnpjs/transition-guide/#async-iterator-pattern) which outlines that get-all was deprecated and the new method to use.

**Comment by abhishekjdgsl** [comment]
thank you @juliemturner, I'll update code accordingly
