### ISSUE TITLE
breakRoleInheritance crashing a Azure Function

### ISSUE THREAD

**Issue by Dangerous-Mind** [pnp/pnpjs#3104]
### Major Version

4.x

### Minor Version Number

4.3.0

### Target environment

NodeJS

### Additional environment details

A NodeJS Azure Function Timer Job that takes care of some provisioning of libraries.

### Expected or Desired Behavior

The permissions on the library should be broken.
The code 0x80131904 might be a throttling issue, so it should be taken care has a throttling and have a retry.
The user should be able to catch the error so that he can treat it.

I know it's a 500 error, But it shouldn't crash the function and kill all the other running processes. 
Reported a similar problem some time ago with other commands that killed the thread on a SPFx webpart when it crashed and it was fixed at the time.
Tested with pnp version 3.2 and 4.3

### Observed Behavior

I want to break the permissions on the library and sometimes it crashes killing the process. Any catch or try catch are ignored.

It throws this exception:

`Exception while executing function: Functions.IndexProvisioningTimer node exited with code 1 (0x1) LanguageWorkerConsoleLog[error] Worker uncaught exception (learn more: https://go.microsoft.com/fwlink/?linkid=2097909 ): Error: Error making HttpClient request in queryable [500] Internal Server Error ::> {"odata.error":{"code":"-2146232060, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"Exception from HRESULT: 0x80131904"}}}     at HttpRequestError.init (file:///home/site/wwwroot/node_modules/@pnp/queryable/behaviors/parsers.js:95:16)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)     at async Function.errorCheck (file:///home/site/wwwroot/node_modules/@pnp/queryable/behaviors/parsers.js:44:15)     at async Timeout._onTimeout (file:///home/site/wwwroot/node_modules/@pnp/queryable/queryable.js:120:50)`

### Steps to Reproduce

The exception never get's triggers the catch. 

```
await SP.web.lists.getByTitle(libraryName).breakRoleInheritance(false)
            .catch(async (error) => {
                context.error(`Error breaking permissions inheritance: ${error.message}`);
            });
```

**Comment by Dangerous-Mind** [comment]
Has a workaround I added this function and call it in the beginning of the functions to prevent the process from blowing up and it seams to be working fine now.
I still receive the errors but I can treat them on the catch (mostly retry the entry).

```typescript
import { LogLevel } from "@azure/msal-node";

export function processUncaughtErrorHandling(context: any): void {
    // Global error handler for unhandled promise rejections
    if (!process.listenerCount('unhandledRejection')) {
        process.on('unhandledRejection', (reason, promise) => {
            context.error({
                message: `Unhandled Rejection at: ${promise}, reason: ${reason}`,
                level: LogLevel.Error
            });
        });
    }
    if (!process.listenerCount('uncaughtException')) {
        // Global error handler for uncaught exceptions
        process.on('uncaughtException', (error) => {
            context.log({
                message: `Uncaught Exception: ${error.message}`,
                level: LogLevel.Error
            });
        });
    }
}
```

**Comment by patrick-rodgers** [comment]
I updated those functions to return the promise instead of await it. I think that should fix this based on previous similar things we saw in early testing. I guess these just got missed to be updated.
