### ISSUE TITLE
Where are the interfaces from version 3 ? 

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#3108]
### What version of PnPjs library you are using

4.x

### Minor Version Number

4.3.0

### Target environment

SharePoint Framework

### Additional environment details

Upgrading SPFx 1.18.1 project form @pnp/sp 3.2  to 4.3 
And Typescript complains about interfaces not existing. 

### Question/Request

I had:
`import { IItem, IItemUpdateResult} from "@pnp/sp/items";
const updateDocumentNumberMaster: (documentNumber: string, newDocName: string) => Promise<IItemUpdateResult>
`
shows error 
Module '"@pnp/sp/items"' has no exported member 'IItemUpdateResult'.ts(2305) 

Same was for IWebEnsureUserResult, IFileAddResult, 
Is there an external *.d.ts file I should use?

**Comment by juliemturner** [comment]
IItemUpdateResult was deprecated in v4... the update call now returns the payload that the SP Rest API returns instead of the payload plus a IItem object. 

The return is Promise<any>, you would type for the list item you're updating if you need the information.

**Comment by Ofer-Gal** [comment]
Thanks.
What about IWebEnsureUserResult and IFileAddResult ?
Start using 'any' ?

**Comment by juliemturner** [comment]
Just look at the typing signature in intellisense or look up the method in the source code.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
