### ISSUE TITLE
Will @pnp/graph support sharerpoint online operated by 21Vianet ?

### ISSUE THREAD

**Issue by Haiqi-Wu** [pnp/pnpjs#3112]
### What version of PnPjs library you are using

4.x

### Minor Version Number

4.0

### Target environment

SharePoint Framework

### Additional environment details

SharePoint Framework form extension in SPO operated by 21Vianet

### Question/Request

To get information about the current user, for example, the same code works fine in the global version of SharePoint, and the request from SharePoint operated by 21v is as follows:
![image](https://github.com/user-attachments/assets/03a11259-39b6-40ff-aeb1-27aeb50b81cb)
`const allUsers = await props.graph.me();`

Does it support SharePoint Online operated by 21Vianet or do I need to do some extra configuration to make it work? 
Thank you!

**Comment by Haiqi-Wu** [comment]
I find the DEFAULT_GRAPH_URL in @pnp/graph/index.js and change it to 21v graph endpoint. And then it works well.
![image](https://github.com/user-attachments/assets/61096c78-eedb-41a6-a830-d14ff3a1c35d)
I think it would be a good solution to add an azure environment optional parameter to pnp's graph constructor. Changing the url locally is just a workaround.

**Comment by bcameron1231** [comment]
> I think it would be a good solution to add an azure environment optional parameter to pnp's graph constructor.

We do. You can pass in the url into your graphfi object.

`const graph = graphfi('https://microsoftgraph.chinacloudapi.cn')`

**Comment by Haiqi-Wu** [comment]
OK. Thank you!
