### ISSUE TITLE
Is there a limit on the number of list items returned?

### ISSUE THREAD

**Issue by SharonGilmore** [pnp/pnpjs#3118]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.24.0

### Target environment

All

### Additional environment details

I'm writing a SharePoint WebPart using SPFx.

### Question/Request

Apologies if this is a very basic question, but I can't see anything about it in the docs.

I have a list of users on my site (stored as an actual List, which is updated manually).  When I retrieve the List using

```
const userList: any[] = await sp.web.lists
        .getByTitle("Users")
        .items.select("*", "User/Title", "User/EMail")
        .expand("User")();
```
I only seem to get 100 records back, although I have more than 100 records in my List.  Is this a limit which is imposed by default?  If so, can I change it so that it returns all records? Thanks.

**Comment by juliemturner** [comment]
By default the api returns 100 items, to change the number that are returned, use `.top(x)`... x  can be 1 -> 5000. If you need more than 5000 you have to use paged Iterator and that is in the docs.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
