### ISSUE TITLE
Trouble with Taxonomy

### ISSUE THREAD

**Issue by JamesDerrickHH** [pnp/pnpjs#3123]
### What version of PnPjs library you are using

4.x

### Minor Version Number

4

### Target environment

SharePoint Framework

### Additional environment details

Trying to create a sharepoint webpart, originally created using yeoman with React as the framework

### Question/Request

I cannot seem to import taxonomy
I've simply tried to follow the basic example and run `import { ITermStoreInfo } from "@pnp/sp/taxonomy";`
but it errors saying Cannot find module '@pnp/sp/taxonomy' or its corresponding type declarations
looking at the node_module and there doesn't seem to be a taxonomy folder
is there an extra pnp package I need to install?

**Comment by bcameron1231** [comment]
Hi. Taxonomy is no longer available in the SP Module. In Version 4, we moved Taxonomy to use the Graph Taxonomy APIs @pnp/graph/taxonomy

Please see our v4 transition guide
https://pnp.github.io/pnpjs/transition-guide/#sharepoint-taxonomy-has-moved-to-pnpgraph-from-pnpsp

**Comment by JamesDerrickHH** [comment]
Thanks so much, I must have been looking at old documentation by mistake
