### ISSUE TITLE
The call to graph.me produces "Failed to construct 'URL'" error.

### ISSUE THREAD

**Issue by stastny1** [pnp/pnpjs#3124]
### What version of PnPjs library you are using

4.x

### Minor Version Number

4.4.0

### Target environment

Browser App (Hosted external to Microsoft 365 platform)

### Additional environment details

I am developing an add-on for MS Teams.  I need to work with Graph API, so my first step is to get a graph token using the obo flow. This is step is already taken care of. 

### Question/Request

I am trying to setup pnpjs, so that I can use it for fetching data with graph api. As I described in environment details, my app is running in MS Teams environment. Therefore, I have got an access token, which I have to use with the library.
Here is a simple test function, which fails:
``` typescript
export async function testPnp(graphToken: string) {
  const graph = graphfi().using(BearerToken(graphToken));
  const me = await graph.me();
  console.log(me);
}
```
It's the call to `graph.me` that is problematic. It produces this error:
![image](https://github.com/user-attachments/assets/3f13442f-56f6-4c16-ac90-0410d5d77c44)
Is this a bug, or is there any other mandatory step to properly setup this library?

**Comment by patrick-rodgers** [comment]
I think you're missing some behaviors. You are only applying the BearerToken behavior and none of the others. What environment are you in (browser/node)?

**Comment by stastny1** [comment]
It's browser.

**Comment by patrick-rodgers** [comment]
[This article](https://pnp.github.io/pnpjs/msaljsclient/) should help get you started.

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
