### ISSUE TITLE
use batched actions across different site/webs

### ISSUE THREAD

**Issue by mdissel** [pnp/pnpjs#3125]
### What version of PnPjs library you are using

3.x

### Minor Version Number

24

### Target environment

SharePoint Framework

### Additional environment details

SPFX

### Question/Request

Can i execute the batch command to load list items in different lists located in different web instances?

How can I add the request to the batch instance?

```
const [batched, execute] = this._dms.context.sp.batched();
changes.forEach(changeditem => {
	const web = Web([this._dms.Web, changeditem.remoteItem.sharepointIds.siteUrl]);
	void web.lists.getById(changeditem.remoteItem.sharepointIds.listId).items.getById(changeditem.remoteItem.sharepointIds.listItemId)
		.select(...fields.fieldNames)
		.expand(...fields.expandedFieldNames)()
		.then(item => {
			// only add items, no folder
			if (item.FileSystemObjectType === 0) {
				result.changed.push({
					...item,
					ListId: listId
				});
			}
		})
		.catch(error => {
			if (error.status === 404) {
				// skip
			} else {
				console.error(error);
			}
		});
});
await execute();
`
```

**Comment by patrick-rodgers** [comment]
I don't believe this is possible - have you found something indicating it is?

**Comment by mdissel** [comment]
never mind, found the answer.. not possible.

The request URL and the URLs inside the body must target the same site. All URLs are case-sensitive.
See: https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis#executive-summary-of-the-batch-option
