### ISSUE TITLE
how to get full version history of SharePoint list item from from begining

### ISSUE THREAD

**Issue by deep-ponkiya-web** [pnp/pnpjs#3134]
### What version of PnPjs library you are using

3.x

### Minor Version Number

1.0

### Target environment

All

### Additional environment details

"@pnp/sp": "^3.13.0",
"react": "17.0.1",
"@microsoft/sp-core-library": "^1.17.1",
 "@microsoft/sp-lodash-subset": "^1.17.1",
"@microsoft/sp-office-ui-fabric-core": "^1.17.1",
"@microsoft/sp-property-pane": "^1.17.1",
"@microsoft/sp-webpart-base": "^1.17.1",
    

### Question/Request

i am working with spfx with react.i need full version history of SharePoint list item from begining.
but pnp/js return version number 10.0 when history more then 50. please assist me for this issue.

```
export const getItemHistory = async (Id, LIST_NAME) => {
    let queryParams = new GET_LIST_QUERY_PARAMS();
    queryParams.selectProperties = ["*,Versions"];
    queryParams.expandProperties = ["Versions"];

    const assetResult = await getSPListItemById(
        LIST_NAME,
        queryParams.selectProperties,
        queryParams.expandProperties,
        Id
    );

    return assetResult;
}

```

**Comment by juliemturner** [comment]
Did you try this: https://pnp.github.io/pnpjs/sp/items/#get-version-history

**Comment by deep-ponkiya-web** [comment]
> Did you try this: https://pnp.github.io/pnpjs/sp/items/#get-version-history

Yes but in pnp/js get response only top 50

**Comment by juliemturner** [comment]
Did you try adding the .top parameter to versions?

**Comment by deep-ponkiya-web** [comment]
> Did you try adding the .top parameter to versions?
@juliemturner  Yes i already Added To 5000 entries

**Comment by patrick-rodgers** [comment]
@deep-ponkiya-web - what is the version retention set to on the library? How many versions are you expecting to get?

**Comment by deep-ponkiya-web** [comment]
> I mean I'm glad you can get version history with that query but I pointed you to the docs where the call is:
> 
> `const itemVersions: any = await sp.web.lists.getByTitle("My List").items.getById({item id}).versions();`
> 
> I think you can expand that to:
> 
> `const itemVersions: any = await sp.web.lists.getByTitle("My List").items.getById({item id}).versions.top(100)();`
> 
> but I haven't tried that so I can't say for sure.
> 
> Also I'd really suggest you move to version 4.

@juliemturner 

Yes i tried your solution but only top 50 entries get. Any Other solution?

**Comment by juliemturner** [comment]
What is the retention policy set on the list/library?
