### ISSUE TITLE
Getting: "Save Conflict.  Your changes conflict with those made concurrently by another user." When Deleting an item with cascade delete in another list.

### ISSUE THREAD

**Issue by jduysen-tsbg** [pnp/pnpjs#3135]
### What version of PnPjs library you are using

2.x (No longer supported)

### Minor Version Number

11

### Target environment

SharePoint Framework

### Additional environment details

Sharepoint online with SPFx

### Question/Request

When I use list item delete on an item that is referenced in another list with cascade delete turned on, I get: **Save Conflict.\n\nYour changes conflict with those made concurrently by another user. If you want your changes to be applied, click Back in your Web browser, refresh the page, and resubmit your changes.**

I have tried doing .delete(item["odata.etag"]) with the same result.  As soon as I turn cascade delete off in the child list the delete functions correctly without issue.  Has anyone encountered this before?

![image](https://github.com/user-attachments/assets/8cef4b78-87b5-4d5f-9231-2aa1557a96e7)

Thanks,

James

**Comment by juliemturner** [comment]
SharePoint Client-side Pages API is being deprecated and no changes will be made to the existing endpoint. Closing this issue to track pages updates to #3137

**Comment by jduysen-tsbg** [comment]
This is for list items, not pages...

**Comment by juliemturner** [comment]
Apologies I was on the wrong item.

This issue however it built into SharePoint and is not related to PnPjs. In general, that is not a feature any of us use, because of the issue you're experiencing.

**Comment by jduysen-tsbg** [comment]
I have a hard time believing no one uses item.delete.  I am able to delete an item using the out of the box user interface, so it seems that the library could be a common denominator in the issue.  But thanks for replying, I will find a workaround.

**Comment by juliemturner** [comment]
You're right, item.delete is used all the time, what isn't used all the time is cascade delete. 

This library is a passthrough to the SharePoint REST APIs (and Microsoft Graph APIs). You can verify in the console how the API is being called. Usually if something can be done in the UI and can't be done through code, I take a look at the network console while doing the action in the UI and see how the call is different. Maybe you need to include an IF-MATCH header.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
