### ISSUE TITLE
Cannot update Location type field

### ISSUE THREAD

**Issue by jamesm2024** [pnp/pnpjs#3138]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.25.0

### Target environment

SharePoint Framework

### Additional environment details

SharePoint Online, React

### Question/Request

I cant find much documentation on the Location field.
I have noticed in Power Apps that the Location field has linked fields.
- Name
- Street
- City  
- etc

I am uncertain on how to update the linked fields in the batch update.

I've created the Location field as follows:
await sp.web.lists.getByTitle(listName).fields.addLocation("Location", { Description: "The Location field is the location of the meeting." });

I have used the following array to update the list items using batch and it works fine. 

itemsToAdd = [
                { Title: listName, Date: '2024-09-21T23:00:30.784Z', Attendees: "Tom Jones" },
                { Title: listName, Date: '2023-09-22T23:00:30.784Z', Attendees: "Howard Parker" },
];

All good so far...

I'm having trouble when I try to update the Location field. I have tried the following:

itemsToAdd = [
                { Title: listName, Date: '2024-09-21T23:00:30.784Z', Location: 'New York', Attendees: "Tom Jones" },
                { Title: listName, Date: '2023-09-22T23:00:30.784Z', Location: 'New York', Attendees: "Fred Nerk" },
];

No luck.....

I have also tried:

itemsToAdd = [
                { Title: listName, Date: '2024-09-21T23:00:30.784Z', Location: { Name: 'New York', Street: '5th St' }, Attendees: "Tom Jones" },
                { Title: listName, Date: '2023-09-22T23:00:30.784Z', Location: { Name: 'New York', Street: '5th St' }, Attendees: "Fred Nerk" },
];

No luck.....

Looking for guidence.

**Comment by juliemturner** [comment]
I do it this way, where ProjectLocation is the Location field.

```TypeScript
const projectId = 1;
const project = sp.web.lists.getById(process.env.ProjectListId).items.getById(projectId).select("Id, ProjectLocation")()
const projectLocation: ILocation = JSON.parse(project.ProjectLocation);
projectLocation.Coordinates = coordinates;
const ProjectLocation = JSON.stringify(projectLocation);
const update = await sp.web.lists.getById(process.env.ProjectListId).items.getById(project.Id).update({ ProjectLocation });
```

**Comment by jamesm2024** [comment]
Hi Julie, 
Thanks for your help.
How do import the Ilocation type?
Regards
James

**Comment by jamesm2024** [comment]
Hi Julie,
Got it all going.
Thanks for the lead.

This is the result:

const update = await sp.web.lists.getByTitle("My List").items.getById(1).update({ Location: JSON.stringify({DisplayName: "Work", LocationSource: "", LocationUri: "", UniqueId: "", Address: {Street: "20 York St", City: "Sydney", State: "NSW", CountryOrRegion: "Australia", PostalCode: "2000" }}) });

A line or two in the documentation about this would be great. What's the process for this. Can I help?

Cheers
James

**Comment by jamesm2024** [comment]
Where is that documentation? I feel i am always working in the dark.

**Comment by juliemturner** [comment]
I just added it, it's not PR/merged yet.
