### ISSUE TITLE
Is there an API to update List Item View/Edit/Add Form formatting with JSON

### ISSUE THREAD

**Issue by jamesm2024** [pnp/pnpjs#3139]
### What version of PnPjs library you are using

3.x

### Minor Version Number

3.25.0

### Target environment

SharePoint Framework

### Additional environment details

SharePoint Online, React

### Question/Request

Just wondering if there is an API to pass JSON to a list item form (header/body/footer)

https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration

![Form JSON Formatter](https://github.com/user-attachments/assets/a2eca1c3-137e-40c5-8da4-468030b7f21f)

**Comment by juliemturner** [comment]
There's a property on the column (list or site) called "CustomFormatter" that takes a stringified JSON object as the field.

**Comment by jamesm2024** [comment]
Hi Julie,
I have looked at the columns of the list but there is no "CustomFormatter".
Could you provide a little more information.
Thanks
James

**Comment by juliemturner** [comment]
No there isn't a field called CustomFormatter there's a property of a field called CustomFormatter.

**Comment by jamesm2024** [comment]
All good. 
Have updated JSON formating in ContentType and all is working well.
Thanks
