### ISSUE TITLE
Authentication SPA with pnpJS

### ISSUE THREAD

**Issue by ahernandez-iusup** [pnp/pnpjs#3144]
### What version of PnPjs library you are using

3.x

### Minor Version Number

1.0

### Target environment

NodeJS

### Additional environment details

I'm developing a node.js add-in for outlook, and i'm and trying to connect to SharePoint via SPA with pnpjs.
I have followed this steps:
https://pnp.github.io/pnpjs/v2/authentication/msaljsclient/#use-in-single-page-applications

But i cannot use imports statements in my SPA (i use .ejs as a web page) so I tried to look for a cdn or equivalences but i'm struggling with that. Maybe someone could show me how i could autenthicate to my sharepoint in my client side.
I have been looking for examples but i didn't found anything that fits my interests.

### Question/Request

```JavaScript
const { sp } = pnp;


        // Función para obtener los elementos de una lista de SharePoint
            try {
                sp.setup({
                    sp: {
                        fetchClientFactory: MsalClientSetup({
                            auth: {
                                authority: "https://login.microsoftonline.com/common",
                                clientId: "{client-id}",
                                redirectUri: "{redirect-uri}",
                            },
                        }, ["AllSites.FullControl"])
                    },
                });

                const data = await sp;
                console.log(data);
            } catch (error) {
                console.error("Error obteniendo elementos:", error);
            }
        
´´´
This code is the one that i'm running but the pnp to initilaize the sp constant is not found

**Comment by juliemturner** [comment]
The link you shared is for V2 of the library. There was a major update to v3 so you really need to look at more updated docs. That said, v2 and v3 are deprecated, we're not on v4. Although a major release it was more for the deprecation of some specific endpoints and other refactoring not as much in teh day to day use. So, essentially your sample code for v2 will never work for v3. I would start with the documentation and move to v4. https://pnp.github.io/pnpjs/

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
