### ISSUE TITLE
Rest API v2.1 in Sharepoint on-premise for Taxonomy

### ISSUE THREAD

**Issue by QuentinBrun** [pnp/pnpjs#3146]
### What version of PnPjs library you are using

2.x (No longer supported)

### Minor Version Number

2.0.8

### Target environment

Browser App (Hosted external to Microsoft 365 platform)

### Additional environment details

I'am using react, typescript and target sharepoint on-premise Subscription Edition

### Question/Request

Hi, 
I know that version 2.x is not supported anymore but maybe some of you may still have an answer. 

Version 2 documentation state that it should be working with sharepoint on-premise. Even the version 4 documentation state that for working with on-premise we should use version 2. So I tried to use version 2.

Version 2 work for everything I need but for taxonomy. I have checked and version 2 rely on Rest v2.1 endpoint like the following: _api/v2.1/termstore/groups/.../sets/.../terms

When calling this rest API on my sharepoint SE server, I get an error:

_Could not load file or assembly &#39;WinLive.SkyShared.Infrastructure.Utilities, Version=3.0.0.0, Culture=neutral, PublicKeyToken=6826d94a3ff89317&#39; or one of its dependencies. The located assembly&#39;s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)_

My question is: can anyone tell me if Sharepoint SE should support Rest API v2.1 ? (So that I can either try to fix my sharepoint installation or move to PnPjs v1 ?) 

Thanks,

**Comment by juliemturner** [comment]
No, the REST 2.1 api is online only and will not work. That endpoint has been removed from v4 in lieu of the graph endpoints but unfortunately that doesn't help you with your work against SharePoint SE.

**Comment by QuentinBrun** [comment]
Thank you for your quick answer. That answer my question and I will go ahead with version 1.
