### ISSUE TITLE
getLockedByUser only returns the current user. not other  with file open.

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#3148]
### What version of PnPjs library you are using

4.x

### Minor Version Number

4.5.0

### Target environment

SharePoint Framework

### Additional environment details

Tring to find out if anyone has a certain file open before checkout inside a SPFx webpart authenticating with the context.  

### Question/Request

The code
```
     const file: IFile = await projWeb.getFileByServerRelativePath("/teams/3000.005/DPCDocuments/Turn OFF OneDrive Syncing.docx")
        const o:ISiteUserProps = await file.getLockedByUser();
        if (o)    console.log(o.Title, o.LoginName);
```
shows my name and login when I am the one with the file open. 
When someone else has the file open, o== null 
Is there a way to make it aware of other users with the file open?
Thank you

**Comment by juliemturner** [comment]
We don't believe there is a way to do this today.

**Comment by Ofer-Gal** [comment]
Thanks
