### ISSUE TITLE
Pagination on SPList - an insurmountable problem when > 5000 items?

### ISSUE THREAD

**Issue by pwmusic** [pnp/pnpjs#3149]
### What version of PnPjs library you are using

4.x

### Minor Version Number

0.1

### Target environment

SharePoint Framework

### Additional environment details

I generated an SPFx project using Yeoman and version 1.19 of the framework.

I don't believe authentication is a contributing factor as all other lists query without issue. Also, I could query this list until the row count went about 5000.

### Question/Request

I'm finding it impossible to paginate through an SPList when the list contains more than 5000 items. (In this case, there are 5890 list items.)

I believe I've followed the docs but perhaps I've missed something and it _is_ possible to query moderately-sized lists.

Any and all suggestions would be most welcome.

Here's my generic function:

```
interface ODataResponse<T> {
  value: T[];
  '@odata.nextLink'?: string;
}

  public static async getAllItems<T>(
    listSourceSiteWeb: IWeb | undefined, 
    listTitle: string, 
    listColumns: string,
  ): Promise<T[]> {
  
  if (!listSourceSiteWeb) {
    throw new Error("listSourceSiteWeb is undefined");
  }

  const circuitBreaker = 10000;

  try {
    let allItems: T[] = [];
    let finalBatchRetrieved = false;
    const batchSize = 500;
    let skipCount = 0;

    do {
      let query = listSourceSiteWeb.lists.getByTitle(listTitle).items.top(batchSize).skip(skipCount);

      const response: ODataResponse<T> = await query.select(listColumns)();

      if (Array.isArray(response)) {
        // Case 1: If response is an array, no pagination (response is the data)
        if (response.length > 0) {
          allItems = [...allItems, ...response];
          skipCount += response.length;
        }

        if (response.length < batchSize) {
          console.log(`response.length (${response.length}) less than batchSize (${batchSize}) - breaking the do-while`);
          console.log("response = ", response);
          finalBatchRetrieved = true;
        }
      } else if (response.value) {
          // Case 2: If response has a value property, it contains the paginated data
          allItems = [...allItems, ...response.value];
          skipCount += response.value.length;
      } else {
        console.error('Unexpected response format:', response);
        break;
      }

      if (skipCount > circuitBreaker) {
        console.log(`Circuit breaker hit - escaping at ${circuitBreaker}`);
        finalBatchRetrieved = true;
      }
    } while (!finalBatchRetrieved);

    return Promise.resolve(allItems);

    } catch (error) {
      console.error(`Error in getAllItems()`);
      console.error(error);

      return Promise.reject(`getAllItems(): ${error}`);
    }
  }
```

**Comment by juliemturner** [comment]
I'm not quite sure what your doing with the code you shared, but this is the example:

https://pnp.github.io/pnpjs/sp/items/#get-paged-items

Here's a production code sample (simplified somewhat):

```ts
let allItems: IClient[];
let items: IClient[];
const queryable = this._sp.web.lists.getByTitle(CLIENT_LIST).items
        .select("Id", "Title", "ClientCode", "URL", "ActiveClient")
        .top(5000)
        .filter("ActiveClient eq 1")
        .orderBy("Title");

for await (items of queryable) {
   allItems= allItems.concat(items)
}
```

**Comment by pwmusic** [comment]
Hi @juliemturner 

Thank you so much for taking the time to reply.

Isn't it the case that this code snippet will only return the first 5000 items though? My list has increased to ~5900 items and I need to iterate through all of them but unless I'm misreading it, won't this code only retrieve the top 5000?

**Comment by patrick-rodgers** [comment]
Did you give it a try? It should return all the items in page sizes of 5000.

**Comment by pwmusic** [comment]
I didn't because I don't think it covers my use-case.

The code in this example looks to be filtering by 'ActiveClient eq 1'. Presumably, in the 'for await' there is an update of ActiveClient to set it to a value other than 1 to stop it being picked up when re-filtered.

However, there is no such filter I can use on my query - I simply want to retrieve all items in the list.

With this being a key requirement of my use-case, I don't believe the suggested code will help.

**Comment by bcameron1231** [comment]
> The code in this example looks to be filtering by 'ActiveClient eq 1'. Presumably, in the 'for await' there is an update of ActiveClient to set it to a value other than 1 to stop it being picked up when re-filtered.

This was just sample code for you to see how Async Iterators work. We have docs on this approach and can be used to retrieve all items in a list
https://pnp.github.io/pnpjs/concepts/async-paging/

For your code it would be similar to
```
let allItems: T[] = [];
const batchSize = 500;

 for await (const items of  _sp.web.lists.getByTitle(listTitle).items.top(batchSize)) {
   allItems = allItems.concat(items);
   
   // if you want to stop just call break;
   //break;
 }
```

This certainly supports your use case. Async Iterators just continue to page through the items in the batchSize until you tell it to stop.

**Comment by pwmusic** [comment]
Thank you for your continued responses to this.

My code follows these notes.

When called without a filter, the code loads allItems[] with 5896 items. This is the correct number of items.

If I add a filter, in this case "SourceID eq 1 and Status ne 'Completed'", I get the error:
Error in getAllItems() HttpRequestError: Error making HttpClient request in queryable [500]  ::> {"odata.error":{"code":"-2147024860, Microsoft.SharePoint.SPQueryThrottledException","message":{"lang":"en-US","value":"The attempted operation is prohibited because it exceeds the list view threshold."}}}

I could filter the results manually, but this code is intended to be a generic 'getAllItems' function.

In any case, the current behaviour when a filter is applied doesn't seem ideal...

```
const listSourceSiteWeb = Web(siteTargetUrl).using(SPFx(context));

      let queryable = listSourceSiteWeb.lists.getByTitle(listTitle).items
        .select(listColumns)
        .top(batchSize);

      if (filter) {
        console.log("Adding a filter");
        queryable.filter(filter);
      }

      let counter = 0;

      for await (const items of queryable) {
        allItems = allItems.concat(items);
        console.log(`counter = ${++counter}`);
      }

      console.log("allItems.length = ", allItems.length);
```

**Comment by pwmusic** [comment]
One further update, I changed the filter to 'SourceID eq 1' but that didn't make the 'list view threshold' exception go away.

Also, SourceID is indexed.

**Comment by juliemturner** [comment]
I think you have some other issue with your code... the error is not related to the code you shared. I would search your code for "getAllItems" as that seems to be where things are breaking.

**Comment by bcameron1231** [comment]
A thing to note is how the OData Queries work in SharePoint. $top ( ` .top() `) is applied after the query and filter, so it is affected by the List View Threshold even if you request only 500 items. Additionally, the $filter ( ` .filter() ` ) must always return less than 5,000 items or you're going to continue to get this error.  Lastly, depending on the column type you're filtering against you may also still have this occur, for example, lookups. 

Unfortunately there isn't much we can do here to help as you're working up against issues with SharePoint and not with the PnPjs library itself.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
