### ISSUE TITLE
PnPJs and PCF Control, popup and redirection uri

### ISSUE THREAD

**Issue by krunal039** [pnp/pnpjs#3154]
### What version of PnPjs library you are using

4.x

### Minor Version Number

4.6

### Target environment

other (enter in the "Additional environment details" area below)

### Additional environment details

I’m using PnPJs to create a PCF control for uploading large files to SharePoint within a canvas app. The code below is working while editing the canvas app, along with the redirection URI : https://authoring.eu-il109.gateway.prod.island.powerapps.com/v3.24095.15.310953622/embed/
`import { IInputs, IOutputs } from "./generated/ManifestTypes";
import type { MSALOptions } from "@pnp/msaljsclient";
import { spfi, SPBrowser } from "@pnp/sp";
import { MSAL, getMSAL } from "@pnp/msaljsclient";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/site-users/web";

export class pcfspolargeupload implements ComponentFramework.StandardControl<IInputs, IOutputs> {

constructor()
{

}

public async init(context: ComponentFramework.Context<IInputs>, notifyOutputChanged: () => void, state: ComponentFramework.Dictionary, container:HTMLDivElement): Promise<void>
{
    let _notifyOutputChanged: () => void
    let _context: ComponentFramework.Context<IInputs>
    let _spContext: any

    const options: MSALOptions = {
        configuration: {
            auth: {
                authority: "https://login.microsoftonline.com/[TenantID]/",
                clientId: "[AppID]",
            },
            cache: {
                claimsBasedCachingEnabled: true // in order to avoid network call to refresh a token every time claims are requested
            }
        },
        authParams: {
            forceRefresh: false,
            scopes: ["https://tenant.sharepoint.com/.default"],
        }
    };
    
    const sp = spfi("https://tenant.sharepoint.com/").using(SPBrowser(), MSAL(options));
    
    const user = await sp.web.currentUser();
    
    // For logout later on
    const msalInstance = getMSAL();
    const currentAccount = msalInstance.getActiveAccount();

    const list = sp.web.lists.getByTitle("Documents");

    // we can use this 'list' variable to run more queries on the list:
    const r = await list.select("Id")();

    // log the list Id to console
    console.log(r.Id);

    container.appendChild(document.createTextNode(r.Id));

}

public updateView(context: ComponentFramework.Context<IInputs>): void
{
}
public getOutputs(): IOutputs
{
    return {};
}

public destroy(): void
{
}
}`

### Question/Request

When I publish the app and access it, the redirection URI changes to: https://runtime-app.powerplatform.com/publishedapp/e/default-cc83b6ac-505f-4efc-a552-a2c7bfa6d7e3/preloadindex/V1. The popup doesn’t close, and I’m unsure what I’m doing wrong. What steps should I take to get PnPJs working with my AAD app to upload large files to SharePoint via PCF control in Canvas app?

![image](https://github.com/user-attachments/assets/263b7096-7f40-4bfd-976e-f6de01086f53)

**Comment by krunal039** [comment]
![image](https://github.com/user-attachments/assets/7c07f616-c776-4d7f-9a46-8e01a9954d70)

**Comment by patrick-rodgers** [comment]
What is the error in the server logs? I.e. why do you think this is a PnPjs library issue? Based on the above I don't know what the underlying error is or where to start investigating.

**Comment by krunal039** [comment]
> What is the error in the server logs? I.e. why do you think this is a PnPjs library issue? Based on the above I don't know what the underlying error is or where to start investigating.

I do not know if it is an issue with PnP library, just want to know if there is anything I am doing wrong here to get an access token in PCF control? I could not find much sample as well

**Comment by bcameron1231** [comment]
Hi, did you update the Redirect URL in Azure for the App Registration for the new URL?

**Comment by krunal039** [comment]
Yes, I did update, popup is not closing.

**Comment by bcameron1231** [comment]
Do you see any errors in the developer console (F12 -> Console) in the browser when you load the application?

**Comment by krunal039** [comment]
No related to Auth or redirection.

**Comment by bcameron1231** [comment]
Okay. Unfortunately there isn't quite enough information to provide a definitive answer. Are you seeing queries for the token and authorize to login.microsoft.com?

It may just be an issue with the Power Apps environment once it's published. It's likely unrelated to the PnPjs library.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
