### ISSUE TITLE
How add a site column to a site content type using pnp sp. 

### ISSUE THREAD

**Issue by jamesm2024** [pnp/pnpjs#3156]
### What version of PnPjs library you are using

3.x (No longer supported)

### Minor Version Number

3.25.0

### Target environment

SharePoint Framework

### Additional environment details

SharePoint Online, React

### Question/Request

I am trying to add a site column to a site content type using pnp sp. Im wondering if there is any further progress as I have read the unfortunate outcomes of both previous issues:
How to add/associate a site column to a content type? #290 and 
Assign a site column to content type or list content type? #1379

**Comment by juliemturner** [comment]
Those work arounds still work. But the graph endpoint has been implemented: https://pnp.github.io/pnpjs/graph/columns/#add-a-column-reference-content-types

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
