### ISSUE TITLE
All in all I guess this was surmountable 🙂

### ISSUE THREAD

**Issue by pwmusic** [pnp/pnpjs#3163]
All in all I guess this was surmountable 🙂

_Originally posted by @patrick-rodgers in https://github.com/pnp/pnpjs/issues/3149#issuecomment-2413972002_

Unfortunately not.

Beau Cameron's comment "Unfortunately there isn't much we can do here to help as you're working up against issues with SharePoint and not with the PnPjs library itself." indicated it is simply impossible to retrieve items from an SPList that has more than 5000 list items.

I had to redesign my solution to work with this limitation. Lots of work!

I would be delighted if you were able to (politely) tell me I _can_ actually iterate through all 6-7000 list items.

(To provide some additional information, the list contains an email address, two numeric fields, and a second text field. The query column, email address, is indexed.)

**Comment by bcameron1231** [comment]
> indicated it is simply impossible to retrieve items from an SPList that has more than 5000 list items.

For clarity, this is not exactly what I said. I said it's impossible to do so _because of your filter condition._

> I would be delighted if you were able to (politely) tell me I can actually iterate through all 6-7000 list items.

You can iterate through lists of 6-7000 with the library. What you **cannot do** is use a filter condition that returns more than 5,000 items when it evaluates. This is a SharePoint limitation. If you need all the items, remove the filter and filter client-side or come up with a filter condition that retrieves <5k at a time.
