### ISSUE TITLE
Getting list of users with access to a securable

### ISSUE THREAD

**Issue by pheidler** [pnp/pnpjs#3164]
### What version of PnPjs library you are using

2.x (No longer supported)

### Minor Version Number

13.0

### Target environment

SharePoint Framework

### Additional environment details

SPFx

### Question/Request

Is there any way to generate a list of users with access to a given securable (in our case, subsites and list items)?

I've gone through a number of iterations on this, originally using [siteUsers](https://pnp.github.io/pnpjs/sp/webs/#siteusers), and eventually settling on fetching the role definition bindings and expanding the SharePoint and M365 groups to get each member. I moved away from using the siteUsers endpoint because it often led to throttling with checking each user against the securable, and there were too many quirks with how this list was kept updated. The role definition binding approach worked well (although a bit complicated), but I've only now realized that it fails for any permission level below site admin (including full control).

For example, this code fails with a 403 Forbidden for any user that is not a site admin, on any resource.
```
const roleAssignments: IExpandedRoleAssignmentInfo[] =
      await securable.roleAssignments
        .expand("RoleDefinitionBindings", "Member/Users")
        .get();
```
I feel like I'm reinventing the wheel here... considering users with full control can view the list of users through the SharePoint permissions UI, why isn't there an endpoint that supports this? It feels like a fairly common use case to abstract the SharePoint permissions.

**Comment by pheidler** [comment]
Let me know if I'm posting this in the wrong place. Thought maybe there was something I'd missed in the library, or someone else has tried to implement something similar.

**Comment by bcameron1231** [comment]
Hi. Yes, unfortunately RoleDefinitionBindings requires higher level access. I don't have a great answer, except maybe trying to handle the throttling a bit more in your previous approach.

**Comment by pheidler** [comment]
Ok, thanks.
