### ISSUE TITLE
Azure Function Unauthorized: 401 - ID3035: The request was not valid or is malformed.

### ISSUE THREAD

**Issue by oza-c** [pnp/pnpjs#3165]
### What version of PnPjs library you are using

4.x

### Minor Version Number

4.6.0

### Target environment

NodeJS

### Additional environment details

Azure Function (V4) with Certificate authentication 

### Question/Request

Hey, I have the following problem. I am in the process of converting / redeveloping a Powershell script into Typescript. Both scripts use the same app registration but differ in the authentication. The PowerShell script is executed manually and can thus be authenticated via Interactive Browser, the Azure Functions must therefore work (as expected, no manual login possible) via certificate.
The page to be called is the same, but somehow it doesn't seem to work with pnpJs.

'Error making HttpClient request in queryable [401] Unauthorized ::> {"error_description":"ID3035: The request was not valid or is malformed."}'
   
     const buffer = readFileSync(process.cwd() + "/src/utils/cert/xxxxx.pem");

     const configuration: Configuration = {
         auth: {
             authority: "https://login.microsoftonline.com/xxxxx/",
             clientId: "xxxxx",
             clientCertificate: {
                thumbprint: "xxxxx",
                privateKey: buffer.toString(),
            }
         }
     };

     const sp = spfi().using(SPDefault({
        baseUrl: 'https://xxxx.sharepoint.com/sites/testSite/',
        msal: {
            config: configuration,
            scopes: [ 'https://xxxx.sharepoint.com/.default' ]
        }
    }));

    const w = await sp.web.select("Title", "Description")();`

**Comment by patrick-rodgers** [comment]
Can you show the imports for that file? I use the node auth every day - so fairly confident it works.

**Comment by oza-c** [comment]
> Did you grant your application the proper permissions? Interactive Browser is delegated permissions. Connecting via client_credentials require Application Permissions. You'll get this error if you haven't granted the proper permissions.

Yes, that was the mistake. Thanks
