### ISSUE TITLE
Access Denied when using @pnp/graph/taxonomy as a Term Store Admin

### ISSUE THREAD

**Issue by thehorseofcourse** [pnp/pnpjs#3169]
### What version of PnPjs library you are using

4.x

### Minor Version Number

4.7

### Target environment

SharePoint Framework

### Additional environment details

package.json looks like this 
```
{
  "name": "team-directory-hierarchy",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=16.13.0 <17.0.0 || >=18.17.1 <19.0.0"
  },
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@fluentui/react": "^8.106.4",
    "@microsoft/sp-component-base": "1.18.0",
    "@microsoft/sp-core-library": "1.18.0",
    "@microsoft/sp-lodash-subset": "1.18.0",
    "@microsoft/sp-office-ui-fabric-core": "1.18.0",
    "@microsoft/sp-property-pane": "1.18.0",
    "@microsoft/sp-webpart-base": "1.18.0",
    "@pnp/sp": "^4.6.0",
    "@pnp/spfx-property-controls": "^3.18.0",
    "is-url": "^1.2.4",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "tslib": "2.3.1"
  },
  "devDependencies": {
    "@microsoft/eslint-config-spfx": "1.18.0",
    "@microsoft/eslint-plugin-spfx": "1.18.0",
    "@microsoft/rush-stack-compiler-4.7": "0.1.0",
    "@microsoft/sp-build-web": "1.18.0",
    "@microsoft/sp-module-interfaces": "1.18.0",
    "@pnp/graph": "^4.7.0",
    "@rushstack/eslint-config": "2.5.1",
    "@types/is-url": "^1.2.32",
    "@types/react": "17.0.45",
    "@types/react-dom": "17.0.17",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "eslint": "8.7.0",
    "eslint-plugin-react-hooks": "4.3.0",
    "gulp": "4.0.2",
    "typescript": "4.7.4"
  }
}
```

### Question/Request

I am trying to get a specific term in a termset but i keep getting the following error : 

> Error fetching user info: HttpRequestError: Error making HttpClient request in queryable [403]  ::> {"error":{"code":"accessDenied","message":"The current user has insufficient permissions to perform this operation.","innerError":{"date":"2024-11-20T10:03:32","request-id":"de75dcee-ce91-43e8-a656-0d6f33ac189a","client-request-id":"de75dcee-ce91-43e8-a656-0d6f33ac189a"}}}
>     at HttpRequestError.init (c:\Projects\TeamDirectoryHierarchy\dist\node_modules\@pnp\graph\node_modules\@pnp\queryable\behaviors\parsers.js:95:1)
>     at async Function.errorCheck (c:\Projects\TeamDirectoryHierarchy\dist\node_modules\@pnp\graph\node_modules\@pnp\queryable\behaviors\parsers.js:44:1)
>     at async https://localhost:4321/dist/team-directory-hierachy-web-part.js:16359:50 {response: Response, status: 403, statusText: '', isHttpRequestError: true, stack: 'Error: Error making HttpClient request in que…/team-directory-hierachy-web-part.js:16359:50', …

I have tried multiple variations with this, just getting the termstore, a group and all i am getting the same error.
I am following the documentation so I am confused where i am going wrong. Any help will be greatly appreciated

Here is the code i am running

```
import "@pnp/graph/taxonomy"
import "@pnp/graph/sites";
import {graphfi, GraphFI, SPFx } from '@pnp/graph';
const _graph = graphfi().using(SPFx(this.context!))
// get term groups
const info = await _graph.termStore.sets.getById("55eb802e-fbca-455b-a7d2-d5919d4ea3d2").getTermById("039422c2-4979-47d2-aa95-ee318d25d3f0")();
console.log(info)

```

**Comment by juliemturner** [comment]
This library is a pass-through proxy for the API's so if you're getting a 403 then either the user accessing the SPFx solution does not have permissions to do what they're trying to do in the term store or you have not properly configured permissions in SharePoint for SPFx to get a token for delegated permissions to the graph endpoint you're trying to access. I'm gathering the latter as it's often overlooked. I can point you to the specific section of the docs that you're probably missing: [Configure the API permissions requests](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#configure-the-api-permissions-requests). Don't forget that you then need to deploy the solution (this can be a dev package) and approve the api's before this will work. The last sentence in the section I pointed you to has a link to that part of the process.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
