### ISSUE TITLE
Error Response Body "locked" (at least at files.addChunked)

### ISSUE THREAD

**Issue by chr-sad** [pnp/pnpjs#3171]
### Major Version

4.x

### Minor Version Number

4.7.0

### Target environment

SharePoint Framework

### Additional environment details

I am using @pnp/sp v 4.7.0 in an SPFx 1.20.0 webpart on Chrome Version 131.0.6778.86 (64-Bit).

### Expected or Desired Behavior

I want to have access to the error details when calling SharePoint APIs with @pnp/sp to implement specific error handling. The error response should not be locked.

### Observed Behavior

The error response is locked.

### Steps to Reproduce

I am using @pnp/sp v 4.7.0 in our SPFx 1.20.0 solutions and really like it - great work!!!

Now i am facing some issue which seems to me like a possible bug (or maybe i just do not use the feature as intended). In my current usecase I want to use the files.addChunked API to upload a file to SharePoint. My code looks something like:

```
try
{
  //upload file...
  const targetWebUrl:string = options?.targetWebUrl || this.form.props.webUrl;
  const web = this.listFormService.getWeb(targetWebUrl);
  const fileUploadResult:IFileInfo = await (this.listFormService.getUploadDestinationFolder(web, targetFolderUrl) as IFolder)
      .files
      .addChunked(fileName, content, {
          progress: ((data:IFileUploadProgressData) => {
              let percent:number = 0;
              if(content.size && content.size > 0)
                  percent = (data.offset / content.size);
  
              if(options && options.progress)
              {
                  //update progress...
                  options.progress(data.offset, content.size, percent * 100);
              }
          }),
          Overwrite: options ? options.overwrite : undefined
      });
  ...
}
catch(err)
{
    //check upload failed callback
    if(options && options.uploadFailed)
    {
        //upload failed...
        options.uploadFailed(err);
    }
    ...
}
```

The idea is to try to upload the file, but give the caller the possibility to handle custom error cases. In the current scenario the caller would like to check, if the error indicates, that there is already a file with the requested name.

Usually i try to check this kind of errors by using the err.response.json() (after checking the http status code) informations, but in this case, the repsonse.body is locked, so I can not read it or clone it. Since I do not see any code in between, it seems that pnp is using the response already (but not a cloned one) so our code can not use it any longer.

![image](https://github.com/user-attachments/assets/e124ccfc-c8de-440c-a937-bbefeaf232d5)

Could this issue be solved or if it is just me not correctly using the library, can you give me a hint how to solve it?

**Comment by patrick-rodgers** [comment]
In the latest version [we took out cloning](https://github.com/pnp/pnpjs/blob/version-4/packages/queryable/behaviors/parsers.ts#L130) as it was causing issues in some versions of Node. We do include the body in the error.

What information do you need that we aren't including?

**Comment by chr-sad** [comment]
@patrick-rodgers thank you for the very fast response! Basically i wanted to use (and already use multiple times in our solutions) the error handling like in the pnp documentation:
https://pnp.github.io/pnpjs/concepts/error-handling/
<img width="641" alt="image" src="https://github.com/user-attachments/assets/28e88e01-762b-4b70-a1a7-143b445c3644">

Of course I saw the details as text in the error and i can check something like indexOf "-2130575257" in the string to determine the odata error-code (in our current case that the file already exists, but it is a generic function not only for this specific usecase, so i want to be flexible to handle all kinds of errors correctly), but it is not the "same" as parsing the complete json and have all the options available. In the code I also saw, that you pass the reponse, but as in the screenshot above I can not use the body of it since it's locked.

The only possibility for us would be a string comparison (as mentioned above) to be able to check something like this, or am I missing something here?

**Comment by bewster** [comment]
Took me a while to find this issue, and to confirm it was not something I was doing wrong.

I downgraded to @pnp/sp@4.6.0 to get this capability working.

It might be nice to add a comment to the documentation.

**Comment by juliemturner** [comment]
It wasn't an intentional change. As @patrick-rodgers said, it was in response to another issue. We're considering which direction we want to go in, reverting the change, or changing the documentation.

**Comment by chr-sad** [comment]
It would be great if the change is reverted since it was a minor release an breaks existing solutions. If the direction will be to go the new way I think I will have to downgrade an stick with 4.6.0 as well and not upgrade till our next major release to not break dependent solutions.
