### ISSUE TITLE
addUsingPath 403 Access denied

### ISSUE THREAD

**Issue by bewster** [pnp/pnpjs#3174]
### What version of PnPjs library you are using

4.x

### Minor Version Number

4.7.0

### Target environment

SharePoint Framework

### Additional environment details

Debugging in hosted workbench

### Question/Request

I am unsure what I should be doing to able to create a folder on a SharePoint site.

https://pnp.github.io/pnpjs/concepts/auth-spfx/ makes it sound so simple, but without any real content.  When I try researching more it goes off into MSAL and MS Graph API; but I believe I should be able to achieve this just the SharePoint REST API.

Using `getSP` from https://github.com/pnp/pnpjs/blob/version-4/samples/spfx-react-components/src/webparts/pnPjs/pnpjsConfig.ts read calls work fine and I can get folder info from sites in the tenant.

When I try `this._sp.web.folders.addUsingPath()`, as per https://pnp.github.io/pnpjs/sp/folders/#add, I get the 403 response.

**Comment by juliemturner** [comment]
A 403 is "forbidden" which would mean the user that is trying to add the folder at the destination of the path you're giving it doesn't have the permissions to do that or the path you gave it doesn't allow a folder to be created there.

**Comment by bewster** [comment]
I got something to work...

I noticed in the browser that the Request URL used was in the site context:

https://mytenant.sharepoint.com/sites/mysite/_api/web/folders/AddUsingPath(DecodedUrl=@a1,overwrite=@a2)?@a1=%27%2Fsites%2Fmysite%2FWeb%20Part%20Testing%2Fnewfolder%27&@a2=false&$Expand=ListItemAllFields/PermMask

whereas `this._sp.web.folders.addUsingPath()` was using the tenant context:

https://mytenant.sharepoint.com/_api/web/folders/addUsingPath(DecodedUrl='%2Fsites%2Fmysite%2FWeb%20Part%20Testing%2Fnewfolder',overwrite=false)

So I got an `IFolder` of the site and called `.folders.addUsingPath(customerFolder)` from there.

https://mytenant.sharepoint.com/sites/mysite/_api/web/getFolderByServerRelativePath(decodedUrl='%2Fsites%2Fmysite')/folders/addUsingPath(DecodedUrl='%2Fsites%2Fmysite%2FWeb%20Part%20Testing%2Fnewfolder',overwrite=false)
(Although not exactly the same)

So need to use the `web` for the site I have access to - just need some nicer\simpler code to reference it.

**Comment by bewster** [comment]
My question seems similar to #2754 , although there I think the answer is a third approach:

```
const sp: SPFI = getSP();
const folderUrl = "sites/CommunicationDev/Shared%20Documents/Folder001";
await sp.web.getFolderByServerRelativePath("sites/CommunicationDev/Shared%20Documents").folders.addUsingPath(folderUrl);
```

I have also found https://pnp.github.io/pnpjs/sp/folders/#addsubfolderusingpath which also works, can be simpler as the path does not need to be created.

I have used:

```
const folder = await folderFromPath(this._sp.web, parentFolderUrl);
const folderAddResult = await folder.addSubFolderUsingPath('Folder001');
```

**Comment by juliemturner** [comment]
I'm not exactly sure what your question is, it appears you've answered it for yourself?

**Comment by bewster** [comment]
> I'm not exactly sure what your question is, it appears you've answered it for yourself?

Yes, it might be that I have sufficiently answered my own question.
