### ISSUE TITLE
Batch doesn't work for graph "convertContent"

### ISSUE THREAD

**Issue by Youssef-El-Garmit** [pnp/pnpjs#3177]
### Major Version

4.x

### Minor Version Number

6.0

### Target environment

SharePoint Framework

### Additional environment details

i m using react and ts

### Expected or Desired Behavior

I m trying to convertContent using graph, wich work well, but when i try using batch i get wrong blob as response that doesnt work

### Observed Behavior

i should get a good blob as when i m not using batch

### Steps to Reproduce

```TypeScript
const [batchedGraph, execute] = getGraph().batched();
.......
batchedGraph.sites.getById(this._directory.siteId.toString()).drives.getById(graphListInfo.drive.id).getItemByPath(`/${tempNewFileName}`).convertContent("pdf").then((file)=>{
                console.log(file);
                console.log(URL.createObjectURL(file));
                mapNewFile.set(newFileSP, {name:`${request.title}_${laboratory.acronym}.pdf`,content:file});
            })
```

**Comment by patrick-rodgers** [comment]
I don't think the file operations will work with batching. Can you at least share the error message you are getting?

**Comment by Youssef-El-Garmit** [comment]
Hello, thanks for the quick response. There is no error, but the Blob returned is corrupted. I think the error come from the 302 redirection in the batch for which there is no follow up request. When i check the network log after the batch there is no follow up request

**Comment by Youssef-El-Garmit** [comment]
> I don't think the file operations will work with batching. Can you at least share the error message you are getting?

Hello, thanks for the quick response. There is no error, but the Blob returned is corrupted. I think the error come from the 302 redirection in the batch for which there is no follow up request. When i check the network log after the batch there is no follow up request. You can try the same line code with batch and without, you will be see that there is no error but normal return a good blob and not the batched one.

**Comment by Youssef-El-Garmit** [comment]
Hello, i finally fix it, after some search the way the function convertContent is write cannot write with batch :
 ```TypeScript
 public async convertContent(format: "pdf"): Promise<Blob> {
        const query = GraphQueryable(this, `content?format=${format}`)
            .using(BlobParse())
            .using(CacheNever());

        query.on.pre(async (url, init, result) => {

            (<any>init).responseType = "arraybuffer";

            return [url, init, result];
        });

        return query();
    }
   ```
   
   The problem is that in batch the return is a json and not a blob :
```json   
{location : "https://link_to_the_objecturl/"}
```

So to fix it i write this code :
 ```TypeScript
 public async convertContent(format: "pdf", graph: GraphInit): Promise<Blob> {
        const query = GraphQueryable(graph, `content?format=${format}`)
            .using(CacheNever());
    
        query.on.post(async function (url, result) {
            const response = await fetch(result?.location);            
            const blob = response.ok ? await response.blob() : undefined;
            return [url, blob];
        });
    
        return query();
    }
   ```
   
   can you please modify this function to works with batch and not bacthed in a next update ...

**Comment by patrick-rodgers** [comment]
There isn't anything for us to do here. We are returning the response from the server, correctly in the batch. I wouldn't expect file content to come back in a batch, though perhaps there are places it does. I also don't know that we should auto-follow locations and get blobs. I'd recommend just writing the method you need in this case to properly handle it as you require.

In fact, you already have it:

```
       query.on.post(async function (url, result) {
           const response = await fetch(result?.location);            
           const blob = response.ok ? await response.blob() : undefined;
           return [url, blob];
       });
```

you can wrap that in a behavior if you like:

```
export function FollowLocation(): TimelinePipe<Queryable> {

    return (instance: Queryable) => {

        instance.on.post(async (url, result) => {
           const response = await fetch(result?.location);            
           const blob = response.ok ? await response.blob() : undefined;
           return [url, blob];
        });

        return instance;
    };
}
```

and use it to do what you want:

```
const myItem = batchedGraph.sites.getById(this._directory.siteId.toString()).drives.getById(graphListInfo.drive.id).getItemByPath(`/${tempNewFileName}`);

myItem.using(FollowLocation());

const result = awaitmyItem.convertContent("pdf");
```

**Comment by Youssef-El-Garmit** [comment]
Thank for your reply @patrick-rodgers . I try you solution with the behavior but it doesn't work, because by default due to (.using(BlobParse())) the json "{location : "https://link_to_the_objecturl/"}" is converted to blob so we cannot fetch it...

**Comment by patrick-rodgers** [comment]
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!
