### ISSUE TITLE
Developing a custom web part similar to default image web part

### ISSUE THREAD

**Issue by addin-dev-24** [pnp/pnpjs#3178]
### What version of PnPjs library you are using

4.x

### Minor Version Number

1.0

### Target environment

All

### Additional environment details

I am using SharePoint online version

### Question/Request

I want to develop a web part similar to the default image web part, incorporating all its features. The original requirement is to allow users to select images from a third-party image source. Once an image is selected, the web part should display the image in the same manner as the default image web part. 

I would like to know whether it is possible to customize the default image web part or the `FilePicker`(include custom image source in a new section) to achieve this functionality.

**Comment by patrick-rodgers** [comment]
This doesn't appear to be a question on the library? Was there something with PnPjs involved?
