### ISSUE TITLE
How do I opt-out of telemetry in v4? 

### ISSUE THREAD

**Issue by sugar-cubes-m** [pnp/pnpjs#3179]
### What version of PnPjs library you are using

4.x

### Minor Version Number

4

### Target environment

SharePoint Framework

### Additional environment details

NA

### Question/Request

How do I opt-out of telemetry in v4? Could you please provide a code sample to do so. Would simply not including Telemetry into .using(... do the trick?

**Comment by sugar-cubes-m** [comment]
Just to validate that I understand docs and what you are saying correctly, If I simply;y do something like this: 
graphCache: graphfi()
                    .using(graphSPFx(....))
                    .using(PnPLogging(LogLevel.Warning))
                    .using(BrowserFetchWithRetry())
                    .using(Caching(cacheConfig)),
        spCache: spfi(...)
                 .using(BrowserFetchWithRetry())
                 .using(PnPLogging(LogLevel.Warning))
                 .using(Caching(cacheConfig)),
there will be no telemetry for either since I am not including Telemetry into my behavior trees above, correct?

**Comment by juliemturner** [comment]
graphSPFx includes a bunch of behaviors already, including BrowserFetchWithRetry... so I think if you're going to use behaviors included in the package and not roll your own you need to look at them internally first. For example: https://github.com/pnp/pnpjs/blob/version-4/packages/graph/behaviors/spfx.ts#L48

**Comment by sugar-cubes-m** [comment]
Thank you for pointing that out, so If I understand your reply correctly:

1) the answer is no: by simply including my own using(s) I am not overriding any of the behaviors (including DefaultInit) 

2) and thus must write my own behavior and not use DefaultInit/DefaultHeaders similar to the [documentation sample here](https://pnp.github.io/pnpjs/core/behaviors/#composing-behaviors) where one would need to supply own DefaultInit/DefaultHeaders similar to how the code (here)[https://github.com/pnp/pnpjs/blob/version-4/packages/graph/behaviors/defaults.ts] and exclude Telemetry explicitly.

3) and thus there is no straight forward way to switch telemetry off that we used to have in version 2 i.e.: 
```typescript
import PnPTelemetry from '@pnp/telemetry-js';
...
 const telemetry = PnPTelemetry.getInstance();
  telemetry.optOut();
```

Could you please confirm approach in #2 to disable telemetry as correct one at this point in time for v4?

Personally I have no issue with telemetry at all. It is an org requirement (that I work for) informational security department to disable it. All I am trying to do is to understand how to do so. More specific example in documentation on how to do so or simpler way to opt out would be very nice to have.

**Comment by juliemturner** [comment]
Yes, #2 is the route you would have to take... 

That said, this is not telemetry as most security organizations would define, so before you go through all this effort you might want to discuss it with them and show them the "telemetry" code that executes. Microsoft itself tracks just a whole ton of telemetry after you call the api, all we're doing to tracking which ones are called, not by who or where from, just which ones.

**Comment by sugar-cubes-m** [comment]
Understood, thank you @juliemturner
