### ISSUE TITLE
renderlistdata doesn't return values for documents in subfolders in libraries

### ISSUE THREAD

**Issue by hamedy** [pnp/pnpjs#318]
So I have a React document library webpart which fetches individual items using renderlistdata for populating the edit form. 

Everything works fine on the root level documents but not for items in subfolders. 

this is an example response I get back for a subfolder item:

{"d":{"RenderListData":"{ \"Row\" : \n[],\"FolderPermissions\" : \"0x7ffffffffffbffff\"\r\n\n}"}}

this is an example response I get back for a root level item:

{"d":{"RenderListData":"{ \"Row\" : \n[{\r\n\"ID\": \"6\",\r\n\"PermMask\": \"0x7ffffffffffbffff\",\r\n\"FSObjType\": \"0\",\r\n\"HTML_x0020_File_x0020_Type\": \"\",\r\n\"UniqueId\": \"{78C3D3D9-162F-4A34-AFF6-C22F8CA09995}\",\r\n\"ProgId\": \"\",\r\n\"NoExecute\": \"1\",\r\n\"ContentType\": \"\",\r\n\"Title\": \"\",\r\n\"FileLeafRef\": \"1540289093320.xlsx\",\r\n\"ContentVersion\": \"1\",\r\n\"DocConcurrencyNumber\": \"3\",\r\n\"_VirusStatus\": \"\"\r\n}\r\n],\"FirstRow\" : 1,\r\n\"FolderPermissions\" : \"0x7ffffffffffbffff\"\r\n,\"LastRow\" : 1,\r\n\"RowLimit\" : 30\r\n,\"FilterLink\" : \"?\"\n,\"ForceNoHierarchy\" : \"1\"\n,\"HierarchyHasIndention\" : \"\"\n\n}"}}

any ideas? this is by the way using the old pnp js, I tried the new library also but that didn't work either. Is there a known bug in the old pnp renderlistdata? 

thanks in advance :)

**Comment by koltyakov** [comment]
Hi @hamedy,

What SP version do you use?
I implemented recently a similar webpart yet with `renderListDataAsStream` and experienced no issues. 
If your SP is 2016 or later or SPO `renderListDataAsStream` is a way to go.

```typescript
const listPath = '/sites/site/doclib';
const folderPath = decodeURIComponent('Folder 01/Folder 02');
web.getList(listPath).renderListDataAsStream({
      ViewXml: `
        <View>
          <ViewFields>
            <FieldRef Name="ID" />
            <FieldRef Name="ContentType" />
            <FieldRef Name="FileLeafRef" />
            <FieldRef Name="ItemChildCount" />
            <FieldRef Name="FolderChildCount" />
            <FieldRef Name="FileRef" />
            <FieldRef Name="Title" />
            <FieldRef Name="Author" />
            <FieldRef Name="Created" />
            <FieldRef Name="Editor" />
            <FieldRef Name="Modified" />
            <FieldRef Name="File_x0020_Size" />
            <FieldRef Name="FSObjType" />
            <FieldRef Name="DocIcon" />
            <FieldRef Name="ServerUrl" />
            <FieldRef Name="_UIVersionString" />
          </ViewFields>
          <RowLimit Paged="TRUE">5000</RowLimit>
        </View>
      `
}, { RootFolder: folderPath });
```

**Comment by hamedy** [comment]
thanks for your reply. I'm using SPO. Not sure if you're using the new pnp or the deprecated one. But is the "{ RootFolder: folderPath }" part necessary in the old pnp? I thought passing the id of the item in the viewxml would be enough? 

this is a sample of my request url:

https://[domain].sharepoint.com/sites/brilliantcore/sitetemplate/_api/web/lists/getByTitle('Dokumenter')/renderlistdata(@viewXml)?@viewXml='<View><Query><Where><Eq><FieldRef Name="ID" /><Value Type="Number">16</Value></Eq></Where></Query><ViewFields><FieldRef Name="Id" /><FieldRef Name="Title" /><FieldRef Name="FileLeafRef" /></ViewFields></View>'

**Comment by koltyakov** [comment]
I obviously mentioning PnPjs (not sp-pnp-js) :smile:

> I'm using SPO

That's good. So you can grab and use `renderListDataAsStream`. It's a modern version of `renderListData` which is based on POST (not a limited GET as `renderListData`) and has a variety of extra settings. The `RootFolder` parameter is one of them.

> viewXml

`viewXml` should stay for a valid CAML query not an ID of an item.

**Comment by hamedy** [comment]
ok, now tried your suggestion and I get access denied on contextinfo! Not sure what I'm doing wrong.
tried it with and without RootFolder.

`import { Web } from "@pnp/sp";
let web = new Web("https://[domain].sharepoint.com/sites/brilliantcore/sitetemplate");
web.lists.getByTitle("Dokumenter").renderListDataAsStream({
    ViewXml: `
                          <View>
                            <ViewFields>
                              <FieldRef Name="ID" />
                              <FieldRef Name="ContentType" />
                              <FieldRef Name="FileLeafRef" />
                              <FieldRef Name="ItemChildCount" />
                              <FieldRef Name="FolderChildCount" />
                              <FieldRef Name="FileRef" />
                              <FieldRef Name="Title" />
                              <FieldRef Name="Author" />
                              <FieldRef Name="Created" />
                              <FieldRef Name="Editor" />
                              <FieldRef Name="Modified" />
                              <FieldRef Name="File_x0020_Size" />
                              <FieldRef Name="FSObjType" />
                              <FieldRef Name="DocIcon" />
                              <FieldRef Name="ServerUrl" />
                              <FieldRef Name="_UIVersionString" />
                            </ViewFields>
                            <RowLimit Paged="TRUE">5000</RowLimit>
                          </View>
                        `
})
    .then((results) => {
        console.log("results", results)
    });`

**Comment by hamedy** [comment]
figured out, got it to work with your suggested approach. Thanks for your help!

**Comment by koltyakov** [comment]
Thanks, closing this one.

**Comment by pinjala** [comment]
> figured out, got it to work with your suggested approach. Thanks for your help!

@hamedy  : i am having the same issue . its not working when i selected any document inside of folder . But working when i selected at root level of doument library ..i am using renderListDataAsStream. Please guide me how do you fix and let me know the changes .
