### ISSUE TITLE
Retrieving DriveItem Thumbnails

### ISSUE THREAD

**Issue by Nistro-dev** [pnp/pnpjs#3182]
### What version of PnPjs library you are using

4.x

### Minor Version Number

7.0

### Target environment

SharePoint Framework

### Additional environment details

- **pnpjs Version**: `4.7.0`
- **Browser**: `Firefox 133.0.3 (64 bits)`
- **Framework**: `React 17`
- **SharePoint Environment**: `SharePoint Online`
- **Usage Context**:
  - Initializing pnpjs with the appropriate configuration within a library.
  - Attempting to retrieve thumbnails using the provided REST endpoint.

- **Initialization Code**:
```typescript
export abstract class Service extends BaseService {

    protected sp: SPFI;
    protected graph: GraphFI;

    constructor(serviceScope: ServiceScope) {
        super(serviceScope);
        serviceScope.whenFinished(async () => {
            this.sp = spfi().using(SPFxSP({
                pageContext: this.pageContext
            }));

            this.graph = graphfi().using(SPFxGraph({aadTokenProviderFactory: this.aadTokenProviderFactory}), SPFxToken({aadTokenProviderFactory: this.aadTokenProviderFactory}));
        });
    }
}
```

### Question/Request

I would like to request the addition of support for retrieving thumbnails of `driveItem` objects using pnpjs. Specifically, I aim to access thumbnails through the following REST endpoint:
```
v1.0/sites/{siteId}/lists/{listId}/items/{itemId}/driveItem/thumbnails/
```

**Comment by juliemturner** [comment]
I believe it's already available... https://pnp.github.io/pnpjs/graph/files/#get-thumbnails

**Comment by Nistro-dev** [comment]
Thanks, didnt see it...
