### ISSUE TITLE
SearchQuery: Using QueryTag property throws error

### ISSUE THREAD

**Issue by jimmywim** [pnp/pnpjs#320]
### Category
- Bug

### Version

Please specify what version of the library you are using: [1.2.3]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
using sp.search, passing in a SearchQuery object, with QueryTag property set to an array of strings, should return the search query.

### Observed Behavior
The following error:
`A node of type 'StartArray' was read from the JSON reader when trying to read a value of a property; however, a 'PrimitiveValue' or 'StartObject' node was expected.`

### Steps to Reproduce
```
    var query: SearchQuery = {
      Querytext: `Department:${department}`,
      SourceId: "B09A7990-05EA-4AF9-81EF-EDFAB16C4E31",
      QueryTag: ['EmployeeQuery']
    }
    var results = await sp.search(query);
```

Modifying the search.d.ts file, line 242 where QueryTag is defined to just `string` instead of `string[]`, and setting the QueryTag to a single string yields no error.

**Comment by patrick-rodgers** [comment]
Thanks, appreciate you submitting this fix!
