### ISSUE TITLE
GraphBatch auto limit requests to 20 per http request

### ISSUE THREAD

**Issue by patrick-rodgers** [pnp/pnpjs#324]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ next        ]

Please specify what version(s) of SharePoint you are targeting: [ SPO      ]

### Expected / Desired Behavior / Question

GraphBatch auto limit requests to 20 per http request as per the spec.

**Comment by pkmelee337** [comment]
Hi @patrick-rodgers , Thanks for all the actions! :-) Maybe I can be of help with this one. The way I fixed this in my extended GraphBatch class is as followed:

```typescript
import { GraphBatch, ODataBatchRequestInfo } from "@pnp/pnpjs";

export class MyGraphBatch extends GraphBatch {
    private readonly maximumBatchSize: number = 20;

    protected async executeImpl(): Promise<void> {
        if(this.requests.length > this.maximumBatchSize) {
            this.executeMultipleBatches(this.requests);
        } else {
            await super.executeImpl();
        }
    }
    
    private async executeMultipleBatches(requestsLeft: ODataBatchRequestInfo[]): Promise<void> {
        let requestToExecute = requestsLeft.splice(0, (requestsLeft.length >= this.maximumBatchSize) ? this.maximumBatchSize : requestsLeft.length);
        requestsLeft = requestsLeft.filter((o) => requestToExecute.indexOf(o) === -1);
        this.requests.splice(0, this.requests.length); // clear current requests
        this.requests.push(...requestToExecute);
        await super.executeImpl();

        if (requestsLeft.length > 0) {
            await this.executeMultipleBatches(requestsLeft);
        }
    }
}
```

This executes all the batch requests in batches of 20. If you like, you can re-use some of the code in the final implementation.
