### ISSUE TITLE
Graph - "Message: User login is required" when navigating to another page with the login popup still open

### ISSUE THREAD

**Issue by pkmelee337** [pnp/pnpjs#335]
### Category
- [ ] Enhancement
- [ x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.2.3 ]

Please specify what version(s) of SharePoint you are targeting: [ SPO ]

### Expected / Desired Behavior / Question
On our SharePoint homepage we've got a few SPFx webpart consuming the graph with pnpjs. This is working quite allright in most scenario's. On another page we have got another SPFx webpart consuming the graph. When opening the homepage and clicking straight through to this next page, the browser is navigating when the popup is still open. I'm expecting the webpart on the next page to render without issues.

### Observed Behavior
Retrieving graph properties on the next page are failing with the message "User login is required". When refreshing the page the webpart is working allright.

### Steps to Reproduce
As decribed above 👍

**Comment by patrick-rodgers** [comment]
We are moving in the next release to use the SPFx 1.6 capabilites that does not require the pop-up. Going to close this as the work has already been done and mentioned in #316 & #218.

Next release is planned for Friday November 2
