### ISSUE TITLE
sp.profiles.setSingleValueProfileProperty causes a "Error making HttpClient request in queryable: [500]"

### ISSUE THREAD

**Issue by rmngh** [pnp/pnpjs#340]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.3]

Please specify what version(s) of SharePoint you are targeting: [Online]

I'm currently utilizing the sp.profiles.setSingleValueProfileProperty function in order to update a property for a User Profile. I'm setting up sp via sp.setup({ spfxContext: this.context }) from the base webpart client and then issuing a call in onInit to setSingleValueProfileProperty. The call fails with a "Error making HttpClient request in queryable: [500]". Retrieving properties works perfectly via sp.profiles.myProperties.get(). I found another instance where a user ran into the same issue (https://sharepoint.stackexchange.com/questions/247087/spfx-pnp-js-setting-value-of-a-custom-user-profile-property), but was able to resolve it. They never mentioned what the issue was. Am I missing a setup step? Thanks.

**Comment by patrick-rodgers** [comment]
Hi @rmngh - not sure what might be causing your error exactly. Did you get the message the server returned?

I tried a few things to generate errors and got a 500 error if the property wasn't created. The error I got in this case was:

> Property Not Defined: test.  An administrator must create this property in the Profile Administration tool.

The fix was to create the property.

Then I got the error:

> Property Not Editable: This property can only be modified by an administrator.

The fix was to make the property editable. It did take a few seconds for the change to take affect.

Generally the error messages help guide as to what might be wrong. Not always true but a good place to start. Let us know if this gets you sorted. Thanks!

**Comment by rmngh** [comment]
@patrick-rodgers Hmm...that's odd. The only error I get is the 500 in the title of this ticket ("Error making HttpClient request in queryable: [500]"). Do I need to setup the HttpClient before issuing the call? I thought I had to do that if I needed to make a custom call.

**Comment by patrick-rodgers** [comment]
You can see the full error if you [enable verbose logging and setup the console logger](https://pnp.github.io/pnpjs/logging/docs/). Alternatively you can look at the result of the bad request in fiddler or the F12 developer console in the browser. It being a developer tenant shouldn't matter, but perhaps a property is missing you expect to exist?

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Please _reopen_ the issue should you need to continue the discussion. Thanks!

**Comment by patrick-rodgers** [comment]
@rmngh - just wanted to circle back and let you know I took a look at improving the error message for pipeline http requests. We will now provide the full error body in the message along with the previous information. This will hopefully make things easier going forward for folks to see exactly what went wrong without any other steps needed.

**Comment by rmngh** [comment]
@patrick-rodgers Appreciate that! Thanks.
