### ISSUE TITLE
Cannot call any methods on listitem after retriving it

### ISSUE THREAD

**Issue by russgove** [pnp/pnpjs#342]
x Bug
x Question
Version 1.2.4
Hi, not sure if this is a bug or i'm doing something wrong. I have this code in the oninit method of an spfx webpart running in spo:

 public onInit(): Promise<void> {

    debugger;

    return super.onInit()
      .then(() => {
        debugger;
        sp.setup({
          spfxContext: this.context
        });
        debugger;
        //var listId: string// = this.context.pageContext.list.id.toString();//"48243be7-6e44-4e12-8f41-e79c69ae8c15"
        var listId = "48243be7-6e44-4e12-8f41-e79c69ae8c15"
        var queryParameters = new UrlQueryParameterCollection(window.location.href);
        const id: number = parseInt(queryParameters.getValue("ID")); // 4017
        return sp.web.lists.getById(listId).items.getById(id).get()
          .then((item: Item) => {
            debugger;
            this.item = item;
            return item.currentUserHasPermissions(PermissionKind.EditListItems)
              .then((haspermission) => {
                debugger;
              })
              .catch(err => {
                debugger;
              });

          })
          .catch((error) => {
            console.log(`Error fetching task. Task ID is ${id}. List ID is ${listId}`);
          });

      });
  }

Issue is with the line
item.currentUserHasPermissions(PermissionKind.EditListItems)

It compile fine, but at runtime currentUserHasPermissions is undefined.
In fact item is just a plain object. It has no methids that are defined in pnpJS

Am i doing something wrong?

**Comment by patrick-rodgers** [comment]
Hi @russgove , we don't automatically merge the Class Item into the results unless you specify that you want that to happen using the spODataEntity and spODataEntityArray methods. I just looked and realized we never created a new docs page covering this after we switched docs. Here is [the original one from the old library](https://github.com/SharePoint/PnP-JS-Core/wiki/Response-Parsers#whats-included) to help get you moving. I am going to leave this open as a documentation need to ensure we get the page created. Thanks for letting us know.

**Comment by russgove** [comment]
thanks for the quick reply patrick! I change the code to this:
   return super.onInit()
      .then(() => {
        debugger;
        sp.setup({
          spfxContext: this.context
        });
        debugger;
        var listId: string = this.context.pageContext.list.id.toString();//"48243be7-6e44-4e12-8f41-e79c69ae8c15"
        var queryParameters = new UrlQueryParameterCollection(window.location.href);
        const id: number = parseInt(queryParameters.getValue("ID")); // 4017
        return sp.web.lists.getById(listId).items.getById(id).get(new ODataDefaultParser())
          .then((item: Item) => {
            debugger;
            return item.currentUserHasPermissions(this.properties.permission)
              .then((haspermission) => {
                if (haspermission) {
                  debugger;
                  var origUrl = document.location.toString();
                  var editUrl = origUrl.replace(this.properties.changeFrom,this.properties.changeTo);
                  document.location.href = editUrl;
                }
                else {
                  //noop
                }
              })
              .catch(err => {
                debugger;
              });
          })
          .catch((error) => {
            console.log(`Error fetching task. Task ID is ${id}. List ID is ${listId}`);
          });
      });
  }

but i am getting the same result (item is stuill just an object). What am I missing?

**Comment by russgove** [comment]
I tried 
   return sp.web.lists.getById(listId).items.getById(id).get<Item>()

that didnt work either

**Comment by patrick-rodgers** [comment]
Give this a shot, updated docs page that I just tested: https://pnp.github.io/pnpjs/sp/docs/entity-merging/

**Comment by patrick-rodgers** [comment]
reopening until @russgove confirms he id good.

**Comment by russgove** [comment]
I changed my imports to 
import { sp, Item, spODataEntity,PermissionKind } from "@pnp/sp";

and the get call to 
  return sp.web.lists.getById(listId).items.getById(id).get<spODataEntity<Item>>()

typescript is telling me  TS2304: Cannot find name 'spODataEntity'.

full webpart code :
import * as React from 'react';
import * as ReactDom from 'react-dom';
import { Version, UrlQueryParameterCollection } from '@microsoft/sp-core-library';
import {
  BaseClientSideWebPart,
  IPropertyPaneConfiguration,
  PropertyPaneTextField,
  IPropertyPaneDropdownOption,
  PropertyPaneDropdown
} from '@microsoft/sp-webpart-base';

import * as strings from 'ReactFormRedirectWebPartStrings';
import ReactFormRedirect from './components/ReactFormRedirect';
import { IReactFormRedirectProps } from './components/IReactFormRedirectProps';

import { SPListItem, SPList, SPPermission } from '@microsoft/sp-page-context';
import { sp, Item, spODataEntity,PermissionKind } from "@pnp/sp";
import { ODataDefaultParser } from '@pnp/odata';
import { StringRepresentable } from 'lodash';

export interface IReactFormRedirectWebPartProps {
  permission: PermissionKind;
  changeFrom: string;
  changeTo: string;
}

export default class ReactFormRedirectWebPart extends BaseClientSideWebPart<IReactFormRedirectWebPartProps> {

  private _item: Item;
  public get item(): Item {
    return this._item;
  }
  public set item(v: Item) {
    this._item = v;
  }

  public getPermissionTypes(): IPropertyPaneDropdownOption[] {
    debugger;
    let perms = new Array();
    for (const perm in SPPermission) {

      if (typeof (SPPermission[perm]) === "object") {
        perms.push({
          text: perm,
          key: perm
        });
      }
    }
    return perms;
  }
  public onInit(): Promise<void> {

    debugger;

    return super.onInit()
      .then(() => {
        debugger;
        sp.setup({
          spfxContext: this.context
        });
        debugger;
        var listId: string = this.context.pageContext.list.id.toString();//"48243be7-6e44-4e12-8f41-e79c69ae8c15"
        var queryParameters = new UrlQueryParameterCollection(window.location.href);
        const id: number = parseInt(queryParameters.getValue("ID")); // 4017
        return sp.web.lists.getById(listId).items.getById(id).get<spODataEntity<Item>>()
        
          .then((item: Item) => {
            debugger;
            return item.currentUserHasPermissions(this.properties.permission)
              .then((haspermission) => {
                if (haspermission) {
                  debugger;
                  var origUrl = document.location.toString();
                  var editUrl = origUrl.replace(this.properties.changeFrom,this.properties.changeTo);
                  document.location.href = editUrl;
                }
                else {
                  //noop
                }
              })
              .catch(err => {
                debugger;
              });
          })
          .catch((error) => {
            console.log(`Error fetching task. Task ID is ${id}. List ID is ${listId}`);
          });
      });
  }

  public render(): void {
    debugger;



    // const element: React.ReactElement<IReactFormRedirectProps> = React.createElement(
    //   ReactFormRedirect,
    //   {
    //     item: this.item,
    //     permissionKind: this.properties.permission,
    //   }
    // );

    // ReactDom.render(element, this.domElement);
  }


  protected onDispose(): void {
    ReactDom.unmountComponentAtNode(this.domElement);
  }

  protected get dataVersion(): Version {
    return Version.parse('1.0');
  }

  protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: [
            {
              groupName: strings.BasicGroupName,
              groupFields: [
          
                PropertyPaneDropdown("permission", {
                  label: "If User has this persmission on the current item",
                  options: this.getPermissionTypes()
                }),
                PropertyPaneTextField("changeFrom",                {
                  label:"Change this string in the URL"
                }),
                PropertyPaneTextField("changeTo",                {
                  label:"to this string"
                })

              ]
            }
          ]
        }
      ]
    };
  }
}

**Comment by patrick-rodgers** [comment]
Please have a close look at the linked article, especially this line:

```
const item = await sp.web.lists.getByTitle("ListTitle").items.getById(1).get(spODataEntity<Item, MyProps>(Item));
```

Note that spODataEntity is being passed with two type parameters to ensure proper definition of the resulting object.  The main paramenter `Item` in this example is the constructor of the type you are trying to create.

**Comment by russgove** [comment]
OK, I added the my props, but i am still getting the error  TS2304: Cannot
find name 'spODataEntity'.

import * as React from 'react';
import * as ReactDom from 'react-dom';
import { Version, UrlQueryParameterCollection } from
'@microsoft/sp-core-library';
import {
BaseClientSideWebPart,
IPropertyPaneConfiguration,
PropertyPaneTextField,
IPropertyPaneDropdownOption,
PropertyPaneDropdown
} from '@microsoft/sp-webpart-base';

import * as strings from 'ReactFormRedirectWebPartStrings';
import ReactFormRedirect from './components/ReactFormRedirect';
import { IReactFormRedirectProps } from
'./components/IReactFormRedirectProps';

import { SPListItem, SPList, SPPermission } from
'@microsoft/sp-page-context';
import { sp, Item, PermissionKind, spODataEntity } from "@pnp/sp";
import { ODataDefaultParser } from '@pnp/odata';
import { StringRepresentable } from 'lodash';

export interface IReactFormRedirectWebPartProps {
permission: PermissionKind;
changeFrom: string;
changeTo: string;
}
interface MyProps {
Id: number;
}
export default class ReactFormRedirectWebPart extends BaseClientSideWebPart<
IReactFormRedirectWebPartProps> {

private _item: Item;
public get item(): Item {
return this._item;
}
public set item(v: Item) {
this._item = v;
}

public getPermissionTypes(): IPropertyPaneDropdownOption[] {
debugger;
let perms = new Array();
for (const perm in SPPermission) {

if (typeof (SPPermission[perm]) === "object") {
perms.push({
text: perm,
key: perm
});
}
}
return perms;
}
public onInit(): Promise<void> {

debugger;

return super.onInit()
.then(() => {
debugger;
sp.setup({
spfxContext: this.context
});
debugger;
var listId: string = this.context.pageContext.list.id.toString();
//"48243be7-6e44-4e12-8f41-e79c69ae8c15"
var queryParameters = new UrlQueryParameterCollection(window.location.href);
const id: number = parseInt(queryParameters.getValue("ID")); // 4017
return sp.web.lists.getById(listId).items.getById(id).get<spODataEntity<Item,
MyProps>>()
.then((item: Item) => {
debugger;
return item.currentUserHasPermissions(this.properties.permission)
.then((haspermission) => {
if (haspermission) {
debugger;
var origUrl = document.location.toString();
var editUrl = origUrl.replace(this.properties.changeFrom,this.properties.
changeTo);
document.location.href = editUrl;
}
else {
//noop
}
})
.catch(err => {
debugger;
});
})
.catch((error) => {
console.log(`Error fetching task. Task ID is ${id}. List ID is ${listId}`);
});
});
}

public render(): void {
debugger;



// const element: React.ReactElement<IReactFormRedirectProps> =
React.createElement(
// ReactFormRedirect,
// {
// item: this.item,
// permissionKind: this.properties.permission,
// }
// );

// ReactDom.render(element, this.domElement);
}


protected onDispose(): void {
ReactDom.unmountComponentAtNode(this.domElement);
}

protected get dataVersion(): Version {
return Version.parse('1.0');
}

protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
return {
pages: [
{
header: {
description: strings.PropertyPaneDescription
},
groups: [
{
groupName: strings.BasicGroupName,
groupFields: [
PropertyPaneDropdown("permission", {
label: "If User has this persmission on the current item",
options: this.getPermissionTypes()
}),
PropertyPaneTextField("changeFrom", {
label:"Change this string in the URL"
}),
PropertyPaneTextField("changeTo", {
label:"to this string"
})

]
}
]
}
]
};
}
}


package.json :
{
"name": "react-form-redirect-2",
"version": "0.0.1",
"private": true,
"engines": {
"node": ">=0.10.0"
},
"scripts": {
"build": "gulp bundle",
"clean": "gulp clean",
"test": "gulp test"
},
"dependencies": {
"@microsoft/sp-core-library": "1.6.0",
"@microsoft/sp-lodash-subset": "1.6.0",
"@microsoft/sp-office-ui-fabric-core": "1.6.0",
"@microsoft/sp-webpart-base": "1.6.0",
"@pnp/common": "1.2.4",
"@pnp/logging": "1.2.4",
"@pnp/odata": "1.2.4",
"@pnp/sp": "1.2.4",
"@types/es6-promise": "0.0.33",
"@types/react": "15.6.6",
"@types/react-dom": "15.5.6",
"@types/webpack-env": "1.13.1",
"react": "15.6.2",
"react-dom": "15.6.2"
},
"devDependencies": {
"@microsoft/sp-build-web": "1.6.0",
"@microsoft/sp-module-interfaces": "1.6.0",
"@microsoft/sp-webpart-workbench": "1.6.0",
"tslint-microsoft-contrib": "~5.0.0",
"gulp": "~3.9.1",
"@types/chai": "3.4.34",
"@types/mocha": "2.2.38",
"ajv": "~5.2.2"
}
}

**Comment by patrick-rodgers** [comment]
Have again a look at the code sample. The spODataEntity<Item, MyProps>(Item) construct is passed INTO the get method as an argument, not used as a type parameter. I think that is what is tripping you up.

get`(` spODataEntity<Item, MyProps>(Item) `)`

**Comment by russgove** [comment]
ah, that did it. Thanks. Is this changed from older versions. I don recall
having to do this in the past!

**Comment by patrick-rodgers** [comment]
No change in behavior, but the helper methods did change names. We have never auto-merged the data and instances. This pattern also allows you the write your own sub-class of Item and have that returned by passing that constructor to the method.

Going to close this as answered, glad things are working for you and thanks for catching the missing article.
