### ISSUE TITLE
Error Updating items in Pages Library SP2013

### ISSUE THREAD

**Issue by dniemuth** [pnp/pnpjs#344]
- [ ] Enhancement
- [X] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.2.4 ]

Please specify what version(s) of SharePoint you are targeting: [ SP2013 ]

### Issue

I'm running a node application targeting a SP2013 Pages library. I am able to get information from this library, but updating or creating items in here does not work. I get this error.
`Error: Error making HttpClient request in queryable: [500] Internal Server Error`

This code works fine.
```
web.lists.getByTitle('Pages').items.getById(4661).get()
    .then(res => {
      console.log(res);
    })
```

This code fails.
```
web.lists.getByTitle('Pages').items.getById(4661).update(
    {
      Categories_x0020_and_x0020_Topics: '.1;.4;#2;#11;#12;'
    }
  ).then(res => {
    console.log(res)
  }).catch(err => {
    console.log(err);
  })
```
The field Categories and Topics is correct (this is what is returned with the successful snippet) and is a single line of text field.

Any thoughts?

**Comment by patrick-rodgers** [comment]
Can you see if you get any additional error details back from the server? Unfortunately without a bit more detail we would just be guessing at what might be wrong. It could be the field name, or perhaps some other field is required.

**Comment by patrick-rodgers** [comment]
Going to close this as we didn't hear back. Please _reopen_ if you still need help and can provide a bit more detail around the error, browser, or a minimal repro on GitHub and we'll take a look. Thanks!
