### ISSUE TITLE
Search on hub scope

### ISSUE THREAD

**Issue by berubejp** [pnp/pnpjs#346]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### 

I'm currently doing search request on all sites. I would like to get results from all related sites within a hub. Something that would look like this:
```tsx 
const search = new Search("https://mytenant.sharepoint.com/sites/MyHub");
search.execute(<SearchQuery>{
  Querytext: "some text",
  RowLimit: 10,
  EnableInterleaving: true
}).then((r: SearchResults) => {
  ...
});
```

It is available from the SharePoint UI.

![image](https://user-images.githubusercontent.com/6032760/48140517-ee7d2f80-e276-11e8-8b6e-dabb9e8f1ed3.png)

Is it possible to search within a hub scope?

**Comment by patrick-rodgers** [comment]
You can do pretty much exactly what you wrote above, see [this comment in a previous issue](https://github.com/pnp/pnpjs/issues/308#issuecomment-434053733). I am not aware of anything special around hub sites, but please try that out and let us know if it doesn't work as expected. Perhaps you can examine the call the UI webpart is making to get some insight as well.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Please _reopen_ the issue should you need to continue the conversation. Thanks!
