### ISSUE TITLE
"Unexpected anonymous AMD define" when dynamically loading from CDN 

### ISSUE THREAD

**Issue by ejvanderveen** [pnp/pnpjs#350]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.2.3  ]

Please specify what version(s) of SharePoint you are targeting: [ o365  ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Dynamically load pnp-js from CDN from within a non-SPFX solution bundled with webpack.

### Observed Behavior
When I load pnpjs from a CDN from within a non-SPFX typescript solution bundled with Webpack.
When I use JQuery.getScript to load for instance: 
https://cdnjs.cloudflare.com/ajax/libs/pnp-pnpjs/1.2.3/pnpjs.es5.umd.js
It fails with the following error: Uncaught TypeError: Unexpected anonymous AMD define ... 
... at pnpjs.es5.umd.js:12  at pnpjs.es5.umd.js:14

Seems to fail on the "eval" which is being done after the actual load. 

Pretty sure it is me doing the loading the wrong way, but can't figure out what the correct way is. 
When I let webpack just bundle the  imports (just like in a SPFX solution) everything is working fine.

**Comment by patrick-rodgers** [comment]
You could try one of the non-umd files, pnpjs.es5.js and see. The other approach would be to configure webpack to create external chunks of your deps and load those from your cdn. Webpack should output chunks that it can load.

We can also [take a look at this setting](https://webpack.js.org/configuration/output/#output-umdnameddefine), though I am not sure what else that will break for others.

One of the challenges we have is that there are so many ways to load/bundle files it is hard to ensure we support everything anyone could do.

**Comment by ejvanderveen** [comment]
Tried the other file you mentioned; https://rbwidgets.azureedge.net/node/pnp-pnpjs/1.2.3/pnpjs.es5. No more "unexpected anomymous AMD define" message this time, but still an error... This time an: "Unexpected token {" message pointing at the first curly brace for the first import statement in that file. 
I first tried this using the  jQuery.getScript method as I did before which does an eval of the code after loading. But I also tried a jQuery.ajax call to load the file as a text and then executing it using the "New Function" patern. They both give the same result. Will try to load it by programmaticaly adding a scripttag to the document, which feels a bit as a dirty fix.

**Comment by koltyakov** [comment]
@ejvanderveen,

> When I use JQuery.getScript to load for instance:
> https://cdnjs.cloudflare.com/ajax/libs/pnp-pnpjs/1.2.3/pnpjs.es5.umd.js

Did you try loading bundle (pnpjs.es5.umd.bundle.js)?

For non-SPFx solutions, I can humbly recommend taking a look at [generator-sppp](https://github.com/koltyakov/generator-sppp) it includes PnPjs by default and WebPack external configuration:

```typescript
// Inside WebPack config
config.externals = Object.assign(config.externals || {}, {
  '@pnp/sp': 'pnp'
});
```

When `pnpjs.es5.umd.bundle.js` should be referenced/loaded before it's used. This allows use usual ES6 modules without adding libraries to the bundle.

Another approach is to use dynamic import (`import('@pnp/sp').then(({ sp })) => { sp.web.andSoOn... })`) and WebPack chunks.

**Comment by patrick-rodgers** [comment]
Going to close this due to lack of activity. Please do _reopen_ should you need to continue the conversation. Thanks!
