### ISSUE TITLE
Trying to delete multiple fields in a list at once?

### ISSUE THREAD

**Issue by simkessy** [pnp/pnpjs#354]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    Latest    ]

Please specify what version(s) of SharePoint you are targeting: [     2013    ]

I'm trying to loop through an array of column names and delete them from my list. The first one works fine but the following ones return an error saying something about needing a new version. 

Wondering if there's an established way of deleting multiple fields or if I need to requery the fields or list for each request. 

This is how I'm doing it: 

```
let fieldsToDelete = [
            "Field1",
            "Field2",
            "Field3"
        ];

        // Delete fields from Web
        fieldsToDelete.forEach(f => {
            myapp.v201.web.fields
                .getByInternalNameOrTitle(f)
                .delete()
                .then(() => {
                    console.log(`${f} deleted from web`);
                })
                .finally(() => {
                    // Delete from PS List
                    myapp.v201.lists.myList.fields
                        .getByInternalNameOrTitle(f)
                        .delete()
                        .then(() => {
                            console.log(`${f} deleted from My List 1`);
                        })
                        .catch(frb.error.log);

                    // Delete from DAS
                    myapp.v201.lists.myList2.fields
                        .getByInternalNameOrTitle(f)
                        .delete()
                        .then(() => {
                            console.log(`${f} deleted from My List 2`);
                        })
                        .catch(myapp.error.log);
                })
                .catch(myapp.error.log);
        });
```

**Comment by koltyakov** [comment]
Deleting fields is similar to adding I'd suggest. They should be deleted sequentially.
So, `for/of loop and async/await` is the option for SP 2013, for the version which supports batch API, fields can be deleted in a batch (sequential actions on the back-end). 
Also, `.finally`? It's not supported in the current promises implementation, is it?

**Comment by simkessy** [comment]
Thank you.
