### ISSUE TITLE
Implement fix for getting term label name instead of id for single value managed metadata field

### ISSUE THREAD

**Issue by unnieayilliath** [pnp/pnpjs#358]
### Category
- [x] Enhancement
### Version

Please specify what version of the library you are using: [     1.2.5    ]

Please specify what version(s) of SharePoint you are targeting: [    SP 2013     ]

I am getting all field values of a list item using below method:
```
  pnp.sp.web.lists.getByTitle(libName).items.getById(8).get().then((item) => {
        console.log(item);
});
```

### Expected / Desired Behavior / Question
The returned object contains the look up id for Managed metadata fields instead of the label name. This is a longstanding issue with SharePoint REST endpoint which Microsoft has not fixed yet but there are some workarounds to this problem.
![image](https://user-images.githubusercontent.com/9658606/48282572-5c358100-e45a-11e8-80a8-73371ac357fc.png)

Workarounds are discussed over this [StackExchange post](https://sharepoint.stackexchange.com/questions/119096/can-i-use-expand-to-get-managed-metadata-column-values).

**Comment by koltyakov** [comment]
Unfortunately, it can't be in the library. This is REST API behaviour. But you can uservoice for it [here](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/10503294-fix-the-rest-api-to-return-the-value-and-not-the-i).

As a workaround `renderListData` or `renderListDataAsStream` methods can be used.

**Comment by unnieayilliath** [comment]
@koltyakov  Thanks for pointing me to renderListData , I had already up-voted the user voice , but it's been years idk why this can't be fixed at REST API

**Comment by patrick-rodgers** [comment]
Going to close this as answered. If the conversation needs to continue please _reopen_ the issue so we can assist. Thanks!
