### ISSUE TITLE
IE Out of Stack Error

### ISSUE THREAD

**Issue by paigeflourin** [pnp/pnpjs#360]
### Category
- [ ] Enhancement
- [x ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Expected / Desired Behavior / Question

i raised a question just a few days ago and I managed to get it working thanks to this thread

https://github.com/pnp/pnpjs/issues/356#issuecomment-437262125

> but now when i was working on the project suddeny it doesnt load in IE again. i have this error:
> [SPLoaderError.loadComponentError]:
> ***Failed to load component "7616bc1f-6a77-48e6-a550-c41c9fca3c37" (QnAListWebPart).
> Original error: ***Failed to load entry point from component "7616bc1f-6a77-48e6-a550-c41c9fca3c37" (QnAListWebPart).
> Original error: Error loading https://component-id.invalid/7616bc1f-6a77-48e6-a550-c41c9fca3c37_0.0.1
>  Out of stack space
> 
> ***INNERERROR:
> ***Failed to load entry point from component "7616bc1f-6a77-48e6-a550-c41c9fca3c37" (QnAListWebPart).
> Original error: Error loading https://component-id.invalid/7616bc1f-6a77-48e6-a550-c41c9fca3c37_0.0.1
>  Out of stack space
> ***CALLSTACK:
> Error
>    at t._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-02.006/sp-webpart-workbench-assembly_en-us_587d44d4fe881d07cae5c73c88d6ab19.js:271:16308)
>    at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-02.006/sp-webpart-workbench-assembly_en-us_587d44d4fe881d07cae5c73c88d6ab19.js:271:15844)
>    at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-02.006/sp-webpart-workbench-assembly_en-us_587d44d4fe881d07cae5c73c88d6ab19.js:1166:22277)
>    at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-02.006/sp-webpart-workbench-assembly_en-us_587d44d4fe881d07cae5c73c88d6ab19.js:1166:16597)
>    at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-02.006/sp-webpart-workbench-assembly_en-us_587d44d4fe881d07cae5c73c88d6ab19.js:1166:12622)
>    at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-11-02.006/sp-webpart-workbench-assembly_en-us_587d44d4fe881d07cae5c73c88d6ab19.js:1166:71700)
>    at s (https://localhost:4321/dist/qn-a-list-web-part.js:32220:8680)
>    at Anonymous function (https://localhost:4321/dist/qn-a-list-web-part.js:32220:8827)
>    at a (https://localhost:4321/dist/qn-a-list-web-part.js:32220:27451)

### Steps to Reproduce

I have added  imports for ie11 polyfills;

import "@pnp/polyfill-ie11";

as per my code: https://github.com/paigeflourin/test 

there are configursations needed but given that the webpart doesnt load in ie, i dont think those are needed to be provided.

**Comment by patrick-rodgers** [comment]
I cloned your test repo you linked above and could not duplicate this error while running gulp serve. Can you provide any additional details? I am also not entirely sure the pnp libraries are causing a stack exception, more folks I think would be reporting that.

**Comment by patrick-rodgers** [comment]
Going to close this due to lack of activity, please do _reopen_ should you need to continue the conversation. Thanks!
