### ISSUE TITLE
Version Differences Question

### ISSUE THREAD

**Issue by gbminnock** [pnp/pnpjs#361]
### Version   1.1.4   
Please specify what version(s) of SharePoint you are targeting: [    SPO    ]

Hi,

I am retrieving version history using @pnp/sp and was wondering if I could get some guidance on comparing the versions for differences. Is this something I should do myself or is their a method for achieving this? 

I do see a field named MetaInfo - could that be used in this scenario?

Tks,
Gary

**Comment by koltyakov** [comment]
Hi @gbminnock,

There is no such a helper, however, versions difference can be easily achievable with some custom code, e.g.:

```typescript
import { sp } from '@pnp/sp';

const list = sp.web.lists.getByTitle('Projects');
list.items.getById(3).versions.get()
    .then(versions => {
        return versions.map((current, i) => {
            return i === 0
               ? current
               : deepDiff(current, versions[i - 1])
        });
    })
    .then(changes => console.log(changes));

function deepDiff(obj1: any, obj2: any): any {
    let difference = {};
    // Implementation
    return difference;
}
``` 

`deepDiff` implementation can be reused from some 3rd party, I believe there should be something in `lodash`.

**Comment by gbminnock** [comment]
Ok thanks!
