### ISSUE TITLE
Fields Endpoint returning: "Value cannot be null for parameter name "type"" 

### ISSUE THREAD

**Issue by simkessy** [pnp/pnpjs#363]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    **3.0.10**    ] **(I know it's the old version, pretty sure that's not the problem however)** 

Please specify what version(s) of SharePoint you are targeting: [     **2016**    ]

I'm trying to get a lists fields in a custom JS application. It's failing when I make the call through the app but when I do it in the console it works fine. If I take the request URL and paste into the browser I get results back as well. 

I've looked at the two requests and there's nothing different other than the `Request Headers accept property` between when it's called in app vs console

![image](https://user-images.githubusercontent.com/5871660/48441800-45847800-e741-11e8-8ecd-4de3c3ffc44e.png)
At the start of my application however I run: 
```
$pnp.setup({
    sp: {
        headers: {
            Accept: "application/json; odata=verbose"
        }
    },
    defaultCachingStore: "session", // or "local"
    defaultCachingTimeoutSeconds: 30,
    globalCacheDisable: false, // or true to disable caching in case of debugging/testing
    enableCacheExpiration: true, // added in 2.0.8
    cacheExpirationIntervalMilliseconds: 1000 // added in 2.0.8
});
```

**Comment by koltyakov** [comment]
`3.0.10`, @simkessy, man, seriously? Time to upgrade! ;)

Can it be that you mixing `Accept` header in upper and lower case?

As, if to provide:

```json
sp.setup({ sp: { headers: {
  Accept: "application/json; odata=verbose" // <-- Upper
}}});
//... some other place
sp.setup({ sp: { headers: {
  accept: "application/json; odata=nometadata" // <-- Lower
}}});
```

you may end up with `application/json; odata=verbose, application/json; odata=nometadata`.

**Comment by simkessy** [comment]
> 3.0.10, @simkessy, man, seriously? Time to upgrade! ;)

Yea I know, client doesn't want to upgrade dependencies just yet :( 


I tried updating the setup: 

```
$pnp.setup({
    sp: {
        headers: {
            accept: "application/json; odata=nometadata"
        }
    }
});
```

But I just end up with ` accept: "application/json; odata=nometadata,  accept: "application/json; odata=nometadata"`

and it still failed.

Could there be a SharePoint 2016 setting that's conflicting?

**Comment by simkessy** [comment]
Yea, removing the header overrides in the setup didn't help.

**Comment by simkessy** [comment]
So what I've observed is that in SharePoint 2013, in order to get Pnpjs to work we have to set: 

`odata=verbose` 

However in 2016, most of the default calls are using `odata=nometadata`. I can't find a way to force SharePoint 2016 to return `odata=verbose` for my rest calls and pnp.setup doesn't always seem to work. 

I have to handle this in my application somehow because the result of a call is not different between environments. For example: 

I have to do something like this for choice fields: `_.get(f.Choices, "results", f.Choices)`  

Simplest solution would be to force 2016 odata headers buuut, then it's verbose and results in longer / larger payloads which isn't ideal as well i guess.

**Comment by patrick-rodgers** [comment]
The old version sp-pnp-js is no longer supported. Would ask that you please update to the newer libraries and see if the issue is resolved. If not, we can look to see what is wrong. Thanks.

**Comment by patrick-rodgers** [comment]
I see you have left a thumbs down and closed the issue. That is unfortunate, but please understand we [clearly communicated](https://github.com/sharepoint/pnp-js-core#this-library-is-deprecated) that the old library is deprecated, and allowed for a 6 month period where we supported both libraries in parallel to help with transitioning. Please do update the application and we are very happy to try and help; however, we cannot support things indefinitely.

Look at it this way: IF we loaded up the old library, got setup to do testing, and found an issue then what? Would the expectation be to do a fix and release for a deprecated library? I hope you can see it from our side at least a bit.

Hope you continue to use the libraries and participate in the community.
