### ISSUE TITLE
BreakRoleInheritance on ListItem

### ISSUE THREAD

**Issue by enti333** [pnp/pnpjs#364]
### Category
- [ ] Enhancement
- [ ] Bug
- [X ] Question
- [ ] Documentation gap/issue

Hello. I want to ask how can I use BreakRoleInheritance on ListItem and set custom permission for specific user. 
Thank you very much.

**Comment by koltyakov** [comment]
Hi @enti333,

Copying an answer sample from another [question ticket](https://github.com/SharePoint/PnP-JS-Core/issues/804#issuecomment-387339458);

```typescript
import { sp } from '@pnp/sp';

(async () => {

  // List, item, file or folder instance
  const list = sp.web.getList(`/sites/site/Lists/List`);
  const item = list.items.getById(3);

  // Break role inheritence for unique permissions
  await item.breakRoleInheritance(false); // Method receives params

  // Get user/group proncipal Id
  const { Id: principalId } = await sp.web.currentUser.select('Id').get();
  // Get role definition Id
  const { Id: roleDefId } = await sp.web.roleDefinitions.getByName('Edit').get();

  // Assigning permissions
  await item.roleAssignments.add(principalId, roleDefId);

  console.log(`Done`);

})().catch(console.log);
```

Also, this [docs article](https://pnp.github.io/pnpjs/sp/docs/permissions/) might be helpful.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Please _reopen_ if you have additional questions. Thanks!

**Comment by enti333** [comment]
Thank you very much koltyakov. It is working without any problem....I am sorry I didn't find it in documentation...

**Comment by Nagarajan1605** [comment]
Hi  koltyakov,
 $pnp.sp.web.lists.getByTitle("testlist").items.getById(8).get().then(function(results){
results.breakRoleInheritance(false);
});

After executing this i want to assign permission for this individual item. Need to assign some groups and individual users. Could you please assist me.

**Comment by Nagarajan1605** [comment]
Hi koltyakov,

I have a doubt if person has only Edit with contribute permission on the site level. Using this "Edit" permission how user can break the item permission. As of now user who is having "Full Conrol" only can break the item permission. In this scenario user is having only Edit permission but needs to break the item permission. 

Could you please assist me. 

Thanks

**Comment by koltyakov** [comment]
Sure you have to have a proper permissions level.
