### ISSUE TITLE
Is it possible to set the http headers accept odata=nometada on batch requests?

### ISSUE THREAD

**Issue by simkessy** [pnp/pnpjs#365]
### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   latest      ]

Please specify what version(s) of SharePoint you are targeting: [    online     ]

I'm making a batch call and the http header request is **"accept: application/json"** my call is about 7s long due to the number of columns and items being returns (17mb). 

I'm hoping if there's a way to set the batch request to run under `odata=nometadata` it might improve performance.

**Comment by koltyakov** [comment]
Hi @simkessy,

Yes, possible, via `.configure` method:

```typescript
import { sp } from '@pnp/sp';

const list1 = sp.web.lists.getByTitle('List1');
const list2 = sp.web.lists.getByTitle('List2');
const data: any = {};

const batch = sp.web.createBatch();
const headers = {
    headers: {
        Accept: 'application/json;odata=nometadata'
    }
};
list1.configure(headers).items.inBatch(batch)
    .get().then(items => data.items1 = items);
list2.configure(headers).items.inBatch(batch)
    .get().then(items => data.items2 = items);

batch.execute().then(_ => console.log(data));
```

![image](https://user-images.githubusercontent.com/7816483/48533457-a46afe00-e8b5-11e8-8271-73a1ffe61ff6.png)

**Comment by simkessy** [comment]
Hey I gave it a shot: 

```
        let result = null;

        let web = new pnp.Web(mysiteurl);
        let batch = web.createBatch();

        const headers = {
            Accept: "application/json;odata=nometadata"
        };

        web.lists
            .getByTitle(listName)
            .configure({ headers })
            .items.top(5000)
            .select(selectFields.join())
            .expand(expandFields.join())
            .filter("Active eq 1")
            .inBatch(batch)
            .get()
            .then(function(data) {
                result = data;
            });

        return batch.execute().then(function() {
            return result;
        });
```
But my payload looks like this: 
```
--batch_3c74b8d1-78b2-48e1-94b5-b307f58e34ab
Content-Type: application/http
Content-Transfer-Encoding: binary
```

**Comment by patrick-rodgers** [comment]
That's fair, reopening as a documentation gap.

**Comment by patrick-rodgers** [comment]
Closing this with docs [update complete](https://github.com/pnp/pnpjs/blob/dev/packages/odata/docs/queryable.md#configure)
