### ISSUE TITLE
@pnp/sp-taxonomy - Support JSOM method termStore.getTermsById(termIds: Guid[])

### ISSUE THREAD

**Issue by FranckyC** [pnp/pnpjs#366]
### Category
- [x ] Enhancement

Currently, in the [react-search-refiners](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-search-refiners) SPFx sample, I use JSOM to retrieve multiple terms by their ids at once via the `termStore.getTermsById(termIds: Guid[])`. It would be nice to get the counterpart in pnpjs.
For now, if I want to do the same thing, I would batch multiple queries with single id which is not very efficient.

Thanks!

**Comment by FranckyC** [comment]
That was quick! Thanks @patrick-rodgers, you're awesome ;)

**Comment by patrick-rodgers** [comment]
It is pretty easy to add a method :) we just need to know there is a need
