### ISSUE TITLE
Implement more caching strategies, including stale-while-revalidate

### ISSUE THREAD

**Issue by alirobe** [pnp/pnpjs#371]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Expected / Desired Behavior / Question
I'd like to be able to use a "stale-while-revalidate" type cache strategy with PnP's useCaching. This would provide the cached response, but then update the cache in the background **every time**. The user is always only a page refresh away from an updated response, but rendering is not delayed. This would be  similar to how workbox caches content (described here: https://developers.google.com/web/fundamentals/instant-and-offline/offline-cookbook/#stale-while-revalidate). Ideally it would also have a sliding expiry, and operate inBatch. 

I left this ticket name open, as you may find other caching strategies in the workbox offline cookbook interesting to discuss... (e.g. background sync)

I could potentially assist in writing this if needed, but I'd need some pointers on getting started as I'm not familiar with the project or how caching is handled, and when it comes to caching, it's easy to damage things in untestable ways...

**Comment by patrick-rodgers** [comment]
This is an interesting idea, but would be better as something that lives outside the library. As you mentioned there are many different caching patterns and lots of different preferences - and it wouldn't make sense to internalize them all to the library. The pattern we chose is simple and always provides the latest data until expiration which seems to work well for most people. It also fits into the request pipeline nicely. Implementing other strategies would likely require at least partial reworking of the pipeline, updates to batching, and probably other changes that aren't as obvious. And if we did it for this one then do we do it for the next, and the next after that?

My suggestion would be to write this up as a library and share it with the community, perhaps demo it on an upcoming call? Sound good?

**Comment by alirobe** [comment]
I'm sorry, but I don't have the time or skills to maintain a separate caching library for public consumption.

I was hoping to be able to make a simple pull request if pointed in the right direction, or use a third party caching library for myself. 

I felt that this particular pattern would be very handy for a _lot_ of scenarios, and not just for the product I work on, which is why I brought it up. It's the main pattern I like to use. It might have been an error to make the title too broad!

**Comment by patrick-rodgers** [comment]
Here is an implementation that achieves the caching strategy you are interested in, without any updates to the library. In exploring this I also took a look at ways to expand how we do caching and it is more work than I think is worth it for the reasons above. I recognize that it does require wrapping each request, but that isn't so bad on the whole.

### Implement caching helper method:
> Don't call usingCaching just apply the helper method
```TypeScript
const map = new Map<string, any>();

async function staleWhileRevalidate<T>(key: string, p: Promise<T>): Promise<T> {

    if (map.has(key)) {

        // In Cache
        p.then(u => {
            // Update Cache once we have a result
            map.set(key, u);
        });

        // Return from Cache
        return map.get(key);
    }

    // Not In Cache so we need to wait for the value
    const r = await p;

    // Set Cache
    map.set(key, r);

    // Return from Promise
    return r;
}
```

### And here is the usage
> Don't call usingCaching just apply the helper method
```TypeScript
// this one will wait for the request to finish
const r1 = await staleWhileRevalidate("test1", sp.web.select("Title", "Description").get());

console.log(JSON.stringify(r1, null, 2));

// this one will return the result from cache and then update the cache in the background
const r2 = await staleWhileRevalidate("test1", sp.web.select("Title", "Description").get());

console.log(JSON.stringify(r2, null, 2));
```

I have also added this as an article in the docs since others may also be interested in ways to implement custom caching. Thanks for the idea.

**Comment by alirobe** [comment]
Love it! Thanks 🎉

**Comment by alirobe** [comment]
MI

**Comment by patrick-rodgers** [comment]
Added section to docs here: https://github.com/pnp/pnpjs/blob/dev/packages/odata/docs/caching.md#implement-custom-caching

**Comment by alirobe** [comment]
OK, i'll close this and create a PR when I actually do it. Nothing for you guys to do. Thanks! 👍
