### ISSUE TITLE
Teams in GA

### ISSUE THREAD

**Issue by simonagren** [pnp/pnpjs#372]
### Category
- [ X ] Enhancement
- [ ] Bug
- [ X ] Question
- [ ] Documentation gap/issue

@patrick-rodgers @koltyakov 
I'm starting to work with what Patrick built in the "Teams" for Graph, now that it's in GA.
Ok with you guys? :)

**Comment by patrick-rodgers** [comment]
Great!

**Comment by patrick-rodgers** [comment]
Closing this with merge of #373. Great work adding all that functionality, thank you!
