### ISSUE TITLE
Deployment pnpjs project to SharePoint Online

### ISSUE THREAD

**Issue by enti333** [pnp/pnpjs#382]
- [ ] Enhancement
- [ ] Bug
- [ X] Question
- [ ] Documentation gap/issue

I have maybe one simple question but I am not sure how to do that. I have check the documentation but I don't know what to do...
I have been using pnpjs in script editor web part on SharePoint online...I have referenced my JS files and also es5 pnp js files...Everything is working without any problem and with pnp I can do almost everything...
Now I want to start working with typescript and using pnpjs little more like professional. 

So I have 
1. Created new project in visual studio code
2. Run this code from terminal npm install @pnp/pnpjs --save ...install was successful 
3. Created test.ts file with code like this 
`import pnp from "@pnp/pnpjs";

pnp.sp.web.get().then(w => {

    console.log(JSON.stringify(w, null, 4));
});`

4. And now what? I need to use my code in NEW Form ...
Before that when I was using simple JS I just create script editor webpart ...uploaded js files to assets folder and in script editor I have add links to JS files...and Everything start to work...
But Right now I am not sure what to do....Where I need to upload node_modules or my TS/JS files ...how to referenced it on new form...

Thank you for helping me with this base problem of implementation.

**Comment by koltyakov** [comment]
@enti333, this is a generic development question rather than related to PnPjs library one.
Any materials related how to bundle modern JS/TS to ES5 will work. There is nothing specific here in regards to the library. Please check [docs' deployment section](https://pnp.github.io/pnpjs/documentation/deployment/).
If you still on a road on the transition from legacy to modern and SPFx, and going delivering JS code for classic part of SPO in a classic way but with modern toolchains and frontend development approaches, my suggestion is to try [SPPP](https://github.com/koltyakov/generator-sppp) generator (it scaffolds a project ready to go with PnPjs, TypeScript, Webpack and automation tasks).
However, for a long strategy, I'd recommend investing in learning SPFx.

**Comment by enti333** [comment]
Hello. Thank you very much for your help. There is one big problem with SPFX or maybe two, three. 
1. Ok I can build SPFX webpart and use it in classic design mode ...The loading of any simple webpart is too long...For example I have List with 20 fields...I will create SPFX webpart with these fields because I want to use some custom logic...I will add this webpart to SharePoint NEW Form via Add Webpart... When user press button NEW my SPFX webpart will be loaded but many timed there is loading images for more then 5 seconds...and this is only simple scenario...(I used react office fabric tools)
2. I am not able to use SPFX webpart when New Experience is loaded in NEW\Edit\Display forms ...I just need to overwrite the standard design because I want to use in these forms custom logic... This is not possible also with SharePoint Framewrok extensions... Ok maybe I can use PowerApps but I don't want to us power apps my logic is two much complicated...
3. Ok So I try it another way....With powershell I just rewrite New\Edit\Display form url ...Then I create new app page and insrtet there my SPFX webpart. UrlLinks to New\Edit\Display form are setup to my new app page with my custom logic....Looks nice....But the problem is that I don't know why but in SharePoint online you can not use ListId or ID as a parameter in URL...There is an error (noCommand or something like this....But SharePoint automatically in Edit and Display form custom URL add  these parameters to URL....I need these parameters because from that I know what to load in my custom inputs....
Hmm...Maybe you have found some solution for these problems but for me is right now better to use classic development because I know it will work... But I will be very thankful if you have maybe some help for me how to use SPFX webparts in list forms.... 

So I am going to test SPPP Generator ... my biggest and maybe only problem with my development is that I don't know what I need to upload to SharePoint online so everything will work with TS...But I will check SPPP.  
Again thank you very much for any help

**Comment by patrick-rodgers** [comment]
Going to close this thread as the questions regarding the pnpjs libraries seem answered. You can always checkout the [SharePoint Developer Documentation](https://aka.ms/spdev-docs) for general development questions and the [MS Tech Community for Sharepoint](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) is a great place to ask for guidance from the community. Thanks!
