### ISSUE TITLE
 Can't add Select to getItemsByCAMLQuery

### ISSUE THREAD

**Issue by CPritch** [pnp/pnpjs#383]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

To be able to add an optional Select parameter in the same format as Expand. There is an inherent issue with SP that we need to work around.

- All Views are filtered by CAML
- Therefore we must use get items by CAML 
- This REST endpoint is broken and doesn't work with expand (Why is it even on there if it doesn't work?) 
- Therefore we must hack around with Select: FieldValueAsText/Project

#### Observed Behavior

There is no way of passing a Select prop.

#### Steps to Reproduce

Try to use GetItemByCAML and expand in any way. It simply doesn't work for lookups. I think this is a limitation of the broken REST rather than PNP. PNPJS is missing a Select parameter regardless.

**Comment by patrick-rodgers** [comment]
I don't entirely follow what you are asking for. You seem to indicate that there is a bug in the REST service itself? If so we can't do much about that.k Are you saying we need to include a select option in the getItemsByCAMLQuery method? I thought the select was handled by the viewfields collection in the xml, no?

**Comment by CPritch** [comment]
@patrick-rogers

More venting that the expand bug has existed on that endpoint for a long time.

Secondly, no. ViewFields has no influence on what data is returned. If you need to select a property such as a 'field value as text' you need to add a $select parameter.

**Comment by CPritch** [comment]
I will have a look once I get home so I can crawl the typings for that feature. 

I would guess it's not fit for the described issue here though. List Views always save using XML, so it's either come up with our own view management system or to get CAML working.

We're in the process of writing a CAML to oData converter but until then we can't mix CAML views and oData filters.

I have worked around the problem for now by making a second request when this would be solved by simply letting me add the Select query param to that endpoint.

**Comment by CPritch** [comment]
As an update I have looked over RenderListData. I'm not sure how a totally detached rendering function is supposed to help me select lookup fields as values or expand lookups from a list.

There has to be a CAML to Odata converter implemented or else no one will move away to odata based systems. Saving everything modified as ListXml and then providing no way to mix this with odata means  that one of three things is being forced on the SP devs:

1. To build their own oData view management
2. To build their own CAML to oData converter to mix ViewXml and Odata
3. To use depreciating old CAML based systems

I propose No. 2 since I seriously doubt any SP View infrastructure is going to change any time soon. There has to be some real push from somewhere to open-source this module and not let every SP Dev hoard it for themselves.

**Comment by patrick-rodgers** [comment]
I am not sure why renderListData doesn't work for you. The below example take a view from a list that has a lookup field and includes the lookup field's values from the references list in the view. It loads the xml of the view and uses that xml to retrieve items which match what is shown in the view. No expand/select needed.

```TypeScript
const list = sp.web.lists.getByTitle("LookupList");

const viewData = await list.defaultView.select("HtmlSchemaXml").get<{HtmlSchemaXml: string}>();

const r = await list.renderListData(viewData.HtmlSchemaXml);

console.log(JSON.stringify(r, null, 2));
```

**Comment by CPritch** [comment]
> As an update I have looked over RenderListData. I'm not sure how a totally detached rendering function is supposed to help me select lookup fields as values or expand lookups from a list.

I should've been more clear as renderListData is almost there. It's fine if I want just the current values in a slice of view but it certainly is closer to what's necessary to get it working. I'm investigating renderListDataAsStream as this is how it appears the OOTB Modern has managed to get ListViews working.

1. I need to render Pages of view content - This is a p_ID query param (still poking the function to get this set, thinking its the second override params of renderListDataAsStream)
2. getNext and other functions appear to not be exposed as I guess because of the massive differences here.
3. This definitely seems like the right route so thanks for pointing me in the direction of the right area.

I would reiterate that It's a little frustrating that as soon as I wan't to implement anything involved with OOTB views I'm immediately dragged back to a system that is well over a decade old at this point. 

Is there a plan to update List Views to be saved as oData rather than CAML? I would love to implement a "top=" paging system but don't want to implement my own view saving or to build a CAML to oData converter. Especially since there are so many great oData generators.

**Comment by patrick-rodgers** [comment]
Hi @CPritch -

This issues list is for topics dealing with the pnpjs libraries and not the correct forum for general product discussion. Would recommend [UserVoice](https://sharepoint.uservoice.com/) for that where you can request changes.

We have within this library made the choice to build our paging system around the odata methods as that is the preferred way to do it. It sounds like you have a specific requirement to use the view xml to render your data and would encourage you to use the newer render list data methods over the getItemsByCAMLQuery. At this point I think the questions in this thread have all been answered, please let us know if we can close the thread or if you have additional questions.

Thanks!

**Comment by CPritch** [comment]
So after much investigation I have come up with a solution. Your pointer to renderListData ended up being useful as I have ended up using this to figure out totalling of custom dynamic views. I still see this as an issue with pnp not exposing the any query parameters available to getItemsByCaml. I ended up having to use direct endpoints.

In my investigations I discovered MS's own ListView solution uses the RenderListDataAsStream endpoint! There's no odata filters exposed to that anyway. The filtering hobbles together the old filterValue1 etc... query parameters. There's not even mix max date range filtering, but I look forward to changes here early 2019 from the sounds of it on Uservoice.

I do agree that the odata endpoints should be used as I want to use them. Luckily using the getItems endpoint with the CAML params I can get paging through $top & $skip. The key magic though is the second request to the renderListDataAsStream endpoint. You can actually get that to return totals for modified CAMLQueries from a view such as custom filtering allowing for page numbering and proper sums and view counts. All with mixed in custom filtering controls. Unfortunately not odata filtering for now.

Again, would've been made a lot simpler but I encountered the following in pnp:

- renderListDataAsStream/renderListData doesn't return hasNext or getNext or accept any page tokens.
(MS achieves this with one call to this endpoint and then repeated calls on scroll bottom with a view param)
- getItemsByCaml has no query params or top or obeys xml paging at all despite being the getItems endpoint

I'm more than happy to submit I PR in the future if this isn't on the books any time soon. It would help us integrate better with pnp.
