### ISSUE TITLE
The request uses too many resources (Only Add 15 records then failed)

### ISSUE THREAD

**Issue by samsiddiquiz** [pnp/pnpjs#384]
I am working O365 and getting error after 15 items added using Pnp Batch.
Please Help?
I pasted code:
```
const batch = pnp.sp.createBatch(Items.length);
        const listname = pnp.sp.crossDomainWeb(RateCardDashboard.appWebUrl(), RateCardDashboard.hostWebUrl()).lists.getByTitle(FinanceRateCardListname);
        for (var i = 0; i < Items.length; i++) {
            var items = {
                RateCode: Items[i].RateCode,
                Heading: Items[i].ProductName,
                Description: Items[i].Description,
                Rate: Items[i].RateVatable,
                Discount: Items[i].DiscountRate,
                DiscountPrice: Items[i].DiscountValue,
                RateNonVatable: Items[i].RateNonVatable,
                VatRate: Items[i].VatRate,
                VatValue: Items[i].VatValue,
                TotalPrice: Items[i].TotalPrice,
            };
            listname.items.inBatch(batch).add(items).then(function (data) {
                console.log("Success FinanceRateCardListname", i);
            }).catch(function (error) {
                console.log("Error FinanceRateCardListname", i, "  ", error);
            });
        }
        batch.execute().then(function () {
            $.alert({
                title: 'Success!',
                type: 'green',
                icon: 'fa fa-check',
                content: 'All Correct Data Saved.',
            });
            console.log("Success BulkUpload");
        }).catch(function (error) {
            $.alert({
                title: 'Error!',
                type: 'red',
                icon: 'fa fa-warning',
                content: 'Something went wrong.',
            });
            console.log("Error BulkUpload", error);
        });
```

![image](https://user-images.githubusercontent.com/32498803/49011320-daeb2780-f197-11e8-85ae-b7b5ec4f368b.png)

**Comment by patrick-rodgers** [comment]
Can you try with a smaller batch size and see if the issue is solved? I don't believe there is anything we can do in the library to resolve this. I am not aware of a hard limit on requests/batch, if you are please let me know perhaps we can do what we did in the graph library and handle that.

**Comment by samsiddiquiz** [comment]
> Can you try with a smaller batch size and see if the issue is solved? I don't believe there is anything we can do in the library to resolve this. I am not aware of a hard limit on requests/batch, if you are please let me know perhaps we can do what we did in the graph library and handle that.



> Can you try with a smaller batch size and see if the issue is solved? I don't believe there is anything we can do in the library to resolve this. I am not aware of a hard limit on requests/batch, if you are please let me know perhaps we can do what we did in the graph library and handle that.

@patrick-rodgers I tried to add 14 items with (20k Batch size ), issue is resolved, but i have 200+ item what should i do ? i used sharepoint rest api(without pnp library) i update 999 items in single call it worked, but pnp i am getting error? any help please?

**Comment by koltyakov** [comment]
On backstage, PnPjs crafts the batch multibody and sends REST request. I believe the package size makes sense, update one field for many items package can be smaller in size than creating items with huge payloads. PnPjs adds no "heaviness" to the batches.
For `add` operations, I usually split physical batched to contain less than 100 elements.
Also, `EntityTypeFullName` should be passed as a second parameter to add method.
[This approach](https://github.com/SharePoint/PnP-JS-Core/issues/668#issuecomment-352986262) might be helpful.

**Comment by samsiddiquiz** [comment]
> On backstage, PnPjs crafts the batch's multibody and sends ordinary REST request. I believe the multipart package body size makes sense, update one field for many items package can be smaller in size than creating items with huge payloads. Wherein, PnPjs adds no "heaviness" to the batches.
> 
> For `add` operations, I usually split physical batched to contain less than 100 elements.
> 
> Also, `EntityTypeFullName` should be passed as a second parameter to add method.
> 
> [This approach](https://github.com/SharePoint/PnP-JS-Core/issues/668#issuecomment-352986262) might be helpful.

@koltyakov Thank you for your response, your code is hard to understand for me, can you simplify or explain for me please? or can you tell me batch limit size or element length for single batch?
Thanks in advance, Sorry for poor English.

**Comment by patrick-rodgers** [comment]
You can see a simpler implementation of the same idea @koltyakov shared [here](https://pnp.github.io/pnpjs/sp/docs/items/#add-multiple-items). We can't tell you a hard limit as it doesn't (do far as I know) exist. It is based on some calculation of the work required on the server. In the Add Multiple Items example you can see the usage of the getListItemEntityTypeFullName method to cut the number of required calls in half which should help.

If you are adding 200 items once that I would just write a loop, add them in batches of say 10, and be done with it. If you are adding 200 items often that might be an opportunity to examine your design and see if it can be made more efficient. I.e. what are you doing with that information? For example if it is say logging data can you add all 200 items into a note field as JSON in a single item? Not sure

**Comment by samsiddiquiz** [comment]
@patrick-rodgers thank you for your quick response, Brother i have task to dumb Excel sheet row data into list, i would be N number of rows, for better efficiency  i am using batching, but after 15 calls getting error in batch. please help me :)

**Comment by koltyakov** [comment]
@samsiddiquiz,
 
The main ideas of the sample:

- Use `EntityTypeFullName` for mass updates
- Split batches down to a size which works for the payloads
- Recursion can arrange a queue of batches call
- Results and errors should be collected separately

`processBatch` function implementation can be just reused, there are comments for important parts inside the function too. Usage is straightforward: ```await processBatch(list, entityType, data);```. `data` object should have a specific format.

**Comment by samsiddiquiz** [comment]
@koltyakov  How we get batch size ? and which size will work for payloads? when EntityTypeFullName is constant ? why we call multiple for getting same results? 
I am asking, please guide me.

**Comment by koltyakov** [comment]
So many questions... Sign...

> How we get batch size? and which size will work for payloads?

By reducing the number of operations in a batch which works for a specific payloads combination.
If 100 operations in a batch can be proceeded with the backend, reducing to 50 and so on.

> when EntityTypeFullName is constant?

An entity is the same for the list.

> why we call multiple for getting same results?

Can you paraphrase or elaborate?

**Comment by CPritch** [comment]
Clearly whatever @samsiddiquiz is doing is exceeding the length of the request body for a batch request. I'm guessing one of those values being saved adds up to a lot, my money's on 'Description'.

@samsiddiquiz I suggest you read up on 'Sequential Batch Processing.' You could argue that it could be implemented in the library for simplicity but there's way too many variations on implementing this and different goals for doing so.
