### ISSUE TITLE
IRefiner.Entries should be an array

### ISSUE THREAD

**Issue by cslecours** [pnp/pnpjs#385]
A regression following #352

IRefiner.Entries was an array before.

Now : 
`export interface IRefiner {
    Name: string;
    Entries: { RefinementCount: string; RefinementName: string; RefinementToken: string; RefinementValue: string; };
}
`

Before : 
` { Name: string; Entries: { RefinementCount: string; RefinementName: string; RefinementToken: string; RefinementValue: string; }[]; }`

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  1.2.6       ]

Please specify what version(s) of SharePoint you are targeting: [    online     ]

**Comment by bcage29** [comment]
@pljfdi in the react-search-refiners sample it causes a bug. It is expecting that type to be an array. In the [SearchService](https://github.com/SharePoint/sp-dev-fx-webparts/blob/master/samples/react-search-refiners/spfx/src/services/SearchService/SearchService.ts) file line 206

**Comment by cslecours** [comment]
In SharePoint Online, Entries is an array.

![image](https://user-images.githubusercontent.com/3374584/49045193-30c2ce00-f19e-11e8-8652-243abeb1386a.png)

**Comment by pljfdi** [comment]
@bcage29 Thanks for that, and sorry for the mistake. 
The interface is literally a copy/paste of the original code; and somehow, I messed that up when I created the pull-request.
