### ISSUE TITLE
Cannot find module '@microsoft/sp-dialog'. 

### ISSUE THREAD

**Issue by Mike-tech** [pnp/pnpjs#387]
Hello

Just spin up new SPFx project and i am unable to use  BaseDialog, IDialogConfiguration. The last time i used this i didn't have any issue.

I tried installing using both "npm install @microsoft/sp-dialog" "npm install --save-dev@microsoft/sp-dialog" but this seems to break the project and i just get blank page. 

Can you please let me know how best to wake this guy up. If this is no longer supported then what is an alternative. 

Thanks

**Comment by koltyakov** [comment]
Hi @Mike-tech,

You probably have a typo - missing space between --save-dev flag and package name.
However, `@microsoft/sp-dialog` module has no relation to PnPjs at all. ;)

**Comment by Mike-tech** [comment]
Oh sorry i should be targeting the SPFx github not PnPjs. I do have space on my actual command line. 

Ok cheers, i''ll chase this up with the right people...

Thanks

**Comment by Mike-tech** [comment]
Apologies PnPjs team for hijacking your platform and targeting wrong audience. 

Since i've already made the mistake i thought i might as well answer the question here: 

The answer is to run the install command as: **npm i @microsoft/sp-dialog**. Found it here [https://www.npmjs.com/package/@microsoft/sp-dialog](https://www.npmjs.com/package/@microsoft/sp-dialog).

Not sure what the difference between npm i and npm install, which i used initially???

Sorry team!
