### ISSUE TITLE
Issue saving a user field value

### ISSUE THREAD

**Issue by raymondlittle100** [pnp/pnpjs#39]
### Category
- [ ] Enhancement
- [x ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  1.0.3       ]

### Expected / Desired Behavior / Question
Ability to save/update single select user fields

### Observed Behavior
I have tried numerous ways but either the value isn't respected or I get an error back

### Steps to Reproduce
Use code to fetch the page then from the page fetch the list item. Once i have the list item batch up an array of ListItemFormUpdateValue objects. This all works fine for boolean, taxonomy, date and SLOT but I can't get it to work for user fields. 

I found some documentation around updating user fields at the link below but this doesn't seem to work
https://github.com/pnp/pnp/blob/dev/packages/sp/docs/items.md

I can fetch the value by using column name with 'Id', see below.
![image](https://user-images.githubusercontent.com/23637375/37207910-16eb771e-2397-11e8-84bf-7373d158fc9d.png)

If I try and update using 'KIRA_CP_ContentOwnerId' it gives me the standard SP error saying the field can't be found. If I try and use the actual field internal name 'KIRA_CP_ContentOwner' it never sets the value. I'm using the 'validateUpdateListItem' function on the list item

public savePageMetadata(pageListItem:Item): Promise<any> 
  {         
    return new Promise<any>((resolve) => 
    {          
//my list of objects to pass to the function
      let fieldValues = this.createItemUpdateValues();
      console.log(fieldValues);
      pageListItem.validateUpdateListItem(fieldValues).then((updateResult) => 
      {
        //check if there are any errors
        let fieldErrors = updateResult.filter(itemUpdate => itemUpdate.HasException);
        //if we have errors
        if(fieldErrors != null && fieldErrors.length>0)
        {
          console.log("savePageMetadata Errors");
          console.log(fieldErrors);
        }
        else
        {
          console.log("savePageMetadata ok");
          //otherwise ok
          resolve();
        }
      }).catch((error) =>
      {
        console.log(error);
      });
    });
  }

**Comment by patrick-rodgers** [comment]
Did you see the section at the bottom on [resolving field names](https://github.com/pnp/pnp/blob/dev/packages/sp/docs/items.md#resolving-field-names)? Could be something with that maybe. Setting the Id should work so long as the name is right. What version of SharePoint are you targeting?

**Comment by raymondlittle100** [comment]
I haven't tried the link you sent so I will give it a go. I assumed since I was able to fetch the data using the field name, KIRA_CP_ContentOwnerId, and get a valid value back I should be ok to use this in the update

**Comment by raymondlittle100** [comment]
Hi,

Just tried the script you suggested, see code and result below. I'm targeting O365

Code
![image](https://user-images.githubusercontent.com/23637375/37393732-d390f6ca-2769-11e8-9a2e-fcbdf2f6c6cd.png)

Debugging result
![image](https://user-images.githubusercontent.com/23637375/37393747-e05e41dc-2769-11e8-9e1a-fed4d95a0647.png)

**Comment by patrick-rodgers** [comment]
Did you try and update with that entity property name as the field name with success?

**Comment by patrick-rodgers** [comment]
If you try in a different list with a different user field do things work? This is starting to seem like something with this list or configuration, and I am unable to duplicate any issues with setting user fields as you describe.

**Comment by raymondlittle100** [comment]
Just tried again on a new team site with both an OOTB SP list and then in the site pages library and it didn't work. For the list I created a new list, added a new column called 'UserOne', added a new item, updated code to fetch the item, checked the entity property name which was UserOne, called then 'validateUpdateListItem' and got no save errors. When i checked the item it was updated but the user field was blank.

I followed the same process for doing this in the site pages library except i added the new field to the wiki content type and set the new pages as this first. As with the list the updated date changed but the user stayed the same.

Sample code here
https://github.com/raymondlittle100/RL-Test-SPFx-WebParts/tree/master/PnPTesting

**Comment by patrick-rodgers** [comment]
After doing a little more digging it appears that [lookup fields cannot be updated](https://social.technet.microsoft.com/Forums/en-US/5e67dc3d-c808-49ee-9aab-383a5cea5bce/sharepoint-angulr-rest-api-update-file-item-userd-field-property?forum=sharepointdevelopment) with ValidateUpdateListItem. I was testing with update, which is my fault as I missed initially your use of ValidateUpdateListItem.

That seemed lame so I kept digging and found [this post](https://stackoverflow.com/questions/31649783/sharepoint-csom-how-to-update-person-or-group-field-using-validateupdatelistite). The below code does work for me:

```TypeScript
const j = await sp.web.lists.getByTitle("UserFieldList").items.getById(3).validateUpdateListItem([{
    FieldName: "User1",
    FieldValue: JSON.stringify([{ "Key": "i:0#.f|membership|person@tenant.com" }]),
},
{
    FieldName: "Title",
    FieldValue: "Test 3 - Updated 5",
}]);
```

Give that a try and you should be all set.

**Comment by raymondlittle100** [comment]
Aye perfect that works
