### ISSUE TITLE
Ambient const enums are not allowed when the '--isolatedModules' flag is provided

### ISSUE THREAD

**Issue by Oceanswave** [pnp/pnpjs#394]
Similar to https://github.com/OfficeDev/office-ui-fabric-react/issues/7110, using create-react-app 2.1.x with TS 3.1.6 and @pnp/sp 1.2.6, importing  { sp } from "@pnp/sp" results in the following error:

```
Type error: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.  TS1209

     6 |  * Page promotion state
     7 |  */
  >  8 | export declare const enum PromotedState {
       |                           ^
     9 |     /**
    10 |      * Regular client side page
    11 |      */

```

**Comment by Oceanswave** [comment]
Setting ```"skipLibCheck": true``` in tsconfig.json resolves this error. Closing.

**Comment by Link631** [comment]
I have the same Problem with following imports:

import { sp, PrincipalSource, PrincipalType } from "@pnp/sp";

PrincipalSource.All and 
PrincipalType.User

SkipLibCheck is true, I need to set IsolatedModules to false to remove the Error, but its not what i want...
