### ISSUE TITLE
Error using getStorageEntity - Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by frnk01** [pnp/pnpjs#396]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.6]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

SPFX Version: 1.7.0

### Expected / Desired Behavior / Question
Get property from tenant properties in app catalog

### Observed Behavior
`Uncaught (in promise) TypeError: Cannot read property 'call' of undefined`

### Steps to Reproduce
Error when running getStorageEntity in SPFX extension (CommandSet)

```
  public async getConfiguration(): Promise<StorageEntity> {
    const configWeb: StorageEntity = await sp.web.getStorageEntity("PROPNAME");
    return configWeb;
  }
```

**Comment by frnk01** [comment]
@patrick-rodgers I did a complete reinstall and now it worked, but I think there is a typo in the documentation. Shouldn't it be `sp.web.getStorageEntitiy('prop')` and not `sp.getStorageEntity('prop')`?

[https://pnp.github.io/pnpjs/sp/docs/tenant-properties/](https://pnp.github.io/pnpjs/sp/docs/tenant-properties/)

**Comment by patrick-rodgers** [comment]
1) awesome things are working for you now.
2) yes, that is a typo, will get it updated. thanks for letting us know.

**Comment by patrick-rodgers** [comment]
Fixed via on-line editor so closing this. Thanks!
