### ISSUE TITLE
property of type is not assignable to string index type

### ISSUE THREAD

**Issue by johannes-z** [pnp/pnpjs#397]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: ["@pnp/sp": "^1.2.6"]

Please specify what version(s) of SharePoint you are targeting: [`not applicable`]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

I get errors when building my project using:

```
"@pnp/common": "^1.2.6",
    "@pnp/logging": "^1.2.6",
    "@pnp/odata": "^1.2.6",
    "@pnp/sp": "^1.2.6",
    "typescript": "^3.2.1",
```

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

```
ERROR in .../node_modules/@pnp/sp/src/types.d.ts
1349:5 Property 'Title' of type 'string | undefined' is not assignable to string index type 'string | number | boolean'.
    1347 |     Indexed?: boolean;
    1348 |     Required?: boolean;
  > 1349 |     Title?: string;
         |     ^
    1350 |     ValidationFormula?: string;
    1351 |     ValidationMessage?: string;
    1352 | }
ERROR in .../node_modules/@pnp/sp/src/types.d.ts
1350:5 Property 'ValidationFormula' of type 'string | undefined' is not assignable to string index type 'string | number | boolean'.
    1348 |     Required?: boolean;
    1349 |     Title?: string;
  > 1350 |     ValidationFormula?: string;
         |     ^
    1351 |     ValidationMessage?: string;
    1352 | }
    1353 | export declare enum ChoiceFieldFormatType {
ERROR in .../node_modules/@pnp/sp/src/types.d.ts
1351:5 Property 'ValidationMessage' of type 'string | undefined' is not assignable to string index type 'string | number | boolean'.
    1349 |     Title?: string;
    1350 |     ValidationFormula?: string;
  > 1351 |     ValidationMessage?: string;
         |     ^
    1352 | }
    1353 | export declare enum ChoiceFieldFormatType {
    1354 |     Dropdown = 0,
```

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

1. Create a new project
2. Add packages
3. Add Code (e.g. `import { sp } from '@pnp/sp' ... }
4. Build

This error might be thrown because of eslint; this is my eslintrc:

```js
module.exports = {
  root: true,
  env: {
    node: true,
  },
  extends: [
    'plugin:vue/recommended',
    '@vue/standard',
    '@vue/typescript',
  ],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    // allow async-await
    'generator-star-spacing': 'off',
    'vue/max-attributes-per-line': 0,
    // extra rules
    'comma-dangle': ['error', 'always-multiline'],
  },
  parserOptions: {
    parser: 'typescript-eslint-parser',
  },
}
```

**Comment by johannes-z** [comment]
@patrick-rodgers doesn't eslint ignore all the files listed in the gitignore. My gitignore already lists the node_modules folder.

**Comment by koltyakov** [comment]
Skip library check to prevent local setting be applied on the imported modules which could have different settings:

**tsconfig.json**

```json
{
    "compilerOptions": {
        // ...
        "skipLibCheck": true,
        // ...
    },
   // ...
}
```

**Comment by johannes-z** [comment]
Thanks @koltyakov that's what I was missing!

**Comment by gonadn** [comment]
dident work for me, "skipLibCheck": true is allready in my tsconfig.json file...?
I mean it allready was in "tsconfig.json" when i first created the prosject...
