### ISSUE TITLE
Usage of serverProcessedContent 

### ISSUE THREAD

**Issue by jayeshvg** [pnp/pnpjs#402]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.1.4]

Please specify what version(s) of SharePoint you are targeting: [Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
How to add serverProcessedContent properties when using  new ClientSideWebpart() in my SPFx solution to add a yammer feed onto a page.

### Steps to Reproduce
sectionColumn.addControl(
      new ClientSideWebpart('Title of webpart', "Description of webpart",
        {
           *Property json*
        },
        'webpart Id',
        null,
        "serverProcessedContent": {
          "searchablePlainTexts": {
            "title": "title"
          }
        }
      )
    );

**Comment by patrick-rodgers** [comment]
Hi @jayeshvg - I don't think you need to edit the server processed content on the client side. The below code works for me to add a Yammer webpart:

```TypeScript
// get webpart defs
const defs = await sp.web.getClientSideWebParts();

// this is the id of the definition in my farm
const yammerPartDef = defs.filter(d => d.Id === "31e9537e-f9dc-40a4-8834-0e3b7df418bc")[0];

// page file
const file = sp.web.getFileByServerRelativePath("/sites/dev/SitePages/Testing_kVKF.aspx");

// create page instance
const page = await ClientSidePage.fromFile(file);

// create part instance from definition
const part = ClientSideWebpart.fromComponentDef(yammerPartDef);

// update data version
part.dataVersion = "1.5";

// set the properties required
part.setProperties({
    feedType: 0,
    isSuiteConnected: false,
    mode: 2,
    networkId: 9999999,
    yammerEmbedContainerHeight: 400,
    yammerFeedURL: "",
    yammerGroupId: -1,
    yammerGroupMugshotUrl: "https://mug0.assets-yammer.com/mugshot/images/{width}x{height}/all_company.png",
    yammerGroupName: "All Company",
    yammerGroupUrl: "https://www.yammer.com/{tenant}/#/threads/company?type=general",
});

// add to the section/column you want
page.sections[0].addControl(part);

// persist changes
page.save();
```

I got the property values and correct data version by adding the part through the UI and then reading them to see what I needed to use. We don't currently have a way to detect the data version, see #52 or to predict the required properties as they are different for each part. HTH

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Please _reopen_ if you need to continue the conversation. Thanks!

**Comment by jayeshvg** [comment]
Following helped
`sectionColumn.addControl(
      new ClientSideWebpart('WebPart title', "WebPart Description", {
        <webpartproperties in order required for addControl method>, {
          "searchablePlainTexts": {
            "title": "Title to be displayed"
          },
         <other webpart properties in order required for addControl method>
        })
    );`
