### ISSUE TITLE
Review packaging of libraries

### ISSUE THREAD

**Issue by patrick-rodgers** [pnp/pnpjs#403]
### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

Because things change the 2.0 release is a good time to review how we are packaging the library and what changes make sense to make. Can we reduce the number of packaged files - or do we need more options?

Edit: thinking specifically about the "built" js files included in each package [as outlined here](https://pnp.github.io/pnpjs/documentation/package-structure/).

**Comment by baywet** [comment]
I think that one important thing to keep in mind is that SPFx has a bunch of limitations today with externals and the way they package/bundle solutions. It'd be very interesting to have a solution on pnpjs that works properly given their constraints, without having a complex externals configuration and even if we need multiple pnpjs "libraries" (eg I need taxomomy and sp and …) avoiding duplicates as well.
