### ISSUE TITLE
createCommunicationSite param bug

### ISSUE THREAD

**Issue by KieranDaviesV** [pnp/pnpjs#405]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.2.6      ]

Please specify what version(s) of SharePoint you are targeting: [    SPO     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
createCommunicationSite takes 7 params, 3 of the params which are supposed to be string are set to ""  | undefined. So empty string or undefined.

### Observed Behavior
Well i cant add a string to the function

### Steps to Reproduce
try to use the function and adding a string into the last 3 fields

**Comment by gautamdsheth** [comment]
That is my bad indeed. 

It has however been fixed in [PR 380](https://github.com/pnp/pnpjs/pull/380). You will to have wait for the next release 1.2.7 to fix it. Meanwhile you can create it with the first 4 parameters.

**Comment by patrick-rodgers** [comment]
The next release is scheduled for this Friday, Dec 7.

**Comment by patrick-rodgers** [comment]
Going to close this one as it is already fixed. Thanks @gautamdsheth for getting the fix in and @KieranDaviesV for letting us know.
