### ISSUE TITLE
Please add the ability to write configuration to List

### ISSUE THREAD

**Issue by bva999** [pnp/pnpjs#407]
### Category
- [x] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.6 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online  ]

When we use **@pnp/config-store** we can only get values from the List using **SPListConfigurationProvider**. 
But we can't write in the list. 
And then the question is , what is the settings.Add, settings.AddJSON and settings.apply? 
I confused....

**Comment by patrick-rodgers** [comment]
The idea behind that library originally (its start was way back at the beginning of sp-pnp-js) is that it provides a way at runtime to easily load a readonly configuration store. Settings would be something the application read, not updated. Like a web.config file.

If you need to update say the settings list, pnpjs provides ways to easily [update list items](https://pnp.github.io/pnpjs/sp/docs/items/#update).

The methods you ask about add settings into the collection during runtime, but were never intended to write them back to the store.

**Comment by bva999** [comment]
> so what you are really asking for is a way to tell the provider of settings to persist back whatever you have put into it into its store?
Yes, it would be great to have this opportunity. Of course, I can update list items of the configuration list.   
But provider already knows list name and fields and settings object already knows all about values and keys....I think it would simplify usage of  the configuration list.

**Comment by patrick-rodgers** [comment]
Going to close this one as we don't have plans to implement this functionality as it exists through the ability to add/update items. If someone wants to submit a PR adding this capability to the config store we'll take a look at merging it. Thanks!
