### ISSUE TITLE
Two search web parts only works on same page

### ISSUE THREAD

**Issue by Akurt2** [pnp/pnpjs#408]
### Category
- [ ] Enhancement
- [ ] Bug
- [X ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.2.6     ]

Please specify what version(s) of SharePoint you are targeting: [        Online ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question

I have two web parts which has the same search function defined as:

```
`import { WebPartContext } from "@microsoft/sp-webpart-base";
import pnp, { SearchQuery, SearchQueryBuilder, SearchResults, SearchResult } from '@pnp/pnpjs';

export class ProjectItemProvider {
    private context: WebPartContext;
```

    constructor(context: WebPartContext) {
        this.context = context;
        
    }

    public GetSiteItemsByContentId(contentTypeId: string, selectProperties: string[]): Promise<SearchResult[]> {
        const _searchQuerySettings: SearchQuery = {
            TrimDuplicates: false,
            RowLimit: 500, 
            SelectProperties: selectProperties.concat(["ParentLink"])
        };
        
        let q = SearchQueryBuilder(`ContentTypeId:${contentTypeId}*`, _searchQuerySettings).rowLimit(500);
        const srPromise = new Promise<SearchResult[]>((resolve, reject) => {
            pnp.sp.search(q).then((response: SearchResults) => {

                resolve(response.PrimarySearchResults);
            });
        });
        return srPromise;
    }
}`

Which will get data from lists in the tenant. 
### Observed Behavior
I want to place the two web parts in two places:

mytenant.com/sites/mysite
mytentant.com/sites/mySite/sitePages/myPage

But the search function at 
mytenant.com/sites/mysite
Works SOMETIMES, and if it does not work the console will throw this error:

POST https://mytenant.com/sites/_api/search/postquery 404
Uncaught (in promise) Error: Error making HttpClient request in queryable [404]  ::
 There is no operation handler registered for '{"operation_12":["getItems_24","pageLoad_162"]}'.

The web part on the other path, mytentant.com/sites/mySite/sitePages/myPage constantly throws the same error and have never worked, only in the online workbench. It seems that when I ONLY have the web part on mytenant.com/sites/mysite it seems more stable, but if I put the other one it will disturb it. Can't confirm this to 100%.

BUT when I put the two web parts on the same page, then it works as it should.

If I look at the console errors, its seems that the context (?) might causing an issue. But why? Any way to solve this?

**Comment by patrick-rodgers** [comment]
Any updates here? Will close shortly due to inactivity. Thanks!

**Comment by patrick-rodgers** [comment]
Going to close this due to inactivity. If you are still stuck, please _reopen_ the issue so we can help out. Thanks!
