### ISSUE TITLE
Create a child term

### ISSUE THREAD

**Issue by MarianoPrz** [pnp/pnpjs#409]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.4]

Please specify what version(s) of SharePoint you are targeting: [Sharepoint Online]

**Hi! It's supported add a child term? I mean, i've a term and below of this i want to add a new term. Documentation nothing says about this, and intellisense doesn't show nothing like too..

Thanks in advance!**

**Comment by patrick-rodgers** [comment]
Closing this as the capability was added in #411. Thanks for the suggestion.
