### ISSUE TITLE
attachmentFiles getBlob() get wrong type

### ISSUE THREAD

**Issue by NZainchkovskiy** [pnp/pnpjs#417]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.7]

Please specify what version(s) of SharePoint you are targeting: [SP 2016 on premises]

### Expected / Desired Behavior / Question
I have a list item with docx document attached. I'm getting this attach via `attachmentFiles.getByName(name).getBlob()` and see that blob type is `application/json`. Size of blob 3 times more then real file. When I download this blob via downloadjs or FileSaver, file is corrupted. File content seems escaped. I got something like that inside:
`\u0000\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\`
What I did wrong and how I can fix it?
Thank you!

**Comment by koltyakov** [comment]
Hi Nikolay, 
Could you describe where the code is executing? SP page, Node.js app, via proxy, etc.?

**Comment by NZainchkovskiy** [comment]
Hi Andrew, 
I got this issue via proxy (sp-rest-proxy). 
Now, when you asked, I wonder maybe it's a proxy issue. 
I will check this behavior at SP page and will be back with update.
Thank you.

**Comment by koltyakov** [comment]
It's probably the proxy thing. Please raise an issue there, will check and fix if it's the case.

Tried something like:

```typescript
const attachmentBlob = await list.items.getById(20).attachmentFiles.getByName(attachmentFileName).getBlob();
await list.items.getById(21).attachmentFiles.add(attachmentFileName, attachmentBlob);
```

It works.

Closing this one. As it assumably not PnPjs's issue.
