### ISSUE TITLE
Get Hub site Department ID using pnp js

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/pnpjs#418]
Is it possible to get current site department id using pnp js or search ?

**Comment by gautamdsheth** [comment]
DeparmentId corresponds to the Hub Site ID property of a SP Site object.

You can get the value as below:

```Typescript
import { sp } from "@pnp/sp";
sp.site.select("HubSiteId").get().then(w => {
    console.log(w);
});
```

**Comment by koltyakov** [comment]
Closing this as answered. Thanks, @gautamdsheth!
