### ISSUE TITLE
renderListData returns HTML encoded special characters (&amp;)

### ISSUE THREAD

**Issue by thomasberman** [pnp/pnpjs#423]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.4]

Please specify what version(s) of SharePoint you are targeting: [Online/SPFx 1.6]

### Expected / Desired Behavior / Question
When I return list items via renderListData, I get HTML encoded special characters (`&amp;` in my case) in the field values if there is an & in a text field. When I return the same item via list.items.getById(); I do not get encoded characters. 

Wondering if this is by design/built into SharePoint/a bug and whether I should parse the string myself to fix this etc.

### Steps to Reproduce

- Create a list item with a single line text field and an ampersand (&) in the text field value. For example: a single line text field called myTextField with the value: `m&m's`

- Run: renderListData and pass in a CAML query to get that list item: myTextField value: `m&amp;m's`

- Run: sp.list.items.getById(id). myTextField value: `m&m's`

**Comment by patrick-rodgers** [comment]
We aren't doing any special parsing so that is what the method returns by design. I would just go ahead and handle this as needed. I am not aware of a flag to get unencoded results back.

**Comment by thomasberman** [comment]
Great. Thanks, Patrick
