### ISSUE TITLE
Multiple attachment upload causing 409 conflict error.

### ISSUE THREAD

**Issue by LiamSolDev** [pnp/pnpjs#428]
Hi Everyone,

### Category
- [ ] Enhancement
- [X ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: sp-pnp-js@3.0.10

Please specify what version(s) of SharePoint you are targeting: SharePoint Online

### Expected Behavior Question
When uploaded multiple attachments of any size the promise setup up in item.attachmentFiles.addMultiple(attachments) will chain the requests and upload them correctly 

### Observed Behaviour
When using the item.attachmentFiles.addMultiple(attachments), it is intermittently causing a 409 error due to conflicts in the upload,   my research has led me to believe this is caused by one file not being fully uploaded before moving onto the next, in the test case that most commonly causes this the files are approximately 3Mb in size. The error is more likely to occur the more files that are being uploaded. All files uploaded have different names and content.

![error](https://user-images.githubusercontent.com/44843976/50209035-af102b80-036a-11e9-8395-b13df7bb2bb5.png)

### Steps to Reproduce
Files are stored in an array in the state and pulled out and converted into an array of attachments before being uploaded with item.attachmentFiles.addMultiple(attachments) code bellow:

![upload attachments](https://user-images.githubusercontent.com/44843976/50209087-d0711780-036a-11e9-8732-a5126a9a0ac1.PNG)

I am currently working to resolve this issue, any assistance or information from people who have encountered this issue before will be appreciated.

Thank you for your feedback!

**Comment by koltyakov** [comment]
Hi @LiamSolDev, 

The problem can be because of `sp-pnp-js@3.0.10` which was deprecated almost half a year ago.

**Please use the recent @pnp/* packages instead.**

Recent PnPjs treats attachments upload sequence:

```typescript
    public addMultiple(files: AttachmentFileInfo[]): Promise<void> {

        // add the files in series so we don't get update conflicts
        return files.reduce((chain, file) => chain.then(() => this.clone(AttachmentFiles, `add(FileName='${file.name}')`, false).postCore({
            body: file.content,
        })), Promise.resolve());
    }
```

there should be no issue you describe.

**Comment by koltyakov** [comment]
However, it's strange as `sp-pnp-js@3.0.10`'s implementation for `addMultiple` was the same.

**Comment by LiamSolDev** [comment]
Hi Thanks for the reply.

I will try updating and see if that helps with the issue, but assuming that is not the case as there as been no code change, is there any other solutions you can think of?

Kind Regards,
Liam

**Comment by koltyakov** [comment]
@LiamSolDev, can't really reproduce. What I'm doing is: loop a number (e.g. 5) of attachments creation, deletion and so on in a cycle. No 409.

**Comment by koltyakov** [comment]
Regards updating, just following [transition guide](https://pnp.github.io/pnpjs/documentation/transition-guide/) should be safe to go path. Also some [changes to polyfills](https://pnp.github.io/pnpjs/documentation/polyfill/).

**Comment by LiamSolDev** [comment]
Hi Thanks for trying and the tips for updating. 

I'll try to get a test case where it always breaks for me.

Kind Regards,
Liam

**Comment by patrick-rodgers** [comment]
Going to close this as inactive. Once you get your code updated to use the latest version of the libraries and can share a reproduction please open a new issue. Thanks!

**Comment by anomepani** [comment]
I am also getting 409 conflicts error while uploadeding multiple attachments to list item.
