### ISSUE TITLE
issue with get term group's data

### ISSUE THREAD

**Issue by paigeflourin** [pnp/pnpjs#429]
I am trying to get the term set under the term group:

![c966z](https://user-images.githubusercontent.com/6951524/50214875-5a959c00-03bc-11e9-80ac-d4b82511ef36.png)
![sa5a0](https://user-images.githubusercontent.com/6951524/50214876-5a959c00-03bc-11e9-8bc5-a79c1d7d8062.png)

i am following the documentation https://pnp.github.io/pnpjs/sp-taxonomy/docs/ for retrieving the items and i am using this:

```
const store: ITermStore = taxonomy.termStores.getByName("Taxonomy_v5o/SbcTE2cegwO2dtAN9l==");

        const group: ITermGroup & ITermGroupData = store.getTermGroupById("0ba6845c-1468-4ec5-a5a8-718f1fb05431").get();
```

        

but i get this error, even if i just copied this snippet from the documentation, am i missing something?

![image](https://user-images.githubusercontent.com/6951524/50214835-320da200-03bc-11e9-8808-c7d3e3543252.png)

**Comment by simonagren** [comment]
Hi @paigeflourin 
It seems like you are trying to add a Promise and not a result to that constant, if we use `await` we will wait fot the promise to finish.

If you are doing this in a `async` function you can try this following code. And if you are using `.then`, let me know then I'll change the code for you:

```TypeScript
const store: ITermStore = await taxonomy.termStores.getByName('Taxonomy_BXNhZFumwYDfQvlT5Br52A==').get();
const group: ITermGroup & ITermGroupData = await store.getTermGroupById("0e8f395e-ff58-4d45-9ff7-e331ab728beb").get();
const tSets = await group.termSets.get();
console.log(tSets);
```
Let me know how it works out :)

**Comment by paigeflourin** [comment]
Hi @simonagren ,

sorry i have read your response late but i used this one:

```
 const store: ITermStore = await taxonomy.termStores.getByName("Taxonomy_9D1X5aueEcT7a3LKqetQKw==");
        const setWithData = await store.getTermSetById("6c285b4d-49f9-4666-981d-2b7be6872978");
        const termSetGroup = await setWithData.group.get();

        const terms = await setWithData.terms.get();

```
and it apparently worked! but thank you for your answer it looks like what i used :)

**Comment by simonagren** [comment]
@paigeflourin Glad you fixed it :)
