### ISSUE TITLE
Add section to Client Side Page not working in Team Site

### ISSUE THREAD

**Issue by umaknow-jessica** [pnp/pnpjs#435]
### Category
- [x] Bug
- [ ] Question
- [ ] Enhancement
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.8-0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question

In a Team Site, when I add a control to a section in a Client Side Page, then save and publish the page, I expect the section and its content to be saved in the page. 

### Observed Behavior

In a Team Site, when I add sections and controls to a Client Side Page then go to the page, there is no content in the page.

I think something changed in SharePoint, because the function to add sections to a page used to work some months ago with an older version of pnp js and now it doesn't work anymore.

### Steps to Reproduce

Run the following code in a Team Site

```
const web = new Web(webUrl);
const page = await ClientSidePage.fromFile(web.getFileByServerRelativeUrl(`${webUrl}/SitePages/${pageName}.aspx`));
page.addSection().addControl(new ClientSideText("Here is some text!"));
await page.save();
await page.publish();
```

**Comment by patrick-rodgers** [comment]
Are you getting an error or other feedback from the server when you send the request?

**Comment by patrick-rodgers** [comment]
Currently I can't duplicate this. I ran your code in my farm and I got a page with the webpart as expected. I tried it both with a new page (created with the library) and an existing page. Can you share any more details about what is happening in the code or what the existing content of the page might be? Are there other webparts on the page? Are there any errors when the page is being loaded and parsed in the fromFile call?

**Comment by umaknow-jessica** [comment]
Hi! I did some testing, and the code works in standard release but not in targeted release. The page is a new page created with the code, so it has initially no webparts in it. When creating the page in targeted release with the ``web.addClientSidePage`` function, the page is created with the error "no component id". Here's how I have to create the page in targetedRelease to not have this error : 
````
await web.getFolderByServerRelativeUrl(pagesLibraryUrl).files.addTemplateFile(`${pageFolderPath}/${pageName}.aspx`, TemplateFileType.ClientSidePage);
    const page = await ClientSidePage.fromFile(web.getFileByServerRelativeUrl(`${pageFolderPath}/${pageName}.aspx`));
    const pageItem = await page.getItem();
    await web.getList(pagesLibraryUrl).items.getById(pageItem["Id"]).update({
      ClientSideApplicationId: "b6917cb1-93a0-4b97-a84d-7cf49975d4ec",
      Title: pageName
    });
````

**Comment by simonagren** [comment]
@umaknow-jessica I don't know if this has something to do with it.
But newly created pages does not have sections etc when accessing from Rest. 
At least a while back you needed to make a manual update (via GUI) for the sections etc to be available.
This is by design in SharePoint.

**Comment by patrick-rodgers** [comment]
@umaknow-jessica - when you add a page we set the client side application id, but you are using a different code path. Can you try the web's addClientSidePage or addClientSidePageByPath methods and see if that works for you? That is the way we can control creating the page correctly, when you do it through another method it is out of our control.

**Comment by patrick-rodgers** [comment]
Going to close this due to inactivity, please open a new issue and reference this one if you are still having troubles. Thanks!

**Comment by joyjeevan** [comment]
@patrick-rodgers Hi,
I am having the same issue. i.e Page content is not saving
I have followed the same [link](https://pnp.github.io/pnpjs/sp/docs/client-side-pages/#add-client-side-page) you mentioned.
Here is my code 
` const pageFile = sp.web.getFileByServerRelativeUrl('/sites/TestPlayground-Joy/SitePages/SamplePage01.aspx');
  const page = await ClientSidePage.fromFile(pageFile);
  page.sections = [];
  const section = page.addSection();
  section.addControl(new ClientSideText('HTML content goes here'));
  await page.save()
})()
  .then(_ => console.log('Done'))
  .catch(console.log);`

here is the object when console logging the page object after save
`batch: (...)
commentsDisabled: false
hasBatch: (...)
listItemAllFields: (...)
parentUrl: (...)
query: (...)
sections: Array(1)
0: CanvasSection
columns: [CanvasColumn]
defaultColumn: (...)
order: 1
page: ClientSidePage {_query: Map(0), _options: {…}, _url: "_api/web/getFileByServerRelativeUrl('/sites/TestPlayground-Joy/SitePages/SamplePage01.aspx')", _parentUrl: "_api/web/getFileByServerRelativeUrl('/sites/TestPlayground-Joy/SitePages/SamplePage01.aspx')", _useCaching: false, …}
_memId: "c20d64a1-6bb3-4db1-9c30-60395c8c558f"
__proto__: Object
length: 1
__proto__: Array(0)
versions: class_1
_batch: null
_cachingOptions: null
_cloneParentCacheOptions: null
_cloneParentWasCaching: false
_forceCaching: false
_options: {headers: {…}}
_parentUrl: "_api/web/getFileByServerRelativeUrl('/sites/TestPlayground-Joy/SitePages/SamplePage01.aspx')"
_query: Map(0) {}
_url: "_api/web/getFileByServerRelativeUrl('/sites/TestPlayground-Joy/SitePages/SamplePage01.aspx')"
_useCaching: false
__proto__: File`

comments section gets disabled by using page.disableComments();

**Comment by umaknow-jessica** [comment]
Hi! I was able to fix the issue on the past, and it worked well until this morning. The code and the environment was not changed. It seems the update of the CanvasContent1 property returns a 304 not modified, but I don't know what I can do to fix this

**Comment by umaknow-jessica** [comment]
Update : I can manage to save the page content by updating the CanvasContent1 property with Jsom

**Comment by Joy-jeevan** [comment]
Sorry for late reply and thank you for replying back. I am just a beginner in sharepoint, so could be able elaborate what exactly I have to change in CanvasContent1

**Comment by umaknow-jessica** [comment]
Hi! After adding your controls in the page, you can update the page list item property CanvasContent1 with the value from `page.toHtml()`. For now, I think you will need to update it with JSOM since the update function from pnp js doesn't seem work for that specific property.

**Comment by Joy-jeevan** [comment]
@umaknow-jessica thank you for your reply. I think this is a major issue from pnp js as many other users have been pointing out. so I guess I'll have to wait for the update of pnp js to solve this issue in next release. Thanks again. Sharing is Caring.
