### ISSUE TITLE
sp-taxonomy: throw error if entity (term set, term) has not been found

### ISSUE THREAD

**Issue by AJIXuMuK** [pnp/pnpjs#439]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.7]

Please specify what version(s) of SharePoint you are targeting: [ Online]

### Expected / Desired Behavior / Question
Let's say, a developer tries to get term set by id: `await termStore.getTermSetById(id).get()` and provides nonexistent id.
(Use case for such scenario: a developer tries to iterate through multiple term stores and find term set by specified id.)
Currently such a request still will return `TermSet` object where the properties are not initialized (`termSet.Id` or `termSet.Name` are undefined, etc.).
I understand that this is exactly how the ProcessQuery.svc works as it doesn't throw the error as well but just doesn't return any data:
![no-data-terset](https://user-images.githubusercontent.com/17036219/50371586-88bcdc80-0572-11e9-9f27-d59819d11998.png)
But I would think that it might be better, if possible, to throw the error from library or just return `null` object or something.
What do you think?

### Observed Behavior
`TermSet` with no initialized term set data is returned.

### Steps to Reproduce
```typescript
taxonomy.setup({
      spfxContext: this.context
    });

    const termSet = await taxonomy.getDefaultSiteCollectionTermStore().getTermSetById('ad54531f-506e-4cc6-af4f-71157f6f3281').get(); 
```

**Comment by AJIXuMuK** [comment]
@patrick-rodgers in my scenario I have a control (basically Term Picker) that has a configuration `TermSetId` that stored somewhere.
When the control is rendered it is "trimmed" with this `TermSetId`. If the tenant has multiple term stores I'll need to check what term store contains the term set and then work with it.

Currently `termStore.getTermSetById().get()` will return an object and I need to check internal props.
If it return `null` it would be easier to understand that the object is not there.

Maybe it's too unique situation and doesn't worth it. It was just a bit unexpected.

**Comment by patrick-rodgers** [comment]
Right on, will leave this open for investigation. Thanks for the idea.

**Comment by patrick-rodgers** [comment]
Going to close this as we are dropping the sp-taxonomy library for v2 as taxonomy support is coming to the graph and we will move to support that.

**Comment by abdenourben** [comment]
Ho can I import taxonomy and use it in PnPjs v2?

**Comment by koltyakov** [comment]
@abdenourben, you can't. Taxonomy support is dropped. Please check for [details](https://pnp.github.io/pnpjs/transition-guide/#drop-client-svc-and-sp-taxonomy-libraries).

**Comment by abdenourben** [comment]
In my WebPart, I work with v2 of PnPjs, how can I use taxonomy? Is the installation of @pnp/sp-taxonomy package is enough?

**Comment by juliemturner** [comment]
As the documentation says, if you need to use taxonomy then you need to stick with version 1 of PnPJS.
