### ISSUE TITLE
GetParentWeb method throwing error

### ISSUE THREAD

**Issue by jcosta33** [pnp/pnpjs#441]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

@pnp/sp: [    "1.2.7"     ]

SharePoint version: [    SPFx     ]

### Expected / Desired Behavior / Question
I'm trying to use the getParentSite() method.

### Observed Behavior
![imagem](https://user-images.githubusercontent.com/8978270/50485582-c8aa1680-09ed-11e9-87e9-992844b7d222.png)

It's throwing this error. I have set up the context as such:

  sp.setup({
    spfxContext: context  
  });

Context is this.context coming from the onInit method of my ApplicationCustomizer. (SPFx Extension)

### Steps to Reproduce
Just try using the method on SPFx.

Thanks!

**Comment by patrick-rodgers** [comment]
I'd be curious if you could share your code where you load the parent web? I'd like to understand the flow and see where it is failing. It might affect other parts of the library.

**Comment by patrick-rodgers** [comment]
But what is the "ParentWeb" variable in your screen shot? I can't see where that comes from so am not sure what was happening.

**Comment by jcosta33** [comment]
The "ParentWeb" variable is inside your library, the error happens internally in the library itself when the method is evoked. I should've stated this explicitly right away, sorry. Thank you for the quick response!
