### ISSUE TITLE
Azure Function in VS Code SPO add-in list items always empty

### ISSUE THREAD

**Issue by nda1974** [pnp/pnpjs#447]
### Category
- [ ] Enhancement
- [ ] Bug
- [X ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [      Version 1.2.7   ]
Please specify what version(s) of SharePoint you are targeting: [     SharePoint Online    ]

### Observed Behavior
Trying to use @pnp/nodejs and @pnp/sp and unable to retrive list tems

I have followed this example:
https://simonagren.github.io/azurefunction-v2-pnpjs/

I've made an Azure Function and setup the add-in and provided the relevant permissions in the SharePoint Online site collection.
`<AppPermissionRequests AllowAppOnlyPolicy="true">
<AppPermissionRequest Scope="{My Sitecollection}" Right="FullControl" />
</AppPermissionRequests>
`
I've set up SP like this

` sp.setup({
        sp: {
            fetchClientFactory: () => {
                return new SPFetchClient(
                  "{My sitecollection url}", 
                  process.env.spId, 
                  process.env.spSecret,
                  SPOAuthEnv.SPO
                  );
            },
            baseUrl:"https://lbforsikring.sharepoint.com/sites/skade"
        }
    });`

When executing the code below - the "listItems"is always an empty array.
`const listItems = await sp.web.lists.getByTitle("My List Title").items.getAll();`
However, executing this code
`const web = await sp.web.select("Title").expand('Lists').get();`
Returns all the lists in the web as expected.

**Comment by simonagren** [comment]
Hi @nda1974 
Do you get any errors while trying to retrieve the items?
And if you try to get like the title of the list, would that work?
```TypeScript
const listTitle= await sp.web.lists.getByTitle("My List Title").select('Title').get();
console.log(listTitle.Title);
```

**Comment by nda1974** [comment]
The problem is solved as described in https://github.com/pnp/pnpjs/issues/178. I'm closing the issue, thank you for your help.

**Comment by simonagren** [comment]
Cool, nice that It got fixed :) And thank you for checking our PnPJs, and my blog :D
