### ISSUE TITLE
Batch promises never resolve IE

### ISSUE THREAD

**Issue by araver** [pnp/pnpjs#453]
### Category
- [ ] Enhancement
- [ X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.7]

Please specify what version(s) of SharePoint you are targeting: [Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Creating a batch request to resolve or fail in IE.

### Observed Behavior
When i make a batch request it never gets resolved in IE and no error message is shown. Works in all other browser.

### Steps to Reproduce
Create a batch request. Try to resolve the batch request.

**Comment by simonagren** [comment]
Hi @araver!
Have you tried using the IE11 polyfills for PnPJs? https://pnp.github.io/pnpjs/documentation/polyfill/

**Comment by araver** [comment]
Yes. That didn't work.

**Comment by simonagren** [comment]
Out of my league then I think, @koltyakov ? ;)

**Comment by koltyakov** [comment]
I still staking on polyfills. And confirming that batches work for me in IE.

![image](https://user-images.githubusercontent.com/7816483/51077244-b221e180-16b4-11e9-94a1-3619b6e6cc72.png)

this is a result of something simple as this:

![image](https://user-images.githubusercontent.com/7816483/51077254-cd8cec80-16b4-11e9-90be-cebc7577c50b.png)

**Comment by koltyakov** [comment]
@araver can you post a sample repo with a bare minimum configuration to reproduce the issue?

**Comment by patrick-rodgers** [comment]
Couple of things. I am assuming you are trying in IE11, anything earlier is not supported. Also, please as @koltyakov asks, please provide us repro code so we can test this out. At this point you haven't shared any code so we can't see what you are doing. Thanks!

**Comment by araver** [comment]
I figured it out. Let me clarify, it's only batch requests using the Graph Client. The problem was the graph client uses Array.Fill. And IE doesn't support that method nor does the "@pnp/polyfill-ie11" or spfx include a polyfill for the "Fill" method. Also i think the reason I wasn't getting an error is because react was catching it. Once I moved it into a simpler solution, I was able to surface the error. Here is a repro in case you want to see the issue.

````typescript
let teams = await graph.me.joinedTeams.get();
console.log("Teams", teams);
let promises: Promise<any>[] = [];
let groupSiteBatch = graph.createBatch();
for(let i = 0; i < teams.length; i++){
  let team = teams[i];
  let gsItem = groupSiteBatch.add<any>(`https://graph.microsoft.com/v1.0/groups/${team.id}/sites/root`, "GET", {}, new ODataDefaultParser(), team.id);
  promises.push(gsItem);
}
await groupSiteBatch.execute();

var items = await Promise.all(promises);
console.log(items);
````

**Comment by patrick-rodgers** [comment]
Ah, ok. I just updated the polyfill package to include the array.fill method. you can try that and see if it helps. Thanks!
