### ISSUE TITLE
Use @pnp/graph in non-spfx solution

### ISSUE THREAD

**Issue by c-eiser13** [pnp/pnpjs#455]
### Category
- [ ] Enhancement
- [ ] Bug
- [ X ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.7 ]

Please specify what version(s) of SharePoint you are targeting: [ SPO ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Hey folks, I am trying to use the @pnp/graph in a non framework solution that is AngularJS 1.6 where we are using webpack to bundle this solution. I am currently using @pnp/sp with no issues, but am having trouble getting Graph to work. My main question is what I am trying to accomplish even possible? 

I have a service in the solution defined as a class and in the constructor is where I am configuring both sp and graph and I am using the AdalClient in @pnp/common:
![graph](https://user-images.githubusercontent.com/42096464/51140658-bc56f380-180c-11e9-8426-0c030383b797.PNG)

I am calling this simple test function from one of my components:
![graph1](https://user-images.githubusercontent.com/42096464/51140011-02ab5300-180b-11e9-9fa2-008668162698.PNG)

The first time I visit my page with component that calls this function, I get a popup for a second or two, then it disappears, never asks me to login or for credentials. In the dev tools, my catch block is hit with the error: "Token renewal operation failed due to timeout".

I based my configuration off this doc: https://pnp.github.io/pnpjs/common/docs/adalclient/. If there is a better resource out there you could point me to, i'd greatly appreciate it. If further info is needed, I can provide as well.  Thanks!

Thank you for your feedback!

**Comment by c-eiser13** [comment]
@patrick-rodgers thanks for the quick response. I will take a look at the related issue and see what I might be able to find and will monitor this post for any updates. Thanks!

**Comment by patrick-rodgers** [comment]
The other thing you could look at, depending on what you need to call is the graph proxy v2 api as discussed [here](https://docs.microsoft.com/en-us/onedrive/developer/sp2019/docs/rest-api/?view=odsp-graph-online) and [here](https://www.techmikael.com/2019/01/introducing-sharepoint-rest-api-v20.html).

Due to all the auth issues and CORS etc if possible we really recommend using SPFx to handle graph calls.

**Comment by c-eiser13** [comment]
@patrick-rodgers thanks for providing those links, useful information for future uses.  I was also able to locate the tokens in session storage, but continue getting the timeout error. As for my current use case, I've had to go a different route since I was after the SharePoint activity reports and handling the 302 redirect in JS was not going to work. Instead, I created a WebApi that will get the token, call the graph endpoint and format the CSV data into JSON for me. You can close this issue and appreciate the help.  Thanks!
