### ISSUE TITLE
Can't add rich text multi-line text field to a list

### ISSUE THREAD

**Issue by tsekityam** [pnp/pnpjs#461]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: **1.2.8**

Please specify what version(s) of SharePoint you are targeting: **SharePoint Online**

### Expected Behavior
After the field is added successfully, the field should support rich text editor in native SharePoint form
![opera snapshot_2019-01-17_105343_esquel sharepoint com](https://user-images.githubusercontent.com/3814422/51292585-476efe00-1a46-11e9-9e09-330e88bb4c7c.png)

### Observed Behavior
Although the settings of the field added claims that it is support rich text, but the field doesn't support rich text in the native SharePoint form. It is not a true rich text field.
![opera snapshot_2019-01-17_104959_esquel sharepoint com](https://user-images.githubusercontent.com/3814422/51292521-fa8b2780-1a45-11e9-84a2-b26bddbba657.png)
![opera snapshot_2019-01-17_104716_esquel sharepoint com](https://user-images.githubusercontent.com/3814422/51292517-f65f0a00-1a45-11e9-8a04-bbd2ef6ed271.png)

### Steps to Reproduce
``` ts
private onAddArticleList = (title: string, mode: PromotionMode) => {
  let w = new Web(this.props.siteUrl);
    .then(addListResult => {
      return addListResult.list.fields
        .addMultilineText("Content")
        .then(addFieldResult => {
          return addListResult;
        });
    })
  // do something else...
}
```

****
The value of `addFieldResult.data.SchemaXml` is 
``` xml
<Field
    DisplayName="Content"
    Type="Note"
    Required="FALSE"
    ID="{/* deleted */}"
    SourceID="{/* deleted */}"
    StaticName="Content"
    Name="Content"
    ColName="ntext2"
    RowOrdinal="0"
    AllowHyperlink="TRUE"
    AppendOnly="FALSE"
    NumLines="6"
    RestrictedMode="FALSE"
    RichText="TRUE"
    Version="1" />
```

I found that the [RichTextMode](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spfieldmultilinetext.richtextmode?view=sharepoint-server) property is missing in the returned schema. Once I add `RichTextMode="FullHtml"` to the schema, then rich text editor appears in the form.

**Comment by patrick-rodgers** [comment]
Had a look and that property is not exposed to the clients (doesn't appear in CSOM either). I don't know why that is the case, but if you need to create a full rich text field creating it using the XML is the way currently, as you have found. I will add something to the docs indicating this.
