### ISSUE TITLE
pnp/sp SearchSuggest declaration file count doesn't accept string

### ISSUE THREAD

**Issue by abhrabhattacharyya** [pnp/pnpjs#463]
### Category
- Bug

### Version

Please specify what version of the library you are using: 1.2.8

Please specify what version(s) of SharePoint you are targeting: 2016

### Expected 
On compilation no issues

### Observed Behavior
Using @pnp/sp for sp.web.select() in React@16.6.3 and TypeScript@3.2.2 application. 
On build we could see the following issue:
`C:/Git/sharepoint-widget/node_modules/@pnp/sp/src/searchsuggest.d.ts
(14,5): Property 'count' of type 'number | undefined' is not assignable to string index type 'string | number | boolean'.`

### Steps to Reproduce
`
private async Init(): Promise<SpContext> {
     await sp.web.select('Title, Url').get()
           .then(data => {
                this._title = data.Title;
                this._url = data.Url;
            });
        await sp.web.select('AllProperties').expand('AllProperties').get()
            .then(response => {
                var customerIdValue = response.AllProperties.OData__x005f_dttedr_x005f_customer_x005f_id;
                if (customerIdValue !== undefined && customerIdValue.trim() !== '') {
                    this._customerId = customerIdValue;
                }
            });
        return SpContext._instance;
    }
`

**Comment by patrick-rodgers** [comment]
Hi @abhrabhattacharyya - I am not seeing in the code you shared where you are using the search suggest api? I think the count is supposed to be a number, so if you are setting it to a string that would in fact be a type check error as is reported. Can you share the code where you are using the search suggest API? That would likely help us assist you. Thanks!

**Comment by abhrabhattacharyya** [comment]
Hi @patrick-rodgers, Thanks for the reply... Actually we are not using search at all in our project. We are only using sp.web.select(). Then why this issue is coming...

**Comment by koltyakov** [comment]
So you are receiving TypeScript messages out of the node_modules?
Sounds similar to these cases https://github.com/pnp/pnpjs/issues/299 and https://github.com/pnp/pnpjs/issues/362.
Could you check is `"skipLibCheck": true,` is presented in your project's `tsconfig.json` file?

**Comment by abhrabhattacharyya** [comment]
Thanks for the reply... It worked!!!
