### ISSUE TITLE
Excluding PnP from bundling & loading from CDN - webpack

### ISSUE THREAD

**Issue by unnieayilliath** [pnp/pnpjs#467]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [      1.2.8   ]

Please specify what version(s) of SharePoint you are targeting: [     2013    ]

### Expected / Desired Behavior / Question
I am trying to implement a typescript solution to create web-parts for SP 2013. I am intending to use the generated html/js inside a CEWP. I am not using any framework such as React/Angular. I am using webpack for compilation. My solution works well when I include pnpjs inside my bundle. But I want to exclude pnpjs from my bundle and want to load it from a CDN. I have successfully excluded the pnpjs from my bundles and am loading it on the page using script tag. But the module resolution does not work with my current set up and I get below error:

```
Uncaught Error: Module name "@pnp/pnpjs" has not been loaded yet for context: _. Use require([])
https://requirejs.org/docs/errors.html#notloaded
    at makeError (require.min.js:1)
    at Object.s [as require] (require.min.js:1)
    at requirejs (require.min.js:1)
    at Object.<anonymous> (helloworld-bundle.js:1)
    at n (helloworld-bundle.js:1)
    at Object.<anonymous> (helloworld-bundle.js:1)
    at n (helloworld-bundle.js:1)
    at Object.<anonymous> (helloworld-bundle.js:1)
    at n (helloworld-bundle.js:1)
    at helloworld-bundle.js:1

```
I have my repo uploaded to github for reference = > https://github.com/unnieayilliath/SP2013.Typescript.Webparts 

Any help is highly appreciated !

**Comment by koltyakov** [comment]
Hi @unnieayilliath,

You can check how I do this in [generator-sppp](https://github.com/koltyakov/generator-sppp).

Long story short:

- Add WebPack's externals ```{ '@pnp/sp': 'pnp' }```
- Load polyfills and PnPjs bundle (e.g. `pnpjs.es5.umd.bundle.min.js`) to the page

**Comment by unnieayilliath** [comment]
@koltyakov  thanks a lot, I was missing polyfills.
