### ISSUE TITLE
Typescript + webpack: Loading sp-taxonomy from CDN 

### ISSUE THREAD

**Issue by unnieayilliath** [pnp/pnpjs#469]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [      1.2.8   ]

Please specify what version(s) of SharePoint you are targeting: [    SP 2013     ]

### Expected / Desired Behavior / Question

I am using @pnp/sp-taxonomy in my Typescript solution working against SP 2013. My solution works well when the sp-taxonomy package is included in my bundle. But now I am trying to load the package from CDN. I have read from the documentation that, I need to make sure all the dependent  libraries for pnp.sp-taxonomy should be also loaded to the page manually. So I have included the load scripts for all dependent libraries  as below & polyfills are also loaded:
```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-pnpjs/1.2.7/pnpjs.es5.umd.bundle.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-common/1.2.8/common.es5.umd.bundle.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-logging/1.2.8/logging.es5.umd.bundle.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-odata/1.2.8/odata.es5.umd.bundle.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-sp/1.2.8/sp.es5.umd.bundle.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-sp-clientsvc/1.2.8/sp-clientsvc.es5.umd.bundle.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-sp-taxonomy/1.2.8/sp-taxonomy.es5.umd.bundle.min.js" ></script>
```

In my webpack config, I have marked `@pnp/sp-taxonomy` as external like below:
```
externals:{
    '@pnp/pnpjs': 'pnp',
    '@pnp/sp-taxonomy': 'pnp.sp-taxonomy',
  }
```

When I run it , I get the below error:

> Uncaught ReferenceError: taxonomy is not defined
>     at Object.<anonymous> (forecast-bundle.js:1)
>     at n (forecast-bundle.js:1)
>     at Object.<anonymous> (forecast-bundle.js:1)
>     at n (forecast-bundle.js:1)
>     at Object.<anonymous> (forecast-bundle.js:1)
>     at n (forecast-bundle.js:1)
>     at Object.<anonymous> (forecast-bundle.js:1)
>     at n (forecast-bundle.js:1)
>     at forecast-bundle.js:1
>     at forecast-bundle.js:1

My solution works properly for pnpjs imports. What am I missing here?

**Comment by koltyakov** [comment]
Hi @unnieayilliath,

This works for me. 

```json
externals:{
  '@pnp/sp': 'pnp',
  '@pnp/sp-clientsvc': ['window', 'pnp.sp-clientsvc'],
  '@pnp/sp-taxonomy': ['window', 'pnp.sp-taxonomy'],
}
```

Side note, regards this:

```html
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-pnpjs/1.2.7/pnpjs.es5.umd.bundle.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-common/1.2.8/common.es5.umd.bundle.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-logging/1.2.8/logging.es5.umd.bundle.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-odata/1.2.8/odata.es5.umd.bundle.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-sp/1.2.8/sp.es5.umd.bundle.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-sp-clientsvc/1.2.8/sp-clientsvc.es5.umd.bundle.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-sp-taxonomy/1.2.8/sp-taxonomy.es5.umd.bundle.min.js" ></script>
```

`pnpjs.es5.umd.bundle.min.js` includes the following packages: `common.es5.umd.bundle.min.js`, `logging.es5.umd.bundle.min.js`, `odata.es5.umd.bundle.min.js`, and `sp.es5.umd.bundle.min.js`. No need to load twice.

Also, it's better to never mix different versions for peer packages (e.g. 1.2.7 and 1.2.8. etc.).

**Comment by unnieayilliath** [comment]
Thanks @koltyakov  `'@pnp/sp-taxonomy': ['window', 'pnp.sp-taxonomy'],` did the trick. thanks for the additional guidance, much appreciated!
