### ISSUE TITLE
Bug within SharePoint REST API with managed metadata that affects pnpjs utilities/documentation

### ISSUE THREAD

**Issue by jhholm** [pnp/pnpjs#470]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.8]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

### Expected / Desired Behavior / Question
When updating a list item with multiple taxonomy fields and updating a single taxonomy field within that item with [pnpjs taxonomy utilities](https://github.com/pnp/pnpjs/blob/dev/packages/sp-taxonomy/docs/utilities.md), SharePoint Search should return all taxonomy field data in managed properties.

### Observed Behavior
When updating a list item with multiple taxonomy fields and updating a single taxonomy field with [pnpjs taxonomy utilities](https://github.com/pnp/pnpjs/blob/dev/packages/sp-taxonomy/docs/utilities.md), SharePoint Online search only returns the taxonomy fields that were updated in the update call. In this case the single taxonomy field.

### Steps to Reproduce
1. Create a team site
2. Create a new content type inheriting from item in the team site
3. Add two new Managed Metadata site columns to the created content type (e.g. named TEST_MM_1 and TEST_MM_2) with customized term set. You can use single value managed metadata field.
4. Add terms to the customized term sets via Term Store Management
5. Create a new custom list
6. Configure the list to allow management of content types (Advanced settings - Allow management of content types
7. Add the created content type to the list
8. Add a new item with added content type and fill in both the managed metadata fields
9. Wait for sharepoint search crawl to commence
10. Use e.g. [SharePoint Search Query Tool](https://github.com/SharePoint/PnP-Tools/tree/master/Solutions/SharePoint.Search.QueryTool) to check that the automatically created managed properties owstaxIdTESTMM1 and owstaxIdTESTMM2 have values. Note that with automatically created managed properties, the managed properties need to be case sensitive when used as selectproperties in a search query.
11. Update the created items one managed metadata field as described in [here](https://github.com/pnp/pnpjs/blob/dev/packages/sp-taxonomy/docs/utilities.md).
12. Optional: You can also update the list item title field as documented [here](https://github.com/pnp/pnpjs/blob/dev/packages/sp/docs/items.md#Update). Makes it easier for you to check when sharepoint search has done it's crawling magic.
13. Wait for SharePoint search crawl the changes
14. Check via SharePoint Search Query Tool that you can only get the other owstaxIdTESTMM# managed property value for that item.

### Description of issue

Basically this seems to be an issue on SharePoint Online REST API update method what the taxonomy utility is using. So technically it's not a bug within pnpjs, but the documentation should note that you should not use the update api to update managed metadata fields if you need search functionality. 

### Circumvention of issue
1. When doing updates on an item with taxonomy fields, you can use the update API, but you should always update all managed metadata fields in the same update call to keep search intact.
2. Use item.updateValidateUpdateListItem -method, which SharePoint Online modern list forms seem to use internally. This does not cause the aforementioned issue and will also fix a broken item in search to return all taxonomy managed properties.

### Further information to consider
I've opened a service request to notify Microsoft about this bug, but it might take a while as my development tenant is not a premier support tenant. I've managed to reproduce this in 3 different tenants already. I should be able to produce pnp schemas to simplify the creation of a test case if required. Would like to hear if you can reproduce this easily. 

I would recommend updating the documentation about these "gotchas" that a SharePoint developer just "has to know" when doing development.

In general the "old-school" REST API's for getting an item and updating an item seem to be problematic when it comes to working with taxonomy fields. Item.get() will not return the managed metadata labels, but for some odd reason the WssId as the label. You can see the same odd behaviour when filtering taxonomy fields in a modern list view.

In my day to day development I try to avoid using item.add, item.get and item.update completely. I've noticed that using list.addValidateUpdateItemUsingPath, list.renderListDataAsStream and item.validateUpdateListItem cause no/less issues.

**Comment by jhholm** [comment]
This also seems to only affect the ows_taxId_TEST_MM_# crawled property, as ows_TEST_MM_# crawled property still seems to work after updating a taxonomy field via update API. If you are e.g. using the taxonomy label as a refiner (RefinableStringXX), you won't notice the issue and Search will get all (updated and not updated) labels correctly.

**Comment by patrick-rodgers** [comment]
Hi @jhholm - thank you for the detailed description of the issue you have found. As you noted this doesn't appear to be an issue with this library, so we don't have any actions to take.

Documenting all the possible "gotchas" in SharePoint development falls well outside of the scope of this library.

You can report this as well to the [sp-dev-docs](https://github.com/sharepoint/sp-dev-docs/issues) issue list which is monitored by the SP engineering team.
