### ISSUE TITLE
Getting Parent Site Context

### ISSUE THREAD

**Issue by jcosta33** [pnp/pnpjs#471]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.8]

Please specify what version(s) of SharePoint you are targeting: [O365, Modern pages]

### Expected / Desired Behavior / Question
Is there a way to get the parent site's context? I was trying to use the getParentWeb method but it doesn't seem to return the context. I'd like to be able to recursively get the parentWeb until I hit the root site. I was planning to do this by getting the parent web and loading its context into the sp.setup() method so that I could evoke it again to keep going back. Is there a way to do this?

Thanks!

**Comment by koltyakov** [comment]
Hi @jcosta33,

Looks like using implicit Web/Site object creations is what you're looking for.

```typescript
import { Web } from '@pnp/sp';
const web = new Web('[WEB_ABSOLUTE_URL]');
```

**Comment by jcosta33** [comment]
Hi @koltyakov!

Thank you! I'll give that one a go :)

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Please open a new issue should you still require assistance. Thanks!
