### ISSUE TITLE
sp.web.allProperties return type is SharePointQueryableCollection instead of SharePointQueryable

### ISSUE THREAD

**Issue by AJIXuMuK** [pnp/pnpjs#476]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.8]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
`sp.web.allProperties` should be defined in code to return object instead of collection
### Observed Behavior
```typescript
/**
 * Allows access to the web's all properties collection
 */
readonly allProperties: SharePointQueryableCollection;
```

But result of the request is an object with key-value pairs.

### Steps to Reproduce
In SPFx web part:
```typescript
protected async onInit(): Promise<void> {
    sp.setup({
      spfxContext: this.context
    });

    const props = await sp.web.allProperties.get();
    console.log(props);

    return super.onInit();
  }
```

**Comment by patrick-rodgers** [comment]
On the server it is represented as a collection. What is broken with the current implementation?

**Comment by AJIXuMuK** [comment]
It is represented as a [hashtable](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/ms443280(v=office.15))

And `_api/web/allProperties` result looks like that:
<img width="1270" alt="screen shot 2019-01-22 at 9 18 44 pm" src="https://user-images.githubusercontent.com/17036219/51584697-5103c600-1e8b-11e9-97c0-ba85582b636e.png">
