### ISSUE TITLE
Using PnP.js to Login to Sharepoint as a User

### ISSUE THREAD

**Issue by Michael5011st** [pnp/pnpjs#481]
### Category
- [ ] Enhancement
- [ ] Bug
- [X ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [current ]
Please specify what version(s) of SharePoint you are targeting: [    Sharepoint Online     ]

###Question
Hello, I was wondering if it is possible to do this type of behavior, https://www.vrdmn.com/2018/05/spfx-calling-back-to-sharepoint-from.html, using pnp.js,

**Comment by patrick-rodgers** [comment]
@simonagren just published a blog post [similar to this topic](https://simonagren.github.io/intro-durable/) and there exist options external to the library for [authorizing as a user](https://github.com/SharePoint-NodeJS/pnp-auth). Can you share where you are stuck in the process and we can provide a bit more targeted guidance. Thanks!

**Comment by Michael5011st** [comment]
Hello, thank you for the suggested ready. That blog was able to answer the question I had,
