### ISSUE TITLE
Can I use the Config-Store to provide data from an extension to webparts on the page?

### ISSUE THREAD

**Issue by Arknev** [pnp/pnpjs#483]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Latest

### Expected / Desired Behavior / Question

In my site collection I have a role based security app that we use to assign roles to authenticated users which determines what they can do in our solutions. Getting the configuration for the current user in an Extension seems like the best choice. Then I need to make the data available for custom webparts on the page to implement business rules. Thus, can I leverage the config-store module to store values and consume them in my custom webparts? This would allow me to handle the user role logic per site in one place and take advantage of caching while having a single set of props available in my webparts.

**Comment by patrick-rodgers** [comment]
I am not 100% on what you are trying to do - but the config store is a simple key/value store which can optionally be loaded from a SharePoint list. It does not contain anything to determine per-user config or provide a way to hook into it outside of the current closure (per control). Currently there is also not a functionality to write back to the store from the config-store (though you can use standard SP operations) - however we do have an open request for that #407.

You can use the module to load a shared set of configuration values. If you have per-user configuration the SharePoint profile might be a better place to store those.

**Comment by Arknev** [comment]
I see what you are saying. I was wondering if it would be possible to add and set keys/values via settings.Add and settings.AddJSON, while taking advantage of the caching, all in an extension. Then have those settings available for consumption in any custom WebPart on the page. It sounds like that isn't the intent of this module at this time. Thanks for the info.
