### ISSUE TITLE
Support for SP.RemoteWeb

### ISSUE THREAD

**Issue by hugoabernier** [pnp/pnpjs#485]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.8]

Please specify what version(s) of SharePoint you are targeting: [Office 365]

### Expected / Desired Behavior / Question
The PnPJs libraries are amazing, and I feel like a spoiled brat for asking this, but it would be great to add support for SP.RemoteWeb.

Example scenario: need to add support to get Web or Lists from another site collection.

### Observed Behavior
No such support at this time. Using a separate site collection url in PnP code results in a 404.

### Steps to Reproduce
1. Follow steps to (open a web directly)[https://pnp.github.io/pnpjs/sp/docs/webs/#get-a-web-directly].
2. Use your OneDrive url as the web url
3. Get a 404 error.
4. Rewrite the query to use SPHttpRequest and use (YourAbsoluteSiteUrl)/_api/SP.RemoteWeb(@a1)/Web/Lists, passing your OneDrive url as @a1.
5. Get results.

I'd be happy to contribute if it helps.

**Comment by patrick-rodgers** [comment]
Thanks for the idea, we'll have a look.

**Comment by patrick-rodgers** [comment]
Finally having a chance to circle back and look into this. When I test what you did above `(YourAbsoluteSiteUrl)/_api/SP.RemoteWeb(@A1)/Web/Lists` the results I get back are a bit broken. For example the url I get for an entity is based on the current web I am in:

https://tenant.sharepoint.com/sites/dev/_api/Web/Lists(guid'837e6e3e-6891-460d-9994-b4c3ecef365c')

It also appears to be designed primarily as a sharing mechanism for OneDrive, not as a way to access other webs as remote with full capabilities. There are a set of client callable methods on SPRemoteWeb class:

- public SPFile GetFileByServerRelativeUrl(string serverRelativeFileUrl)
- public SPList GetListById(Guid listGuid)
- public SPList GetListByServerRelativeUrl(string serverRelativeUrl)
- public SPFolder GetFolderByServerRelativeUrl(string serverRelativeUrl)
- public SPGroup GetGroupById(int groupId)
- public bool CanSendEmail (readonly property)
- public bool ShareByEmailEnabled (readonly property)
- public bool ShareByLinkEnabled (readonly property)

Given these constraints is this still useful to you? If we built this out we couldn't provide you the full API to a remote site in perhaps the way you might have imagined.

**Comment by patrick-rodgers** [comment]
@hugoabernier - heard you say in the call that you opened an issue but we didn't implement it. Did you have a chance to review my findings above and respond?

**Comment by hugoabernier** [comment]
@patrick-rodgers sorry, I didn't mean to imply you didn't do anything about it :-), but I have to admit I didn't notice your response. 

I'll have to test, but I could have sworn I used the SP.RemoteWeb api to access content from one site to another. When I wrote the suggestion, that was how I imagined people using it.

If the RemoteWeb api is limited to OneDrive, it may be less useful than I anticipated.

Why don't we wait and see if anyone else has a need for it?

I'm still happy to take this on, if anyone wants it. If there are other priorities, feel free to reach out to me and I'll help wherever I can.

By the way, thanks for the awesome library and empowering the community!

**Comment by patrick-rodgers** [comment]
Going to close this. If you or someone wants to submit a PR for remote webs we will absolutely accept it - but for now not something we plan to implement.

I think it sorta works to call some things using remote web, but I am not sure where it would start to break down, so I am hesitant to implement it at this time.
