### ISSUE TITLE
hubSiteData question

### ISSUE THREAD

**Issue by simonagren** [pnp/pnpjs#487]
### Category
- [X] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

@patrick-rodgers @koltyakov I'm not used working within the `sp`package so I'm asking first :)

It seems we are missing some commands regarding HubSites.
_api/HubSites
_api/HubSites/GetById
And also the web/HubSiteData seems to return a `Promise<void>`.

So do you have any suggestions, should we make a HubSite.ts and create Types for HubSite and HubSiteData?

**Comment by patrick-rodgers** [comment]
I haven't looked at hub sites specifically. As always, if there is missing coverage that makes sense to add (ie folks want to use it) than I support adding it. Yes, I would think as well it makes sense to update the Promise to give some indication of what comes back there as it isn't void.

**Comment by simonagren** [comment]
If I would make a PR, could you have a look at it and decide if it's in the ballpark.
And if needed do some changes/point me in the right direction?

**Comment by patrick-rodgers** [comment]
Sure, that works for me.
