### ISSUE TITLE
Getting "Access Denied" error for UserHasPermissions query in PnP SP

### ISSUE THREAD

**Issue by AnjaniChallamcherla** [pnp/pnpjs#489]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [  ] Bug
- [ ] Question
- [ ] Documentation gap/issue

Hi All,
I am getting an Intermittent error while checking userHasPermissions.
Some times it is working fine, some times it is throwing error.
This is my code:
```
await sp.web.userHasPermissions("i:0#.f|membership|" + this.props.currentUserEmail, PermissionKind.ManageLists).then(perms => {
userPerm = perms;
console.log('userMail ' + this.props.currentUserEmail + ' UserPerm ' + userPerm);
}).catch(e => console.log(e.message));
```

Somebody please help
![image](https://user-images.githubusercontent.com/42473451/52226342-94efc580-28a4-11e9-9d6e-05d6d1ef71c0.png)

### Expected / Desired Behavior / Question
It should display data if user have permissions

### Observed Behavior
Some times it is working fine, some times it is throwing error. After some time if i refresh the page then it is working fine. 

### Steps to Reproduce
Reloading the page multiple times

**Comment by AnjaniChallamcherla** [comment]
Yes, my code is running inside spfx and I called the setup function. Also different people with different permissions (Full Control, Edit and Read) are trying to access the web part. 
Some times the web part works fine but after refreshing the page multiple times it is throwing "Access Denied" error and then after some time it works fine.

**Comment by patrick-rodgers** [comment]
Hi @AnjaniChallamcherla - if folks without the necessary permissions try and execute a request the will get access denied. I don't see this as a problem with the library, but if you can provide a repository we can clone that reproduces the behavior consistently _with_ a user that has the correct permissions we can take a look.

**Comment by AnjaniChallamcherla** [comment]
Hi @patrick-rodgers, Thank you for your quick response.
One quick question, does "userHasPermissions" function work fine for users who have Edit/Read access to the site.
I have been testing my spfx solution from morning, I didn't get the error. Not sure whether the error got fixed itself or it will come in the future.

**Comment by AnjaniChallamcherla** [comment]
Hi @patrick-rodgers,
I created a spfx web part which queries **userHasPermissions** only. Below is the link of the web part:
https://github.com/AnjaniChallamcherla/checkPermissions

I published the web part and tested with a user who is in Site Members group (Edit access). Initially it worked fine but after refreshing the page multiple times it got **Access Denied** error.  

Please help

**Comment by koltyakov** [comment]
Hi @AnjaniChallamcherla,

Please treat sp.web.userHasPermissions as an admin endpoint, as users with lack of permissions should not have permissions to check other persons rights.

Luckily, there should be an alternative for current user option. Let me suggest a possible solution:

```typescript
import { sp, List, PermissionKind } from '@pnp/sp';

sp.web.select('EffectiveBasePermissions').get()
    .then(({ EffectiveBasePermissions }) => {
        return sp.web.hasPermissions(EffectiveBasePermissions, PermissionKind.ManageLists);
    })
    .then(hasPermissions => {
        console.log(hasPermissions ? 'Good to go...' : 'No way buddy!');
    })
    .catch(console.warn)
```

This should work for ordinary users as well.

**Comment by AnjaniChallamcherla** [comment]
Hi @koltyakov,
Thank you so much for your response.
The code you provided worked perfectly well.
I think it will be great if you add that **sp.web.userHasPermissions is for admins** in https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Permissions


Thank you once again, Appreciate your valuable responses.
