### ISSUE TITLE
Retrieve column value (page property) by site ID from Site Pages list

### ISSUE THREAD

**Issue by DigitalSa1nt** [pnp/pnpjs#491]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [Latest ]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

### Question

apologies for the likely silly question, but I've been unable to find an answer that makes sense, or at least one that marries up with my understanding of the SharePoint terminology.

I'm trying to get access to Page Properties from within an SPfx Extension and I'm not entirely sure how to go about it, at first I thought I could query it using something like:

var list = await pnp.sp.web.lists.getByTitle("Site Pages").get();

then I could simply find the row by the Site Page ID that I'd get using:

var idString: string = this.context.pageContext.listItem.id.toString();

and then knowing the column names:

'FooterLink1', 'FooterLink2', 'FooterLink3'.

I could then pull out the hyperlink and create my footers link menu with this information.

Am I missing something because the pnp library returns a 404 not found.

**Comment by simonagren** [comment]
@DigitalSa1nt 
I'm not sure I understand. When do you get a 404?
Which code are you using then?

**Comment by DigitalSa1nt** [comment]
> @DigitalSa1nt
> I'm not sure I understand. When do you get a 404?
> Which code are you using then?

pnp.sp.web.lists.getByTitle("Site Pages").get(); 

I'm looking at the network calls in the Chrome debugger, and the call that this makes returns a 404 not found, which I am assuming is because it can't find the list 'Site Pages' That's all I'm trying to do really.

**Comment by simonagren** [comment]
Hmm, can you see which url is being used? Do you have Fiddler?
I just tried this and it worked fine for me:
```TypeScript
 import pnp from "@pnp/pnpjs";

(async () => {
const list = await pnp.sp.web.lists.getByTitle("Site Pages").get();
console.log(list);
})()
```

How do you use your code, SharePoint Framework, Script editor etc?

**Comment by DigitalSa1nt** [comment]
> Hmm, can you see which url is being used? Do you have Fiddler?
> I just tried this and it worked fine for me:
> 
> ```ts
>  import pnp from "@pnp/pnpjs";
> 
> (async () => {
> const list = await pnp.sp.web.lists.getByTitle("Site Pages").get();
> console.log(list);
> })()
> ```
> 
> How do you use your code, SharePoint Framework, Script editor etc?

i'm using the SPfx template within VS2017 creating an extension. The URL looks like this:

https://[tenant].sharepoint.com/sites/[CollectionName]/_api/web/lists/getbytitle(%22Site%20Pages%22)/items(6)

I've just removed the tenant and site name from the above, but the structure doesn't look quite right so I'm guessing that's what is throwing back 400/404 errors?

**Comment by DigitalSa1nt** [comment]
> Ok, I personaly like to use the
> `import { sp } from "@pnp/sp";`
> 
> I think you are missing the [setup](https://pnp.github.io/pnpjs/documentation/getting-started/#getting-started-with-sharepoint-framework) step?
> 
> Check out the link but here's an example where you setup with the Extensions context in the "onInit" of the extension:
> 
> ```ts
> import { sp } from "@pnp/sp";
> 
> // ...
> 
> public onInit(): Promise<void> {
> 
>   return super.onInit().then(_ => {
> 
>     // other init code may be present
> 
>     sp.setup({
>       spfxContext: this.context
>     });
>   });
> }
> ```

Thank you that solved my problem, I was using the same setup that I used for caching etc. That seemed to work without passing in the context the way you do it above. But adding your suggestion into the following worked for me:

```
pnp.setup({
	defaultCachingStore: "session",
	spfxContext: this.context,
	defaultCachingTimeoutSeconds: 900, //15min
	globalCacheDisable: true // true to disable caching in case of debugging/testing
});

pnp.sp.web.lists.getById(this.context.pageContext.list.id.toString())
	.items.getById(this.context.pageContext.listItem.id)
	.select("FooterLink1", "FooterLink2", "FooterLink3", "FooterLink4")
	.get()
	.then(d => {
		console.log(d);
		// do stuff using the received data
});
```
