### ISSUE TITLE
SP Search modern pages commentscount & likes count

### ISSUE THREAD

**Issue by jonathanhotono** [pnp/pnpjs#493]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

Just a quick question on search querying for modern page likes count & comments count. I can't seem to find the correct managed property for both at all as all managed property returned 0 counts.
![image](https://user-images.githubusercontent.com/6864547/52317973-714c8c80-2a16-11e9-81c4-e1c6309618ce.png)
![image](https://user-images.githubusercontent.com/6864547/52317993-84f7f300-2a16-11e9-9ed5-7f49de71daa9.png)

Does it mean that I have to make additional query again just to get each items likes/comments count?
https://pnp.github.io/pnpjs/sp/docs/comments-likes/

**Comment by patrick-rodgers** [comment]
Hi @jonathanhotono - this appears to be a general development questions not specific to this library. Would encourage you to ask it in the [Microsoft Tech Community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) or [StackOverflow](https://stackoverflow.com/questions/tagged/sharepoint). Please understand we can't scale to handle all development questions. Thank you for your interest in pnpjs!
