### ISSUE TITLE
Update Modern Site Page page banner image and title using pnpjs

### ISSUE THREAD

**Issue by aakashbhardwaj619** [pnp/pnpjs#494]
**Category**
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

When provisioning a new site page using the ClientSidePage.create() method is there any way to set a default Title and banner image for the new page through code at the time of provisioning?

### Version

Please specify what version of the library you are using: @pnp/sp 1.2.7

Please specify what version(s) of SharePoint you are targeting: SharePoint Online

**Comment by patrick-rodgers** [comment]
Not currently, but that seems like something we could add pretty easily.

**Comment by aakashbhardwaj619** [comment]
Thanks for the quick response. It would be really helpful if we could get the provision to update the modern page banner image as well as other properties of the PageTitle web part like Title, Text above Title, Title alignment, etc. through pnpjs. Any idea by when we can expect this to be rolled out?

**Comment by patrick-rodgers** [comment]
LOL, so you increased what you are asking for and now asking for a timeline? Did you have some time to contribute to add this functionality?

**Comment by aakashbhardwaj619** [comment]
I apologize if my question came out the wrong way but my intention was to know if any development of such sorts was in the roadmap.

I appreciate the great work you guys are doing.

**Comment by simonagren** [comment]
As @patrick-rodgers we/you could look at implementing some helper commands.
As far as I know you set these values via the list item, and the look of the "banner" is primarilly set via the `LayoutWebpartsContent`property.
And there's a lot of HTML in that property, so I would handle it with care.

Here's an example where you could set some properties of the list item, and you might be able to experiement with these and find something.

```TypeScript
//So you have your page from create()
const page = ......

const item:any = await page.getItem();
const updRes = await item.update({
    Title: 'PnPJsTitle',
    OData__TopicHeader: 'PnPJs',
    BannerImageUrl: { Description: "Some Description",
Url: "https://<tenant>.sharepoint.com/sites/test3/Images1/pnp-pnpjs-600.png" }
});
console.log(updRes);
```

**Comment by aakashbhardwaj619** [comment]
Thanks for your help @simonagren. I wrote the below code to update the banner properties of a newly provisioned ClientSidePage. I accessed the maintenance mode of a modern page with banner image and got the JSON value for its data/ properties. Then I encoded the JSON string and assigned its value to the data-sp-controldata attribute in LayoutWebPartsContent property.

    newPage.getItem().then((newPageItem) => { //newPage is the ClientSidePage
      let layoutWebPartsContentJson = {
        "id": "cbe7b0a9-3504-44dd-a3a3-0e5cacd07788",
        "instanceId": "cbe7b0a9-3504-44dd-a3a3-0e5cacd07788",
        "title": "Title Region",
        "description": "Title Region Description",
        "serverProcessedContent": {
          "htmlStrings": {},
          "searchablePlainTexts": {},
          "imageSources": {
            "imageSource": myImageUrl //the new banner image URL
          },
          "links": {},
          "customMetadata": {}
        },
        "dataVersion": "1.4",
        "properties": {
          "title": myBannerTitle, //the new banner title
          "imageSourceType": 2,
          "layoutType": "FullWidthImage",
          "textAlignment": "Left",
          "showTopicHeader": true,
          "showPublishDate": false,
          "topicHeader": null,
          "authorByline": null,
          "authors": [],
          "altText": "",
          "translateX": 49.92307692307693,
          "translateY": 46.49122807017544
        }
      };

      var layoutWebPartsContentString = JSON.stringify(layoutWebPartsContentJson);
      layoutWebPartsContentString = layoutWebPartsContentString.replace(/:/gmi, '&#58;').replace(/{/gmi, '&#123;').replace(/}/gmi, '&#125;').replace(/"/gmi, '&quot;');
      let layoutWebPartsContentValue = '<div><div data-sp-canvascontrol="" data-sp-canvasdataversion="1.4" data-sp-controldata="'+layoutWebPartsContentString+'"></div></div>';
      newPageItem.update({
        LayoutWebpartsContent: layoutWebPartsContentValue,
        OData__TopicHeader: myTopicHeader //the new banner text above title header
      }).then(() => {
        console.log('Banner properties updated');
      });
    });
