### ISSUE TITLE
batch.execute is not resolving

### ISSUE THREAD

**Issue by hafeez1042** [pnp/pnpjs#497]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  1.2.8 ]

Please specify what version(s) of SharePoint you are targeting: [ Sharepoint online ]

### Expected / Desired Behavior / Question
batch.execute() as a promise should resolve or reject

### Observed Behavior
not resolving or rejecting the promise.

### Steps to Reproduce
Add items to a list as batch

_Solved by downgrading to 1.2.1_

**Comment by koltyakov** [comment]
Thanks for reporting! We know about an issue, it's a duplicate https://github.com/pnp/pnpjs/issues/468

**Comment by patrick-rodgers** [comment]
Closing this as duplicate.
