### ISSUE TITLE
Cannot upgrade typescript version in package-lock.json

### ISSUE THREAD

**Issue by foofaraw** [pnp/pnpjs#498]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [X] Documentation gap/issue

### Version
Please specify what version of the library you are using: [1.2.8]

Please specify what version(s) of SharePoint you are targeting: [SP16 on-prem]

### Expected / Desired Behavior / Question
I'm trying to upgrade from TypeScript 2.2.2 to 2.4.2 as mention in the [documentation](https://pnp.github.io/pnpjs/documentation/SPFx-On-Premesis-2016/) for SharePoint 2016 on-premises.

### Observed Behavior
I change the version of typescript and the block of code as specified in the documentation, but after running npm install TypeScript version in package-lock.json file is getting changed back to ~2.2.2.

**Comment by patrick-rodgers** [comment]
When you run `npm list typescript` what is the result?

**Comment by foofaraw** [comment]
![screenshot 2019-02-08 at 17 34 24](https://user-images.githubusercontent.com/24656920/52491654-ddbabd80-2bc7-11e9-9c89-990cea1ba339.png)

This is how dependencies look by default for `gulp-core-build-typescript` package.

![screenshot 2019-02-08 at 17 36 39](https://user-images.githubusercontent.com/24656920/52491792-2ecab180-2bc8-11e9-9989-7338e517d511.png)

There is also another module listed as dependency directly to the whole web part.

![screenshot 2019-02-08 at 17 38 04](https://user-images.githubusercontent.com/24656920/52492041-badcd900-2bc8-11e9-8c08-664f709b695c.png)

**Comment by patrick-rodgers** [comment]
It looks like you've missed updating one of the locations. Can you ensure you have updated all the typescript references and removed node_modules and reinstalled?

**Comment by foofaraw** [comment]
Yes, I change all occurrences to 2.4.2, remove node_modules, run `npm install` and typescript version under `gulp-core-build-typescript` is changed back to `"typescript": ~2.2.2`

**Comment by patrick-rodgers** [comment]
Have you resolved this issue? Have retested the instructions from the docs and they appear to work for me.

**Comment by patrick-rodgers** [comment]
Going to close this due to inactivity, also with the latest version of SPFx you can use any version of TypeScript you want so this should no longer be an issue for folks.

**Comment by pensphreak** [comment]
Has this issue ever been resolved? It still happens to me

**Comment by ncmadhan1989** [comment]
Change everywhere to 2.2.4 and download the zip file of 2.2.4 and replace in nodemodules hope this will helps you

**Comment by pensphreak** [comment]
I did that, then I remove node_modules and npm install again.  package-lock.json updates itself again to 2.2.2 and the problem continues

**Comment by ncmadhan1989** [comment]
Dont use npm install,just follow what i said,change 2.2.4 everywhere in pakage lock.json and download 2.2.4 zip files and replace in nodemodules folder
