### ISSUE TITLE
Question regarding classes and Graph package development

### ISSUE THREAD

**Issue by simonagren** [pnp/pnpjs#501]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

@patrick-rodgers @koltyakov  I'm currently working with the "SharePoint" functionality of the Graph, and then we get duplicate classes (sp package)  ex: List, Lists...

How would you suggest I handle this, should I just rename the classes. Because we don't want the sp package dependency in the graph and we also want GraphQueryables.

**Comment by patrick-rodgers** [comment]
We do not want to have sp dependencies in graph. If the names are the same they will collide in the pnpjs rollup library. I don't have a great suggestion, but something like GraphList or GraphSPList maybe.

**Comment by simonagren** [comment]
Yeah. I went with SPList initially. But Maybe Graph is better to be more consistant, like the internals 😀

**Comment by patrick-rodgers** [comment]
Are we good to close this?

**Comment by simonagren** [comment]
Indeed! You can check out the PR if you want

**Comment by patrick-rodgers** [comment]
Right on, thanks! Will check it out.
