### ISSUE TITLE
orderBy doesn't work - $orderBy parameter is not added to the query string

### ISSUE THREAD

**Issue by AJIXuMuK** [pnp/pnpjs#505]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.9]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
`orderBy` in list items request works correctly
### Observed Behavior
`$orderBy` parameter is not added to the query string
### Steps to Reproduce
```typescript
sp.web.lists.getByTitle('somelist').items.orderBy('Title').getAll();
```
the resulting request:
```
https://tenant.sharepoint.com/sites/Test/_api/web/lists/getByTitle('somelist')/items?$top=2000
```

**Comment by koltyakov** [comment]
It's not a bug, Alex (@AJIXuMuK), this is by design. Check this for details https://github.com/pnp/pnpjs/issues/499

**Comment by AJIXuMuK** [comment]
True, my bad!

I've used that for small list :)
