### ISSUE TITLE
Issue with ShareObject

### ISSUE THREAD

**Issue by kabdul-rightpoint** [pnp/pnpjs#507]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.0.10  ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online  ]

I'm working on setting up sharing (by external email) on folders(which internally has subfolders). It works in one environment but not in the other. Both have same sharing settings at the admin level. I get the error "Couldn't resolve user xxx@xxx.com". The same code works for the same email id on another tenant. Any ideas?

![sharing_issue](https://user-images.githubusercontent.com/46936470/52814999-24defd80-3063-11e9-9ca6-bdd324de0dd5.png)

**Comment by patrick-rodgers** [comment]
As you are getting back an error from the server it seems like it would be a configuration thing with external sharing in one of the tenants. There wouldn't be any difference in the code running - not sure how we can help.

Here are two articles on sharing, perhaps they can help point you to the missing config option blocking you:

- [Share SharePoint files or folders](https://support.office.com/en-us/article/share-sharepoint-files-or-folders-1fe37332-0f9a-4719-970e-d2578da4941c)
- [Sharing and permissions in the SharePoint modern experience](https://docs.microsoft.com/en-us/sharepoint/sharing-permissions-modern-experience)

**Comment by patrick-rodgers** [comment]
Going to close this as it doesn't appear to be an issue with the library. Please open a new issue and reference this one if you believe there is an issue in the library preventing sharing from working. Thanks!
