### ISSUE TITLE
Support site collection app catalogs

### ISSUE THREAD

**Issue by pedro-pedrosa** [pnp/pnpjs#508]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.9]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
Add support for site collection app catalogs as noted [here](https://docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins).

> ALM APIs are also supported for the site collection app catalog. URLs for the site collection app catalog operations are exactly the same, but you can change the tenantappcatalog to sitecollectionappcatalog.

I suppose a boolean flag for `Web.getAppCatalog()` discriminating between tenant/site-collection catalogs would be enough.

**Comment by patrick-rodgers** [comment]
Added this into the #533 PR. New method getSiteCollectionAppCatalog added to web.
