### ISSUE TITLE
Azure Web App (Angular) not working with SPFetchClient

### ISSUE THREAD

**Issue by gonadn** [pnp/pnpjs#509]
### Category
- [ ] Enhancement
- [ ] Bug
- [*] Question
- [ ] Documentation gap/issue

PnP Version: [    
 "@pnp/common": "^1.2.9",
    "@pnp/graph": "^1.2.9",
    "@pnp/logging": "^1.2.9",
    "@pnp/nodejs": "^1.2.9",
    "@pnp/odata": "^1.2.9",
    "@pnp/sp": "^1.2.9",
     ]

Iam creating Angular (Angular-cli) application hosting on Azure as Azure App Service (WebApp) .
And i want to access data in SharePoint from Angular application using @pnp/nodejs ,
![image](https://user-images.githubusercontent.com/3224441/52905420-64137700-323a-11e9-9c54-15713d1d5caa.png)

when i add code below in my .ts constructor() i get a bunch of errors in console:
![image](https://user-images.githubusercontent.com/3224441/52905452-b359a780-323a-11e9-966c-ad4b3c3bb9f0.png)

Errors i get:
![image](https://user-images.githubusercontent.com/3224441/52905468-ca989500-323a-11e9-9780-35a006834a88.png)

Anyone had this issue, or am i doing something wrong here?
How can i access data in SharePoint from an application hosted in Azure as a App Service (WebApp) ?

**Comment by simonagren** [comment]
This seems to have to do with Angular CLI and Crypto and some changes to how Crypto is being/not being used anymore.

Check out this comment on how you might be able to solve it:
https://github.com/angular/angular-cli/issues/1548#issuecomment-450891241

**Comment by gonadn** [comment]
hi @simonagren , thanks for your time, i tried the solution descriebed in the article you refer to...

The fix/solution:
![image](https://user-images.githubusercontent.com/3224441/52913755-78e71d80-32c1-11e9-8695-e71dff2cc7ff.png)

i got rid of all errors with "crypto", but got another error:
![image](https://user-images.githubusercontent.com/3224441/52913802-b6e44180-32c1-11e9-8f56-2215d108740d.png)

**Comment by gonadn** [comment]
the solution was to add net: 'empty' and tyld: 'empty' to web.config.js , as described here: [link](https://github.com/request/request/issues/1691)
your link #1529 had the solution: I needed to add polyfills for node stuff in webpack.config.js, like this:

```
config.node = {
  console: 'empty',
  fs: 'empty',
  net: 'empty',
  tls: 'empty'
}
```
Thanks a lot!

**Comment by simonagren** [comment]
Was gonna write that one first, but I dint't think it did the trick, haha. @gonadn could you close the issue?

**Comment by gonadn** [comment]
thanks to @simonagren  for refering to article witch helped to fix the issue... 💯
