### ISSUE TITLE
Webpart not added to ClientSidePage

### ISSUE THREAD

**Issue by RodCoder** [pnp/pnpjs#510]
### Category
- [ ] Enhancement
- [x ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version 1.2.9

Please specify what version of the library you are using: @pnp/sp

Please specify what version(s) of SharePoint you are targeting:  SharePoint Online

### Expected Behaviour
Modern page is created with the components inside.

### Observed Behavior
Modern page is created but no sections, columns and controls are added.

### Steps to Reproduce
Create new page:
const newsPage: ClientSidePage = await web.addClientSidePage(`${this.state.pageName}.aspx`);

Add sections and columns:
let mainSection = newsPage.addSection();
let leftColumn = mainSection.addColumn(8);
let rightColumn = mainSection.addColumn(4);

Add a control:
leftColumn.addControl(new ClientSideText("Hello! This is a news page template"));

Save page:
newsPage.save();

Debugging:
let newsItem = await newsPage.getItem();
console.log(newsItem); ---> We can observe that newsItem has the 'CanvasContent1' null

### Additional
If testing in SPEditor, here's the full code:

import { sp, ClientSideText } from "@pnp/sp";

sp.web.addClientSidePage('testinconsole.aspx').then(page => {
    let mainSection = page.addSection();
    let leftColumn = mainSection.addColumn(8);
    let rightColumn = mainSection.addColumn(4);

    leftColumn.addControl(new ClientSideText("Hello! This is a news page template"));

    page.save().then(result => {
        console.log(result);
    })
});

**Comment by koltyakov** [comment]
Duplicate https://github.com/pnp/pnpjs/issues/504
