### ISSUE TITLE
Not able to add clientside components in a site page using @pnp/sp

### ISSUE THREAD

**Issue by UdayaMS** [pnp/pnpjs#512]
I am not able to add clientside component in an existing modern page, the code used to work before but now when i check the same code is not working, i tried installing the latest pnp/sp package but no luck.

### Category
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

1.2.9   @pnp/sp@1.2.9

Please specify what version(s) of SharePoint you are targeting: [  SharePoint Online ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
After running the code the component should be in the page.

### Observed Behavior
Can see only a blank page without any controls added using the following code.

let web = new Web("<site url>");    

    
    const page = await web.addClientSidePageByPath(`New.aspx`, "<site collection relatinve url>/SitePages","New");    
    
    await page.checkout();  

    page.addSection().addControl(new ClientSideText("@pnp/sp is a great library!"));
    page.addSection().addControl(new ClientSideText("@pnp/sp is a great library!1"));
    page.addSection().addControl(new ClientSideText("@pnp/sp is a great library!2"));
    page.addSection().addControl(new ClientSideText("@pnp/sp is a great library!3"));
    
    page.save();

**Comment by koltyakov** [comment]
Duplicate https://github.com/pnp/pnpjs/issues/504
