### ISSUE TITLE
Not able to deploy SPFx webpart in Sharepoint 2019 onprem

### ISSUE THREAD

**Issue by krishnavandanapu** [pnp/pnpjs#515]
Hi All,

I have setup SharePoint 2019 on-prem and getting the below error when I am trying to deploy SPFx webpart control as part of the catalog:

**There were errors when validating the App manifest.: Xml Validation Exception: 'The 'IsClientSideSolution' attribute is not declared.' on line '1', position '249'., Xml Validation Exception: 'The element 'Properties' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest' has incomplete content. List of possible elements expected: 'StartPage' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'.' on line '1', position '338'., Xml Validation Exception: 'The element 'App' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest' has incomplete content. List of possible elements expected: 'AppPrincipal' in namespace 'http://schemas.microsoft.com/sharepoint/2012/app/manifest'.' on line '1', position '351'.**

When I search over internet I see the same issue in SP2016 but nothing with SP19.

I have also installed all the updates provided in the below link:
https://docs.microsoft.com/en-us/officeupdates/sharepoint-updates
 
Request you to help me with the solution.
Thank you for your support in advance.

**Note**: The same solution is working seamlessly in SPO.

Regards,
Krishna.Vandanapu

**Comment by koltyakov** [comment]
Hi @krishnavandanapu,
You mismatched the repository. 
[sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues) is a correct place for addressing SPFx issues.

**Comment by krishnavandanapu** [comment]
> Hi @krishnavandanapu,
> You mismatched the repository.
> [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues) is a correct place for addressing SPFx issues.

Thank you for routing me in the right direction.
