### ISSUE TITLE
All Interfaces prefixed with "I"

### ISSUE THREAD

**Issue by patrick-rodgers** [pnp/pnpjs#519]
In 2.0 we will update all the interfaces to be prefixed with an "I".

Reasons for this change:

- Right now we do both which can be confusing
- We are adding a lot of interfaces in 2.0 and want to ensure it is clear what each "thing" is
- As much as anything can be this seems to becoming a "standard" across a lot of TypeScript libraries

**Comment by s-KaiNet** [comment]
Actually proven TypeScript community members recommend [not to use](https://github.com/basarat/typescript-book/blob/master/docs/styleguide/styleguide.md#interface) `I` prefix for interfaces. :)

**Comment by patrick-rodgers** [comment]
Well I knew whatever choice was made we'd be wrong, so good to get that confirmation. Thanks.

**Comment by olemp** [comment]
I support prefixing interfaces with `I`. If you want to implement a interface in a class, you need to differ them by naming convention somehow and I think prefixing with `I` is a good way.
