### ISSUE TITLE
Web part data version attribute wrong

### ISSUE THREAD

**Issue by raymondlittle100** [pnp/pnpjs#52]
### Category
- [ ] Enhancement
- [ x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     1.0.3    ]

### Expected / Desired Behavior / Question
Adding a new OOTB SharePoint 'People' web part and configuring via library. Trying to set this to use the 'Descriptive' layout.

### Observed Behavior
Web part always defaults to 'Compact' layout

### Steps to Reproduce
Fetch web part definitions
private getClientSideWebPartDefinitions(): Promise<ClientSidePageComponent[]> 
  { 
    return new Promise<ClientSidePageComponent[]>((resolve) => 
    { 
      resolve(this.props.spRest.web.getClientSideWebParts());
    });  
  }

Create custom interface to replicate OOTB people web part properties, importantly setting layout to 2

private getContactWebPartProperties() :ISharePointPersonContact
  {  
    let contactUsers:IPersonsEntity[] =[];

    const ownerUser = getMetadataItem(this.state.pageMetadata, "KIRA_CP_ContentOwner");
    let ownerContact:IPersonsEntity = {
      id:ownerUser.fieldValue[0].tertiaryText,
      upn:ownerUser.fieldValue[0].secondaryText,
      role:"",
      department: "",
      phone:"",
      sip:""         
    };

    contactUsers.push(ownerContact);
    
    let contactWebPartProps: ISharePointPersonContact=
    {
      layout:2,
      persons:contactUsers      
    };

    return contactWebPartProps;
  }

Find web part definition and add web part setting to properties created in snippet above. 

// find the definition we want, here by id
    // const partDef = parts.filter(c => c.Id.toLocaleLowerCase() === "{"+webPartId.toLowerCase()+"}");
    let partDef = webPartDefinitions.filter(c => c.Id.toLocaleLowerCase() === "{"+webPartId.toLowerCase()+"}");

    /*if its null could be because of issue where some web parts start 
    with '{' and some don't. So first try with '{' then without*/
    if(partDef == null || partDef.length ==0)
    {
      partDef = webPartDefinitions.filter(c => c.Id.toLocaleLowerCase() === webPartId.toLowerCase());
    }
    
    // optionally ensure you found the def
    if (partDef.length < 1) {
        // we didn't find it so we throw an error
        throw new Error("Could not find the web part");
    }

    // create a ClientWebPart instance from the definition
    let part = ClientSideWebpart.fromComponentDef(partDef[0]);
    part.webPartId = webPartId;
  
    if(webPartProperties != null)
    {
      part.setProperties<any>(webPartProperties);
    }

    //add web part    
    page.sections[sectionNumber].columns[columnNumber].addControl(part);

Code all works ok but the web part is always in compact view. I think the issue is down to the web part definition dataVersion being set to 1.0 whereas the same web part added to the page manually shows the dataVersion of 1.2, see below

Debugging window
![componentdataversion](https://user-images.githubusercontent.com/23637375/37599710-47c4dda6-2b7d-11e8-877e-9def176d5cae.PNG)

Maintenance mode settings for manually added web part
![contactwebpartsettingsmanuallyadded](https://user-images.githubusercontent.com/23637375/37599760-6649d5ce-2b7d-11e8-8d70-472b0e552e8c.PNG)

**Comment by patrick-rodgers** [comment]
Just looked into this and I am not sure how to "fix" it. The dataVersion doesn't appear to come back with the definition, at least I don't see it (please tell me if I missed it) - meaning I don't know how to set it to anything other than the 1.0 default. We aren't setting the value from the definition - and this reminds me why.

When I do this (I made a property public to do it) it works how you want:

```TypeScript
const partDefs = await sp.web.getClientSideWebParts();

const yy = partDefs.filter(d => d.Id.startsWith("7f7184"));

const part = ClientSideWebpart.fromComponentDef(yy[0]);

part.setProperties({
    layout: 2,
    persons: [{
        id: "i:0#.f|membership|patrick@atenant.com",
    }],
});
// FORCE dataVersion
part.dataVersion = "1.2";

const page = await ClientSidePage.fromFile(sp.web.getFileByServerRelativeUrl("/sites/dev/sitepages/Test_8q5L.aspx"));

page.addSection().addControl(part);

await page.save();
```

So changing the dataVersion DOES fix the issue. Now here is the problem, I have no idea how to know what to set to the dataVersion to. In this case 1.2 works - but I can't tie that to anything solid to handle this automatically. Not saying it can't be done - but I haven't found it yet. This one remains open for now.

**Comment by raymondlittle100** [comment]
Thanks for the update it certainly is a strange one. Just to check are you planning on exposing the dataVersion property so this can be updated?

**Comment by patrick-rodgers** [comment]
It is already, you can use to get around the protected bit.

```TypeScript
(<any>part).dataVersion = "1.2";
```

And in the next version it will be public. I am also adding code to read the value from the webpart markup when it comes in.

**Comment by raymondlittle100** [comment]
Updated to version 1.0.4 and was able to set the dataVersion to 1.2 and this worked. I'll keep an eye out for the full fix so I can remove the hard coded version

**Comment by patrick-rodgers** [comment]
Going to close this as blocked and I don't see any plans to address this on the product side. We can revisit if/when updates are made on the server. Thanks!
