### ISSUE TITLE
 Add section and columns to Client Side Page not getting added.

### ISSUE THREAD

**Issue by Joy-jeevan** [pnp/pnpjs#520]
Page content is not getting saved  using PnP JS 
I have followed the [link](https://pnp.github.io/pnpjs/sp/docs/client-side-pages/#add-client-side-page)
I am using Pnpjs version 1.2.9,tried with 1.2.8 too for SharePointOnline.

Here is my code 
`(async () => { 
       const pageFile = sp.web.getFileByServerRelativeUrl('/sites/TestPlayground-Joy/SitePages/SamplePage01.aspx');
       const page = await ClientSidePage.fromFile(pageFile);
       const section = page.addSection();
       section.addControl(new ClientSideText('HTML content goes here'));
       await page.save();
})()
  .then(_ => console.log('Done'))
  .catch(console.log);`

comments section gets disabled by using page.disableComments();

I have tried creating new page and getting its instance, tried to add contents to page. the sections and columns are getting added to the page object but doesn't get saved on page.save().
There are no errors on the page.

_Originally posted by @Joy-jeevan in https://github.com/pnp/pnpjs/issues/435#issuecomment-466349972_

**Comment by koltyakov** [comment]
Duplicate https://github.com/pnp/pnpjs/issues/504
