### ISSUE TITLE
Trying to get root site collection navigation

### ISSUE THREAD

**Issue by jcosta33** [pnp/pnpjs#522]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

Please specify what version of the library you are using: [1.2.7]

Please specify what version(s) of SharePoint you are targeting: [Modern O365]

### Question

I'd like to use the **getMenuState** method to retrieve the navigation of the root site collection. This method only exists inside de **sp** object, which is set up like this:
```
  sp.setup({
    spfxContext: context
  });
```
I can use the **getRootWeb** method but that doesn't give me that **sp** object where I can access the method I need. Is there a way to set up the **sp** with the root site collection context? What can I do here?

Thank you!

**Comment by koltyakov** [comment]
How about explicit object creation?

```typescript
import { NavigationService } from '@pnp/sp';
const siteAbsUrl = 'https://contoso.sharepoint.com/sites/siiite';
const navigation = new NavigationService(siteAbsUrl);
navigation.getMenuState().then(console.log);
```

**Comment by jcosta33** [comment]
Thank you for the quick response! I'm having some trouble though... It seems like it doesn't matter what string I pass into the **NavigationService**, it'll always return the local navigation. As you can see in this screenshot, I'm passing in an URL to a valid site but the output includes properties pointing to the site where the solution is deployed and the navigation is the local one as well. 

![image](https://user-images.githubusercontent.com/8978270/53515137-34c5fb00-3ac1-11e9-95ea-f98c4d18fb8c.png)

**Comment by patrick-rodgers** [comment]
Updated the class to support what you want to do. It is rolled into the #533 PR.

**Comment by jcosta33** [comment]
Any ETA on when this fix will be released?

**Comment by patrick-rodgers** [comment]
It was released Friday as indicated in the [Chanelog](https://github.com/pnp/pnpjs/blob/dev/CHANGELOG.md#130---2019-08-03) and the milestone in the linked PR.
