### ISSUE TITLE
Set my profile picture issue.

### ISSUE THREAD

**Issue by pavan2920** [pnp/pnpjs#524]
Hi All, 

I am using the below function to update profile image in sharepoint online and getting error. Could any one help me with updating profile picture ? 

**setMyProfilePic(profilePicSource: Blob): Promise<void>;**

_Error: Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-2147024809, System.ArgumentException","message":{"lang":"en-US","value":"Parameter is not valid."}}}_

Thanks 
Pavan.

**Comment by patrick-rodgers** [comment]
Can you please share a fuller code sample showing the context? Thanks.

**Comment by patrick-rodgers** [comment]
Going to close this due to lack of response. If you are still seeing this issue please open a fresh issue and reference this one. Thanks!

**Comment by minasaif** [comment]
Hi pavan2920, What happend in this issue? did you get to pass it? cause i'm facing the same.
