### ISSUE TITLE
Term Set Custom Sort Order Always Null

### ISSUE THREAD

**Issue by jcosta33** [pnp/pnpjs#525]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.7]

Please specify what version(s) of SharePoint you are targeting: [Modern]

### Observed Behavior
I've set up my term set navigation with custom sort orders. The root elements are properly ordered in the object returned by the API but their children aren't. I've had a look at the object and found that the **CustomSortOrder** property is always null, even when the items are properly ordered. 
![image](https://user-images.githubusercontent.com/8978270/53632749-9eebb680-3c0d-11e9-88a5-5cd544c37131.png)

### Steps to Reproduce
Create a navigation term set with at least 2 levels, create custom sort orders for both levels and inspect the object returned by the API.

**Comment by patrick-rodgers** [comment]
Can you share your code? Also, if the values coming back from the server are always null - not sure what we can do. We just take the data and merge it into the object without trimming it.

**Comment by jcosta33** [comment]
![image](https://user-images.githubusercontent.com/8978270/53643529-33fda800-3c2c-11e9-842c-532518181aee.png)

Then it goes on to the callbacks where I populate my own navigation object with the data coming from the API. 

So this a problem with SharePoint itself?

**Comment by patrick-rodgers** [comment]
I don't know yet for sure - I just mean if we make the request and the data doesn't come back not sure what we need to do. Perhaps we can get it to come back, I just mean we aren't filtering what comes back, we just merge it into an object instance and return it.

**Comment by jcosta33** [comment]
Is there a way to determine if there's something wrong with the API or SP itself? I need to come up with a solution for this in my end and if this is something you can do nothing about I have to rethink the way I'm currently doing things in this project.

**Comment by jcosta33** [comment]
Can you guys have a look into this to determine whether you can do something about it or not? If I know for sure that I need to come up with a different solution that's totally fine, I'll just be working on that solution, but first I need to know for sure so as to not waste time.

**Comment by Sartor87** [comment]
Recently, we have encountered the same issue. What we've done is to update the sort order of the terms and it fixed by itself - just re-arranged the terms and returned to the initial sort order.
