### ISSUE TITLE
News web part definition doesn't exist

### ISSUE THREAD

**Issue by umaknow-annie** [pnp/pnpjs#526]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.2.8 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

### Expected / Desired Behavior / Question

I am looking to get the News web part definition but when i get it with the code bellow, the partDef is undefined. It's look like the News Web Part doesn't exist in the ClientSideWebParts. But when I go in SharePoint the web part is there.

### Steps to Reproduce
```
public getClientSitePageWeb(page: ClientSidePage): Web {
    return new Web(this.getClientSidePageWebUrl(page));
  }

const partDefs = (await this.getClientSitePageWeb(targetPage).getClientSideWebParts() as any).GetClientSideWebParts.results;

const partDef = find(partDefs, def => def.Id.toLowerCase().indexOf("8c88f208-6c77-4bdb-86a0-0c47b4316588") !== -1);
```

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
If there is no error and the webpart isn't in the list this is likely something within the site. We don't filter what is there, we just return the list we get back.
