### ISSUE TITLE
Issue adding an image web part

### ISSUE THREAD

**Issue by wobba** [pnp/pnpjs#528]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.9]

Please specify what version(s) of SharePoint you are targeting: [Online]

I'm trying to add an image web part using pnpjs, but it won't show. (The embed web part seems to work just fine as per the sample docs). 

I've manually added an image web part, which shows the following data in `propertiesJson`.

```json
{
	"imageSourceType": 2,
	"overlayText": "",
	"siteId": "6ca1e5e6-e525-43f3-bc4b-43cd2ab3fbff",
	"webId": "3dbe2921-3620-40c3-b3f1-edeaeb01429d",
	"listId": "04b1b5ca-dae3-4e92-bd45-74fbfb2d420a",
	"uniqueId": "8b8263da-fd0a-45c0-bcd9-c432ca49e79d",
	"imgWidth": 318,
	"imgHeight": 200,
	"fixAspectRatio": false,
	"isOverlayTextEnabled": false,
	"altText": ""
}
```

Then using the following code, the web part is added, but no information is showing.

```ts
const partDefs = await this._web.getClientSideWebParts();
const partDef = partDefs.filter(c => c.Id === 'd1d91016-032f-456d-98a4-721247c305e8');
const part = ClientSideWebpart.fromComponentDef(partDef[0]);

part.setProperties<Image>({
	imageSourceType: 2,
	overlayText: '',
	siteId: '6ca1e5e6-e525-43f3-bc4b-43cd2ab3fbff',
	webId: '3dbe2921-3620-40c3-b3f1-edeaeb01429d',
	listId: '04b1b5ca-dae3-4e92-bd45-74fbfb2d420a',
	uniqueId: '8b8263da-fd0a-45c0-bcd9-c432ca49e79d',
	imgWidth: 318,
	imgHeight: 200,
	fixAspectRatio: false,
	isOverlayTextEnabled: false,
	altText: ''
});
page.addSection().addControl(part);
```

Also, if I try to retrieve the web part using PnP Posh I get
```posh
Get-PnPClientSideComponent : Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JObject'.
```

Am I missing something, or any idea what happens?

**Comment by koltyakov** [comment]
Hi Mikael, it's a more global issue rather than an image web part. As a result of client-side pages API or/and canvas content format. See more: https://github.com/pnp/pnpjs/issues/504
An alignment with recent changes is required to make web parts provisioning work again.

**Comment by wobba** [comment]
Figured it out with the help of https://github.com/SharePoint/PnP-PowerShell/issues/1253. I also set the data version to 1.8.
```
part.setProperties<Image>({
   imageSource: 'https://url...'
});
```
