### ISSUE TITLE
SPRequestExecutorClient adding to global with <script>

### ISSUE THREAD

**Issue by PavelAl** [pnp/pnpjs#529]
### Category
- [ ] Enhancement
- [X] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.9]

Please specify what version(s) of SharePoint you are targeting: [2016]

### Expected
Hello in my work for project that made on addin model I need to upload files from user. The user will upload files from within app and then I need to upload them on web with data. I try to use pnp.sp.crossDomain object to make it real but it requered to made fetch factory setup and for that mater I need to use SPRequestExecutorClient. I restricted with pure js and aspx so I add SPRequestExecutorClient with script 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-pnpjs/1.2.9/pnpjs.es5.umd.bundle.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-sp-addinhelpers/1.2.9/sp-addinhelpers.es5.umd.bundle.min.js"></script>
I expected that it would add pnp.SPRequestExecutorClient  or just SPRequestExecutorClient  to global variables but I can't find it in pnp. 

### Observed Behavior
As I said before - after adding with pnp-sp-addinhelpers on page the SPRequestExecutorClient  can't be found in global variables. If I use es5.umd.min.js file instead of es5.umd.bundle.min.js file it would create pnp['sp-addinhelpers'] but it would be empty object.

### Steps to Reproduce
Just add 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-pnpjs/1.2.9/pnpjs.es5.umd.bundle.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pnp-sp-addinhelpers/1.2.9/sp-addinhelpers.es5.umd.bundle.min.js"></script>
on empty page and try to find SPRequestExecutorClient on it. Also try to see for pnp['sp-addinhelpers']. But it would be empty object.

**Comment by patrick-rodgers** [comment]
I think the easier approach would be to bundle your code along with this library and other supporting libraries into a single js file. Then include that into your site in a single script tag. It could then process the operations instead of coding directly within the script editor part.
