### ISSUE TITLE
sp.utility.searchPrincipals has wrong return type

### ISSUE THREAD

**Issue by Nulifier** [pnp/pnpjs#530]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.9]

Please specify what version(s) of SharePoint you are targeting: [SharePoint 2013 On-Prem]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
For the `sp.utiltiy.searchPrincipals` method, the return type should be `PrincipalInfo[]` but it is actually returning an object with this type `{SearchPrincipalsUsingContextWeb: {results: PrincipalInfo[]} }`

Example:
![image](https://user-images.githubusercontent.com/6885933/53822062-2f870700-3f2c-11e9-8003-e0849a1f76db.png)

This isn't a major issue as I can just correct the response after the query returns but it requires me to cast the response to the correct type. This was mentioned in #249 but was lost in discussion there. I suspect this affects many of the other queries in the sp.utilities as they follow the same format.

**Comment by patrick-rodgers** [comment]
This is due to you being on 2013 and not having the latest patches setup and are operating in verbose mode. We'll patch it, thanks.

**Comment by patrick-rodgers** [comment]
Rolled up in #533 PR.
