### ISSUE TITLE
addClientSidePage when using new Web()

### ISSUE THREAD

**Issue by wobba** [pnp/pnpjs#534]
### Category
- [x] Bug

### Version

Please specify what version of the library you are using: [1.2.10-3]

Please specify what version(s) of SharePoint you are targeting: [SPO]

The following code runs against the default URL (in my case localhost as it's an Office add-in).

```typescript
let web = new Web('https://tenant/site');
const page = await web.addClientSidePage('test.aspx');
```

Checking network trace the call runs against:
`https://localhost:3000/_api/sitepages/pages` instead of `https://tenant/site/_api/sitepages/pages`.

Ref https://github.com/pnp/pnpjs/issues/504 @patrick-rodgers

**Comment by patrick-rodgers** [comment]
Thanks, I think I see the issue.

**Comment by patrick-rodgers** [comment]
Pushed fix for this into the same PR, will release another beta once I get through the rest of these issues. Thanks!
