### ISSUE TITLE
IE11 problem with currentUserHasPermissions

### ISSUE THREAD

**Issue by enti333** [pnp/pnpjs#535]
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

Hello. 
I don't know why but in my SPFX webpart I have this code

```
sp.web.lists.getById(this.properties.listGuid).currentUserHasPermissions(PermissionKind.AddListItems).then(perms => {  
            this.RenderDocument();

          }).catch(e => {
            
          });
```
But in IE11 this doesnt work....I get this error:
Object doesn't support property or method 'from'

"TypeError: Object doesn't support property or method 'from'\n   at SharePointQueryable.prototype.toUrlAndQuery (https://localhost:4321/dist/contracts-approvement-web-part.js:18562:13)\n   at SharePointQueryable.prototype.toRequestContext (https://localhost:4321/dist/contracts-approvement-web-part.js:18641:9)\n   at Anonymous function (https://localhost:4321/dist/contracts-approvement-web-part.js:56233:41)\n   at T (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.008/sp-webpart-workbench-assembly_en-us_d3cbeb438ed3a4fb90d7ada926020c72.js:8:2116)\n   at L (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.008/sp-webpart-workbench-assembly_en-us_d3cbeb438ed3a4fb90d7ada926020c72.js:8:2232)\n   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.008/sp-webpart-workbench-assembly_en-us_d3cbeb438ed3a4fb90d7ada926020c72.js:8:555)\n   at c (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-02-22.008/sp-webpart-workbench-assembly_en-us_d3cbeb438ed3a4fb90d7ada926020c72.js:8:362)"

In other browsers this works without any problem but in IE11 doesnt.....

The problem is also same with this code 

```
sp.web.lists.getById(this.properties.listGuid).select('EffectiveBasePermissions').get()
          .then(({ EffectiveBasePermissions: eBasePerm }) => {
            const { hasPermissions } = sp.web;
            const { ViewListItems, AddListItems, EditListItems } = PermissionKind;
            return {
              viewListItems: hasPermissions(eBasePerm, ViewListItems),
              addListItems: hasPermissions(eBasePerm, AddListItems),
              editListItems: hasPermissions(eBasePerm, EditListItems)
            };
          })
          .then(listPermissions => {
            this.RenderDocument();
          })
          .catch(e => {
            console.warn();
          }); 
```

I get same error 
Object doesn't support property or method 'from'

Any other functions like additem or update works but this permission methods not....

Thank you for your help.

**Comment by koltyakov** [comment]
You're missing Array.from polyfill on the page to make it work in IE. Please check this out https://pnp.github.io/pnpjs/documentation/polyfill/
By using `@pnp/polyfill-ie11` one can be abstracted from what polyfills to use.

**Comment by enti333** [comment]
Thank you Andrew. Again you are right. I think that I need to buy you a bear for your help. 
Thank you

**Comment by enti333** [comment]
Hello. I must reopen the issue.... Andrew I still want to buy you a bear:)
The problem is that everything works greate with polyfill on IE11 if I am on workbench (local or Online)....
But When I deploy my app to appcatalog and install in site.... The app doesn't work...
So the problem is on IE11 with @pnp/polyfill-ie11 in local or online workbench everything works....But after deployment it doesn't work....
Hmm.... No error in console or something....Thank you

**Comment by enti333** [comment]
I have found the problem between computer and me:) Thank you
