### ISSUE TITLE
ClientSidePages: Setting PageLayoutType

### ISSUE THREAD

**Issue by olemp** [pnp/pnpjs#536]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
1.2.10-3

### Expected / Desired Behavior / Question
Using the ClientSidePage part of `pnpjs` I except to be able to set PageLayoutType. Previously this could be done by using `page.getItem()`, then setting PageLayout type on the `Item`.

Ref https://github.com/pnp/pnpjs/issues/504

**Comment by patrick-rodgers** [comment]
You can set this still using create but you mean for existing pages? Will add a property for that as part of the same PR.

**Comment by olemp** [comment]
@patrick-rodgers Using create? I'm using `web.addClientSidePage` which only takes name, title and librarytitle. Is there another method for creating pages I've missed?

**Comment by olemp** [comment]
@patrick-rodgers Ah, `ClientSidePage.create`. Awesome.
