### ISSUE TITLE
ClientSidePages: Copy page web parts using fromHtml and toHtml

### ISSUE THREAD

**Issue by aakashbhardwaj619** [pnp/pnpjs#538]
Hi,

I was using the pnpjs ClientSidePage's fromHtml and toHtml methods to copy all of a page's sections, columns and web parts into a new page while provisioning. So far, the code was working fine up until some changes have been made supposedly at Microsoft's end due to which the method are not copying any of the content. Is there any alternate to achieve the same functionality using another method of the existing or beta version of pnpjs?

### Category
- [x] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.7]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

**Comment by patrick-rodgers** [comment]
These methods are no longer supported as we have switched APIs and are no longer setting the field directly. Mentioned this in the thread for #504 as well.

BUT I went ahead and added a copyPage method you can use moving forward. Usage will be:

```
const page = await ClientSidePage.fromFile(sp.web.getFileByServerRelativePath("/sites/dev/SitePages/source.aspx"));

const newPage = await page.copyPage(sp.web, "copy.aspx", "My Title");
```
