### ISSUE TITLE
Get section background properties?

### ISSUE THREAD

**Issue by umaknow-annie** [pnp/pnpjs#540]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.2.8 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

### Expected / Desired Behavior / Question
Is there a way to get and set the section background properties in CanvasSection class? I didn't find any properties to get or set the color.

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
This functionality is not currently present. We can look at adding it, but currently the focus is on getting things working again from #504.

**Comment by patrick-rodgers** [comment]
This is complete and will be part of the next release. Will also be in the next beta version if you want to try it out before the release. Thanks!

**Comment by patrick-rodgers** [comment]
Just published a new beta, v1.3.1-1, which contains the updates mentioned in this issue. Please give it a try if you have time and let us know if you see any further issues. Thanks!
