### ISSUE TITLE
Headers is not defined

### ISSUE THREAD

**Issue by RoelVB** [pnp/pnpjs#541]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 1.2.9

Please specify what version(s) of SharePoint you are targeting: Online

### Expected / Desired Behavior / Question
I'm using `@pnp/sp` inside Node and I want to access multiple Sharepoint Online tenants in parallel. So I'm not using `sp.setup()`, since this is a global config, but I use `sp.configure()`. Unfortunately this returns the error `ReferenceError: Headers is not defined`.

### Steps to Reproduce
Here's some example code:
```typescript
import { sp } from '@pnp/sp';
import * as spauth from 'node-sp-auth';

const options = await spauth.getAuth('https://tenant.sharepoint.com', {username: 'username', password: 'password'});
sp.configure({headers: options.headers}, 'https://tenant.sharepoint.com').web.get().then((web)=>{
    console.log('web', web);
});
```

If there is a better way to do this I would be glad to hear it.

**Comment by RoelVB** [comment]
I would guess it has something to do with this:
https://github.com/pnp/pnpjs/blob/18a0bd91de1012732e8fa2775522f70c1e41ba8f/packages/nodejs/src/nodejs.ts#L7-L10
But I don't understand what "this" is.

**Comment by patrick-rodgers** [comment]
You need to setup and use the node client, which will populate the required globals for you as shown in the docs on the getting started page: https://pnp.github.io/pnpjs/documentation/getting-started/#connect-to-sharepoint-from-node.

```
// configure your node options (only once in your application)
sp.setup({
    sp: {
        fetchClientFactory: () => {
            return new SPFetchClient("{site url}", "{client id}", "{client secret}");
        },
    },
});

// make a call to SharePoint and log it in the console
sp.web.select("Title", "Description").get().then(w => {
    console.log(JSON.stringify(w, null, 4));
});
```

**Comment by RoelVB** [comment]
Hi @patrick-rodgers,

I know this, but I want to access multiple tenants in parallel. As I understand `sp.setup()` is a global configuration.

**Comment by patrick-rodgers** [comment]
The issue you reported is that the headers were not defined. Where we define them is when you include the nodejs library. Have you tried that?

**Comment by RoelVB** [comment]
It turns out adding this resolves the issue:
```typescript
import { NodeFetchClient } from '@pnp/nodejs';

sp.setup({
    sp: {
        fetchClientFactory: ()=>new NodeFetchClient(),
    },
});
```
Looking at it, it does make sense.

Thank you for your assistance!
