### ISSUE TITLE
ClientSidePages: Cannot read property 'toUrl' of null

### ISSUE THREAD

**Issue by olemp** [pnp/pnpjs#542]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Observed Behavior
Fails with error `Cannot read property 'toUrl' of null`.

![image](https://user-images.githubusercontent.com/7606007/54016785-58a1d480-4184-11e9-9ecb-5e7070c08f78.png)

See https://github.com/pnp/pnpjs/issues/537 for details.

**Comment by olemp** [comment]
Looks like the signature of ClientSidePage.create was changed, and I was missing web.

**Comment by patrick-rodgers** [comment]
Yes, if possible avoid using the constructor directly. At this point you have to pass in a certain set of things for stuff to work right. I know that isn't ideal, but its what happened when we rewrote things.
