### ISSUE TITLE
ClientSide Page - unexpected layout

### ISSUE THREAD

**Issue by Sartor87** [pnp/pnpjs#550]
### Category
- [ ] Enhancement
- [X] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.3.0     ]

Please specify what version(s) of SharePoint you are targeting: [    Online     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Expects that two columns with ratio 33% : 66% to be generated.

### Observed Behavior
Three columns are always produced, regardless of the column factor set. The page has its properties set properly. We have tried different combinations for columns, but it seems that always three columns are being generated.

After the page is saved, and if you place a breakpoint on 

      const pageId: number = (page as any).json.Id;

You will see that page.sections[0]["columns"] collection returns properly two columns.

### Steps to Reproduce

    const page = await sp.web.addClientSidePage("pnp130test.aspx", "pnp130test");
    const mainSection = page.addSection();
    mainSection.order = 1;
    const left = mainSection.addColumn(4);
    const right = mainSection.addColumn(8);
    left.order = 1;
    left.factor = 4;
    right.order = 2;
    right.factor = 8;

    // Adding web parts to sections, omitted

     try {
        await page.save();
      }
      catch (error) {
        console.error(error);
      }
      await page.disableComments();
      const pageId: number = (page as any).json.Id;

      const pageItem = await sp.web.lists.getByTitle("Site Pages").items.getById(pageId).update({
        "ContentTypeId": contentTypeId,
        "PromotedState": 2,
        "BannerImageUrl": {
          "__metadata": { "type": "SP.FieldUrlValue" },
          "Description": "",
          "Url": ""
        }
      });

**Comment by aakashbhardwaj619** [comment]
I'm also observing the same behavior when using the new **copyPage** method. The source page has 2 column layout but the new page gets created with a 3 column layout.

**Comment by patrick-rodgers** [comment]
Got this fixed I believe, will be part of the next beta and release. You can give it a try once the beta is out and let us know if you still see issues.

**Comment by patrick-rodgers** [comment]
Just published a new beta, v1.3.1-1, which contains the updates mentioned in this issue. Please give it a try if you have time and let us know if you see any further issues. Thanks!

**Comment by Sartor87** [comment]
I was not able to test it - it seems that there is some regression with Site Pages / addClientSidePage. [https://github.com/pnp/pnpjs/issues/565](url)

**Comment by aakashbhardwaj619** [comment]
I just tested this using the **copyPage** method and it is working fine now. The new page gets created with the same layout as the source page and my source page had a 2 column layout. Thanks!
