### ISSUE TITLE
Web permissions always returning either 404 or 403

### ISSUE THREAD

**Issue by jcosta33** [pnp/pnpjs#552]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.0]

Please specify what version(s) of SharePoint you are targeting: [Modern O365]

### Observed Behavior
I'm using two different environments. One is a tenant where I don't have full control and can't edit list items at the root site, for example. The other tenant is mine and I have full control everywhere. 

In the first environment, when I try to validate my local site collection permissions everything works fine. When I try to validate the tenant level permissions [by setting up a custom Web(' TENANTURL' ) ] I get a 403 error: 

```
theme-latest-application-customizer.js:13698 Uncaught (in promise) Error: Error making HttpClient request in queryable [403]  ::> {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}
    at new HttpRequestError (theme-latest-application-customizer.js:13698)
    at theme-latest-application-customizer.js:13707
```

In the second environment, I always get a 404, no matter what level permissions I'm trying to validate.
```
Uncaught (in promise) Error: Error making HttpClient request in queryable [404]  ::> 
    at new HttpRequestError (parsers.ts:13)
    at parsers.ts:19
```

This is how I'm attempting to retrieve that information:
![image](https://user-images.githubusercontent.com/8978270/54357189-6c05e180-4655-11e9-8ded-b3102caa74f4.png)

I've also tried all the other permission methods, with the same results.

I understand the situation with the first environment (giving me the 403) is probably an issue with the endpoint itself. This is not the most important though since at least to some degree the 403 still lets me know that the user doesn't have permissions on that site, considering this only seems to happen when the user genuinely doesn't have permissions. The main problem is the 404 I'm getting in my tenant. 

Thank you!

**Comment by carlosmiguelsns** [comment]
Hello guys, I'm running the same issue!
Do you've any news on these? 

Thank you!

**Comment by koltyakov** [comment]
What exactly is passed to Web object initiation? It should be SPWeb/SPSite absolute URL.
Can you try just getting basic web info instead of getCurrentUserEffectivePermissions? Or getting effective base permissions via selecting web property like [this](https://github.com/pnp/pnpjs/issues/259#issuecomment-426159979)? Will it end up with the same result?

**Comment by jcosta33** [comment]
I'm passing the absolute URL of the root of a site collection into the Web initiation. I have no edit permissions on that site collection but I can read the info from the lists and if I pull some list info through the API (using the same object as the one I'm getting the 403 with) it works normally. The 404 resolved itself apparently as it's no longer happening.

**Comment by jcosta33** [comment]
Quick update: I just noticed that the 404 does occur but not when running the app on a Hub site, where it works fine. Hope this is useful!

**Comment by michaelmaillot** [comment]
Hi,

I got the same issue (403 for the "getCurrentUserEffectivePermissions" method on the Web).

So I ended up by another approach, through the "hasAllPermissions" and the "hasAnyPermissions" methods, through the "webpartContext.pageContext.web.permissions" and it works !

Thx for the investigations 🙂
