### ISSUE TITLE
Support configuration of ClientSidePage queryable

### ISSUE THREAD

**Issue by pedro-pedrosa** [pnp/pnpjs#556]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
Bug/enhancement depending on the point of view.

Currently, queryables expose a `configure(options)` method which allows one to configure things like request headers for a specific request, overriding global config.

`ClientSidePage`s do not allow this as it exposes a static `fromFile` method that only accepts a file as argument.

Bug: it should use the same configuration as the file I'm passing _(should it?)_
Enhancement: allow one to specify the config object to be used on requests. I cannot rely on global configuration for this.

Thanks!

**Comment by patrick-rodgers** [comment]
Added functionality to respect the configureFrom and configure methods when called on the ClientSidePage instance. Also updated code to use any configuration settings from the File instance supplied to fromFile. This will be in the upcoming beta and release.

**Comment by patrick-rodgers** [comment]
Just published a new beta, v1.3.1-1, which contains the updates mentioned in this issue. Please give it a try if you have time and let us know if you see any further issues. Thanks!
