### ISSUE TITLE
Is it possible to add an event receiver by pnp/sp?

### ISSUE THREAD

**Issue by honb** [pnp/pnpjs#559]
hi there ,
I want to create/delete an event receiver for a list
Something like this: sp.web.lists.getByTitle('TestEventReceivers').eventReceivers.add()
ReceiverAssembly = ""
ReceiverName = "RemoteEventReceiver1",
ReceiverUrl = remoteUrl,

Not sure this can be done by JSOM or Rest API?

Thanks in advance!

**Comment by patrick-rodgers** [comment]
Yes: 

[subscriptions property ](https://github.com/pnp/pnpjs/blob/dev/packages/sp/src/lists.ts#L226)on List class:

Implementation:

https://github.com/pnp/pnpjs/blob/dev/packages/sp/src/subscriptions.ts

**Comment by honb** [comment]
Thanks Patrick,
subscriptions.add() ==> how can i specify event type and other properties?

**Comment by patrick-rodgers** [comment]
The subscriptions are powered by webhooks which send notifications for all events, [you can read more on picking out what you need from that](https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/webhooks-reference-implementation#grab-the-changes-your-service-needs-to-act-upon).

Perhaps I misunderstood, we do not have a way to add server side event receivers via REST. You would likely handle that with server side code. Either a timerjob to ensure on a schedule that all lists has some receiver or as attached to list templates.
