### ISSUE TITLE
Add error handling for fetching pages with invalid characters

### ISSUE THREAD

**Issue by raymondlittle100** [pnp/pnpjs#56]
### Category
- [ x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  1.0.3       ]

### Expected / Desired Behavior / Question
When fetching a page if you have a ' in the page name the request fails because the REST query doesn't like the unescaped '

See sample code below. I'm able to fetch the first page but the second executes an invalid REST call due to '. 

Original Code
public componentDidMount()
  {
    this.loadPageDetails();
  }

  public async loadPageDetails()
  {
    try
    {
      const page = await ClientSidePage.fromFile(this.props.spRest.web.getFileByServerRelativeUrl("/sites/HR/SitePages/page-1.aspx"));
      console.log(`Page 1 ${page}`);
      const page2 = await ClientSidePage.fromFile(this.props.spRest.web.getFileByServerRelativeUrl("/sites/HR/SitePages/page'1.aspx"));
      console.log(`Page 2 ${page2}`);
    }
    catch(error)
    {
      console.log(`Error ${error}`);
    }
  }

Additional checks I added in my code
public async loadPageDetails()
  {
    const pageUrl1:string = encodeURIComponent("/sites/HR/SitePages/page-1.aspx");
    let pageUrl2:string = encodeURIComponent("/sites/HR/SitePages/page'1.aspx");
    /*special case where "'" isn't covered and REST doesn't like this
    so manually replace this */
    pageUrl2 = pageUrl2.split("'").join("''");

    try
    {
      const page = await ClientSidePage.fromFile(this.props.spRest.web.getFileByServerRelativeUrl(pageUrl1));
      console.log(`Page 1 ${page}`);
      const page2 = await ClientSidePage.fromFile(this.props.spRest.web.getFileByServerRelativeUrl(pageUrl2));
      console.log(`Page 2 ${page2}`);
    }
    catch(error)
    {
      console.log(`Error ${error}`);
    }
  }

**Comment by patrick-rodgers** [comment]
Welcome thoughts from others, but in the past we have generally said that encoding needs to be handled before folks pass things into the library. Issue in trying to cover encoding is all the various languages, etc - we would always be chasing something. I'll leave this open for others to comment, but I am leaning towards taking no action.

I am curious if the getFileByServerRelativeUrl works as the url generated would be something like:
`getFileByServerRelativeUrl('/sites/HR/SitePages/page''1.aspx')`

Thanks!

**Comment by koltyakov** [comment]
@raymondlittle100, can you try wrapping pages URIs with `encodeURIComponent()`? Will it help?
