### ISSUE TITLE
Is it possible

### ISSUE THREAD

**Issue by mgordic** [pnp/pnpjs#566]
Hi,

Is extending of list item entity still supported (like in previous versions -https://github.com/SharePoint/PnP-JS-Core/wiki/Extending-with-Custom-Business-Objects)

I haven't found yet getAs<MyItem[]> for example anywhere in library, so any help in this direction will be highly appreciated.

### Category
- [ ] Enhancement
- [ ] Bug
- [  ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    latest from pnp     ]

Please specify what version(s) of SharePoint you are targeting: [       o365  ]

**Comment by patrick-rodgers** [comment]
Yes, still 100% possible. New docs [page moved to here](https://pnp.github.io/pnpjs/sp/docs/entity-merging/). Have a look at that and let us know what questions you have. We can always improve the docs but it is just a question of time.

**Comment by mgordic** [comment]
Hi Patrick,

Thank you for quick reply.

I am trying to migrate this code https://blog.josequinto.com/2017/06/28/create-custom-parser-and-array-parser-to-generate-query-and-property-names-in-pnp-js-core/#Post-Series-Index

into new version of library. Problem that I am facing so far is that due the different organization of the library, some imports are missing or I can't find them at all, like following:

import {  QueryableConstructor, Util} from "sp-pnp-js";

**Comment by patrick-rodgers** [comment]
You might check with Jose to see if he can update the sample or if someone else has some time to update it for you. Most of the exports are the same but in some cases the names possibly changed. [Util is now separate functions](https://github.com/pnp/pnpjs/blob/dev/packages/common/src/util.ts) and QueryableConstructor is now [SharePointQueryableConstructor](https://github.com/pnp/pnpjs/blob/dev/packages/sp/src/sharepointqueryable.ts#L21). They are also split across packages now.
