### ISSUE TITLE
pnp sp js file upload await.

### ISSUE THREAD

**Issue by andarkeerthi** [pnp/pnpjs#567]
Hi, I am using the following code to upload the document to the Doc Library and trying to update the metadata columns and once after completing the operation I am trying to redirect to some other page. Presently it is uploading the file but it is not waiting till the metadata column gets updated. it redirects before that.  Do we have an option to wait until the entire operation gets completed?

```
private async _saveSupportDoc() {
		var documents = this.state.documentsControl;
		let isUploaded = false;
		if (documents.length > 0) {
			let docCount = this.state.supportingDocCount;
			documents.forEach(element => {

				if (element.documentType == "Support") {
					let fileName = this.state.contract.RequestNumber + '_' + docCount + element.name.substr(element.name.lastIndexOf('.'));
					sp.web.getFolderByServerRelativeUrl("/sites/" + this.props.currentSite + "/SupportingDocuments/").files
						.add(fileName, element.file, false)
						.then(f => f.file.getItem())
						.then(item => {
							item.update({
								ContractId: `${this.state.contract.ID}`
							}).then(_ => {
								this.setState({
									loading: false
								});
							});
						})
				}
				docCount++;
			});
		}
		location.href=this.props.myPendingUrl;
	}
```

**Comment by koltyakov** [comment]
Hey @andarkeerthi, 

It's a general JS development question, not related to PnPjs at all, but just connected to how `Promises` work in JavaScript. Your question header even contains the answer - `await` keyword. Please check generic topics like `Promises`, Promises chaining, `async/await`, `for/of` loops, this will make building such logic in JavaScript/TypeScript with PnPjs and any other async functionality straightforward.

Some comments on your code as a free of charge consulting: 😆

```typescript
private async _saveSupportDoc() {
  const documents = this.state.documentsControl;
  for (const element of documents) { // for/of require for await works in a loop
    let docCount = 1;
    if (element.documentType == 'Support') {
      const fileName = this.state.contract.RequestNumber + '_' + docCount + element.name.substr(element.name.lastIndexOf('.'));
      // await the promise
      await sp.web.getFolderByServerRelativeUrl(`/sites/${this.props.currentSite}/SupportingDocuments/`)
        .files.add(fileName, element.file, false)
        .then(f => f.file.getItem())
        .then(item => {
          // should return sub promise to await item update too
          return item.update({
            ContractId: `${this.state.contract.ID}`
          });
        });
      }
      docCount += 1;
    }
  }
  this.setState({ loading: false }); // makes little sense as the result of save operation is route navigatin
  location.href = this.props.myPendingUrl;
}
```

As you can see none of PnPjs specific things. We really would encourage you to ask such questions in the [Microsoft Tech Community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) or [StackOverflow](https://stackoverflow.com/questions/tagged/sharepoint). Please understand we can't scale to handle all development questions. Thank you for your interest in pnpjs!

**Comment by ncmadhan1989** [comment]
Your Answer is Exactly ok,but my concern is related to I.E. 11,its doesn't supports async/await keywords,whats the workaround for that??

**Comment by koltyakov** [comment]
@ncmadhan1989, when a code is "compiled" down to a supported by a browser version async/await and other modern JS/TS features has to be transpiled, polyfilled (e.g. fetch, promises) those which are a syntactic sugar replaced to the corresponding code ES5 code (transpiled). Anyway one never writes a raw ES5 to support legacy outdated browsers, this is a build pipeline responsibility to bundle a code to run in a browser.

**Comment by ncmadhan1989** [comment]
Thankz for ur reply koltyakov,but here i am not using spfx to  transpiling es6 to es5 model,i am using plain javascript,so kindly share a sample

My Code
 var input =document.getElementById("inputVideo");
      var filesUploaded = 0;
       var fileCount= input.files.length;
for(var ifile = 0; ifile  < fileCount; ifile++)
{
var newfile=input.files[ifile];
      // you can adjust this number to control what size files are uploaded in chunks
 //     if (newfile.size <= 10485760) {

          // small upload
          var myfilename=$("#ddlVideoAlbum option:selected").text()+newfile.name
        newweb.getFolderByServerRelativeUrl("/VideoGallery/").files.add(myfilename, newfile, true).then(function(filedata)
          {
             filedata.file.getItem().then(function(item) {

     item.update(VideoData);
     filesUploaded++;
     if(fileCount == filesUploaded)
{  

                      $('.loader-overlay').addClass('loaded');
                     alertify.alert().setting({
    'label':oklabel,
    'message': fileuploadsucs ,
    'onok': function(){window.location.href=_spPageContextInfo.webAbsoluteUrl+"/Pages/VideoAll.aspx";
}
  }).show().setHeader('<em>'+confirmation+'</em> ').set('closable', false)

                    
                    }
    }).catch(function(error){ErrorLogger(error.message,"VideoGallery","VideoGallery")});


 }).catch(function(error){ErrorLogger(error.message,"VideoGallery","VideoGallery")});

 }
