### ISSUE TITLE
Call two REST 

### ISSUE THREAD

**Issue by selvaag** [pnp/pnpjs#577]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Code sample
`  EXAMPLE CODE >>
sp.web.lists.getByTitle(listname).items.select(select).expand("AssignedTo").top(1000).get().then( res => {
         
          if (res.length > 0) {
            this.setState({
              height: res.length * this.rowHeight + 70
            });
          }

          // MAP TASK ITEMS
          const data: IGanttData[] = res.map( obj => {

            // COLLECT PROJECT VALUES, LOOKUPVALUES
            **let proj = sp.web.lists.getByTitle("Projects").items.getById(obj.ProjectId).get();
            console.log(proj);**

            let users = "";
            if ( obj.hasOwnProperty("AssignedTo") ) {
              users = obj.AssignedTo[0].EMail;
            }

            let rObj: IGanttData = {
              id: obj.ID,
              text: obj.Title,
              Body: obj.Body,
              start_date: moment(obj.StartDate).format("DD/MM/YYYY"),
              end_date: moment(obj.DueDate).format("DD/MM/YYYY"),
              progress: obj.PercentComplete,
              parent: obj.PredecessorsId[obj.PredecessorsId.length-1],
              users: users || "",
              open: true,
              sendmail: true
            };
            return rObj;
          });
}

`
### Expected / Desired Behavior / Question
get proj property values from ListItem

### Observed Behavior
No proj propery values returned. The code does not return need values from 
let proj = sp.web.lists.getByTitle("Projects").items.getById(obj.ProjectId).get();

### Steps to Reproduce
Ref. sample code

### Submission Guidelines

Thank you for your feedback!

**Comment by sympmarc** [comment]
Do you see any errors in the console? Can you look at the call in the Network tab to see whether it is successful, even if it returns nothing?

**Comment by patrick-rodgers** [comment]
You either need to `await` the result or use `then` after the get() call. In your case proj is a Promise. You are also using "proj" and "obj" - are those meant to be the same variable?

**Comment by koltyakov** [comment]
Also, for async/await work in a loop for/of loops should be used.
However, the code in the sample introduces a large issue. A potential number of requests could be 1000+1, this is huge. The client-side app can fail and SPO (if it's SPO) can throttle and once again lead to an unworking app. 
It's better to expand lookup values or request complete project list items and merge 2 arrays in memory rather than requesting each project details separately.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Thanks!

**Comment by selvaag** [comment]
Thanks for all your reply comments, I will check issue further and try load two arrays in memory.
