### ISSUE TITLE
HubSiteData - response type

### ISSUE THREAD

**Issue by salascz** [pnp/pnpjs#579]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.1]

Please specify what version(s) of SharePoint you are targeting: [Online, dedicated tenant]

### Expected / Desired Behavior / Question
The hubSiteData method in [webs.ts](https://github.com/pnp/pnpjs/blob/d6569b2bc5c3587276b9427eadff23d53a6fcb8e/packages/sp/src/webs.ts) class expect the IHubSiteData result. The result object does not match the [REST API](https://docs.microsoft.com/en-us/sharepoint/dev/features/hub-site/rest-hubsitedata-method#sample-response) definition.

### Observed Behavior
The call returns a string value instead of IHubSiteData value.

### Steps to Reproduce
You need to have a site collection (child) connected to the hub site collection. If you call the `await sp.web.hubSiteData(false);` code in the context of child site connection, the result is string, not an object.

### Comments
Hello, I checked both categories (Question & Bug) because I am not sure, what should be the desired behavior. The response IHubSiteData count with properties like `Url`, but the REST API definition use the `url` property (I did not found any mapping on PnP JS side). 
On the other site the output from `/_api/web/HubSiteData(true)` call did not mach the REST API definition as well :( (I am working on dedicated SharePoint Online instance) - the REST call returns output like this:
```
{
   "d": {
      "HubSiteData": {
         "headerEmphasis": null,
         "themeKey": "...",
         "name": "...",
         "url": "HUB SITE URL",
         "logoUrl": null,
         "usesMetadataNavigation": false,
         "megaMenuEnabled": false,
         "navigation": [
            ...NAVIGATION DATA...
         ],
         "siteDesignId": "00000000-0000-0000-0000-000000000000",
         "requiresJoinApproval": false
      }
   }
}
```

The same call with PnP JS returns string:
```
"{"headerEmphasis":null,"themeKey":"...","name":"...","url":"HUB SITE URL","logoUrl":null,"usesMetadataNavigation":false,"megaMenuEnabled":false,"navigation":[...NAVIGATION DATA...],"siteDesignId":"00000000-0000-0000-0000-000000000000","requiresJoinApproval":false}"
```

**Comment by koltyakov** [comment]
The shape of response can be different depending on OData mode (verbose/minimalmetadata/nomatadata), however we abstract such things away. Confirming that `web.hubSiteData` response is not parsed raw string, which probably was not the case 5 month ago when a method was added to the library. Looks like a bug for me which we definitely can fix sooner.

**Comment by patrick-rodgers** [comment]
@koltyakov - were you working on this one?

**Comment by koltyakov** [comment]
Have not started yet =(

**Comment by patrick-rodgers** [comment]
Cool, no worries, I will have a look now, just didn't want to duplicate work

**Comment by patrick-rodgers** [comment]
Fixed this and added to PR #581.

For whatever reason the value is now a string vs the object so added a JSON.parse.

**Comment by salascz** [comment]
Thanks for taking care of this issue. 

I did not find any update in the `IHubSiteData` -> the JSON.parse() returns a different object as I described in the description (the `IHubSiteData` use first letter in uppercase, the REST response return all properties in lowercase)

**Comment by patrick-rodgers** [comment]
So you are reporting two issues? The one you described was that the result is coming back as a string?

**Comment by salascz** [comment]
Yes, mentioned in the **Comments** section

**Comment by salascz** [comment]
Hi @patrick-rodgers, would it be possible to remove "fixed" status as the interface has not been fixed?
Thanks

**Comment by patrick-rodgers** [comment]
Have had time to circle back and update the interface. Should now match what is coming back from the service.
