### ISSUE TITLE
addChunked 404 Message

### ISSUE THREAD

**Issue by dipetersen** [pnp/pnpjs#580]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.3.1-2 ]

Please specify what version(s) of SharePoint you are targeting: [ 2013 ]

### Expected / Desired Behavior / Question

Using the example code to upload files via client.  

If file is less than or equal to 10485760, use the files.add method.

If the file is larger, use the files.addChunked method.

using the above logic, the file uploads to a folder in a document library.

### Observed Behavior
When uploading a file less than 10485760 bytes, the upload process works fine.  When uploading larger files using the addChuncked method, the following error is received:

```
POST http://spdev/dev/subscriptionmanager/_api/web/getFolderByServerRelativeUrl('/dev/subscriptionmanager/subscriptiondocuments/93/')/files('My15MBFile.zip')/startUpload(uploadId=guid'f7a5d376-1318-487b-9735-fe97eab5e8c5') 404 (Not Found)

Message: Error making HttpClient request in queryable [404] Not Found ::> {"error":{"code":"-1, Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot find resource for the request startUpload."}}} Data: {"response":{},"status":404,"statusText":"Not Found","isHttpRequestError":true}
```

### Steps to Reproduce
Here is the code I am using:
```javascript
  UploadFiles() {
    return new Promise((resolve, reject) => {
      if (UploadQueue.length == 0) resolve(true);
      const folder = `${config.docpath}/${this.SubscriptionId}/`;
      const promises = [];
      pnp.sp.web.folders.add(folder).then(d => {
        UploadQueue.forEach(f => {
          f = f[0];
          const file = f.files[0];
          if (file.size <= 10485760) {
            promises.push(
              pnp.sp.web.getFolderByServerRelativeUrl(folder).files.add(file.name, file, true)
            );
          } else {
            promises.push(
              pnp.sp.web.getFolderByServerRelativeUrl(folder).files.addChunked(file.name, file, data => {
                    Logger.log({
                      data: data,
                      level: LogLevel.Verbose,
                      message: "progress"
                    });
                  },
                  true
                )
                .then(_ => Logger.write("done!"))
            );
          }
        });
        Promise.all(promises).then(values => {
          console.log("made it past the values");
          console.log("values", values);
          resolve(values);
        });
      });
    });
  }
```

**Comment by patrick-rodgers** [comment]
These methods are not available in [2013 as per the official docs](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-rest-reference/dn450841(v=office.15)#startupload-method).

> This method is currently available only on Office 365.

**Comment by dipetersen** [comment]
Thank you.  I have been searching forever on this.  I appreciate the link. Closing.
