### ISSUE TITLE
Nodejs sp-fetch-client failed "connect ECONNREFUSED" behind corporate proxy

### ISSUE THREAD

**Issue by jecatomas** [pnp/pnpjs#582]
### Category
- [x] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.1]

Please specify what version(s) of SharePoint you are targeting: [Online, dedicated tenant]

### Expected / Desired Behavior / Question
I am behind corporate proxy and I am not able to pass my proxy to authentication calls inside SPFetchClient methods. Only SPFetchClient.fetch could be overridden.
 
### Observed Behavior
My call failed with following message:

`
FetchError: request to https://accounts.accesscontrol.windows.net/metadata/json/1?realm=a00de4ec-48a8-43a6-be74-e31274e2060d failed, reason: connect ECONNREFUSED 40.126.2.34:443
`
### Steps to Reproduce
You need to be behind corporate proxy for reproducing this issue.
Run following code in Nodejs application:
```
sp.setup({'
      sp: {'
        fetchClientFactory: () => {
          return new SPFetchClient(<Your site URL>, <Client ID>, <Client Secret>);
        }
      }
    });
const web = await sp.web.select('Title').get();
```

### Submission Guidelines
To fix this issue, you can do following:

1. Use `https-proxy-agent` NPM package
2. Add optional parameter `proxyUrl?: string` to `SPFetchClient` constructor
3. Add `agent` option to `fetch` call in `SPFetchClient` class if `proxyUrl` is set in `SPFetchClient.getAuthUrlExtra` method:
```
const r = await this._fetchClient.fetch(url, {
      method: 'GET',
      agent: new HttpsProxyAgent(proxyUrl)
  } as any);
```
4. Add optional parameter `proxyUrl?: string` to `getAddInOnlyAccessToken` function in [`sptokenutils.ts` file](https://github.com/pnp/pnpjs/blob/f6f392e7046ed75f909c383d69413939f5e5a8c6/packages/nodejs/src/sptokenutils.ts)
5. Propagate `proxyUrl?: string` to `getTokenInternal` function in [`sptokenutils.ts` file](https://github.com/pnp/pnpjs/blob/f6f392e7046ed75f909c383d69413939f5e5a8c6/packages/nodejs/src/sptokenutils.ts)
6. Add `agent` option to `nodeFetch` call in `getTokenInternal` function if `proxyUrl` is set:
```
const r = await nodeFetch(params.stsUri, {
    body: body.join('&'),
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    },
    method: 'POST',
    agent: new HttpsProxyAgent(proxyUrl)
  });
```

**Comment by koltyakov** [comment]
Hi @jecatomas,

It's Node.js standard behavior behind a proxy. Node.js requires the corresponding configuration to be aware that it should use a proxy.

Common way IFAIK is to provide `https_proxy`, `http_proxy` environment variables as well as `NODE_TLS_REJECT_UNAUTHORIZED`.

```bash
set https_proxy=http://[proxy]:[port]
set http_proxy=http://[proxy]:[port]
set NODE_TLS_REJECT_UNAUTHORIZED=0
```

**Comment by jecatomas** [comment]
Hi @koltyakov,
According to this https://github.com/nodejs/node/issues/8381 issue NodeJs does not support environment variables for setting global proxy for NodeJs fetch. Solution could be usage of `global-tunnel-ng` NPM package. This package can get settings from environment variables. But could be nice to have option to set proxy for calls in SPFetchClient, because will be more straightforward for developers.

**Comment by patrick-rodgers** [comment]
Have mixed feelings on this one. This is the first time it has come up, so I feel like it is either very uncommon or there is some other work around that folks are using. But, its not a terribly complicated fix and you've outlined it well enough. But, it does give us another dependency to manage. But, that's not so bad really.

This would also enable a scenario where all requests could easily be run through something like fiddler locally. Which could be nice for debugging.

I don't really want to update the constructor as that is a breaking change so will add a property instead.

Let me give this a try and we'll see.

**Comment by patrick-rodgers** [comment]
Got this done and works with fiddler. After looking at it I ended up implementing it differently than your suggestion as it was much less work. Usage will be:

```TypeScript
import { SPFetchClient, SPOAuthEnv, setProxyUrl } from "@pnp/nodejs";

sp.setup({
    sp: {
        fetchClientFactory: () => {
            // optional, I needed this to make fiddler work
            process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
            // call the set proxy url function and it will be used for all requests regardless of client
            setProxyUrl("http://127.0.0.1:8888");
            return new SPFetchClient(settings.testing.sp.url, settings.testing.sp.id, settings.testing.sp.secret, SPOAuthEnv.SPO);
        },
    },
});
```
I also added a new docs page describing usage.

**Comment by jecatomas** [comment]
setProxy method will be good enough. Thanks for implementation.
