### ISSUE TITLE
How to set properties for client side webpart

### ISSUE THREAD

**Issue by Prakash-Ramasamy** [pnp/pnpjs#583]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ **1.3.0** ]

Please specify what version(s) of SharePoint you are targeting: [ **SPO** ]

### Expected / Desired Behavior / Question
Custom properties should be added to client side webpart

### Observed Behavior
Not accepting the custom properties

### Steps to Reproduce

const footerSection = page.addSection();
const relatedDocsColumn = footerSection.addColumn(12);
const partDefs = await web.getClientSideWebParts();
const relatedAttachments = partDefs.filter(webPartID => webPartID.Id == "f92bf067-bc19-489e-a556-7fe95f508720")[0];
relatedDocsColumn.addControl(new ClientSideWebpart(**{
    "isDocumentLibrary": true,
    "selectedListId": "3de55ea7-b1a1-47ea-b97a-558d7a50fc11",
    "listTitle": "Related Attachments",
    "selectedListUrl": "/sites/Test-News/Related Attachments",
    "webRelativeListUrl": "/Related Attachments",
    "webpartHeightKey": 4,
    "selectedViewId": "da47ddd6-db6a-4d60-8e8d-710e68b8319c",
    "selectedFolderPath": "",
    "hideCommandBar": false
 }**));

In the last step I am getting error. I am not able to pass my custom properties to the web part. Since I have upgraded the version from 1.2.7 to 1.3.0, I am getting this error. Is there any documentation / example  to add custom properties to the client side webpart.

Could you please help me with any suggestion/solution.

**Comment by patrick-rodgers** [comment]
Hi @Prakash-Ramasamy - I am not sure that this would ever have worked. If you have a look at the [old code](https://github.com/pnp/pnpjs/blob/7d099a62631afa1367c8d28b6f1aec89df2241ec/packages/sp/src/clientsidepages.ts#L792) the constructor never accepted the properties in this manner. You may have in the past not gotten an error, but this code certainly wasn't doing what you expected.

You should use the setProperties method which will set the web part properties. Please give that a try and let us know. Thanks!

**Comment by Prakash-Ramasamy** [comment]
Hi @patrick-rodgers - I have tried the below code which you suggested and it is working as expected. Thank you very much for your help. 

```
const relatedAttachments = partDefs.filter(webPartID => webPartID.Id == "f92bf067-bc19-489e-a556-7fe95f508720")[0];
const relatedAttachmentsWP: ClientSideWebpart = ClientSideWebpart.fromComponentDef(relatedAttachments);       
relatedAttachmentsWP.setProperties({       	  
	  "isDocumentLibrary": true,
          "selectedListId": "3de55ea7-b1a1-47ea-b97a-558d7a50fc11",
          "listTitle": "Related Attachments",
          "selectedListUrl": "/sites/Test-News/Related Attachments",
          "webRelativeListUrl": "/Related Attachments",
          "webpartHeightKey": 4,
          "selectedViewId": "da47ddd6-db6a-4d60-8e8d-710e68b8319c",
          "selectedFolderPath": "",
          "hideCommandBar": false
});
relatedDocsColumn.addControl(relatedAttachmentsWP);
```

I have one more question related to this. Is checkout option removed for ClientSidePage? In previous version the checkout and publish options were available. Currently to checkout the page I am making one more call to get the page as file then I am doing check out. Is this the correct way of doing checkout a ClientSidePage? 

Thanks in advance

```
await page.save();
 web.getFileByServerRelativeUrl("/sites/test-news/SitePages/" + pageUrl + ".aspx").checkout().then(_ => {
       console.log("Success");
}).catch(error => {
       console.log(error);
});
```

**Comment by patrick-rodgers** [comment]
When you save you handle the checkout for you, update the content, then publish. You can control if it is published by passing a boolean into the save method - the default is that it is published. We don't currently have explicit methods available for checkout and save as draft.

**Comment by Prakash-Ramasamy** [comment]
@patrick-rodgers Thank you for clarifying my doubts.

**Comment by patrick-rodgers** [comment]
Awesome, glad its worked out. Thanks for using the library!
