### ISSUE TITLE
how to pass username and password instead of client id and client secret?

### ISSUE THREAD

**Issue by peterremote1980** [pnp/pnpjs#584]
hi
   how to pass username and password instead of client id and client secret?
Thanks
Peter

**Comment by patrick-rodgers** [comment]
Hi @peterremote1980 - we don't support that through the library. But you are in luck, there is a package that helps handle authentication with many more modes available, [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth). You will have to evaluate it yourself to determine if it meets your needs but others have had success supporting these scenarios. HTH

**Comment by koltyakov** [comment]
The simplest way to master node-sp-auth with PnPjs is [pnp-auth](https://github.com/SharePoint-NodeJS/pnp-auth).

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Thanks!
