### ISSUE TITLE
how to get only selected properties instead of all when using getFileByServerRelativeUrl

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/pnpjs#586]
I am using the following code : 
I dont want listItemAllFields , i only want selected fields
`  url = await sp.web.getFileByServerRelativeUrl(relativeUrl).listItemAllFields.get().then((items => {
            return (items.ServerRedirectedEmbedUrl);
          }))`

**Comment by koltyakov** [comment]
Hi @harshdamaniahd,

The same exactly approach as with any other OData modified endpoint - by using `select` and providing comma separated string with fields: `.listItemAllFields.select('Id,Created')`.
