### ISSUE TITLE
Site asset file caching

### ISSUE THREAD

**Issue by MijoBarbaric** [pnp/pnpjs#587]
Hi guys,

Building an SPFx webpart for a modern team site on which the user can upload an image and crop it afterwards. Source image as well as the cropped image is stored as file in the site assets library. This is done via:

```javascript
public ensureSiteAssetsLibrary(siteUrl: string): Promise<List> {
    let web: Web = new Web(siteUrl);
    return web.lists.ensureSiteAssetsLibrary();
}

public async uploadImage(siteUrl: string, fileName: string, blob: Blob): Promise<FileAddResult> {
    let siteAssetsLibrary = await this.ensureSiteAssetsLibrary(siteUrl);
    const shouldOverwrite = true;
    return siteAssetsLibrary.rootFolder.files.add(fileName, blob, shouldOverwrite);
}
```

We are referencing the img src directly via url:
```javascript
const fileName = "someImage.jpg";
let siteAssetsUrl = this._context.pageContext.site.absoluteUrl + "siteassets/";
let fileUrl = `${siteAssetsUrl}${fileName}`;
//Can be something like:
//https://foo.sharepoint.com/sites/MyModernSite/siteassets/someImage.jpg
```

Due to the crop functionality the same image gets overwritten over and over again. When referencing to it there is some unexpected behaviour: Hitting F5 and refreshing the latest 2 or 3 versions change up each other randomly. When accessing `https://foo.sharepoint.com/sites/MyModernSite/siteassets/someImage.jpg` directly in the browser (with client caching deactivated through DevTools in Chrome), it is not always the latest version of the file. Just hitting F5 repeatedly and the image changes...

What kind of caching is going on in the site assets? What would be the best way to truly overwrite a file without having its history?

Appreciate any help, thank you!

pnp/sp version: 1.2.8
Environment: SharePoint Online
Modern team site

**Comment by patrick-rodgers** [comment]
Hi @MijoBarbaric - we don't have any visibility into how the SPO caching is working. This isn't a library issue as such - but perhaps you can maintain the image in memory while you are editing it and only do updates when the user clicks a button? Or perhaps you can append some random string to the end ?t=8387 each time you request the image and see if that gets you around any caching? Or perhaps you can look at the get preview functionality which might bypass any caching, not sure.

```
const f = new SharePointQueryable(webUrl, "_layouts/15/getpreview.ashx");
f.query.set("guidSite", `${siteId}`);
f.query.set("guidWeb", `${webId}`);
f.query.set("guidFile", `${imgId}`);
const imageUrl = f.toUrlAndQuery();
```

Going to close this as non-library. You may find more help in the [tech community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) or [sp-dev-docs](https://github.com/sharepoint/sp-dev-docs/issues).
