### ISSUE TITLE
Add DateTime field with default date to Today's Date

### ISSUE THREAD

**Issue by simkessy** [pnp/pnpjs#590]
How would I add a field that's a DateTime with the default date being Today's Date? 

### Category
- [ ] Enhancement
- [ ] Bug
- [ x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   Latest     ]

**Comment by tsekityam** [comment]
I suggest to use schemal XML to create the field.
i.e.
```ts
let w = new Web("https://example.sharepoint.com/");
w.lists.getByTitle("Example").fields.createFieldAsXml(`<Field DisplayName="Test" FriendlyDisplayFormat="Disabled" Format="DateOnly" Title="Test" Type="DateTime" StaticName="Test" Name="Test"><Default>[today]</Default></Field>`
).then(result => {
    console.log(result);
});
```

**Comment by patrick-rodgers** [comment]
@tsekityam's answer works well, would also suggest this as easiest approach. Going to close this as answered. Thanks!
