### ISSUE TITLE
ClientSidePages: Update existing control properties

### ISSUE THREAD

**Issue by olemp** [pnp/pnpjs#596]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

Would like the ability to update control properties.

Example:

```typescript
const plannerWebPartId = '39c4c1c2-63fa-41be-8cc2-f6c0b49b253d';
const page = await ClientSidePage.fromFile(sp.web.getFileByServerRelativePath(`${this.props.webServerRelativeUrl}/SitePages/Hjem.aspx`));
const plannerControl = page.findControl(c => c.json.webPartId === plannerWebPartId);
plannerControl.setProperties<any>({ planId: 'dhhasdh32' });
plannerControl.update();
await page.save();
```

**Comment by patrick-rodgers** [comment]
OK, I think this works now - unsure on the request? Is there a bug in the setProperties method?

**Comment by olemp** [comment]
`plannerControl` is of type `ColumnControl`. It's `ClientSideWebpart` that has the `setProperties` method.

**Comment by olemp** [comment]
So this part is what I want implemented. Sorry if that was unclear.

```typescript
plannerControl.setProperties<any>({ planId: 'dhhasdh32' });
plannerControl.update();
```

**Comment by olemp** [comment]
Looks like Control is "castable".

```typescript
 const page = await ClientSidePage.fromFile(sp.web.getFileByServerRelativePath(`${this.props.webServerRelativeUrl}/SitePages/${pageName}.aspx`));
    const control = page.findControl(c => objectGet(c, 'json.webPartId') === webPartId) as ClientSideWebpart;
    control.setProperties<any>({
      ...objectGet(control, 'data.webPartData.properties'),
      ...properties,
    });
    await page.save();
```

**Comment by wobba** [comment]
@olemp Would you consider adding this as a sample to the documentation in a PR? :) https://github.com/pnp/pnpjs/blob/dev/packages/sp/docs/client-side-pages.md

**Comment by patrick-rodgers** [comment]
Control is castable but also findControl is a generic. So you can do something like: `~findControl<ClientSideWebpart>(blah)` and it should work as you expect.

**Comment by olemp** [comment]
Figured 1 minute later. 😬
