### ISSUE TITLE
addClientSidePageByPath() not able create Client page is specified Path

### ISSUE THREAD

**Issue by Joy-jeevan** [pnp/pnpjs#598]
### Category
-  Bug

### Version

Please specify what version of the library you are using: [ 1.3.2  ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online    ]

### Expected / Desired Behavior / Question
const page = await sp.web.addClientSidePageByPath(`file-name`, "/sites/dev/SitePages/clientPages");

the above code should create page in /sites/dev/SitePages/clientPages but it creates in /sites/dev/SitePages/  which is default directory

**Comment by patrick-rodgers** [comment]
The backend API currently only supports creating pages at the root, not in sub folders. This isn't a bug, just what we are able to provide based on what is available to us from the service.

**Comment by Joy-jeevan** [comment]
thanks :) I tried that method has it was mentioned in document and was not working.

**Comment by patrick-rodgers** [comment]
Cool, going to close this as answered. Thanks!
