### ISSUE TITLE
Error when deleting a modern page comment

### ISSUE THREAD

**Issue by wobba** [pnp/pnpjs#599]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.2]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Steps to Reproduce

Using the following code

```ts
const comments = await item.comments.get(spODataEntityArray<Comment, CommentData>(Comment));
await comments[0].delete();
```

Looking at network trace this generates the following error from a `POST` request:

```json
Uncaught (in promise) Error: Error making HttpClient request in queryable [400]  ::>
{"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException",
"message":{"lang":"en-US","value":"The expression
 \"https:/foo.sharepoint.com/teams/Test/_api/web/lists('c4461b11-9c0a-42dc-93b0-a38f68d8245e')/GetItemById(2)/Comments(4)/DeleteComment\"
is not valid."}}}
```

Looking at the network traffic when deleting from the UI a `DELETE` REST request is made to:
```
https://techmikael.sharepoint.com/teams/BedreTest/_api/web/lists('%7Bc4461b11-9c0a-42dc-93b0-a38f68d8245e%7D')/GetItemById(2)/Comments(4)
```

Seems there has been an API change in the background perhaps? Testing this in a TR tenant.

**Comment by patrick-rodgers** [comment]
Thanks, will have a look.

**Comment by patrick-rodgers** [comment]
Updated, will close this on merge.
