### ISSUE TITLE
TypeScript errors. SP2016 On-Premises, PnP 1.3.1

### ISSUE THREAD

**Issue by FullStackRafik** [pnp/pnpjs#600]
I get some errors each time I run "npm install" then "gulp serve" or "gulp build".
Here are the errors I get:

node_modules\@pnp\common\src\util.d.ts(66,56): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\common\src\util.d.ts(66,88): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\parsers.d.ts(44,36): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\queryable.d.ts(88,24): error TS1005: ',' expected.
node_modules\@pnp\sp\src\items.d.ts(59,0): error TS1128: Declaration or statement expected.
 error TS2346: Supplied parameters do not match any signature of call target.
I can resolve the issue by removing some created folders inside 'gulp-core-build-typescript'.

**Comment by koltyakov** [comment]
Please check the corresponding docs section: https://pnp.github.io/pnpjs/documentation/SPFx-On-Premesis-2016/

**Comment by FullStackRafik** [comment]
But as mentioned in this section: 
> Note this article applies to version 1.4.1 SharePoint Framework projects targetting on-premesis only.

But I'm using the version 1.1.0 SharePoint Framework  because I'm using Sharepoint 2016 on-premesis.

**Comment by patrick-rodgers** [comment]
It is the same error, we should update the docs to say =< 1.4.1. The errors comes from the older version of TypeScript.

**Comment by FullStackRafik** [comment]
It's fixed, thanks.
