### ISSUE TITLE
Work with data in batch calls. 

### ISSUE THREAD

**Issue by enti333** [pnp/pnpjs#602]
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

Hello. I want to ask if is possible in batch working with items from for example first call:
`let rUser;
    let batch = web.createBatch();

    sp.web.currentUser.inBatch(batch).get().then((r: CurrentUser) => {
      rUser = r;
    });
sp.web.siteGroups.getByName("GroupName").users.inBatch(batch).getById(rUser["Id"]).get().then(rs => {
///
    }).catch(error => {
      console.log("user does not belong");
    });

batch.execute()`

This is only example the main problem how to work with data from first call in second call. 
How to please achieve this by batch. 
Thank you

**Comment by koltyakov** [comment]
There was a similar question not far ago: https://github.com/pnp/pnpjs/issues/548#issuecomment-472329724

A value from one request no matter batch it or not can be used in another one if it's already resolved on the client.

**Comment by patrick-rodgers** [comment]
Yes, once the data comes back it is just JSON data like any other.
