### ISSUE TITLE
SPFetchClient TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by TylerDurham** [pnp/pnpjs#603]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.2]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question

Running the [Getting Started](https://pnp.github.io/pnpjs/nodejs/docs/sp-fetch-client/) sample code for NodeJS and not getting an exception.

### Observed Behavior
I'm getting the following error:
TypeError: Cannot read property 'filter' of undefined
    at SPFetchClient.<anonymous> (C:\Development\SmartterHealth\sh-provisioning\node_modules\@pnp\nodejs\dist\nodejs.es5.umd.js:2509:58)
    at step (C:\Development\SmartterHealth\sh-provisioning\node_modules\@pnp\nodejs\dist\nodejs.es5.umd.js:77:35)
    at Object.next (C:\Development\SmartterHealth\sh-provisioning\node_modules\@pnp\nodejs\dist\nodejs.es5.umd.js:58:65)
    at fulfilled (C:\Development\SmartterHealth\sh-provisioning\node_modules\@pnp\nodejs\dist\nodejs.es5.umd.js:48:70)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

### Steps to Reproduce

Run the following code after project setup.

import { sp } from "@pnp/sp";
import { SPFetchClient, SPOAuthEnv } from "@pnp/nodejs";

const CLIENT_ID = "MYCLIENTID";
const CLIENT_SECRET = "MYCLIENTSECRET";
const REALM = "MYREALM";

// configure your node options (only once in your application)
sp.setup({
    sp: {
        fetchClientFactory: () => {
            return new SPFetchClient("https://mytenant.sharepoint.com/sites/mysite", CLIENT_ID, CLIENT_SECRET, SPOAuthEnv.SPO, REALM );
        },
    },
});

// execute a library request as normal
sp.web.get().then(w => {
    console.log(JSON.stringify(w, null, 4));
}).catch(e => {
    console.error(e);
});

**Comment by williamyinssw** [comment]
@TylerDurham , I'm just wondering if you have resolved this issue, because it's closed without a solution. I'm currently testing SPFetchClient against on premises SharePoint environment, and facing the same issue. If you can tell a bit about your solution fixing it that would be great ;)

**Comment by williamyinssw** [comment]
@jrwiller13 Thank you.
I wonder which authentication strategy did you choose when you initialize the `./config/private.config.json` file?
Did you use "Add-In Only permissions (On-Prem)"?

I had a discussion with @koltyakov and @s-KaiNet at [Gitter](https://gitter.im/sharepoint-node/Lobby?at=5bbe6037f659e67772936d1a), it looks like there are additional configuration steps needed for on-premises SharePoint environment if we want to use SPFetchClient with "Add-in-authentication" for on-premises SharePoint.
Detail steps can be found at this [wiki page ](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint-on-premise-addin-only-authentication).

**Comment by jrwiller13** [comment]
@williamyinssw For our purposes, we have a bunch of service accounts that we use for our automated processes so unfortunately, I went that avenue for our Node.js processes.
