### ISSUE TITLE
Calendar Recurring Events not expanding. 

### ISSUE THREAD

**Issue by cvairavan-1980** [pnp/pnpjs#605]
### Category
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
1.3.2
Please specify what version of the library you are using: [   1.3.2      ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online         ]

### Expected / Desired Behavior / Question
I am trying to get Events from Calendar along with Recurring Events using getItemsByCAMLQuery with QueryOptions. It is returning Parent Recurring Event but not expanidng  it. If the event marked as Daily, expecting to show events data for daily. Is it an issue or I am any doing anything wrong?

Below is my code
const xml = `<View> \
    <ViewFields> \
    <FieldRef Name=`Title` /> \
    <FieldRef Name=`EventDate` /> \
    <FieldRef Name=`EndDate` /> \
    <FieldRef Name=`Location` /> \
    <FieldRef Name=`Description` /> \
    <FieldRef Name=`fRecurrence` /> \
    <FieldRef Name=`RecurrenceData` /> \
    <FieldRef Name=`fAllDayEvent` /> \
    <FieldRef Name=`ID` /> \
    </ViewFields> \
        <Query> \
        <Where> \
    <DateRangesOverlap> \
        <FieldRef Name=`EventDate` /> \
        <FieldRef Name=`EndDate` /> \
        <FieldRef Name=`RecurrenceID` /> \
        <Value Type=`DateTime`> \
            <Today /> \
        </Value> \
    </DateRangesOverlap> \
</Where> \
<OrderBy> \
    <FieldRef Name=`EventDate` /> \
</OrderBy>\
          </Query> \
          <QueryOptions> \
          <CalendarDate>` + new Date().toISOString() + `</CalendarDate>\
<ExpandRecurrence>TRUE</ExpandRecurrence>\
          <RecurrencePatternXMLVersion>v3</RecurrencePatternXMLVersion>\
          <RecurrenceOrderBy>TRUE</RecurrenceOrderBy>\
          <ViewAttributes Scope=`RecursiveAll`/>\
          </QueryOptions>\
          <RowLimit>10</RowLimit> \
          </View>`;
    let q: pnp.CamlQuery = {
      ViewXml: xml,
      
    };
     

    pnp.sp.web.lists.getByTitle(LIST_NAME).items.filter(dateFilter).get().then(
      res=>{
        console.log('Direct Method..');
        console.log(res);
      }
    );

**Comment by sympmarc** [comment]
You also need to have this in the Query Options in the CAML:
`<ExpandRecurrence>TRUE</ExpandRecurrence>`
See my post [Retrieving Expanded Calendar Events with REST vs. SOAP](https://sympmarc.com/2015/07/07/retrieving-expanded-calendar-events-with-rest-vs-soap/)

**Comment by cvairavan-1980** [comment]
> You also need to have this in the Query Options in the CAML:
> `<ExpandRecurrence>TRUE</ExpandRecurrence>`
> See my post [Retrieving Expanded Calendar Events with REST vs. SOAP](https://sympmarc.com/2015/07/07/retrieving-expanded-calendar-events-with-rest-vs-soap/)

Hi Sympmarc

Thanks for your reply. I have added ExpandRecurrence in the QueryOptions but still it is not expanding. And I came across your post even before also. I am not using SpServices library and looking for options in Sp-Pnp-Js. As your post was belong to July 2015, thought there will be some update.

**Comment by koltyakov** [comment]
Recurrent events is the pain in API, no support in OData. If `getItemsByCAMLQuery` doesn't work, you can try `renderListData` and `renderListDataAsStream`, e.g.:

```typescript
import { sp } from '@pnp/sp';

sp.web.lists.getByTitle('Calendar')
    .renderListDataAsStream({
        OverrideViewXml: `
            <QueryOptions>
                <ExpandRecurrence>TRUE</ExpandRecurrence>
            </QueryOptions>
        `
    })
    .then(console.log)
    .catch(console.log);
```

![image](https://user-images.githubusercontent.com/7816483/56409753-1ab7c600-6283-11e9-8cda-0035389ff730.png)

**Comment by koltyakov** [comment]
UPD: Or by default `renderListDataAsStream` does it. So start with `renderListDataAsStream` and find the corresponding caml or override which works for the usecase.

```typescript
sp.web.lists.getByTitle('Calendar').renderListDataAsStream({}).then(console.log).catch(console.log);
```

**Comment by cvairavan-1980** [comment]
> UPD: By default `renderListDataAsStream` does it. So start with `renderListDataAsStream` and find the corresponding caml or override which works for the usecase.
> 
> ```ts
> sp.web.lists.getByTitle('Calendar').renderListDataAsStream({}).then(console.log);
> ```
> 
> My assumption on OverrideViewXml in the previous sample was a false positive.
Hi koltyakov,

Thanks for the reply.
My use case is to retrieve the Upcoming events from the calendar with pagination.

Below are my findings..

1. for renderListDataAsStream() method, ExpandRecurrence is not needed as it is expanding it by default.
2. RowLimit option in mentioned in the view xml, didn't have any impact. Sample below

    const xml = " <View>       <Query> \
        <Where> \
    <DateRangesOverlap> \
        <FieldRef Name='EventDate' /> \
        <FieldRef Name='EndDate' /> \
        <FieldRef Name='RecurrenceID' /> \
        <Value Type='DateTime'> \
            <Now /> \
        </Value> \
    </DateRangesOverlap> \
</Where> \
<OrderBy> \
    <FieldRef Name='EventDate' /> \
</OrderBy>\
          </Query> \
          <RowLimit Paged='TRUE'>10</RowLimit> \ 
          </View>";

3. For Paging, we have to pass the we need to pass the Paging value.

sp.web.lists.getByTitle(LIST_NAME).renderListDataAsStream({OverrideViewXml: xml, Paging:'Paged=TRUE&RowLimit=5'}).then(
      res=> { console.log(res); })

4. But facing problem when trying to get 2nd Page. As per the document, to get the second page, we need to pass Last Id, and Last Title from the first page. In case of Recurring events, ID return was "2.0.2019-04-19T10:30:00Z" (It is there in your screen shot also). If we pass this value, getting empty rows.
sp.web.lists.getByTitle(LIST_NAME).renderListDataAsStream({OverrideViewXml: xml, Paging:'Paged=TRUE&RowLimit=5'}).then(
      res=> { console.log(res);
         const lstId = res.Row[res.Row.length-1].ID;
        const lstTitle =  res.Row[res.Row.length-1].Title;
        console.log(lstId);
        console.log(lstTitle);
//Getting Second Page data
         sp.web.lists.getByTitle(LIST_NAME).renderListDataAsStream({OverrideViewXml: xml, Paging:'Paged=TRUE&RowLimit=5&p_ID=${lstId}&p_Title=${lstTitle}'}).then(
          res1=> { console.log(res1);           
            });
      });

Looking for work around. If I find anything update here..

**Comment by patrick-rodgers** [comment]
Going to close this as it doesn't appear to be an issue with the library. If there is still an issue here I missed please open a new issue and reference this one explaining what is not working and we can take a look. Thanks!

**Comment by Rameishvaghela** [comment]
> UPD: By default `renderListDataAsStream` does it. So start with `renderListDataAsStream` and find the corresponding caml or override which works for the usecase.
> 
> ```ts
> sp.web.lists.getByTitle('Calendar').renderListDataAsStream({}).then(console.log);
> ```
> 
> My assumption on OverrideViewXml in the previous sample was a false positive.

How can I selecct the column..i used this but not able to find the Category column in it.
