### ISSUE TITLE
Changing Search context

### ISSUE THREAD

**Issue by jcosta33** [pnp/pnpjs#606]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.2]

Please specify what version(s) of SharePoint you are targeting: [Modern SPO]

### Expected / Desired Behavior / Question
I'd like to change the context of the Search object but it seems that instantiating it as `const search = new Search(absoluteURL)` isn't making any difference in the results of the query. Am I doing something wrong or is this just possible?

**Comment by koltyakov** [comment]
Hi @jcosta33,

Actually, `new Search(webAbsUrl)` ends up sending requests to provided `webAbsUrl`.

```typesctipt
const search = new Search(webAbsUrl);
search.execute('*').then(console.log).catch(console.log);
``` 

however, you probably searching for a way to limit search with a specific web, then this is what you probably need:

```typescript
search.execute(`* Path:${webAbsUrl}`).then(console.log).catch(console.log);
```

**Comment by jcosta33** [comment]
I think that was it, thanks!

**Comment by koltyakov** [comment]
Cool. Closing the issue.
