### ISSUE TITLE
Incorrect legacy SharePoint client.svc/ProcessQuery endpoint

### ISSUE THREAD

**Issue by FaganSC** [pnp/pnpjs#607]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [ 1.3.2 ]
Please specify what version(s) of SharePoint you are targeting: [ Online ]

### Expected / Desired Behavior / Question
In use the package **@pnp/sp-taxonomy** to call Terms from the Term Store, the Endpoint URL do not always generate correctly. I know it's using the legacy SharePoint client.svc/ProcessQuery endpoint.

I've been this issue also with calling the SharePoint Rest API Endpoint in another project yesterday, but I'll submit an issue for that one when I get a chance to reproduce it. 

### Observed Behavior
When calling the Terms Endpoint from the root site collection home page **https://tenant.sharepoint.com**, the endpoint URL is correct with calling **https://tenant.sharepoint.com/_vti_bin/client.svc/ProcessQuery?**

When calling the Terms Endpoint from another site collection home page **https://tenant.sharepoint.com/sites/team**, the endpoint URL is incorrect with https://tenant.sharepoint.com/sites/_vti_bin/client.svc/ProcessQuery? and drops the site collection part of the URL

However, when calling the Terms Endpoint from that second site collection document library page **https://tenant.sharepoint.com/sites/team/Shared%20Documents/**, the endpoint URL is correct with https://tenant.sharepoint.com/sites/team/_vti_bin/client.svc/ProcessQuery? 

### Steps to Reproduce
Use the example from the site https://pnp.github.io/pnpjs/sp-taxonomy/docs/terms/

Works on Root Site Collection but not Site Collection Home Pages

Looks to be an issue with parsing the URL to generate the Endpoint URL.

**Comment by patrick-rodgers** [comment]
Have you [called the setup method](https://pnp.github.io/pnpjs/documentation/getting-started/#establish-context) to ensure the base url is set? Can you also share a fuller sample of your code? Thanks.

**Comment by FaganSC** [comment]
Now I feel kind of stupid now. That was the issue. Odd that haven't had to do that for other calls, but it might be the same reason it worked on the root site collection and not other site collections. I'm going to have to double check some of my current deployments to make sure they might not have the same issue if used in different sites. Thanks @patrick-rodgers for your help!

**Comment by patrick-rodgers** [comment]
No worries. It is tricky because depending on the scenario we do our best to auto-capture the web url, but can't in SPFx for example. We can on the workbench, which sometimes causes confusion. That is why we always recommend calling setup so there is no question as to what is happening.
