### ISSUE TITLE
node_modules\@pnp\sp\src\sharepointqueryable.d.ts(108,48): error TS1005: ',' expected.

### ISSUE THREAD

**Issue by Nagarajan1605** [pnp/pnpjs#608]
Warning - tslint - src\webparts\demoPnpwp\components\DemoPnpwp.tsx(7,22): error whitespace: missing whitespace
Warning - tslint - src\webparts\demoPnpwp\components\DemoPnpwp.tsx(17,13): error whitespace: missing whitespace
Error - typescript - node_modules\@pnp\common\src\util.d.ts(66,56): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\common\src\util.d.ts(66,88): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\parsers.d.ts(44,36): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\queryable.d.ts(88,24): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\queryable.d.ts(89,25): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\queryable.d.ts(90,26): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\queryable.d.ts(91,27): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\queryable.d.ts(92,24): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\queryable.d.ts(132,83): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\queryable.d.ts(165,10): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\queryable.d.ts(166,24): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\queryable.d.ts(167,25): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\queryable.d.ts(168,26): error TS1005: ',' expected.
Error - typescript - node_modules\@pnp\odata\src\queryable.d.ts(169,27): error TS1005: ',' expected.

Node version: v8.11.3
`-- @microsoft/sp-build-web@1.1.0
  `-- @microsoft/gulp-core-build-typescript@3.1.1
    +-- @microsoft/api-extractor@2.3.8
    | `-- typescript@2.4.2
    `-- typescript@2.2.2
Am using react framework in that i have installed @pnp-sp to perform CRUD operation. But its creating this issue. Could you please help me.

**Comment by koltyakov** [comment]
Hi @Nagarajan1605, 

So you're using SPFx for On-Prem?

The same was asked many times. The steps which should be taken are described [here](https://pnp.github.io/pnpjs/documentation/SPFx-On-Premesis-2016/).

Also, you might need adding "skipLibCheck": true option in tsconfig.json/compilerOptions.

If nothing helps, please post a bare minimum project repository which we can clone and reproduce the issue.

**Comment by Nagarajan1605** [comment]
"skipLibCheck": true,

**Comment by bricenocar** [comment]
I had the same issue, this is what I did: [link](https://github.com/pnp/pnpjs/issues/687). Hope it helps :)

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Please open a fresh issue if you are still having problems. Thanks!
