### ISSUE TITLE
create team site not allowing to pass site design parameter

### ISSUE THREAD

**Issue by praveenbattula** [pnp/pnpjs#609]
sp.site.createModernTeamSite() is not accepting the site design parameter to run site scripts upon team site creation. If we add this parameter, then we can take advantage of the full API capabilities. 

### Category
- [x ] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [   1.3.1-2.      ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online      ]

### Expected / Desired Behavior / Question
sp.site.createModernTeamSite() is not accepting the site design parameter to run site scripts upon team site creation. If we add this parameter then we can take advantage of the full API capabilities. 

### Observed Behavior
Currently it is not accepting the site script/site design parameter.

### Steps to Reproduce
you can check the method parameters.

**Comment by patrick-rodgers** [comment]
Added this, will be part of next release on Friday July 12
