### ISSUE TITLE
Filter items by a property through all versions

### ISSUE THREAD

**Issue by FullStackRafik** [pnp/pnpjs#611]
I need to filter items by a property through all versions history.
When I use this code, I get an error( result[0].versions undefined)
 ```
import {Web} from  "@pnp/sp";
let web = new Web(siteUrl);
web.lists.getByTitle(listName).items.get().then((result) => {
          result[0].versions.get().then(console.log); 
        });
```
through url:
`https://.........../_api/web/lists/getByTitle('MyList')/items/getById(4)?$select=versions`
There is no field or "versions" property.

Any suggestions please?

**Comment by Rens-Braspenning** [comment]
Currently figuring out the same thing. It seems the property is '**V**ersions'

`list.items.getById(this.props.listitemid).select('Versions').expand('Versions').get().then((item: Item) => {
          console.log(item['Versions']);
        });`

**Comment by FullStackRafik** [comment]
It doesn't work:
There is no field or property "Versions".

**Comment by koltyakov** [comment]
Versions should be expanded when getting version info along with item's metadata:

![image](https://user-images.githubusercontent.com/7816483/56651334-7a520f00-6691-11e9-87ed-24da30d60e7e.png)

**Comment by FullStackRafik** [comment]
Hre is my code:
`web.lists.getByTitle(listName).items.getById(4).select('*,Versions').expand('versions').get().then((item) => { console.log });`

Here is the error I get:
```
Failed to load resource: the server responded with a status of 400 (Bad Request) [https://.../_api/web/lists/getByTitle('MyList')/items(4)?$select=*,Versions&$expand=versions]
Error: Error making HttpClient request in queryable [400] Bad Request ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.SPException","message":{"lang":"fr-FR","value":"Il n'existe pas de champ ni de propri\u00e9t\u00e9 \u00ab\u00a0Versions\u00a0\u00bb."}}}
```
 

That means: There is no field or property "Versions".

**Comment by koltyakov** [comment]
Versions API support in REST appeared far after 2016, so this won't work. If I'm not wrong versions in REST were introduced in SPO in 2017-2018-something. Previously, there were /versions for files.

**Comment by FullStackRafik** [comment]
So there is no solution to get an item's versions using PnP for Sharepoint 2016 On-Prem?

**Comment by koltyakov** [comment]
`item.file.versions` should return some (not very useful info but anyway info) in SP 2016.

Also, when I got to deal with versions in 2016 last time legacy SOAP (GetVersionCollection, /_vti_bin/lists.asmx) was the only possible way to get extended info. SOAP can be consumed with PnPjs as well, using `SPHttpClient`.

Not a complete code (as I can't copy it from the project as is):

```typescript
const soapBody = `
    <?xml version="1.0" encoding="utf-8"?>
    <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
      <soap:Body>
        <GetVersionCollection xmlns="http://schemas.microsoft.com/sharepoint/soap/">
          <strlistID>${props.listId}</strlistID>
          <strlistItemID>${props.itemId}</strlistItemID>
          <strFieldName>${props.fieldName}</strFieldName>
        </GetVersionCollection>
      </soap:Body>
    </soap:Envelope>
`;

const soapHeaders = (soapBody: string): any => {
  return {
    'Accept': 'application/xml, text/xml, */*; q=0.01',
    'Content-Type': 'text/xml;charset="UTF-8"',
    'X-Requested-With': 'XMLHttpRequest',
    'Content-Length': soapBody.length
  };
};

const httpClient = new SPHttpClient();

httpClient.post(`${props.siteUrl}/_vti_bin/lists.asmx`, {
  headers,
  body: soapBody,
  json: false
} as any)
  .then(r => r.text())
  .then(parseXml) // from import { parseString } from 'xml2js';
  .then(r => r['soap:Envelope']['soap:Body'][0].GetVersionCollectionResponse[0].GetVersionCollectionResult[0])
  .then(r => (r.Versions[0].Version || []).map(v => v.$));
```

**Comment by koltyakov** [comment]
And yes, versions in old SharePoint versions is a real pain and yeah 2016 is old one already. ;)
