### ISSUE TITLE
Use aliases as much as possible

### ISSUE THREAD

**Issue by wmertens** [pnp/pnpjs#613]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [latest]

Please specify what version(s) of SharePoint you are targeting: [   2013      ]

### Expected / Desired Behavior / Question

I sometimes encounter URLs that are too long. To work around this, I try to look up things by list ID but that's not always possible.

It would be great if all aliasable parameters of a url were aliased, so that the url length is minimal.

**Comment by patrick-rodgers** [comment]
We already have the capability for you [to alias parameters for these scenarios](https://pnp.github.io/pnpjs/sp/docs/alias-parameters/). I am not sure there is a benefit for the majority of use cases to add the complexity to alias everything internally. We do for some methods, but when chaining things we would have to track what alias names were already used, etc. IMO better to use the existing capability the few times when you need it.

**Comment by wmertens** [comment]
IMHO, alias parameters are (once again) a peculiarity due to the REST API, which this library strives to abstract away.

Aliases are strictly better than embedding paths, and this library can better keep track of the alias names in use for a resource than the library users.

In any case, for my use case manual aliases are doable, thanks :)

**Comment by wmertens** [comment]
Actually, I can't even find the documentation for the Sharepoint REST API for aliases :( I wanted to find the exact naming scheme and case sensitivity etc - it would be better if this knowledge was embedded into the library.

**Comment by patrick-rodgers** [comment]
Going to close this as we have no plans to implement this as mentioned above. I understand your position that the library should contain everything possible, but work/value isn't there for me on this one. If someone would like to submit a PR we'll take a look at merging it. I would suggest at this point that if someone does want to do the work to please target the dev-v2 branch. Thanks!
