### ISSUE TITLE
PNP.js add item function is not working in sharepoint custom page

### ISSUE THREAD

**Issue by Nagarajan1605** [pnp/pnpjs#614]
<script type="text/javascript" src="/sites/MP/SiteAssets/js/jquery-1.12.3.min.js"></script>
	<script type="text/javascript" src="/sites/MP/SiteAssets/js/fetch.js"></script>
	<script type="text/javascript" src="/sites/MP/SiteAssets/js/es6-promise.js"></script>
    <script type="text/javascript" src="/sites/MP/SiteAssets/js/pnp.min.js"></script>
	<script type="text/javascript" src="/sites/MP/SiteAssets/js/moment.js"></script>
	<script type="text/javascript" src="/sites/MP/SiteAssets/js/jquery-ui.js"></script>
	<script src="/sites/MP/SiteAssets/js/bootstrap.min.js"></script>
	<script src="/sites/MP/SiteAssets/js/bootstrap-datepicker.js"></script>
$("#btnPotentialTopic").click(function(){
debugger;
_documentTypes=$('input:radio[name=radio-group]:checked').parent().find('label').text();
_policyDocument=$('input:radio[name=radio-groupPolicy]:checked').parent().find('label').text();
_dateTopicEntered=$("#Date-Topic-Entered").val();
_potentialDocumentType=$("#PotentialDocType :selected").text();
_potentialTopicCreatedBy=$("#Potentialtopiccreatedby :selected").text();
_potentialTopicReadyforDevelopment=$('input:radio[name=radio-groupPolicyDevelopment]:checked').parent().find('label').text();
AddPotentialtopic();
});

function AddPotentialtopic(){
debugger;
$pnp.sp.web.lists.getByTitle("WOW").items.add({
DocType:_documentTypes,
PotentialTopic:_policyDocument,
TopicEnteredDate:_dateTopicEntered,
PotDocType:_potentialDocumentType,
PotentialtopicCreatedby:_potentialTopicCreatedBy,
PotTopicRdyForDev:_potentialTopicReadyforDevelopment

}).then(results=>{
alert("Your Data has been saved sucessfully");
console.log(results);
window.location.href="/sites/MP/SitePages/Report.aspx";
});

}

After executing this code its coming inside the Addpotential topic function and execute the pnp add item function but finally its not adding the data and not coming inside the results section.

No error in console too. Could you please tell me what could be the issue.

This is not SPFx. I put the custom page in share point and executing this code.

Item has to add and it should enter in to the result section and page should be redirect to report.aspx

**Comment by koltyakov** [comment]
Hi @Nagarajan1605, 

There are no issues with basic operations obviously. 

Please specify the version of PnPjs which you use and results from network tab in DevTools, also in what browser the issue is experienced.

I doubt that bare minimal configuration is correct. Please make sure that you're following docs recommendations: [getting started](https://pnp.github.io/pnpjs/documentation/getting-started/#getting-started-outside-sharepoint-framework), [polyfills](https://pnp.github.io/pnpjs/documentation/polyfill/) and [deployment](https://pnp.github.io/pnpjs/documentation/deployment/).

If it's IE used, some polyfills are missed.

What's `pnp.min.js`? Probably not a bundled (pnpjs.es5.umd.bundle.min.js).

Why `$pnp`? For a pretty long time `pnp` is a global alias. Deprecated `sp-pnp-js` had been deprecated a year ago.

Also, you miss `catch` condition in the promise and won't see any error because of incorrect payload or missing list, etc.

**Comment by CPritch** [comment]
@koltyakov , @Nagarajan1605 

I can also add to this and say that we have an integration of pnp-js running on custom SharePoint classic pages just fine. Whilst we do everything in modern now it is simple enough to do this once you have webpack and a TS loader set up.

Here's a modified version of a larger class where we initialise SP from a classic page:

```TS
import { sp } from "@pnp/sp";

declare global {
  interface Window {
    ExecuteOrDelayUntilScriptLoaded: any;
    _spPageContextInfo: any;
  }
}

export class pnpClassic {
  public pageCtx: any;
  constructor() {
    this.pageCtx = {};
    window.ExecuteOrDelayUntilScriptLoaded(() => {
      this.initialize();
    }, "sp.js");
  }

  private initialize(): void {
    // Set context for classic pages
    if (window._spPageContextInfo) {
      this.pageCtx.rootWebUrl = window._spPageContextInfo.webAbsoluteUrl;
    } else {
      console.error("Error: No page context available.");
      return;
    }
    sp.setup({
      sp: {
        headers: {
          Accept: "application/json;odata=verbose"
        },
        baseUrl: this.pageCtx.rootWeb
      }
    });
  }
}
```

Please be aware that this class is not a singleton so you're best of integrating that design pattern for something like this.

**Comment by Nagarajan1605** [comment]
in IE browser its not working. I am able to perform crud operations in edge and chrome browser. 

Hi,
 
I am doing CRUD operation using pnp.js in sharepoint site through custom page. I am able to perform all the actions in EDGE and Chrome browser. 
 
But when i try to do the same in IE browser its not working. 
 
Getting the error as 401. 
 
I received Request header: Accept: image/gif, image/jpeg, image/pjpeg, application/x-ms-application, application/xaml+xml, application/x-ms-xbap, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*Accept-Encoding: gzip, deflateAccept-Language: en-USAuthorization: NTLM TlRMTVNTUAABAAAAB4IIogAAAAAAAAAAAAAAAAAAAAAKAO5CAAAADw==Connection: Keep-AliveCookie: WSS_FullScreenMode=falseHost: portaldev.ibx.comIf-Modified-Since: Mon, 13 May 2019 12:09:39 GMTUser-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; Zoom 3.6.0) 
 
 
Response header:  
Content-Length: 0
Date: Mon, 13 May 2019 12:13:30 GMT
MicrosoftSharePointTeamServices: 16.0.0.4822
request-id: 9934dc9e-a935-0049-b7d0-2c747ec5a0ba
Server: Microsoft-IIS/10.0
SPIisLatency: 0
SPRequestDuration: 1
SPRequestGuid: 9934dc9e-a935-0049-b7d0-2c747ec5a0ba
WWW-Authenticate: NTLM TlRMTVNTUAACAAAAEAAQADgAAAAFgomiUcK1cn/yL0oAAAAAAAAAAIoAigBIAAAACgA5OAAAAA9MAEEATgBHAFIATwBVAFAAAgAQAEwAQQBOAEcAUgBPAFUAUAABABAAVwBTAFMAUABMAE4AMAAxAAQADgBpAGIAeAAuAGMAbwBtAAMAIABXAFMAUwBQAEwATgAwADEALgBpAGIAeAAuAGMAbwBtAAUAGABhAGQAZgBvAHIAZQBzAHQALgBjAG8AbQAHAAgAGR2VR4UJ1QEAAAAA
X-Content-Type-Options: nosniff
X-FRAME-OPTIONS: SAMEORIGIN
X-MS-InvokeApp: 1; RequireReadOnly
X-Powered-By: ASP.NET
 
Herewith i have attached the error screenshot.  
 
![PNP Notworking in IE browser](https://user-images.githubusercontent.com/21313599/57622244-cb776380-75aa-11e9-92f0-70e55b1bdce6.jpg)

**Comment by Nagarajan1605** [comment]
Am using Custom Page in SharePoint and for CRUD operations am using PNP.js

**Comment by koltyakov** [comment]
@Nagarajan1605 [polyfills](https://pnp.github.io/pnpjs/documentation/polyfill/) must be used for IE.

**Comment by sympmarc** [comment]
@Nagarajan1605 - Take a look at the [polyfills for IE](https://pnp.github.io/pnpjs/documentation/polyfill/). It will probably solve your issue.

**Comment by Nagarajan1605** [comment]
https://cdn.polyfill.io/v2/polyfill.min.js?callback=stuffisloaded&features=es6,fetch,Map&flags=always,gated i have downloaded polyfills from the above url and used in my script as follows
**</div>**

<script type="text/javascript" src="http://portaldev.ibx.com/sites/MP/SiteAssets/js/polyfill.min.js"></script>
<script type="text/javascript" src="http://portaldev.ibx.com/sites/MP/SiteAssets/js/es6-promise.js"></script>
<script type="text/javascript" src="http://portaldev.ibx.com/sites/MP/SiteAssets/js/fetch.js"></script>
<script type="text/javascript" src="http://portaldev.ibx.com/sites/MP/SiteAssets/js/pnp.min.js"></script>


**<script>**
 var fileInfos = []; 
 var getattachment=[];
 var listid;
 var filename;
 var responseid;

am calling that script after my html design before the $document. ready script. But still am getting the error. Could you please help me on this issue.

**Comment by koltyakov** [comment]
With the sample from the docs taken as is but with add operation:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnp-pnpjs/1.3.2/pnpjs.es5.umd.bundle.min.js" type="text/javascript"></script>
<script>
function stuffisloaded() {

  pnp.sp.web.lists.getByTitle('CustomList').items.add({ Title: 'New item' })
    .then(function() { console.log('Added') })
    .catch(function(err) { console.log('Error', err) });

}
</script>
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?callback=stuffisloaded&features=es6,fetch,Map&flags=always,gated"></script>
```

everything works in IE11 for me.

However, I have a clue. You're probably on On-Prem and ending up with IE10 cause default X-UA-Compatible metatag. IE10 requires additional polyfills and is not something we ever aimed to support. On old legacy On-Prem projects, I usually use [SPPP generator](https://github.com/koltyakov/generator-sppp) and [this set of polyfills](https://github.com/koltyakov/sp-build-tasks/blob/master/src/webpack/polyfills.ts) and experienced no issues in IE even when it switches to IE10 compatibility mode.

**Comment by Nagarajan1605** [comment]
Am using IE 11 only, 
<html>
<head>

<script type="text/javascript" src="http://portaldev.ibx.com/sites/MP/SiteAssets/js/jquery.min.js"></script>
<script type="text/javascript" src="http://portaldev.ibx.com/sites/MP/SiteAssets/js/bootstrap.min.js"></script>
<script type="text/javascript" src="http://portaldev.ibx.com/sites/MP/SiteAssets/js/editor.js"></script>
<link rel="stylesheet" href="http://portaldev.ibx.com/sites/MP/SiteAssets/css/bootstrap.min.css"/>
<link rel="stylesheet" href="http://portaldev.ibx.com/sites/MP/SiteAssets/css/font-awesome.css"/>
<link rel="stylesheet" href="http://portaldev.ibx.com/sites/MP/SiteAssets/css/editor.css"/>
   





</head>
<body>

<div>

<button type="button" id="savedata">Save </button>
</div>

<div>

<button type="button" id="updatedata">update </button>
</div>

<div>

<button type="button" id="getdata">Get </button>
</div>



 <div id="fileuploader">
 <input type="file" id="exampleFormControlFile1" name="myfiles" multiple="multiple">
 <button type="button" id="uploadattachment">upload</button>
 </div>
 <div id="txtEditor">
 </div>
  <div id="divtxtEditor">
 </div>
<div id="attachmentdata"></div>
<div>
<textarea id="comment"></textarea>
</div>
<div><button type="button" id="Responsedata">Create Response </button></div>
<div>
<table id="responsetbl">

</table>

</div>

<script type="text/javascript" src="http://portaldev.ibx.com/sites/MP/SiteAssets/js/polyfill.min.js" defer></script>
<script type="text/javascript" src="http://portaldev.ibx.com/sites/MP/SiteAssets/js/es6-promise.map" defer></script>

<script type="text/javascript" src="http://portaldev.ibx.com/sites/MP/SiteAssets/js/es6-promise.js" defer></script>
<script type="text/javascript" src="http://portaldev.ibx.com/sites/MP/SiteAssets/js/fetch.js" defer></script>
<script type="text/javascript" src="http://portaldev.ibx.com/sites/MP/SiteAssets/js/pnp.min.js" defer></script>



<script>
 var fileInfos = []; 
 var getattachment=[];
 var listid;
 var filename;
 var responseid;
$(document).ready(function(){
debugger;

var richtextdata;
var rictextcontentdiv;
var id=9;
var attachmentdata=[];
$("#exampleFormControlFile1").on('change',function(){
blob();
});
$("#txtEditor").Editor(); 
$("#divtxtEditor").Editor(); 

 $pnp.sp.web.lists.getByTitle("MedicalPolicy").items.select("Title","Responseid","ID").filter("ID eq 16").get().then(function(results){
		responseid= results[0].ResponseId;
		
		
});

});

This is my code. I have few more functions which i didnt include here. 

When i debug the IE11 browser i am getting error at 

window.__BROWSERTOOLS_CONSOLE_SAFEFUNC = function (fn, safeAssert) { var returnFn = function __BROWSERTOOLS_CONSOLE_SAFEFUNC() { try { return fn(arguments); } catch (e) { safeAssert(e); } }; return returnFn;

After it executes return (arguments) It throws error. Do you have any solution to solve it.
