### ISSUE TITLE
SafeQueryPropertiesTemplateUrl is not a valid URL

### ISSUE THREAD

**Issue by johannes-z** [pnp/pnpjs#615]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.2]

Please specify what version(s) of SharePoint you are targeting: [SP2016]

### Expected / Desired Behavior / Question

Querying the sharepoint search using `sp.search(searchOptions)` on a sitecollection throws an error because it targets `/_api` instead of `/sites/subsite/_api`.

### Observed Behavior

```
{"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"The SafeQueryPropertiesTemplateUrl \"The SafeQueryPropertiesTemplateUrl &quot;{0}&quot; is not a valid URL.\" is not a valid URL."}}}
```

See https://paulryan.com.au/2016/calling-sharepoint-_api-wrong-root-site/

**Comment by johannes-z** [comment]
@patrick-rodgers Was this issue resolved?

**Comment by patrick-rodgers** [comment]
The issue here is very likely not performing the [setup steps as outlined in the guide](https://pnp.github.io/pnpjs/documentation/getting-started/#establish-context). Give those a try and please open a new issue with additional details referencing this one if that is not the case.
