### ISSUE TITLE
Expand Lookup field cache

### ISSUE THREAD

**Issue by FullStackRafik** [pnp/pnpjs#616]
When I retrieve items with expand function, it still getting the old value of the lookupfield untill I update another field.
For example:
web.lists.getByTitle(MyList).items.getById(1).select('Id','Created','Modified','TestLookup/Name').expand("TestLookup").get().then((result) .....
TestLookup refers to data from a column within another list (Testlist), in this case if I update the Name field from Testlist, this function still retrieving the old value until I update a field of the current list(MyList).

Any suggestions please?

**Comment by patrick-rodgers** [comment]
Hi @FullStackRafik,

I think the way it works is that the value is stored in the receiving lookup list and only updated on save (or possibly by a timer later). If you are trying to update the field and immediately get the new value that might be why you are seeing this issue. I don't know of anything we can do on our side for this. You might have to query both lists (unfortunate) or see if waiting a few seconds helps. If others have experience with this issue please chime in with possible fixes.

**Comment by FullStackRafik** [comment]
Hi @patrick-rodgers ,
Thanks for your response, please note that waiting for seconds or minutes doesn't resolve the issue, all I have to do is to update another field from the List(MyList).
I can update any field  and get the new value, but not the lookup field and here is the problem.

**Comment by sympmarc** [comment]
This doesn't sound right based on my experience. The expansion means the call fetches the value from the corresponding lookup list, sort of like a join. (This is why there are limits on the number of looukp columns in a list - sadly.) Are you sure the change you are making in Testlist is saved and if versioning is on that it's published as a major version?

**Comment by FullStackRafik** [comment]
Hi @sympmarc,
Thanks for your response.
Yes, I'm sure that the  change I'm making in Testlist  is saved and there is no versioning on this list.
Actually when I test that from workbench (https://localhost:4321/temp/workbench.html), I get always the updated value on time, but when I test that from a SharePoint page I still getting the old value of the Lookupfield untill updating another field from MyList.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. If you are still having issues here please open a new issue and reference this one. Thanks!
