### ISSUE TITLE
wrong api url

### ISSUE THREAD

**Issue by peterremote1980** [pnp/pnpjs#617]
hi, these code:

```

		sp.web.lists.getByTitle(this.list).items.orderBy("Sequence", true).get().then((items: any[]) => {
			for (let item of items) {
				this.menus.push(
					<div className={styles.column}>
						<div className={styles.departmentBox} style={{ backgroundColor: item.fhmv }}><a href={item.URL} className={styles.link} data-toggle="tooltip" data-placement="top" title={item.Tooltip}>{item.Title}</a></div>
					</div>
				);
			}
			this.forceUpdate();
		});
```

will access **https://xxx.sharepoint.com/SitePages/_api/web/lists/getByTitle('colorful_theme_menu')/items?$orderby=Sequence%20asc** from **https://xxx.sharepoint.com/SitePages/Home.aspx**

why?

even i did, same result:

```
		sp.setup({
			spfxContext: this.context
		});
```
thanks
Peter

**Comment by koltyakov** [comment]
Hi @peterremote1980,

Are you sure that you've placed `sp.setup` in a [correct location](https://pnp.github.io/pnpjs/documentation/getting-started/#using-pnpsp-setup) within SPFx webpart/extension but not somewhere where SPFx's context is not populated yet? 

Alternatively, strict web object declaration can be used (`const web = new Web('[WEB_ABS_URL]')`).

**Comment by koltyakov** [comment]
Closing the issue. With the same comment as [here](https://github.com/pnp/pnpjs/issues/620).

**Comment by Cannedfood** [comment]
FYI: This generally seems to happen, when sp.setup didn't run; The solution seems to be:
1. Make sure the `sp.setup` is run in the correct location, like koltyakov said
2. Make sure you only use `sp.web` AFTER it has been initialized
