### ISSUE TITLE
SPFetchClient still gives ECONNREFUSED when used behind corporate proxy

### ISSUE THREAD

**Issue by sbrown-fc** [pnp/pnpjs#619]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.2]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question

Able to connect to SharePoint Online via SPFetchClient using a client ID and secret.

### Observed Behavior

Get the error `FetchError: request to ... failed, reason: connect ECONNREFUSED`

### Steps to Reproduce

Use the [code from the docs](https://pnp.github.io/pnpjs/nodejs/docs/proxy/) with an online site you have access to.

### Possible Solution?

Not sure but could it be that

https://github.com/pnp/pnpjs/blob/b37a71060993ccbb3586d727db915d92d4ebd6b2/packages/nodejs/src/sptokenutils.ts#L3

is importing the default node-fetch rather than the one with the proxy options added, which is found here:

https://github.com/pnp/pnpjs/blob/dev/packages/nodejs/src/net/fetch.ts

Is that causing the request in sptokenutils.ts to not use the proxy?

**Comment by patrick-rodgers** [comment]
Best approach here might be for you to provide a PR that fixes this. We don't have a way to test and this is an issue that so far has only reported by you.

**Comment by patrick-rodgers** [comment]
Updated the code to ensure that the same shared fetch method is used by sptokenutils. As I don't have a ready way to test this I can't confirm this will fix the reported issue. Will be part of the release on July 12.

**Comment by sbrown-fc** [comment]
Thanks @patrick-rodgers; I can confirm the fix has resolved our issue.
