### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by peterremote1980** [pnp/pnpjs#620]
Hi
  I got Access denied from this code running as a standalone electon app (outside sharepoint). But if i open a browser to browse to /_api/web/webinfos which is ok. Why?

```
new PnpNode(pnpNodeSettings).init().then((settings) => {
	sp.web.webs.get()
		.then((lists) => {
			const a = [];
			for (let i of lists) {
				// a += i.Title + '\t' + i.Url + "<br>";
				console.log(i.Title);
				const b: any = {};
				b.Title = i.Title;
				b.Url = i.Url;
				a.push(b);
			}
			mainWindow.webContents.send("sendToHTML", a);
		});
}).catch();
```
thanks
Peter

**Comment by koltyakov** [comment]
Doesn't look like an issue related to PnPjs but a question on PnpNode (sp-pnp-node library).
**It's better to raise a question in the corresponding repository**. Auth strategy, SharePoint version, network, and PnpNode initiation settings are important. It's also better using [factory](https://github.com/koltyakov/sp-pnp-node#factory-example) approach and strict base url declaration. First to check is will your settings/creds work in a console Node.js application. Then [troubleshoot](https://github.com/koltyakov/node-sp-auth-troubleshoot) authentication.

**Comment by patrick-rodgers** [comment]
Please also have a [look at the code sample](https://github.com/pnp/pnpjs/issues/492#issuecomment-460738746) I provided you previously.

**Comment by peterremote1980** [comment]
Hi Patrick, my code is successfully run by using sharepoint administrator account. If i use normal user account, it has exception.

**Comment by peterremote1980** [comment]
what permission i need to grant to the user for running this code?

sp.web.webs.get().then((lists) => {

**Comment by wobba** [comment]
@peterremote1980 I suggest you start to read up on SharePoint permissions at https://docs.microsoft.com/en-us/sharepoint/what-is-permissions-inheritance. A user in the default visitors group (read) or members group (edit) will be able to list out all lists in a web.

It's easier if you tell us what permissions you have granted the user (if any).

**Comment by peterremote1980** [comment]
Yes, if i login to that account, and manually browse to  /_api/web/webinfos, it works.
But using that account to execute sp.web.webs.get() will fail. I am really no idea and waiting to die now. I stucked into this problem for weeks. Please help.

**Comment by koltyakov** [comment]
You always mentioning `_api/web/webinfos` endpoint but querying `_api/web/webs`. If `webinfos` suites due to user/permissions/data why not switching to the corresponding method?

PnPjs method | REST API endpoint
--- | ---
sp.web.webs | _api/web/webs
sp.web.webinfos | _api/web/webinfos

**Comment by koltyakov** [comment]
Closing this one. And it's really not good when a person who asks for help never come back reporting that the solution worked for him. Kind of abusement, IMO.

**Comment by peterremote1980** [comment]
i am so sorry about late and thanks for your answer.
