### ISSUE TITLE
[2.0.0] sub module: SP-appcatalog

### ISSUE THREAD

**Issue by PopWarner** [pnp/pnpjs#625]
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

**Comment by KEMiCZA** [comment]
Hi, I would like to complete this one.

**Comment by PopWarner** [comment]
Thank you @KEMiCZA! You are awesome! The status has been updated to "in progress" and is all ready for you.

The Readme for dev-v2 has also been updated to include a link to the recording of the contributors call, which can help provide additional guidance. Worth watching if you were unable to attend or have not yet seen it:
https://github.com/pnp/pnpjs/blob/dev-v2/README.md

Thank you again!

**Comment by KEMiCZA** [comment]
@patrick-rodgers test on v2 branch failed for web: https://github.com/pnp/pnpjs/blob/dev-v2/test/sp/web.ts

**Comment by KEMiCZA** [comment]
Hey I need some assistance for writing the test-cases. I want to upload a valid app to the appcatalog using the __add__ method. This works fine in the browser, but when running/debugging the tests it does not work (which is running in nodejs). 

I've mapped my file to an array and then I do the following in my test file:

```typescript
const appCatWeb = await sp.getTenantAppCatalogWeb();
const appCatalog = appCatWeb.getAppCatalog();
const rawArrayData = [80, 75, 3, etc...];
const data = new Uint8Array(rawArrayData).buffer;
await appCatalog.add("name00001", data);
```
Result in the appcatalog is that the file is uploaded but corrupted. When I download the file and inspect the contents I see __[object Object]__. 

When running the following code inside the browser it works fine:
```typescript
import { sp } from "@pnp/sp";

(async () => {
    const appCatWeb = await sp.getTenantAppCatalogWeb();
    const appCatalog = appCatWeb.getAppCatalog();
    const rawArrayData = [80, 75, 3, etc...];
    const data = new Uint8Array(rawArrayData).buffer;
    appCatalog.add("TEST0000000001", data);
})();
```

**Comment by patrick-rodgers** [comment]
Guessing this has something to do with a difference in how things are handled in node vs browser. I will try and find some time to research it for you.

**Comment by KEMiCZA** [comment]
@patrick-rodgers I had some time today to take a deeper look at this. When I said it works in the browser, I meant it works with v1 of PnPjs using the Chrome extension SP Editor.

The problem occurs when trying to parse the data to JSON: https://github.com/pnp/pnpjs/blob/c456f06c36b5f305f4c60d3e4f3dba1abd20bc46/packages/odata/src/queryable.ts#L15-L35

The content of the source object looks like this, specifically the body object is of type ArrayBuffer:
![image](https://user-images.githubusercontent.com/3862716/62189217-b5d63680-b36e-11e9-8b51-543623fb3eed.png)

After this line of code, object s (which is a string) contains an empty body object:
![image](https://user-images.githubusercontent.com/3862716/62189291-e4541180-b36e-11e9-94f2-375a2986fcc7.png)

I haven't tested the compiled version for v2 in the browser yet, but I assume this would result in the same issue as in node.

I've also noticed the queryable.ts code is a lot different than from v1.

**Comment by KEMiCZA** [comment]
This seems to work for now:

https://github.com/KEMiCZA/pnpjs/blob/6a79709e8ce43b5a5a39231757843eede2fe4d38/packages/odata/src/queryable.ts#L15-L61

```typescript
export function cloneQueryableData(source: Partial<IQueryableData>): Partial<IQueryableData> {


    const s = JSON.stringify(source, (key: string, value: any) => {


        switch (key) {
            case "query":
                return JSON.stringify([...(<Map<string, string>>value)]);
            case "batch":
                return "-";
            case "batchDependency":
                return "-";
            case "cachingOptions":
                return "-";
            case "clientFactory":
                return "-";
            case "parser":
                return "-";
            default:
                return value;
        }
    }, 0);


    const parsed = JSON.parse(s, (key: any, value: any) => {
        switch (key) {
            case "query":
                return new Map(JSON.parse(value));
            case "batch":
                return source.batch;
            case "batchDependency":
                return source.batchDependency;
            case "cachingOptions":
                return source.cachingOptions;
            case "clientFactory":
                return source.clientFactory;
            case "parser":
                return source.parser;
            default:
                return value;
        }
    });
    
    if(source.options && source.options.body){
        parsed.options.body = source.options.body;
    }


    return parsed;
}
```

Not sure if this a valid solution, you know way more about this @patrick-rodgers 
But I can now hopefully complete my tests.
