### ISSUE TITLE
[2.0.0] sub module: SP-content-types

### ISSUE THREAD

**Issue by PopWarner** [pnp/pnpjs#630]
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

**Comment by joakimhogberg** [comment]
Hey @PopWarner, I want to work on this one. Please assign me :)

**Comment by PopWarner** [comment]
WooHoo...awesome @joakimhogberg! Thank you... I've changed the status from "help wanted" to "in progress and it's all ready for you.

I know you already know this stuff, but including in case you didn't have the link handy:

The Readme for dev-v2 has also been updated to include a link to the recording of the contributors call, which can help provide additional guidance. Worth watching if you were unable to attend or have not yet seen it:
https://github.com/pnp/pnpjs/blob/dev-v2/README.md

Thanks again!!

**Comment by joakimhogberg** [comment]
Thank you David!

**Comment by PopWarner** [comment]
Hi @joakimhogberg....how have you been? Hope all is going good for ya... :)

We wanted to check-in and see how you are going with the current item and if you needed any help or had any questions? 

We are aiming for a Release Candidate Beta by the end of September and wanted to follow up with the issues which are "In progress" to see how things are going. 

Thank you so much again for helping out and looking forward to hearing from you. :)

**Comment by joakimhogberg** [comment]
Hi @PopWarner , thanks for checking in! 

I'm good thank you, hope you are too mate!

Getting back to my routines after summer vacation took longer than anticipated, that's why I've been quite inactive here... 

I will keep working on this issue during the weekend and get back to you in a day or two. Cheers!

**Comment by joakimhogberg** [comment]
PR submitted @PopWarner, thanks for reminding me about this!

**Comment by PopWarner** [comment]
@joakimhogberg Awesome!!  Thank you!! 👍
