### ISSUE TITLE
[2.0.0] sub module: SP-lists

### ISSUE THREAD

**Issue by PopWarner** [pnp/pnpjs#638]
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

**Comment by joakimhogberg** [comment]
Hi, can I work on this?

**Comment by PopWarner** [comment]
Hi @joakimhogberg!  :) Absolutely and thank you for your willingness to contribute. 👍 Were you able to review the FAQ's? If everything looks good to you, I can remove the "status: help wanted" label and apply the "status: in progress" label.

**Comment by joakimhogberg** [comment]
@PopWarner , yes I've read up on the getting started / contributing documents. Is there anything specific to working on v2 that I might have missed?

 I set up my testing enviroment (v2) and added a few unit tests which seems to run fine. I think I feel comfortable enough to get going :)

**Comment by PopWarner** [comment]
Fantastic @joakimhogberg! I've updated the "status" label's and it's all yours to start working on my man. Thank you again!! 👍 :)

**Comment by simonagren** [comment]
@joakimhogberg and @PopWarner in the same thread. My two main men ;)
