### ISSUE TITLE
[2.0.0] sub module: SP-profiles

### ISSUE THREAD

**Issue by PopWarner** [pnp/pnpjs#641]
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

**Comment by dcashpeterson** [comment]
I can take this on.

**Comment by PopWarner** [comment]
@dcashpeterson you're on fire! Thank you...you rock! 👍

**Comment by patrick-rodgers** [comment]
Hello, wanted to check on the status on this item as it is on the list of required things to be done before v2 can release. Please let us know an update - and if you won't have time to work on it, no worries just focused on getting things finalized. Thanks!

**Comment by dcashpeterson** [comment]
@patrick-rodgers I'm sorry, I got busy. I will have this done hopefully by tomorrow. If you need to pull it back I can submit a PR. I'm working on the documentation now.

**Comment by dcashpeterson** [comment]
@patrick-rodgers I submitted a pull request with the updated documentation.

**Comment by patrick-rodgers** [comment]
Thanks, just got it merged!
