### ISSUE TITLE
[2.0.0] sub module: GRAPH-users

### ISSUE THREAD

**Issue by simonagren** [pnp/pnpjs#657]
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

**Comment by baywet** [comment]
hey @simonagren I can take this one :)

**Comment by juliemturner** [comment]
All you @baywet!

**Comment by baywet** [comment]
ramping up here, I think I'm not understanding something properly
I created `/test/graph/users.ts` with the following content
```TS
import { testSettings } from "../main";
import {graph } from "@pnp/graph";
import "@pnp/graph/src/users";
import "@pnp/graph/presets";
import { expect } from "chai";

describe("Users", function () {
    if (testSettings.enableWebTests) {
        it("gets current user", async function() {
            const me = await graph.me.get();
            return expect(me).not.null();
        });
    }
});
```
However it's complaining the get method doesn't exist on me. I'm probably missing something in terms of imports but not sure what at this point.
Thanks for the help!

**Comment by simonagren** [comment]
@baywet you don't need to use .get()
So: 
```TypeScript
const me = await graph.me();
```
Sorry for late reply :D

**Comment by PopWarner** [comment]
YoYo @baywet....how are things going with you man! Hope all is well... :)

We wanted to check-in and see how you are going with the current item and if you needed any help or had any questions? 

We are aiming for a Release Candidate Beta by the end of September and wanted to follow up with the issues which are "In progress" to see how things are going. 

Thank you so much again for helping out and looking forward to hearing from you. :)

**Comment by baywet** [comment]
Hey @PopWarner !
Thanks for checking-in. TBH I took some time off and slowed down during summer (they are short up here in Montréal so you might as well enjoy those as much as you can)
I don't want to be a blocker so feel free to re-assign if you have somebody else that wants it. But I don't see myself working on that before a few weeks.

**Comment by PopWarner** [comment]
@baywet you definitely have to take advantage of that!! :)

I'll open it back up and definitely ping back if you want to work on of the other ones in the future. Thanks for the quick response. 👍

**Comment by baywet** [comment]
@PopWarner just submitted a draft pull request. There are probably things that are missing/not done probably but hopefully with a few iterations we'll be able to align it :)

**Comment by PopWarner** [comment]
@baywet sweet!!! Thank you my man. I'm gonna go ahead and take off the "help wanted" and put back on the "in progress"! Thanks again for the help! :)

**Comment by baywet** [comment]
PR has been approved, Issue probably can be closed now
