### ISSUE TITLE
[2.0.0] sub module: SP-related-items

### ISSUE THREAD

**Issue by PopWarner** [pnp/pnpjs#659]
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

**Comment by amortsell** [comment]
@PopWarner I'm willing to take responsibility for this issue, and try to do the transfer to v2. 0.0 for the related items module. Is there anything else than what's mentioned in the checklist in the issue description to think of?

**Comment by PopWarner** [comment]
Thank you @amortsell!!! 👍 

The status has been updated to "in progress" and is ready for you.

What is listed in the checklist should cover everything needed. 

The Readme for dev-v2 has also been updated to include a link to the recording of the contributors call, which can help provide additional guidance. Worth watching if you were unable to attend or have not yet seen it:
https://github.com/pnp/pnpjs/blob/dev-v2/README.md

Thank you again!

**Comment by amortsell** [comment]
@PopWarner I'm quite new to writing the tests and would appreciate a little guidance on how to implement the test cases for this module. I have figured out the basic principles on how the test library works and looked at a few examples to get the hang of it. I still feel a little uncertain though, on how to implement my describe methods  to make POST requests to get a result to compare to the result of the tested method.

**Comment by PopWarner** [comment]
@amortsell thank you for reaching out. I'm traveling for work quite a bit the next few weeks with limited availability, unfortunately. :(

You mentioned that you looked at some of the other samples? Also, maybe take a look at the most recent completed PR's and see if they provide any additional help.
**Completed PRs**: https://github.com/pnp/pnpjs/pulls?q=is%3Apr+is%3Aclosed

I will also reach out to some of the other team members and see if they have any availability. Alternatively, another idea might be to check in your most recent tests to your repo and point the group to it take a look specifically where you are looking for guidance....not required but just thinking of ideas.

Thanks again so much on helping out! 👍

**Comment by amortsell** [comment]
Thanks @PopWarner!

I checked among the recently merged PR's and found a few tests which I can
use as samples for tests I'm writing. I will try to complete this module by
the end of this week.

Regards

Anders

**Comment by PopWarner** [comment]
@amortsell Excellent!!!!!

Thanks for the update. Don't hesitate to reach out if you have any other questions and we will do our best to get back to you or get you an answer.

Thanks again for the efforts! 👍

**Comment by PopWarner** [comment]
Hi @amortsell, I hope all is going well with you. :)

I wanted to check-in and see how things are going on this module. Feel free to reach out if you have any questions! 

Thanks again for your willingness to help! 👍

**Comment by amortsell** [comment]
Hi @popwarner,

Thanks for reaching out. All is well with me, but there has been a little
bit of a tough situation within the family for a few weeks so I haven't
been able to find any time to complete the issue yet. Things are looking
better again since earlier this week and I plan to pick up where I left off
rather soon, hopefully some night this or next week.

Regards

Anders

**Comment by patrick-rodgers** [comment]
I went ahead and completed the tasks for this one, no worries. Once you've got some time there will always be plenty to help out with :). Thanks for your interest and look forward to working with you.

**Comment by amortsell** [comment]
Thanks a lot, Roger. I'm sorry not being able to complete the tasks. When
things calm down at work I will try to find something else to contribute
to.

Regards

Anders

**Comment by amortsell** [comment]
Hi Patrick,

I forgot to appreciate your support on this one. I checked your
contributions and learned a lot on how to think when it comes to testing
software,and also realized I would never have been able to complete these
tests without assistance from someone more experienced on tdd.

Once again thank you for resolving this.

Regards

Anders Mörtsell
