### ISSUE TITLE
Ability to order by multiple values when fetching list items

### ISSUE THREAD

**Issue by raymondlittle100** [pnp/pnpjs#66]
### Category
- [ x] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.0.4      ]

### Expected / Desired Behavior / Question
It would be nice to be able to add multiple ordering clauses for example order by field A then field B.

### Observed Behavior
Currently only seems to accept a single field with an ascending flag

**Comment by patrick-rodgers** [comment]
You can do this by chaining the orderby calls:

```TypeScript
const url = sp.web.lists.orderBy("Title").orderBy("Created", true).toUrlAndQuery();
```

**Comment by raymondlittle100** [comment]
OK will do but might be nice to have an overload which accepts a string array containing a list of fields

**Comment by patrick-rodgers** [comment]
That's not a change we will make as it doesn't really work as well as the fluent approach above. Each item in the array would need to be a string and ordering indicator and it covers a use-case that isn't frequent. You can easily as well write a helper function should you wish to apply an arbitrary array of orderby clauses. Thanks as always for the feedback!

Going to close this issue as answered, should you need to continue the conversation please _reopen_ the issue. Thanks!

**Comment by suryamishra2111** [comment]
Hi Patrick, 
What if we need to order dynamically? For example, if I have a grid with many columns and I want the user to select sorting orders in multiple columns? How do we create orderBy chains dynamically based on input or first time page load?
