### ISSUE TITLE
[2.0.0] sub module: SP-search

### ISSUE THREAD

**Issue by PopWarner** [pnp/pnpjs#660]
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

**Comment by siata13** [comment]
Hi, I would like to help with this one.
@juliemturner @simonagren @PopWarner

**Comment by PopWarner** [comment]
Thank you @siata13! :) I've added the "status: in progress" lablel. Please feel free to fork and begin working on the SP-search sub module in your dev-v2 branch. Please feel free to reach out with any questions. 👍

**Comment by simonagren** [comment]
Nice @siata13 Piotr :D 
As David said, reach out if you have any questions!

**Comment by PopWarner** [comment]
YoYo @siata13...hoping things are going well for you my man! :)

We wanted to check-in and see how you are going with the current item and if you needed any help or had any questions? 

We are aiming for a Release Candidate Beta by the end of September and wanted to follow up with the issues which are "In progress" to see how things are going. 

Thank you so much again for helping out and looking forward to hearing from you. :)

**Comment by PopWarner** [comment]
Spoke with @siata13 and he has had some things come up, so we are going to move this back into the pool of available 2.0 modules that can be grabbed by the community. :)
