### ISSUE TITLE
[2.0.0] sub module: SP-site-groups

### ISSUE THREAD

**Issue by PopWarner** [pnp/pnpjs#664]
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

**Comment by RamPrasadMeenavalli** [comment]
I would like to work on and complete the tasks for this sub module. @juliemturner @simonagren @PopWarner.

**Comment by PopWarner** [comment]
Thank you @RamPrasadMeenavalli! The status has been updated to "in progress" and is ready for you.

The Readme for dev-v2 has also been updated to include a link to the recording of the contributors call, which can help provide additional guidance. Worth watching if you were unable to attend or have not yet seen it:
https://github.com/pnp/pnpjs/blob/dev-v2/README.md

Thank you again!

**Comment by RamPrasadMeenavalli** [comment]
Hey Guys,  @juliemturner @simonagren @PopWarner
I am done making the changes for this module. Submitted a PR

The build was successful locally when I did 'npm run build'. But the Build check on the PR failed (https://travis-ci.com/pnp/pnpjs/builds/120974500)

It shows errors from the security module. I made sure I haven't made any changes or pushed anything for the security module.

Could you let me know if I am missing something. Thank you.
