### ISSUE TITLE
[2.0.0] sub module: SP-site-users

### ISSUE THREAD

**Issue by PopWarner** [pnp/pnpjs#666]
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

**Comment by ValerasNarbutas** [comment]
I would like to work on and complete the tasks for this sub module. @juliemturner @simonagren @PopWarner.

**Comment by PopWarner** [comment]
Thank you @ValerasNarbutas!! You rock. The status has been updated to "in progress" and the sub module is all yours to begin work on. :)

**Comment by ValerasNarbutas** [comment]
Thanks @PopWarner , not sure if something wrong with mine env but fresh fork from dev-v2 gives me errors in sp/site-users/types.ts 
![image](https://user-images.githubusercontent.com/16476453/60022517-a80d0180-969c-11e9-837a-847e936d5409.png)

Tried to look for the answer but could not yet resolve, Is this something you are familiar maybe?

**Comment by ValerasNarbutas** [comment]
Nevermind, i have resolved issue. :)

**Comment by PopWarner** [comment]
Hi @ValerasNarbutas...hope things are going well for you. :)

We wanted to check-in and see how you are going with the current item and if you needed any help or had any questions? 

We are aiming for a Release Candidate Beta by the end of September and wanted to follow up with the issues which are "In progress" to see how things are going. 

Thank you so much again for helping out and looking forward to hearing from you. :)

**Comment by PopWarner** [comment]
Hi @ValerasNarbutas. We wanted to check in with you again to see how things are going? We are moving along nicely in the march towards a v2 beta for PnPjs and wanted to see if you were still working on this issue?

If you are unable to continue, it's no problem at all. We totally understand that sometimes things get in the way. :) Let us know and if needed we can go ahead and move it back into the "help wanted" status.

**Comment by ValerasNarbutas** [comment]
Good day @PopWarner , i have totally missed your messages, i did started on this at the time i have asked, got distracted. Thanks for changing status. I had to do it myself, but forgot completely :(

**Comment by PopWarner** [comment]
Hi @ValerasNarbutas! :) No problem. It looks like you are working on this one again, is that correct?

If so, I can go ahead and remove the "help wanted" label and re-apply the "in progress" label.

Thanks and looking forward to your reply. 👍

**Comment by ValerasNarbutas** [comment]
Hi @PopWarner ,
yes sure, i was just trying to upload old code i had from summer :) 
I will try to complete task this time.

**Comment by ValerasNarbutas** [comment]
Hi @patrick-rodgers 
i have submitted pull request for this again (i cannot point to the issue #666 looks like), just adding documentation with some examples and minor fix in test/mian.ts file.
