### ISSUE TITLE
[2.0.0] sub module: SP-sites

### ISSUE THREAD

**Issue by PopWarner** [pnp/pnpjs#667]
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

**Comment by Ramakrishnan24689** [comment]
Hi @PopWarner,

I almost finished up writing the test and got stuck while writing test for the method createmodernteam.  under SP-sites submodules

The **issue** here is app-only token does not have sufficient permission to create a modern team site.  So the test with SPFetchClient fails. (Does not create site.)

Request you to share your suggestion in this regard. 

The link below where it is stated
https://pnp.github.io/pnpjs/sp/docs/sites/#create-a-modern-team-site

**Comment by Ramakrishnan24689** [comment]
Hi All(@PopWarner, @simonagren , @juliemturner ),

Kindly ignore my previous comment. 
I have reached the last step and wanted to confirm (as it was not much clear from our community call [video](https://www.youtube.com/watch?v=fTUFVAegmvQ))

As I am working on **Site sub module** and when comparing it with 1.x branch, I can see methods deleteSites, joinhubsite, registerhubsite, unregisterhubsite etc which are not there in dev-v2. So in this step, it is expected to move these to the dev-v2 branch right? Just wanted to confirm before performing it !!

**Comment by Ramakrishnan24689** [comment]
Hi All(@PopWarner, @simonagren , @juliemturner ),

All the tasks were completed. 

Please find PR link below and let me know in case of any change.

https://github.com/pnp/pnpjs/pull/848
