### ISSUE TITLE
[2.0.0] sub module: SP-user-custom-actions

### ISSUE THREAD

**Issue by PopWarner** [pnp/pnpjs#671]
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

**Comment by JonasBjerke89** [comment]
Please sign me up for this one, if help is still needed :)

**Comment by JonasBjerke89** [comment]
I have been working on this, but writing test-cases for "UserCustomActions.add" and "UserCustomAction.update" is problematic because of the "NoScript" flag enabled on modern sites.

Is there a way for us to make testcases with an **classic site underneath** or should we skip writing test-cases for those two methods? Or do you see another option?

**Comment by JonasBjerke89** [comment]
@patrick-rodgers Any thoughts on this?

**Comment by patrick-rodgers** [comment]
There are a few places where writing tests doesn't really work for whatever reason. What I have been doing is writing the test, making sure it works (by creating a classic site for example), then commenting it out with a note on why it is commented out. That means we have a test we can run if needed. For much of the API the code doesn't really ever change (this is a place like that) so I am not too worried.
