### ISSUE TITLE
sp.search postquery 404 on modern page that is not home.aspx

### ISSUE THREAD

**Issue by c-eiser13** [pnp/pnpjs#679]
### Category
- [ ] Enhancement
- [ X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
1.3.2

Please specify what version of the library you are using: [     1.3.2    ]

Please specify what version(s) of SharePoint you are targeting: [     SPO    ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Call sp.search from a modern page that is not the homepage of a web and get results.

### Observed Behavior
I was working on a new web part that will utilize search and created a modern page in SitePages to test the web part while developing. I created a very basic sp.search call to return all results from the people result source and was receiving a 404 and my catch block was being hit. I checked a similar web part that uses search and sits on a web homepage and it was working correctly. 
The broken web part sits on a page: https://tenant.sharepoint.com/sites/test/sitepages/web-part-testing.aspx. Next, I looked in the network tab and noticed the failed request to postquery which is using a URL relative to SitePages: https://tenant.sharepoint.com/sites/test/SitePages/_api/search/postquery.

Trying to open this url in the browser returns a 404 as well. When I move this web part to the homepage of a site, it appears to determine the relative URL properly (assuming since modern does not add the /SitePages/home.aspx to the URL). This request is successful: https://tenant.sharepoint.com/sites/site/_api/search/postquery

I took a look at the source code and tried debugging and looks like the issue may be in the toabsoluteurl.ts file, but I could not confirm. Below are the screen shots I took of the errors.

![postquery1](https://user-images.githubusercontent.com/42096464/57423698-9ea60380-71da-11e9-9c64-55cbefc27352.PNG)

![postquery4](https://user-images.githubusercontent.com/42096464/57423702-a1a0f400-71da-11e9-974f-955750e3df2b.PNG)

### Steps to Reproduce
Create a basic web part (i'm using spfx 1.8.2) and add to a modern page that is not home.aspx. Add a basic search call, I was able to repro with:
sp.search("test").then((r: SearchResults) => {

    console.log(r.ElapsedTime);
    console.log(r.RowCount);
    console.log(r.PrimarySearchResults);
}).catch(e)

**Comment by koltyakov** [comment]
Did you [configure spfxContext](https://pnp.github.io/pnpjs/documentation/getting-started/#using-pnpsp-setup) correctly?

**Comment by c-eiser13** [comment]
@koltyakov my apologies, I was switching between two projects yesterday when testing this out and completely missed the fact that I did not have an oninit in the web part that was not working. Thanks gfor the quick reply, closing this issue.
