### ISSUE TITLE
hubsites.ts - HubSites error on SitePages

### ISSUE THREAD

**Issue by ArndBrugman** [pnp/pnpjs#680]
### Category
- [ ] Enhancement
- [ X ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [ 1.3.2        ]
Please specify what version(s) of SharePoint you are targeting: [ SP Online         ]

### Desired Behavior
sp.HubSites should return hubsites also on SitePages.

### Observed Behavior
sp.HubSites does not return hubsites on SitePages.

### Steps to Reproduce
create component getting hubsites and put on a site page

## Proposed fix: 
change @defaultPath("_api/hubsites")
to @defaultPath("/_api/hubsites")

**Comment by patrick-rodgers** [comment]
Are you setting up the context as shown in the [getting started docs](https://pnp.github.io/pnpjs/documentation/getting-started/#establish-context)? With the way the internals work that slash shouldn't matter.

**Comment by ArndBrugman** [comment]
Ah. that did the trick, i've never used the sp.setup and everything worked as expected but not this hubSIte get. Thx! This works like a charm :)
