### ISSUE TITLE
getItemsByCAMLQuery not returning people field Expand value

### ISSUE THREAD

**Issue by ahamedfazil** [pnp/pnpjs#682]
Hi,
I am trying to expand People picker field by using getItemsByCAMLQuery. Unfortunately I am not getting expanded value. Below is the code I use to expand person field - k_submitter

![image](https://user-images.githubusercontent.com/21005625/57518084-8f2cd480-7318-11e9-8d02-78b6cf03ed4f.png)

`const q: CamlQuery = {
  ViewXml: xml
};

pnp.sp.web.lists
  .getByTitle("MyList")
  .getItemsByCAMLQuery(q, "k_submitter/Title")
  .then((items: any[]) => {
    console.log("items", items);
});`

![image](https://user-images.githubusercontent.com/21005625/57517350-ec278b00-7316-11e9-84e3-5b8396fcdf1e.png)

my pnp version -> @pnp/pnpjs": "^1.3.0"
Any help on this is highly appreciated. Thank you in advance.

**Comment by koltyakov** [comment]
Not sure that such a mixture of CAML+OData would ever work this way. 
You can use pure OData `.select('Person/Title').expand('Person')` or expanding `FieldValuesAsText` in `getItemsByCAMLQuery` or trying `renderListDataAsStream` which also deals with CAML but offers more options.

1\. `getItemsByCAMLQuery` and expanding `FieldValuesAsText`:

![image](https://user-images.githubusercontent.com/7816483/57520080-7971dc00-7325-11e9-823d-cf5b3cc3c571.png)

2\. `renderListDataAsStream`:

![image](https://user-images.githubusercontent.com/7816483/57520229-cfdf1a80-7325-11e9-8b14-b5193b838d2b.png)

**Comment by ahamedfazil** [comment]
Thank you @koltyakov , yes it is helpful and now I can get the Text value of people picker field. But the internal name of the field is different, any idea why?.

![image](https://user-images.githubusercontent.com/21005625/57520600-5a238080-731e-11e9-9561-850fb2903688.png)

And I was referring to this https://github.com/SharePoint/PnP-JS-Core/issues/777#issuecomment-380446030 so that I used CAML query with field/Title expand option. Unfortunately I didn't get expected output.

**Comment by koltyakov** [comment]
SharePoint & REST API as well replaces special characters. What you're dealing is even not internal names but OData entity properties names. In most of the cases, EntityPropertyName is equal to  Internal name but not always (`k_submitter` would have the same Internal and Entity names). In expanded `FieldValues*` some additional replacements are taking place as `_` replacement with its Unicode representation `_x005f_`. Interesting, I even didn't pay attention to this as almost never use `getItemsByCAMLQuery`. Anyways it's on the API's side, not the library's.

**Comment by ahamedfazil** [comment]
Thank you again @koltyakov its really informative. Going to close this ticket since you resolved the issue.
