### ISSUE TITLE
Creating a new item with a person field

### ISSUE THREAD

**Issue by Katli95** [pnp/pnpjs#683]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are [`"@pnp/sp": "^1.2.9"`]

Please specify what version(s) of SharePoint you are targeting: [Online]

### ~~Expected / Desired Behavior~~ / **Question**
As always, starting on a positive note, really love the `pnpjs` library, it's really intuitive!

I'm creating a item in a list which has a person field. I had expected to be able to create a new item and reference the user by EMail or something similar, but am instead confronted by the ID field. I discovered that there is actually a hidden lookup list "behind" the person field. My issue now is that I don't know how to add a user to a field which isn't already in said "hidden lookup list". 

I'm using `sp-dev-fx-controls-react` `<PeoplePicker/>` to select the person so I have access to:
- 'i:0#.f|membership|username@tenant.com' (never really sure what this string is called, it's not the UPN, not the EMail and not the Title, so what is it called exactly? I've seen different names in different sources)
- And also the Title (User Full Name) and the corresponding EMail.

What is the best way to add a new item and reference the user with this being the data I have access to?

I saw [this](https://www.linkedin.com/pulse/list-items-system-update-options-sharepoint-online-andrew-koltyakov/) awesome article but it mentions that 

> you have to have Full Control over the items to do the same [validateUpdateListItem] in REST. 

Is this the case, because my user's don't have full control permissions to the item so in that case this wouldn't work. What is the recommended way for me to fulfill this requirement?

**Comment by sympmarc** [comment]
The PeoplePicker control has an option ensureUser. If you pass true for that, it will ensure your user is in the User Information List. If it’s not there, it will add it.

Your question is more about the PeoplePicker, so it might have made more sense to ask it in the other repo.

**Comment by Katli95** [comment]
@sympmarc Oh, great! Thank you so much, I had no Idea the people picker could handle this for me! I thought I would have to do some manual stuff through the REST API. And thanks for replying on a weekend, yet another reason to love this community!
