### ISSUE TITLE
Profile picture

### ISSUE THREAD

**Issue by FullStackRafik** [pnp/pnpjs#686]
Is there any way to get the url of the profile picture for a specific user?

**Comment by koltyakov** [comment]
In SharePoint, there are tons of different ways of getting a profile pic. ;)
I'd suggest taking a looks at any profile pic on a tenant in standard UI and use the same logic in the app.

E.g.:
- https://outlook.office365.com/owa/service.svc/s/GetPersonaPhoto?email=username@contoso.onmicrosoft.com&UA=0&size=HR96x96
- https://eur.delve.office.com/mt/v3/people/profileimage?userId=username@contoso.onmicrosoft.com&size=L
- ...

**Comment by FullStackRafik** [comment]
Sorry, I didn't specify that I'm using Sharepoint 2016 On-premises,I know that this service is available using Sharepoint online, but is it available using SP2016 On-premises?
Thanks.

**Comment by koltyakov** [comment]
In SP 2016 `userphoto.aspx` can be used: `/_layouts/15/userphoto.aspx?AccountName=username@contoso.com&Size=L`.

**Comment by FullStackRafik** [comment]
Thanks.
