### ISSUE TITLE
PNPJS Typescript version compatibility on SPFx for SharePoint 2016 is having issues

### ISSUE THREAD

**Issue by bricenocar** [pnp/pnpjs#687]
### Category
- [ ] Enhancement
- [ x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.3.2   ]

Please specify what version(s) of SharePoint you are targeting: [ 2016 ]

I am working with a SPFx webpart running on SP2016. I am using pnp to get/set data from SharePoint.

I installed pnp packages by running:
npm install @pnp/logging @pnp/common @pnp/odata @pnp/sp --save

I got the issue with typescript v2.2.2, so I followed this [article ](https://pnp.github.io/pnpjs/documentation/SPFx-On-Premesis-2016/) and everything worked fine.

On friday, I started to get the issue again. When I checked my package-lock.json I saw that dependencies on @microsoft/gulp-core-build-typescript have changed and now the quick solution explained in the article mentioned is not working anymore.

I created a new clean project to try to reproduce the issue, and same result.

Is there anything I am missing?

**Comment by bricenocar** [comment]
I managed to fix my issue (maybe not the best way) but it is a workaround anyway.

What happens is that running npm install after following this [article](https://pnp.github.io/pnpjs/documentation/SPFx-On-Premesis-2016/) the package-lock.json file gets re-generated and the "requires" section of the package **@microsoft/gulp-core-build-typescript** gets re-written to "typescript":"~2.2.2". In addition, the dependency definition for typescript gets generated not under the package **@microsoft/gulp-core-build-typescript** but as a root dependency in the file. So I did the updates just as the article explains, but instead of running npm install I ran npm ci, this way the package-lock.json does not change (and actually behaves as locked file) and the typescript 2.4.2 is used.

I hope it helps :)

**Comment by koltyakov** [comment]
Thanks!

**Comment by jpalo** [comment]
Small update to @bricenocar comment above: direct link to working article is [this](https://pnp.github.io/pnpjs/v1/documentation/SPFx-On-Premesis-2016/).

**Comment by martin-braun** [comment]
This is a terrible work-around. It causes several warnings in my SPFX project. If your library targets SPFX environments, it should not break on the lower TypeScript versions that are shipped with yoeman. I agree that it would be better if Microsoft would rise the TypeScript version on their templates, but they don't and you ignored it, simply leaving the poor who target on-premise behind with a terrible work-around that involves hacking the package-lock.json.
