### ISSUE TITLE
Expand

### ISSUE THREAD

**Issue by FullStackRafik** [pnp/pnpjs#689]
Here is the scenario:
List1 contains lookupfield1 from List2, and List2 contains lookupfield2 from List3.

So can I get lookupfield2 properties using expand but from List1?

**Comment by koltyakov** [comment]
Sorry, but I'm closing this one.
First of all, this is a question not related to the library directly but SharePoint API in general. Such kind of question is better asking in tech community or StackOverflow, etc.
Also, please, please!, do not remove issues templates completely, they are for the reason and the instructions from the issue template are highly appreciated.
Regarding your question, no, in SharePoint API you can't expand complex datatypes for lookups including other lookups.
