### ISSUE TITLE
Get user's group (AD)

### ISSUE THREAD

**Issue by FullStackRafik** [pnp/pnpjs#691]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] **Question**
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  1.3.1       ]

Please specify what version(s) of SharePoint you are targeting: [  Sharepoint 2016 On-premises]

Can this method retrieve groups to which user belongs but those groups from Active Directory:
web.currentUser.groups.get().then((r) => {  
          return r
...
Example:
Group1 in Sharepoint contains Group 2 from AD that contains multiple users including the current one.

Thanks

**Comment by koltyakov** [comment]
Hi @FullStackRafik, 

Unfortunately, this is not possible using SharePoint client-side API. `user.groups` returns SharePoint groups only.

Can only be done with a custom web service and deligated requests to Active Directory.

**Comment by patrick-rodgers** [comment]
Closing this as answered. Thanks!
