### ISSUE TITLE
@pnp/graph user picture

### ISSUE THREAD

**Issue by mstivoi** [pnp/pnpjs#693]
### Category
- [ ] Enhancement
- [ ] Bug
- [ x ] Question
- [ ] Documentation gap/issue
### Version

Please specify what version of the library you are using: [  1.3.2   ]

Please specify what version(s) of SharePoint you are targeting: [ Online   ]
### Expected / Desired Behavior / Question
How do i get User photo property which i can see in IUser interface ?

graph.users.getById(this.props.email).get() do not return Photo/Photos property.
Select also not helped.

If not possible , please refer me to correct library , where i can retrieve this information. 
Thank You

**Comment by patrick-rodgers** [comment]
This went out as part of 1.3.4 released today, July 12. Closing this issue as complete.
