### ISSUE TITLE
Get another user info using PnPJS with SPFx

### ISSUE THREAD

**Issue by Danielaroc** [pnp/pnpjs#695]
I want to get a list of items from a SharePoint list, and display them in a specific way in SPFx webpart. I could use PnPJS to get Text and Number fields, but for the Author field, I am only getting the ID.

I'd like to get some other info, like email address, display name, and user image. My code now looks like this:

```
  sp.web.lists.getByTitle('Projects').items.get().then(items => {
           //console.log(items)
        })
```

However I am getting something like this:

![image](https://user-images.githubusercontent.com/50559115/57984244-ec670b00-7a27-11e9-8cf1-dd0f424a3cb4.png)

How can I use AuthorId to get more info about that user?

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

**Comment by sympmarc** [comment]
You need to `expand` the `Author` field because it is a complex field which is a lookup into the `User Information List`. You should also use a `select` to only request the columns you need to reduce the payload.

``` JavaScript
      sp.web
        .lists
        .getByTitle('Projects')
        .select("Id", "Title", "Author/ID", "Author/Title", "Author/Email")
        .expand("Author")
        .items.get().then(items => {
          //console.log(items)
        });
```

You should also consider using `async`/`await` to make your code simpler, rather than using `then`.

**Comment by Danielaroc** [comment]
@sympmarc Great tips. Thanks for the detailed answer!

**Comment by Danielaroc** [comment]
@sympmarc  .. One more side question. If we use PnPJS, is there any need to use @microsoft/sp-http SPHttpClient?

**Comment by koltyakov** [comment]
@Danielaroc,

While using PnPjs I can't see serious reasons using `@microsoft/sp-http`. PnPjs provided everything @microsoft/sp-http can offer and even much more. And when a custom endpoint needed PnPjs's SPHttpClient can do it.

**Comment by Danielaroc** [comment]
Thank you @koltyakov!

**Comment by kevin-lane** [comment]
@sympmarc It did not work for me. I get the same result like before. I can't access information about the user who created the list item.  I did exactly what you told.

**Comment by sympmarc** [comment]
@kevin-lane Hard to say what the issue is. Want to share your code?

**Comment by kevin-lane** [comment]
@sympmarc `    componentDidMount(){
        this._getList();
    }

    private async _getList() {
        const items: any[] = await sp.web.lists.getByTitle("Tulips").items.get();
        this.setState({ items: items });
        console.log(this.state.items);
        console.log(items);
        
        const testItem  = await sp.web.lists
                        .getByTitle("Tulips")
                        .select("Id", "Title", "Author/ID", "Author/Title", "Author/Email")
                        .expand("Author")
                        .items.get();
        console.log(testItem);   
    }`

**Comment by sympmarc** [comment]
@kevin-lane And what do you get back? Are you getting valid items from the list? If so, can you show what the JSON looks like?

**Comment by kevin-lane** [comment]
@sympmarc 
![image](https://user-images.githubusercontent.com/33052389/96499618-efce7980-124d-11eb-9c58-0ffe76759e4a.png)

**Comment by koltyakov** [comment]
In this code:

```typescript
const testItem  = await sp.web.lists
                    .getByTitle("Tulips")
                    .select("Id", "Title", "Author/ID", "Author/Title", "Author/Email") // <-- and this 
                    .expand("Author") // <-- and this 
                    .items.get(); // should be after items
```

like this:

```typescript
const testItem  = await sp.web.lists
                    .getByTitle("Tulips")
                    .items
                    .select("Id", "Title", "Author/ID", "Author/Title", "Author/Email")
                    .expand("Author")
                    .get();
```

**Comment by kevin-lane** [comment]
@koltyakov @sympmarc Thanks alot for the help. It work but when I have "Author/Email" in the select method it gives the following errors:

![image](https://user-images.githubusercontent.com/33052389/96502961-d976ec80-1252-11eb-8822-868db3ad3ace.png)

**Comment by juliemturner** [comment]
I'm pretty sure you have a case issue, it should be Author/EMail --- capital M.

**Comment by koltyakov** [comment]
Yep, the casing is important. Missed those with EMail. Linking https://github.com/pnp/pnpjs/issues/919#issuecomment-552437890 ticket as the one containing other expandable user props. Might be handy.

**Comment by sympmarc** [comment]
@juliemturner #FTW.

**Comment by kevin-lane** [comment]
Now it worked. Thanks a lot for the help @juliemturner, @koltyakov and @sympmarc 💯 👍
