### ISSUE TITLE
Import data

### ISSUE THREAD

**Issue by FullStackRafik** [pnp/pnpjs#696]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.1]

Please specify what version(s) of SharePoint you are targeting: [ 2016 on Premises        ]
Hello,
Is there any library from PnP which can helps to read data from a csv file and import it to a specific SharePoint List?
Thanks.

**Comment by patrick-rodgers** [comment]
If you search around you can find solutions to this issue in either this issues list or other places. Going to close this issue as this isn't a general help forum and your question is not library related. Perhaps try the [tech communities](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev). Thanks!
