### ISSUE TITLE
NodeJS package doesn't support the client certificate credential flow

### ISSUE THREAD

**Issue by kcasamento** [pnp/pnpjs#697]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.3.2     ]

Please specify what version(s) of SharePoint you are targeting: [    Online     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Desired Behavior / Question
I've currently run into the need to use PnPJS in a node application inside of an Azure Function.  As a result I need to support the client credentials flow using a certificate as client secret is no longer supported for app only access tokens.  Ultimately it would be ideal to bootstrap pnpjs to use adal-node's "acquireTokenWithClientCertificate" flow.

Luckily you have provided a means to pass in my own factory function to sp.setup and thus I've worked arount this and have built a fetch client for the above scenario.  Code is a bit integrated and spread out at the moment, but I am happy to clean up and submit a PR if needed.

**Comment by patrick-rodgers** [comment]
Yes, if you want to put together PR for this that would be great, thanks!

**Comment by patrick-rodgers** [comment]
Closing this after merging the PR. Thanks! Great work.
