### ISSUE TITLE
Config-store List - getConfiguration required?

### ISSUE THREAD

**Issue by gbminnock** [pnp/pnpjs#70]
- [x] Question

**Config-Store**

Is it required to call getConfiguration() on the provider in order to load the values from the SharePoint list. 

I've tried the syntax here but it doesn't seem to work: [config-store](https://github.com/pnp/pnpjs/blob/dev/packages/config-store/docs/providers.md )

tks.

**Comment by patrick-rodgers** [comment]
Hi @gbminnock - thanks for reporting this. Looks like we have two issues, one with the documentation and another bug in the code. Never good. We'll get things sorted in time for the next release. Thanks!

**Comment by gbminnock** [comment]
Hi @patrick-rodgers, thank you for the quick turn around on this. 
I wonder is it possible to get this before the 1.0.5 milestone release? Maybe I could download from your repository and build myself from patrick-rodgers/pnp ? 
Gary.

**Comment by patrick-rodgers** [comment]
We will publish a beta on Friday (April 20) which will contain this update. You can download the dev branch and build from there if you need, but there aren't currently docs fully explaining the build system. `gulp package` should package all the libraries into the ./dist folder. Unfortunately I can't offer you too much support beyond that currently. But on Friday you can grab the beta. HTH

**Comment by gbminnock** [comment]
Hi @patrick-rodgers 
That helps, I'll wait for the beta.
Thanks again.

**Comment by gbminnock** [comment]
Works great @patrick-rodgers, thanks for this. 
I've implemented a provider for property bags which I could contribute if you think it could be useful?
