### ISSUE TITLE
Error getting user profile properties in SP

### ISSUE THREAD

**Issue by ameyatoraskar** [pnp/pnpjs#702]
**Category**
[ ] Enhancement

[X] Bug

[ ] Question

**Version**
Please specify what version of the library you are using: [ 1.3.2 ]

**Expected / Desired Behavior / Question**
when calling the method to get properties of the current user, I expect it to return the properties of the current user

**Observed Behavior**
When making this call in javascript on a page in the SitePages library:
$pnp.sp.profiles.myProperties.get().then(...

I receive the following error in the console:
GET https://mydev.sharepoint.com/sites/_api/sp.userprofiles.peoplemanager/getmyproperties 404
Error: Error: Error making HttpClient request in queryable [404]  ::> 

My actual site URL is https://mydev.sharepoint.com/sites/iHello
but somehow its skipping /iHello and this code works fine on subsites and on other site pages like document libraries/lists/site pages.

**Steps to Reproduce**
below is code

 sp.profiles.myProperties.get().then(function(result) {  
      console.log("============ inside pnp.sp.profiles.myProperties.get() =============="); 
        var userProperties = result.UserProfileProperties;  
        var userPropertyValues = "";  
        userProperties.forEach(function(property) {  
            userPropertyValues += property.Key + " - " + property.Value + "<br/>";  
            console.log(property.Key + " - " + property.Value);  
        });  
        
    }).catch(function(error) {  
        console.log("Error: " + error);  
    }); 

Thanks!

**Comment by patrick-rodgers** [comment]
If you are using this inside SPFx have you used the [setup function](https://pnp.github.io/pnpjs/documentation/getting-started/#getting-started-with-sharepoint-framework)? If not, how are you using the library?

**Comment by ameyatoraskar** [comment]
Hi Patrick, set up function worked...thank you!

**Comment by ValerasNarbutas** [comment]
> If you are using this inside SPFx have you used the [setup function](https://pnp.github.io/pnpjs/documentation/getting-started/#getting-started-with-sharepoint-framework)? If not, how are you using the library?

@patrick-rodgers  hey, this link to setup function already invalid

**Comment by koltyakov** [comment]
We have search in docs, btw. Welcome :D 

![4CB4E037-EFF6-47EB-95C3-C1FC71341782](https://user-images.githubusercontent.com/7816483/72376623-4c30c580-371f-11ea-9fd4-09a2db51f1fd.jpeg)
