### ISSUE TITLE
Issue when creating a new item with user field

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/pnpjs#703]
Library :  "@pnp/sp": "^1.3.2",
error 
parsers.ts:13 Uncaught (in promise) Error: Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"A node of type 'PrimitiveValue' was read from the JSON reader when trying to read the entries of a feed. A 'StartObject' or 'EndArray' node was expected."}}}
    at new HttpRequestError (parsers.ts:13)

await sp.web.lists.getByTitle("TEST").items.add({
```
    Title: "Title",
    usern:11
      }).then((iar: ItemAddResult) => {
    console.log(iar);
```
    at parsers.ts:19

**Comment by koltyakov** [comment]
The payload is incorrect. Please check the [docs](https://pnp.github.io/pnpjs/sp/docs/items/#user-fields).

**Comment by harshdamaniahd** [comment]
sorry what does payload mean . I am using the below code
sp.web.lists.getByTitle("PeopleFields").items.add({
    Title: getGUID(),
    User1Id: 9, // allows a single user
    User2Id: { 
        results: [ 16, 45 ] // allows multiple users
    }
}).then(i => {
    console.log(i);
});

**Comment by koltyakov** [comment]
The payload is the object you pass to the operation. Based on this piece of code `usern:11` it's obvious that it's incorrect. A lookup/people picker entity name can't be `usern`. Lookup id entity names are always suffixed with `Id`. E.g. if the field internal name MyUser it's entity name in the payload must be `MyUserId`.

**Comment by harshdamaniahd** [comment]
ok let me check

**Comment by harshdamaniahd** [comment]
@koltyakov  oops now it get :-) thank you for helping.
