### ISSUE TITLE
Create a "news page" on SharePoint Online with @pnp/sp/clientsidepages ?

### ISSUE THREAD

**Issue by dkhmm** [pnp/pnpjs#704]
### Category
- [X] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.2]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
How can I create a "news page" on SharePoint Online with @pnp/sp/clientsidepages ?
either with the method: sp.web.addClientSidePage or sp.web.addClientSidePageByPath

### Observed Behavior

I can create site pages, but I want to create news pages.
It seems not possible to set the property: PromotedState to 2.
It would be nice if the methods to create site pages contained a way to specify if it is a site page or news page.

I appreciate your help with the above questions.

**Comment by patrick-rodgers** [comment]
There exists a [promoteToNews](https://github.com/pnp/pnpjs/blob/dev/packages/sp/src/clientsidepages.ts#L476) method on the page, have you tried that?

**Comment by dkhmm** [comment]
Hi Patrick. 
Thanks for your quick answer, I will have a look at it.
Is it still in dev branch, and not released yet?

**Comment by patrick-rodgers** [comment]
Just checked, it does appear that is not yet merged to master. Will aim to get a release out when I am back the first week of June. Thanks.

**Comment by patrick-rodgers** [comment]
Closing this, just published latest version which includes the promote news method.
