### ISSUE TITLE
CamlQuery expand error

### ISSUE THREAD

**Issue by FullStackRafik** [pnp/pnpjs#705]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     1.3.1    ]

Please specify what version(s) of SharePoint you are targeting: [       Sharepoint 2016 On-premises  ]

I get an error: 400 bad request when I use getItemsByCAMLQuery with expand when I remove the expand function it works.
Any suggestions please?

**Comment by koltyakov** [comment]
Hi @FullStackRafik, not everything is expandable with CAML. Can you provide the sample?

**Comment by FullStackRafik** [comment]
Here is it:
let web = new Web(siteUrl);
Const camlQuery = `<View><Query>
    <ProjectedFields>\
        <Field Name="Ref" Type="Lookup" List="List2" ShowField="Title" />\
       </ProjectedFields>\
       <Joins>\
        <Join Type="Left" ListAlias="List2">\
         <Eq>\
          <FieldRef DigiDossMetRefDE="Ref" RefType="Ref" />\
          <FieldRef List="List2" Name="Ref" />\
         </Eq>\
        </Join>\
       </Joins></Query></View>`;
         return  web.lists.getByTitle(listName).getItemsByCAMLQuery({ ViewXml: camlQuery },"FolderNumber","Author","Editor")

**Comment by FullStackRafik** [comment]
Here is it:
let web = new Web(siteUrl);
Const camlQuery = `<View><Query>
    <ProjectedFields>\
        <Field Name="Ref" Type="Lookup" List="List2" ShowField="Title" />\
       </ProjectedFields>\
       <Joins>\
        <Join Type="Left" ListAlias="List2">\
         <Eq>\
          <FieldRef Name="Ref" RefType="ID" />\
          <FieldRef List="List2" Name="ID" />\
         </Eq>\
        </Join>\
       </Joins></Query></View>`;
         return  web.lists.getByTitle(listName).getItemsByCAMLQuery({ ViewXml: camlQuery },"FolderNumber","Author","Editor")

**Comment by koltyakov** [comment]
I don't think Author/Editor can be expanded. In [this issue](https://github.com/pnp/pnpjs/issues/682), we ended up with a suggestion to use `renderListDataAsStream`.

**Comment by FullStackRafik** [comment]
Thanks for your prompt response.
What about other expanded fields? I need also to expand fields rather than Author Editor.

**Comment by FullStackRafik** [comment]
Thanks for your prompt response.
I can't get the expanded fields
Here is my query:
       let myList=  web.lists.getByTitle(listName)
        
       return myList.renderListDataAsStream({
          ViewXml: `
            <View>
            <ViewFields>
            <FieldRef Name="Author"/>
            <FieldRef Name="Person"/>
            </ViewFields>
              <Query>
                <GroupBy Collapse="TRUE">
                  <FieldRef Name="Ref" />
                </GroupBy>
              </Query>
            </View>
          `
        })
        .then((result) => {
          console.log(result)

And this is the console result:
![image](https://user-images.githubusercontent.com/16403403/58262911-66c2c280-7d7b-11e9-9f90-63dbae459894.png)

**Comment by patrick-rodgers** [comment]
Please [review the example](#682) @koltyakov provided, it answers your question.
