### ISSUE TITLE
distinct

### ISSUE THREAD

**Issue by FullStackRafik** [pnp/pnpjs#706]
### Category
- [ ] Enhancement
- [ ] Bug
-[x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.3.1     ]

Please specify what version(s) of SharePoint you are targeting: [     SP2016 On-premises    ]

Is there any way to distinct the result?

**Comment by koltyakov** [comment]
Yes, and nope, there is no distinct in REST OData. This should be done via client-side logic.

But, here is a [way](https://github.com/koltyakov/spday-spb-2018-js-usecases/blob/master/src/06-Electron/src/backend/operations.ts#L24) for a simple distinct using group by and renderListDataAsStream method:

```typescript
list.renderListDataAsStream({
  ViewXml: `
    View>
      <Query>
        <GroupBy Collapse="TRUE">
          <FieldRef Name="SPDayVote" />
        </GroupBy>
      </Query>
    </View>
  `
})
```

**Comment by patrick-rodgers** [comment]
Going to close this as answered, thanks!
