### ISSUE TITLE
Cannot get aadTokenProviderFactory error outside SPFx

### ISSUE THREAD

**Issue by RoelVB** [pnp/pnpjs#708]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 1.3.2

Please specify what version(s) of SharePoint you are targeting: Online

### Observed Behavior
I'm trying to do a graph request (from webbrowser) with a token I already have. But I receive the error:
`TypeError: Cannot get property aadTokenProviderFactory from undefined reference`
(this is not the exact error, because I've translated it tot English)

`aadTokenProviderFactory` is something in the SPFx context. But I'm not using SPFx for this one.
So it looks like the `BearerTokenFetchClient` isn't used!?

### Steps to Reproduce
Here's some example code:
```typescript
import { BearerTokenFetchClient } from '@pnp/common';
import { graph } from '@pnp/graph';

graph.setup({
    graph: {
        fetchClientFactory: ()=>new BearerTokenFetchClient(token),
    }
});

graph.me.get().then((me)=>{
    console.log('me', me);
}).catch((error)=>{
    console.error('me error', error); // This is triggered
});
```

**Comment by RoelVB** [comment]
I did some research and looking at [graphlibconfig.ts](https://github.com/pnp/pnpjs/blob/master/packages/graph/src/config/graphlibconfig.ts) I would expect `RuntimeConfig.get('graph')` to return my setup/config. But instead it returns `undefined`.


Trying to configure using 
```typescript
RuntimeConfig.extend({graph: {
    fetchClientFactory: ()=>new BearerTokenFetchClient(token),
}});
```
gives me the same result as using `graph.setup()`


So it looks like something isn't going as expected here:
https://github.com/pnp/pnpjs/blob/5b32569b61daa77a9b32af12c119f86edf2726ee/packages/common/src/libconfig.ts#L68-L70

**Comment by RoelVB** [comment]
I've created a nasty workaround:
```typescript
(RuntimeConfig as any)._v.set('graph', {
    fetchClientFactory: ()=>new BearerTokenFetchClient(token),
});
````
This does work.

**Comment by RoelVB** [comment]
Almost there! I'm writing an Office add-in, so I'm forced to use Internet Explorer.

It seems this isn't IE compatible:
https://github.com/pnp/pnpjs/blob/5b32569b61daa77a9b32af12c119f86edf2726ee/packages/common/src/collections.ts#L18

**Comment by RoelVB** [comment]
Getting close! I'm writing an Office add-in, so I'm forced to use Internet Explorer.
The issue seem to be with using the `Map` class in IE.

This returns an empty object in IE:
https://github.com/pnp/pnpjs/blob/5b32569b61daa77a9b32af12c119f86edf2726ee/packages/common/src/collections.ts#L25-L30

Sorry for all the messages, but it would be a shame if someone is trying to figure out the same thing.

**Comment by RoelVB** [comment]
Solved (for now) it by using the [es6-shim](https://github.com/paulmillr/es6-shim) pollyfill, but I doubt this is the best solution.

**Comment by patrick-rodgers** [comment]
We also have the [polyfill package](https://pnp.github.io/pnpjs/documentation/polyfill/#ie-11-polyfill-package) for folks using ie11, did you have a look at that?

Trying to piece together your thread, I think the issue was just that Map is not supported in IE11. The polyfill should address this - which again is addressed on the docs page specifically. Let us know if the polyfill package helps out. Thanks.

**Comment by RoelVB** [comment]
Now I feel stupid I didn't notice the IE11 polyfill. I did specifically look for it in the documentation, but didn't find anything.

I'll try this on Monday.
