### ISSUE TITLE
PnP search IE bug

### ISSUE THREAD

**Issue by FullStackRafik** [pnp/pnpjs#714]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ "@pnp/polyfill-ie11": "^1.0.1",@pnp:  "^1.3.1"  ]

Please specify what version(s) of SharePoint you are targeting: [    SP2016 On-premises    ]

I get an error with the search method using Internet Explorer:
Object doesn't support property or method 'assign'.

Here the code I use:
```
import 'es6-promise';
import 'core-js/es/array';
import 'core-js/es/number';
import 'whatwg-fetch';
import "@pnp/polyfill-ie11";
import { SearchQueryBuilder } from "@pnp/polyfill-ie11/dist/searchquerybuilder";
import { sp, ISearchQueryBuilder } from "@pnp/sp";


   const builder: ISearchQueryBuilder = SearchQueryBuilder().text(queryTextString);
    builder.selectProperties("Title", "SPWebUrl", "projectID","RefinableString06","Path")
  return sp.search(builder).then(results => {
        searchResults= results.PrimarySearchResults
        return searchResults
    })
    .catch(e => {
        console.error(e);
    });
  }
```

Any suggestions please?

**Comment by koltyakov** [comment]
Hi @FullStackRafik,

`Object.assign` polyfill is missed, we'll add it to `@pnp/polyfill-ie11` shortly.

As a temporary workaround, you can use `import 'core-js/stable/object/assign';`.

Some additional comment: @pnp/polyfill-ie11 includes required polyfills (mostly), so you don't need importing es6-promise, whatwg-fetch, array. It's already done by [importing @pnp/polyfill-ie11](https://github.com/pnp/pnpjs/blob/master/tools/polyfill-ie11/index.ts).

This works for me in IE11:

```typescript
import 'core-js/stable/object/assign';
import '@pnp/polyfill-ie11';

import { sp, ISearchQueryBuilder } from '@pnp/sp';
import { SearchQueryBuilder } from '@pnp/polyfill-ie11/dist/searchquerybuilder';

const builder: ISearchQueryBuilder = SearchQueryBuilder().text('*');
builder.selectProperties('Title', 'SPWebUrl', 'Path');

sp.search(builder) .then(({ PrimarySearchResults }) => console.log(PrimarySearchResults));
```

For IE10 some additional polyfills might be required such as `Map`. However, importing `import 'core-js/stable/map';` didn't work for me in IE10 from the first quick try.
