### ISSUE TITLE
renderListDataAsStream missing FilterValue1-10...

### ISSUE THREAD

**Issue by johannes-z** [pnp/pnpjs#723]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.2]

Please specify what version(s) of SharePoint you are targeting: [O365]

### Expected / Desired Behavior / Question

FilterValue1, FilterType1, etc. currently cannot be used with the renderListDataAsStream method. It can neither be specified in parameters or overrideParameters.

EDIT: Ideally, renderListDataAsStream has a third parameter, that's an object with key/value pairs that are added as URL parameters.

**Comment by patrick-rodgers** [comment]
Hi @johannes-z - finally have time to look back on some issues. For this, why can;t you include those fields in the overrideParameters? Something like:

```TypeScript
sp.web.lists.getListByTitle("Bob").renderListDataAsStream({
DatesInUtc: true,
}, {
FilterValue1: "something",
FilterType1: "somethingelse",
...
});
```

**Comment by johannes-z** [comment]
@patrick-rodgers Hm I'm pretty sure I tried this before but I got an error from sharepoint, saying that this key/value pair wasn't allowed in the overrideParameters, but it works now (using version 1.3.3 instead of 1.3.2). I'll close this for now, and open it in case I come across the error again.
