### ISSUE TITLE
publish function sending calls to incorrect REST url

### ISSUE THREAD

**Issue by lsavard** [pnp/pnpjs#725]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.3.2        ]

Please specify what version(s) of SharePoint you are targeting: [ Online         ]

### Expected Behavior
when using the .publish() function, the call is made successfully to the correct REST endpoint

### Observed Behavior
Behavior is correct when function is called from ListView (e.g. https://xxxxx.sharepoint.com/sites/Test/Documents/Forms/AllItems.aspx ). In that case, we can see the request being sent to correct url :   https://xxxxx.sharepoint.com/sites/Test/_api/web/getFileByServerRelativeUrl('/sites/Test/Documents/Document.docx')/publish(comment='')

Behavior is NOT correct when same function is called, by same code, from ListView WebPart in a modern site page (e.g. the site home page https://xxxxx.sharepoint.com/sites/Test). In that case, we can see the request being sent to incorrect url :   https://xxxxx.sharepoint.com/sites/_api/web/getFileByServerRelativeUrl('/sites/Test/Documents/Document.docx')/publish(comment='')

Thanks !

**Comment by KEMiCZA** [comment]
@lsavard did you establish the SPFx context?

https://pnp.github.io/pnpjs/documentation/getting-started/#getting-started-with-sharepoint-framework

**Comment by lsavard** [comment]
Thanks ! It works flawlessly with this setup !
