### ISSUE TITLE
the parameter: listRelativePath is missing in the addClientSidePageByPath method

### ISSUE THREAD

**Issue by dkhmm** [pnp/pnpjs#727]
### Category
- [ ] Enhancement
- [X] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.3]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question

I want to create a client side page with a relative path.
But it seems like the parameter (listRelativePath) is missing in code ?

`
    /**

     * Creates a new client side page using the library path
     *
     * @param pageName Name of the new page
     * @param listRelativePath The server relative path to the list's root folder (including /sites/ if applicable)
     * @param title Display title of the new page
     */
    public addClientSidePageByPath(pageName: string, title = pageName.replace(/\.[^/.]+$/, "")): Promise<ClientSidePage> {
        return ClientSidePage.create(this, pageName, title);
    }`

I appreciate your help with the above question
Henrik

**Comment by juliemturner** [comment]
Not sure if it's relevant to the question but I need to create pages in sub-folders in the pages library so I ended up using:

    sp.web.getFileByServerRelativeUrl(sourceUrl).copyTo(destUrl, true);

That said, this does not take relative url's so I build out the full url by using:

    document.location.origin + relativeurl

**Comment by dkhmm** [comment]
Thanks!
Instead of the missing parameter, I used the following, because I only needed to root pages:
```
const w = new Web(theURL);
const page: ClientSidePage = await w.addClientSidePageByPath(theFileName, theTitle);
```

**Comment by pconnell99** [comment]
Sorry to comment on a closed ticket, but the page at https://pnp.github.io/pnpjs/sp/docs/client-side-pages/ still references this parameter incorrectly - who fixes that?
