### ISSUE TITLE
How to add array in to sharePoint single line of text field using PNP .js

### ISSUE THREAD

**Issue by Nagarajan1605** [pnp/pnpjs#728]
Hi,

I have a scenario,

Where multiple check box values are there during add function i have to add all the arrary values in to sharePoint list column using pnp.js. This is onpremise SP2016.

Please Look at the below code.
function multiplepoliciescheckbox(){
		
			$('input[type=checkbox]:checked').each(function (){
				multiplepoliciesval=$(this).parent().find('label').text();
				checkedpolicies.push(multiplepoliciesval);
			});
	
	}

function DummySavePolicy(){
multiplepoliciescheckbox();
//PNP JS ADD Method
$pnp.sp.web.lists.getByTitle("TestList").items.add({
Title:{results:[checkedpolicies]},

});

**Comment by koltyakov** [comment]
This question has nothing in common with PnPjs internals or REST API, but a general development question. We encourage asking such questions in Tech Community or other community resources and forums.

However, before closing this. You just need to convert your object data to the field data type/OData. E.g. saving to a string/text the data should be a string. A JS object can be serialized to a string using `JSON.stringify`.
