### ISSUE TITLE
404 errors for pages in documentation

### ISSUE THREAD

**Issue by lhoff** [pnp/pnpjs#730]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [N.A. ]

Please specify what version(s) of SharePoint you are targeting: [N.A.]

### Observed Behavior
In the [documentation](https://pnp.github.io/pnpjs/documentation/packages/), on the Packages page, under 'common', the links for '[decorators](https://pnp.github.io/pnpjs/common/docs/decorators.md)' and '[exceptions](https://pnp.github.io/pnpjs/common/docs/exceptions.md)' go to a 404 page.

**Comment by patrick-rodgers** [comment]
Thanks, we'll get that cleaned up.

**Comment by patrick-rodgers** [comment]
Got this updated, new docs will publish with the next release on Friday July 12
