### ISSUE TITLE
transition guide

### ISSUE THREAD

**Issue by RiccardoAmadi** [pnp/pnpjs#736]
The link for the trasition guide at https://github.com/SharePoint/PnP-JS-Core results in a 404

### Category
- [x] Documentation gap/issue

### Expected Behavior
Clicking the link shows the guide

### Observed Behavior
The page https://pnp.github.io/pnpjs/transition-guide.html results in a 404

**Comment by patrick-rodgers** [comment]
Thanks, updated the link.
