### ISSUE TITLE
Store Data from batch in array and work with these data after batch executed

### ISSUE THREAD

**Issue by enti333** [pnp/pnpjs#745]
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

Hello. Please I need little help with understand why my array is not filled in batch. 
I am working with batch and I want that my property **EmailProcessArray**   is filled with data 

```
let EmailProcessArray = [];
let batch = sp.createBatch();
    
arrayItems.forEach(element => {
  sp.web.lists.getByTitle(encodeURIComponent('XXXX')).items
    .getById(parseInt(element)).inBatch(batch).select("ID,Title").get()
    .then(dataT => {
      EmailProcessArray.push({
        ID: dataT.ID,
        Title: dataT.Title,
      });
});
    
batch.execute().then(x => {
  //EmailProcessArray is empty
}).catch(err => {});
````

When debugging I see that EmailProcessArray is filled but when batch is executed the property is empty... 
What I am doing wrong how to work with data executed in batch.... 
Thank you very much.

**Comment by koltyakov** [comment]
Hi @enti333,

_To be able to read a code sample I got to apply a change in your initial message._

Logically, it's correct and after batch executed the array should be populated with values.
In your code you execute `batch.execute()` inside array `forEach`, looks this is the reason.

After a quick try with some minor code changes, it just works as expected:

![image](https://user-images.githubusercontent.com/7816483/59981319-08069800-960a-11e9-8ad9-ac3f846fd5f3.png)

So, I tend considering that it's an error in your code which causes the issue on your end.

**Comment by enti333** [comment]
Thank you very much.,Right now is working. Thank you:)
