### ISSUE TITLE
Adding folder in a List doesn't create an assigned list item - is it an error?

### ISSUE THREAD

**Issue by k2042** [pnp/pnpjs#747]
### Category
- [ ] Enhancement
- [X] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.2]

Please specify what version(s) of SharePoint you are targeting: [SPO]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.* 1: It's complicated. 2: From the abundance of questions about creating subfolders and the answers I assume the issue is not resolved.

### Expected / Desired Behavior / Question
When in a Document Library or its subfolder, I use the method chain  web.getFolderByServerRelativeUrl(relativeUrl).folders.add(folderName) and get a subfolder created with the desired path, name and also an assigned list item, which, in the first place, makes the folder visible in the DocLib and also can receive values for custom columns in the DocLib.
When doing the same in a List, I expect the same behavior. However...

### Observed Behavior
...the method chain web.getFolderByServerRelativeUrl(relativeUrl).folders.add(folderName) called for a List or its subfolder creates only the folder itself, without an assigned item to it. As a result, a programmatically created folder is not visible in the list (yet accessible via URL).

The workaround around it can be found in https://github.com/pnp/pnpjs/issues/100, it helps,
 but it makes things complicated without a need.

Is the difference between folders.add() calls in a Library and a List (not creating the list item assigned to the new folder in a List) a bug or a feature?

### Steps to Reproduce
Use the following call chain for a List root folder or subfolder via relative URL: web.getFolderByServerRelativeUrl(relativeUrl).folders.add(folderName)

**Comment by koltyakov** [comment]
And it shouldn't. This is how the SharePoint API designed to work. When a folder item is needed, the item with corresponding folder content type should be created.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Thanks!
