### ISSUE TITLE
HubSiteData - navigation array not showing all results

### ISSUE THREAD

**Issue by AndresPita** [pnp/pnpjs#748]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [1.3.3]
Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior
The hubSiteData(true) method returns all sites associated to the hub.

### Observed Behavior
The call returns only one site collection even though more are associated to the hub.

### Steps to Reproduce
You need to have multiple site collections (children) associated to the hub site collection.
Since the issue can be with the `forceRefresh?: boolean` I suggest creating new site collections and associate them to the hub. Call `await sp.web.hubSiteData(true);` in the context of the hub site collection (parent). The result is that only one navigation node is returned in the array.

### Comments
Hello. I suspect that the issue might be with the forceRefresh. But that's just my guess.
Calling `/_api/web/HubSiteData(true)` has the same behaviour/bug.

**Comment by patrick-rodgers** [comment]
If you are seeing the same behavior calling the site directly unfortunately we won't be able to do much to help. Do the other sites you expect to see appear after some time or never? Is the behavior consistent when calling the service directly?

**Comment by AndresPita** [comment]
@patrick-rodgers After further testing I realized that the call only returns the sites associated which are (manually) set up in the navigation of the hub site. 
I expected the call to be able to return all the sites which are associated to a hub site regardless of being set up in the navigation or not.

**Comment by patrick-rodgers** [comment]
Ok, sounds like we can close this then?
