### ISSUE TITLE
getAll equivalent in pnpjs-graph ??

### ISSUE THREAD

**Issue by narulasrinivas** [pnp/pnpjs#750]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using:    "@pnp/graph": "^1.3.3"      

Please specify what version(s) of SharePoint you are targeting: SharePoint Online

### Question
In @pnp/sp,  there is **getAll** method to fetch all items from a list irrespective of its size. Do we've any equivalent to this in @pnp/graph?

Here is the docs for @pnp/sp reference : [https://pnp.github.io/pnpjs/sp/docs/items/#get-all-items](url)

My list has 7600 records and in @pnp/graph, I used **top** method. But top method returns only 5000 records.

Here is my code snippet.

`
let listId : string = "a6b90b14-f5ba-4e47-a476-421437df4436";

      //Query fetch all items for the given list Info
      const listQuery = new GraphQueryableCollection(graph.sites.getById('srinivasnarula.sharepoint.com', '/sites/sitecol1/subsite1'), "lists/" +listId+ "/items");

      //Expand the fields object to read fields content
      const fetchFieldsinList = await listQuery.expand("fields").top(7600).get();

      for (const listDataInfo of fetchFieldsinList) {
    
        let results = await listDataInfo.fields;

          console.log(results);
      }
`

Please let me know if there is any method available in @pnp/Graph equivalent to getAll of @pnp/sp.

**Comment by patrick-rodgers** [comment]
There is not currently an equivalent method in the graph library. You can use the sp library's method as a work around, we can leave this open as an enhancement idea.

**Comment by patrick-rodgers** [comment]
Going to close this in favor of the sp method that already exists. Happy to take a PR if someone wants to code this up. Thanks!
