### ISSUE TITLE
Send email - From address is not working.

### ISSUE THREAD

**Issue by pavan2920** [pnp/pnpjs#751]
Hi Team, 

I am using  sp.utility.sendEmail(email) to send email to the user, which works. 

I want to modify the From address which is a optional parameter in **EmailProperties** Interface. Tried assigning a value for **From** property as String but doesn't work. 

Can any one help me with the same? 

Thanks & Regards, 
Pavan.

**Comment by patrick-rodgers** [comment]
When sending email from REST the from address is always ignored and the tenant configured from address is used. At least that is what I remember from the last time this was asked, I don't think anything has changed.

**Comment by patrick-rodgers** [comment]
Going to close this as answered, thanks.
