### ISSUE TITLE
locale enum missing

### ISSUE THREAD

**Issue by jonathan-dev** [pnp/pnpjs#754]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.3]

Please specify what version(s) of SharePoint you are targeting: [SP13]

### Question
Why is the locale enum added in this https://github.com/SharePoint/PnP-JS-Core/pull/67 pull request no longer available? Where is it gone or why was it removed?

**Comment by patrick-rodgers** [comment]
We removed it from the library some time ago as it wasn't being used by folks and generated a large block of un-minimizable code. If you need the full enum you can grab the contents of that file and easily add it to your project.
