### ISSUE TITLE
Save list item not working with pnp/graph

### ISSUE THREAD

**Issue by narulasrinivas** [pnp/pnpjs#755]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   ` "@pnp/graph": "^1.3.3"`      ]

Please specify what version(s) of SharePoint you are targeting: [     SharePoint Online    ]

### Expected / Desired Behavior / Question
I'm trying to save list item to sharepoint list using pnp/graph. I followed an example to create a record as shown below.

```
import { graph } from "@pnp/graph";

const newItem = await graph.sites.getById('contoso.sharepoint.com').lists.getById('listId').items.create({
"fields": {
    "Title": "Widget",
    "Color": "Purple",
    "Weight": 32
  }
})
```

But when I put in my ts file, it is giving me below error:

```
Argument of type '{ "fields": { "Title": string; "Color": string; "Weight": number; }; }' is not assignable to parameter of type 'FieldValueSet'.
  Object literal may only specify known properties, and '"fields"' does not exist in type 'FieldValueSet'.ts
```

Please help me to fix this issue and of what's causing this issue?

**Comment by patrick-rodgers** [comment]
I don't think you need the "fields" part, I believe you just need to supply the object like this:

```TypeScript
const newItem = await graph.sites.getById('contoso.sharepoint.com').lists.getById('listId').items.create({
    "Title": "Widget",
    "Color": "Purple",
    "Weight": 32,
});
```

**Comment by narulasrinivas** [comment]
I tried that also, still getting same error

```
const newItem = await  graph.sites.getById('srinivasnarula.sharepoint.com').lists.getById('listId').items.create({
            "Title": "Widget",
            "Color": "Purple",
            "Weight": 32
              });
```

Error
```
Argument of type '{ "Title": string; "Color": string; "Weight": number; }' is not assignable to parameter of type 'FieldValueSet'.
  Object literal may only specify known properties, and '"Title"' does not exist in type 'FieldValueSet'.
```

**Comment by patrick-rodgers** [comment]
Can you try it this way based on the error message:

```TypeScript
const newItem = await graph.sites.getById('contoso.sharepoint.com').lists.getById('listId').items.create({
    Title: "Widget",
    Color: "Purple",
    Weight: 32,
});
```

**Comment by narulasrinivas** [comment]
Even with above code, it is still same

```
Argument of type '{ Title: string; Color: string; Weight: number; }' is not assignable to parameter of type 'FieldValueSet'.
  Object literal may only specify known properties, and 'Title' does not exist in type 'FieldValueSet'.
```

**Comment by narulasrinivas** [comment]
Hi Community....Did anybody tried to use this code?. If so, can anybody help me to resolve this issue?

**Comment by KEMiCZA** [comment]
@narulasrinivas  can you try:

```typescript
const newItem = await graph.sites.getById('contoso.sharepoint.com').lists.getById('listId').items.create(<any>{
    Title: "Widget",
    Color: "Purple",
    Weight: 32,
});
```

**Comment by narulasrinivas** [comment]
@KEMiCZA - It worked perfectly. Thanks alot for helping me out.

@patrick-rodgers - Whether working code will be updated in pnpjs v1 or directly in pnpjs v2?

I'm happy to give a hand to update in either of them.

**Comment by patrick-rodgers** [comment]
I think honestly this is a bug in the graph types as it doesn't make much sense looking at their d.ts file. We should change our typing to any for this, or a TypedHash<any>. This should be fixed in v1 and v2. If you want to submit a PR that would be much appreciated for sure.

**Comment by patrick-rodgers** [comment]
Fixed this in v1 branch, will go out as part of the Friday July 12 release.
