### ISSUE TITLE
SharePoint operations docs link (@pnp/graph/sites) is missing from pnpjs/graph

### ISSUE THREAD

**Issue by narulasrinivas** [pnp/pnpjs#756]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

###  Desired Behavior
In pnp/graph documentation, sites package is missing from the documentation. 

@pnp/graph packages are listed in [pnpjs/graph](https://pnp.github.io/pnpjs/graph/docs/), but [pnp/graph/sites](https://pnp.github.io/pnpjs/graph/docs/sites/) are missing under packages. 

I came across this [pnp/graph/sites](https://pnp.github.io/pnpjs/graph/docs/sites/) in google search, not showing it up under graph packages. 

Is it expected behaviour or docs link is missing or docs are under review?

**Comment by patrick-rodgers** [comment]
Yes, this is known and we will have fully updated docs for v2 coming out later this year. Thanks!
