### ISSUE TITLE
disable Logger

### ISSUE THREAD

**Issue by TomBombardil** [pnp/pnpjs#761]
### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.3.3     ]

Please specify what version(s) of SharePoint you are targeting: [    SP2016     ]

### Expected / Desired Behavior / Question
How to disable logging output to console when executing requests

### Observed Behavior
pnp keeps logging to console even after changing the Loggers activeLogLevel to LogLevel.Off and/or clearing the Loggers subscribers

### Steps to Reproduce
I tried to disable logging output when executing requests by adding 
Logger.activeLogLevel = LogLevel.Off;
after sp.setup
like so:
```
constructor() {
        this.addinWebUrl = decodeURIComponent(this.util.getQueryStringParameter('SPAppWebUrl'));
        sp.setup({
            sp: {
                headers: {
                    'Accept': 'application/json; odata=verbose'
                },
                fetchClientFactory: () => {
                    return new SPRequestExecutorClient();
                }
            }
        });
        Logger.activeLogLevel = LogLevel.Off;
        Logger.clearSubscribers();
    }
```
However this does not disable the logging output. Can someone please tell me how to avoid logging output?

btw: working on a provider hosted addin

Thank you for your feedback!

**Comment by KEMiCZA** [comment]
How are you logging, are you still using console.log or Logger.write?

**Comment by TomBombardil** [comment]
I am using console.log.
My problem however is that pnp is logging excessivly to console, which makes it hard to find my own logging entries.
I want to disable pnp from logging to console.

**Comment by KEMiCZA** [comment]
I tried reproducing this issue, but it works fine for me.
Can you share more of your code?

**Comment by patrick-rodgers** [comment]
Unless you are explicitly subscribing a logger in your application I am not sure how we would be logging anything. As requested by @KEMiCZA can you provide a minimal reproduction we can clone and examine?

**Comment by TomBombardil** [comment]
Hello again

Very sorry for having bothered you with this issue. It seems the logging originates from the sp.requestexecutor.js

That's what they basically look like:
```
Mon Jul 08 2019 09:10:49 GMT+0200 (W. Europe Daylight Time):RequestExecutor.PostMessage.Message: {"command":"Ping","postMessageId":"SP.RequestExecutor5"}
Mon Jul 08 2019 09:10:49 GMT+0200 (W. Europe Daylight Time):RequestExecutorMessageProcessor.OnMessage
```

I tried copying the file SP.RequestExecutor.js into the app and disabling the logging function - but somehow it gets pulled again from the hive (_layouts/15/).

I understand this has nothing to do with pnpjs - however if you have any idea how I could get rid of these logging messages It would be much appreciated.

Kind regards

**Comment by KEMiCZA** [comment]
Why do you want to remove those messages anyway?

If you want to be more specific with your own console logs, there are some tricks out there. For example you could group your logs. You could also do a console.clear() before doing your own logging.

A quick google search: https://medium.com/appsflyer/10-tips-for-javascript-debugging-like-a-pro-with-console-7140027eb5f6

The following stackoverflow had a similar question: https://sharepoint.stackexchange.com/questions/209555/how-to-remove-sp-requestexecutors-js-console-logs

I quickly looked at the javascript in the sp.requestexecutor.js file and there's a wrapper function for logging. You can perhaps override this function using the following code:

```javascript
SP.RequestExecutor.$1 = function() {};
```

I do have to say that this is not a PnPjs issue, so it would be better to ask these kind of questions on a different forum in the future. And if you can please close the issue.

**Comment by TomBombardil** [comment]
Thanks for the input!

**Comment by patrick-rodgers** [comment]
All good @TomBombardil , thanks!
