### ISSUE TITLE
Unable to Add Custom roleDefinition

### ISSUE THREAD

**Issue by wimosh** [pnp/pnpjs#766]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
   "@microsoft/sp-core-library": "1.8.2",
    "@microsoft/sp-lodash-subset": "1.8.2",
    "@microsoft/sp-office-ui-fabric-core": "1.8.2",
    "@microsoft/sp-property-pane": "1.8.2",
    "@microsoft/sp-webpart-base": "1.8.2",
     "@pnp/sp": "^1.3.3

### Expected / Desired Behavior / Question
After called the Roledefinitions  add method:
![image](https://user-images.githubusercontent.com/26660996/60844676-72920900-a1b0-11e9-87c8-302a64f96f01.png)
Expected a new Roledefinition Created in the current web.

### Observed Behavior
Got error 400.
![image](https://user-images.githubusercontent.com/26660996/60845452-c271cf80-a1b2-11e9-8925-9a257914437d.png)
![image](https://user-images.githubusercontent.com/26660996/60845471-cf8ebe80-a1b2-11e9-964c-dc33de87b41d.png)
![image](https://user-images.githubusercontent.com/26660996/60845503-e9300600-a1b2-11e9-91ef-f03ba034f692.png)

After some investigation, I changed the TypeScript type definitions types.d.ts:
From:
![image](https://user-images.githubusercontent.com/26660996/60845267-1fb95100-a1b2-11e9-89fd-21edfaac94f5.png)
To:
![image](https://user-images.githubusercontent.com/26660996/60844869-02d04e00-a1b1-11e9-8b0d-73e089aed088.png)

With this, the method worked as expected:
![image](https://user-images.githubusercontent.com/26660996/60845347-64dd8300-a1b2-11e9-98c5-9563f92befa0.png)
![image](https://user-images.githubusercontent.com/26660996/60845399-90606d80-a1b2-11e9-9e01-19647f4a876b.png)

### Steps to Reproduce

```typescript 
// Remove this if you don't have any code sample to provide
import { sp } from "@pnp/sp";
.
.
.
export default class DemoWebPart extends BaseClientSideWebPart<IDemoWebPartProps> {
public onInit(): Promise<void> {
    return super.onInit().then(_ => {
      sp.setup({
        spfxContext: this.context
      });
    });
  }
 public render(): void {
    const element: React.ReactElement<IDemoWebPartProps> = React.createElement(DemoComponent, {
      description: this.properties.description,
      sp: sp
    });

    ReactDom.render(element, this.domElement);
  }

.
.
.
}

export default class DemoComponent extends React.Component<
  IDemoComponentProps,
  IDemoComponentState
>{
.
.
protected createRoleDefinition = (): Promise<RoleDefinitionAddResult> => {
 let permission:BasePermissions ={
      High: 0,
      Low: 67309570
 }   
  return this.props.sp.web.roleDefinitions.add("test","test",1000,permission);
  };
.
.
}

```
Am i doing something wrong? 
If not, what workaround should I implement?

**Comment by patrick-rodgers** [comment]
Well that is odd, I swear at one point we changed this from string to number to fix a different parsing issue. I have updated the code for both add and update without changing the interface. So you can still pass numbers and they get converted to strings. The other way would be a breaking change to the interface, which I'd like to avoid. Thanks for reporting this. Fix will be part of the release this Friday July 12.
