### ISSUE TITLE
how to use getPaged with entity merging

### ISSUE THREAD

**Issue by ioan-agopian** [pnp/pnpjs#767]
### Category
- [ ] Enhancement
- [ ] Bug
- [ x] Question
- [x ] Documentation gap/issue

### Version
    "@pnp/common": "^1.3.3",
    "@pnp/logging": "^1.3.3",
    "@pnp/odata": "^1.3.3",
    "@pnp/sp": "^1.3.3",

### Expected / Desired Behavior / Question
I am trying to use entity merging (https://pnp.github.io/pnpjs/sp/docs/entity-merging/) with getPaged. 

I have the following code:
```
sp.web.lists.getByTitle(Stock.ListTitle).items.select("Id","Title", "Quantity")
          .getPaged<Stock[]>().then((items: PagedItemCollection<Stock[]>) => {
                      console.log(items.results);` 
});
```

The items returned have all the correct properties, however any custom functions defined in the Stock class are not available on the items returned. 

Any suggestions or direction will be much appreciated.

**Comment by patrick-rodgers** [comment]
Well, great question. We don't currently have support for that. Let me have a look at what it will take and maybe get it into the Friday release (July 12).

**Comment by patrick-rodgers** [comment]
Had a chance to add this, will be in 1.3.4 on Friday. You can see the [docs here](https://github.com/pnp/pnpjs/blob/dev/packages/sp/docs/entity-merging.md#use-with-item-getpaged)
