### ISSUE TITLE
Cannot alias name with embedded apostrophe

### ISSUE THREAD

**Issue by wmertens** [pnp/pnpjs#772]
### Category
- [x] Bug

### Version

Please specify what version of the library you are using: [    1.3.2     ]

Please specify what version(s) of SharePoint you are targeting: [   no idea      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

The changelog for 1.3.3 does not include anything that might fix this

### Expected / Desired Behavior / Question

aliases should always work

### Observed Behavior

When using the following function

```js
export const getFolderByUrl = (url) => {
    const web = new Web(siteUrl)
	// Note: this uses an alias to shorten the path. Make sure they don't clash with other aliases
	return web.getFolderByServerRelativeUrl(
		`!@x1::${
			// TEMP workaround for pnpjs issue #313
			url.replace(/'/g, "''")
		}`
	)
}
```

with the url `"/pathToSite/Shared Documents/blabla/diploma's restaurateurs"`, it cuts the url at the apostrophe and creates the nonsense SP URL `https://sharepointhost/pathToSite/_api/web/getFolderByServerRelativeUrl(@x1%27s%20restaurateurs%27)/listItemAllFields?@x1=%27/pathToSite/Shared%20Documents/blabla/diploma%27`

it seems to me that if an argument starts with `/^!@[a-zA-Z0-9]+::/`, the rest of the argument is the string to alias?

**Comment by wmertens** [comment]
I came up with this workaround which probably won't work in v2

```js
	return web.getFolderByServerRelativeUrl(
		`!@x1::${
			// this is required in pnpjs v1
			encodeURIComponent(url)
			// workaround for https://github.com/pnp/pnpjs/issues/772
			// only works because it will be used in a query string
			.replace(/'/g, '%27%27')
		}`
	)
```

**Comment by patrick-rodgers** [comment]
I understand your focus on parameter aliases based on the other issues and comments you've made, but this is overall an edge case. Will take a look at resolving this for the next release, but don't want to rush something in that might end up breaking more than it fixes. Also, it appears you have a workaround that while not ideal unblocks your scenario so waiting and applying the right fix is the best options IMO.

**Comment by patrick-rodgers** [comment]
This is fixed in v2 and we won't back port the fix to v1 as it is tied into the escaping query strings all up.
