### ISSUE TITLE
Cannot use FieldcreationProperties to add multiple selections in a personandgroup column

### ISSUE THREAD

**Issue by igarcia7** [pnp/pnpjs#774]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   import { sp, FieldUserSelectionMode } from "@pnp/sp"      ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online    ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
**Ability to use parameter SelectionGroup when creating a person and group column in a list. 
Properties to modify "Allow multiple selections" cannot be set via the sp.web.list addUser command.** 
Revised the section in npn types.ts, the parameter is not present to use. 

Reference: https://github.com/pnp/pnpjs/blob/dev/packages/sp/src/types.ts

export interface FieldCreationProperties extends TypedHash<string | number | boolean> {
    DefaultFormula?: string;
    Description?: string;
    EnforceUniqueValues?: boolean;
    FieldTypeKind?: number;
    Group?: string;
    Hidden?: boolean;
    Indexed?: boolean;
    Required?: boolean;
    Title?: string;
    ValidationFormula?: string;
    ValidationMessage?: string;
}

*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
1. create list with <div>"pnpWeb.lists.add(ListSiteInfo, 'Site Information List', 100, false)"</div>
2. create people column with Div below, 
3. no ability to allow multiple selections in column
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

<div>``sp.web.lists.getByTitle(ListSiteInfo).fields.addUser('Primary Contact',FieldUserSelectionMode.PeopleAndGroups,{Required: true});
```</div>



Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
You can already do this. The interface extends TypedHash so you can add any props you need:

```TypeScript
    await sp.web.lists.getByTitle("ChoiceFieldList").fields.addUser("something", FieldUserSelectionMode.PeopleAndGroups, {
        AllowMultipleValues: true,
        Required: true,
    });
```
