### ISSUE TITLE
Document 

### ISSUE THREAD

**Issue by JaeEmAre67** [pnp/pnpjs#775]
### Category
- [ ] Enhancement
- [X] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.2.8  ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.* Updated to 1.3.2-0 with same issue

### Expected / Desired Behavior / Question
Ability to upload any Microsoft Office document (docx, xlsx, pptx) to a document library with a custom People Picker field which is required. Failure appears to be at the check-in process. If check-in is not required, the file is uploaded with no (0)

### Observed Behavior
Uploading any other file type (pdf, jpeg) works without issue, Microsoft Office document fail using exact same code into same library

### Steps to Reproduce
Using the code below, a document is uploaded to a file field on a React generated form, along with about 12 other metadata fields (input, textarea, select and a couple connected to the term store). The code below *does* upload the document to the library, however the other fields are not set and the check in fails because of missing required fields. This *does* work if the file is a PDF or JPEG. If the file extension is DOCX, XLSX or PPTX it fails.

<div>
```typescript 

let updateListItemInSP = async (spObject:any, filePath:string, dataObject:object, listId:string, listItemId:string):Promise<void> => {
    try {
        let listItem:object = await spObject.web.lists.getById(listId).items.getById(parseInt(listItemId)).get();

        // check out the sharepoint item
        if ( listItem['CheckoutUserId'] === null ) {
            await pnpjs.checkOutItem(spObject, filePath);
        }

        // update the item using its list id and itemId and passing an object containing the updated fields
        await spObject.web.lists.getById(listId).items.getById(parseInt(listItemId)).update(dataObject).then((updateResults) => {
            try {
                // check the list item back in upon successful update
                if ( listItem['CheckoutUserId'] !== undefined ) {
                    pnpjs.checkInItem(spObject, filePath);
                }
            } catch (exception) {
                common.logException(exception);
            }
        }).catch((exception) => {
            common.logException(exception);

            // discard the checkout from a fail update
            pnpjs.checkOutItem(spObject, filePath, true);
        });
    } catch (exception) {
        common.logException(exception);
    }
};
```
</div>

**Comment by koltyakov** [comment]
Doesn't look like any sort of a bug in PnPjs but a REST API and SharePoint behavior. Therefore nothing to change on our end to amend this.
You can try the library setting to "Require Check Out" so the document after the initial upload is checked out, then update with mandatory fields and checking should work.

**Comment by patrick-rodgers** [comment]
Can you share a repo we can clone that shows this issue? At least then we can debug it and see what is actually happening.

**Comment by patrick-rodgers** [comment]
Closing this due to no response. Should you still require help please open a new issue and reference this one. Thanks!
