### ISSUE TITLE
Using Graph beta endpoint

### ISSUE THREAD

**Issue by JakeStanger** [pnp/pnpjs#777]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.3]

Please specify what version(s) of SharePoint you are targeting: [Online, SPFx 1.8.2]

### Expected / Desired Behavior / Question

Is it current possible to use PnP Graph to perform requests on the beta Graph endpoints? If not, what is the recommended approach?

If this is not possible and something you are looking to add, I'd be willing to submit a PR.

**Comment by patrick-rodgers** [comment]
There is a [protected method "setEndpoint"](https://github.com/pnp/pnpjs/blob/dev/packages/graph/src/graphqueryable.ts#L125) you can use if you cast the object to "any":

```
(<any>obj).setEndpoint("beta")
```

That isn't optimal so for this release I will make that method public. That will go out today.

**Comment by JakeStanger** [comment]
Brilliant, amazing service!
