### ISSUE TITLE
Get EMail from UserField which has multiple selections

### ISSUE THREAD

**Issue by enti333** [pnp/pnpjs#778]
- [ ] Enhancement
- [ X] Bug
- [ ] Question
- [ ] Documentation gap/issue

Hello. When my user field has multiple selections enabled I am not able to get EMail data for these users. I ame able to get Title or ID but not EMail....

`sp.web.lists.getByTitle(encodeURIComponent('XXXX')).items.filter("xxxxx eq '" + this.state.recipientDepartament + "'").select("kontakt_person/EMail").expand("kontakt_person").get().then(data => { ` 

This throw an error when I disable multiple selections everything works. 
Thank you very much for help.

**Comment by koltyakov** [comment]
What the error message? SharePoint version?

Is unlikely an error in PnPjs but environment/artefacts/SP version.

And the scenario works for me in SPO, btw:

![image](https://user-images.githubusercontent.com/7816483/61082379-07f00000-a432-11e9-9b07-d87c003c0f66.png)

**Comment by enti333** [comment]
Hello. The error is 

Uncaught (in promise) Error: Error making HttpClient request in queryable [500]  ::> {"odata.error":{"code":"-2146232832, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"Cannot get value for projected field kontakt_person_x005f_EMail."}}} 

Thank you... I have tested it again when this field is not Multiple it works if it is multiple it doesn't but only for EMail property...Title and ID is OK...Thank you

**Comment by enti333** [comment]
I think that I found the problem is I have in this field user which doesn't have email account

This user doesn't have an Exchange Online license.

and it doesn't work....But question is ...is this OK that it ends with error? Thank you

**Comment by koltyakov** [comment]
These cases with HTTP 500/other StatusCodes is a server API response, 100% non-library.

**Comment by enti333** [comment]
Hmm....But my test user doesn't have email account...When field is not set for multiple it works and in EMail property I have null....But When I enable Multiple it ends with this error.... So Again it is OK that it doesn't have null but ends with error...Thank you

**Comment by koltyakov** [comment]
It's not ok, IMO, but it is current SharePoint API behavior, and I think I faced the same too yet it was not critical in my case. Unfortunetely nothing can be changed in the library to fix server side of the REST API as PnPjs is a client.

**Comment by enti333** [comment]
Thank Andrew for you help:)
