### ISSUE TITLE
sp.profiles.clientPeoplePickerSearchUser does not work with odata=verbose

### ISSUE THREAD

**Issue by Zerg00s** [pnp/pnpjs#78]
### Category
- [ ] Enhancement
- [ X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.0.4]

### Expected / Desired Behavior / Question
sp.profiles.clientPeoplePickerSearchUser should return data with when using **odata=verbose**:

> Accept: 'application/json;odata=verbose'

### Observed Behavior
Error:

> Uncaught (in promise) SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at eval (sp.es5.js:8390)

### Steps to Reproduce
```
import { sp } from '@pnp/sp';

sp.setup({ sp: { headers: { Accept: '**application/json;odata=verbose**' } } });

sp.profiles.clientPeoplePickerSearchUser({
  MaximumEntitySuggestions: 5,
  PrincipalSource: 15,
  PrincipalType: 15,
  QueryString: 'test'
}).then((entiries) => console.log(entiries));
```

### Temporary Workaround
Use odata=minimalmetadata

```
import { sp } from '@pnp/sp';

sp.setup({ sp: { headers: { Accept: '**application/json;odata=minimalmetadata**' } } });

sp.profiles.clientPeoplePickerSearchUser({
  MaximumEntitySuggestions: 5,
  PrincipalSource: 15,
  PrincipalType: 15,
  QueryString: 'test'
}).then((entiries) => console.log(entiries));

```

**Comment by koltyakov** [comment]
Hey Denis,

Thanks for reporting! We'll take a look into this issue.

**Comment by koltyakov** [comment]
Fixed locally, almost ready to push a PR after some tests done.

**Comment by koltyakov** [comment]
Here we are, PR is done. Please stay tuned for traditional Friday beta celebration. ;)
