### ISSUE TITLE
SharePoint Alerts via sp rest

### ISSUE THREAD

**Issue by gbminnock** [pnp/pnpjs#782]
- [ ] Question

### Version 

Please specify what version of the library you are using: [     1.3.3    ]

Please specify what version(s) of SharePoint you are targeting: [       Online  ]

Is it possible to add alerts using pnp/sp. The alerts I want to add are referenced using
~/_api/web/alerts
and adding alert at
~/api/web/alerts/add with an accompanying json body. 

I tried this out using SPHttpClient calling the api endpoint and posting body but was unable to get it to work.
thanks,
Gary

**Comment by patrick-rodgers** [comment]
We don't have that endpoint included yet. If it is exposed via REST we should be able to add it. Will tag this as an enhancement.

**Comment by gbminnock** [comment]
Thanks @patrick-rodgers

**Comment by gbminnock** [comment]
@patrick-rodgers  I've had a look at the @pnp sp-clientsvc but I am unable to figure out what needs to be done to use the client.svc. I have the xml payload pulled from csom 'add alert' equivalent using fiddler. I wonder would there be some guidance on how to use it?

**Comment by koltyakov** [comment]
Hi @gbminnock,

I'd suggest something similar to [such call pattern](https://github.com/koltyakov/sp-sig-20180705-demo/blob/master/src/02-clientSvc/helper.ts).
