### ISSUE TITLE
Unable to add client side wepbart after updating version. 

### ISSUE THREAD

**Issue by pavan2920** [pnp/pnpjs#783]
Hi Team, 

I have recently updated version for "@pnp/sp": "1.3.2".
Now when my code is trying to add webpart in cliendside page it accepts only one parameter of type : IClientSideWebPartData

Trying to give the markup as its in interface. The webpart is getting added but throws error saying something went wrong. 

Can any one help me identifying if something i am missing here. 

 
![image](https://user-images.githubusercontent.com/10346150/61200590-91882200-a6ff-11e9-8618-41261859181e.png)

Please note i am using "8c88f208-6c77-4bdb-86a0-0c47b4316588" to add news webpart. 
Thank you. 
Pavan.

**Comment by patrick-rodgers** [comment]
Can you share the error and also a repo where we can clone and reproduce this issue? Also, please have a [look at the docs](https://pnp.github.io/pnpjs/sp/docs/client-side-pages/#add-client-side-web-parts), generally when adding a web part you will want to start from the definition.

**Comment by patrick-rodgers** [comment]
Going to close this due to inactivity. If this is still an issue please open a new issue and reference this one. Thanks!
