### ISSUE TITLE
SP folder add: use addUsingPath?

### ISSUE THREAD

**Issue by wmertens** [pnp/pnpjs#785]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  latest       ]

Please specify what version(s) of SharePoint you are targeting: [  no idea       ]

### Expected / Desired Behavior / Question

As you know, I want to be able to handle all filenames that sharepoint can handle.

I just discovered that I can't create a folder with an emoji in the name. When I do (I pass the name as an alias after encoding it), it POSTS to the url `https://yaska.sharepoint.com/PROJECT1/_api/web/lists('b2571580-9769-4e45-8fa9-8b580d347f67')/rootFolder/folders/add(@p1)?@p1='to%F0%9F%98%8DHere'`

This creates a folder but the name is shown without the emoji and at the same time it's not possible to create the emoji name from the web interface. So it's the correct name and not the correct name at the same time.

When I create the folder using the web interface, it works just fine. This POSTs to `https://yaska.sharepoint.com/Project1/_api/web/folders/AddUsingPath(DecodedUrl=@a1,overwrite=@a2)?@a1=%27%2FProject1%2FShared%20Documents%2Fto%F0%9F%98%8DHere%27&@a2=false`

and the name shows up with the emoji.

Would it be possible to use AddUsingPath in this library, or would this limit compatibility with older SP versions?

**Comment by patrick-rodgers** [comment]
It can be added, we target SPO.

**Comment by wmertens** [comment]
How about trying it once, and if it fails with 500 set a flag and use the old way? It seems that `/add` is buggy, no?
