### ISSUE TITLE
PDF Blob is returned as octet-stream which I can't convert to Base64. 

### ISSUE THREAD

**Issue by BirudVora** [pnp/pnpjs#786]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.4]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online 2016]

Question:

I want to read a PDF file saved in SharePoint Online using getFileByServerRelativeUrl('').getBlob(). The code works fine but it returns Blob with type: "application/octet-stream". I can't convert content of this Blob to Base64. 

I need the content in Base64 format because in the next step I want to attach this PDF file in the Email I am sending using Microsoft Graph API.

Can you please let me know if there is a way to get Blob content in a correct format?

### Steps to Reproduce
```typescript 
import pnp from "@pnp/pnpjs";
pnp.sp.web.getFileByServerRelativeUrl('/sites/TestAddIn/Shared Documents/Test3.pdf').getBlob()
```

**Comment by patrick-rodgers** [comment]
Are you working in node or a browser?

**Comment by BirudVora** [comment]
Thank you Patrick for looking into this. 

Browser. We are using this code in building SharePoint Web Part running in Chrome or Firefox browsers.

**Comment by patrick-rodgers** [comment]
An internet search [offers this option](https://www.reddit.com/r/learnjavascript/comments/4povjv/converting_octetstream_to_base64/) as one of the first results, you can give it a try.

**Comment by patrick-rodgers** [comment]
Going to close this due to lack of activity. If you still have this issue please open a new issue and reference this one. Thanks!

**Comment by Sagar-SalesforceTechnicalArchitech** [comment]
Hi patrick,
I am still facing same issue. I am not able to convert binary encoded octet to base64. Helping me with this will much appreciated and its urgent in my project
