### ISSUE TITLE
PnPJS "partially" doesnt work in SPFx extension when used via external CDN reference

### ISSUE THREAD

**Issue by gautamdsheth** [pnp/pnpjs#788]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.4]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question

PnP JS should work when used as external CDN reference in an SPFx extension project. 

I am not 100% sure if its PnPJS issue or SPFx issue.

### Observed Behavior

When using PnP JS as external CDN reference in SPFx extension (app customizer), the SP list/library pages kinda freezes. 

The list/lib loses the OOTB command bar menu to add new list item, flow, powerapps etc.

When i open the browser console, i see lots of errors like - `Error: No define call for bgm` etc..

![spfx1](https://user-images.githubusercontent.com/8832018/61380297-ba0e4880-a8c6-11e9-8dcb-2adef04d3698.PNG)

The HTTP request made via PnPJS succeeds as well, so no issue there.

Even the Site contents page is unusable and loses the command bar menu ( ability to add new lists and subsites) 

Strangely, it works perfectly fine on Modern pages.

I followed [this deployment](https://pnp.github.io/pnpjs/documentation/deployment/) guide. 

These are plain, simple and vanilla OOTB list and libraries. No customization via PowerApps. 

When similar code is used in SPFx webparts it works perfectly fine. 

Only in case of SPFx extension i face this issue. If however, i bundle the files and remove external references there are no errors and SP list pages act normally.

### Steps to Reproduce

1) Create an SPFx extension - application customizer. It can be simple NoScript extension. Have targeted SharePoint Online since I am using that only.
2) Install pnpjs libraries 
3) Modify the `config.json` file as below:

```typescript

"externals": {    
    "@pnp/sp": {
      "path": "https://cdnjs.cloudflare.com/ajax/libs/pnp-sp/1.3.4/sp.es5.umd.min.js",
      "globalName": "pnp.sp",
      "globalDependencies": [
        "@pnp/logging",
        "@pnp/common",
        "@pnp/odata",
        "tslib"
      ]
    },
    "@pnp/odata": {
      "path": "https://cdnjs.cloudflare.com/ajax/libs/pnp-odata/1.3.4/odata.es5.umd.min.js",
      "globalName": "pnp.odata",
      "globalDependencies": [
        "@pnp/common",
        "@pnp/logging",
        "tslib"
      ]
    },
    "@pnp/common": {
      "path": "https://cdnjs.cloudflare.com/ajax/libs/pnp-common/1.3.4/common.es5.umd.bundle.min.js",
      "globalName": "pnp.common"
    },
    "@pnp/logging": {
      "path": "https://cdnjs.cloudflare.com/ajax/libs/pnp-logging/1.3.4/logging.es5.umd.min.js",
      "globalName": "pnp.logging",
      "globalDependencies": [
        "tslib"
      ]
    },
    "tslib": {
      "path": "https://cdnjs.cloudflare.com/ajax/libs/tslib/1.10.0/tslib.min.js",
      "globalName": "tslib"
    }

```

4) Modify the extension typescript file as below:

Use the below import statements and require:

```typescript
require("tslib");
require("@pnp/logging");
require("@pnp/common");
require("@pnp/odata");
import { sp } from "@pnp/sp";

```
Add the below code in the onInit method:

```typescript
@override
  public onInit(): Promise<void> {
    Log.info(LOG_SOURCE, `Initialized ${strings.Title}`);

    sp.setup({
      spfxContext: this.context,      
    });  

    let message: string = this.properties.testMessage;
    if (!message) {
      message = '(No properties were provided.)';
    }

    sp.web.select("Title").get().then(r => {
      console.log(r);
    })

    //Dialog.alert(`Hello from ${strings.Title}:\n\n${message}`);

    return Promise.resolve();
  }
```

My `package.json` file is as below:

```typescript
{
  //code omitted for brevity
   ,  
  "dependencies": {
    "@microsoft/sp-core-library": "1.8.2",
    "@microsoft/decorators": "1.8.2",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33",
    "@microsoft/sp-dialog": "1.8.2",
    "@microsoft/sp-application-base": "1.8.2",
    "@pnp/common": "^1.3.4",
    "@pnp/logging": "^1.3.4",
    "@pnp/odata": "^1.3.4",
    "@pnp/polyfill-ie11": "^1.0.2",
    "@pnp/sp": "^1.3.4"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.8.2",
    "@microsoft/sp-tslint-rules": "1.8.2",
    "@microsoft/sp-module-interfaces": "1.8.2",
    "@microsoft/sp-webpart-workbench": "1.8.2",
    "@microsoft/rush-stack-compiler-2.9": "0.7.7",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}

```

5) Clean, Bundle and Package the SPFx solution. Upload it to app catalog 

6) Open any modern SP site. I tested it on communication sites across multiple tenants( both first release and standard releases) and each time the lists/libraries(`AllItems.aspx`) and site contents page(`viewlsts.aspx`) froze, became unusable, lost the OOTB command bar and throws lots of console errors. 

Temporary workaround is to bundle the `pnpjs` files and deploy the solution. But it increases the bundle size. We want to un-bundle it as we are using it across multiple webparts and extensions.

Somehow, there doesn't seem to be a problem in SPFx webparts. It only impacts extensions and that too on the OOTB pages like `AllItems.aspx` and `Viewlsts.aspx`. 

I am not sure whether this is a library issue or SPFx issue.

**Comment by patrick-rodgers** [comment]
Going to close this as resolved by [v2 custom bundles](https://pnp.github.io/pnpjs/concepts/custom-bundle/). You can now easily build and host your own bundles however you need for your needs. This is a much more flexible way than us trying to create bundles to match everyone's needs. Also the v2 update to use dependencies vs peer-deps should help here as well. Thanks!
