### ISSUE TITLE
@pnp/graph missing me/manager where me/directReports is supported

### ISSUE THREAD

**Issue by ArndBrugman** [pnp/pnpjs#790]
The graph (https://developer.microsoft.com/en-us/graph/graph-explorer) supports calls for getting the current users' manager (https://graph.microsoft.com/v1.0/me/manager) and directReports (https://graph.microsoft.com/v1.0/me/directReports).

When using the graph from @pnp there is a call available to get directReports (await graph.me.directReports.get();) but it lacks support for getting manager (?await graph.me.manager.get();?).

This call would be a valuable addition to the graph interface @pnp.

### Category
- [X] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [    1.3.4     ]
Please specify what version(s) of SharePoint you are targeting: [   Sharepoint Online      ]

### Expected / Desired Behavior / Question
I would like to use the same structured calls for getting a users' manager as for directReports.

### Observed Behavior
call for manager on users is missing in @pnp/graph 1.3.4

### Steps to Reproduce
await graph.me.directReports.get();
await graph.me.manager.get(); // <- missing function.

<div>```typescript 
import { graph } from "@pnp/graph";

await graph.me.directReports.get();
await graph.me.manager.get(); // <- missing function.
```</div>

**Comment by ktskumar** [comment]
Hi @patrick-rodgers May I work on it?

**Comment by patrick-rodgers** [comment]
@ktskumar - absolutely! I'll mark this as in progress. Thanks!
