### ISSUE TITLE
Argument of type '{ spfxContext: ListViewCommandSetContext; }' is not assignable to parameter of type 'SPConfiguration'.

### ISSUE THREAD

**Issue by omega1119** [pnp/pnpjs#792]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.4]

Please specify what version(s) of SharePoint you are targeting: [Online]

Hi there,

I've created a ListView Command Extension using this guide

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api

My package.json is:

{
  "name": "bot-listviewcommand",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/decorators": "1.8.2",
    "@microsoft/sp-core-library": "1.8.2",
    "@microsoft/sp-dialog": "1.8.2",
    "@microsoft/sp-listview-extensibility": "1.8.2",
    "@pnp/sp": "^1.3.4",
    "@types/es6-promise": "0.0.33",
    "@types/webpack-env": "1.13.1"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.8.2",
    "@microsoft/sp-tslint-rules": "1.8.2",
    "@microsoft/sp-module-interfaces": "1.8.2",
    "@microsoft/sp-webpart-workbench": "1.8.2",
    "@microsoft/rush-stack-compiler-2.9": "0.7.7",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}

I'm using the @pnp/sp library to write to a field in a selected item, however when I try to build/run the extension I get the following error:

Argument of type '{ spfxContext: ListViewCommandSetContext; }' is not assignable to parameter of type 'SPConfiguration'.

The issue happens in the code below

```typescript 
import { sp } from "@pnp/sp";

sp.setup({
        spfxContext: this.context
      });
```

Thanks

**Comment by koltyakov** [comment]
Looks that in your case `sp.setup` is used in the wrong place and `this.context` is not spfxContext (`SPConfiguration`) but `ListViewCommandSetContext`.
This is not a bug in the library but a wrong initiation. Please follow the documentation notes https://pnp.github.io/pnpjs/documentation/getting-started/#using-pnpsp-setup
Also can recommend taking a look at community samples, e.g. [this one](https://github.com/SharePoint/sp-dev-fx-extensions/blob/5590de43556a5be4884b4a69ee0da8ce8eed90c6/samples/js-command-clone/src/extensions/spfxClone/SpfxCloneCommandSet.ts#L37) with Command Set and PnPjs initialization.
Also, for most of the cases, only baseUrl is actually required, and beeing knowing web absolute url it can be provided to the `sp.setup` or `new Web('ABS_URL')`.

**Comment by omega1119** [comment]
Hi @koltyakov,

thanks for the reply. Apologies I should have been more specific, my onInit looks like this:

public onInit(): Promise<void> {
    console.log("Loading onInit");
    return super.onInit().then(_ => {
      sp.setup({
        spfxContext: this.context
      });
    });
  }

I've followed these examples on other projects but haven't had a problem like this before. Although I was using an older version of pnpjs.

**Comment by koltyakov** [comment]
Could you please post a repository with minimal configuration setup which you use for us to clone and try to reproduce the behavior? Thanks, this can save a lot of time on recreating the issue.

**Comment by omega1119** [comment]
I deleted my node_modules but also included 

"@pnp/common": "^1.3.4",
    "@pnp/logging": "^1.3.4",
    "@pnp/odata": "^1.3.4",

in my package.json and the issue has stopped when I reinstalled the packages. I had only installed "@pnp/sp": "^1.3.4", initially.

**Comment by patrick-rodgers** [comment]
Thanks @omega1119  and @koltyakov , looks like this is resolved. Will close. If you encounter this again, please open a new issue and reference this one. Thanks.
