### ISSUE TITLE
Search PrimaryQueryResults and SecondaryQueryResults

### ISSUE THREAD

**Issue by wills01** [pnp/pnpjs#793]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.3.4      ]

Please specify what version(s) of SharePoint you are targeting: [   Online    ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
When executing sp.search results are not as expected.

RawSearchResults.PrimaryQueryResult return totalRows = 10, however it only returns 8
RawSearchResults.SecondaryQueryResult returns the additional 2 rows that are expected

expected behaviour should be totalrows are confined to the results in each ResultsTableCollection.

### Observed Behavior
Also PrimaryQueryResults is a ResultTableCollection which is correct
but SecondaryQueryResults should be an array of ResultTableCollection as this returns an array and each array is "People" or "Documents by" etc. This seams to be populated when using search terms that include people names,

### Steps to Reproduce
Search for Documents using user name , that are authored

As a workaround, I have concatenated the SecondaryQueryResults array element with PrimaryQueryResults

**Comment by koltyakov** [comment]
That’s how search API works, not on PnPjs’s side.

**Comment by wills01** [comment]
Ok i get that, but surely the SecondaryQueryResults should still be defined as an array of ResultTableCollection, this is in PNPJs side.

**Comment by koltyakov** [comment]
Thanks, @wills01!

Agreed, `SecondaryQueryResults`'s interface should not be a `ResultTableCollection` but an array of `ResultTableCollection`, that's the gap.
