### ISSUE TITLE
Unable to update file metadata using Chunked Method

### ISSUE THREAD

**Issue by ncmadhan1989** [pnp/pnpjs#795]
Unable to update file metadata using Chunked Method

web.getFolderByServerRelativeUrl("/sites/dev/Shared%20Documents/test/").files.addChunked(file.name, file, data => {

            Logger.log({ data: data, level: LogLevel.Verbose, message: "progress" });

        }, true).then(_ => Logger.write("done!"));

i.e.
f.file.getItem().then(item => {

    item.update({
        Title: "A Title",
        OtherField: "My Other Value"
    });
});

kindly provide the sample

**Comment by koltyakov** [comment]
You can chain document creation response with getting the item and updating it.

```typescript
sp.web.getFolderByServerRelativeUrl(folderUri)
    .files.addChunked(filename, data)
    .then(({ file }) => file.getItem())
    .then((item) => {
        return item.update({
            Title: 'A value'
        });
    })
    .then(() => console.log('Bada ba da boom done!'))
    .catch(console.log);
```

P.S. We really encourage [reading docs](https://pnp.github.io/pnpjs/sp/docs/files/#setting-associated-item-values) (👈 isn't it just an identical sample) and asking general development and obvious questions on the forums, but not the issues. And it's a general dev question, IMO, as just a combination of a few straightforward common methods and promises chaining. Thanks!
