### ISSUE TITLE
ClientSidePage.fromFile in SP2019 onPrem incorrect url

### ISSUE THREAD

**Issue by LeeYaoSan** [pnp/pnpjs#797]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.4]

Please specify what version(s) of SharePoint you are targeting: [SP2019 on-prem]

### Expected / Desired Behavior / Question
Getting a client side page in a SPFx webpart.

### Observed Behavior
When getting a client side page using
```typescript 
const list = sp.web.getList(`/SitePages`);
const pageFile = list.items.getById(pageID).file;
const clientsidePage = await ClientSidePage.fromFile(pageFile);
```

As the page is stored in SitePages list, it is trying to load the page from  _http://hostname/SitePages/_api/web/getList('/SitePages')/items(ItemID)/file/listItemAllFields_ instead of _http://hostname/_api/web/getList('/SitePages')/items(ItemID)/file/listItemAllFields_ 

The result is a 404 error:
netutil.ts:53 GET http://hostname/SitePages/_api/web/getList('/SitePages')/items(ItemID)/file/listItemAllFields **404 (Not Found)**

### Steps to Reproduce
In a SharePoint 2019 on premises installation, create a new SPFx web part and try to get a client side webpart using the following:

```typescript 
import { 
  sp,
  ClientSidePage
} from '@pnp/sp';

[…]

const list = sp.web.getList(`/SitePages`);
const pageFile = list.items.getById(pageID).file;
const clientsidePage = await ClientSidePage.fromFile(pageFile);
```

**Comment by patrick-rodgers** [comment]
Have you[ invoked the setup function with the context](https://pnp.github.io/pnpjs/documentation/getting-started/#establish-context)?

**Comment by LeeYaoSan** [comment]
I did, but I made a mistake.

After I corrected the setup invoking everything is working fine now.

Thank you for your help and apologies for the inconvenience

**Comment by patrick-rodgers** [comment]
No worries, glad its working for you!
