### ISSUE TITLE
How to get all lists from the sp.web object

### ISSUE THREAD

**Issue by DaveHaasPowderSoftware** [pnp/pnpjs#799]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.4]

Please specify what version(s) of SharePoint you are targeting: [2019]

### Expected / Desired Behavior / Question

Get all lists from a web (after applying a filter)

### Observed Behavior

Cannot figure out how to do that

### Steps to Reproduce

How do I get all the lists (perhaps after applying a filter) from the lists property of the web object?

All I see are lists.getById() and lists.getByTitle()

There doesn't seem to be just a get() method anymore?

I'm trying to do:

```typescript 
sp.web.lists.filter("(BaseTemplate eq 101) and (Hidden eq false)").select("Title", "ID").get();
```

which I had found on another blog site.

**Comment by patrick-rodgers** [comment]
This should be all you need, nothing has changed. Are you getting an error?

```
const y = await sp.web.lists.get();
```

**Comment by DaveHaasPowderSoftware** [comment]
Well ok, that's bizarre.

I installed 1.3.4 of pnpjs and the .get() method would not show up in VSCode intellisense. I had to back the version all the way to 1.2.9 to get it to appear.

I then uninstalled 1.2.9 and reinstalled 1.3.4 and it started to show up.

Seems to have been a problem with the typescript server.

Sorry about that.

Cheers,

**Comment by patrick-rodgers** [comment]
No worries, glad its working for you now! I sometimes have to close and restart vscode as it seems like the TS processes gets caught up somehow and intellisense ceases to work.
