### ISSUE TITLE
Context / SPFetchClietn breaks when multiple requests come into ExpressJs

### ISSUE THREAD

**Issue by MarkusFeldmann** [pnp/pnpjs#80]
Hi 

- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version 

@pnp/common: "^1.0.4"
@pnp/logging: "^1.0.4"
@pnp/nodejs: "^1.0.4"
@pnp/odata: "^1.0.4"
@pnp/sp: "^1.0.4"

Maybe I am getting it wrong, but shouldn't it be possible to run concurrent requests through the express Middlewares doing something with pnp/sp?
I have a Route that catches POST requests and should ensure a list and add a couple of items. This works perfectly as long, as I only issue one request at a time:

```typescript
sppnp.sp.setup({
  sp: {
    fetchClientFactory: () => {
      return new fc.SPFetchClient(siteUrl, clientId, appSecret);
    },
  },
});

sppnp.sp.web.get().then(w => {
  log.info("[START] CRM Creating metadalist in web %s", siteUrl);
  sppnp.sp.web.lists.ensure('metadata').then(ler => {
    if (ler.created) {
      let batch = sppnp.sp.web.createBatch();
      ler.list.fields.inBatch(batch).addText('DataOwner');
        batch.execute().then(_ => {
        return ler.list.items.add({
          Title: "metadata",
          DataOwner: req.body.DataOwner,
        }).then(_ => {
          log.info("[END] Created metadatalist in web %s", siteUrl);
[...]
```

When I call a similar Route at the same time, that does another one like this (with another siteUrl of course):

```typescript
sppnp.sp.setup({
  sp: {
    fetchClientFactory: () => {
      return new fc.SPFetchClient(siteUrl2, clientId, appSecret);
    },
  },
});

sppnp.sp.web.get().then(w => {
    log.info("[START] Creating metadalist in web %s", siteUrl);
    sppnp.sp.web.lists.ensure('metadata').then(ler => {
      if (ler.created) {
        let batch = sppnp.sp.web.createBatch();
        ler.list.fields.inBatch(batch).addText('DataOwner');
        batch.execute().then(_ => {
          return ler.list.items.add({
            Title: "metadata",
            DataOwner: dataOwner,
          }).then(_ => {
            log.info("[END] Created metadatalist in web %s", siteUrl);
[...]
```

The first request immediately crashes, giving me a 404:

```json
{
  "name": "O365 SiteMaker Express",
  "hostname": "CL150078",
  "pid": 12752,
  "level": 50,
  "msg": "Error in CRM Create metadalist in web ProcessHttpClientResponseException: Error making HttpClient request in queryable: [404] Not Found",
  "time": "2018-04-23T15:57:23.919Z",
  "v": 0
}
```

I experienced the exact same behaviour using the older pnp-js-core libraries.

### Steps to Reproduce

I simply do these two requests, at the same time. The first comes from an Angular App, calling createSite / createlist in sequence. I put a setTimeout between these two, to be able to fire the second request in between this.
The second request comes from a C# cli program, that calls a different API Endpoint that does site creation and list creation one after the other. 
Each of these two run separately, perfectly works.

Did I get something totally wrong or should this be possible?

best regrads,
Markus Feldmann

**Comment by koltyakov** [comment]
Hi @MarkusFeldmann,

Are all the sites the Express app talking shares the same credentials?

By using ```pnp.sp.web``` the lib tries detect a default `baseUrl`, it's more a browser's approach. But even in a browser solution ,it's better using explicit `Web` object initiation with strictly providing web URL.

For instance:

```typescript
import { Web } from '@pnp/sp';

const web = new Web('[web_absolute_url]');
web.get().then(w => {
    log.info("[START] Creating metadalist in web %s", siteUrl);
    web.lists.ensure('metadata').then(ler => {
// [...]
```

This should exclude situations with unpredictable web paths.

Whereas, credentials can't be switched so easily yet this is not important while it's the same clientId/appSecret and the same site collection all the way. Otherwise, with different creds for different methods, `sp.setup({ sp: { fetchClientFactory: () => ... } }` should be called before each physical request (this scenario is not recommended).

Hope this helps.

**Comment by MarkusFeldmann** [comment]
Hi @koltyakov 
Yeah, last night I had a deeper look into the library and found that the approach stores the context globally. So as I am on a schedule I converted the whole thing to to promise based rest. In fact it would be really nice to be able to do it like with C#'s CSOM approach, create a context and simply use it for the request / operation at hand.

anyway: thx
best regards,
Markus

**Comment by koltyakov** [comment]
I guess we could consider potential context-related enhancements or techniques for multi-contextual (different SiteCollections/credentials) tasks in Node.js/server-side scenarios with PnPjs. Especially in case of growing demand.

Meanwhile, I'm going to close this issue as answered. In a situation with the same credentials, creating `new Web('[abs_ur]')` should definitely be the cake.
