### ISSUE TITLE
pnp/sp-clientsvc

### ISSUE THREAD

**Issue by gbminnock** [pnp/pnpjs#800]
### Category
- [x ] Question
- [x ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.3.2     ]

Please specify what version(s) of SharePoint you are targeting: [   online      ]

### Expected / Desired Behavior / Question
I would like to use the @pnp/sp-clientsvc package to utilize functionality not yet supported by the sharepoint rest api. 

I have looked at the taxonomy package but am having difficulty following it. I am not familiar with the ObjectPath/Actions/Methods in use there. 

Maybe the documentation could be enhanced so that I could make use of it. Other documentation in relation to the subject could also be helpful. 

Thank you. 
Gary

**Comment by patrick-rodgers** [comment]
Hi @gbminnock,

The sp-clientsvc library was developed to support the sp-taxonomy library enabling a long desired feature of easy taxonomy access in modern applications. We never had plans to provide a parallel implementation to the REST API through that library and didn't document it heavily (we only wrote it to support the taxonomy work). There are some code comments but not a ton. For version 2 we will be dropping these two libraries as formal REST support for taxonomy is coming (hopefully soon) and we will move to support that. Fully documenting the clientsvc library is not something we can dedicate any time to currently.

Depending on your needs you can let us know what you are trying to do and we can try and help with guidance on how to accomplish that - or if you need to use the CSOM end point (i.e. posting XML bodies) it is likely far easier to handle them as one off methods that post the XML required.

**Comment by gbminnock** [comment]
Hi @patrick-rodgers , thanks for your input on this. I decided to reverse engineer from a CSOM program I created to do the same. Its a bit tricky but I think it will work just as well. It's probably a better option at this point since the client-svc package is being removed.
Thanks again,
Gary
