### ISSUE TITLE
v2 - Delete method not functioning on fields endpoint for lists or web

### ISSUE THREAD

**Issue by juliemturner** [pnp/pnpjs#803]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2]

Please specify what version(s) of SharePoint you are targeting: [SPO]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question

sp.web.fields.getById("<guid>").delete() should remove the field from the site columns
sp.web.lists.getByTitle("Documents").fields.getById("<guid>").delete() should remove the field from the list

### Observed Behavior
Both calls property return the field when calling the .get() method but fail using the .delete() method with the following error:

(node:50156) UnhandledPromiseRejectionWarning: Error: Error making HttpClient request in queryable [400] Bad Request ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"The type SP.FieldCollection does not support HTTP DELETE method."}}}
    at Function.<anonymous> (c:\codePnP\pnpjs\packages\odata\src\errors.ts:11:16)
    at Generator.next (<anonymous>)
    at fulfilled (c:\codePnP\pnpjs\node_modules\tslib\tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

### Steps to Reproduce

```typescript 
// Remove this if you don't have any code sample to provide
import { sp } from "@pnp/sp";
import "@pnp/sp/src/webs";
import "@pnp/sp/src/lists";
import "@pnp/sp/src/fields";

const testFieldSchema = '<Field ID="{060E50AC-E9C1-4D3C-B1F9-DE0BCAC300F6}" \
          Name="Amount" \
          DisplayName="Amount" \
          Type="Currency" \
          Decimals="2" \
          Min="0" \
          Required="FALSE" \
          Group="Financial Columns" />';
const field = await sp.web.lists.getByTitle(listName).fields.createFieldAsXml(testFieldSchema);
await sp.web.fields.getById("060E50AC-E9C1-4D3C-B1F9-DE0BCAC300F6").delete();
```

**Comment by patrick-rodgers** [comment]
I removed the delete method. Not sure if this was a change in the API or we never tested it, but the delete method is not exposed to REST.

**Comment by hafeez1042** [comment]
The delete method was available in v1.x.x, and still, I can use that delete method, 
I didn't get how

> the delete method is not exposed to REST.
