### ISSUE TITLE
Taxonomy addTerm fails when term contains ampersand character

### ISSUE THREAD

**Issue by PatBeaup** [pnp/pnpjs#804]
### Category
- [X] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.4]

Please specify what version(s) of SharePoint you are targeting: [2016]

### Expected
Use the taxonomy **addTerm** function on a value with the ampersand character ("&"), e.g. "Test & Report", and get such term added to the termset.

### Observed Behavior
Use of ampersand character ("&") in taxonomy with **addTerm** function fails.

### Steps to Reproduce
When using the following code, an error is thrown:
```javascript 
const myTerm = "Test & Report";
termSet.addTerm(myTerm, '1033')
```

### Workaround
Replace the & in the term name by `&amp;`, as such:

```javascript 
const myTerm = "Test & Report";
termSet.addTerm(myTerm.replace(/&/g, "&amp;"), '1033')
```

The workaround I suggest will work but that'd be nice if the **addTerm** function could do it itself. Also there might be other characters that cause a similar issue (but I don't have the time right now to look for them, sorry).

**Comment by patrick-rodgers** [comment]
This will go out as part of 1.3.5
