### ISSUE TITLE
Filtering Large Lists

### ISSUE THREAD

**Issue by campuslane** [pnp/pnpjs#806]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

From the documentation for sp list items, what does this mean that the filter operation will likely fail on large lists?  So it's not possible to reliably filter on larger lists?  Is there another way to filter lists then?

````
// we can also use filter as a supported odata operation, but this will likely fail on large lists
sp.web.lists.getByTitle("BigList").items.select("Title").filter("Title eq 'Test'").getAll().then((allItems: any[]) => {

    // how many did we get
    console.log(allItems.length);
});
````

**Comment by koltyakov** [comment]
PnPjs ends up with REST API requests. REST API (as well as other SharePoint APIs) has its limitations. List views/requests threshold is one of them. When working with large lists (more than 5000 items in a view) you must meet certain criteria not to be throttled. See [large lists](https://support.office.com/en-us/article/manage-large-lists-and-libraries-in-sharepoint-b8588dae-9387-48c2-9248-c24122f07c59).

So if the conditions for the API to return data within large lists aren't met REST call fails.

**Comment by Sendil85** [comment]
Hello,
You mean there is no way to get items from large lists with filters?

**Comment by koltyakov** [comment]
The short answer is no. But it depends on some conditions met. If the first part of a filter after being applied individually narrows results to less than a number of view throttling limit and the filter is applied to the indexed column it'll work event in a list with millions of items. Important to note that top condition can't be involved in the equation. Many consider "I'll apply `.top(5000)` and I'm safe", unfortunately, that does not work this way. Alternatively, the search API can be an option. Anyways, lists structure, indexing columns, and how the application is going to be scaled requests-wise with data grows is a topic of planning during app design.

**Comment by Sendil85** [comment]
Thanks for your prompt response. 
I didn't get you,

But it depends on some conditions met. If the first part of a filter after being applied individually narrows results to less than a number of view throttling limit and the filter is applied to the indexed column it'll work event in a list with millions of items.

I have only one filter, that will bring only one result even then it failed, is that how it behaves or am I doing something wrong?
