### ISSUE TITLE
How to update HTML_x0020_File_x0020_Type of Folder

### ISSUE THREAD

**Issue by RoSchoe** [pnp/pnpjs#813]
### Category
- [ ] Enhancement
- [ ] Bug
- [ x] Question
- [ ] Documentation gap/issue

### Expected / Desired Behavior / Question
How to update HTML_x0020_File_x0020_Type of a Folder?
Or how to copy an OneNote file

To copy one folder to other location is not the problem.
But if there is a OneNote file in this folder is shown as folder type after copy and not as OneNote Type.

I tried:
`////folder was copied but is interpreted as folder not as onenote
let folder = sp.web.getFolderByServerRelativeUrl(folderUrl); 

folder.getItem()
     .then(item => item.update({ HTML_x0020_File_x0020_Type: 'OneNote.Notebook' }))
     .then(console.log);`

I think it has to do with HTML_x0020_File_x0020_Type isn't it?
What do i miss?

**Comment by koltyakov** [comment]
This should answer the question I guess https://github.com/SharePoint/PnP-JS-Core/issues/508

**Comment by RoSchoe** [comment]
to use one note api for that standard process/function for files/folders is not what i have expected but 
it seems that at the moment there is no other solution.

Thank you

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Please open a new issue and reference this one if you require additional help. Thanks!

**Comment by RoSchoe** [comment]
brief summary of my solution 
--> solution by using graph API  --> [MSGraphClient](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph)

i used to do a post request to oneNote Graph API to copy oneNotebook

it is possible to use [copyTo](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/notebook-copynotebook.md) method  for sites (Scope)

and then move copied file to destination folder via [item.update ](https://github.com/pnp/pnpjs/issues/68)
