### ISSUE TITLE
Expand Author Field with CAML query

### ISSUE THREAD

**Issue by jonathan-dev** [pnp/pnpjs#818]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.4]

Please specify what version(s) of SharePoint you are targeting: [SP13 on Premise]

### Expected / Desired Behavior / Question
Using the `getItemsByCAMLQuery` method I'm trying to expand the `Author` Field (`list.getItemsByCAMLQuery({ViewXml: xml}, "Author")`).

I was able to expand a File successfully using CAML.
I also found [this](https://github.com/SharePoint/PnP-JS-Core/issues/777#issuecomment-401396837) issue wich might be related.

### Observed Behavior
I'm able to do this when I'm not using CAML but when I'm using CAML I'm getting 400 Bad Request (The $expand query is not valid for field 'Author'.)

### Steps to Reproduce
Try to expand Author field in CAML request

```typescript 
list.getItemsByCAMLQuery({ViewXml: xml}, "Author")
```

**Comment by koltyakov** [comment]
Was discussed many times in the issues here, quick search shows at [least 11 questions](https://github.com/pnp/pnpjs/search?q=getItemsByCAMLQuery&type=Issues) in the issues. Please take a look at [some](https://github.com/pnp/pnpjs/issues/682).

**Comment by patrick-rodgers** [comment]
Closing as answered, thanks!
