### ISSUE TITLE
How to delete a term?

### ISSUE THREAD

**Issue by ellonimo** [pnp/pnpjs#822]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [latest]

Please specify what version(s) of SharePoint you are targeting: [2016]

### Question
Hi. I need to delete a term from term set, but I see no delete/remove method for term object. Via UI I can do this, even more I can delete a term with children. 
Deprecation is less suitable for my current task and can be only a workaround solution.
Does pnp provide delete/remove method for term?

Thank you

**Comment by patrick-rodgers** [comment]
Sure, we can look at adding the delete method.

**Comment by MarianoPrz** [comment]
Hi @patrick-rodgers !, it's look like you've forget to add the type definition for the delete method. It doesn't appear at my solution ( @pnp/sp-taxonomy": "1.3.10" ) neither in SP editor pnp js console. Beyond that the method works accessing like this => term['delete']() where term is an instance of ITerm. Thanks in advance!
