### ISSUE TITLE
SharePoint DatePicker Field empty validation 

### ISSUE THREAD

**Issue by Nagarajan1605** [pnp/pnpjs#825]
Hi,

I am trying to save the sharepoint date picker field. But its not mandatory field. While validation am getting the result of the date picker field as "". But while saving its throwing error.

_Effectivedate=$("#npc-effective-date").val();

$pnp.sp.web.lists.getByTitle("MPPolicyList").items.add({
effectivedate:_Effectivedate;
}):

effectivedate(this is the internal sharepoint column name). This is a date picker field with data type dateandtime.

Please give me some solution

**Comment by patrick-rodgers** [comment]
Can you please share the error you are getting?

**Comment by koltyakov** [comment]
@Nagarajan1605,

Also, can you validate that the value is ISO string (e.g. `2019-08-20T14:14:29.082Z`)?

**Comment by Nagarajan1605** [comment]
Yes. I did that. but i am not selecting any value in that date picker field. So it returns value as "". While save am getting error as primitive value should be checked. EDM.Datetime. Basically "" string value is not accepting in datepicker field.

**Comment by koltyakov** [comment]
So you need to validate the correctness of payload and input data by your own obviously. And provide only supported by the REST API values, etc.

**Comment by sympmarc** [comment]
It sounds like your jQuery line:

_Effectivedate=$("#npc-effective-date").val();

Isn’t getting the value from the date picker, and this isn’t a PnPjs issue at all? If so, your selector probably isn’t right. But I’m not sure what type of date picker you mean.

**Comment by Nagarajan1605** [comment]
I refer the sharepoint date picker column. Datatype is Dateand Time.  But finally i found the solution. 

$pnp.sp.web.lists.getByTitle("MPPolicyList").items.add({
effectivedate:_Effectivedate?_Effectivedate:null;
}):

While retrieving we have to check the same null value so it will convert it into normal string.

**Comment by koltyakov** [comment]
@Nagarajan1605 that’s what you were suggested a few comments before :D But glad you figured out.
