### ISSUE TITLE
PnP SP not running all operations in IE

### ISSUE THREAD

**Issue by antoniobriones** [pnp/pnpjs#828]
Hi, 

I'm running this version of IE: 11.1268.16299.0

The following pnp sp operations do not work in IE (basically, these promises never get resolved, then method is never called and the underlying requests to the SharePoint REST API is never executed):

![image](https://user-images.githubusercontent.com/50162129/63470503-34d8ff00-c443-11e9-9d6f-ba210199efeb.png)

![image](https://user-images.githubusercontent.com/50162129/63470567-5639eb00-c443-11e9-96e2-a65137f992c2.png)

It seems this only happens to some operations. While filtering items from a list doesn't work:

sp.web.lists.getByTitle("SiteOwnerPanelConfig").items.filter('').get().then()

it works if we just get all items (removing filter condition), or get the list. 

This works as expected in Edge, Chrome and other browsers.

Is there any workaround? Thanks

**Comment by patrick-rodgers** [comment]
Have you installed the [polyfill library](https://pnp.github.io/pnpjs/documentation/polyfill/) or are otherwise using polyfills? These are required to patch functionality in IE11.

**Comment by antoniobriones** [comment]
That did it, we were missing the polyfills, thanks!
