### ISSUE TITLE
Can't send email

### ISSUE THREAD

**Issue by Abrissirba** [pnp/pnpjs#829]
# Category
- [ ] Enhancement
- [x ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: 1.3.5

Please specify what version(s) of SharePoint you are targeting: Online

### Expected / Desired Behavior / Question
Trying to send an email with graph.me.sendMail. The sendMail takes a parameter of the type IMessage. If I do that I get a 400 bad request saying that the required parameter Message is missing. Looking at the documentation here, https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=javascript, it looks like the rest endpoint for sendMail should wrap the IMessage inside the following object:
```
{
    message: IMessage,
    saveToSentItems: boolean
}
```

I tried to change the object I passed to sendMail to that format, with as any at the end to make it compile, and then the email was sent.

It feels like the type of the argument that sendMail takes should be changed

**Comment by patrick-rodgers** [comment]
Fixed, will be in 1.3.6

**Comment by patrick-rodgers** [comment]
Fixed this, will be part of 1.3.6 out this Friday.
