### ISSUE TITLE
sp-taxonomy: How to move a Term?

### ISSUE THREAD

**Issue by bkmagnetron** [pnp/pnpjs#831]
### Category
- [x] Enhancement
- [x] Question
- [ ] Bug
- [ ] Documentation gap/issue

I can see that just like #822 there is no option to move a term.
This is a blocker for me in completing a task.
My use case is I have to run a service in AWS that syncs the Terms from another data source.
So, to complete the sync I need to able to Create, Update & Move/Delete a Term.
I have done the Create and Update part.
But I have no idea on how to move a Term.

What are all the alternatives that I currently have?
Some kind of advice will be really helpful.

**Comment by patrick-rodgers** [comment]
The best option would be to use the CSOM libraries for this. For the move operation we need to represent the entire term/termset that would be the new parent in a way we aren't really setup to do easily.

Happy to take a PR if someone wants to work it out.

**Comment by patrick-rodgers** [comment]
Going to close this due to age, happy to take a PR to implement it. Thanks!

**Comment by IlyaOpanyuk** [comment]
Hi, do you have any updates on this issue ? 
This is a blocker for me in completing a task.
My case is create service to make CRUD operations with Terms. 

What are all the alternatives that I currently have?
Would be great if you could give some advices.
