### ISSUE TITLE
sp.profiles.getPropertiesFor(loginName) method not working in IE11

### ISSUE THREAD

**Issue by saiava** [pnp/pnpjs#836]
Hi,
sp.profiles.getPropertiesFor(loginName) method not working in IE11. In chrome& Edge its working fine below is my code:

sp.profiles.getPropertiesFor(userLoginNameResponse.LoginName).then((userProfileData:any)=>{
        return userProfileData;
      })
I tried this one too:
let userProfileData = await sp.profiles.getPropertiesFor(userLoginNameResponse.LoginName) as any;

Thank you
Sai

**Comment by koltyakov** [comment]
Hi @saiava,

Are you sure that you didn't miss all the required [Polyfills](https://pnp.github.io/pnpjs/documentation/polyfill/)?

**Comment by saiava** [comment]
> Hi @saiava,
> 
> Are you sure that you didn't miss all the required [Polyfills](https://pnp.github.io/pnpjs/documentation/polyfill/)?

you mean polyfills for the IE browser.

**Comment by koltyakov** [comment]
Yes, @pnp/polyfill-ie11 package is a simple way of adding polyfills for IE.

**Comment by saiava** [comment]
> Yes, @pnp/polyfill-ie11 package is a simple way of adding polyfills for IE.

Issue Solved!!!
Just now i checked. I haven't added the polyfills for IE. I added now and its working fine now. Thanks koltyakov.
