### ISSUE TITLE
ProviderHostedRequestContext.create throws type error for Secret value

### ISSUE THREAD

**Issue by vamsiabhinav1993** [pnp/pnpjs#844]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [x] Question

### Version

Version of the library used: [ 1.3.5]

version of SharePoint targeted: [Sharepoint online]

### Expected / Desired Behavior / Question
Working on building a sharepoint provider hosted add-in using pnpjs and restify. Desired behaviour is to get user context from the details obtained by the query string.

### Observed Behavior
Not sure if this is an issue. But,  ProviderHostedRequestContext.create throws a type error saying that secret has to be a string or buffer. But, I was trying to test the application by sending hardcoded secret value and yet I face the same error message. 

### Steps to Reproduce
Within restify listener, initiate the setup using sp.setup.
Get spAppToken and spSiteUrl from the request's body.
Create context request object using  ProviderHostedRequestContext.create(spSiteUrl,<client Id hardcoded >,<client Secret hardcoded>,spAppToken)
npm start

```
import { sp, SPRest } from "@pnp/sp";
import { NodeFetchClient, ProviderHostedRequestContext } from "@pnp/nodejs";
import {createServer,plugins} from "restify";

const server = createServer();

const PORT = <desired port value>;

server.use(plugins.queryParser());

server.use(plugins.bodyParser());

server.post('/testUser', async function (req, res, next) {
sp.setup({
        sp: {
            fetchClientFactory: () => {
                return new NodeFetchClient();
            },
        },
    });

const spAppToken = req.body.SPAppToken;
    const spSiteUrl = req.body.SPSiteUrl;
    
    console.log("AppToken: " + spAppToken);
    console.log("SiteUrl: " + spSiteUrl);
    console.log(req.body);

const ctx = await ProviderHostedRequestContext.create(spSiteUrl, <hardcoded Client Id>, <hardcoded client secret>, spAppToken);
}
```

**Comment by patrick-rodgers** [comment]
Had a look and I am not able to recreate this with the information provided. The only line I can think would be a problem is:

```TypeScript
const secret = Buffer.from(clientSecret, "base64");
```

But if you are passing a string that should be fine. Unless something is happening within the jwt library - are you able to debug a little deeper and help us hunt down the error?

**Comment by patrick-rodgers** [comment]
Going to close this due to inactivity. If you continue to have an issue here please open a new issue, reference this one, and let us know you are still having trouble. Thanks!
