### ISSUE TITLE
sp.site.createCommunicationSite not working properly in Azure Function

### ISSUE THREAD

**Issue by parmira5** [pnp/pnpjs#847]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.3.5     ]

Please specify what version(s) of SharePoint you are targeting: [    SPO    ]

### Expected / Desired Behavior / Question
Should provision SPO communication site with parameters passed in.

### Observed Behavior
Returns:
`{
  "d": {
    "Create": {
      "__metadata": {
        "type": "Microsoft.SharePoint.Portal.SPSiteCreationResponse"
      },
      "SiteId": "",
      "SiteStatus": 3,
      "SiteUrl": ""
    }
  }
}`

And no communication site is created.

### Steps to Reproduce
Create a new Azure HTTPTrigger Function
npm install all necessary libraries

```javascript
var sp = require('@pnp/sp').sp;
var SPFetchClient = require('@pnp/nodejs').SPFetchClient;

let siteURL = 'https://mytenant.sharepoint.com'
let sitesPath = 'https://mytenant.sharepoint.com/sites/'
let clientId = 'omitted';
let clientSecret = 'omitted';

sp.setup({
    sp: {
        fetchClientFactory: () => {
            return new SPFetchClient(siteURL, clientId, clientSecret);
        },
    },
});

module.exports = async function (context, req) {

    context.log('JavaScript HTTP trigger function processed a request.');

    if ( req.body && req.body.projectName && req.body.projectOraseq && req.body.projectManager ) {
        let {projectName, projectOraseq} = req.body;
        const s = await sp.site.createCommunicationSite(
            projectName,
            1033,
            false,
            `${sitesPath}${projectOraseq}`,
        );

        context.res = {
            
            // status: 200, /* Defaults to 200 */
            body: s

        };
    }
    else {
        context.res = {
            status: 400,
            body: "Please pass a name on the query string or in the request body"
        };
    }
};
``

**Comment by gautamdsheth** [comment]
Hi @parmira5, since you are in App-only context, you also need to set the owner. This parameter is supported in pnpjs, just set its value and your function should work.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Thanks all!
