### ISSUE TITLE
How to return the data as Observable in SPFx

### ISSUE THREAD

**Issue by spvjebaraj** [pnp/pnpjs#849]
Team,

I am working in SPFx with React along with PnP JS. I want to return the output as Observable<MyModel[]>. I have installed the rxjs library in my project and I used the below code. But it is not working. I used the same code in Angular, it is working.

`public getListItemDetails<T>(
    listTitle: string,
    selectedFields: string,
    orderBy: string
  ): Observable<T[]> {
    return from(
      sp.web.lists
        .getByTitle(listTitle)
        .items.select(selectedFields)
        .orderBy(orderBy)
    ).pipe(
      map((res: T[]) => {
        return res.map(item => {
          return item;
        });
      })
    );
  }`

I am calling the above method from the separate file as below.
`public getAssetType(): Observable<IAssetType[]> {
    const listTitle = "Asset Type";
    const selectedFields = "ID, Title";
    const orderBy = "Title";
    return this.commonService.getListItemDetails<IAssetType>(
      listTitle,
      selectedFields,
      orderBy
    );
  }`

Finally I am calling the method from WebPart.tsx file as below.
`this.commonService.getAssetType().subscribe(
      response => {
        if (response !== null) {
          console.log(response);
        }
      },
      error => console.log("Error: ", error),
      () => console.log("Done")
    );`

I am getting the error like below.
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

When I do the mouse hover on "from" keyword, it shows as Observable<'unknown'> in SPFx project. But when I do the same in Angular project, it shows as Observable<MyModel[]>.

Please help me on this.

**Comment by koltyakov** [comment]
Hey @spvjebaraj,

Looks like you piping not a Promise value:

![image](https://user-images.githubusercontent.com/7816483/65036281-c741c500-d953-11e9-849c-bba9e13210ad.png)

**Comment by spvjebaraj** [comment]
Hi Andrew,

Thanks for the quick response. It's working like charm. Why it is differ from Angular? Kindly share the details.

Thanks

**Comment by koltyakov** [comment]
There is no difference, from/pipe deals with `Observable, Promise, Array, or Iterable`, however, you provided not a Promise but `SharePointQueryableCollection` instance.

**Comment by spvjebaraj** [comment]
Thanks Andrew. One more thing, I used the below code in Angular it is working. If I use it in SPFx, am getting the syntax error "Type 'Observable<'unknown'>' is not assignable to type 'Observable<T[]>'".

`public getListItemDetails<T>(
    listTitle: string,
    selectedFields: string,
    orderBy: string
  ): Observable<T[]> {
    return from(
        sp.web.lists
          .getByTitle(listTitle)
          .items.select(selectedFields)
          .filter(filter)
          .orderBy(orderBy)
          .get<T[]>()
      );
}`

Any idea on this?
