### ISSUE TITLE
How to add new item using PnP JS with return type of Observable<ItemAddResult>

### ISSUE THREAD

**Issue by spvjebaraj** [pnp/pnpjs#851]
Hi Team,

I am working in SPFx with React along with PnP JS. In that am using the Observables (RxJS libraries) to handle asynchronous operations. I am using the below code to add new items to the list. But I am getting the syntax error as "Type 'Observable<'unknown'>' is not assignable to type 'Observable<'ItemAddResult'>'". But it is working in Angular project.

`public postDataToList(
    listTitle: string,
    contents: any
  ): Observable<ItemAddResult> {
    return from(
      sp.web.lists
        .getByTitle(listTitle)
        .items.add(contents)
        .then((result: ItemAddResult) => {
          return result;
        })
    );
  }`

Kindly help me on this.

**Comment by koltyakov** [comment]
Going to close this as a not library-related question. You can always post on the [Microsoft Tech Community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) for suggestions around general coding practices.
