### ISSUE TITLE
super.onInit() errors "error TS2339: Property 'onInit' does not exist on type 'Component"

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpjs#852]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version SPFx 1.9.1

Please specify what version of the library you are using: [    ^1.3.5     ]

Please specify what version(s) of SharePoint you are targeting: [    Online     ]

### Expected / Desired Behavior / Question
gulp serve with no errors

### Observed Behavior
error TS2339: Property 'onInit' does not exist on type 'Component<IPnpUploadProps, {}, any>'.
[16:56:05] Error - 'tsc' sub task errored after 4.92 s
 exited with code 2
[16:56:06] Finished subtask 'tslint' after 7.56 s

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

```typescript 
// Remove this if you don't have any code sample to provide
import { sp } from "@pnp/sp"
export default class PnpUpload extends React.Component<IPnpUploadProps, {}> {
  public onInit(): Promise<void> {
    return super.**onInit()**.then((_: any) => {
      // other init code may be present
      sp.setup({
        spfxContext: this.context
      });
    });
  }
```
There is lint error on super.**onInit()**
Did I put the code from the example in the wrong place?

**Comment by patrick-rodgers** [comment]
onInit is specific to SPFx and is there when you inherit from the SPFx stack. If you are just using a React component you wouldn't have that method to override. You would need to place the setup code somewhere within your project where it will be run once on each page load per closure.

**Comment by Ofer-Gal** [comment]
It did not complain when I put it in the PnpUploadWebPart extends BaseClientSideWebPart class
But then how do I refer to it (spfxContext) in the component itself?

**Comment by Ofer-Gal** [comment]
Also, the documentation for upload in  https://pnp.github.io/pnpjs/sp/docs/files/  Adding Files is a bit confusing maybe because of jQuery.
How would I do it in the react component? (I have the files with @progress/kendo-react-upload )
Is there an example to upload files within SPFx using Graph? (@pnp/graph)

Is it correct to assume everything related to node.js in the documentation does not relate to SPFx? 
Thank you for your tolerance with me :-)

**Comment by juliemturner** [comment]
I do the onInit thing all the time. Not sure why you're using the return super.... so I can't speak to that.

For Example: 

```typescript
public async onInit(): Promise<void> {
    //Initialize PnPLogger
    Logger.subscribe(new ConsoleListener());
    Logger.activeLogLevel = LogLevel.Info;
    //Initialize PnPJs
    sp.setup({
      spfxContext: this.context
    });
    this.render();
}
```

@Ofer-Gal -- I'd suggest, to get the best response, it would be better if post your second question as a new issue.

**Comment by Ofer-Gal** [comment]
The  the return super.... is from the example in https://pnp.github.io/pnpjs/documentation/getting-started/  Using @pnp/sp setup.
I will try it your way
Thank you much

**Comment by AdiuTankT72** [comment]
I have the same problem. I did set up in onInit of the class that extends BaseClientSideWebPart but when I am trying to use sp.something in the React.Component then the sp is not initialized correctly as it builds URLs with /SitePages/ in the URL. So... using sp.something in my webpart works fine but inside my react component in this web part it builds wrong URLs. How I can setup sp object in the react component?

**Comment by koltyakov** [comment]
Once SPFx context is established PnPjs know where to send requests exactly. So it's a must-have configuration in SPFx solutions.

**Comment by AdiuTankT72** [comment]
I understand so why it is not working correctly? 
I have in my webpart:
`protected onInit() : Promise<void>
  {
    sp.setup({spfxContext: this.context});
    return super.onInit();
  }`
and all requests to SP works correctly. But I have also a React.Component rendered by this webpart and inside it SP requests are formatted wrongly. I have tried to add sp.setup to  public render(): React.ReactElement<IShowListDataProps> but it does not help.

**Comment by koltyakov** [comment]
sp.setup is global. Once it's configured any web part or React components with effects that use API calls are configured with the same context. Maybe something reconfigures the context after it's originally initiated or an API call happens earlier the context was actually established. Hard to say anything without a reproducible sample.
In most cases, the only thing from the context which really makes sense is the web absolute URL. With web absolute URL it's handy to construct a web object like `const web = Web('web_abs_url')` and then use it as an API entry point.

P.S. Please start a new issue rather than commenting on a closed one, closed issues are not overviewed and mostly not visible.
