### ISSUE TITLE
Only getting 1000 user from graph

### ISSUE THREAD

**Issue by Savanoop95** [pnp/pnpjs#853]
Only the first 1000 users are getting by using the graph from @pnp.
Is there any way to get more than 1000 users?

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.3.5        ]

Please specify what version(s) of SharePoint you are targeting: [ Sharepoint Online        ]

### Expected / Desired Behavior / Question
Only the first 1000 users are getting by using the graph from @pnp.
Is there any way to get more than 1000 users?

### Observed Behavior
Only the first 1000 users are getting by using the graph from @pnp.

### Steps to Reproduce

```typescript 
// Remove this if you don't have any code sample to provide
import { graph } from "@pnp/graph";
graph.users.top(999).get();
```

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
You are limiting the query to 999 users using top - so that is likely why you are getting 1000 back. If the graph api only gives you 1000 you can use skip with top to get pages of data.

**Comment by rmbw74** [comment]
How do you get the skipToken? it looks like pnp returns only the value?

**Comment by Savanoop95** [comment]
you can't use skip in @pnp/graph, you can get the nextUrl by passing new JSONParser() in the get() as a parameter

**Comment by patrick-rodgers** [comment]
Closing this as answered, Thanks!
