### ISSUE TITLE
Unable to use SPFetchClient from Angular 8 app

### ISSUE THREAD

**Issue by gianespo** [pnp/pnpjs#854]
I'm trying to use the SPFetchClient to query data on a SharePoint Server 2016 from an Angular 8 app. I followed the steps described in the PnP JS documentation: https://pnp.github.io/pnpjs/nodejs/docs/sp-fetch-client/ but when I run `ng build` or `npm start` I get the following error:

`ERROR in ../../node_modules/adal-node/lib/adal.d.ts:1:23 - error TS2307: Cannot find module 'http'.`
`1 import * as http from "http";`

How I can solve this?

### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.5]

Please specify what version(s) of SharePoint you are targeting: [2016]

### Expected / Desired Behavior / Question
The expected behavior is that I'm able to run `ng build` or `npm start` to build the code and run it. One running the code should be able to connect to the specified SharePoint site and query data as requested.

### Observed Behavior
Unable to build and run the code.

### Steps to Reproduce
Following the steps to reproduce the bug:

1. Create a new Angular 8 project.
2. Create a service and add the following code to it:

```typescript 
import { sp } from '@pnp/sp';
import { SPFetchClient } from '@pnp/nodejs';

export class SharepointService {

  constructor() { }

  public getPages() {
    sp.setup({
      sp: {
        fetchClientFactory: () => {
          return new SPFetchClient('<siteUrl>', '<cliendId>', '<clientSecret>');
        }
      }
    });
    sp.web.lists.getByTitle('Pages').rootFolder.files.get().then(files => {
      console.log(files);
    }).catch(e => {
      console.error(e);
    });
  }
}
```

3. Run `npm start`

**Comment by koltyakov** [comment]
@gianespo,

We predicted this and created API proxy.
For this scenario please take at https://github.com/koltyakov/sp-rest-proxy project.

**Comment by gianespo** [comment]
It looks like what I need, I will try it!
Thanks
