### ISSUE TITLE
How to retrieve Multiple Users from User Profile using PnP JS

### ISSUE THREAD

**Issue by spvjebaraj** [pnp/pnpjs#855]
Hi Team,

I am working in SPFx project along with PnP JS library. I am using the below code to fetch the user profile properties for the given user. It's working fine without any issue. How to filter the user based on the email address while typing in texbox (like auto suggest). In REST API, we can use substringof to pass the value to filtered the results from list. How to do it in PnP JS for filtering the multiple users.

`sp.profiles.getPropertiesFor(accountName)`

Thanks in advance

**Comment by koltyakov** [comment]
Hi @spvjebaraj, `clientPeoplePickerSearchUser` method is what you need.

**Comment by spvjebaraj** [comment]
Thanks Andrew. Now am able to get the multiple users. In that results, I am unable to get the Profile Picture. How to get the Picture URL? Could you please share your thoughts.

**Comment by koltyakov** [comment]
The picture should be retrieved based on the platform you're, for SPO and On-Prem it's different. Also, there are 100500 different ways of getting a profile image, and I don't know the one to be universal. E.g. `https://outlook.office365.com/owa/service.svc/s/GetPersonaPhoto?email=usernale@contoso.onmicrosoft.com&UA=0&size=HR96x96` should work well for SPO.

**Comment by spvjebaraj** [comment]
Thanks Andrew. I will use the above approach to get the profile picture.

Thanks a lot for your help.

**Comment by koltyakov** [comment]
Cheers!
