### ISSUE TITLE
Date Range with multiple dates comparison spfx

### ISSUE THREAD

**Issue by parthaj** [pnp/pnpjs#856]
Hi Team,

We are developing spfx application, where the user is allowed to enter multiple dates or the date range in date field. We need to use it to compare the dates with the dates(start dates & end dates) provided in the filter condition and list down only the matching items between start and end dates. Please advise on the approach of storing the dates in sharepoint lists and on the comparison.

Thanks,

**Comment by koltyakov** [comment]
The question is not related to the library or API, but a general development and design question. We encourage asking such in tech community or other online forums.
