### ISSUE TITLE
How to get the multiline column value which has append text property set true.

### ISSUE THREAD

**Issue by craghavendra21** [pnp/pnpjs#859]
### Category
- [x ] Question

### Expected / Desired Behavior / Question
I have a multiline column named as "Notes" in a list. This column has the "append text" property set to true.
So when I retrieve the item I am getting this column null value. Please help me query this.

  ```
    let list = web.lists.getByTitle("Sample List");
    let listItem = list.items.getById(1).select("Title", "Notes");
    listItem.get();
```

**Comment by koltyakov** [comment]
Hi @craghavendra21, you should get versions and combine such field values. Append text is based on versioning.
