### ISSUE TITLE
folder.moveTo() throws Microsoft.SharePoint.Client.ResourceNotFoundException

### ISSUE THREAD

**Issue by abiargenuvolsistemas** [pnp/pnpjs#863]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.3.5      ]

Please specify what version(s) of SharePoint you are targeting: [   Sharepoint Online      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
sp.web.getFolderByServerRelativeUrl("/sites/....").moveTo(".....") should move a folder into a target destination.

### Observed Behavior
moveTo() method resolves Promise with the following error: 
{ 'odata.error':
   { code: '-1, Microsoft.SharePoint.Client.ResourceNotFoundException',
     message:
      { lang: 'es-ES',
        value: 'No se encuentra el recurso para la solicitud _api.' } } }
(in English would be something like: "resource not found for the _api request"

### Steps to Reproduce
``` javascript
 sp.setup({
    sp: {
      fetchClientFactory: () => {
        return new SPFetchClient("{site_url}", "xxxx", "xxx", SPOAuthEnv.SPO );
      },
    },
  })
sp.web.getFolderByServerRelativeUrl("{source_folder_relative_url}").moveTo("{target_folder_relative_url}")
  .then( (result) => {
    console.log(result)
  })
  .catch( (err) => {
    console.error(err);
  })
````
sp.web.getFolderByServerRelativeUrl("...").get() works fine and returns the correct folder. 

I've also tried to add() a dumb folder to the target document library and that works fine as well.

Also would like to know if the moveTo() method would work with Document Sets as well.

Thank you in advance!

**Comment by patrick-rodgers** [comment]
Fixed this, will be part of 1.3.6 out this Friday.
