### ISSUE TITLE
Anonymous access - ClientSidePage.fromFile(...) - 401 Error

### ISSUE THREAD

**Issue by FlamingFox911** [pnp/pnpjs#864]
### Category
- [X] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 1.3.5

Please specify what version(s) of SharePoint you are targeting: 2019 On-Premise

### Expected / Desired Behavior / Question
I am developing a custom breadcrumb SPFx, and I am required to put the title of the page in the breadcrumb (since this helps for multilingual translations). The process I have works when I am logged in. However, this process does not work when I am accessing it as an **_anonymous_** user. I would also like to clarify that the anonymous user is able to successfully get the File from the path specified in the "Steps to Reproduce".

How can I obtain the title of the ClientSidePage as an anonymous user? Can it be done, or is there another way of getting it?

### Steps to Reproduce
Perform necessary setup for SPRest. I have done it in the constructor of the component:
```typescript
sp.setup({
  spfxContext: this.state.context
});
```
Run the code below:
```typescript 
// path = '/subsite/SitePages/A-Page.aspx';
private async getTitle(path: string): Promise<string> {
  let page: ClientSidePage;
  try {
    page = await ClientSidePage.fromFile(sp.web.getFileByServerRelativeUrl(path)); //Error happens here
  } catch (error) {
    console.error(error);
  }
  if (page && page.title) {
    return page.title;
  } else {
    // Failed to get title, use fallback.
  }
}
```
After a few canceled prompts to login, I get the following error message.
```
Error making HttpClient request in queryable [401] Unauthorized ::> {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access denied. You do not have permission to perform this action or access this resource."}}}
    at new HttpRequestError (parsers.ts:13)
    at parsers.ts:19
```

**Comment by koltyakov** [comment]
Hi @FlamingFox911,

The path should be a correct relative URL.
E.g. if the page address is `https://contoso.sharepoint.com/sites/site/subsite/SitePages/A-Page.aspx`, the relative URL should be `/sites/site/subsite/SitePages/A-Page.aspx`.

The other thing, 401 is unauthorized server response, but it's likely because of the incorrect URL which is provided to the API.

Anyways, this doesn't look as an issue with the library.

**Comment by FlamingFox911** [comment]
Hi. Just getting back to say thank you for your suggestions, but the problem was not getting the file as I explained here:

> I would also like to clarify that the anonymous user is able to successfully get the File from the path specified in the "Steps to Reproduce"

I have, however, resolved this issue. After experimenting with REST API calls from the browser I have found the field I am looking for. I didn't have to change much from my original code:
```typescript
private async getTitle(path: string): Promise<string> {
  // ... Some early static path checks
  let v: any = await sp.web.getFileByServerRelativePath(path).get();
  if (v && v.Title) {
    // We have a title
    return v.Title;
  } else {
    // Fallback (use filename from path instead)
    const crumb: string[] = path.split('/');
    return crumb[crumb.length - 1];
  }
}
```
Thanks again.
