### ISSUE TITLE
Is sp.profiles.setSingleValueProfileProperty support SharePoint 2019?

### ISSUE THREAD

**Issue by RogerZhang-CatapultSystems** [pnp/pnpjs#868]
Is sp.profiles.setSingleValueProfileProperty support SharePoint 2019?  When I call sp.profiles.setSingleValueProfileProperty against SharePoint 2019, there have no error in the response, but the property value didn't update? I want to confirm with you, whether the API support SharePoint 2019

**Comment by KEMiCZA** [comment]
I just check the _api/$metadata endpoint on a SharePoint 2019 farm and it seems it's supported:
![image](https://user-images.githubusercontent.com/3862716/66390538-2c289200-e9cb-11e9-84d7-bab1e5230a8a.png)

Not sure what's going wrong. Maybe check the ULS logs if you have access to those?

**Comment by RogerZhang-CatapultSystems** [comment]
Below log may be the root cause for the API calling, but not sure how to make ProfilePropertiesCSOM flight enabled, please give me advices, great thanks.

10/08/2019 05:02:15.24 	w3wp.exe (0x2B08)                       	0x24C0	SharePoint Portal Server      	User Profiles                 	aw2z4	Medium  	**ProfilePropertiesCSOM flight is enabled : False**	c7d60b9f-201e-506e-9b48-2676e959befb

10/08/2019 05:02:15.24 	w3wp.exe (0x2B08)                       	0x24C0	SharePoint Portal Server      	User Profiles                 	aw2zm	Medium  	PeopleManager.SetSingleValueProfileProperty(accountName=FUSESP2019 usespadmin,propertyName=MyLinks) - **Profile Write CSOM Flight is not enabled**.	c7d60b9f-201e-506e-9b48-2676e959befb

**Comment by KEMiCZA** [comment]
It might be a limitation of SharePoint onpremise in this case. Even though the method is available, I suspect it will only work in SharePoint Online. I'm not sure if we can fall back to _vti_bin/userprofileservice.asmx to achieve this.

**Comment by patrick-rodgers** [comment]
This appears to be a limitation in SP2019 on prem. Sorry, not much we can do to help out on this one.

**Comment by mgwojciech** [comment]
Hi,
I had the same issue and switched to old endpoint.
Here is a post how to wor around that:
https://czlowiek-sharepoint.blogspot.com/2019/11/sharepoint-onprem-2019-update-user.html
