### ISSUE TITLE
How to set context for pnpjs in Service ?

### ISSUE THREAD

**Issue by kmprasad4u** [pnp/pnpjs#869]
How can we set the spfxContext when we use pnpjs in a service layer. 

In service classes we normally use serviceScope to get all the required dependencies. Through serviceScope.consume(PageContext.serviceKey) we can only get reference to this.context.pageContext, where as spfxContext requires this.context to be passed. Is it possible to get this.context via serviceScope.consume ? If not, are there any other ways to set the spfxContext. 

PS: We are trying to use library components for services classes and CDN for loading PnPJs. 

### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.3]

Please specify what version(s) of SharePoint you are targeting: [Sharepoint Online]

**Comment by patrick-rodgers** [comment]
Can you share a repo we can clone showing what you are trying to do?

**Comment by kmprasad4u** [comment]
I will get a repo ready in some time...

**Comment by kmprasad4u** [comment]
@patrick-rodgers 
Sorry I forgot raising the question.
Here is a sample
https://github.com/kmprasad4u/SPFx-Library-Service-Sample

**Comment by kmprasad4u** [comment]
@patrick-rodgers
Any suggestions ?

**Comment by patrick-rodgers** [comment]
Hi @kmprasad4u - sorry for delay, been a busy period for me. Thank you for the example - yes your workaround is perfectly valid and I think is probably the easiest way to move forward. If you look at the source we do what you are doing (read the url) but your use the baseUrl overrides that and uses the value you specify. At the end of the day the same thing is happening.

I wasn't aware you could only get the page context in this scenario so this is something we should put in the getting started docs. Thanks!

**Comment by patrick-rodgers** [comment]
[Here is the link to the updated docs](https://github.com/pnp/pnpjs/blob/dev/packages/documentation/getting-started.md#establish-context-with-an-spfx-service)

**Comment by kmprasad4u** [comment]
Thanks for the clarification :)
