### ISSUE TITLE
pnp.sp.profiles.myProperties.get() has a wrong URL - 404 error

### ISSUE THREAD

**Issue by eariel** [pnp/pnpjs#872]
Category
- [ ] Enhancement
- [] Bug
- [ ] Question
- [X] Documentation gap/issue

 Version 

@pnp/pnpjs: version 1.3.5
SharePoint Online with framework 1.8.2

I have an extension to collect data from user and page information and send it to Analytics application.
This extension has been working fine, but for some reason I don't know, the request URL  has changed and I receive a 404 error.

Steps to reproduce:

Is a simple application extension with few lines of code:

private static async getUserProfileProperties(): Promise<any> {
    
    return pnp.sp.profiles.myProperties.get();
  }

public onInit(): Promise<void> {
    
    pnp.setup({
      spfxContext: this.context
    });
// more stuff here

 AnalyticsInjectorApplicationCustomizer.getUserProfileProperties().then(data => {
      data.UserProfileProperties.forEach(function(property) {
           // iterate the properties here and do something with them
      })
})

}

checking the error, I can see that the reques URL has changed and now is including "/SitePages/"

https://<tenantUrl>/sites/<sitename>/**SitePages**/_api/sp.userprofiles.peoplemanager/getmyproperties

I have no idea what has changed, as I said, this has been working fine until few days ago. If I paste the request URL removing "SitePages" I can see that some information is returned, but not sure if the main issue is that.

Any help will be appreciated,

Thanks!

**Comment by KEMiCZA** [comment]
What's your import declaration for the **pnp** object like?

See the following documentation on how to correctly setup your SPFx context: https://pnp.github.io/pnpjs/documentation/getting-started/

Try the following:

```typescript
import { sp } from "@pnp/sp";
...

@override
public onInit(): Promise<void> {
  return super.onInit().then(_ => {
    sp.setup({
      spfxContext: this.context
    });

    getUserProfileProperties().then(x => ...);

  });
}
```

**Comment by KEMiCZA** [comment]
I've also noticed you're using the pnpjs package. AFAIK you shouldn't be using this library/package, as stated in the documentation: https://github.com/pnp/pnpjs/blob/dev/packages/pnpjs/docs/index.md

Try installing and using the default packages:
```
npm install @pnp/logging @pnp/common @pnp/odata @pnp/sp @pnp/graph --save
```

**Comment by eariel** [comment]
Sorry, I forgot to provide that line.
My declaration for pnp is:

import * as pnp from '@pnp/pnpjs';

**Comment by patrick-rodgers** [comment]
Can you share a repo we can clone and see this issue? It is very much that the context or url is not getting set correctly. There hasn't been a change in the library around this functionality so likely something was updated within your application.

**Comment by eariel** [comment]
My first attempt to work with this library was using this example:
https://www.c-sharpcorner.com/article/retrieve-user-profile-properties-using-spfx-and-pnp-js-in-sharepoint-online/ 


I've customized this solution and now I have the same issue. @patrick-rodgers  as you said, I'm not sure if something has changed, but not in my solution, I'm thinking something at tenant level, like profile or security configuration.. but no idea what kind of change can produce this behaviour.

[Custom_getuserproperties.zip](https://github.com/pnp/pnpjs/files/3718002/Custom_getuserproperties.zip)

Thanks

**Comment by patrick-rodgers** [comment]
The wrong url is for sure because something isn't getting setup correctly, i.e. with the placement of the setup function. If I test the method you are trying to use it works as expected - so this is something to do with your solution. Can you post the code in a repo? Downloading and extracting a random zip file isn't my favorite way to work, nothing personal.

**Comment by KEMiCZA** [comment]
@eariel the zip you provided contains no setup code for PnPjs in the **GetUserProfilePropertiesWebPart.ts** file? Also you said it's an application customizer, but the code you provided is a webpart.

For reference this is the code from the **GetUserProfilePropertiesWebPart.ts** file:

```typescript
import { Version } from '@microsoft/sp-core-library';
import * as pnp from 'sp-pnp-js';
import { BaseClientSideWebPart } from '@microsoft/sp-webpart-base';
import {
  IPropertyPaneConfiguration,
  PropertyPaneTextField
} from '@microsoft/sp-property-pane';
import { escape } from '@microsoft/sp-lodash-subset';

import styles from './GetUserProfilePropertiesWebPart.module.scss';
import * as strings from 'GetUserProfilePropertiesWebPartStrings';

export interface IGetUserProfilePropertiesWebPartProps {
  description: string;
}

export default class GetUserProfilePropertiesWebPart extends BaseClientSideWebPart<IGetUserProfilePropertiesWebPartProps> {


  private GetUserProperties(): void {

    pnp.sp.profiles.myProperties.get().then(function (result) {
      var userProperties = result.UserProfileProperties;
      var userPropertyValues = "";
      userProperties.forEach(function (property) {
        userPropertyValues += property.Key + " - " + property.Value + "<br/>";
      });
      document.getElementById("spUserProfileProperties").innerHTML = userPropertyValues;
    }).catch(function (error) {
      console.log("Error: " + error);
    });

  }

  public render(): void {
    this.domElement.innerHTML = `
     <div class="${styles.helloWorld}">
  <div class="${styles.container}">
    <div class="ms-Grid-row ms-bgColor-themeDark ms-fontColor-white ${styles.row}">
      <div class="ms-Grid-col ms-u-lg10 ms-u-xl8 ms-u-xlPush2 ms-u-lgPush1">
        <span class="ms-font-xl ms-fontColor-white" style="font-size:28px">Welcome to SharePoint Framework Development using PnP JS Library</span>
        
        <p class="ms-font-l ms-fontColor-white" style="text-align: left">Demo : Retrieve User Profile Properties</p>
      </div>
    </div>
    <div class="ms-Grid-row ms-bgColor-themeDark ms-fontColor-white ${styles.row}">
    <div style="background-color:Black;color:white;text-align: center;font-weight: bold;font-size:18px;">User Profile Details</div>
    <br>
<div id="spUserProfileProperties" />
    </div>
  </div>
</div>`;
    this.GetUserProperties();
  }


  protected get dataVersion(): Version {
    return Version.parse('1.0');
  }

  protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: [
            {
              groupName: strings.BasicGroupName,
              groupFields: [
                PropertyPaneTextField('description', {
                  label: strings.DescriptionFieldLabel
                })
              ]
            }
          ]
        }
      ]
    };
  }
}

```

**Comment by eariel** [comment]
> The wrong url is for sure because something isn't getting setup correctly, i.e. with the placement of the setup function. If I test the method you are trying to use it works as expected - so this is something to do with your solution. Can you post the code in a repo? Downloading and extracting a random zip file isn't my favorite way to work, nothing personal.

https://github.com/eariel/GetUserProfileTestWP

**Comment by eariel** [comment]
@KEMiCZA  yes, I've provided a webpart because my extension is part of a project with other componentes and some sensitive information about my client... I don't want to change that project to remove or change that.

This webpart was my first contact with the pnpjs library, and I used this simple example to test the method, and it worked fine!

Right now, both (extension and webpart) have the same behaviour (same error 404).

I've uploaded the sample webpart to this repository too 

https://github.com/eariel/GetUserProfileTestWP 

Thanks!

**Comment by patrick-rodgers** [comment]
The [webpart code you posted](https://github.com/eariel/GetUserProfileTestWP/blob/master/getuserproperties/src/webparts/getUserProfileProperties/GetUserProfilePropertiesWebPart.ts) does not seem to include the onInit setup function as [outlined in the docs](https://pnp.github.io/pnpjs/documentation/getting-started/#getting-started-with-sharepoint-framework)? Can you try adding it and see if that resolves your issue?

Because each webpart represents a closure you need to call setup in each component - perhaps that is where your confusion is?

**Comment by patrick-rodgers** [comment]
Closing this as answered. If you continue to have issues after adding the appropriate setup code please open a new issue, link this one, and provide any new details you can. Thanks!

**Comment by KoenZomers** [comment]
> The [webpart code you posted](https://github.com/eariel/GetUserProfileTestWP/blob/master/getuserproperties/src/webparts/getUserProfileProperties/GetUserProfilePropertiesWebPart.ts) does not seem to include the onInit setup function as [outlined in the docs](https://pnp.github.io/pnpjs/documentation/getting-started/#getting-started-with-sharepoint-framework)? Can you try adding it and see if that resolves your issue?
> 
> Because each webpart represents a closure you need to call setup in each component - perhaps that is where your confusion is?

Ran into the same issue and doing this fixed it for me. Updated link how to accomplish this as the one mentioned in the quote no longer works: https://pnp.github.io/pnpjs/getting-started/#using-pnpcommon-setup
