### ISSUE TITLE
Break inheritance while item creation and assign permission to group

### ISSUE THREAD

**Issue by Nagarajan1605** [pnp/pnpjs#876]
Hi Team,,
I already referred this below url
SharePoint/PnP-JS-Core#804 but while executing i am getting promise pending. Below i have given my code.

$pnp.sp.web.lists.getByTitle("testlist").items.getById(8).get().then(function(results){
results.breakRoleInheritance(false);
});

$pnp.sp.web.lists.getByTitle("test").items.add({

	test1:test,
	test2:test,
	test3:test
	
}).then(function(resultdata){
_Newitemidvalue = resultdata.data.Id;
$pnp.sp.web.lists.getByTitle("testlist").items.getById(_Newitemidvalue ).get().then(function(results){
results.breakRoleInheritance(false);
});
});

After executing this i want to assign permission for this individual item. Need to assign some groups and individual users. Could you please assist me.

**Comment by koltyakov** [comment]
Hi @Nagarajan1605, 

You already pointed to the answer to your question.
Items' permissions in terms of API are no difference to list or other SharePoint artifacts.
However, the mistake is using the results for chaining `breakRoleInheritance`, it should be chained with getting an item by id or result's item instead. I'd encourage using types to avoid such questions, which are just answered by TypeScript in an editor.

```typescript
import { sp } from '@pnp/sp';

const list = sp.web.getList('/sites/site/lists/list');

(async () => {

  // Get user/group proncipal Id
  const { Id: principalId } = await sp.web.currentUser.select('Id').get();
  // Get role definition Id
  const { Id: roleDefId } = await sp.web.roleDefinitions.getByName('Edit').get();

  const { item } = await list.items.add({ Title: 'My new item' });
  // Break role inheritence for unique permissions
  await item.breakRoleInheritance(false);

  // Assigning permissions
  await item.roleAssignments.add(principalId, roleDefId);

  console.log('Done');

})()
  .catch(console.error);
```
