### ISSUE TITLE
renderListDataAsStream function should allow an option to set URL query parameters

### ISSUE THREAD

**Issue by johannes-z** [pnp/pnpjs#877]
References https://github.com/pnp/pnpjs/issues/723

### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.6]

Please specify what version(s) of SharePoint you are targeting: [SPO]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
The parameters `FilterFields1`, and `FilterValues1` are supported by the `overrideParameters` of the `renderListDataAsStream` API, but do not provide any functionality. SPO Modern UI also uses these parameters, but as query parameters. The only way to use these parameters as of now with pnpjs is to use the `SPHttpClient` and calling the `renderListDataAsStream` endpoint yourself.

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

```typescript 
// Remove this if you don't have any code sample to provide
import { sp, SPHttpClient, Web, RenderListDataParameters } from "@pnp/sp";
var web = new Web(window.location.origin + '...')

var list = web.getList('...')

var parameters: RenderListDataParameters = {
    ViewXml: `<View><ViewFields><FieldRef Name="Title" /></ViewFields></View>`
}
var overrideParameters = {
    FilterFields1: 'Title',
    FilterValues1: 'Value1;#Value2' // Value1%3B%23Value2 doesn't work either
}

// no filter is applied
list.renderListDataAsStream(parameters, overrideParameters)
.then(r => console.log(r.Row.map(r => r.Title)))

var endpoint = list.toUrl() + '/renderListDataAsStream'
var client = new SPHttpClient()

// filter is applied
client.post(`${endpoint}?FilterFields1=Title&FilterValues1=Value1%3B%23Value2`, {
    body: JSON.stringify({
        parameters
    })
})
.then(r => r.json())
.then(r => console.log(r))
```

**Comment by johannes-z** [comment]
Another reason is the `InplaceSearchQuery` query parameter. To use it, you have to do something like this:

```ts
var url = sp.web.getList('/sites/qm/C4ITDocuments').toUrl()

var client = new SPHttpClient()
client.post(`${window.location.origin}/sites/mysite/${url}/renderListDataAsStream?InplaceSearchQuery=Test`, {
    body: JSON.stringify({
        parameters: {
            RenderOptions: RenderListDataOptions.ListData,
        },
    })
}).then(r => r.json()).then(console.log)
```

**Comment by patrick-rodgers** [comment]
Added this for release in 1.3.7, usage will be:

```TypeScript
const data = await sp.web.lists.getByTitle("Generic").renderListDataAsStream({
    ViewXml: `<View><ViewFields><FieldRef Name="Title" /></ViewFields></View>`,
}, null, new Map([["FilterFields1", "Title"], ["FilterValues1", encodeURIComponent("Item 4")]]));
```
