### ISSUE TITLE
Create new site collection

### ISSUE THREAD

**Issue by stvpwrs** [pnp/pnpjs#88]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

@pnp/sp v. 1.0.4

### Question
Is there a way to create a new site collection with pnpjs?

**Comment by patrick-rodgers** [comment]
No - the thinking being site collections are typically created by admins or a provisioning process. Then client side code would operate inside that container. Can you expand on your use case and we can consider adding it?

**Comment by patrick-rodgers** [comment]
After having a look at this we won't be adding support to create new site collections. This is a tenant admin level activity and is better handled through the PnP provisioning engine. There also isn't a REST api to support this action. Thanks for your interest in the library and please let us know if you have further feedback.

**Comment by mag210** [comment]
Hi all, I'm assuming as of 1.26 creating site collections using @pnp/sp is now supported? https://pnp.github.io/pnpjs/sp/docs/sites/
