### ISSUE TITLE
getListItemsWithCAMLQuery not returning data in modile browsers

### ISSUE THREAD

**Issue by MadhuriHM** [pnp/pnpjs#880]
### Category
- [ ] Bug

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online      ]

### Expected / Desired Behavior / Question
The method sp.web.lists.getbytitle(listname).getListItemsWithCAMLQuery(camlQuery,field) should ideally return the list items filtered based on the caml query.

### Observed Behavior
This method works in desktop browsers but is not consistent in mobile browsers. This method does not return any data in mobile browsers.

### Steps to Reproduce
Run the method getListItemsWithCAMLQuery in iPhone 12.1 Safari browser.

```typescript 
sp.web.lists.getbytitle(listname).getListItemsWithCAMLQuery(camlQuery,field) 
```

**Comment by MadhuriHM** [comment]
> REST API behaves the same no matter the client is: ordinary in-browser app or backend HTTP client. So I believe it's something else and other business logic which makes you think it doesn't return data. I'd suggest trying remote debugging or the emulator in XCode for your iPhone device.

I have checked the code again, but it is not working in mobile browser (works fine on desktop).
Also if I replace the method with the below method it works in mobile as well. Is there any difference between getListItemsWithCAMLQuery and this method?

sp.web.lists.getbytitle(listname).items.filter(filter).get()

**Comment by patrick-rodgers** [comment]
One of those methods executes a POST and the other does a GET. There should be no behavior difference in the library between clients, and if you see a difference it might be particular to your device and its configuration. Unless you can provide a clear error with more details than "doesn't work in mobile" there isn't anything we can do to help.

**Comment by patrick-rodgers** [comment]
Going to close this due to lack of detail and existence of a workaround.
