### ISSUE TITLE
No documentation for MS Graph API for SharePoint all list/library operations

### ISSUE THREAD

**Issue by ymihir** [pnp/pnpjs#882]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

I am not able to see the documentation for SharePoint list, library operations with MS Graph API. Also are there any limitations with Graph API for SharePoint lists, library CRUD operations. Below things I found not possible:

- No support for adding attachments to list

- No proper support/documentation for adding people picker column (multiple also) items

- No support for adding Lookup items.

- [x] Documentation gap/issue
- [x] Question

**Comment by patrick-rodgers** [comment]
Hi @ymihir - any reason you don't want to use the sp library which already supports all of these actions?

For the graph library if you have some time we welcome contributions but expanding our graph coverage is not our current priority.

**Comment by ymihir** [comment]
I want to elevate the user privileges by using Graph API with respect to SharePoint. But if methods are there then why there is no documentation? or simply Graph API wont support them that is the reason no documentation available?

**Comment by patrick-rodgers** [comment]
Going to close this issue. Unfortunately it is the official policy of the Graph product team that we are not longer allowed to include the graph library in our offering through PnP. We will remove it from v2 and no longer support it for v1. Any feedback can be directed to the MS Graph team.
