### ISSUE TITLE
Unable to get Terms from Taxonomy TermStore due to CORS

### ISSUE THREAD

**Issue by monkey-butler** [pnp/pnpjs#884]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.3.6      ]

Please specify what version(s) of SharePoint you are targeting: [    SharePoint Online     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Using /sp-taxonomy to get Terms for termstores to store locally to reduce number of API calls I should receive all terms that I can use to convert ItemtermGuid to term name

### Observed Behavior
I am receiving CORS errors from https://ukwest0-completeness.svc.ms/api/collection and this I cannot retrieve the terms for customer.sharepoint.com

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

```typescript 
taxonomy.termStores.getByName(definitions.TermStore).get().then( baseStore => {
      TermStore = baseStore;
      baseStore.groups.getById(definitions.TermGroup).get().then(TermGroup => {
        TermGroup.termSets.getByName(Set).get().then(thisTermSet => {
          thisTermSet.terms.getById(termGUID).get().then(updatedTerm => {
            const TermGuid = updatedTerm.Id.replace('/Guid(','').replace(')/','');
            updatedTerm.Id = TermGuid;
            TermSets[Set][TermGuid] = updatedTerm;
          });
        });
      });
    }).catch(error => {
      console.error(error);
    })
```

**Comment by patrick-rodgers** [comment]
This library cannot solve CORS issues which are enforced by the browser. You would need to look at your solution design and determine the best way to accomplish what you need. SPO does now support CORS requests.
