### ISSUE TITLE
How to filter list items based on managed metadata field value

### ISSUE THREAD

**Issue by MadhuriHM** [pnp/pnpjs#887]
### Category
- [ ] Question

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online  ]

### Expected / Desired Behavior / Question
I want to use the below method to get list items based on a value of a managed metadata field.
sp.web.lists.getbyid(listid).items.filter(filter).get()
What is the filter condition I need to add to get the list items based on a managed metadata field?

```typescript 
sp.web.lists.getbyid(listid).items.filter(filter).get()

**Comment by patrick-rodgers** [comment]
You need to use the getItemsByCAMLQuery method as filtering by MetaData columns is not supported by the $filter query.

```TypeScript
const r = await sp.web.lists.getByTitle("TaxonomyList").getItemsByCAMLQuery({
    ViewXml: `<View><Query><Where><Eq><FieldRef Name="MetaData"/><Value Type="TaxonomyFieldType">Term 2</Value></Eq></Where></Query></View>`,
});
```
