### ISSUE TITLE
Updating multi value Managed metadata field failed with REST API and pnp taxonomy methods

### ISSUE THREAD

**Issue by vipuliflex** [pnp/pnpjs#889]
@patrick-rodgers Facing issue in saving multi-value managed metadata even with "Updating the hidden text field conatining ManagedMetadata field string value" using REST API/Pnp JS failed if field have space in display name while creation and if taxonomy field is created without space then PnP JS methods and REST API  methods are working fine.This is a long time issue please help as i stucked with it for quite a long time.Please help ASAP

**Comment by patrick-rodgers** [comment]
Hi @vipuliflex - this isn't really enough to go on, can you share a repo we can clone to see the issue easily? We need to be able to reproduce it so we can debug and ensure it is fixed. Otherwise we are just guessing. Thanks!

**Comment by patrick-rodgers** [comment]
Going to close this due to inactivity. If you are still blocked please open a new issue, link this issue and let us know you're still stuck with a few more details. Thanks!
