### ISSUE TITLE
/_api/contextinfo URL issue.

### ISSUE THREAD

**Issue by roybselim** [pnp/pnpjs#895]
### Category
- [ ] Enhancement
- [ x ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [  1.3.6   ]

Please specify what version(s) of SharePoint you are targeting: [    SharePoint Online     ]

### Expected / Desired Behavior / Question
I am using sp/pnp to query taxonomy terms in SPFx webpart. When the URL does not have a trailing forward slash ('/') [ex: https://<tenant>/sites/Example] in the end, it will give a fetch error 404 for the endpoint https://<tenant>/sites/_api/contextinfo. This is rightly so because this endpoint does not exists. To correct the issue, I just added a trailing forward slash to the URL [https://<tenant>/sites/Example/] and the endpoint becomes https://<tenant>/sites/Example/_api/contextinfo which is now correct.

### Observed Behavior
So the way the endpoint is constructed requires a trailing forward slash character ('/').
[https://<tenant>/sites/Example ],  No '/'  --> API: https://<tenant>/sites/_api/contextinfo
[https://<tenant>/sites/Example/ ]With '/' --> API: https://<tenant>/sites/Example/_api/contextinfo

### Steps to Reproduce
1.) Create an SPFx webpart using React framework.
2.) Install sp/pnp taxonomy libraries. npm install @pnp/logging @pnp/common @pnp/odata @pnp/sp @pnp/sp-taxonomy @pnp/sp-clientsvc --save
3.) Write this code in the main webpart class that extends the BaseClientSideWebPart

import { taxonomy, ITermStore, ITermSet, ITerms } from "@pnp/sp-taxonomy";

private getTerms(termStore: string, termSetId: string): Promise<any[]> {
    const store: ITermStore = taxonomy.termStores.getByName(termStore);
    const set1: ITermSet = store.getTermSetById(termSetId);
    const terms: ITerms = set1.terms;
    return terms.get();
}

4.) Call this function in the render method or pass it to the React component and call the function in the componentDidMount lifecycle method.
5.) Bundle and package the project and install it in the App catalog. Install the SPFx in any modern site and add the SPFx in any modern pages.
6.) Try opening the site without a trailing forward slash: ex: https://<tenant>/sites/Example and the webpart will not appear.
7.) Try opening the site with a trailing forward slash ex: https://<tenant>/sites/Example/ and the webpart will function properly.

**Comment by koltyakov** [comment]
In SPFx, the context should be established. Did you try following [this](https://pnp.github.io/pnpjs/documentation/getting-started/#establish-context) docs article?

**Comment by roybselim** [comment]
Hello kolyatov,

This resolves the issue. Thanks for pointing me to the right direction.
