### ISSUE TITLE
Cannot set a Geolocation Field value from Node

### ISSUE THREAD

**Issue by escobar5** [pnp/pnpjs#896]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Latest.
Sharepoint Online

### Expected / Desired Behavior / Question
Should be able to add a List Item with a SPFieldGeolocationValue

### Observed Behavior
If I try to add a ListItem with a  SPFieldGeolocationValue, I get this error:

Error: Error making HttpClient request in queryable [400] Bad Request ::> {"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"es-ES","value":"Se encontraron clases de tipo incompatibles. El tipo 'SP.FieldGeolocationValue' era de clase 'Complex' en lugar de la clase esperada 'Primitive'."}}}

This is the code:

```
sp.setup({
  defaultCachingStore: 'session',
  defaultCachingTimeoutSeconds: 60 * 15,
  globalCacheDisable: false,
  sp: {
      fetchClientFactory: () => {
        return new SPFetchClient(config.sharepoint.siteUrl,
          config.sharepoint.clientId, config.sharepoint.clientSecret);
    },
    headers: {
      Accept: 'application/json; odata=verbose',
      "Content-Type": "application/json;odata=verbose"
    }
  }
});

const itemResult = await sp.web.lists.getByTitle('Opiniones')
    .items.add({
      ...
      Ubicacion : {  "__metadata":  {"type": "SP.FieldGeolocationValue"}, Latitude: 60.2872339, Longitude: 24.8516785 }
});

```

**Comment by koltyakov** [comment]
Hi @escobar5, 

Can't see any bug related to the Geolocation field type, the wrong payload can't be classified as a bug. =)

This works for me, please try without `"__metadata":  {"type": "SP.FieldGeolocationValue"}`:

```typescript
sp.web.lists.getByTitle('My Locations')
    .items
    .getById(2)
    .update({
        Location: { // <-- payload without __metadata
            // Altitude: 0,
            Latitude: 60.2872339,
            Longitude: 24.8516785,
            // Measure: 0
        }
    })
    .then(console.log)
```

**Comment by escobar5** [comment]
@koltyakov, thanks for your response. You're right I should have marked it as a question 😬 

I've tried without metadata, but I get this error:

> Error: Error making HttpClient request in queryable [400] Bad Request ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"es-ES","value":"Se encontr\u00f3 un nodo 'StartObject' inesperado al leer del lector JSON. Se esperaba un nodo 'PrimitiveValue'."}}}

**Comment by escobar5** [comment]
It was my bad, I was mistaking the type of field. I was trying to set the value to a field of the new type **Location** of modern SPO Sites. The value of those sites is a JSON Blob like this:


> "Ubicacion":"{\"EntityType\":\"LocalBusiness\",\"LocationSource\":\"Bing\",\"LocationUri\":\"https://www.bingapis.com/api/v6/localbusinesses/YN8041x13437667915995167349?setLang=es\",\"UniqueId\":\"https://www.bingapis.com/api/v6/localbusinesses/YN8041x13437667915995167349?setLang=es\",\"DisplayName\":\"WeWork\",\"Address\":{\"Street\":\"Calle 7 Sur #42-145\",\"City\":\"Medellin\",\"State\":\"CUN\",\"CountryOrRegion\":\"CO\",\"PostalCode\":\"\"},\"Coordinates\":{\"Latitude\":6.197537422180176,\"Longitude\":-75.57356262207031}}"


Thanks for your help
