### ISSUE TITLE
Help Testing v2 Beta

### ISSUE THREAD

**Issue by patrick-rodgers** [pnp/pnpjs#900]
# Help Wanted Testing the v2 beta

## Install

To install the v2 beta use `npm install @pnp/sp@beta --save`

> You no longer need to install all the modules, they are no longer listed as peer dependencies.

## Test

We are looking for feedback in three main areas, though appreciate any feedback you have on v2. _For all issues_ please ensure you note in the title it is for v2 and include the beta version number. If you are not on the latest beta, please update to see if we may have already fixed the issue you are seeing.

### Is something broke?

This include any and all bugs in functionality. Is something that was working in v1 no longer working in v2? If so, please check the [changelog](https://github.com/pnp/pnpjs/blob/dev-v2/CHANGELOG.md) to see if it was a known breaking change.

Did you previously submit a bug in the last few months? If so please ensure we ported the fix over correctly. If your bug is still open in the issues list, no need to log it again for v2.

If you have some time we will of course welcome PRs to help get things patched up.

### How are the [new docs](https://pnp.github.io/pnpjs/documentation/v2-beta/)?

How can we make them clearer? How can we better organize them? What information is missing? Did we spell things wrong (liklely)?

For documentation issues please be as specific as possible in what would make things better. Too often the feedback about the docs is "this is bad" which doesn't give us much to work with. Let us know what would make things easier/clearer/better so we know what to look at changing.

A few things like image paths may be wrong due to the fact we are hosting these temporarily under a sub-folder. No need to report them for now, we will ensure images etc. work for launch. But if you aren't sure please let us know so we don't miss anything.

### How is the [transition guide](https://github.com/pnp/pnpjs/blob/dev-v2/docs/transition-guide.md)?

As you are migrating to v2 from v1 how is the guide? What information is missing? We can't anticipate everything folks are doing, so please let us know or submit an update if you hit a snag while migrating. We want to get the guide as clear as possible, and I am sure there are gaps. Please log an issue and if you have a few minutes a PR to help us out would be great! Thanks!

## Questions?

Please comment in this issue thread with questions on testing the beta. For all other issues please create a new issue with your bug/question/idea.

Thank you all for your help so far, looking forward to getting this release out for everyone!

> We aren't looking to take on major new features during the beta period, but if you have ideas please submit an issue so we can track it and consider it for future releases.

**Comment by KEMiCZA** [comment]
@patrick-rodgers should I refactor all .then() promise references in the documentation to async/await?

**Comment by patrick-rodgers** [comment]
@KEMiCZA - yes, we tried to get most of them but I am sure some where missed. I have a todo around fixing up the items docs (welcome help there). The only place we can't use await is the batching examples - otherwise yes, please.

**Comment by patrick-rodgers** [comment]
Closing this as we are nearing release. Post release any issues should be reported as they normally would through the issues list. Thanks everyone who provided feedback!
