### ISSUE TITLE
current logged in user has full control access or not using pnp js

### ISSUE THREAD

**Issue by Harshagracy** [pnp/pnpjs#902]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Expected / Desired Behavior / Question
I wanted to find out whether current logged in user has full control access.

This is my code:

```
sp.web.currentUser.get().then(result => {
      sp.web.userHasPermissions(result.LoginName, PermissionKind.FullMask).then(perms => {
        console.log(perms);
    });
  });
```

It returns false for user who has full control access and present in owners group.

Any other way to find out this?

PS: I do not want to know whether he is SCA. I can check that in one step using result.isSiteAdmin.

**Comment by ncmadhan1989** [comment]
https://github.com/pnp/pnpjs/issues/489
look on it

import { sp, PermissionKind } from '@pnp/sp';

sp.web.select('EffectiveBasePermissions').get()
    .then(({ EffectiveBasePermissions }) => {
        return sp.web.hasPermissions(EffectiveBasePermissions, PermissionKind.ManageLists);
    })
    .then(hasPermissions => {
        console.log(hasPermissions ? 'Good to go...' : 'No way buddy!');
    })
    .catch(console.warn);

**Comment by patrick-rodgers** [comment]
Going to close this as answered, please open a new issue and reference this one if you are still having trouble. Thanks!
