### ISSUE TITLE
Get all list titles in Site

### ISSUE THREAD

**Issue by robiharid** [pnp/pnpjs#908]
This shows how to get list items once given a list title (https://pnp.github.io/pnpjs/sp/docs/items/)

I want a PropertyPaneDropdown to allow the client-side to select between lists that exist on the site... is there anyway to do this?

**Comment by koltyakov** [comment]
Just get the lists queryable collection:

```typescript
sp.web.lists.select('Id,Title').get().then(console.log)
```

**Comment by patrick-rodgers** [comment]
Closing this as answered. Thanks @koltyakov!
