### ISSUE TITLE
creating webparts with pnp/js

### ISSUE THREAD

**Issue by jmflanders1964** [pnp/pnpjs#909]
I am trying to create a sharepoint page that contains a webpart which contains some text and images. I am trying to do this using pnp/js. I have been able to create a page using pnp/js, but I can not determine how to create the webpart with the text and images. If you can give me some pointers that would be greatly appreciated.

**Comment by patrick-rodgers** [comment]
I would start with the docs which have [an example for adding a web part](https://pnp.github.io/pnpjs/sp/docs/client-side-pages/#add-client-side-web-parts). If you can work through that example I think you will understand the process. Beyond that if you have more specific questions we can try and assist. Thanks!

**Comment by patrick-rodgers** [comment]
Going to close this as answered. If you are still having issues please open a new issue and reference this one with additional details. Thanks!
