### ISSUE TITLE
pnpjs for javascript project

### ISSUE THREAD

**Issue by masterl1983** [pnp/pnpjs#91]
### Category
- [ ] Enhancement
- [ ] Bug
- [x ] Question
- [ ] Documentation gap/issue

### Expected / Desired Behavior / Question
I used the old repo for some time now and I now would like to move to the new repo. I used pnp-js-core for simple tasks in a content-editor webpart. I used the javascript files from the dist folder...

In the new repo I only can find TypesScript files - how can I use the library within a plain javascript project?

Thank you for your feedback!

**Comment by ahsanranjha** [comment]
I am also waiting for same ...

**Comment by koltyakov** [comment]
Also, it's always possible to download compiled version from npm, i.e. https://unpkg.com/@pnp/pnpjs@1.0.4/dist/pnpjs.es5.umd.bundle.js

**Comment by KEMiCZA** [comment]
It seems you can also get the minified js files from the unpkg.com site, just add .min.js at the end, i.e.
https://unpkg.com/@pnp/pnpjs@beta/dist/pnpjs.es5.umd.bundle.min.js

**Comment by koltyakov** [comment]
@KEMiCZA, he he, I updated the links couple of seconds before your comment.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. You can track the availability of the files from the CDN using #6.
