### ISSUE TITLE
sp web 404 when web part is deployed

### ISSUE THREAD

**Issue by robiharid** [pnp/pnpjs#911]
```
"Error making HttpClient request in queryable: [404] "
```

The call works on localhost and on tenant site  /layouts/15/workbench

Fails when I have deployed using the app catalogue. 

`
  console.log('sp  ', sp.web.lists.get());` returns promise rejected

**Comment by koltyakov** [comment]
https://pnp.github.io/pnpjs/documentation/getting-started/#using-pnpsp-setup

**Comment by robiharid** [comment]
> https://pnp.github.io/pnpjs/documentation/getting-started/#using-pnpsp-setup

Thanks @koltyakov ! Please close
