### ISSUE TITLE
Not able to view SharePoint site in Safari - CROSS-ORIGIN Script Error

### ISSUE THREAD

**Issue by spvjebaraj** [pnp/pnpjs#917]
Hi,
I am working in Angular 8 along with PnP js. The site is not opening in Safari Browser. Also in iOS devices, the site is not opening in any browsers. I am getting the below error in console. I am using the below configuration and list fetch code.

"**cross-origin script load denied by cross-origin resource sharing policy**"

`constructor() {
    const config: SPConfiguration = {
      sp: {
        headers: {
          Accept: "application/json; odata=verbose"
        }
      }
    };
    sp.setup(config);
  }`

`getListItemDetails<T>(
    listTitle: string,
    selectedFields: string,
    orderBy: string
  ): Observable<T[]> {
    return from(
      sp.web.lists
        .getByTitle(listTitle)
        .items.select(selectedFields)
        .orderBy(orderBy)
        .get<T[]>()
    );
  }`

Please help me to resolve this issue to work in Safari browser and iOS devices with all browsers.

**Comment by patrick-rodgers** [comment]
The library should behave the same way across all browsers. If you are getting a CORS error it is likely you are trying to make calls from your URL to SharePoint, which does not support CORS. Regardless can you share more details around what you are doing and how so we can attempt to help? Thanks.

**Comment by spvjebaraj** [comment]
Hi Patrick,
Sorry for late reply.  I have written the service as separate ts file, in that I have imported the configuration and related details like below.

`import { CamlQuery, sp, ItemAddResult } from "@pnp/sp";
import { SPConfiguration } from "@pnp/sp/src/config/splibconfig";`

In the service file, I have used the below code to get the items from SharePoint list.

`export class ListDataService {
  constructor() {
    const config: SPConfiguration = {
      sp: {
        headers: {
          Accept: "application/json; odata=verbose"
        }
      }
    };
    sp.setup(config);
  }`

`getListItemDetails<T>(
    listTitle: string,
    selectedFields: string,
    orderBy: string
  ): Observable<T[]> {
    return from(
      sp.web.lists
        .getByTitle(listTitle)
        .items.select(selectedFields)
        .orderBy(orderBy)
        .get<T[]>()
    ).pipe(catchError(this.errorHandler));
  }
}`

Then in my other ts file, I am calling the service as below.

`getHomePageButtons(): Observable<HomePageCategoryDisplay[]> {
    const selectedFields =
      "ID, Title, CategoryIcon, ExternalLink, Layouts, AssociatedListName, OrderNumber, NavPage";
    const orderBy = "OrderNumber";
    return from(
      this.listDataService.getListItemDetails<HomePageCategoryDisplay>(
        this.homePageButtonsListTitle,
        selectedFields,
        orderBy
      )
    );
  }`

Can you please help me on this? It is working in other browsers except Safari. Please help me to solve this.

**Comment by patrick-rodgers** [comment]
This is likely due to differences in how browsers handle CORS - if it is working on one browser but not another that isn't an issue with the library. SPO does not support CORS for REST so far as I know. Going to close this issue as non-library and outside our control. If you believe the issue does exist in the library please open a new issue and reference this one. Thanks!
