### ISSUE TITLE
Get column display name instead of internal name

### ISSUE THREAD

**Issue by robiharid** [pnp/pnpjs#918]
I am displaying the properties of a list item to the user, user-created columns with a space have character codes like x0020 to denote a space.

How can I display the user friendly name with a space instead of the charactor code?

`sp.web.lists.getByTitle('Policies').get()`

**Comment by koltyakov** [comment]
You can get list's or content type's fields and correspond OData Entity field name with a display name.

**Comment by robiharid** [comment]
> Hi @robiharid,
> You can get list's or content type's fields and correspond OData Entity field name with a display name.

Thanks Koltyakov. Not sure where you find OData Entity Field Name property? This is what returns when I get an item in the list:

```
Attachments: true
AuthorId: 11
ComplianceAssetId: null
ContentTypeId: 
Created: 
EditUrl: "Vacancy.aspx?VacancyID="
EditorId: 11
FileSystemObjectType: 0
GUID: 
ID: 29
Id: 29
Modified: 
OData__UIVersionString: "1.0"
ServerRedirectedEmbedUri: null
ServerRedirectedEmbedUrl: ""
Title: "General Manager Vacancies"
odata.editLink: 
odata.etag: ""2""
odata.id: 
odata.type:
```

Do I need to look up the List itself and get the Field Name as a property of that? 

List has a odata.metadata which is another link?

**Comment by koltyakov** [comment]
Well... Something like this (to represent the idea and data relationship):

```typescript
import { sp } from '@pnp/sp';

(async () => {

    const list = sp.web.lists.getByTitle('Custom01');

    // EntityPropertyName is what REST uses in CRUD operations, not internal names,
    // even if in most of the cases they equal
    const fields = await list.fields.select('Title,EntityPropertyName').get().then((res) => {
        return res.reduce((r, f) => {
            r[f.EntityPropertyName] = f.Title;
            return r;
        }, {} as any);
    });

    const items = await list.items.get().then((items) => {
        return items.map((item) => {
            return Object.keys(item).reduce((r, prop) => {
                r[fields[prop]] = item[prop]; // get display name by entity name and assign a value
                return r;
            }, {} as any); // only to demo the relationship, such map doesn't make sense in a actual project
        });
    });

    console.log(items);

})().catch(console.error);
```

Hope this makes more sense.

**Comment by robiharid** [comment]
Thanks again @koltyakov 

The code works. However, it seems a little complicated for what we want to do - grab an EntityPropertyName and add it/remap onto the item object.

Couldn't we do something like this to make it easier to work with: 
```sp.web.lists
    .getByTitle(title)
    .fields.filter('Hidden eq false')
    .get();```
.select('EntityPropertyName') before the .get

then we can grab list items as normal ```
  const items = await sp.web.lists
     .getByTitle(title)
     .items.orderBy(sortBy, toggleAscending)
     .top(limitResults)
     .get();```


then .map the entitypropertyname to the title?

**Comment by koltyakov** [comment]
Oh, I dnk how I missed the tag. Of course, it's not in any kind of enhancement to the library but a question.

I consider this answered. During development, a SharePoint developer deals with internal/entity names and decide how to show display names, based on logic, localizations, API requests to fields metadata, etc.

The payload we return within PnPjs is mostly what is returned with REST API, fewer transformations is better. In an app implementation, any business logic level mapping can take place. This is outside the scope of the library.
