### ISSUE TITLE
Read data from Person field in List

### ISSUE THREAD

**Issue by robiharid** [pnp/pnpjs#919]
I have a column in list that uses the Person data type.

How do I get the details of a person, like their email and number?

Item:
```
Attachments: false
Compliance Asset Id: null
Content Type ID: ""
Created: ""
GUID: ""
ID: 1
Modified: ""
Title: ""
Version: "1.0"
undefined: 14```

I have tried using expand but none of these fields are the Person field?

**Comment by koltyakov** [comment]
You can expand People fields:

![image](https://user-images.githubusercontent.com/7816483/68589429-e6188f80-049c-11ea-8eea-a734f4b2ad92.png)

These should be expandable: Title, Name, EMail, MobilePhone, SipAddress, Department, JobTitle, FirstName, LastName, WorkPhone, UserName, Office, ID, Modified, Created, ImnName, NameWithPicture, NameWithPictureAndDetails, ContentTypeDisp.

The questions you keep on asking are appreciated but tend to be a general SharePoint REST API topic but not something really related to the library. We encourage asking such questions in community forums or Gitter. Thanks!

**Comment by robiharid** [comment]
> You can expand People fields:
> 
> ![image](https://user-images.githubusercontent.com/7816483/68589429-e6188f80-049c-11ea-8eea-a734f4b2ad92.png)
> 
> These should be expandable: Title, Name, EMail, MobilePhone, SipAddress, Department, JobTitle, FirstName, LastName, WorkPhone, UserName, Office, ID, Modified, Created, ImnName, NameWithPicture, NameWithPictureAndDetails, ContentTypeDisp.
> 
> The questions you keep on asking are appreciated but tend to be a general SharePoint REST API topic but not something really related to the library. We encourage asking such questions in community forums or Gitter. Thanks!

Could you link me to the pnpjs forum?

As you can see, my data is not returning a Author field which is why I am asking how to get a hold of it?

**Comment by koltyakov** [comment]
You can always checkout the [SharePoint Developer Documentation](https://aka.ms/spdev-docs) for general development questions and the [MS Tech Community for Sharepoint](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) is a great place to ask for guidance from the community. [Gitter chat room](https://gitter.im/OfficeDev/PnP-JS-Core) also can be a helpful resource, connected with PnPjs. In generic questions with SharePoint API it's better to reference or use when searching generic "sharepoint rest api", then mirror API capabilities to OData modificators and PnPjs wrapper functions.
