### ISSUE TITLE
Is new repository has option to create list items in directly in folder?

### ISSUE THREAD

**Issue by ahsanranjha** [pnp/pnpjs#92]
New Rest Api : 

/_api/SP.AppContextSite(@target)/web/lists/GetByTitle('Sample')/AddValidateUpdateItemUsingPath() 

Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [#] Enhancement
- [ ] Bug
- [# ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ sorry learning now a days, i was not able to check new file version      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* If you have a general question [gitter](https://gitter.im/OfficeDev/PnP-JS-Core) may be a better forum.
* Remember to include sufficient details and context.
* If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thank you for your feedback!

**Comment by koltyakov** [comment]
Hey @ahsanranjha,

The requested endpoint is already in a [process of adding to PnPjs](https://github.com/pnp/pnpjs/pull/89). Yet, it's likely it won't be merged into sp-pnp-js, as we encourage folks to start migrating to [PnPjs](https://github.com/pnp/pnpjs).

---

Once again, for your interest in the sp-pnp-js library. We wanted to mention that this library is being deprecated in July 2018 in favor of the [new scoped pnpjs libraries](https://github.com/pnp/pnpjs). You should begin transitioning your existing projects when possible or start new projects with the new libraries. Please see the [transition guide](https://pnp.github.io/pnpjs/transition-guide.html) for more details on migrating and be sure to let us know if you have any questions. Thanks!

**Comment by patrick-rodgers** [comment]
Closing this as the PR was merged. Will be in the next version. Thanks!

**Comment by ahsanranjha** [comment]
Hello Sir, @patrick-rodgers 

Is this Enhancement updated in latest version? how i can get a latest version?
