### ISSUE TITLE
[V2] Importing Web factory function

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/pnpjs#920]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ v2beta ]

Please specify what version(s) of SharePoint you are targeting: [2016, online ]

### Expected / Desired Behavior / Question
Different instructions from the docs:
at https://pnp.github.io/pnpjs/documentation/v2-beta/transition-guide/
```
import { Web, IWeb } from "@pnp/sp/webs";
const web: IWeb = Web("some absolute url");
```

at https://pnp.github.io/pnpjs/documentation/v2-beta/sp/webs/
```
import { Web } from "@pnp/sp/web";
const web = Web("https://something.sharepoint.com/sites/dev");
```

### Observed Behavior
I tried both of the above and none worked for me. My workaround was to import Web from preset all:
`import { sp, Web } from "@pnp/sp/presets/all";
`
Thank you!

**Comment by patrick-rodgers** [comment]
That's a weird one. I just tried it in an SPFx project and it worked as expected. Can you share exactly what version of the beta you tried? I just did it with the latest (@pnp/sp@2.0.0-13)

My sample code:

```TypeScript
  // .. other stuff omitted, no changes from OOTB webpart

import { sp } from "@pnp/sp";
import "@pnp/sp/lists/web";
import { Web } from "@pnp/sp/webs";

export interface IHelloWorldWebPartProps {
  description: string;
}

export default class HelloWorldWebPart extends BaseClientSideWebPart<IHelloWorldWebPartProps> {

  protected async onInit(): Promise<void> {
    await super.onInit();
    sp.setup({ spfxContext: this.context });
  }

  public render(): void {
    this.domElement.innerHTML = `Loading all the lists...`;
    const web = Web(this.context.pageContext.web.absoluteUrl);

    web.lists.select("Title")<{ Title: string }[]>().then(lists => {
      this.domElement.innerHTML = `<ul>${lists.map(l => `<li>${l.Title}</li>`).join("")}</ul>`;
    });
  }

  // .. other stuff omitted, no changes from OOTB webpart
}



```

**Comment by PathToSharePoint** [comment]
Thanks for the reply. I am on 2.0.0-13 and I'll try your code.

I see that you have included a line `import "@pnp/sp/lists/web";` which is not in the documentation samples. What is its role, and could that explain my issue?

**Comment by patrick-rodgers** [comment]
That import adds the lists functionality to the web object, in this case the .lists property I happened to use in my example. Shouldn't be required if you just need web.

**Comment by PathToSharePoint** [comment]
Dang that could actually be my issue. I thought I was good with sp and Web and would get the list functionality.

**Comment by patrick-rodgers** [comment]
Not with the [new selective import model](https://pnp.github.io/pnpjs/documentation/v2-beta/concepts/selective-imports/). You can now control importing each piece. If we auto-import things then tree-shaking can't work. You can use the [core preset](https://pnp.github.io/pnpjs/documentation/v2-beta/concepts/selective-imports/#presets) to get the main functionality in one go.

**Comment by PathToSharePoint** [comment]
@patrick-rodgers thanks for the help, it worked fine after I added the lists piece.

If I am not mistaken, there is still an error in the instructions on the webs page (link above), it should read:
`import { Web } from "@pnp/sp/webs";`

**Comment by patrick-rodgers** [comment]
Yes that is a typo, will fix it. Thanks. Going to close this issue as resolved.
