### ISSUE TITLE
Support for setting metadata defaults for library

### ISSUE THREAD

**Issue by olemp** [pnp/pnpjs#921]
Category
- [x] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: `1.3.7`

### Enchancement / Question
I'd like support for setting metadata defaults for library (updating client_LocationBasedDefaults.html in /Forms/ folder). Is this supported?

If it's not supported, I got the code ready (https://github.com/Puzzlepart/prosjektportalen/blob/master/src/js/Project/MetadataDefaults.ts) and would like to include this in `pnpjs` if it's okay @patrick-rodgers.

**Comment by patrick-rodgers** [comment]
Sure, that's great. Probably as a method on folder?

**Comment by olemp** [comment]
That's what I thought! 

The `PnP-PowerShell` commandlet is `Set-PnPDefaultColumnValues` so probably something like this?

```typescript
sp.web.lists.getByTitle('Documents').rootFolder.defaultColumnValues.update({ MetadataField: "-1;#label|id" })
``

or just 

```typescript
sp.web.lists.getByTitle('Documents').rootFolder.setDefaultColumnValues({ MetadataField: "-1;#label|id" })
``

**Comment by olemp** [comment]
.. but how can we access the list/library of a folder from the folder instance @patrick-rodgers? 

We might also need access to the list to ensure the `ItemAdded` event receiver.

We need to `[LIBRARY_URL]/Forms/client_LocationBasedDefaults.html`.

**Comment by patrick-rodgers** [comment]
I like your second option `setDefaultColumnValues` attached to the folder object. You can use the getParent method of Queryable - but that won't necessarily work in nested folders you'd need to test it. Or you could loop on selecting the Folder's ParentFolder property - see if you can recurse up that way. Or do something with the properties object:

```TypeScript
  const f = sp.web.lists.getByTitle("Documents").rootFolder;
  f.append("Properties");
  const r = await f();
```

r Includes:
vti_x005f_listname:"{7291BDF6-B218-40C8-AF98-3011B83DF336}"
vti_x005f_listtitle:"Documents"

That should be enough to get you what you need. So far as I know all folders should have those props.

**Comment by patrick-rodgers** [comment]
I'll be honest, working on this but the effort is making me question the value. It feels like adding a hacky implementation on top of an already hacky implementation. BUT I get to use some silly regex, and that can never fail - right? Right?

**Comment by olemp** [comment]
Haha, I understand you @patrick-rodgers. Getting this into pnpjs would make it much easier to use this kind of functionality, but you might be right about the hackyness of a solution for this. 

.. you get to use some lovely regex though 😎

**Comment by patrick-rodgers** [comment]
This is added and will be part of 2.0.4
