### ISSUE TITLE
Result of sp.utility.containsInvalidFileFolderChars() incorrect for some filenames

### ISSUE THREAD

**Issue by toblum** [pnp/pnpjs#922]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.7]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
If I'm correct, the function sp.utility.containsInvalidFileFolderChars() should return "true" for all given filenames that contain disallowed characters.

### Observed Behavior

- containsInvalidFileFolderChars("test:vvv.txt") returns true, correct because of :
- containsInvalidFileFolderChars("test:vvvv.txt") returns false, incorrect 
- containsInvalidFileFolderChars("test:vvvvv.txt") returns true, correct because of :
- containsInvalidFileFolderChars("test:vvvvvv.txt") returns false, incorrect 

### Steps to Reproduce
I have prepared a sample to test here: [https://codesandbox.io/s/friendly-carson-444hn](https://codesandbox.io/s/friendly-carson-444hn?fontsize=14).

Short example:
```typescript 
import { sp } from "@pnp/sp";
console.log(sp.utility.containsInvalidFileFolderChars("test:vvvvv.txt"));
```
Tested with lastest chrome (78.0.3904.97).
I'm unsure why this happens, maybe a unicode issue in the regex?

Thank you for your feedback!

Best regards
Tobias

**Comment by patrick-rodgers** [comment]
Thanks, we'll have a look!
