### ISSUE TITLE
graph.planner.tasks.add potential issue with assignments

### ISSUE THREAD

**Issue by JMTeamway** [pnp/pnpjs#925]
### Category
- [x] Bug

### Version
Please specify what version of the library you are using: [ @pnp/graph": "^1.3.7  ]
Please specify what version(s) of SharePoint you are targeting: [   online    ]

### Expected 
I am creating a new Planner task with assignments.
After the function is executed, the task is created in Planner and the assignments are correctly added.

### Observed Behavior
The Task is correctly created, but with no assignments at all.

### Steps to Reproduce

```typescript 
import { graph } from '@pnp/graph';

        let assignments = {} as {
          [id: string]: {
            "@odata.type": string;
            "orderHint": string;
            };
          };

          assignments[<ExistingUserId>] = {
            "@odata.type": "#microsoft.graph.plannerAssignment",
            "orderHint": " !"
          };
graph.planner.tasks.add(<ExistingPlanId>,"New Task", assignments,<ExistingBucketId>).then([...]);

```
Having a look at the code of planner.ts where data are JSON formated (https://github.com/pnp/pnpjs/blob/dev/packages/graph/src/planner.ts) at line 137 :
```typescript
 body: jsS(postBody)
```
I debugged and found this Json as output of the function :
```typescript
{
	" planId ":" S0u8n_SGGkWHD21huvAQ0JcAFczj ",
	" title ":" TEST # 01 ",
	" b0d2b014 - 9a47 - 4608 - b7e8 - a76cd4803f5d ":{
		" @ odata.type ":" # microsoft.graph.plannerAssignment ",
		" orderHint ":"!"
	},
	" bucketId ":" YgqRgC - Opk - kioot7TKSzJcACd_V "
}
```

Having a look at the Graph API for assignments (https://docs.microsoft.com/fr-fr/graph/api/planner-post-tasks?view=graph-rest-1.0&tabs=http#example), I think that the data block related to assignments should not be put at the root of the body, but inside an "assignments" field in the body :
```typescript
POST https://graph.microsoft.com/v1.0/planner/tasks
Content-type: application/json
Content-length: 285

{
  "planId": "xqQg5FS2LkCp935s-FIFm2QAFkHM",
  "bucketId": "hsOf2dhOJkqyYYZEtdzDe2QAIUCR",
  "title": "Update client list",
  "assignments": {
    "fbab97d0-4932-4511-b675-204639209557": {
      "@odata.type": "#microsoft.graph.plannerAssignment",
      "orderHint": " !"
    }
  },
}
```

I think the issue may be at line 128 :
```typescript
        let postBody = extend({
            planId: planId,
            title: title,
        }, assignments);        // Here the data should be put in an "assignments" field
```

If I'm wrong, please let me know how I could properly add an assignment.

Thank you for your help!

**Comment by JMTeamway** [comment]
@patrick-rodgers  : 
Hi patrick, I saw you worked recently on this file, so I mention you on this comment, I hope it is ok to do so ...
Please have a look at this bug, I think I give enough informations to fix it within minutes ;-)

Thanks for all the good work you provide to the community !

**Comment by patrick-rodgers** [comment]
Thanks @JMTeamway for your detailed analysis. Just out of curiosity since you've done so much work to investigate are you interested in submitting a PR to address this?

**Comment by JMTeamway** [comment]
Hi Patrick, I’d love and would be honored to do so in fact 😊

The only reason I did not is that I am not sure how to test my fix.

-	I can clone the repository
-	I can (try to) fix the issue

Then 
-	I would have to « build » the library maybe
-	Remove references to pnp/graph from my code (SPFX REACT Webpart)
-	Add a reference to my local version of pnp/graph

Then
-	I can do test and validate the fix
-	I can Commit my code
-	I can Create a Pull request


You know what ? There must be a first time to every things ! 

I give a try, maybe I’ll ask for a bit of help, and then I enter the big family of people who cares !

**Comment by patrick-rodgers** [comment]
You already care by reporting the issue, that's great! If you need some help @PopWarner sometimes has time to assist folks with their first PR and can maybe help out. Appreciate it!
