### ISSUE TITLE
[V2] Build in IE11 compatibility mode

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/pnpjs#926]
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.0-13 ]

Please specify what version(s) of SharePoint you are targeting: [2016, Online]

### Expected / Desired Behavior / Question
I would expect the solution to transpile and work in compatibility mode when I add the following lines:
```
// set ie 11 mode
sp.setup({
    ie11: true
});
```

### Observed Behavior
When I add the above lines, the solution errors out at build time. Without those lines it builds just fine.

### Steps to Reproduce
The code below errors out for me at build time (npm run build). If I remove the setup lines it works fine.

```typescript 
import "@pnp/polyfill-ie11";
import React, { useState } from "react";

import { sp } from "@pnp/sp";

// set ie 11 mode
sp.setup({
    ie11: true
});

import "@pnp/sp/lists/web";
import "@pnp/sp/items/list";
import { Web } from "@pnp/sp/webs";

```

Thank you!

**Comment by patrick-rodgers** [comment]
Can you share the error?

**Comment by PathToSharePoint** [comment]
@patrick-rodgers this is what I got (with specific paths removed). Maybe I should use the PnP logging module?
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v13.1.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle pnpjsv2beta@0.1.0~prebuild: pnpjsv2beta@0.1.0
6 info lifecycle pnpjsv2beta@0.1.0~build: pnpjsv2beta@0.1.0
7 verbose lifecycle pnpjsv2beta@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle pnpjsv2beta@0.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin...
9 verbose lifecycle pnpjsv2beta@0.1.0~build: CWD: C:\Users\...
10 silly lifecycle pnpjsv2beta@0.1.0~build: Args: [ '/d /s /c', 'react-scripts build' ]
11 silly lifecycle pnpjsv2beta@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle pnpjsv2beta@0.1.0~build: Failed to exec build script
13 verbose stack Error: pnpjsv2beta@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid pnpjsv2beta@0.1.0
15 verbose cwd C:\Users\...
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v13.1.0
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 1
22 error pnpjsv2beta@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the pnpjsv2beta@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by patrick-rodgers** [comment]
Ok, that error doesn't really help. Are you able to provide any more context around what you are doing?

**Comment by PathToSharePoint** [comment]
@patrick-rodgers just to confirm, are you saying that you are able to build successfully with the above code?
If you don't see any issue with my code, I'll do more testing on create-react-app and SPFx.
Right now I am just testing the above code, there is nothing else. The objective is to validate that I can do a build for an organization whose official browser is still IE11.

**Comment by patrick-rodgers** [comment]
I am able to build the library in ie11 compat mode and run it. You haven't described full steps to reproduce the error, shared an error message we can act on, or shared a repo we can clone to test or reproduce. The error you shared is just the npm error saying the build failed - I don't see anything related to why the build failed or a message that points to something within this library.

**Comment by PathToSharePoint** [comment]
I think I found my mistake. In the code above, I placed sp.setup right after the sp import, while I should have finished all the imports first :-(
