### ISSUE TITLE
SP setup

### ISSUE THREAD

**Issue by artalvarado11** [pnp/pnpjs#93]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.0.4     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

This there a way to setup the library to use a different context with elevated permissions maybe an app context in a spfx extension instead of the user context?

Thank you for your feedback!

**Comment by KEMiCZA** [comment]
I don't think this is possible client side (running in the browser of the user). You will need to set up an API (ie. Azure Function, WebApi) that you can call to do your backend elevated logic.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. There is no concept of elevated permissions or app context within client-side code.
