### ISSUE TITLE
getChanges missing on Site object

### ISSUE THREAD

**Issue by johannes-z** [pnp/pnpjs#930]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.7]

Please specify what version(s) of SharePoint you are targeting: [-]

### Expected / Desired Behavior / Question

`/_api/site/getChanges` should be available through Site.getChanges.

### Observed Behavior

```
const site = new Site('/...')
site.getChanges(...)
```

`getChanges` does not exist on `Site`. `/_api/site/getChanges` is valid though.

**Comment by patrick-rodgers** [comment]
Just curious, why mark this as a bug? We can certainly look at adding this functionality but wouldn't that classify as a enhancement?

**Comment by johannes-z** [comment]
I marked it as an enhancement instead. I though it might have been an initial oversight, i.e. forgotten to be implemented.
