### ISSUE TITLE
SPHttpClient access external url

### ISSUE THREAD

**Issue by robiharid** [pnp/pnpjs#932]
How do I setup SPHttpClient properly?

`import { sp, SPHttpClient } from "@pnp/sp";
`
`
  const client = new SPHttpClient();

  client
    .get(
      feedUrl,
      {
        headers: {
          Accept: "application/json;odata=verbose"
        }
      } /* as FetchOptions, but this is not required */
    )
    .then(res => {
      console.log("res is ", res.text());
      // (res: Response) Fetch's Response
      // ...
    })
    `.catch(console.log);`

This is my current code using fetch:
`return fetch(feedUrl)
    .then(resp => resp.text())
    .then(resp => {
      const xml = convert.xml2js(resp, { compact: true });

      // const rssPosts = xml["rss"]["channel"]["item"];
      const rssPosts = xml["rss"]["channel"]["item"];
      rssPosts.forEach(post => {
        Object.keys(post).forEach(
          key => (post[key] = post[key]._text) || delete post[key]
        );
      });
      return rssPosts;
    });`

I am trying to fetch RSS feeds:

  //https://podcasts.files.bbci.co.uk/b006qj8q.rss
  //https://www.sciencedaily.com/rss/matter_energy/engineering.xml

BBC one works but sciencedaily is giving me CORB issues - SPHttp seems like friendly?

**Comment by patrick-rodgers** [comment]
CORS issues are enforced by the browser and there isn't anything we can do to address this. IF the server supports CORS you can have a look at [using fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) and the `mode: 'cors'` option. There is no benefit to using the client from this library to call non-SharePoint urls. Going to close this issue as it is not related to the library. Thanks!
