### ISSUE TITLE
Is there a way to get count of items in a view 

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/pnpjs#936]
is there any rest query that can get me count of items in a list view

**Comment by koltyakov** [comment]
Not sure will it work for all the cases but you can try something this way, at least adopt and modify the approach:

```typescript
(async () => {
  const list = sp.web.lists.getByTitle(listTitle);
  const { ViewQuery } = await list.views.getByTitle(viewTitle).select('ViewQuery').get();
  const items = await list.renderListDataAsStream({
    ViewXml: `
      <View>
        <Query>
          ${ViewQuery}
          <GroupBy Collapse="TRUE">
            <FieldRef Name="FileDirRef" />
          </GroupBy>
        </Query>
      </View>
    `
  });
  console.log(items.Row[0]['FileDirRef.COUNT.group']);
})();
```

With a view with more items that throttling limit it won't work. Also, if items are located in folders, something else should be used for grouping rather than FileDirRef.

**Comment by sympmarc** [comment]
You could also just retrieve the ID for all the items and count those rows. Make sure you use $top=5000 to ensure you get all items up to the 5000 item limit). Or, in your ViewQuery, <RowLimit>5000</RowLimit>.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Moving forward @harshdamaniahd - general "how do I" questions might be more appropriate for the [Microsoft Tech Community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev). Thanks!
