### ISSUE TITLE
InBatch function to get multiple UserProfile details

### ISSUE THREAD

**Issue by nsksaisaravana** [pnp/pnpjs#939]
I wonder whether I can batch the filter queries to get multiple user profile details, currently, I don't find InBatch function available for @pnp/sp/profiles

### Category
- [ ] Enhancement
- [ ] Bug
- [ *] Question
- [ ] Documentation gap/issue

**Comment by nsksaisaravana** [comment]
currently, I am using below method to get the user profile details. How do i convert this to a barch

```
sp
  .profiles
  .getPropertiesFor(loginName).then((profile: any) => {

    console.log(profile.DisplayName);
    console.log(profile.Email);
    console.log(profile.Title);
    console.log(profile.UserProfileProperties.length);

    // Properties are stored in inconvenient Key/Value pairs,
    // so parse into an object called userProperties
    var properties = {};
    profile.UserProfileProperties.forEach(function(prop) {
    properties[prop.Key] = prop.Value;
    });
    profile.userProperties = properties;

}
```

**Comment by koltyakov** [comment]
I'd suggest getting all profiles with search API instead.

**Comment by patrick-rodgers** [comment]
Hi @nsksaisaravana - it looks like this is answered. Moving forward the [Microsoft Tech Community](https://techcommunity.microsoft.com/t5/SharePoint-Developer/bd-p/SharePointDev) might be a more appropriate "How do I" type questions that are not directly related to this library. Thanks!
