### ISSUE TITLE
SharePoint 2016 - Supported version?

### ISSUE THREAD

**Issue by richardegleston** [pnp/pnpjs#94]
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Expected / Desired Behavior / Question
What version of this library can I use for my SharePoint 2016 on-premise project?
I believe for 2016, I need to be using typescript version 2.2.2.

**Comment by patrick-rodgers** [comment]
Closing with the merge of #95 to include this information in the docs. Please _reopen_ if you have additional questions. Thanks!
