### ISSUE TITLE
Unexpected ItemAddResult when List has column named "value". (@pnp/sp)

### ISSUE THREAD

**Issue by IGkougkousis** [pnp/pnpjs#943]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.6]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online (16.0.19506.12024)]

### Expected Behavior
The property `data` of `ItemAddResult`  should return the properties of the added list item.

### Observed Behavior
If the list contains a column called `value` then the data property is a single primitive (not object) value containing the contents of the field `value` that was posted.

### Steps to Reproduce
Create a new custom list (for this example, I created a list called `ListWithValueCol`). Create a new column called `value`. Column type: I tried number and single line of text, both had the same problem.

```typescript 
sp.web.lists.getByTitle("ListWithValueCol").items.add({
    'Title': 'New entry for my list',
    'value': '123'
}).then((iar: ItemAddResult) => {
    console.log('Property "data" of the ItemAddResult: ', iar.data);
    console.log('The whole ItemAddResult: ', iar);
});
```

Console output:
```
app.component.ts:66 Property "data" of the ItemAddResult:  123
app.component.ts:67 The whole ItemAddResult:  {data: "123", item: Item}
```

Conversely, another list that doesn't have a `value` column behaves like this:

```typescript
sp.web.lists.getByTitle("ListWithoutValueCol").items.add({
      'Title': 'New entry for my list without value col',
      'MyFavNumber': 125,
      'MyFavDate': new Date('2019-06-30'),
      'MyFavValue': '123'
    }).then((iar: ItemAddResult) => {
      console.log('Property "data" of the ItemAddResult: ', iar.data);
      console.log('The whole ItemAddResult: ', iar);
    });
```

The `data` property, as expected:
```
{
    "odata.metadata": "https://xxx.sharepoint.com/sites/cm/_api/$metadata#SP.ListData.ListWithoutValueColListItems/@Element",
    "odata.type": "SP.Data.ListWithoutValueColListItem",
    "odata.id": "4ac4f3c8-721d-4aa3-a1e6-c7b0d6b5b4dd",
    "odata.etag": "\"1\"",
    "odata.editLink": "Web/Lists(guid'9b6f7a05-c16f-4517-9de9-63a680c3b247')/Items(2)",
    "FileSystemObjectType": 0,
    "Id": 2,
    "ServerRedirectedEmbedUri": null,
    "ServerRedirectedEmbedUrl": "",
    "ContentTypeId": "0x0100ED0E265B31B2DD49B413D53D5FFF06CC",
    "Title": "New entry for my list without value col",
    "ComplianceAssetId": null,
    "MyFavNumber": 125,
    "MyFavDate": "2019-06-30T00:00:00Z",
    "MyFavValue": "123",
    "ID": 2,
    "Modified": "2019-11-27T14:27:49Z",
    "Created": "2019-11-27T14:27:49Z",
    "AuthorId": 10,
    "EditorId": 10,
    "OData__UIVersionString": "1.0",
    "Attachments": false,
    "GUID": "3d0cbfd5-ed48-4410-a02a-600721691afa"
}
```

**Comment by patrick-rodgers** [comment]
We won't fix this - issue is related to parsing the responses across the different verbocity levels getting back from SharePoint. You can see that [code here](https://github.com/pnp/pnpjs/blob/dev/packages/odata/src/parsers.ts#L70). One of the OData properties is "value" - which we wouldn't be able to tell apart from your item's field name in any generic way.

For add we would have to change the method signature to take a parser - and then make that change in a lot of other places to support this edge case.

A workaround when retrieving the item:

## v1
```TypeScript
import { JSONParser } from "@pnp/odata";
import { sp } from "@pnp/sp";

const r = await sp.web.lists.getByTitle("ValueColumnList").items.getById(1).get(new JSONParser());

console.log(JSON.stringify(r, null, 2));
```
## v2
```TypeScript
import { JSONParser } from "@pnp/odata";
import { sp } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

const r = await sp.web.lists.getByTitle("ValueColumnList").items.getById(1).usingParser(new JSONParser())();

console.log(JSON.stringify(r, null, 2));
```

**Another workaround would be to name the column "Value" which would bypass this issue completely.**

Understand you will be upset but understand that the level of change to fix this edge case is too much compared to the impact. It only affects fields named "value" or "d".

**Comment by IGkougkousis** [comment]
Thanks for taking the time to test this.

I'm not upset at all, thankfully I'm developing something new and it's totally OK for me to just rename the column. It just stumped me for at least a day, because (it seemed to me at the time) some of my add queries were returning correct `ItemAddResult` and others weren't and it took me a long time figure out it was the `value` column that was the problem in the first place.

**Comment by patrick-rodgers** [comment]
Awesome! Yes, a weird quirky behavior to be sure. Glad its not a big deal and there is an easy path forward! Thanks for using the library and letting us know - if you run into anything else be sure to reach out. Thanks!
