### ISSUE TITLE
Updating Primitive Type Properties in User Profile

### ISSUE THREAD

**Issue by arunakshi** [pnp/pnpjs#944]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

### Category
- [X ] Question

### Version

Please specify what version of the library you are using: [   1.3.7      ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online      ]

### Expected / Desired Behavior / Question
I am trying to update a custom boolean user profile property using pnp/sp profiles and also tried with REST API via SPHttpClient. I expect that the property will be updated using the setSingleValueProfileProperty method.

### Observed Behavior
The method itself can update only the String properties. Still I used the method: setSingleValueProfileProperty for udpating Boolean property and I am getting the following error when I try either approach. 

{"odata.error": {"code": "- 1, Microsoft.Data.OData.ODataException", "message": {"lang": "de-DE", "value": "A primitive value can not converted to the expected type \ "Edm.String \". For details, see the inner exception. "}}}

Is there any other way to update the Primitive User Profile Properties from SPFX webpart.
### Steps to Reproduce
- created new user profile property of Boolean type
- From SPFX webaprt, tried to update the property when user finished the action.

```My Code
 public updateUserProfileWithSingleValue(propertyName: string, propertyValue:any):Promise<boolean> {
        return new Promise<boolean>((resolve, reject) => {
            let accountName = "i:0#.f|membership|" + this._pageContext.user.loginName;
           
            sp.profiles.setSingleValueProfileProperty(accountName, propertyName, propertyValue).then((result) => {
                resolve(true);
            }).catch((error) => {
                reject(false);
            });
        });
    }
```

**Comment by koltyakov** [comment]
Why you are consider this as a bug? The payload and data types should correspond to what is expected with the API. By providing `propertyValue: **any**` you literally taking responsibility for what is passed as a parameter.

**Comment by arunakshi** [comment]
Koltyakov, thank you very much for the reply. Yes, you are right, its not a bug and I removed that label but I expect that the API method allow other Primitive types as well to update. If I pass boolean to the API method: setSingleValueProfileProperty, I get the following error shown from typescript. _Argument of type 'boolean' is not assignable to parameter of type 'string'_

I used propertyValue: **any** in my code to allow any type but the API method is not even allowing if I change the type to boolean parameter in my code.

If it is not in scope, is there any other way to update Primitive Type properties via Pnp.

**Comment by koltyakov** [comment]
But it a specific API doesn't allow anything but stringified value, it can't "workaround" by `any`. A value should be correctly formed correspondingly to the expected by the API. Regarding `setSingleValueProfileProperty` it's always, to my knowledge, a string no matter a type of UPS property. I might be wrong, if so, please point REST API raw call which works with other data types. Did you try passing a string with `"true"` or `"false"`.

**Comment by arunakshi** [comment]
Ah ok. Yes, it works by passing a string with "true". Thank you. I am closing this question.
