### ISSUE TITLE
How to encode % in the file name  while uploading to share point using pnp js core

### ISSUE THREAD

**Issue by ChandanPintu** [pnp/pnpjs#945]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     "@pnp/pnpjs": "^1.3.3",]

Please specify what version(s) of SharePoint you are targeting: [   online      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Question
**how to add a file which have a % symbol to share point ?**

const newFileName = "EDS%1.pdf"

 siteUrl.files.add(encodeURIComponent(newFileName), file, true).then((response) => {
                            submit(null, true);
                        }).catch((err) => {
                            submit(err, true);
                        });

**Comment by umaknow-annie** [comment]
I have the same issue. I am using the version 1.3.7 of the library. When I try to copy a file that contain a % in is name, it will be change by %25.

Example :
```Typescript
const fileServerRelativeUrl = "/sites/MySite/Shared Documents/Pourcent%.txt";
const path = encodeURIComponent(fileServerRelativeUrl.replace(/'/g, "''"));
sp.web.getFileByServerRelativePath(path).copyTo("/sites/MySite/OtherLib");
```
In this example, the file will be copied but the name of the document will be Pourcent%25.txt

**Comment by patrick-rodgers** [comment]
I think we need to update how we add files to use the [newer pound percent safe methods](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api).

**Comment by patrick-rodgers** [comment]
Have added a new method to the files collection named addUsingPath. Usage will be:

```TypeScript
await sp.web.lists.getByTitle("Documents").rootFolder.files.addUsingPath(encodeURIComponent("testd22%#.txt"), "Hello.");
```
