### ISSUE TITLE
PnP JS Code not running in Safari Browser

### ISSUE THREAD

**Issue by spvjebaraj** [pnp/pnpjs#947]
Team,
As per the existing issue in the below link, I have created the [repository](https://github.com/spvjebaraj/spo-pnp-angular) in github to check the code.
[Not able to view SharePoint site in Safari](https://github.com/pnp/pnpjs/issues/917)

Kindly download the code and do the deployment which is mentioned in the ReadMe.md file. Still am facing the issue in Safari. Not able to view the results.

Please help me.

**Comment by koltyakov** [comment]
Did you try removing everything Angular & RxJS specific and try core minimum with PnPjs? 
So you're saying that `sp.profiles.myProperties.get()` fails in Safari on iOS being hosted on a classic page, correct?

**Comment by spvjebaraj** [comment]
Hi Andrew,
Yes it is correct and also if any code written with PnP JS is not working. As per your request, I have removed RxJS and updated the code to return Promise. Even-though it is not working in Safari.
Please check the updated code in my repository.
Please help me.

**Comment by patrick-rodgers** [comment]
IF the error in Safari is a CORS error I am not sure we can do much to help. What other things have you tried? How is this code deployed (is it running inside SharePoint or from your own URL)? The fast that you've said the code works everywhere else points to an issue outside this library.

Do any of these threads help:
- https://stackoverflow.com/questions/16824661/cors-request-not-working-in-safari
- https://forums.asp.net/t/2127659.aspx?CORS+problem+with+iOS+Safari
- https://groups.google.com/forum/#!topic/angular/3hP4JpTHLYY

**Comment by spvjebaraj** [comment]
I have created WebPart page and added the CEWP. In that I referred the index.html file which is uploaded in document library. That document library have all the necessary files which is generated by bg build command by Angular. I will try the links which you have shared and update you.

**Comment by spvjebaraj** [comment]
The above threads didn't help me. Did any one test my solution in Mac? Please help me.
