### ISSUE TITLE
While creating term inside another term, it throws error though term gets created

### ISSUE THREAD

**Issue by srujalsk** [pnp/pnpjs#948]
During the creation of term under another term using method ITerm.addTerm, it throws an exception. But, term does get created as expected.

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.7]

Please specify what version(s) of SharePoint you are targeting: [ONLINE]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*Term should get created without any error, term does get created but it throws exception.*

### Observed Behavior
*addTerm throws unexpected exception, while it works as expected*

### Steps to Reproduce
*Use the below code snippet to reproduce the issue.*

```
const term = await termStore.getTermSetById("aaa-aaa-aaa").terms.select("Name", "PathOfTerm").getByName("xyz").get();

        try {
            newTerm = await term.addTerm(tag.toUpperCase().trim(),1033,true);   
        } catch (error) {
            context.log.warn("SKIPPING ERROR !");
            context.log.warn(error); 
        } 


```

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.
* When selecting a category remove the space between the square brackets and add a x: [ ] --> [x]
* When adding code please use the following syntax to ensure readability and formatting  
  <div>```typescript CODE_GOES_HERE ```</div>

Thank you for your feedback!

**Comment by patrick-rodgers** [comment]
Can you share the exception that is thrown?

**Comment by koltyakov** [comment]
LOL in a second I thought that it was fake @patrick-rodgers, sorry for offtopic.

**Comment by patrick-rodgers** [comment]
Nope - it me.

**Comment by srujalsk** [comment]
It throws "Access Denied" Exception, though I have assigned the following permission to my App
```

<AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
</AppPermissionRequests>
```

**Comment by koltyakov** [comment]
@srujalsk pretty logical expecting access denied when no permissions granted ;)
Check [this article](https://www.techmikael.com/2018/08/modifying-terms-using-app-only-tokens.html) by @wobba on Taxonomy permissions scopes for Add-Ins.

**Comment by srujalsk** [comment]
@koltyakov Thanks a lot for it, let me test it with this solution.

But, the thing that questions me still is that why the hell, I am able to create the term though I don't have enough permission.

I guess there is some issue, either in SharePoint or Library.

**Comment by wobba** [comment]
You need to have `<AppPermissionRequest Scope="http://sharepoint/taxonomy" Right="Write" />` as well for writing terms - and I thought I had added the app@sharepoint part to the official docs, but seems I forgot. Will make a note of this.

**Comment by patrick-rodgers** [comment]
Going to close this as answered. Thanks all!
