### ISSUE TITLE
While trying to add multiple items in SharePoint List using Batch giving an error: 'Error making HttpClient request in queryable [400] Bad Request'

### ISSUE THREAD

**Issue by HarshalWadaskarDev** [pnp/pnpjs#950]
### Category
- [x] Bug
- [x] Question

### Version

Please specify what version of the library you are using: [   1.3.7      ]

Please specify what version(s) of SharePoint you are targeting: [    SharePoint Online     ]

### Expected / Desired Behavior / Question
Multiple items should get added in SharePoint List using Batch. 

### Observed Behavior
It is giving below error:
Uncaught (in promise) Error: Error making HttpClient request in queryable [400] Bad Request ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"Invalid request."}}}
    at new HttpRequestError (parsers.ts:13)

```typescript 
import { sp } from "@pnp/sp";
let list = sp.web.lists.getById('ae1a9823-b339-4461-b4ba-bf1f7bd3551a');
    let batch = sp.web.createBatch(); 
    list.items.inBatch(batch).add({ 'Title': "Batch 1" }).then(b => {
        console.log(b);
    });
    list.items.inBatch(batch).add({ 'Title': "Batch 2" }).then(b => {
        console.log(b);
    });    
    batch.execute().then(d => 
      console.log("Done")
    ).catch(e => {
      console.log(e);
    });
```

**Comment by patrick-rodgers** [comment]
Are you working in SPFx and have you done the [required setup call](https://pnp.github.io/pnpjs/documentation/getting-started/#establish-context)?

**Comment by HarshalWadaskarDev** [comment]
I am working in SPFx for SharePoint Online.

**Comment by patrick-rodgers** [comment]
Part 2 of the question: Have you done the required setup call?

**Comment by ncmadhan1989** [comment]
@harshal use web object instead sp object,its working fine for batch calls, previously me too get the same error

**Comment by HarshalWadaskarDev** [comment]
No.

**Comment by ncmadhan1989** [comment]
import { Web } from '@pnp/sp
const web = new Web(this.props.context.pageContext.web.absoluteUrl);

**Comment by HarshalWadaskarDev** [comment]
@ncmadhan1989 Thank you. Your workaround has worked.

**Comment by patrick-rodgers** [comment]
That workaround shouldn't be needed if you are doing the setup step?? That code is perfectly valid and if that solves your problem great, but if you are doing setup (you haven't confirmed if you are or not) it shouldn't be required.

**Comment by HarshalWadaskarDev** [comment]
@patrick-rodgers  I hadn't added the setup step in my code earlier. Now added the setup part in code and batch is working as expected with SP. Thank you for pointing me at right direction.

**Comment by patrick-rodgers** [comment]
Great, thanks for confirming. I'll close the issue.

**Comment by rvsharma** [comment]
> import { Web } from '@pnp/sp
> const web = new Web(this.props.context.pageContext.web.absoluteUrl);

how to use this in code

**Comment by koltyakov** [comment]
@rvsharma this is described in detail in [docs](https://pnp.github.io/pnpjs/getting-started/#establish-context).

**Comment by ncmadhan1989** [comment]
> > import { Web } from '@pnp/sp
> > const web = new Web(this.props.context.pageContext.web.absoluteUrl);
> 
> @ncmadhan1989 @patrick-rodgers how to use this in code

if using v1 of pnp simply use same as above ,incase of v2 
import { Web } from '@pnp/sp/presets/all
const web =  Web(this.props.context.pageContext.web.absoluteUrl);

**Comment by rvsharma** [comment]
@ncmadhan1989 @patrick-rodgers thank you so much for your support. i was using v2.
