### ISSUE TITLE
[V2] Wrong install documentation?

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/pnpjs#952]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ v2 beta ]

Please specify what version(s) of SharePoint you are targeting: [ all ]

### Expected / Desired Behavior / Question
npm should install v2 beta

### Observed Behavior
When following the instructions on the v2 beta page, v 1.3.7 gets installed:
https://pnp.github.io/pnpjs/documentation/v2-beta/getting-started/

### Steps to Reproduce
Follow instructions in the above page.

Thank you!

**Comment by PopWarner** [comment]
Great question @PathToSharePoint.

I believe the docs are meant to be in effect once v2 goes fully live. 

For the beta testing period, I believe we would want to follow the guidance at the pinned Beta testing help issue:
https://github.com/pnp/pnpjs/issues/900

I could be wrong, so I’ll defer to @patrick-rodgers on the final answer though. :)

**Comment by patrick-rodgers** [comment]
Yes - for now you need to append the `@beta` version to the install string. As David mentioned the issue has the correct install command listed. Once we go live the beta part will not be needed and the install will install 2.x as it would be the latest.

**Comment by PathToSharePoint** [comment]
Right, the issue has the correct information. I was just wondering why the page in the "v2-beta" branch doesn't. Should I interpret this as an imminent move out of beta? :-)

**Comment by patrick-rodgers** [comment]
We will release v2 this month (Dec 2019). I updated the milestone to have a date a few days ago. Not sure that will 100% be the day, but it will happen this month. The page isn't updated because there are only so many hours in my life and updating it to include @beta and then remembering to remove that just seemed like time I could not spend. Going to close this as the question is resolved. Thanks!
