### ISSUE TITLE
[V2] Issues found in docs

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/pnpjs#956]
### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ v2 ]

### Observed 
Just reporting a couple issues I came across while browsing the docs.

https://pnp.github.io/pnpjs/documentation/v2-beta/beta-versions.md
The above page is not found. It is linked from the menu entry "Install Beta Versions".

https://pnp.github.io/pnpjs/documentation/v2-beta/SPFx-On-Premesis-2016/
This page reads "on premesis" instead of "on premises" in a couple places, including the URL itself.
occurance => occurrence

Thank you!

**Comment by PathToSharePoint** [comment]
I am also getting an error when following the instructions for SP 2016, not sure if I missed something:

``-- @microsoft/sp-build-web@1.1.0
  `-- @microsoft/gulp-core-build-typescript@3.1.1
    +-- @microsoft/api-extractor@2.3.8
    | `-- typescript@2.4.2
    `-- UNMET PEER DEPENDENCY typescript@2.4.2  invalid

npm ERR! peer dep missing: typescript@~2.0.3 || >=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev, required by gulp-typescript@3.1.7
npm ERR! peer dep missing: typescript@>=2.0.0, required by tslint@4.5.1`

**Comment by PathToSharePoint** [comment]
I did a second test and got a similar error message.

Shouldn't the instructions be to run a clean install (npm ci) rather than a simple npm install?

**Comment by patrick-rodgers** [comment]
Thanks, fixed the typos!
