### ISSUE TITLE
Adding file to a library fails on a modern page

### ISSUE THREAD

**Issue by sallaadithya** [pnp/pnpjs#958]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.3.7     ]

Please specify what version(s) of SharePoint you are targeting: [   SharePoint Online      ]

### Expected / Desired Behavior / Question
When a file is uploaded using html input FILE type to a document library (Site Pages) on a modern communication site, the file should be added.

### Observed Behavior
When uploading a file to a document library (Site Pages) on a modern communication site, throws an exception.

### Steps to Reproduce
When running the script on modern page, the script throws an error, but on a team site's Article page, there was no issue.
On inspection, the post URL is appending the document library URL on modern page which is described in attachment, please find the file as attachment.
<img width="960" alt="PnP_FileUpload_Error" src="https://user-images.githubusercontent.com/39057966/70600124-f1361b00-1c14-11ea-85f1-1d424f8c24c5.png">

```typescript 
import { sp } from "@pnp/sp";
private uploadFileFromControl(): void {
    //Get the file from File DOM
    var files = this._input.files;
    var file = files[0];
    //Upload a file to the SharePoint Library    
    sp.web.getFolderByServerRelativeUrl(this.props.context.web.serverRelativeUrl + "MyDocs")
      .files.add(file.name, file, true)
      .then((data) => {
        alert("File uploaded sucessfully");
      })
      .catch((error) => {
        alert("Error in uploading");
      });
  }

Thank you for your feedback!

**Comment by koltyakov** [comment]
https://pnp.github.io/pnpjs/documentation/getting-started/#getting-started-with-sharepoint-framework

**Comment by sallaadithya** [comment]
Thanks for the quick reply, it worked!!
