### ISSUE TITLE
Package Specific Serving Error

### ISSUE THREAD

**Issue by thechriskent** [pnp/pnpjs#96]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Expected Behavior
Following the [debugging](https://pnp.github.io/pnpjs/debugging.html) instructions, running `gulp serve --p sp` should serve the @pnp/sp package.

### Observed Behavior
Running this command (with any package) results in `TypeError: Cannot read property 'filter' of undefined` (tools\gulptasks\args.js:27:44). The issue appears to be from a missing `packages` property on the `inConfig` parameter. The serve task appears to be calling the `processConfigComdLine` method with an empty object `{}` which is causing the problem.

**Comment by patrick-rodgers** [comment]
Thanks for reporting this, will get it fixed.

**Comment by patrick-rodgers** [comment]
Fixed, not yet merged. Will close issue on merge. Thanks!

**Comment by patrick-rodgers** [comment]
Fixed in 1.1.0
