### ISSUE TITLE
Office 365 / Azure setup - inBatch support

### ISSUE THREAD

**Issue by tarundhillon** [pnp/pnpjs#961]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.3.7    ]

Please specify what version(s) of SharePoint you are targeting: [Office 365]   

### Expected / Desired Behavior / Question
I have two sites ( separate subscriptions & domains) for Office 365 SharePoint and the  pnp-js batching works for one and does not work for the other https://github.com/SharePoint/PnP-JS-Core/wiki/Batching operations. For everything else both sites work fine.

I have compared the below API Permissions for the two sites which are identical and stated below 

Microsoft Graph (5) >> User.Read, email, offline_access, openid, profile
SharePoint (2)  >> AllSites.FullControl, AllSites.Manage

### Observed Behavior
For a simple batch operations such as 

```typescript
let batch = pnp.sp.createBatch();
pnp.sp.web.lists.inBatch(batch).get().then(r => {console.log(r)});

pnp.sp.web.lists.getByTitle("Tasks").items.inBatch(batch).get().then(r => {
    console.log(r)
});
batch.execute().then(() => console.log("All done!"));
```
**Console Error**

> > core.js:6014 ERROR Error: Uncaught (in promise): Error: Error making HttpClient request in queryable [400] Bad Request ::> {"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"Invalid request."}}}
> Error: Error making HttpClient request in queryable [400] Bad Request ::> {"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"Invalid request."}}}
>     at odata.js:55
>     at ZoneDelegate.invoke (zone-evergreen.js:359)

**Response**

> --batchresponse_b58e3502-0ca8-4594-9fce-bcbd8641e662
> Content-Type: application/http
> Content-Transfer-Encoding: binary
> 
> HTTP/1.1 400 Bad Request
> CONTENT-TYPE: application/json;odata=verbose;charset=utf-8
> 
> {"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"Invalid request."}}}
> --batchresponse_b58e3502-0ca8-4594-9fce-bcbd8641e662
> Content-Type: application/http
> Content-Transfer-Encoding: binary

Clearly this is related to setup but I am wondering if there is any particular setup dependency which the library requires for supporting batching capability ? 

Thanks

**Comment by patrick-rodgers** [comment]
Hmmm, no idea jump to mind for this one. Nothing special should be required for batching to work except for SP version, and if you are in SPO that isn't the issue. And you're running the exact same code in both places?

**Comment by patrick-rodgers** [comment]
Going to close this due to lack of response. If you are still having issues please open a new issue, ref this one, and let us know any additional details you can provide. Thanks!
