### ISSUE TITLE
sp.navigation.getMenuState not returning Nodes results array as empty

### ISSUE THREAD

**Issue by siddharth-vaghasia** [pnp/pnpjs#962]
### Category
- [ ] Bug

### Version

Please specify what version of the library you are using: [     ^1.3.8   ]

Please specify what version(s) of SharePoint you are targeting: [    SharePoint Online     ]

### Expected / Desired Behavior / Question

Nodes are returning blank when SiteMapProvider is set as 'GlobalNavigationSwitchableProvider'

` sp.navigation.getMenuState(null, 5, "GlobalNavigationSwitchableProvider").then(r => {

      console.log(JSON.stringify(r, null, 4));
  
  }).catch(console.error);
`

Output logged in console

![image](https://user-images.githubusercontent.com/9557557/70803061-2db27400-1dd9-11ea-92c7-17533c4eada2.png)

When calling the same from REST API using the below code, we are getting results.

` this.context.spHttpClient.get(`${this.context.pageContext.web.absoluteUrl}/_api/navigation/menustate?mapprovidername='GlobalNavigationSwitchableProvider'`,  
      SPHttpClient.configurations.v1)  
      .then((response: SPHttpClientResponse) => {  
        response.json().then((responseJSON: any) => {  
          console.log(responseJSON);  
        });  
      });  `

Output from REST API.

![image](https://user-images.githubusercontent.com/9557557/70803197-7ff39500-1dd9-11ea-8f2a-f9fdc9002a76.png)

### Observed Behavior

The output from getMenuState method is not returning Nodes array which will contain nodes under current root node.

Let me know if you need any more information.

**Comment by patrick-rodgers** [comment]
Can you verify the requests are hitting the same urls? We are just calling the REST api so would, as you do, expect output to match.

**Comment by siddharth-vaghasia** [comment]
@patrick-rodgers ....it is hitting same urls but seems issue with http method, pnp is sending this as POST hence parameters are being passed as request payload rather than query string...while in REST, it is GET method.

![image](https://user-images.githubusercontent.com/9557557/70844200-c7266800-1e63-11ea-9a21-ea6a0b42145d.png)

Let me know if you need any more information. Seems to be a issue that can be taken by first-time contributor.

**Comment by KEMiCZA** [comment]
I've tried both a GET and POST call. For me they both return the same result.

```typescript
import { sp } from "@pnp/sp";
import { SPHttpClient } from '@pnp/sp';
(async () => {
    // The existing POST call implementation
    const resultPost = await sp.navigation.getMenuState(null, 10, "GlobalNavigationSwitchableProvider");
    console.log(resultPost);

    // HTTP GET call on the MenuState method
    const siteObj = await sp.web.select('Url').get();
    const endpoint = siteObj.Url + `/_api/navigation/MenuState?mapprovidername='GlobalNavigationSwitchableProvider'`;
    const client = new SPHttpClient();
    const response = await client.get(endpoint, {
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
        }
    })
    const resultGet = await response.json();
    console.log(resultGet);
})();
```
<details>
<summary>Result POST call</summary>
<p>

```json
{
    "odata.metadata": "https://kemiczadev.sharepoint.com/sites/pnpjs001/_api/$metadata#SP.MenuState",
    "AudienceIds": [],
    "FriendlyUrlPrefix": "",
    "Nodes": [
        {
            "AudienceIds": [],
            "CustomProperties": [
                {
                    "Key": "NodeType",
                    "Value": "Heading",
                    "ValueType": "Edm.String"
                },
                {
                    "Key": "Description",
                    "Value": "",
                    "ValueType": "Edm.String"
                },
                {
                    "Key": "Target",
                    "Value": null,
                    "ValueType": "Null"
                },
                {
                    "Key": "Audience",
                    "Value": null,
                    "ValueType": "Null"
                },
                {
                    "Key": "QuickId",
                    "Value": "6d9354cd-600c-4c75-a7ff-25bff39293ea,2030",
                    "ValueType": "Edm.String"
                },
                {
                    "Key": "HasChildNodes",
                    "Value": "False",
                    "ValueType": "Edm.String"
                }
            ],
            "FriendlyUrlSegment": "",
            "IsDeleted": false,
            "IsHidden": false,
            "Key": "/sites/pnpjs001?SPNavigationNodeId=2030",
            "Nodes": [],
            "NodeType": 0,
            "SimpleUrl": "http://www.google.be/",
            "Title": "GOoogle"
        }
    ],
    "SimpleUrl": "/sites/pnpjs001/SitePages/Home.aspx",
    "SPSitePrefix": "/sites/pnpjs001",
    "SPWebPrefix": "/sites/pnpjs001",
    "StartingNodeKey": "1002",
    "StartingNodeTitle": "pnpjs001 updated updated updated updated updated updated updated updated updated updated updated updated updated updated updated updated",
    "Version": "2019-12-16T10:04:38.2123585Z"
}
```
</p>
</details>

<details><summary>Result GET call</summary>
<p>

```json
{
    "odata.metadata": "https://kemiczadev.sharepoint.com/sites/pnpjs001/_api/$metadata#SP.MenuState",
    "AudienceIds": [],
    "FriendlyUrlPrefix": "",
    "Nodes": [
        {
            "AudienceIds": [],
            "CustomProperties": [
                {
                    "Key": "NodeType",
                    "Value": "Heading",
                    "ValueType": "Edm.String"
                },
                {
                    "Key": "Description",
                    "Value": "",
                    "ValueType": "Edm.String"
                },
                {
                    "Key": "Target",
                    "Value": null,
                    "ValueType": "Null"
                },
                {
                    "Key": "Audience",
                    "Value": null,
                    "ValueType": "Null"
                },
                {
                    "Key": "QuickId",
                    "Value": "6d9354cd-600c-4c75-a7ff-25bff39293ea,2030",
                    "ValueType": "Edm.String"
                },
                {
                    "Key": "HasChildNodes",
                    "Value": "False",
                    "ValueType": "Edm.String"
                }
            ],
            "FriendlyUrlSegment": "",
            "IsDeleted": false,
            "IsHidden": false,
            "Key": "/sites/pnpjs001?SPNavigationNodeId=2030",
            "Nodes": [],
            "NodeType": 0,
            "SimpleUrl": "http://www.google.be/",
            "Title": "GOoogle"
        }
    ],
    "SimpleUrl": "/sites/pnpjs001/SitePages/Home.aspx",
    "SPSitePrefix": "/sites/pnpjs001",
    "SPWebPrefix": "/sites/pnpjs001",
    "StartingNodeKey": "1002",
    "StartingNodeTitle": "pnpjs001 updated updated updated updated updated updated updated updated updated updated updated updated updated updated updated updated",
    "Version": "2019-12-16T10:04:38.3998621Z"
}
```

</p>
</details>

It seems to me that the original POST method is hitting the root web of your tenant instead of the site your (I assume) webpart is running on? This is usually when you have not configured/established the [SPFx context in your SPFx application](https://pnp.github.io/pnpjs/documentation/getting-started/#establish-context). I think this is also what Patrick was asking if the URL's are the same, meaning does it also hit the same site collection?

**Comment by siddharth-vaghasia** [comment]
@KEMiCZA ..... your observation is correct, I was setting the context, but was overriding base URL, a typical habit of copy paste....thanks on checking and your time..:)

@patrick-rodgers ....sorry for the confusion....pardon my ignorance....it is working as intended...
thanks for this awesome library...!!!
