### ISSUE TITLE
@pnp/sp/clientsidepages is breaking page layout for pages with vertical column

### ISSUE THREAD

**Issue by ruslan-s** [pnp/pnpjs#966]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    1.3.8     ]

Please specify what version(s) of SharePoint you are targeting: [    online     ]

### Expected / Desired Behavior / Question
After loading a page with one section, from type **Vertical Column**, from a file instance 
(page = await ClientSidePage..fromFile(web.getFileByServerRelativeUrl(FromFileRelUrl)), it will be expected, that page layout is will be correct loaded into page instance.  
After `page.save()`, it will be expected that the section with layout-type **Vertical Column** will be not transformed (broken) into normal column. 

### Observed Behavior
After `page.save()` the section with **Vertical Layout** type is "broken" into a normal column, all webparts from the right vertical column are relocated below main content of this section.

After detailed investigations, it was able to localize, that **@pnp/sp/clientsidepages** missing viable property `layoutIndex: Number` on interface **IClientSideWebPartData** like the interface **IClientSideTextData**.

Next problem is that foreach **IClientSideTextData** will be triggered the static initialization 
( `public static Default: IClientSideTextData`), where by **layoutIndex Property** has default value.
This property seems to be missing in the property mapping via **SharePointQueryable**.

HTTP REST Response for the call on (https://xxx.sharepoint.com/sites/xxx/groups/123/_api/sitepages/pages(430))
contains **layoutIndex** property foreach webpart (see CanvasContent1 JSON)

### Steps to Reproduce

1. Create a new modern site page. 

1. Add at least one section to the page.

1. Make this section to an Vertical Column type
1. Make some content into all sections and columns
1. Publish the page
1. Run following code:
```
const WebRelUrl = ''; // Absolute WebUrl of the Web, that contains page from step #1
const FileRelUrl = '';  // Relative file url for the page file from step #1
const web = new Web(WebRelUrl);
const page = await clp.fromFile(web.getFileByServerRelativeUrl(FileRelUrl));
page.save();
```

**Comment by ruslan-s** [comment]
If i insert manually  on each webpart on the page, that should be placed into vertical column, the property **layoutIndex = 2**, it works as expected.

**Comment by patrick-rodgers** [comment]
Yes, we haven't had a chance to add support for vertical columns yet with everything else in the queue. Will try and get this resolved for the next release and include it in v2. Thanks.

**Comment by ruslan-s** [comment]
@patrick-rodgers Thank you for your response!

**Comment by patrick-rodgers** [comment]
Added support for vertical sections in v1 and v2. Docs updated for v2 which match the changes for v1. Working on releasing v2 this week which will include the change, will go out in the next v1 release in Jan.
