### ISSUE TITLE
@pnp/sp bug on web.currentUser.get() without trailing slash on current URL

### ISSUE THREAD

**Issue by ltouro** [pnp/pnpjs#967]
**Describe the bug**

The method ```sp.web.currentUser.get()``` fails when the current browser URL lacks a trailing slash.

**To Reproduce**

1. Add a webpart which uses such method to the homepage in a site with this URL structure: https://tenant.sharepoint.com/sites/site1
2. Access the site with the following URL: https://tenant.sharepoint.com/sites/site1

To make things work, access the site again, now with the following URL: https://tenant.sharepoint.com/sites/site1/

**Expected behavior**

Works with or without trailing slash.

** Current behavior**

The request is sent to a non-existant address when the current URL lacks slash: https://tenant.sharepoint.com/sites/_api/web/currentuser

**Versions**
SharePoint Version: [ Online ]
PnPjs Version: [ 1.3.8 ]

**Comment by patrick-rodgers** [comment]
Are you establishing [the context](https://pnp.github.io/pnpjs/documentation/getting-started/#using-pnpsp-setup)?

**Comment by ltouro** [comment]
> Are you establishing [the context](https://pnp.github.io/pnpjs/documentation/getting-started/#using-pnpsp-setup)?

I see now. Thank you.
