### ISSUE TITLE
Errors after installing pnp 1.3.8 version

### ISSUE THREAD

**Issue by ymihir** [pnp/pnpjs#972]
I have one SPFx solution where the version in 1.3.6 and working good. i have created new solution and installed pnp through npm which was installed 1.3.8 version. 

But unfortunately some methods are throwing errors for 1.3.8 which were working in 1.3.6. Below are them
 ```
let item = sp.web.lists
      .getByTitle(listName)
      .items.getById(id)
      .select(selectFields)
      .expand(expandFields).get()
```
```
public static async getAttachments(sp: SPRest, listName: string, itemId) {
    const list = sp.web.lists.getByTitle(listName);
    return list.items.getById(itemId).attachmentFiles.get()
  }
```

Where ever I am using get method there it is throwing error. If I remove `get()` method at the end then it is not showing any error. Is it any change? Nothing i found in the [documentation](https://pnp.github.io/pnpjs/sp/docs/items/).

**Comment by koltyakov** [comment]
PnPjs contains of a number of packages. Did you upgrade every @pnp/* to the same version?

**Comment by ymihir** [comment]
I didn't installed @pnp/odata. After installation it is working fine.
