### ISSUE TITLE
search api not working, pnpjs v2

### ISSUE THREAD

**Issue by tavikukko** [pnp/pnpjs#975]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [    2.0.0     ]

Please specify what version(s) of SharePoint you are targeting: [    2013,2016,2019,online     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
executing this:
```
import { sp } from "@pnp/sp/presets/all";
sp.search("test").then(x => console.log);
```
Should post the search payload to **_api/seach/postquery** api endpoint

### Observed Behavior

The post query url is **missing** the **_api/search/postquery** and query fails

### Steps to Reproduce
execute this and check the results
```
import { sp } from "@pnp/sp/presets/all";
sp.search("test").then(x => console.log);
```

**Comment by patrick-rodgers** [comment]
Thanks for catching this - not sure how it got through, but it did. I see you submitted PRs for the fixes, appreciate it - will take a look. Thanks!

**Comment by NLRotterdam** [comment]
This seems to still be bugged on 2.0.0,  I am still missing _api/search/postquery. Had to downgrade to v1.
