### ISSUE TITLE
Graph.Planner.Task.delete issue : mandatory REST header field ETag missing in pnp API

### ISSUE THREAD

**Issue by JMTeamway** [pnp/pnpjs#987]
### Category
- [x ] Bug

### Version
Library version : [    Latest     ]
SharePoint : [ Online  ]

### Expected / Desired Behavior / Question
Call to `graph.planner.tasks.getById(id).delete() ` deletes the given task.

### Observed Behavior
The call fails an launch the following  exception : 
```
Error making HttpClient request in queryable [412] Precondition Failed ::> {
  "error": {
    "code": "",
    "message": "The If-Match header must be specified for this kind of request.",
    "innerError": {
      "request-id": "3957078c-4b7e-4aa8-93e3-0a3962c711ba",
      "date": "2020-01-02T10:40:48"
    }
  }
}
```

### Steps to Reproduce
Call the delete function on an existing Planner task.

### Issue explanation
The delete graph API expects the last Task eTag in the header in order to perform the delete.
The current pnp api for delete() does not allow to add this header field.

This behavior is the same with the Graph.Planner.Task.update() function that has this parameter : 
`public update(properties: IPlannerTask, eTag = "*"): Promise<void>`

### Proposed solution
Implement the eTag parameter the same way it is done for the update() function

The development is done and I'm going to create a pull request for it.

**Comment by patrick-rodgers** [comment]
Just wanted to check in on this - we have a release planned for this Friday (Jan 10) and it would be great if you can get the PR submitted by then so we can include the fix in that release. Thanks!

**Comment by JMTeamway** [comment]
Hi Patrick,

Just to clarify : I noticed this bug in one of the latest 1.x version, and I tried to post a fix that was targeted to version 2.X so it did not fit. (Yeah I’m not totally confortable with Github 😊 )
I confirm the bug also exists in version 2.x.

Should I only propose a fix for version 2.x ?
I had a look at the code and think it can be done tomorrow, that would be ok for next release.


Cordialement,

Julien MAGNE
Chef de projet - R&D

Email : julien.magne@teamway.fr<mailto:julien.magne@teamway.fr>

Téléphone : +336 82 23 25 22
[logo_teamway]
________________________________

De : Patrick Rodgers <notifications@github.com>
Envoyé : lundi 6 janvier 2020 16:11
À : pnp/pnpjs <pnpjs@noreply.github.com>
Cc : Julien MAGNE <julien.magne@teamway.fr>; Author <author@noreply.github.com>
Objet : Re: [pnp/pnpjs] Graph.Planner.Task.delete issue : mandatory REST header field ETag missing in pnp API (#987)


Just wanted to check in on this - we have a release planned for this Friday (Jan 10) and it would be great if you can get the PR submitted by then so we can include the fix in that release. Thanks!

**Comment by patrick-rodgers** [comment]
Yes that would be fine - we should fix it in both places if the bug exists in both (I agree it does). If you can get it done that is great, if not let us know and we'll try and take care of it. Thanks!

**Comment by JMTeamway** [comment]
Ok I plan to provide 2 Fixes for tomorrow morning.
I am condident on the fixes I’ll provide, but they will need to be tested as I have not managed yet to have a working testing environnement ( I hope next Meeting  for new contributors will help me on that 😉 ).

Still the testing should be easy for someone having a well configured environnement.


Cordialement,

Julien MAGNE
Chef de projet - R&D

Email : julien.magne@teamway.fr<mailto:julien.magne@teamway.fr>

Téléphone : +336 82 23 25 22
[logo_teamway]
________________________________

De : Patrick Rodgers <notifications@github.com>
Envoyé : lundi 6 janvier 2020 17:09
À : pnp/pnpjs <pnpjs@noreply.github.com>
Cc : Julien MAGNE <julien.magne@teamway.fr>; Author <author@noreply.github.com>
Objet : Re: [pnp/pnpjs] Graph.Planner.Task.delete issue : mandatory REST header field ETag missing in pnp API (#987)


Yes that would be fine - we should fix it in both places if the bug exists in both (I agree it does). If you can get it done that is great, if not let us know and we'll try and take care of it. Thanks!

**Comment by JMTeamway** [comment]
Julien MAGNE a partagé "Invoice-030440" avec vous.




















This link only works for the direct recipients of this message.











Julien MAGNE








Open





































Microsoft respects your privacy. To learn more, please read our Privacy
 Statement.
Microsoft Corporation, One Microsoft Way, Redmond, WA 98052

Unsubscribe from
 share reminder emails.
