### ISSUE TITLE
Can't like a sharepoint list item using pnpjs

### ISSUE THREAD

**Issue by theibrahimi** [pnp/pnpjs#989]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of SharePoint you are targeting: [   sharepoint 2019      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

Hello, 
I'm using pnpjs library in SPFX project, I'm adding a fuction to like a sharepoint list item :

```
import pnp, { Item, ItemUpdateResult } from "sp-pnp-js";
import { spODataEntityArray, Comment, CommentData, Web, ItemAddResult, sp} from "@pnp/sp";
public async getspecificitemandlikeit(itemid) {

        // get a specific item by id
        const item: any = await sp.web.lists.getByTitle("mylist").items.getById(14).get();
        console.log(item);
        // as an example, or any of the below options
        await item.like();
    }
```
I'm getting the error : Uncaught (in promise) TypeError: item.like is not a function.
I can't add 👍 

I used this documentation: [https://github.com/pnp/pnpjs/blob/version-2/docs/sp/comments-likes.md](url)
> import "@pnp/sp/comments/item";

to my code i'm getting error while building project.

Am I missing any import ?  any help please

**Comment by koltyakov** [comment]
Are you really importing `sp-pnp-js`?  It's a deprecated long time ago package, PnPjs packages start with `@pnp/*`.

**Comment by theibrahimi** [comment]
nope I'm importing @pnp/sp
`import { spODataEntityArray, Comment, CommentData, Web, ItemAddResult, sp} from "@pnp/sp";`

**Comment by patrick-rodgers** [comment]
What version of the pnp libraries are you using? If it is v2 have you looked at the [docs for likes and comments](https://pnp.github.io/pnpjs/sp/comments-likes/#like)?

**Comment by theibrahimi** [comment]
thanks for your reply.
I'm using  v2.
I've install it using npm :
`npm install @pnp/logging @pnp/common @pnp/nodejs --save`
I've add 
`import "@pnp/sp/comments";`
and i'm getting the error :

> ./lib/webparts/btb/components/BananeCrud.js
Module not found: Error: Can't resolve '@pnp/sp/comments' in 'C:\Git\vGitBtB\BTB\lib\webparts\btb\components'
resolve '@pnp/sp/comments' in 'C:\Git\vGitBtB\BTB\lib\webparts\btb\components'
  Parsed request is a module
  using description file: C:\Git\vGitBtB\BTB\package.json (relative path: ./lib/webparts/btb/components)
    Field 'browser' doesn't contain a valid alias configuration

**Comment by patrick-rodgers** [comment]
Are you running in node js or SPFx? I am confused because you are importing the nodejs package, which you don't need unless you are running a node app. What version of SPFx? If you are using 1.4.1 please see [this thread](https://github.com/pnp/pnpjs/issues/978#issuecomment-570152141) which might help.

**Comment by KEMiCZA** [comment]
I would suggest that you delete your node_modules folder & remove package.json.lock. Then check package.json and that you have the correct dependecies for @pnp/sp should be `"@pnp/sp": "^2.0.0",`. You don't need any other dependencies for now. Then run `npm i`. I have a feeling you still have the old pnp files located in the nodes_modules folder, which cause conflicts? Just speculating, but worth a try.

**Comment by theibrahimi** [comment]
I've delete @pnp/sp from node_modules folder and modified `"@pnp/sp": "^2.0.0"` in the package.json and run `npm i`.
Actually I have 2.0.0 version but have error when building project:
![Capture](https://user-images.githubusercontent.com/7073903/71691653-3d095980-2da8-11ea-94da-8de0cce372b4.PNG)

** Package json dependecies:**
`"@pnp/common": "^2.0.0",
    "@pnp/graph": "^2.0.0",
    "@pnp/logging": "^2.0.0",
    "@pnp/nodejs": "^2.0.0",
    "@pnp/odata": "^2.0.0",
    "@pnp/pnpjs": "^2.0.0",
    "@pnp/sp": "^2.0.0",`

**Package-lock.json :**
`   "@pnp/sp": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/@pnp/sp/-/sp-2.0.0.tgz",
      "integrity": "sha512-4tAxo3QcSQiORl03DUm+RdMSRjUFZQvTm67hiO3ipISB5VnLAiqrTj1nYkSC3zq3RXHkz4mz0i+iquledI1cUg==",
      "requires": {
        "@pnp/common": "2.0.0",
        "@pnp/logging": "2.0.0",
        "@pnp/odata": "2.0.0",
        "tslib": "1.10.0"
      },`

**Comment by patrick-rodgers** [comment]
Please - read through the comments in the [thread I linked here](https://github.com/pnp/pnpjs/issues/989#issuecomment-570296263) which discusses this issue.

**Comment by theibrahimi** [comment]
@patrick-rodgers 	  @KEMiCZA  I've followes the steps shown in the previous thread but still have the same error when I build the project.
When I run step 5 and 6 
Remove node_modules folder `rimraf node_modules`
Run `npm install`
 It override the changes I've made in step 3, here's a screen of my "package-lock.json" file after following all steps:

![Capture2](https://user-images.githubusercontent.com/7073903/71695926-e30e9100-2db3-11ea-8933-f6f7093ff64d.PNG)

Note : in my "package.json" depedencies I have `"typescript": "^2.4.2"`
![3](https://user-images.githubusercontent.com/7073903/71695999-194c1080-2db4-11ea-9834-aa51ffe9a3b1.PNG)

**Comment by koltyakov** [comment]
@theibrahimi, 

> Run npm install
> It override the changes I've made in step 3, here's a screen of my "package-lock.json" file after following all steps

Can you try `npm ci` instead of `npm install` at that step? CI command should restore the same exactly dependencies that are locked in the package-lock.json. In package.json, it's better to align the TypeScript version.

I also confused with mixed Node.js (@pnp/nodejs, sp-pnp-node) and client-side dependencies which you have as well as deprecated one (sp-pnp-js), and you never answered suggestive questions about this before.

**Comment by theibrahimi** [comment]
@koltyakov 
> Can you try `npm ci` instead of `npm install` at that step? CI command should restore the same exactly dependencies that are locked in the package-lock.json. In package.json, it's better to align the TypeScript version.
Now I have another  error in the webpartts file:
![4](https://user-images.githubusercontent.com/7073903/71700950-ec552900-2dc6-11ea-96cb-43d8f9954888.PNG)

When i build project I have 2 errors:
`Error - typescript - src/webparts/btb/BtbWebPart.ts(25,8): error TS2769: No overload matches this call.
Error - 'typescript' sub task errored after 8.52 s
 TypeScript error(s) occurred.`

when I run `npm list typescript`  I get this output:
![5](https://user-images.githubusercontent.com/7073903/71701022-51108380-2dc7-11ea-8da1-8db260699f95.PNG)


> I also confused with mixed Node.js (@pnp/nodejs, sp-pnp-node) and client-side dependencies which you have as well as deprecated one (sp-pnp-js), and you never answered suggestive questions about this before.
I'm not using (sp-pnp-js) anymore It was for test purposes I gonna clean dependencies later.

**Comment by theibrahimi** [comment]
#978 
My "package.json"

> {
  "name": "btb",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/loader-set-webpack-public-path": "^3.3.15",
    "@microsoft/sp-core-library": "~1.4.0",
    "@microsoft/sp-http": "^1.9.1",
    "@microsoft/sp-lodash-subset": "~1.4.0",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.0",
    "@microsoft/sp-webpart-base": "~1.4.0",
    "@pnp/sp": "^2.0.0",
    "@types/es6-promise": "0.0.33",
    "@types/jquery": "^3.3.31",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@types/webpack-env": "1.13.1",
    "jquery": "^3.4.1",
    "moment": "^2.24.0",
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "react-moment": "^0.9.7",
    "react-router-dom": "^5.1.2",
    "typescript": "^3.6.4"
  },
  "resolutions": {
    "@types/react": "15.6.6"
  },
  "devDependencies": {
    "@microsoft/set-webpack-public-path-plugin": "^2.2.15",
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "tslint-microsoft-contrib": "^6.2.0"
  }
}

Still Have the problem when I run "npm install" or "npm ci" in my package-lock.json I have "@microsoft/gulp-core-build-typescript" wich required  "typescript": "~2.4.1"  if I changed to "3.6.4" the first problem disapear when I build the project but I have the problem discribed in this post

> Hello @KEMiCZA I've followed all steps as shown above and replace all typescript version in "package-lock.json" with "3.6.4" .
> Now I have this errors when i build project :
> `Error - typescript - src/webparts/btb/BtbWebPart.ts(25,8): error TS2769: No overload matches this call. Error - 'typescript' sub task errored after 8.52 s TypeScript error(s) occurred.`
> 
> when I run `npm list typescript` I get this output:
> ![5](https://user-images.githubusercontent.com/7073903/71701022-51108380-2dc7-11ea-8da1-8db260699f95.PNG)
> 
> Any suggestions ?
