### ISSUE TITLE
Does Pnp library implement caching via Etags?

### ISSUE THREAD

**Issue by gbminnock** [pnp/pnpjs#99]
- [ ] Question
Hi I have been using the caching successfully which uses local storage (.useCaching()).

I have a question about whether Etags are being used to figure out if the cache is stale? I was unable to see that being passed in the request/response headers. 

Thanks,
Gary

**Comment by patrick-rodgers** [comment]
No, caching is based solely on the time you supply or the default timeout. This has the advantage of being easier to understand (and code) as well as giving you full control of when things expire.
