### ISSUE TITLE
['Symbol' is undefined] Build does not run on Internet Explorer 11

### ISSUE THREAD

**Issue by SkyleOri** [pnp/pnpjs#996]
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: *2.0.0*

Please specify what version(s) of SharePoint you are targeting: *SharePoint 2013*

### Expected Behavior
The application can work well on Chrome, Firefox and Internet Explorer 11

### Observed Behavior
The application can work well on Chrome, Firefox, but not on Internet Explorer 11, the error show as below:
![2020-01-07_15h44_35](https://user-images.githubusercontent.com/59470395/71881357-b1efe100-3164-11ea-9f48-50983c2f2b5b.png)

### Steps to Reproduce
- Step 1: Run the application on Chrome, Firefox and Internet Explorer 11
- Step 2: Observe the result

**Comment by koltyakov** [comment]
Did you follow [polyfills doc page](https://pnp.github.io/pnpjs/concepts/polyfill/) instructions?

**Comment by SkyleOri** [comment]
I tried to import it into all the files which are using @pnp, but it still did not work.
![2020-01-08_09h13_52](https://user-images.githubusercontent.com/59470395/71944981-13ad5b00-31f8-11ea-99b0-9d1ac1016867.png)

**Comment by patrick-rodgers** [comment]
Are you running this in SPFx and what if so what version?

**Comment by SkyleOri** [comment]
No, I do not use SPFx.
About enabling ie11 mode, I missed it, but it seems to not work after I add it.
![2020-01-09_09h53_25](https://user-images.githubusercontent.com/59470395/72033885-1d04f900-32c6-11ea-8733-4d538f99e6c0.png)

**Comment by semopz** [comment]
Might help https://github.com/pnp/pnpjs/issues/1002#issuecomment-572975881

You will need to make some modifications for use outside of SPFx solutions.

**Comment by patrick-rodgers** [comment]
Was able to reproduce this - unsure why we didn't catch it. I have added the sumbol polyfill to the polyfill package. Just published a new polyfill package 2.0.1 - give that a try and things should now work.

**Comment by patrick-rodgers** [comment]
Going to close this as resolved with the new version of the polyfill library. If someone has further issues please open a new issue and ref this one with the new details. Thanks!
