### ISSUE TITLE
Creating a OneNote Notebook within a specific folder in SharePoint

### ISSUE THREAD

**Issue by Rominkc** [pnp/pnpjs#998]
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.3.8  ]

Please specify what version(s) of SharePoint you are targeting: [   SPO  ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I was wondering if it was possible to create a onenote notebook within a folder on SharePoint. For example I can do sp.web.lists.getByTitle("example").items.add({exampleKey:exampleValue}) to add a new list item. Is there something similar for adding onenote notebooks? I noticed there was a function graph.me.onenote.notebooks.add(). My understanding is that this function adds a onenote notebook to the onenote associated with the user, but I am trying to get this onenote notebook on  (onedrive for business) on the SharePoint site (I believe this is where the onenote would be stored if I manually created it within the folder). My original plan was to use Flow, but currently it doesn't support creation of notebooks, just pages and sections: https://docs.microsoft.com/en-us/connectors/onenote/#/providers/microsoft.powerapps/apis/shared_onenote/apioperations
If anyone has done this before, or could point me in the right direction, it would be greatly appreciated. Thank you

**Comment by patrick-rodgers** [comment]
Have a look at [this thread](https://github.com/pnp/pnpjs/issues/813#issuecomment-520861098) which might help.

**Comment by Rominkc** [comment]
Thank you for the resource I think I can figure it out from here.
