### ISSUE TITLE
Cannot find module '@pnp/sp/webs'

### ISSUE THREAD

**Issue by andreer1** [pnp/pnpjs#999]
I followed the instructions described here https://pnp.github.io/pnpjs/sp/webs/ 
to create a new web context and consult some sharepoint lists in there sites.

one of the steps include import this module.
import { Web } from "@pnp/sp/webs";
and get error in the code editor.

![image](https://user-images.githubusercontent.com/7324159/71991097-9804db80-3202-11ea-80f8-2536cb93c760.png)

this happening with all new modules in the new version of pnpjs
previous i followed the instructions of transition guide https://pnp.github.io/pnpjs/transition-guide/
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [       2  ]

Please specify what version(s) of SharePoint you are targeting: [     online    ]

**Comment by PopWarner** [comment]
Hi @andreer1,

If you go into your "\node_modules\@pnp\sp", is there a "web" folder and is it populated?

I'm curious if PnPjs v2 is not completely installed?

Within your project, if you do an `npm list --depth=0`, does it show 2.0.0?

**Comment by andreer1** [comment]
> Hi @andreer1,
> 
> If you go into your "\node_modules@pnp\sp", is there a "web" folder and is it populated?
> 
> I'm curious if PnPjs v2 is not completely installed?
> 
> Within your project, if you do an `npm list --depth=0`, does it show 2.0.0?

show 1.3
![image](https://user-images.githubusercontent.com/7324159/71994801-65111680-3207-11ea-9c8d-af465433c6ef.png)

but i run the command npm i --save @pnp/sp for install the new version as the transition guide says here https://pnp.github.io/pnpjs/transition-guide/

**Comment by PopWarner** [comment]
Gotcha! The transition guide is for when you are transitioning from v1 to v2. Since you are still using v1, many of the steps would not apply. Version 2 was just recently released, so I'm not sure if maybe you had just created your project prior to that?

You can do one of two things. You can upgrade to v2 or you can continue to use v1, but would want to reference that documentation here:
https://pnp.github.io/pnpjs/v1/

The recommended approach though is to upgrade to v2 as you will receive many new features and benefits. The best way to accomplish that is to uninstall specifically all of the v1 PnPjs packages:
`npm uninstall @pnp/sp @pnp/common @pnp/logging @pnp/odata @pnp/graph`

...and then reinstall v2:
`npm install @pnp/sp @pnp/graph --save`

**Comment by andreer1** [comment]
I followed your steps now and got the same error.
Version of pnp:
![image](https://user-images.githubusercontent.com/7324159/71995967-6b07f700-3209-11ea-99b7-bc4d723d38a4.png)


error:
![image](https://user-images.githubusercontent.com/7324159/71995993-74915f00-3209-11ea-8de2-f264c6d981f4.png)

Now the web subfolder showed up :
![image](https://user-images.githubusercontent.com/7324159/71996119-a9051b00-3209-11ea-83e6-0a850101efbd.png)

**Comment by PopWarner** [comment]
Did the gulp bundle throw an error or is the error just showing in VSCode? Sometimes VSCode can get confused. You could try restarting it.

Also, are you simply trying to make a connection to the web for web-related data? You might not need that specific import. :)
https://pnp.github.io/pnpjs/sp/webs/#access-a-web

**Comment by andreer1** [comment]
> Did the gulp bundle throw an error or is the error just showing in VSCode? Sometimes VSCode can get confused. You could try restarting it.
> 
> Also, are you simply trying to make a connection to the web for web-related data? You might not need that specific import. :)
> https://pnp.github.io/pnpjs/sp/webs/#access-a-web

Yes, the gulp throw this error 
![image](https://user-images.githubusercontent.com/7324159/71996776-c4bcf100-320a-11ea-9e76-c3ae03058b02.png)

what I need is to connect to a different sharepoint site to which the tenant's webpart is hosted to consult a list

**Comment by patrick-rodgers** [comment]
You might need to run `gulp clean` and start over on building your solution depending on what step you are getting stuck on.

**Comment by andreer1** [comment]
> You might need to run `gulp clean` and start over on building your solution depending on what step you are getting stuck on.

I did it, cleand and bundle again.

**Comment by PopWarner** [comment]
If you try building a new solution and install PnPjs, do you have success?

I can try as well but might be a bit delayed. :)

**Comment by andreer1** [comment]
> If you try building a new solution and install PnPjs, do you have success?
> 
> I can try as well but might be a bit delayed. :)

Ok, we have something, importing new libraries works correctly in a new project
Do you have any idea why it doesn't work on the project I'm already working on, if I already uninstall and reinstall?

**Comment by patrick-rodgers** [comment]
No idea other than old version somehow hanging around and interfering. You could delete node_modules and do a reinstall of everything?

At this point things seemed resolved?

**Comment by andreer1** [comment]
> No idea other than old version somehow hanging around and interfering. You could delete node_modules and do a reinstall of everything?
> 
> At this point things seemed resolved?

Yes , this topic is solved, thanks!
